#!/bin/bash
# module load swig/swig-3.0.11
scons -j4 SG_ALL=0 SG_BASE=1 SG_COMBIGRID=1 SG_PYTHON=1 SG_JAVA=0 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 SWIGFLAGS="-I/usr/local.nfs/sgs/software/swig/local/share/swig/3.0.11/python"
