SG++-Doxygen-Documentation: json::json_exception Class Reference
json::json_exception Class Reference
#include <json_exception.hpp>
Public Member Functions
json_exception (const std::string &message)
json_exception (Token &token, const std::string &message)
const char * what () const noexcept override
Constructor & Destructor Documentation
json_exception() [1/2]
json::json_exception::json_exception (Token & token, const std::string & message)
References json::Token::charNumber, json::Token::lineNumber, and json::Token::value.
json_exception() [2/2]
json::json_exception::json_exception (const std::string & message) explicit
Member Function Documentation
what()
const char * json::json_exception::what () const override noexcept
Referenced by sgpp::datadriven::DataMiningConfigParser::DataMiningConfigParser(), sgpp::datadriven::LearnerSGDEConfiguration::LearnerSGDEConfiguration(), and sgpp::datadriven::SparseGridDensityEstimatorConfiguration::SparseGridDensityEstimatorConfiguration().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/json/json_exception.hpp
base/src/sgpp/base/tools/json/json_exception.cpp