SG++-Doxygen-Documentation: sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT > Class Template Reference
sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT > Class Template Reference
weakly fundamental not-a-knot spline basis (1st derivative).
#include <WeaklyFundamentalNakSplineBasisDeriv1.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
WeaklyFundamentalNakSplineBasisDeriv1 ()
Default constructor.
WeaklyFundamentalNakSplineBasisDeriv1 (size_t degree)
Constructor.
~WeaklyFundamentalNakSplineBasisDeriv1 () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
WeaklyFundamentalSplineBasisDeriv1< LT, IT > weaklyFundamentalSplineBasisDeriv1
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >
weakly fundamental not-a-knot spline basis (1st derivative).
Constructor & Destructor Documentation
WeaklyFundamentalNakSplineBasisDeriv1() [1/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineBasisDeriv1 () inline
Default constructor.
WeaklyFundamentalNakSplineBasisDeriv1() [2/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineBasisDeriv1 (size_t degree) inline explicit
Constructor.
Parameters
degree Spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::getDegree().
~WeaklyFundamentalNakSplineBasisDeriv1()
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::~WeaklyFundamentalNakSplineBasisDeriv1 () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::getDegree(), and sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::weaklyFundamentalSplineBasisDeriv1.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative().
evalDx()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::weaklyFundamentalSplineBasisDeriv1.
Referenced by sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::eval(), and sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineBasisDeriv1().
getIntegral()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
weaklyFundamentalSplineBasisDeriv1
template<class LT , class IT > WeaklyFundamentalSplineBasisDeriv1<LT, IT> sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::weaklyFundamentalSplineBasisDeriv1 protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::eval(), and sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/WeaklyFundamentalNakSplineBasisDeriv1.hpp