SG++-Doxygen-Documentation: sgpp::datadriven::DataTransformationTypeParser Class Reference
sgpp::datadriven::DataTransformationTypeParser Class Reference
Convenience class to convert strings to sgpp::datadriven::DataTransformationType and generate string representations for values of sgpp::datadriven::DataTransformationType.
#include <DataTransformationTypeParser.hpp>
Static Public Member Functions
static DataTransformationType parse (const std::string &input)
Convert strings to values sgpp::datadriven::DataTransformationType.
static const std::string & toString (DataTransformationType type)
Generate string representations for values of sgpp::datadriven::DataTransformationType.
Detailed Description
Convenience class to convert strings to sgpp::datadriven::DataTransformationType and generate string representations for values of sgpp::datadriven::DataTransformationType.
Member Function Documentation
parse()
DataTransformationType sgpp::datadriven::DataTransformationTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::datadriven::DataTransformationType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::datadriven::DataTransformationType.
Returns
the corresponding sgpp::datadriven::DataTransformationType.
References sgpp::datadriven::NONE, and sgpp::datadriven::ROSENBLATT.
toString()
const std::string & sgpp::datadriven::DataTransformationTypeParser::toString (DataTransformationType type) static
Generate string representations for values of sgpp::datadriven::DataTransformationType.
Parameters
type enum value.
Returns
string representation of a sgpp::datadriven::DataTransformationType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/DataTransformationTypeParser.hpp
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/DataTransformationTypeParser.cpp