SG++-Doxygen-Documentation: sgpp::pde::OperationLaplaceExplicitLinear Class Reference
sgpp::pde::OperationLaplaceExplicitLinear Class Reference
Implementation for B-spline functions of Laplace Operation, linear grids without boundaries.
#include <OperationLaplaceExplicitLinear.hpp>
Public Member Functions
virtual void down (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D down operation
virtual void downOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D down operation that is only executed in one direction
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationLaplaceExplicitLinear (sgpp::base::DataMatrix *m, sgpp::base::GridStorage *storage)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
OperationLaplaceExplicitLinear (sgpp::base::GridStorage *storage)
Constructor that creates an own matrix i.e.
virtual void specialOP (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t gradient_dim)
All calculations for gradient_dim, parallel version using OpenMP 3.
virtual void up (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D up operation
virtual void upOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D up operation that is only executed in one direction
virtual ~OperationLaplaceExplicitLinear ()
Destructor.
Public Member Functions inherited from sgpp::pde::UpDownOneOpDim
void multParallelBuildingBlock (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t operationDim)
This functions provides the same functionality as the normal mult routine.
UpDownOneOpDim (sgpp::base::GridStorage *storage)
Constructor.
UpDownOneOpDim (sgpp::base::GridStorage *storage, sgpp::base::DataVector &coef)
Constructor.
virtual ~UpDownOneOpDim ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::UpDownOneOpDim
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::UpDownOneOpDim
void updown (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
Recursive procedure for updown(), parallel version using OpenMP 3.
Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::DataVector * coefs
Pointer to the sgpp::base::DataVector of the coefs.
const size_t numAlgoDims_
number of algorithmic dimensions
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Static Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
static const size_t maxParallelDims_ = TASKS_PARALLEL_UPDOWN
max number of parallel stages (dimension recursive calls)
Detailed Description
Implementation for B-spline functions of Laplace Operation, linear grids without boundaries.
Constructor & Destructor Documentation
OperationLaplaceExplicitLinear() [1/2]
sgpp::pde::OperationLaplaceExplicitLinear::OperationLaplaceExplicitLinear (sgpp::base::DataMatrix * m, sgpp::base::GridStorage * storage)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
matrix is NOT destroyed by the destructor of OperationLaplaceExplicitLinear
Parameters
m pointer to datamatrix of size (number of grid point) x (number of grid points)
storage pointer to the sparse grid storage
References m, and sgpp::pde::UpDownOneOpDim::storage.
OperationLaplaceExplicitLinear() [2/2]
sgpp::pde::OperationLaplaceExplicitLinear::OperationLaplaceExplicitLinear (sgpp::base::GridStorage * storage) explicit
Constructor that creates an own matrix i.e.
matrix is destroyed by the destructor of OperationLaplaceExplicitLinear
Parameters
storage pointer to the sparse grid storage
References sgpp::base::HashGridStorage::getSize(), and sgpp::pde::UpDownOneOpDim::storage.
~OperationLaplaceExplicitLinear()
sgpp::pde::OperationLaplaceExplicitLinear::~OperationLaplaceExplicitLinear () virtual
Destructor.
Member Function Documentation
down()
void sgpp::pde::OperationLaplaceExplicitLinear::down (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) virtual
std 1D down operation
Parameters
dim dimension in which to apply the down-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha.
downOpDim()
void sgpp::pde::OperationLaplaceExplicitLinear::downOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) virtual
special 1D down operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that down-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
References alpha.
Referenced by specialOP().
mult()
void sgpp::pde::OperationLaplaceExplicitLinear::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
Reimplemented from sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), and sgpp::base::DataVector::getSize().
specialOP()
void sgpp::pde::OperationLaplaceExplicitLinear::specialOP (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim, size_t op_dim) virtual
All calculations for gradient_dim, parallel version using OpenMP 3.
Parameters
alpha the coefficients of the grid points
result the result of the operations
dim the current dimension in the recursion
op_dim the dimension in that a special operation is applied
Reimplemented from sgpp::pde::UpDownOneOpDim.
References alpha, downOpDim(), sgpp::base::DataVector::getSize(), and sgpp::pde::UpDownOneOpDim::updown().
up()
void sgpp::pde::OperationLaplaceExplicitLinear::up (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) virtual
std 1D up operation
Parameters
dim dimension in which to apply the up-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha.
upOpDim()
void sgpp::pde::OperationLaplaceExplicitLinear::upOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) virtual
special 1D up operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that up-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplaceExplicitLinear.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplaceExplicitLinear.cpp