SG++-Doxygen-Documentation: sgpp::datadriven::GridFactory Class Reference
sgpp::datadriven::GridFactory Class Reference
Factory class to create grids based on a configuration file.
#include <GridFactory.hpp>
Public Member Functions
sgpp::base::Grid * createGrid (const sgpp::base::GeneralGridConfiguration &gridConfig, const std::set< std::set< size_t > > interactions) const
Creates and initializes a grid based on a configuration file.
void getBlockInteractions (std::set< std::set< size_t > > &interactions, sgpp::datadriven::GeometryConfiguration &geometryConfig, sgpp::datadriven::StencilConfiguration &stencilConf) const
void getDirectNeighbours (std::set< std::set< size_t > > &interactions, sgpp::datadriven::GeometryConfiguration &geometryConfig, sgpp::datadriven::StencilConfiguration &stencilConf) const
void getHierarchicalParents (std::set< std::set< size_t > > &interactions, sgpp::datadriven::GeometryConfiguration &geometryConfig, sgpp::datadriven::StencilConfiguration &stencilConf) const
std::set< std::set< size_t > > getInteractions (sgpp::datadriven::GeometryConfiguration config) const
GridFactory ()
Detailed Description
Factory class to create grids based on a configuration file.
Constructor & Destructor Documentation
GridFactory()
sgpp::datadriven::GridFactory::GridFactory () inline
Member Function Documentation
createGrid()
sgpp::base::Grid * sgpp::datadriven::GridFactory::createGrid (const sgpp::base::GeneralGridConfiguration & gridConfig, const std::set< std::set< size_t > > interactions) const
Creates and initializes a grid based on a configuration file.
Parameters
gridConfig the grid configuration
interactions the interactions for each dimension
Returns
pointer to the grid object created
References sgpp::base::GridGenerator::anisotropicFull(), sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::ComponentGrid, sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::generalType_, sgpp::base::Grid::getGenerator(), sgpp::base::Grid::getSize(), sgpp::base::GeneralGridConfiguration::level_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::GridGenerator::regular(), sgpp::base::GridGenerator::regularInter(), and sgpp::base::GeneralGridConfiguration::type_.
Referenced by sgpp::datadriven::ModelFittingBase::buildGrid(), sgpp::datadriven::ModelFittingBase::buildGrid(), sgpp::datadriven::DBMatPermutationFactory::getPermutedObject(), and sgpp::datadriven::LearnerSGDEOnOffParallel::LearnerSGDEOnOffParallel().
getBlockInteractions()
void sgpp::datadriven::GridFactory::getBlockInteractions (std::set< std::set< size_t > > & interactions, sgpp::datadriven::GeometryConfiguration & geometryConfig, sgpp::datadriven::StencilConfiguration & stencilConf) const
References sgpp::datadriven::StencilConfiguration::applyOnLayers_, sgpp::datadriven::StencilConfiguration::blockLenght_, and sgpp::datadriven::GeometryConfiguration::dim_.
getDirectNeighbours()
void sgpp::datadriven::GridFactory::getDirectNeighbours (std::set< std::set< size_t > > & interactions, sgpp::datadriven::GeometryConfiguration & geometryConfig, sgpp::datadriven::StencilConfiguration & stencilConf) const
References sgpp::datadriven::StencilConfiguration::applyOnLayers_, sgpp::datadriven::StencilConfiguration::colorIndex_, and sgpp::datadriven::GeometryConfiguration::dim_.
getHierarchicalParents()
void sgpp::datadriven::GridFactory::getHierarchicalParents (std::set< std::set< size_t > > & interactions, sgpp::datadriven::GeometryConfiguration & geometryConfig, sgpp::datadriven::StencilConfiguration & stencilConf) const
References sgpp::datadriven::StencilConfiguration::applyOnLayers_, sgpp::datadriven::StencilConfiguration::colorIndex_, sgpp::datadriven::GeometryConfiguration::dim_, sgpp::datadriven::NextHierarchicalParent, and sgpp::datadriven::StencilConfiguration::stencilType_.
getInteractions()
std::set< std::set< size_t > > sgpp::datadriven::GridFactory::getInteractions (sgpp::datadriven::GeometryConfiguration config) const
References sgpp::datadriven::AllHierarchicalParent, sgpp::datadriven::Block, sgpp::datadriven::GeometryConfiguration::dim_, sgpp::datadriven::DirectNeighbour, sgpp::datadriven::NextHierarchicalParent, sgpp::datadriven::None, and sgpp::datadriven::GeometryConfiguration::stencils_.
Referenced by sgpp::datadriven::ModelFittingClassification::adapt(), sgpp::datadriven::ModelFittingDensityEstimation::adapt(), sgpp::datadriven::ModelFittingLeastSquares::adapt(), sgpp::datadriven::ModelFittingBase::buildGrid(), sgpp::datadriven::ModelFittingBase::getInteractions(), and sgpp::datadriven::DBMatPermutationFactory::getPermutedObject().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/GridFactory.hpp
datadriven/src/sgpp/datadriven/algorithm/GridFactory.cpp