SG++-Doxygen-Documentation: sgpp::base::HermiteBasis Class Reference
sgpp::base::HermiteBasis Class Reference
#include <HermiteBasis.hpp>
Static Public Member Functions
static double h_0_0 (double x)
static double h_0_1 (double x)
static double h_1_0 (double x)
static double h_1_1 (double x)
Member Function Documentation
h_0_0()
static double sgpp::base::HermiteBasis::h_0_0 (double x) inline static
Referenced by sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D().
h_0_1()
static double sgpp::base::HermiteBasis::h_0_1 (double x) inline static
Referenced by sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D().
h_1_0()
static double sgpp::base::HermiteBasis::h_1_0 (double x) inline static
Referenced by sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D().
h_1_1()
static double sgpp::base::HermiteBasis::h_1_1 (double x) inline static
Referenced by sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/HermiteBasis.hpp