SG++-Doxygen-Documentation: sgpp::datadriven::SortedDataset Class Reference
sgpp::datadriven::SortedDataset Class Reference
Dataset that can be ordered. Accessing the included DataMatrix might invalidate the order.
#include <SortedDataset.hpp>
Public Types
enum OrderType {
None , External , Random , Morton ,
Invalid
}
Available permutations.
Public Member Functions
sgpp::base::DataMatrix & getData ()
Sets the OrderType to OrderType::Invalid.
OrderType getOrderType () const
Returns current order type.
void restoreOrder ()
Restores the original order in case of a valid order type. Sets ot to OrderType::None.
void setOrder (const std::vector< size_t > &permutation)
Reorders the data with a given permutation.
void setOrder (OrderType order)
Sets the order for the dataset and rearranges the data.
SortedDataset ()
Constructs an empty dataset (zero size).
SortedDataset (const Dataset &src)
Constructs a copy of a dataset.
SortedDataset (size_t numberInstances, size_t dimension)
Constructs an empty dataset with given size.
Public Member Functions inherited from sgpp::datadriven::Dataset
Dataset ()
Constructs an empty dataset (zero size).
Dataset (size_t numberInstances, size_t dimension)
Constructs an empty dataset with given size.
sgpp::base::DataMatrix & getData ()
const sgpp::base::DataMatrix & getData () const
size_t getDimension () const
size_t getNumberInstances () const
sgpp::base::DataVector & getTargets ()
const sgpp::base::DataVector & getTargets () const
Protected Member Functions
void usePermutation ()
uses the permutation on the DataMatrix and the DataVector
Protected Attributes
OrderType ot
std::vector< size_t > perm
Protected Attributes inherited from sgpp::datadriven::Dataset
sgpp::base::DataMatrix data
size_t dimension
size_t numberInstances
sgpp::base::DataVector targets
Detailed Description
Dataset that can be ordered. Accessing the included DataMatrix might invalidate the order.
Member Enumeration Documentation
OrderType
enum sgpp::datadriven::SortedDataset::OrderType
Available permutations.
Enumerator
None
External
Random
Morton
Invalid
Constructor & Destructor Documentation
SortedDataset() [1/3]
sgpp::datadriven::SortedDataset::SortedDataset ()
Constructs an empty dataset (zero size).
References None, ot, and perm.
SortedDataset() [2/3]
sgpp::datadriven::SortedDataset::SortedDataset (size_t numberInstances, size_t dimension)
Constructs an empty dataset with given size.
Parameters
numberInstances number of instances in the dataset
dimension number of dimensions in the dataset
References None, sgpp::datadriven::Dataset::numberInstances, ot, and perm.
SortedDataset() [3/3]
sgpp::datadriven::SortedDataset::SortedDataset (const Dataset & src) explicit
Constructs a copy of a dataset.
References sgpp::datadriven::Dataset::getNumberInstances(), None, ot, and perm.
Member Function Documentation
getData()
sgpp::base::DataMatrix & sgpp::datadriven::SortedDataset::getData ()
Sets the OrderType to OrderType::Invalid.
Returns
training data of the dataset
References sgpp::datadriven::Dataset::getData(), Invalid, and ot.
getOrderType()
SortedDataset::OrderType sgpp::datadriven::SortedDataset::getOrderType () const
Returns current order type.
References ot.
restoreOrder()
void sgpp::datadriven::SortedDataset::restoreOrder ()
Restores the original order in case of a valid order type. Sets ot to OrderType::None.
References sgpp::datadriven::Dataset::data, sgpp::base::DataMatrix::getNcols(), Invalid, ot, perm, and sgpp::datadriven::Dataset::targets.
setOrder() [1/2]
void sgpp::datadriven::SortedDataset::setOrder (const std::vector< size_t > & permutation)
Reorders the data with a given permutation.
Sets the order type to OrderType::External If the permutation is invalid due to a size or index mismatch, ot is set to OrderType::Invalid. The i-th data value is permuted to the permutation[i]-th position.
References External, Invalid, sgpp::datadriven::Dataset::numberInstances, ot, perm, and usePermutation().
setOrder() [2/2]
void sgpp::datadriven::SortedDataset::setOrder (OrderType order)
Sets the order for the dataset and rearranges the data.
The order is unchanged in case of OrderType::External. OrderType::None creates the identity permutation.
The order is unchanged in case of OrderType::External.
References sgpp::datadriven::Dataset::data, External, Invalid, Morton, None, sgpp::datadriven::Dataset::numberInstances, ot, perm, Random, and usePermutation().
usePermutation()
void sgpp::datadriven::SortedDataset::usePermutation () protected
uses the permutation on the DataMatrix and the DataVector
References sgpp::datadriven::Dataset::data, sgpp::base::DataMatrix::getNcols(), perm, and sgpp::datadriven::Dataset::targets.
Referenced by setOrder(), and setOrder().
Member Data Documentation
ot
OrderType sgpp::datadriven::SortedDataset::ot protected
Referenced by getData(), getOrderType(), restoreOrder(), setOrder(), setOrder(), SortedDataset(), SortedDataset(), and SortedDataset().
perm
std::vector<size_t> sgpp::datadriven::SortedDataset::perm protected
Referenced by restoreOrder(), setOrder(), setOrder(), SortedDataset(), SortedDataset(), SortedDataset(), and usePermutation().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/SortedDataset.hpp
datadriven/src/sgpp/datadriven/tools/SortedDataset.cpp