SG++-Doxygen-Documentation: sgpp::datadriven::MultiGridRefinementFunctor Class Reference
sgpp::datadriven::MultiGridRefinementFunctor Class Reference abstract
Abstract super-class for refinement functors operating on multiple grids.
#include <MultiGridRefinementFunctor.hpp>
Public Member Functions
virtual size_t getNumGrids ()=0
Returns the number of grids the functor can / does refine.
virtual void preComputeEvaluations ()
Used if expensive computations (eg.
virtual void setGridIndex (size_t grid_index)=0
Sets the index (into the vector of grids) of the grid to be refined.
virtual ~MultiGridRefinementFunctor ()
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual size_t getRefinementsNum () const
Returns the maximal number of points that should be refined.
virtual double getRefinementThreshold () const =0
Returns the threshold for refinement.
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
virtual double operator() (GridStorage &storage, size_t seq) const =0
This should be returning a refinement value for every grid point.
RefinementFunctor ()
Constructor.
virtual double start () const =0
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
virtual ~RefinementFunctor ()
Destructor.
Additional Inherited Members
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Detailed Description
Abstract super-class for refinement functors operating on multiple grids.
Constructor & Destructor Documentation
~MultiGridRefinementFunctor()
virtual sgpp::datadriven::MultiGridRefinementFunctor::~MultiGridRefinementFunctor () inline virtual
Member Function Documentation
getNumGrids()
virtual size_t sgpp::datadriven::MultiGridRefinementFunctor::getNumGrids () pure virtual
Returns the number of grids the functor can / does refine.
Implemented in sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, and sgpp::datadriven::MultiSurplusRefinementFunctor.
preComputeEvaluations()
virtual void sgpp::datadriven::MultiGridRefinementFunctor::preComputeEvaluations () inline virtual
Used if expensive computations (eg.
grid evaluations) are cached, usually for one refinement step.
Reimplemented in sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, and sgpp::datadriven::ZeroCrossingRefinementFunctor.
Referenced by sgpp::datadriven::ModelFittingClassification::adapt(), sgpp::datadriven::RefinementHandler::handleDataAndZeroBasedRefinement(), and sgpp::datadriven::LearnerSGDE::trainOnline().
setGridIndex()
virtual void sgpp::datadriven::MultiGridRefinementFunctor::setGridIndex (size_t grid_index) pure virtual
Sets the index (into the vector of grids) of the grid to be refined.
Parameters
grid_index The index of the grid to be refined
Implemented in sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, and sgpp::datadriven::MultiSurplusRefinementFunctor.
Referenced by sgpp::datadriven::ModelFittingClassification::adapt(), sgpp::datadriven::RefinementHandler::handleDataAndZeroBasedRefinement(), and sgpp::datadriven::LearnerSGDE::trainOnline().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/functors/MultiGridRefinementFunctor.hpp