SG++-Doxygen-Documentation: sgpp::optimization::optimizer::AdaptiveGradientDescent Class Reference
sgpp::optimization::optimizer::AdaptiveGradientDescent Class Reference
Gradient descent with adaptive step size.
#include <AdaptiveGradientDescent.hpp>
Public Member Functions
AdaptiveGradientDescent (const AdaptiveGradientDescent &other)
Copy constructor.
AdaptiveGradientDescent (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, size_t maxItCount=DEFAULT_N, double tolerance=DEFAULT_TOLERANCE, double stepSizeIncreaseFactor=DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor=DEFAULT_STEP_SIZE_DECREASE_FACTOR, double lineSearchAccuracy=DEFAULT_LINE_SEARCH_ACCURACY)
Constructor.
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getLineSearchAccuracy () const
double getStepSizeDecreaseFactor () const
double getStepSizeIncreaseFactor () const
double getTolerance () const
void optimize () override
Pure virtual method for optimization of the objective function.
void setLineSearchAccuracy (double lineSearchAccuracy)
void setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
void setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
void setTolerance (double tolerance)
~AdaptiveGradientDescent () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_LINE_SEARCH_ACCURACY = 0.01
default line search accuracy
static constexpr double DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5
default step size decrease factor
static constexpr double DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2
default step size increase factor
static constexpr double DEFAULT_TOLERANCE = 1e-6
default tolerance
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double rhoAlphaMinus
step size decrease factor
double rhoAlphaPlus
step size increase factor
double rhoLs
line search accuracy
double theta
tolerance
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Gradient descent with adaptive step size.
Constructor & Destructor Documentation
AdaptiveGradientDescent() [1/2]
sgpp::optimization::optimizer::AdaptiveGradientDescent::AdaptiveGradientDescent (const base::ScalarFunction & f, const base::ScalarFunctionGradient & fGradient, size_t maxItCount = DEFAULT_N, double tolerance = DEFAULT_TOLERANCE, double stepSizeIncreaseFactor = DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor = DEFAULT_STEP_SIZE_DECREASE_FACTOR, double lineSearchAccuracy = DEFAULT_LINE_SEARCH_ACCURACY)
Constructor.
Parameters
f objective function
fGradient objective function gradient
maxItCount maximal number of function evaluations
tolerance tolerance
stepSizeIncreaseFactor step size increase factor
stepSizeDecreaseFactor step size decrease factor
lineSearchAccuracy line search accuracy
AdaptiveGradientDescent() [2/2]
sgpp::optimization::optimizer::AdaptiveGradientDescent::AdaptiveGradientDescent (const AdaptiveGradientDescent & other)
Copy constructor.
Parameters
other optimizer to be copied
~AdaptiveGradientDescent()
sgpp::optimization::optimizer::AdaptiveGradientDescent::~AdaptiveGradientDescent () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getLineSearchAccuracy()
double sgpp::optimization::optimizer::AdaptiveGradientDescent::getLineSearchAccuracy () const
Returns
line search accuracy
References rhoLs.
getStepSizeDecreaseFactor()
double sgpp::optimization::optimizer::AdaptiveGradientDescent::getStepSizeDecreaseFactor () const
Returns
step size decrease factor
References rhoAlphaMinus.
getStepSizeIncreaseFactor()
double sgpp::optimization::optimizer::AdaptiveGradientDescent::getStepSizeIncreaseFactor () const
Returns
step size increase factor
References rhoAlphaPlus.
getTolerance()
double sgpp::optimization::optimizer::AdaptiveGradientDescent::getTolerance () const
Returns
tolerance
References theta.
optimize()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References alpha, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::base::Printer::getInstance(), sgpp::base::DataVector::l2Norm(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), rhoAlphaMinus, rhoAlphaPlus, rhoLs, theta, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setLineSearchAccuracy()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::setLineSearchAccuracy (double lineSearchAccuracy)
Parameters
lineSearchAccuracy line search accuracy
References rhoLs.
setStepSizeDecreaseFactor()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
Parameters
stepSizeDecreaseFactor step size decrease factor
References rhoAlphaMinus.
setStepSizeIncreaseFactor()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
Parameters
stepSizeIncreaseFactor step size increase factor
References rhoAlphaPlus.
setTolerance()
void sgpp::optimization::optimizer::AdaptiveGradientDescent::setTolerance (double tolerance)
Parameters
tolerance tolerance
References theta.
Member Data Documentation
DEFAULT_LINE_SEARCH_ACCURACY
constexpr double sgpp::optimization::optimizer::AdaptiveGradientDescent::DEFAULT_LINE_SEARCH_ACCURACY = 0.01 static constexpr
default line search accuracy
DEFAULT_STEP_SIZE_DECREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveGradientDescent::DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5 static constexpr
default step size decrease factor
DEFAULT_STEP_SIZE_INCREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveGradientDescent::DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2 static constexpr
default step size increase factor
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::AdaptiveGradientDescent::DEFAULT_TOLERANCE = 1e-6 static constexpr
default tolerance
rhoAlphaMinus
double sgpp::optimization::optimizer::AdaptiveGradientDescent::rhoAlphaMinus protected
step size decrease factor
Referenced by getStepSizeDecreaseFactor(), optimize(), and setStepSizeDecreaseFactor().
rhoAlphaPlus
double sgpp::optimization::optimizer::AdaptiveGradientDescent::rhoAlphaPlus protected
step size increase factor
Referenced by getStepSizeIncreaseFactor(), optimize(), and setStepSizeIncreaseFactor().
rhoLs
double sgpp::optimization::optimizer::AdaptiveGradientDescent::rhoLs protected
line search accuracy
Referenced by getLineSearchAccuracy(), optimize(), and setLineSearchAccuracy().
theta
double sgpp::optimization::optimizer::AdaptiveGradientDescent::theta protected
tolerance
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/AdaptiveGradientDescent.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/AdaptiveGradientDescent.cpp