SG++-Doxygen-Documentation: sgpp::base::OperationEvalLinearClenshawCurtisNaive Class Reference
sgpp::base::OperationEvalLinearClenshawCurtisNaive Class Reference
#include <OperationEvalLinearClenshawCurtisNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalLinearClenshawCurtisNaive (GridStorage &storage)
Constructor.
~OperationEvalLinearClenshawCurtisNaive () override
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SLinearClenshawCurtisBase base
1D linear basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Constructor & Destructor Documentation
OperationEvalLinearClenshawCurtisNaive()
sgpp::base::OperationEvalLinearClenshawCurtisNaive::OperationEvalLinearClenshawCurtisNaive (GridStorage & storage) inline explicit
Constructor.
Parameters
storage storage of the sparse grid
~OperationEvalLinearClenshawCurtisNaive()
sgpp::base::OperationEvalLinearClenshawCurtisNaive::~OperationEvalLinearClenshawCurtisNaive () inline override
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SLinearClenshawCurtisBase sgpp::base::OperationEvalLinearClenshawCurtisNaive::base protected
1D linear basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalLinearClenshawCurtisNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalLinearClenshawCurtisNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalLinearClenshawCurtisNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalLinearClenshawCurtisNaive.cpp