SG++-Doxygen-Documentation: sgpp::optimization::test_problems::TremblingParabolaObjective Class Reference
sgpp::optimization::test_problems::TremblingParabolaObjective Class Reference
Trembling parabola objective function.
#include <TremblingParabola.hpp>
Public Member Functions
void clone (std::unique_ptr< base::ScalarFunction > &clone) const override
double evalUndisplaced (const base::DataVector &x) override
TremblingParabolaObjective (size_t d, size_t p)
Constructor.
~TremblingParabolaObjective () override
Destructor.
Public Member Functions inherited from sgpp::optimization::test_problems::TestScalarFunction
double eval (const base::DataVector &x) override
Evaluate displaced function.
const base::DataVector & getDisplacement () const
void setDisplacement (const base::DataVector &displacement)
TestScalarFunction (size_t d)
Constructor.
~TestScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Protected Member Functions
double splineTrembling (double x) const
Protected Attributes
const base::SBsplineBase bSplineBasis
const double g0
const size_t p
Protected Attributes inherited from sgpp::optimization::test_problems::TestScalarFunction
base::DataVector displacement
displacement vector
base::DataVector xTmp
temporary vector for displacing
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
Trembling parabola objective function.
Definition:
\[\bar{f}(\bar{\vec{x}}) := \sum_{t=1}^d \left(\bar{x}_t^2/10 + \frac{|\bar{x}_t|}{2} \left(\frac{g^p(\bar{x}_t)}{g^p(0)} + 1\right)\right),\qquad g^p(x) := \sum_{k \sim x} (-1)^k b^p(x - k + (p+1)/2)\]
with \(b^p\) being the B-spline with knots \((0, 1, \dotsc, p + 1)\) (degree \(p\)) and the sum running over all \(k\) for which the summand doesn't vanish
Constructor & Destructor Documentation
TremblingParabolaObjective()
sgpp::optimization::test_problems::TremblingParabolaObjective::TremblingParabolaObjective (size_t d, size_t p)
Constructor.
Parameters
d dimension of the domain
p smoothness of the function (\(p\) times continuously differentiable)
~TremblingParabolaObjective()
sgpp::optimization::test_problems::TremblingParabolaObjective::~TremblingParabolaObjective () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::test_problems::TremblingParabolaObjective::clone (std::unique_ptr< base::ScalarFunction > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone().
Referenced by clone().
evalUndisplaced()
double sgpp::optimization::test_problems::TremblingParabolaObjective::evalUndisplaced (const base::DataVector & x) override virtual
Parameters
x point \(\vec{x} \in [0, 1]^d\)
Returns
\(f(\vec{x})\)
Implements sgpp::optimization::test_problems::TestScalarFunction.
References sgpp::base::ScalarFunction::d, g0, and splineTrembling().
splineTrembling()
double sgpp::optimization::test_problems::TremblingParabolaObjective::splineTrembling (double x) const inline protected
References bSplineBasis, p, and sgpp::base::BsplineBasis< LT, IT >::uniformBSpline().
Referenced by evalUndisplaced().
Member Data Documentation
bSplineBasis
const base::SBsplineBase sgpp::optimization::test_problems::TremblingParabolaObjective::bSplineBasis protected
Referenced by splineTrembling().
g0
const double sgpp::optimization::test_problems::TremblingParabolaObjective::g0 protected
Referenced by evalUndisplaced().
p
const size_t sgpp::optimization::test_problems::TremblingParabolaObjective::p protected
Referenced by splineTrembling().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/unconstrained/TremblingParabola.hpp
optimization/src/sgpp/optimization/test_problems/unconstrained/TremblingParabola.cpp