SG++-Doxygen-Documentation: sgpp::base::ModBsplineClenshawCurtisGrid Class Reference
sgpp::base::ModBsplineClenshawCurtisGrid Class Reference
Grid with modified Clenshaw-Curtis Bspline basis functions.
#include <ModBsplineClenshawCurtisGrid.hpp>
Public Member Functions
SBasis & getBasis () override
virtual size_t getDegree ()
GridGenerator & getGenerator () override
Creates new GridGenerator This must be changed if we add other storage types.
sgpp::base::GridType getType () override
ModBsplineClenshawCurtisGrid (size_t dim, size_t degree)
Constructor of grid with modified Clenshaw-Curtis Bspline basis functions.
void serialize (std::ostream &ostr, int version=SERIALIZATION_VERSION) override
Serializes the grid.
~ModBsplineClenshawCurtisGrid () override
Destructor.
Public Member Functions inherited from sgpp::base::Grid
Grid * clone ()
copies a grid
Grid * createGridOfEquivalentType (size_t numDims)
creates an equivalent grid without copying the grid points
std::vector< size_t > getAlgorithmicDimensions ()
returns the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
virtual BoundingBox & getBoundingBox ()
gets a reference to the GridStorage's BoundingsBox object
size_t getDimension () const
Returns the number of dimensions.
size_t getSize () const
Returns the number of points on the grid.
virtual GridStorage & getStorage ()
gets a reference to the GridStorage object
virtual Stretching & getStretching ()
gets a reference to the GridStorage's Stretching object
std::string getTypeAsString ()
Returns a string that identifies the grid type uniquely.
sgpp::base::GridType getZeroBoundaryType ()
Returns the grid type that corresponds to the actual type but does no boundary treatment.
Grid (const Grid &other)=delete
delete copy constructor
void insertPoint (size_t dim, unsigned int levels[], unsigned int indices[], bool isLeaf)
Insert one point to the grid.
void refine (DataVector &vector, int numOfPoints)
Refine grid Refine the given number of points on the grid according to the vector.
std::string serialize (int version=SERIALIZATION_VERSION)
Serializes grid to a string.
void serialize (std::string &ostr, int version=SERIALIZATION_VERSION)
Serializes grid to a string.
void setAlgorithmicDimensions (std::vector< size_t > newAlgoDims)
sets the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
virtual void setBoundingBox (BoundingBox &boundingBox)
sets the GridStorage's BoundingsBox
virtual void setStretching (Stretching &stretching)
sets the GridStorage's Stretching pointer to a Stretching object
virtual ~Grid ()
Desctructor.
Static Public Member Functions
static Grid * unserialize (std::istream &istr)
reads a grid out of a string
Static Public Member Functions inherited from sgpp::base::Grid
static Grid * createBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a B-spline trapezoid boundary grid
static Grid * createBsplineClenshawCurtisGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a B-spline Clenshaw-Curtis grid
static Grid * createBsplineGrid (size_t dim, size_t degree)
creates a B-spline grid
static Grid * createFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createFundamentalSplineGrid (size_t dim, size_t degree)
creates a fundamental spline grid
static Grid * createGrid (RegularGridConfiguration gridConfig)
creates a grid defined by the grid configuration
static Grid * createLinearBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a linear boundary grid
static Grid * createLinearClenshawCurtisBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a linear Clenshaw-Curtis boundary grid
static Grid * createLinearClenshawCurtisGrid (size_t dim)
creates a linear Clenshaw-Curtis grid
static Grid * createLinearGrid (size_t dim)
Creates and returns a grid without grid points on the boundary (zero boundary conditions) with piecewise linear basis functions.
static Grid * createLinearGridStencil (size_t dim)
creates a stencil for a linear grid (without boundaries)
static Grid * createLinearStretchedBoundaryGrid (size_t dim)
creates a linearstretched truncated boundary grid
static Grid * createLinearStretchedGrid (size_t dim)
creates a linear stretched grid without boundaries
static Grid * createLinearTruncatedBoundaryGrid (size_t dim)
creates a truncated boundary grid=contains all the gridpoints of the fullgrids which have \(|l|<level and li>=l_user\)
static Grid * createModBsplineClenshawCurtisGrid (size_t dim, size_t degree)
creates a modified B-spline Clenshaw-Curtis grid
static Grid * createModBsplineGrid (size_t dim, size_t degree)
creates a modified B-spline grid
static Grid * createModFundamentalSplineGrid (size_t dim, size_t degree)
creates a modified fundamental spline grid
static Grid * createModLinearClenshawCurtisGrid (size_t dim)
creates a modified linear Clenshaw-Curtis grid
static Grid * createModLinearGrid (size_t dim)
creates a modified linear grid
static Grid * createModLinearGridStencil (size_t dim)
creates a stencil for a modified linear grid (without boundaries)
static Grid * createModNakBsplineGrid (size_t dim, size_t degree)
static Grid * createModPolyClenshawCurtisGrid (size_t dim, size_t degree)
creates a modified poly grid with clenshaw curtis points
static Grid * createModPolyGrid (size_t dim, size_t degree)
creates a modified polynomial grid
static Grid * createModWaveletGrid (size_t dim)
creates a modified wavelet grid
static Grid * createModWeaklyFundamentalNakSplineGrid (size_t dim, size_t degree)
static Grid * createNakBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createNakBsplineExtendedGrid (size_t dim, size_t degree)
creates a not a knot B-Spline extended grid
static Grid * createNakBsplineGrid (size_t dim, size_t degree)
creates a not a knot B-Spline grid
static Grid * createNakPBsplineGrid (size_t dim, size_t degree)
creates a not a knot polynomial B-Spline extended grid
static Grid * createNaturalBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a not a knot B-Spline boundary grid
static Grid * createPeriodicGrid (size_t dim)
creates a periodic grid
static Grid * createPolyBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a polynomial grid with truncated boundary
static Grid * createPolyClenshawCurtisBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a poly Clenshaw Curtis boundary grid with clenshaw curtis points
static Grid * createPolyClenshawCurtisGrid (size_t dim, size_t degree)
creates a poly grid with clenshaw curtis points
static Grid * createPolyGrid (size_t dim, size_t degree)
creates a polynomial grid
static Grid * createPrewaveletGrid (size_t dim)
creates a prewavelet grid
static Grid * createSquareRootGrid (size_t dim)
creates a square root grid (h-grid)
static Grid * createWaveletBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a wavelet trapezoid boundary grid
static Grid * createWaveletGrid (size_t dim)
creates a wavelet grid
static Grid * createWeaklyFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createWeaklyFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static GridType stringToGridType (const std::string &gridType)
Conversion from string to grid type.
static Grid * unserialize (const std::string &istr)
reads a grid out of a string
static Grid * unserialize (std::istream &istr)
reads a grid out of a stream
static Grid * unserializeFromFile (std::string filename)
opens a file given by name and reads a grid out of the stored string @ param filename name of the file
Protected Member Functions
ModBsplineClenshawCurtisGrid (std::istream &istr)
This constructor creates a new GridStorage out of the stream.
Protected Member Functions inherited from sgpp::base::Grid
Grid (BoundingBox &boundingBox)
Constructor initializing the grid storage with the given BoundingBox.
Grid (size_t dim)
Constructor initializing the grid storage with the given dimensionality.
Grid (std::istream &istr)
This constructor creates a new GridStorage out of the stream.
Grid (Stretching &stretching)
Constructor initializing the grid storage with the given Stretching.
Protected Attributes
std::unique_ptr< SBsplineModifiedClenshawCurtisBase > basis_
B-spline basis.
size_t degree
B-spline degree.
StandardGridGenerator generator
grid generator
Protected Attributes inherited from sgpp::base::Grid
GridStorage storage
GridStorage object of the grid.
Additional Inherited Members
Protected Types inherited from sgpp::base::Grid
typedef Grid *(* Factory) (std::istream &)
typedef std::map< std::string, Grid::Factory > factoryMap
typedef std::map< sgpp::base::GridType, std::string > gridTypeVerboseMap
Static Protected Member Functions inherited from sgpp::base::Grid
static Grid * nullFactory (std::istream &)
Factory for everything we don't know.
Detailed Description
Grid with modified Clenshaw-Curtis Bspline basis functions.
Constructor & Destructor Documentation
ModBsplineClenshawCurtisGrid() [1/2]
sgpp::base::ModBsplineClenshawCurtisGrid::ModBsplineClenshawCurtisGrid (std::istream & istr) explicit protected
This constructor creates a new GridStorage out of the stream.
Parameters
istr inputstream that contains the grid information
References basis_, and degree.
ModBsplineClenshawCurtisGrid() [2/2]
sgpp::base::ModBsplineClenshawCurtisGrid::ModBsplineClenshawCurtisGrid (size_t dim, size_t degree) explicit
Constructor of grid with modified Clenshaw-Curtis Bspline basis functions.
Parameters
dim the dimension of the grid
degree the bspline's degree
References sgpp::base::HashGridStorage::setStretching(), and sgpp::base::Grid::storage.
~ModBsplineClenshawCurtisGrid()
sgpp::base::ModBsplineClenshawCurtisGrid::~ModBsplineClenshawCurtisGrid () override
Destructor.
Member Function Documentation
getBasis()
SBasis & sgpp::base::ModBsplineClenshawCurtisGrid::getBasis () override virtual
Returns
B-spline basis
Implements sgpp::base::Grid.
References basis_.
getDegree()
size_t sgpp::base::ModBsplineClenshawCurtisGrid::getDegree () virtual
Returns
B-spline degree
References degree.
Referenced by sgpp::op_factory::createOperationEvalGradientNaive(), sgpp::op_factory::createOperationEvalHessianNaive(), sgpp::op_factory::createOperationEvalNaive(), sgpp::op_factory::createOperationEvalPartialDerivativeNaive(), sgpp::op_factory::createOperationQuadrature(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), and sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation().
getGenerator()
GridGenerator & sgpp::base::ModBsplineClenshawCurtisGrid::getGenerator () override virtual
Creates new GridGenerator This must be changed if we add other storage types.
Returns
pointer to a GridGenerator object
Implements sgpp::base::Grid.
References generator.
getType()
sgpp::base::GridType sgpp::base::ModBsplineClenshawCurtisGrid::getType () override virtual
Returns
string that identifies the grid type uniquely
Implements sgpp::base::Grid.
References sgpp::base::ModBsplineClenshawCurtis.
serialize()
void sgpp::base::ModBsplineClenshawCurtisGrid::serialize (std::ostream & ostr, int version = SERIALIZATION_VERSION) override virtual
Serializes the grid.
Parameters
ostr stream to which the grid is written
version the serialization version of the file
Reimplemented from sgpp::base::Grid.
References degree, and sgpp::base::Grid::serialize().
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
unserialize()
Grid * sgpp::base::ModBsplineClenshawCurtisGrid::unserialize (std::istream & istr) static
reads a grid out of a string
Parameters
istr string that contains the grid information
Returns
grid
Member Data Documentation
basis_
std::unique_ptr<SBsplineModifiedClenshawCurtisBase> sgpp::base::ModBsplineClenshawCurtisGrid::basis_ protected
B-spline basis.
Referenced by getBasis(), and ModBsplineClenshawCurtisGrid().
degree
size_t sgpp::base::ModBsplineClenshawCurtisGrid::degree protected
B-spline degree.
Referenced by getDegree(), ModBsplineClenshawCurtisGrid(), and serialize().
generator
StandardGridGenerator sgpp::base::ModBsplineClenshawCurtisGrid::generator protected
grid generator
Referenced by getGenerator().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/type/ModBsplineClenshawCurtisGrid.hpp
base/src/sgpp/base/grid/type/ModBsplineClenshawCurtisGrid.cpp