SG++-Doxygen-Documentation: sgpp::datadriven::DensityEstimator Class Reference
sgpp::datadriven::DensityEstimator Class Reference abstract
#include <DensityEstimator.hpp>
Public Member Functions
virtual void corrcoef (base::DataMatrix &corr, base::DataMatrix *bounds=nullptr)
virtual void cov (base::DataMatrix &cov, base::DataMatrix *bounds=nullptr)=0
double crossEntropy (sgpp::base::DataMatrix &samples)
DensityEstimator ()
virtual size_t getDim ()=0
virtual size_t getNsamples ()=0
virtual std::shared_ptr< base::DataMatrix > getSamples ()=0
virtual std::shared_ptr< base::DataVector > getSamples (size_t dim)=0
virtual void initialize (base::DataMatrix &samples)=0
virtual double mean ()=0
virtual void pdf (base::DataMatrix &points, base::DataVector &res)=0
virtual double pdf (base::DataVector &x)=0
virtual double std_deviation ()
virtual double variance ()=0
virtual ~DensityEstimator ()
Constructor & Destructor Documentation
DensityEstimator()
sgpp::datadriven::DensityEstimator::DensityEstimator ()
~DensityEstimator()
sgpp::datadriven::DensityEstimator::~DensityEstimator () virtual
Member Function Documentation
corrcoef()
void sgpp::datadriven::DensityEstimator::corrcoef (base::DataMatrix & corr, base::DataMatrix * bounds = nullptr) virtual
References cov(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), and sgpp::base::DataMatrix::set().
cov()
virtual void sgpp::datadriven::DensityEstimator::cov (base::DataMatrix & cov, base::DataMatrix * bounds = nullptr) pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by corrcoef(), and python.uq.dists.Dist.Dist::corrcoeff().
crossEntropy()
double sgpp::datadriven::DensityEstimator::crossEntropy (sgpp::base::DataMatrix & samples)
References pdf().
Referenced by sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::eval().
getDim()
virtual size_t sgpp::datadriven::DensityEstimator::getDim () pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.uq.dists.Dist.Dist::cov(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), and python.uq.uq_setting.UQSetting.UQSetting::getDim().
getNsamples()
virtual size_t sgpp::datadriven::DensityEstimator::getNsamples () pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
getSamples() [1/2]
virtual std::shared_ptr< base::DataMatrix > sgpp::datadriven::DensityEstimator::getSamples () pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
getSamples() [2/2]
virtual std::shared_ptr< base::DataVector > sgpp::datadriven::DensityEstimator::getSamples (size_t dim) pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
initialize()
virtual void sgpp::datadriven::DensityEstimator::initialize (base::DataMatrix & samples) pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
mean()
virtual double sgpp::datadriven::DensityEstimator::mean () pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), python.uq.dists.LibAGFDist.LibAGFDist::var(), and python.uq.dists.SGDEdist.SGDEdist::var().
pdf() [1/2]
virtual void sgpp::datadriven::DensityEstimator::pdf (base::DataMatrix & points, base::DataVector & res) pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
pdf() [2/2]
virtual double sgpp::datadriven::DensityEstimator::pdf (base::DataVector & x) pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
std_deviation()
double sgpp::datadriven::DensityEstimator::std_deviation () virtual
References variance().
variance()
virtual double sgpp::datadriven::DensityEstimator::variance () pure virtual
Implemented in sgpp::datadriven::KernelDensityEstimator, sgpp::datadriven::LearnerSGDE, and sgpp::datadriven::SparseGridDensityEstimator.
Referenced by std_deviation().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/DensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/DensityEstimator.cpp