SG++-Doxygen-Documentation: sgpp::solver::LassoFunction Class Reference
sgpp::solver::LassoFunction Class Reference
The LassoFunction class.
#include <LassoFunction.hpp>
Public Member Functions
double eval (base::DataVector weights) override
eval evaluates the regularization function for weights.
LassoFunction (double lambda)
LassoFunction.
base::DataVector prox (const base::DataVector &weights, double stepsize) override
prox evaluates the proximal operator for the function for weights.
~LassoFunction () override
Public Member Functions inherited from sgpp::solver::RegularizationFunction
virtual ~RegularizationFunction ()
Detailed Description
The LassoFunction class.
This class models the standard lasso regularization penalty \(\Vert \boldsymbol{\alpha} \Vert_1 \).
Constructor & Destructor Documentation
LassoFunction()
sgpp::solver::LassoFunction::LassoFunction (double lambda) inline explicit
LassoFunction.
Parameters
lambda controls the regularization strength.
References lambda.
~LassoFunction()
sgpp::solver::LassoFunction::~LassoFunction () inline override
Member Function Documentation
eval()
double sgpp::solver::LassoFunction::eval (base::DataVector weights) inline override virtual
eval evaluates the regularization function for weights.
Parameters
weights
Implements sgpp::solver::RegularizationFunction.
References sgpp::base::DataVector::abs(), and sgpp::base::DataVector::sum().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
prox()
base::DataVector sgpp::solver::LassoFunction::prox (const base::DataVector & weights, double stepsize) inline override virtual
prox evaluates the proximal operator for the function for weights.
Parameters
weights
stepsize is the stepsize used for the proximal step
Implements sgpp::solver::RegularizationFunction.
References sgpp::base::DataVector::getSize().
Referenced by sgpp::solver::ElasticNetFunction::prox().
The documentation for this class was generated from the following file:
solver/src/sgpp/solver/sle/fista/LassoFunction.hpp