SG++-Doxygen-Documentation: sgpp::base::OperationEvalHessian Class Reference
sgpp::base::OperationEvalHessian Class Reference abstract
Abstract operation for evaluating a linear combination of basis functions, its gradient and its Hessian.
#include <OperationEvalHessian.hpp>
Public Member Functions
virtual void evalHessian (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient, std::vector< DataMatrix > &hessian)
virtual double evalHessian (const DataVector &alpha, const DataVector &point, DataVector &gradient, DataMatrix &hessian)=0
OperationEvalHessian ()
Constructor.
virtual ~OperationEvalHessian ()
Destructor.
Public Attributes
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Abstract operation for evaluating a linear combination of basis functions, its gradient and its Hessian.
Constructor & Destructor Documentation
OperationEvalHessian()
sgpp::base::OperationEvalHessian::OperationEvalHessian () inline
Constructor.
~OperationEvalHessian()
virtual sgpp::base::OperationEvalHessian::~OperationEvalHessian () inline virtual
Destructor.
Member Function Documentation
evalHessian() [1/2]
virtual void sgpp::base::OperationEvalHessian::evalHessian (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient, std::vector< DataMatrix > & hessian) inline virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
[out] hessian vector of Hessians of the linear combination
Reimplemented in sgpp::base::OperationEvalHessianBsplineBoundaryNaive, sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive, sgpp::base::OperationEvalHessianBsplineNaive, sgpp::base::OperationEvalHessianFundamentalNakSplineNaive, sgpp::base::OperationEvalHessianFundamentalSplineNaive, sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalHessianModBsplineNaive, sgpp::base::OperationEvalHessianModFundamentalSplineNaive, sgpp::base::OperationEvalHessianModNakBsplineNaive, sgpp::base::OperationEvalHessianModWaveletNaive, sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive, sgpp::base::OperationEvalHessianWaveletBoundaryNaive, sgpp::base::OperationEvalHessianWaveletNaive, sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive.
References alpha, evalHessian(), m, sgpp::base::DataMatrix::resize(), and sgpp::base::DataMatrix::setRow().
evalHessian() [2/2]
virtual double sgpp::base::OperationEvalHessian::evalHessian (const DataVector & alpha, const DataVector & point, DataVector & gradient, DataMatrix & hessian) pure virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient vector of the linear combination
[out] hessian Hessian matrix of the linear combination
Returns
value of the linear combination
Implemented in sgpp::base::OperationEvalHessianBsplineBoundaryNaive, sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive, sgpp::base::OperationEvalHessianBsplineNaive, sgpp::base::OperationEvalHessianFundamentalNakSplineNaive, sgpp::base::OperationEvalHessianFundamentalSplineNaive, sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalHessianModBsplineNaive, sgpp::base::OperationEvalHessianModFundamentalSplineNaive, sgpp::base::OperationEvalHessianModNakBsplineNaive, sgpp::base::OperationEvalHessianModWaveletNaive, sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive, sgpp::base::OperationEvalHessianWaveletBoundaryNaive, sgpp::base::OperationEvalHessianWaveletNaive, sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive.
Referenced by evalHessian().
Member Data Documentation
pointInUnitCube
DataVector sgpp::base::OperationEvalHessian::pointInUnitCube
untransformed evaluation point (temporary vector)
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationEvalHessian.hpp