SG++-Doxygen-Documentation: sgpp::datadriven::OperationTestPoly Class Reference
sgpp::datadriven::OperationTestPoly Class Reference
This class implements OperationTest for a grids with poly basis ansatzfunctions with.
#include <OperationTestPoly.hpp>
Public Member Functions
virtual void calculateROCcurve (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &classes, sgpp::base::DataVector &thresholds, sgpp::base::DataMatrix &ROC_curve)
Computes the classification accuracy on some test data.
OperationTestPoly (base::GridStorage *storage, size_t degree)
Constructor.
virtual double test (base::DataVector &alpha, base::DataMatrix &data, base::DataVector &classes)
Computes the classification accuracy on some test data.
virtual double testMSE (base::DataVector &alpha, base::DataMatrix &data, base::DataVector &refValues)
Computes the regression accuracy on some test data.
virtual double testWithCharacteristicNumber (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &classes, sgpp::base::DataVector &charaNumbers)
Computes the classification accuracy on some test data.
virtual ~OperationTestPoly ()
Destructor.
Public Member Functions inherited from sgpp::datadriven::OperationTest
OperationTest ()
Constructor.
virtual ~OperationTest ()
Destructor.
Protected Attributes
base::SPolyBase base
Poly Basis object.
base::GridStorage * storage
Pointer to base::GridStorage object.
Detailed Description
This class implements OperationTest for a grids with poly basis ansatzfunctions with.
Constructor & Destructor Documentation
OperationTestPoly()
sgpp::datadriven::OperationTestPoly::OperationTestPoly (base::GridStorage * storage, size_t degree) inline explicit
Constructor.
Parameters
storage the grid's base::GridStorage object
degree the polynom's max. degree
~OperationTestPoly()
virtual sgpp::datadriven::OperationTestPoly::~OperationTestPoly () inline virtual
Destructor.
Member Function Documentation
calculateROCcurve()
void sgpp::datadriven::OperationTestPoly::calculateROCcurve (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & classes, sgpp::base::DataVector & thresholds, sgpp::base::DataMatrix & ROC_curve) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off variable at threshold
Also the number of the TP TN FP FN are determined
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector the holds the class information
thresholds the thresholds (between -1.0 and 1.0) for calculating the ROC curve
ROC_curve DataMatrix into which the ROC curve is stored
Implements sgpp::datadriven::OperationTest.
References base, storage, and sgpp::datadriven::test_calculateROCcurve().
test()
double sgpp::datadriven::OperationTestPoly::test (base::DataVector & alpha, base::DataMatrix & data, base::DataVector & classes) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off at 0.
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector holding the class information
Implements sgpp::datadriven::OperationTest.
References base, storage, and sgpp::datadriven::test_dataset().
testMSE()
double sgpp::datadriven::OperationTestPoly::testMSE (base::DataVector & alpha, base::DataMatrix & data, base::DataVector & refValues) virtual
Computes the regression accuracy on some test data.
The function is evaluated at the given points. Calculates the MSE between between the given values and the values evaluated on the sparse grid.
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
refValues sgpp::base::DataVector holding the reference function values
Implements sgpp::datadriven::OperationTest.
References base, storage, and sgpp::datadriven::test_dataset_mse().
Referenced by python.uq.manager.ASGCStatistics.ASGCStatistics::updateResults().
testWithCharacteristicNumber()
double sgpp::datadriven::OperationTestPoly::testWithCharacteristicNumber (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & classes, sgpp::base::DataVector & charaNumbers) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off at 0.
Also the number of the TP TN FP FN are determined
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector the holds the class information
charaNumbers the number of true positives, true negatives, false positives, false negatives (Vector of length 4)
Implements sgpp::datadriven::OperationTest.
References base, storage, and sgpp::datadriven::test_datasetWithCharacteristicNumber().
Member Data Documentation
base
base::SPolyBase sgpp::datadriven::OperationTestPoly::base protected
Poly Basis object.
Referenced by calculateROCcurve(), test(), testMSE(), and testWithCharacteristicNumber().
storage
base::GridStorage* sgpp::datadriven::OperationTestPoly::storage protected
Pointer to base::GridStorage object.
Referenced by calculateROCcurve(), test(), testMSE(), and testWithCharacteristicNumber().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationTestPoly.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationTestPoly.cpp