SG++-Doxygen-Documentation: sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
Modified polynomial base functions.
#include <PolyModifiedClenshawCurtisBasis.hpp>
Public Member Functions
double eval (LT level, IT index, double p) override
Evaluate the basis function with given level and index.
double eval (LT level, IT index, double p, double offset, double width)
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
double evalHierToTop (LT level, IT index, DataVector &coeffs, double pos)
Evaluates all the hierarchical ancestors of the node defined by level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
PolyModifiedClenshawCurtisBasis (size_t degree)
Constructor.
~PolyModifiedClenshawCurtisBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
ClenshawCurtisTable & clenshawCurtisTable
reference to the Clenshaw-Curtis cache table
SPolyClenshawCurtisBase polyBasis
poly basis
Detailed Description
template<class LT, class IT>
class sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >
Modified polynomial base functions.
Special polynomial functions to cover values unequal 0 at the border. Implemented as seen in AWR 2 paper by Prof. Bungartz (http://www5.in.tum.de/wiki/index.php/Algorithmen_des_Wissenschaftlichen_Rechnens_II_-_Winter_08)
Constructor & Destructor Documentation
PolyModifiedClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::PolyModifiedClenshawCurtisBasis (size_t degree) inline explicit
Constructor.
Parameters
degree the polynom's max. degree
~PolyModifiedClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::~PolyModifiedClenshawCurtisBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval (LT level, IT index, double x) inline override virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::ClenshawCurtisTable::getPoint(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalHierToTop(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), and sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose().
eval() [2/2]
template<class LT , class IT > double sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval (LT level, IT index, double p, double offset, double width) inline
References sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::ClenshawCurtisTable::getPoint(), level, and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::polyBasis.
Referenced by sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult().
evalHierToTop()
template<class LT , class IT > double sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalHierToTop (LT level, IT index, DataVector & coeffs, double pos) inline
Evaluates all the hierarchical ancestors of the node defined by level and index.
NOTE: It does not evaluate the current node itself.
Parameters
level
index
coeffs
pos
Returns
References sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), and level.
Referenced by sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), and sgpp::base::HierarchisationModPolyClenshawCurtis::rec().
getDegree()
template<class LT , class IT > size_t sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getDegree(), and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::polyBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::ClenshawCurtisTable::getPoint(), level, and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::polyBasis.
Referenced by sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature().
Member Data Documentation
clenshawCurtisTable
template<class LT , class IT > ClenshawCurtisTable& sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable protected
reference to the Clenshaw-Curtis cache table
Referenced by sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalDx(), and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
polyBasis
template<class LT , class IT > SPolyClenshawCurtisBase sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::polyBasis protected
poly basis
Referenced by sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getDegree(), and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/PolyModifiedClenshawCurtisBasis.hpp