SG++-Doxygen-Documentation: sgpp::base::BoundaryGridGenerator Class Reference
sgpp::base::BoundaryGridGenerator Class Reference
This class provides the interface for the grid generation for grids with boundaries, pentagon cut through sub space scheme.
#include <BoundaryGridGenerator.hpp>
Public Member Functions
BoundaryGridGenerator (GridStorage &storage, level_t boundaryLevel=1)
Constructor.
void cliques (size_t level, size_t clique_size) override
Creates a sparse grid with fully connected cliques.
void coarsen (CoarseningFunctor &func, std::vector< size_t > *removedSeq) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void coarsenNFirstOnly (CoarseningFunctor &func, size_t numFirstOnly, std::vector< size_t > *removedSeq, size_t minIndexConsidered) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void full (size_t level) override
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
level_t getBoundaryLevel () const
size_t getNumberOfRefinablePoints () override
Returns the number of points on the grid that can be refined in the next iteration.
size_t getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
size_t getNumberOfRemovablePoints () override
Returns the number of points on the grid that can be removed in the next iteration.
void refine (RefinementFunctor &func, std::vector< size_t > *addedPoints=nullptr) override
Refines a grid according to the settings of the RefinementFunctor func.
void refineMaxLevel (RefinementFunctor &func, size_t maxLevel) override
Refines a grid according to the settings of the RefinementFunctor func.
void regular (size_t level) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
void setBoundaryLevel (level_t boundaryLevel)
~BoundaryGridGenerator () override
Destructor.
Public Member Functions inherited from sgpp::base::GridGenerator
virtual void anisotropicFull (std::vector< size_t > dimlevels)
Creates an anisotropicFull Grid for certain level vector, for example [2,3,1] results in a 3x7x1 grid.
virtual void cliques (size_t level, size_t clique_size, double T)
Creates a sparse grid with fully connected cliques.
GridGenerator ()
Constructor.
virtual void refineInter (RefinementFunctor &func, const std::set< std::set< size_t > > &interactions)
Refines a grid according to the settings of the RefinementFunctor func.
virtual void regular (size_t level, double T)
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
virtual void regularInter (size_t level, const std::set< std::set< size_t > > &terms, double T)
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
virtual void truncated (size_t level, size_t l_user)
Creates a grid which doesn't contain the fullgrids with li<l_user, for any li level_t.
virtual ~GridGenerator ()
Destructor.
Protected Attributes
level_t boundaryLevel
level at which the boundary points should be inserted
GridStorage & storage
reference to the grid's storage object
Detailed Description
This class provides the interface for the grid generation for grids with boundaries, pentagon cut through sub space scheme.
Constructor & Destructor Documentation
BoundaryGridGenerator()
sgpp::base::BoundaryGridGenerator::BoundaryGridGenerator (GridStorage & storage, level_t boundaryLevel = 1) explicit
Constructor.
Parameters
storage template type that holds the grid points
boundaryLevel 1 + how much levels the boundary is coarser than the main axes, 0 means one level finer, 1 means same level, 2 means one level coarser, etc.
~BoundaryGridGenerator()
sgpp::base::BoundaryGridGenerator::~BoundaryGridGenerator () override
Destructor.
Member Function Documentation
cliques()
void sgpp::base::BoundaryGridGenerator::cliques (size_t level, size_t clique_size) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
Implements sgpp::base::GridGenerator.
coarsen()
void sgpp::base::BoundaryGridGenerator::coarsen (CoarseningFunctor & func, std::vector< size_t > * removedSeq) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Parameters
func pointer to coarsening functor
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen(), and storage.
Referenced by coarsen(), coarsenNFirstOnly(), and getNumberOfRemovablePoints().
coarsenNFirstOnly()
void sgpp::base::BoundaryGridGenerator::coarsenNFirstOnly (CoarseningFunctor & func, size_t numFirstOnly, std::vector< size_t > * removedSeq, size_t minIndexConsidered) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Only numFirstOnly first grid points are checked for coarsening.
Parameters
func pointer to coarsening functor
numFirstOnly max. number grid points to be coarsened
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
minIndexConsidered Minimum index of grid points that will be coarsened
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen_NFirstOnly(), and storage.
full()
void sgpp::base::BoundaryGridGenerator::full (size_t level) override virtual
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::fullWithBoundary(), level, and storage.
getBoundaryLevel()
level_t sgpp::base::BoundaryGridGenerator::getBoundaryLevel () const
References boundaryLevel.
getNumberOfRefinablePoints()
size_t sgpp::base::BoundaryGridGenerator::getNumberOfRefinablePoints () override virtual
Returns the number of points on the grid that can be refined in the next iteration.
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), refine(), and storage.
getNumberOfRefinablePointsToMaxLevel()
size_t sgpp::base::BoundaryGridGenerator::getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override virtual
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
Parameters
maxLevel no points on higher levels than maxLevel will be created
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), refine(), and storage.
getNumberOfRemovablePoints()
size_t sgpp::base::BoundaryGridGenerator::getNumberOfRemovablePoints () override virtual
Returns the number of points on the grid that can be removed in the next iteration.
Returns
the number of points on the grid that can be removed
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), and storage.
refine()
void sgpp::base::BoundaryGridGenerator::refine (RefinementFunctor & func, std::vector< size_t > * addedPoints = nullptr) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
Parameters
func reference to refinement functor
addedPoints pointer to vector to add newly created grid points to
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinementBoundaries::free_refine(), refine(), and storage.
Referenced by getNumberOfRefinablePoints(), getNumberOfRefinablePointsToMaxLevel(), refine(), and refineMaxLevel().
refineMaxLevel()
void sgpp::base::BoundaryGridGenerator::refineMaxLevel (RefinementFunctor & func, size_t maxLevel) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
additionally a maximum level for refinement is taken into account
Parameters
func pointer to refinement functor
maxLevel no points on higher levels than maxLevel will be created
Implements sgpp::base::GridGenerator.
References refine(), sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel(), and storage.
regular()
void sgpp::base::BoundaryGridGenerator::regular (size_t level) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References boundaryLevel, level, sgpp::base::HashGenerator::regularWithBoundaries(), and storage.
setBoundaryLevel()
void sgpp::base::BoundaryGridGenerator::setBoundaryLevel (level_t boundaryLevel)
References boundaryLevel.
Referenced by sgpp::base::BsplineBoundaryGrid::BsplineBoundaryGrid(), sgpp::base::BsplineClenshawCurtisGrid::BsplineClenshawCurtisGrid(), sgpp::base::FundamentalNakSplineBoundaryGrid::FundamentalNakSplineBoundaryGrid(), sgpp::base::FundamentalSplineBoundaryGrid::FundamentalSplineBoundaryGrid(), sgpp::base::LinearBoundaryGrid::LinearBoundaryGrid(), sgpp::base::LinearClenshawCurtisBoundaryGrid::LinearClenshawCurtisBoundaryGrid(), sgpp::base::NakBsplineBoundaryGrid::NakBsplineBoundaryGrid(), sgpp::base::NaturalBsplineBoundaryGrid::NaturalBsplineBoundaryGrid(), sgpp::base::PolyBoundaryGrid::PolyBoundaryGrid(), sgpp::base::PolyClenshawCurtisBoundaryGrid::PolyClenshawCurtisBoundaryGrid(), sgpp::base::WaveletBoundaryGrid::WaveletBoundaryGrid(), sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid::WeaklyFundamentalNakSplineBoundaryGrid(), and sgpp::base::WeaklyFundamentalSplineBoundaryGrid::WeaklyFundamentalSplineBoundaryGrid().
Member Data Documentation
boundaryLevel
level_t sgpp::base::BoundaryGridGenerator::boundaryLevel protected
level at which the boundary points should be inserted
Referenced by getBoundaryLevel(), regular(), and setBoundaryLevel().
storage
GridStorage& sgpp::base::BoundaryGridGenerator::storage protected
reference to the grid's storage object
Referenced by coarsen(), coarsenNFirstOnly(), full(), getNumberOfRefinablePoints(), getNumberOfRefinablePointsToMaxLevel(), getNumberOfRemovablePoints(), refine(), refineMaxLevel(), and regular().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/BoundaryGridGenerator.hpp
base/src/sgpp/base/grid/generation/BoundaryGridGenerator.cpp