SG++-Doxygen-Documentation: sgpp::datadriven::SparseGridMiner Class Reference
sgpp::datadriven::SparseGridMiner Class Reference abstract
SparseGridMiner models the entire mining process for data mining with sparse grids.
#include <SparseGridMiner.hpp>
Public Member Functions
ModelFittingBase * getModel ()
Returns the trained model.
Visualizer * getVisualizer ()
virtual double learn (bool verbose)=0
Perform Learning cycle: Get samples from data source and based on the scoring procedure, generalize data by fitting and asses quality of the fit.
SparseGridMiner & operator= (const SparseGridMiner &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
SparseGridMiner & operator= (SparseGridMiner &&rhs)=default
Default Move assign operator.
void setModel (ModelFittingBase *model)
SparseGridMiner (const SparseGridMiner &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
SparseGridMiner (ModelFittingBase *fitter, Scorer *scorer, Visualizer *visualizer)
Constructor.
SparseGridMiner (SparseGridMiner &&rhs)=default
Default Move constructor .
double test (Dataset &testDataset)
Evaluate the model on a certain test dataset.
virtual ~SparseGridMiner ()=default
Default destructor.
Static Public Member Functions
static void print (const char *message)
Print output on one process.
static void print (const std::string &message)
Print output on one process.
static void print (std::ostringstream &messageStream)
Print output on one process.
Protected Attributes
std::unique_ptr< ModelFittingBase > fitter
Fitter that trains a model based on data samples.
std::unique_ptr< Scorer > scorer
Scorer that quantifies the quality of a fit.
std::unique_ptr< Visualizer > visualizer
Detailed Description
SparseGridMiner models the entire mining process for data mining with sparse grids.
It aggregates and automates data input, fitting and validation modules and controls the mining process.
Constructor & Destructor Documentation
SparseGridMiner() [1/3]
sgpp::datadriven::SparseGridMiner::SparseGridMiner (ModelFittingBase * fitter, Scorer * scorer, Visualizer * visualizer)
Constructor.
Parameters
fitter configured instance of fitter object that generalize the model. The miner instance will take ownership of the passed object.
scorer configured instance of scorer object that will assess the quality of the generalization provided by the fitter on testing data. The miner instance will take ownership of the passed object.
visualizer configured instance of the visualizer object that will execute the visualization module of the model. The miner instance will take ownership of the passed object
SparseGridMiner() [2/3]
sgpp::datadriven::SparseGridMiner::SparseGridMiner (const SparseGridMiner & rhs) delete
Copy constructor deleted - not all members can be copied or cloned .
Parameters
rhs the object to copy from
SparseGridMiner() [3/3]
sgpp::datadriven::SparseGridMiner::SparseGridMiner (SparseGridMiner && rhs) default
Default Move constructor .
Parameters
rhs the object to move from
~SparseGridMiner()
virtual sgpp::datadriven::SparseGridMiner::~SparseGridMiner () virtual default
Default destructor.
Member Function Documentation
getModel()
ModelFittingBase * sgpp::datadriven::SparseGridMiner::getModel ()
Returns the trained model.
Returns
the trained model
getVisualizer()
Visualizer * sgpp::datadriven::SparseGridMiner::getVisualizer ()
learn()
virtual double sgpp::datadriven::SparseGridMiner::learn (bool verbose) pure virtual
Perform Learning cycle: Get samples from data source and based on the scoring procedure, generalize data by fitting and asses quality of the fit.
Implemented in sgpp::datadriven::SparseGridMinerCrossValidation, sgpp::datadriven::SparseGridMinerSplitting, and sgpp::datadriven::SparseGridMinerSplittingTwoDatasets.
operator=() [1/2]
SparseGridMiner & sgpp::datadriven::SparseGridMiner::operator= (const SparseGridMiner & rhs) delete
Default copy assign operator deleted because not all members can be copied.
Parameters
rhs the object to copy from
operator=() [2/2]
SparseGridMiner & sgpp::datadriven::SparseGridMiner::operator= (SparseGridMiner && rhs) default
Default Move assign operator.
Parameters
rhs the object to move from
print() [1/3]
void sgpp::datadriven::SparseGridMiner::print (const char * message) static
Print output on one process.
Parameters
message
References print().
print() [2/3]
void sgpp::datadriven::SparseGridMiner::print (const std::string & message) static
Print output on one process.
Parameters
message
References sgpp::datadriven::BlacsProcessGrid::getCurrentProcess().
Referenced by sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::SparseGridMinerSplitting::optimizeLambda(), print(), and print().
print() [3/3]
void sgpp::datadriven::SparseGridMiner::print (std::ostringstream & messageStream) static
Print output on one process.
Parameters
messageStream stream with the concatenated message
References print().
setModel()
void sgpp::datadriven::SparseGridMiner::setModel (ModelFittingBase * model)
References fitter, and sgpp::datadriven::ModelFittingBase::reset().
test()
double sgpp::datadriven::SparseGridMiner::test (Dataset & testDataset)
Evaluate the model on a certain test dataset.
Parameters
testDataset dataset used quantify accuracy using sgpp::datadriven::Metric.
Returns
score of the fit.
References fitter, and scorer.
Member Data Documentation
fitter
std::unique_ptr<ModelFittingBase> sgpp::datadriven::SparseGridMiner::fitter protected
Fitter that trains a model based on data samples.
Referenced by sgpp::datadriven::SparseGridMinerSplitting::evaluateLambda(), sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn(), sgpp::datadriven::SparseGridMinerSplitting::optimizeLambda(), setModel(), and test().
scorer
std::unique_ptr<Scorer> sgpp::datadriven::SparseGridMiner::scorer protected
Scorer that quantifies the quality of a fit.
(e.g. cross validation or training with testing)
Referenced by sgpp::datadriven::SparseGridMinerSplitting::evaluateLambda(), sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn(), and test().
visualizer
std::unique_ptr<Visualizer> sgpp::datadriven::SparseGridMiner::visualizer protected
Referenced by sgpp::datadriven::SparseGridMinerCrossValidation::learn(), and sgpp::datadriven::SparseGridMinerSplitting::learn().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/base/SparseGridMiner.hpp
datadriven/src/sgpp/datadriven/datamining/base/SparseGridMiner.cpp