SG++-Doxygen-Documentation: sgpp::base::GridPrinter Class Reference
sgpp::base::GridPrinter Class Reference
This class implements a utility that allows you to print a grid to file.
#include <GridPrinter.hpp>
Public Member Functions
GridPrinter (Grid &SparseGrid)
Std-Constructor.
virtual void printGrid (DataVector &alpha, std::string tFilename, size_t PointsPerDimension)
Print the grid with its function to a file; front end.
virtual void printGridDomain (DataVector &alpha, std::string tFilename, BoundingBox &GridArea, size_t PointsPerDimension)
Print the grid with its function to a file; front end.
virtual void printLevelIndexGrid (std::string tFilename)
Print the grid points in level/index format to a file; front end.
virtual void printSparseGrid (DataVector &alpha, std::string tFilename, bool bSurplus)
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
virtual void printSparseGridExpTransform (DataVector &alpha, std::string tFilename, bool bSurplus)
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
virtual ~GridPrinter ()
Std-Destructor.
Protected Attributes
Grid * myGrid
Pointer to the grid Object, which should be printed.
Detailed Description
This class implements a utility that allows you to print a grid to file.
These files can be plotted with gnuplot.
Constructor & Destructor Documentation
GridPrinter()
sgpp::base::GridPrinter::GridPrinter (Grid & SparseGrid) explicit
Std-Constructor.
Parameters
SparseGrid Reference to a Spare Grid, that should be printed
~GridPrinter()
sgpp::base::GridPrinter::~GridPrinter () virtual
Std-Destructor.
Member Function Documentation
printGrid()
void sgpp::base::GridPrinter::printGrid (DataVector & alpha, std::string tFilename, size_t PointsPerDimension) virtual
Print the grid with its function to a file; front end.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absolute path to the file the grid is written into
PointsPerDimension specifies how many functions evaluations in every dimension should be calculated
Reimplemented in sgpp::base::GridPrinterForStretching.
References alpha, sgpp::op_factory::createOperationEval(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::Grid::getBoundingBox(), sgpp::base::Grid::getDimension(), sgpp::base::Grid::getSize(), sgpp::base::BoundingBox1D::leftBoundary, myGrid, and sgpp::base::BoundingBox1D::rightBoundary.
Referenced by sgpp::datadriven::LearnerBase::dumpFunction(), sgpp::datadriven::LearnerBaseSP::dumpFunction(), and sgpp::pde::PDESolver::printGrid().
printGridDomain()
void sgpp::base::GridPrinter::printGridDomain (DataVector & alpha, std::string tFilename, BoundingBox & GridArea, size_t PointsPerDimension) virtual
Print the grid with its function to a file; front end.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absolute path to the file the grid is written into
GridArea The area in which the function should be plotted
PointsPerDimension specifies how many functions evaluations in every dimension should be calculated
Reimplemented in sgpp::base::GridPrinterForStretching.
References alpha, sgpp::op_factory::createOperationEval(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::Grid::getDimension(), sgpp::base::Grid::getSize(), sgpp::base::BoundingBox1D::leftBoundary, myGrid, and sgpp::base::BoundingBox1D::rightBoundary.
Referenced by sgpp::pde::PDESolver::printGridDomain().
printLevelIndexGrid()
void sgpp::base::GridPrinter::printLevelIndexGrid (std::string tFilename) virtual
Print the grid points in level/index format to a file; front end.
Parameters
tFilename absolute path to the file the grid is written into
References sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStorage(), and myGrid.
Referenced by sgpp::pde::PDESolver::printLevelIndexGrid().
printSparseGrid()
void sgpp::base::GridPrinter::printSparseGrid (DataVector & alpha, std::string tFilename, bool bSurplus) virtual
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absoulte path to the file the grid is written into
bSurplus specifies whether the surplus (true) or the node basis value (false) is written
Reimplemented in sgpp::base::GridPrinterForStretching.
References alpha, sgpp::op_factory::createOperationHierarchisation(), sgpp::base::HashGridStorage::getCoordinates(), sgpp::base::Grid::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStorage(), and myGrid.
Referenced by sgpp::datadriven::LearnerBase::dumpGrid(), sgpp::datadriven::LearnerBaseSP::dumpGrid(), sgpp::pde::PDESolver::printSparseGrid(), and sgpp::solver::Euler::solve().
printSparseGridExpTransform()
void sgpp::base::GridPrinter::printSparseGridExpTransform (DataVector & alpha, std::string tFilename, bool bSurplus) virtual
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
The coordinates of the grid points are pushed the exp function. So log transformed grids can be plotted in cartesion coordinates.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absoulte path to the file the grid is written into
bSurplus specifies whether the surplus (true) or the node basis value (false) is written
Reimplemented in sgpp::base::GridPrinterForStretching.
References alpha, sgpp::op_factory::createOperationHierarchisation(), sgpp::base::HashGridStorage::getCoordinates(), sgpp::base::Grid::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStorage(), and myGrid.
Referenced by sgpp::pde::PDESolver::printSparseGridExpTransform().
Member Data Documentation
myGrid
Grid* sgpp::base::GridPrinter::myGrid protected
Pointer to the grid Object, which should be printed.
Referenced by sgpp::base::GridPrinterForStretching::GridPrinterForStretching(), printGrid(), sgpp::base::GridPrinterForStretching::printGrid(), printGridDomain(), sgpp::base::GridPrinterForStretching::printGridDomainStretching(), printLevelIndexGrid(), printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), printSparseGridExpTransform(), and sgpp::base::GridPrinterForStretching::printSparseGridExpTransform().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/GridPrinter.hpp
base/src/sgpp/base/tools/GridPrinter.cpp