SG++-Doxygen-Documentation: sgpp::optimization::optimizer::CMAES Class Reference
sgpp::optimization::optimizer::CMAES Class Reference
Gradient-free CMA-ES method.
#include <CMAES.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
CMAES (const base::ScalarFunction &f, size_t maxFcnEvalCount=DEFAULT_MAX_FCN_EVAL_COUNT)
Constructor.
CMAES (const CMAES &other)
Copy constructor.
void optimize () override
Pure virtual method for optimization of the objective function.
~CMAES () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static const size_t DEFAULT_MAX_FCN_EVAL_COUNT = 1000
default maximal number of function evaluations
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Additional Inherited Members
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Gradient-free CMA-ES method.
Constructor & Destructor Documentation
CMAES() [1/2]
sgpp::optimization::optimizer::CMAES::CMAES (const base::ScalarFunction & f, size_t maxFcnEvalCount = DEFAULT_MAX_FCN_EVAL_COUNT) explicit
Constructor.
The starting point is set to \((0.5, \dotsc, 0.5)^{\mathrm{T}}\).
Parameters
f objective function
maxFcnEvalCount maximal number of function evaluations
CMAES() [2/2]
sgpp::optimization::optimizer::CMAES::CMAES (const CMAES & other)
Copy constructor.
Parameters
other optimizer to be copied
~CMAES()
sgpp::optimization::optimizer::CMAES::~CMAES () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::CMAES::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
optimize()
void sgpp::optimization::optimizer::CMAES::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::base::DataVector::add(), sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), D, sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::base::RandomNumberGenerator::getGaussianRN(), sgpp::base::Printer::getInstance(), sgpp::base::RandomNumberGenerator::getInstance(), sgpp::base::DataVector::l2Norm(), lambda, m, mu, sgpp::base::DataMatrix::mult(), sgpp::base::DataVector::mult(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), sgpp::optimization::math::schurDecomposition(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataVector::sum(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
Member Data Documentation
DEFAULT_MAX_FCN_EVAL_COUNT
const size_t sgpp::optimization::optimizer::CMAES::DEFAULT_MAX_FCN_EVAL_COUNT = 1000 static
default maximal number of function evaluations
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/CMAES.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/CMAES.cpp