SG++-Doxygen-Documentation: sgpp::datadriven::DataBasedRefinementFunctor Class Reference
sgpp::datadriven::DataBasedRefinementFunctor Class Reference
Data based refinement uses data points to find refinement candidates.
#include <DataBasedRefinementFunctor.hpp>
Public Member Functions
void computeH ()
Recomputes the set of relevant data (the set H).
DataBasedRefinementFunctor (std::vector< base::Grid * > grids, std::vector< base::DataVector * > alphas, std::vector< double > priors, base::DataMatrix *data, base::DataVector *targets, size_t refinements_num=1, bool level_penalize=false, std::vector< double > coeff_a=std::vector< double >(), double threshold=0.0)
Constructor.
base::DataMatrix & getHk (size_t index)
Returns a ref to the specified H_k, used for debugging /plotting.
size_t getNumGrids () override
Returns the number of grids the functor can / does refine.
size_t getRefinementsNum () const override
Returns the maximal number of points that should be refined.
double getRefinementThreshold () const override
Returns the threshold for refinement.
double operator() (base::GridStorage &storage, size_t seq) const override
This should be returning a refinement value for every grid point.
void setData (base::DataMatrix *data, base::DataVector *targets)
Set the training data + targets which is the basis for determining relevant data points.
void setGridIndex (size_t grid_index) override
Sets the index (into the vector of grids) of the grid to be refined.
double start () const override
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
~DataBasedRefinementFunctor () override
Public Member Functions inherited from sgpp::datadriven::MultiGridRefinementFunctor
virtual void preComputeEvaluations ()
Used if expensive computations (eg.
virtual ~MultiGridRefinementFunctor ()
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
RefinementFunctor ()
Constructor.
virtual ~RefinementFunctor ()
Destructor.
Protected Member Functions
void computeHkl (base::DataMatrix &inters, size_t cl_ind1, size_t cl_ind2)
Computes the "intersection data points" of class k and l.
bool isWithinSupport (base::HashGridPoint &gp, base::DataVector &point) const
Is point in support of basis function at gp.
Protected Attributes
std::vector< base::DataVector * > alphas
std::vector< double > coeff_a
The scaling coefficients for this->means.
size_t current_grid_index
base::DataMatrix * data
Pointer to the training data used for determining H.
base::DataMatrix evals
Evaluations of data points are cached here.
std::vector< base::Grid * > grids
std::vector< base::DataMatrix > h
Each H_k contains a set of "intersection data points" between class k and all other classes.
bool level_penalize
std::vector< double > means
The mean values of the PDFs given by grids, alphas Approximated using this->data.
std::vector< double > priors
size_t refinements_num
base::DataVector * targets
Pointer to targets related to this->data.
double threshold
Additional Inherited Members
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Detailed Description
Data based refinement uses data points to find refinement candidates.
For the given data sets class-intersection sets H_k are computed. A grid points is included in H_k if for at least on class l PDF_k(point) > coeff_a_k * mu_k AND PDF_l(point) > coeff_a_l * mu_l. To determine the score of a grid point, the number of data points from H_k within the support of this grid point is taken
Constructor & Destructor Documentation
DataBasedRefinementFunctor()
sgpp::datadriven::DataBasedRefinementFunctor::DataBasedRefinementFunctor (std::vector< base::Grid * > grids, std::vector< base::DataVector * > alphas, std::vector< double > priors, base::DataMatrix * data, base::DataVector * targets, size_t refinements_num = 1, bool level_penalize = false, std::vector< double > coeff_a = std::vector<double>(), double threshold = 0.0)
Constructor.
Parameters
grids Vector of grids. current_grid_index specifies the grid to be refined
alphas Vector of surpluses related to the grids
priors Vector of priors related to the classificator
data The data used to compute the sets H_k
targets The classes for data
refinements_num Maximum number of refinements done
level_penalize If a level penalizing is multiplied to the score (2^{|l|_1})
coeff_a Scaling coefficients for the computation of H_k. Per default 1.0
threshold Threshold for refinement scores
References coeff_a, computeH(), data, grids, and targets.
~DataBasedRefinementFunctor()
sgpp::datadriven::DataBasedRefinementFunctor::~DataBasedRefinementFunctor () inline override
Member Function Documentation
computeH()
void sgpp::datadriven::DataBasedRefinementFunctor::computeH ()
Recomputes the set of relevant data (the set H).
If the training data is changed, call this method to actually re-compute H. Might require a lot of time depending on the size of the training data.
References alphas, computeHkl(), sgpp::op_factory::createOperationMultipleEval(), data, evals, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), grids, h, means, priors, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setColumn(), and sgpp::base::DataVector::sum().
Referenced by DataBasedRefinementFunctor().
computeHkl()
void sgpp::datadriven::DataBasedRefinementFunctor::computeHkl (base::DataMatrix & inters, size_t cl_ind1, size_t cl_ind2) protected
Computes the "intersection data points" of class k and l.
References sgpp::base::DataMatrix::appendRow(), coeff_a, data, evals, sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), and means.
Referenced by computeH().
getHk()
base::DataMatrix & sgpp::datadriven::DataBasedRefinementFunctor::getHk (size_t index)
Returns a ref to the specified H_k, used for debugging /plotting.
Parameters
index The index k for H_k
References h.
getNumGrids()
size_t sgpp::datadriven::DataBasedRefinementFunctor::getNumGrids () override virtual
Returns the number of grids the functor can / does refine.
Implements sgpp::datadriven::MultiGridRefinementFunctor.
References grids.
getRefinementsNum()
size_t sgpp::datadriven::DataBasedRefinementFunctor::getRefinementsNum () const override virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
number of points that should refined. Default value: 1.
Reimplemented from sgpp::base::RefinementFunctor.
References refinements_num.
getRefinementThreshold()
double sgpp::datadriven::DataBasedRefinementFunctor::getRefinementThreshold () const override virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion (e.g., alpha or error) greater or equal to this threshold will be refined.
Returns
threshold value for refinement. Default value: 0.
Implements sgpp::base::RefinementFunctor.
References threshold.
isWithinSupport()
bool sgpp::datadriven::DataBasedRefinementFunctor::isWithinSupport (base::HashGridPoint & gp, base::DataVector & point) const protected
Is point in support of basis function at gp.
References sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridPoint::getStandardCoordinate(), and level.
Referenced by operator()().
operator()()
double sgpp::datadriven::DataBasedRefinementFunctor::operator() (base::GridStorage & storage, size_t seq) const override virtual
This should be returning a refinement value for every grid point.
The point with the highest value will be refined first.
Parameters
storage reference to the grids storage object
seq sequence number in the coefficients array
Returns
refinement value
Implements sgpp::base::RefinementFunctor.
References current_grid_index, data, sgpp::base::HashGridPoint::getLevelSum(), sgpp::base::DataMatrix::getNcols(), sgpp::base::HashGridStorage::getPoint(), h, isWithinSupport(), and level_penalize.
setData()
void sgpp::datadriven::DataBasedRefinementFunctor::setData (base::DataMatrix * data, base::DataVector * targets)
Set the training data + targets which is the basis for determining relevant data points.
This method is only necessary in data-streaming scenarios where the training data changes overall.
Parameters
data Pointer to the (subset of) training data used
targets Pointer to the related targets
References data, and targets.
setGridIndex()
void sgpp::datadriven::DataBasedRefinementFunctor::setGridIndex (size_t grid_index) override virtual
Sets the index (into the vector of grids) of the grid to be refined.
Parameters
grid_index The index of the grid to be refined
Implements sgpp::datadriven::MultiGridRefinementFunctor.
References current_grid_index.
start()
double sgpp::datadriven::DataBasedRefinementFunctor::start () const override virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implements sgpp::base::RefinementFunctor.
Member Data Documentation
alphas
std::vector<base::DataVector*> sgpp::datadriven::DataBasedRefinementFunctor::alphas protected
Referenced by computeH().
coeff_a
std::vector<double> sgpp::datadriven::DataBasedRefinementFunctor::coeff_a protected
The scaling coefficients for this->means.
Referenced by computeHkl(), and DataBasedRefinementFunctor().
current_grid_index
size_t sgpp::datadriven::DataBasedRefinementFunctor::current_grid_index protected
Referenced by operator()(), and setGridIndex().
data
base::DataMatrix* sgpp::datadriven::DataBasedRefinementFunctor::data protected
Pointer to the training data used for determining H.
Referenced by computeH(), computeHkl(), DataBasedRefinementFunctor(), operator()(), and setData().
evals
base::DataMatrix sgpp::datadriven::DataBasedRefinementFunctor::evals protected
Evaluations of data points are cached here.
Referenced by computeH(), and computeHkl().
grids
std::vector<base::Grid*> sgpp::datadriven::DataBasedRefinementFunctor::grids protected
Referenced by computeH(), DataBasedRefinementFunctor(), and getNumGrids().
h
std::vector<base::DataMatrix> sgpp::datadriven::DataBasedRefinementFunctor::h protected
Each H_k contains a set of "intersection data points" between class k and all other classes.
These sets are the basis for the scoring process
Referenced by computeH(), getHk(), and operator()().
level_penalize
bool sgpp::datadriven::DataBasedRefinementFunctor::level_penalize protected
Referenced by operator()().
means
std::vector<double> sgpp::datadriven::DataBasedRefinementFunctor::means protected
The mean values of the PDFs given by grids, alphas Approximated using this->data.
Referenced by computeH(), and computeHkl().
priors
std::vector<double> sgpp::datadriven::DataBasedRefinementFunctor::priors protected
Referenced by computeH().
refinements_num
size_t sgpp::datadriven::DataBasedRefinementFunctor::refinements_num protected
Referenced by getRefinementsNum().
targets
base::DataVector* sgpp::datadriven::DataBasedRefinementFunctor::targets protected
Pointer to targets related to this->data.
Referenced by DataBasedRefinementFunctor(), and setData().
threshold
double sgpp::datadriven::DataBasedRefinementFunctor::threshold protected
Referenced by getRefinementThreshold().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/functors/classification/DataBasedRefinementFunctor.hpp
datadriven/src/sgpp/datadriven/functors/classification/DataBasedRefinementFunctor.cpp