SG++-Doxygen-Documentation: sgpp::datadriven::MortonOrder Class Reference
sgpp::datadriven::MortonOrder Class Reference
#include <MortonOrder.hpp>
Public Member Functions
const std::vector< size_t > & getPermutation () const
bool isIdentity () const
bool isOrdered () const
MortonOrder (sgpp::datadriven::Dataset *dataset)
void orderDataset ()
void restoreDataset ()
Protected Attributes
sgpp::datadriven::Dataset * _dataset
bool _isIdentity
bool _isOrdered
std::vector< size_t > permutation
Constructor & Destructor Documentation
MortonOrder()
sgpp::datadriven::MortonOrder::MortonOrder (sgpp::datadriven::Dataset * dataset) explicit
References _dataset, _isIdentity, _isOrdered, sgpp::datadriven::Dataset::getData(), and permutation.
Member Function Documentation
getPermutation()
const std::vector< size_t > & sgpp::datadriven::MortonOrder::getPermutation () const
References permutation.
isIdentity()
bool sgpp::datadriven::MortonOrder::isIdentity () const
References _isIdentity.
isOrdered()
bool sgpp::datadriven::MortonOrder::isOrdered () const
References _isOrdered.
orderDataset()
void sgpp::datadriven::MortonOrder::orderDataset ()
References _dataset, _isOrdered, sgpp::datadriven::Dataset::getData(), sgpp::base::DataMatrix::getNcols(), sgpp::datadriven::Dataset::getTargets(), and permutation.
restoreDataset()
void sgpp::datadriven::MortonOrder::restoreDataset ()
References _dataset, _isOrdered, sgpp::datadriven::Dataset::getData(), sgpp::base::DataMatrix::getNcols(), sgpp::datadriven::Dataset::getTargets(), and permutation.
Member Data Documentation
_dataset
sgpp::datadriven::Dataset* sgpp::datadriven::MortonOrder::_dataset protected
Referenced by MortonOrder(), orderDataset(), and restoreDataset().
_isIdentity
bool sgpp::datadriven::MortonOrder::_isIdentity protected
Referenced by isIdentity(), and MortonOrder().
_isOrdered
bool sgpp::datadriven::MortonOrder::_isOrdered protected
Referenced by isOrdered(), MortonOrder(), orderDataset(), and restoreDataset().
permutation
std::vector<size_t> sgpp::datadriven::MortonOrder::permutation protected
Referenced by getPermutation(), MortonOrder(), orderDataset(), and restoreDataset().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/mortonOrder/MortonOrder.hpp
datadriven/src/sgpp/datadriven/tools/mortonOrder/MortonOrder.cpp