SG++-Doxygen-Documentation: sgpp::base::GridPrinterForStretching Class Reference
sgpp::base::GridPrinterForStretching Class Reference
This class implements a utility that allows you to print a grid to file.
#include <GridPrinterForStretching.hpp>
Public Member Functions
GridPrinterForStretching (Grid &SparseGrid)
Std-Constructor.
void printGrid (DataVector &alpha, std::string tFilename, size_t PointsPerDimension) override
Print the grid with its function to a file; front end.
void printGridDomain (DataVector &alpha, std::string tFilename, BoundingBox &GridArea, size_t PointsPerDimension) override
This function is not used for stretching grid printing, use printGridDomainStretching instead.
void printGridDomainStretching (DataVector &alpha, std::string tFilename, Stretching &GridArea, size_t PointsPerDimension)
Print the grid with its function to a file; front end.
void printSparseGrid (DataVector &alpha, std::string tFilename, bool bSurplus) override
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
void printSparseGridExpTransform (DataVector &alpha, std::string tFilename, bool bSurplus) override
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
~GridPrinterForStretching () override
Std-Destructor.
Public Member Functions inherited from sgpp::base::GridPrinter
GridPrinter (Grid &SparseGrid)
Std-Constructor.
virtual void printLevelIndexGrid (std::string tFilename)
Print the grid points in level/index format to a file; front end.
virtual ~GridPrinter ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::GridPrinter
Grid * myGrid
Pointer to the grid Object, which should be printed.
Detailed Description
This class implements a utility that allows you to print a grid to file.
These files can be plotted with gnuplot.
Constructor & Destructor Documentation
GridPrinterForStretching()
sgpp::base::GridPrinterForStretching::GridPrinterForStretching (Grid & SparseGrid) explicit
Std-Constructor.
Parameters
SparseGrid Reference to a Spare Grid, that should be printed
References sgpp::base::GridPrinter::myGrid.
~GridPrinterForStretching()
sgpp::base::GridPrinterForStretching::~GridPrinterForStretching () override
Std-Destructor.
Member Function Documentation
printGrid()
void sgpp::base::GridPrinterForStretching::printGrid (DataVector & alpha, std::string tFilename, size_t PointsPerDimension) override virtual
Print the grid with its function to a file; front end.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absolute path to the file the grid is written into
PointsPerDimension specifies how many functions evaluations in every dimension should be calculated
Reimplemented from sgpp::base::GridPrinter.
References alpha, sgpp::op_factory::createOperationEval(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::Grid::getDimension(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStretching(), sgpp::base::BoundingBox1D::leftBoundary, sgpp::base::GridPrinter::myGrid, and sgpp::base::BoundingBox1D::rightBoundary.
Referenced by sgpp::pde::HeatEquationSolverWithStretching::printGrid().
printGridDomain()
void sgpp::base::GridPrinterForStretching::printGridDomain (DataVector & alpha, std::string tFilename, BoundingBox & GridArea, size_t PointsPerDimension) override virtual
This function is not used for stretching grid printing, use printGridDomainStretching instead.
Reimplemented from sgpp::base::GridPrinter.
printGridDomainStretching()
void sgpp::base::GridPrinterForStretching::printGridDomainStretching (DataVector & alpha, std::string tFilename, Stretching & GridArea, size_t PointsPerDimension)
Print the grid with its function to a file; front end.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absolute path to the file the grid is written into
GridArea The area in which the function should be plotted
PointsPerDimension specifies how many functions evaluations in every dimension should be calculated
References alpha, sgpp::op_factory::createOperationEval(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::Grid::getDimension(), sgpp::base::Grid::getSize(), sgpp::base::BoundingBox1D::leftBoundary, sgpp::base::GridPrinter::myGrid, and sgpp::base::BoundingBox1D::rightBoundary.
Referenced by sgpp::pde::HeatEquationSolverWithStretching::printGridDomainStretching().
printSparseGrid()
void sgpp::base::GridPrinterForStretching::printSparseGrid (DataVector & alpha, std::string tFilename, bool bSurplus) override virtual
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absoulte path to the file the grid is written into
bSurplus specifies whether the surplus (true) or the node basis value (false) is written
Reimplemented from sgpp::base::GridPrinter.
References alpha, sgpp::op_factory::createOperationHierarchisation(), sgpp::base::HashGridStorage::getCoordinates(), sgpp::base::Grid::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStorage(), and sgpp::base::GridPrinter::myGrid.
Referenced by sgpp::pde::HeatEquationSolverWithStretching::printSparseGrid().
printSparseGridExpTransform()
void sgpp::base::GridPrinterForStretching::printSparseGridExpTransform (DataVector & alpha, std::string tFilename, bool bSurplus) override virtual
Prints the Grid Points of the Sparse Grid either with their node basis value or their hierarchical surplus.
The coordinates of the grid points are pushed the exp function. So log transformed grids can be plotted in cartesion coordinates.
Parameters
alpha the coefficients of the grid's ansatzfunctions
tFilename absoulte path to the file the grid is written into
bSurplus specifies whether the surplus (true) or the node basis value (false) is written
Reimplemented from sgpp::base::GridPrinter.
References alpha, sgpp::op_factory::createOperationHierarchisation(), sgpp::base::HashGridStorage::getCoordinates(), sgpp::base::Grid::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::Grid::getSize(), sgpp::base::Grid::getStorage(), and sgpp::base::GridPrinter::myGrid.
Referenced by sgpp::pde::HeatEquationSolverWithStretching::printSparseGridExpTransform().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/GridPrinterForStretching.hpp
base/src/sgpp/base/tools/GridPrinterForStretching.cpp