SG++-Doxygen-Documentation: sgpp::solver::ConjugateGradients Class Reference
sgpp::solver::ConjugateGradients Class Reference
#include <ConjugateGradients.hpp>
Public Member Functions
virtual void calcStarting ()
function that signals the start of the calculation of the CG method (used in python)
virtual void complete ()
function that signals the finish of the cg method (used in python)
ConjugateGradients (size_t imax, double epsilon)
Std-Constructor.
virtual void iterationComplete ()
function that signals that one iteration step of the CG method has been completed (used in python)
virtual void solve (sgpp::base::OperationMatrix &SystemMatrix, sgpp::base::DataVector &alpha, sgpp::base::DataVector &b, bool reuse=false, bool verbose=false, double max_threshold=-1.0)
Pure virtual Function that defines a solve method for an iterative solver.
virtual void starting ()
function that signals the start of the CG method (used in python)
virtual ~ConjugateGradients ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SLESolver
SLESolver (size_t imax, double epsilon)
Std-Constructor.
virtual ~SLESolver ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolver
double getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
double getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (double eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolver (size_t nMaximumIterations, double epsilon)
Std-Constructor.
virtual ~SGSolver ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolver
double myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
double residuum
residuum
Constructor & Destructor Documentation
ConjugateGradients()
ConjugateGradients::ConjugateGradients (size_t imax, double epsilon)
Std-Constructor.
~ConjugateGradients()
ConjugateGradients::~ConjugateGradients () virtual
Std-Destructor.
Member Function Documentation
calcStarting()
void ConjugateGradients::calcStarting () virtual
function that signals the start of the calculation of the CG method (used in python)
Referenced by solve().
complete()
void ConjugateGradients::complete () virtual
function that signals the finish of the cg method (used in python)
Referenced by solve().
iterationComplete()
void ConjugateGradients::iterationComplete () virtual
function that signals that one iteration step of the CG method has been completed (used in python)
Referenced by solve().
solve()
void ConjugateGradients::solve (sgpp::base::OperationMatrix & SystemMatrix, sgpp::base::DataVector & alpha, sgpp::base::DataVector & b, bool reuse = false, bool verbose = false, double max_threshold = -1.0) virtual
Pure virtual Function that defines a solve method for an iterative solver.
Parameters
SystemMatrix reference to an sgpp::base::OperationMatrix Object that implements the matrix vector multiplication
alpha the sparse grid's coefficients which have to be determined
b the right hand side of the system of linear equations
reuse identifies if the alphas, stored in alpha at calling time, should be reused
verbose prints information during execution of the solver
max_threshold additional abort criteria for solver, default value is 10^-9!
Implements sgpp::solver::SLESolver.
References sgpp::base::DataVector::add(), alpha, sgpp::base::DataVector::axpy(), calcStarting(), complete(), sgpp::base::DataVector::dotProduct(), sgpp::base::DataVector::getSize(), iterationComplete(), sgpp::base::OperationMatrix::mult(), sgpp::base::DataVector::mult(), sgpp::solver::SGSolver::myEpsilon, sgpp::solver::SGSolver::nIterations, sgpp::solver::SGSolver::nMaxIterations, sgpp::solver::SGSolver::residuum, sgpp::base::DataVector::setAll(), and starting().
Referenced by sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), main(), main(), sgpp::pde::PoissonEquationSolver::solvePDE(), sgpp::pde::PoissonEquationSolver::storeInnerSolution(), sgpp::datadriven::SparseGridDensityEstimator::train(), sgpp::datadriven::LearnerSGDE::train(), sgpp::datadriven::LearnerSGDE::trainOnline(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), and sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update().
starting()
void ConjugateGradients::starting () virtual
function that signals the start of the CG method (used in python)
Referenced by solve().
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/sle/ConjugateGradients.hpp
solver/src/sgpp/solver/sle/ConjugateGradients.cpp