SG++-Doxygen-Documentation: sgpp::base::WeaklyFundamentalSplineBasis< LT, IT > Class Template Reference
sgpp::base::WeaklyFundamentalSplineBasis< LT, IT > Class Template Reference
weakly fundamental spline basis.
#include <WeaklyFundamentalSplineBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
WeaklyFundamentalSplineBasis ()
Default constructor.
WeaklyFundamentalSplineBasis (size_t degree)
Constructor.
~WeaklyFundamentalSplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
size_t degree
degree of the spline
Detailed Description
template<class LT, class IT>
class sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >
weakly fundamental spline basis.
Constructor & Destructor Documentation
WeaklyFundamentalSplineBasis() [1/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::WeaklyFundamentalSplineBasis () inline
Default constructor.
WeaklyFundamentalSplineBasis() [2/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::WeaklyFundamentalSplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree Spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::degree.
~WeaklyFundamentalSplineBasis()
template<class LT , class IT > sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::~WeaklyFundamentalSplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::degree.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative().
evalDx()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
Spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::degree.
getIntegral()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
degree
template<class LT , class IT > size_t sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::degree protected
degree of the spline
Referenced by sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::getDegree(), and sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::WeaklyFundamentalSplineBasis().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/WeaklyFundamentalSplineBasis.hpp