SG++-Doxygen-Documentation: sgpp::base::MutexType Class Reference
sgpp::base::MutexType Class Reference
Wrapper for OpenMP nested locks.
#include <MutexType.hpp>
Public Member Functions
void lock ()
Lock the MutexType.
MutexType ()
Constructor.
MutexType (const MutexType &other)
Custom copy constructor to prevent copying the lock.
MutexType & operator= (const MutexType &other)
Custom assignment operator to prevent copying the lock.
void unlock ()
Unlock the MutexType.
~MutexType ()
Destructor.
Protected Attributes
omp_nest_lock_t _lock
OpenMP lock.
Detailed Description
Wrapper for OpenMP nested locks.
Once locked, other threads block when trying to lock the same MutexType. However, the MutexType can be locked multiple times by the same thread without blocking. In this case, it has to be unlocked the same number of times to let the other threads continuing execution.
Adopted from http://bisqwit.iki.fi/story/howto/openmp/#Locks.
Constructor & Destructor Documentation
MutexType() [1/2]
sgpp::base::MutexType::MutexType () inline
Constructor.
References _lock.
MutexType() [2/2]
sgpp::base::MutexType::MutexType (const MutexType & other) inline
Custom copy constructor to prevent copying the lock.
Parameters
other object to be copied
References _lock.
~MutexType()
sgpp::base::MutexType::~MutexType () inline
Destructor.
References _lock.
Member Function Documentation
lock()
void sgpp::base::MutexType::lock () inline
Lock the MutexType.
References _lock.
Referenced by sgpp::optimization::FuzzyExtensionPrinciple::apply(), sgpp::base::ScopedLock::lockAgain(), sgpp::optimization::optimizer::MultiStart::optimize(), and sgpp::base::ScopedLock::ScopedLock().
operator=()
MutexType & sgpp::base::MutexType::operator= (const MutexType & other) inline
Custom assignment operator to prevent copying the lock.
Parameters
other object to be assigned to
Returns
*this
unlock()
void sgpp::base::MutexType::unlock () inline
Unlock the MutexType.
References _lock.
Referenced by sgpp::optimization::FuzzyExtensionPrinciple::apply(), sgpp::optimization::optimizer::MultiStart::optimize(), and sgpp::base::ScopedLock::unlock().
Member Data Documentation
_lock
omp_nest_lock_t sgpp::base::MutexType::_lock protected
OpenMP lock.
Referenced by lock(), MutexType(), MutexType(), unlock(), and ~MutexType().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/MutexType.hpp