SG++-Doxygen-Documentation: sgpp::base::SGppStopwatch Class Reference
sgpp::base::SGppStopwatch Class Reference
OS-independent version of a stop watch (using std::chrono).
#include <SGppStopwatch.hpp>
Public Member Functions
SGppStopwatch ()
Constructor.
void start ()
Starts the stop watch.
double stop ()
Stops the stop watch.
~SGppStopwatch ()
Destructor.
Protected Attributes
std::chrono::time_point< std::chrono::high_resolution_clock > start_time
Detailed Description
OS-independent version of a stop watch (using std::chrono).
Part of SGpp, so you can easily calculate the needed time of SGpp computations with a high precision
Constructor & Destructor Documentation
SGppStopwatch()
sgpp::base::SGppStopwatch::SGppStopwatch ()
Constructor.
Resets the stop watch.
~SGppStopwatch()
sgpp::base::SGppStopwatch::~SGppStopwatch ()
Destructor.
Member Function Documentation
start()
void sgpp::base::SGppStopwatch::start ()
Starts the stop watch.
References start_time.
Referenced by sgpp::datadriven::SystemMatrixDensityRatioEstimation::generateb(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::generateb(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::mult(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::mult(), sgpp::datadriven::OperationMultiEvalCuda::mult(), sgpp::datadriven::OperationMultiEvalHPX::mult(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::mult(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult(), sgpp::datadriven::OperationMultiEvalCuda::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::multTranspose(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose(), sgpp::datadriven::OperationMultiEvalHPX::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalCuda::multTransposeFMA(), sgpp::pde::HeatEquationSolver::solveCrankNicolson(), sgpp::pde::HeatEquationSolverWithStretching::solveCrankNicolson(), sgpp::pde::HeatEquationSolver::solveExplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveExplicitEuler(), sgpp::pde::HeatEquationSolver::solveImplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveImplicitEuler(), sgpp::pde::PoissonEquationSolver::solvePDE(), sgpp::pde::PoissonEquationSolver::storeInnerRHS(), sgpp::pde::HeatEquationSolver::storeInnerRHS(), sgpp::pde::HeatEquationSolver::storeInnerSolution(), sgpp::datadriven::LearnerLeastSquaresIdentity::testRegular(), and sgpp::datadriven::LearnerBaseSP::train().
stop()
double sgpp::base::SGppStopwatch::stop ()
Stops the stop watch.
Returns
elapsed time since the last call to start in seconds
References start_time.
Referenced by sgpp::datadriven::SystemMatrixDensityRatioEstimation::generateb(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::generateb(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::mult(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::mult(), sgpp::datadriven::OperationMultiEvalCuda::mult(), sgpp::datadriven::OperationMultiEvalHPX::mult(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::mult(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult(), sgpp::datadriven::OperationMultiEvalCuda::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::multTranspose(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose(), sgpp::datadriven::OperationMultiEvalHPX::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalCuda::multTransposeFMA(), sgpp::base::Printer::printStatusEnd(), sgpp::pde::HeatEquationSolver::solveCrankNicolson(), sgpp::pde::HeatEquationSolverWithStretching::solveCrankNicolson(), sgpp::pde::HeatEquationSolver::solveExplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveExplicitEuler(), sgpp::pde::HeatEquationSolver::solveImplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveImplicitEuler(), sgpp::pde::PoissonEquationSolver::solvePDE(), sgpp::pde::PoissonEquationSolver::storeInnerRHS(), sgpp::pde::HeatEquationSolver::storeInnerRHS(), sgpp::datadriven::LearnerLeastSquaresIdentity::testRegular(), and sgpp::datadriven::LearnerBaseSP::train().
Member Data Documentation
start_time
std::chrono::time_point<std::chrono::high_resolution_clock> sgpp::base::SGppStopwatch::start_time protected
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/SGppStopwatch.hpp
base/src/sgpp/base/tools/SGppStopwatch.cpp