SG++-Doxygen-Documentation: sgpp::optimization::optimizer::Rprop Class Reference
sgpp::optimization::optimizer::Rprop Class Reference
Rprop method for unconstrained optimization.
#include <Rprop.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getInitialStepSize () const
double getStepSizeDecreaseFactor () const
double getStepSizeIncreaseFactor () const
double getTolerance () const
void optimize () override
Pure virtual method for optimization of the objective function.
Rprop (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, size_t maxItCount=DEFAULT_N, double tolerance=DEFAULT_TOLERANCE, double initialStepSize=DEFAULT_INITIAL_STEP_SIZE, double stepSizeIncreaseFactor=DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor=DEFAULT_STEP_SIZE_DECREASE_FACTOR)
Constructor.
Rprop (const Rprop &other)
Copy constructor.
void setInitialStepSize (double initialStepSize)
void setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
void setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
void setTolerance (double tolerance)
~Rprop () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_INITIAL_STEP_SIZE = 0.01
default initial step size
static constexpr double DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5
default step size decrease factor
static constexpr double DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2
default step size increase factor
static constexpr double DEFAULT_TOLERANCE = 1e-6
default tolerance
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double initialAlpha
initial step size
double rhoAlphaMinus
step size decrease factor
double rhoAlphaPlus
step size increase factor
double theta
tolerance
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Rprop method for unconstrained optimization.
Constructor & Destructor Documentation
Rprop() [1/2]
sgpp::optimization::optimizer::Rprop::Rprop (const base::ScalarFunction & f, const base::ScalarFunctionGradient & fGradient, size_t maxItCount = DEFAULT_N, double tolerance = DEFAULT_TOLERANCE, double initialStepSize = DEFAULT_INITIAL_STEP_SIZE, double stepSizeIncreaseFactor = DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor = DEFAULT_STEP_SIZE_DECREASE_FACTOR)
Constructor.
Parameters
f objective function
fGradient objective function gradient
maxItCount maximal number of function evaluations
tolerance tolerance
initialStepSize initial step size
stepSizeIncreaseFactor step size increase factor
stepSizeDecreaseFactor step size decrease factor
Rprop() [2/2]
sgpp::optimization::optimizer::Rprop::Rprop (const Rprop & other)
Copy constructor.
Parameters
other optimizer to be copied
~Rprop()
sgpp::optimization::optimizer::Rprop::~Rprop () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::Rprop::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getInitialStepSize()
double sgpp::optimization::optimizer::Rprop::getInitialStepSize () const
Returns
initial step size
References initialAlpha.
getStepSizeDecreaseFactor()
double sgpp::optimization::optimizer::Rprop::getStepSizeDecreaseFactor () const
Returns
step size decrease factor
References rhoAlphaMinus.
getStepSizeIncreaseFactor()
double sgpp::optimization::optimizer::Rprop::getStepSizeIncreaseFactor () const
Returns
step size increase factor
References rhoAlphaPlus.
getTolerance()
double sgpp::optimization::optimizer::Rprop::getTolerance () const
Returns
tolerance
References theta.
optimize()
void sgpp::optimization::optimizer::Rprop::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References alpha, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::base::Printer::getInstance(), initialAlpha, sgpp::base::DataVector::l2Norm(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), rhoAlphaMinus, rhoAlphaPlus, sgpp::base::DataVector::sub(), theta, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setInitialStepSize()
void sgpp::optimization::optimizer::Rprop::setInitialStepSize (double initialStepSize)
Parameters
initialStepSize initial step size
References initialAlpha.
setStepSizeDecreaseFactor()
void sgpp::optimization::optimizer::Rprop::setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
Parameters
stepSizeDecreaseFactor step size decrease factor
References rhoAlphaMinus.
setStepSizeIncreaseFactor()
void sgpp::optimization::optimizer::Rprop::setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
Parameters
stepSizeIncreaseFactor step size increase factor
References rhoAlphaPlus.
setTolerance()
void sgpp::optimization::optimizer::Rprop::setTolerance (double tolerance)
Parameters
tolerance tolerance
References theta.
Member Data Documentation
DEFAULT_INITIAL_STEP_SIZE
constexpr double sgpp::optimization::optimizer::Rprop::DEFAULT_INITIAL_STEP_SIZE = 0.01 static constexpr
default initial step size
DEFAULT_STEP_SIZE_DECREASE_FACTOR
constexpr double sgpp::optimization::optimizer::Rprop::DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5 static constexpr
default step size decrease factor
DEFAULT_STEP_SIZE_INCREASE_FACTOR
constexpr double sgpp::optimization::optimizer::Rprop::DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2 static constexpr
default step size increase factor
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::Rprop::DEFAULT_TOLERANCE = 1e-6 static constexpr
default tolerance
initialAlpha
double sgpp::optimization::optimizer::Rprop::initialAlpha protected
initial step size
Referenced by getInitialStepSize(), optimize(), and setInitialStepSize().
rhoAlphaMinus
double sgpp::optimization::optimizer::Rprop::rhoAlphaMinus protected
step size decrease factor
Referenced by getStepSizeDecreaseFactor(), optimize(), and setStepSizeDecreaseFactor().
rhoAlphaPlus
double sgpp::optimization::optimizer::Rprop::rhoAlphaPlus protected
step size increase factor
Referenced by getStepSizeIncreaseFactor(), optimize(), and setStepSizeIncreaseFactor().
theta
double sgpp::optimization::optimizer::Rprop::theta protected
tolerance
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/Rprop.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/Rprop.cpp