SG++-Doxygen-Documentation: sgpp::datadriven::Friedman2Generator Class Reference
sgpp::datadriven::Friedman2Generator Class Reference
#include <DatasetGenerator.hpp>
Public Member Functions
virtual void createData (size_t offset, size_t size, base::DataMatrix &trData, base::DataVector &classes)
virtual size_t getDims ()
Public Member Functions inherited from sgpp::datadriven::DatasetGenerator
virtual double normal (double mean, double stddev)
generate normally distributed random variable see http://de.wikipedia.org/wiki/Box-Muller-Methode uses rand(), make sure to call srand yourself
virtual double uniform (double a, double b)
virtual ~DatasetGenerator ()
Member Function Documentation
createData()
void sgpp::datadriven::Friedman2Generator::createData (size_t offset, size_t size, base::DataMatrix & trData, base::DataVector & classes) virtual
Implements sgpp::datadriven::DatasetGenerator.
References sgpp::base::DataMatrix::get(), M_PI, sgpp::datadriven::DatasetGenerator::normal(), sgpp::base::DataMatrix::normalizeDimension(), sgpp::base::DataMatrix::resize(), sgpp::base::DataVector::set(), sgpp::base::DataMatrix::set(), and sgpp::datadriven::DatasetGenerator::uniform().
getDims()
size_t sgpp::datadriven::Friedman2Generator::getDims () virtual
Implements sgpp::datadriven::DatasetGenerator.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/DatasetGenerator.hpp
datadriven/src/sgpp/datadriven/tools/DatasetGenerator.cpp