SG++-Doxygen-Documentation: sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP Class Reference
sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP Class Reference
This class implements the ParabolicPDESolverSystem for the Heat Equation.
#include <HeatEquationParabolicPDESolverSystemParallelOMP.hpp>
Public Member Functions
virtual void coarsenAndRefine (bool isLastTimestep=false)
virtual void finishTimestep ()
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
virtual sgpp::base::DataVector * generateRHS ()
generates the right hand side of the system
HeatEquationParabolicPDESolverSystemParallelOMP (sgpp::base::Grid &SparseGrid, sgpp::base::DataVector &alpha, double a, double TimestepSize, std::string OperationMode="ExEul")
Std-Constructor.
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Multiplicates a vector with the matrix.
virtual void startTimestep ()
Implements some start jobs of every timestep, e.g.discounting boundaries.
virtual ~HeatEquationParabolicPDESolverSystemParallelOMP ()
Std-Destructor.
Public Member Functions inherited from sgpp::pde::OperationParabolicPDESolverSystemDirichlet
virtual sgpp::base::DataVector * getGridCoefficientsForCG ()
gets a pointer to the sparse grids coefficients used in the CG method to solve one timestep.
OperationParabolicPDESolverSystemDirichlet ()
Constructor.
virtual ~OperationParabolicPDESolverSystemDirichlet ()
Destructor.
Public Member Functions inherited from sgpp::solver::OperationParabolicPDESolverSystem
void abortTimestep ()
aborts the current timestep execution
sgpp::base::Grid * getGrid ()
get the pointer to the underlying grid object
sgpp::base::DataVector * getGridCoefficients ()
gets a pointer to the sparse grids coefficients with evtl.
void getGridCoefficientsForSC (sgpp::base::DataVector &Values)
stores the values of the (dehierarchized) grid in the sgpp::base::DataVector Values used by time step size control methods
sgpp::base::GridStorage * getGridStorage ()
std::string getODESolver ()
Returns the specified ODE solver for this instance.
sgpp::base::GridStorage * getOldGridStorage ()
sgpp::base::GridStorage * getSecondGridStorage ()
size_t getSumGridPointsComplete ()
Returns the number of average grid points for the complete grid.
size_t getSumGridPointsInner ()
Returns the number of average grid points for the inner grid.
OperationParabolicPDESolverSystem ()
Constructor.
void saveAlpha ()
stores the current alpha_complete into alpha_complete_old to be available in the next timestep
void setODESolver (std::string ode)
defines the used ODE Solver for this instance, this is important because the implementation of mult and generateRHS depends on the used ODE solver
void setTimestepSize (double newTimestepSize)
set the size of the new timestep
virtual ~OperationParabolicPDESolverSystem ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
void applyLOperatorComplete (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's system matrix, on complete grid - with boundaries
void applyLOperatorInner (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's system matrix, on inner grid only
void applyMassMatrixComplete (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's mass matrix, on complete grid - with boundaries
void applyMassMatrixInner (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's mass matrix, on inner grid only
Protected Attributes
double a
the heat coefficient
sgpp::base::OperationMatrix * OpLaplaceBound
the Laplace Operation (Stiffness Matrix), on boundary grid
sgpp::base::OperationMatrix * OpLaplaceInner
the Laplace Operation (Stiffness Matrix), on inner grid
sgpp::base::OperationMatrix * OpMassBound
the LTwoDotProduct Operation (Mass Matrix), on boundary grid
sgpp::base::OperationMatrix * OpMassInner
the LTwoDotProduct Operation (Mass Matrix), on inner grid
Protected Attributes inherited from sgpp::pde::OperationParabolicPDESolverSystemDirichlet
sgpp::base::DataVector * alpha_inner
Pointer to the alphas (ansatzfunctions' coefficients; inner points only)
sgpp::base::DirichletUpdateVector * BoundaryUpdate
Routine to modify the boundaries/inner points of the grid.
sgpp::base::DirichletGridConverter * GridConverter
Class that allows a simple conversion between a grid with and a without boundary points.
sgpp::base::Grid * InnerGrid
Pointer to the inner grid object.
Protected Attributes inherited from sgpp::solver::OperationParabolicPDESolverSystem
sgpp::base::DataVector * alpha_complete
Pointer to the alphas (ansatzfunctions' coefficients)
sgpp::base::DataVector * alpha_complete_old
Pointer to the alphas from the last timestep, needed when using variable timestep sizes.
sgpp::base::DataVector * alpha_complete_tmp
Pointer to temporary alphas, needed when using variable timestep sizes.
bool bnewODESolver
checks whether a new ODE solver has been selected after creation
sgpp::base::Grid * BoundGrid
Pointer to the grid object.
size_t numSumGridpointsComplete
Stores number of average gridpoints, complete grid.
size_t numSumGridpointsInner
Stores number of average gridpoints, inner grid.
sgpp::base::GridStorage * oldGridStorage
Pointer to the grid from the last iteration.
sgpp::base::DataVector * rhs
sgpp::base::GridStorage * secondGridStorage
Pointer to the grid from the last aborted iteration.
double TimestepSize
the size of one timestep used in the ODE Solver
double TimestepSize_old
the size of the last timestep
std::string tOperationMode
specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler ImEul for implicit Euler CrNic for Crank Nicolson solver
Detailed Description
This class implements the ParabolicPDESolverSystem for the Heat Equation.
Constructor & Destructor Documentation
HeatEquationParabolicPDESolverSystemParallelOMP()
sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP (sgpp::base::Grid & SparseGrid, sgpp::base::DataVector & alpha, double a, double TimestepSize, std::string OperationMode = "ExEul")
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
alpha the sparse grid's coefficients
a the heat coefficient
TimestepSize the size of one timestep used in the ODE Solver
OperationMode specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler, ImEul for implicit Euler, CrNic for Crank Nicolson solver
References a, alpha, sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::BoundaryUpdate, sgpp::solver::OperationParabolicPDESolverSystem::BoundGrid, sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::op_factory::createOperationLaplace(), sgpp::op_factory::createOperationLTwoDotProduct(), sgpp::base::Grid::getStorage(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, OpLaplaceBound, OpLaplaceInner, OpMassBound, OpMassInner, sgpp::solver::OperationParabolicPDESolverSystem::rhs, sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize, and sgpp::solver::OperationParabolicPDESolverSystem::tOperationMode.
~HeatEquationParabolicPDESolverSystemParallelOMP()
sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::~HeatEquationParabolicPDESolverSystemParallelOMP () virtual
Std-Destructor.
References sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::BoundaryUpdate, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, OpLaplaceBound, OpLaplaceInner, OpMassBound, OpMassInner, and sgpp::solver::OperationParabolicPDESolverSystem::rhs.
Member Function Documentation
applyLOperatorComplete()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's system matrix, on complete grid - with boundaries
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
discuss methods in order to avoid this cast
Implements sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References a, sgpp::base::DataVector::add(), alpha, sgpp::base::DataVector::axpy(), sgpp::base::HashGridStorage::getAlgorithmicDimensions(), sgpp::base::DataVector::getSize(), sgpp::base::Grid::getStorage(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, OpLaplaceBound, and sgpp::base::DataVector::setAll().
Referenced by generateRHS().
applyLOperatorInner()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's system matrix, on inner grid only
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
discuss methods in order to avoid this cast
Implements sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References a, sgpp::base::DataVector::add(), alpha, sgpp::base::DataVector::axpy(), sgpp::base::HashGridStorage::getAlgorithmicDimensions(), sgpp::base::DataVector::getSize(), sgpp::base::Grid::getStorage(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, OpLaplaceInner, and sgpp::base::DataVector::setAll().
Referenced by mult().
applyMassMatrixComplete()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixComplete (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's mass matrix, on complete grid - with boundaries
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
Implements sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References sgpp::base::DataVector::add(), alpha, sgpp::base::DataVector::getSize(), OpMassBound, and sgpp::base::DataVector::setAll().
Referenced by generateRHS().
applyMassMatrixInner()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixInner (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's mass matrix, on inner grid only
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
Implements sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References sgpp::base::DataVector::add(), alpha, sgpp::base::DataVector::getSize(), OpMassInner, and sgpp::base::DataVector::setAll().
Referenced by mult().
coarsenAndRefine()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::coarsenAndRefine (bool isLastTimestep = false) virtual
Implements sgpp::solver::OperationParabolicPDESolverSystem.
finishTimestep()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::finishTimestep () virtual
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
some boundary adjustments.
Implements sgpp::solver::OperationParabolicPDESolverSystem.
References sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, and sgpp::base::DirichletGridConverter::updateBoundaryCoefs().
generateRHS()
sgpp::base::DataVector * sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS () virtual
generates the right hand side of the system
Returns
returns the rhs
Reimplemented from sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References sgpp::base::DataVector::add(), sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, applyLOperatorComplete(), applyMassMatrixComplete(), sgpp::base::DataVector::axpy(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::BoundaryUpdate, sgpp::base::DirichletGridConverter::calcInnerCoefs(), sgpp::base::DataVector::getSize(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, sgpp::solver::OperationParabolicPDESolverSystem::rhs, sgpp::base::DataVector::setAll(), sgpp::base::DirichletUpdateVector::setInnerPointsToZero(), startTimestep(), sgpp::base::DataVector::sub(), sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize, and sgpp::solver::OperationParabolicPDESolverSystem::tOperationMode.
mult()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Multiplicates a vector with the matrix.
Parameters
alpha sgpp::base::DataVector that contains the ansatzfunctions' coefficients
result sgpp::base::DataVector into which the result of the space discretization operation is stored
Reimplemented from sgpp::pde::OperationParabolicPDESolverSystemDirichlet.
References sgpp::base::DataVector::add(), alpha, applyLOperatorInner(), applyMassMatrixInner(), sgpp::base::DataVector::axpy(), sgpp::base::DataVector::getSize(), sgpp::base::DataVector::setAll(), sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize, and sgpp::solver::OperationParabolicPDESolverSystem::tOperationMode.
startTimestep()
void sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::startTimestep () virtual
Implements some start jobs of every timestep, e.g.discounting boundaries.
Implements sgpp::solver::OperationParabolicPDESolverSystem.
Referenced by generateRHS().
Member Data Documentation
a
double sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::a protected
the heat coefficient
Referenced by applyLOperatorComplete(), applyLOperatorInner(), and HeatEquationParabolicPDESolverSystemParallelOMP().
OpLaplaceBound
sgpp::base::OperationMatrix* sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::OpLaplaceBound protected
the Laplace Operation (Stiffness Matrix), on boundary grid
Referenced by applyLOperatorComplete(), HeatEquationParabolicPDESolverSystemParallelOMP(), and ~HeatEquationParabolicPDESolverSystemParallelOMP().
OpLaplaceInner
sgpp::base::OperationMatrix* sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::OpLaplaceInner protected
the Laplace Operation (Stiffness Matrix), on inner grid
Referenced by applyLOperatorInner(), HeatEquationParabolicPDESolverSystemParallelOMP(), and ~HeatEquationParabolicPDESolverSystemParallelOMP().
OpMassBound
sgpp::base::OperationMatrix* sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::OpMassBound protected
the LTwoDotProduct Operation (Mass Matrix), on boundary grid
Referenced by applyMassMatrixComplete(), HeatEquationParabolicPDESolverSystemParallelOMP(), and ~HeatEquationParabolicPDESolverSystemParallelOMP().
OpMassInner
sgpp::base::OperationMatrix* sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::OpMassInner protected
the LTwoDotProduct Operation (Mass Matrix), on inner grid
Referenced by applyMassMatrixInner(), HeatEquationParabolicPDESolverSystemParallelOMP(), and ~HeatEquationParabolicPDESolverSystemParallelOMP().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/algorithm/HeatEquationParabolicPDESolverSystemParallelOMP.hpp
pde/src/sgpp/pde/algorithm/HeatEquationParabolicPDESolverSystemParallelOMP.cpp