SG++-Doxygen-Documentation: sgpp::optimization::test_problems::UnconstrainedTestProblem Class Reference
sgpp::optimization::test_problems::UnconstrainedTestProblem Class Reference abstract
Base class for analytical, unconstrained test problems.
#include <UnconstrainedTestProblem.hpp>
Public Member Functions
void generateDisplacement ()
Generate normally distributed pseudorandom displacement with default standard deviation.
void generateDisplacement (double stdDev)
Generate normally distributed pseudorandom displacement.
const base::DataVector & getDisplacement () const
virtual TestScalarFunction & getObjectiveFunction ()=0
double getOptimalPoint (base::DataVector &x)
Returns the minimal point of the displaced function.
virtual double getOptimalPointUndisplaced (base::DataVector &x)=0
Pure virtual method returning the minimal point (or one of the minimal points, if there are multiple of them) of the test function.
void setDisplacement (const base::DataVector &displacement)
Sets the displacement vector.
UnconstrainedTestProblem (size_t d)
Constructor.
virtual ~UnconstrainedTestProblem ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_STANDARD_DEVIATION = 0.01
default standard deviation for the displacement vector
Protected Member Functions
virtual bool isDisplacementFeasible ()
Checks if the current displacement is ok for the specific objective function.
Protected Attributes
size_t d
number of parameters
base::DataVector displacement
displacement vector
Detailed Description
Base class for analytical, unconstrained test problems.
This class essentially manages an objective function, generates a Gaussian displacement vector, and contains the location of the optimal point.
Constructor & Destructor Documentation
UnconstrainedTestProblem()
sgpp::optimization::test_problems::UnconstrainedTestProblem::UnconstrainedTestProblem (size_t d) explicit
Constructor.
The displacement is set to all zeros, so to displace the function call generateDisplacement() afterwards.
Parameters
d dimension of the domain
~UnconstrainedTestProblem()
sgpp::optimization::test_problems::UnconstrainedTestProblem::~UnconstrainedTestProblem () virtual
Destructor.
Member Function Documentation
generateDisplacement() [1/2]
void sgpp::optimization::test_problems::UnconstrainedTestProblem::generateDisplacement ()
Generate normally distributed pseudorandom displacement with default standard deviation.
This method also sets the new displacement in the objective function.
References DEFAULT_STANDARD_DEVIATION, and generateDisplacement().
Referenced by generateDisplacement().
generateDisplacement() [2/2]
void sgpp::optimization::test_problems::UnconstrainedTestProblem::generateDisplacement (double stdDev)
Generate normally distributed pseudorandom displacement.
This method also sets the new displacement in the objective function.
Parameters
stdDev standard deviation of the displacement coordinates
References d, displacement, sgpp::base::RandomNumberGenerator::getGaussianRN(), sgpp::base::RandomNumberGenerator::getInstance(), getObjectiveFunction(), isDisplacementFeasible(), and sgpp::optimization::test_problems::TestScalarFunction::setDisplacement().
getDisplacement()
const base::DataVector & sgpp::optimization::test_problems::UnconstrainedTestProblem::getDisplacement () const
Returns
currently used displacement
References displacement.
getObjectiveFunction()
virtual TestScalarFunction & sgpp::optimization::test_problems::UnconstrainedTestProblem::getObjectiveFunction () pure virtual
Returns
objective function of the test problem
Implemented in sgpp::optimization::test_problems::AbsoluteValue, sgpp::optimization::test_problems::Ackley, sgpp::optimization::test_problems::Alpine02, sgpp::optimization::test_problems::Beale, sgpp::optimization::test_problems::Branin01, sgpp::optimization::test_problems::Branin02, sgpp::optimization::test_problems::BubbleWrap, sgpp::optimization::test_problems::EasomYang, sgpp::optimization::test_problems::Eggholder, sgpp::optimization::test_problems::GoldsteinPrice, sgpp::optimization::test_problems::Griewank, sgpp::optimization::test_problems::Hartman3, sgpp::optimization::test_problems::Hartman6, sgpp::optimization::test_problems::Himmelblau, sgpp::optimization::test_problems::HoelderTable, sgpp::optimization::test_problems::IncreasingPower, sgpp::optimization::test_problems::Michalewicz, sgpp::optimization::test_problems::Mladineo, sgpp::optimization::test_problems::Perm, sgpp::optimization::test_problems::Rastrigin, sgpp::optimization::test_problems::Rosenbrock, sgpp::optimization::test_problems::Schwefel06, sgpp::optimization::test_problems::Schwefel22, sgpp::optimization::test_problems::Schwefel26, sgpp::optimization::test_problems::SHCB, sgpp::optimization::test_problems::Sphere, and sgpp::optimization::test_problems::TremblingParabola.
Referenced by generateDisplacement(), and setDisplacement().
getOptimalPoint()
double sgpp::optimization::test_problems::UnconstrainedTestProblem::getOptimalPoint (base::DataVector & x)
Returns the minimal point of the displaced function.
Parameters
[out] x reverse displaced minimal point \(\vec{x}_\opt - \vec{d}\)
Returns
minimal function value \(f(\vec{x}_\opt)\)
References displacement, getOptimalPointUndisplaced(), and sgpp::base::DataVector::sub().
Referenced by isDisplacementFeasible().
getOptimalPointUndisplaced()
virtual double sgpp::optimization::test_problems::UnconstrainedTestProblem::getOptimalPointUndisplaced (base::DataVector & x) pure virtual
Pure virtual method returning the minimal point (or one of the minimal points, if there are multiple of them) of the test function.
Parameters
[out] x minimal point \(\vec{x}_\opt\)
Returns
minimal function value \(f(\vec{x}_\opt)\)
Implemented in sgpp::optimization::test_problems::AbsoluteValue, sgpp::optimization::test_problems::Ackley, sgpp::optimization::test_problems::Alpine02, sgpp::optimization::test_problems::Beale, sgpp::optimization::test_problems::Branin01, sgpp::optimization::test_problems::Branin02, sgpp::optimization::test_problems::BubbleWrap, sgpp::optimization::test_problems::EasomYang, sgpp::optimization::test_problems::Eggholder, sgpp::optimization::test_problems::GoldsteinPrice, sgpp::optimization::test_problems::Griewank, sgpp::optimization::test_problems::Hartman3, sgpp::optimization::test_problems::Hartman6, sgpp::optimization::test_problems::Himmelblau, sgpp::optimization::test_problems::HoelderTable, sgpp::optimization::test_problems::IncreasingPower, sgpp::optimization::test_problems::Michalewicz, sgpp::optimization::test_problems::Mladineo, sgpp::optimization::test_problems::Perm, sgpp::optimization::test_problems::Rastrigin, sgpp::optimization::test_problems::Rosenbrock, sgpp::optimization::test_problems::Schwefel06, sgpp::optimization::test_problems::Schwefel22, sgpp::optimization::test_problems::Schwefel26, sgpp::optimization::test_problems::SHCB, sgpp::optimization::test_problems::Sphere, and sgpp::optimization::test_problems::TremblingParabola.
Referenced by getOptimalPoint().
isDisplacementFeasible()
bool sgpp::optimization::test_problems::UnconstrainedTestProblem::isDisplacementFeasible () protected virtual
Checks if the current displacement is ok for the specific objective function.
An infeasible displacement would be one for which one of the following happens:
The optimal point is displaced out of \([0, 1]^d\).
Singularities, where the function is not well-defined, are displaced into \([0, 1]^d\).
This function is called by generateDisplacement to check the feasibility of the new displacement. Only 1. will be checked by default. For additional constraints on the displacement, override this function.
Returns
whether the current displacement is feasible
Reimplemented in sgpp::optimization::test_problems::Eggholder, sgpp::optimization::test_problems::HoelderTable, and sgpp::optimization::test_problems::Mladineo.
References d, and getOptimalPoint().
Referenced by generateDisplacement(), sgpp::optimization::test_problems::Eggholder::isDisplacementFeasible(), sgpp::optimization::test_problems::HoelderTable::isDisplacementFeasible(), and sgpp::optimization::test_problems::Mladineo::isDisplacementFeasible().
setDisplacement()
void sgpp::optimization::test_problems::UnconstrainedTestProblem::setDisplacement (const base::DataVector & displacement)
Sets the displacement vector.
This method also sets the new displacement in the objective function.
Parameters
displacement currently used displacement
References displacement, getObjectiveFunction(), and sgpp::optimization::test_problems::TestScalarFunction::setDisplacement().
Member Data Documentation
d
size_t sgpp::optimization::test_problems::UnconstrainedTestProblem::d protected
number of parameters
Referenced by generateDisplacement(), sgpp::optimization::test_problems::AbsoluteValue::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Ackley::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Alpine02::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::BubbleWrap::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::EasomYang::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Griewank::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::IncreasingPower::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Perm::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Rastrigin::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Rosenbrock::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Schwefel22::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Schwefel26::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Sphere::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::TremblingParabola::getOptimalPointUndisplaced(), and isDisplacementFeasible().
DEFAULT_STANDARD_DEVIATION
constexpr double sgpp::optimization::test_problems::UnconstrainedTestProblem::DEFAULT_STANDARD_DEVIATION = 0.01 static constexpr
default standard deviation for the displacement vector
Referenced by generateDisplacement().
displacement
base::DataVector sgpp::optimization::test_problems::UnconstrainedTestProblem::displacement protected
displacement vector
Referenced by generateDisplacement(), getDisplacement(), getOptimalPoint(), sgpp::optimization::test_problems::Eggholder::isDisplacementFeasible(), sgpp::optimization::test_problems::HoelderTable::isDisplacementFeasible(), sgpp::optimization::test_problems::Mladineo::isDisplacementFeasible(), and setDisplacement().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/unconstrained/UnconstrainedTestProblem.hpp
optimization/src/sgpp/optimization/test_problems/unconstrained/UnconstrainedTestProblem.cpp