SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureModBspline Class Reference
sgpp::base::OperationQuadratureModBspline Class Reference
Quadrature on sparse grid, polynomial grid without boundaries.
#include <OperationQuadratureModBspline.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for Bspline basis functions of max.
OperationQuadratureModBspline (GridStorage &storage, size_t degree)
Constructor of OperationQuadratureBspline.
~OperationQuadratureModBspline () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SBsplineModifiedBase base
Bspline Boundary Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, polynomial grid without boundaries.
Constructor & Destructor Documentation
OperationQuadratureModBspline()
sgpp::base::OperationQuadratureModBspline::OperationQuadratureModBspline (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadratureBspline.
Parameters
storage Pointer to the grid's GridStorage object
degree the polynom's max. degree
~OperationQuadratureModBspline()
sgpp::base::OperationQuadratureModBspline::~OperationQuadratureModBspline () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureModBspline::doQuadrature (DataVector & alpha) override virtual
Quadrature for Bspline basis functions of max.
degree 7
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BsplineModifiedBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SBsplineModifiedBase sgpp::base::OperationQuadratureModBspline::base protected
Bspline Boundary Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadratureModBspline::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureModBspline.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureModBspline.cpp