SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensityMarginalizeKDE Class Reference
sgpp::datadriven::OperationDensityMarginalizeKDE Class Reference
Marginalize Probability Density Function.
#include <OperationDensityMarginalizeKDE.hpp>
Public Member Functions
void doMarginalize (size_t mdim, datadriven::KernelDensityEstimator &marginalizedKDE)
Marginalizes (Density) functions in dimension mdim.
void doMarginalize (std::vector< size_t > &mdims, datadriven::KernelDensityEstimator &marginalizedKDE)
Marginalizes (Density) functions in all dimensions mdims.
void margToDimX (size_t mdim, datadriven::KernelDensityEstimator &marginalizedKDE)
Keep applying marginalizes to (Density) Functions, until it's reduced to 1 dimension (dim_x)
void margToDimXs (std::vector< size_t > &mdims, datadriven::KernelDensityEstimator &marginalizedKDE)
Keep applying marginalizes to (Density) Functions, until it's reduced to the dimensions in mdims.
OperationDensityMarginalizeKDE (datadriven::KernelDensityEstimator &kde)
virtual ~OperationDensityMarginalizeKDE ()
Detailed Description
Marginalize Probability Density Function.
Constructor & Destructor Documentation
OperationDensityMarginalizeKDE()
sgpp::datadriven::OperationDensityMarginalizeKDE::OperationDensityMarginalizeKDE (datadriven::KernelDensityEstimator & kde) explicit
~OperationDensityMarginalizeKDE()
sgpp::datadriven::OperationDensityMarginalizeKDE::~OperationDensityMarginalizeKDE () virtual
Member Function Documentation
doMarginalize() [1/2]
void sgpp::datadriven::OperationDensityMarginalizeKDE::doMarginalize (size_t mdim, datadriven::KernelDensityEstimator & marginalizedKDE)
Marginalizes (Density) functions in dimension mdim.
Parameters
mdim marginalize in dimension mdim
marginalizedKDE marginalized kernel density
References sgpp::datadriven::KernelDensityEstimator::initialize().
doMarginalize() [2/2]
void sgpp::datadriven::OperationDensityMarginalizeKDE::doMarginalize (std::vector< size_t > & mdims, datadriven::KernelDensityEstimator & marginalizedKDE)
Marginalizes (Density) functions in all dimensions mdims.
Parameters
mdims marginalized in all dimensions in mdims
marginalizedKDE marginalized kernel density
References sgpp::datadriven::KernelDensityEstimator::initialize().
margToDimX()
void sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimX (size_t mdim, datadriven::KernelDensityEstimator & marginalizedKDE)
Keep applying marginalizes to (Density) Functions, until it's reduced to 1 dimension (dim_x)
Parameters
mdim Target dimension, all other dimensions will be marginalized
marginalizedKDE result of marginalization
References sgpp::datadriven::KernelDensityEstimator::initialize().
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX().
margToDimXs()
void sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimXs (std::vector< size_t > & mdims, datadriven::KernelDensityEstimator & marginalizedKDE)
Keep applying marginalizes to (Density) Functions, until it's reduced to the dimensions in mdims.
Parameters
mdims Target dimensions, all other dimensions will be marginalized
marginalizedKDE result of marginalization
References sgpp::datadriven::KernelDensityEstimator::initialize().
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::doConditional().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMarginalizeKDE.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMarginalizeKDE.cpp