SG++-Doxygen-Documentation: sgpp::base::AlgorithmMultipleEvaluation< BASIS > Class Template Reference
sgpp::base::AlgorithmMultipleEvaluation< BASIS > Class Template Reference
Abstract implementation for multiple function evaluations.
#include <AlgorithmMultipleEvaluation.hpp>
Public Member Functions
void mult (GridStorage &storage, BASIS &basis, DataVector &source, DataMatrix &x, DataVector &result)
Performs a mass evaluation.
void mult_transpose (GridStorage &storage, BASIS &basis, DataVector &source, DataMatrix &x, DataVector &result)
Performs a transposed mass evaluation.
Detailed Description
template<class BASIS>
class sgpp::base::AlgorithmMultipleEvaluation< BASIS >
Abstract implementation for multiple function evaluations.
In Data Mining to operators are needed: mass evaluation and transposed evaluation, referenced in literature as matrix vector products with matrices B^T (mass evaluation) and B (transposed evaluation).
If there are \(N\) basis functions \(\varphi(\vec{x})\) and \(m\) data points, then B is a (mxN) matrix, with
\[ (B)_{j,i} = \varphi_i(x_j). \]
Member Function Documentation
mult()
template<class BASIS > void sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult (GridStorage & storage, BASIS & basis, DataVector & source, DataMatrix & x, DataVector & result) inline
Performs a mass evaluation.
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::base::OperationMultipleEvalLinear::mult().
mult_transpose()
template<class BASIS > void sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose (GridStorage & storage, BASIS & basis, DataVector & source, DataMatrix & x, DataVector & result) inline
Performs a transposed mass evaluation.
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::base::DataVector::add(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::base::OperationMultipleEvalLinear::multTranspose().
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/AlgorithmMultipleEvaluation.hpp