SG++-Doxygen-Documentation: sgpp::datadriven::RosenblattTransformation Class Reference
sgpp::datadriven::RosenblattTransformation Class Reference
#include <RosenblattTransformation.hpp>
Public Member Functions
LearnerSGDE createSGDELearner (size_t dim, RosenblattTransformationConfig config)
Helper function It configures and creates a SGDE learner with meaningful parameters.
Dataset * doInverseTransformation (Dataset *dataset) override
Wrapper for Rosenblatt inverse transformation.
Dataset * doTransformation (Dataset *dataset) override
Wrapper for Rosenblatt transformation.
void initialize (Dataset *dataset, DataTransformationConfig config) override
Initializes a transformation by approximating probability density function (PDF), calculates grid and alpha for numSamples samples of a dataset.
RosenblattTransformation ()
Default constructor.
Public Member Functions inherited from sgpp::datadriven::DataTransformation
DataTransformation ()=default
Default constructor.
virtual ~DataTransformation ()=default
Virtual destructor.
Constructor & Destructor Documentation
RosenblattTransformation()
sgpp::datadriven::RosenblattTransformation::RosenblattTransformation ()
Default constructor.
Member Function Documentation
createSGDELearner()
sgpp::datadriven::LearnerSGDE sgpp::datadriven::RosenblattTransformation::createSGDELearner (size_t dim, RosenblattTransformationConfig config)
Helper function It configures and creates a SGDE learner with meaningful parameters.
References adaptivityConfig, sgpp::solver::CG, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::CrossvalidationConfiguration::enable_, sgpp::solver::SLESolverConfiguration::eps_, sgpp::datadriven::RosenblattTransformationConfig::gridLevel_, sgpp::datadriven::Laplace, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::RosenblattTransformationConfig::solverEps_, sgpp::datadriven::RosenblattTransformationConfig::solverMaxIterations_, sgpp::datadriven::RosenblattTransformationConfig::solverThreshold_, sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::GeneralGridConfiguration::type_, sgpp::datadriven::RegularizationConfiguration::type_, and sgpp::solver::SLESolverConfiguration::type_.
Referenced by initialize().
doInverseTransformation()
Dataset * sgpp::datadriven::RosenblattTransformation::doInverseTransformation (Dataset * dataset) override virtual
Wrapper for Rosenblatt inverse transformation.
Can be called from an initialized DataTransformation (with DataTransformationType::ROSENBLATT)
Parameters
dataset pointer to the dataset to be Rosenblatt inverse transformed
Returns
pointer to the backwards transformed dataset
Implements sgpp::datadriven::DataTransformation.
References sgpp::op_factory::createOperationInverseRosenblattTransformation(), dataset, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), and sgpp::datadriven::Dataset::getNumberInstances().
doTransformation()
Dataset * sgpp::datadriven::RosenblattTransformation::doTransformation (Dataset * dataset) override virtual
Wrapper for Rosenblatt transformation.
Can be called from an initialized DataTransformation (with DataTransformationType::ROSENBLATT)
Parameters
dataset pointer to the dataset to be Rosenblatt transformed
Returns
pointer to the transformed dataset
Implements sgpp::datadriven::DataTransformation.
References sgpp::op_factory::createOperationRosenblattTransformation(), dataset, sgpp::datadriven::OperationRosenblattTransformation::doTransformation(), sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), and sgpp::datadriven::Dataset::getNumberInstances().
initialize()
void sgpp::datadriven::RosenblattTransformation::initialize (Dataset * dataset, DataTransformationConfig config) override virtual
Initializes a transformation by approximating probability density function (PDF), calculates grid and alpha for numSamples samples of a dataset.
Parameters
dataset pointer to the dataset to be initialized
config configuration containing parameters for initalization
Implements sgpp::datadriven::DataTransformation.
References createSGDELearner(), dataset, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::base::DataMatrix::getRow(), sgpp::datadriven::LearnerSGDE::getSharedGrid(), sgpp::datadriven::LearnerSGDE::getSharedSurpluses(), sgpp::datadriven::LearnerSGDE::initialize(), sgpp::datadriven::RosenblattTransformationConfig::numSamples_, sgpp::datadriven::DataTransformationConfig::rosenblattConfig_, and sgpp::datadriven::LearnerSGDE::train().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/RosenblattTransformation.hpp
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/RosenblattTransformation.cpp