SG++-Doxygen-Documentation: sgpp::base::OCLOperationConfiguration Class Reference
sgpp::base::OCLOperationConfiguration Class Reference
#include <OCLOperationConfiguration.hpp>
Public Member Functions
OperationConfiguration * clone () override
std::vector< std::reference_wrapper< json::Node > > getAllDeviceNodes ()
OCLOperationConfiguration ()
OCLOperationConfiguration (const std::string &fileName)
Public Member Functions inherited from sgpp::base::OperationConfiguration
OperationConfiguration ()
OperationConfiguration (const std::string &fileName)
Public Member Functions inherited from json::JSON
void clear ()
void deserialize (std::string content)
void deserializeFromString (const std::string &content)
JSON ()
JSON (const JSON &original)
JSON (const std::string &fileName)
DictNode & operator= (const DictNode &right)
JSON & operator= (const JSON &original)
Node & operator= (const Node &right) override
void serialize (const std::string &outFileName)
void serialize (std::ostream &outFile, size_t indentWidth) override
Public Member Functions inherited from json::DictNode
void addAttribute (const std::string &name, std::unique_ptr< Node > node) override
Node & addDictAttr (const std::string &name) override
Node & addIDAttr (const std::string &name, const bool &value) override
Node & addIDAttr (const std::string &name, const char *value) override
Node & addIDAttr (const std::string &name, const double &value) override
Node & addIDAttr (const std::string &name, const int64_t &value) override
Node & addIDAttr (const std::string &name, const std::string &value) override
Node & addIDAttr (const std::string &name, const uint64_t &value) override
Node & addListAttr (const std::string &name) override
Node & addTextAttr (const std::string &name, const std::string &value) override
bool contains (const std::string &key) override
DictNode ()
DictNode (const DictNode &original)
std::unique_ptr< Node > erase (Node &node) override
std::vector< std::string > & keys () override
DictNode & operator= (const DictNode &right)
Node & operator[] (const std::string &key) override
void parse (std::vector< Token > &stream) override
void parseAttributes (std::vector< Token > &stream)
std::unique_ptr< Node > removeAttribute (const std::string name) override
Node & replaceDictAttr (const std::string &name) override
Node & replaceIDAttr (const std::string &name, const bool &value) override
Node & replaceIDAttr (const std::string &name, const char *value) override
Node & replaceIDAttr (const std::string &name, const double &value) override
Node & replaceIDAttr (const std::string &name, const int64_t &value) override
Node & replaceIDAttr (const std::string &name, const std::string &value) override
Node & replaceIDAttr (const std::string &name, const uint64_t &value) override
Node & replaceListAttr (const std::string &name) override
Node & replaceTextAttr (const std::string &name, const std::string &value) override
size_t size () override
Public Member Functions inherited from json::Node
virtual Node & addDictValue ()
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListValue ()
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual std::unique_ptr< Node > erase ()
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const size_t index)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual ~Node ()=default
Static Public Member Functions
static std::unique_ptr< OCLOperationConfiguration > fromString (std::string &parametersString)
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Protected Attributes inherited from json::DictNode
std::map< std::string, std::unique_ptr< Node > > attributes
std::vector< std::string > keyOrder
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
OCLOperationConfiguration() [1/2]
sgpp::base::OCLOperationConfiguration::OCLOperationConfiguration ()
Referenced by clone().
OCLOperationConfiguration() [2/2]
sgpp::base::OCLOperationConfiguration::OCLOperationConfiguration (const std::string & fileName) explicit
Member Function Documentation
clone()
OperationConfiguration * sgpp::base::OCLOperationConfiguration::clone () override virtual
Reimplemented from sgpp::base::OperationConfiguration.
References OCLOperationConfiguration().
fromString()
std::unique_ptr< OCLOperationConfiguration > sgpp::base::OCLOperationConfiguration::fromString (std::string & parametersString) static
getAllDeviceNodes()
std::vector< std::reference_wrapper< json::Node > > sgpp::base::OCLOperationConfiguration::getAllDeviceNodes ()
References json::Node::keys().
The documentation for this class was generated from the following files:
base/src/sgpp/base/opencl/OCLOperationConfiguration.hpp
base/src/sgpp/base/opencl/OCLOperationConfiguration.cpp