SG++-Doxygen-Documentation: sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive Class Reference
sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive Class Reference
#include <OperationMultipleEvalModPolyClenshawCurtisNaive.hpp>
Public Member Functions
double getDuration () override
void mult (DataVector &alpha, DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (DataVector &source, DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEvalModPolyClenshawCurtisNaive (Grid &grid, size_t degree, DataMatrix &dataset)
~OperationMultipleEvalModPolyClenshawCurtisNaive () override
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual std::string getImplementationName ()
Name of this implementation of the operation.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual void prepare ()
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
virtual ~OperationMultipleEval ()
Destructor.
Protected Attributes
SPolyModifiedClenshawCurtisBase base
1D B-spline basis
DataMatrix pointsInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Constructor & Destructor Documentation
OperationMultipleEvalModPolyClenshawCurtisNaive()
sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::OperationMultipleEvalModPolyClenshawCurtisNaive (Grid & grid, size_t degree, DataMatrix & dataset) inline
~OperationMultipleEvalModPolyClenshawCurtisNaive()
sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::~OperationMultipleEvalModPolyClenshawCurtisNaive () inline override
Member Function Documentation
getDuration()
double sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::getDuration () override virtual
Implements sgpp::base::OperationMultipleEval.
mult()
void sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult (DataVector & alpha, DataVector & result) override virtual
Multiplication of \(B^T\) with vector \(\alpha\).
Parameters
alpha vector, to which \(B\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References alpha, base, sgpp::base::OperationMultipleEval::dataset, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::DataMatrix::getNrows(), sgpp::base::HashGridStorage::getSize(), m, pointsInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointsToUnitCube().
multTranspose()
void sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose (DataVector & source, DataVector & result) override virtual
Multiplication of \(B\) with vector \(\alpha\).
Parameters
source vector, to which \(B^T\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References alpha, base, sgpp::base::OperationMultipleEval::dataset, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::DataMatrix::getNrows(), sgpp::base::HashGridStorage::getSize(), m, pointsInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointsToUnitCube().
Member Data Documentation
base
SPolyModifiedClenshawCurtisBase sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::base protected
1D B-spline basis
Referenced by mult(), and multTranspose().
pointsInUnitCube
DataMatrix sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::pointsInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by mult(), and multTranspose().
storage
GridStorage& sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::storage protected
storage of the sparse grid
Referenced by mult(), and multTranspose().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationMultipleEvalModPolyClenshawCurtisNaive.hpp
base/src/sgpp/base/operation/hash/OperationMultipleEvalModPolyClenshawCurtisNaive.cpp