SG++-Doxygen-Documentation: sgpp::datadriven::DataMiningConfigParser Class Reference
sgpp::datadriven::DataMiningConfigParser Class Reference
#include <DataMiningConfigParser.hpp>
Public Member Functions
DataMiningConfigParser (const std::string &filepath)
bool getDataSourceConfig (DataSourceConfig &config, const DataSourceConfig &defaults) const
bool getFitterAdaptivityConfig (base::AdaptivityConfiguration &config, const base::AdaptivityConfiguration &defaults) const
bool getFitterConfigType (FitterType &fitter, const FitterType &defaults) const
bool getFitterCrossvalidationConfig (CrossvalidationConfiguration &config, const CrossvalidationConfiguration &defaults) const
bool getFitterDatabaseConfig (datadriven::DatabaseConfiguration &config, const datadriven::DatabaseConfiguration &defaults) const
Returns the database configuration of the fitter if it exists.
bool getFitterDensityEstimationConfig (DensityEstimationConfiguration &config, const DensityEstimationConfiguration &defaults) const
bool getFitterGridConfig (base::GeneralGridConfiguration &config, const base::GeneralGridConfiguration &defaults) const
bool getFitterLambda (double &lambda, double defaultValue) const
bool getFitterLearnerConfig (datadriven::LearnerConfiguration &config, const datadriven::LearnerConfiguration &defaults) const
Initializes the learner configuration if it exists.
bool getFitterParallelConfig (datadriven::ParallelConfiguration &config, const datadriven::ParallelConfiguration &defaults) const
Initializes the parallel configuration if it exists.
bool getFitterRegularizationConfig (RegularizationConfiguration &config, const RegularizationConfiguration &defaults) const
bool getFitterSolverFinalConfig (solver::SLESolverConfiguration &config, const solver::SLESolverConfiguration &defaults) const
bool getFitterSolverRefineConfig (solver::SLESolverConfiguration &config, const solver::SLESolverConfiguration &defaults) const
bool getGeometryConfig (datadriven::GeometryConfiguration &config, const datadriven::GeometryConfiguration &defaults) const
Initializes the geometry configuration if it exists.
void getHPOConfig (HPOConfig &config)
std::string getHPOMethod (std::string defaultValue) const
void getHyperparameters (std::map< std::string, ContinuousParameter > &conpar, std::map< std::string, DiscreteParameter > &dispar, std::map< std::string, DiscreteParameter > &catpar, std::vector< base::GridType > &basisFunctions) const
bool getMultiDataSourceConfig (std::vector< DataSourceConfig > &config, const std::vector< DataSourceConfig > &defaults) const
Expands on getDataSourceConfig by allowing multiple dataSource instances.
bool getScorerConfig (ScorerConfiguration &config, const ScorerConfiguration &defaults) const
Reads the configuration for the scorer.
bool getVisualizationGeneralConfig (datadriven::VisualizationGeneralConfig &config, const datadriven::VisualizationGeneralConfig &defaults) const
Initializes the visualization general configuration if it exists.
bool getVisualizationParameters (datadriven::VisualizationParameters &config, const datadriven::VisualizationParameters &defaults) const
Initializes the visualization parameters configuration if it exists.
bool hasDataSourceConfig () const
bool hasDataTransformationConfig () const
bool hasFitterConfig () const
bool hasFitterConfigCrossValidation () const
Checks whether the fitter configuration contains a cross validation configuration.
bool hasGeometryConfig () const
bool hasParallelConfig () const
bool hasScorerConfig () const
bool hasVisualizationConfig () const
bool hasVisualizationGeneralConfig () const
bool hasVisualizationParametersConfig () const
std::vector< int64_t > parseIntArray (json::JSON::DictNode &dict, const std::string &key, std::vector< int64_t > defaultValue, const std::string &parentNode) const
virtual ~DataMiningConfigParser ()
Constructor & Destructor Documentation
DataMiningConfigParser()
sgpp::datadriven::DataMiningConfigParser::DataMiningConfigParser (const std::string & filepath) explicit
References json::json_exception::what().
~DataMiningConfigParser()
sgpp::datadriven::DataMiningConfigParser::~DataMiningConfigParser () virtual
Member Function Documentation
getDataSourceConfig()
bool sgpp::datadriven::DataMiningConfigParser::getDataSourceConfig (DataSourceConfig & config, const DataSourceConfig & defaults) const
References sgpp::datadriven::DataSourceConfig::batchSize_, sgpp::datadriven::DataSourceConfig::dataTransformationConfig_, sgpp::datadriven::DataSourceConfig::epochs_, sgpp::datadriven::DataSourceConfig::filePath_, sgpp::datadriven::DataSourceConfig::fileType_, hasDataSourceConfig(), hasDataTransformationConfig(), sgpp::datadriven::DataSourceConfig::hasTargets_, sgpp::datadriven::DataSourceConfig::isCompressed_, sgpp::datadriven::DataSourceConfig::numBatches_, sgpp::datadriven::DataSourceFileTypeParser::parse(), sgpp::datadriven::DataSourceShufflingTypeParser::parse(), sgpp::datadriven::DataSourceConfig::randomSeed_, sgpp::datadriven::DataSourceConfig::readinClasses_, sgpp::datadriven::DataSourceConfig::readinColumns_, sgpp::datadriven::DataSourceConfig::readinCutoff_, sgpp::datadriven::DataSourceConfig::shuffling_, sgpp::datadriven::DataSourceConfig::testBatchSize_, sgpp::datadriven::DataSourceConfig::testFilePath_, sgpp::datadriven::DataSourceConfig::testFileType_, sgpp::datadriven::DataSourceConfig::testHasTargets_, sgpp::datadriven::DataSourceConfig::testIsCompressed_, sgpp::datadriven::DataSourceConfig::testNumBatches_, sgpp::datadriven::DataSourceConfig::testReadinClasses_, sgpp::datadriven::DataSourceConfig::testReadinColumns_, sgpp::datadriven::DataSourceConfig::testReadinCutoff_, sgpp::datadriven::DataSourceFileTypeParser::toString(), sgpp::datadriven::DataSourceShufflingTypeParser::toString(), and sgpp::datadriven::DataSourceConfig::validationPortion_.
getFitterAdaptivityConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig (base::AdaptivityConfiguration & config, const base::AdaptivityConfiguration & defaults) const
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::coarseningFunctorType_, sgpp::base::AdaptivityConfiguration::coarseningThreshold_, sgpp::base::AdaptivityConfiguration::coarsenInitialPoints_, sgpp::base::AdaptivityConfiguration::errorBasedRefinement_, sgpp::base::AdaptivityConfiguration::errorBufferSize_, sgpp::base::AdaptivityConfiguration::errorConvergenceThreshold_, sgpp::base::AdaptivityConfiguration::errorMinInterval_, hasFitterConfig(), sgpp::base::AdaptivityConfiguration::levelPenalize_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numCoarseningPoints_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityThresholdTypeParser::parse(), sgpp::base::CoarseningFunctorTypeParser::parse(), sgpp::base::RefinementFunctorTypeParser::parse(), sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::precomputeEvaluations_, sgpp::base::AdaptivityConfiguration::refinementFunctorType_, sgpp::base::AdaptivityConfiguration::refinementPeriod_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::AdaptivityConfiguration::scalingCoefficients_, json::ListNode::size(), sgpp::base::AdaptivityConfiguration::thresholdType_, sgpp::base::AdaptivityThresholdTypeParser::toString(), sgpp::base::CoarseningFunctorTypeParser::toString(), and sgpp::base::RefinementFunctorTypeParser::toString().
getFitterConfigType()
bool sgpp::datadriven::DataMiningConfigParser::getFitterConfigType (FitterType & fitter, const FitterType & defaults) const
References hasFitterConfig(), and sgpp::datadriven::FitterTypeParser::parse().
getFitterCrossvalidationConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterCrossvalidationConfig (CrossvalidationConfiguration & config, const CrossvalidationConfiguration & defaults) const
References sgpp::datadriven::CrossvalidationConfiguration::enable_, hasFitterConfig(), sgpp::datadriven::CrossvalidationConfiguration::kfold_, sgpp::datadriven::CrossvalidationConfiguration::lambda_, sgpp::datadriven::CrossvalidationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationConfiguration::lambdaSteps_, sgpp::datadriven::CrossvalidationConfiguration::logScale_, sgpp::datadriven::CrossvalidationConfiguration::seed_, sgpp::datadriven::CrossvalidationConfiguration::shuffle_, and sgpp::datadriven::CrossvalidationConfiguration::silent_.
getFitterDatabaseConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterDatabaseConfig (datadriven::DatabaseConfiguration & config, const datadriven::DatabaseConfiguration & defaults) const
Returns the database configuration of the fitter if it exists.
Parameters
config the configuration object that will be initialized
defaults default values if the fitter does not contain a database configuration
Returns
whether the fitter contains a database configuration
References sgpp::datadriven::DatabaseConfiguration::filePath_, and hasFitterConfig().
getFitterDensityEstimationConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterDensityEstimationConfig (DensityEstimationConfiguration & config, const DensityEstimationConfiguration & defaults) const
References sgpp::datadriven::DensityEstimationConfiguration::decomposition_, hasFitterConfig(), sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsDecompose_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsRefine_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsSolver_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsUpdateLambda_, sgpp::datadriven::DensityEstimationConfiguration::normalize_, sgpp::datadriven::DensityEstimationTypeParser::parse(), sgpp::datadriven::MatrixDecompositionTypeParser::parse(), sgpp::datadriven::DensityEstimationTypeParser::toString(), sgpp::datadriven::MatrixDecompositionTypeParser::toString(), sgpp::datadriven::DensityEstimationConfiguration::type_, and sgpp::datadriven::DensityEstimationConfiguration::useOfflinePermutation_.
getFitterGridConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterGridConfig (base::GeneralGridConfiguration & config, const base::GeneralGridConfiguration & defaults) const
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::base::GeneralGridConfiguration::generalType_, hasFitterConfig(), sgpp::base::GeneralGridConfiguration::level_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::GeneralGridTypeParser::parse(), sgpp::base::GridTypeParser::parse(), sgpp::base::GridTypeParser::toString(), and sgpp::base::GeneralGridConfiguration::type_.
getFitterLambda()
bool sgpp::datadriven::DataMiningConfigParser::getFitterLambda (double & lambda, double defaultValue) const
getFitterLearnerConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterLearnerConfig (datadriven::LearnerConfiguration & config, const datadriven::LearnerConfiguration & defaults) const
Initializes the learner configuration if it exists.
Parameters
config the configuration instance that will be initialized
defaults default values if the fitter config does not contain a matching entry
Returns
whether the configuration contains a learner configuration
References hasFitterConfig(), sgpp::datadriven::LearnerConfiguration::learningRate_, and sgpp::datadriven::LearnerConfiguration::usePrior_.
getFitterParallelConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterParallelConfig (datadriven::ParallelConfiguration & config, const datadriven::ParallelConfiguration & defaults) const
Initializes the parallel configuration if it exists.
Parameters
config the configuration instance that will be initialized
defaults default values if the parallel config does not contain a matching entry
Returns
whether the configuration contains a parallel configuration
References sgpp::datadriven::ParallelConfiguration::columnBlockSize_, hasFitterConfig(), hasParallelConfig(), sgpp::datadriven::ParallelConfiguration::processCols_, sgpp::datadriven::ParallelConfiguration::processRows_, sgpp::datadriven::ParallelConfiguration::rowBlockSize_, and sgpp::datadriven::ParallelConfiguration::scalapackEnabled_.
getFitterRegularizationConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterRegularizationConfig (RegularizationConfiguration & config, const RegularizationConfiguration & defaults) const
References sgpp::datadriven::RegularizationConfiguration::convergenceThreshold_, sgpp::datadriven::RegularizationConfiguration::exponentBase_, hasFitterConfig(), sgpp::datadriven::RegularizationConfiguration::intervalA_, sgpp::datadriven::RegularizationConfiguration::intervalB_, sgpp::datadriven::RegularizationConfiguration::l1Ratio_, sgpp::datadriven::RegularizationConfiguration::lambda_, sgpp::datadriven::RegularizationConfiguration::optimizeLambda_, sgpp::datadriven::RegularizationConfiguration::optimizerTolerance_, sgpp::datadriven::RegularizationTypeParser::parse(), sgpp::datadriven::ScorerMetricTypeParser::parseRegularizationMetric(), sgpp::datadriven::RegularizationConfiguration::regularizationMetric_, sgpp::datadriven::ScorerMetricTypeParser::regularizationMetricToString(), sgpp::datadriven::RegularizationTypeParser::toString(), and sgpp::datadriven::RegularizationConfiguration::type_.
getFitterSolverFinalConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterSolverFinalConfig (solver::SLESolverConfiguration & config, const solver::SLESolverConfiguration & defaults) const
References hasFitterConfig().
getFitterSolverRefineConfig()
bool sgpp::datadriven::DataMiningConfigParser::getFitterSolverRefineConfig (solver::SLESolverConfiguration & config, const solver::SLESolverConfiguration & defaults) const
References hasFitterConfig().
getGeometryConfig()
bool sgpp::datadriven::DataMiningConfigParser::getGeometryConfig (datadriven::GeometryConfiguration & config, const datadriven::GeometryConfiguration & defaults) const
Initializes the geometry configuration if it exists.
Parameters
config the configuration instance that will be initialized
defaults default values if the fitter config does not contain a matching entry
Returns
whether the configuration contains a learner configuration
References sgpp::datadriven::StencilConfiguration::applyOnLayers_, sgpp::datadriven::Block, sgpp::datadriven::StencilConfiguration::blockLenght_, sgpp::datadriven::StencilConfiguration::colorIndex_, sgpp::datadriven::GeometryConfiguration::dim_, hasFitterConfig(), hasGeometryConfig(), sgpp::datadriven::GeometryConfigurationParser::parseStencil(), sgpp::datadriven::GeometryConfiguration::stencils_, and sgpp::datadriven::StencilConfiguration::stencilType_.
getHPOConfig()
void sgpp::datadriven::DataMiningConfigParser::getHPOConfig (HPOConfig & config)
References sgpp::datadriven::HPOConfig::getConstraints(), sgpp::datadriven::HPOConfig::getLambda(), sgpp::datadriven::HPOConfig::getNRandom(), sgpp::datadriven::HPOConfig::getNRuns(), sgpp::datadriven::HPOConfig::getNTrainSamples(), sgpp::datadriven::HPOConfig::getSeed(), sgpp::datadriven::HPOConfig::getStages(), parseIntArray(), sgpp::datadriven::HPOConfig::setConstraints(), sgpp::datadriven::HPOConfig::setLambda(), sgpp::datadriven::HPOConfig::setNRandom(), sgpp::datadriven::HPOConfig::setNRuns(), sgpp::datadriven::HPOConfig::setNTrainSamples(), sgpp::datadriven::HPOConfig::setSeed(), and sgpp::datadriven::HPOConfig::setStages().
getHPOMethod()
std::string sgpp::datadriven::DataMiningConfigParser::getHPOMethod (std::string defaultValue) const
getHyperparameters()
void sgpp::datadriven::DataMiningConfigParser::getHyperparameters (std::map< std::string, ContinuousParameter > & conpar, std::map< std::string, DiscreteParameter > & dispar, std::map< std::string, DiscreteParameter > & catpar, std::vector< base::GridType > & basisFunctions) const
References sgpp::base::GridTypeParser::parse().
getMultiDataSourceConfig()
bool sgpp::datadriven::DataMiningConfigParser::getMultiDataSourceConfig (std::vector< DataSourceConfig > & config, const std::vector< DataSourceConfig > & defaults) const
Expands on getDataSourceConfig by allowing multiple dataSource instances.
The first instance is used as a template for filling in the parameters for all dataSource instances.
References json::Node::get(), hasDataSourceConfig(), hasDataTransformationConfig(), sgpp::datadriven::DataSourceFileTypeParser::parse(), sgpp::datadriven::DataSourceShufflingTypeParser::parse(), json::ListNode::size(), sgpp::datadriven::DataSourceFileTypeParser::toString(), and sgpp::datadriven::DataSourceShufflingTypeParser::toString().
getScorerConfig()
bool sgpp::datadriven::DataMiningConfigParser::getScorerConfig (ScorerConfiguration & config, const ScorerConfiguration & defaults) const
Reads the configuration for the scorer.
Parameters
config the configuration instance to initialize
defaults a set of configurations initialized with default values
Returns
if the configuration file contained a scorer configuration
References hasScorerConfig(), sgpp::datadriven::ScorerConfiguration::metric_, sgpp::datadriven::ScorerMetricTypeParser::parse(), and sgpp::datadriven::ScorerMetricTypeParser::toString().
getVisualizationGeneralConfig()
bool sgpp::datadriven::DataMiningConfigParser::getVisualizationGeneralConfig (datadriven::VisualizationGeneralConfig & config, const datadriven::VisualizationGeneralConfig & defaults) const
Initializes the visualization general configuration if it exists.
Parameters
config the configuration instance that will be initiazlized
defaults default values if the fitter config does not contain a matching entry
Returns
wether the configuration contains a visualization configuration
References sgpp::datadriven::VisualizationGeneralConfig::algorithm_, sgpp::datadriven::VisualizationGeneralConfig::crossValidation_, sgpp::datadriven::VisualizationGeneralConfig::execute_, hasFitterConfig(), hasVisualizationConfig(), hasVisualizationGeneralConfig(), sgpp::datadriven::VisualizationGeneralConfig::numBatches_, sgpp::datadriven::VisualizationTypesParser::parseFileType(), sgpp::datadriven::VisualizationGeneralConfig::targetDirectory_, sgpp::datadriven::VisualizationGeneralConfig::targetFileType_, and sgpp::datadriven::VisualizationTypesParser::toString().
getVisualizationParameters()
bool sgpp::datadriven::DataMiningConfigParser::getVisualizationParameters (datadriven::VisualizationParameters & config, const datadriven::VisualizationParameters & defaults) const
Initializes the visualization parameters configuration if it exists.
Parameters
config the configuration instance that will be initiazlized
defaults default values if the fitter config does not contain a matching entry
Returns
wether the configuration contains a visualization configuration
References hasVisualizationParametersConfig(), sgpp::datadriven::VisualizationParameters::maxNumberIterations_, sgpp::datadriven::VisualizationParameters::numberCores_, sgpp::datadriven::VisualizationParameters::perplexity_, sgpp::datadriven::VisualizationParameters::seed_, sgpp::datadriven::VisualizationParameters::targetDimension_, and sgpp::datadriven::VisualizationParameters::theta_.
hasDataSourceConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasDataSourceConfig () const
Referenced by getDataSourceConfig(), getMultiDataSourceConfig(), and hasDataTransformationConfig().
hasDataTransformationConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasDataTransformationConfig () const
References hasDataSourceConfig(), and hasDataTransformationConfig().
Referenced by getDataSourceConfig(), getMultiDataSourceConfig(), and hasDataTransformationConfig().
hasFitterConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasFitterConfig () const
Referenced by getFitterAdaptivityConfig(), getFitterConfigType(), getFitterCrossvalidationConfig(), getFitterDatabaseConfig(), getFitterDensityEstimationConfig(), getFitterGridConfig(), getFitterLearnerConfig(), getFitterParallelConfig(), getFitterRegularizationConfig(), getFitterSolverFinalConfig(), getFitterSolverRefineConfig(), getGeometryConfig(), getVisualizationGeneralConfig(), hasFitterConfigCrossValidation(), and hasParallelConfig().
hasFitterConfigCrossValidation()
bool sgpp::datadriven::DataMiningConfigParser::hasFitterConfigCrossValidation () const
Checks whether the fitter configuration contains a cross validation configuration.
Returns
if the fitter configuration contains a cross validation configuration
References hasFitterConfig().
hasGeometryConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasGeometryConfig () const
Referenced by getGeometryConfig().
hasParallelConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasParallelConfig () const
References hasFitterConfig(), and hasParallelConfig().
Referenced by getFitterParallelConfig(), and hasParallelConfig().
hasScorerConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasScorerConfig () const
Referenced by getScorerConfig().
hasVisualizationConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasVisualizationConfig () const
Referenced by getVisualizationGeneralConfig(), hasVisualizationGeneralConfig(), and hasVisualizationParametersConfig().
hasVisualizationGeneralConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasVisualizationGeneralConfig () const
References hasVisualizationConfig().
Referenced by getVisualizationGeneralConfig().
hasVisualizationParametersConfig()
bool sgpp::datadriven::DataMiningConfigParser::hasVisualizationParametersConfig () const
References hasVisualizationConfig().
Referenced by getVisualizationParameters().
parseIntArray()
std::vector< int64_t > sgpp::datadriven::DataMiningConfigParser::parseIntArray (json::JSON::DictNode & dict, const std::string & key, std::vector< int64_t > defaultValue, const std::string & parentNode) const
References json::DictNode::contains(), json::Node::get(), and json::DictNode::size().
Referenced by getHPOConfig().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/configuration/DataMiningConfigParser.hpp
datadriven/src/sgpp/datadriven/datamining/configuration/DataMiningConfigParser.cpp