SG++-Doxygen-Documentation: sgpp::datadriven::ScottsRule Class Reference
sgpp::datadriven::ScottsRule Class Reference
#include <KernelDensityEstimator.hpp>
Static Public Member Functions
static void optimizeBandwidths (KernelDensityEstimator *kde, base::DataVector &bandwidths)
Member Function Documentation
optimizeBandwidths()
void sgpp::datadriven::ScottsRule::optimizeBandwidths (KernelDensityEstimator * kde, base::DataVector & bandwidths) static
References sgpp::datadriven::KernelDensityEstimator::getDim(), sgpp::datadriven::KernelDensityEstimator::getSamples(), and sgpp::datadriven::RuleOfThumb::getSampleStd().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp