SG++-Doxygen-Documentation: sgpp::base::KernelSourceBuilderBase< T > Class Template Reference
sgpp::base::KernelSourceBuilderBase< T > Class Template Reference
#include <KernelSourceBuilderBase.hpp>
Public Member Functions
KernelSourceBuilderBase ()
Protected Member Functions
std::string constSuffix ()
std::string floatType ()
std::string intType ()
std::string reuseSource (std::string fileName)
void writeSource (std::string fileName, std::string source)
Protected Attributes
std::vector< std::string > indent
Static Protected Attributes
static const size_t MAX_INDENT_LEVEL = 10
Constructor & Destructor Documentation
KernelSourceBuilderBase()
template<typename T > sgpp::base::KernelSourceBuilderBase< T >::KernelSourceBuilderBase () inline
References sgpp::base::KernelSourceBuilderBase< T >::indent, and sgpp::base::KernelSourceBuilderBase< T >::MAX_INDENT_LEVEL.
Member Function Documentation
constSuffix()
template<typename T > std::string sgpp::base::KernelSourceBuilderBase< T >::constSuffix () inline protected
floatType()
template<typename T > std::string sgpp::base::KernelSourceBuilderBase< T >::floatType () inline protected
Referenced by sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::generateSource(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::generateSource(), and sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::generateSource().
intType()
template<typename T > std::string sgpp::base::KernelSourceBuilderBase< T >::intType () inline protected
reuseSource()
template<typename T > std::string sgpp::base::KernelSourceBuilderBase< T >::reuseSource (std::string fileName) inline protected
References fileName.
Referenced by sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::generateSource(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::generateSource(), and sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::generateSource().
writeSource()
template<typename T > void sgpp::base::KernelSourceBuilderBase< T >::writeSource (std::string fileName, std::string source) inline protected
References fileName.
Referenced by sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::generateSource(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::generateSource(), and sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::generateSource().
Member Data Documentation
indent
template<typename T > std::vector<std::string> sgpp::base::KernelSourceBuilderBase< T >::indent protected
Referenced by sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::generateSource(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::generateSource(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::generateSource(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::generateSource(), and sgpp::base::KernelSourceBuilderBase< T >::KernelSourceBuilderBase().
MAX_INDENT_LEVEL
template<typename T > const size_t sgpp::base::KernelSourceBuilderBase< T >::MAX_INDENT_LEVEL = 10 static protected
Referenced by sgpp::base::KernelSourceBuilderBase< T >::KernelSourceBuilderBase().
The documentation for this class was generated from the following file:
base/src/sgpp/base/opencl/KernelSourceBuilderBase.hpp