SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOfflineGE Class Reference
sgpp::datadriven::DBMatOfflineGE Class Reference
DBMatOffline specialization as a base class for all algorithms based on gaussian elimination on a dense matrix.
#include <DBMatOfflineGE.hpp>
Public Member Functions
void buildMatrix (Grid *grid, const RegularizationConfiguration &regularizationConfig) override
Builds the right hand side matrix with identity regularization term.
DBMatOfflineGE (const std::string &fileName)
Public Member Functions inherited from sgpp::datadriven::DBMatOffline
virtual DBMatOffline * clone () const =0
Interface for the clone idiom.
virtual void compute_inverse ()
virtual void compute_inverse_parallel (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
parallel/distributed version of compute_inverse()
void compute_L2_refine_vectors (DataMatrix *mat_refine, Grid *grid, size_t newPoints)
computes vectors of L2 products of grid points for refinement
DBMatOffline (const DBMatOffline &rhs)
Copy Constructor.
DBMatOffline (const std::string &fileName)
Constructor Create offline object from serialized offline object.
DBMatOffline (DBMatOffline &&rhs)=default
Default move constructor.
virtual void decomposeMatrix (const RegularizationConfiguration &regularizationConfig, const DensityEstimationConfiguration &densityEstimationConfig)=0
Decomposes the matrix according to the chosen decomposition type.
virtual void decomposeMatrixParallel (RegularizationConfiguration &regularizationConfig, DensityEstimationConfiguration &densityEstimationConfig, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
The parallel/distributed version of decomposeMatrix(...)
DataMatrixDistributed & getDecomposedInverseDistributed ()
Get a reference to the distributed decomposed matrix, analogously to getDecomposedMatrixDistributed()
DataMatrix & getDecomposedMatrix ()
Get a reference to the decomposed matrix.
DataMatrixDistributed & getDecomposedMatrixDistributed ()
Get a reference to the distributed decomposed matrix.
virtual sgpp::datadriven::MatrixDecompositionType getDecompositionType ()=0
Returns the decomposition type of the DBMatOffline object.
virtual size_t getGridSize ()
Returns the dimensionality of the quadratic lhs matrix (i.e.
DataMatrix & getInverseMatrix ()
Get a reference to the inverse matrix.
DataMatrix & getLhsMatrix_ONLY_FOR_TESTING ()
Allows access to lhs matrix, which is meant ONLY FOR TESTING.
virtual const DataMatrix & getUnmodifiedR ()=0
Get the unmodified (without added lambda) system matrix R.
virtual const DataMatrixDistributed & getUnmodifiedRDistributed (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)=0
Get the distributed version of the unmodified (without added lambda) system matrix R.
virtual bool isRefineable ()=0
Only Offline objects based on Cholesky decomposition, or orthogonal adaptivity can be refined.
DBMatOffline & operator= (const DBMatOffline &rhs)
Default copy assign operator.
DBMatOffline & operator= (DBMatOffline &&rhs)=default
Default move assign operator.
void printMatrix ()
Prints the matrix onto standard output.
virtual void store (const std::string &fileName)
Serialize the DBMatOffline Object.
virtual void syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the decomposed matrix.
virtual void syncDistributedInverse (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the inverse matrix.
virtual void updateRegularization (double lambda)=0
Modifies the decomposition to update the regularization parameter lambda.
virtual void updateRegularizationParallel (double lambda, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)=0
Modifies the parallel decomposition to update the regularization parameter lambda.
virtual ~DBMatOffline ()=default
Default virtual destructor.
Protected Member Functions
DBMatOfflineGE ()
Protected Member Functions inherited from sgpp::datadriven::DBMatOffline
DBMatOffline ()
void parseInter (const std::string &fileName, std::set< std::set< size_t > > &interactions) const
Read the Interactionsterms from a serialized DBMatOfflibe object.
Additional Inherited Members
Public Attributes inherited from sgpp::datadriven::DBMatOffline
std::set< std::set< size_t > > interactions
Protected Attributes inherited from sgpp::datadriven::DBMatOffline
bool isConstructed
bool isDecomposed
DataMatrixDistributed lhsDistributed
DataMatrixDistributed lhsDistributedInverse
DataMatrix lhsInverse
DataMatrix lhsMatrix
Detailed Description
DBMatOffline specialization as a base class for all algorithms based on gaussian elimination on a dense matrix.
Constructor & Destructor Documentation
DBMatOfflineGE() [1/2]
sgpp::datadriven::DBMatOfflineGE::DBMatOfflineGE (const std::string & fileName) explicit
References fileName, sgpp::datadriven::DBMatOffline::lhsMatrix, and sgpp::base::StringTokenizer::tokenize().
DBMatOfflineGE() [2/2]
sgpp::datadriven::DBMatOfflineGE::DBMatOfflineGE () protected
Member Function Documentation
buildMatrix()
void sgpp::datadriven::DBMatOfflineGE::buildMatrix (Grid * grid, const RegularizationConfiguration & regularizationConfig) override virtual
Builds the right hand side matrix with identity regularization term.
Parameters
grid The grid object the matrix is based on
regularizationConfig Configures the regularization which is incorporated into the lhs
Reimplemented from sgpp::datadriven::DBMatOffline.
References sgpp::base::DataMatrix::add(), sgpp::datadriven::DBMatOffline::buildMatrix(), grid(), sgpp::datadriven::Identity, sgpp::datadriven::DBMatOffline::isConstructed, sgpp::datadriven::RegularizationConfiguration::lambda_, sgpp::datadriven::DBMatOffline::lhsMatrix, sgpp::base::DataMatrix::set(), sgpp::base::DataMatrix::setAll(), and sgpp::datadriven::RegularizationConfiguration::type_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatOfflineGE.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatOfflineGE.cpp