SG++-Doxygen-Documentation: sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix Class Reference
sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix Class Reference
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
#include <PiecewiseConstantSmoothedRegressionSystemMatrix.hpp>
Public Member Functions
void generateb (sgpp::base::DataVector &b)
Generates the right hand side of the classification equation.
void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Generates the left hand side of the classification equation.
PiecewiseConstantSmoothedRegressionSystemMatrix (sgpp::datadriven::PiecewiseConstantRegression::Node &piecewiseRegressor, sgpp::base::Grid &grid, sgpp::base::OperationMatrix &C, double lambdaRegression)
Std-Constructor.
virtual ~PiecewiseConstantSmoothedRegressionSystemMatrix ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
Constructor & Destructor Documentation
PiecewiseConstantSmoothedRegressionSystemMatrix()
sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::PiecewiseConstantSmoothedRegressionSystemMatrix (sgpp::datadriven::PiecewiseConstantRegression::Node & piecewiseRegressor, sgpp::base::Grid & grid, sgpp::base::OperationMatrix & C, double lambdaRegression)
Std-Constructor.
Parameters
piecewiseRegressor approximation with piecewise-constant octtree
grid reference to the sparse grid
C the regression functional
lambdaRegression the regression parameter
References sgpp::op_factory::createOperationLTwoDotProduct().
~PiecewiseConstantSmoothedRegressionSystemMatrix()
sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::~PiecewiseConstantSmoothedRegressionSystemMatrix () virtual
Std-Destructor.
Member Function Documentation
generateb()
void sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::generateb (sgpp::base::DataVector & b)
Generates the right hand side of the classification equation.
Parameters
b reference to the vector which will contain the result of the matrix vector multiplication on the rhs
References sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), sgpp::base::Grid::getStorage(), and sgpp::datadriven::PiecewiseConstantRegression::Node::integrate().
mult()
void sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Generates the left hand side of the classification equation.
Parameters
alpha parameters for the sparse grid functions
result reference to the vector which will contain the result
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMatrix::mult(), and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/PiecewiseConstantSmoothedRegressionSystemMatrix.hpp
datadriven/src/sgpp/datadriven/algorithm/PiecewiseConstantSmoothedRegressionSystemMatrix.cpp