SG++-Doxygen-Documentation: sgpp::base::FundamentalSplineModifiedBasis< LT, IT > Class Template Reference
sgpp::base::FundamentalSplineModifiedBasis< LT, IT > Class Template Reference
Modified fundamental spline basis on Noboundary grids.
#include <FundamentalSplineModifiedBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
FundamentalSplineModifiedBasis ()
Default constructor.
FundamentalSplineModifiedBasis (size_t degree)
Constructor.
size_t getDegree () const override
double getIntegral (LT l, IT i) override
~FundamentalSplineModifiedBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis.
std::vector< double > coefficients
B-spline coefficients.
DataVector coordinates
coordinates and weights for calculating integrals
FundamentalSplineBasis< LT, IT > fundamentalSplineBasis
fundamental spline basis for fundamental spline evaluation
bool integrationInitialized = false
DataVector weights
Detailed Description
template<class LT, class IT>
class sgpp::base::FundamentalSplineModifiedBasis< LT, IT >
Modified fundamental spline basis on Noboundary grids.
Constructor & Destructor Documentation
FundamentalSplineModifiedBasis() [1/2]
template<class LT , class IT > sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::FundamentalSplineModifiedBasis () inline
Default constructor.
FundamentalSplineModifiedBasis() [2/2]
template<class LT , class IT > sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::FundamentalSplineModifiedBasis (size_t degree) inline explicit
Constructor.
Parameters
degree fundamental spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis, and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients.
~FundamentalSplineModifiedBasis()
template<class LT , class IT > sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::~FundamentalSplineModifiedBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of modified fundamental spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients, and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::fundamentalSplineBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), and sgpp::base::HierarchisationModFundamentalSpline::operator()().
evalDx()
template<class LT , class IT > double sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of modified fundamental spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients, and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::fundamentalSplineBasis.
Referenced by sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative().
evalDxDx()
template<class LT , class IT > double sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of modified fundamental spline basis function
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients, and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::fundamentalSplineBasis.
Referenced by sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
value of the integral
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coordinates, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::eval(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), h, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::integrationInitialized, and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::weights.
Referenced by sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::bsplineBasis protected
B-spline basis.
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::eval(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDx(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDxDx(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::FundamentalSplineModifiedBasis(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getDegree(), and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral().
coefficients
template<class LT , class IT > std::vector<double> sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coefficients protected
B-spline coefficients.
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::eval(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDx(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDxDx(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::FundamentalSplineModifiedBasis(), and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral().
coordinates
template<class LT , class IT > DataVector sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::coordinates protected
coordinates and weights for calculating integrals
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral().
fundamentalSplineBasis
template<class LT , class IT > FundamentalSplineBasis<LT, IT> sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::fundamentalSplineBasis protected
fundamental spline basis for fundamental spline evaluation
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::eval(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDx(), and sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::evalDxDx().
integrationInitialized
template<class LT , class IT > bool sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::integrationInitialized = false protected
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral().
weights
template<class LT , class IT > DataVector sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::weights protected
Referenced by sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/FundamentalSplineModifiedBasis.hpp