SG++-Doxygen-Documentation: sgpp::base::StandardGridGenerator Class Reference
sgpp::base::StandardGridGenerator Class Reference
GridGenerator for standard grids without boundaries.
#include <StandardGridGenerator.hpp>
Public Member Functions
void anisotropicFull (std::vector< size_t > dimlevels) override
Creates an anisotropicFull Grid for certain level vector, for example [2,3,1] results in a 3x7x1 grid.
void cliques (size_t level, size_t clique_size) override
Creates a sparse grid with fully connected cliques.
void cliques (size_t level, size_t clique_size, double T) override
Creates a sparse grid with fully connected cliques.
void coarsen (CoarseningFunctor &func, std::vector< size_t > *removedSeq) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void coarsenNFirstOnly (CoarseningFunctor &func, size_t numFirstOnly, std::vector< size_t > *removedSeq, size_t minIndexConsidered) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void full (size_t level) override
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
size_t getNumberOfRefinablePoints () override
Returns the number of points on the grid that can be refined in the next iteration.
size_t getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
size_t getNumberOfRemovablePoints () override
Returns the number of points on the grid that can be removed in the next iteration.
void refine (RefinementFunctor &func, std::vector< size_t > *addedPoints=nullptr) override
Refines a grid according to the settings of the RefinementFunctor func.
void refineInter (RefinementFunctor &func, const std::set< std::set< size_t > > &interactions) override
Refines a grid according to the settings of the RefinementFunctor func.
void refineInter (RefinementFunctor &func, const std::unordered_set< std::vector< bool > > &interactions)
void refineMaxLevel (RefinementFunctor &func, size_t maxLevel) override
Refines a grid according to the settings of the RefinementFunctor func.
void regular (size_t level) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
void regular (size_t level, double T) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
void regularInter (size_t level, const std::set< std::set< size_t > > &terms, double T) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
StandardGridGenerator (GridStorage &storage)
Constructor.
~StandardGridGenerator () override
Destructor.
Public Member Functions inherited from sgpp::base::GridGenerator
GridGenerator ()
Constructor.
virtual void truncated (size_t level, size_t l_user)
Creates a grid which doesn't contain the fullgrids with li<l_user, for any li level_t.
virtual ~GridGenerator ()
Destructor.
Protected Attributes
GridStorage & storage
reference to the storage object
Detailed Description
GridGenerator for standard grids without boundaries.
Constructor & Destructor Documentation
StandardGridGenerator()
sgpp::base::StandardGridGenerator::StandardGridGenerator (GridStorage & storage) explicit
Constructor.
Parameters
storage the grid's storage object
~StandardGridGenerator()
sgpp::base::StandardGridGenerator::~StandardGridGenerator () override
Destructor.
Member Function Documentation
anisotropicFull()
void sgpp::base::StandardGridGenerator::anisotropicFull (std::vector< size_t > dimlevels) override virtual
Creates an anisotropicFull Grid for certain level vector, for example [2,3,1] results in a 3x7x1 grid.
Reimplemented from sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::anisotropicFull(), and storage.
cliques() [1/2]
void sgpp::base::StandardGridGenerator::cliques (size_t level, size_t clique_size) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::cliques(), level, and storage.
cliques() [2/2]
void sgpp::base::StandardGridGenerator::cliques (size_t level, size_t clique_size, double T) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
T modifier for subgrid selection, T = 0 implies standard sparse grid. For further information see Griebel and Knapek's paper optimized tensor-product approximation spaces
Reimplemented from sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::cliques(), level, and storage.
coarsen()
void sgpp::base::StandardGridGenerator::coarsen (CoarseningFunctor & func, std::vector< size_t > * removedSeq) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Parameters
func pointer to coarsening functor
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen(), and storage.
Referenced by coarsen(), coarsenNFirstOnly(), and getNumberOfRemovablePoints().
coarsenNFirstOnly()
void sgpp::base::StandardGridGenerator::coarsenNFirstOnly (CoarseningFunctor & func, size_t numFirstOnly, std::vector< size_t > * removedSeq, size_t minIndexConsidered) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Only numFirstOnly first grid points are checked for coarsening.
Parameters
func pointer to coarsening functor
numFirstOnly max. number grid points to be coarsened
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
minIndexConsidered Minimum index of grid points that will be coarsened
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen_NFirstOnly(), and storage.
full()
void sgpp::base::StandardGridGenerator::full (size_t level) override virtual
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::full(), level, and storage.
getNumberOfRefinablePoints()
size_t sgpp::base::StandardGridGenerator::getNumberOfRefinablePoints () override virtual
Returns the number of points on the grid that can be refined in the next iteration.
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinement::getNumberOfRefinablePoints(), refine(), and storage.
getNumberOfRefinablePointsToMaxLevel()
size_t sgpp::base::StandardGridGenerator::getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override virtual
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
Parameters
maxLevel no points on higher levels than maxLevel will be created
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
getNumberOfRemovablePoints()
size_t sgpp::base::StandardGridGenerator::getNumberOfRemovablePoints () override virtual
Returns the number of points on the grid that can be removed in the next iteration.
Returns
the number of points on the grid that can be removed
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), and storage.
refine()
void sgpp::base::StandardGridGenerator::refine (RefinementFunctor & func, std::vector< size_t > * addedPoints = nullptr) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
Parameters
func reference to refinement functor
addedPoints pointer to vector to add newly created grid points to
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinement::free_refine(), refine(), and storage.
Referenced by getNumberOfRefinablePoints(), refine(), and refineInter().
refineInter() [1/2]
void sgpp::base::StandardGridGenerator::refineInter (RefinementFunctor & func, const std::set< std::set< size_t > > & interactions) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
Does not create any interactions, that are not in the list of allowed interactions.
Refines the grid, but only adds interactions that are contained in the set interactions, i.e. only desired interactions. Each desired interaction is encoded as a vector which contains all desired interactions. For example, if we want to include grid points that model an interaction between the first and the second predictor, we would include the vector [1,2] in interactions.
Parameters
func pointer to refinement functor
interactions allowed interactions
Reimplemented from sgpp::base::GridGenerator.
References sgpp::base::HashGridStorage::getDimension(), refineInter(), and storage.
refineInter() [2/2]
void sgpp::base::StandardGridGenerator::refineInter (RefinementFunctor & func, const std::unordered_set< std::vector< bool > > & interactions)
References refine(), and storage.
Referenced by refineInter().
refineMaxLevel()
void sgpp::base::StandardGridGenerator::refineMaxLevel (RefinementFunctor & func, size_t maxLevel) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
additionally a maximum level for refinement is taken into account
Parameters
func pointer to refinement functor
maxLevel no points on higher levels than maxLevel will be created
Implements sgpp::base::GridGenerator.
regular() [1/2]
void sgpp::base::StandardGridGenerator::regular (size_t level) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References level, sgpp::base::HashGenerator::regular(), and storage.
regular() [2/2]
void sgpp::base::StandardGridGenerator::regular (size_t level, double T) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
If the used grid doesn't support the parameter t, t = 0 is used instead.
Parameters
level Grid level
T modifier for subgrid selection, T = 0 implies standard sparse grid. For further information see Griebel and Knapek's paper optimized tensor-product approximation spaces
Reimplemented from sgpp::base::GridGenerator.
References level, sgpp::base::HashGenerator::regular(), and storage.
regularInter()
void sgpp::base::StandardGridGenerator::regularInter (size_t level, const std::set< std::set< size_t > > & terms, double T) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
If the used grid doesn't support the parameter t, t = 0 is used instead. This grid generator allows the creation of regular grids that only contain some interaction terms.
Parameters
level Grid level
T modifier for subgrid selection, T = 0 implies standard sparse grid. For further information see Griebel and Knapek's paper optimized tensor-product approximation spaces
terms determines the included interaction terms.
Reimplemented from sgpp::base::GridGenerator.
References level, sgpp::base::HashGenerator::regularInter(), and storage.
Member Data Documentation
storage
GridStorage& sgpp::base::StandardGridGenerator::storage protected
reference to the storage object
Referenced by anisotropicFull(), cliques(), cliques(), coarsen(), coarsenNFirstOnly(), full(), getNumberOfRefinablePoints(), getNumberOfRemovablePoints(), refine(), refineInter(), refineInter(), regular(), regular(), and regularInter().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/StandardGridGenerator.hpp
base/src/sgpp/base/grid/generation/StandardGridGenerator.cpp