SG++-Doxygen-Documentation: sgpp::pde::OperationLaplaceLinearStretched Class Reference
sgpp::pde::OperationLaplaceLinearStretched Class Reference
Implementation for linear functions of Laplace Operation, linear grids without boundaries.
#include <OperationLaplaceLinearStretched.hpp>
Public Member Functions
OperationLaplaceLinearStretched (sgpp::base::GridStorage *storage)
Constructor of OperationLaplaceLinearStretched.
virtual ~OperationLaplaceLinearStretched ()
Destructor.
Public Member Functions inherited from sgpp::pde::UpDownOneOpDim
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
void multParallelBuildingBlock (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t operationDim)
This functions provides the same functionality as the normal mult routine.
UpDownOneOpDim (sgpp::base::GridStorage *storage)
Constructor.
UpDownOneOpDim (sgpp::base::GridStorage *storage, sgpp::base::DataVector &coef)
Constructor.
virtual ~UpDownOneOpDim ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
virtual void down (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D down operation
virtual void downOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D down operation that is only executed in one direction
virtual void specialOP (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t gradient_dim)
All calculations for gradient_dim, parallel version using OpenMP 3.
virtual void up (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D up operation
virtual void upOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D up operation that is only executed in one direction
Protected Member Functions inherited from sgpp::pde::UpDownOneOpDim
void updown (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
Recursive procedure for updown(), parallel version using OpenMP 3.
Additional Inherited Members
Protected Types inherited from sgpp::pde::UpDownOneOpDim
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::DataVector * coefs
Pointer to the sgpp::base::DataVector of the coefs.
const size_t numAlgoDims_
number of algorithmic dimensions
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Static Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
static const size_t maxParallelDims_ = TASKS_PARALLEL_UPDOWN
max number of parallel stages (dimension recursive calls)
Detailed Description
Implementation for linear functions of Laplace Operation, linear grids without boundaries.
Constructor & Destructor Documentation
OperationLaplaceLinearStretched()
sgpp::pde::OperationLaplaceLinearStretched::OperationLaplaceLinearStretched (sgpp::base::GridStorage * storage) explicit
Constructor of OperationLaplaceLinearStretched.
Parameters
storage Pointer to the grid's gridstorage obejct
~OperationLaplaceLinearStretched()
sgpp::pde::OperationLaplaceLinearStretched::~OperationLaplaceLinearStretched () virtual
Destructor.
Member Function Documentation
down()
void sgpp::pde::OperationLaplaceLinearStretched::down (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D down operation
Parameters
dim dimension in which to apply the down-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
downOpDim()
void sgpp::pde::OperationLaplaceLinearStretched::downOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D down operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that down-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
References alpha, and sgpp::pde::UpDownOneOpDim::storage.
Referenced by specialOP().
specialOP()
void sgpp::pde::OperationLaplaceLinearStretched::specialOP (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim, size_t op_dim) protected virtual
All calculations for gradient_dim, parallel version using OpenMP 3.
Parameters
alpha the coefficients of the grid points
result the result of the operations
dim the current dimension in the recursion
op_dim the dimension in that a special operation is applied
Reimplemented from sgpp::pde::UpDownOneOpDim.
References alpha, downOpDim(), sgpp::base::DataVector::getSize(), and sgpp::pde::UpDownOneOpDim::updown().
up()
void sgpp::pde::OperationLaplaceLinearStretched::up (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D up operation
Parameters
dim dimension in which to apply the up-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
upOpDim()
void sgpp::pde::OperationLaplaceLinearStretched::upOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D up operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that up-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplaceLinearStretched.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplaceLinearStretched.cpp