SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOnlineDE Class Reference
sgpp::datadriven::DBMatOnlineDE Class Reference abstract
Class that stores, generates and manipulates a density function during online phase in on/off learning.
#include <DBMatOnlineDE.hpp>
Public Member Functions
void computeDensityDifferenceFunction (DataVector &alpha, DataMatrix &mp, DataMatrix &mq, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool save_b=false, bool do_cv=false)
Computes the density difference function for two data matrix instances.
void computeDensityDifferenceFunction (DataVector &alpha, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool do_cv=false)
Computes the density difference function again based on the saved b's (only applicable for streaming)
void computeDensityFunction (DataVector &alpha, DataMatrix &m, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool save_b=false, bool do_cv=false)
Computes the density function for a certain data matrix.
void computeDensityFunction (DataVector &alpha, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool do_cv=false)
Computes the density function again based on the saved b's (only applicable for streaming)
void computeDensityFunctionParallel (DataVectorDistributed &alpha, DataMatrix &m, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, const ParallelConfiguration &parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool save_b=false, bool do_cv=false, std::list< size_t > *deletedPoints=nullptr, size_t newPoints=0)
Computes the density function for a certain data matrix in parallel using ScaLAPACK.
void computeDensityFunctionParallel (DataVectorDistributed &alpha, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, const ParallelConfiguration &parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool do_cv=false)
Computes the density function again based on the saved b's (only applicable for streaming) in parallel on a cluster using ScaLAPACK.
DataVector computeWeightedBFromBatch (DataMatrix &m, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool weighted)
Computes/updates the b vector for the given batch of data.
DataVectorDistributed computeWeightedBFromBatchParallel (DataMatrix &m, Grid &grid, const DensityEstimationConfiguration &densityEstimationConfig, const ParallelConfiguration &parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool weighted)
Computes/updates the b vector for the given batch of data in parallel using ScaLAPACK.
std::vector< DataVector > computeWeightedBFromBatchTwoDatasets (DataMatrix &mp, DataMatrix &mq, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool weighted)
Initializes the b vector for the given batch of data in two datasets scenarios.
DBMatOnlineDE (DBMatOffline &offline, Grid &grid, double lambda, double beta=0.)
Constructor.
double eval (DataVector &alpha, const DataVector &p, Grid &grid, bool force=false)
Evaluates the density function at a certain point.
void eval (DataVector &alpha, DataMatrix &values, DataVector &results, Grid &grid, bool force=false)
Evaluates the density function on multiple points.
void evalParallel (DataVector &alpha, DataMatrix &values, DataVectorDistributed &results, Grid &grid, bool force=false)
Evaluates the density function on multiple points using parallelization.
double getBeta ()
Returns the current weighting factor.
bool isComputed ()
Returns if the surplus has already been computed.
double normalize (DataVector &alpha, Grid &grid, size_t samples=1000)
Normalize the Density.
double normalizeQuadrature (DataVector &alpha, Grid &grid)
Normalize the Density using Quadrature.
void resetTraining ()
Resets the training state of the model.
void setBeta (double beta)
Sets the weighting factor.
virtual void syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the distributed decomposition, only has an effect if ScaLAPACK is used.
void updateRhs (size_t gridSize, std::vector< size_t > &deletedPoints)
Restructures the rhs (b vector) of the system matrix.
Public Member Functions inherited from sgpp::datadriven::DBMatOnline
DBMatOnline (const DBMatOnline &rhs)=delete
DBMatOnline (DBMatOffline &o)
Constructor.
DBMatOnline (DBMatOnline &&rhs)=default
DBMatOffline & getOfflineObject ()
Returns a reference to the offline object.
const DBMatOffline & getOfflineObject () const
DBMatOnline & operator= (const DBMatOnline &rhs)=delete
DBMatOnline & operator= (DBMatOnline &&rhs)=delete
void setLambda (double lambda)
virtual std::vector< size_t > updateSystemMatrixDecomposition (DensityEstimationConfiguration &densityEstimationConfig, Grid &grid, size_t numAddedGridPoints, std::vector< size_t > &deletedGridPointIndices, double lambda)
Update the system matrix decomposition after the grid has been modified.
virtual ~DBMatOnline ()=default
Destructor.
Protected Member Functions
double computeL2Error (DataVector &alpha, Grid &grid)
double resDensity (DataVector &alpha, Grid &grid)
virtual void solveSLE (DataVector &alpha, DataVector &b, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool do_cv)=0
virtual void solveSLEParallel (DataVectorDistributed &alpha, DataVectorDistributed &b, Grid &grid, DensityEstimationConfiguration &densityEstimationConfig, bool do_cv=0)=0
Protected Attributes
double beta
DataVector bSave
std::unique_ptr< DataVectorDistributed > bSaveDistributed
DataVector bSaveExtra
DataVector bTotalPoints
std::unique_ptr< DataVectorDistributed > bTotalPointsDistributed
DataVector bTotalPointsExtra
bool distributedVectorsInitialized
bool functionComputed
double lambda
bool localVectorsInitialized
double normFactor
size_t oDim
DataMatrix * testMat
DataMatrix * testMatRes
bool useExtraLocalVectors
Protected Attributes inherited from sgpp::datadriven::DBMatOnline
DBMatOffline & offlineObject
Detailed Description
Class that stores, generates and manipulates a density function during online phase in on/off learning.
Constructor & Destructor Documentation
DBMatOnlineDE()
sgpp::datadriven::DBMatOnlineDE::DBMatOnlineDE (DBMatOffline & offline, Grid & grid, double lambda, double beta = 0.) explicit
Constructor.
Parameters
offline The offline object we base our evaluations on.
grid The underlying grid (TODO(fuchsgruber) do we need this?)
lambda The regularization strength (TODO(fuchsgruber) remove this)
beta The initial weighting factor
References functionComputed, grid(), and oDim.
Member Function Documentation
computeDensityDifferenceFunction() [1/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction (DataVector & alpha, DataMatrix & mp, DataMatrix & mq, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool save_b = false, bool do_cv = false)
Computes the density difference function for two data matrix instances.
Parameters
alpha the vector where surplusses for the density function will be stored
mp the matrix that contains the data points for the first input dataset
mq the matrix that contains the data points for the second input dataset
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
save_b Indicates whether the old right hand side should be saved and combined with the new right hand side (aka streaming)
do_cv Indicates whether crossvalidation should take place
References alpha, beta, bSave, bSaveExtra, bTotalPoints, bTotalPointsExtra, computeWeightedBFromBatchTwoDatasets(), functionComputed, sgpp::base::DataVector::get(), sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), grid(), localVectorsInitialized, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::base::DataVector::set(), solveSLE(), and useExtraLocalVectors.
computeDensityDifferenceFunction() [2/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction (DataVector & alpha, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool do_cv = false)
Computes the density difference function again based on the saved b's (only applicable for streaming)
Parameters
alpha the vector where surplusses for the density function will be stored
grid The underlying grid
densityEstimationConfig Configuration for the density estimation combined with the new right hand side (aka streaming)
do_cv Indicates whether crossvalidation should take place
References alpha, bSave, bSaveExtra, bTotalPoints, bTotalPointsExtra, functionComputed, sgpp::base::DataVector::get(), grid(), and solveSLE().
computeDensityFunction() [1/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityFunction (DataVector & alpha, DataMatrix & m, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool save_b = false, bool do_cv = false)
Computes the density function for a certain data matrix.
Parameters
alpha the vector where surplusses for the density function will be stored
m the matrix that contains the data points
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
save_b Indicates whether the old right hand side should be saved and combined with the new right hand side (aka streaming)
do_cv Indicates whether crossvalidation should take place
References alpha, beta, bSave, bTotalPoints, computeWeightedBFromBatch(), functionComputed, sgpp::base::DataVector::get(), sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::base::DataMatrix::getNcols(), grid(), localVectorsInitialized, m, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::base::DataVector::set(), and solveSLE().
computeDensityFunction() [2/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityFunction (DataVector & alpha, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool do_cv = false)
Computes the density function again based on the saved b's (only applicable for streaming)
Parameters
alpha the vector where surplusses for the density function will be stored
grid The underlying grid
densityEstimationConfig Configuration for the density estimation combined with the new right hand side (aka streaming)
do_cv Indicates whether crossvalidation should take place
References alpha, bSave, bTotalPoints, functionComputed, sgpp::base::DataVector::get(), grid(), and solveSLE().
computeDensityFunctionParallel() [1/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityFunctionParallel (DataVectorDistributed & alpha, DataMatrix & m, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, const ParallelConfiguration & parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool save_b = false, bool do_cv = false, std::list< size_t > * deletedPoints = nullptr, size_t newPoints = 0)
Computes the density function for a certain data matrix in parallel using ScaLAPACK.
Parameters
alpha the distributed vector where surplusses for the density function will be stored
m the matrix that contains the data points, currently every process has to have the data points
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
parallelConfig configuration for ScaLAPACK
processGrid pointer to BlacsProcessGrid
save_b Indicates whether the old right hand side should be saved and combined with the new right hand side (aka streaming)
do_cv Indicates whether crossvalidation should take place
deletedPoints indicates the indices of removed grid points due to coarsening
newPoints indicates the amount of added points due to refinement
References alpha, beta, bSaveDistributed, bTotalPointsDistributed, computeWeightedBFromBatchParallel(), distributedVectorsInitialized, functionComputed, sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::base::DataMatrix::getNcols(), grid(), m, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::datadriven::ParallelConfiguration::rowBlockSize_, and solveSLEParallel().
computeDensityFunctionParallel() [2/2]
void sgpp::datadriven::DBMatOnlineDE::computeDensityFunctionParallel (DataVectorDistributed & alpha, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, const ParallelConfiguration & parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool do_cv = false)
Computes the density function again based on the saved b's (only applicable for streaming) in parallel on a cluster using ScaLAPACK.
Parameters
alpha the vector where surplusses for the density function will be stored
grid The underlying grid
densityEstimationConfig Configuration for the density estimation combined with the new right hand side (aka streaming)
parallelConfig configuration for ScaLAPACK
processGrid pointer to BlacsProcessGrid
do_cv Indicates whether crossvalidation should take place
References alpha, bSaveDistributed, bTotalPointsDistributed, functionComputed, grid(), sgpp::datadriven::ParallelConfiguration::rowBlockSize_, and solveSLEParallel().
computeL2Error()
double sgpp::datadriven::DBMatOnlineDE::computeL2Error (DataVector & alpha, Grid & grid) protected
References eval(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid(), testMat, and testMatRes.
computeWeightedBFromBatch()
DataVector sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch (DataMatrix & m, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool weighted)
Computes/updates the b vector for the given batch of data.
Parameters
m the matrix that contains the data points
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
weighted Flag to decide whether to weight the b vector with the no. of points
References sgpp::op_factory::createOperationMultipleEval(), sgpp::op_factory::createOperationMultipleEvalInter(), sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::datadriven::DBMatOnlineDE_SMW::getB(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::getB(), sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::base::DataMatrix::getNcols(), grid(), sgpp::datadriven::DBMatOffline::interactions, sgpp::datadriven::LU, m, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::datadriven::OrthoAdapt, sgpp::datadriven::SMW_chol, and sgpp::datadriven::SMW_ortho.
Referenced by computeDensityFunction().
computeWeightedBFromBatchParallel()
DataVectorDistributed sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchParallel (DataMatrix & m, Grid & grid, const DensityEstimationConfiguration & densityEstimationConfig, const ParallelConfiguration & parallelConfig, std::shared_ptr< BlacsProcessGrid > processGrid, bool weighted)
Computes/updates the b vector for the given batch of data in parallel using ScaLAPACK.
Parameters
m the matrix that contains the data points, currently every process has to have the data points
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
parallelConfig ScaLAPACK configuration
processGrid process grid for ScaLAPACK
weighted Flag to decide whether to weight the b vector with the no. of points
References sgpp::op_factory::createOperationMultipleEval(), sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::datadriven::DBMatOnlineDEOrthoAdapt::getB(), sgpp::datadriven::DBMatOnlineDE_SMW::getBDistributed(), sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::datadriven::DataMatrixDistributed::getGlobalCols(), sgpp::base::DataMatrix::getNcols(), grid(), sgpp::datadriven::DBMatOffline::interactions, m, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::datadriven::OrthoAdapt, sgpp::datadriven::ParallelConfiguration::rowBlockSize_, sgpp::datadriven::SCALAPACK, sgpp::datadriven::SMW_chol, and sgpp::datadriven::SMW_ortho.
Referenced by computeDensityFunctionParallel().
computeWeightedBFromBatchTwoDatasets()
std::vector< DataVector > sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets (DataMatrix & mp, DataMatrix & mq, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool weighted)
Initializes the b vector for the given batch of data in two datasets scenarios.
Does not compute the actual b, but initializes it and computes the two dataset contributions bp and bq. All these three vectors are returned, in this order, if weighted is false. Otherwise, only the final b is returned and usable in the std::vector.
Parameters
mp the matrix that contains the first data points
mq the matrix that contains the second data points
grid The underlying grid
densityEstimationConfig Configuration for the density estimation
weighted Flag to decide whether to weight the b vector with the no. of points
References sgpp::op_factory::createOperationMultipleEval(), sgpp::op_factory::createOperationMultipleEvalInter(), sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::base::DataVector::get(), sgpp::datadriven::DBMatOnlineDE_SMW::getB(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::getB(), sgpp::datadriven::DBMatOffline::getDecomposedMatrix(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), grid(), sgpp::datadriven::DBMatOffline::interactions, sgpp::datadriven::LU, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::datadriven::OrthoAdapt, sgpp::base::DataVector::setAll(), sgpp::datadriven::SMW_chol, and sgpp::datadriven::SMW_ortho.
Referenced by computeDensityDifferenceFunction().
eval() [1/2]
double sgpp::datadriven::DBMatOnlineDE::eval (DataVector & alpha, const DataVector & p, Grid & grid, bool force = false)
Evaluates the density function at a certain point.
Parameters
alpha the vector of surplusses
p the point at which the function is evaluated
grid the underlying grid
force if set, it will even try to evaluate if the internal state recommends otherwise
Returns
the result of the evaluation
References alpha, sgpp::op_factory::createOperationEval(), functionComputed, grid(), and normFactor.
Referenced by computeL2Error(), python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), and normalize().
eval() [2/2]
void sgpp::datadriven::DBMatOnlineDE::eval (DataVector & alpha, DataMatrix & values, DataVector & results, Grid & grid, bool force = false)
Evaluates the density function on multiple points.
Parameters
alpha the vector of surplusses
values the points at which the function is evaluated
results the result of the evaluation
grid the underlying grid
force if set, it will even try to evaluate if the internal state recommends otherwise
References alpha, sgpp::op_factory::createOperationMultipleEval(), sgpp::op_factory::createOperationMultipleEvalInter(), functionComputed, grid(), sgpp::datadriven::DBMatOffline::interactions, sgpp::base::DataVector::mult(), normFactor, and sgpp::datadriven::DBMatOnline::offlineObject.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalParallel()
void sgpp::datadriven::DBMatOnlineDE::evalParallel (DataVector & alpha, DataMatrix & values, DataVectorDistributed & results, Grid & grid, bool force = false)
Evaluates the density function on multiple points using parallelization.
Parameters
alpha the vector of surplusses
values the points at which the function is evaluated
results the result of the evaluation
grid the underlying grid
force if set, it will even try to evaluate if the internal state recommends otherwise
References alpha, sgpp::op_factory::createOperationMultipleEval(), functionComputed, grid(), sgpp::datadriven::DBMatOffline::interactions, normFactor, sgpp::datadriven::DBMatOnline::offlineObject, sgpp::datadriven::SCALAPACK, and sgpp::datadriven::DataVectorDistributed::scale().
getBeta()
double sgpp::datadriven::DBMatOnlineDE::getBeta ()
Returns the current weighting factor.
References beta.
isComputed()
bool sgpp::datadriven::DBMatOnlineDE::isComputed ()
Returns if the surplus has already been computed.
References functionComputed.
normalize()
double sgpp::datadriven::DBMatOnlineDE::normalize (DataVector & alpha, Grid & grid, size_t samples = 1000)
Normalize the Density.
Parameters
alpha the vector of surplusses
grid the underlying grid
samples number of samples to be used for MC quadrature
References eval(), grid(), normFactor, and oDim.
normalizeQuadrature()
double sgpp::datadriven::DBMatOnlineDE::normalizeQuadrature (DataVector & alpha, Grid & grid)
Normalize the Density using Quadrature.
Parameters
alpha the vector of surplusses
grid the underlying grid
References alpha, sgpp::op_factory::createOperationQuadrature(), sgpp::base::OperationQuadrature::doQuadrature(), grid(), and normFactor.
resDensity()
double sgpp::datadriven::DBMatOnlineDE::resDensity (DataVector & alpha, Grid & grid) protected
References alpha, sgpp::op_factory::createOperationIdentity(), sgpp::datadriven::DensitySystemMatrix::generateb(), sgpp::base::DataVector::getSize(), grid(), sgpp::base::DataVector::l2Norm(), sgpp::datadriven::DensitySystemMatrix::mult(), and testMat.
resetTraining()
void sgpp::datadriven::DBMatOnlineDE::resetTraining ()
Resets the training state of the model.
References distributedVectorsInitialized, functionComputed, and localVectorsInitialized.
setBeta()
void sgpp::datadriven::DBMatOnlineDE::setBeta (double beta)
Sets the weighting factor.
Parameters
beta the new weighting factor. If set to 0, no plasticity takes place.
References beta.
solveSLE()
virtual void sgpp::datadriven::DBMatOnlineDE::solveSLE (DataVector & alpha, DataVector & b, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool do_cv) protected pure virtual
Implemented in sgpp::datadriven::DBMatOnlineDE_SMW, sgpp::datadriven::DBMatOnlineDEChol, and sgpp::datadriven::DBMatOnlineDEOrthoAdapt.
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), computeDensityFunction(), and computeDensityFunction().
solveSLEParallel()
virtual void sgpp::datadriven::DBMatOnlineDE::solveSLEParallel (DataVectorDistributed & alpha, DataVectorDistributed & b, Grid & grid, DensityEstimationConfiguration & densityEstimationConfig, bool do_cv = 0) protected pure virtual
Implemented in sgpp::datadriven::DBMatOnlineDE_SMW, sgpp::datadriven::DBMatOnlineDEChol, and sgpp::datadriven::DBMatOnlineDEOrthoAdapt.
Referenced by computeDensityFunctionParallel(), and computeDensityFunctionParallel().
syncDistributedDecomposition()
void sgpp::datadriven::DBMatOnlineDE::syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) virtual
Synchronizes the distributed decomposition, only has an effect if ScaLAPACK is used.
Reimplemented in sgpp::datadriven::DBMatOnlineDE_SMW, and sgpp::datadriven::DBMatOnlineDEOrthoAdapt.
References sgpp::datadriven::DBMatOnline::offlineObject, and sgpp::datadriven::DBMatOffline::syncDistributedDecomposition().
updateRhs()
void sgpp::datadriven::DBMatOnlineDE::updateRhs (size_t gridSize, std::vector< size_t > & deletedPoints)
Restructures the rhs (b vector) of the system matrix.
This is only availible for streaming, i.e. when computeDensityFunction was called with save_b = true. First b is coarsened, then extended according to the new grid size (refinement).
Parameters
gridSize grid size after coarsening and refinement (inherently gives the number of points added during refinement after coarsening)
deletedPoints pointer to list of indexes that will be removed from b
References bSave, bSaveDistributed, bSaveExtra, bTotalPoints, bTotalPointsDistributed, bTotalPointsExtra, distributedVectorsInitialized, functionComputed, localVectorsInitialized, sgpp::base::DataVector::remove(), sgpp::base::DataVector::resizeZero(), and useExtraLocalVectors.
Member Data Documentation
beta
double sgpp::datadriven::DBMatOnlineDE::beta protected
Referenced by computeDensityDifferenceFunction(), computeDensityFunction(), computeDensityFunctionParallel(), getBeta(), and setBeta().
bSave
DataVector sgpp::datadriven::DBMatOnlineDE::bSave protected
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), computeDensityFunction(), computeDensityFunction(), and updateRhs().
bSaveDistributed
std::unique_ptr<DataVectorDistributed> sgpp::datadriven::DBMatOnlineDE::bSaveDistributed protected
Referenced by computeDensityFunctionParallel(), computeDensityFunctionParallel(), and updateRhs().
bSaveExtra
DataVector sgpp::datadriven::DBMatOnlineDE::bSaveExtra protected
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), and updateRhs().
bTotalPoints
DataVector sgpp::datadriven::DBMatOnlineDE::bTotalPoints protected
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), computeDensityFunction(), computeDensityFunction(), and updateRhs().
bTotalPointsDistributed
std::unique_ptr<DataVectorDistributed> sgpp::datadriven::DBMatOnlineDE::bTotalPointsDistributed protected
Referenced by computeDensityFunctionParallel(), computeDensityFunctionParallel(), and updateRhs().
bTotalPointsExtra
DataVector sgpp::datadriven::DBMatOnlineDE::bTotalPointsExtra protected
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), and updateRhs().
distributedVectorsInitialized
bool sgpp::datadriven::DBMatOnlineDE::distributedVectorsInitialized protected
Referenced by computeDensityFunctionParallel(), resetTraining(), and updateRhs().
functionComputed
bool sgpp::datadriven::DBMatOnlineDE::functionComputed protected
Referenced by computeDensityDifferenceFunction(), computeDensityDifferenceFunction(), computeDensityFunction(), computeDensityFunction(), computeDensityFunctionParallel(), computeDensityFunctionParallel(), DBMatOnlineDE(), eval(), eval(), evalParallel(), isComputed(), resetTraining(), and updateRhs().
lambda
double sgpp::datadriven::DBMatOnlineDE::lambda protected
Referenced by sgpp::datadriven::DBMatOnlineDEChol::buildCholSolver(), sgpp::datadriven::DBMatOnlineDEChol::solveSLE(), sgpp::datadriven::DBMatOnlineDEChol::solveSLEParallel(), sgpp::datadriven::DBMatOnlineDE_SMW::updateSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDEChol::updateSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::updateSystemMatrixDecomposition(), and sgpp::datadriven::DBMatOnlineDE_SMW::updateSystemMatrixDecompositionParallel().
localVectorsInitialized
bool sgpp::datadriven::DBMatOnlineDE::localVectorsInitialized protected
Referenced by computeDensityDifferenceFunction(), computeDensityFunction(), resetTraining(), and updateRhs().
normFactor
double sgpp::datadriven::DBMatOnlineDE::normFactor protected
Referenced by eval(), eval(), evalParallel(), normalize(), and normalizeQuadrature().
oDim
size_t sgpp::datadriven::DBMatOnlineDE::oDim protected
Referenced by DBMatOnlineDE(), and normalize().
testMat
DataMatrix* sgpp::datadriven::DBMatOnlineDE::testMat protected
Referenced by computeL2Error(), and resDensity().
testMatRes
DataMatrix * sgpp::datadriven::DBMatOnlineDE::testMatRes protected
Referenced by computeL2Error().
useExtraLocalVectors
bool sgpp::datadriven::DBMatOnlineDE::useExtraLocalVectors protected
Referenced by computeDensityDifferenceFunction(), and updateRhs().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatOnlineDE.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatOnlineDE.cpp