SG++-Doxygen-Documentation: sgpp::base::OperationEvalModLinearNaive Class Reference
sgpp::base::OperationEvalModLinearNaive Class Reference
#include <OperationEvalModLinearNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalModLinearNaive (GridStorage &storage)
Constructor.
~OperationEvalModLinearNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SLinearModifiedBase base
1D linear basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Constructor & Destructor Documentation
OperationEvalModLinearNaive()
sgpp::base::OperationEvalModLinearNaive::OperationEvalModLinearNaive (GridStorage & storage) inline explicit
Constructor.
Parameters
storage storage of the sparse grid
~OperationEvalModLinearNaive()
sgpp::base::OperationEvalModLinearNaive::~OperationEvalModLinearNaive () inline override
Destructor.
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalModLinearNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearModifiedBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalModLinearNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearModifiedBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SLinearModifiedBase sgpp::base::OperationEvalModLinearNaive::base protected
1D linear basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalModLinearNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalModLinearNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalModLinearNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalModLinearNaive.cpp