SG++-Doxygen-Documentation: sgpp::base::DataVector Class Reference
sgpp::base::DataVector Class Reference
A class to store one-dimensional data.
#include <DataVector.hpp>
Public Member Functions
void abs ()
Sets all elements to their absolute value.
void accumulate (const DataVector &vec)
void add (const DataVector &vec)
Adds the values from another DataVector to the current values.
size_t append ()
Appends a new element and returns index of it.
void append (DataVector::iterator first, DataVector::iterator last)
Appends sequence of elements from another DataVector given by iterators.
size_t append (double value)
Appends a new element and returns index of new element.
void axpy (double a, DataVector &x)
Adds a*x to current vector.
void componentwise_div (const DataVector &vec)
Divides the current DataVector component-wise by another DataVector.
void componentwise_mult (const DataVector &vec)
Multiplies the current DataVector component-wise with another DataVector.
void copyFrom (const DataVector &vec)
Copies the data from another DataVector vec.
DataVector ()
Create an empty DataVector.
DataVector (const DataVector &)=default
Copy constructor.
DataVector (DataVector &&)=default
Move constructor.
DataVector (double *input, size_t size)
Create a new DataVector from a double array with size elements.
DataVector (size_t size)
Create a DataVector with size elements (uninitialized values).
DataVector (size_t size, double value)
Create a DataVector with size elements and initializes all elements with the same value.
DataVector (std::initializer_list< double > input)
Create a new DataVector from a std::initializer_list<double>.
DataVector (std::vector< double > input)
Create a new DataVector from a std::vector<double>.
DataVector (std::vector< int > input)
Create a new DataVector from a std::vector<int>.
double dotProduct (const DataVector &vec) const
Returns the dot product of the two vectors.
double get (size_t i) const
Returns the i-th element.
size_t getNumberNonZero () const
Determines the number of non-zero elements in the vector.
double * getPointer ()
gets a pointer to the data array
const double * getPointer () const
gets a const pointer to the data array
size_t getSize () const
gets the elements stored in the vector
void insert (size_t index, double value)
Inserts a new element at the given index.
double l2Norm () const
Returns the vector's \(l^2\)-norm, i.e., \(\sqrt{ \sum_i x_i^2 }\).
double max () const
Returns the maximum over all entries.
double maxNorm () const
calculates the vector's max norm
double min () const
Returns the minimum over all entries.
void minmax (double *min, double *max) const
Determines minimum and maximum over all entries.
void mult (double scalar)
multiplies all elements by a constant factor
void normalize ()
Normalizes vector entries to [0,1].
void normalize (double border)
Normalizes vector entries to [border, 1-border].
DataVector & operator= (const DataVector &)=default
Copy assignment operator.
DataVector & operator= (DataVector &&)=default
Move assignment operator.
void partitionClasses (double threshold)
Partitions vector into two classes using a choosen border.
void remove (std::vector< size_t > &indexesToRemove)
Removes indexes form the vector.
void resizeZero (size_t nrows)
Resizes the DataVector to size elements.
void restructure (std::vector< size_t > &remainingIndex)
Resizes the DataVector by removing entries.
double RMSNorm () const
Returns the vector's root mean square (RMS)-norm, i.e., \(\sqrt{ 1/N \sum_{i=1}^N x_i^2 }\).
void set (size_t i, double value)
Sets the element at index i to value.
void setAll (double value)
Sets all values of DataVector to value.
void sqr ()
Squares all elements of the DataVector.
void sqrt ()
Takes the square root of all elements of the DataVector.
void sub (const DataVector &vec)
Subtracts the values from another DataVector of the current values.
double sum () const
Returns the sum of all elements.
void toFile (const std::string &fileName) const
std::string toString () const
Returns a description of the DataVector as a string.
void toString (std::string &text) const
Writes the data stored in the DataVector into a string.
~DataVector ()=default
Destructor.
Static Public Member Functions
static DataVector fromFile (const std::string &fileName)
static DataVector fromString (const std::string &serializedVector)
Detailed Description
A class to store one-dimensional data.
Typically, an object of type DataVector will contain an array of (hierarchical) coefficients (or surplusses), or the coordinates of a data point at which a sparse grid function should be evaluated.
Constructor & Destructor Documentation
DataVector() [1/9]
sgpp::base::DataVector::DataVector ()
Create an empty DataVector.
DataVector() [2/9]
sgpp::base::DataVector::DataVector (const DataVector &) default
Copy constructor.
DataVector() [3/9]
sgpp::base::DataVector::DataVector (DataVector &&) default
Move constructor.
~DataVector()
sgpp::base::DataVector::~DataVector () default
Destructor.
DataVector() [4/9]
sgpp::base::DataVector::DataVector (size_t size) explicit
Create a DataVector with size elements (uninitialized values).
Parameters
size Number of elements
DataVector() [5/9]
sgpp::base::DataVector::DataVector (size_t size, double value)
Create a DataVector with size elements and initializes all elements with the same value.
Parameters
size Number of elements
value Value for all entries
DataVector() [6/9]
sgpp::base::DataVector::DataVector (double * input, size_t size)
Create a new DataVector from a double array with size elements.
Parameters
input double array that contains the data
size number of elements
DataVector() [7/9]
sgpp::base::DataVector::DataVector (std::vector< double > input) explicit
Create a new DataVector from a std::vector<double>.
Parameters
input std::vector<double> that contains the data
DataVector() [8/9]
sgpp::base::DataVector::DataVector (std::initializer_list< double > input) explicit
Create a new DataVector from a std::initializer_list<double>.
Parameters
input std::initializer_list<double> that contains the data
DataVector() [9/9]
sgpp::base::DataVector::DataVector (std::vector< int > input) explicit
Create a new DataVector from a std::vector<int>.
Parameters
input std::vector<int> that contains the data
Member Function Documentation
abs()
void sgpp::base::DataVector::abs ()
Sets all elements to their absolute value.
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::solver::LassoFunction::eval(), and sgpp::base::VectorSurplusRefinementFunctor::operator()().
accumulate()
void sgpp::base::DataVector::accumulate (const DataVector & vec)
add()
void sgpp::base::DataVector::add (const DataVector & vec)
Adds the values from another DataVector to the current values.
Modifies the current values.
Parameters
vec The DataVector which is added to the current values
Referenced by sgpp::datadriven::PrimalDualSVM::add(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixInner(), sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::datadriven::ModelFittingDensityEstimationCombi::evaluate(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::StdUpDown::mult(), sgpp::pde::UpDownFourOpDims::mult(), sgpp::pde::UpDownOneOpDim::mult(), sgpp::pde::UpDownOneOpDimWithShadow::mult(), sgpp::pde::UpDownTwoOpDims::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose(), sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed(), sgpp::pde::StdUpDown::multParallelBuildingBlock(), sgpp::pde::UpDownOneOpDim::multParallelBuildingBlock(), sgpp::pde::UpDownTwoOpDims::multParallelBuildingBlock(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::datadriven::BayesianOptimization::setScales(), sgpp::solver::Fista< F >::solve(), sgpp::solver::ConjugateGradients::solve(), sgpp::pde::UpDownOneOpDim::specialOP(), sgpp::pde::UpDownOneOpDimWithShadow::specialOP(), sgpp::pde::UpDownTwoOpDims::specialOpOne(), sgpp::pde::UpDownTwoOpDims::specialOpOneAndOpTwo(), sgpp::pde::UpDownTwoOpDims::specialOpTwo(), sgpp::pde::UpDownFourOpDims::specialOpX(), sgpp::optimization::ResponseSurface::transformPoint(), sgpp::optimization::ResponseSurfaceVector::transformPoint(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update(), sgpp::pde::StdUpDown::updown(), sgpp::pde::UpDownOneOpDim::updown(), sgpp::pde::UpDownOneOpDimWithShadow::updown(), and sgpp::pde::UpDownTwoOpDims::updown().
append() [1/3]
size_t sgpp::base::DataVector::append ()
Appends a new element and returns index of it.
Returns
Index of new element
References append().
Referenced by sgpp::datadriven::PrimalDualSVM::add(), append(), sgpp::base::DataMatrix::fromString(), fromString(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::optimization::optimizer::DifferentialEvolution::optimize(), sgpp::optimization::optimizer::GradientDescent::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), sgpp::optimization::optimizer::NelderMead::optimize(), sgpp::optimization::optimizer::Newton::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), sgpp::solver::Euler::solve(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::LearnerSGDE::trainOnline(), sgpp::base::ForwardSelectorRefinementIndicator::update(), and sgpp::base::ImpurityRefinementIndicator::update().
append() [2/3]
void sgpp::base::DataVector::append (DataVector::iterator first, DataVector::iterator last)
Appends sequence of elements from another DataVector given by iterators.
Parameters
first iterator pointing to the first element of the sequence
last iterator pointing to the last element of the sequence
References insert().
append() [3/3]
size_t sgpp::base::DataVector::append (double value)
Appends a new element and returns index of new element.
Parameters
value Value of new element
Returns
Index of new element
axpy()
void sgpp::base::DataVector::axpy (double a, DataVector & x)
Adds a*x to current vector.
BLAS Level 1 (elementary vector operations) operation: axpy.
Parameters
a A scalar
x Reference to the DataVector
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::DensityDifferenceSystemMatrix::generateb(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::datadriven::DensityDifferenceSystemMatrix::mult(), sgpp::datadriven::DensitySystemMatrix::mult(), sgpp::datadriven::DMSystemMatrix::mult(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::mult(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::mult(), sgpp::datadriven::DMWeightMatrix::mult(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::mult(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::UpDownFourOpDims::mult(), sgpp::pde::UpDownOneOpDim::mult(), sgpp::pde::UpDownTwoOpDims::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), sgpp::pde::UpDownOneOpDim::multParallelBuildingBlock(), sgpp::pde::UpDownTwoOpDims::multParallelBuildingBlock(), sgpp::solver::BiCGStab::solve(), sgpp::solver::ConjugateGradients::solve(), sgpp::solver::BiCGStabSP::solve(), sgpp::solver::ConjugateGradientsSP::solve(), and sgpp::datadriven::LearnerSGD::train().
componentwise_div()
void sgpp::base::DataVector::componentwise_div (const DataVector & vec)
Divides the current DataVector component-wise by another DataVector.
Modifies the current values. Performs
for i from 1 to this.getSize()
  this[i] /= vec[i]
Note: No check for division by zero!
Parameters
vec the DataVector which the current DataVector is divided by
Referenced by sgpp::optimization::ResponseSurface::transformPoint(), sgpp::optimization::ResponseSurfaceVector::transformPoint(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), and sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update().
componentwise_mult()
void sgpp::base::DataVector::componentwise_mult (const DataVector & vec)
Multiplies the current DataVector component-wise with another DataVector.
Modifies the current values. Performs
for i from 1 to this.getSize()
  this[i] *= vec[i]
Parameters
vec the DataVector which is multiplied to current DataVector
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::DMWeightMatrix::generateb(), l2Norm(), sgpp::datadriven::OperationRegularizationDiagonal::mult(), sgpp::datadriven::DMWeightMatrix::mult(), sgpp::pde::PDESolver::refineInitialGridSurplusSubDomain(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevelSubDomain(), sgpp::optimization::ResponseSurface::transformPoint(), and sgpp::optimization::ResponseSurfaceVector::transformPoint().
copyFrom()
void sgpp::base::DataVector::copyFrom (const DataVector & vec)
Copies the data from another DataVector vec.
Disregards the number of entries set for the two vectors, i.e., just copies the data entry by entry. If the size matches, the current DataVector is an exact copy of vec. If not, as many elements as possible are copied, and everything else is left untouched.
Parameters
vec The source DataVector containing the data
Referenced by sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::base::OperationEvalModLinear::eval(), sgpp::datadriven::PolynomialChaosExpansion::getVariance(), sgpp::datadriven::OperationRegularizationDiagonal::mult(), sgpp::datadriven::DBMatOnlineDEChol::solveSLEParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), and sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel().
dotProduct()
double sgpp::base::DataVector::dotProduct (const DataVector & vec) const
Returns the dot product of the two vectors.
Parameters
vec Reference to another vector
Returns
The dot-product
References sum().
Referenced by sgpp::datadriven::PrimalDualSVM::add(), sgpp::combigrid::CombinationGrid::combineValues(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::solver::RidgeFunction::eval(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::BayesianOptimization::likelihood(), sgpp::optimization::optimizer::lineSearchArmijo(), sgpp::datadriven::BayesianOptimization::mean(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::datadriven::PrimalDualSVM::predictRaw(), sgpp::solver::BiCGStab::solve(), sgpp::solver::ConjugateGradients::solve(), sgpp::base::sle_solver::BiCGStab::solve(), sgpp::datadriven::LearnerSGD::train(), sgpp::solver::StepsizeControl::twoNorm(), and sgpp::datadriven::BayesianOptimization::var().
fromFile()
DataVector sgpp::base::DataVector::fromFile (const std::string & fileName) static
References f, fileName, and fromString().
fromString()
DataVector sgpp::base::DataVector::fromString (const std::string & serializedVector) static
References append().
Referenced by fromFile(), and sgpp::datadriven::MultipleEvalHPX::LocalityMultiplier::mult().
get()
double sgpp::base::DataVector::get (size_t i) const inline
Returns the i-th element.
Parameters
i position of the element
Returns
data[i]
Referenced by sgpp::base::DirichletUpdateVector::applyDirichletConditions(), sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::base::DirichletGridConverter::calcInnerCoefs(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyForwardSolve(), sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunction(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), sgpp::base::PrecisionConverter::convertDataVectorToDataVectorSP(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::LearnerSGDEOnOffParallel::getAccuracy(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracy(), sgpp::datadriven::LearnerSGDE::getAccuracy(), sgpp::datadriven::LearnerBase::getAccuracy(), sgpp::datadriven::LearnerSVM::getAccuracy(), sgpp::datadriven::LearnerSGD::getAccuracy(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracyBL(), sgpp::datadriven::LearnerSGD::getBatchError(), sgpp::datadriven::LearnerBase::getCassificatorQuality(), sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), sgpp::datadriven::LearnerSGD::getError(), sgpp::datadriven::LearnerSVM::getError(), sgpp::datadriven::AlgorithmAdaBoostBase::getMaxGridPoint(), sgpp::datadriven::AlgorithmAdaBoostBase::getMeanGridPoint(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::datadriven::AlgorithmAdaBoostBase::getROC(), sgpp::datadriven::AlgorithmAdaBoostBase::getSumGridPoint(), sgpp::datadriven::LearnerSGDE::getSurpluses(), sgpp::datadriven::RefinementHandler::handleSurplusBasedRefinement(), sgpp::datadriven::MetaLearner::learnAndCompareString(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::OperationDensityMargTo1D::margToDimXs(), sgpp::datadriven::Accuracy::measure(), sgpp::datadriven::NegativeLogLikelihood::measure(), sgpp::datadriven::Accuracy::measureLowerIsBetter(), sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues(), sgpp::pde::UpDownOneOpDim::mult(), sgpp::base::DirichletUpdateVector::multiply(), sgpp::base::DirichletUpdateVector::multiplyBoundary(), sgpp::base::DirichletUpdateVector::multiplyBoundaryVector(), sgpp::pde::UpDownOneOpDim::multParallelBuildingBlock(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::ImpurityRefinementIndicator::operator()(), sgpp::base::PredictiveRefinementIndicator::operator()(), sgpp::base::ForwardSelectorRefinementIndicator::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::datadriven::LearnerSGD::predict(), sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs(), sgpp::datadriven::VisualizerClassification::runVisualization(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataMatrix::setRow(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::pde::PoissonEquationSolver::storeInnerRHS(), sgpp::pde::HeatEquationSolver::storeInnerRHS(), sgpp::pde::PoissonEquationSolver::storeInnerSolution(), sgpp::pde::HeatEquationSolver::storeInnerSolution(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::test_calculateROCcurve(), sgpp::datadriven::LearnerSGDE::train(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::LearnerSGDE::trainOnline(), sgpp::datadriven::ModelFittingClassification::update(), sgpp::base::ForwardSelectorRefinementIndicator::update(), sgpp::base::ImpurityRefinementIndicator::update(), sgpp::base::DirichletGridConverter::updateBoundaryCoefs(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), and sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel().
getNumberNonZero()
size_t sgpp::base::DataVector::getNumberNonZero () const
Determines the number of non-zero elements in the vector.
Returns
The number of non-zero elements
getPointer() [1/2]
double * sgpp::base::DataVector::getPointer ()
gets a pointer to the data array
Returns
pointer to the data array
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatDMSChol::choleskyDowndate(), sgpp::datadriven::DBMatDMSChol::choleskyUpdate(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadratureFunc(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), sgpp::solver::StepsizeControl::maxNorm(), sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multImpl(), sgpp::datadriven::OperationMultiEvalMPI::multSlave(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multTransposeImpl(), sgpp::optimization::SplineResponseSurface::optimize(), sgpp::datadriven::DBMatDMS_SMW::solve(), sgpp::datadriven::DBMatDMSOrthoAdapt::solve(), sgpp::base::sle_solver::solveInternal(), sgpp::datadriven::LearnerSGD::train(), and sgpp::optimization::file_io::writeVector().
getPointer() [2/2]
const double * sgpp::base::DataVector::getPointer () const
gets a const pointer to the data array
Returns
const pointer to the data array
getSize()
size_t sgpp::base::DataVector::getSize () const inline
gets the elements stored in the vector
Deprecated:
in favour of the equivalent size() method
Returns
elements stored in the vector
Referenced by sgpp::base::DataMatrix::addReduce(), sgpp::base::DataMatrix::addReduce(), sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), sgpp::base::DataMatrix::appendCol(), sgpp::base::DataMatrix::appendRow(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixInner(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyDowndate(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyForwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyUpdate(), sgpp::datadriven::LearnerSGDE::computeResidual(), sgpp::datadriven::SparseGridDensityEstimator::computeResidual(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), python.uq.uq_setting.UQSetting.UQSetting::convert(), sgpp::base::PrecisionConverter::convertDataVectorToDataVectorSP(), sgpp::base::HashGenerator::decodeCoords(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), doAllRefinements(), doAllRefinements(), doAllRefinements(), doAllRefinements(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_start_dimX(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_start_dimX(), sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature(), sgpp::solver::ElasticNetFunction::eval(), sgpp::solver::GroupLassoFunction::eval(), sgpp::optimization::SplineResponseSurface::evalGradient(), sgpp::pde::PDESolver::evaluateCuboid(), sgpp::optimization::InterpolatedFuzzyInterval::evaluateMembershipFunction(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::findNodesWithNegativeCoefficients(), sgpp::base::DataMatrix::fromString(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::datadriven::DensityDifferenceSystemMatrix::generateb(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::datadriven::LearnerSGDEOnOffParallel::getAccuracy(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracy(), sgpp::datadriven::LearnerSGDE::getAccuracy(), sgpp::datadriven::LearnerBase::getAccuracy(), sgpp::datadriven::LearnerSVM::getAccuracy(), sgpp::datadriven::LearnerSGD::getAccuracy(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracyBL(), sgpp::datadriven::KernelDensityEstimator::getBandwidths(), sgpp::datadriven::LearnerBase::getCassificatorQuality(), sgpp::base::DataMatrix::getColumn(), sgpp::base::DataTensor::getColumn(), sgpp::optimization::InterpolatedFuzzyInterval::getCoreLowerBound(), sgpp::optimization::InterpolatedFuzzyInterval::getCoreUpperBound(), sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), sgpp::base::RandomNumberGenerator::getGaussianRV(), sgpp::datadriven::PolynomialChaosExpansion::getL2Error(), sgpp::datadriven::AlgorithmAdaBoostBase::getROC(), sgpp::base::DataMatrix::getRow(), sgpp::quadrature::NaiveSampleGenerator::getSample(), sgpp::quadrature::StratifiedSampleGenerator::getSample(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), sgpp::base::RandomNumberGenerator::getUniformRV(), sgpp::datadriven::PolynomialChaosExpansion::getVariance(), sgpp::datadriven::RefinementHandler::handleSurplusBasedRefinement(), hpx_main(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), sgpp::datadriven::MetaLearner::learnAndCompareString(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::optimization::optimizer::lineSearchArmijo(), main(), main(), sgpp::datadriven::OperationMakePositive::makeCurrentNodalValuesPositive(), sgpp::datadriven::OperationDensityMargTo1D::margToDimXs(), sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues(), sgpp::datadriven::DensityDifferenceSystemMatrix::mult(), sgpp::datadriven::DensitySystemMatrix::mult(), sgpp::datadriven::DMSystemMatrix::mult(), sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::mult(), sgpp::base::DataMatrix::mult(), sgpp::base::OperationDiagonal::mult(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::AlgorithmDGEMV< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult(), sgpp::datadriven::DMWeightMatrix::mult(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::mult(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::StdUpDown::mult(), sgpp::pde::UpDownFourOpDims::mult(), sgpp::pde::UpDownOneOpDim::mult(), sgpp::pde::UpDownOneOpDimEnhanced::mult(), sgpp::pde::UpDownOneOpDimWithShadow::mult(), sgpp::pde::UpDownTwoOpDims::mult(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceExplicitBspline::mult(), sgpp::pde::OperationLaplaceExplicitLinear::mult(), sgpp::pde::OperationLaplaceExplicitModBspline::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinearBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::mult(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose(), sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult_transpose(), sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed(), sgpp::datadriven::PrimalDualSVM::multiply(), sgpp::pde::StdUpDown::multParallelBuildingBlock(), sgpp::pde::UpDownOneOpDimEnhanced::multParallelBuildingBlock(), sgpp::pde::UpDownOneOpDim::multParallelBuildingBlock(), sgpp::pde::UpDownTwoOpDims::multParallelBuildingBlock(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::multTranspose(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::multTranspose(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates(), sgpp::optimization::SplineResponseSurface::optimize(), sgpp::datadriven::MaximumLikelihoodCrossValidation::optimizeBandwidths(), sgpp::solver::VarTimestep::predictor(), sgpp::solver::LassoFunction::prox(), sgpp::solver::GroupLassoFunction::prox(), sgpp::solver::RidgeFunction::prox(), sgpp::pde::PDESolver::refineInitialGridSurplusSubDomain(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevelSubDomain(), sgpp::datadriven::DBMatOnlineDE::resDensity(), RMSNorm(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution(), sgpp::datadriven::KernelDensityEstimator::setBandwidths(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataMatrix::setRow(), sgpp::base::sle_solver::BiCGStab::setStartingPoint(), sgpp::solver::Fista< F >::solve(), sgpp::datadriven::DBMatDMS_SMW::solve(), sgpp::datadriven::DBMatDMSOrthoAdapt::solve(), sgpp::solver::BiCGStab::solve(), sgpp::solver::ConjugateGradients::solve(), sgpp::solver::BiCGStabSP::solve(), sgpp::solver::ConjugateGradientsSP::solve(), sgpp::base::sle_solver::BiCGStab::solve(), sgpp::solver::StepsizeControl::solve(), sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature(), sgpp::pde::OperationLaplaceExplicitLinear::specialOP(), sgpp::pde::OperationLaplaceLinear::specialOP(), sgpp::pde::OperationLaplaceLinearStretched::specialOP(), sgpp::pde::UpDownOneOpDim::specialOP(), sgpp::pde::UpDownOneOpDimWithShadow::specialOP(), sgpp::pde::UpDownTwoOpDims::specialOpOne(), sgpp::pde::UpDownTwoOpDims::specialOpOneAndOpTwo(), sgpp::pde::UpDownTwoOpDims::specialOpTwo(), sgpp::pde::UpDownFourOpDims::specialOpX(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::pde::PoissonEquationSolver::storeInnerRHS(), sgpp::pde::HeatEquationSolver::storeInnerRHS(), sgpp::pde::PoissonEquationSolver::storeInnerSolution(), sgpp::pde::HeatEquationSolver::storeInnerSolution(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::test_calculateROCcurve(), sgpp::datadriven::test_dataset_mse(), sgpp::datadriven::test_datasetWithCharacteristicNumber(), sgpp::datadriven::ClassificationLearner::train(), sgpp::datadriven::RegressionLearner::train(), sgpp::datadriven::LearnerBase::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::LearnerSGDE::trainOnline(), sgpp::datadriven::LearnerSGDEOnOffParallel::updateAlpha(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel(), sgpp::pde::StdUpDown::updown(), sgpp::pde::UpDownOneOpDim::updown(), sgpp::pde::UpDownOneOpDimWithShadow::updown(), sgpp::pde::UpDownTwoOpDims::updown(), verifyLearned(), sgpp::optimization::file_io::writeGrid(), and sgpp::optimization::file_io::writeVector().
insert()
void sgpp::base::DataVector::insert (size_t index, double value)
Inserts a new element at the given index.
Parameters
index Index of new element
value Value of new element
References insert().
Referenced by append(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), and insert().
l2Norm()
double sgpp::base::DataVector::l2Norm () const
Returns the vector's \(l^2\)-norm, i.e., \(\sqrt{ \sum_i x_i^2 }\).
Returns
The vector's \(l^2\)-norm.
References componentwise_mult(), l2Norm(), and sum().
Referenced by sgpp::datadriven::LearnerSGDE::computeResidual(), sgpp::datadriven::SparseGridDensityEstimator::computeResidual(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::computeResidual(), l2Norm(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::optimization::optimizer::Newton::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), and sgpp::datadriven::DBMatOnlineDE::resDensity().
max()
double sgpp::base::DataVector::max () const
Returns the maximum over all entries.
Returns
global maximum
References max().
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::BayesianOptimization::BayesianOptimization(), sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::OperationDensityRejectionSamplingLinear::doSampling(), sgpp::optimization::optimizer::AugmentedLagrangian::findFeasiblePoint(), main(), max(), maxNorm(), normalize(), sgpp::base::VectorSurplusRefinementFunctor::operator()(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), and sgpp::datadriven::BayesianOptimization::updateGP().
maxNorm()
double sgpp::base::DataVector::maxNorm () const
calculates the vector's max norm
Returns
the vector's max norm
References max().
Referenced by sgpp::optimization::optimizer::AugmentedLagrangian::findFeasiblePoint(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), and sgpp::datadriven::BayesianOptimization::updateGP().
min()
double sgpp::base::DataVector::min () const
Returns the minimum over all entries.
Returns
Minimal value
References min().
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::BayesianOptimization::BayesianOptimization(), sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), main(), min(), normalize(), and sgpp::datadriven::BayesianOptimization::updateGP().
minmax()
void sgpp::base::DataVector::minmax (double * min, double * max) const
Determines minimum and maximum over all entries.
Parameters
min Reference variable for the minimum
max Reference variable for the maximum
Referenced by normalize().
mult()
void sgpp::base::DataVector::mult (double scalar)
multiplies all elements by a constant factor
Parameters
scalar the constant
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::PrimalDualSVM::add(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::DBMatOnlineDE::eval(), sgpp::datadriven::ModelFittingClassification::evaluate(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::DensityDifferenceSystemMatrix::generateb(), sgpp::datadriven::DensitySystemMatrix::generateb(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), sgpp::datadriven::MultipleEvalHPX::LocalityMultiplier::mult(), sgpp::datadriven::PrimalDualSVM::multiply(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::solver::ElasticNetFunction::prox(), sgpp::datadriven::BayesianOptimization::setScales(), sgpp::solver::ConjugateGradients::solve(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), and sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update().
normalize() [1/2]
void sgpp::base::DataVector::normalize ()
Normalizes vector entries to [0,1].
References normalize().
Referenced by sgpp::datadriven::BayesianOptimization::BayesianOptimization(), sgpp::datadriven::Harmonica::calculateConstrainedSpace(), normalize(), and sgpp::datadriven::BayesianOptimization::updateGP().
normalize() [2/2]
void sgpp::base::DataVector::normalize (double border)
Normalizes vector entries to [border, 1-border].
Parameters
border width of border
References max(), min(), and minmax().
operator=() [1/2]
DataVector & sgpp::base::DataVector::operator= (const DataVector &) default
Copy assignment operator.
operator=() [2/2]
DataVector & sgpp::base::DataVector::operator= (DataVector &&) default
Move assignment operator.
partitionClasses()
void sgpp::base::DataVector::partitionClasses (double threshold)
Partitions vector into two classes using a choosen border.
Parameters
threshold value of the border
remove()
void sgpp::base::DataVector::remove (std::vector< size_t > & indexesToRemove)
Removes indexes form the vector.
Throws an exception if the boundaries are violated
Parameters
indexesToRemove a vector if indexes that will be removed from the vector
Referenced by sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::adapt(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::adapt(), sgpp::datadriven::ModelFittingDensityEstimationCG::adapt(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::adapt(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::adapt(), python.uq.uq_setting.UQSetting.UQSetting::cleanUp(), sgpp::datadriven::LearnerSGDEOnOffParallel::updateAlpha(), and sgpp::datadriven::DBMatOnlineDE::updateRhs().
resizeZero()
void sgpp::base::DataVector::resizeZero (size_t nrows)
Resizes the DataVector to size elements.
All new additional entries are set to zero. If nrows is smaller than the current number of rows, all superfluous entries are removed.
Parameters
nrows New number of rows of the DataVector
Referenced by sgpp::datadriven::ModelFittingDensityRatioEstimation::adapt(), sgpp::datadriven::ModelFittingLeastSquares::adapt(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::adapt(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::adapt(), sgpp::datadriven::ModelFittingDensityEstimationCG::adapt(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::adapt(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::adapt(), sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), sgpp::optimization::SplineResponseSurfaceVector::getMeans(), sgpp::optimization::SplineResponseSurfaceVector::getVariances(), sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates(), sgpp::datadriven::VisualizerClassification::runVisualization(), sgpp::datadriven::DBMatOnlineDE_SMW::solveSLE(), sgpp::datadriven::DBMatOnlineDEChol::solveSLE(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::solveSLE(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::LearnerSGDEOnOffParallel::updateAlpha(), and sgpp::datadriven::DBMatOnlineDE::updateRhs().
restructure()
void sgpp::base::DataVector::restructure (std::vector< size_t > & remainingIndex)
Resizes the DataVector by removing entries.
Throws an exception if boundaries a violated.
Parameters
remainingIndex vector that contains the remaining indices of the DataVector
RMSNorm()
double sgpp::base::DataVector::RMSNorm () const
Returns the vector's root mean square (RMS)-norm, i.e., \(\sqrt{ 1/N \sum_{i=1}^N x_i^2 }\).
If the vector's entries correspond to function values on a full grid, this is the discrete \(L^2\)-norm of the corresponding function.
Returns
The vector's root mean square-norm.
References getSize(), sqr(), and sum().
set()
void sgpp::base::DataVector::set (size_t i, double value)
Sets the element at index i to value.
Parameters
i Index
value New value for element
Referenced by sgpp::base::DataMatrix::addReduce(), sgpp::base::DataMatrix::addReduce(), sgpp::base::DirichletUpdateVector::applyDirichletConditions(), sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::base::DirichletGridConverter::calcInnerCoefs(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyForwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyUpdateLambda(), sgpp::datadriven::AlgorithmAdaBoostBase::classif(), sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunction(), sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::ModelFittingClassification::evaluate(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::LearnerSGD::getBatchError(), sgpp::base::HashGridPoint::getStandardCoordinates(), sgpp::combigrid::IndexVectorIterator::getStandardCoordinates(), sgpp::datadriven::PolynomialChaosExpansion::getVariance(), sgpp::datadriven::VisualizerClassification::initializeMatrices(), sgpp::datadriven::VisualizerDensityEstimation::initializeMatrices(), sgpp::datadriven::OperationDensityMargTo1D::margToDimXs(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multImpl(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multImpl(), sgpp::base::DirichletUpdateVector::multiply(), sgpp::base::DirichletUpdateVector::multiplyBoundary(), sgpp::base::DirichletUpdateVector::multiplyBoundaryVector(), sgpp::base::ImpurityRefinementIndicator::operator()(), sgpp::datadriven::LearnerSGD::predict(), sgpp::datadriven::LearnerSGDE::predict(), sgpp::datadriven::LearnerSVM::predict(), sgpp::datadriven::ARFFTools::readARFF(), sgpp::datadriven::CSVTools::readCSV(), sgpp::datadriven::VisualizerClassification::runVisualization(), sgpp::base::DirichletUpdateVector::setBoundariesToZero(), sgpp::base::DirichletUpdateVector::setInnerPointsToZero(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::test_datasetWithCharacteristicNumber(), sgpp::base::DirichletGridConverter::updateBoundaryCoefs(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel(), and sgpp::datadriven::CSVWriter::writeCSV().
setAll()
void sgpp::base::DataVector::setAll (double value)
Sets all values of DataVector to value.
Parameters
value New value for all entries
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyMassMatrixInner(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyForwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyUpdateLambda(), sgpp::combigrid::CombinationGrid::combineSparseGridValues(), sgpp::datadriven::DensitySystemMatrix::computeUnweightedRhs(), sgpp::datadriven::DensityDifferenceSystemMatrix::computeUnweightedRhs(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), sgpp::datadriven::KernelDensityEstimator::cov(), sgpp::combigrid::CombinationGrid::distributeValuesToFullGrid(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::pde::OperationLaplaceModLinear::down(), sgpp::pde::OperationLaplaceModLinear::downOpDim(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::InterpolantVectorFunction::eval(), sgpp::base::InterpolantVectorFunctionGradient::eval(), sgpp::base::InterpolantVectorFunctionHessian::eval(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::datadriven::ModelFittingDensityEstimationCombi::evaluate(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::getGridCoefficientsForCG(), sgpp::optimization::test_problems::G03::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::G12::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Ackley::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Alpine02::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::BubbleWrap::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::EasomYang::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Griewank::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Rastrigin::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Rosenbrock::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Schwefel22::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Schwefel26::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::Sphere::getOptimalPointUndisplaced(), sgpp::optimization::test_problems::TremblingParabola::getOptimalPointUndisplaced(), hpx_main(), sgpp::datadriven::KernelDensityEstimator::initialize(), sgpp::datadriven::KernelDensityEstimator::initialize(), sgpp::datadriven::LearnerSGD::LearnerSGD(), sgpp::base::SLE::matrixVectorMultiplication(), sgpp::datadriven::DensityDifferenceSystemMatrix::mult(), sgpp::datadriven::DensitySystemMatrix::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::base::AlgorithmDGEMV< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::mult(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::StdUpDown::mult(), sgpp::pde::UpDownFourOpDims::mult(), sgpp::pde::UpDownOneOpDim::mult(), sgpp::pde::UpDownOneOpDimEnhanced::mult(), sgpp::pde::UpDownOneOpDimWithShadow::mult(), sgpp::pde::UpDownTwoOpDims::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::mult(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose(), sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed(), sgpp::combigrid::OperationEvalFullGrid::multiEval(), sgpp::pde::StdUpDown::multParallelBuildingBlock(), sgpp::pde::UpDownOneOpDimEnhanced::multParallelBuildingBlock(), sgpp::pde::UpDownOneOpDim::multParallelBuildingBlock(), sgpp::pde::UpDownTwoOpDims::multParallelBuildingBlock(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates(), sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates(), sgpp::pde::DowndPhidPhiBBIterativeLinear::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretched::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::datadriven::KernelDensityEstimator::pdf(), sgpp::solver::BiCGStab::solve(), sgpp::solver::ConjugateGradients::solve(), sgpp::solver::BiCGStabSP::solve(), sgpp::solver::ConjugateGradientsSP::solve(), sgpp::base::sle_solver::BiCGStab::solve(), sgpp::base::sle_solver::solveInternal(), sgpp::pde::UpDownOneOpDimWithShadow::specialOP(), sgpp::datadriven::SparseGridDensityEstimator::train(), sgpp::datadriven::LearnerSGDE::train(), sgpp::pde::OperationLaplaceModLinear::up(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update(), sgpp::pde::UpDownOneOpDimWithShadow::updown(), and sgpp::pde::OperationLaplaceModLinear::upOpDim().
sqr()
void sgpp::base::DataVector::sqr ()
Squares all elements of the DataVector.
Referenced by sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::PolynomialChaosExpansion::getVariance(), RMSNorm(), and sgpp::datadriven::test_dataset_mse().
sqrt()
void sgpp::base::DataVector::sqrt ()
Takes the square root of all elements of the DataVector.
sub()
void sgpp::base::DataVector::sub (const DataVector & vec)
Subtracts the values from another DataVector of the current values.
Modifies the current values.
Parameters
vec The DataVector which is subtracted from the current values
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::BayesianOptimization::BayesianOptimization(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::optimization::test_problems::ConstrainedTestProblem::getOptimalPoint(), sgpp::optimization::test_problems::UnconstrainedTestProblem::getOptimalPoint(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), sgpp::solver::Fista< F >::solve(), sgpp::datadriven::test_dataset_mse(), sgpp::optimization::ResponseSurface::transformPoint(), sgpp::optimization::ResponseSurfaceVector::transformPoint(), sgpp::solver::StepsizeControl::twoNorm(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update(), and sgpp::datadriven::BayesianOptimization::updateGP().
sum()
double sgpp::base::DataVector::sum () const
Returns the sum of all elements.
Returns
The sum of all elements
Referenced by sgpp::datadriven::BayesianOptimization::BayesianOptimization(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::costsComputingCandidates(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), dotProduct(), sgpp::solver::LassoFunction::eval(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), sgpp::datadriven::PolynomialChaosExpansion::getL2Error(), sgpp::datadriven::PolynomialChaosExpansion::getVariance(), l2Norm(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates(), sgpp::optimization::optimizer::CMAES::optimize(), RMSNorm(), sgpp::datadriven::test_dataset_mse(), and sgpp::datadriven::BayesianOptimization::updateGP().
toFile()
void sgpp::base::DataVector::toFile (const std::string & fileName) const
References f, fileName, and toString().
Referenced by main().
toString() [1/2]
std::string sgpp::base::DataVector::toString () const
Returns a description of the DataVector as a string.
Returns
string of the DataVector
References toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), toFile(), and toString().
toString() [2/2]
void sgpp::base::DataVector::toString (std::string & text) const
Writes the data stored in the DataVector into a string.
Parameters
text string to which the data is written
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getEvalVector(), main(), sgpp::datadriven::OperationMultiEvalHPX::mult(), sgpp::base::operator<<(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::GradientDescent::optimize(), sgpp::optimization::optimizer::Newton::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), sgpp::datadriven::DataVectorDistributed::printVector(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::ModelFittingBaseSingleGrid::storeFitter(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson(), and sgpp::datadriven::CSVTools::writeMatrixToCSVFile().
The documentation for this class was generated from the following files:
base/src/sgpp/base/datatypes/DataVector.hpp
base/src/sgpp/base/datatypes/DataVector.cpp