SG++-Doxygen-Documentation: sgpp::datadriven::BoHyperparameterOptimizer Class Reference
sgpp::datadriven::BoHyperparameterOptimizer Class Reference
BoHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
#include <BoHyperparameterOptimizer.hpp>
Public Member Functions
BoHyperparameterOptimizer (BoHyperparameterOptimizer &&rhs)=default
Default Move constructor .
BoHyperparameterOptimizer (const BoHyperparameterOptimizer &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
BoHyperparameterOptimizer (SparseGridMiner *miner, FitterFactory *fitterFactory, DataMiningConfigParser &parser)
Constructor.
BoHyperparameterOptimizer & operator= (BoHyperparameterOptimizer &&rhs)=default
Default Move assign operator.
BoHyperparameterOptimizer & operator= (const BoHyperparameterOptimizer &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
double run (bool writeToFile) override
Run hyperparameter optimization using Bayesian Optimization and random search to warm up.
double transformScore (double original)
Possible score function transformation to accentuate the optimum.
~BoHyperparameterOptimizer () override=default
Default destructor.
Public Member Functions inherited from sgpp::datadriven::HyperparameterOptimizer
HyperparameterOptimizer (const HyperparameterOptimizer &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
HyperparameterOptimizer (HyperparameterOptimizer &&rhs)=default
Default Move constructor .
HyperparameterOptimizer (SparseGridMiner *miner, FitterFactory *fitterFactory, DataMiningConfigParser &parser)
Constructor.
HyperparameterOptimizer & operator= (const HyperparameterOptimizer &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
HyperparameterOptimizer & operator= (HyperparameterOptimizer &&rhs)=default
Default Move assign operator.
virtual ~HyperparameterOptimizer ()=default
Default destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::HyperparameterOptimizer
HPOConfig config
Configuration for all hpo details.
std::unique_ptr< FitterFactory > fitterFactory
FitterFactory to provide fitters for running different hyperparameter configurations.
std::unique_ptr< SparseGridMiner > miner
Miner providing all testing facilities.
Detailed Description
BoHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
It offers access to different hyperparameter optimization procedures.
Constructor & Destructor Documentation
BoHyperparameterOptimizer() [1/3]
sgpp::datadriven::BoHyperparameterOptimizer::BoHyperparameterOptimizer (SparseGridMiner * miner, FitterFactory * fitterFactory, DataMiningConfigParser & parser)
Constructor.
Parameters
miner configured instance of SGMiner object, that will provide the learning process. The HyperparameterOptimizer instance will take ownership of the passed object.
fitterFactory configured instance of factory object that provides fitters with manipulated hyperparameters. The HyperparameterOptimizer instance will take ownership of the passed object.
parser reference to parser object to read configuration info
BoHyperparameterOptimizer() [2/3]
sgpp::datadriven::BoHyperparameterOptimizer::BoHyperparameterOptimizer (const BoHyperparameterOptimizer & rhs) delete
Copy constructor deleted - not all members can be copied or cloned .
Parameters
rhs the object to copy from
BoHyperparameterOptimizer() [3/3]
sgpp::datadriven::BoHyperparameterOptimizer::BoHyperparameterOptimizer (BoHyperparameterOptimizer && rhs) default
Default Move constructor .
Parameters
rhs the object to move from
~BoHyperparameterOptimizer()
sgpp::datadriven::BoHyperparameterOptimizer::~BoHyperparameterOptimizer () override default
Default destructor.
Member Function Documentation
operator=() [1/2]
BoHyperparameterOptimizer & sgpp::datadriven::BoHyperparameterOptimizer::operator= (BoHyperparameterOptimizer && rhs) default
Default Move assign operator.
Parameters
rhs the object to move from
operator=() [2/2]
BoHyperparameterOptimizer & sgpp::datadriven::BoHyperparameterOptimizer::operator= (const BoHyperparameterOptimizer & rhs) delete
Default copy assign operator deleted because not all members can be copied.
Parameters
rhs the object to copy from
run()
double sgpp::datadriven::BoHyperparameterOptimizer::run (bool writeToFile) override virtual
Run hyperparameter optimization using Bayesian Optimization and random search to warm up.
Implements sgpp::datadriven::HyperparameterOptimizer.
References sgpp::datadriven::HyperparameterOptimizer::config, sgpp::base::Printer::disableStatusPrinting(), sgpp::datadriven::BayesianOptimization::fitScales(), sgpp::datadriven::HyperparameterOptimizer::fitterFactory, sgpp::base::Printer::getInstance(), sgpp::datadriven::HPOConfig::getNRandom(), sgpp::datadriven::HPOConfig::getNRuns(), sgpp::datadriven::HPOConfig::getSeed(), sgpp::datadriven::BayesianOptimization::main(), sgpp::datadriven::HyperparameterOptimizer::miner, sgpp::datadriven::BayesianOptimization::setScales(), sgpp::datadriven::BOConfig::setScore(), transformScore(), and sgpp::datadriven::BayesianOptimization::updateGP().
Referenced by python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution().
transformScore()
double sgpp::datadriven::BoHyperparameterOptimizer::transformScore (double original)
Possible score function transformation to accentuate the optimum.
Parameters
original
Returns
transformed value
Referenced by run().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/hpo/BoHyperparameterOptimizer.hpp
datadriven/src/sgpp/datadriven/datamining/modules/hpo/BoHyperparameterOptimizer.cpp