SG++-Doxygen-Documentation: sgpp::base::ForwardSelectorRefinementIndicator Class Reference
sgpp::base::ForwardSelectorRefinementIndicator Class Reference
A refinement indicator for support vector classification using sparse grids (according to König BA).
#include <ForwardSelectorRefinementIndicator.hpp>
Public Types
typedef GridPoint counter_key_type
typedef std::pair< size_t, double > value_type
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Public Member Functions
ForwardSelectorRefinementIndicator (Grid &grid, DataMatrix &svs, DataVector &alphas, DataVector &w1, DataVector &w2, double beta, double threshold=0.0, size_t refinementsNum=1, bool performUpdate=true)
Constructor.
size_t getRefinementsNum () const override
Returns the maximal number of points that should be refined.
double getRefinementThreshold () const override
Returns the threshold for refinement.
virtual double operator() (GridPoint &point) const
This should be returning a refinement indicator for the specified grid point The point with the highest value will be refined first.
double operator() (GridStorage &storage, size_t seq) const override
This should be returning a refinement indication value for every grid point.
double runOperator (GridStorage &storage, size_t seq)
double start () const override
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
void update (GridPoint &point)
Update normal vector of SVM.
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
RefinementFunctor ()
Constructor.
virtual ~RefinementFunctor ()
Destructor.
Protected Attributes
DataVector & alphas
double beta
bool performUpdate
size_t refinementsNum
DataVector rv1
DataVector rv2
DataMatrix & svs
double threshold
DataVector & w1
DataVector & w2
Detailed Description
A refinement indicator for support vector classification using sparse grids (according to König BA).
Member Typedef Documentation
counter_key_type
typedef GridPoint sgpp::base::ForwardSelectorRefinementIndicator::counter_key_type
value_type
typedef std::pair<size_t, double> sgpp::base::ForwardSelectorRefinementIndicator::value_type
Constructor & Destructor Documentation
ForwardSelectorRefinementIndicator()
sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator (Grid & grid, DataMatrix & svs, DataVector & alphas, DataVector & w1, DataVector & w2, double beta, double threshold = 0.0, size_t refinementsNum = 1, bool performUpdate = true)
Constructor.
Parameters
grid The sparse grid
svs Contains all currently stored support vectors
alphas The weights corresponding to the support vectors
w1 The normal vector
w2 The normal vector computted with abs weights
beta Specifies relevance of grid points (default: equal relevance for all grid points)
threshold The refinement threshold; Only grid points with indicator values greater than this threshold will be refined
refinementsNum The max amount of grid points to be refined
performUpdate Specifies if normal vector should be updated after refinement
References sgpp::base::DataVector::add(), alpha, alphas, sgpp::op_factory::createOperationMultipleEval(), sgpp::base::DataVector::dotProduct(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::mult(), rv1, rv2, sgpp::base::DataVector::set(), sgpp::base::DataMatrix::setRow(), svs, and w1.
Member Function Documentation
getRefinementsNum()
size_t sgpp::base::ForwardSelectorRefinementIndicator::getRefinementsNum () const override virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
number of points that should refined. Default value: 1.
Reimplemented from sgpp::base::RefinementFunctor.
References refinementsNum.
getRefinementThreshold()
double sgpp::base::ForwardSelectorRefinementIndicator::getRefinementThreshold () const override virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion greater than this threshold will be refined.
Returns
threshold value for refinement. Default value: 0.
Implements sgpp::base::RefinementFunctor.
References threshold.
Referenced by sgpp::base::ForwardSelectorRefinement::getIndicator().
operator()() [1/2]
double sgpp::base::ForwardSelectorRefinementIndicator::operator() (GridPoint & point) const virtual
This should be returning a refinement indicator for the specified grid point The point with the highest value will be refined first.
Parameters
point Grid point for which to calculate an indicator value
Returns
The indicator value
operator()() [2/2]
double sgpp::base::ForwardSelectorRefinementIndicator::operator() (GridStorage & storage, size_t seq) const override virtual
This should be returning a refinement indication value for every grid point.
The grid point with the highest value will be refined first.
Parameters
storage Reference to the grids storage object
seq Sequence number in the coefficients array
Returns
The refinement indicator value
Implements sgpp::base::RefinementFunctor.
References beta, sgpp::base::DataVector::get(), rv2, w1, and w2.
runOperator()
double sgpp::base::ForwardSelectorRefinementIndicator::runOperator (GridStorage & storage, size_t seq)
References sgpp::base::HashGridStorage::getPoint().
start()
double sgpp::base::ForwardSelectorRefinementIndicator::start () const override virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implements sgpp::base::RefinementFunctor.
update()
void sgpp::base::ForwardSelectorRefinementIndicator::update (GridPoint & point)
Update normal vector of SVM.
For each new grid point the normal vector has to be extended by one component.
Parameters
point The new grid point
References alphas, sgpp::base::DataVector::append(), sgpp::base::Basis< LT, IT >::eval(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getBasis(), sgpp::base::DataMatrix::getNrows(), level, performUpdate, svs, w1, and w2.
Referenced by python.uq.refinement.RefinementStrategy.Ranking::rank(), sgpp::base::ForwardSelectorRefinement::refineGridpointsCollection(), and python.learner.LearnedKnowledge.LearnedKnowledge::setMemento().
Member Data Documentation
alphas
DataVector& sgpp::base::ForwardSelectorRefinementIndicator::alphas protected
Referenced by ForwardSelectorRefinementIndicator(), and update().
beta
double sgpp::base::ForwardSelectorRefinementIndicator::beta protected
Referenced by operator()().
performUpdate
bool sgpp::base::ForwardSelectorRefinementIndicator::performUpdate protected
Referenced by update().
refinementsNum
size_t sgpp::base::ForwardSelectorRefinementIndicator::refinementsNum protected
Referenced by getRefinementsNum().
rv1
DataVector sgpp::base::ForwardSelectorRefinementIndicator::rv1 protected
Referenced by ForwardSelectorRefinementIndicator().
rv2
DataVector sgpp::base::ForwardSelectorRefinementIndicator::rv2 protected
Referenced by ForwardSelectorRefinementIndicator(), and operator()().
svs
DataMatrix& sgpp::base::ForwardSelectorRefinementIndicator::svs protected
Referenced by ForwardSelectorRefinementIndicator(), and update().
threshold
double sgpp::base::ForwardSelectorRefinementIndicator::threshold protected
Referenced by getRefinementThreshold().
w1
DataVector& sgpp::base::ForwardSelectorRefinementIndicator::w1 protected
Referenced by ForwardSelectorRefinementIndicator(), operator()(), and update().
w2
DataVector& sgpp::base::ForwardSelectorRefinementIndicator::w2 protected
Referenced by operator()(), and update().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/functors/ForwardSelectorRefinementIndicator.hpp
base/src/sgpp/base/grid/generation/functors/ForwardSelectorRefinementIndicator.cpp