SG++-Doxygen-Documentation: sgpp::solver::Fista< F > Class Template Reference
sgpp::solver::Fista< F > Class Template Reference
Fast Iterative Shrinkage Tresholding Algorithm is a solver for least-squares problems.
#include <Fista.hpp>
Public Member Functions
Fista (F g)
Fista.
void solve (base::OperationMultipleEval &op, base::DataVector &weights, const base::DataVector &classes, size_t maxIt, double threshold, double L=0.5) override
solve solves the problem.
~Fista () override
Public Member Functions inherited from sgpp::solver::FistaBase
double getL ()
virtual ~FistaBase ()
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::FistaBase
double L = 0.5
Detailed Description
template<typename F>
class sgpp::solver::Fista< F >
Fast Iterative Shrinkage Tresholding Algorithm is a solver for least-squares problems.
It can solve all problems that are seperable in a least-squares part and a convex, not necessarily smooth other function. The other function is a template argument. FISTA is an optimal first order method for this problem class.
Constructor & Destructor Documentation
Fista()
template<typename F > sgpp::solver::Fista< F >::Fista (F g) inline explicit
Fista.
Parameters
g is the regularization function.
References g.
~Fista()
template<typename F > sgpp::solver::Fista< F >::~Fista () inline override
Member Function Documentation
solve()
template<typename F > void sgpp::solver::Fista< F >::solve (base::OperationMultipleEval & op, base::DataVector & weights, const base::DataVector & classes, size_t maxIt, double threshold, double L = 0.5) inline override virtual
solve solves the problem.
Parameters
op
weights is the first guess for the solution
classes is the target vector
maxIt is the maximum number of iterations
threshold is the desired accuracy
L is a guess for the Lipschitz number of the gradient of the least squares part. It is used to improve the speed of the linesearch, and should be 0.5 for the first iteration. Has to be positive.
Implements sgpp::solver::FistaBase.
References sgpp::base::DataVector::add(), sgpp::base::DataVector::getSize(), sgpp::solver::FistaBase::L, and sgpp::base::DataVector::sub().
The documentation for this class was generated from the following file:
solver/src/sgpp/solver/sle/fista/Fista.hpp