SG++-Doxygen-Documentation: sgpp::pde::OperationLaplaceExplicitBspline Class Reference
sgpp::pde::OperationLaplaceExplicitBspline Class Reference
Implementation for B-spline functions of Laplace Operation, linear grids without boundaries.
#include <OperationLaplaceExplicitBspline.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationLaplaceExplicitBspline (sgpp::base::DataMatrix *m, sgpp::base::Grid *grid)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
OperationLaplaceExplicitBspline (sgpp::base::Grid *grid)
Constructor that creates an own matrix i.e.
virtual ~OperationLaplaceExplicitBspline ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Implementation for B-spline functions of Laplace Operation, linear grids without boundaries.
Constructor & Destructor Documentation
OperationLaplaceExplicitBspline() [1/2]
sgpp::pde::OperationLaplaceExplicitBspline::OperationLaplaceExplicitBspline (sgpp::base::DataMatrix * m, sgpp::base::Grid * grid)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
matrix is NOT destroyed by the destructor of OperationLaplaceExplicitBspline
Parameters
m pointer to datamatrix of size (number of grid point) x (number of grid points)
grid the sparse grid
References grid(), and m.
OperationLaplaceExplicitBspline() [2/2]
sgpp::pde::OperationLaplaceExplicitBspline::OperationLaplaceExplicitBspline (sgpp::base::Grid * grid) explicit
Constructor that creates an own matrix i.e.
matrix is destroyed by the destructor of OperationLaplaceExplicitBspline
Parameters
grid the sparse grid
References grid().
~OperationLaplaceExplicitBspline()
sgpp::pde::OperationLaplaceExplicitBspline::~OperationLaplaceExplicitBspline () virtual
Destructor.
Member Function Documentation
mult()
void sgpp::pde::OperationLaplaceExplicitBspline::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), and sgpp::base::DataVector::getSize().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplaceExplicitBspline.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplaceExplicitBspline.cpp