SG++-Doxygen-Documentation: sgpp::base::OperationWeightedQuadratureNakBsplineModified Class Reference
sgpp::base::OperationWeightedQuadratureNakBsplineModified Class Reference
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
#include <OperationWeightedQuadratureNakBsplineModified.hpp>
Public Member Functions
double doWeightedQuadrature (DataVector &alpha, sgpp::base::DistributionsVector pdfs) override
Quadrature for not a knot B-spline basis functions w.r.t.
OperationWeightedQuadratureNakBsplineModified (GridStorage &storage, size_t degree, size_t quadOrder)
Constructor of OperationQuadratureNakBsplineModified.
~OperationWeightedQuadratureNakBsplineModified () override
Public Member Functions inherited from sgpp::base::OperationWeightedQuadrature
OperationWeightedQuadrature ()
Constructor.
virtual ~OperationWeightedQuadrature ()
Destructor.
Protected Attributes
SNakBsplineModifiedBase base
Basis object.
std::shared_ptr< base::DataVector > quadCoordinates
quadrature rule coordinates
size_t quadOrder
quadrature rule order
std::shared_ptr< base::DataVector > quadWeights
quadrature rule weights
GridStorage & storage
Detailed Description
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
Constructor & Destructor Documentation
OperationWeightedQuadratureNakBsplineModified()
sgpp::base::OperationWeightedQuadratureNakBsplineModified::OperationWeightedQuadratureNakBsplineModified (GridStorage & storage, size_t degree, size_t quadOrder) inline
Constructor of OperationQuadratureNakBsplineModified.
Parameters
storage Pointer to the grid's GridStorage object
degree the B-spline degree
quadOrder quadrature order
References sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), quadCoordinates, quadOrder, and quadWeights.
~OperationWeightedQuadratureNakBsplineModified()
sgpp::base::OperationWeightedQuadratureNakBsplineModified::~OperationWeightedQuadratureNakBsplineModified () inline override
Member Function Documentation
doWeightedQuadrature()
double sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature (DataVector & alpha, sgpp::base::DistributionsVector pdfs) override virtual
Quadrature for not a knot B-spline basis functions w.r.t.
a probability density function
Parameters
alpha Coefficient vector for current grid
pdfs probability density functions
Implements sgpp::base::OperationWeightedQuadrature.
References alpha, base, sgpp::base::DistributionsVector::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::NakBsplineModifiedBasis< LT, IT >::getMean(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getSize(), quadCoordinates, quadWeights, and storage.
Member Data Documentation
base
SNakBsplineModifiedBase sgpp::base::OperationWeightedQuadratureNakBsplineModified::base protected
Basis object.
Referenced by doWeightedQuadrature().
quadCoordinates
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBsplineModified::quadCoordinates protected
quadrature rule coordinates
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBsplineModified().
quadOrder
size_t sgpp::base::OperationWeightedQuadratureNakBsplineModified::quadOrder protected
quadrature rule order
Referenced by OperationWeightedQuadratureNakBsplineModified().
quadWeights
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBsplineModified::quadWeights protected
quadrature rule weights
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBsplineModified().
storage
GridStorage& sgpp::base::OperationWeightedQuadratureNakBsplineModified::storage protected
Referenced by doWeightedQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBsplineModified.hpp
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBsplineModified.cpp