SG++-Doxygen-Documentation: sgpp::optimization::HashRefinementMultiple Class Reference
sgpp::optimization::HashRefinementMultiple Class Reference
Descendant of base::HashRefinement refining without the generation of hierarchical ancestors.
#include <HashRefinementMultiple.hpp>
Public Member Functions
size_t getNumberOfRefinablePoints (base::GridStorage &storage) override
Returns the number of refineable points, e.g.
void refineGridpoint1D (base::GridStorage &storage, base::GridPoint &point, size_t t) override
Refines a grid point in one dimension.
Public Member Functions inherited from sgpp::base::HashRefinement
void free_refine (GridStorage &storage, RefinementFunctor &functor, std::vector< size_t > *addedPoints=nullptr) override
Refines a grid according to a RefinementFunctor provided.
void refineGridpoint1D (GridStorage &storage, size_t seq, size_t d) override
Refine one grid point along a single direction.
~HashRefinement () override
Public Member Functions inherited from sgpp::base::AbstractRefinement
virtual size_t getIndexOfMin (RefinementFunctor::value_type *array, size_t length)
Returns the index of the first occurrence of minimal element in array.
bool isRefinable (GridStorage &storage, GridPoint &point)
Check if the grid point is refinable.
virtual ~AbstractRefinement ()
Destructor.
Protected Member Functions
void collectRefinablePoints (base::GridStorage &storage, base::RefinementFunctor &functor, base::AbstractRefinement::refinement_container_type &collection) override
Examine the grid points and stores the indices those that can be refined and have maximal indicator values.
Protected Member Functions inherited from sgpp::base::HashRefinement
virtual void addElementToCollection (const GridStorage::grid_map_iterator &iter, AbstractRefinement::refinement_list_type current_value_list, size_t refinements_num, AbstractRefinement::refinement_container_type &collection)
Adds elements to the collection.
void createGridpoint (GridStorage &storage, GridPoint &point) override
This method creates a new point on the grid.
AbstractRefinement::refinement_list_type getIndicator (GridStorage &storage, const GridStorage::grid_map_iterator &iter, const RefinementFunctor &functor) const override
Generates a list with indicator elements.
void refineGridpoint (GridStorage &storage, size_t refine_index) override
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
void refineGridpointsCollection (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection) override
Extends the grid adding elements defined in collection.
Protected Member Functions inherited from sgpp::base::AbstractRefinement
virtual void createGridpoint1D (GridPoint &point, size_t d, GridStorage &storage, index_t &source_index, level_t &source_level)
Creates children grid points along single direction.
virtual void createGridpointSubroutine (GridStorage &storage, GridPoint &point)
Subroutine for grid point creation.
Additional Inherited Members
Public Types inherited from sgpp::base::AbstractRefinement
typedef std::vector< refinement_pair_type > refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
typedef AbstractRefinement_refinement_key refinement_key_type
Type of the identifier of the refinement atom (e.g.
typedef std::forward_list< AbstractRefinement::refinement_pair_type > refinement_list_type
typedef std::pair< std::shared_ptr< refinement_key_type >, refinement_value_type > refinement_pair_type
Pair for the refinement key and value.
typedef double refinement_value_type
Type of functor value assigned to each refinement atom.
Static Public Member Functions inherited from sgpp::base::AbstractRefinement
static bool compare_pairs (const refinement_pair_type &lhs, const refinement_pair_type &rhs)
Comparison of the refinement_pair_type.
Detailed Description
Descendant of base::HashRefinement refining without the generation of hierarchical ancestors.
In SG++ grids (as in sgpp::base), every grid fulfills the "hierarchical ancestors" property, e.g. every gridpoint has a direct ancestor in every dimension whose level is > 1.
By using this refinement class, the property doesn't necessarily hold anymore. The original base::HashRefinement looks at the neigbors of a grid point to be refined. If a neighbor in a dimension and a direction (left/right) already exists, no new point is inserted. If it doesn't exist, it is inserted and all hierarchical ancestors are generated recursively.
HashRefinementMultiple instead inserts exactly \(2d\) new grid points, if a point is to be refined (for Noboundary grids with \(d\) being the number of dimensions). This is done by looking at neighbors of higher levels (closer to the point to be refined) and inserting the first neighbor that doesn't exist in the grid. Additionally, no hierarchical ancestors are creating by omitting the base::HashRefinement::createGridpoint() calls.
Grids without the "hierarchical ancestors" property don't allow most standard algorithms to be executed on them, therefore grids and basis functions are separated in this module from those in sgpp::base.
Member Function Documentation
collectRefinablePoints()
void sgpp::optimization::HashRefinementMultiple::collectRefinablePoints (base::GridStorage & storage, base::RefinementFunctor & functor, base::AbstractRefinement::refinement_container_type & collection) inline override protected virtual
Examine the grid points and stores the indices those that can be refined and have maximal indicator values.
This function differences from its counterpart in base::HashRefinement insofar every grid point could potentially be refined.
Parameters
storage hashmap that stores the grid points
functor a PredictiveRefinementIndicator specifying the refinement criteria
collection container that contains elements to refine (empty initially)
Reimplemented from sgpp::base::HashRefinement.
References sgpp::base::HashRefinement::addElementToCollection(), sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::HashRefinement::getIndicator(), and sgpp::base::RefinementFunctor::getRefinementsNum().
getNumberOfRefinablePoints()
size_t sgpp::optimization::HashRefinementMultiple::getNumberOfRefinablePoints (base::GridStorage & storage) inline override virtual
Returns the number of refineable points, e.g.
the number of all points (every grid point can be refined).
Parameters
storage grid storage
Returns
number of refinable points
Reimplemented from sgpp::base::HashRefinement.
References sgpp::base::HashGridStorage::getSize().
refineGridpoint1D()
void sgpp::optimization::HashRefinementMultiple::refineGridpoint1D (base::GridStorage & storage, base::GridPoint & point, size_t t) inline override virtual
Refines a grid point in one dimension.
This creates exactly two new grid points.
Parameters
storage grid storage
point point of the grid point
t dimension in which the refinement should take place
Reimplemented from sgpp::base::HashRefinement.
References sgpp::base::HashGridStorage::insert(), and sgpp::base::HashGridStorage::isContaining().
The documentation for this class was generated from the following file:
optimization/src/sgpp/optimization/gridgen/HashRefinementMultiple.hpp