SG++-Doxygen-Documentation: json::Node Class Reference
json::Node Class Reference abstract
#include <Node.hpp>
Public Member Functions
virtual void addAttribute (const std::string &name, std::unique_ptr< Node > node)
virtual Node & addDictAttr (const std::string &name)
virtual Node & addDictValue ()
virtual Node & addIDAttr (const std::string &name, const bool &value)
virtual Node & addIDAttr (const std::string &name, const char *value)
virtual Node & addIDAttr (const std::string &name, const double &value)
virtual Node & addIDAttr (const std::string &name, const int64_t &value)
virtual Node & addIDAttr (const std::string &name, const std::string &value)
virtual Node & addIDAttr (const std::string &name, const uint64_t &value)
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListAttr (const std::string &name)
virtual Node & addListValue ()
virtual Node & addTextAttr (const std::string &name, const std::string &value)
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual Node * clone ()=0
virtual bool contains (const std::string &key)
virtual std::unique_ptr< Node > erase ()
virtual std::unique_ptr< Node > erase (Node &node)
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
virtual std::vector< std::string > & keys ()
Node ()
Node (const Node &right)=default
virtual Node & operator= (const Node &right)
virtual Node & operator[] (const size_t index)
virtual Node & operator[] (const std::string &key)
virtual void parse (std::vector< Token > &stream)=0
virtual std::unique_ptr< Node > removeAttribute (const std::string name)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual Node & replaceDictAttr (const std::string &name)
virtual Node & replaceIDAttr (const std::string &name, const bool &value)
virtual Node & replaceIDAttr (const std::string &name, const char *value)
virtual Node & replaceIDAttr (const std::string &name, const double &value)
virtual Node & replaceIDAttr (const std::string &name, const int64_t &value)
virtual Node & replaceIDAttr (const std::string &name, const std::string &value)
virtual Node & replaceIDAttr (const std::string &name, const uint64_t &value)
virtual Node & replaceListAttr (const std::string &name)
virtual Node & replaceTextAttr (const std::string &name, const std::string &value)
virtual void serialize (std::ostream &outFile, size_t indentWidth)=0
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual size_t size ()=0
virtual ~Node ()=default
Public Attributes
size_t orderedKeyIndex
Node * parent
Static Protected Attributes
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
Node() [1/2]
json::Node::Node ()
Node() [2/2]
json::Node::Node (const Node & right) default
~Node()
virtual json::Node::~Node () virtual default
Member Function Documentation
addAttribute()
void json::Node::addAttribute (const std::string & name, std::unique_ptr< Node > node) virtual
Reimplemented in json::DictNode.
Referenced by python.data.DataSpecification.DataSpecification::createNumericAttributes().
addDictAttr()
Node & json::Node::addDictAttr (const std::string & name) virtual
Reimplemented in json::DictNode.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters(), sgpp::base::OCLManagerMultiPlatform::configureDevice(), and sgpp::base::OCLManagerMultiPlatform::configurePlatform().
addDictValue()
Node & json::Node::addDictValue () virtual
Reimplemented in json::ListNode.
Referenced by sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), and sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson().
addIDAttr() [1/6]
Node & json::Node::addIDAttr (const std::string & name, const bool & value) virtual
Reimplemented in json::DictNode.
addIDAttr() [2/6]
Node & json::Node::addIDAttr (const std::string & name, const char * value) virtual
Reimplemented in json::DictNode.
addIDAttr() [3/6]
Node & json::Node::addIDAttr (const std::string & name, const double & value) virtual
Reimplemented in json::DictNode.
addIDAttr() [4/6]
Node & json::Node::addIDAttr (const std::string & name, const int64_t & value) virtual
Reimplemented in json::DictNode.
addIDAttr() [5/6]
Node & json::Node::addIDAttr (const std::string & name, const std::string & value) virtual
Reimplemented in json::DictNode.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters().
addIDAttr() [6/6]
Node & json::Node::addIDAttr (const std::string & name, const uint64_t & value) virtual
Reimplemented in json::DictNode.
addIdValue() [1/6]
Node & json::Node::addIdValue (const bool & value) virtual
Reimplemented in json::ListNode.
addIdValue() [2/6]
Node & json::Node::addIdValue (const char * value) virtual
Reimplemented in json::ListNode.
addIdValue() [3/6]
Node & json::Node::addIdValue (const double & value) virtual
Reimplemented in json::ListNode.
addIdValue() [4/6]
Node & json::Node::addIdValue (const int64_t & value) virtual
Reimplemented in json::ListNode.
addIdValue() [5/6]
Node & json::Node::addIdValue (const std::string & value) virtual
Reimplemented in json::ListNode.
Referenced by sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), and sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification().
addIdValue() [6/6]
Node & json::Node::addIdValue (const uint64_t & value) virtual
Reimplemented in json::ListNode.
addListAttr()
Node & json::Node::addListAttr (const std::string & name) virtual
Reimplemented in json::DictNode.
addListValue()
Node & json::Node::addListValue () virtual
Reimplemented in json::ListNode.
addTextAttr()
Node & json::Node::addTextAttr (const std::string & name, const std::string & value) virtual
Reimplemented in json::DictNode.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters().
addTextValue()
Node & json::Node::addTextValue (const std::string & value) virtual
Reimplemented in json::ListNode.
addValue()
void json::Node::addValue (std::unique_ptr< Node > node) virtual
Reimplemented in json::ListNode.
clone()
virtual Node * json::Node::clone () pure virtual
Implemented in json::JSON, sgpp::base::OperationConfiguration, sgpp::base::OCLOperationConfiguration, json::DictNode, json::IDNode, json::ListNode, json::TextNode, sgpp::datadriven::LearnerSGDEConfiguration, and sgpp::datadriven::SparseGridDensityEstimatorConfiguration.
Referenced by sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification().
contains()
bool json::Node::contains (const std::string & key) virtual
Reimplemented in json::DictNode.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters(), sgpp::base::OCLManagerMultiPlatform::buildKernel(), sgpp::base::OCLManagerMultiPlatform::configureDevice(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderB< real_type >::generateSource(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderPruneGraph< real_type >::generateSource(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderCreateGraph< real_type >::generateSource(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderMult< real_type >::generateSource(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::KernelCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::KernelDensityMult(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderCreateGraph< real_type >::SourceBuilderCreateGraph(), and sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult().
erase() [1/2]
std::unique_ptr< Node > json::Node::erase () virtual
References erase(), and parent.
erase() [2/2]
std::unique_ptr< Node > json::Node::erase (Node & node) virtual
Reimplemented in json::DictNode, and json::ListNode.
Referenced by erase().
get()
std::string & json::Node::get () virtual
Reimplemented in json::IDNode, and json::TextNode.
Referenced by sgpp::base::OCLManagerMultiPlatform::buildKernel(), sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), sgpp::datadriven::DBMatDatabase::getDataMatrix(), sgpp::datadriven::LearnerScenario::getInternalPrecision(), sgpp::datadriven::DataMiningConfigParser::getMultiDataSourceConfig(), and sgpp::datadriven::DataMiningConfigParser::parseIntArray().
getBool()
bool json::Node::getBool () virtual
Reimplemented in json::IDNode, and json::TextNode.
Referenced by sgpp::base::OCLManagerMultiPlatform::buildKernel(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::KernelCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::KernelDensityB(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::KernelDensityMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::KernelMult(), sgpp::datadriven::StreamingModOCLOpt::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLUnified::KernelMult< real_type >::KernelMult(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLOpt::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLUnified::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMultTranspose< T >::KernelMultTranspose(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::KernelPruneGraph(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderCreateGraph< real_type >::SourceBuilderCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::SourceBuilderMult(), sgpp::datadriven::StreamingOCLMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), and sgpp::datadriven::StreamingOCLMultiPlatform::SourceBuilderMultTranspose< real_type >::SourceBuilderMultTranspose().
getDouble()
double json::Node::getDouble () virtual
Reimplemented in json::IDNode, and json::TextNode.
getInt()
int64_t json::Node::getInt () virtual
Reimplemented in json::IDNode, and json::TextNode.
Referenced by sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages().
getUInt()
uint64_t json::Node::getUInt () virtual
Reimplemented in json::IDNode, and json::TextNode.
Referenced by sgpp::base::OCLManagerMultiPlatform::configureDevice(), sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::KernelCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::KernelDensityB(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::KernelDensityMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::KernelMult(), sgpp::datadriven::StreamingModOCLOpt::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLUnified::KernelMult< real_type >::KernelMult(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMult< T >::KernelMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLOpt::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingModOCLUnified::KernelMultTranspose< real_type >::KernelMultTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMultTranspose< T >::KernelMultTranspose(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::KernelPruneGraph(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderCreateGraph< real_type >::SourceBuilderCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMult< T >::SourceBuilderMult(), sgpp::datadriven::StreamingOCLMultiPlatform::SourceBuilderMult< real_type >::SourceBuilderMult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLOpt::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), sgpp::datadriven::StreamingModOCLUnified::SourceBuilderMultTranspose< T >::SourceBuilderMultTranspose(), and sgpp::datadriven::StreamingOCLMultiPlatform::SourceBuilderMultTranspose< real_type >::SourceBuilderMultTranspose().
keys()
std::vector< std::string > & json::Node::keys () virtual
Reimplemented in json::DictNode.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), and sgpp::base::OCLOperationConfiguration::getAllDeviceNodes().
operator=()
Node & json::Node::operator= (const Node & right) virtual
Reimplemented in json::DictNode, json::IDNode, json::JSON, json::ListNode, and json::TextNode.
operator[]() [1/2]
Node & json::Node::operator[] (const size_t index) virtual
Reimplemented in json::ListNode.
operator[]() [2/2]
Node & json::Node::operator[] (const std::string & key) virtual
Reimplemented in json::DictNode.
parse()
virtual void json::Node::parse (std::vector< Token > & stream) pure virtual
Implemented in json::DictNode, json::IDNode, json::ListNode, and json::TextNode.
removeAttribute()
std::unique_ptr< Node > json::Node::removeAttribute (const std::string name) virtual
Reimplemented in json::DictNode.
removeValue()
std::unique_ptr< Node > json::Node::removeValue (size_t index) virtual
Reimplemented in json::ListNode.
replaceDictAttr()
Node & json::Node::replaceDictAttr (const std::string & name) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [1/6]
Node & json::Node::replaceIDAttr (const std::string & name, const bool & value) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [2/6]
Node & json::Node::replaceIDAttr (const std::string & name, const char * value) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [3/6]
Node & json::Node::replaceIDAttr (const std::string & name, const double & value) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [4/6]
Node & json::Node::replaceIDAttr (const std::string & name, const int64_t & value) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [5/6]
Node & json::Node::replaceIDAttr (const std::string & name, const std::string & value) virtual
Reimplemented in json::DictNode.
replaceIDAttr() [6/6]
Node & json::Node::replaceIDAttr (const std::string & name, const uint64_t & value) virtual
Reimplemented in json::DictNode.
replaceListAttr()
Node & json::Node::replaceListAttr (const std::string & name) virtual
Reimplemented in json::DictNode.
replaceTextAttr()
Node & json::Node::replaceTextAttr (const std::string & name, const std::string & value) virtual
Reimplemented in json::DictNode.
serialize()
virtual void json::Node::serialize (std::ostream & outFile, size_t indentWidth) pure virtual
Implemented in json::DictNode, json::IDNode, json::JSON, json::ListNode, and json::TextNode.
Referenced by operator<<(), python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
set()
void json::Node::set (const std::string & value) virtual
Reimplemented in json::IDNode, and json::TextNode.
setBool()
void json::Node::setBool (bool boolValue) virtual
Reimplemented in json::IDNode, and json::TextNode.
setDouble()
void json::Node::setDouble (double doubleValue) virtual
Reimplemented in json::IDNode, and json::TextNode.
setInt()
void json::Node::setInt (int64_t intValue) virtual
Reimplemented in json::IDNode, and json::TextNode.
setUInt()
void json::Node::setUInt (uint64_t uintValue) virtual
Reimplemented in json::IDNode, and json::TextNode.
size()
virtual size_t json::Node::size () pure virtual
Implemented in json::DictNode, json::IDNode, json::ListNode, and json::TextNode.
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), python.data.DataContainer.DataContainer::getSize(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::KernelDensityB().
Member Data Documentation
orderedKeyIndex
size_t json::Node::orderedKeyIndex
Referenced by json::JSON::clear(), json::DictNode::DictNode(), json::ListNode::ListNode(), json::DictNode::operator=(), json::ListNode::operator=(), and json::DictNode::removeAttribute().
parent
Node* json::Node::parent
Referenced by json::JSON::clear(), json::DictNode::DictNode(), erase(), json::ListNode::erase(), json::ListNode::ListNode(), and json::ListNode::operator=().
SERIALIZE_INDENT
const int json::Node::SERIALIZE_INDENT = 3 static protected
Referenced by json::DictNode::serialize(), and json::ListNode::serialize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/json/Node.hpp
base/src/sgpp/base/tools/json/Node.cpp