SG++-Doxygen-Documentation: sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T > Class Template Reference
sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T > Class Template Reference
#include <OperationClusteringOCL.hpp>
Public Member Functions
std::vector< size_t > calculate_clusters (base::Grid *grid, sgpp::base::DataMatrix &dataset, double lambda, size_t k, double treshold)
OperationClusteringOCL (std::string opencl_configuration, bool verbose)
Constructor & Destructor Documentation
OperationClusteringOCL()
template<typename T > sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::OperationClusteringOCL (std::string opencl_configuration, bool verbose) inline
Member Function Documentation
calculate_clusters()
template<typename T > std::vector< size_t > sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters (base::Grid * grid, sgpp::base::DataMatrix & dataset, double lambda, size_t k, double treshold) inline
References alpha, sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::create_graph(), sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::createNearestNeighborGraphConfigured(), dataset, sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::find_clusters(), sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::generateb(), grid(), lambda, sgpp::base::DataVector::max(), sgpp::base::DataVector::min(), sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::prune_graph(), and sgpp::datadriven::pruneNearestNeighborGraphConfigured().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationClusteringOCL/OperationClusteringOCL.hpp