SG++-Doxygen-Documentation: sgpp::optimization::optimizer::MultiStart Class Reference
sgpp::optimization::optimizer::MultiStart Class Reference
Meta optimization algorithm calling local algorithm multiple times.
#include <MultiStart.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
const std::vector< size_t > & getHistoryOfInnerIterations () const
size_t getPopulationSize () const
MultiStart (const base::ScalarFunction &f, size_t maxFcnEvalCount=DEFAULT_MAX_FCN_EVAL_COUNT, size_t populationSize=0)
Constructor.
MultiStart (const MultiStart &other)
Copy constructor.
MultiStart (const UnconstrainedOptimizer &optimizer, size_t maxFcnEvalCount=DEFAULT_MAX_FCN_EVAL_COUNT, size_t populationSize=0)
Constructor with custom optimization algorithm.
void optimize () override
Pure virtual method for optimization of the objective function.
void setObjectiveFunction (const base::ScalarFunction &f) override
void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient) override
void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian) override
void setPopulationSize (size_t populationSize)
~MultiStart () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static const size_t DEFAULT_MAX_FCN_EVAL_COUNT = 1000
default maximal number of function evaluations
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Member Functions
void initialize (size_t populationSize)
Initializes populationSize.
Protected Attributes
NelderMead defaultOptimizer
default optimization algorithm
std::vector< size_t > kHist
search history (inner iterations)
std::unique_ptr< UnconstrainedOptimizer > optimizer
optimization algorithm
size_t populationSize
number of individual points
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Meta optimization algorithm calling local algorithm multiple times.
MultiStart generates a random population of a given number of starting points, and then runs a local optimization algorithm for each of the starting point. The best point wins.
Constructor & Destructor Documentation
MultiStart() [1/3]
sgpp::optimization::optimizer::MultiStart::MultiStart (const base::ScalarFunction & f, size_t maxFcnEvalCount = DEFAULT_MAX_FCN_EVAL_COUNT, size_t populationSize = 0)
Constructor.
By default, Nelder-Mead is used as optimization algorithm.
Parameters
f objective function
maxFcnEvalCount maximal number of function evaluations
populationSize number of individual points (default: \(\min(10d, 100)\))
References sgpp::optimization::optimizer::NelderMead::clone(), defaultOptimizer, initialize(), optimizer, and populationSize.
MultiStart() [2/3]
sgpp::optimization::optimizer::MultiStart::MultiStart (const UnconstrainedOptimizer & optimizer, size_t maxFcnEvalCount = DEFAULT_MAX_FCN_EVAL_COUNT, size_t populationSize = 0)
Constructor with custom optimization algorithm.
The current values of the optimizer's N and starting point properties will not be used.
Parameters
optimizer optimization algorithm and objective function
maxFcnEvalCount maximal number of function evaluations
populationSize number of individual points (default: \(\min(10d, 100)\))
References sgpp::optimization::optimizer::UnconstrainedOptimizer::clone(), initialize(), optimizer, and populationSize.
MultiStart() [3/3]
sgpp::optimization::optimizer::MultiStart::MultiStart (const MultiStart & other)
Copy constructor.
Parameters
other optimizer to be copied
References initialize(), optimizer, and populationSize.
~MultiStart()
sgpp::optimization::optimizer::MultiStart::~MultiStart () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::MultiStart::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone(), and sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::FuzzyExtensionPrincipleViaOptimization().
getHistoryOfInnerIterations()
const std::vector< size_t > & sgpp::optimization::optimizer::MultiStart::getHistoryOfInnerIterations () const
Returns
vector in which the k-th entry indicates the number of inner iterations in the k-th (outer) iteration, empty vector on error
References kHist.
getPopulationSize()
size_t sgpp::optimization::optimizer::MultiStart::getPopulationSize () const
Returns
number of individual points
References populationSize.
initialize()
void sgpp::optimization::optimizer::MultiStart::initialize (size_t populationSize) protected
Initializes populationSize.
Parameters
populationSize number of individual points (zero to use default value)
References sgpp::optimization::optimizer::UnconstrainedOptimizer::f, and populationSize.
Referenced by MultiStart(), MultiStart(), and MultiStart().
optimize()
void sgpp::optimization::optimizer::MultiStart::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), sgpp::optimization::optimizer::UnconstrainedOptimizer::clone(), sgpp::base::Printer::disableStatusPrinting(), sgpp::base::Printer::enableStatusPrinting(), sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::optimization::optimizer::UnconstrainedOptimizer::getHistoryOfOptimalPoints(), sgpp::base::Printer::getInstance(), sgpp::base::RandomNumberGenerator::getInstance(), sgpp::base::Printer::getMutex(), sgpp::base::DataMatrix::getNrows(), sgpp::optimization::optimizer::UnconstrainedOptimizer::getOptimalPoint(), sgpp::optimization::optimizer::UnconstrainedOptimizer::getOptimalValue(), sgpp::base::RandomNumberGenerator::getUniformRN(), sgpp::base::Printer::isStatusPrintingEnabled(), kHist, sgpp::base::MutexType::lock(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::optimization::optimizer::UnconstrainedOptimizer::optimize(), optimizer, populationSize, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), sgpp::optimization::optimizer::UnconstrainedOptimizer::setN(), sgpp::optimization::optimizer::UnconstrainedOptimizer::setStartingPoint(), sgpp::base::MutexType::unlock(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
Referenced by sgpp::datadriven::BayesianOptimization::fitScales(), and sgpp::datadriven::BayesianOptimization::main().
setObjectiveFunction()
void sgpp::optimization::optimizer::MultiStart::setObjectiveFunction (const base::ScalarFunction & f) override virtual
Parameters
f objective function
Reimplemented from sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::optimization::optimizer::UnconstrainedOptimizer::f, optimizer, and sgpp::optimization::optimizer::UnconstrainedOptimizer::setObjectiveFunction().
setObjectiveGradient()
void sgpp::optimization::optimizer::MultiStart::setObjectiveGradient (const base::ScalarFunctionGradient * fGradient) override virtual
Parameters
fGradient objective gradient
Reimplemented from sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, optimizer, and sgpp::optimization::optimizer::UnconstrainedOptimizer::setObjectiveGradient().
setObjectiveHessian()
void sgpp::optimization::optimizer::MultiStart::setObjectiveHessian (const base::ScalarFunctionHessian * fHessian) override virtual
Parameters
fHessian objective Hessian
Reimplemented from sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::optimization::optimizer::UnconstrainedOptimizer::fHessian, optimizer, and sgpp::optimization::optimizer::UnconstrainedOptimizer::setObjectiveHessian().
setPopulationSize()
void sgpp::optimization::optimizer::MultiStart::setPopulationSize (size_t populationSize)
Parameters
populationSize number of individual points
References populationSize.
Member Data Documentation
DEFAULT_MAX_FCN_EVAL_COUNT
const size_t sgpp::optimization::optimizer::MultiStart::DEFAULT_MAX_FCN_EVAL_COUNT = 1000 static
default maximal number of function evaluations
defaultOptimizer
NelderMead sgpp::optimization::optimizer::MultiStart::defaultOptimizer protected
default optimization algorithm
Referenced by MultiStart().
kHist
std::vector<size_t> sgpp::optimization::optimizer::MultiStart::kHist protected
search history (inner iterations)
Referenced by getHistoryOfInnerIterations(), and optimize().
optimizer
std::unique_ptr<UnconstrainedOptimizer> sgpp::optimization::optimizer::MultiStart::optimizer protected
optimization algorithm
Referenced by MultiStart(), MultiStart(), MultiStart(), optimize(), setObjectiveFunction(), setObjectiveGradient(), and setObjectiveHessian().
populationSize
size_t sgpp::optimization::optimizer::MultiStart::populationSize protected
number of individual points
Referenced by getPopulationSize(), initialize(), MultiStart(), MultiStart(), MultiStart(), optimize(), and setPopulationSize().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/MultiStart.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/MultiStart.cpp