SG++-Doxygen-Documentation: sgpp::base::GaussLegendreQuadRule1D Class Reference
sgpp::base::GaussLegendreQuadRule1D Class Reference
#include <GaussLegendreQuadRule1D.hpp>
Public Member Functions
GaussLegendreQuadRule1D ()
load gauss quadrature points for uniform weight function.
GaussLegendreQuadRule1D (const GaussLegendreQuadRule1D &that)=delete
void getLevelPointsAndWeightsNormalized (size_t level, base::DataVector &coordinates, base::DataVector &weights)
the coordinates are normalized to [0, 1].
~GaussLegendreQuadRule1D () override
Public Member Functions inherited from sgpp::base::QuadRule1D
void getLevelPointsAndWeights (size_t level, base::DataVector &coordinates, base::DataVector &weights)
size_t getMaxSupportedLevel () const
QuadRule1D ()
virtual ~QuadRule1D ()
Static Public Member Functions
static GaussLegendreQuadRule1D & getInstance ()
Additional Inherited Members
Public Attributes inherited from sgpp::base::QuadRule1D
std::vector< double > coordinatesWeights
Constructor & Destructor Documentation
GaussLegendreQuadRule1D() [1/2]
sgpp::base::GaussLegendreQuadRule1D::GaussLegendreQuadRule1D ()
load gauss quadrature points for uniform weight function.
The points and the weights are generated with numpy.polynomial.legendre.leggauss. the weights are additionally normalized to 1.
References sgpp::base::QuadRule1D::coordinatesWeights.
~GaussLegendreQuadRule1D()
sgpp::base::GaussLegendreQuadRule1D::~GaussLegendreQuadRule1D () override
GaussLegendreQuadRule1D() [2/2]
sgpp::base::GaussLegendreQuadRule1D::GaussLegendreQuadRule1D (const GaussLegendreQuadRule1D & that) delete
Member Function Documentation
getInstance()
GaussLegendreQuadRule1D & sgpp::base::GaussLegendreQuadRule1D::getInstance () static
getLevelPointsAndWeightsNormalized()
void sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized (size_t level, base::DataVector & coordinates, base::DataVector & weights)
the coordinates are normalized to [0, 1].
Parameters
level level of quadrature, is equal to the number of quadrature points
coordinates returns the x-coordinates in [0, 1]
weights returns the corresponding weights (scaled by 0.5)
References sgpp::base::QuadRule1D::getLevelPointsAndWeights(), level, and sgpp::base::DataVector::mult().
Referenced by sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral(), sgpp::base::FundamentalSplineModifiedBasis< LT, IT >::getIntegral(), sgpp::base::NakBsplineBasis< LT, IT >::getIntegral(), sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getIntegral(), sgpp::base::NakPBsplineBasis< LT, IT >::getIntegral(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::OperationWeightedQuadratureNakBspline::OperationWeightedQuadratureNakBspline(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::OperationWeightedQuadratureNakBsplineBoundary(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::OperationWeightedQuadratureNakBsplineExtended(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::OperationWeightedQuadratureNakBsplineModified(), sgpp::base::OperationWeightedQuadratureNakPBspline::OperationWeightedQuadratureNakPBspline(), and sgpp::base::OperationWeightedSecondMomentNak::OperationWeightedSecondMomentNak().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/GaussLegendreQuadRule1D.hpp
base/src/sgpp/base/tools/GaussLegendreQuadRule1D.cpp