SG++-Doxygen-Documentation: sgpp::datadriven::DataTransformation Class Reference
sgpp::datadriven::DataTransformation Class Reference abstract
DataTransformation is an abstraction for an object that provides different transformations on datasets, for example Rosenblatt-transformation to get a uniform distribution over the unit cube.
#include <DataTransformation.hpp>
Public Member Functions
DataTransformation ()=default
Default constructor.
virtual Dataset * doInverseTransformation (Dataset *dataset)=0
Performs the backwards transformation on a given dataset for a data transformationn built with DataTransformationBuilder.
virtual Dataset * doTransformation (Dataset *dataset)=0
Performs a data transformation on a given dataset for a data transformationn built with DataTransformationBuilder.
virtual void initialize (Dataset *dataset, DataTransformationConfig config)=0
Initializes a data transformation for a given dataset according to the specified config.
virtual ~DataTransformation ()=default
Virtual destructor.
Detailed Description
DataTransformation is an abstraction for an object that provides different transformations on datasets, for example Rosenblatt-transformation to get a uniform distribution over the unit cube.
Constructor & Destructor Documentation
DataTransformation()
sgpp::datadriven::DataTransformation::DataTransformation () default
Default constructor.
~DataTransformation()
virtual sgpp::datadriven::DataTransformation::~DataTransformation () virtual default
Virtual destructor.
Member Function Documentation
doInverseTransformation()
virtual Dataset * sgpp::datadriven::DataTransformation::doInverseTransformation (Dataset * dataset) pure virtual
Performs the backwards transformation on a given dataset for a data transformationn built with DataTransformationBuilder.
Parameters
dataset pointer to the dataset to be transformed backwards
Returns
pointer to the backwards transformed dataset
Implemented in sgpp::datadriven::RosenblattTransformation.
doTransformation()
virtual Dataset * sgpp::datadriven::DataTransformation::doTransformation (Dataset * dataset) pure virtual
Performs a data transformation on a given dataset for a data transformationn built with DataTransformationBuilder.
Parameters
dataset pointer to the dataset to be transformed
Returns
pointer to the transformed dataset
Implemented in sgpp::datadriven::RosenblattTransformation.
Referenced by sgpp::datadriven::DataSource::getAllSamples(), and sgpp::datadriven::DataSource::getNextSamples().
initialize()
virtual void sgpp::datadriven::DataTransformation::initialize (Dataset * dataset, DataTransformationConfig config) pure virtual
Initializes a data transformation for a given dataset according to the specified config.
Parameters
dataset pointer to the dataset to be initialized
config configuration containing parameters for initalization
Implemented in sgpp::datadriven::RosenblattTransformation.
Referenced by sgpp::datadriven::DataSource::getAllSamples(), and sgpp::datadriven::DataSource::getNextSamples().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/DataTransformation.hpp