SG++-Doxygen-Documentation: sgpp::base::OCLStretchedBufferMultiPlatform Class Reference
sgpp::base::OCLStretchedBufferMultiPlatform Class Reference
#include <OCLStretchedBufferMultiPlatform.hpp>
Public Member Functions
void combineBuffer (std::map< cl_platform_id, size_t * > indexStart, std::map< cl_platform_id, size_t * > indexEnd, cl_platform_id platformId)
void copyToOtherHostBuffers (cl_platform_id originPlatformId)
void freeBuffer ()
cl_mem * getBuffer (cl_platform_id platformId, size_t deviceNumber)
void * getMappedHostBuffer (cl_platform_id platformId)
void initializeBuffer (size_t sizeofType, size_t elements)
bool isInitialized ()
OCLStretchedBufferMultiPlatform (std::shared_ptr< OCLManagerMultiPlatform > manager)
void readFromBuffer (std::map< cl_platform_id, size_t * > indexStart, std::map< cl_platform_id, size_t * > indexEnd)
void writeToBuffer ()
~OCLStretchedBufferMultiPlatform ()
Constructor & Destructor Documentation
OCLStretchedBufferMultiPlatform()
sgpp::base::OCLStretchedBufferMultiPlatform::OCLStretchedBufferMultiPlatform (std::shared_ptr< OCLManagerMultiPlatform > manager)
~OCLStretchedBufferMultiPlatform()
sgpp::base::OCLStretchedBufferMultiPlatform::~OCLStretchedBufferMultiPlatform ()
References freeBuffer().
Member Function Documentation
combineBuffer()
void sgpp::base::OCLStretchedBufferMultiPlatform::combineBuffer (std::map< cl_platform_id, size_t * > indexStart, std::map< cl_platform_id, size_t * > indexEnd, cl_platform_id platformId)
copyToOtherHostBuffers()
void sgpp::base::OCLStretchedBufferMultiPlatform::copyToOtherHostBuffers (cl_platform_id originPlatformId)
freeBuffer()
void sgpp::base::OCLStretchedBufferMultiPlatform::freeBuffer ()
Referenced by doStuff(), and ~OCLStretchedBufferMultiPlatform().
getBuffer()
cl_mem * sgpp::base::OCLStretchedBufferMultiPlatform::getBuffer (cl_platform_id platformId, size_t deviceNumber)
getMappedHostBuffer()
void * sgpp::base::OCLStretchedBufferMultiPlatform::getMappedHostBuffer (cl_platform_id platformId)
initializeBuffer()
void sgpp::base::OCLStretchedBufferMultiPlatform::initializeBuffer (size_t sizeofType, size_t elements)
Referenced by doStuff().
isInitialized()
bool sgpp::base::OCLStretchedBufferMultiPlatform::isInitialized ()
readFromBuffer()
void sgpp::base::OCLStretchedBufferMultiPlatform::readFromBuffer (std::map< cl_platform_id, size_t * > indexStart, std::map< cl_platform_id, size_t * > indexEnd)
writeToBuffer()
void sgpp::base::OCLStretchedBufferMultiPlatform::writeToBuffer ()
The documentation for this class was generated from the following files:
base/src/sgpp/base/opencl/OCLStretchedBufferMultiPlatform.hpp
base/src/sgpp/base/opencl/OCLStretchedBufferMultiPlatform.cpp