SG++-Doxygen-Documentation: sgpp::base::VectorDistributionRefinementFunctor Class Reference
sgpp::base::VectorDistributionRefinementFunctor Class Reference
A refinement functor for vector valued function.
#include <VectorDistributionRefinementFunctor.hpp>
Public Member Functions
size_t getRefinementsNum () const override
Returns the maximal number of points that should be refined.
double getRefinementThreshold () const override
Returns the threshold for refinement.
double operator() (GridStorage &storage, size_t seq) const override
This should be returning a refinement value for every grid point.
double start () const override
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
VectorDistributionRefinementFunctor (DataMatrix &alphas, sgpp::base::DistributionsVector pdfs, size_t refinements_num=1, double threshold=0.0)
Constructor.
~VectorDistributionRefinementFunctor () override
Destructor.
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
RefinementFunctor ()
Constructor.
virtual ~RefinementFunctor ()
Destructor.
Protected Attributes
DataMatrix & alphas
pointer to the vector that stores the alpha values
sgpp::base::DistributionsVector pdfs
size_t refinements_num
number of grid points to refine
sgpp::base::DataVector sampleVector
double threshold
threshold, only the points with greater to equal absolute values of the refinement criterion (e.g.
Additional Inherited Members
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Detailed Description
A refinement functor for vector valued function.
Refining according to the maximal absolute values in a DataMatrix (of coefficients) provided.
Constructor & Destructor Documentation
VectorDistributionRefinementFunctor()
sgpp::base::VectorDistributionRefinementFunctor::VectorDistributionRefinementFunctor (DataMatrix & alphas, sgpp::base::DistributionsVector pdfs, size_t refinements_num = 1, double threshold = 0.0)
Constructor.
Parameters
alphas DataMatrix that is basis for refinement decisions. The [i,j]-th entry corresponds to the i-th grid point and the j-th result (<=> each column are coefficients for one output dimension)
pdfs the probability density functions 'distributions'
refinements_num Number of grid points which should be refined (if possible - there could be less refinable grid points)
threshold The absolute value of the entries have to be greater or equal than the threshold
This functor draws random samples following the pdfs and refines the grid points closest to these samples
References sgpp::base::DataMatrix::get(), sgpp::base::DistributionsVector::getBounds(), sgpp::base::DistributionsVector::getSize(), pdfs, sgpp::base::DistributionsVector::sample(), and sampleVector.
~VectorDistributionRefinementFunctor()
sgpp::base::VectorDistributionRefinementFunctor::~VectorDistributionRefinementFunctor () override
Destructor.
Member Function Documentation
getRefinementsNum()
size_t sgpp::base::VectorDistributionRefinementFunctor::getRefinementsNum () const override virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
number of points that should refined. Default value: 1.
Reimplemented from sgpp::base::RefinementFunctor.
References refinements_num.
getRefinementThreshold()
double sgpp::base::VectorDistributionRefinementFunctor::getRefinementThreshold () const override virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion (e.g., alpha or error) greater or equal to this threshold will be refined.
Returns
threshold value for refinement. Default value: 0.
Implements sgpp::base::RefinementFunctor.
References threshold.
operator()()
double sgpp::base::VectorDistributionRefinementFunctor::operator() (GridStorage & storage, size_t seq) const override virtual
This should be returning a refinement value for every grid point.
Parameters
storage reference to the grids storage object
seq sequence number in the coefficients array
Returns
refinement value
Implements sgpp::base::RefinementFunctor.
References sgpp::base::HashGridStorage::getPointCoordinates(), and sampleVector.
start()
double sgpp::base::VectorDistributionRefinementFunctor::start () const override virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implements sgpp::base::RefinementFunctor.
Member Data Documentation
alphas
DataMatrix& sgpp::base::VectorDistributionRefinementFunctor::alphas protected
pointer to the vector that stores the alpha values
pdfs
sgpp::base::DistributionsVector sgpp::base::VectorDistributionRefinementFunctor::pdfs protected
Referenced by VectorDistributionRefinementFunctor().
refinements_num
size_t sgpp::base::VectorDistributionRefinementFunctor::refinements_num protected
number of grid points to refine
Referenced by getRefinementsNum().
sampleVector
sgpp::base::DataVector sgpp::base::VectorDistributionRefinementFunctor::sampleVector protected
Referenced by operator()(), and VectorDistributionRefinementFunctor().
threshold
double sgpp::base::VectorDistributionRefinementFunctor::threshold protected
threshold, only the points with greater to equal absolute values of the refinement criterion (e.g.
alpha or error) will be refined
Referenced by getRefinementThreshold().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/functors/VectorDistributionRefinementFunctor.hpp
base/src/sgpp/base/grid/generation/functors/VectorDistributionRefinementFunctor.cpp