SG++-Doxygen-Documentation: sgpp::base::Basis< LT, IT > Class Template Reference
sgpp::base::Basis< LT, IT > Class Template Reference abstract
Basis class for basis functions.
#include <Basis.hpp>
Public Member Functions
virtual double eval (LT level, IT index, double x)=0
Evaluate the basis function with given level and index.
virtual double evalDx (LT level, IT index, double x)=0
Evaluate the basis functions derivative with given level and index.
virtual size_t getDegree () const =0
Returns the polynomial degree of the basis.
virtual double getIntegral (LT level, IT index)=0
returns the integal of the current basis function
virtual ~Basis ()
Destructor.
Detailed Description
template<class LT, class IT>
class sgpp::base::Basis< LT, IT >
Basis class for basis functions.
Constructor & Destructor Documentation
~Basis()
template<class LT , class IT > virtual sgpp::base::Basis< LT, IT >::~Basis () inline virtual
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > virtual double sgpp::base::Basis< LT, IT >::eval (LT level, IT index, double x) pure virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implemented in sgpp::base::BsplineBasis< LT, IT >, sgpp::base::BsplineBoundaryBasis< LT, IT >, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >, sgpp::base::BsplineModifiedBasis< LT, IT >, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::FundamentalNakSplineBasis< LT, IT >, sgpp::base::FundamentalSplineBasis< LT, IT >, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >, sgpp::base::LinearBasis< LT, IT >, sgpp::base::LinearBoundaryBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::LinearModifiedBasis< LT, IT >, sgpp::base::LinearPeriodicBasis< LT, IT >, sgpp::base::NakBsplineBasis< LT, IT >, sgpp::base::NakBsplineBasisDeriv1< LT, IT >, sgpp::base::NakBsplineBasisDeriv2< LT, IT >, sgpp::base::NakBsplineBoundaryBasis< LT, IT >, sgpp::base::NakBsplineExtendedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv1< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >, sgpp::base::NakPBsplineBasis< LT, IT >, sgpp::base::NaturalBsplineBasis< LT, IT >, sgpp::base::WaveletBasis< LT, IT >, sgpp::base::WaveletBoundaryBasis< LT, IT >, sgpp::base::WaveletModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::PolyBasis< LT, IT >, sgpp::base::PolyBoundaryBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::PolyModifiedBasis< LT, IT >, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >, and sgpp::base::PrewaveletBasis< LT, IT >.
Referenced by sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::PredictiveRefinementIndicator::operator()(), sgpp::base::ForwardSelectorRefinementIndicator::update(), and sgpp::base::ImpurityRefinementIndicator::update().
evalDx()
template<class LT , class IT > virtual double sgpp::base::Basis< LT, IT >::evalDx (LT level, IT index, double x) pure virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implemented in sgpp::base::BsplineBasis< LT, IT >, sgpp::base::BsplineBoundaryBasis< LT, IT >, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >, sgpp::base::BsplineModifiedBasis< LT, IT >, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::FundamentalNakSplineBasis< LT, IT >, sgpp::base::FundamentalSplineBasis< LT, IT >, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineBasis< LT, IT >, sgpp::base::NakBsplineBoundaryBasis< LT, IT >, sgpp::base::NakBsplineExtendedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv1< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >, sgpp::base::NakPBsplineBasis< LT, IT >, sgpp::base::WaveletBasis< LT, IT >, sgpp::base::WaveletBoundaryBasis< LT, IT >, sgpp::base::WaveletModifiedBasis< LT, IT >, sgpp::base::LinearBasis< LT, IT >, sgpp::base::LinearBoundaryBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::LinearModifiedBasis< LT, IT >, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::LinearPeriodicBasis< LT, IT >, sgpp::base::LinearStretchedBasis< LT, IT >, sgpp::base::LinearStretchedBoundaryBasis< LT, IT >, sgpp::base::NakBsplineBasisDeriv1< LT, IT >, sgpp::base::NakBsplineBasisDeriv2< LT, IT >, sgpp::base::NaturalBsplineBasis< LT, IT >, sgpp::base::PolyBasis< LT, IT >, sgpp::base::PolyBoundaryBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::PolyModifiedBasis< LT, IT >, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::PrewaveletBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >, and sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >.
getDegree()
template<class LT , class IT > virtual size_t sgpp::base::Basis< LT, IT >::getDegree () const pure virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implemented in sgpp::base::BsplineBasis< LT, IT >, sgpp::base::BsplineBasis< unsigned int, unsigned int >, sgpp::base::BsplineBoundaryBasis< LT, IT >, sgpp::base::BsplineBoundaryBasis< unsigned int, unsigned int >, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >, sgpp::base::BsplineClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::BsplineModifiedBasis< LT, IT >, sgpp::base::BsplineModifiedBasis< unsigned int, unsigned int >, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::BsplineModifiedClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::FundamentalNakSplineBasis< LT, IT >, sgpp::base::FundamentalNakSplineBasis< unsigned int, unsigned int >, sgpp::base::FundamentalSplineBasis< LT, IT >, sgpp::base::FundamentalSplineBasis< unsigned int, unsigned int >, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >, sgpp::base::FundamentalSplineModifiedBasis< unsigned int, unsigned int >, sgpp::base::LinearBasis< LT, IT >, sgpp::base::LinearBasis< unsigned int, unsigned int >, sgpp::base::LinearBoundaryBasis< LT, IT >, sgpp::base::LinearBoundaryBasis< unsigned int, unsigned int >, sgpp::base::LinearClenshawCurtisBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int >, sgpp::base::LinearModifiedBasis< LT, IT >, sgpp::base::LinearModifiedBasis< unsigned int, unsigned int >, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::LinearModifiedClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::LinearPeriodicBasis< LT, IT >, sgpp::base::LinearStretchedBasis< LT, IT >, sgpp::base::LinearStretchedBoundaryBasis< LT, IT >, sgpp::base::NakBsplineBasis< LT, IT >, sgpp::base::NakBsplineBasis< unsigned int, unsigned int >, sgpp::base::NakBsplineBasisDeriv1< LT, IT >, sgpp::base::NakBsplineBasisDeriv1< unsigned int, unsigned int >, sgpp::base::NakBsplineBasisDeriv2< LT, IT >, sgpp::base::NakBsplineBasisDeriv2< unsigned int, unsigned int >, sgpp::base::NakBsplineBoundaryBasis< LT, IT >, sgpp::base::NakBsplineBoundaryBasis< unsigned int, unsigned int >, sgpp::base::NakBsplineExtendedBasis< LT, IT >, sgpp::base::NakBsplineExtendedBasis< unsigned int, unsigned int >, sgpp::base::NakBsplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasis< unsigned int, unsigned int >, sgpp::base::NakBsplineModifiedBasisDeriv1< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv1< unsigned int, unsigned int >, sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv2< unsigned int, unsigned int >, sgpp::base::NakPBsplineBasis< LT, IT >, sgpp::base::NakPBsplineBasis< unsigned int, unsigned int >, sgpp::base::NaturalBsplineBasis< LT, IT >, sgpp::base::NaturalBsplineBasis< unsigned int, unsigned int >, sgpp::base::PolyBasis< LT, IT >, sgpp::base::PolyBasis< unsigned int, unsigned int >, sgpp::base::PolyBoundaryBasis< LT, IT >, sgpp::base::PolyBoundaryBasis< unsigned int, unsigned int >, sgpp::base::PolyClenshawCurtisBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int >, sgpp::base::PolyModifiedBasis< LT, IT >, sgpp::base::PolyModifiedBasis< unsigned int, unsigned int >, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::PolyModifiedClenshawCurtisBasis< unsigned int, unsigned int >, sgpp::base::PrewaveletBasis< LT, IT >, sgpp::base::WaveletBasis< LT, IT >, sgpp::base::WaveletBasis< unsigned int, unsigned int >, sgpp::base::WaveletBoundaryBasis< LT, IT >, sgpp::base::WaveletBoundaryBasis< unsigned int, unsigned int >, sgpp::base::WaveletModifiedBasis< LT, IT >, sgpp::base::WaveletModifiedBasis< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasis< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv2< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv2< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasis< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasisDeriv1< unsigned int, unsigned int >, sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >, and sgpp::base::WeaklyFundamentalSplineBasisDeriv2< unsigned int, unsigned int >.
getIntegral()
template<class LT , class IT > virtual double sgpp::base::Basis< LT, IT >::getIntegral (LT level, IT index) pure virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implemented in sgpp::base::BsplineBoundaryBasis< LT, IT >, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >, sgpp::base::BsplineModifiedBasis< LT, IT >, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::FundamentalSplineBasis< LT, IT >, sgpp::base::FundamentalSplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineBasis< LT, IT >, sgpp::base::NakBsplineBoundaryBasis< LT, IT >, sgpp::base::NakBsplineExtendedBasis< LT, IT >, sgpp::base::NakPBsplineBasis< LT, IT >, sgpp::base::BsplineBasis< LT, IT >, sgpp::base::FundamentalNakSplineBasis< LT, IT >, sgpp::base::LinearBasis< LT, IT >, sgpp::base::LinearBoundaryBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBasis< LT, IT >, sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::LinearModifiedBasis< LT, IT >, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::LinearPeriodicBasis< LT, IT >, sgpp::base::LinearStretchedBoundaryBasis< LT, IT >, sgpp::base::NakBsplineBasisDeriv1< LT, IT >, sgpp::base::NakBsplineBasisDeriv2< LT, IT >, sgpp::base::NakBsplineModifiedBasis< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv1< LT, IT >, sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >, sgpp::base::NaturalBsplineBasis< LT, IT >, sgpp::base::PolyBasis< LT, IT >, sgpp::base::PolyBoundaryBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBasis< LT, IT >, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >, sgpp::base::PolyModifiedBasis< LT, IT >, sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >, sgpp::base::PrewaveletBasis< LT, IT >, sgpp::base::WaveletBasis< LT, IT >, sgpp::base::WaveletBoundaryBasis< LT, IT >, sgpp::base::WaveletModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >, sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv2< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >, sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >, and sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >.
Referenced by sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), and sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/Basis.hpp