SG++-Doxygen-Documentation: sgpp::base::ClenshawCurtisTable Class Reference
sgpp::base::ClenshawCurtisTable Class Reference
Lookup table for 1D Clenshaw-Curtis points.
#include <ClenshawCurtisTable.hpp>
Public Types
typedef HashGridPoint::index_type index_type
typedef HashGridPoint::level_type level_type
Public Member Functions
double getPoint (level_type l, index_type i) const
double getPoint (level_type l, index_type i, index_type hInv) const
Static Public Member Functions
static ClenshawCurtisTable & getInstance ()
Static Public Attributes
static const level_type DEFAULT_MAX_LEVEL = 16
default number of intervals
Protected Member Functions
double calculatePoint (double h, index_type i) const
double calculatePoint (index_type hInv, index_type i) const
Protected Attributes
level_type maxLevel
maximal level
DataVector table
lookup table
Detailed Description
Lookup table for 1D Clenshaw-Curtis points.
This class precomputes the first maxLevel levels of a 1D Clenshaw-Curtis grid to increase performance of Clenshaw-Curtis grids.
Member Typedef Documentation
index_type
typedef HashGridPoint::index_type sgpp::base::ClenshawCurtisTable::index_type
level_type
typedef HashGridPoint::level_type sgpp::base::ClenshawCurtisTable::level_type
Member Function Documentation
calculatePoint() [1/2]
double sgpp::base::ClenshawCurtisTable::calculatePoint (double h, index_type i) const inline protected
Parameters
h step width of the grid point (2^(-l))
i index of the grid point (can be even)
References h, and M_PI.
calculatePoint() [2/2]
double sgpp::base::ClenshawCurtisTable::calculatePoint (index_type hInv, index_type i) const inline protected
Parameters
hInv 2^l
i index of the grid point (can be even)
References calculatePoint().
Referenced by calculatePoint(), getPoint(), and getPoint().
getInstance()
ClenshawCurtisTable & sgpp::base::ClenshawCurtisTable::getInstance () static
getPoint() [1/2]
double sgpp::base::ClenshawCurtisTable::getPoint (level_type l, index_type i) const inline
Parameters
l level of the grid point
i index of the grid point (can be even)
References calculatePoint(), sgpp::base::DataVector::get(), maxLevel, and table.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::LinearClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::LinearClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), and sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec().
getPoint() [2/2]
double sgpp::base::ClenshawCurtisTable::getPoint (level_type l, index_type i, index_type hInv) const inline
Parameters
l level of the grid point
i index of the grid point (can be even)
hInv 2^l
References calculatePoint(), sgpp::base::DataVector::get(), maxLevel, and table.
Member Data Documentation
DEFAULT_MAX_LEVEL
const level_type sgpp::base::ClenshawCurtisTable::DEFAULT_MAX_LEVEL = 16 static
default number of intervals
maxLevel
level_type sgpp::base::ClenshawCurtisTable::maxLevel protected
maximal level
Referenced by python.uq.operations.forcePositivity.localHierarchicalIntersectionSearch.LocalHierarchicalIntersectionCandidates::getMaxLevelOfChildrenUpToMaxLevel(), getPoint(), getPoint(), python.uq.refinement.AdmissibleSet.AdmissibleSetGenerator::insertPoint(), and python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive().
table
DataVector sgpp::base::ClenshawCurtisTable::table protected
lookup table
Referenced by getPoint(), and getPoint().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/ClenshawCurtisTable.hpp
base/src/sgpp/base/tools/ClenshawCurtisTable.cpp