SG++-Doxygen-Documentation: sgpp::datadriven::OperationRegularizationDiagonal Class Reference
sgpp::datadriven::OperationRegularizationDiagonal Class Reference abstract
Implementation of the application of a diagonal matrix to a DataVector for regularization.
#include <OperationRegularizationDiagonal.hpp>
Public Member Functions
virtual void mult (base::DataVector &alpha, base::DataVector &result)
Multiplication with diagonal matrix.
OperationRegularizationDiagonal (base::GridStorage *storage, int mode, double k)
Constructor of OperationRegularizationDiagonal.
virtual ~OperationRegularizationDiagonal ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Static Public Attributes
static const int ANISOTROPIC_PENALTY = 4
static const int H0HKLAPLACE = 2
Diagonal scaling for pseudo-laplace, replacing \(L_2\) with \(H^0\) in 1d.
static const int HKMIX = 1
Diagonal scaling for \(H^k_\textbf{mix}\)-norm (product of \(H^k\) 1D norms)
static const int ISOTROPIC_PENALTY = 3
Protected Member Functions
virtual void init ()
Check for mode and run corresponding init.
virtual void initAnisotropicPenalty ()
Initialize ANISOTROPIC_PENALTY, ignores constructor parameter k.
virtual void initH0HkLaplace (double k)=0
Initialize H0HkLaplace.
virtual void initHkmix (double k)=0
Initialize Hkmix.
virtual void initIsotropicPenalty ()
Initialize ISOTROPIC_PENALTY, ignores constructor parameter k.
Protected Attributes
base::DataVector diagonal
double k
int mode
size_t size
base::GridStorage * storage
Detailed Description
Implementation of the application of a diagonal matrix to a DataVector for regularization.
This class implements several scaling possibilities.
Constructor & Destructor Documentation
OperationRegularizationDiagonal()
sgpp::datadriven::OperationRegularizationDiagonal::OperationRegularizationDiagonal (base::GridStorage * storage, int mode, double k)
Constructor of OperationRegularizationDiagonal.
Constructor should most likely call init() in subclasses.
Parameters
storage Pointer to grid's storage object
mode Mode, specifying which regularization to use. Example: OperationRegularizationDiagonal::HKMIX.
k Parameter for \(H^k\)
References sgpp::base::HashGridStorage::getSize(), and size.
~OperationRegularizationDiagonal()
virtual sgpp::datadriven::OperationRegularizationDiagonal::~OperationRegularizationDiagonal () inline virtual
Destructor.
Member Function Documentation
init()
void sgpp::datadriven::OperationRegularizationDiagonal::init () protected virtual
Check for mode and run corresponding init.
References ANISOTROPIC_PENALTY, H0HKLAPLACE, HKMIX, initAnisotropicPenalty(), initH0HkLaplace(), initHkmix(), initIsotropicPenalty(), ISOTROPIC_PENALTY, k, and mode.
Referenced by mult(), and sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::OperationRegularizationDiagonalLinearBoundary().
initAnisotropicPenalty()
void sgpp::datadriven::OperationRegularizationDiagonal::initAnisotropicPenalty () protected virtual
Initialize ANISOTROPIC_PENALTY, ignores constructor parameter k.
Diagonal entries are \(\frac{1}{2}\log(1+(\frac{\max\{l_1,\dots,l_d\}}{\max\{\min\{l_1,\dots,l_d\},1\}})d)\).
References diagonal, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getLevelMax(), sgpp::base::HashGridPoint::getLevelMin(), sgpp::base::HashGridStorage::getPoint(), size, and storage.
Referenced by init().
initH0HkLaplace()
virtual void sgpp::datadriven::OperationRegularizationDiagonal::initH0HkLaplace (double k) protected pure virtual
Initialize H0HkLaplace.
Diagonal entries are \(\sum_{k=1}^d \langle \phi_k(x_k),\phi_k(x_k) \rangle_{H^k} \prod_{l\neq k} \langle \phi_k(x_k),\phi_k(x_k) \rangle_{H^0}\).
Parameters
k Parameter k
Implemented in sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary.
Referenced by init().
initHkmix()
virtual void sgpp::datadriven::OperationRegularizationDiagonal::initHkmix (double k) protected pure virtual
Initialize Hkmix.
Diagonal entries are \(\prod_{k=1}^d \langle \phi_k(x_k),\phi_k(x_k) \rangle_{H^k}\).
Parameters
k Parameter k
Implemented in sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary.
Referenced by init().
initIsotropicPenalty()
void sgpp::datadriven::OperationRegularizationDiagonal::initIsotropicPenalty () protected virtual
Initialize ISOTROPIC_PENALTY, ignores constructor parameter k.
Diagonal entries are \(\frac{1}{\max\{l_1,\dots,l_d\}-\min\{l_1,\dots,l_d\}+1}d\).
References diagonal, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getLevelMax(), sgpp::base::HashGridPoint::getLevelMin(), sgpp::base::HashGridStorage::getPoint(), size, and storage.
Referenced by init().
mult()
void sgpp::datadriven::OperationRegularizationDiagonal::mult (base::DataVector & alpha, base::DataVector & result) virtual
Multiplication with diagonal matrix.
Parameters
alpha Source vector
result Result vector (entries are overwritten)
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataVector::componentwise_mult(), sgpp::base::DataVector::copyFrom(), diagonal, sgpp::base::HashGridStorage::getSize(), init(), size, and storage.
Member Data Documentation
ANISOTROPIC_PENALTY
const int sgpp::datadriven::OperationRegularizationDiagonal::ANISOTROPIC_PENALTY = 4 static
Referenced by init().
diagonal
base::DataVector sgpp::datadriven::OperationRegularizationDiagonal::diagonal protected
Referenced by initAnisotropicPenalty(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), initIsotropicPenalty(), and mult().
H0HKLAPLACE
const int sgpp::datadriven::OperationRegularizationDiagonal::H0HKLAPLACE = 2 static
Diagonal scaling for pseudo-laplace, replacing \(L_2\) with \(H^0\) in 1d.
Referenced by init().
HKMIX
const int sgpp::datadriven::OperationRegularizationDiagonal::HKMIX = 1 static
Diagonal scaling for \(H^k_\textbf{mix}\)-norm (product of \(H^k\) 1D norms)
Referenced by init().
ISOTROPIC_PENALTY
const int sgpp::datadriven::OperationRegularizationDiagonal::ISOTROPIC_PENALTY = 3 static
Referenced by init().
k
double sgpp::datadriven::OperationRegularizationDiagonal::k protected
Referenced by python.uq.uq_setting.UQSettingManager.Sampler::expandSample(), init(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), python.uq.uq_setting.UQSettingManager.Sampler::reset(), and python.uq.uq_setting.UQSettingManager.Sampler::unitSample().
mode
int sgpp::datadriven::OperationRegularizationDiagonal::mode protected
Referenced by init().
size
size_t sgpp::datadriven::OperationRegularizationDiagonal::size protected
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), python.data.DataContainer.DataContainer::getSize(), initAnisotropicPenalty(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), initIsotropicPenalty(), mult(), and OperationRegularizationDiagonal().
storage
base::GridStorage* sgpp::datadriven::OperationRegularizationDiagonal::storage protected
Referenced by initAnisotropicPenalty(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), initIsotropicPenalty(), and mult().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRegularizationDiagonal.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRegularizationDiagonal.cpp