SG++-Doxygen-Documentation: sgpp::datadriven::SystemMatrixDensityRatioEstimation Class Reference
sgpp::datadriven::SystemMatrixDensityRatioEstimation Class Reference
Class that implements the virtual class base::OperationMatrix for the application of density ratio estimation for SystemMatrixDRE.
#include <SystemMatrixDensityRatioEstimation.hpp>
Public Member Functions
virtual void generateb (base::DataVector &b)
Generates the right hand side of the equation.
virtual void mult (base::DataVector &alpha, base::DataVector &result)
starts the Multiplication with the matrix
virtual void prepareGrid ()
forward declaration
void setImplementation (datadriven::OperationMultipleEvalConfiguration operationConfiguration)
SystemMatrixDensityRatioEstimation (base::Grid &SparseGrid, base::DataMatrix &trainDataP, base::DataMatrix &trainDataQ, double lambda)
Std-Constructor.
virtual ~SystemMatrixDensityRatioEstimation ()
Std-Destructor.
Public Member Functions inherited from sgpp::datadriven::DMSystemMatrixDRE
DMSystemMatrixDRE (base::DataMatrix &trainDataP, base::DataMatrix &trainDataQ, double lambda)
Std-Constructor.
virtual void getTimers (double &timeMult, double &computeMult, double &timeMultTrans, double &computeMultTrans)
gets the timer's values by saving them into call by reference values
virtual void resetTimers ()
resets all timers to 0
virtual ~DMSystemMatrixDRE ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::DMSystemMatrixDRE
double completeTimeMult_
time needed for Mult
double completeTimeMultTrans_
time needed for Mult transposed
double computeTimeMult_
time needed only for the computation of mult, interesting on accelerator boards
double computeTimeMultTrans_
time needed only for the computation of mult transposed, interesting on accelerator boards
base::DataMatrix datasetP_
the datasets
base::DataMatrix datasetQ_
double lambda_
the lambda, the regularisation parameter
base::SGppStopwatch * myTimer_
Stopwatch needed to determine the durations of mult and mult transposed.
Detailed Description
Class that implements the virtual class base::OperationMatrix for the application of density ratio estimation for SystemMatrixDRE.
The Identity matrix is used as regularization operator.
For the Operation B's mult and mutlTransposed functions vectorized formulations are used.
Constructor & Destructor Documentation
SystemMatrixDensityRatioEstimation()
sgpp::datadriven::SystemMatrixDensityRatioEstimation::SystemMatrixDensityRatioEstimation (base::Grid & SparseGrid, base::DataMatrix & trainDataP, base::DataMatrix & trainDataQ, double lambda)
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
trainDataP reference to base::DataMatrix that contains the training data for first dataset
trainDataQ reference to base::DataMatrix that contains the training data for second dataset
lambda the lambda, the regression parameter
References sgpp::op_factory::createOperationMultipleEval(), sgpp::datadriven::DMSystemMatrixDRE::datasetP_, sgpp::datadriven::DMSystemMatrixDRE::datasetQ_, and sgpp::base::DataMatrix::getNrows().
~SystemMatrixDensityRatioEstimation()
sgpp::datadriven::SystemMatrixDensityRatioEstimation::~SystemMatrixDensityRatioEstimation () virtual
Std-Destructor.
Member Function Documentation
generateb()
void sgpp::datadriven::SystemMatrixDensityRatioEstimation::generateb (base::DataVector & b) virtual
Generates the right hand side of the equation.
Parameters
b reference to the vector that will contain the result of the matrix vector multiplication on the rhs
Implements sgpp::datadriven::DMSystemMatrixDRE.
References sgpp::datadriven::DMSystemMatrixDRE::completeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixDRE::computeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixDRE::myTimer_, sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
mult()
void sgpp::datadriven::SystemMatrixDensityRatioEstimation::mult (base::DataVector & alpha, base::DataVector & result) virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::datadriven::DMSystemMatrixDRE.
References alpha, sgpp::base::DataVector::axpy(), sgpp::datadriven::DMSystemMatrixDRE::completeTimeMult_, sgpp::datadriven::DMSystemMatrixDRE::completeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixDRE::computeTimeMult_, sgpp::datadriven::DMSystemMatrixDRE::computeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixDRE::lambda_, sgpp::base::DataVector::mult(), sgpp::datadriven::DMSystemMatrixDRE::myTimer_, sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
prepareGrid()
void sgpp::datadriven::SystemMatrixDensityRatioEstimation::prepareGrid () virtual
forward declaration
rebuilds the base::DataMatrix for Level and Index this routine is needed for supporting adaptive grids with vectorized high performance kernels
Reimplemented from sgpp::datadriven::DMSystemMatrixDRE.
setImplementation()
void sgpp::datadriven::SystemMatrixDensityRatioEstimation::setImplementation (datadriven::OperationMultipleEvalConfiguration operationConfiguration)
References sgpp::op_factory::createOperationMultipleEval(), sgpp::datadriven::DMSystemMatrixDRE::datasetP_, and sgpp::datadriven::DMSystemMatrixDRE::datasetQ_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/SystemMatrixDensityRatioEstimation.hpp
datadriven/src/sgpp/datadriven/algorithm/SystemMatrixDensityRatioEstimation.cpp