SG++-Doxygen-Documentation: sgpp::solver::RidgeFunction Class Reference
sgpp::solver::RidgeFunction Class Reference
The RidgeFunction class.
#include <RidgeFunction.hpp>
Public Member Functions
double eval (sgpp::base::DataVector weights) override
eval evaluates the regularization function for weights.
base::DataVector prox (const sgpp::base::DataVector &weights, double stepsize) override
prox evaluates the proximal operator for the function for weights.
RidgeFunction (double lambda)
RidgeFunction.
~RidgeFunction () override
Public Member Functions inherited from sgpp::solver::RegularizationFunction
virtual ~RegularizationFunction ()
Detailed Description
The RidgeFunction class.
Corresponds to the regularization function \(\Vert \boldsymbol{\alpha} \Vert_2^2\).
Constructor & Destructor Documentation
RidgeFunction()
sgpp::solver::RidgeFunction::RidgeFunction (double lambda) inline explicit
RidgeFunction.
Parameters
lambda controls the regularization strength.
References lambda.
~RidgeFunction()
sgpp::solver::RidgeFunction::~RidgeFunction () inline override
Member Function Documentation
eval()
double sgpp::solver::RidgeFunction::eval (sgpp::base::DataVector weights) inline override virtual
eval evaluates the regularization function for weights.
Parameters
weights
Implements sgpp::solver::RegularizationFunction.
References sgpp::base::DataVector::dotProduct().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
prox()
base::DataVector sgpp::solver::RidgeFunction::prox (const sgpp::base::DataVector & weights, double stepsize) inline override virtual
prox evaluates the proximal operator for the function for weights.
Parameters
weights
stepsize is the stepsize used for the proximal step
Implements sgpp::solver::RegularizationFunction.
References sgpp::base::DataVector::getSize().
The documentation for this class was generated from the following file:
solver/src/sgpp/solver/sle/fista/RidgeFunction.hpp