SG++-Doxygen-Documentation: sgpp::datadriven::FitterConfiguration Class Reference
sgpp::datadriven::FitterConfiguration Class Reference abstract
General configuration object for fitters.
#include <FitterConfiguration.hpp>
Public Member Functions
virtual FitterConfiguration * clone () const =0
Polymorphic clone pattern.
void dumpToStream (std::ostream &stream_out=std::cout) const
print out all parameters to stream
FitterConfiguration ()=default
Sets up a Fitter configuration with its default values.
FitterConfiguration (const FitterConfiguration &rhs)=default
Copy constructor.
FitterConfiguration (FitterConfiguration &&rhs)=default
Move constructor.
datadriven::CrossvalidationConfiguration & getCrossvalidationConfig ()
Get or set how the crossvalidation should behave.
const datadriven::CrossvalidationConfiguration & getCrossvalidationConfig () const
Get how the crossvalidation should behave.
const datadriven::DatabaseConfiguration & getDatabaseConfig () const
Returns the database configuration, i.e.
datadriven::DensityEstimationConfiguration & getDensityEstimationConfig ()
Get or set how the density estimation should behave.
const datadriven::DensityEstimationConfiguration & getDensityEstimationConfig () const
Get how the density estimation should behave.
const datadriven::GeometryConfiguration & getGeometryConfig () const
base::GeneralGridConfiguration & getGridConfig ()
Get or set initial conditions for the grid before adaptive refinement.
const base::GeneralGridConfiguration & getGridConfig () const
Get initial conditions for the grid before adaptive refinement.
const datadriven::LearnerConfiguration & getLearnerConfig () const
Returns the configuration for the learner's behaviour.
datadriven::OperationMultipleEvalConfiguration & getMultipleEvalConfig ()
Get or set implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
const datadriven::OperationMultipleEvalConfiguration & getMultipleEvalConfig () const
Get implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
const datadriven::ParallelConfiguration & getParallelConfig () const
Returns the configuration for parallelization with ScaLAPACK.
base::AdaptivityConfiguration & getRefinementConfig ()
Get or set how the adaptivity algorithms for the grid should behave.
const base::AdaptivityConfiguration & getRefinementConfig () const
Get how the adaptivity algorithms for the grid should behave.
datadriven::RegularizationConfiguration & getRegularizationConfig ()
Get or set the type of regularization operation to use.
const datadriven::RegularizationConfiguration & getRegularizationConfig () const
Get the type of regularization operation to use.
solver::SLESolverConfiguration & getSolverFinalConfig ()
Get or set configuration for the linear system solver when solving the final, refined system.
const solver::SLESolverConfiguration & getSolverFinalConfig () const
Get configuration for the linear system solver when solving the final, refined system.
solver::SLESolverConfiguration & getSolverRefineConfig ()
Get or set configuration for the linear system solver which should be used while building adaptive grids.
const solver::SLESolverConfiguration & getSolverRefineConfig () const
Get configuration for the linear system solver which should be used while building adaptive grids.
FitterConfiguration & operator= (const FitterConfiguration &rhs)=default
Copy assign operator.
FitterConfiguration & operator= (FitterConfiguration &&rhs)=default
Move assign operator.
virtual void readParams (const DataMiningConfigParser &parser)=0
obtain parameters from a parser
virtual void setupDefaults ()
set default values for all members based on the desired scenario.
virtual ~FitterConfiguration ()=default
virtual destructor.
Protected Attributes
base::AdaptivityConfiguration adaptivityConfig
Configure how the adaptivity algorithms for the grid should behave.
datadriven::CrossvalidationConfiguration crossvalidationConfig
Configure how the crossvalidation should behave.
datadriven::DatabaseConfiguration databaseConfig
Configure where the lhs datamatrix decomposition database is stored.
datadriven::DensityEstimationConfiguration densityEstimationConfig
Configure how the density estimation should behave.
datadriven::GeometryConfiguration geometryConfig
base::GeneralGridConfiguration gridConfig
Initial conditions for the grid before adaptive refinement.
datadriven::LearnerConfiguration learnerConfig
Configuration for the learner's behaviour.
datadriven::OperationMultipleEvalConfiguration multipleEvalConfig
Determine implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
datadriven::ParallelConfiguration parallelConfig
Configuration for parallelization with ScaLAPACK.
datadriven::RegularizationConfiguration regularizationConfig
Set the type of regularization operation to use and specify the influence of the regularization term vs data term from 0 (no regularization) to 1 (no data term).
solver::SLESolverConfiguration solverFinalConfig
Configuration for the linear system solver when solving the final, refined system.
solver::SLESolverConfiguration solverRefineConfig
Configuration for the linear system solver which should be used while building adaptive grids.
Detailed Description
General configuration object for fitters.
Bundles all structures needed to build a sparse grid, fit a sparse grid based model, and perform adaptive refinement.
Constructor & Destructor Documentation
FitterConfiguration() [1/3]
sgpp::datadriven::FitterConfiguration::FitterConfiguration () default
Sets up a Fitter configuration with its default values.
FitterConfiguration() [2/3]
sgpp::datadriven::FitterConfiguration::FitterConfiguration (const FitterConfiguration & rhs) default
Copy constructor.
Parameters
rhs const reference to the scorer object to copy from.
FitterConfiguration() [3/3]
sgpp::datadriven::FitterConfiguration::FitterConfiguration (FitterConfiguration && rhs) default
Move constructor.
Parameters
rhs R-value reference to a scorer object to moved from.
~FitterConfiguration()
virtual sgpp::datadriven::FitterConfiguration::~FitterConfiguration () virtual default
virtual destructor.
Member Function Documentation
clone()
virtual FitterConfiguration * sgpp::datadriven::FitterConfiguration::clone () const pure virtual
Polymorphic clone pattern.
Returns
deep copy of this object. New object is owned by caller.
Implemented in sgpp::datadriven::FitterConfigurationClassification, sgpp::datadriven::FitterConfigurationDensityEstimation, and sgpp::datadriven::FitterConfigurationLeastSquares.
dumpToStream()
void sgpp::datadriven::FitterConfiguration::dumpToStream (std::ostream & stream_out = std::cout) const
print out all parameters to stream
References adaptivityConfig, crossvalidationConfig, databaseConfig, densityEstimationConfig, sgpp::datadriven::DMConfigTools::dumpToStream(), gridConfig, learnerConfig, parallelConfig, regularizationConfig, solverFinalConfig, and solverRefineConfig.
getCrossvalidationConfig() [1/2]
datadriven::CrossvalidationConfiguration & sgpp::datadriven::FitterConfiguration::getCrossvalidationConfig ()
Get or set how the crossvalidation should behave.
Returns
CrossvalidationConfiguration
References getCrossvalidationConfig().
getCrossvalidationConfig() [2/2]
const datadriven::CrossvalidationConfiguration & sgpp::datadriven::FitterConfiguration::getCrossvalidationConfig () const
Get how the crossvalidation should behave.
Returns
immutable CrossvalidationConfiguration
References crossvalidationConfig.
Referenced by getCrossvalidationConfig().
getDatabaseConfig()
const datadriven::DatabaseConfiguration & sgpp::datadriven::FitterConfiguration::getDatabaseConfig () const
Returns the database configuration, i.e.
the filepath
Returns
immutable DatabaseConfiguration
References databaseConfig.
Referenced by main().
getDensityEstimationConfig() [1/2]
datadriven::DensityEstimationConfiguration & sgpp::datadriven::FitterConfiguration::getDensityEstimationConfig ()
Get or set how the density estimation should behave.
Returns
DensityEstimationConfiguration
References getDensityEstimationConfig().
getDensityEstimationConfig() [2/2]
const datadriven::DensityEstimationConfiguration & sgpp::datadriven::FitterConfiguration::getDensityEstimationConfig () const
Get how the density estimation should behave.
Returns
immutable DensityEstimationConfiguration
References densityEstimationConfig.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::createNewModel(), sgpp::datadriven::ModelFittingDensityEstimationCombi::fit(), getDensityEstimationConfig(), and main().
getGeometryConfig()
const datadriven::GeometryConfiguration & sgpp::datadriven::FitterConfiguration::getGeometryConfig () const
References geometryConfig.
getGridConfig() [1/2]
base::GeneralGridConfiguration & sgpp::datadriven::FitterConfiguration::getGridConfig ()
Get or set initial conditions for the grid before adaptive refinement.
Returns
GeneralGridConfiguration
References getGridConfig().
getGridConfig() [2/2]
const base::GeneralGridConfiguration & sgpp::datadriven::FitterConfiguration::getGridConfig () const
Get initial conditions for the grid before adaptive refinement.
Returns
immutable GeneralGridConfiguration
References gridConfig.
Referenced by getGridConfig(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts(), main(), sgpp::datadriven::VisualizerClassification::runVisualization(), and sgpp::datadriven::VisualizerDensityEstimation::runVisualization().
getLearnerConfig()
const datadriven::LearnerConfiguration & sgpp::datadriven::FitterConfiguration::getLearnerConfig () const
Returns the configuration for the learner's behaviour.
Returns
immutable LearnerConfiguration
References learnerConfig.
getMultipleEvalConfig() [1/2]
datadriven::OperationMultipleEvalConfiguration & sgpp::datadriven::FitterConfiguration::getMultipleEvalConfig ()
Get or set implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
Returns
current OperationMultipleEvalConfiguration
References getMultipleEvalConfig().
getMultipleEvalConfig() [2/2]
const datadriven::OperationMultipleEvalConfiguration & sgpp::datadriven::FitterConfiguration::getMultipleEvalConfig () const
Get implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
Returns
immutable OperationMultipleEvalConfiguration
References multipleEvalConfig.
Referenced by getMultipleEvalConfig().
getParallelConfig()
const datadriven::ParallelConfiguration & sgpp::datadriven::FitterConfiguration::getParallelConfig () const
Returns the configuration for parallelization with ScaLAPACK.
Returns
immutable ParallelConfiguration
References parallelConfig.
Referenced by sgpp::datadriven::ModelFittingClassification::ModelFittingClassification(), and sgpp::datadriven::Scorer::test().
getRefinementConfig() [1/2]
base::AdaptivityConfiguration & sgpp::datadriven::FitterConfiguration::getRefinementConfig ()
Get or set how the adaptivity algorithms for the grid should behave.
Returns
AdaptivityConfiguration
References getRefinementConfig().
getRefinementConfig() [2/2]
const base::AdaptivityConfiguration & sgpp::datadriven::FitterConfiguration::getRefinementConfig () const
Get how the adaptivity algorithms for the grid should behave.
Returns
immutable AdaptivityConfiguration
References adaptivityConfig.
Referenced by getRefinementConfig(), and main().
getRegularizationConfig() [1/2]
datadriven::RegularizationConfiguration & sgpp::datadriven::FitterConfiguration::getRegularizationConfig ()
Get or set the type of regularization operation to use.
Returns
RegularizationConfiguration
References getRegularizationConfig().
getRegularizationConfig() [2/2]
const datadriven::RegularizationConfiguration & sgpp::datadriven::FitterConfiguration::getRegularizationConfig () const
Get the type of regularization operation to use.
Returns
immutable RegularizationConfiguration
References regularizationConfig.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::fit(), getRegularizationConfig(), and main().
getSolverFinalConfig() [1/2]
solver::SLESolverConfiguration & sgpp::datadriven::FitterConfiguration::getSolverFinalConfig ()
Get or set configuration for the linear system solver when solving the final, refined system.
Returns
SLESolverConfiguration
References getSolverFinalConfig().
getSolverFinalConfig() [2/2]
const solver::SLESolverConfiguration & sgpp::datadriven::FitterConfiguration::getSolverFinalConfig () const
Get configuration for the linear system solver when solving the final, refined system.
Returns
immutable SLESolverConfiguration
References solverFinalConfig.
Referenced by getSolverFinalConfig(), sgpp::datadriven::ModelFittingDensityRatioEstimation::ModelFittingDensityRatioEstimation(), and sgpp::datadriven::ModelFittingLeastSquares::ModelFittingLeastSquares().
getSolverRefineConfig() [1/2]
solver::SLESolverConfiguration & sgpp::datadriven::FitterConfiguration::getSolverRefineConfig ()
Get or set configuration for the linear system solver which should be used while building adaptive grids.
Returns
SLESolverConfiguration
References getSolverRefineConfig().
getSolverRefineConfig() [2/2]
const solver::SLESolverConfiguration & sgpp::datadriven::FitterConfiguration::getSolverRefineConfig () const
Get configuration for the linear system solver which should be used while building adaptive grids.
Returns
immutable SLESolverConfiguration
References solverRefineConfig.
Referenced by getSolverRefineConfig().
operator=() [1/2]
FitterConfiguration & sgpp::datadriven::FitterConfiguration::operator= (const FitterConfiguration & rhs) default
Copy assign operator.
Parameters
rhs const reference to the scorer object to copy from.
Returns
rerefernce to this with updated values.
operator=() [2/2]
FitterConfiguration & sgpp::datadriven::FitterConfiguration::operator= (FitterConfiguration && rhs) default
Move assign operator.
Parameters
rhs R-value reference to an a scorer object to move from.
Returns
rerefernce to this with updated values.
readParams()
virtual void sgpp::datadriven::FitterConfiguration::readParams (const DataMiningConfigParser & parser) pure virtual
obtain parameters from a parser
Parameters
parser the parser object to read from
Implemented in sgpp::datadriven::FitterConfigurationDensityEstimation, and sgpp::datadriven::FitterConfigurationLeastSquares.
setupDefaults()
void sgpp::datadriven::FitterConfiguration::setupDefaults () virtual
set default values for all members based on the desired scenario.
Reimplemented in sgpp::datadriven::FitterConfigurationClassification, sgpp::datadriven::FitterConfigurationDensityEstimation, and sgpp::datadriven::FitterConfigurationLeastSquares.
References adaptivityConfig, sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::solver::CG, sgpp::base::AdaptivityConfiguration::coarseningFunctorType_, sgpp::base::AdaptivityConfiguration::coarseningThreshold_, sgpp::base::AdaptivityConfiguration::coarsenInitialPoints_, sgpp::datadriven::RegularizationConfiguration::convergenceThreshold_, crossvalidationConfig, databaseConfig, sgpp::datadriven::Decomposition, sgpp::datadriven::DensityEstimationConfiguration::decomposition_, densityEstimationConfig, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::GeometryConfiguration::dim_, sgpp::datadriven::CrossvalidationConfiguration::enable_, sgpp::solver::SLESolverConfiguration::eps_, sgpp::base::AdaptivityConfiguration::errorBasedRefinement_, sgpp::base::AdaptivityConfiguration::errorBufferSize_, sgpp::base::AdaptivityConfiguration::errorConvergenceThreshold_, sgpp::base::AdaptivityConfiguration::errorMinInterval_, sgpp::datadriven::RegularizationConfiguration::exponentBase_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::datadriven::DatabaseConfiguration::filePath_, geometryConfig, gridConfig, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsDecompose_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsRefine_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsSolver_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsUpdateLambda_, sgpp::datadriven::Identity, sgpp::datadriven::RegularizationConfiguration::intervalA_, sgpp::datadriven::RegularizationConfiguration::intervalB_, sgpp::datadriven::CrossvalidationConfiguration::kfold_, sgpp::datadriven::RegularizationConfiguration::l1Ratio_, sgpp::datadriven::CrossvalidationConfiguration::lambda_, sgpp::datadriven::RegularizationConfiguration::lambda_, sgpp::datadriven::RegularizationConfiguration::lambda_end_, sgpp::datadriven::RegularizationConfiguration::lambda_log_scale_, sgpp::datadriven::RegularizationConfiguration::lambda_steps_, sgpp::datadriven::CrossvalidationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationConfiguration::lambdaSteps_, sgpp::datadriven::RegularizationConfiguration::lamda_start_, learnerConfig, sgpp::datadriven::LearnerConfiguration::learningRate_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::AdaptivityConfiguration::levelPenalize_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::Linear, sgpp::datadriven::CrossvalidationConfiguration::logScale_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numCoarseningPoints_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::RegularizationConfiguration::optimizeLambda_, sgpp::datadriven::RegularizationConfiguration::optimizerTolerance_, sgpp::datadriven::OrthoAdapt, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::precomputeEvaluations_, sgpp::base::AdaptivityConfiguration::refinementFunctorType_, sgpp::base::AdaptivityConfiguration::refinementPeriod_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, regularizationConfig, sgpp::base::AdaptivityConfiguration::scalingCoefficients_, sgpp::datadriven::CrossvalidationConfiguration::seed_, sgpp::datadriven::CrossvalidationConfiguration::shuffle_, sgpp::datadriven::CrossvalidationConfiguration::silent_, solverFinalConfig, solverRefineConfig, sgpp::datadriven::GeometryConfiguration::stencils_, sgpp::base::Surplus, sgpp::base::GeneralGridConfiguration::t_, sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::GeneralGridConfiguration::type_, sgpp::datadriven::DensityEstimationConfiguration::type_, sgpp::datadriven::RegularizationConfiguration::type_, sgpp::solver::SLESolverConfiguration::type_, sgpp::datadriven::DensityEstimationConfiguration::useOfflinePermutation_, sgpp::datadriven::LearnerConfiguration::usePrior_, and sgpp::solver::SLESolverConfiguration::verbose_.
Referenced by sgpp::datadriven::FitterConfigurationDensityEstimation::setupDefaults(), and sgpp::datadriven::FitterConfigurationLeastSquares::setupDefaults().
Member Data Documentation
adaptivityConfig
base::AdaptivityConfiguration sgpp::datadriven::FitterConfiguration::adaptivityConfig protected
Configure how the adaptivity algorithms for the grid should behave.
Referenced by dumpToStream(), getRefinementConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), sgpp::datadriven::FitterConfigurationLeastSquares::readParams(), and setupDefaults().
crossvalidationConfig
datadriven::CrossvalidationConfiguration sgpp::datadriven::FitterConfiguration::crossvalidationConfig protected
Configure how the crossvalidation should behave.
Referenced by dumpToStream(), getCrossvalidationConfig(), and setupDefaults().
databaseConfig
datadriven::DatabaseConfiguration sgpp::datadriven::FitterConfiguration::databaseConfig protected
Configure where the lhs datamatrix decomposition database is stored.
Referenced by dumpToStream(), getDatabaseConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), and setupDefaults().
densityEstimationConfig
datadriven::DensityEstimationConfiguration sgpp::datadriven::FitterConfiguration::densityEstimationConfig protected
Configure how the density estimation should behave.
Referenced by dumpToStream(), getDensityEstimationConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), and setupDefaults().
geometryConfig
datadriven::GeometryConfiguration sgpp::datadriven::FitterConfiguration::geometryConfig protected
Referenced by getGeometryConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), and setupDefaults().
gridConfig
base::GeneralGridConfiguration sgpp::datadriven::FitterConfiguration::gridConfig protected
Initial conditions for the grid before adaptive refinement.
Referenced by dumpToStream(), getGridConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), sgpp::datadriven::FitterConfigurationLeastSquares::readParams(), and setupDefaults().
learnerConfig
datadriven::LearnerConfiguration sgpp::datadriven::FitterConfiguration::learnerConfig protected
Configuration for the learner's behaviour.
Referenced by dumpToStream(), getLearnerConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), and setupDefaults().
multipleEvalConfig
datadriven::OperationMultipleEvalConfiguration sgpp::datadriven::FitterConfiguration::multipleEvalConfig protected
Determine implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
Referenced by getMultipleEvalConfig().
parallelConfig
datadriven::ParallelConfiguration sgpp::datadriven::FitterConfiguration::parallelConfig protected
Configuration for parallelization with ScaLAPACK.
Referenced by dumpToStream(), getParallelConfig(), and sgpp::datadriven::FitterConfigurationDensityEstimation::readParams().
regularizationConfig
datadriven::RegularizationConfiguration sgpp::datadriven::FitterConfiguration::regularizationConfig protected
Set the type of regularization operation to use and specify the influence of the regularization term vs data term from 0 (no regularization) to 1 (no data term).
Referenced by dumpToStream(), getRegularizationConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), sgpp::datadriven::FitterConfigurationLeastSquares::readParams(), and setupDefaults().
solverFinalConfig
solver::SLESolverConfiguration sgpp::datadriven::FitterConfiguration::solverFinalConfig protected
Configuration for the linear system solver when solving the final, refined system.
Referenced by dumpToStream(), getSolverFinalConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), sgpp::datadriven::FitterConfigurationLeastSquares::readParams(), and setupDefaults().
solverRefineConfig
solver::SLESolverConfiguration sgpp::datadriven::FitterConfiguration::solverRefineConfig protected
Configuration for the linear system solver which should be used while building adaptive grids.
Referenced by dumpToStream(), getSolverRefineConfig(), sgpp::datadriven::FitterConfigurationDensityEstimation::readParams(), sgpp::datadriven::FitterConfigurationLeastSquares::readParams(), and setupDefaults().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfiguration.hpp
datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfiguration.cpp