SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T > Class Template Reference
Class for the OpenCL density matrix vector multiplication.
#include <KernelB.hpp>
Public Member Functions
double finalize_rhs_generation (std::vector< T > &result, size_t startid=0, size_t chunksize=0)
void initialize_dataset (std::vector< T > &data)
KernelDensityB (std::shared_ptr< base::OCLDevice > dev, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node &kernelConfiguration, std::vector< int > &points)
void start_rhs_generation (size_t startid=0, size_t chunksize=0)
Generates part of the right hand side density vector.
~KernelDensityB ()
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
Adds the possible building parameters to the configuration if they do not exist yet.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >
Class for the OpenCL density matrix vector multiplication.
Constructor & Destructor Documentation
KernelDensityB()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::KernelDensityB (std::shared_ptr< base::OCLDevice > dev, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node & kernelConfiguration, std::vector< int > & points) inline
References json::Node::getBool(), json::Node::getUInt(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and json::Node::size().
~KernelDensityB()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::~KernelDensityB () inline
Member Function Documentation
augmentDefaultParameters()
template<typename T > static void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
Adds the possible building parameters to the configuration if they do not exist yet.
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
finalize_rhs_generation()
template<typename T > double sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::finalize_rhs_generation (std::vector< T > & result, size_t startid = 0, size_t chunksize = 0) inline
References sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), and sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::finalize_rhs_generation(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::generateb().
initialize_dataset()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::initialize_dataset (std::vector< T > & data) inline
References sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and sgpp::base::OCLBufferWrapperSD< T >::isInitialized().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::generateb(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::initialize_dataset().
start_rhs_generation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation (size_t startid = 0, size_t chunksize = 0) inline
Generates part of the right hand side density vector.
References sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderB< real_type >::generateSource(), sgpp::base::OCLBufferWrapperSD< T >::getBuffer(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and sgpp::base::OCLBufferWrapperSD< T >::isInitialized().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::generateb(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::start_rhs_generation().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationDensityOCLMultiPlatform/KernelB.hpp