SG++-Doxygen-Documentation: sgpp::datadriven::OperationMakePositive Class Reference
sgpp::datadriven::OperationMakePositive Class Reference
This class enforces the function value range of a sparse grid function to be larger than 0.
#include <OperationMakePositive.hpp>
Public Types
typedef std::map< size_t, base::HashGridPoint > gridPointCandidatesMap
Public Member Functions
std::vector< size_t > & getAddedGridPoints ()
std::vector< size_t > & getAddedGridPointsForPositivity ()
OperationMakePositiveCandidateSetAlgorithm & getCandidateSetAlgorithm ()
void initialize (base::Grid &grid, base::DataVector &alpha)
initializes the operation
void makeCurrentNodalValuesPositive (base::Grid &grid, base::DataVector &alpha, double tol=-1e-14)
Enforce the function values at each grid point to larger than the specified tolerance.
void makePositive (base::Grid &grid, base::DataVector &alpha, bool forcePositiveNodalValues=false)
Make the sparse grid function defined by grid and coefficient vector positive.
size_t numAddedGridPoints ()
size_t numAddedGridPointsForPositivity ()
base::DataVector & numAddedGridPointsForPositivityPerIteration ()
OperationMakePositive (MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm=MakePositiveCandidateSearchAlgorithm::IntersectionsJoin, MakePositiveInterpolationAlgorithm interpolationAlgorithm=MakePositiveInterpolationAlgorithm::SetToZero, bool generateConsistentGrid=true, bool verbose=false, sgpp::base::ScalarFunction *f=nullptr)
Constructor.
virtual ~OperationMakePositive ()
Descrutor.
Detailed Description
This class enforces the function value range of a sparse grid function to be larger than 0.
It uses a discretization based approach where we add the minimum amount of full grid points to enforce the positivity.
Member Typedef Documentation
gridPointCandidatesMap
typedef std::map<size_t, base::HashGridPoint> sgpp::datadriven::OperationMakePositive::gridPointCandidatesMap
Constructor & Destructor Documentation
OperationMakePositive()
sgpp::datadriven::OperationMakePositive::OperationMakePositive (MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm = MakePositiveCandidateSearchAlgorithm::IntersectionsJoin, MakePositiveInterpolationAlgorithm interpolationAlgorithm = MakePositiveInterpolationAlgorithm::SetToZero, bool generateConsistentGrid = true, bool verbose = false, sgpp::base::ScalarFunction * f = nullptr) explicit
Constructor.
Parameters
candidateSearchAlgorithm defines how to generate the full grid candidate set
interpolationAlgorithm defines how to compute the coefficients for the new grid points
generateConsistentGrid define if the hierarchical ancestors of all new grid points are inserted as well
verbose print information or not
f scalar function to be interpolated
~OperationMakePositive()
sgpp::datadriven::OperationMakePositive::~OperationMakePositive () virtual
Descrutor.
Member Function Documentation
getAddedGridPoints()
std::vector< size_t > & sgpp::datadriven::OperationMakePositive::getAddedGridPoints ()
Returns
vector containing the indices of the added grid points
getAddedGridPointsForPositivity()
std::vector< size_t > & sgpp::datadriven::OperationMakePositive::getAddedGridPointsForPositivity ()
Returns
vector containing the indices which have just been added for positivity
getCandidateSetAlgorithm()
OperationMakePositiveCandidateSetAlgorithm & sgpp::datadriven::OperationMakePositive::getCandidateSetAlgorithm ()
Returns
candidate set algorithm
initialize()
void sgpp::datadriven::OperationMakePositive::initialize (base::Grid & grid, base::DataVector & alpha)
initializes the operation
Parameters
grid Grid
alpha coefficients
References sgpp::datadriven::FullGrid, grid(), sgpp::datadriven::HybridFullIntersections, sgpp::datadriven::InterpolateBoundaries1d, sgpp::datadriven::InterpolateExp, sgpp::datadriven::InterpolateFunction, sgpp::datadriven::Intersections, sgpp::datadriven::IntersectionsJoin, and sgpp::datadriven::SetToZero.
Referenced by makePositive().
makeCurrentNodalValuesPositive()
void sgpp::datadriven::OperationMakePositive::makeCurrentNodalValuesPositive (base::Grid & grid, base::DataVector & alpha, double tol = -1e-14)
Enforce the function values at each grid point to larger than the specified tolerance.
The ones which are not are set to zero. For this function we need the hierarchization and dechierarchization operations.
Parameters
grid grid
alpha coefficient vector
tol tolerance for negativity
References alpha, sgpp::op_factory::createOperationHierarchisation(), sgpp::base::DataVector::getSize(), and grid().
Referenced by makePositive(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), and python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive().
makePositive()
void sgpp::datadriven::OperationMakePositive::makePositive (base::Grid & grid, base::DataVector & alpha, bool forcePositiveNodalValues = false)
Make the sparse grid function defined by grid and coefficient vector positive.
Parameters
grid Grid where the new grid is stored
alpha coefficient vector of new grid
forcePositiveNodalValues nodal values are forced to be non-negative or not
References alpha, grid(), initialize(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearTruncatedBoundary, makeCurrentNodalValuesPositive(), numAddedGridPoints(), and numAddedGridPointsForPositivity().
Referenced by sgpp::datadriven::SparseGridDensityEstimator::initialize().
numAddedGridPoints()
size_t sgpp::datadriven::OperationMakePositive::numAddedGridPoints ()
Returns
number of newly added grid points
Referenced by makePositive().
numAddedGridPointsForPositivity()
size_t sgpp::datadriven::OperationMakePositive::numAddedGridPointsForPositivity ()
Returns
number of newly added grid points for guaranteeing positivity
Referenced by makePositive().
numAddedGridPointsForPositivityPerIteration()
base::DataVector & sgpp::datadriven::OperationMakePositive::numAddedGridPointsForPositivityPerIteration ()
Returns
number of newly added grid points for guaranteeing positivity per iteration
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositive.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositive.cpp