SG++-Doxygen-Documentation: sgpp::base::WrapperVectorFunction Class Reference
sgpp::base::WrapperVectorFunction Class Reference
Implementation of VectorFunction that wraps a std::function object.
#include <WrapperVectorFunction.hpp>
Public Types
typedef std::function< void(const DataVector &, DataVector &)> FunctionEvalType
Public Member Functions
void clone (std::unique_ptr< VectorFunction > &clone) const override
void eval (const DataVector &x, DataVector &value) override
WrapperVectorFunction (size_t d, size_t m, FunctionEvalType f)
Constructor.
~WrapperVectorFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::VectorFunction
virtual void eval (const DataMatrix &x, DataMatrix &value)
Convenience method for calculating \(g(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfComponents () const
size_t getNumberOfParameters () const
VectorFunction (size_t d, size_t m)
Constructor.
virtual ~VectorFunction ()
Destructor.
Protected Attributes
FunctionEvalType f
function to be wrapped
Protected Attributes inherited from sgpp::base::VectorFunction
size_t d
dimension of the domain
size_t m
number of components
Detailed Description
Implementation of VectorFunction that wraps a std::function object.
Member Typedef Documentation
FunctionEvalType
typedef std::function<void(const DataVector&, DataVector&)> sgpp::base::WrapperVectorFunction::FunctionEvalType
Constructor & Destructor Documentation
WrapperVectorFunction()
sgpp::base::WrapperVectorFunction::WrapperVectorFunction (size_t d, size_t m, FunctionEvalType f) inline
Constructor.
Parameters
d dimension of the domain
m number of components
f function to be wrapped
~WrapperVectorFunction()
sgpp::base::WrapperVectorFunction::~WrapperVectorFunction () inline override
Destructor.
Member Function Documentation
clone()
void sgpp::base::WrapperVectorFunction::clone (std::unique_ptr< VectorFunction > & clone) const inline override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::VectorFunction.
References clone(), sgpp::base::VectorFunction::d, f, and sgpp::base::VectorFunction::m.
Referenced by clone().
eval()
void sgpp::base::WrapperVectorFunction::eval (const DataVector & x, DataVector & value) inline override virtual
Parameters
[in] x evaluation point \(\vec{x} \in [0, 1]^d\)
[out] value \(g(\vec{x})\)
Implements sgpp::base::VectorFunction.
References f.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
f
FunctionEvalType sgpp::base::WrapperVectorFunction::f protected
function to be wrapped
Referenced by clone(), eval(), and python.uq.refinement.RefinementStrategy.PredictiveRanking::rank().
The documentation for this class was generated from the following file:
base/src/sgpp/base/function/vector/WrapperVectorFunction.hpp