SG++-Doxygen-Documentation: sgpp::datadriven::StreamingOCLMultiPlatform::Configuration Class Reference
sgpp::datadriven::StreamingOCLMultiPlatform::Configuration Class Reference
Configuration class for the operation OperationMultiEvalStreamingOCLMultiPlatform.
#include <Configuration.hpp>
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
Takes a configuration and checks whether parameters are missing.
static const std::string & getKernelName ()
Detailed Description
Configuration class for the operation OperationMultiEvalStreamingOCLMultiPlatform.
This class provides a name and a default configuration for the operation.
See also
OperationMultiEvalStreamingOCLMultiPlatform
Member Function Documentation
augmentDefaultParameters()
static void sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
Takes a configuration and checks whether parameters are missing.
Missing parameters are added and initialized with their default values. This function only configures devices that are specified in the configuration.
Parameters
parameters Set of parameters to augment with default parameters
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), getKernelName(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::createStreamingOCLMultiPlatformConfigured().
getKernelName()
static const std::string & sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::getKernelName () inline static
Returns
The name of the kernel
Referenced by augmentDefaultParameters(), and sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::OperationMultiEvalStreamingOCLMultiPlatform().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingOCLMultiPlatform/Configuration.hpp