SG++-Doxygen-Documentation: sgpp::base::NakBsplineModifiedBasis< LT, IT > Class Template Reference
sgpp::base::NakBsplineModifiedBasis< LT, IT > Class Template Reference
Not-a-knot B-spline basis.
#include <NakBsplineModifiedBasis.hpp>
Public Member Functions
double basisMean (LT l, IT i, size_t start, size_t stop, double offset, double hik, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights, std::shared_ptr< sgpp::base::Distribution > pdf)
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
double getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights)
Calculates the mean int b_i(x) rho(x) dx of a basis function b_i w.r.t.
NakBsplineModifiedBasis ()
Default constructor.
NakBsplineModifiedBasis (size_t degree)
Constructor.
~NakBsplineModifiedBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
NakBsplineBasis< LT, IT > nakBsplineBasis
B-spline basis for B-spline evaluation.
NakBsplineModifiedBasisDeriv1< LT, IT > nakBsplineModifiedBasisDeriv1
NakBsplineMOdifiedBAsisDeriv1 for derivative evaluations.
Detailed Description
template<class LT, class IT>
class sgpp::base::NakBsplineModifiedBasis< LT, IT >
Not-a-knot B-spline basis.
Constructor & Destructor Documentation
NakBsplineModifiedBasis() [1/2]
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasis< LT, IT >::NakBsplineModifiedBasis () inline
Default constructor.
NakBsplineModifiedBasis() [2/2]
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasis< LT, IT >::NakBsplineModifiedBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::getDegree().
~NakBsplineModifiedBasis()
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasis< LT, IT >::~NakBsplineModifiedBasis () inline override
Destructor.
Member Function Documentation
basisMean()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasis< LT, IT >::basisMean (LT l, IT i, size_t start, size_t stop, double offset, double hik, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights, std::shared_ptr< sgpp::base::Distribution > pdf) inline
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::eval().
Referenced by sgpp::base::NakBsplineModifiedBasis< LT, IT >::getMean().
eval()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::getDegree(), and sgpp::base::NakBsplineModifiedBasis< LT, IT >::nakBsplineBasis.
Referenced by sgpp::base::NakBsplineModifiedBasis< LT, IT >::basisMean(), python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), and sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of wavelet basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::nakBsplineModifiedBasisDeriv1.
Referenced by sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), and sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient().
getDegree()
template<class LT , class IT > size_t sgpp::base::NakBsplineModifiedBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::nakBsplineBasis.
Referenced by sgpp::base::NakBsplineModifiedBasis< LT, IT >::eval(), sgpp::base::NakBsplineModifiedBasis< LT, IT >::getMean(), and sgpp::base::NakBsplineModifiedBasis< LT, IT >::NakBsplineModifiedBasis().
getIntegral()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Referenced by sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature().
getMean()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasis< LT, IT >::getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights) inline
Calculates the mean int b_i(x) rho(x) dx of a basis function b_i w.r.t.
the probability density function rho
Parameters
l level of basis function
i index of basis function
pdf probability density function
quadCoordinates coordinates of the quadrature rule to be used
quadWeights weights of the quadrature rule to be used
Returns
mean of basis function
References sgpp::base::NakBsplineModifiedBasis< LT, IT >::basisMean(), and sgpp::base::NakBsplineModifiedBasis< LT, IT >::getDegree().
Referenced by sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature().
Member Data Documentation
nakBsplineBasis
template<class LT , class IT > NakBsplineBasis<LT, IT> sgpp::base::NakBsplineModifiedBasis< LT, IT >::nakBsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::NakBsplineModifiedBasis< LT, IT >::eval(), and sgpp::base::NakBsplineModifiedBasis< LT, IT >::getDegree().
nakBsplineModifiedBasisDeriv1
template<class LT , class IT > NakBsplineModifiedBasisDeriv1<LT, IT> sgpp::base::NakBsplineModifiedBasis< LT, IT >::nakBsplineModifiedBasisDeriv1 protected
NakBsplineMOdifiedBAsisDeriv1 for derivative evaluations.
Referenced by sgpp::base::NakBsplineModifiedBasis< LT, IT >::evalDx().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/NakBsplineModifiedBasis.hpp