SG++-Doxygen-Documentation: sgpp::optimization::test_problems::FloudasObjective Class Reference
sgpp::optimization::test_problems::FloudasObjective Class Reference
Floudas objective function.
#include <Floudas.hpp>
Public Member Functions
void clone (std::unique_ptr< base::ScalarFunction > &clone) const override
double evalUndisplaced (const base::DataVector &x) override
FloudasObjective ()
Constructor.
~FloudasObjective () override
Destructor.
Public Member Functions inherited from sgpp::optimization::test_problems::TestScalarFunction
double eval (const base::DataVector &x) override
Evaluate displaced function.
const base::DataVector & getDisplacement () const
void setDisplacement (const base::DataVector &displacement)
TestScalarFunction (size_t d)
Constructor.
~TestScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::optimization::test_problems::TestScalarFunction
base::DataVector displacement
displacement vector
base::DataVector xTmp
temporary vector for displacing
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
Floudas objective function.
Definition:
\[\bar{f}(\bar{\vec{x}}) := -\bar{x}_1 - \bar{x}_2\]
Constructor & Destructor Documentation
FloudasObjective()
sgpp::optimization::test_problems::FloudasObjective::FloudasObjective ()
Constructor.
Referenced by clone().
~FloudasObjective()
sgpp::optimization::test_problems::FloudasObjective::~FloudasObjective () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::test_problems::FloudasObjective::clone (std::unique_ptr< base::ScalarFunction > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone(), and FloudasObjective().
Referenced by clone().
evalUndisplaced()
double sgpp::optimization::test_problems::FloudasObjective::evalUndisplaced (const base::DataVector & x) override virtual
Parameters
x point \(\vec{x} \in [0, 1]^d\)
Returns
\(f(\vec{x})\)
Implements sgpp::optimization::test_problems::TestScalarFunction.
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/constrained/Floudas.hpp
optimization/src/sgpp/optimization/test_problems/constrained/Floudas.cpp