SG++-Doxygen-Documentation: json::DictNode Class Reference
json::DictNode Class Reference
#include <DictNode.hpp>
Public Member Functions
void addAttribute (const std::string &name, std::unique_ptr< Node > node) override
Node & addDictAttr (const std::string &name) override
Node & addIDAttr (const std::string &name, const bool &value) override
Node & addIDAttr (const std::string &name, const char *value) override
Node & addIDAttr (const std::string &name, const double &value) override
Node & addIDAttr (const std::string &name, const int64_t &value) override
Node & addIDAttr (const std::string &name, const std::string &value) override
Node & addIDAttr (const std::string &name, const uint64_t &value) override
Node & addListAttr (const std::string &name) override
Node & addTextAttr (const std::string &name, const std::string &value) override
Node * clone () override
bool contains (const std::string &key) override
DictNode ()
DictNode (const DictNode &original)
std::unique_ptr< Node > erase (Node &node) override
std::vector< std::string > & keys () override
DictNode & operator= (const DictNode &right)
Node & operator= (const Node &right) override
Node & operator[] (const std::string &key) override
void parse (std::vector< Token > &stream) override
void parseAttributes (std::vector< Token > &stream)
std::unique_ptr< Node > removeAttribute (const std::string name) override
Node & replaceDictAttr (const std::string &name) override
Node & replaceIDAttr (const std::string &name, const bool &value) override
Node & replaceIDAttr (const std::string &name, const char *value) override
Node & replaceIDAttr (const std::string &name, const double &value) override
Node & replaceIDAttr (const std::string &name, const int64_t &value) override
Node & replaceIDAttr (const std::string &name, const std::string &value) override
Node & replaceIDAttr (const std::string &name, const uint64_t &value) override
Node & replaceListAttr (const std::string &name) override
Node & replaceTextAttr (const std::string &name, const std::string &value) override
void serialize (std::ostream &outFile, size_t indentWidth) override
size_t size () override
Public Member Functions inherited from json::Node
virtual Node & addDictValue ()
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListValue ()
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual std::unique_ptr< Node > erase ()
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const size_t index)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual ~Node ()=default
Protected Attributes
std::map< std::string, std::unique_ptr< Node > > attributes
std::vector< std::string > keyOrder
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
DictNode() [1/2]
json::DictNode::DictNode ()
Referenced by addDictAttr(), clone(), and parseAttributes().
DictNode() [2/2]
json::DictNode::DictNode (const DictNode & original)
References attributes, keyOrder, json::Node::orderedKeyIndex, and json::Node::parent.
Member Function Documentation
addAttribute()
void json::DictNode::addAttribute (const std::string & name, std::unique_ptr< Node > node) override virtual
Reimplemented from json::Node.
References attributes, and keyOrder.
Referenced by addDictAttr(), addIDAttr(), addIDAttr(), addIDAttr(), addIDAttr(), addIDAttr(), addListAttr(), addTextAttr(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), and python.data.DataSpecification.DataSpecification::createNumericAttributes().
addDictAttr()
Node & json::DictNode::addDictAttr (const std::string & name) override virtual
Reimplemented from json::Node.
References addAttribute(), and DictNode().
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix(), replaceDictAttr(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), and sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson().
addIDAttr() [1/6]
Node & json::DictNode::addIDAttr (const std::string & name, const bool & value) override virtual
Reimplemented from json::Node.
References addAttribute().
addIDAttr() [2/6]
Node & json::DictNode::addIDAttr (const std::string & name, const char * value) override virtual
Reimplemented from json::Node.
References addIDAttr().
addIDAttr() [3/6]
Node & json::DictNode::addIDAttr (const std::string & name, const double & value) override virtual
Reimplemented from json::Node.
References addAttribute().
addIDAttr() [4/6]
Node & json::DictNode::addIDAttr (const std::string & name, const int64_t & value) override virtual
Reimplemented from json::Node.
References addAttribute().
addIDAttr() [5/6]
Node & json::DictNode::addIDAttr (const std::string & name, const std::string & value) override virtual
Reimplemented from json::Node.
References addAttribute().
Referenced by addIDAttr(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration(), sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters(), sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters(), sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters(), sgpp::datadriven::DBMatDatabase::putDataMatrix(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), and sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson().
addIDAttr() [6/6]
Node & json::DictNode::addIDAttr (const std::string & name, const uint64_t & value) override virtual
Reimplemented from json::Node.
References addAttribute().
addListAttr()
Node & json::DictNode::addListAttr (const std::string & name) override virtual
Reimplemented from json::Node.
References addAttribute().
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix(), replaceListAttr(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), and sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson().
addTextAttr()
Node & json::DictNode::addTextAttr (const std::string & name, const std::string & value) override virtual
Reimplemented from json::Node.
References addAttribute().
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix(), and replaceTextAttr().
clone()
Node * json::DictNode::clone () override virtual
Implements json::Node.
Reimplemented in json::JSON, sgpp::base::OperationConfiguration, sgpp::base::OCLOperationConfiguration, sgpp::datadriven::LearnerSGDEConfiguration, and sgpp::datadriven::SparseGridDensityEstimatorConfiguration.
References DictNode().
contains()
bool json::DictNode::contains (const std::string & key) override virtual
Reimplemented from json::Node.
References attributes.
Referenced by sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::createNearestNeighborGraphConfigured(), sgpp::datadriven::LearnerSGDEConfiguration::LearnerSGDEConfiguration(), sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters(), sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters(), sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters(), sgpp::datadriven::DataMiningConfigParser::parseIntArray(), sgpp::datadriven::pruneNearestNeighborGraphConfigured(), and sgpp::datadriven::SparseGridDensityEstimatorConfiguration::SparseGridDensityEstimatorConfiguration().
erase()
std::unique_ptr< Node > json::DictNode::erase (Node & node) override virtual
Reimplemented from json::Node.
References attributes, and removeAttribute().
keys()
std::vector< std::string > & json::DictNode::keys () override virtual
Reimplemented from json::Node.
References keyOrder.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters(), and sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration().
operator=() [1/2]
DictNode & json::DictNode::operator= (const DictNode & right)
References keyOrder, and json::Node::orderedKeyIndex.
Referenced by json::JSON::operator=(), and operator=().
operator=() [2/2]
Node & json::DictNode::operator= (const Node & right) override virtual
Reimplemented from json::Node.
Reimplemented in json::JSON.
References operator=().
operator[]()
Node & json::DictNode::operator[] (const std::string & key) override virtual
Reimplemented from json::Node.
References attributes.
parse()
void json::DictNode::parse (std::vector< Token > & stream) override virtual
Implements json::Node.
References json::LBRACE, parseAttributes(), and json::RBRACE.
Referenced by json::JSON::deserialize(), json::JSON::deserializeFromString(), and json::JSON::JSON().
parseAttributes()
void json::DictNode::parseAttributes (std::vector< Token > & stream)
References attributes, json::COLON, json::COMMA, DictNode(), json::ID, keyOrder, json::LBRACE, json::LBRACKET, json::RBRACE, and json::STRING.
Referenced by parse().
removeAttribute()
std::unique_ptr< Node > json::DictNode::removeAttribute (const std::string name) override virtual
Reimplemented from json::Node.
References attributes, keyOrder, and json::Node::orderedKeyIndex.
Referenced by erase(), replaceDictAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceListAttr(), and replaceTextAttr().
replaceDictAttr()
Node & json::DictNode::replaceDictAttr (const std::string & name) override virtual
Reimplemented from json::Node.
References addDictAttr(), attributes, and removeAttribute().
replaceIDAttr() [1/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const bool & value) override virtual
Reimplemented from json::Node.
References addIDAttr(), attributes, and removeAttribute().
replaceIDAttr() [2/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const char * value) override virtual
Reimplemented from json::Node.
References replaceIDAttr().
replaceIDAttr() [3/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const double & value) override virtual
Reimplemented from json::Node.
References addIDAttr(), attributes, and removeAttribute().
replaceIDAttr() [4/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const int64_t & value) override virtual
Reimplemented from json::Node.
References addIDAttr(), attributes, and removeAttribute().
replaceIDAttr() [5/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const std::string & value) override virtual
Reimplemented from json::Node.
References addIDAttr(), attributes, and removeAttribute().
Referenced by main(), and replaceIDAttr().
replaceIDAttr() [6/6]
Node & json::DictNode::replaceIDAttr (const std::string & name, const uint64_t & value) override virtual
Reimplemented from json::Node.
References addIDAttr(), attributes, and removeAttribute().
replaceListAttr()
Node & json::DictNode::replaceListAttr (const std::string & name) override virtual
Reimplemented from json::Node.
References addListAttr(), attributes, and removeAttribute().
replaceTextAttr()
Node & json::DictNode::replaceTextAttr (const std::string & name, const std::string & value) override virtual
Reimplemented from json::Node.
References addTextAttr(), attributes, and removeAttribute().
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
serialize()
void json::DictNode::serialize (std::ostream & outFile, size_t indentWidth) override virtual
Implements json::Node.
Reimplemented in json::JSON.
References attributes, keyOrder, and json::Node::SERIALIZE_INDENT.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
size()
size_t json::DictNode::size () override virtual
Implements json::Node.
References keyOrder.
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), python.data.DataContainer.DataContainer::getSize(), and sgpp::datadriven::DataMiningConfigParser::parseIntArray().
Member Data Documentation
attributes
std::map<std::string, std::unique_ptr<Node> > json::DictNode::attributes protected
Referenced by python.data.DataSpecification.DataSpecification::__init__(), addAttribute(), python.data.DataSpecification.DataSpecification::addAttribute(), python.data.DataSpecification.DataSpecification::cleanAttributes(), json::JSON::clear(), contains(), DictNode(), erase(), python.data.DataSpecification.DataSpecification::getAttributes(), operator[](), parseAttributes(), removeAttribute(), replaceDictAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceIDAttr(), replaceListAttr(), replaceTextAttr(), serialize(), and json::JSON::serialize().
keyOrder
std::vector<std::string> json::DictNode::keyOrder protected
Referenced by addAttribute(), json::JSON::clear(), DictNode(), keys(), operator=(), parseAttributes(), removeAttribute(), serialize(), and size().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/json/DictNode.hpp
base/src/sgpp/base/tools/json/DictNode.cpp