SG++-Doxygen-Documentation: sgpp::base::OperationEvalWaveletNaive Class Reference
sgpp::base::OperationEvalWaveletNaive Class Reference
Operation for evaluating wavelet linear combinations on Noboundary grids.
#include <OperationEvalWaveletNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalWaveletNaive (GridStorage &storage)
Constructor.
~OperationEvalWaveletNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SWaveletBase base
1D wavelet basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Detailed Description
Operation for evaluating wavelet linear combinations on Noboundary grids.
Constructor & Destructor Documentation
OperationEvalWaveletNaive()
sgpp::base::OperationEvalWaveletNaive::OperationEvalWaveletNaive (GridStorage & storage) inline explicit
Constructor.
Parameters
storage storage of the sparse grid
~OperationEvalWaveletNaive()
sgpp::base::OperationEvalWaveletNaive::~OperationEvalWaveletNaive () inline override
Destructor.
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalWaveletNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::WaveletBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalWaveletNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::WaveletBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SWaveletBase sgpp::base::OperationEvalWaveletNaive::base protected
1D wavelet basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalWaveletNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalWaveletNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalWaveletNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalWaveletNaive.cpp