SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T > Class Template Reference
Class for the OpenCL density matrix vector multiplication.
#include <KernelMult.hpp>
Public Member Functions
double finish_mult (std::vector< T > &result, int startid, int chunksize)
void initialize_alpha_buffer (std::vector< T > &alpha)
KernelDensityMult (std::shared_ptr< base::OCLDevice > dev, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node &kernelConfiguration, std::vector< int > &points, T lambda)
void start_mult (size_t startid, size_t chunksize)
Executes part of one matrix-vector density multiplication from startid to startid + chunksize.
~KernelDensityMult ()
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
Adds all possible building parameters to the configuration if they do not exist yet.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >
Class for the OpenCL density matrix vector multiplication.
Constructor & Destructor Documentation
KernelDensityMult()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::KernelDensityMult (std::shared_ptr< base::OCLDevice > dev, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node & kernelConfiguration, std::vector< int > & points, T lambda) inline
References json::Node::contains(), json::Node::getBool(), json::Node::getUInt(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and lambda.
~KernelDensityMult()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::~KernelDensityMult () inline
Member Function Documentation
augmentDefaultParameters()
template<typename T > static void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
Adds all possible building parameters to the configuration if they do not exist yet.
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
finish_mult()
template<typename T > double sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::finish_mult (std::vector< T > & result, int startid, int chunksize) inline
References sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), and sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::finish_partial_mult(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::mult().
initialize_alpha_buffer()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::initialize_alpha_buffer (std::vector< T > & alpha) inline
References alpha, and sgpp::base::OCLBufferWrapperSD< T >::intializeTo().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::initialize_alpha(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::mult().
start_mult()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult (size_t startid, size_t chunksize) inline
Executes part of one matrix-vector density multiplication from startid to startid + chunksize.
References sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderMult< real_type >::generateSource(), sgpp::base::OCLBufferWrapperSD< T >::getBuffer(), sgpp::base::OCLBufferWrapperSD< T >::initializeBuffer(), sgpp::base::OCLBufferWrapperSD< T >::isInitialized(), and lambda.
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::mult(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::start_partial_mult().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationDensityOCLMultiPlatform/KernelMult.hpp