SG++-Doxygen-Documentation: sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive Class Reference
sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive Class Reference
Operation for evaluating modified weakly fundamental spline linear combinations on Noboundary grids and their gradients.
#include <OperationEvalGradientModWeaklyFundamentalNakSplineNaive.hpp>
Public Member Functions
void evalGradient (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient) override
double evalGradient (const DataVector &alpha, const DataVector &point, DataVector &gradient) override
OperationEvalGradientModWeaklyFundamentalNakSplineNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalGradientModWeaklyFundamentalNakSplineNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalGradient
OperationEvalGradient ()
Constructor.
virtual ~OperationEvalGradient ()
Destructor.
Protected Attributes
SWeaklyFundamentalNakSplineModifiedBase base
1D spline basis
SWeaklyFundamentalNakSplineModifiedBaseDeriv1 baseDeriv1
1D spline basis derivative
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalGradient
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating modified weakly fundamental spline linear combinations on Noboundary grids and their gradients.
Constructor & Destructor Documentation
OperationEvalGradientModWeaklyFundamentalNakSplineNaive()
sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::OperationEvalGradientModWeaklyFundamentalNakSplineNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalGradientModWeaklyFundamentalNakSplineNaive()
sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::~OperationEvalGradientModWeaklyFundamentalNakSplineNaive () inline override
Destructor.
Member Function Documentation
evalGradient() [1/2]
void sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
Reimplemented from sgpp::base::OperationEvalGradient.
References alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalGradient() [2/2]
double sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient (const DataVector & alpha, const DataVector & point, DataVector & gradient) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient of linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalGradient.
References sgpp::base::DataVector::add(), alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SWeaklyFundamentalNakSplineModifiedBase sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::base protected
1D spline basis
Referenced by evalGradient(), and evalGradient().
baseDeriv1
SWeaklyFundamentalNakSplineModifiedBaseDeriv1 sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::baseDeriv1 protected
1D spline basis derivative
Referenced by evalGradient(), and evalGradient().
innerDerivative
DataVector sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalGradient(), and evalGradient().
pointInUnitCube
DataVector sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalGradient(), and evalGradient().
storage
GridStorage& sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::storage protected
storage of the sparse grid
Referenced by evalGradient(), and evalGradient().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalGradientModWeaklyFundamentalNakSplineNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalGradientModWeaklyFundamentalNakSplineNaive.cpp