SG++-Doxygen-Documentation: sgpp::solver::BiCGStabSP Class Reference
sgpp::solver::BiCGStabSP Class Reference
#include <BiCGStabSP.hpp>
Public Member Functions
BiCGStabSP (size_t imax, float epsilon)
Std-Constructor.
virtual void solve (sgpp::base::OperationMatrixSP &SystemMatrix, sgpp::base::DataVectorSP &alpha, sgpp::base::DataVectorSP &b, bool reuse=false, bool verbose=false, float max_threshold=-1.0)
max_threashold is ignored in this solver
virtual ~BiCGStabSP ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SLESolverSP
SLESolverSP (size_t imax, float epsilon)
Std-Constructor.
virtual ~SLESolverSP ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolverSP
float getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
float getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (float eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolverSP (size_t nMaximumIterations, float epsilon)
Std-Constructor.
virtual ~SGSolverSP ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolverSP
float myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
float residuum
residuum
Constructor & Destructor Documentation
BiCGStabSP()
sgpp::solver::BiCGStabSP::BiCGStabSP (size_t imax, float epsilon)
Std-Constructor.
~BiCGStabSP()
sgpp::solver::BiCGStabSP::~BiCGStabSP () virtual
Std-Destructor.
Member Function Documentation
solve()
void sgpp::solver::BiCGStabSP::solve (sgpp::base::OperationMatrixSP & SystemMatrix, sgpp::base::DataVectorSP & alpha, sgpp::base::DataVectorSP & b, bool reuse = false, bool verbose = false, float max_threshold = -1.0) virtual
max_threashold is ignored in this solver
Reference: http://www.iue.tuwien.ac.at/phd/heinreichsberger/node70.html http://www.numerik.math.tu-graz.ac.at/kurse/lgs/SIMNET6.pdf http://netlib.org
Implements sgpp::solver::SLESolverSP.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVectorSP::axpy(), sgpp::base::DataVectorSP::dotProduct(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMatrixSP::mult(), sgpp::solver::SGSolverSP::myEpsilon, sgpp::solver::SGSolverSP::nIterations, sgpp::solver::SGSolverSP::nMaxIterations, sgpp::solver::SGSolverSP::residuum, and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/sle/BiCGStabSP.hpp
solver/src/sgpp/solver/sle/BiCGStabSP.cpp