SG++-Doxygen-Documentation: sgpp::base::FundamentalNakSplineBasis< LT, IT > Class Template Reference
sgpp::base::FundamentalNakSplineBasis< LT, IT > Class Template Reference
Fundamental not-a-knot spline basis.
#include <FundamentalNakSplineBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
FundamentalNakSplineBasis ()
Default constructor.
FundamentalNakSplineBasis (size_t degree)
Constructor.
int getCoefficients (LT l, IT i, std::vector< double > &coefficients)
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
~FundamentalNakSplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
std::vector< double > coefficients
B-spline coefficients.
FundamentalSplineBasis< LT, IT > fundamentalSplineBasis
fundamental spline basis
NakBsplineBasis< LT, IT > nakBsplineBasis
not-a-knot B-spline basis
NakBsplineBasisDeriv1< LT, IT > nakBsplineBasisDeriv1
1st derivative of not-a-knot B-spline basis
NakBsplineBasisDeriv2< LT, IT > nakBsplineBasisDeriv2
2nd derivative of not-a-knot B-spline basis
Detailed Description
template<class LT, class IT>
class sgpp::base::FundamentalNakSplineBasis< LT, IT >
Fundamental not-a-knot spline basis.
Constructor & Destructor Documentation
FundamentalNakSplineBasis() [1/2]
template<class LT , class IT > sgpp::base::FundamentalNakSplineBasis< LT, IT >::FundamentalNakSplineBasis () inline
Default constructor.
FundamentalNakSplineBasis() [2/2]
template<class LT , class IT > sgpp::base::FundamentalNakSplineBasis< LT, IT >::FundamentalNakSplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree spline degree, must be odd (if it's even, degree - 1 is used)
~FundamentalNakSplineBasis()
template<class LT , class IT > sgpp::base::FundamentalNakSplineBasis< LT, IT >::~FundamentalNakSplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of fundamental not-a-knot spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalNakSplineBasis< LT, IT >::coefficients, sgpp::base::FundamentalNakSplineBasis< LT, IT >::fundamentalSplineBasis, sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), and sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()().
evalDx()
template<class LT , class IT > double sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of fundamental not-a-knot spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalNakSplineBasis< LT, IT >::coefficients, sgpp::base::FundamentalNakSplineBasis< LT, IT >::fundamentalSplineBasis, sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasisDeriv1.
Referenced by sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative().
evalDxDx()
template<class LT , class IT > double sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of fundamental not-a-knot spline basis function
References sgpp::base::FundamentalNakSplineBasis< LT, IT >::coefficients, sgpp::base::FundamentalNakSplineBasis< LT, IT >::fundamentalSplineBasis, sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasisDeriv2.
Referenced by sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian().
getCoefficients()
template<class LT , class IT > int sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients (LT l, IT i, std::vector< double > & coefficients) inline
References sgpp::base::FundamentalNakSplineBasis< LT, IT >::coefficients, and sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasis.
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDxDx().
getDegree()
template<class LT , class IT > size_t sgpp::base::FundamentalNakSplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
fundamental not-a-knot spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::FundamentalNakSplineBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
coefficients
template<class LT , class IT > std::vector<double> sgpp::base::FundamentalNakSplineBasis< LT, IT >::coefficients protected
B-spline coefficients.
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDxDx(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients().
fundamentalSplineBasis
template<class LT , class IT > FundamentalSplineBasis<LT, IT> sgpp::base::FundamentalNakSplineBasis< LT, IT >::fundamentalSplineBasis protected
fundamental spline basis
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDxDx().
nakBsplineBasis
template<class LT , class IT > NakBsplineBasis<LT, IT> sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasis protected
not-a-knot B-spline basis
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::getCoefficients(), and sgpp::base::FundamentalNakSplineBasis< LT, IT >::getDegree().
nakBsplineBasisDeriv1
template<class LT , class IT > NakBsplineBasisDeriv1<LT, IT> sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasisDeriv1 protected
1st derivative of not-a-knot B-spline basis
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx().
nakBsplineBasisDeriv2
template<class LT , class IT > NakBsplineBasisDeriv2<LT, IT> sgpp::base::FundamentalNakSplineBasis< LT, IT >::nakBsplineBasisDeriv2 protected
2nd derivative of not-a-knot B-spline basis
Referenced by sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDxDx().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/FundamentalNakSplineBasis.hpp