SG++-Doxygen-Documentation: sgpp::base::DistributionTruncGamma Class Reference
sgpp::base::DistributionTruncGamma Class Reference
#include <DistributionTruncGamma.hpp>
Public Member Functions
DistributionTruncGamma (double alpha=0, double r=20)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionTruncGamma ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Constructor & Destructor Documentation
DistributionTruncGamma()
sgpp::base::DistributionTruncGamma::DistributionTruncGamma (double alpha = 0, double r = 20) inline explicit
Constructor.
~DistributionTruncGamma()
virtual sgpp::base::DistributionTruncGamma::~DistributionTruncGamma () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionTruncGamma::eval (double x) inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionTruncGamma::getBounds () inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionTruncGamma::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionTruncGamma::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::TruncGamma.
sample()
double sgpp::base::DistributionTruncGamma::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionTruncGamma.hpp