SG++-Doxygen-Documentation: sgpp::datadriven::SystemMatrixLeastSquaresIdentity Class Reference
sgpp::datadriven::SystemMatrixLeastSquaresIdentity Class Reference
Class that implements the virtual class base::OperationMatrix for the application of classification for the Systemmatrix.
#include <SystemMatrixLeastSquaresIdentity.hpp>
Public Member Functions
virtual void generateb (base::DataVector &classes, base::DataVector &b)
Generates the right hand side of the classification equation.
virtual void mult (base::DataVector &alpha, base::DataVector &result)
starts the Multiplication with the matrix
virtual void prepareGrid ()
forward declaration
void setImplementation (datadriven::OperationMultipleEvalConfiguration operationConfiguration)
SystemMatrixLeastSquaresIdentity (base::Grid &SparseGrid, base::DataMatrix &trainData, double lambda)
Std-Constructor.
virtual ~SystemMatrixLeastSquaresIdentity ()
Std-Destructor.
Public Member Functions inherited from sgpp::datadriven::DMSystemMatrixBase
DMSystemMatrixBase (base::DataMatrix &trainData, double lambda)
Std-Constructor.
virtual void getTimers (double &timeMult, double &computeMult, double &timeMultTrans, double &computeMultTrans)
gets the timer's values by saving them into call by reference values
virtual void resetTimers ()
resets all timers to 0
virtual ~DMSystemMatrixBase ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::DMSystemMatrixBase
double completeTimeMult_
time needed for Mult
double completeTimeMultTrans_
time needed for Mult transposed
double computeTimeMult_
time needed only for the computation of mult, interesting on accelerator boards
double computeTimeMultTrans_
time needed only for the computation of mult transposed, interesting on accelerator boards
base::DataMatrix dataset_
the dataset
double lambda_
the lambda, the regularisation parameter
base::SGppStopwatch * myTimer_
Stopwatch needed to determine the durations of mult and mult transposed.
Detailed Description
Class that implements the virtual class base::OperationMatrix for the application of classification for the Systemmatrix.
The Identity matrix is used as regularization operator.
For the Operation B's mult and mutlTransposed functions vectorized formulations are used.
Constructor & Destructor Documentation
SystemMatrixLeastSquaresIdentity()
sgpp::datadriven::SystemMatrixLeastSquaresIdentity::SystemMatrixLeastSquaresIdentity (base::Grid & SparseGrid, base::DataMatrix & trainData, double lambda)
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
trainData reference to base::DataMatrix that contains the training data
lambda the lambda, the regression parameter
References sgpp::op_factory::createOperationMultipleEval(), sgpp::datadriven::DMSystemMatrixBase::dataset_, and sgpp::base::DataMatrix::getNrows().
~SystemMatrixLeastSquaresIdentity()
sgpp::datadriven::SystemMatrixLeastSquaresIdentity::~SystemMatrixLeastSquaresIdentity () virtual
Std-Destructor.
Member Function Documentation
generateb()
void sgpp::datadriven::SystemMatrixLeastSquaresIdentity::generateb (base::DataVector & classes, base::DataVector & b) virtual
Generates the right hand side of the classification equation.
Parameters
classes the class information of the training data
b reference to the vector that will contain the result of the matrix vector multiplication on the rhs
Implements sgpp::datadriven::DMSystemMatrixBase.
References sgpp::datadriven::DMSystemMatrixBase::completeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixBase::computeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixBase::myTimer_, sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
mult()
void sgpp::datadriven::SystemMatrixLeastSquaresIdentity::mult (base::DataVector & alpha, base::DataVector & result) virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::datadriven::DMSystemMatrixBase.
References alpha, sgpp::base::DataVector::axpy(), sgpp::datadriven::DMSystemMatrixBase::completeTimeMult_, sgpp::datadriven::DMSystemMatrixBase::completeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixBase::computeTimeMult_, sgpp::datadriven::DMSystemMatrixBase::computeTimeMultTrans_, sgpp::datadriven::DMSystemMatrixBase::lambda_, sgpp::datadriven::DMSystemMatrixBase::myTimer_, sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
prepareGrid()
void sgpp::datadriven::SystemMatrixLeastSquaresIdentity::prepareGrid () virtual
forward declaration
rebuilds the base::DataMatrix for Level and Index this routine is needed for supporting adaptive grids with vectorized high performance kernels
Reimplemented from sgpp::datadriven::DMSystemMatrixBase.
setImplementation()
void sgpp::datadriven::SystemMatrixLeastSquaresIdentity::setImplementation (datadriven::OperationMultipleEvalConfiguration operationConfiguration)
References sgpp::op_factory::createOperationMultipleEval(), and sgpp::datadriven::DMSystemMatrixBase::dataset_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/SystemMatrixLeastSquaresIdentity.hpp
datadriven/src/sgpp/datadriven/algorithm/SystemMatrixLeastSquaresIdentity.cpp