SG++-Doxygen-Documentation: sgpp::solver::SLESolver Class Reference
sgpp::solver::SLESolver Class Reference abstract
#include <SLESolver.hpp>
Public Member Functions
SLESolver (size_t imax, double epsilon)
Std-Constructor.
virtual void solve (sgpp::base::OperationMatrix &SystemMatrix, sgpp::base::DataVector &alpha, sgpp::base::DataVector &b, bool reuse=false, bool verbose=false, double max_threshold=DEFAULT_RES_THRESHOLD)=0
Pure virtual Function that defines a solve method for an iterative solver.
virtual ~SLESolver ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolver
double getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
double getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (double eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolver (size_t nMaximumIterations, double epsilon)
Std-Constructor.
virtual ~SGSolver ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolver
double myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
double residuum
residuum
Constructor & Destructor Documentation
SLESolver()
sgpp::solver::SLESolver::SLESolver (size_t imax, double epsilon) inline
Std-Constructor.
Parameters
imax number of maximum executed iterations
epsilon the final error in the iterative solver
~SLESolver()
virtual sgpp::solver::SLESolver::~SLESolver () inline virtual
Std-Destructor.
Member Function Documentation
solve()
virtual void sgpp::solver::SLESolver::solve (sgpp::base::OperationMatrix & SystemMatrix, sgpp::base::DataVector & alpha, sgpp::base::DataVector & b, bool reuse = false, bool verbose = false, double max_threshold = DEFAULT_RES_THRESHOLD) pure virtual
Pure virtual Function that defines a solve method for an iterative solver.
Parameters
SystemMatrix reference to an sgpp::base::OperationMatrix Object that implements the matrix vector multiplication
alpha the sparse grid's coefficients which have to be determined
b the right hand side of the system of linear equations
reuse identifies if the alphas, stored in alpha at calling time, should be reused
verbose prints information during execution of the solver
max_threshold additional abort criteria for solver, default value is 10^-9!
Implemented in sgpp::solver::BiCGStab, and sgpp::solver::ConjugateGradients.
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::VarTimestep::predictor(), sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), and sgpp::solver::Euler::solve().
The documentation for this class was generated from the following file:
solver/src/sgpp/solver/SLESolver.hpp