SG++-Doxygen-Documentation: sgpp::base::LinearBasis< LT, IT > Class Template Reference
sgpp::base::LinearBasis< LT, IT > Class Template Reference
Linear basis on Noboundary grids.
#include <LinearBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
~LinearBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Detailed Description
template<class LT, class IT>
class sgpp::base::LinearBasis< LT, IT >
Linear basis on Noboundary grids.
Constructor & Destructor Documentation
~LinearBasis()
template<class LT , class IT > sgpp::base::LinearBasis< LT, IT >::~LinearBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::LinearBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of linear basis function
Implements sgpp::base::Basis< LT, IT >.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::datadriven::OperationDotProductLinear::eval(), sgpp::datadriven::PiecewiseConstantRegression::Node::integrate(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), and sgpp::base::OperationMultipleEvalLinearNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::LinearBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
Reimplemented in sgpp::base::LinearStretchedBasis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::LinearBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
Reimplemented in sgpp::base::LinearStretchedBasis< LT, IT >.
getIntegral()
template<class LT , class IT > double sgpp::base::LinearBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References level.
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/LinearBasis.hpp