SG++-Doxygen-Documentation: sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive Class Reference
sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive Class Reference
Operation for evaluating partial derivatives of modified weakly fundamental spline linear combinations on Noboundary grids.
#include <OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive.hpp>
Public Member Functions
void evalPartialDerivative (const DataMatrix &alpha, const DataVector &point, size_t derivDim, DataVector &value, DataVector &partialDerivative) override
double evalPartialDerivative (const DataVector &alpha, const DataVector &point, size_t derivDim, double &partialDerivative) override
OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalPartialDerivative
OperationEvalPartialDerivative ()
Constructor.
virtual ~OperationEvalPartialDerivative ()
Destructor.
Protected Attributes
SWeaklyFundamentalNakSplineModifiedBase base
1D spline basis
SWeaklyFundamentalNakSplineModifiedBaseDeriv1 baseDeriv1
1D spline basis derivative
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalPartialDerivative
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating partial derivatives of modified weakly fundamental spline linear combinations on Noboundary grids.
Constructor & Destructor Documentation
OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive()
sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive()
sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::~OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive () inline override
Destructor.
Member Function Documentation
evalPartialDerivative() [1/2]
void sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative (const DataMatrix & alpha, const DataVector & point, size_t derivDim, DataVector & value, DataVector & partialDerivative) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
derivDim dimension in which the partial derivative should be taken (0, ..., d-1)
[out] value values of the linear combination
[out] partialDerivative values of the partial derivatives of the linear combination (the j-th entry corresponds to the j-th column of alpha)
Reimplemented from sgpp::base::OperationEvalPartialDerivative.
References alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalPartialDerivative() [2/2]
double sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative (const DataVector & alpha, const DataVector & point, size_t derivDim, double & partialDerivative) override virtual
Parameters
alpha coefficient vector
point evaluation point
derivDim dimension in which the partial derivative should be taken (0, ..., d-1)
[out] partialDerivative value of the partial derivative of the linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalPartialDerivative.
References alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineModifiedBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SWeaklyFundamentalNakSplineModifiedBase sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::base protected
1D spline basis
Referenced by evalPartialDerivative(), and evalPartialDerivative().
baseDeriv1
SWeaklyFundamentalNakSplineModifiedBaseDeriv1 sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::baseDeriv1 protected
1D spline basis derivative
Referenced by evalPartialDerivative(), and evalPartialDerivative().
pointInUnitCube
DataVector sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalPartialDerivative(), and evalPartialDerivative().
storage
GridStorage& sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::storage protected
storage of the sparse grid
Referenced by evalPartialDerivative(), and evalPartialDerivative().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive.cpp