SG++-Doxygen-Documentation: sgpp::pde::HeatEquationParabolicPDESolverSystem Class Reference
sgpp::pde::HeatEquationParabolicPDESolverSystem Class Reference
This class implements the ParabolicPDESolverSystem for the Heat Equation.
#include <HeatEquationParabolicPDESolverSystem.hpp>
Public Member Functions
virtual void coarsenAndRefine (bool isLastTimestep=false)
virtual void finishTimestep ()
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
HeatEquationParabolicPDESolverSystem (sgpp::base::Grid &SparseGrid, sgpp::base::DataVector &alpha, double a, double TimestepSize, std::string OperationMode="ExEul")
Std-Constructor.
virtual void startTimestep ()
Implements some start jobs of every timestep, e.g.discounting boundaries.
virtual ~HeatEquationParabolicPDESolverSystem ()
Std-Destructor.
Public Member Functions inherited from sgpp::pde::OperationParabolicPDESolverSystemDirichlet
virtual sgpp::base::DataVector * generateRHS ()
generates the right hand side of the system
virtual sgpp::base::DataVector * getGridCoefficientsForCG ()
gets a pointer to the sparse grids coefficients used in the CG method to solve one timestep.
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Multiplicates a vector with the matrix.
OperationParabolicPDESolverSystemDirichlet ()
Constructor.
virtual ~OperationParabolicPDESolverSystemDirichlet ()
Destructor.
Public Member Functions inherited from sgpp::solver::OperationParabolicPDESolverSystem
void abortTimestep ()
aborts the current timestep execution
sgpp::base::Grid * getGrid ()
get the pointer to the underlying grid object
sgpp::base::DataVector * getGridCoefficients ()
gets a pointer to the sparse grids coefficients with evtl.
void getGridCoefficientsForSC (sgpp::base::DataVector &Values)
stores the values of the (dehierarchized) grid in the sgpp::base::DataVector Values used by time step size control methods
sgpp::base::GridStorage * getGridStorage ()
std::string getODESolver ()
Returns the specified ODE solver for this instance.
sgpp::base::GridStorage * getOldGridStorage ()
sgpp::base::GridStorage * getSecondGridStorage ()
size_t getSumGridPointsComplete ()
Returns the number of average grid points for the complete grid.
size_t getSumGridPointsInner ()
Returns the number of average grid points for the inner grid.
OperationParabolicPDESolverSystem ()
Constructor.
void saveAlpha ()
stores the current alpha_complete into alpha_complete_old to be available in the next timestep
void setODESolver (std::string ode)
defines the used ODE Solver for this instance, this is important because the implementation of mult and generateRHS depends on the used ODE solver
void setTimestepSize (double newTimestepSize)
set the size of the new timestep
virtual ~OperationParabolicPDESolverSystem ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::pde::OperationParabolicPDESolverSystemDirichlet
sgpp::base::DataVector * alpha_inner
Pointer to the alphas (ansatzfunctions' coefficients; inner points only)
sgpp::base::DirichletUpdateVector * BoundaryUpdate
Routine to modify the boundaries/inner points of the grid.
sgpp::base::DirichletGridConverter * GridConverter
Class that allows a simple conversion between a grid with and a without boundary points.
sgpp::base::Grid * InnerGrid
Pointer to the inner grid object.
Protected Attributes inherited from sgpp::solver::OperationParabolicPDESolverSystem
sgpp::base::DataVector * alpha_complete
Pointer to the alphas (ansatzfunctions' coefficients)
sgpp::base::DataVector * alpha_complete_old
Pointer to the alphas from the last timestep, needed when using variable timestep sizes.
sgpp::base::DataVector * alpha_complete_tmp
Pointer to temporary alphas, needed when using variable timestep sizes.
bool bnewODESolver
checks whether a new ODE solver has been selected after creation
sgpp::base::Grid * BoundGrid
Pointer to the grid object.
size_t numSumGridpointsComplete
Stores number of average gridpoints, complete grid.
size_t numSumGridpointsInner
Stores number of average gridpoints, inner grid.
sgpp::base::GridStorage * oldGridStorage
Pointer to the grid from the last iteration.
sgpp::base::DataVector * rhs
sgpp::base::GridStorage * secondGridStorage
Pointer to the grid from the last aborted iteration.
double TimestepSize
the size of one timestep used in the ODE Solver
double TimestepSize_old
the size of the last timestep
std::string tOperationMode
specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler ImEul for implicit Euler CrNic for Crank Nicolson solver
Detailed Description
This class implements the ParabolicPDESolverSystem for the Heat Equation.
Constructor & Destructor Documentation
HeatEquationParabolicPDESolverSystem()
sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem (sgpp::base::Grid & SparseGrid, sgpp::base::DataVector & alpha, double a, double TimestepSize, std::string OperationMode = "ExEul")
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
alpha the sparse grid's coefficients
a the heat coefficient
TimestepSize the size of one timestep used in the ODE Solver
OperationMode specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler, ImEul for implicit Euler, CrNic for Crank Nicolson solver
References alpha, sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::BoundaryUpdate, sgpp::solver::OperationParabolicPDESolverSystem::BoundGrid, sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::op_factory::createOperationLaplace(), sgpp::op_factory::createOperationLTwoDotProduct(), sgpp::base::Grid::getStorage(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, sgpp::solver::OperationParabolicPDESolverSystem::rhs, sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize, and sgpp::solver::OperationParabolicPDESolverSystem::tOperationMode.
~HeatEquationParabolicPDESolverSystem()
sgpp::pde::HeatEquationParabolicPDESolverSystem::~HeatEquationParabolicPDESolverSystem () virtual
Std-Destructor.
References sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::BoundaryUpdate, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::InnerGrid, and sgpp::solver::OperationParabolicPDESolverSystem::rhs.
Member Function Documentation
coarsenAndRefine()
void sgpp::pde::HeatEquationParabolicPDESolverSystem::coarsenAndRefine (bool isLastTimestep = false) virtual
Implements sgpp::solver::OperationParabolicPDESolverSystem.
finishTimestep()
void sgpp::pde::HeatEquationParabolicPDESolverSystem::finishTimestep () virtual
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
some boundary adjustments.
Implements sgpp::solver::OperationParabolicPDESolverSystem.
References sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::alpha_inner, sgpp::pde::OperationParabolicPDESolverSystemDirichlet::GridConverter, and sgpp::base::DirichletGridConverter::updateBoundaryCoefs().
startTimestep()
void sgpp::pde::HeatEquationParabolicPDESolverSystem::startTimestep () virtual
Implements some start jobs of every timestep, e.g.discounting boundaries.
Implements sgpp::solver::OperationParabolicPDESolverSystem.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/algorithm/HeatEquationParabolicPDESolverSystem.hpp
pde/src/sgpp/pde/algorithm/HeatEquationParabolicPDESolverSystem.cpp