SG++-Doxygen-Documentation: sgpp::datadriven::ScorerMetricTypeParser Class Reference
sgpp::datadriven::ScorerMetricTypeParser Class Reference
Convenience class to convert strings to sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType and generate string representations for values of sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType.
#include <ScorerMetricTypeParser.hpp>
Static Public Member Functions
static ScorerMetricType parse (const std::string &input)
Convert strings to values sgpp::datadriven::ScorerMetricType.
static RegularizationMetricType parseRegularizationMetric (const std::string &input)
Convert strings to values sgpp::datadriven::RegularizationMetricType.
static const std::string & regularizationMetricToString (RegularizationMetricType type)
generate string representations for values of sgpp::datadriven::RegularizationMetricType.
static const std::string & toString (ScorerMetricType type)
generate string representations for values of sgpp::datadriven::ScorerMetricType.
Detailed Description
Convenience class to convert strings to sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType and generate string representations for values of sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType.
Member Function Documentation
parse()
ScorerMetricType sgpp::datadriven::ScorerMetricTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::datadriven::ScorerMetricType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::datadriven::ScorerMetricType.
Returns
the corresponding sgpp::datadriven::ScorerMetricType.
References sgpp::datadriven::accuracy, sgpp::datadriven::mse, and sgpp::datadriven::nll.
Referenced by sgpp::datadriven::DataMiningConfigParser::getScorerConfig().
parseRegularizationMetric()
RegularizationMetricType sgpp::datadriven::ScorerMetricTypeParser::parseRegularizationMetric (const std::string & input) static
Convert strings to values sgpp::datadriven::RegularizationMetricType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::datadriven::RegularizationMetricType.
Returns
the corresponding sgpp::datadriven::RegularizationMetricType.
References sgpp::datadriven::accuracy, sgpp::datadriven::mse, sgpp::datadriven::nll, and sgpp::datadriven::residual.
Referenced by sgpp::datadriven::DataMiningConfigParser::getFitterRegularizationConfig().
regularizationMetricToString()
const std::string & sgpp::datadriven::ScorerMetricTypeParser::regularizationMetricToString (RegularizationMetricType type) static
generate string representations for values of sgpp::datadriven::RegularizationMetricType.
Parameters
type enum value.
Returns
string representation of a sgpp::datadriven::RegularizationMetricType.
Referenced by sgpp::datadriven::DataMiningConfigParser::getFitterRegularizationConfig().
toString()
const std::string & sgpp::datadriven::ScorerMetricTypeParser::toString (ScorerMetricType type) static
generate string representations for values of sgpp::datadriven::ScorerMetricType.
Parameters
type enum value.
Returns
string representation of a sgpp::datadriven::ScorerMetricType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DataMiningConfigParser::getScorerConfig(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/scoring/ScorerMetricTypeParser.hpp
datadriven/src/sgpp/datadriven/datamining/modules/scoring/ScorerMetricTypeParser.cpp