SG++-Doxygen-Documentation: sgpp::base::OCLZeroCopyBuffer Class Reference
sgpp::base::OCLZeroCopyBuffer Class Reference
#include <OCLZeroCopyBuffer.hpp>
Public Member Functions
void freeBuffer ()
cl_mem * getBuffer (size_t deviceNumber)
void * getMappedBuffer ()
void initializeBuffer (void *initialValues, size_t sizeofType, size_t elements, bool readOnly)
bool isInitialized ()
OCLZeroCopyBuffer (std::shared_ptr< OCLManager > manager)
void readFromBuffer (void *hostData)
void writeToBuffer (void *hostData)
~OCLZeroCopyBuffer ()
Constructor & Destructor Documentation
OCLZeroCopyBuffer()
sgpp::base::OCLZeroCopyBuffer::OCLZeroCopyBuffer (std::shared_ptr< OCLManager > manager) explicit
~OCLZeroCopyBuffer()
sgpp::base::OCLZeroCopyBuffer::~OCLZeroCopyBuffer ()
References freeBuffer().
Member Function Documentation
freeBuffer()
void sgpp::base::OCLZeroCopyBuffer::freeBuffer ()
Referenced by ~OCLZeroCopyBuffer().
getBuffer()
cl_mem * sgpp::base::OCLZeroCopyBuffer::getBuffer (size_t deviceNumber)
getMappedBuffer()
void * sgpp::base::OCLZeroCopyBuffer::getMappedBuffer ()
initializeBuffer()
void sgpp::base::OCLZeroCopyBuffer::initializeBuffer (void * initialValues, size_t sizeofType, size_t elements, bool readOnly)
References writeToBuffer().
isInitialized()
bool sgpp::base::OCLZeroCopyBuffer::isInitialized ()
readFromBuffer()
void sgpp::base::OCLZeroCopyBuffer::readFromBuffer (void * hostData)
writeToBuffer()
void sgpp::base::OCLZeroCopyBuffer::writeToBuffer (void * hostData)
Referenced by initializeBuffer().
The documentation for this class was generated from the following files:
base/src/sgpp/base/opencl/OCLZeroCopyBuffer.hpp
base/src/sgpp/base/opencl/OCLZeroCopyBuffer.cpp