SG++-Doxygen-Documentation: sgpp::base::DistributionBeta Class Reference
sgpp::base::DistributionBeta Class Reference
Disclaimer: This implementation models the beta distribution used for Polynomial Chaos Expansion and should not be confused with the textbook definition of a beta distribution.
#include <DistributionBeta.hpp>
Public Member Functions
DistributionBeta (double alpha, double beta)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionBeta ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Detailed Description
Disclaimer: This implementation models the beta distribution used for Polynomial Chaos Expansion and should not be confused with the textbook definition of a beta distribution.
Constructor & Destructor Documentation
DistributionBeta()
sgpp::base::DistributionBeta::DistributionBeta (double alpha, double beta) inline explicit
Constructor.
References alpha.
~DistributionBeta()
virtual sgpp::base::DistributionBeta::~DistributionBeta () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionBeta::eval (double x) inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionBeta::getBounds () inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionBeta::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionBeta::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Beta.
sample()
double sgpp::base::DistributionBeta::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionBeta.hpp