SG++-Doxygen-Documentation: sgpp::base::RefinementFunctor Class Reference
sgpp::base::RefinementFunctor Class Reference abstract
Abstract class that defines the interface that refinement functors have to provide.
#include <RefinementFunctor.hpp>
Public Types
typedef double value_type
Public Member Functions
virtual size_t getRefinementsNum () const
Returns the maximal number of points that should be refined.
virtual double getRefinementThreshold () const =0
Returns the threshold for refinement.
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
virtual double operator() (GridStorage &storage, size_t seq) const =0
This should be returning a refinement value for every grid point.
RefinementFunctor ()
Constructor.
virtual double start () const =0
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
virtual ~RefinementFunctor ()
Destructor.
Detailed Description
Abstract class that defines the interface that refinement functors have to provide.
Member Typedef Documentation
value_type
typedef double sgpp::base::RefinementFunctor::value_type
Constructor & Destructor Documentation
RefinementFunctor()
sgpp::base::RefinementFunctor::RefinementFunctor () inline
Constructor.
~RefinementFunctor()
virtual sgpp::base::RefinementFunctor::~RefinementFunctor () inline virtual
Destructor.
Member Function Documentation
getRefinementsNum()
virtual size_t sgpp::base::RefinementFunctor::getRefinementsNum () const inline virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
number of points that should refined. Default value: 1.
Reimplemented in sgpp::base::ForwardSelectorRefinementIndicator, sgpp::base::ImpurityRefinementIndicator, sgpp::base::PredictiveRefinementIndicator, sgpp::base::SurplusRefinementFunctor, sgpp::base::SurplusVolumeRefinementFunctor, sgpp::base::VectorDistributionRefinementFunctor, sgpp::base::VectorSurplusRefinementFunctor, sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, and sgpp::datadriven::MultiSurplusRefinementFunctor.
Referenced by sgpp::optimization::HashRefinementMultiple::collectRefinablePoints(), sgpp::base::HashRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), sgpp::base::ForwardSelectorRefinement::collectRefinablePoints(), sgpp::base::ImpurityRefinement::collectRefinablePoints(), sgpp::base::MultipleClassRefinement::collectRefinablePoints(), sgpp::base::PredictiveRefinement::collectRefinablePoints(), sgpp::base::SubspaceRefinement::collectRefinablePoints(), and sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel().
getRefinementThreshold()
virtual double sgpp::base::RefinementFunctor::getRefinementThreshold () const pure virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion (e.g., alpha or error) greater or equal to this threshold will be refined.
Returns
threshold value for refinement. Default value: 0.
Implemented in sgpp::base::ForwardSelectorRefinementIndicator, sgpp::base::ImpurityRefinementIndicator, sgpp::base::PredictiveRefinementIndicator, sgpp::base::SurplusRefinementFunctor, sgpp::base::SurplusVolumeRefinementFunctor, sgpp::base::VectorDistributionRefinementFunctor, sgpp::base::VectorSurplusRefinementFunctor, sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, and sgpp::datadriven::MultiSurplusRefinementFunctor.
Referenced by sgpp::base::HashRefinement::refineGridpointsCollection(), sgpp::base::HashRefinementBoundaries::refineGridpointsCollection(), sgpp::base::PredictiveRefinement::refineGridpointsCollection(), and sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel().
getTotalRefinementValue()
virtual double sgpp::base::RefinementFunctor::getTotalRefinementValue (GridStorage & storage) const inline virtual
Returns the total sum of local (error) indicators used for refinement.
Parameters
storage pointer to the grids storage object
Returns
total sum of local (error) indicators used for refinement
References sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), and operator()().
operator()()
virtual double sgpp::base::RefinementFunctor::operator() (GridStorage & storage, size_t seq) const pure virtual
This should be returning a refinement value for every grid point.
The point with the highest value will be refined first.
Parameters
storage reference to the grids storage object
seq sequence number in the coefficients array
Returns
refinement value
Implemented in sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::MultipleClassRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, sgpp::datadriven::MultiSurplusRefinementFunctor, sgpp::base::ForwardSelectorRefinementIndicator, sgpp::base::ImpurityRefinementIndicator, sgpp::base::PredictiveRefinementIndicator, sgpp::base::SurplusRefinementFunctor, sgpp::base::SurplusVolumeRefinementFunctor, sgpp::base::VectorDistributionRefinementFunctor, and sgpp::base::VectorSurplusRefinementFunctor.
Referenced by getTotalRefinementValue().
start()
virtual double sgpp::base::RefinementFunctor::start () const pure virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implemented in sgpp::base::ForwardSelectorRefinementIndicator, sgpp::base::ImpurityRefinementIndicator, sgpp::base::PredictiveRefinementIndicator, sgpp::base::SurplusRefinementFunctor, sgpp::base::SurplusVolumeRefinementFunctor, sgpp::base::VectorDistributionRefinementFunctor, sgpp::base::VectorSurplusRefinementFunctor, sgpp::datadriven::ClassificationRefinementFunctor, sgpp::datadriven::DataBasedRefinementFunctor, sgpp::datadriven::GridPointBasedRefinementFunctor, sgpp::datadriven::ZeroCrossingRefinementFunctor, and sgpp::datadriven::MultiSurplusRefinementFunctor.
Referenced by sgpp::base::PredictiveRefinement::refineGridpointsCollection(), and sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel().
The documentation for this class was generated from the following file:
base/src/sgpp/base/grid/generation/functors/RefinementFunctor.hpp