SG++-Doxygen-Documentation: sgpp::base::OperationEvalModLinearClenshawCurtisNaive Class Reference
sgpp::base::OperationEvalModLinearClenshawCurtisNaive Class Reference
#include <OperationEvalModLinearClenshawCurtisNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalModLinearClenshawCurtisNaive (GridStorage &storage)
Constructor.
~OperationEvalModLinearClenshawCurtisNaive () override
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SLinearModifiedClenshawCurtisBase base
1D linear basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Constructor & Destructor Documentation
OperationEvalModLinearClenshawCurtisNaive()
sgpp::base::OperationEvalModLinearClenshawCurtisNaive::OperationEvalModLinearClenshawCurtisNaive (GridStorage & storage) inline explicit
Constructor.
Parameters
storage storage of the sparse grid
~OperationEvalModLinearClenshawCurtisNaive()
sgpp::base::OperationEvalModLinearClenshawCurtisNaive::~OperationEvalModLinearClenshawCurtisNaive () inline override
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SLinearModifiedClenshawCurtisBase sgpp::base::OperationEvalModLinearClenshawCurtisNaive::base protected
1D linear basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalModLinearClenshawCurtisNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalModLinearClenshawCurtisNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalModLinearClenshawCurtisNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalModLinearClenshawCurtisNaive.cpp