SG++-Doxygen-Documentation: sgpp::pde::PhiPhiUpBBLinearBoundary Class Reference
sgpp::pde::PhiPhiUpBBLinearBoundary Class Reference
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
#include <PhiPhiUpBBLinearBoundary.hpp>
Public Member Functions
virtual void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of up in the direction of dimension dim
PhiPhiUpBBLinearBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiUpBBLinearBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::PhiPhiUpBBLinear
PhiPhiUpBBLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiUpBBLinear ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::PhiPhiUpBBLinear
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::PhiPhiUpBBLinear
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double &fl, double &fr)
recursive function for the calculation of Up without bounding Box support
void recBB (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double &fl, double &fr, double q, double t)
recursive function for the calculation of Up with Bounding Box Support
Protected Attributes inherited from sgpp::pde::PhiPhiUpBBLinear
sgpp::base::BoundingBox * boundingBox
Pointer to the bounding box Obejct.
sgpp::base::GridStorage * storage
Pointer to sgpp::base::GridStorage object.
Detailed Description
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
Constructor & Destructor Documentation
PhiPhiUpBBLinearBoundary()
sgpp::pde::PhiPhiUpBBLinearBoundary::PhiPhiUpBBLinearBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiUpBBLinearBoundary()
sgpp::pde::PhiPhiUpBBLinearBoundary::~PhiPhiUpBBLinearBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiUpBBLinearBoundary::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of up in the direction of dimension dim
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the up operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::pde::PhiPhiUpBBLinear.
References sgpp::pde::PhiPhiUpBBLinear::boundingBox, sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::BoundingBox::hasDirichletBoundaryLeft(), sgpp::base::BoundingBox::hasDirichletBoundaryRight(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), and sgpp::pde::PhiPhiUpBBLinear::storage.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/PhiPhiUpBBLinearBoundary.hpp
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/PhiPhiUpBBLinearBoundary.cpp