SG++-Doxygen-Documentation: json::TextNode Class Reference
json::TextNode Class Reference
#include <TextNode.hpp>
Public Member Functions
Node * clone () override
std::string & get () override
bool getBool () override
double getDouble () override
int64_t getInt () override
uint64_t getUInt () override
Node & operator= (const Node &right) override
TextNode & operator= (const TextNode &right)=default
void parse (std::vector< Token > &stream) override
void serialize (std::ostream &outFile, size_t indentWidth) override
void set (const std::string &value) override
void setBool (bool boolValue) override
void setDouble (double numericValue) override
void setInt (int64_t intValue) override
void setUInt (uint64_t uintValue) override
size_t size () override
TextNode ()
Public Member Functions inherited from json::Node
virtual void addAttribute (const std::string &name, std::unique_ptr< Node > node)
virtual Node & addDictAttr (const std::string &name)
virtual Node & addDictValue ()
virtual Node & addIDAttr (const std::string &name, const bool &value)
virtual Node & addIDAttr (const std::string &name, const char *value)
virtual Node & addIDAttr (const std::string &name, const double &value)
virtual Node & addIDAttr (const std::string &name, const int64_t &value)
virtual Node & addIDAttr (const std::string &name, const std::string &value)
virtual Node & addIDAttr (const std::string &name, const uint64_t &value)
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListAttr (const std::string &name)
virtual Node & addListValue ()
virtual Node & addTextAttr (const std::string &name, const std::string &value)
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual bool contains (const std::string &key)
virtual std::unique_ptr< Node > erase ()
virtual std::unique_ptr< Node > erase (Node &node)
virtual std::vector< std::string > & keys ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const size_t index)
virtual Node & operator[] (const std::string &key)
virtual std::unique_ptr< Node > removeAttribute (const std::string name)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual Node & replaceDictAttr (const std::string &name)
virtual Node & replaceIDAttr (const std::string &name, const bool &value)
virtual Node & replaceIDAttr (const std::string &name, const char *value)
virtual Node & replaceIDAttr (const std::string &name, const double &value)
virtual Node & replaceIDAttr (const std::string &name, const int64_t &value)
virtual Node & replaceIDAttr (const std::string &name, const std::string &value)
virtual Node & replaceIDAttr (const std::string &name, const uint64_t &value)
virtual Node & replaceListAttr (const std::string &name)
virtual Node & replaceTextAttr (const std::string &name, const std::string &value)
virtual ~Node ()=default
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
TextNode()
json::TextNode::TextNode ()
Referenced by clone().
Member Function Documentation
clone()
Node * json::TextNode::clone () override virtual
Implements json::Node.
References TextNode().
get()
std::string & json::TextNode::get () override virtual
Reimplemented from json::Node.
getBool()
bool json::TextNode::getBool () override virtual
Reimplemented from json::Node.
getDouble()
double json::TextNode::getDouble () override virtual
Reimplemented from json::Node.
getInt()
int64_t json::TextNode::getInt () override virtual
Reimplemented from json::Node.
getUInt()
uint64_t json::TextNode::getUInt () override virtual
Reimplemented from json::Node.
operator=() [1/2]
Node & json::TextNode::operator= (const Node & right) override virtual
Reimplemented from json::Node.
References operator=().
operator=() [2/2]
TextNode & json::TextNode::operator= (const TextNode & right) default
Referenced by operator=().
parse()
void json::TextNode::parse (std::vector< Token > & stream) override virtual
Implements json::Node.
References json::STRING.
serialize()
void json::TextNode::serialize (std::ostream & outFile, size_t indentWidth) override virtual
Implements json::Node.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
set()
void json::TextNode::set (const std::string & value) override virtual
Reimplemented from json::Node.
setBool()
void json::TextNode::setBool (bool boolValue) override virtual
Reimplemented from json::Node.
setDouble()
void json::TextNode::setDouble (double numericValue) override virtual
Reimplemented from json::Node.
setInt()
void json::TextNode::setInt (int64_t intValue) override virtual
Reimplemented from json::Node.
setUInt()
void json::TextNode::setUInt (uint64_t uintValue) override virtual
Reimplemented from json::Node.
size()
size_t json::TextNode::size () override virtual
Implements json::Node.
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), and python.data.DataContainer.DataContainer::getSize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/json/TextNode.hpp
base/src/sgpp/base/tools/json/TextNode.cpp