SG++-Doxygen-Documentation: sgpp::datadriven::DatasetGenerator Class Reference
sgpp::datadriven::DatasetGenerator Class Reference abstract
#include <DatasetGenerator.hpp>
Public Member Functions
virtual void createData (size_t offset, size_t size, base::DataMatrix &trainingData, base::DataVector &classes)=0
virtual size_t getDims ()=0
virtual double normal (double mean, double stddev)
generate normally distributed random variable see http://de.wikipedia.org/wiki/Box-Muller-Methode uses rand(), make sure to call srand yourself
virtual double uniform (double a, double b)
virtual ~DatasetGenerator ()
Constructor & Destructor Documentation
~DatasetGenerator()
sgpp::datadriven::DatasetGenerator::~DatasetGenerator () virtual
Member Function Documentation
createData()
virtual void sgpp::datadriven::DatasetGenerator::createData (size_t offset, size_t size, base::DataMatrix & trainingData, base::DataVector & classes) pure virtual
Implemented in sgpp::datadriven::Friedman1Generator, sgpp::datadriven::Friedman2Generator, and sgpp::datadriven::Friedman3Generator.
getDims()
virtual size_t sgpp::datadriven::DatasetGenerator::getDims () pure virtual
Implemented in sgpp::datadriven::Friedman1Generator, sgpp::datadriven::Friedman2Generator, and sgpp::datadriven::Friedman3Generator.
normal()
double sgpp::datadriven::DatasetGenerator::normal (double mean, double stddev) virtual
generate normally distributed random variable see http://de.wikipedia.org/wiki/Box-Muller-Methode uses rand(), make sure to call srand yourself
Parameters
mean mean of distribution
stddev std deviation of distribution
Returns
normally distributed random var
References M_PI.
Referenced by python.uq.dists.NatafDist.NatafDist::cdf(), sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), python.uq.dists.NatafDist.NatafDist::ppf(), python.uq.operations.natafTransformation.NatafTransformation::trans_U_to_Z(), python.uq.operations.natafTransformation.NatafTransformation::trans_X_to_Z(), python.uq.operations.natafTransformation.NatafTransformation::trans_Z_to_U(), and python.uq.operations.natafTransformation.NatafTransformation::trans_Z_to_X().
uniform()
double sgpp::datadriven::DatasetGenerator::uniform (double a, double b) virtual
Referenced by sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), and sgpp::datadriven::Friedman3Generator::createData().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/DatasetGenerator.hpp
datadriven/src/sgpp/datadriven/tools/DatasetGenerator.cpp