SG++-Doxygen-Documentation: sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT > Class Template Reference
sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT > Class Template Reference
Polynomial basis functions.
#include <PolyClenshawCurtisBoundaryBasis.hpp>
Public Member Functions
double eval (LT level, IT index, double p) override
Evaluate the basis function with given level and index.
double eval (LT level, IT index, double p, double offset, double width)
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
double evalHierToTop (LT level, IT index, DataVector &coeffs, double pos)
Evaluates all the hierarchical ancestors of the node defined by level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
PolyClenshawCurtisBoundaryBasis (size_t degree)
Constructor.
~PolyClenshawCurtisBoundaryBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
SPolyClenshawCurtisBase polyBasis
poly basis for clenshaw curtis grid
Detailed Description
template<class LT, class IT>
class sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >
Polynomial basis functions.
Version
$HEAD$
Constructor & Destructor Documentation
PolyClenshawCurtisBoundaryBasis()
template<class LT , class IT > sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::PolyClenshawCurtisBoundaryBasis (size_t degree) inline explicit
Constructor.
Parameters
degree the polynom's max. degree
~PolyClenshawCurtisBoundaryBasis()
template<class LT , class IT > sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::~PolyClenshawCurtisBoundaryBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval (LT level, IT index, double x) inline override virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), level, and sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::polyBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalHierToTop(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), and sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB().
eval() [2/2]
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval (LT level, IT index, double p, double offset, double width) inline
References sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), level, and sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::polyBasis.
Referenced by sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult().
evalHierToTop()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalHierToTop (LT level, IT index, DataVector & coeffs, double pos) inline
Evaluates all the hierarchical ancestors of the node defined by level and index.
NOTE: It does not evaluate the current node itself.
Parameters
level
index
coeffs
pos
Returns
References sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), and level.
Referenced by sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), and sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec().
getDegree()
template<class LT , class IT > size_t sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getDegree(), and sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::polyBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), level, and sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::polyBasis.
Referenced by sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature().
Member Data Documentation
polyBasis
template<class LT , class IT > SPolyClenshawCurtisBase sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::polyBasis protected
poly basis for clenshaw curtis grid
Referenced by sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalDx(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/PolyClenshawCurtisBoundaryBasis.hpp