SG++-Doxygen-Documentation: sgpp::base::StringTokenizer Class Reference
sgpp::base::StringTokenizer Class Reference
#include <StringTokenizer.hpp>
Static Public Member Functions
static void tokenize (const std::string &s, const char *delim, std::vector< std::string > &v)
Member Function Documentation
tokenize()
static void sgpp::base::StringTokenizer::tokenize (const std::string & s, const char * delim, std::vector< std::string > & v) inline static
Referenced by sgpp::datadriven::DBMatOfflineFactory::buildFromFile(), sgpp::datadriven::DBMatOfflineGE::DBMatOfflineGE(), sgpp::datadriven::DBMatOfflineOrthoAdapt::DBMatOfflineOrthoAdapt(), and sgpp::datadriven::DBMatOffline::parseInter().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/StringTokenizer.hpp