SG++-Doxygen-Documentation: sgpp::solver::SLESolverTypeParser Class Reference
sgpp::solver::SLESolverTypeParser Class Reference
Convenience class to convert strings to sgpp::solver::SLESolverType and generate string representations for values of sgpp::solver::SLESolverType.
#include <SLESolverTypeParser.hpp>
Static Public Member Functions
static SLESolverType parse (const std::string &input)
Convert strings to values sgpp::solver::SLESolverType.
static const std::string & toString (SLESolverType type)
generate string representations for values of sgpp::solver::SLESolverType.
Detailed Description
Convenience class to convert strings to sgpp::solver::SLESolverType and generate string representations for values of sgpp::solver::SLESolverType.
Member Function Documentation
parse()
SLESolverType sgpp::solver::SLESolverTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::solver::SLESolverType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::solver::SLESolverType.
Returns
the corresponding sgpp::solver::SLESolverType.
References sgpp::solver::BiCGSTAB, sgpp::solver::CG, and sgpp::solver::FISTA.
toString()
const std::string & sgpp::solver::SLESolverTypeParser::toString (SLESolverType type) static
generate string representations for values of sgpp::solver::SLESolverType.
Parameters
type enum value.
Returns
string representation of a sgpp::solver::SLESolverType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DMConfigTools::dumpToStream(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/SLESolverTypeParser.hpp
solver/src/sgpp/solver/SLESolverTypeParser.cpp