SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureNakBsplineExtended Class Reference
sgpp::base::OperationQuadratureNakBsplineExtended Class Reference
Quadrature on sparse grid, not a knot extended B-spline grid.
#include <OperationQuadratureNakBsplineExtended.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for not a knot B-spline basis functions.
OperationQuadratureNakBsplineExtended (GridStorage &storage, size_t degree)
Constructor of OperationQuadratureNakBsplineExtended.
~OperationQuadratureNakBsplineExtended () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SNakBsplineExtendedBase base
Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, not a knot extended B-spline grid.
Constructor & Destructor Documentation
OperationQuadratureNakBsplineExtended()
sgpp::base::OperationQuadratureNakBsplineExtended::OperationQuadratureNakBsplineExtended (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadratureNakBsplineExtended.
Parameters
storage Pointer to the grid's GridStorage object
degree the B-spline degree
~OperationQuadratureNakBsplineExtended()
sgpp::base::OperationQuadratureNakBsplineExtended::~OperationQuadratureNakBsplineExtended () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature (DataVector & alpha) override virtual
Quadrature for not a knot B-spline basis functions.
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::NakBsplineExtendedBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getSize(), and storage.
Member Data Documentation
base
SNakBsplineExtendedBase sgpp::base::OperationQuadratureNakBsplineExtended::base protected
Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadratureNakBsplineExtended::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureNakBsplineExtended.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureNakBsplineExtended.cpp