SG++-Doxygen-Documentation: sgpp::optimization::IterativeGridGeneratorRitterNovak Class Reference
sgpp::optimization::IterativeGridGeneratorRitterNovak Class Reference
Iterative grid generation based on Ritter/Novak's refinement criterion.
#include <IterativeGridGeneratorRitterNovak.hpp>
Public Types
enum class PowMethod { STD_POW , FAST_POW }
exponentiation methods
Public Member Functions
bool generate () override
Generate the grid.
double getAdaptivity () const
base::level_t getInitialLevel () const
base::level_t getMaxLevel () const
PowMethod getPowMethod () const
IterativeGridGeneratorRitterNovak (base::ScalarFunction &f, base::Grid &grid, size_t N, double adaptivity=DEFAULT_ADAPTIVITY, base::level_t initialLevel=DEFAULT_INITIAL_LEVEL, base::level_t maxLevel=DEFAULT_MAX_LEVEL, PowMethod powMethod=PowMethod::STD_POW)
Constructor.
void setAdaptivity (double adaptivity)
void setInitialLevel (base::level_t initialLevel)
void setMaxLevel (base::level_t maxLevel)
void setPowMethod (PowMethod powMethod)
~IterativeGridGeneratorRitterNovak () override
Destructor.
Public Member Functions inherited from sgpp::optimization::IterativeGridGenerator
const base::DataVector & getFunctionValues () const
base::Grid & getGrid () const
IterativeGridGenerator (base::ScalarFunction &f, base::Grid &grid, size_t N)
Constructor.
void printIterativeGridGenerator () const
Prints grid points and function values.
virtual ~IterativeGridGenerator ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_ADAPTIVITY = 0.85
default adaptivity
static const base::level_t DEFAULT_INITIAL_LEVEL = 3
default level of initial regular sparse grid
static const base::level_t DEFAULT_MAX_LEVEL = 20
default maximal level of grid points
Protected Attributes
double gamma
adaptivity
base::level_t initialLevel
level of initial regular sparse grid
base::level_t maxLevel
maximal level of grid points
PowMethod powMethod
exponentiation method
Protected Attributes inherited from sgpp::optimization::IterativeGridGenerator
base::ScalarFunction & f
objective function
base::DataVector functionValues
vector of function values at the grid points
base::Grid & grid
underlying grid
size_t N
maximal number of grid points
Additional Inherited Members
Protected Member Functions inherited from sgpp::optimization::IterativeGridGenerator
void evalFunction (size_t oldGridSize=0)
Evaluates the objective function at grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] and saves values in functionValues.
void undoRefinement (size_t oldGridSize)
Removes grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] from the grid.
Detailed Description
Iterative grid generation based on Ritter/Novak's refinement criterion.
Caution: This class uses HashRefinementMultiple, so it generates grids that don't meet the "hierarchical ancestors" requirement!
Literature: Erich Novak, Klaus Ritter. Global Optimization Using Hyperbolic Cross Points. In: Christodoulos A. Floudas, Panos M. Pardalos (eds.): State of the Art in Global Optimization, Computational Methods and Applications, Vol. 7. Springer 1996. DOI: 10.1007/978-1-4613-3437-8_2
See also
HashRefinementMultiple
Member Enumeration Documentation
PowMethod
enum class sgpp::optimization::IterativeGridGeneratorRitterNovak::PowMethod strong
exponentiation methods
Enumerator
STD_POW
FAST_POW
Constructor & Destructor Documentation
IterativeGridGeneratorRitterNovak()
sgpp::optimization::IterativeGridGeneratorRitterNovak::IterativeGridGeneratorRitterNovak (base::ScalarFunction & f, base::Grid & grid, size_t N, double adaptivity = DEFAULT_ADAPTIVITY, base::level_t initialLevel = DEFAULT_INITIAL_LEVEL, base::level_t maxLevel = DEFAULT_MAX_LEVEL, PowMethod powMethod = PowMethod::STD_POW)
Constructor.
Do not destruct the grid before this object!
Parameters
f objective function
grid grid (should be empty)
N maximal number of grid points
adaptivity adaptivity between 0 and 1
initialLevel level of initial regular sparse grid
maxLevel maximal level of grid points
powMethod exponentiation method (fastPow is faster than std::pow, but only approximative)
~IterativeGridGeneratorRitterNovak()
sgpp::optimization::IterativeGridGeneratorRitterNovak::~IterativeGridGeneratorRitterNovak () override
Destructor.
Member Function Documentation
generate()
bool sgpp::optimization::IterativeGridGeneratorRitterNovak::generate () override virtual
Generate the grid.
Returns
true on success, otherwise false
Implements sgpp::optimization::IterativeGridGenerator.
References sgpp::optimization::IterativeGridGenerator::evalFunction(), sgpp::optimization::IterativeGridGenerator::f, sgpp::base::HashRefinement::free_refine(), sgpp::optimization::IterativeGridGenerator::functionValues, g, gamma, sgpp::base::HashGridPoint::get(), sgpp::base::Grid::getGenerator(), sgpp::base::Printer::getInstance(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::ScalarFunction::getNumberOfParameters(), sgpp::base::DataVector::getSize(), sgpp::base::Grid::getStorage(), sgpp::optimization::IterativeGridGenerator::grid, initialLevel, sgpp::base::DataVector::insert(), maxLevel, sgpp::optimization::IterativeGridGenerator::N, powMethod, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::GridGenerator::regular(), sgpp::base::HashGridPoint::set(), sgpp::base::DataVector::setAll(), STD_POW, and sgpp::optimization::IterativeGridGenerator::undoRefinement().
Referenced by sgpp::optimization::SplineResponseSurface::ritterNovak().
getAdaptivity()
double sgpp::optimization::IterativeGridGeneratorRitterNovak::getAdaptivity () const
Returns
adaptivity between 0 and 1
References gamma.
getInitialLevel()
base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::getInitialLevel () const
Returns
level of initial regular sparse grid
References initialLevel.
getMaxLevel()
base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::getMaxLevel () const
Returns
maximal level of grid points
References maxLevel.
getPowMethod()
IterativeGridGeneratorRitterNovak::PowMethod sgpp::optimization::IterativeGridGeneratorRitterNovak::getPowMethod () const
Returns
exponentiation method
References powMethod.
setAdaptivity()
void sgpp::optimization::IterativeGridGeneratorRitterNovak::setAdaptivity (double adaptivity)
Parameters
adaptivity adaptivity between 0 and 1
References gamma.
setInitialLevel()
void sgpp::optimization::IterativeGridGeneratorRitterNovak::setInitialLevel (base::level_t initialLevel)
Parameters
initialLevel level of initial regular sparse grid
References initialLevel.
setMaxLevel()
void sgpp::optimization::IterativeGridGeneratorRitterNovak::setMaxLevel (base::level_t maxLevel)
Parameters
maxLevel maximal level of grid points
References maxLevel.
setPowMethod()
void sgpp::optimization::IterativeGridGeneratorRitterNovak::setPowMethod (IterativeGridGeneratorRitterNovak::PowMethod powMethod)
Parameters
powMethod exponentiation method
References powMethod.
Member Data Documentation
DEFAULT_ADAPTIVITY
constexpr double sgpp::optimization::IterativeGridGeneratorRitterNovak::DEFAULT_ADAPTIVITY = 0.85 static constexpr
default adaptivity
DEFAULT_INITIAL_LEVEL
const base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::DEFAULT_INITIAL_LEVEL = 3 static
default level of initial regular sparse grid
DEFAULT_MAX_LEVEL
const base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::DEFAULT_MAX_LEVEL = 20 static
default maximal level of grid points
gamma
double sgpp::optimization::IterativeGridGeneratorRitterNovak::gamma protected
adaptivity
Referenced by sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), generate(), getAdaptivity(), and setAdaptivity().
initialLevel
base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::initialLevel protected
level of initial regular sparse grid
Referenced by sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), generate(), getInitialLevel(), and setInitialLevel().
maxLevel
base::level_t sgpp::optimization::IterativeGridGeneratorRitterNovak::maxLevel protected
maximal level of grid points
Referenced by sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), generate(), getMaxLevel(), python.uq.operations.forcePositivity.localHierarchicalIntersectionSearch.LocalHierarchicalIntersectionCandidates::getMaxLevelOfChildrenUpToMaxLevel(), python.uq.refinement.AdmissibleSet.AdmissibleSetGenerator::insertPoint(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), and setMaxLevel().
powMethod
PowMethod sgpp::optimization::IterativeGridGeneratorRitterNovak::powMethod protected
exponentiation method
Referenced by sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), generate(), getPowMethod(), and setPowMethod().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorRitterNovak.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorRitterNovak.cpp