SG++-Doxygen-Documentation: sgpp::optimization::IterativeGridGeneratorSOO Class Reference
sgpp::optimization::IterativeGridGeneratorSOO Class Reference
Iterative grid generator using simultaneous optimistic optimization (SOO).
#include <IterativeGridGeneratorSOO.hpp>
Public Types
typedef std::function< size_t(size_t)> AdaptivityFunction
Public Member Functions
bool generate () override
Generate the grid.
AdaptivityFunction getAdaptivity () const
IterativeGridGeneratorSOO (base::ScalarFunction &f, base::Grid &grid, size_t N, double adaptivity=DEFAULT_ADAPTIVITY)
Constructor.
void setAdaptivity (AdaptivityFunction adaptivity)
void setAdaptivity (double adaptivity)
~IterativeGridGeneratorSOO () override
Destructor.
Public Member Functions inherited from sgpp::optimization::IterativeGridGenerator
const base::DataVector & getFunctionValues () const
base::Grid & getGrid () const
IterativeGridGenerator (base::ScalarFunction &f, base::Grid &grid, size_t N)
Constructor.
void printIterativeGridGenerator () const
Prints grid points and function values.
virtual ~IterativeGridGenerator ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_ADAPTIVITY = 0.5
default adaptivity
Protected Attributes
AdaptivityFunction hMax
adaptivity
Protected Attributes inherited from sgpp::optimization::IterativeGridGenerator
base::ScalarFunction & f
objective function
base::DataVector functionValues
vector of function values at the grid points
base::Grid & grid
underlying grid
size_t N
maximal number of grid points
Additional Inherited Members
Protected Member Functions inherited from sgpp::optimization::IterativeGridGenerator
void evalFunction (size_t oldGridSize=0)
Evaluates the objective function at grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] and saves values in functionValues.
void undoRefinement (size_t oldGridSize)
Removes grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] from the grid.
Detailed Description
Iterative grid generator using simultaneous optimistic optimization (SOO).
Member Typedef Documentation
AdaptivityFunction
typedef std::function<size_t(size_t)> sgpp::optimization::IterativeGridGeneratorSOO::AdaptivityFunction
Constructor & Destructor Documentation
IterativeGridGeneratorSOO()
sgpp::optimization::IterativeGridGeneratorSOO::IterativeGridGeneratorSOO (base::ScalarFunction & f, base::Grid & grid, size_t N, double adaptivity = DEFAULT_ADAPTIVITY)
Constructor.
Do not destruct the grid before this object!
Parameters
f objective function
grid grid (should be empty)
N maximal number of grid points
adaptivity adaptivity (positive number)
References setAdaptivity().
~IterativeGridGeneratorSOO()
sgpp::optimization::IterativeGridGeneratorSOO::~IterativeGridGeneratorSOO () override
Destructor.
Member Function Documentation
generate()
bool sgpp::optimization::IterativeGridGeneratorSOO::generate () override virtual
Generate the grid.
Returns
true on success, otherwise false
Implements sgpp::optimization::IterativeGridGenerator.
References sgpp::base::ScalarFunction::eval(), sgpp::optimization::IterativeGridGenerator::evalFunction(), sgpp::optimization::IterativeGridGenerator::f, sgpp::base::HashRefinement::free_refine(), sgpp::optimization::IterativeGridGenerator::functionValues, sgpp::base::Printer::getInstance(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::ScalarFunction::getNumberOfParameters(), sgpp::base::Grid::getStorage(), sgpp::optimization::IterativeGridGenerator::grid, hMax, sgpp::optimization::IterativeGridGenerator::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::HashGridPoint::set(), and sgpp::optimization::IterativeGridGenerator::undoRefinement().
getAdaptivity()
IterativeGridGeneratorSOO::AdaptivityFunction sgpp::optimization::IterativeGridGeneratorSOO::getAdaptivity () const
References hMax.
setAdaptivity() [1/2]
void sgpp::optimization::IterativeGridGeneratorSOO::setAdaptivity (IterativeGridGeneratorSOO::AdaptivityFunction adaptivity)
References hMax.
setAdaptivity() [2/2]
void sgpp::optimization::IterativeGridGeneratorSOO::setAdaptivity (double adaptivity)
References hMax.
Referenced by IterativeGridGeneratorSOO().
Member Data Documentation
DEFAULT_ADAPTIVITY
constexpr double sgpp::optimization::IterativeGridGeneratorSOO::DEFAULT_ADAPTIVITY = 0.5 static constexpr
default adaptivity
hMax
AdaptivityFunction sgpp::optimization::IterativeGridGeneratorSOO::hMax protected
adaptivity
Referenced by generate(), getAdaptivity(), setAdaptivity(), and setAdaptivity().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorSOO.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorSOO.cpp