SG++-Doxygen-Documentation: sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
B-spline basis on Clenshaw-Curtis grids.
#include <BsplineModifiedClenshawCurtisBasis.hpp>
Public Member Functions
BsplineModifiedClenshawCurtisBasis ()
Default constructor.
BsplineModifiedClenshawCurtisBasis (size_t degree)
Constructor.
double clenshawCurtisPoint (LT l, IT i) const
double clenshawCurtisPointNegativeIndex (LT l, IT ni) const
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
double getIntegral (LT l, IT i) override
~BsplineModifiedClenshawCurtisBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Member Functions
double clenshawCurtisPoint (LT l, IT i, IT hInv) const
double clenshawCurtisPointNegativeIndex (LT l, IT ni, IT hInv) const
void constructKnots (LT l, IT i, IT hInv)
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
void constructKnotsNegativeIndex (LT l, IT ni, IT hInv)
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
double modifiedBSpline (LT l, IT hInv, double x, size_t p)
double modifiedBSplineDx (LT l, IT hInv, double x, size_t p)
double modifiedBSplineDxDx (LT l, IT hInv, double x, size_t p)
double nonUniformBSpline (double x, size_t p, size_t k) const
double nonUniformBSplineDx (double x, size_t p, size_t k) const
double nonUniformBSplineDxDx (double x, size_t p, size_t k) const
Protected Attributes
ClenshawCurtisTable & clenshawCurtisTable
reference to the Clenshaw-Curtis cache table
DataVector coordinates
size_t degree
degree of the B-spline
bool integrationInitialized = false
DataVector weights
std::vector< double > xi
temporary helper vector of fixed size p+2 containing B-spline knots
omp_nest_lock_t xiLock
Detailed Description
template<class LT, class IT>
class sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >
B-spline basis on Clenshaw-Curtis grids.
Constructor & Destructor Documentation
BsplineModifiedClenshawCurtisBasis() [1/2]
template<class LT , class IT > sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::BsplineModifiedClenshawCurtisBasis () inline
Default constructor.
BsplineModifiedClenshawCurtisBasis() [2/2]
template<class LT , class IT > sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::BsplineModifiedClenshawCurtisBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
~BsplineModifiedClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::~BsplineModifiedClenshawCurtisBasis () inline override
Destructor.
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
Member Function Documentation
clenshawCurtisPoint() [1/2]
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint (LT l, IT i) const inline
Parameters
l level of the grid point
i index of the grid point
Returns
i-th Clenshaw-Curtis grid point with level l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint().
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), and sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult().
clenshawCurtisPoint() [2/2]
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint (LT l, IT i, IT hInv) const inline protected
Parameters
l level of the grid point
i index of the grid point
hInv 2^l
Returns
i-th Clenshaw-Curtis grid point with level l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, and sgpp::base::ClenshawCurtisTable::getPoint().
clenshawCurtisPointNegativeIndex() [1/2]
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex (LT l, IT ni) const inline
Parameters
l level of the grid point
ni neagtive index -i of the grid point
Returns
(-ni)-th Clenshaw-Curtis grid point with level l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex().
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex().
clenshawCurtisPointNegativeIndex() [2/2]
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex (LT l, IT ni, IT hInv) const inline protected
Parameters
l level of the grid point
ni negative index -i of the grid point
hInv 2^l
Returns
(-ni)-th Clenshaw-Curtis grid point with level l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, and sgpp::base::ClenshawCurtisTable::getPoint().
constructKnots()
template<class LT , class IT > void sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots (LT l, IT i, IT hInv) inline protected
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
Parameters
l level of basis function
i index of basis function
hInv 2^l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx().
constructKnotsNegativeIndex()
template<class LT , class IT > void sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex (LT l, IT ni, IT hInv) inline protected
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
Parameters
l level of basis function
ni negative index -i of basis function
hInv 2^l
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx().
eval()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of modified Clenshaw-Curtis B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), and sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of modified Clenshaw-Curtis B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
Referenced by sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), and sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult().
evalDxDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of modified Clenshaw-Curtis B-spline basis function
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
Referenced by sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), and sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree.
getIntegral()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
value of the integral
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::coordinates, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), h, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::integrationInitialized, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::weights, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock.
Referenced by sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature().
modifiedBSpline()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline (LT l, IT hInv, double x, size_t p) inline protected
Parameters
l level of basis function
hInv 2^l
x evaluation point
p B-spline degree
Returns
value of modified Clenshaw-Curtis B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline().
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval().
modifiedBSplineDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx (LT l, IT hInv, double x, size_t p) inline protected
Parameters
l level of basis function
hInv 2^l
x evaluation point
p B-spline degree
Returns
value of derivative of modified Clenshaw-Curtis B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx().
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx().
modifiedBSplineDxDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx (LT l, IT hInv, double x, size_t p) inline protected
Parameters
l level of basis function
hInv 2^l
x evaluation point
p B-spline degree
Returns
value of 2nd derivative of modified Clenshaw-Curtis B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx().
nonUniformBSpline()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline (double x, size_t p, size_t k) const inline protected
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
nonUniformBSplineDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx (double x, size_t p, size_t k) const inline protected
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of derivative of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx().
nonUniformBSplineDxDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx (double x, size_t p, size_t k) const inline protected
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of 2nd derivative of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx().
Member Data Documentation
clenshawCurtisTable
template<class LT , class IT > ClenshawCurtisTable& sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable protected
reference to the Clenshaw-Curtis cache table
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisPointNegativeIndex().
coordinates
template<class LT , class IT > DataVector sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::coordinates protected
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
degree
template<class LT , class IT > size_t sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::degree protected
degree of the B-spline
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::BsplineModifiedClenshawCurtisBasis(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getDegree(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::modifiedBSplineDxDx().
integrationInitialized
template<class LT , class IT > bool sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::integrationInitialized = false protected
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
weights
template<class LT , class IT > DataVector sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::weights protected
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
xi
template<class LT , class IT > std::vector<double> sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xi protected
temporary helper vector of fixed size p+2 containing B-spline knots
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::constructKnotsNegativeIndex(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
xiLock
template<class LT , class IT > omp_nest_lock_t sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::xiLock protected
Referenced by sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::BsplineModifiedClenshawCurtisBasis(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::getIntegral(), and sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::~BsplineModifiedClenshawCurtisBasis().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/BsplineModifiedClenshawCurtisBasis.hpp