SG++-Doxygen-Documentation: sgpp::optimization::optimizer::AugmentedLagrangian Class Reference
sgpp::optimization::optimizer::AugmentedLagrangian Class Reference
Augmented Lagrangian method for constrained optimization.
#include <AugmentedLagrangian.hpp>
Public Member Functions
AugmentedLagrangian (const AugmentedLagrangian &other)
Copy constructor.
AugmentedLagrangian (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, const base::VectorFunction &g, const base::VectorFunctionGradient &gGradient, const base::VectorFunction &h, const base::VectorFunctionGradient &hGradient, size_t maxItCount=DEFAULT_N, double xTolerance=DEFAULT_X_TOLERANCE, double constraintTolerance=DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue=DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor=DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with adaptive gradient descent as optimization algorithm (gradient-based).
AugmentedLagrangian (const base::ScalarFunction &f, const base::VectorFunction &g, const base::VectorFunction &h, size_t maxItCount=DEFAULT_N, double xTolerance=DEFAULT_X_TOLERANCE, double constraintTolerance=DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue=DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor=DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with Nelder-Mead as optimization algorithm (gradient-free).
AugmentedLagrangian (const UnconstrainedOptimizer &unconstrainedOptimizer, const base::VectorFunction &g, const base::VectorFunctionGradient *gGradient, const base::VectorFunction &h, const base::VectorFunctionGradient *hGradient, size_t maxItCount=DEFAULT_N, double xTolerance=DEFAULT_X_TOLERANCE, double constraintTolerance=DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue=DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor=DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with custom unconstrained optimization algorithm (gradient-free or gradient-based).
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
base::DataVector findFeasiblePoint () const
Try to find a feasible initial point by solving an auxiliary problem.
double getConstraintTolerance () const
const std::vector< size_t > & getHistoryOfInnerIterationNumbers () const
const base::DataMatrix & getHistoryOfInnerIterationPoints () const
double getPenaltyIncreaseFactor () const
double getPenaltyStartValue () const
double getXTolerance () const
void optimize () override
Pure virtual method for optimization of the objective function.
void setConstraintTolerance (double constraintTolerance)
void setPenaltyIncreaseFactor (double penaltyIncreaseFactor)
void setPenaltyStartValue (double penaltyStartValue)
void setXTolerance (double xTolerance)
~AugmentedLagrangian () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::ConstrainedOptimizer
ConstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, const base::VectorFunction &g, const base::VectorFunctionGradient &gGradient, const base::VectorFunction &h, const base::VectorFunctionGradient &hGradient, size_t N=DEFAULT_N)
Constructor.
ConstrainedOptimizer (const base::ScalarFunction &f, const base::VectorFunction &g, const base::VectorFunction &h, size_t N=DEFAULT_N)
Constructor.
ConstrainedOptimizer (const ConstrainedOptimizer &other)
Copy constructor.
ConstrainedOptimizer (const UnconstrainedOptimizer &unconstrainedOptimizer, const base::VectorFunction &g, const base::VectorFunctionGradient *gGradient, const base::VectorFunction &h, const base::VectorFunctionGradient *hGradient, size_t N=DEFAULT_N)
Constructor with custom unconstrained optimization algorithm (gradient-free or gradient-based).
base::VectorFunction & getEqualityConstraintFunction () const
base::VectorFunctionGradient * getEqualityConstraintGradient () const
base::VectorFunction & getInequalityConstraintFunction () const
base::VectorFunctionGradient * getInequalityConstraintGradient () const
void setEqualityConstraintFunction (const base::VectorFunction &h)
void setEqualityConstraintGradient (const base::VectorFunctionGradient *hGradient)
void setInequalityConstraintFunction (const base::VectorFunction &g)
void setInequalityConstraintGradient (const base::VectorFunctionGradient *gGradient)
~ConstrainedOptimizer () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_CONSTRAINT_TOLERANCE = 1e-6
default constraint tolerance
static constexpr double DEFAULT_PENALTY_INCREASE_FACTOR = 1.5
default penalty increase factor
static constexpr double DEFAULT_PENALTY_START_VALUE = 1.0
default penalty start value
static constexpr double DEFAULT_X_TOLERANCE = 1e-6
default point tolerance
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double epsilon
constraint tolerance
std::vector< size_t > kHistInner
search history (number of inner iterations)
double mu0
penalty start value
double rhoMuPlus
penalty increase factor
double theta
point tolerance
base::DataMatrix xHistInner
search history (inner iterations)
Protected Attributes inherited from sgpp::optimization::optimizer::ConstrainedOptimizer
std::unique_ptr< base::VectorFunction > g
inequality constraint function
std::unique_ptr< base::VectorFunctionGradient > gGradient
inequality constraint function gradient
std::unique_ptr< base::VectorFunction > h
equality constraint function
std::unique_ptr< base::VectorFunctionGradient > hGradient
equality constraint function gradient
std::unique_ptr< UnconstrainedOptimizer > unconstrainedOptimizer
unconstrained optimization algorithm
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Augmented Lagrangian method for constrained optimization.
Constructor & Destructor Documentation
AugmentedLagrangian() [1/4]
sgpp::optimization::optimizer::AugmentedLagrangian::AugmentedLagrangian (const base::ScalarFunction & f, const base::VectorFunction & g, const base::VectorFunction & h, size_t maxItCount = DEFAULT_N, double xTolerance = DEFAULT_X_TOLERANCE, double constraintTolerance = DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue = DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor = DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with Nelder-Mead as optimization algorithm (gradient-free).
Parameters
f objective function
g inequality constraint
h equality constraint
maxItCount maximal number of function evaluations
xTolerance point tolerance
constraintTolerance constraint tolerance
penaltyStartValue penalty start value
penaltyIncreaseFactor penalty increase factor
AugmentedLagrangian() [2/4]
sgpp::optimization::optimizer::AugmentedLagrangian::AugmentedLagrangian (const base::ScalarFunction & f, const base::ScalarFunctionGradient & fGradient, const base::VectorFunction & g, const base::VectorFunctionGradient & gGradient, const base::VectorFunction & h, const base::VectorFunctionGradient & hGradient, size_t maxItCount = DEFAULT_N, double xTolerance = DEFAULT_X_TOLERANCE, double constraintTolerance = DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue = DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor = DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with adaptive gradient descent as optimization algorithm (gradient-based).
Parameters
f objective function
fGradient objective function gradient
g inequality constraint
gGradient inequality constraint gradient
h equality constraint
hGradient equality constraint gradient
maxItCount maximal number of function evaluations
xTolerance point tolerance
constraintTolerance constraint tolerance
penaltyStartValue penalty start value
penaltyIncreaseFactor penalty increase factor
References theta, and sgpp::optimization::optimizer::ConstrainedOptimizer::unconstrainedOptimizer.
AugmentedLagrangian() [3/4]
sgpp::optimization::optimizer::AugmentedLagrangian::AugmentedLagrangian (const UnconstrainedOptimizer & unconstrainedOptimizer, const base::VectorFunction & g, const base::VectorFunctionGradient * gGradient, const base::VectorFunction & h, const base::VectorFunctionGradient * hGradient, size_t maxItCount = DEFAULT_N, double xTolerance = DEFAULT_X_TOLERANCE, double constraintTolerance = DEFAULT_CONSTRAINT_TOLERANCE, double penaltyStartValue = DEFAULT_PENALTY_START_VALUE, double penaltyIncreaseFactor = DEFAULT_PENALTY_INCREASE_FACTOR)
Constructor with custom unconstrained optimization algorithm (gradient-free or gradient-based).
Parameters
unconstrainedOptimizer unconstrained optimization algorithm
g inequality constraint
gGradient inequality constraint gradient (nullptr to omit)
h equality constraint
hGradient equality constraint gradient (nullptr to omit)
maxItCount maximal number of function evaluations
xTolerance point tolerance
constraintTolerance constraint tolerance
penaltyStartValue penalty start value
penaltyIncreaseFactor penalty increase factor
AugmentedLagrangian() [4/4]
sgpp::optimization::optimizer::AugmentedLagrangian::AugmentedLagrangian (const AugmentedLagrangian & other)
Copy constructor.
Parameters
other optimizer to be copied
~AugmentedLagrangian()
sgpp::optimization::optimizer::AugmentedLagrangian::~AugmentedLagrangian () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::AugmentedLagrangian::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
findFeasiblePoint()
base::DataVector sgpp::optimization::optimizer::AugmentedLagrangian::findFeasiblePoint () const
Try to find a feasible initial point by solving an auxiliary problem.
However, it is not guaranteed that the method works, i.e., it should be checked afterwards that the returned point is actually feasible.
Returns
feasible point in \([0, 1]^d\)
References sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::ConstrainedOptimizer::g, sgpp::base::EmptyVectorFunction::getInstance(), sgpp::base::EmptyVectorFunctionGradient::getInstance(), sgpp::optimization::optimizer::ConstrainedOptimizer::gGradient, sgpp::optimization::optimizer::ConstrainedOptimizer::h, sgpp::optimization::optimizer::ConstrainedOptimizer::hGradient, sgpp::base::DataVector::max(), sgpp::base::DataVector::maxNorm(), mG, mH, sMax, and sMin.
getConstraintTolerance()
double sgpp::optimization::optimizer::AugmentedLagrangian::getConstraintTolerance () const
Returns
constraint tolerance
References epsilon.
getHistoryOfInnerIterationNumbers()
const std::vector< size_t > & sgpp::optimization::optimizer::AugmentedLagrangian::getHistoryOfInnerIterationNumbers () const
Returns
vector in which the k-th entry indicates the number of inner iterations in the k-th (outer) iteration, empty vector on error
References kHistInner.
getHistoryOfInnerIterationPoints()
const base::DataMatrix & sgpp::optimization::optimizer::AugmentedLagrangian::getHistoryOfInnerIterationPoints () const
Returns
tall matrix (d columns) in which the history of optimal points of the iterations are concatenated
References xHistInner.
getPenaltyIncreaseFactor()
double sgpp::optimization::optimizer::AugmentedLagrangian::getPenaltyIncreaseFactor () const
Returns
penalty increase factor
References rhoMuPlus.
getPenaltyStartValue()
double sgpp::optimization::optimizer::AugmentedLagrangian::getPenaltyStartValue () const
Returns
penalty start value
References mu0.
getXTolerance()
double sgpp::optimization::optimizer::AugmentedLagrangian::getXTolerance () const
Returns
point tolerance
References theta.
optimize()
void sgpp::optimization::optimizer::AugmentedLagrangian::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), epsilon, sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::optimization::optimizer::ConstrainedOptimizer::g, sgpp::base::Printer::getInstance(), sgpp::base::DataMatrix::getNrows(), sgpp::optimization::optimizer::ConstrainedOptimizer::gGradient, sgpp::optimization::optimizer::ConstrainedOptimizer::h, sgpp::optimization::optimizer::ConstrainedOptimizer::hGradient, kHistInner, sgpp::base::DataVector::l2Norm(), lambda, sgpp::base::DataVector::max(), sgpp::base::DataVector::maxNorm(), mG, mH, mu, mu0, sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), rhoMuPlus, sgpp::base::DataVector::sub(), theta, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::ConstrainedOptimizer::unconstrainedOptimizer, sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, xHistInner, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setConstraintTolerance()
void sgpp::optimization::optimizer::AugmentedLagrangian::setConstraintTolerance (double constraintTolerance)
Parameters
constraintTolerance constraint tolerance
References epsilon.
setPenaltyIncreaseFactor()
void sgpp::optimization::optimizer::AugmentedLagrangian::setPenaltyIncreaseFactor (double penaltyIncreaseFactor)
Parameters
penaltyIncreaseFactor penalty increase factor
References rhoMuPlus.
setPenaltyStartValue()
void sgpp::optimization::optimizer::AugmentedLagrangian::setPenaltyStartValue (double penaltyStartValue)
Parameters
penaltyStartValue penalty start value
References mu0.
setXTolerance()
void sgpp::optimization::optimizer::AugmentedLagrangian::setXTolerance (double xTolerance)
Parameters
xTolerance point tolerance
References theta.
Member Data Documentation
DEFAULT_CONSTRAINT_TOLERANCE
constexpr double sgpp::optimization::optimizer::AugmentedLagrangian::DEFAULT_CONSTRAINT_TOLERANCE = 1e-6 static constexpr
default constraint tolerance
DEFAULT_PENALTY_INCREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AugmentedLagrangian::DEFAULT_PENALTY_INCREASE_FACTOR = 1.5 static constexpr
default penalty increase factor
DEFAULT_PENALTY_START_VALUE
constexpr double sgpp::optimization::optimizer::AugmentedLagrangian::DEFAULT_PENALTY_START_VALUE = 1.0 static constexpr
default penalty start value
DEFAULT_X_TOLERANCE
constexpr double sgpp::optimization::optimizer::AugmentedLagrangian::DEFAULT_X_TOLERANCE = 1e-6 static constexpr
default point tolerance
epsilon
double sgpp::optimization::optimizer::AugmentedLagrangian::epsilon protected
constraint tolerance
Referenced by getConstraintTolerance(), optimize(), and setConstraintTolerance().
kHistInner
std::vector<size_t> sgpp::optimization::optimizer::AugmentedLagrangian::kHistInner protected
search history (number of inner iterations)
Referenced by getHistoryOfInnerIterationNumbers(), and optimize().
mu0
double sgpp::optimization::optimizer::AugmentedLagrangian::mu0 protected
penalty start value
Referenced by getPenaltyStartValue(), optimize(), and setPenaltyStartValue().
rhoMuPlus
double sgpp::optimization::optimizer::AugmentedLagrangian::rhoMuPlus protected
penalty increase factor
Referenced by getPenaltyIncreaseFactor(), optimize(), and setPenaltyIncreaseFactor().
theta
double sgpp::optimization::optimizer::AugmentedLagrangian::theta protected
point tolerance
Referenced by AugmentedLagrangian(), getXTolerance(), optimize(), and setXTolerance().
xHistInner
base::DataMatrix sgpp::optimization::optimizer::AugmentedLagrangian::xHistInner protected
search history (inner iterations)
Referenced by getHistoryOfInnerIterationPoints(), and optimize().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/constrained/AugmentedLagrangian.hpp
optimization/src/sgpp/optimization/optimizer/constrained/AugmentedLagrangian.cpp