SG++-Doxygen-Documentation: sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive Class Reference
sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive Class Reference
Operation for evaluating weakly fundamental spline linear combinations on Boundary grids, their gradients and their Hessians.
#include <OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive.hpp>
Public Member Functions
void evalHessian (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient, std::vector< DataMatrix > &hessian) override
double evalHessian (const DataVector &alpha, const DataVector &point, DataVector &gradient, DataMatrix &hessian) override
OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalHessian
OperationEvalHessian ()
Constructor.
virtual ~OperationEvalHessian ()
Destructor.
Protected Attributes
SWeaklyFundamentalSplineBase base
1D spline basis
SWeaklyFundamentalSplineBaseDeriv1 baseDeriv1
1D spline basis derivative
SWeaklyFundamentalSplineBaseDeriv2 baseDeriv2
1D spline basis 2nd derivative
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalHessian
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating weakly fundamental spline linear combinations on Boundary grids, their gradients and their Hessians.
Constructor & Destructor Documentation
OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive()
sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive()
sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::~OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive () inline override
Destructor.
Member Function Documentation
evalHessian() [1/2]
void sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient, std::vector< DataMatrix > & hessian) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
[out] hessian vector of Hessians of the linear combination
Reimplemented from sgpp::base::OperationEvalHessian.
References alpha, base, baseDeriv1, baseDeriv2, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >::eval(), sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalHessian() [2/2]
double sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian (const DataVector & alpha, const DataVector & point, DataVector & gradient, DataMatrix & hessian) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient vector of the linear combination
[out] hessian Hessian matrix of the linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalHessian.
References sgpp::base::DataMatrix::add(), sgpp::base::DataVector::add(), alpha, base, baseDeriv1, baseDeriv2, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalSplineBasisDeriv1< LT, IT >::eval(), sgpp::base::WeaklyFundamentalSplineBasisDeriv2< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SWeaklyFundamentalSplineBase sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::base protected
1D spline basis
Referenced by evalHessian(), and evalHessian().
baseDeriv1
SWeaklyFundamentalSplineBaseDeriv1 sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::baseDeriv1 protected
1D spline basis derivative
Referenced by evalHessian(), and evalHessian().
baseDeriv2
SWeaklyFundamentalSplineBaseDeriv2 sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::baseDeriv2 protected
1D spline basis 2nd derivative
Referenced by evalHessian(), and evalHessian().
innerDerivative
DataVector sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalHessian(), and evalHessian().
pointInUnitCube
DataVector sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalHessian(), and evalHessian().
storage
GridStorage& sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::storage protected
storage of the sparse grid
Referenced by evalHessian(), and evalHessian().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive.cpp