SG++-Doxygen-Documentation: sgpp::datadriven::KDEMaximumLikelihoodCrossValidation Class Reference
sgpp::datadriven::KDEMaximumLikelihoodCrossValidation Class Reference
#include <KernelDensityEstimator.hpp>
Public Member Functions
virtual void clone (std::unique_ptr< sgpp::base::ScalarFunction > &clone) const
double eval (const sgpp::base::DataVector &x)
Pure virtual method for calculating \(f(\vec{x})\).
KDEMaximumLikelihoodCrossValidation (KernelDensityEstimator &kde, size_t kfold=10, std::uint64_t seedValue=std::mt19937_64::default_seed)
Constructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Constructor & Destructor Documentation
KDEMaximumLikelihoodCrossValidation()
sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::KDEMaximumLikelihoodCrossValidation (KernelDensityEstimator & kde, size_t kfold = 10, std::uint64_t seedValue = std::mt19937_64::default_seed) explicit
Constructor.
References sgpp::datadriven::KernelDensityEstimator::getSamples().
Member Function Documentation
clone()
virtual void sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::clone (std::unique_ptr< sgpp::base::ScalarFunction > & clone) const inline virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone().
Referenced by clone().
eval()
double sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::eval (const sgpp::base::DataVector & x) virtual
Pure virtual method for calculating \(f(\vec{x})\).
Parameters
x evaluation point \(\vec{x} \in [0, 1]^d\)
Returns
\(f(\vec{x})\)
Implements sgpp::base::ScalarFunction.
References sgpp::datadriven::DensityEstimator::crossEntropy(), sgpp::datadriven::KernelDensityEstimator::getKernel(), sgpp::datadriven::Kernel::getType(), sgpp::datadriven::NONE, and sgpp::datadriven::KernelDensityEstimator::setBandwidths().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp