SG++-Doxygen-Documentation: sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS > Class Template Reference
sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS > Class Template Reference
Abstract implementation for distributed multiple function evaluations.
#include <AlgorithmMultipleEvaluationDistributed.hpp>
Public Member Functions
void mult (sgpp::base::GridStorage &storage, BASIS &basis, sgpp::base::DataVector &source, DataMatrix &x, DataVectorDistributed &result)
Performs a distributed mass evaluation.
void mult_transpose (sgpp::base::GridStorage &storage, BASIS &basis, sgpp::base::DataVector &source, DataMatrix &x, DataVectorDistributed &result)
Performs a distributed transposed mass evaluation.
Detailed Description
template<class BASIS>
class sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >
Abstract implementation for distributed multiple function evaluations.
Based on AlgorithmMultipleEvaluation.hpp
In Data Mining to operators are needed: mass evaluation and transposed evaluation, referenced in literature as matrix vector products with matrices B^T (mass evaluation) and B (transposed evaluation).
If there are \(N\) basis functions \(\varphi(\vec{x})\) and \(m\) data points, then B is a (mxN) matrix, with
\[ (B)_{j,i} = \varphi_i(x_j). \]
Member Function Documentation
mult()
template<class BASIS > void sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult (sgpp::base::GridStorage & storage, BASIS & basis, sgpp::base::DataVector & source, DataMatrix & x, DataVectorDistributed & result) inline
Performs a distributed mass evaluation.
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::datadriven::DataVectorDistributed::getLocalPointer(), sgpp::datadriven::DataVectorDistributed::getLocalRows(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getRow(), sgpp::datadriven::DataVectorDistributed::isProcessMapped(), and sgpp::datadriven::DataVectorDistributed::localToGlobalRowIndex().
Referenced by sgpp::datadriven::OperationMultipleEvalLinearDistributed::multDistributed(), and sgpp::datadriven::OperationMultipleEvalModLinearDistributed::multDistributed().
mult_transpose()
template<class BASIS > void sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult_transpose (sgpp::base::GridStorage & storage, BASIS & basis, sgpp::base::DataVector & source, DataMatrix & x, DataVectorDistributed & result) inline
Performs a distributed transposed mass evaluation.
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::datadriven::DataVectorDistributed::add(), sgpp::datadriven::DataVectorDistributed::distribute(), sgpp::datadriven::DataVectorDistributed::getBlockSize(), sgpp::datadriven::DataVectorDistributed::getGlobalRows(), sgpp::base::DataMatrix::getNcols(), sgpp::datadriven::DataVectorDistributed::getProcessGrid(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), sgpp::datadriven::DataVectorDistributed::isProcessMapped(), and sgpp::datadriven::DataVectorDistributed::setAll().
Referenced by sgpp::datadriven::OperationMultipleEvalLinearDistributed::multTransposeDistributed(), and sgpp::datadriven::OperationMultipleEvalModLinearDistributed::multTransposeDistributed().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/algorithm/AlgorithmMultipleEvaluationDistributed.hpp