SG++-Doxygen-Documentation: sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT > Class Template Reference
sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT > Class Template Reference
Linear basis on Clenshaw-Curtis grids.
#include <LinearClenshawCurtisBoundaryBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double eval (LT level, IT index, double p, double offset, double width)
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
LinearClenshawCurtisBoundaryBasis ()
~LinearClenshawCurtisBoundaryBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
SLinearClenshawCurtisBase basis
linear clenshaw curtis basis
Detailed Description
template<class LT, class IT>
class sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >
Linear basis on Clenshaw-Curtis grids.
Constructor & Destructor Documentation
LinearClenshawCurtisBoundaryBasis()
template<class LT , class IT > sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::LinearClenshawCurtisBoundaryBasis () inline
~LinearClenshawCurtisBoundaryBasis()
template<class LT , class IT > sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::~LinearClenshawCurtisBoundaryBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of Clenshaw-Curtis linear basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::basis, and sgpp::base::LinearClenshawCurtisBasis< LT, IT >::eval().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), and sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB().
eval() [2/2]
template<class LT , class IT > double sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::eval (LT level, IT index, double p, double offset, double width) inline
References sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::eval(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
getIntegral()
template<class LT , class IT > double sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::basis, sgpp::base::LinearClenshawCurtisBasis< LT, IT >::getIntegral(), and level.
Referenced by sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature().
Member Data Documentation
basis
template<class LT , class IT > SLinearClenshawCurtisBase sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::basis protected
linear clenshaw curtis basis
Referenced by sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::eval(), and sgpp::base::LinearClenshawCurtisBoundaryBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/LinearClenshawCurtisBoundaryBasis.hpp