SG++-Doxygen-Documentation: sgpp::datadriven::DMWeightMatrix Class Reference
sgpp::datadriven::DMWeightMatrix Class Reference
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix with weight.
#include <DMWeightMatrix.hpp>
Public Member Functions
DMWeightMatrix (sgpp::base::Grid &SparseGrid, sgpp::base::DataMatrix &trainData, sgpp::base::OperationMatrix &C, double lambda, sgpp::base::DataVector &w)
Std-Constructor.
void generateb (sgpp::base::DataVector &classes, sgpp::base::DataVector &b)
Generates the right hand side of the classification equation.
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
virtual ~DMWeightMatrix ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix with weight.
Constructor & Destructor Documentation
DMWeightMatrix()
sgpp::datadriven::DMWeightMatrix::DMWeightMatrix (sgpp::base::Grid & SparseGrid, sgpp::base::DataMatrix & trainData, sgpp::base::OperationMatrix & C, double lambda, sgpp::base::DataVector & w)
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
trainData reference to sgpp::base::DataVector that contains the training data
C the regression functional
lambda the lambda, the regression parameter
w the weights to the training data
References sgpp::op_factory::createOperationMultipleEval(), and lambda.
~DMWeightMatrix()
sgpp::datadriven::DMWeightMatrix::~DMWeightMatrix () virtual
Std-Destructor.
Member Function Documentation
generateb()
void sgpp::datadriven::DMWeightMatrix::generateb (sgpp::base::DataVector & classes, sgpp::base::DataVector & b)
Generates the right hand side of the classification equation.
Parameters
classes the class information of the training data
b reference to the vector that will contain the result of the matrix vector multiplication on the rhs
References sgpp::base::DataVector::componentwise_mult(), and sgpp::base::OperationMultipleEval::multTranspose().
Referenced by sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver().
mult()
void sgpp::datadriven::DMWeightMatrix::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVector::componentwise_mult(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMatrix::mult(), sgpp::base::OperationMultipleEval::mult(), and sgpp::base::OperationMultipleEval::multTranspose().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DMWeightMatrix.hpp
datadriven/src/sgpp/datadriven/algorithm/DMWeightMatrix.cpp