SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensitySampling1D Class Reference
sgpp::datadriven::OperationDensitySampling1D Class Reference abstract
Sample 1D Probability Density Function.
#include <OperationDensitySampling1D.hpp>
Public Member Functions
virtual void doSampling1D (base::DataVector *alpha, size_t num_samples, base::DataVector *&samples, unsigned int *seedp)=0
Sampling on 1D grid.
OperationDensitySampling1D ()
virtual ~OperationDensitySampling1D ()
Detailed Description
Sample 1D Probability Density Function.
Constructor & Destructor Documentation
OperationDensitySampling1D()
sgpp::datadriven::OperationDensitySampling1D::OperationDensitySampling1D () inline
~OperationDensitySampling1D()
virtual sgpp::datadriven::OperationDensitySampling1D::~OperationDensitySampling1D () inline virtual
Member Function Documentation
doSampling1D()
virtual void sgpp::datadriven::OperationDensitySampling1D::doSampling1D (base::DataVector * alpha, size_t num_samples, base::DataVector *& samples, unsigned int * seedp) pure virtual
Sampling on 1D grid.
Parameters
alpha Coefficient vector for current grid (1D grid)
num_samples # of samples to draw
samples Output DataVector
seedp seed
Implemented in sgpp::datadriven::OperationDensitySampling1DLinear.
Referenced by sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), and sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensitySampling1D.hpp