SG++-Doxygen-Documentation: sgpp::combigrid::OperationEvalFullGrid Class Reference
sgpp::combigrid::OperationEvalFullGrid Class Reference
Operation for evaluating a full grid function (linear combination of full grid basis functions).
#include <OperationEvalFullGrid.hpp>
Public Member Functions
double eval (const base::DataVector &surpluses, const base::DataVector &point) override
Evaluate a full grid function at one point.
const FullGrid & getGrid () const
virtual void multiEval (const base::DataVector &surpluses, const base::DataMatrix &points, base::DataVector &result)
Evaluate a full grid function at multiple points.
OperationEvalFullGrid ()
Default constructor.
OperationEvalFullGrid (const FullGrid &grid)
Constructor.
void setGrid (const FullGrid &grid)
~OperationEvalFullGrid () override
Virtual destructor.
Public Member Functions inherited from sgpp::base::OperationEval
virtual void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value)
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
FullGrid grid
full grid
Detailed Description
Operation for evaluating a full grid function (linear combination of full grid basis functions).
Constructor & Destructor Documentation
OperationEvalFullGrid() [1/2]
sgpp::combigrid::OperationEvalFullGrid::OperationEvalFullGrid ()
Default constructor.
OperationEvalFullGrid() [2/2]
sgpp::combigrid::OperationEvalFullGrid::OperationEvalFullGrid (const FullGrid & grid) explicit
Constructor.
Parameters
grid full grid
~OperationEvalFullGrid()
sgpp::combigrid::OperationEvalFullGrid::~OperationEvalFullGrid () override
Virtual destructor.
Member Function Documentation
eval()
double sgpp::combigrid::OperationEvalFullGrid::eval (const base::DataVector & surpluses, const base::DataVector & point) override virtual
Evaluate a full grid function at one point.
Parameters
surpluses coefficients for the full grid basis functions (may be nodal/hierarchical)
point point at which to evaluate the full grid function
Returns
value of the full grid function at the given point
Implements sgpp::base::OperationEval.
References sgpp::combigrid::HeterogeneousBasis::eval(), sgpp::combigrid::FullGrid::getBasis(), sgpp::combigrid::FullGrid::getLevel(), grid, and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), and sgpp::combigrid::OperationEvalCombinationGrid::eval().
getGrid()
const FullGrid & sgpp::combigrid::OperationEvalFullGrid::getGrid () const
Returns
full grid
References grid.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
multiEval()
void sgpp::combigrid::OperationEvalFullGrid::multiEval (const base::DataVector & surpluses, const base::DataMatrix & points, base::DataVector & result) virtual
Evaluate a full grid function at multiple points.
Parameters
[in] surpluses coefficients for the full grid basis functions (may be nodal/hierarchical)
[in] points points at which to evaluate the full grid function (every row corresponds to one point)
[out] result values of the full grid function at the given points
References sgpp::combigrid::HeterogeneousBasis::eval(), sgpp::combigrid::FullGrid::getBasis(), sgpp::combigrid::FullGrid::getLevel(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid, level, and sgpp::base::DataVector::setAll().
Referenced by sgpp::combigrid::OperationEvalCombinationGrid::multiEval().
setGrid()
void sgpp::combigrid::OperationEvalFullGrid::setGrid (const FullGrid & grid)
Parameters
grid full grid
References grid.
Referenced by sgpp::combigrid::OperationEvalCombinationGrid::eval(), sgpp::combigrid::OperationEvalCombinationGrid::multiEval(), and python.controller.CheckpointController.CheckpointController::setLearner().
Member Data Documentation
grid
FullGrid sgpp::combigrid::OperationEvalFullGrid::grid protected
full grid
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), eval(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), multiEval(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), setGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
The documentation for this class was generated from the following files:
combigrid/src/sgpp/combigrid/operation/OperationEvalFullGrid.hpp
combigrid/src/sgpp/combigrid/operation/OperationEvalFullGrid.cpp