SG++-Doxygen-Documentation: sgpp::base::CoarseningFunctorTypeParser Class Reference
sgpp::base::CoarseningFunctorTypeParser Class Reference
#include <CoarseningFunctorTypeParser.hpp>
Static Public Member Functions
static CoarseningFunctorType parse (const std::string &input)
Convert strings to values sgpp::base::CoarseningFunctorType.
static const std::string & toString (CoarseningFunctorType type)
generate string representations for values of sgpp::base::CoarseningFunctorType.
Member Function Documentation
parse()
CoarseningFunctorType sgpp::base::CoarseningFunctorTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::base::CoarseningFunctorType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::base::CoarseningFunctorType.
Returns
the corresponding sgpp::base::CoarseningFunctorType.
References sgpp::base::Classification, sgpp::base::Surplus, and sgpp::base::SurplusVolume.
Referenced by sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig().
toString()
const std::string & sgpp::base::CoarseningFunctorTypeParser::toString (CoarseningFunctorType type) static
generate string representations for values of sgpp::base::CoarseningFunctorType.
Parameters
type enum value.
Returns
string representation of a sgpp::base::CoarseningFunctorType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DMConfigTools::dumpToStream(), sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/CoarseningFunctorTypeParser.hpp
base/src/sgpp/base/grid/CoarseningFunctorTypeParser.cpp