SG++-Doxygen-Documentation: sgpp::optimization::test_problems::G11EqualityConstraint Class Reference
sgpp::optimization::test_problems::G11EqualityConstraint Class Reference
G11 equality constraint function.
#include <G11.hpp>
Public Member Functions
void clone (std::unique_ptr< base::VectorFunction > &clone) const override
void evalUndisplaced (const base::DataVector &x, base::DataVector &value) override
G11EqualityConstraint ()
Constructor.
~G11EqualityConstraint () override
Destructor.
Public Member Functions inherited from sgpp::optimization::test_problems::TestVectorFunction
void eval (const base::DataVector &x, base::DataVector &value) override
Evaluate displaced function.
const base::DataVector & getDisplacement () const
void setDisplacement (const base::DataVector &displacement)
TestVectorFunction (size_t d, size_t m)
Constructor.
~TestVectorFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::VectorFunction
virtual void eval (const DataMatrix &x, DataMatrix &value)
Convenience method for calculating \(g(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfComponents () const
size_t getNumberOfParameters () const
VectorFunction (size_t d, size_t m)
Constructor.
virtual ~VectorFunction ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::optimization::test_problems::TestVectorFunction
base::DataVector displacement
displacement vector
base::DataVector xTmp
temporary vector for displacing
Protected Attributes inherited from sgpp::base::VectorFunction
size_t d
dimension of the domain
size_t m
number of components
Detailed Description
G11 equality constraint function.
Definition:
\[\bar{h}(\bar{\vec{x}}) := \bar{x}_2 - \bar{x}_1^2\]
Constructor & Destructor Documentation
G11EqualityConstraint()
sgpp::optimization::test_problems::G11EqualityConstraint::G11EqualityConstraint ()
Constructor.
Referenced by clone().
~G11EqualityConstraint()
sgpp::optimization::test_problems::G11EqualityConstraint::~G11EqualityConstraint () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::test_problems::G11EqualityConstraint::clone (std::unique_ptr< base::VectorFunction > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::VectorFunction.
References clone(), and G11EqualityConstraint().
Referenced by clone().
evalUndisplaced()
void sgpp::optimization::test_problems::G11EqualityConstraint::evalUndisplaced (const base::DataVector & x, base::DataVector & value) override virtual
Parameters
x point \(\vec{x} \in \mathbb{R}^d\)
[out] value \(\vec{f}(\vec{x})\)
Implements sgpp::optimization::test_problems::TestVectorFunction.
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/constrained/G11.hpp
optimization/src/sgpp/optimization/test_problems/constrained/G11.cpp