SG++-Doxygen-Documentation: sgpp::datadriven::DMConfigTools Class Reference
sgpp::datadriven::DMConfigTools Class Reference
#include <DMConfigTools.hpp>
Static Public Member Functions
static void dumpToStream (const base::AdaptivityConfiguration &adaptivityConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const base::CombiGridConfiguration &gridConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const base::GeneralGridConfiguration &gridConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const base::RegularGridConfiguration &gridConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const CrossvalidationConfiguration &crossvalidationConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const DatabaseConfiguration &databaseConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const DensityEstimationConfiguration &densityEstimationConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const LearnerConfiguration &learnerConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const ParallelConfiguration &parallelConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const RegularizationConfiguration &regularizationConfig, std::ostream &stream_out=std::cout)
static void dumpToStream (const solver::SLESolverConfiguration &solverConfig, std::ostream &stream_out=std::cout)
Member Function Documentation
dumpToStream() [1/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const base::AdaptivityConfiguration & adaptivityConfig, std::ostream & stream_out = std::cout) inline static
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::coarseningFunctorType_, sgpp::base::AdaptivityConfiguration::coarseningThreshold_, sgpp::base::AdaptivityConfiguration::coarsenInitialPoints_, sgpp::base::AdaptivityConfiguration::errorBasedRefinement_, sgpp::base::AdaptivityConfiguration::errorBufferSize_, sgpp::base::AdaptivityConfiguration::errorConvergenceThreshold_, sgpp::base::AdaptivityConfiguration::errorMinInterval_, sgpp::base::AdaptivityConfiguration::levelPenalize_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numCoarseningPoints_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::precomputeEvaluations_, sgpp::base::AdaptivityConfiguration::refinementFunctorType_, sgpp::base::AdaptivityConfiguration::refinementPeriod_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::AdaptivityConfiguration::scalingCoefficients_, sgpp::base::AdaptivityConfiguration::thresholdType_, sgpp::base::AdaptivityThresholdTypeParser::toString(), sgpp::base::CoarseningFunctorTypeParser::toString(), and sgpp::base::RefinementFunctorTypeParser::toString().
dumpToStream() [2/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const base::CombiGridConfiguration & gridConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::base::GeneralGridConfiguration::generalType_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::CombiGridConfiguration::levels, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::GeneralGridConfiguration::t_, sgpp::base::GridTypeParser::toString(), sgpp::base::GeneralGridTypeParser::toString(), and sgpp::base::GeneralGridConfiguration::type_.
dumpToStream() [3/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const base::GeneralGridConfiguration & gridConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::base::GeneralGridConfiguration::generalType_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::GeneralGridConfiguration::t_, sgpp::base::GridTypeParser::toString(), sgpp::base::GeneralGridTypeParser::toString(), and sgpp::base::GeneralGridConfiguration::type_.
Referenced by sgpp::datadriven::FitterConfiguration::dumpToStream().
dumpToStream() [4/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const base::RegularGridConfiguration & gridConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::base::GeneralGridConfiguration::generalType_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::GeneralGridConfiguration::t_, sgpp::base::GridTypeParser::toString(), sgpp::base::GeneralGridTypeParser::toString(), and sgpp::base::GeneralGridConfiguration::type_.
dumpToStream() [5/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const CrossvalidationConfiguration & crossvalidationConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::CrossvalidationConfiguration::enable_, sgpp::datadriven::CrossvalidationConfiguration::kfold_, sgpp::datadriven::CrossvalidationConfiguration::lambda_, sgpp::datadriven::CrossvalidationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationConfiguration::lambdaSteps_, sgpp::datadriven::CrossvalidationConfiguration::logScale_, sgpp::datadriven::CrossvalidationConfiguration::seed_, sgpp::datadriven::CrossvalidationConfiguration::shuffle_, and sgpp::datadriven::CrossvalidationConfiguration::silent_.
dumpToStream() [6/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const DatabaseConfiguration & databaseConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::DatabaseConfiguration::filePath_.
dumpToStream() [7/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const DensityEstimationConfiguration & densityEstimationConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsDecompose_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsRefine_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsSolver_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsUpdateLambda_, sgpp::datadriven::DensityEstimationConfiguration::normalize_, sgpp::datadriven::DensityEstimationTypeParser::toString(), sgpp::datadriven::MatrixDecompositionTypeParser::toString(), sgpp::datadriven::DensityEstimationConfiguration::type_, and sgpp::datadriven::DensityEstimationConfiguration::useOfflinePermutation_.
dumpToStream() [8/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const LearnerConfiguration & learnerConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::LearnerConfiguration::learningRate_, and sgpp::datadriven::LearnerConfiguration::usePrior_.
dumpToStream() [9/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const ParallelConfiguration & parallelConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::ParallelConfiguration::columnBlockSize_, sgpp::datadriven::ParallelConfiguration::processCols_, sgpp::datadriven::ParallelConfiguration::processRows_, sgpp::datadriven::ParallelConfiguration::rowBlockSize_, and sgpp::datadriven::ParallelConfiguration::scalapackEnabled_.
dumpToStream() [10/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const RegularizationConfiguration & regularizationConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::datadriven::RegularizationConfiguration::convergenceThreshold_, sgpp::datadriven::RegularizationConfiguration::exponentBase_, sgpp::datadriven::RegularizationConfiguration::intervalA_, sgpp::datadriven::RegularizationConfiguration::intervalB_, sgpp::datadriven::RegularizationConfiguration::l1Ratio_, sgpp::datadriven::RegularizationConfiguration::lambda_, sgpp::datadriven::RegularizationConfiguration::lambda_end_, sgpp::datadriven::RegularizationConfiguration::lambda_log_scale_, sgpp::datadriven::RegularizationConfiguration::lambda_steps_, sgpp::datadriven::RegularizationConfiguration::lamda_start_, sgpp::datadriven::RegularizationConfiguration::optimizeLambda_, sgpp::datadriven::RegularizationConfiguration::optimizerTolerance_, sgpp::datadriven::RegularizationTypeParser::toString(), and sgpp::datadriven::RegularizationConfiguration::type_.
dumpToStream() [11/11]
static void sgpp::datadriven::DMConfigTools::dumpToStream (const solver::SLESolverConfiguration & solverConfig, std::ostream & stream_out = std::cout) inline static
References sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::solver::SLESolverConfiguration::threshold_, sgpp::solver::SLESolverTypeParser::toString(), sgpp::solver::SLESolverConfiguration::type_, and sgpp::solver::SLESolverConfiguration::verbose_.
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/tools/DMConfigTools.hpp