SG++-Doxygen-Documentation: sgpp::base::OperationWeightedQuadratureNakBsplineExtended Class Reference
sgpp::base::OperationWeightedQuadratureNakBsplineExtended Class Reference
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
#include <OperationWeightedQuadratureNakBsplineExtended.hpp>
Public Member Functions
double doWeightedQuadrature (DataVector &alpha, sgpp::base::DistributionsVector pdfs) override
Quadrature for not a knot B-spline basis functions w.r.t.
OperationWeightedQuadratureNakBsplineExtended (GridStorage &storage, size_t degree, size_t quadOrder)
Constructor of OperationQuadratureNakBsplineExtended.
~OperationWeightedQuadratureNakBsplineExtended () override
Public Member Functions inherited from sgpp::base::OperationWeightedQuadrature
OperationWeightedQuadrature ()
Constructor.
virtual ~OperationWeightedQuadrature ()
Destructor.
Protected Attributes
SNakBsplineExtendedBase base
basis object
std::shared_ptr< base::DataVector > quadCoordinates
quadrature rule coordinates
size_t quadOrder
quadrature rule order
std::shared_ptr< base::DataVector > quadWeights
quadrature rule weights
GridStorage & storage
Detailed Description
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
Constructor & Destructor Documentation
OperationWeightedQuadratureNakBsplineExtended()
sgpp::base::OperationWeightedQuadratureNakBsplineExtended::OperationWeightedQuadratureNakBsplineExtended (GridStorage & storage, size_t degree, size_t quadOrder) inline
Constructor of OperationQuadratureNakBsplineExtended.
Parameters
storage Pointer to the grid's GridStorage object
degree the B-spline degree
quadOrder quadrature order
References sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), quadCoordinates, quadOrder, and quadWeights.
~OperationWeightedQuadratureNakBsplineExtended()
sgpp::base::OperationWeightedQuadratureNakBsplineExtended::~OperationWeightedQuadratureNakBsplineExtended () inline override
Member Function Documentation
doWeightedQuadrature()
double sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature (DataVector & alpha, sgpp::base::DistributionsVector pdfs) override virtual
Quadrature for not a knot B-spline basis functions w.r.t.
a probability density function
Parameters
alpha Coefficient vector for current grid
pdfs probability density functions
Implements sgpp::base::OperationWeightedQuadrature.
References alpha, base, sgpp::base::DistributionsVector::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::NakBsplineExtendedBasis< LT, IT >::getMean(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getSize(), quadCoordinates, quadWeights, and storage.
Member Data Documentation
base
SNakBsplineExtendedBase sgpp::base::OperationWeightedQuadratureNakBsplineExtended::base protected
basis object
Referenced by doWeightedQuadrature().
quadCoordinates
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBsplineExtended::quadCoordinates protected
quadrature rule coordinates
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBsplineExtended().
quadOrder
size_t sgpp::base::OperationWeightedQuadratureNakBsplineExtended::quadOrder protected
quadrature rule order
Referenced by OperationWeightedQuadratureNakBsplineExtended().
quadWeights
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBsplineExtended::quadWeights protected
quadrature rule weights
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBsplineExtended().
storage
GridStorage& sgpp::base::OperationWeightedQuadratureNakBsplineExtended::storage protected
Referenced by doWeightedQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBsplineExtended.hpp
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBsplineExtended.cpp