SG++-Doxygen-Documentation: sgpp::datadriven::DBMatPermutationFactory Class Reference
sgpp::datadriven::DBMatPermutationFactory Class Reference
#include <DBMatPermutationFactory.hpp>
Public Member Functions
DBMatPermutationFactory ()
DBMatPermutationFactory (std::shared_ptr< DBMatObjectStore > store)
DBMatPermutationFactory (std::shared_ptr< DBMatObjectStore > store, const std::string &dbFilePath)
DBMatOfflinePermutable * getPermutedObject (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig)
Returns a offline object matching the specified configuration.
Protected Attributes
std::string dbFilePath
bool hasDataBase
std::shared_ptr< DBMatObjectStore > store
Constructor & Destructor Documentation
DBMatPermutationFactory() [1/3]
sgpp::datadriven::DBMatPermutationFactory::DBMatPermutationFactory ()
DBMatPermutationFactory() [2/3]
sgpp::datadriven::DBMatPermutationFactory::DBMatPermutationFactory (std::shared_ptr< DBMatObjectStore > store) explicit
DBMatPermutationFactory() [3/3]
sgpp::datadriven::DBMatPermutationFactory::DBMatPermutationFactory (std::shared_ptr< DBMatObjectStore > store, const std::string & dbFilePath) explicit
Member Function Documentation
getPermutedObject()
DBMatOfflinePermutable * sgpp::datadriven::DBMatPermutationFactory::getPermutedObject (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig)
Returns a offline object matching the specified configuration.
If the store contains a suitable base object, the permutation and blow-up approach is applied on a copy of the base object, which is then returned. If no suitable base object exists in the store, the factory builds a suitable object from scratch and stores it. If a database file is given, the database is searched for a base object, which is then again stored.
Parameters
gridConfig The desired grid configuration.
geometryConfig The desired geometry configuration.
adaptivityConfig The desired adaptivity configuration.
regularizationConfig The desired regularization configuration.
densityEstimationConfig The desired desnity estimation configuration.
Returns
A offline object that matches the configuration.
References adaptivityConfig, sgpp::datadriven::DBMatOfflineFactory::buildFromFile(), sgpp::datadriven::DBMatOffline::buildMatrix(), sgpp::datadriven::DBMatOfflineFactory::buildOfflineObject(), sgpp::datadriven::DBMatOffline::clone(), sgpp::datadriven::GridFactory::createGrid(), dbFilePath, sgpp::datadriven::DBMatOffline::decomposeMatrix(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), sgpp::datadriven::GridFactory::getInteractions(), sgpp::datadriven::PermutationUtil::getNormalizedConfig(), grid(), sgpp::datadriven::DBMatDatabase::hasBaseDataMatrix(), hasDataBase, sgpp::datadriven::DBMatOfflinePermutable::permuteDecomposition(), sgpp::datadriven::GeometryConfiguration::stencils_, and store.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit().
Member Data Documentation
dbFilePath
std::string sgpp::datadriven::DBMatPermutationFactory::dbFilePath protected
Referenced by getPermutedObject().
hasDataBase
bool sgpp::datadriven::DBMatPermutationFactory::hasDataBase protected
Referenced by getPermutedObject().
store
std::shared_ptr<DBMatObjectStore> sgpp::datadriven::DBMatPermutationFactory::store protected
Referenced by getPermutedObject().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatPermutationFactory.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatPermutationFactory.cpp