SG++-Doxygen-Documentation: sgpp::base::BsplineClenshawCurtisBasis< LT, IT > Class Template Reference
sgpp::base::BsplineClenshawCurtisBasis< LT, IT > Class Template Reference
B-spline basis on Clenshaw-Curtis grids.
#include <BsplineClenshawCurtisBasis.hpp>
Public Member Functions
BsplineClenshawCurtisBasis ()
Default constructor.
BsplineClenshawCurtisBasis (size_t degree)
Constructor.
double clenshawCurtisPoint (LT l, IT i) const
void constructKnots (LT l, IT i)
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
double getIntegral (LT l, IT i) override
double nonUniformBSpline (double x, size_t p, size_t k) const
double nonUniformBSplineDx (double x, size_t p, size_t k) const
double nonUniformBSplineDxDx (double x, size_t p, size_t k) const
~BsplineClenshawCurtisBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis for B-spline evaluation.
ClenshawCurtisTable & clenshawCurtisTable
reference to the Clenshaw-Curtis cache table
DataVector coordinates
bool integrationInitialized = false
DataVector weights
std::vector< double > xi
temporary helper vector of fixed size p+2 containing B-spline knots
Detailed Description
template<class LT, class IT>
class sgpp::base::BsplineClenshawCurtisBasis< LT, IT >
B-spline basis on Clenshaw-Curtis grids.
Constructor & Destructor Documentation
BsplineClenshawCurtisBasis() [1/2]
template<class LT , class IT > sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::BsplineClenshawCurtisBasis () inline
Default constructor.
BsplineClenshawCurtisBasis() [2/2]
template<class LT , class IT > sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::BsplineClenshawCurtisBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
~BsplineClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::~BsplineClenshawCurtisBasis () inline override
Destructor.
Member Function Documentation
clenshawCurtisPoint()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint (LT l, IT i) const inline
Parameters
l level of the grid point
i index of the grid point
Returns
i-th Clenshaw-Curtis grid point with level l
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, and sgpp::base::ClenshawCurtisTable::getPoint().
Referenced by sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), and sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult().
constructKnots()
template<class LT , class IT > void sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots (LT l, IT i) inline
Construct the (p+2) Clenshaw-Curtis knots of a B-spline basis function and save them in xi.
Parameters
l level of basis function
i index of basis function
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::ClenshawCurtisTable::getPoint(), h, and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral().
eval()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of Clenshaw-Curtis B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), and sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of Clenshaw-Curtis B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx().
Referenced by sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), and sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult().
evalDxDx()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of Clenshaw-Curtis B-spline basis function
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
Referenced by sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), and sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
integral of the basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::coordinates, sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), h, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::integrationInitialized, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::weights, and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature().
nonUniformBSpline()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline (double x, size_t p, size_t k) const inline
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
nonUniformBSplineDx()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx (double x, size_t p, size_t k) const inline
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of derivative of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx().
nonUniformBSplineDxDx()
template<class LT , class IT > double sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx (double x, size_t p, size_t k) const inline
Parameters
x evaluation point
p B-spline degree
k index of B-spline in the knot sequence
Returns
value of 2nd derivative of non-uniform B-spline with knots \(\{\xi_k, ... \xi_{k+p+1}\}\)
References sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::bsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getDegree(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral().
clenshawCurtisTable
template<class LT , class IT > ClenshawCurtisTable& sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisTable protected
reference to the Clenshaw-Curtis cache table
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::clenshawCurtisPoint(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots().
coordinates
template<class LT , class IT > DataVector sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::coordinates protected
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral().
integrationInitialized
template<class LT , class IT > bool sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::integrationInitialized = false protected
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral().
weights
template<class LT , class IT > DataVector sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::weights protected
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral().
xi
template<class LT , class IT > std::vector<double> sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::xi protected
temporary helper vector of fixed size p+2 containing B-spline knots
Referenced by sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::constructKnots(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSpline(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDx(), and sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::nonUniformBSplineDxDx().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/BsplineClenshawCurtisBasis.hpp