SG++-Doxygen-Documentation: sgpp::datadriven::RefinementMonitor Class Reference
sgpp::datadriven::RefinementMonitor Class Reference abstract
Superclass for refinement monitors.
#include <RefinementMonitor.hpp>
Public Member Functions
virtual void pushToBuffer (size_t numberInstances, double currentValidError, double currentTrainError)=0
Stores the current error values in the buffer.
virtual size_t refinementsNecessary ()=0
Checks if the model needs to be refined.
virtual ~RefinementMonitor ()=default
Destructor.
Detailed Description
Superclass for refinement monitors.
They track whether a refinement should happen or not.
Constructor & Destructor Documentation
~RefinementMonitor()
virtual sgpp::datadriven::RefinementMonitor::~RefinementMonitor () virtual default
Destructor.
Member Function Documentation
pushToBuffer()
virtual void sgpp::datadriven::RefinementMonitor::pushToBuffer (size_t numberInstances, double currentValidError, double currentTrainError) pure virtual
Stores the current error values in the buffer.
If the buffer has reached the maximum size, the oldest values are removed.
Parameters
numberInstances the number of instances added
currentValidError The current validation error
currentTrainError The current training error
Implemented in sgpp::datadriven::RefinementMonitorConvergence, and sgpp::datadriven::RefinementMonitorPeriodic.
Referenced by sgpp::datadriven::RefinementHandler::checkRefinementNecessary(), sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), and sgpp::datadriven::LearnerSGDE::trainOnline().
refinementsNecessary()
virtual size_t sgpp::datadriven::RefinementMonitor::refinementsNecessary () pure virtual
Checks if the model needs to be refined.
Returns
the number of refinements that are triggered by the monitor
Implemented in sgpp::datadriven::RefinementMonitorConvergence, and sgpp::datadriven::RefinementMonitorPeriodic.
Referenced by sgpp::datadriven::RefinementHandler::checkRefinementNecessary(), sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), and sgpp::datadriven::LearnerSGDE::trainOnline().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/algorithm/RefinementMonitor.hpp