SG++-Doxygen-Documentation: sgpp::optimization::IterativeGridGeneratorLinearSurplus Class Reference
sgpp::optimization::IterativeGridGeneratorLinearSurplus Class Reference
Iterative grid generation based on linear surplusses.
#include <IterativeGridGeneratorLinearSurplus.hpp>
Public Member Functions
bool generate () override
Generate the grid.
double getAdaptivity () const
base::level_t getInitialLevel () const
IterativeGridGeneratorLinearSurplus (base::ScalarFunction &f, base::Grid &grid, size_t N, double adaptivity=DEFAULT_ADAPTIVITY, base::level_t initialLevel=DEFAULT_INITIAL_LEVEL)
Constructor.
void setAdaptivity (double adaptivity)
void setInitialLevel (base::level_t initialLevel)
~IterativeGridGeneratorLinearSurplus () override
Destructor.
Public Member Functions inherited from sgpp::optimization::IterativeGridGenerator
const base::DataVector & getFunctionValues () const
base::Grid & getGrid () const
IterativeGridGenerator (base::ScalarFunction &f, base::Grid &grid, size_t N)
Constructor.
void printIterativeGridGenerator () const
Prints grid points and function values.
virtual ~IterativeGridGenerator ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_ADAPTIVITY = 0.2
default adaptivity
static const base::level_t DEFAULT_INITIAL_LEVEL = 3
default level of initial regular sparse grid
Protected Attributes
double gamma
adaptivity
base::level_t initialLevel
level of initial regular sparse grid
std::unique_ptr< base::Grid > linearGrid
pointer to a linear grid (of the same type as the "real" grid)
Protected Attributes inherited from sgpp::optimization::IterativeGridGenerator
base::ScalarFunction & f
objective function
base::DataVector functionValues
vector of function values at the grid points
base::Grid & grid
underlying grid
size_t N
maximal number of grid points
Additional Inherited Members
Protected Member Functions inherited from sgpp::optimization::IterativeGridGenerator
void evalFunction (size_t oldGridSize=0)
Evaluates the objective function at grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] and saves values in functionValues.
void undoRefinement (size_t oldGridSize)
Removes grid points with indices [oldGridSize, oldGridSize + 1, ..., grid.getSize() - 1] from the grid.
Detailed Description
Iterative grid generation based on linear surplusses.
In each iteration, the fraction of \(gamma\) (e.g. \(\gamma = 0.2\) means 20%) of the grid points with the largest hierarchical linear surplusses are refined.
Constructor & Destructor Documentation
IterativeGridGeneratorLinearSurplus()
sgpp::optimization::IterativeGridGeneratorLinearSurplus::IterativeGridGeneratorLinearSurplus (base::ScalarFunction & f, base::Grid & grid, size_t N, double adaptivity = DEFAULT_ADAPTIVITY, base::level_t initialLevel = DEFAULT_INITIAL_LEVEL)
Constructor.
Do not destruct the grid before this object!
Parameters
f objective function
grid grid (should be empty)
N maximal number of grid points
adaptivity adaptivity between 0 and 1
initialLevel level of initial regular sparse grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::optimization::IterativeGridGenerator::f, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::ScalarFunction::getNumberOfParameters(), sgpp::base::Grid::getType(), sgpp::optimization::IterativeGridGenerator::grid, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, linearGrid, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModNakBspline, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NaturalBsplineBoundary, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
~IterativeGridGeneratorLinearSurplus()
sgpp::optimization::IterativeGridGeneratorLinearSurplus::~IterativeGridGeneratorLinearSurplus () override
Destructor.
Member Function Documentation
generate()
bool sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate () override virtual
Generate the grid.
Returns
true on success, otherwise false
Implements sgpp::optimization::IterativeGridGenerator.
References sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::Printer::disableStatusPrinting(), sgpp::base::Printer::enableStatusPrinting(), sgpp::optimization::IterativeGridGenerator::evalFunction(), sgpp::optimization::IterativeGridGenerator::functionValues, gamma, sgpp::base::Grid::getGenerator(), sgpp::base::Printer::getInstance(), sgpp::base::HierarchisationSLE::getMatrixEntry(), sgpp::base::DataVector::getPointer(), sgpp::base::Grid::getStorage(), sgpp::base::Grid::getType(), sgpp::optimization::IterativeGridGenerator::grid, initialLevel, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtisBoundary, linearGrid, sgpp::optimization::IterativeGridGenerator::N, sgpp::base::NakBsplineBoundary, sgpp::base::NaturalBsplineBoundary, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::setAll(), sgpp::base::sle_solver::BiCGStab::solve(), sgpp::optimization::IterativeGridGenerator::undoRefinement(), sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
getAdaptivity()
double sgpp::optimization::IterativeGridGeneratorLinearSurplus::getAdaptivity () const
Returns
adaptivity between 0 and 1
References gamma.
getInitialLevel()
base::level_t sgpp::optimization::IterativeGridGeneratorLinearSurplus::getInitialLevel () const
Returns
level of initial regular sparse grid
References initialLevel.
setAdaptivity()
void sgpp::optimization::IterativeGridGeneratorLinearSurplus::setAdaptivity (double adaptivity)
Parameters
adaptivity adaptivity between 0 and 1
References gamma.
setInitialLevel()
void sgpp::optimization::IterativeGridGeneratorLinearSurplus::setInitialLevel (base::level_t initialLevel)
Parameters
initialLevel level of initial regular sparse grid
References initialLevel.
Member Data Documentation
DEFAULT_ADAPTIVITY
constexpr double sgpp::optimization::IterativeGridGeneratorLinearSurplus::DEFAULT_ADAPTIVITY = 0.2 static constexpr
default adaptivity
DEFAULT_INITIAL_LEVEL
const base::level_t sgpp::optimization::IterativeGridGeneratorLinearSurplus::DEFAULT_INITIAL_LEVEL = 3 static
default level of initial regular sparse grid
gamma
double sgpp::optimization::IterativeGridGeneratorLinearSurplus::gamma protected
adaptivity
Referenced by generate(), getAdaptivity(), and setAdaptivity().
initialLevel
base::level_t sgpp::optimization::IterativeGridGeneratorLinearSurplus::initialLevel protected
level of initial regular sparse grid
Referenced by generate(), getInitialLevel(), and setInitialLevel().
linearGrid
std::unique_ptr<base::Grid> sgpp::optimization::IterativeGridGeneratorLinearSurplus::linearGrid protected
pointer to a linear grid (of the same type as the "real" grid)
Referenced by generate(), and IterativeGridGeneratorLinearSurplus().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorLinearSurplus.hpp
optimization/src/sgpp/optimization/gridgen/IterativeGridGeneratorLinearSurplus.cpp