SG++-Doxygen-Documentation: sgpp::base::GridTypeParser Class Reference
sgpp::base::GridTypeParser Class Reference
#include <GridTypeParser.hpp>
Static Public Member Functions
static GridType parse (const std::string &input)
Convert strings to values sgpp::base::GridType.
static const std::string & toString (GridType type)
generate string representations for values of sgpp::base::GridType.
Member Function Documentation
parse()
GridType sgpp::base::GridTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::base::GridType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::base::GridType.
Returns
the corresponding sgpp::base::GridType.
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearStencil, sgpp::base::ModPoly, sgpp::base::ModWavelet, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::Prewavelet, sgpp::base::SquareRoot, sgpp::base::Wavelet, and sgpp::base::WaveletBoundary.
Referenced by sgpp::datadriven::DataMiningConfigParser::getFitterGridConfig(), and sgpp::datadriven::DataMiningConfigParser::getHyperparameters().
toString()
const std::string & sgpp::base::GridTypeParser::toString (GridType type) static
generate string representations for values of sgpp::base::GridType.
Parameters
type enum value.
Returns
string representation of a sgpp::base::GridType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DMConfigTools::dumpToStream(), sgpp::datadriven::DMConfigTools::dumpToStream(), sgpp::datadriven::DMConfigTools::dumpToStream(), sgpp::datadriven::DataMiningConfigParser::getFitterGridConfig(), sgpp::datadriven::FitterFactory::printConfig(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/GridTypeParser.hpp
base/src/sgpp/base/grid/GridTypeParser.cpp