SG++-Doxygen-Documentation: sgpp::datadriven::HarmonicaHyperparameterOptimizer Class Reference
sgpp::datadriven::HarmonicaHyperparameterOptimizer Class Reference
HarmonicaHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
#include <HarmonicaHyperparameterOptimizer.hpp>
Public Member Functions
HarmonicaHyperparameterOptimizer (const HarmonicaHyperparameterOptimizer &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
HarmonicaHyperparameterOptimizer (HarmonicaHyperparameterOptimizer &&rhs)=default
Default Move constructor .
HarmonicaHyperparameterOptimizer (SparseGridMiner *miner, FitterFactory *fitterFactory, DataMiningConfigParser &parser)
Constructor.
HarmonicaHyperparameterOptimizer & operator= (const HarmonicaHyperparameterOptimizer &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
HarmonicaHyperparameterOptimizer & operator= (HarmonicaHyperparameterOptimizer &&rhs)=default
Default Move assign operator.
double run (bool writeToFile) override
Run hyperparameter optimization using Harmonica.
~HarmonicaHyperparameterOptimizer () override=default
Default destructor.
Public Member Functions inherited from sgpp::datadriven::HyperparameterOptimizer
HyperparameterOptimizer (const HyperparameterOptimizer &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
HyperparameterOptimizer (HyperparameterOptimizer &&rhs)=default
Default Move constructor .
HyperparameterOptimizer (SparseGridMiner *miner, FitterFactory *fitterFactory, DataMiningConfigParser &parser)
Constructor.
HyperparameterOptimizer & operator= (const HyperparameterOptimizer &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
HyperparameterOptimizer & operator= (HyperparameterOptimizer &&rhs)=default
Default Move assign operator.
virtual ~HyperparameterOptimizer ()=default
Default destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::HyperparameterOptimizer
HPOConfig config
Configuration for all hpo details.
std::unique_ptr< FitterFactory > fitterFactory
FitterFactory to provide fitters for running different hyperparameter configurations.
std::unique_ptr< SparseGridMiner > miner
Miner providing all testing facilities.
Detailed Description
HarmonicaHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
It offers access to different hyperparameter optimization procedures.
Constructor & Destructor Documentation
HarmonicaHyperparameterOptimizer() [1/3]
sgpp::datadriven::HarmonicaHyperparameterOptimizer::HarmonicaHyperparameterOptimizer (SparseGridMiner * miner, FitterFactory * fitterFactory, DataMiningConfigParser & parser)
Constructor.
Parameters
miner configured instance of SGMiner object, that will provide the learning process. The HyperparameterOptimizer instance will take ownership of the passed object.
fitterFactory configured instance of factory object that provides fitters with manipulated hyperparameters. The HarmonicaHyperparameterOptimizer instance will take ownership of the passed object.
parser reference to parser object to read configuration info
HarmonicaHyperparameterOptimizer() [2/3]
sgpp::datadriven::HarmonicaHyperparameterOptimizer::HarmonicaHyperparameterOptimizer (const HarmonicaHyperparameterOptimizer & rhs) delete
Copy constructor deleted - not all members can be copied or cloned .
Parameters
rhs the object to copy from
HarmonicaHyperparameterOptimizer() [3/3]
sgpp::datadriven::HarmonicaHyperparameterOptimizer::HarmonicaHyperparameterOptimizer (HarmonicaHyperparameterOptimizer && rhs) default
Default Move constructor .
Parameters
rhs the object to move from
~HarmonicaHyperparameterOptimizer()
sgpp::datadriven::HarmonicaHyperparameterOptimizer::~HarmonicaHyperparameterOptimizer () override default
Default destructor.
Member Function Documentation
operator=() [1/2]
HarmonicaHyperparameterOptimizer & sgpp::datadriven::HarmonicaHyperparameterOptimizer::operator= (const HarmonicaHyperparameterOptimizer & rhs) delete
Default copy assign operator deleted because not all members can be copied.
Parameters
rhs the object to copy from
operator=() [2/2]
HarmonicaHyperparameterOptimizer & sgpp::datadriven::HarmonicaHyperparameterOptimizer::operator= (HarmonicaHyperparameterOptimizer && rhs) default
Default Move assign operator.
Parameters
rhs the object to move from
run()
double sgpp::datadriven::HarmonicaHyperparameterOptimizer::run (bool writeToFile) override virtual
Run hyperparameter optimization using Harmonica.
Implements sgpp::datadriven::HyperparameterOptimizer.
References sgpp::datadriven::HyperparameterOptimizer::config, sgpp::datadriven::HyperparameterOptimizer::fitterFactory, sgpp::datadriven::HPOConfig::getConstraints(), sgpp::datadriven::HPOConfig::getLambda(), sgpp::datadriven::HPOConfig::getSeed(), sgpp::datadriven::HPOConfig::getStages(), and sgpp::datadriven::HyperparameterOptimizer::miner.
Referenced by python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/hpo/HarmonicaHyperparameterOptimizer.hpp
datadriven/src/sgpp/datadriven/datamining/modules/hpo/HarmonicaHyperparameterOptimizer.cpp