SG++-Doxygen-Documentation: sgpp::base::ImpurityRefinementIndicator Class Reference
sgpp::base::ImpurityRefinementIndicator Class Reference
A refinement indicator for classification problems based on impurity measures (e.g.
#include <ImpurityRefinementIndicator.hpp>
Public Types
typedef GridPoint counter_key_type
typedef std::pair< size_t, double > value_type
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Public Member Functions
size_t getRefinementsNum () const override
Returns the maximal number of points that should be refined.
double getRefinementThreshold () const override
Returns the threshold for refinement.
ImpurityRefinementIndicator (Grid &grid, DataMatrix &dataset, DataVector *alphas, DataVector *w1, DataVector *w2, DataVector &classesComputed, double threshold=0.0, size_t refinementsNum=1)
Constructor.
virtual double operator() (GridPoint &point) const
This should be returning a refinement indicator for the specified grid point.
double operator() (GridStorage &storage, size_t seq) const override
This should be returning a refinement value for every grid point.
double start () const override
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
void update (GridPoint &point)
Update normal vector of SVM.
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
RefinementFunctor ()
Constructor.
virtual ~RefinementFunctor ()
Destructor.
Public Attributes
DataVector * alphas
DataVector * w1
DataVector * w2
Protected Attributes
DataVector & classesComputed
DataMatrix & dataset
size_t refinementsNum
double threshold
Detailed Description
A refinement indicator for classification problems based on impurity measures (e.g.
gini impurity, entropy impurity,...). It calculates local impurities based on the information from the provided data set. If the indicator is applied within the SVM learner, the normal vector needs to be extended after each refinement.
Member Typedef Documentation
counter_key_type
typedef GridPoint sgpp::base::ImpurityRefinementIndicator::counter_key_type
value_type
typedef std::pair<size_t, double> sgpp::base::ImpurityRefinementIndicator::value_type
Constructor & Destructor Documentation
ImpurityRefinementIndicator()
sgpp::base::ImpurityRefinementIndicator::ImpurityRefinementIndicator (Grid & grid, DataMatrix & dataset, DataVector * alphas, DataVector * w1, DataVector * w2, DataVector & classesComputed, double threshold = 0.0, size_t refinementsNum = 1)
Constructor.
Parameters
grid The grid to refine.
dataset The set of data points used to compute impurities
alphas The weights corresponding to the support vectors (only required for SVM learner)
w1 Normal vector (only required for SVM learner)
w2 Normal vector computed with abs values (only required for SVM learner)
classesComputed The predicted labels for the data points from dataset
threshold The refinement threshold; Only grid points with indicator values greater than this threshold will be refined
refinementsNum The max amount of grid points to be refined
Member Function Documentation
getRefinementsNum()
size_t sgpp::base::ImpurityRefinementIndicator::getRefinementsNum () const override virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
Number of points that should refined. Default value: 1.
Reimplemented from sgpp::base::RefinementFunctor.
References refinementsNum.
getRefinementThreshold()
double sgpp::base::ImpurityRefinementIndicator::getRefinementThreshold () const override virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion greater than this threshold will be refined.
Returns
Threshold value for refinement. Default value: 0.
Implements sgpp::base::RefinementFunctor.
References threshold.
Referenced by sgpp::base::ImpurityRefinement::getIndicator().
operator()() [1/2]
double sgpp::base::ImpurityRefinementIndicator::operator() (GridPoint & point) const virtual
This should be returning a refinement indicator for the specified grid point.
The point with the highest value will be refined first.
Parameters
point The grid point for which to calculate an indicator value
Returns
The indicator value
References classesComputed, dataset, sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNrows(), h, level, and sgpp::base::DataVector::set().
operator()() [2/2]
double sgpp::base::ImpurityRefinementIndicator::operator() (GridStorage & storage, size_t seq) const override virtual
This should be returning a refinement value for every grid point.
The point with the highest value will be refined first.
Parameters
storage Reference to the grids storage object
seq Sequence number in the coefficients array
Returns
refinement value
Implements sgpp::base::RefinementFunctor.
start()
double sgpp::base::ImpurityRefinementIndicator::start () const override virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implements sgpp::base::RefinementFunctor.
update()
void sgpp::base::ImpurityRefinementIndicator::update (GridPoint & point)
Update normal vector of SVM.
For each new grid point the normal vector has to be extended by one component. Only required for SVMLearner!
Parameters
point The new grid point
References alphas, sgpp::base::DataVector::append(), dataset, sgpp::base::Basis< LT, IT >::eval(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getBasis(), sgpp::base::DataMatrix::getNrows(), level, w1, and w2.
Referenced by python.uq.refinement.RefinementStrategy.Ranking::rank(), sgpp::base::ImpurityRefinement::refineGridpointsCollection(), and python.learner.LearnedKnowledge.LearnedKnowledge::setMemento().
Member Data Documentation
alphas
DataVector* sgpp::base::ImpurityRefinementIndicator::alphas
Referenced by sgpp::base::ImpurityRefinement::refineGridpointsCollection(), and update().
classesComputed
DataVector& sgpp::base::ImpurityRefinementIndicator::classesComputed protected
Referenced by operator()().
dataset
DataMatrix& sgpp::base::ImpurityRefinementIndicator::dataset protected
Referenced by operator()(), and update().
refinementsNum
size_t sgpp::base::ImpurityRefinementIndicator::refinementsNum protected
Referenced by getRefinementsNum().
threshold
double sgpp::base::ImpurityRefinementIndicator::threshold protected
Referenced by getRefinementThreshold().
w1
DataVector* sgpp::base::ImpurityRefinementIndicator::w1
Referenced by sgpp::base::ImpurityRefinement::refineGridpointsCollection(), and update().
w2
DataVector* sgpp::base::ImpurityRefinementIndicator::w2
Referenced by update().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/functors/ImpurityRefinementIndicator.hpp
base/src/sgpp/base/grid/generation/functors/ImpurityRefinementIndicator.cpp