SG++-Doxygen-Documentation: sgpp::datadriven::PolynomialChaosExpansion Class Reference
sgpp::datadriven::PolynomialChaosExpansion Class Reference
a PCE object providing different methods to calculate the PCE coefficients and evaluating the expansion
#include <PolynomialChaosExpansion.hpp>
Public Member Functions
double adaptiveQuadratureWeighted (const std::function< double(const base::DataVector &)> &funct, int dim, size_t n, size_t quadOrder)
base::DataVector calculateCoefficients (int n, bool use_adaptive)
void clearCoefficients ()
double evalExpansion (const base::DataVector &xi, int n, bool use_adaptive)
base::DataVector getCoefficients ()
double getL2Error (int n, bool use_adaptive)
double getMean (int n, bool use_adaptive)
double getVariance (int n, bool use_adaptive)
PolynomialChaosExpansion (std::function< double(const base::DataVector &)> func, int order, sgpp::base::DistributionsVector distributions)
double sparseGridQuadrature (const std::function< double(const base::DataVector &)> &funct, int dim, int n, size_t quadOrder)
~PolynomialChaosExpansion ()
Destructor.
Detailed Description
a PCE object providing different methods to calculate the PCE coefficients and evaluating the expansion
Constructor & Destructor Documentation
PolynomialChaosExpansion()
sgpp::datadriven::PolynomialChaosExpansion::PolynomialChaosExpansion (std::function< double(const base::DataVector &)> func, int order, sgpp::base::DistributionsVector distributions)
References sgpp::base::Beta, sgpp::datadriven::Beta, sgpp::datadriven::Exponential, f, sgpp::datadriven::Gamma, sgpp::base::DistributionsVector::get(), sgpp::base::DistributionsVector::getSize(), sgpp::base::Lognormal, sgpp::base::Normal, sgpp::datadriven::Normal, sgpp::base::DistributionsVector::push_back(), sgpp::base::TruncExponential, sgpp::base::TruncGamma, sgpp::base::TruncNormal, sgpp::base::Uniform, and sgpp::datadriven::Uniform.
~PolynomialChaosExpansion()
sgpp::datadriven::PolynomialChaosExpansion::~PolynomialChaosExpansion ()
Destructor.
Member Function Documentation
adaptiveQuadratureWeighted()
double sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted (const std::function< double(const base::DataVector &)> & funct, int dim, size_t n, size_t quadOrder)
Refine adaptively until number of points is reached.
References sgpp::base::DataVector::copyFrom(), sgpp::base::Grid::createNakBsplineExtendedGrid(), sgpp::op_factory::createOperationHierarchisation(), sgpp::op_factory::createOperationWeightedQuadrature(), sgpp::base::HashGridPoint::getStandardCoordinate(), grid(), and sgpp::base::sle_solver::Eigen::solve().
Referenced by calculateCoefficients().
calculateCoefficients()
base::DataVector sgpp::datadriven::PolynomialChaosExpansion::calculateCoefficients (int n, bool use_adaptive)
References adaptiveQuadratureWeighted(), and sparseGridQuadrature().
Referenced by evalExpansion(), getMean(), and getVariance().
clearCoefficients()
void sgpp::datadriven::PolynomialChaosExpansion::clearCoefficients ()
evalExpansion()
double sgpp::datadriven::PolynomialChaosExpansion::evalExpansion (const base::DataVector & xi, int n, bool use_adaptive)
References sgpp::base::Beta, calculateCoefficients(), sgpp::base::DistributionsVector::get(), sgpp::base::Lognormal, sgpp::base::Normal, sgpp::base::TruncExponential, sgpp::base::TruncGamma, sgpp::base::TruncNormal, and sgpp::base::Uniform.
Referenced by getL2Error().
getCoefficients()
base::DataVector sgpp::datadriven::PolynomialChaosExpansion::getCoefficients ()
getL2Error()
double sgpp::datadriven::PolynomialChaosExpansion::getL2Error (int n, bool use_adaptive)
References sgpp::base::Beta, evalExpansion(), sgpp::base::DistributionsVector::get(), sgpp::base::DataVector::getSize(), sgpp::base::Lognormal, sgpp::base::Normal, sgpp::base::DistributionsVector::sample(), sgpp::base::DataVector::sum(), sgpp::base::TruncExponential, sgpp::base::TruncGamma, sgpp::base::TruncNormal, and sgpp::base::Uniform.
getMean()
double sgpp::datadriven::PolynomialChaosExpansion::getMean (int n, bool use_adaptive)
References calculateCoefficients().
getVariance()
double sgpp::datadriven::PolynomialChaosExpansion::getVariance (int n, bool use_adaptive)
References calculateCoefficients(), sgpp::base::DataVector::copyFrom(), sgpp::base::DataVector::getSize(), sgpp::base::DataVector::set(), sgpp::base::DataVector::sqr(), and sgpp::base::DataVector::sum().
sparseGridQuadrature()
double sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature (const std::function< double(const base::DataVector &)> & funct, int dim, int n, size_t quadOrder)
References sgpp::base::Grid::createNakBsplineExtendedGrid(), sgpp::op_factory::createOperationHierarchisation(), sgpp::op_factory::createOperationWeightedQuadrature(), sgpp::base::DataVector::getSize(), sgpp::base::HashGridPoint::getStandardCoordinate(), grid(), and sgpp::base::sle_solver::Eigen::solve().
Referenced by calculateCoefficients().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/PolynomialChaosExpansion.hpp
datadriven/src/sgpp/datadriven/tools/PolynomialChaosExpansion.cpp