SG++-Doxygen-Documentation: sgpp::datadriven::AlgorithmAdaBoostBase Class Reference
sgpp::datadriven::AlgorithmAdaBoostBase Class Reference abstract
#include <AlgorithmAdaBoostBase.hpp>
Public Member Functions
AlgorithmAdaBoostBase (base::Grid &SparseGrid, base::GridType gridType, base::level_t gridLevel, base::DataMatrix &trainData, base::DataVector &trainDataClass, size_t NUM, double lambda, size_t IMAX, double eps, size_t IMAX_final, double eps_final, double firstLabel, double secondLabel, double threshold, double maxLambda, double minLambda, size_t searchNum, bool refine, size_t refineMode, size_t refineNum, size_t numberOfAda, double percentOfAda, size_t mode)
Std-Constructor.
void classif (base::DataMatrix &testData, base::DataVector &algorithmClassTrain, base::DataVector &algorithmClassTest, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest)
Performs a classify for the testing dataset according to the baselearners get from the algorithm.
void doAdaBoostR2 (base::DataMatrix &weights, base::DataMatrix &testData, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest, std::string lossFucType)
Performs the Adaboost.R2(a regression algorithm)
void doAdaBoostRT (base::DataMatrix &weights, base::DataMatrix &testData, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest, double Tvalue, std::string powerType)
Performs the Adaboost.RT(a regression algorithm)
void doDiscreteAdaBoost (base::DataVector &hypoWeight, base::DataVector &weightError, base::DataMatrix &weights, base::DataMatrix &decision, base::DataMatrix &testData, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest)
Performs the Discrete Adaboost.
void doRealAdaBoost (base::DataMatrix &weights, base::DataMatrix &testData, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest)
Performs the Real Adaboost.
void doRefinement (base::DataVector &alpha_ada, base::DataVector &weight_ada, size_t curBaseLearner)
Performs refinement of grid to get an adaptive grid.
void eval (base::DataMatrix &testData, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest)
Performs a real value calculate for the testing dataset.
void getAccuracy (base::DataMatrix &testData, base::DataVector &testDataClass, double *accuracy_train, double *accuracy_test)
Performs an accuracy evaluation for the testing dataset.
void getAccuracyBL (base::DataMatrix &testData, base::DataVector &testDataClass, base::DataMatrix &algorithmValueTrain, base::DataMatrix &algorithmValueTest, double *accuracy_train, double *accuracy_test, size_t yourBaseLearner)
Performs an accuracy evaluation for the testing dataset with a specified number of base learner.
size_t getActualBL ()
Get the actual base learners after doing adaboosting.
size_t getMaxGridPoint (size_t baseLearner)
Get the max GridPoint ever used in adaboosting.
size_t getMeanGridPoint (size_t baseLearner)
Get the mean GridPoint ever used in adaboosting.
void getROC (base::DataMatrix &validationData, base::DataVector &validationDataClass, double *acc, double *sensitivity, double *specificity, double *precision, double *recall, double *fOneScore)
Performs an evaluation to get ROC related parameter.
size_t getSumGridPoint (size_t baseLearner)
Get the sum GridPoint ever used in adaboosting.
double hValue (double realValue)
Performs a hypothesis classifier.
virtual ~AlgorithmAdaBoostBase ()
Std-Deconstructor.
Protected Member Functions
virtual void alphaSolver (double &lambda, base::DataVector &weight, base::DataVector &alpha, bool final)=0
Performs a solver to get alpha.
Protected Attributes
size_t actualBaseLearners
Actual base learners number for Adaboosting.
size_t boostMode
Set the boost mode (1: Discrete Adaboost, 2: Real Adaboost)
base::DataVector * classes
Pointer to the class(real value in regression) of the data vector.
base::DataMatrix * data
Pointer to the data matrix.
size_t dim
DataSet Dimension.
double epsilon
Parameter for CG solver(during the refinement)
double epsilon_final
Parameter for CG solver(for the last refinement)
base::Grid * grid
the grid
size_t gridPoint
Number of grid points.
size_t imax
Parameter for CG solver(during the refinement)
size_t imax_final
Parameter for CG solver(for the last refinement)
double labelOne
One label of the DataSet.
double labelTwo
Another label of the DataSet.
double lamb
the lambda, the regularisation parameter
double lambLogMax
Log of the Max lambda in searching for optimal lambda.
size_t lambSteps
Number of iteration in searching for optimal lambda.
double lambStepsize
Interval size with logrange used in searching optimal lambda.
base::level_t level
grid level
base::DataVector * maxGridPoint
Number of the maximum grid points used in the algorithm.
size_t numBaseLearners
Number of base learner for Adaboosting.
size_t numData
the size of the grid
size_t numOfAda
Number of Grid points to refine.
double perOfAda
Percentage of Grid points to refine(between 0 and 1)
bool refinement
Judgement of grid refine.
size_t refineMode
Select the refine mode(1:use grid number, 2: use grid number percentage)
size_t refineTimes
Number of refinement with a certain percentage of Grid points.
base::DataVector * sumGridPoint
Number of the sum grid points used in the algorithm.
double threshold
Threshold to predict class.
base::GridType type
type of grid; implemented cases: Linear Grid, LinearL0Boundary Grid, ModLinear Grid;
Constructor & Destructor Documentation
AlgorithmAdaBoostBase()
sgpp::datadriven::AlgorithmAdaBoostBase::AlgorithmAdaBoostBase (base::Grid & SparseGrid, base::GridType gridType, base::level_t gridLevel, base::DataMatrix & trainData, base::DataVector & trainDataClass, size_t NUM, double lambda, size_t IMAX, double eps, size_t IMAX_final, double eps_final, double firstLabel, double secondLabel, double threshold, double maxLambda, double minLambda, size_t searchNum, bool refine, size_t refineMode, size_t refineNum, size_t numberOfAda, double percentOfAda, size_t mode)
Std-Constructor.
Parameters
SparseGrid reference to the sparse grid
gridType reference to the type of grid
gridLevel reference to the level of grid
trainData reference to the training dataset
trainDataClass reference to the class(real value in regression) of training dataset
NUM the number of baselearner for Adaboosting
lambda the regularisation parameter
IMAX the parameter for ConjugateGradients
eps the parameter for ConjugateGradients
IMAX_final the parameter for ConjugateGradients used for last refinement step
eps_final the parameter for ConjugateGradients used for last refinement step
firstLabel one label from training dataset
secondLabel another label from training dataset
threshold the parameter for predicting a class
maxLambda the max lambda used in searching optimal lambda
minLambda the min lambda used in searching optimal lambda
searchNum the searching times used in searching for optimal lambda
refine the judgement of refine
refineMode Select the refine mode
refineNum the Number of refinement with a certain percentage of Grid points
numberOfAda the number of Grid points to refine
percentOfAda the percentage of Grid points to refine
mode the adaboost type to choose
References actualBaseLearners, boostMode, classes, data, dim, epsilon, epsilon_final, sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNrows(), sgpp::base::HashGridStorage::getSize(), sgpp::base::Grid::getStorage(), grid, gridPoint, imax, imax_final, labelOne, labelTwo, lamb, lambda, lambLogMax, lambSteps, lambStepsize, level, sgpp::base::Linear, sgpp::base::LinearL0Boundary, maxGridPoint, sgpp::base::ModLinear, numBaseLearners, numData, numOfAda, perOfAda, refinement, refineMode, refineTimes, sumGridPoint, threshold, and type.
~AlgorithmAdaBoostBase()
sgpp::datadriven::AlgorithmAdaBoostBase::~AlgorithmAdaBoostBase () virtual
Std-Deconstructor.
Member Function Documentation
alphaSolver()
virtual void sgpp::datadriven::AlgorithmAdaBoostBase::alphaSolver (double & lambda, base::DataVector & weight, base::DataVector & alpha, bool final) protected pure virtual
Performs a solver to get alpha.
Parameters
lambda the regularisation parameter
weight the weights of examples
alpha output the coefficients of the sparse grid's basis functions
final judgement the final step of this base learner
Implemented in sgpp::datadriven::AlgorithmAdaBoostIdentity.
Referenced by doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), and doRefinement().
classif()
void sgpp::datadriven::AlgorithmAdaBoostBase::classif (base::DataMatrix & testData, base::DataVector & algorithmClassTrain, base::DataVector & algorithmClassTest, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest)
Performs a classify for the testing dataset according to the baselearners get from the algorithm.
Parameters
testData reference to the testing dataset
algorithmClassTrain reference to the class of training dataset got from the algorithm
algorithmClassTest reference to the class of testing dataset got from the algorithm
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
References eval(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNrows(), hValue(), numData, and sgpp::base::DataVector::set().
Referenced by getAccuracy(), and getROC().
doAdaBoostR2()
void sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2 (base::DataMatrix & weights, base::DataMatrix & testData, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest, std::string lossFucType)
Performs the Adaboost.R2(a regression algorithm)
Parameters
weights the matrix to store weights of every training date for every weak learner
testData reference to the testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
lossFucType the loss function type(linear, square or exponential)
References sgpp::base::DataVector::abs(), actualBaseLearners, alphaSolver(), sgpp::base::DataVector::axpy(), classes, sgpp::base::DataVector::componentwise_mult(), sgpp::base::DataVector::copyFrom(), sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationEval(), data, dim, doRefinement(), sgpp::base::DataVector::dotProduct(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getColumn(), sgpp::base::Grid::getGenerator(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), grid, gridPoint, lamb, level, sgpp::base::Linear, sgpp::base::LinearL0Boundary, sgpp::base::DataVector::max(), maxGridPoint, sgpp::base::ModLinear, sgpp::base::DataVector::mult(), numBaseLearners, numData, refinement, sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::set(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataVector::sqr(), sgpp::base::DataVector::sum(), sumGridPoint, and type.
doAdaBoostRT()
void sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT (base::DataMatrix & weights, base::DataMatrix & testData, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest, double Tvalue, std::string powerType)
Performs the Adaboost.RT(a regression algorithm)
Parameters
weights the matrix to store weights of every training date for every weak learner
testData reference to the testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
Tvalue the threshold to demarcate the prediction correctness(only from 0 to 1)
powerType the error rate power coefficient(linear, square or cubic)
References actualBaseLearners, alphaSolver(), sgpp::base::DataVector::axpy(), classes, sgpp::base::DataVector::copyFrom(), sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationEval(), data, dim, doRefinement(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getColumn(), sgpp::base::Grid::getGenerator(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), grid, gridPoint, lamb, level, sgpp::base::Linear, sgpp::base::LinearL0Boundary, maxGridPoint, sgpp::base::ModLinear, sgpp::base::DataVector::mult(), numBaseLearners, numData, refinement, sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::set(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataVector::sum(), sumGridPoint, and type.
doDiscreteAdaBoost()
void sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost (base::DataVector & hypoWeight, base::DataVector & weightError, base::DataMatrix & weights, base::DataMatrix & decision, base::DataMatrix & testData, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest)
Performs the Discrete Adaboost.
Parameters
hypoWeight the vector to store hypothesis weights(Alpha-t)
weightError the vector to store the weight error of each iteration
weights the matrix to store weights of every training date for every weak learner
decision the matrix to store the decision right or not according to the true class
testData reference to the testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
References actualBaseLearners, alphaSolver(), sgpp::base::DataVector::copyFrom(), sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationEval(), data, dim, doRefinement(), sgpp::base::DataVector::dotProduct(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getGenerator(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), grid, gridPoint, hValue(), lamb, lambLogMax, lambSteps, lambStepsize, level, sgpp::base::Linear, sgpp::base::LinearL0Boundary, maxGridPoint, sgpp::base::ModLinear, sgpp::base::DataVector::mult(), numBaseLearners, numData, refinement, sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::set(), sgpp::base::DataMatrix::set(), sgpp::base::DataVector::setAll(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataVector::sum(), sumGridPoint, and type.
Referenced by eval().
doRealAdaBoost()
void sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost (base::DataMatrix & weights, base::DataMatrix & testData, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest)
Performs the Real Adaboost.
Parameters
weights the matrix to store weights of every training date for every weak learner
testData reference to the testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
References actualBaseLearners, alphaSolver(), classes, sgpp::base::DataVector::copyFrom(), sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationEval(), data, dim, doRefinement(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getGenerator(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), grid, gridPoint, lamb, level, sgpp::base::Linear, sgpp::base::LinearL0Boundary, maxGridPoint, sgpp::base::ModLinear, sgpp::base::DataVector::mult(), numBaseLearners, numData, refinement, sgpp::base::GridGenerator::regular(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::set(), sgpp::base::DataMatrix::set(), sgpp::base::DataMatrix::setColumn(), sgpp::base::DataVector::sum(), sumGridPoint, and type.
Referenced by eval().
doRefinement()
void sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement (base::DataVector & alpha_ada, base::DataVector & weight_ada, size_t curBaseLearner)
Performs refinement of grid to get an adaptive grid.
Parameters
alpha_ada the coefficients of the sparse grid's basis functions and to be refined
weight_ada the weights of examples
curBaseLearner the current base learner
References alphaSolver(), sgpp::base::DataVector::get(), sgpp::base::Grid::getGenerator(), sgpp::base::Grid::getSize(), sgpp::base::HashGridStorage::getSize(), sgpp::base::Grid::getStorage(), grid, lamb, maxGridPoint, numOfAda, perOfAda, sgpp::base::GridGenerator::refine(), refineMode, refineTimes, sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::set(), and sumGridPoint.
Referenced by doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), and doRealAdaBoost().
eval()
void sgpp::datadriven::AlgorithmAdaBoostBase::eval (base::DataMatrix & testData, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest)
Performs a real value calculate for the testing dataset.
Parameters
testData reference to the testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
References boostMode, doDiscreteAdaBoost(), doRealAdaBoost(), numBaseLearners, and numData.
Referenced by classif(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getAccuracy()
void sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracy (base::DataMatrix & testData, base::DataVector & testDataClass, double * accuracy_train, double * accuracy_test)
Performs an accuracy evaluation for the testing dataset.
Parameters
testData reference to the testing dataset
testDataClass reference to the class of testing dataset
accuracy_train reference to the accuracy for the training dataset
accuracy_test reference to the accuracy for the testing dataset
References classif(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), numBaseLearners, and numData.
getAccuracyBL()
void sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracyBL (base::DataMatrix & testData, base::DataVector & testDataClass, base::DataMatrix & algorithmValueTrain, base::DataMatrix & algorithmValueTest, double * accuracy_train, double * accuracy_test, size_t yourBaseLearner)
Performs an accuracy evaluation for the testing dataset with a specified number of base learner.
Parameters
testData reference to the testing dataset
testDataClass reference to the class of testing dataset
algorithmValueTrain the matrix reference to the real value of training dataset got from the algorithm with diff base learners
algorithmValueTest the matrix reference to the real value of testing dataset got from the algorithm with diff base learners
accuracy_train reference to the accuracy for the training dataset
accuracy_test reference to the accuracy for the testing dataset
yourBaseLearner the number of base learner specified
References sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), hValue(), and numData.
getActualBL()
size_t sgpp::datadriven::AlgorithmAdaBoostBase::getActualBL ()
Get the actual base learners after doing adaboosting.
References actualBaseLearners.
getMaxGridPoint()
size_t sgpp::datadriven::AlgorithmAdaBoostBase::getMaxGridPoint (size_t baseLearner)
Get the max GridPoint ever used in adaboosting.
Parameters
baseLearner number of baselearner
References sgpp::base::DataVector::get(), and maxGridPoint.
getMeanGridPoint()
size_t sgpp::datadriven::AlgorithmAdaBoostBase::getMeanGridPoint (size_t baseLearner)
Get the mean GridPoint ever used in adaboosting.
Parameters
baseLearner number of baselearner
References sgpp::base::DataVector::get(), and sumGridPoint.
getROC()
void sgpp::datadriven::AlgorithmAdaBoostBase::getROC (base::DataMatrix & validationData, base::DataVector & validationDataClass, double * acc, double * sensitivity, double * specificity, double * precision, double * recall, double * fOneScore)
Performs an evaluation to get ROC related parameter.
Parameters
validationData reference to the validation dataset
validationDataClass reference to the class of validation dataset
acc reference to the accuracy for the validation dataset
sensitivity reference to the sensitivity for the validation dataset
specificity reference to the specificity for the validation dataset
precision reference to the precision for the validation dataset
recall reference to the recall for the validation dataset
fOneScore reference to the specificity for the validation dataset
References classif(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), numBaseLearners, and numData.
getSumGridPoint()
size_t sgpp::datadriven::AlgorithmAdaBoostBase::getSumGridPoint (size_t baseLearner)
Get the sum GridPoint ever used in adaboosting.
Parameters
baseLearner number of baselearner
References sgpp::base::DataVector::get(), and sumGridPoint.
hValue()
double sgpp::datadriven::AlgorithmAdaBoostBase::hValue (double realValue)
Performs a hypothesis classifier.
Parameters
realValue real value of function
References labelOne, labelTwo, and threshold.
Referenced by classif(), doDiscreteAdaBoost(), and getAccuracyBL().
Member Data Documentation
actualBaseLearners
size_t sgpp::datadriven::AlgorithmAdaBoostBase::actualBaseLearners protected
Actual base learners number for Adaboosting.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), and getActualBL().
boostMode
size_t sgpp::datadriven::AlgorithmAdaBoostBase::boostMode protected
Set the boost mode (1: Discrete Adaboost, 2: Real Adaboost)
Referenced by AlgorithmAdaBoostBase(), and eval().
classes
base::DataVector* sgpp::datadriven::AlgorithmAdaBoostBase::classes protected
Pointer to the class(real value in regression) of the data vector.
Referenced by AlgorithmAdaBoostBase(), sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), doAdaBoostR2(), doAdaBoostRT(), and doRealAdaBoost().
data
base::DataMatrix* sgpp::datadriven::AlgorithmAdaBoostBase::data protected
Pointer to the data matrix.
Referenced by AlgorithmAdaBoostBase(), sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), and doRealAdaBoost().
dim
size_t sgpp::datadriven::AlgorithmAdaBoostBase::dim protected
DataSet Dimension.
Referenced by python.data.DataContainer.DataContainer::__init__(), python.uq.dists.EstimatedDist.EstimatedDist::_convertEvalPoint(), AlgorithmAdaBoostBase(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.dists.KDEDist.KDEDist::cov(), python.uq.dists.SGDEdist.SGDEdist::cov(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), python.data.DataContainer.DataContainer::getDataSubsetByIndexList(), python.data.DataContainer.DataContainer::getDim(), python.uq.dists.EstimatedDist.EstimatedDist::getDim(), python.uq.dists.LibAGFDist.LibAGFDist::getDim(), python.uq.dists.NatafDist.NatafDist::getDim(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.uq.dists.EstimatedDist.EstimatedDist::rvs(), python.uq.dists.NatafDist.NatafDist::rvs(), python.uq.dists.KDEDist.KDEDist::rvs(), python.uq.dists.SGDEdist.SGDEdist::rvs(), python.uq.operations.natafTransformation.NatafTransformation::trans_X_to_Z(), and python.uq.operations.natafTransformation.NatafTransformation::trans_Z_to_X().
epsilon
double sgpp::datadriven::AlgorithmAdaBoostBase::epsilon protected
Parameter for CG solver(during the refinement)
Referenced by AlgorithmAdaBoostBase(), and sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver().
epsilon_final
double sgpp::datadriven::AlgorithmAdaBoostBase::epsilon_final protected
Parameter for CG solver(for the last refinement)
Referenced by AlgorithmAdaBoostBase(), and sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver().
grid
base::Grid* sgpp::datadriven::AlgorithmAdaBoostBase::grid protected
the grid
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), AlgorithmAdaBoostBase(), sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), doRealAdaBoost(), doRefinement(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
gridPoint
size_t sgpp::datadriven::AlgorithmAdaBoostBase::gridPoint protected
Number of grid points.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), and doRealAdaBoost().
imax
size_t sgpp::datadriven::AlgorithmAdaBoostBase::imax protected
Parameter for CG solver(during the refinement)
Referenced by AlgorithmAdaBoostBase(), and sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver().
imax_final
size_t sgpp::datadriven::AlgorithmAdaBoostBase::imax_final protected
Parameter for CG solver(for the last refinement)
Referenced by AlgorithmAdaBoostBase(), and sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver().
labelOne
double sgpp::datadriven::AlgorithmAdaBoostBase::labelOne protected
One label of the DataSet.
Referenced by AlgorithmAdaBoostBase(), and hValue().
labelTwo
double sgpp::datadriven::AlgorithmAdaBoostBase::labelTwo protected
Another label of the DataSet.
Referenced by AlgorithmAdaBoostBase(), and hValue().
lamb
double sgpp::datadriven::AlgorithmAdaBoostBase::lamb protected
the lambda, the regularisation parameter
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), and doRefinement().
lambLogMax
double sgpp::datadriven::AlgorithmAdaBoostBase::lambLogMax protected
Log of the Max lambda in searching for optimal lambda.
Referenced by AlgorithmAdaBoostBase(), and doDiscreteAdaBoost().
lambSteps
size_t sgpp::datadriven::AlgorithmAdaBoostBase::lambSteps protected
Number of iteration in searching for optimal lambda.
Referenced by AlgorithmAdaBoostBase(), and doDiscreteAdaBoost().
lambStepsize
double sgpp::datadriven::AlgorithmAdaBoostBase::lambStepsize protected
Interval size with logrange used in searching optimal lambda.
Referenced by AlgorithmAdaBoostBase(), and doDiscreteAdaBoost().
level
base::level_t sgpp::datadriven::AlgorithmAdaBoostBase::level protected
grid level
Referenced by python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::__eq__(), python.learner.folding.FoldingPolicy.FoldingPolicy::__next__(), AlgorithmAdaBoostBase(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::contains(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::containsDimx(), python.uq.learner.builder.GridDescriptor.GridDescriptor::createGrid(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), python.uq.estimators.MarginalIntegralStrategy.MarginalIntegralStrategy::estimate(), python.uq.learner.builder.GridDescriptor.GridDescriptor::fromGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::getLevelIndex(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::getMaxLevel(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::overlap(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::overlapDimx(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::transformToReferenceGrid(), python.uq.manager.ASGCStatistics.ASGCStatistics::updateResults(), python.uq.learner.builder.GridDescriptor.GridDescriptor::withLevel(), and python.uq.learner.builder.RegressorSpecificationDescriptor.FoldingDescriptor::withLevel().
maxGridPoint
base::DataVector* sgpp::datadriven::AlgorithmAdaBoostBase::maxGridPoint protected
Number of the maximum grid points used in the algorithm.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), doRefinement(), and getMaxGridPoint().
numBaseLearners
size_t sgpp::datadriven::AlgorithmAdaBoostBase::numBaseLearners protected
Number of base learner for Adaboosting.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), eval(), getAccuracy(), and getROC().
numData
size_t sgpp::datadriven::AlgorithmAdaBoostBase::numData protected
the size of the grid
Referenced by AlgorithmAdaBoostBase(), classif(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), eval(), getAccuracy(), getAccuracyBL(), and getROC().
numOfAda
size_t sgpp::datadriven::AlgorithmAdaBoostBase::numOfAda protected
Number of Grid points to refine.
Referenced by AlgorithmAdaBoostBase(), and doRefinement().
perOfAda
double sgpp::datadriven::AlgorithmAdaBoostBase::perOfAda protected
Percentage of Grid points to refine(between 0 and 1)
Referenced by AlgorithmAdaBoostBase(), and doRefinement().
refinement
bool sgpp::datadriven::AlgorithmAdaBoostBase::refinement protected
Judgement of grid refine.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), and doRealAdaBoost().
refineMode
size_t sgpp::datadriven::AlgorithmAdaBoostBase::refineMode protected
Select the refine mode(1:use grid number, 2: use grid number percentage)
Referenced by AlgorithmAdaBoostBase(), and doRefinement().
refineTimes
size_t sgpp::datadriven::AlgorithmAdaBoostBase::refineTimes protected
Number of refinement with a certain percentage of Grid points.
Referenced by AlgorithmAdaBoostBase(), and doRefinement().
sumGridPoint
base::DataVector* sgpp::datadriven::AlgorithmAdaBoostBase::sumGridPoint protected
Number of the sum grid points used in the algorithm.
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), doRealAdaBoost(), doRefinement(), getMeanGridPoint(), and getSumGridPoint().
threshold
double sgpp::datadriven::AlgorithmAdaBoostBase::threshold protected
Threshold to predict class.
Referenced by AlgorithmAdaBoostBase(), and hValue().
type
base::GridType sgpp::datadriven::AlgorithmAdaBoostBase::type protected
type of grid; implemented cases: Linear Grid, LinearL0Boundary Grid, ModLinear Grid;
Referenced by AlgorithmAdaBoostBase(), doAdaBoostR2(), doAdaBoostRT(), doDiscreteAdaBoost(), and doRealAdaBoost().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/AlgorithmAdaBoostBase.hpp
datadriven/src/sgpp/datadriven/algorithm/AlgorithmAdaBoostBase.cpp