SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::OperationDensityMultMPI Class Reference
sgpp::datadriven::clusteringmpi::OperationDensityMultMPI Class Reference
#include <OperationDensityMPI.hpp>
Public Member Functions
virtual void mult (base::DataVector &alpha, base::DataVector &result)
starts the Multiplication with the matrix
OperationDensityMultMPI (base::Grid &grid, double lambda, std::string ocl_conf_filename)
virtual ~OperationDensityMultMPI ()
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::DensityWorker
DensityWorker ()
DensityWorker (base::Grid &grid, double lambda)
DensityWorker (base::Grid &grid, double lambda, std::string ocl_conf_filename)
virtual ~DensityWorker ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
virtual ~MPIWorkerGridBase ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual ~MPIWorkerBase (void)
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
MPIWorkerPackageBase (std::string operationName, int multiplier)
MPIWorkerPackageBase (std::string operationName, int multiplier, std::string ocl_conf_filename)
void start_worker_main (void)
virtual ~MPIWorkerPackageBase ()
Additional Inherited Members
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::DensityWorker
void begin_opencl_operation (int *workpackage)
void finalize_opencl_operation (double *result_buffer, int *workpackage)
void receive_alpha (double **alpha)
void receive_and_send_initial_data (void)
void send_alpha (double **alpha)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
MPIWorkerGridBase (std::string operationName)
MPIWorkerGridBase (std::string operationName, base::Grid &grid)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
void divide_workpackages (int *package, double *erg)
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::DensityWorker
double * alpha
double lambda
size_t oldgridsize
DensityOCLMultiPlatform::OperationDensity * op
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
int complete_gridsize
int grid_dimensions
int * gridpoints
int gridsize
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
bool verbose
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
MPI_Comm & master_worker_comm
MPI_Datatype mpi_typ
size_t opencl_device
bool opencl_node
size_t opencl_platform
bool overseer_node
int packagesize_multiplier
base::OCLOperationConfiguration * parameters
bool prefetching
bool redistribute
int secondary_workpackage [2]
size_t size
MPI_Comm & sub_worker_comm
Constructor & Destructor Documentation
OperationDensityMultMPI()
sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::OperationDensityMultMPI (base::Grid & grid, double lambda, std::string ocl_conf_filename) inline
~OperationDensityMultMPI()
virtual sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::~OperationDensityMultMPI () inline virtual
Member Function Documentation
mult()
virtual void sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult (base::DataVector & alpha, base::DataVector & result) inline virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::base::OperationMatrix.
References sgpp::datadriven::clusteringmpi::DensityWorker::alpha, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::base::DataVector::getPointer(), sgpp::base::DataVector::getSize(), sgpp::datadriven::clusteringmpi::DensityWorker::send_alpha(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_sub_workers(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::sub_worker_comm.
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationDensityMPI.hpp