SG++-Doxygen-Documentation: sgpp::solver::ConjugateGradientsSP Class Reference
sgpp::solver::ConjugateGradientsSP Class Reference
#include <ConjugateGradientsSP.hpp>
Public Member Functions
virtual void calcStarting ()
function that signals the start of the calculation of the CG method (used in python)
virtual void complete ()
function that signals the finish of the cg method (used in python)
ConjugateGradientsSP (size_t imax, float epsilon)
Std-Constructor.
virtual void iterationComplete ()
function that signals that one iteration step of the CG method has been completed (used in python)
void solve (sgpp::base::OperationMatrixSP &SystemMatrix, sgpp::base::DataVectorSP &alpha, sgpp::base::DataVectorSP &b, bool reuse=false, bool verbose=false, float max_threshold=-1.0)
function that defines a solve method for an iterative solver.
virtual void starting ()
function that signals the start of the CG method (used in python)
virtual ~ConjugateGradientsSP ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SLESolverSP
SLESolverSP (size_t imax, float epsilon)
Std-Constructor.
virtual ~SLESolverSP ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolverSP
float getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
float getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (float eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolverSP (size_t nMaximumIterations, float epsilon)
Std-Constructor.
virtual ~SGSolverSP ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolverSP
float myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
float residuum
residuum
Constructor & Destructor Documentation
ConjugateGradientsSP()
sgpp::solver::ConjugateGradientsSP::ConjugateGradientsSP (size_t imax, float epsilon)
Std-Constructor.
~ConjugateGradientsSP()
sgpp::solver::ConjugateGradientsSP::~ConjugateGradientsSP () virtual
Std-Destructor.
Member Function Documentation
calcStarting()
void sgpp::solver::ConjugateGradientsSP::calcStarting () virtual
function that signals the start of the calculation of the CG method (used in python)
complete()
void sgpp::solver::ConjugateGradientsSP::complete () virtual
function that signals the finish of the cg method (used in python)
iterationComplete()
void sgpp::solver::ConjugateGradientsSP::iterationComplete () virtual
function that signals that one iteration step of the CG method has been completed (used in python)
solve()
void sgpp::solver::ConjugateGradientsSP::solve (sgpp::base::OperationMatrixSP & SystemMatrix, sgpp::base::DataVectorSP & alpha, sgpp::base::DataVectorSP & b, bool reuse = false, bool verbose = false, float max_threshold = -1.0) virtual
function that defines a solve method for an iterative solver.
In contrast to the normal solve routine this method operates on sinlge precision data.
Parameters
SystemMatrix reference to an sgpp::base::OperationMatrix Object that implements the matrix vector multiplication
alpha the sparse grid's coefficients which have to be determined
b the right hand side of the system of linear equations
reuse identifies if the alphas, stored in alpha at calling time, should be reused
verbose prints information during execution of the solver
max_threshold additional abort criteria for solver
Implements sgpp::solver::SLESolverSP.
References sgpp::base::DataVectorSP::add(), alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVectorSP::dotProduct(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMatrixSP::mult(), sgpp::base::DataVectorSP::mult(), sgpp::solver::SGSolverSP::myEpsilon, sgpp::solver::SGSolverSP::nIterations, sgpp::solver::SGSolverSP::nMaxIterations, sgpp::solver::SGSolverSP::residuum, sgpp::base::DataVector::setAll(), and sgpp::base::DataVectorSP::setAll().
starting()
void sgpp::solver::ConjugateGradientsSP::starting () virtual
function that signals the start of the CG method (used in python)
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/sle/ConjugateGradientsSP.hpp
solver/src/sgpp/solver/sle/ConjugateGradientsSP.cpp