SG++-Doxygen-Documentation: python.uq.analysis.KnowledgeTypes.KnowledgeTypes Class Reference
python.uq.analysis.KnowledgeTypes.KnowledgeTypes Class Reference
Public Member Functions
getFunctionToApproximate (cls, dtype, U)
toString (cls, item)
transformData (cls, data, U, dtype)
xrange (cls)
Static Public Attributes
int EXPECTATIONVALUE = 2
int SIMPLE = 0
int SQUARED = 1
int VARIANCE = 3
Member Function Documentation
getFunctionToApproximate()
python.uq.analysis.KnowledgeTypes.KnowledgeTypes.getFunctionToApproximate (cls, dtype, U)
Referenced by python.uq.analysis.KnowledgeTypes.KnowledgeTypes.transformData().
toString()
python.uq.analysis.KnowledgeTypes.KnowledgeTypes.toString (cls, item)
Referenced by python.controller.LearnerEventController.LearnerEventController.__repr__(), python.controller.SolverEventController.SolverEventController.__repr__(), python.learner.Learner.Learner.createMemento(), python.uq.learner.Learner.Learner.createMemento(), and python.learner.formatter.GridFormatter.GridFormatter.serialize().
transformData()
python.uq.analysis.KnowledgeTypes.KnowledgeTypes.transformData (cls, data, U, dtype)
Transform the given data set with respect to the
specified dtype.
@param data: dictionary {<time step>: {<parameter>: 1d numpy array}}
@param U: Dist, distribution
@param dtype: KnowledgeType
References f, and python.uq.analysis.KnowledgeTypes.KnowledgeTypes.getFunctionToApproximate().
xrange()
python.uq.analysis.KnowledgeTypes.KnowledgeTypes.xrange (cls)
Member Data Documentation
EXPECTATIONVALUE
int python.uq.analysis.KnowledgeTypes.KnowledgeTypes.EXPECTATIONVALUE = 2 static
SIMPLE
int python.uq.analysis.KnowledgeTypes.KnowledgeTypes.SIMPLE = 0 static
SQUARED
int python.uq.analysis.KnowledgeTypes.KnowledgeTypes.SQUARED = 1 static
VARIANCE
int python.uq.analysis.KnowledgeTypes.KnowledgeTypes.VARIANCE = 3 static
The documentation for this class was generated from the following file:
datadriven/python/uq/analysis/KnowledgeTypes.py