SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T > Class Template Reference
Class for opencl density multiplication and density right hand side vector.
#include <OperationDensityOCLMultiPlatform.hpp>
Public Member Functions
void finalize_rhs_generation (sgpp::base::DataVector &b, size_t start_id, size_t chunksize) override
void finish_partial_mult (double *result, int start_id, int chunksize) override
void generateb (base::DataMatrix &dataset, sgpp::base::DataVector &b, size_t start_id=0, size_t chunksize=0) override
Generates the right hand side vector for the density equation.
void initialize_alpha (double *alpha) override
Use before calling partial_mult directly.
void initialize_dataset (base::DataMatrix &dataset) override
void mult (base::DataVector &alpha, base::DataVector &result) override
Execute one matrix-vector multiplication with the density matrix.
OperationDensityOCLMultiPlatform (base::Grid &grid, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration *parameters, T lambda, size_t platform_id, size_t device_id)
Normal constructor.
OperationDensityOCLMultiPlatform (int *gridpoints, size_t gridsize, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration *parameters, T lambda, size_t platform_id, size_t device_id)
Constructor for mpi nodes - accepts grid als integer array.
void start_partial_mult (int start_id, int chunksize) override
Execute a partial (startindex to startindex+chunksize) multiplication with the density matrix.
void start_rhs_generation (size_t start_id, size_t chunksize) override
~OperationDensityOCLMultiPlatform ()
Public Member Functions inherited from sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity
OperationDensity ()
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity
static void load_default_parameters (base::OCLOperationConfiguration *parameters)
Generate the default parameters in die json configuration.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >
Class for opencl density multiplication and density right hand side vector.
Constructor & Destructor Documentation
OperationDensityOCLMultiPlatform() [1/2]
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::OperationDensityOCLMultiPlatform (base::Grid & grid, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration * parameters, T lambda, size_t platform_id, size_t device_id) inline
Normal constructor.
References grid(), and lambda.
OperationDensityOCLMultiPlatform() [2/2]
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::OperationDensityOCLMultiPlatform (int * gridpoints, size_t gridsize, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration * parameters, T lambda, size_t platform_id, size_t device_id) inline
Constructor for mpi nodes - accepts grid als integer array.
References lambda.
~OperationDensityOCLMultiPlatform()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::~OperationDensityOCLMultiPlatform () inline
Member Function Documentation
finalize_rhs_generation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::finalize_rhs_generation (sgpp::base::DataVector & b, size_t start_id, size_t chunksize) inline override virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::finalize_rhs_generation().
finish_partial_mult()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::finish_partial_mult (double * result, int start_id, int chunksize) inline override virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::finish_mult().
generateb()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::generateb (base::DataMatrix & dataset, sgpp::base::DataVector & b, size_t start_id = 0, size_t chunksize = 0) inline override virtual
Generates the right hand side vector for the density equation.
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References dataset, sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::finalize_rhs_generation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::initialize_dataset(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation().
initialize_alpha()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::initialize_alpha (double * alpha) inline override virtual
Use before calling partial_mult directly.
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References alpha, and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::initialize_alpha_buffer().
initialize_dataset()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::initialize_dataset (base::DataMatrix & dataset) inline override virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References dataset, and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::initialize_dataset().
mult()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::mult (base::DataVector & alpha, base::DataVector & result) inline override virtual
Execute one matrix-vector multiplication with the density matrix.
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References alpha, sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::finish_mult(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::initialize_alpha_buffer(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult().
start_partial_mult()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::start_partial_mult (int start_id, int chunksize) inline override virtual
Execute a partial (startindex to startindex+chunksize) multiplication with the density matrix.
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult().
start_rhs_generation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >::start_rhs_generation (size_t start_id, size_t chunksize) inline override virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationDensityOCLMultiPlatform/OperationDensityOCLMultiPlatform.hpp