SG++-Doxygen-Documentation: sgpp::base::QuadRule1D Class Reference
sgpp::base::QuadRule1D Class Reference
#include <QuadRule1D.hpp>
Public Member Functions
void getLevelPointsAndWeights (size_t level, base::DataVector &coordinates, base::DataVector &weights)
size_t getMaxSupportedLevel () const
QuadRule1D ()
virtual ~QuadRule1D ()
Public Attributes
std::vector< double > coordinatesWeights
Constructor & Destructor Documentation
QuadRule1D()
sgpp::base::QuadRule1D::QuadRule1D ()
~QuadRule1D()
sgpp::base::QuadRule1D::~QuadRule1D () virtual
Member Function Documentation
getLevelPointsAndWeights()
void sgpp::base::QuadRule1D::getLevelPointsAndWeights (size_t level, base::DataVector & coordinates, base::DataVector & weights)
References coordinatesWeights, getMaxSupportedLevel(), and level.
Referenced by sgpp::base::PolyBasis< LT, IT >::getIntegral(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), and sgpp::base::GaussHermiteQuadRule1D::getLevelPointsAndWeightsNormalized().
getMaxSupportedLevel()
size_t sgpp::base::QuadRule1D::getMaxSupportedLevel () const
References coordinatesWeights.
Referenced by getLevelPointsAndWeights().
Member Data Documentation
coordinatesWeights
std::vector<double> sgpp::base::QuadRule1D::coordinatesWeights
Referenced by sgpp::base::GaussHermiteQuadRule1D::GaussHermiteQuadRule1D(), sgpp::base::GaussLegendreQuadRule1D::GaussLegendreQuadRule1D(), getLevelPointsAndWeights(), and getMaxSupportedLevel().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/QuadRule1D.hpp
base/src/sgpp/base/tools/QuadRule1D.cpp