SG++-Doxygen-Documentation: sgpp::base::DehierarchisationLinear Class Reference
sgpp::base::DehierarchisationLinear Class Reference
Class that implements the dehierarchisation on a linear sparse grid.
#include <DehierarchisationLinear.hpp>
Public Member Functions
DehierarchisationLinear (GridStorage &storage)
Constructor, must be bind to a grid.
virtual void operator() (DataVector &source, DataVector &result, grid_iterator &index, size_t dim)
Implements operator() needed by the sweep class during the grid traversal.
virtual ~DehierarchisationLinear ()
Destructor.
Protected Types
typedef GridStorage::grid_iterator grid_iterator
Protected Member Functions
void rec (DataVector &source, DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
Recursive dehierarchisaton algorithm, this algorithms works in-place -> source should be equal to result.
Protected Attributes
GridStorage & storage
the grid object
Detailed Description
Class that implements the dehierarchisation on a linear sparse grid.
Therefore the ()operator has to be implement in order to use the sweep algorithm for the grid traversal
Member Typedef Documentation
grid_iterator
typedef GridStorage::grid_iterator sgpp::base::DehierarchisationLinear::grid_iterator protected
Constructor & Destructor Documentation
DehierarchisationLinear()
sgpp::base::DehierarchisationLinear::DehierarchisationLinear (GridStorage & storage) explicit
Constructor, must be bind to a grid.
Parameters
storage the grid storage object of the the grid, on which the dehierarchisation should be executed
~DehierarchisationLinear()
sgpp::base::DehierarchisationLinear::~DehierarchisationLinear () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::base::DehierarchisationLinear::operator() (DataVector & source, DataVector & result, grid_iterator & index, size_t dim) virtual
Implements operator() needed by the sweep class during the grid traversal.
This function is applied to the whole grid.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented in sgpp::base::DehierarchisationLinearBoundary.
References rec().
rec()
void sgpp::base::DehierarchisationLinear::rec (DataVector & source, DataVector & result, grid_iterator & index, size_t dim, double fl, double fr) protected
Recursive dehierarchisaton algorithm, this algorithms works in-place -> source should be equal to result.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
fl left value of the current region regarded in this step of the recursion
fr right value of the current region regarded in this step of the recursion
References sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), and rec().
Member Data Documentation
storage
GridStorage& sgpp::base::DehierarchisationLinear::storage protected
the grid object
Referenced by sgpp::base::DehierarchisationLinearBoundary::operator()(), and rec().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinear.hpp
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinear.cpp