SG++-Doxygen-Documentation: sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive Class Reference
sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive Class Reference
Operation for evaluating modified Clenshaw-Curtis B-spline linear combinations on Noboundary grids, their gradients, and their Hessians.
#include <OperationEvalHessianModBsplineClenshawCurtisNaive.hpp>
Public Member Functions
void evalHessian (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient, std::vector< DataMatrix > &hessian) override
double evalHessian (const DataVector &alpha, const DataVector &point, DataVector &gradient, DataMatrix &hessian) override
OperationEvalHessianModBsplineClenshawCurtisNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalHessianModBsplineClenshawCurtisNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalHessian
OperationEvalHessian ()
Constructor.
virtual ~OperationEvalHessian ()
Destructor.
Protected Attributes
SBsplineModifiedClenshawCurtisBase base
1D B-spline basis
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalHessian
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating modified Clenshaw-Curtis B-spline linear combinations on Noboundary grids, their gradients, and their Hessians.
Constructor & Destructor Documentation
OperationEvalHessianModBsplineClenshawCurtisNaive()
sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::OperationEvalHessianModBsplineClenshawCurtisNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalHessianModBsplineClenshawCurtisNaive()
sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::~OperationEvalHessianModBsplineClenshawCurtisNaive () inline override
Destructor.
Member Function Documentation
evalHessian() [1/2]
void sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient, std::vector< DataMatrix > & hessian) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
[out] hessian vector of Hessians of the linear combination
Reimplemented from sgpp::base::OperationEvalHessian.
References alpha, base, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalHessian() [2/2]
double sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian (const DataVector & alpha, const DataVector & point, DataVector & gradient, DataMatrix & hessian) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient vector of the linear combination
[out] hessian Hessian matrix of the linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalHessian.
References sgpp::base::DataMatrix::add(), sgpp::base::DataVector::add(), alpha, base, sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SBsplineModifiedClenshawCurtisBase sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::base protected
1D B-spline basis
Referenced by evalHessian(), and evalHessian().
innerDerivative
DataVector sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalHessian(), and evalHessian().
pointInUnitCube
DataVector sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalHessian(), and evalHessian().
storage
GridStorage& sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::storage protected
storage of the sparse grid
Referenced by evalHessian(), and evalHessian().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalHessianModBsplineClenshawCurtisNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalHessianModBsplineClenshawCurtisNaive.cpp