SG++-Doxygen-Documentation: sgpp::base::DehierarchisationPolyClenshawCurtisBoundary Class Reference
sgpp::base::DehierarchisationPolyClenshawCurtisBoundary Class Reference
Class that implements the dehierarchisation on a polynomial sparse grid.
#include <DehierarchisationPolyClenshawCurtisBoundary.hpp>
Public Member Functions
DehierarchisationPolyClenshawCurtisBoundary (GridStorage &storage, SPolyClenshawCurtisBoundaryBase *base)
Constructor, must be bind to a grid.
void operator() (DataVector &source, DataVector &result, grid_iterator &index, size_t dim)
Implements operator() needed by the sweep class during the grid traversal.
~DehierarchisationPolyClenshawCurtisBoundary ()
Destructor.
Protected Types
typedef GridStorage::grid_iterator grid_iterator
typedef index_t index_type
typedef level_t level_type
Protected Member Functions
void rec (DataVector &source, DataVector &result, grid_iterator &index, size_t dim, DataVector &coeffs)
Recursive dehierarchisation algorithm, this algorithms works in-place -> source should be equal to result.
Protected Attributes
SPolyClenshawCurtisBoundaryBase * base
the base
ClenshawCurtisTable & clenshawCurtisTable
clenshaw curtis points
GridStorage & storage
the grid object
Detailed Description
Class that implements the dehierarchisation on a polynomial sparse grid.
Therefore the ()operator has to be implement in order to use the sweep algorithm for the grid traversal
Member Typedef Documentation
grid_iterator
typedef GridStorage::grid_iterator sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::grid_iterator protected
index_type
typedef index_t sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::index_type protected
level_type
typedef level_t sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::level_type protected
Constructor & Destructor Documentation
DehierarchisationPolyClenshawCurtisBoundary()
sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::DehierarchisationPolyClenshawCurtisBoundary (GridStorage & storage, SPolyClenshawCurtisBoundaryBase * base) explicit
Constructor, must be bind to a grid.
Parameters
storage the grid storage object of the the grid, on which the dehierarchisation should be executed
base Polynomial basis
~DehierarchisationPolyClenshawCurtisBoundary()
sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::~DehierarchisationPolyClenshawCurtisBoundary ()
Destructor.
Member Function Documentation
operator()()
void sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::operator() (DataVector & source, DataVector & result, grid_iterator & index, size_t dim)
Implements operator() needed by the sweep class during the grid traversal.
This function is applied to the whole grid.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
References sgpp::base::HashGridIterator::getGridDepth(), rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToRightLevelZero(), and sgpp::base::HashGridIterator::seq().
rec()
void sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec (DataVector & source, DataVector & result, grid_iterator & index, size_t dim, DataVector & coeffs) protected
Recursive dehierarchisation algorithm, this algorithms works in-place -> source should be equal to result.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
coeffs nodal coefficients computed so far
References base, clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalHierToTop(), sgpp::base::HashGridIterator::get(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), and rec().
Member Data Documentation
base
SPolyClenshawCurtisBoundaryBase* sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::base protected
the base
Referenced by rec().
clenshawCurtisTable
ClenshawCurtisTable& sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::clenshawCurtisTable protected
clenshaw curtis points
Referenced by rec().
storage
GridStorage& sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::storage protected
the grid object
Referenced by rec().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationPolyClenshawCurtisBoundary.hpp
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationPolyClenshawCurtisBoundary.cpp