SG++-Doxygen-Documentation: sgpp::base::DistributionTruncExponential Class Reference
sgpp::base::DistributionTruncExponential Class Reference
#include <DistributionTruncExponential.hpp>
Public Member Functions
DistributionTruncExponential (double r=20, double lambda=1)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionTruncExponential ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Constructor & Destructor Documentation
DistributionTruncExponential()
sgpp::base::DistributionTruncExponential::DistributionTruncExponential (double r = 20, double lambda = 1) inline explicit
Constructor.
~DistributionTruncExponential()
virtual sgpp::base::DistributionTruncExponential::~DistributionTruncExponential () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionTruncExponential::eval (double x) inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionTruncExponential::getBounds () inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionTruncExponential::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionTruncExponential::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::TruncExponential.
sample()
double sgpp::base::DistributionTruncExponential::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionTruncExponential.hpp