SG++-Doxygen-Documentation: sgpp::optimization::test_problems::TestScalarFunction Class Reference
sgpp::optimization::test_problems::TestScalarFunction Class Reference abstract
Base class for analytical objective function examples ("test functions").
#include <TestScalarFunction.hpp>
Public Member Functions
double eval (const base::DataVector &x) override
Evaluate displaced function.
virtual double evalUndisplaced (const base::DataVector &x)=0
Pure virtual method for evaluating the undisplaced function.
const base::DataVector & getDisplacement () const
void setDisplacement (const base::DataVector &displacement)
TestScalarFunction (size_t d)
Constructor.
~TestScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void clone (std::unique_ptr< ScalarFunction > &clone) const =0
Pure virtual method for cloning the function.
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Protected Attributes
base::DataVector displacement
displacement vector
base::DataVector xTmp
temporary vector for displacing
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
Base class for analytical objective function examples ("test functions").
This class differs from ScalarFunction in the way that evaluation point \(\vec{x}\) are pseudorandomly displaced when calling the eval() function. Evaluting the undisplaced function must be implemented in evalUndisplaced. The displaced function is \(\vec{x} \mapsto f(\vec{x} + \vec{d})\) for a vector \(\vec{d}\) ("displacement").
Taking the average of results of multiple runs with different displacements makes results more robust and significant.
Constructor & Destructor Documentation
TestScalarFunction()
sgpp::optimization::test_problems::TestScalarFunction::TestScalarFunction (size_t d) explicit
Constructor.
The displacement is set to all zeros, so to displace the function call generateDisplacement() afterwards.
Parameters
d dimension of the domain
~TestScalarFunction()
sgpp::optimization::test_problems::TestScalarFunction::~TestScalarFunction () override
Destructor.
Member Function Documentation
eval()
double sgpp::optimization::test_problems::TestScalarFunction::eval (const base::DataVector & x) override virtual
Evaluate displaced function.
Parameters
x point \(\vec{x} \in \mathbb{R}^d\)
Returns
\(f(\vec{x} + \vec{d})\) with displacement \(\vec{d}\)
Implements sgpp::base::ScalarFunction.
References sgpp::base::ScalarFunction::d, displacement, evalUndisplaced(), and xTmp.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalUndisplaced()
virtual double sgpp::optimization::test_problems::TestScalarFunction::evalUndisplaced (const base::DataVector & x) pure virtual
Pure virtual method for evaluating the undisplaced function.
Parameters
x point \(\vec{x} \in \mathbb{R}^d\)
Returns
\(f(\vec{x})\)
Implemented in sgpp::optimization::test_problems::FloudasObjective, sgpp::optimization::test_problems::G03Objective, sgpp::optimization::test_problems::G04Objective, sgpp::optimization::test_problems::G04SquaredObjective, sgpp::optimization::test_problems::G05Objective, sgpp::optimization::test_problems::G06Objective, sgpp::optimization::test_problems::G08Objective, sgpp::optimization::test_problems::G09Objective, sgpp::optimization::test_problems::G10Objective, sgpp::optimization::test_problems::G11Objective, sgpp::optimization::test_problems::G12Objective, sgpp::optimization::test_problems::G13Objective, sgpp::optimization::test_problems::SimionescuObjective, sgpp::optimization::test_problems::SolandObjective, sgpp::optimization::test_problems::AbsoluteValueObjective, sgpp::optimization::test_problems::AckleyObjective, sgpp::optimization::test_problems::Alpine02Objective, sgpp::optimization::test_problems::BealeObjective, sgpp::optimization::test_problems::Branin01Objective, sgpp::optimization::test_problems::Branin02Objective, sgpp::optimization::test_problems::BubbleWrapObjective, sgpp::optimization::test_problems::EasomYangObjective, sgpp::optimization::test_problems::EggholderObjective, sgpp::optimization::test_problems::GoldsteinPriceObjective, sgpp::optimization::test_problems::GriewankObjective, sgpp::optimization::test_problems::Hartman3Objective, sgpp::optimization::test_problems::Hartman6Objective, sgpp::optimization::test_problems::HimmelblauObjective, sgpp::optimization::test_problems::HoelderTableObjective, sgpp::optimization::test_problems::IncreasingPowerObjective, sgpp::optimization::test_problems::MichalewiczObjective, sgpp::optimization::test_problems::MladineoObjective, sgpp::optimization::test_problems::PermObjective, sgpp::optimization::test_problems::RastriginObjective, sgpp::optimization::test_problems::RosenbrockObjective, sgpp::optimization::test_problems::Schwefel06Objective, sgpp::optimization::test_problems::Schwefel22Objective, sgpp::optimization::test_problems::Schwefel26Objective, sgpp::optimization::test_problems::SHCBObjective, sgpp::optimization::test_problems::SphereObjective, and sgpp::optimization::test_problems::TremblingParabolaObjective.
Referenced by eval().
getDisplacement()
const base::DataVector & sgpp::optimization::test_problems::TestScalarFunction::getDisplacement () const
Returns
currently used displacement
References displacement.
setDisplacement()
void sgpp::optimization::test_problems::TestScalarFunction::setDisplacement (const base::DataVector & displacement)
Parameters
displacement currently used displacement
References displacement.
Referenced by sgpp::optimization::test_problems::ConstrainedTestProblem::generateDisplacement(), sgpp::optimization::test_problems::UnconstrainedTestProblem::generateDisplacement(), sgpp::optimization::test_problems::ConstrainedTestProblem::setDisplacement(), and sgpp::optimization::test_problems::UnconstrainedTestProblem::setDisplacement().
Member Data Documentation
displacement
base::DataVector sgpp::optimization::test_problems::TestScalarFunction::displacement protected
displacement vector
Referenced by eval(), getDisplacement(), and setDisplacement().
xTmp
base::DataVector sgpp::optimization::test_problems::TestScalarFunction::xTmp protected
temporary vector for displacing
Referenced by eval().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/TestScalarFunction.hpp
optimization/src/sgpp/optimization/test_problems/TestScalarFunction.cpp