SG++-Doxygen-Documentation: sgpp::base::DistributionsVector Class Reference
sgpp::base::DistributionsVector Class Reference
#include <DistributionsVector.hpp>
Public Member Functions
void clear ()
DistributionsVector ()
DistributionsVector (const DistributionsVector &other)
DistributionsVector (size_t dim)
DistributionsVector (size_t dim, std::shared_ptr< sgpp::base::Distribution > pdf)
std::shared_ptr< sgpp::base::Distribution > get (size_t i)
sgpp::base::DataMatrix getBounds () const
std::vector< std::shared_ptr< sgpp::base::Distribution > > getDistributions ()
size_t getSize () const
void push_back (std::shared_ptr< sgpp::base::Distribution > pdf)
sgpp::base::DataVector sample () const
virtual ~DistributionsVector ()
Constructor & Destructor Documentation
DistributionsVector() [1/4]
sgpp::base::DistributionsVector::DistributionsVector ()
DistributionsVector() [2/4]
sgpp::base::DistributionsVector::DistributionsVector (size_t dim) explicit
DistributionsVector() [3/4]
sgpp::base::DistributionsVector::DistributionsVector (size_t dim, std::shared_ptr< sgpp::base::Distribution > pdf)
DistributionsVector() [4/4]
sgpp::base::DistributionsVector::DistributionsVector (const DistributionsVector & other)
~DistributionsVector()
sgpp::base::DistributionsVector::~DistributionsVector () virtual
Member Function Documentation
clear()
void sgpp::base::DistributionsVector::clear ()
get()
std::shared_ptr< sgpp::base::Distribution > sgpp::base::DistributionsVector::get (size_t i)
Referenced by sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakPBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature(), sgpp::datadriven::PolynomialChaosExpansion::evalExpansion(), sgpp::datadriven::PolynomialChaosExpansion::getL2Error(), and sgpp::datadriven::PolynomialChaosExpansion::PolynomialChaosExpansion().
getBounds()
sgpp::base::DataMatrix sgpp::base::DistributionsVector::getBounds () const
References getBounds(), and sgpp::base::DataMatrix::setRow().
Referenced by python.uq.dists.J.J::discretize(), getBounds(), python.uq.dists.Dist.Dist::l2error(), and sgpp::base::VectorDistributionRefinementFunctor::VectorDistributionRefinementFunctor().
getDistributions()
std::vector< std::shared_ptr< sgpp::base::Distribution > > sgpp::base::DistributionsVector::getDistributions ()
Referenced by python.uq.parameters.ParameterSet.ParameterSet::getIndependentJointDistribution().
getSize()
size_t sgpp::base::DistributionsVector::getSize () const
Referenced by python.uq.uq_setting.UQSetting.UQSetting::convert(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), sgpp::datadriven::PolynomialChaosExpansion::PolynomialChaosExpansion(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution(), and sgpp::base::VectorDistributionRefinementFunctor::VectorDistributionRefinementFunctor().
push_back()
void sgpp::base::DistributionsVector::push_back (std::shared_ptr< sgpp::base::Distribution > pdf)
Referenced by sgpp::datadriven::PolynomialChaosExpansion::PolynomialChaosExpansion().
sample()
sgpp::base::DataVector sgpp::base::DistributionsVector::sample () const
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList(), sgpp::datadriven::PolynomialChaosExpansion::getL2Error(), and sgpp::base::VectorDistributionRefinementFunctor::VectorDistributionRefinementFunctor().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/DistributionsVector.hpp
base/src/sgpp/base/tools/DistributionsVector.cpp