SG++-Doxygen-Documentation: sgpp::datadriven::OperationRosenblattTransformationPoly Class Reference
sgpp::datadriven::OperationRosenblattTransformationPoly Class Reference
keep applying marginalize to function until it's reduced to only 1 dimension
#include <OperationRosenblattTransformationPoly.hpp>
Public Member Functions
void doTransformation (base::DataVector *alpha, base::DataMatrix *points, base::DataMatrix *pointscdf)
Transformation with mixed starting dimensions.
void doTransformation (base::DataVector *alpha, base::DataMatrix *points, base::DataMatrix *pointscdf, size_t dim_start)
Transformation with specified starting dimension.
OperationRosenblattTransformationPoly (base::Grid *grid)
virtual ~OperationRosenblattTransformationPoly ()
Public Member Functions inherited from sgpp::datadriven::OperationRosenblattTransformation
OperationRosenblattTransformation ()
virtual ~OperationRosenblattTransformation ()
Protected Member Functions
virtual double doTransformation1D (base::Grid *grid1d, base::DataVector *alpha1d, double coord1d)
void doTransformation_in_next_dim (base::Grid *g_in, base::DataVector *a_in, size_t dim_x, base::DataVector *coords1d, base::DataVector *cdfs1d, size_t &curr_dim)
void doTransformation_start_dimX (base::Grid *g_in, base::DataVector *a_in, size_t dim_start, base::DataVector *coords1d, base::DataVector *cdfs1d)
Protected Attributes
base::Grid * grid
Detailed Description
keep applying marginalize to function until it's reduced to only 1 dimension
Constructor & Destructor Documentation
OperationRosenblattTransformationPoly()
sgpp::datadriven::OperationRosenblattTransformationPoly::OperationRosenblattTransformationPoly (base::Grid * grid) inline explicit
~OperationRosenblattTransformationPoly()
virtual sgpp::datadriven::OperationRosenblattTransformationPoly::~OperationRosenblattTransformationPoly () inline virtual
Member Function Documentation
doTransformation() [1/2]
void sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation (base::DataVector * alpha, base::DataMatrix * points, base::DataMatrix * pointscdf) virtual
Transformation with mixed starting dimensions.
Parameters
alpha Coefficient vector for current grid
points Input Matrix
pointscdf Output Matrix
Implements sgpp::datadriven::OperationRosenblattTransformation.
References alpha, sgpp::op_factory::createOperationDensityMargTo1D(), doTransformation1D(), doTransformation_start_dimX(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid, sgpp::base::DataMatrix::set(), and sgpp::base::DataMatrix::setRow().
doTransformation() [2/2]
void sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation (base::DataVector * alpha, base::DataMatrix * points, base::DataMatrix * pointscdf, size_t dim_start) virtual
Transformation with specified starting dimension.
Parameters
alpha Coefficient vector for current grid
points Input Matrix
pointscdf Output Matrix
dim_start Starting dimension
Implements sgpp::datadriven::OperationRosenblattTransformation.
References alpha, sgpp::op_factory::createOperationDensityMargTo1D(), doTransformation1D(), doTransformation_start_dimX(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid, sgpp::base::DataMatrix::set(), and sgpp::base::DataMatrix::setRow().
doTransformation1D()
double sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation1D (base::Grid * grid1d, base::DataVector * alpha1d, double coord1d) protected virtual
References sgpp::op_factory::createOperationRosenblattTransformation1D().
Referenced by doTransformation(), doTransformation(), and doTransformation_in_next_dim().
doTransformation_in_next_dim()
void sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim (base::Grid * g_in, base::DataVector * a_in, size_t dim_x, base::DataVector * coords1d, base::DataVector * cdfs1d, size_t & curr_dim) protected
References sgpp::op_factory::createOperationDensityConditional(), sgpp::op_factory::createOperationDensityMargTo1D(), sgpp::datadriven::OperationDensityConditional::doConditional(), doTransformation1D(), doTransformation_in_next_dim(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataVector::getSize(), sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), and sgpp::base::DataVector::set().
Referenced by doTransformation_in_next_dim(), and doTransformation_start_dimX().
doTransformation_start_dimX()
void sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_start_dimX (base::Grid * g_in, base::DataVector * a_in, size_t dim_start, base::DataVector * coords1d, base::DataVector * cdfs1d) protected
References doTransformation_in_next_dim(), and sgpp::base::DataVector::getSize().
Referenced by doTransformation(), and doTransformation().
Member Data Documentation
grid
base::Grid* sgpp::datadriven::OperationRosenblattTransformationPoly::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), doTransformation(), doTransformation(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRosenblattTransformationPoly.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRosenblattTransformationPoly.cpp