SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T > Class Template Reference
OpenCL kernel class for operation to create a k nearest neighbor graph.
#include <KernelCreateGraph.hpp>
Public Member Functions
void begin_graph_creation (size_t startid, size_t chunksize)
Runs the opencl kernel to find the k nearest neighbors of all datapoints in the given chunk.
double finalize_graph_creation (std::vector< int > &result, size_t startid, size_t chunksize)
KernelCreateGraph (std::shared_ptr< base::OCLDevice > dev, size_t dims, size_t k, std::vector< T > &data, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node &kernelConfiguration)
~KernelCreateGraph ()
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
Adds all possible building parameters to the configuration if they do not exist yet.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >
OpenCL kernel class for operation to create a k nearest neighbor graph.
Constructor & Destructor Documentation
KernelCreateGraph()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::KernelCreateGraph (std::shared_ptr< base::OCLDevice > dev, size_t dims, size_t k, std::vector< T > & data, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node & kernelConfiguration) inline
References json::Node::contains(), json::Node::getBool(), json::Node::getUInt(), and sgpp::base::OCLBufferWrapperSD< T >::intializeTo().
~KernelCreateGraph()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::~KernelCreateGraph () inline
Member Function Documentation
augmentDefaultParameters()
template<typename T > static void sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
Adds all possible building parameters to the configuration if they do not exist yet.
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters().
begin_graph_creation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation (size_t startid, size_t chunksize) inline
Runs the opencl kernel to find the k nearest neighbors of all datapoints in the given chunk.
References sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderCreateGraph< real_type >::generateSource(), sgpp::base::OCLBufferWrapperSD< T >::getBuffer(), sgpp::base::OCLBufferWrapperSD< T >::initializeBuffer(), and sgpp::base::OCLBufferWrapperSD< T >::isInitialized().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::begin_graph_creation(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::create_graph().
finalize_graph_creation()
template<typename T > double sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::finalize_graph_creation (std::vector< int > & result, size_t startid, size_t chunksize) inline
References sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), and sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::create_graph(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::finalize_graph_creation().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationCreateGraphOCL/KernelCreateGraph.hpp