SG++-Doxygen-Documentation: sgpp::base::OperationArbitraryBoundaryHierarchisation Class Reference
sgpp::base::OperationArbitraryBoundaryHierarchisation Class Reference
This class implements the hierarchisation and dehierarchisation on sparse grids which do not have a grid point at the boundary in each direction for every inner point (boundaryLevel > 1)
#include <OperationArbitraryBoundaryHierarchisation.hpp>
Public Member Functions
void doDehierarchisation (DataVector &alpha)
Implements the dehierarchisation on a sparse grid.
void doHierarchisation (DataVector &nodal_values)
Implements the hierarchisation on a sparse grid.
OperationArbitraryBoundaryHierarchisation (Grid &grid)
Constructor.
virtual ~OperationArbitraryBoundaryHierarchisation ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationHierarchisation
OperationHierarchisation ()
Constructor.
virtual ~OperationHierarchisation ()
Destructor.
Detailed Description
This class implements the hierarchisation and dehierarchisation on sparse grids which do not have a grid point at the boundary in each direction for every inner point (boundaryLevel > 1)
Constructor & Destructor Documentation
OperationArbitraryBoundaryHierarchisation()
sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation (Grid & grid) explicit
Constructor.
Parameters
grid Grid which is to be used for hierarchisation
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::Grid::createGrid(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), sgpp::base::HashGridStorage::insert(), sgpp::base::HashGridPoint::isInnerPoint(), sgpp::base::GeneralGridConfiguration::maxDegree_, and sgpp::base::GeneralGridConfiguration::type_.
~OperationArbitraryBoundaryHierarchisation()
sgpp::base::OperationArbitraryBoundaryHierarchisation::~OperationArbitraryBoundaryHierarchisation () virtual
Destructor.
Member Function Documentation
doDehierarchisation()
void sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation (DataVector & alpha) virtual
Implements the dehierarchisation on a sparse grid.
Parameters
alpha the coefficients of the sparse grid's basis functions
Implements sgpp::base::OperationHierarchisation.
References alpha, sgpp::base::HashGridStorage::getCoordinateArrays(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridStorage::getSize(), and sgpp::base::HashGridPoint::isInnerPoint().
doHierarchisation()
void sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation (DataVector & nodal_values) virtual
Implements the hierarchisation on a sparse grid.
Parameters
nodal_values the function's values in the nodal basis
Implements sgpp::base::OperationHierarchisation.
References sgpp::op_factory::createOperationHierarchisation(), sgpp::base::HashGridStorage::getCoordinateArrays(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridStorage::getSize(), sgpp::base::HashGridPoint::isInnerPoint(), and sgpp::base::DataVector::sub().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationArbitraryBoundaryHierarchisation.hpp
base/src/sgpp/base/operation/hash/OperationArbitraryBoundaryHierarchisation.cpp