SG++-Doxygen-Documentation: sgpp::optimization::optimizer::GradientDescent Class Reference
sgpp::optimization::optimizer::GradientDescent Class Reference
Gradient-based method of steepest descent.
#include <GradientDescent.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getBeta () const
double getEpsilon () const
double getGamma () const
double getTolerance () const
GradientDescent (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, size_t maxItCount=DEFAULT_MAX_IT_COUNT, double beta=DEFAULT_BETA, double gamma=DEFAULT_GAMMA, double tolerance=DEFAULT_TOLERANCE, double epsilon=DEFAULT_EPSILON)
Constructor.
GradientDescent (const GradientDescent &other)
Copy constructor.
void optimize () override
Pure virtual method for optimization of the objective function.
void setBeta (double beta)
void setEpsilon (double epsilon)
void setGamma (double gamma)
void setTolerance (double tolerance)
~GradientDescent () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_BETA = 0.5
default beta (parameter for Armijo's rule)
static constexpr double DEFAULT_EPSILON = 1e-18
default epsilon (parameter for Armijo's rule)
static constexpr double DEFAULT_GAMMA = 1e-2
default gamma (parameter for Armijo's rule)
static const size_t DEFAULT_MAX_IT_COUNT = 2000
default maximal number of iterations
static constexpr double DEFAULT_TOLERANCE = 1e-8
default tolerance (parameter for Armijo's rule)
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double beta
beta (parameter for Armijo's rule)
double eps
epsilon (parameter for Armijo's rule)
double gamma
gamma (parameter for Armijo's rule)
double tol
tolerance (parameter for Armijo's rule)
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Gradient-based method of steepest descent.
Constructor & Destructor Documentation
GradientDescent() [1/2]
sgpp::optimization::optimizer::GradientDescent::GradientDescent (const base::ScalarFunction & f, const base::ScalarFunctionGradient & fGradient, size_t maxItCount = DEFAULT_MAX_IT_COUNT, double beta = DEFAULT_BETA, double gamma = DEFAULT_GAMMA, double tolerance = DEFAULT_TOLERANCE, double epsilon = DEFAULT_EPSILON)
Constructor.
Parameters
f objective function
fGradient objective function gradient
maxItCount maximal number of iterations
beta beta (parameter for Armijo's rule)
gamma gamma (parameter for Armijo's rule)
tolerance tolerance (parameter for Armijo's rule)
epsilon epsilon (parameter for Armijo's rule)
GradientDescent() [2/2]
sgpp::optimization::optimizer::GradientDescent::GradientDescent (const GradientDescent & other)
Copy constructor.
Parameters
other optimizer to be copied
~GradientDescent()
sgpp::optimization::optimizer::GradientDescent::~GradientDescent () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::GradientDescent::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getBeta()
double sgpp::optimization::optimizer::GradientDescent::getBeta () const
Returns
beta (parameter for Armijo's rule)
References beta.
getEpsilon()
double sgpp::optimization::optimizer::GradientDescent::getEpsilon () const
Returns
epsilon (parameter for Armijo's rule)
References eps.
getGamma()
double sgpp::optimization::optimizer::GradientDescent::getGamma () const
Returns
gamma (parameter for Armijo's rule)
References gamma.
getTolerance()
double sgpp::optimization::optimizer::GradientDescent::getTolerance () const
Returns
tolerance (parameter for Armijo's rule)
References tol.
optimize()
void sgpp::optimization::optimizer::GradientDescent::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), beta, eps, sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, gamma, sgpp::base::Printer::getInstance(), sgpp::optimization::optimizer::lineSearchArmijo(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), tol, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
Referenced by sgpp::optimization::SplineResponseSurface::optimize().
setBeta()
void sgpp::optimization::optimizer::GradientDescent::setBeta (double beta)
Parameters
beta beta (parameter for Armijo's rule)
References beta.
setEpsilon()
void sgpp::optimization::optimizer::GradientDescent::setEpsilon (double epsilon)
Parameters
epsilon epsilon (parameter for Armijo's rule)
References eps.
setGamma()
void sgpp::optimization::optimizer::GradientDescent::setGamma (double gamma)
Parameters
gamma gamma (parameter for Armijo's rule)
References gamma.
setTolerance()
void sgpp::optimization::optimizer::GradientDescent::setTolerance (double tolerance)
Parameters
tolerance tolerance (parameter for Armijo's rule)
References tol.
Member Data Documentation
beta
double sgpp::optimization::optimizer::GradientDescent::beta protected
beta (parameter for Armijo's rule)
Referenced by getBeta(), optimize(), and setBeta().
DEFAULT_BETA
constexpr double sgpp::optimization::optimizer::GradientDescent::DEFAULT_BETA = 0.5 static constexpr
default beta (parameter for Armijo's rule)
DEFAULT_EPSILON
constexpr double sgpp::optimization::optimizer::GradientDescent::DEFAULT_EPSILON = 1e-18 static constexpr
default epsilon (parameter for Armijo's rule)
DEFAULT_GAMMA
constexpr double sgpp::optimization::optimizer::GradientDescent::DEFAULT_GAMMA = 1e-2 static constexpr
default gamma (parameter for Armijo's rule)
DEFAULT_MAX_IT_COUNT
const size_t sgpp::optimization::optimizer::GradientDescent::DEFAULT_MAX_IT_COUNT = 2000 static
default maximal number of iterations
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::GradientDescent::DEFAULT_TOLERANCE = 1e-8 static constexpr
default tolerance (parameter for Armijo's rule)
eps
double sgpp::optimization::optimizer::GradientDescent::eps protected
epsilon (parameter for Armijo's rule)
Referenced by getEpsilon(), optimize(), and setEpsilon().
gamma
double sgpp::optimization::optimizer::GradientDescent::gamma protected
gamma (parameter for Armijo's rule)
Referenced by getGamma(), optimize(), and setGamma().
tol
double sgpp::optimization::optimizer::GradientDescent::tol protected
tolerance (parameter for Armijo's rule)
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/GradientDescent.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/GradientDescent.cpp