SG++-Doxygen-Documentation: sgpp::datadriven::OperationMultiEvalStreaming Class Reference
sgpp::datadriven::OperationMultiEvalStreaming Class Reference
#include <OperationMultiEvalStreaming.hpp>
Public Member Functions
size_t getChunkDataPoints ()
size_t getChunkGridPoints ()
double getDuration () override
void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (sgpp::base::DataVector &source, sgpp::base::DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
OperationMultiEvalStreaming (base::Grid &grid, base::DataMatrix &dataset)
void prepare () override
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
~OperationMultiEvalStreaming () override
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual std::string getImplementationName ()
Name of this implementation of the operation.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual ~OperationMultipleEval ()
Destructor.
Protected Attributes
double duration
sgpp::base::DataMatrix * index_ = nullptr
Member to store the sparse grid's indices for better vectorization.
sgpp::base::DataMatrix * level_ = nullptr
Member to store the sparse grid's levels for better vectorization.
sgpp::base::SGppStopwatch myTimer_
Timer object to handle time measurements.
sgpp::base::DataMatrix preparedDataset
base::GridStorage * storage
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Constructor & Destructor Documentation
OperationMultiEvalStreaming()
sgpp::datadriven::OperationMultiEvalStreaming::OperationMultiEvalStreaming (base::Grid & grid, base::DataMatrix & dataset)
References sgpp::base::Grid::getStorage(), prepare(), preparedDataset, storage, and sgpp::base::DataMatrix::transpose().
~OperationMultiEvalStreaming()
sgpp::datadriven::OperationMultiEvalStreaming::~OperationMultiEvalStreaming () override
References index_, and level_.
Member Function Documentation
getChunkDataPoints()
size_t sgpp::datadriven::OperationMultiEvalStreaming::getChunkDataPoints ()
References STREAMING_LINEAR_MIC_AVX512_UNROLLING_WIDTH.
Referenced by mult().
getChunkGridPoints()
size_t sgpp::datadriven::OperationMultiEvalStreaming::getChunkGridPoints ()
getDuration()
double sgpp::datadriven::OperationMultiEvalStreaming::getDuration () override virtual
Implements sgpp::base::OperationMultipleEval.
References duration.
mult()
void sgpp::datadriven::OperationMultiEvalStreaming::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) override virtual
Multiplication of \(B^T\) with vector \(\alpha\).
Parameters
alpha vector, to which \(B\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References alpha, duration, getChunkDataPoints(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataVector::getSize(), index_, level_, myTimer_, preparedDataset, sgpp::base::DataVector::setAll(), sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
multTranspose()
void sgpp::datadriven::OperationMultiEvalStreaming::multTranspose (sgpp::base::DataVector & source, sgpp::base::DataVector & result) override virtual
Multiplication of \(B\) with vector \(\alpha\).
Parameters
source vector, to which \(B^T\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References duration, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataVector::getSize(), sgpp::base::HashGridStorage::getSize(), index_, level_, myTimer_, preparedDataset, sgpp::base::DataVector::setAll(), sgpp::base::SGppStopwatch::start(), sgpp::base::SGppStopwatch::stop(), and storage.
prepare()
void sgpp::datadriven::OperationMultiEvalStreaming::prepare () override virtual
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
This function is by default called with each "mult()", "multTranspose()" or evaluation operation and can be ignored from an external perspective. This is not overridden by every kernel.
Reimplemented from sgpp::base::OperationMultipleEval.
Referenced by OperationMultiEvalStreaming().
Member Data Documentation
duration
double sgpp::datadriven::OperationMultiEvalStreaming::duration protected
Referenced by getDuration(), mult(), and multTranspose().
index_
sgpp::base::DataMatrix* sgpp::datadriven::OperationMultiEvalStreaming::index_ = nullptr protected
Member to store the sparse grid's indices for better vectorization.
Referenced by mult(), multTranspose(), and ~OperationMultiEvalStreaming().
level_
sgpp::base::DataMatrix* sgpp::datadriven::OperationMultiEvalStreaming::level_ = nullptr protected
Member to store the sparse grid's levels for better vectorization.
Referenced by mult(), multTranspose(), and ~OperationMultiEvalStreaming().
myTimer_
sgpp::base::SGppStopwatch sgpp::datadriven::OperationMultiEvalStreaming::myTimer_ protected
Timer object to handle time measurements.
Referenced by mult(), and multTranspose().
preparedDataset
sgpp::base::DataMatrix sgpp::datadriven::OperationMultiEvalStreaming::preparedDataset protected
Referenced by mult(), multTranspose(), and OperationMultiEvalStreaming().
storage
base::GridStorage* sgpp::datadriven::OperationMultiEvalStreaming::storage protected
Referenced by multTranspose(), and OperationMultiEvalStreaming().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultiEvalStreaming/OperationMultiEvalStreaming.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultiEvalStreaming/OperationMultiEvalStreaming.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultiEvalStreaming/OperationMultiEvalStreaming_multTransposeImpl.cpp