SG++-Doxygen-Documentation: sgpp::base::OperationHierarchisationPrewavelet Class Reference
sgpp::base::OperationHierarchisationPrewavelet Class Reference
Hierarchisation on sparse grid with prewavelets and no boundary.
#include <OperationHierarchisationPrewavelet.hpp>
Public Member Functions
void doDehierarchisation (DataVector &alpha) override
Implements the dehierarchisation on a sparse grid.
void doHierarchisation (DataVector &node_values) override
Implements the hierarchisation on a sparse grid.
OperationHierarchisationPrewavelet (GridStorage &storage, GridStorage &shadowStorage)
Constructor of OperationHierarchisationPrewavelet.
~OperationHierarchisationPrewavelet () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationHierarchisation
OperationHierarchisation ()
Constructor.
virtual ~OperationHierarchisation ()
Destructor.
Protected Member Functions
void expandGrid ()
void shrinkGrid ()
Protected Attributes
GridStorage & shadowStorage
GridStorage & storage
reference to the grid's GridStorage object
Detailed Description
Hierarchisation on sparse grid with prewavelets and no boundary.
Please note, that there is no efficient way to directly calculate the hierarchical surpluses for the prewavelet base. But there is a fast and efficient way to transform hierarchical surpluses of the normal linear ansatzfunctions into the prewavelet base and vice versa. Thus, we use the normal hierarchisation of the linear basis and afterwards transform the resulting Vector into prewavelets (see ConvertLinearToPrewavelet.hpp). For the Dehierarchisation, this process is reversed (see ConvertPrewaveletToLinear.hpp)
Constructor & Destructor Documentation
OperationHierarchisationPrewavelet()
sgpp::base::OperationHierarchisationPrewavelet::OperationHierarchisationPrewavelet (GridStorage & storage, GridStorage & shadowStorage) inline
Constructor of OperationHierarchisationPrewavelet.
An adaptive grid with prewavelet ansatz functions requires for operations using the up-down algorithm shadow points. These shadow points a needed just for data transport, thus they do not have an influence on the final function. Please refer to sgpp::pde::UpDownOneOpDimWithShadow for more information.
Parameters
storage Pointer to the grid's gridstorage obejct
shadowStorage shadow points (see detailed description)
~OperationHierarchisationPrewavelet()
sgpp::base::OperationHierarchisationPrewavelet::~OperationHierarchisationPrewavelet () inline override
Destructor.
Member Function Documentation
doDehierarchisation()
void sgpp::base::OperationHierarchisationPrewavelet::doDehierarchisation (DataVector & alpha) override virtual
Implements the dehierarchisation on a sparse grid.
Parameters
alpha the coefficients of the sparse grid's basis functions
Implements sgpp::base::OperationHierarchisation.
References alpha, sgpp::base::HashGridStorage::getDimension(), storage, and sgpp::base::sweep< FUNC >::sweep1D().
doHierarchisation()
void sgpp::base::OperationHierarchisationPrewavelet::doHierarchisation (DataVector & node_values) override virtual
Implements the hierarchisation on a sparse grid.
Parameters
node_values the function's values in the nodal basis
Implements sgpp::base::OperationHierarchisation.
References sgpp::base::HashGridStorage::getDimension(), shadowStorage, storage, and sgpp::base::sweep< FUNC >::sweep1D().
expandGrid()
void sgpp::base::OperationHierarchisationPrewavelet::expandGrid () protected
References sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), sgpp::base::HashGridStorage::insert(), sgpp::base::HashGridPoint::isLeaf(), shadowStorage, storage, and sgpp::base::HashGridPoint::toString().
shrinkGrid()
void sgpp::base::OperationHierarchisationPrewavelet::shrinkGrid () protected
References sgpp::base::HashGridStorage::deleteLast(), sgpp::base::HashGridStorage::getSize(), shadowStorage, and storage.
Member Data Documentation
shadowStorage
GridStorage& sgpp::base::OperationHierarchisationPrewavelet::shadowStorage protected
Referenced by doHierarchisation(), expandGrid(), and shrinkGrid().
storage
GridStorage& sgpp::base::OperationHierarchisationPrewavelet::storage protected
reference to the grid's GridStorage object
Referenced by doDehierarchisation(), doHierarchisation(), expandGrid(), and shrinkGrid().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationHierarchisationPrewavelet.hpp
base/src/sgpp/base/operation/hash/OperationHierarchisationPrewavelet.cpp