SG++-Doxygen-Documentation: sgpp::base::CoarseningFunctor Class Reference
sgpp::base::CoarseningFunctor Class Reference abstract
Abstract class that defines the interfaces that coarsening functors have to provide.
#include <CoarseningFunctor.hpp>
Public Types
typedef double value_type
Public Member Functions
CoarseningFunctor ()
Constructor.
virtual double getCoarseningThreshold () const =0
Returns the threshold value.
virtual size_t getRemovementsNum () const
Returns the maximal number of points that should be removed.
virtual double operator() (GridStorage &storage, size_t seq)=0
This should be returning a coarsening value for every grid point.
virtual double start () const =0
This should return the initial value of coarsening criterion (e.g.
virtual ~CoarseningFunctor ()
Destructor.
Detailed Description
Abstract class that defines the interfaces that coarsening functors have to provide.
Member Typedef Documentation
value_type
typedef double sgpp::base::CoarseningFunctor::value_type
Constructor & Destructor Documentation
CoarseningFunctor()
sgpp::base::CoarseningFunctor::CoarseningFunctor () inline
Constructor.
~CoarseningFunctor()
virtual sgpp::base::CoarseningFunctor::~CoarseningFunctor () inline virtual
Destructor.
Member Function Documentation
getCoarseningThreshold()
virtual double sgpp::base::CoarseningFunctor::getCoarseningThreshold () const pure virtual
Returns the threshold value.
Only the grid points with absolute value of coarsening criterion (e.g. alpha) less or equal to this threshold will be removed
Returns
threshold value for refinement. Default value: 0.
Implemented in sgpp::base::SurplusCoarseningFunctor, and sgpp::base::SurplusVolumeCoarseningFunctor.
Referenced by sgpp::base::HashCoarsening::free_coarsen_NFirstOnly().
getRemovementsNum()
virtual size_t sgpp::base::CoarseningFunctor::getRemovementsNum () const inline virtual
Returns the maximal number of points that should be removed.
The maximal number of points to removed is set in the constructor of implementation class.
Returns
number of points that should removed. Default value: 1.
Reimplemented in sgpp::base::SurplusCoarseningFunctor, and sgpp::base::SurplusVolumeCoarseningFunctor.
Referenced by sgpp::base::HashCoarsening::free_coarsen_NFirstOnly().
operator()()
virtual double sgpp::base::CoarseningFunctor::operator() (GridStorage & storage, size_t seq) pure virtual
This should be returning a coarsening value for every grid point.
The point with the lowest value will be removed first.
Parameters
storage reference to the grids storage object
seq sequence number in the coefficients array
Returns
refinement value
Implemented in sgpp::base::SurplusCoarseningFunctor, and sgpp::base::SurplusVolumeCoarseningFunctor.
start()
virtual double sgpp::base::CoarseningFunctor::start () const pure virtual
This should return the initial value of coarsening criterion (e.g.
alpha or error).
Returns
the initial value
Implemented in sgpp::base::SurplusCoarseningFunctor, and sgpp::base::SurplusVolumeCoarseningFunctor.
Referenced by sgpp::base::HashCoarsening::free_coarsen_NFirstOnly().
The documentation for this class was generated from the following file:
base/src/sgpp/base/grid/generation/functors/CoarseningFunctor.hpp