SG++-Doxygen-Documentation: sgpp::datadriven::LearnerBaseSP Class Reference
sgpp::datadriven::LearnerBaseSP Class Reference abstract
Abstract class that implements a regression/classification learner based on spatial adaptive Sparse Grids.
#include <LearnerBaseSP.hpp>
Public Member Functions
void dumpFunction (std::string tFilename, size_t resolution)
simple dump of sparse grid function into file, e.g.
void dumpGrid (std::string tFilename)
simple dump of grid points into file, e.g.
virtual double getAccuracy (const sgpp::base::DataVectorSP &classesComputed, const sgpp::base::DataVectorSP &classesReference, const float threshold=0.0)
compute the accuracy for given testDataset.
virtual double getAccuracy (sgpp::base::DataMatrixSP &testDataset, const sgpp::base::DataVectorSP &classesReference, const float threshold=0.0)
compute the accuracy for given testDataset.
virtual ClassificatorQuality getCassificatorQuality (const sgpp::base::DataVectorSP &classesComputed, const sgpp::base::DataVectorSP &classesReference, const float threshold=0.0)
compute the quality for given testDataset, classification ONLY!
virtual ClassificatorQuality getCassificatorQuality (sgpp::base::DataMatrixSP &testDataset, const sgpp::base::DataVectorSP &classesReference, const float threshold=0.0)
compute the quality for given testDataset, classification ONLY! test is automatically called in order to determine the regression values of the current learner
bool getIsRegression () const
determines the current mode
bool getIsVerbose () const
determines the current verbose mode of learner
LearnerBaseSP (const bool isRegression, const bool isVerbose=true)
Constructor.
LearnerBaseSP (const LearnerBaseSP &copyMe)
Copy-Constructor.
LearnerBaseSP (std::string tGridFilename, std::string tAlphaFilename, const bool isRegression, const bool isVerbose=true)
Constructor.
virtual sgpp::base::DataVectorSP predict (sgpp::base::DataMatrixSP &testDataset)
executes a Regression test for a given dataset and returns the result
void setIsVerbose (const bool isVerbose)
sets the current verbose mode of learner
void store (std::string tGridFilename, std::string tAlphaFilename)
store the grid and its current coefficients into files for further usage.
LearnerTiming train (sgpp::base::DataMatrixSP &testDataset, sgpp::base::DataVectorSP &classes, const sgpp::base::RegularGridConfiguration &gridConfig, const sgpp::solver::SLESolverSPConfiguration &SolverConfig, const float lambdaRegularization)
Learning a dataset with regular sparse grids.
virtual LearnerTiming train (sgpp::base::DataMatrixSP &testDataset, sgpp::base::DataVectorSP &classes, const sgpp::base::RegularGridConfiguration &gridConfig, const sgpp::solver::SLESolverSPConfiguration &SolverConfigRefine, const sgpp::solver::SLESolverSPConfiguration &SolverConfigFinal, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, bool testAccDuringAdapt, const float lambdaRegularization)
Learning a dataset with spatially adaptive sparse grids.
virtual ~LearnerBaseSP ()
Destructor.
Protected Member Functions
virtual sgpp::datadriven::DMSystemMatrixBaseSP * createDMSystem (sgpp::base::DataMatrixSP &trainDataset, float lambdaRegularization)=0
abstract method that constructs the corresponding system of linear equations Derived classes MUST overwrite this functions!
virtual void InitializeGrid (const sgpp::base::RegularGridConfiguration &gridConfig)
Initialize the grid and its coefficients.
virtual void postProcessing (const sgpp::base::DataMatrixSP &trainDataset, const sgpp::solver::SLESolverType &solver, const size_t numNeededIterations)
Hook-Method for post-processing after each refinement learning.
virtual void preProcessing ()
Hook-Method for pre-processing before starting learning.
Protected Attributes
sgpp::base::DataVectorSP * alpha_
the grid's coefficients
double execTime_
execution time
double GByte_
number of transferred Gbytes
double GFlop_
number of executed Floating Point operations
sgpp::base::Grid * grid_
sparse grid object
bool isRegression_
is regression selected
bool isTrained_
is the grid trained
bool isVerbose_
is verbose output enabled
Detailed Description
Abstract class that implements a regression/classification learner based on spatial adaptive Sparse Grids.
Furthermore this class is intended to provide a framework for adavanded regression and classification methods by allowing to override basic routines like train and test.
This versions supports single precision datatypes.
Constructor & Destructor Documentation
LearnerBaseSP() [1/3]
sgpp::datadriven::LearnerBaseSP::LearnerBaseSP (const bool isRegression, const bool isVerbose = true) explicit
Constructor.
Parameters
isRegression flag for regression
isVerbose flag for verbose output
LearnerBaseSP() [2/3]
sgpp::datadriven::LearnerBaseSP::LearnerBaseSP (std::string tGridFilename, std::string tAlphaFilename, const bool isRegression, const bool isVerbose = true)
Constructor.
Parameters
tGridFilename path to file that contains a serialized grid
tAlphaFilename path to file that contains the grid's coefficients
isRegression set to true if a regression task should be executed
isVerbose set to true in order to allow console output
LearnerBaseSP() [3/3]
sgpp::datadriven::LearnerBaseSP::LearnerBaseSP (const LearnerBaseSP & copyMe)
Copy-Constructor.
Parameters
copyMe LearnerBase that should be duplicated
References alpha_, execTime_, GByte_, GFlop_, grid_, isRegression_, isTrained_, sgpp::base::Grid::serialize(), and sgpp::base::Grid::unserialize().
~LearnerBaseSP()
sgpp::datadriven::LearnerBaseSP::~LearnerBaseSP () virtual
Destructor.
References alpha_, and grid_.
Member Function Documentation
createDMSystem()
virtual sgpp::datadriven::DMSystemMatrixBaseSP * sgpp::datadriven::LearnerBaseSP::createDMSystem (sgpp::base::DataMatrixSP & trainDataset, float lambdaRegularization) protected pure virtual
abstract method that constructs the corresponding system of linear equations Derived classes MUST overwrite this functions!
Parameters
trainDataset training dataset
lambdaRegularization lambda regularization parameter
Referenced by train().
dumpFunction()
void sgpp::datadriven::LearnerBaseSP::dumpFunction (std::string tFilename, size_t resolution)
simple dump of sparse grid function into file, e.g.
used to plot with gnuplot.
only executed if grid is trained and number of dimensions <= 2.
Parameters
tFilename filename to store the dump to
resolution resolution of function plot
References alpha_, sgpp::base::PrecisionConverter::convertDataVectorSPToDataVector(), sgpp::base::Grid::getDimension(), sgpp::base::DataVectorSP::getSize(), grid_, isTrained_, and sgpp::base::GridPrinter::printGrid().
dumpGrid()
void sgpp::datadriven::LearnerBaseSP::dumpGrid (std::string tFilename)
simple dump of grid points into file, e.g.
used to plot with gnuplot
only executed if grid is trained
Parameters
tFilename filename to store the dump to
References alpha_, sgpp::base::PrecisionConverter::convertDataVectorSPToDataVector(), sgpp::base::DataVectorSP::getSize(), grid_, isTrained_, and sgpp::base::GridPrinter::printSparseGrid().
getAccuracy() [1/2]
double sgpp::datadriven::LearnerBaseSP::getAccuracy (const sgpp::base::DataVectorSP & classesComputed, const sgpp::base::DataVectorSP & classesReference, const float threshold = 0.0) virtual
compute the accuracy for given testDataset.
In case if classification (isRegression == false) this routine returns the learner's accuracy In case of regressions (isRegression == true) this routine returns the learner's MSE
Parameters
classesComputed regression results of the test dataset
classesReference reference labels of the test dataset
threshold threshold used for classification, ignored when performing regressions
Returns
accuracy, percent or MSE, depending on the execution mode
References sgpp::base::DataVectorSP::get(), sgpp::base::DataVectorSP::getSize(), and isRegression_.
getAccuracy() [2/2]
double sgpp::datadriven::LearnerBaseSP::getAccuracy (sgpp::base::DataMatrixSP & testDataset, const sgpp::base::DataVectorSP & classesReference, const float threshold = 0.0) virtual
compute the accuracy for given testDataset.
test is automatically called in order to determine the regression values of the current learner
In case if classification (isRegression == false) this routine returns the learner's accuracy In case of regressions (isRegression == true) this routine returns the learner's MSE
Parameters
testDataset dataset to be tested
classesReference reference labels of the test dataset
threshold threshold used for classification, ignored when performing regressions
Returns
accuracy, percent or MSE, depending on the execution mode
References getAccuracy(), and predict().
Referenced by getAccuracy(), and train().
getCassificatorQuality() [1/2]
ClassificatorQuality sgpp::datadriven::LearnerBaseSP::getCassificatorQuality (const sgpp::base::DataVectorSP & classesComputed, const sgpp::base::DataVectorSP & classesReference, const float threshold = 0.0) virtual
compute the quality for given testDataset, classification ONLY!
Parameters
classesComputed regression results of the test dataset
classesReference reference labels of the test dataset
threshold threshold used for classification, ignored when performing regressions
Returns
quality structure containing tp, tn, fp, fn counts
References sgpp::datadriven::ClassificatorQuality::falseNegative_, sgpp::datadriven::ClassificatorQuality::falsePositive_, sgpp::base::DataVectorSP::get(), sgpp::base::DataVectorSP::getSize(), isRegression_, sgpp::datadriven::ClassificatorQuality::trueNegative_, and sgpp::datadriven::ClassificatorQuality::truePositive_.
getCassificatorQuality() [2/2]
ClassificatorQuality sgpp::datadriven::LearnerBaseSP::getCassificatorQuality (sgpp::base::DataMatrixSP & testDataset, const sgpp::base::DataVectorSP & classesReference, const float threshold = 0.0) virtual
compute the quality for given testDataset, classification ONLY! test is automatically called in order to determine the regression values of the current learner
Parameters
testDataset dataset to be tested
classesReference reference labels of the test dataset
threshold threshold used for classification, ignored when performing regressions
Returns
quality structure containing tp, tn, fp, fn counts
References getCassificatorQuality(), and predict().
Referenced by getCassificatorQuality().
getIsRegression()
bool sgpp::datadriven::LearnerBaseSP::getIsRegression () const
determines the current mode
Returns
returns whether the current mode is regression or not
References isRegression_.
getIsVerbose()
bool sgpp::datadriven::LearnerBaseSP::getIsVerbose () const
determines the current verbose mode of learner
Returns
returns whether the current learner has verbose output
References isVerbose_.
InitializeGrid()
void sgpp::datadriven::LearnerBaseSP::InitializeGrid (const sgpp::base::RegularGridConfiguration & gridConfig) protected virtual
Initialize the grid and its coefficients.
Parameters
gridConfig structure which describes the regular start grid
References alpha_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::Grid::getGenerator(), sgpp::base::Grid::getSize(), grid_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::ModLinear, sgpp::base::GridGenerator::regular(), sgpp::base::DataVectorSP::setAll(), and sgpp::base::GeneralGridConfiguration::type_.
Referenced by train().
postProcessing()
void sgpp::datadriven::LearnerBaseSP::postProcessing (const sgpp::base::DataMatrixSP & trainDataset, const sgpp::solver::SLESolverType & solver, const size_t numNeededIterations) protected virtual
Hook-Method for post-processing after each refinement learning.
can be overwritten by derived classes
Parameters
trainDataset matrix with training data set
solver solver
numNeededIterations number of required iterations
References execTime_, and isVerbose_.
Referenced by train().
predict()
sgpp::base::DataVectorSP sgpp::datadriven::LearnerBaseSP::predict (sgpp::base::DataMatrixSP & testDataset) virtual
executes a Regression test for a given dataset and returns the result
Parameters
testDataset dataset that is evaluated with the current learner
Returns
regression values of testDataset
References alpha_, sgpp::base::PrecisionConverter::convertDataMatrixSPToDataMatrix(), sgpp::base::PrecisionConverter::convertDataVectorSPToDataVector(), sgpp::base::PrecisionConverter::convertDataVectorToDataVectorSP(), sgpp::op_factory::createOperationMultipleEval(), sgpp::base::DataMatrixSP::getNcols(), sgpp::base::DataMatrixSP::getNrows(), sgpp::base::Grid::getSize(), grid_, and sgpp::base::OperationMultipleEval::mult().
Referenced by getAccuracy(), and getCassificatorQuality().
preProcessing()
void sgpp::datadriven::LearnerBaseSP::preProcessing () protected virtual
Hook-Method for pre-processing before starting learning.
can be overwritten by derived classes
Referenced by train().
setIsVerbose()
void sgpp::datadriven::LearnerBaseSP::setIsVerbose (const bool isVerbose)
sets the current verbose mode of learner
Parameters
isVerbose the current learner's verbose output
References isVerbose_.
store()
void sgpp::datadriven::LearnerBaseSP::store (std::string tGridFilename, std::string tAlphaFilename)
store the grid and its current coefficients into files for further usage.
Parameters
tGridFilename filename of grid file
tAlphaFilename filename of coefficient file
train() [1/2]
LearnerTiming sgpp::datadriven::LearnerBaseSP::train (sgpp::base::DataMatrixSP & testDataset, sgpp::base::DataVectorSP & classes, const sgpp::base::RegularGridConfiguration & gridConfig, const sgpp::solver::SLESolverSPConfiguration & SolverConfig, const float lambdaRegularization)
Learning a dataset with regular sparse grids.
Parameters
testDataset the training dataset
classes classes corresponding to the training dataset
gridConfig configuration of the regular grid
SolverConfig configuration of the SLE solver
lambdaRegularization regularization parameter lambda
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, and train().
train() [2/2]
LearnerTiming sgpp::datadriven::LearnerBaseSP::train (sgpp::base::DataMatrixSP & testDataset, sgpp::base::DataVectorSP & classes, const sgpp::base::RegularGridConfiguration & gridConfig, const sgpp::solver::SLESolverSPConfiguration & SolverConfigRefine, const sgpp::solver::SLESolverSPConfiguration & SolverConfigFinal, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, bool testAccDuringAdapt, const float lambdaRegularization) virtual
Learning a dataset with spatially adaptive sparse grids.
Parameters
testDataset the training dataset
classes classes corresponding to the training dataset
gridConfig configuration of the regular start grid
SolverConfigRefine configuration of the SLE solver during the adaptive refinements of the grid
SolverConfigFinal configuration of the final SLE solving step on the refined grid
adaptivityConfig configuration of the adaptivity strategy
testAccDuringAdapt set to true if the training accuracy should be determined in evert refinement step
lambdaRegularization regularization parameter lambda
References adaptivityConfig, alpha_, sgpp::solver::BiCGSTAB, sgpp::solver::CG, sgpp::base::PrecisionConverter::convertDataVectorSPToDataVector(), createDMSystem(), sgpp::solver::SLESolverSPConfiguration::eps_, execTime_, GByte_, sgpp::datadriven::LearnerTiming::GByte_, sgpp::datadriven::DMSystemMatrixBaseSP::generateb(), getAccuracy(), sgpp::base::Grid::getGenerator(), sgpp::base::DataMatrixSP::getNrows(), sgpp::solver::SGSolverSP::getNumberIterations(), sgpp::solver::SGSolverSP::getResiduum(), sgpp::base::DataVectorSP::getSize(), sgpp::base::Grid::getSize(), sgpp::datadriven::DMSystemMatrixBaseSP::getTimers(), GFlop_, sgpp::datadriven::LearnerTiming::GFlop_, grid_, InitializeGrid(), isRegression_, isTrained_, isVerbose_, sgpp::solver::SLESolverSPConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, postProcessing(), preProcessing(), sgpp::datadriven::DMSystemMatrixBaseSP::rebuildLevelAndIndex(), sgpp::base::GridGenerator::refine(), sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::DataVectorSP::resizeZero(), sgpp::solver::SGSolverSP::setEpsilon(), sgpp::solver::SGSolverSP::setMaxIterations(), sgpp::solver::SLESolverSP::solve(), sgpp::base::SGppStopwatch::start(), sgpp::base::SGppStopwatch::stop(), sgpp::datadriven::LearnerTiming::timeComplete_, sgpp::datadriven::LearnerTiming::timeMultComplete_, sgpp::datadriven::LearnerTiming::timeMultCompute_, sgpp::datadriven::LearnerTiming::timeMultTransComplete_, sgpp::datadriven::LearnerTiming::timeMultTransCompute_, sgpp::datadriven::LearnerTiming::timeRegularization_, and sgpp::solver::SLESolverSPConfiguration::type_.
Referenced by train().
Member Data Documentation
alpha_
sgpp::base::DataVectorSP* sgpp::datadriven::LearnerBaseSP::alpha_ protected
the grid's coefficients
Referenced by dumpFunction(), dumpGrid(), InitializeGrid(), LearnerBaseSP(), predict(), train(), and ~LearnerBaseSP().
execTime_
double sgpp::datadriven::LearnerBaseSP::execTime_ protected
execution time
Referenced by LearnerBaseSP(), postProcessing(), and train().
GByte_
double sgpp::datadriven::LearnerBaseSP::GByte_ protected
number of transferred Gbytes
Referenced by LearnerBaseSP(), and train().
GFlop_
double sgpp::datadriven::LearnerBaseSP::GFlop_ protected
number of executed Floating Point operations
Referenced by LearnerBaseSP(), and train().
grid_
sgpp::base::Grid* sgpp::datadriven::LearnerBaseSP::grid_ protected
sparse grid object
Referenced by dumpFunction(), dumpGrid(), InitializeGrid(), LearnerBaseSP(), predict(), train(), and ~LearnerBaseSP().
isRegression_
bool sgpp::datadriven::LearnerBaseSP::isRegression_ protected
is regression selected
Referenced by getAccuracy(), getCassificatorQuality(), getIsRegression(), LearnerBaseSP(), and train().
isTrained_
bool sgpp::datadriven::LearnerBaseSP::isTrained_ protected
is the grid trained
Referenced by dumpFunction(), dumpGrid(), LearnerBaseSP(), and train().
isVerbose_
bool sgpp::datadriven::LearnerBaseSP::isVerbose_ protected
is verbose output enabled
Referenced by getIsVerbose(), postProcessing(), setIsVerbose(), and train().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/LearnerBaseSP.hpp
datadriven/src/sgpp/datadriven/application/LearnerBaseSP.cpp