SG++-Doxygen-Documentation: sgpp::base::NaturalBsplineBasis< LT, IT > Class Template Reference
sgpp::base::NaturalBsplineBasis< LT, IT > Class Template Reference
B-spline basis with natural boundary conditions.
#include <NaturalBsplineBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
NaturalBsplineBasis ()
Default constructor.
NaturalBsplineBasis (size_t degree)
Constructor.
~NaturalBsplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::NaturalBsplineBasis< LT, IT >
B-spline basis with natural boundary conditions.
Constructor & Destructor Documentation
NaturalBsplineBasis() [1/2]
template<class LT , class IT > sgpp::base::NaturalBsplineBasis< LT, IT >::NaturalBsplineBasis () inline
Default constructor.
NaturalBsplineBasis() [2/2]
template<class LT , class IT > sgpp::base::NaturalBsplineBasis< LT, IT >::NaturalBsplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::NaturalBsplineBasis< LT, IT >::getDegree().
~NaturalBsplineBasis()
template<class LT , class IT > sgpp::base::NaturalBsplineBasis< LT, IT >::~NaturalBsplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::NaturalBsplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NaturalBsplineBasis< LT, IT >::bsplineBasis, and sgpp::base::NaturalBsplineBasis< LT, IT >::getDegree().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), and sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval().
evalDx()
template<class LT , class IT > double sgpp::base::NaturalBsplineBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::NaturalBsplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NaturalBsplineBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::NaturalBsplineBasis< LT, IT >::eval(), and sgpp::base::NaturalBsplineBasis< LT, IT >::NaturalBsplineBasis().
getIntegral()
template<class LT , class IT > double sgpp::base::NaturalBsplineBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::NaturalBsplineBasis< LT, IT >::bsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::NaturalBsplineBasis< LT, IT >::eval(), and sgpp::base::NaturalBsplineBasis< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/NaturalBsplineBasis.hpp