SG++-Doxygen-Documentation: sgpp::base::EvalCuboidGeneratorForStretching Class Reference
sgpp::base::EvalCuboidGeneratorForStretching Class Reference
This class builds a cuboid in the d-dimension space.
#include <EvalCuboidGeneratorForStretching.hpp>
Public Member Functions
EvalCuboidGeneratorForStretching ()
Constructor.
void getEvaluationCuboid (DataMatrix &EvaluationPoints, Stretching &SubDomain, size_t points)
This function builds an cuboid which will be stored into the EvaluationPoint variable of this function.
~EvalCuboidGeneratorForStretching ()
Destructor.
Detailed Description
This class builds a cuboid in the d-dimension space.
This cuboid is discretesized by a regular full grid.
Constructor & Destructor Documentation
EvalCuboidGeneratorForStretching()
sgpp::base::EvalCuboidGeneratorForStretching::EvalCuboidGeneratorForStretching ()
Constructor.
~EvalCuboidGeneratorForStretching()
sgpp::base::EvalCuboidGeneratorForStretching::~EvalCuboidGeneratorForStretching ()
Destructor.
Member Function Documentation
getEvaluationCuboid()
void sgpp::base::EvalCuboidGeneratorForStretching::getEvaluationCuboid (DataMatrix & EvaluationPoints, Stretching & SubDomain, size_t points)
This function builds an cuboid which will be stored into the EvaluationPoint variable of this function.
This is by done by building a cuboid around a bounding box. Be aware that this function returns points to the power of d points.
Parameters
EvaluationPoints DataMatrix that will contain the evaluation points afterwards
SubDomain the bounding box of the evaluation cuboid
points number of points used in every dimension
References sgpp::base::BoundingBox::getDimension(), sgpp::base::DataMatrix::resize(), and sgpp::base::DataMatrix::setRow().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/EvalCuboidGeneratorForStretching.hpp
base/src/sgpp/base/tools/EvalCuboidGeneratorForStretching.cpp