SG++-Doxygen-Documentation: sgpp::datadriven::ARFFTools Class Reference
sgpp::datadriven::ARFFTools Class Reference
Class that provides functionality to read ARFF files.
#include <ARFFTools.hpp>
Static Public Member Functions
static Dataset readARFF (std::istream &stream, bool hasTargets=true, size_t instanceCutoff=-1, std::vector< size_t > selectedCols=std::vector< size_t >(), std::vector< double > selectedTargets=std::vector< double >())
Sequentially reads a ARFF file.
static Dataset readARFFFromFile (const std::string &filename, bool hasTargets=true, size_t instanceCutoff=-1, std::vector< size_t > selectedCols=std::vector< size_t >(), std::vector< double > selectedTargets=std::vector< double >())
Wrapper from input type: File.
static Dataset readARFFFromString (const std::string &content, bool hasTargets=true, size_t instanceCutoff=-1, std::vector< size_t > selectedCols=std::vector< size_t >(), std::vector< double > selectedTargets=std::vector< double >())
Wrapper from input type: String.
static void readARFFSize (std::istream &stream, size_t &numberInstances, size_t &dimension, bool hasTargets, std::vector< double > selectedTargets)
Reads the size of a ARFF file.
static void readARFFSizeFromFile (const std::string &filename, size_t &numberInstances, size_t &dimension, bool hasTargets=true, std::vector< double > selectedTargets=std::vector< double >())
Wrapper from input type: File.
static void readARFFSizeFromString (const std::string &content, size_t &numberInstances, size_t &dimension, bool hasTargets=true, std::vector< double > selectedTargets=std::vector< double >())
Wrapper from input type: String.
Detailed Description
Class that provides functionality to read ARFF files.
Member Function Documentation
readARFF()
Dataset sgpp::datadriven::ARFFTools::readARFF (std::istream & stream, bool hasTargets = true, size_t instanceCutoff = -1, std::vector< size_t > selectedCols = std::vector<size_t>(), std::vector< double > selectedTargets = std::vector<double>()) static
Sequentially reads a ARFF file.
Parameters
stream contains the raw data. Note: After this function exists, stream will be at eof. For further use it should be cleared and reset
hasTargets whether the csv has columns for targets (supervised learning)
instanceCutoff maximal number of instances to include in the returned Dataset. May not be reached if there are less than instanceCutoff (valid w.r.t. selectedTargets) rows in csv file. If the value is -1 i.e. the maximal value of the (unsigned) size_t, all valid rows are included
selectedCols which columns are written to the DataMatrix as dimensions. Order matters, i.e. selectedCols = [0, 3, 2] will result in a DataMatrix with dim0 = row0, dim1 = row3, dim2 = row2. If hasTargets=true, the last row must not be specified here as it is written to the target vector, not the DataMatrix. If empty (default) all rows (except possible the target row) will be used in ascending order.
selectedTargets filter for targets. Only applicable if hasTargets=true. Only rows with target-entry (last column) equal to one of the entries in selectedTarget are written to the dataset. All other rows are skipped. Float-comparison uses 0.001 precision. This parameter is intended to use for classification with integer values as classes. If empty (default) all targets are admissible and all rows are written as rows (instances) in the dataset.
Returns
ARFF as Dataset
References dataset, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getTargets(), readARFFSize(), sgpp::base::DataVector::set(), and sgpp::base::DataMatrix::set().
Referenced by readARFFFromFile(), and readARFFFromString().
readARFFFromFile()
Dataset sgpp::datadriven::ARFFTools::readARFFFromFile (const std::string & filename, bool hasTargets = true, size_t instanceCutoff = -1, std::vector< size_t > selectedCols = std::vector<size_t>(), std::vector< double > selectedTargets = std::vector<double>()) static
Wrapper from input type: File.
See readARFF for more details
References readARFF().
Referenced by hpx_main(), main(), main(), and sgpp::datadriven::ArffFileSampleProvider::readFile().
readARFFFromString()
Dataset sgpp::datadriven::ARFFTools::readARFFFromString (const std::string & content, bool hasTargets = true, size_t instanceCutoff = -1, std::vector< size_t > selectedCols = std::vector<size_t>(), std::vector< double > selectedTargets = std::vector<double>()) static
Wrapper from input type: String.
See readARFF for more details
References readARFF().
Referenced by sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::MetaLearner::learnReferenceString(), sgpp::datadriven::MetaLearner::learnString(), and sgpp::datadriven::ArffFileSampleProvider::readString().
readARFFSize()
void sgpp::datadriven::ARFFTools::readARFFSize (std::istream & stream, size_t & numberInstances, size_t & dimension, bool hasTargets, std::vector< double > selectedTargets) static
Reads the size of a ARFF file.
Parameters
stream contains the raw data. Note: After this function exists, stream will be at eof. For further use it should be cleared and reset
[out] numberInstances number of instances in the dataset
[out] dimension number of columns (dimensions) in the dataset
hasTargets whether the csv has a columns for targets (supervised learning). If true, dimension = number of columns - 1
selectedTargets (see readCSVPartial). If this vector is not empty (default) numberIstances reflects only the number of instance which are admissible with respect to selectedTargets. If empty all targets are admissible and all rows are considered as instances.
Referenced by readARFF(), readARFFSizeFromFile(), and readARFFSizeFromString().
readARFFSizeFromFile()
void sgpp::datadriven::ARFFTools::readARFFSizeFromFile (const std::string & filename, size_t & numberInstances, size_t & dimension, bool hasTargets = true, std::vector< double > selectedTargets = std::vector<double>()) static
Wrapper from input type: File.
See readARFFSize for more details
References readARFFSize().
readARFFSizeFromString()
void sgpp::datadriven::ARFFTools::readARFFSizeFromString (const std::string & content, size_t & numberInstances, size_t & dimension, bool hasTargets = true, std::vector< double > selectedTargets = std::vector<double>()) static
Wrapper from input type: String.
See readARFFSize for more details
References readARFFSize().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/ARFFTools.hpp
datadriven/src/sgpp/datadriven/tools/ARFFTools.cpp