SG++-Doxygen-Documentation: sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type > Class Template Reference
sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type > Class Template Reference
#include <KernelMult.hpp>
Public Member Functions
double getBuildDuration ()
KernelMult (std::shared_ptr< base::OCLDevice > device, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node &kernelConfiguration, std::shared_ptr< base::QueueLoadBalancerOpenMP > queueBalancerMult)
double mult (std::vector< real_type > &level, std::vector< real_type > &index, std::vector< real_type > &mask, std::vector< real_type > &offset, std::vector< real_type > &dataset, std::vector< real_type > &alpha, std::vector< real_type > &result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data)
void resetKernel ()
~KernelMult ()
Constructor & Destructor Documentation
KernelMult()
template<typename real_type > sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::KernelMult (std::shared_ptr< base::OCLDevice > device, size_t dims, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node & kernelConfiguration, std::shared_ptr< base::QueueLoadBalancerOpenMP > queueBalancerMult) inline
References json::Node::getBool(), and json::Node::getUInt().
~KernelMult()
template<typename real_type > sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::~KernelMult () inline
Member Function Documentation
getBuildDuration()
template<typename real_type > double sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::getBuildDuration () inline
mult()
template<typename real_type > double sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::mult (std::vector< real_type > & level, std::vector< real_type > & index, std::vector< real_type > & mask, std::vector< real_type > & offset, std::vector< real_type > & dataset, std::vector< real_type > & alpha, std::vector< real_type > & result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data) inline
References alpha, dataset, sgpp::datadriven::StreamingModOCLMaskMultiPlatform::SourceBuilderMult< T >::generateSource(), sgpp::base::OCLBufferWrapperSD< T >::getBuffer(), sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), level, and sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer().
resetKernel()
template<typename real_type > void sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::resetKernel () inline
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingModOCLMaskMultiPlatform/KernelMult.hpp