SG++-Doxygen-Documentation: sgpp::base::OperationFirstMomentModLinear Class Reference
sgpp::base::OperationFirstMomentModLinear Class Reference
FirstMomemnt of sparse grid function, linear grid without boundaries.
#include <OperationFirstMomentModLinear.hpp>
Public Member Functions
double doQuadrature (const DataVector &alpha, DataMatrix *bounds=nullptr) override
Compute first moment of the function.
OperationFirstMomentModLinear (GridStorage &storage)
Constructor of OperationFirstMomentModLinear.
~OperationFirstMomentModLinear () override
Public Member Functions inherited from sgpp::base::OperationFirstMoment
OperationFirstMoment ()
Constructor.
virtual ~OperationFirstMoment ()
Destructor.
Protected Attributes
GridStorage & storage
Detailed Description
FirstMomemnt of sparse grid function, linear grid without boundaries.
Constructor & Destructor Documentation
OperationFirstMomentModLinear()
sgpp::base::OperationFirstMomentModLinear::OperationFirstMomentModLinear (GridStorage & storage) inline explicit
Constructor of OperationFirstMomentModLinear.
Parameters
storage sparse grid storage object
~OperationFirstMomentModLinear()
sgpp::base::OperationFirstMomentModLinear::~OperationFirstMomentModLinear () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationFirstMomentModLinear::doQuadrature (const DataVector & alpha, DataMatrix * bounds = nullptr) override virtual
Compute first moment of the function.
\[ \int_{\Omega} x\cdot f(x) dx. \]
Parameters
alpha Coefficient vector for current grid
bounds describes the boundaries of the hypercube of the original function
Implements sgpp::base::OperationFirstMoment.
References alpha, sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), level, and storage.
Member Data Documentation
storage
GridStorage& sgpp::base::OperationFirstMomentModLinear::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationFirstMomentModLinear.hpp
base/src/sgpp/base/operation/hash/OperationFirstMomentModLinear.cpp