SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::MPIWorkerBase Class Reference
sgpp::datadriven::clusteringmpi::MPIWorkerBase Class Reference abstract
Base class for MPI master node operations.
#include <OperationMPI.hpp>
Public Member Functions
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual void start_worker_main (void)=0
virtual ~MPIWorkerBase (void)
Protected Attributes
bool verbose
Detailed Description
Base class for MPI master node operations.
Constructor & Destructor Documentation
MPIWorkerBase() [1/2]
sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase (std::string worker_class_name) explicit
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_communicator(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_configuration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), json::Node::getBool(), and verbose.
MPIWorkerBase() [2/2]
sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase (void)
~MPIWorkerBase()
sgpp::datadriven::clusteringmpi::MPIWorkerBase::~MPIWorkerBase (void) virtual
Member Function Documentation
release_sub_workers()
void sgpp::datadriven::clusteringmpi::MPIWorkerBase::release_sub_workers (void)
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_communicator(), and sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count().
start_sub_workers()
void sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_sub_workers (void)
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_communicator(), and sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count().
Referenced by sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::create_graph(), sgpp::datadriven::clusteringmpi::OperationPrunedGraphCreationMPI::create_graph(), sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), and sgpp::datadriven::clusteringmpi::OperationDummy::start_operation().
start_worker_main()
virtual void sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_worker_main (void) pure virtual
Implemented in sgpp::datadriven::clusteringmpi::GraphCreationWorker, sgpp::datadriven::clusteringmpi::WorkerDummy, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >, and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< int >.
Member Data Documentation
verbose
bool sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose protected
Referenced by python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::addFullGridPoints(), python.uq.refinement.RefinementManager.RefinementManager::candidates(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::computeCandidates(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), python.uq.operations.forcePositivity.findIntersections.IntersectionCandidates::findIntersections(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::getLocalMaxLevel(), python.uq.manager.ASGCUQManager.ASGCUQManager::learnDataWithoutTest(), python.uq.manager.ASGCUQManager.ASGCUQManager::learnDataWithTest(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makeCurrentNodalValuesPositive(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), MPIWorkerBase(), sgpp::datadriven::clusteringmpi::DensityWorker::receive_and_send_initial_data(), python.uq.manager.ASGCUQManager.ASGCUQManager::recomputeStats(), python.uq.refinement.RefinementManager.RefinementManager::refineGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::splitFullGrids(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::start_worker_main(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main(), and sgpp::datadriven::clusteringmpi::WorkerDummy::WorkerDummy().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationMPI.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationMPI.cpp