SG++-Doxygen-Documentation: sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary Class Reference
sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary Class Reference
Explicit representation of the matrix \((\Phi_i,\Phi_j)_{L2}\) for a sparse grid.
#include <OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary (sgpp::base::DataMatrix *m, sgpp::base::Grid *grid)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary (sgpp::base::Grid *grid)
Constructor that creates an own matrix i.e.
virtual ~OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Explicit representation of the matrix \((\Phi_i,\Phi_j)_{L2}\) for a sparse grid.
Constructor & Destructor Documentation
OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary() [1/2]
sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary (sgpp::base::DataMatrix * m, sgpp::base::Grid * grid)
Constructor that uses a external matrix pointer to construct the matrix, i.e.
matrix is NOT destroyed by the destructor of OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundaryFullGrid
Parameters
m pointer to datamatrix of size (number of grid point) x (number of grid points)
grid the sparse grid
References grid(), and m.
OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary() [2/2]
sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary (sgpp::base::Grid * grid) explicit
Constructor that creates an own matrix i.e.
matrix is destroyed by the destructor of OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundaryFullGrid
Parameters
grid the sparse grid
References grid().
~OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary()
sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::~OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary () virtual
Destructor.
Member Function Documentation
mult()
void sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), and sgpp::base::DataVector::getSize().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary.hpp
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary.cpp