SG++-Doxygen-Documentation: sgpp::datadriven::DBMatObjectStore::ObjectContainer Class Reference
sgpp::datadriven::DBMatObjectStore::ObjectContainer Class Reference
Datastructure to store offline objects together with their configuration.
#include <DBMatObjectStore.hpp>
Public Member Functions
bool configMatches (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig, bool searchBase)
Checks wheter the configuration of a container matches a given configuration.
const sgpp::base::GeneralGridConfiguration & getGridConfig () const
Returns a read-only reference to the containers grid configuration.
const DBMatOffline & getOfflineObject () const
Returns a read-only reference to the containers offline object.
ObjectContainer (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig, std::unique_ptr< const DBMatOffline > offlineObject)
Public constructor.
Detailed Description
Datastructure to store offline objects together with their configuration.
This class is not intended to be used outside of DBMatObjectStore.
Constructor & Destructor Documentation
ObjectContainer()
sgpp::datadriven::DBMatObjectStore::ObjectContainer::ObjectContainer (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig, std::unique_ptr< const DBMatOffline > offlineObject) explicit
Public constructor.
Gets initialized with the offline object and the correspoding configuration. Note that ownership of the given offline object get transfered to the container. I.e. if the container is deleted, its offline object is deleted as well.
Parameters
gridConfig Grid configuration
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
offlineObject Unique pointer to an offline object. Ownership of this object gets transfered to the container
Member Function Documentation
configMatches()
bool sgpp::datadriven::DBMatObjectStore::ObjectContainer::configMatches (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig, bool searchBase)
Checks wheter the configuration of a container matches a given configuration.
If searcBase = true, it is checked wheter the offline object is a suitable base object for the permutation and blow-up approach.
Parameters
gridConfig Grid configuration
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
searchBase Flag to specify whether an identical offline object or a suitable base object is to be searched
Returns
true
false
References adaptivityConfig, sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::AdaptivityConfiguration::coarseningFunctorType_, sgpp::base::AdaptivityConfiguration::coarseningThreshold_, sgpp::base::ComponentGrid, sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::datadriven::PermutationUtil::deleteOnesFromLevelVec(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::AdaptivityConfiguration::errorBasedRefinement_, sgpp::base::AdaptivityConfiguration::errorBufferSize_, sgpp::base::AdaptivityConfiguration::errorConvergenceThreshold_, sgpp::base::AdaptivityConfiguration::errorMinInterval_, sgpp::datadriven::RegularizationConfiguration::exponentBase_, sgpp::base::GeneralGridConfiguration::generalType_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsDecompose_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsRefine_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsSolver_, sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsUpdateLambda_, sgpp::datadriven::PermutationUtil::isPermutation(), sgpp::datadriven::RegularizationConfiguration::l1Ratio_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::AdaptivityConfiguration::levelPenalize_, sgpp::base::GeneralGridConfiguration::levelVector_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::datadriven::DensityEstimationConfiguration::normalize_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::precomputeEvaluations_, sgpp::base::AdaptivityConfiguration::refinementFunctorType_, sgpp::base::AdaptivityConfiguration::refinementPeriod_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::AdaptivityConfiguration::scalingCoefficients_, sgpp::base::GeneralGridConfiguration::type_, sgpp::datadriven::DensityEstimationConfiguration::type_, and sgpp::datadriven::RegularizationConfiguration::type_.
getGridConfig()
const sgpp::base::GeneralGridConfiguration & sgpp::datadriven::DBMatObjectStore::ObjectContainer::getGridConfig () const
Returns a read-only reference to the containers grid configuration.
Returns
const sgpp::base::GeneralGridConfiguration&
Referenced by sgpp::datadriven::DBMatObjectStore::getBaseObject().
getOfflineObject()
const DBMatOffline & sgpp::datadriven::DBMatObjectStore::ObjectContainer::getOfflineObject () const
Returns a read-only reference to the containers offline object.
Returns
const DBMatOffline&
Referenced by sgpp::datadriven::DBMatObjectStore::getBaseObject(), and sgpp::datadriven::DBMatObjectStore::getObject().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatObjectStore.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatObjectStore.cpp