SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureNakBsplineModified Class Reference
sgpp::base::OperationQuadratureNakBsplineModified Class Reference
Quadrature on sparse grid, not a knot modified B-spline grid.
#include <OperationQuadratureNakBsplineModified.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for not a knot B-spline basis functions.
OperationQuadratureNakBsplineModified (GridStorage &storage, size_t degree)
Constructor of OperationQuadratureNakBsplineModified.
~OperationQuadratureNakBsplineModified () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SNakBsplineModifiedBase base
Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, not a knot modified B-spline grid.
Constructor & Destructor Documentation
OperationQuadratureNakBsplineModified()
sgpp::base::OperationQuadratureNakBsplineModified::OperationQuadratureNakBsplineModified (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadratureNakBsplineModified.
Parameters
storage Pointer to the grid's GridStorage object
degree the B-spline degree
~OperationQuadratureNakBsplineModified()
sgpp::base::OperationQuadratureNakBsplineModified::~OperationQuadratureNakBsplineModified () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature (DataVector & alpha) override virtual
Quadrature for not a knot B-spline basis functions.
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::NakBsplineModifiedBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SNakBsplineModifiedBase sgpp::base::OperationQuadratureNakBsplineModified::base protected
Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadratureNakBsplineModified::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureNakBsplineModified.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureNakBsplineModified.cpp