SG++-Doxygen-Documentation: sgpp::base::ImpurityRefinement_refinement_key Class Reference
sgpp::base::ImpurityRefinement_refinement_key Class Reference
Container type for impurity refinement collection.
#include <ImpurityRefinement.hpp>
Public Member Functions
size_t getDim ()
Returns dimensionality.
ImpurityRefinement_refinement_key (const GridPoint &point, size_t seq, size_t dim)
Constructor.
virtual ~ImpurityRefinement_refinement_key ()
Destructor.
Public Member Functions inherited from sgpp::base::AbstractRefinement_refinement_key
AbstractRefinement_refinement_key (const GridPoint &point, size_t seq)
const std::vector< level_t > getLevelVector ()
GridPoint & getPoint ()
size_t getSeq () const
virtual ~AbstractRefinement_refinement_key ()
Detailed Description
Container type for impurity refinement collection.
Constructor & Destructor Documentation
ImpurityRefinement_refinement_key()
sgpp::base::ImpurityRefinement_refinement_key::ImpurityRefinement_refinement_key (const GridPoint & point, size_t seq, size_t dim) inline
Constructor.
Parameters
point grid point
seq sequence number in the hash grid storage
dim dimensionality
~ImpurityRefinement_refinement_key()
virtual sgpp::base::ImpurityRefinement_refinement_key::~ImpurityRefinement_refinement_key () inline virtual
Destructor.
Member Function Documentation
getDim()
size_t sgpp::base::ImpurityRefinement_refinement_key::getDim () inline
Returns dimensionality.
Returns
dimensionality
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.uq.dists.Dist.Dist::cov(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), and python.uq.uq_setting.UQSetting.UQSetting::getDim().
The documentation for this class was generated from the following file:
base/src/sgpp/base/grid/generation/refinement_strategy/ImpurityRefinement.hpp