SG++-Doxygen-Documentation: sgpp::base::AlgorithmDGEMV< BASIS > Class Template Reference
sgpp::base::AlgorithmDGEMV< BASIS > Class Template Reference
Basic multiplaction with B and B^T on grids with no boundaries.
#include <AlgorithmDGEMV.hpp>
Public Member Functions
void mult (GridStorage &storage, BASIS &basis, const DataVector &source, DataMatrix &x, DataVector &result)
Performs the DGEMV Operation on the grid having a transposed matrix.
void mult_transposed (GridStorage &storage, BASIS &basis, const DataVector &source, DataMatrix &x, DataVector &result)
Performs the DGEMV Operation on the grid.
Detailed Description
template<class BASIS>
class sgpp::base::AlgorithmDGEMV< BASIS >
Basic multiplaction with B and B^T on grids with no boundaries.
If there are \(N\) basis functions \(\varphi(\vec{x})\) and \(m\) data points, then B is a (Nxm) matrix, with
\[ (B)_{i,j} = \varphi_i(x_j). \]
(The common known name for this operation is the BLAS routine DGEMV.)
Member Function Documentation
mult()
template<class BASIS > void sgpp::base::AlgorithmDGEMV< BASIS >::mult (GridStorage & storage, BASIS & basis, const DataVector & source, DataMatrix & x, DataVector & result) inline
Performs the DGEMV Operation on the grid having a transposed matrix.
This operation can be executed in parallel by setting the USEOMP define
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::base::OperationMultipleEvalLinearBoundary::mult(), sgpp::base::OperationMultipleEvalLinearStretched::mult(), sgpp::base::OperationMultipleEvalLinearStretchedBoundary::mult(), sgpp::base::OperationMultipleEvalModLinear::mult(), sgpp::base::OperationMultipleEvalModPoly::mult(), sgpp::base::OperationMultipleEvalPeriodic::mult(), sgpp::base::OperationMultipleEvalPoly::mult(), sgpp::base::OperationMultipleEvalPolyBoundary::mult(), and sgpp::base::OperationMultipleEvalPrewavelet::mult().
mult_transposed()
template<class BASIS > void sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed (GridStorage & storage, BASIS & basis, const DataVector & source, DataMatrix & x, DataVector & result) inline
Performs the DGEMV Operation on the grid.
This operation can be executed in parallel by setting the USEOMP define
Parameters
storage GridStorage object that contains the grid's points information
basis a reference to a class that implements a specific basis
source the coefficients of the grid points
x the d-dimensional vector with data points (row-wise)
result the result vector of the matrix vector multiplication
References sgpp::base::DataVector::add(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::base::OperationMultipleEvalLinearBoundary::multTranspose(), sgpp::base::OperationMultipleEvalLinearStretched::multTranspose(), sgpp::base::OperationMultipleEvalLinearStretchedBoundary::multTranspose(), sgpp::base::OperationMultipleEvalModLinear::multTranspose(), sgpp::base::OperationMultipleEvalModPoly::multTranspose(), sgpp::base::OperationMultipleEvalPeriodic::multTranspose(), sgpp::base::OperationMultipleEvalPoly::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundary::multTranspose(), and sgpp::base::OperationMultipleEvalPrewavelet::multTranspose().
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/AlgorithmDGEMV.hpp