SG++-Doxygen-Documentation: sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type > Class Template Reference
sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type > Class Template Reference
#include <SourceBuilderMultTranspose.hpp>
Public Member Functions
std::string generateSource ()
SourceBuilderMultTranspose (std::shared_ptr< base::OCLDevice > device, json::Node &kernelConfiguration, size_t dims)
Public Member Functions inherited from sgpp::base::KernelSourceBuilderBase< real_type >
KernelSourceBuilderBase ()
Additional Inherited Members
Protected Member Functions inherited from sgpp::base::KernelSourceBuilderBase< real_type >
std::string constSuffix ()
std::string floatType ()
std::string intType ()
std::string reuseSource (std::string fileName)
void writeSource (std::string fileName, std::string source)
Protected Attributes inherited from sgpp::base::KernelSourceBuilderBase< real_type >
std::vector< std::string > indent
Static Protected Attributes inherited from sgpp::base::KernelSourceBuilderBase< real_type >
static const size_t MAX_INDENT_LEVEL
Constructor & Destructor Documentation
SourceBuilderMultTranspose()
template<typename real_type > sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type >::SourceBuilderMultTranspose (std::shared_ptr< base::OCLDevice > device, json::Node & kernelConfiguration, size_t dims) inline
References json::Node::getBool(), and json::Node::getUInt().
Member Function Documentation
generateSource()
template<typename real_type > std::string sgpp::datadriven::StreamingModOCLFastMultiPlatform::SourceBuilderMultTranspose< real_type >::generateSource () inline
References sgpp::base::KernelSourceBuilderBase< real_type >::floatType(), sgpp::base::KernelSourceBuilderBase< real_type >::indent, sgpp::base::KernelSourceBuilderBase< real_type >::reuseSource(), and sgpp::base::KernelSourceBuilderBase< real_type >::writeSource().
Referenced by sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::multTranspose().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingModOCLFastMultiPlattform/SourceBuilderMultTranspose.hpp