SG++-Doxygen-Documentation: sgpp::base::ScopedLock Class Reference
sgpp::base::ScopedLock Class Reference
Wrapper around MutexType which locks and unlocks upon construction/destruction.
#include <ScopedLock.hpp>
Public Member Functions
void lockAgain ()
Re-locks the MutexType object, if unlocked.
ScopedLock (MutexType &m)
Constructor, locks the MutexType object.
void unlock ()
Unlocks the MutexType object, if locked.
~ScopedLock ()
Destructor, unlocks the MutexType object.
Protected Attributes
bool locked
whether the MutexType object is locked or not
MutexType & mut
underlying MutexType object
Detailed Description
Wrapper around MutexType which locks and unlocks upon construction/destruction.
Adopted from http://bisqwit.iki.fi/story/howto/openmp/#Locks.
Constructor & Destructor Documentation
ScopedLock()
sgpp::base::ScopedLock::ScopedLock (MutexType & m) inline explicit
Constructor, locks the MutexType object.
Parameters
m MutexType object to be wrapped
References sgpp::base::MutexType::lock(), and mut.
~ScopedLock()
sgpp::base::ScopedLock::~ScopedLock () inline
Destructor, unlocks the MutexType object.
References unlock().
Member Function Documentation
lockAgain()
void sgpp::base::ScopedLock::lockAgain () inline
Re-locks the MutexType object, if unlocked.
References sgpp::base::MutexType::lock(), locked, and mut.
unlock()
void sgpp::base::ScopedLock::unlock () inline
Unlocks the MutexType object, if locked.
References locked, mut, and sgpp::base::MutexType::unlock().
Referenced by ~ScopedLock().
Member Data Documentation
locked
bool sgpp::base::ScopedLock::locked protected
whether the MutexType object is locked or not
Referenced by lockAgain(), and unlock().
mut
MutexType& sgpp::base::ScopedLock::mut protected
underlying MutexType object
Referenced by lockAgain(), ScopedLock(), and unlock().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/ScopedLock.hpp