SG++-Doxygen-Documentation: sgpp::base::DataMatrix Class Reference
sgpp::base::DataMatrix Class Reference
A class to store two-dimensional data.
#include <DataMatrix.hpp>
Public Member Functions
void abs ()
Sets all elements to their absolute value.
void add (const DataMatrix &matr)
Adds the values from another DataMatrix to the current values.
void addReduce (DataVector &reduction)
Reduce the DataMatrix along the columns by adding all entries in one row.
void addReduce (DataVector &reduction, DataVector &beta, size_t start_beta)
Reduce the DataMatrix along the columns by adding all entries in one row.
size_t appendCol (const DataVector &vec)
Appends a new Col with data contained in DataVector vec and returns index of new col.
size_t appendRow ()
Appends a new row and returns index of it.
size_t appendRow (const DataVector &vec)
Appends a new row with data contained in DataVector vec and returns index of new row.
void componentwise_div (const DataMatrix &matr)
Divides the current DataMatrix component-wise by another DataMatrix.
void componentwise_mult (const DataMatrix &matr)
Multiplies the current DataMatrix component-wise with another DataMatrix.
void copyFrom (const DataMatrix &matr)
Copies the data from another DataMatrix matr.
DataMatrix ()
Creates an empty two-dimensional DataMatrix.
DataMatrix (const DataMatrix &)=default
Copy constructor.
DataMatrix (const double *input, size_t nrows, size_t ncols)
Create a new DataMatrix from a double array.
DataMatrix (DataMatrix &&)=default
Move constructor.
DataMatrix (size_t nrows, size_t ncols)
Create a two-dimensional DataMatrix with nrows rows and ncols columns (uninitialized values).
DataMatrix (size_t nrows, size_t ncols, double value)
Create a two-dimensional DataMatrix with nrows rows and ncols columns and initializes all elements with the same value.
DataMatrix (std::initializer_list< double > input, size_t nrows)
Create a new DataMatrix from a std::initializer_list<double>.
DataMatrix (std::vector< double > input, size_t nrows)
Create a new DataMatrix from a std::vector<double>.
void expand (const DataVector &expand)
expands a given DataVector into a DataMatrix.
double get (size_t row, size_t col) const
Returns the value of the element at position [row,col].
size_t getAdditionallyReservedRows () const
Returns the number of unused rows.
void getColumn (size_t col, DataVector &vec) const
Copies the values of a column to the DataVector vec.
size_t getNcols () const
Returns the number of columns of the DataMatrix.
size_t getNrows () const
Returns the number of rows of the DataMatrix.
size_t getNumberNonZero () const
Determines the number of non-zero elements in the vector.
double * getPointer ()
Returns pointer to double array containing underlying data.
const double * getPointer () const
Returns const pointer to double array containing underlying data.
void getRow (size_t row, DataVector &vec) const
Copies the values of a row to the DataVector vec.
void getRow (size_t row, std::vector< double > &vec) const
Copies the values of a row to the std::vector vec.
size_t getSize () const
Returns the total number of (used) elements, i.e., getNrows()*getNCols()
double max () const
Returns the maximum over all entries.
double max (size_t col) const
Returns the maximum value of column col.
double min () const
Returns the minimum over all entries.
double min (size_t col) const
Returns the minimum value of column col.
void minmax (double *min, double *max) const
Determines minimum and maximum over all entries.
void minmax (size_t col, double *min, double *max) const
Determines minimum and maximum of column col.
void mult (const DataVector &x, DataVector &y) const
Multiplies the matrix with a vector x and stores the result in another vector y.
void mult (double scalar)
Multiplies all elements by a constant factor.
void normalizeDimension (size_t d)
Normalizes the d-th dimension (entries in the d-th column) to \([0,1]\).
void normalizeDimension (size_t d, double border)
Normalizes the d-th dimension (entries in the d-th column) to \([border,1-border]\).
double & operator() (size_t row, size_t col)
Returns the value of the element at position [row,col].
const double & operator() (size_t row, size_t col) const
Returns the value of the element at position [row,col].
DataMatrix & operator= (const DataMatrix &)=default
Copy assignment operator.
DataMatrix & operator= (DataMatrix &&)=default
Move assignment operator.
void reserveAdditionalRows (size_t inc_nrows)
Reserves memory for potentially inc_nrows new rows; the actual number of rows remains unchanged.
void resize (size_t nrows)
Resizes the DataMatrix to nrows rows.
void resize (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
void resizeQuadratic (size_t size)
Resizes the quadratic DataMatrix to size rows and size columns.
void resizeRows (size_t nrows)
Resizes the DataMatrix to nrows rows.
void resizeRowsCols (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
void resizeToSubMatrix (size_t row_1, size_t col_1, size_t row_2, size_t col_2)
Resize current matrix to the submatrix Mat[row_1:row_2, col_1:col_2].
void resizeZero (size_t nrows)
Resizes the DataMatrix to nrows rows.
void resizeZero (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
void set (size_t row, size_t col, double value)
Sets the element at position [row,col] to value.
void setAll (double value)
Sets all entries of DataMatrix to value.
void setColumn (size_t col, const DataVector &vec)
Sets a column of the DataMatrix to the values of a DataVector vec.
void setRow (size_t row, const DataVector &vec)
Sets a row of the DataMatrix to the values of a DataVector vec.
void sqr ()
Squares all elements of the DataMatrix.
void sqrt ()
Takes the square root of all elements of the DataMatrix.
void sub (const DataMatrix &matr)
Subtracts the values from another DataMatrix of the current values.
double sum () const
Returns the sum of all elements.
void toFile (const std::string &fileName) const
std::string toString () const
Returns a description of the DataMatrix as a string.
void toString (std::string &text) const
Writes the data stored in the DataMatrix into a string.
void transpose ()
Transposes this DataMatrix.
~DataMatrix ()=default
Destructor.
Static Public Member Functions
static DataMatrix fromFile (const std::string &fileName)
static DataMatrix fromString (const std::string &serializedVector)
Detailed Description
A class to store two-dimensional data.
Typically, DataMatrix would contain a set of (d-dimensional) data or evaluation points, i.e., the DataMatrix consists of d columns, and each row is one of the points. Thus, typical functionality like obtaining the maximum for a certain dimension (or attribute), or normalizing all data points to the unit interval for a certain dimension are provided.
Constructor & Destructor Documentation
DataMatrix() [1/8]
sgpp::base::DataMatrix::DataMatrix ()
Creates an empty two-dimensional DataMatrix.
DataMatrix() [2/8]
sgpp::base::DataMatrix::DataMatrix (const DataMatrix &) default
Copy constructor.
DataMatrix() [3/8]
sgpp::base::DataMatrix::DataMatrix (DataMatrix &&) default
Move constructor.
~DataMatrix()
sgpp::base::DataMatrix::~DataMatrix () default
Destructor.
DataMatrix() [4/8]
sgpp::base::DataMatrix::DataMatrix (size_t nrows, size_t ncols)
Create a two-dimensional DataMatrix with nrows rows and ncols columns (uninitialized values).
Parameters
nrows Number of rows
ncols Number of columns
DataMatrix() [5/8]
sgpp::base::DataMatrix::DataMatrix (size_t nrows, size_t ncols, double value)
Create a two-dimensional DataMatrix with nrows rows and ncols columns and initializes all elements with the same value.
Parameters
nrows Number of rows
ncols Number of columns
value Value for all entries
DataMatrix() [6/8]
sgpp::base::DataMatrix::DataMatrix (const double * input, size_t nrows, size_t ncols)
Create a new DataMatrix from a double array.
The double array contains the entries row-wise: x0_0,x0_1,...,x0_ncol-1, x1_0,x1_1,... ... xnrow_0, xnrow_1,...,xnrow_ncol-1
Parameters
input double array that contains the data
nrows number of rows
ncols number of columns
DataMatrix() [7/8]
sgpp::base::DataMatrix::DataMatrix (std::vector< double > input, size_t nrows) explicit
Create a new DataMatrix from a std::vector<double>.
Parameters
input std::vector<double> that contains the data
nrows number of rows
DataMatrix() [8/8]
sgpp::base::DataMatrix::DataMatrix (std::initializer_list< double > input, size_t nrows) explicit
Create a new DataMatrix from a std::initializer_list<double>.
Parameters
input std::initializer_list<double> that contains the data
nrows number of rows
Member Function Documentation
abs()
void sgpp::base::DataMatrix::abs ()
Sets all elements to their absolute value.
add()
void sgpp::base::DataMatrix::add (const DataMatrix & matr)
Adds the values from another DataMatrix to the current values.
Modifies the current values.
Parameters
matr The DataMatrix which is added to the current values
Referenced by sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), and sgpp::pde::UpDownOneOpDimEnhanced::updown().
addReduce() [1/2]
void sgpp::base::DataMatrix::addReduce (DataVector & reduction)
Reduce the DataMatrix along the columns by adding all entries in one row.
Parameters
reduction DataVector into which the reduce columns are stored
References sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::set().
Referenced by sgpp::pde::UpDownOneOpDimEnhanced::mult(), and sgpp::pde::UpDownOneOpDimEnhanced::multParallelBuildingBlock().
addReduce() [2/2]
void sgpp::base::DataMatrix::addReduce (DataVector & reduction, DataVector & beta, size_t start_beta)
Reduce the DataMatrix along the columns by adding all entries in one row.
Parameters
reduction DataVector to which the reduce columns are added
beta vector with length of number of columns beta[i] is multiplied to each element row[j][i]
start_beta where to start using the beta coefficients
References sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::set().
appendCol()
size_t sgpp::base::DataMatrix::appendCol (const DataVector & vec)
Appends a new Col with data contained in DataVector vec and returns index of new col.
Parameters
vec DataVector (length has to match getNcols()) with data
Returns
Index of new col
References sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::VisualizerDensityEstimation::getHeatmap2D(), sgpp::datadriven::VisualizerClassification::getHeatmap2DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap3D(), sgpp::datadriven::VisualizerClassification::getHeatmap3DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmapMore4D(), sgpp::datadriven::VisualizerClassification::getHeatmapMore4DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts1D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts2D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCutsMore3D(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), and sgpp::datadriven::BayesianOptimization::updateGP().
appendRow() [1/2]
size_t sgpp::base::DataMatrix::appendRow ()
Appends a new row and returns index of it.
Returns
Index of new row
Referenced by sgpp::datadriven::PrimalDualSVM::add(), sgpp::datadriven::DataBasedRefinementFunctor::computeHkl(), sgpp::datadriven::VisualizerClassification::initializeMatrices(), sgpp::datadriven::VisualizerDensityEstimation::initializeMatrices(), sgpp::datadriven::MetaLearner::learnAndCompareString(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::optimization::optimizer::DifferentialEvolution::optimize(), sgpp::optimization::optimizer::GradientDescent::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), sgpp::optimization::optimizer::NelderMead::optimize(), sgpp::optimization::optimizer::Newton::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), sgpp::datadriven::LearnerSGD::pushToBatch(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::LearnerSGDE::trainOnline(), and sgpp::datadriven::BayesianOptimization::updateGP().
appendRow() [2/2]
size_t sgpp::base::DataMatrix::appendRow (const DataVector & vec)
Appends a new row with data contained in DataVector vec and returns index of new row.
Parameters
vec DataVector (length has to match getNcols()) with data
Returns
Index of new row
References sgpp::base::DataVector::getSize().
componentwise_div()
void sgpp::base::DataMatrix::componentwise_div (const DataMatrix & matr)
Divides the current DataMatrix component-wise by another DataMatrix.
Modifies the current values. Performs
for i from 1 to this.getTotalSize()
  this[i] /= matr[i]
Note: No check for division by zero!
Parameters
matr the DataMatrix which the current DataMatrix is divided by
Referenced by sgpp::optimization::SplineResponseSurfaceVector::evalJacobian().
componentwise_mult()
void sgpp::base::DataMatrix::componentwise_mult (const DataMatrix & matr)
Multiplies the current DataMatrix component-wise with another DataMatrix.
Modifies the current values. Performs
for i from 1 to this.getSize()
  this[i] *= matr[i]
Parameters
matr the DataMatrix which is multiplied to current DataMatrix
copyFrom()
void sgpp::base::DataMatrix::copyFrom (const DataMatrix & matr)
Copies the data from another DataMatrix matr.
Disregards the number of rows and columns set for the two matrices, i.e., just copies the data entry by entry (and row by row). If the dimensions match (nrows, ncols), the current DataMatrix is an exact copy of matr. If not, as many elements as possible are copied, and everything else is left untouched.
Parameters
matr The source DataMatrix containing the data
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerDensityEstimation::translateColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumnsLeft(), and sgpp::datadriven::VisualizerDensityEstimation::translateColumnsRight().
expand()
void sgpp::base::DataMatrix::expand (const DataVector & expand)
expands a given DataVector into a DataMatrix.
Parameters
expand DataVector that should be expanded
References expand().
Referenced by expand(), sgpp::pde::UpDownOneOpDimEnhanced::mult(), and sgpp::pde::UpDownOneOpDimEnhanced::multParallelBuildingBlock().
fromFile()
DataMatrix sgpp::base::DataMatrix::fromFile (const std::string & fileName) static
References f, fileName, and fromString().
Referenced by sgpp::optimization::ResponseSurface::nrmsErrorFromTestData(), and sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector().
fromString()
DataMatrix sgpp::base::DataMatrix::fromString (const std::string & serializedVector) static
References sgpp::base::DataVector::append(), sgpp::base::DataVector::getSize(), and m.
Referenced by fromFile(), and sgpp::datadriven::MultipleEvalHPX::LocalityMultiplier::LocalityMultiplier().
get()
double sgpp::base::DataMatrix::get (size_t row, size_t col) const inline
Returns the value of the element at position [row,col].
Parameters
row Row
col Column
Returns
Value of the element
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::buildMatrixWithBounds(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::buildMatrixWithBounds(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyForwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyForwardSolve(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatOfflineDenseIChol::choleskyModification(), sgpp::datadriven::AlgorithmAdaBoostBase::classif(), sgpp::datadriven::DataBasedRefinementFunctor::computeHkl(), sgpp::datadriven::DBMatOnlineDE::computeL2Error(), sgpp::base::PrecisionConverter::convertDataMatrixToDataMatrixSP(), sgpp::datadriven::DensityEstimator::corrcoef(), sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), sgpp::datadriven::BayesianOptimization::decomposeCholesky(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadratureL2Error(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracyBL(), sgpp::datadriven::DBMatOfflineDenseIChol::ichol(), sgpp::datadriven::BayesianOptimization::likelihood(), sgpp::pde::UpDownTwoOpDims::mult(), sgpp::pde::OperationMatrixLTwoDotPeriodic::mult(), sgpp::pde::UpDownTwoOpDims::multParallelBuildingBlock(), sgpp::datadriven::OperationMultiEvalMPI::multSlave(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::ImpurityRefinementIndicator::operator()(), sgpp::base::PredictiveRefinementIndicator::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::BayesianOptimization::solveCholeskySystem(), sgpp::datadriven::LearnerSGDE::trainOnline(), sgpp::base::ForwardSelectorRefinementIndicator::update(), sgpp::base::ImpurityRefinementIndicator::update(), and sgpp::base::VectorDistributionRefinementFunctor::VectorDistributionRefinementFunctor().
getAdditionallyReservedRows()
size_t sgpp::base::DataMatrix::getAdditionallyReservedRows () const inline
Returns the number of unused rows.
Returns
number of unused rows
Referenced by sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset().
getColumn()
void sgpp::base::DataMatrix::getColumn (size_t col, DataVector & vec) const
Copies the values of a column to the DataVector vec.
Parameters
col The column
vec DataVector into which the data is written
References sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::optimization::SplineResponseSurfaceVector::getIntegrals(), sgpp::optimization::SplineResponseSurfaceVector::getMeans(), sgpp::optimization::SplineResponseSurfaceVector::getVariances(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::base::sle_solver::SLESolver::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), sgpp::base::sle_solver::GaussianElimination::solve(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson(), sgpp::datadriven::VisualizerDensityEstimation::swapColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumnsLeft(), and sgpp::datadriven::VisualizerDensityEstimation::translateColumnsRight().
getNcols()
size_t sgpp::base::DataMatrix::getNcols () const inline
Returns the number of columns of the DataMatrix.
Returns
Number of columns
Referenced by sgpp::datadriven::Harmonica::calculateConstrainedSpace(), sgpp::datadriven::DBMatDMSChol::choleskyBackwardSolve(), sgpp::datadriven::DBMatDMSChol::choleskyForwardSolve(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatDMSChol::choleskyUpdateLambda(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunctionParallel(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::DataBasedRefinementFunctor::computeHkl(), sgpp::datadriven::DBMatOnlineDE::computeL2Error(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchParallel(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), sgpp::base::PrecisionConverter::convertDataMatrixToDataMatrixSP(), sgpp::datadriven::DensityEstimator::corrcoef(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::ModelFittingDensityEstimationCG::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationCombi::fit(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap3D(), sgpp::datadriven::VisualizerClassification::getHeatmap3DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmapMore4D(), sgpp::datadriven::VisualizerClassification::getHeatmapMore4DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts2D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCutsMore3D(), sgpp::base::DataTensor::getMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::getUnmodifiedRDistributed(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::datadriven::LearnerSGD::initialize(), sgpp::datadriven::SparseGridDensityEstimator::initialize(), sgpp::datadriven::LearnerSVM::initialize(), sgpp::datadriven::VisualizerClassification::initializeMatrices(), sgpp::datadriven::VisualizerDensityEstimation::initializeMatrices(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), sgpp::datadriven::LearnerSGD::LearnerSGD(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::AlgorithmDGEMV< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult(), sgpp::pde::OperationLaplaceExplicitBspline::mult(), sgpp::pde::OperationLaplaceExplicitLinear::mult(), sgpp::pde::OperationLaplaceExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinearBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::mult(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreaming::mult(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::mult(), sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose(), sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult_transpose(), sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed(), sgpp::combigrid::OperationEvalFullGrid::multiEval(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multImpl(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multImpl(), sgpp::datadriven::OperationMultiEvalMPI::multSlave(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::multTranspose(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multTransposeImpl(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multTransposeImpl(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::OperationMultiEvalStreamingBSplineOCL(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::OperationMultiEvalStreamingModOCLFastMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::OperationMultiEvalStreamingModOCLMaskMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::OperationMultiEvalStreamingModOCLUnified(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::OperationMultiEvalStreamingOCLMultiPlatform(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::OperationMultipleEvalSubspaceCombined(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::OperationMultipleEvalSubspaceSimple(), sgpp::datadriven::DataBasedRefinementFunctor::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::VectorSurplusRefinementFunctor::operator()(), sgpp::datadriven::MortonOrder::orderDataset(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::LearnerSGDE::predict(), sgpp::datadriven::LearnerSVM::predict(), sgpp::datadriven::DBMatOffline::printMatrix(), sgpp::datadriven::MortonOrder::restoreDataset(), sgpp::datadriven::SortedDataset::restoreOrder(), sgpp::datadriven::MPIMethods::sendSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::DBMatDMS_SMW::solve(), sgpp::datadriven::DBMatDMSChol::solve(), sgpp::datadriven::DBMatDMSOrthoAdapt::solve(), sgpp::base::sle_solver::SLESolver::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Auto::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), sgpp::datadriven::DBMatOnlineDEChol::solveSLE(), sgpp::datadriven::DBMatOffline::store(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::DBMatOffline::syncDistributedDecomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::syncDistributedDecomposition(), sgpp::datadriven::DBMatOnlineDE_SMW::syncDistributedDecomposition(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::syncDistributedDecomposition(), sgpp::datadriven::DBMatOffline::syncDistributedInverse(), sgpp::datadriven::DataVectorDistributed::toLocalDataVector(), sgpp::datadriven::DataVectorDistributed::toLocalDataVectorBroadcast(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::BayesianOptimization::updateGP(), sgpp::datadriven::VisualizerDensityEstimation::updateIndexesCuts(), sgpp::datadriven::VisualizerDensityEstimation::updateIndexesHeatmap(), sgpp::datadriven::SortedDataset::usePermutation(), sgpp::optimization::file_io::writeMatrix(), and sgpp::datadriven::CSVTools::writeMatrixToCSVFile().
getNrows()
size_t sgpp::base::DataMatrix::getNrows () const inline
Returns the number of rows of the DataMatrix.
Returns
Number of rows
Referenced by sgpp::datadriven::PrimalDualSVM::add(), sgpp::datadriven::AlgorithmAdaBoostBase::AlgorithmAdaBoostBase(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatDMSChol::choleskyDowndate(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatOfflineDenseIChol::choleskyModification(), sgpp::datadriven::DBMatOfflineChol::choleskyPermutation(), sgpp::datadriven::DBMatDMSChol::choleskyUpdate(), sgpp::datadriven::AlgorithmAdaBoostBase::classif(), sgpp::combigrid::CombinationGrid::combineValues(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse_parallel(), sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::DataBasedRefinementFunctor::computeHkl(), sgpp::datadriven::DBMatOnlineDE::computeL2Error(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), sgpp::base::PrecisionConverter::convertDataMatrixToDataMatrixSP(), sgpp::datadriven::BayesianOptimization::decomposeCholesky(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::base::VectorFunction::eval(), sgpp::base::ScalarFunction::eval(), sgpp::base::ScalarFunctionGradient::eval(), sgpp::base::ScalarFunctionHessian::eval(), sgpp::pde::PDESolver::evaluateCuboid(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracy(), sgpp::datadriven::LearnerSGDE::getAccuracy(), sgpp::datadriven::LearnerSGD::getAccuracy(), sgpp::datadriven::LearnerBase::getAccuracy(), sgpp::datadriven::LearnerSVM::getAccuracy(), sgpp::datadriven::AlgorithmAdaBoostBase::getAccuracyBL(), sgpp::datadriven::LearnerBase::getCassificatorQuality(), sgpp::base::FullSLE::getDimension(), sgpp::datadriven::DBMatOffline::getGridSize(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap2D(), sgpp::datadriven::VisualizerClassification::getHeatmap2DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap3D(), sgpp::datadriven::VisualizerClassification::getHeatmap3DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmapMore4D(), sgpp::datadriven::VisualizerClassification::getHeatmapMore4DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts1D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts2D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCutsMore3D(), sgpp::base::DataTensor::getMatrix(), sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getPaddedDatasetSize(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::getPaddedDatasetSize(), sgpp::datadriven::AlgorithmAdaBoostBase::getROC(), sgpp::datadriven::DBMatOfflineOrthoAdapt::getUnmodifiedRDistributed(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::optimization::math::hessenbergForm(), sgpp::optimization::math::householderTransformation(), sgpp::datadriven::DBMatOfflineDenseIChol::ichol(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), sgpp::datadriven::MetaLearner::learnAndCompareString(), sgpp::datadriven::MetaLearner::learnAndTestString(), main(), sgpp::datadriven::DMSystemMatrix::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::datadriven::OperationMultiEvalHPX::mult(), sgpp::datadriven::OperationMultiEvalMPI::mult(), sgpp::pde::OperationLaplaceExplicitBspline::mult(), sgpp::pde::OperationLaplaceExplicitLinear::mult(), sgpp::pde::OperationLaplaceExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinearBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::mult(), sgpp::combigrid::OperationEvalFullGrid::multiEval(), sgpp::combigrid::OperationEvalCombinationGrid::multiEval(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::OperationMultiEvalStreamingBSplineOCL(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::OperationMultiEvalStreamingModOCLFastMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::OperationMultiEvalStreamingModOCLMaskMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::OperationMultiEvalStreamingModOCLUnified(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::OperationMultiEvalStreamingOCLMultiPlatform(), sgpp::base::ImpurityRefinementIndicator::operator()(), sgpp::base::PredictiveRefinementIndicator::operator()(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::datadriven::DBMatOfflineOrthoAdapt::permuteDecomposition(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::LearnerLeastSquaresIdentity::postProcessing(), sgpp::datadriven::LearnerSGD::predict(), sgpp::datadriven::LearnerSGDE::predict(), sgpp::datadriven::LearnerSVM::predict(), sgpp::datadriven::LearnerBase::predict(), sgpp::datadriven::LearnerLeastSquaresIdentity::predict(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::datadriven::DBMatOffline::printMatrix(), sgpp::datadriven::LearnerSGD::pushToBatch(), sgpp::optimization::math::QRDecomposition(), sgpp::optimization::math::schurDecomposition(), sgpp::datadriven::MPIMethods::sendSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::DBMatDMS_SMW::solve(), sgpp::datadriven::DBMatDMSOrthoAdapt::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Auto::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), sgpp::datadriven::DBMatOffline::store(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::VisualizerClassification::storeTsneJson(), sgpp::datadriven::VisualizerDensityEstimation::storeTsneJson(), sgpp::datadriven::VisualizerDensityEstimation::swapColumns(), sgpp::datadriven::DBMatOffline::syncDistributedDecomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::syncDistributedDecomposition(), sgpp::datadriven::DBMatOnlineDE_SMW::syncDistributedDecomposition(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::syncDistributedDecomposition(), sgpp::datadriven::DBMatOffline::syncDistributedInverse(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::SystemMatrixDensityRatioEstimation(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::SystemMatrixLeastSquaresIdentity(), sgpp::datadriven::test_calculateROCcurve(), sgpp::datadriven::LearnerLeastSquaresIdentity::testRegular(), sgpp::datadriven::RegressionLearner::train(), sgpp::datadriven::LearnerBase::train(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::base::BoundingBox::transformPointsToBoundingBox(), sgpp::base::BoundingBox::transformPointsToUnitCube(), sgpp::datadriven::VisualizerDensityEstimation::translateColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumnsLeft(), sgpp::datadriven::VisualizerDensityEstimation::translateColumnsRight(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update(), sgpp::base::ForwardSelectorRefinementIndicator::update(), sgpp::base::ImpurityRefinementIndicator::update(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel(), sgpp::optimization::file_io::writeMatrix(), and sgpp::datadriven::CSVTools::writeMatrixToCSVFile().
getNumberNonZero()
size_t sgpp::base::DataMatrix::getNumberNonZero () const
Determines the number of non-zero elements in the vector.
Returns
The number of non-zero elements
getPointer() [1/2]
double * sgpp::base::DataMatrix::getPointer ()
Returns pointer to double array containing underlying data.
Returns
Pointer to data
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatDMSChol::choleskyDowndate(), sgpp::datadriven::DBMatOfflineChol::choleskyPermutation(), sgpp::datadriven::DBMatDMSChol::choleskyUpdate(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::computeResidual(), sgpp::datadriven::DBMatOfflineOrthoAdapt::DBMatOfflineOrthoAdapt(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::pde::OperationLaplaceExplicitBspline::mult(), sgpp::pde::OperationLaplaceExplicitLinear::mult(), sgpp::pde::OperationLaplaceExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitLinearBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPoly::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary::mult(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multImpl(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multTransposeImpl(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinear::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinear::operator()(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatDMS_SMW::solve(), sgpp::datadriven::DBMatDMSOrthoAdapt::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::datadriven::DBMatOffline::store(), sgpp::datadriven::DBMatOfflineOrthoAdapt::store(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel(), and sgpp::optimization::file_io::writeMatrix().
getPointer() [2/2]
const double * sgpp::base::DataMatrix::getPointer () const
Returns const pointer to double array containing underlying data.
Returns
Const pointer to data
getRow() [1/2]
void sgpp::base::DataMatrix::getRow (size_t row, DataVector & vec) const
Copies the values of a row to the DataVector vec.
Parameters
row The row
vec DataVector into which the data is written
References sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::datadriven::DataBasedRefinementFunctor::computeHkl(), sgpp::datadriven::DBMatOnlineDE::computeL2Error(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadratureFunc(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::base::VectorFunction::eval(), sgpp::base::ScalarFunction::eval(), sgpp::base::ScalarFunctionGradient::eval(), sgpp::base::ScalarFunctionHessian::eval(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::PiecewiseConstantRegression::Node::getSupportIndizes(), sgpp::datadriven::RosenblattTransformation::initialize(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::AlgorithmDGEMV< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult(), sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult(), sgpp::base::AlgorithmMultipleEvaluation< BASIS >::mult_transpose(), sgpp::datadriven::AlgorithmMultipleEvaluationDistributed< BASIS >::mult_transpose(), sgpp::base::AlgorithmDGEMV< BASIS >::mult_transposed(), sgpp::combigrid::OperationEvalFullGrid::multiEval(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multImpl(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multTransposeImpl(), sgpp::base::VectorSurplusRefinementFunctor::operator()(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::LearnerSGDE::predict(), sgpp::datadriven::LearnerSVM::predict(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::LearnerSGDEOnOffParallel::splitBatchIntoClasses(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::LearnerSVM::storeResults(), sgpp::datadriven::LearnerSVM::train(), sgpp::datadriven::LearnerSGD::train(), sgpp::datadriven::ModelFittingClassification::update(), and sgpp::datadriven::CSVTools::writeMatrixToCSVFile().
getRow() [2/2]
void sgpp::base::DataMatrix::getRow (size_t row, std::vector< double > & vec) const
Copies the values of a row to the std::vector vec.
Parameters
row The row
vec std::vector into which the data is written
getSize()
size_t sgpp::base::DataMatrix::getSize () const inline
Returns the total number of (used) elements, i.e., getNrows()*getNCols()
Returns
Number of elements stored in the matrix
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyModification(), python.uq.uq_setting.UQSetting.UQSetting::convert(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), sgpp::datadriven::DBMatOfflineDenseIChol::ichol(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::OperationMultiEvalStreamingBSplineOCL(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::OperationMultiEvalStreamingModOCLFastMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::OperationMultiEvalStreamingModOCLMaskMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::OperationMultiEvalStreamingModOCLUnified(), sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::OperationMultiEvalStreamingOCLMultiPlatform(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), and python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution().
max() [1/2]
double sgpp::base::DataMatrix::max () const
Returns the maximum over all entries.
Returns
Maximal value of all entries
References max().
Referenced by max(), and max().
max() [2/2]
double sgpp::base::DataMatrix::max (size_t col) const
Returns the maximum value of column col.
Parameters
col Number of the column
Returns
Maximum value
References max().
Referenced by sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), and sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification().
min() [1/2]
double sgpp::base::DataMatrix::min () const
Returns the minimum over all entries.
Returns
Minimal value of all entries
References min().
Referenced by min(), and min().
min() [2/2]
double sgpp::base::DataMatrix::min (size_t col) const
Returns the minimum value of column col.
Parameters
col Number of the column
Returns
Minimum value
References min().
Referenced by sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification(), and sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification().
minmax() [1/2]
void sgpp::base::DataMatrix::minmax (double * min, double * max) const
Determines minimum and maximum over all entries.
Parameters
min Reference variable for the minimum
max Reference variable for the maximum
minmax() [2/2]
void sgpp::base::DataMatrix::minmax (size_t col, double * min, double * max) const
Determines minimum and maximum of column col.
Parameters
col Number of the column
min Reference variable for the minimum
max Reference variable for the maximum
Referenced by normalizeDimension().
mult() [1/2]
void sgpp::base::DataMatrix::mult (const DataVector & x, DataVector & y) const
Multiplies the matrix with a vector x and stores the result in another vector y.
Parameters
[in] x vector to be multiplied
[out] y vector in which the result should be stored
References sgpp::base::DataVector::getSize().
mult() [2/2]
void sgpp::base::DataMatrix::mult (double scalar)
Multiplies all elements by a constant factor.
Parameters
scalar the constant
Referenced by sgpp::combigrid::CombinationGrid::combineValues(), sgpp::datadriven::DBMatOfflinePermutable::dimensionBlowUp(), sgpp::datadriven::OperationMultipleEvalMatrix::mult(), sgpp::datadriven::OperationMultipleEvalMatrix::multTranspose(), sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::datadriven::BayesianOptimization::updateGP(), and sgpp::datadriven::BayesianOptimization::var().
normalizeDimension() [1/2]
void sgpp::base::DataMatrix::normalizeDimension (size_t d)
Normalizes the d-th dimension (entries in the d-th column) to \([0,1]\).
Considers contents of DataMatrix as a d-dimensional dataset, one data point per row.
Parameters
d The dimension (column) that should be normalized (starting with 0)
References normalizeDimension().
Referenced by sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), and normalizeDimension().
normalizeDimension() [2/2]
void sgpp::base::DataMatrix::normalizeDimension (size_t d, double border)
Normalizes the d-th dimension (entries in the d-th column) to \([border,1-border]\).
Considers contents of DataMatrix as a d-dimensional dataset, one data point per row.
Parameters
d The dimension (column) that should be normalized (starting with 0)
border Width of the border
References minmax().
operator()() [1/2]
double & sgpp::base::DataMatrix::operator() (size_t row, size_t col) inline
Returns the value of the element at position [row,col].
Parameters
row Row
col Column
Returns
reference to the element
operator()() [2/2]
const double & sgpp::base::DataMatrix::operator() (size_t row, size_t col) const inline
Returns the value of the element at position [row,col].
Parameters
row Row
col Column
Returns
constant reference to the element
operator=() [1/2]
DataMatrix & sgpp::base::DataMatrix::operator= (const DataMatrix &) default
Copy assignment operator.
operator=() [2/2]
DataMatrix & sgpp::base::DataMatrix::operator= (DataMatrix &&) default
Move assignment operator.
reserveAdditionalRows()
void sgpp::base::DataMatrix::reserveAdditionalRows (size_t inc_nrows)
Reserves memory for potentially inc_nrows new rows; the actual number of rows remains unchanged.
Corresponds to a resize to nrows+inc_nrows new rows while leaving the current matrix' size unchanged.
Parameters
inc_nrows Number of additional rows for which storage is to be reserved.
Referenced by sgpp::datadriven::LearnerSGD::LearnerSGD(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), and sgpp::datadriven::PrimalDualSVM::PrimalDualSVM().
resize() [1/2]
void sgpp::base::DataMatrix::resize (size_t nrows)
Resizes the DataMatrix to nrows rows.
All new additional entries are uninitialized. If nrows is smaller than the current number of rows, all superfluous entries are removed.
Deprecated:
use resizeRows
Parameters
nrows New number of rows of the DataMatrix
References resizeRows().
Referenced by sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::combigrid::CombinationGrid::combineSparseGridValues(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::VectorFunction::eval(), sgpp::base::ScalarFunctionGradient::eval(), sgpp::base::ScalarFunctionHessian::eval(), sgpp::base::OperationEvalGradient::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessian::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::HashGridStorage::getCoordinateArrays(), sgpp::base::EvalCuboidGenerator::getEvaluationCuboid(), sgpp::base::EvalCuboidGeneratorForStretching::getEvaluationCuboid(), sgpp::base::DataTensor::getMatrix(), sgpp::combigrid::IndexVectorRange::getPoints(), sgpp::optimization::math::hessenbergForm(), sgpp::datadriven::VisualizerClassification::initializeMatrices(), sgpp::datadriven::VisualizerDensityEstimation::initializeMatrices(), sgpp::optimization::optimizer::AugmentedLagrangian::optimize(), sgpp::optimization::optimizer::LogBarrier::optimize(), sgpp::optimization::optimizer::SquaredPenalty::optimize(), sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::AdaptiveGradientDescent::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::BFGS::optimize(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::optimization::optimizer::DifferentialEvolution::optimize(), sgpp::optimization::optimizer::GradientDescent::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), sgpp::optimization::optimizer::NelderMead::optimize(), sgpp::optimization::optimizer::Newton::optimize(), sgpp::optimization::optimizer::NLCG::optimize(), sgpp::optimization::optimizer::Rprop::optimize(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::optimization::math::QRDecomposition(), sgpp::optimization::file_io::readMatrix(), resizeQuadratic(), sgpp::optimization::math::schurDecomposition(), sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector(), sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector(), sgpp::datadriven::test_calculateROCcurve(), and transpose().
resize() [2/2]
void sgpp::base::DataMatrix::resize (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
All new additional entries are uninitialized. If nrows*ncols is smaller than the current number of entries, all superfluous entries are removed.
Deprecated:
use resizeRowsCols
Parameters
nrows New number of rows of the DataMatrix
ncols New number of columns of the DataMatrix
References resizeRowsCols().
resizeQuadratic()
void sgpp::base::DataMatrix::resizeQuadratic (size_t size)
Resizes the quadratic DataMatrix to size rows and size columns.
All new additional entries are uninitialized. If size is smaller than the current size of the quadratic DataMatrix, all superfluous entries are removed.
Parameters
size New dimension of quadratic data DataMatrix
References resize().
Referenced by sgpp::datadriven::DBMatOfflineOrthoAdapt::buildMatrix(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatDMSDenseIChol::DBMatDMSDenseIChol(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), and sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel().
resizeRows()
void sgpp::base::DataMatrix::resizeRows (size_t nrows)
Resizes the DataMatrix to nrows rows.
All new additional entries are uninitialized. If nrows is smaller than the current number of rows, all superfluous entries are removed.
Parameters
nrows New number of rows of the DataMatrix
Referenced by resize(), and resizeZero().
resizeRowsCols()
void sgpp::base::DataMatrix::resizeRowsCols (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
All new additional entries are uninitialized. If nrows*ncols is smaller than the current number of entries, all superfluous entries are removed.
Parameters
nrows New number of rows of the DataMatrix
ncols New number of columns of the DataMatrix
Referenced by sgpp::datadriven::MPIMethods::receiveGridComponentsUpdate(), resize(), and resizeZero().
resizeToSubMatrix()
void sgpp::base::DataMatrix::resizeToSubMatrix (size_t row_1, size_t col_1, size_t row_2, size_t col_2)
Resize current matrix to the submatrix Mat[row_1:row_2, col_1:col_2].
Parameters
row_1,col_1 corresponding to left upper index of desired submatrix
row_2,col_2 corresponding to right lower index of desired submatrix
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::VisualizerDensityEstimation::storeCutJson(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), and sgpp::datadriven::VisualizerClassification::storeHeatmapJsonClassification().
resizeZero() [1/2]
void sgpp::base::DataMatrix::resizeZero (size_t nrows)
Resizes the DataMatrix to nrows rows.
All new additional entries are set to zero. If nrows is smaller than the current number of rows, all superfluous entries are removed.
Deprecated:
use resizeRows
Parameters
nrows New number of rows of the DataMatrix
References resizeRows().
resizeZero() [2/2]
void sgpp::base::DataMatrix::resizeZero (size_t nrows, size_t ncols)
Resizes the DataMatrix to nrows rows and ncols columns.
All new additional entries are set to zero. If nrows*ncols is smaller than the current number of entries, all superfluous entries are removed.
Deprecated:
use resizeRowsCols
Parameters
nrows New number of rows of the DataMatrix
ncols New number of columns of the DataMatrix
References resizeRowsCols().
set()
void sgpp::base::DataMatrix::set (size_t row, size_t col, double value) inline
Sets the element at position [row,col] to value.
Parameters
row Row
col Column
value New value for element
Referenced by sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::pde::OperationMatrixLTwoDotExplicitLinear::buildMatrixWithBounds(), sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear::buildMatrixWithBounds(), sgpp::pde::OperationMatrixLTwoDotExplicitModLinear::buildMatrixWithBounds(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatOfflineDenseIChol::choleskyModification(), sgpp::datadriven::DensityEstimator::corrcoef(), sgpp::datadriven::Friedman1Generator::createData(), sgpp::datadriven::Friedman2Generator::createData(), sgpp::datadriven::Friedman3Generator::createData(), sgpp::datadriven::BayesianOptimization::decomposeCholesky(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::base::HashGridStorage::getLevelIndexArraysForEval(), sgpp::base::HashGridStorage::getLevelIndexMaskArraysForModEval(), sgpp::datadriven::DBMatOfflineDenseIChol::ichol(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), sgpp::datadriven::BayesianOptimization::likelihood(), sgpp::datadriven::OperationMultiEvalMPI::multSlave(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::datadriven::ARFFTools::readARFF(), sgpp::datadriven::CSVTools::readCSV(), sgpp::datadriven::Harmonica::setParameters(), sgpp::datadriven::BayesianOptimization::setScales(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::test_calculateROCcurve(), and sgpp::datadriven::BayesianOptimization::updateGP().
setAll()
void sgpp::base::DataMatrix::setAll (double value)
Sets all entries of DataMatrix to value.
Parameters
value New value for all entries
Referenced by sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::combigrid::CombinationGrid::combineSparseGridValues(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), and sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian().
setColumn()
void sgpp::base::DataMatrix::setColumn (size_t col, const DataVector & vec)
Sets a column of the DataMatrix to the values of a DataVector vec.
Parameters
col The column which is to be overwritten
vec DataVector containing the data of the column
References sgpp::base::DataVector::get(), and sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::SparseGridDensityEstimator::marginalize(), sgpp::datadriven::SparseGridDensityEstimator::margToDimX(), sgpp::combigrid::OperationEvalCombinationGrid::multiEval(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector(), sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector(), sgpp::datadriven::VisualizerDensityEstimation::swapColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumns(), sgpp::datadriven::VisualizerDensityEstimation::translateColumnsLeft(), and sgpp::datadriven::VisualizerDensityEstimation::translateColumnsRight().
setRow()
void sgpp::base::DataMatrix::setRow (size_t row, const DataVector & vec)
Sets a row of the DataMatrix to the values of a DataVector vec.
Parameters
row The row which is to be overwritten
vec DataVector containing the data of the row
References sgpp::base::DataVector::get(), and sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::PrimalDualSVM::add(), sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::base::VectorFunction::eval(), sgpp::base::ScalarFunctionGradient::eval(), sgpp::base::ScalarFunctionHessian::eval(), sgpp::base::OperationEvalGradient::evalGradient(), sgpp::base::OperationEvalHessian::evalHessian(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::base::DistributionsVector::getBounds(), sgpp::base::HashGridStorage::getCoordinateArrays(), sgpp::base::EvalCuboidGenerator::getEvaluationCuboid(), sgpp::base::EvalCuboidGeneratorForStretching::getEvaluationCuboid(), sgpp::base::DataTensor::getMatrix(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset(), sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix(), sgpp::datadriven::PrimalDualSVM::predictRaw(), sgpp::datadriven::LearnerSGD::pushToBatch(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), and sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel().
sqr()
void sgpp::base::DataMatrix::sqr ()
Squares all elements of the DataMatrix.
sqrt()
void sgpp::base::DataMatrix::sqrt ()
Takes the square root of all elements of the DataMatrix.
sub()
void sgpp::base::DataMatrix::sub (const DataMatrix & matr)
Subtracts the values from another DataMatrix of the current values.
Modifies the current values.
Parameters
matr The DataMatrix which is subtracted from the current values
sum()
double sgpp::base::DataMatrix::sum () const
Returns the sum of all elements.
Returns
The sum of all elements
toFile()
void sgpp::base::DataMatrix::toFile (const std::string & fileName) const
References f, fileName, and toString().
toString() [1/2]
std::string sgpp::base::DataMatrix::toString () const
Returns a description of the DataMatrix as a string.
Returns
string of the DataMatrix
References toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), toFile(), and toString().
toString() [2/2]
void sgpp::base::DataMatrix::toString (std::string & text) const
Writes the data stored in the DataMatrix into a string.
Parameters
text String to which the data is written
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::OperationMultiEvalHPX::mult(), sgpp::datadriven::DBMatOffline::printMatrix(), sgpp::datadriven::DataMatrixDistributed::printMatrix(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
transpose()
void sgpp::base::DataMatrix::transpose ()
Transposes this DataMatrix.
References resize().
Referenced by sgpp::datadriven::OperationMultipleEvalMatrix::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::OperationMultiEvalModMaskStreaming(), sgpp::datadriven::OperationMultiEvalStreaming::OperationMultiEvalStreaming(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::OperationMultiEvalStreamingBSpline(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::OperationMultiEvalStreamingBSplineOCL(), sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::OperationMultiEvalStreamingModOCLFastMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLMaskMultiPlatform< T >::OperationMultiEvalStreamingModOCLMaskMultiPlatform(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt(), sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::OperationMultiEvalStreamingModOCLUnified(), and sgpp::datadriven::StreamingOCLMultiPlatform::OperationMultiEvalStreamingOCLMultiPlatform< T >::OperationMultiEvalStreamingOCLMultiPlatform().
The documentation for this class was generated from the following files:
base/src/sgpp/base/datatypes/DataMatrix.hpp
base/src/sgpp/base/datatypes/DataMatrix.cpp