SG++-Doxygen-Documentation: sgpp::pde::UpDownOneOpDimEnhanced Class Reference
sgpp::pde::UpDownOneOpDimEnhanced Class Reference abstract
Implements a modified Up/Down Schema with one operation dim.
#include <UpDownOneOpDimEnhanced.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
void multParallelBuildingBlock (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
this functions provides the same functionality as the normal mult routine.
UpDownOneOpDimEnhanced (sgpp::base::GridStorage *storage)
Constructor.
UpDownOneOpDimEnhanced (sgpp::base::GridStorage *storage, sgpp::base::DataVector &coef)
Constructor.
virtual ~UpDownOneOpDimEnhanced ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
virtual void down (sgpp::base::DataMatrix &alpha, sgpp::base::DataMatrix &result, size_t dim)=0
1D down Operation
virtual void up (sgpp::base::DataMatrix &alpha, sgpp::base::DataMatrix &result, size_t dim)=0
1D up Operation
void updown (sgpp::base::DataMatrix &alpha, sgpp::base::DataMatrix &result, size_t dim)
Recursive procedure for updown.
Protected Attributes
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::DataVector * coefs
Pointer to the sgpp::base::DataVector of the coefs.
const size_t numAlgoDims_
number of algorithmic dimensions
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Static Protected Attributes
static const size_t maxParallelDims_ = TASKS_PARALLEL_UPDOWN
max number of parallel stages (dimension recursive calls)
Detailed Description
Implements a modified Up/Down Schema with one operation dim.
All $d$ Up/Downs are executed concurrently and the results are merged afterwards.
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::UpDownOneOpDimEnhanced::grid_iterator protected
Constructor & Destructor Documentation
UpDownOneOpDimEnhanced() [1/2]
sgpp::pde::UpDownOneOpDimEnhanced::UpDownOneOpDimEnhanced (sgpp::base::GridStorage * storage, sgpp::base::DataVector & coef)
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
coef reference to a sgpp::base::DataVector object that contains the bilinear form's constant coefficients; one per dimension
UpDownOneOpDimEnhanced() [2/2]
sgpp::pde::UpDownOneOpDimEnhanced::UpDownOneOpDimEnhanced (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~UpDownOneOpDimEnhanced()
sgpp::pde::UpDownOneOpDimEnhanced::~UpDownOneOpDimEnhanced () virtual
Destructor.
Member Function Documentation
down()
virtual void sgpp::pde::UpDownOneOpDimEnhanced::down (sgpp::base::DataMatrix & alpha, sgpp::base::DataMatrix & result, size_t dim) protected pure virtual
1D down Operation
Parameters
dim dimension in which to apply the down-part
alpha matrix of coefficients
result matrix to store the results of all dimensions
Implemented in sgpp::pde::OperationLaplaceEnhancedLinear, and sgpp::pde::OperationLaplaceEnhancedLinearBoundary.
Referenced by updown().
mult()
void sgpp::pde::UpDownOneOpDimEnhanced::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::base::OperationMatrix.
References sgpp::base::DataMatrix::addReduce(), alpha, coefs, sgpp::base::DataMatrix::expand(), sgpp::base::DataVector::getSize(), numAlgoDims_, sgpp::base::DataVector::setAll(), and updown().
multParallelBuildingBlock()
void sgpp::pde::UpDownOneOpDimEnhanced::multParallelBuildingBlock (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result)
this functions provides the same functionality as the normal mult routine.
However, it doesn't set up an OpenMP task initialization as the mult routine. This method has to be called within a OpenMP task parallelized region.
Using this function is useful in following case: Assuming the solver of a certain requires several operators in the space discretization (e.g. Black Scholes Equations) this method can be used to parallelize their calculation which might results results in a better parallel efficiency on systems with 4 or more cores hence fewer barriers are needed.
Parameters
alpha vector of coefficients
result vector to store the results in
References sgpp::base::DataMatrix::addReduce(), alpha, coefs, sgpp::base::DataMatrix::expand(), sgpp::base::DataVector::getSize(), numAlgoDims_, sgpp::base::DataVector::setAll(), and updown().
up()
virtual void sgpp::pde::UpDownOneOpDimEnhanced::up (sgpp::base::DataMatrix & alpha, sgpp::base::DataMatrix & result, size_t dim) protected pure virtual
1D up Operation
Parameters
dim dimension in which to apply the up-part
alpha matrix of coefficients
result matrix to store the results of all dimensions
Implemented in sgpp::pde::OperationLaplaceEnhancedLinear, and sgpp::pde::OperationLaplaceEnhancedLinearBoundary.
Referenced by updown().
updown()
void sgpp::pde::UpDownOneOpDimEnhanced::updown (sgpp::base::DataMatrix & alpha, sgpp::base::DataMatrix & result, size_t dim) protected
Recursive procedure for updown.
Parameters
dim the current dimension
alpha matrix of coefficients
result matrix to store the results of all dimensions
References sgpp::base::DataMatrix::add(), alpha, down(), maxParallelDims_, numAlgoDims_, up(), and updown().
Referenced by mult(), multParallelBuildingBlock(), and updown().
Member Data Documentation
algoDims
const std::vector<size_t> sgpp::pde::UpDownOneOpDimEnhanced::algoDims protected
algorithmic dimensions, operator is applied in this dimensions
coefs
sgpp::base::DataVector* sgpp::pde::UpDownOneOpDimEnhanced::coefs protected
Pointer to the sgpp::base::DataVector of the coefs.
Referenced by mult(), and multParallelBuildingBlock().
maxParallelDims_
const size_t sgpp::pde::UpDownOneOpDimEnhanced::maxParallelDims_ = TASKS_PARALLEL_UPDOWN static protected
max number of parallel stages (dimension recursive calls)
Referenced by updown().
numAlgoDims_
const size_t sgpp::pde::UpDownOneOpDimEnhanced::numAlgoDims_ protected
number of algorithmic dimensions
Referenced by mult(), multParallelBuildingBlock(), and updown().
storage
sgpp::base::GridStorage* sgpp::pde::UpDownOneOpDimEnhanced::storage protected
Pointer to the grid's storage object.
Referenced by sgpp::pde::OperationLaplaceEnhancedLinear::down(), sgpp::pde::OperationLaplaceEnhancedLinearBoundary::down(), sgpp::pde::OperationLaplaceEnhancedLinear::up(), and sgpp::pde::OperationLaplaceEnhancedLinearBoundary::up().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/algorithm/UpDownOneOpDimEnhanced.hpp
pde/src/sgpp/pde/algorithm/UpDownOneOpDimEnhanced.cpp