SG++-Doxygen-Documentation: sgpp::base::WrapperScalarFunction Class Reference
sgpp::base::WrapperScalarFunction Class Reference
Implementation of ScalarFunction that wraps a std::function object.
#include <WrapperScalarFunction.hpp>
Public Types
typedef std::function< double(const DataVector &)> FunctionEvalType
Public Member Functions
void clone (std::unique_ptr< ScalarFunction > &clone) const override
double eval (const DataVector &x) override
WrapperScalarFunction (size_t d, FunctionEvalType f)
Constructor.
~WrapperScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Protected Attributes
FunctionEvalType f
function to be wrapped
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
Implementation of ScalarFunction that wraps a std::function object.
Member Typedef Documentation
FunctionEvalType
typedef std::function<double(const DataVector&)> sgpp::base::WrapperScalarFunction::FunctionEvalType
Constructor & Destructor Documentation
WrapperScalarFunction()
sgpp::base::WrapperScalarFunction::WrapperScalarFunction (size_t d, FunctionEvalType f) inline
Constructor.
Parameters
d dimension of the domain
f function to be wrapped
~WrapperScalarFunction()
sgpp::base::WrapperScalarFunction::~WrapperScalarFunction () inline override
Destructor.
Member Function Documentation
clone()
void sgpp::base::WrapperScalarFunction::clone (std::unique_ptr< ScalarFunction > & clone) const inline override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone(), sgpp::base::ScalarFunction::d, and f.
Referenced by clone().
eval()
double sgpp::base::WrapperScalarFunction::eval (const DataVector & x) inline override virtual
Parameters
x evaluation point \(\vec{x} \in [0, 1]^d\)
Returns
\(f(\vec{x})\)
Implements sgpp::base::ScalarFunction.
References f.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
f
FunctionEvalType sgpp::base::WrapperScalarFunction::f protected
function to be wrapped
Referenced by clone(), eval(), and python.uq.refinement.RefinementStrategy.PredictiveRanking::rank().
The documentation for this class was generated from the following file:
base/src/sgpp/base/function/scalar/WrapperScalarFunction.hpp