SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T > Class Template Reference
Operation for creation of a k nearest neighbors graph using a dataset.
#include <OperationCreateGraphOCLSingleDevice.hpp>
Public Member Functions
void begin_graph_creation (int startid, int chunksize)
void create_graph (std::vector< int > &resultVector, int startid=0, int chunksize=0)
Creates part of the k nearest neighbor graph (or all of it with the default parameters)
void finalize_graph_creation (std::vector< int > &resultVector, int startid, int chunksize)
OperationCreateGraphOCLSingleDevice (base::DataMatrix &data, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration *parameters, size_t k, size_t platform_id, size_t device_id)
Constructor using a DataMatrix.
OperationCreateGraphOCLSingleDevice (double *dataset, size_t datasize, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration *parameters, size_t k, size_t platform_id, size_t device_id)
Constructor which accepts double vector instead of a DataMatrix.
void set_problemchunk (size_t start_id, size_t chunksize)
virtual ~OperationCreateGraphOCLSingleDevice (void)
Public Member Functions inherited from sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL
OperationCreateGraphOCL ()
virtual ~OperationCreateGraphOCL (void)
Additional Inherited Members
Static Public Member Functions inherited from sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL
static std::vector< size_t > find_clusters (std::vector< int > &graph, size_t k)
Assign a clusterindex for each datapoint using the connected components of the graph.
static void load_default_parameters (base::OCLOperationConfiguration *parameters)
Add the default parameters to the the configuration.
Static Protected Member Functions inherited from sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL
static size_t find_neighbors (size_t index, std::vector< int > &nodes, size_t cluster, size_t k, std::vector< size_t > &clusterList, bool overwrite=false)
Recursive function for traversing the k nearest neighbor graph.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >
Operation for creation of a k nearest neighbors graph using a dataset.
Constructor & Destructor Documentation
OperationCreateGraphOCLSingleDevice() [1/2]
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::OperationCreateGraphOCLSingleDevice (base::DataMatrix & data, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration * parameters, size_t k, size_t platform_id, size_t device_id) inline
Constructor using a DataMatrix.
OperationCreateGraphOCLSingleDevice() [2/2]
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::OperationCreateGraphOCLSingleDevice (double * dataset, size_t datasize, size_t dimensions, std::shared_ptr< base::OCLManagerMultiPlatform > manager, sgpp::base::OCLOperationConfiguration * parameters, size_t k, size_t platform_id, size_t device_id) inline
Constructor which accepts double vector instead of a DataMatrix.
References dataset.
~OperationCreateGraphOCLSingleDevice()
template<typename T > virtual sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::~OperationCreateGraphOCLSingleDevice (void) inline virtual
Member Function Documentation
begin_graph_creation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::begin_graph_creation (int startid, int chunksize) inline virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation().
create_graph()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::create_graph (std::vector< int > & resultVector, int startid = 0, int chunksize = 0) inline virtual
Creates part of the k nearest neighbor graph (or all of it with the default parameters)
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::finalize_graph_creation(), and sgpp::base::operation_exception::what().
finalize_graph_creation()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::finalize_graph_creation (std::vector< int > & resultVector, int startid, int chunksize) inline virtual
Implements sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL.
References sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::finalize_graph_creation().
set_problemchunk()
template<typename T > void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >::set_problemchunk (size_t start_id, size_t chunksize) inline
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationCreateGraphOCL/OperationCreateGraphOCLSingleDevice.hpp