SG++-Doxygen-Documentation: sgpp::datadriven::DensityDifferenceSystemMatrix Class Reference
sgpp::datadriven::DensityDifferenceSystemMatrix Class Reference
Class that implements the virtual class OperationMatrix for the application of density estimation for the Systemmatrix by using a density difference function for two input datasets.
#include <DensityDifferenceSystemMatrix.hpp>
Public Member Functions
void computeUnweightedRhs (base::DataVector &bp, base::DataVector &bq)
Computes the unweighted right hand sides of the density estimation equation.
DensityDifferenceSystemMatrix (base::Grid &grid, base::DataMatrix &trainData_P, base::DataMatrix &trainData_Q, base::OperationMatrix *C, double lambda)
Std-Constructor.
DensityDifferenceSystemMatrix (sgpp::base::OperationMatrix *A, sgpp::base::OperationMultipleEval *B_p, sgpp::base::OperationMultipleEval *B_q, sgpp::base::OperationMatrix *C, double lambda, size_t numSamples_P, size_t numSamples_Q)
Std-Constructor.
void generateb (base::DataVector &b)
Generates the right hand side of the classification equation.
void mult (base::DataVector &alpha, base::DataVector &result)
Generates the left hand side of the density estimation equation.
virtual ~DensityDifferenceSystemMatrix ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Class that implements the virtual class OperationMatrix for the application of density estimation for the Systemmatrix by using a density difference function for two input datasets.
Constructor & Destructor Documentation
DensityDifferenceSystemMatrix() [1/2]
sgpp::datadriven::DensityDifferenceSystemMatrix::DensityDifferenceSystemMatrix (sgpp::base::OperationMatrix * A, sgpp::base::OperationMultipleEval * B_p, sgpp::base::OperationMultipleEval * B_q, sgpp::base::OperationMatrix * C, double lambda, size_t numSamples_P, size_t numSamples_Q)
Std-Constructor.
Parameters
A L^2 dot product matrix of some grid
B_p MultipleEval matrix of grid and data points for first dataset
B_q MultipleEval matrix of grid and data points for second dataset
C the regression functional
lambda the regression parameter
numSamples_P number of data samples for first dataset
numSamples_Q number of data samples for second dataset
DensityDifferenceSystemMatrix() [2/2]
sgpp::datadriven::DensityDifferenceSystemMatrix::DensityDifferenceSystemMatrix (base::Grid & grid, base::DataMatrix & trainData_P, base::DataMatrix & trainData_Q, base::OperationMatrix * C, double lambda)
Std-Constructor.
Parameters
grid reference to the sparse grid
trainData_P reference to DataVector that contains the training data from first dataset
trainData_Q reference to DataVector that contains the training data from second dataset
C the regression functional
lambda the regression parameter
References sgpp::op_factory::createOperationLTwoDotProduct(), sgpp::op_factory::createOperationMultipleEval(), and grid().
~DensityDifferenceSystemMatrix()
sgpp::datadriven::DensityDifferenceSystemMatrix::~DensityDifferenceSystemMatrix () virtual
Std-Destructor.
Member Function Documentation
computeUnweightedRhs()
void sgpp::datadriven::DensityDifferenceSystemMatrix::computeUnweightedRhs (base::DataVector & bp, base::DataVector & bq)
Computes the unweighted right hand sides of the density estimation equation.
Parameters
bp reference to the vector which will contain the result of the matrix vector multiplication on the rhs for first dataset
bq reference to the vector which will contain the result of the matrix vector multiplication on the rhs for second dataset
References sgpp::base::DataVector::setAll().
Referenced by generateb(), and sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update().
generateb()
void sgpp::datadriven::DensityDifferenceSystemMatrix::generateb (base::DataVector & b)
Generates the right hand side of the classification equation.
Parameters
b reference to the vector which will contain the result of the matrix vector multiplication on the rhs
References sgpp::base::DataVector::axpy(), computeUnweightedRhs(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::mult().
mult()
void sgpp::datadriven::DensityDifferenceSystemMatrix::mult (base::DataVector & alpha, base::DataVector & result) virtual
Generates the left hand side of the density estimation equation.
Parameters
alpha parameters for the sparse grid functions
result reference to the vector which will contain the result
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DensityDifferenceSystemMatrix.hpp
datadriven/src/sgpp/datadriven/algorithm/DensityDifferenceSystemMatrix.cpp