SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOffline Class Reference
sgpp::datadriven::DBMatOffline Class Reference abstract
Class that is used to decompose and store the left-hand-side matrix for the density based classification approach (The classification is divided into two parts: the offline step that does not depend on the actual data and the online step that depends on the data).
#include <DBMatOffline.hpp>
Public Member Functions
virtual void buildMatrix (Grid *grid, const RegularizationConfiguration &regularizationConfig)
Builds the right hand side matrix with or without the regularization term depending on the type of decomposition.
virtual DBMatOffline * clone () const =0
Interface for the clone idiom.
virtual void compute_inverse ()
virtual void compute_inverse_parallel (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
parallel/distributed version of compute_inverse()
void compute_L2_refine_vectors (DataMatrix *mat_refine, Grid *grid, size_t newPoints)
computes vectors of L2 products of grid points for refinement
DBMatOffline (const DBMatOffline &rhs)
Copy Constructor.
DBMatOffline (const std::string &fileName)
Constructor Create offline object from serialized offline object.
DBMatOffline (DBMatOffline &&rhs)=default
Default move constructor.
virtual void decomposeMatrix (const RegularizationConfiguration &regularizationConfig, const DensityEstimationConfiguration &densityEstimationConfig)=0
Decomposes the matrix according to the chosen decomposition type.
virtual void decomposeMatrixParallel (RegularizationConfiguration &regularizationConfig, DensityEstimationConfiguration &densityEstimationConfig, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
The parallel/distributed version of decomposeMatrix(...)
DataMatrixDistributed & getDecomposedInverseDistributed ()
Get a reference to the distributed decomposed matrix, analogously to getDecomposedMatrixDistributed()
DataMatrix & getDecomposedMatrix ()
Get a reference to the decomposed matrix.
DataMatrixDistributed & getDecomposedMatrixDistributed ()
Get a reference to the distributed decomposed matrix.
virtual sgpp::datadriven::MatrixDecompositionType getDecompositionType ()=0
Returns the decomposition type of the DBMatOffline object.
virtual size_t getGridSize ()
Returns the dimensionality of the quadratic lhs matrix (i.e.
DataMatrix & getInverseMatrix ()
Get a reference to the inverse matrix.
DataMatrix & getLhsMatrix_ONLY_FOR_TESTING ()
Allows access to lhs matrix, which is meant ONLY FOR TESTING.
virtual const DataMatrix & getUnmodifiedR ()=0
Get the unmodified (without added lambda) system matrix R.
virtual const DataMatrixDistributed & getUnmodifiedRDistributed (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)=0
Get the distributed version of the unmodified (without added lambda) system matrix R.
virtual bool isRefineable ()=0
Only Offline objects based on Cholesky decomposition, or orthogonal adaptivity can be refined.
DBMatOffline & operator= (const DBMatOffline &rhs)
Default copy assign operator.
DBMatOffline & operator= (DBMatOffline &&rhs)=default
Default move assign operator.
void printMatrix ()
Prints the matrix onto standard output.
virtual void store (const std::string &fileName)
Serialize the DBMatOffline Object.
virtual void syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the decomposed matrix.
virtual void syncDistributedInverse (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the inverse matrix.
virtual void updateRegularization (double lambda)=0
Modifies the decomposition to update the regularization parameter lambda.
virtual void updateRegularizationParallel (double lambda, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)=0
Modifies the parallel decomposition to update the regularization parameter lambda.
virtual ~DBMatOffline ()=default
Default virtual destructor.
Public Attributes
std::set< std::set< size_t > > interactions
Protected Member Functions
DBMatOffline ()
void parseInter (const std::string &fileName, std::set< std::set< size_t > > &interactions) const
Read the Interactionsterms from a serialized DBMatOfflibe object.
Protected Attributes
bool isConstructed
bool isDecomposed
DataMatrixDistributed lhsDistributed
DataMatrixDistributed lhsDistributedInverse
DataMatrix lhsInverse
DataMatrix lhsMatrix
Detailed Description
Class that is used to decompose and store the left-hand-side matrix for the density based classification approach (The classification is divided into two parts: the offline step that does not depend on the actual data and the online step that depends on the data).
Uses Gnu Scientific Library (GSL).
Constructor & Destructor Documentation
DBMatOffline() [1/4]
sgpp::datadriven::DBMatOffline::DBMatOffline (const std::string & fileName) explicit
Constructor Create offline object from serialized offline object.
Parameters
fileName path to the file that stores serialized offline object
References interactions, and parseInter().
DBMatOffline() [2/4]
sgpp::datadriven::DBMatOffline::DBMatOffline (const DBMatOffline & rhs)
Copy Constructor.
Parameters
rhs Object to copy
DBMatOffline() [3/4]
sgpp::datadriven::DBMatOffline::DBMatOffline (DBMatOffline && rhs) default
Default move constructor.
~DBMatOffline()
virtual sgpp::datadriven::DBMatOffline::~DBMatOffline () virtual default
Default virtual destructor.
DBMatOffline() [4/4]
sgpp::datadriven::DBMatOffline::DBMatOffline () protected
Member Function Documentation
buildMatrix()
void sgpp::datadriven::DBMatOffline::buildMatrix (Grid * grid, const RegularizationConfiguration & regularizationConfig) virtual
Builds the right hand side matrix with or without the regularization term depending on the type of decomposition.
Parameters
grid The grid object the matrix is based on
regularizationConfig Configures the regularization which is incorporated into the lhs
Reimplemented in sgpp::datadriven::DBMatOfflineGE, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
References sgpp::op_factory::createOperationLTwoDotExplicit(), grid(), isConstructed, and lhsMatrix.
Referenced by sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::buildMatrix(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::DBMatPermutationFactory::getPermutedObject(), and main().
clone()
virtual DBMatOffline * sgpp::datadriven::DBMatOffline::clone () const pure virtual
Interface for the clone idiom.
Returns
a copy of this very object as a pointer to a new DBMatOffline object which is owned by the caller.
Implemented in sgpp::datadriven::DBMatOfflineChol, sgpp::datadriven::DBMatOfflineDenseIChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), and sgpp::datadriven::DBMatPermutationFactory::getPermutedObject().
compute_inverse()
void sgpp::datadriven::DBMatOffline::compute_inverse () virtual
Reimplemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
compute_inverse_parallel()
void sgpp::datadriven::DBMatOffline::compute_inverse_parallel (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) virtual
parallel/distributed version of compute_inverse()
Parameters
processGrid process grid to distribute the matrix on
parallelConfig
Reimplemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit().
compute_L2_refine_vectors()
void sgpp::datadriven::DBMatOffline::compute_L2_refine_vectors (DataMatrix * mat_refine, Grid * grid, size_t newPoints)
computes vectors of L2 products of grid points for refinement
Parameters
mat_refine matrix to store L2 vectors
grid underlying grid
newPoints amount of points to refine
References grid(), sgpp::base::Linear, and sgpp::base::ModLinear.
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyModification().
decomposeMatrix()
virtual void sgpp::datadriven::DBMatOffline::decomposeMatrix (const RegularizationConfiguration & regularizationConfig, const DensityEstimationConfiguration & densityEstimationConfig) pure virtual
Decomposes the matrix according to the chosen decomposition type.
The number of rows of the stored result depends on the decomposition type.
Parameters
regularizationConfig the regularization configuration
densityEstimationConfig the density estimation configuration
Implemented in sgpp::datadriven::DBMatOfflineChol, sgpp::datadriven::DBMatOfflineDenseIChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::DBMatPermutationFactory::getPermutedObject(), and main().
decomposeMatrixParallel()
void sgpp::datadriven::DBMatOffline::decomposeMatrixParallel (RegularizationConfiguration & regularizationConfig, DensityEstimationConfiguration & densityEstimationConfig, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) virtual
The parallel/distributed version of decomposeMatrix(...)
Parameters
regularizationConfig the regularization configuration
densityEstimationConfig the density estimation configuration
processGrid process grid to distribute the matrix on
parallelConfig
Reimplemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit().
getDecomposedInverseDistributed()
DataMatrixDistributed & sgpp::datadriven::DBMatOffline::getDecomposedInverseDistributed ()
Get a reference to the distributed decomposed matrix, analogously to getDecomposedMatrixDistributed()
References isDecomposed, and lhsDistributedInverse.
Referenced by sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), and sgpp::datadriven::DBMatOnlineDE_SMW::solveSLEParallel().
getDecomposedMatrix()
DataMatrix & sgpp::datadriven::DBMatOffline::getDecomposedMatrix ()
Get a reference to the decomposed matrix.
Throws if matrix has not yet been decomposed.
Returns
decomposed matrix
References isDecomposed, and lhsMatrix.
Referenced by sgpp::datadriven::DBMatOnlineDE::computeDensityDifferenceFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunction(), sgpp::datadriven::DBMatOnlineDE::computeDensityFunctionParallel(), sgpp::datadriven::LearnerSGDEOnOffParallel::computeNewSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchParallel(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), and sgpp::datadriven::DBMatOnlineDEChol::solveSLE().
getDecomposedMatrixDistributed()
DataMatrixDistributed & sgpp::datadriven::DBMatOffline::getDecomposedMatrixDistributed ()
Get a reference to the distributed decomposed matrix.
Throws if matrix has not yet been decomposed. In order to return valid data, syncDistributedDecomposition() has to be called if the decomposition was changed (after refinements).
References isDecomposed, and lhsDistributed.
Referenced by sgpp::datadriven::DBMatOnlineDEChol::solveSLEParallel().
getDecompositionType()
virtual sgpp::datadriven::MatrixDecompositionType sgpp::datadriven::DBMatOffline::getDecompositionType () pure virtual
Returns the decomposition type of the DBMatOffline object.
Returns
the type of matrix decomposition
Implemented in sgpp::datadriven::DBMatOfflineChol, sgpp::datadriven::DBMatOfflineDenseIChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Referenced by sgpp::datadriven::DBMatOnlineDEChol::buildCholSolver(), sgpp::datadriven::DBMatOnlineDE_SMW::DBMatOnlineDE_SMW(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::DBMatOnlineDEOrthoAdapt(), and store().
getGridSize()
size_t sgpp::datadriven::DBMatOffline::getGridSize () virtual
Returns the dimensionality of the quadratic lhs matrix (i.e.
the number of rows)
Returns
the grid size
References sgpp::base::DataMatrix::getNrows(), and lhsMatrix.
Referenced by python.learner.TrainingStopPolicy.TrainingStopPolicy::hasGridSizeChanged(), python.learner.TrainingStopPolicy.TrainingStopPolicy::isTrainingComplete(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::sherman_morrison_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::store(), sgpp::datadriven::DBMatOnlineDE_SMW::updateSystemMatrixDecomposition(), sgpp::datadriven::DBMatOnlineDEOrthoAdapt::updateSystemMatrixDecomposition(), and sgpp::datadriven::DBMatOnlineDE_SMW::updateSystemMatrixDecompositionParallel().
getInverseMatrix()
DataMatrix & sgpp::datadriven::DBMatOffline::getInverseMatrix ()
Get a reference to the inverse matrix.
Returns
inverse matrix
References lhsInverse.
Referenced by sgpp::datadriven::DBMatOnlineDE_SMW::smw_adapt(), and sgpp::datadriven::DBMatOnlineDE_SMW::solveSLE().
getLhsMatrix_ONLY_FOR_TESTING()
sgpp::base::DataMatrix & sgpp::datadriven::DBMatOffline::getLhsMatrix_ONLY_FOR_TESTING ()
Allows access to lhs matrix, which is meant ONLY FOR TESTING.
References lhsMatrix.
getUnmodifiedR()
virtual const DataMatrix & sgpp::datadriven::DBMatOffline::getUnmodifiedR () pure virtual
Get the unmodified (without added lambda) system matrix R.
Returns
Matrix R
Implemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
getUnmodifiedRDistributed()
virtual const DataMatrixDistributed & sgpp::datadriven::DBMatOffline::getUnmodifiedRDistributed (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) pure virtual
Get the distributed version of the unmodified (without added lambda) system matrix R.
Only possible in the ScaLAPACK version.
Parameters
processGrid BLACS process grid
parallelConfig config options for ScaLAPACK
Returns
Matrix R
Implemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
isRefineable()
virtual bool sgpp::datadriven::DBMatOffline::isRefineable () pure virtual
Only Offline objects based on Cholesky decomposition, or orthogonal adaptivity can be refined.
Returns
true if object can be refined, else false;
Implemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
operator=() [1/2]
DBMatOffline & sgpp::datadriven::DBMatOffline::operator= (const DBMatOffline & rhs)
Default copy assign operator.
References interactions, isConstructed, isDecomposed, lhsInverse, and lhsMatrix.
operator=() [2/2]
DBMatOffline & sgpp::datadriven::DBMatOffline::operator= (DBMatOffline && rhs) default
Default move assign operator.
parseInter()
void sgpp::datadriven::DBMatOffline::parseInter (const std::string & fileName, std::set< std::set< size_t > > & interactions) const protected
Read the Interactionsterms from a serialized DBMatOfflibe object.
Parameters
fileName path of the serialized DBMatOffline object
interactions the interactions to populate
References fileName, and sgpp::base::StringTokenizer::tokenize().
Referenced by DBMatOffline().
printMatrix()
void sgpp::datadriven::DBMatOffline::printMatrix ()
Prints the matrix onto standard output.
References sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), isDecomposed, lhsMatrix, and sgpp::base::DataMatrix::toString().
store()
void sgpp::datadriven::DBMatOffline::store (const std::string & fileName) virtual
Serialize the DBMatOffline Object.
Parameters
fileName path where to store the file.
Reimplemented in sgpp::datadriven::DBMatOfflineOrthoAdapt.
References fileName, getDecompositionType(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), interactions, isDecomposed, and lhsMatrix.
Referenced by main(), and sgpp::datadriven::DBMatOfflineOrthoAdapt::store().
syncDistributedDecomposition()
void sgpp::datadriven::DBMatOffline::syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) virtual
Synchronizes the decomposed matrix.
Override if more matrices have to be synched.
Parameters
processGrid process grid to distribute the matrix on
parallelConfig
Reimplemented in sgpp::datadriven::DBMatOfflineOrthoAdapt.
References sgpp::datadriven::ParallelConfiguration::columnBlockSize_, sgpp::datadriven::DataMatrixDistributed::fromSharedData(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), isDecomposed, lhsDistributed, lhsMatrix, and sgpp::datadriven::ParallelConfiguration::rowBlockSize_.
Referenced by sgpp::datadriven::DBMatOnlineDE::syncDistributedDecomposition(), and sgpp::datadriven::DBMatOnlineDEOrthoAdapt::syncDistributedDecomposition().
syncDistributedInverse()
void sgpp::datadriven::DBMatOffline::syncDistributedInverse (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) virtual
Synchronizes the inverse matrix.
Parameters
processGrid process grid to distribute the matrix on
parallelConfig
References sgpp::datadriven::ParallelConfiguration::columnBlockSize_, sgpp::datadriven::DataMatrixDistributed::fromSharedData(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), isDecomposed, lhsDistributedInverse, lhsInverse, and sgpp::datadriven::ParallelConfiguration::rowBlockSize_.
updateRegularization()
virtual void sgpp::datadriven::DBMatOffline::updateRegularization (double lambda) pure virtual
Modifies the decomposition to update the regularization parameter lambda.
Parameters
lambda New lambda value
Implemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
updateRegularizationParallel()
virtual void sgpp::datadriven::DBMatOffline::updateRegularizationParallel (double lambda, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration & parallelConfig) pure virtual
Modifies the parallel decomposition to update the regularization parameter lambda.
Parameters
lambda New lambda value
processGrid ScaLAPACK process grid
parallelConfig Configuration for ScaLAPACK
Implemented in sgpp::datadriven::DBMatOfflineChol, and sgpp::datadriven::DBMatOfflineOrthoAdapt.
Member Data Documentation
interactions
std::set<std::set<size_t> > sgpp::datadriven::DBMatOffline::interactions
Referenced by sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchParallel(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), DBMatOffline(), sgpp::datadriven::DBMatOnlineDE::eval(), sgpp::datadriven::DBMatOnlineDE::evalParallel(), operator=(), and store().
isConstructed
bool sgpp::datadriven::DBMatOffline::isConstructed protected
Referenced by buildMatrix(), sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::DBMatOfflineOrthoAdapt(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), and operator=().
isDecomposed
bool sgpp::datadriven::DBMatOffline::isDecomposed protected
Referenced by sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatOfflineChol::choleskyPermutation(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::DBMatOfflineOrthoAdapt(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), getDecomposedInverseDistributed(), getDecomposedMatrix(), getDecomposedMatrixDistributed(), operator=(), printMatrix(), store(), syncDistributedDecomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::syncDistributedDecomposition(), and syncDistributedInverse().
lhsDistributed
DataMatrixDistributed sgpp::datadriven::DBMatOffline::lhsDistributed protected
Referenced by sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), getDecomposedMatrixDistributed(), sgpp::datadriven::DBMatOfflineOrthoAdapt::getUnmodifiedRDistributed(), and syncDistributedDecomposition().
lhsDistributedInverse
DataMatrixDistributed sgpp::datadriven::DBMatOffline::lhsDistributedInverse protected
Referenced by sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse_parallel(), getDecomposedInverseDistributed(), and syncDistributedInverse().
lhsInverse
DataMatrix sgpp::datadriven::DBMatOffline::lhsInverse protected
Referenced by sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), getInverseMatrix(), operator=(), and syncDistributedInverse().
lhsMatrix
DataMatrix sgpp::datadriven::DBMatOffline::lhsMatrix protected
Referenced by buildMatrix(), sgpp::datadriven::DBMatOfflineGE::buildMatrix(), sgpp::datadriven::DBMatOfflineChol::choleskyAddPoint(), sgpp::datadriven::DBMatOfflineChol::choleskyModification(), sgpp::datadriven::DBMatOfflineDenseIChol::choleskyModification(), sgpp::datadriven::DBMatOfflineChol::choleskyPermutation(), sgpp::datadriven::DBMatOfflineChol::compute_inverse(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse(), sgpp::datadriven::DBMatOfflineChol::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::compute_inverse_parallel(), sgpp::datadriven::DBMatOfflineGE::DBMatOfflineGE(), sgpp::datadriven::DBMatOfflineOrthoAdapt::DBMatOfflineOrthoAdapt(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrix(), sgpp::datadriven::DBMatOfflineChol::decomposeMatrixParallel(), sgpp::datadriven::DBMatOfflineOrthoAdapt::decomposeMatrixParallel(), getDecomposedMatrix(), getGridSize(), getLhsMatrix_ONLY_FOR_TESTING(), sgpp::datadriven::DBMatOfflineOrthoAdapt::getUnmodifiedR(), sgpp::datadriven::DBMatOfflineOrthoAdapt::getUnmodifiedRDistributed(), sgpp::datadriven::DBMatOfflineOrthoAdapt::hessenberg_decomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::invert_symmetric_tridiag(), operator=(), sgpp::datadriven::DBMatOfflinePermutable::permuteLhsMatrix(), printMatrix(), store(), syncDistributedDecomposition(), sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularization(), and sgpp::datadriven::DBMatOfflineOrthoAdapt::updateRegularizationParallel().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatOffline.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatOffline.cpp