SG++-Doxygen-Documentation: sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive Class Reference
sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive Class Reference
Operation for evaluating weakly fundamental spline linear combinations on Boundary grids with not-a-knot-boundary conditions and their gradients.
#include <OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive.hpp>
Public Member Functions
void evalGradient (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient) override
double evalGradient (const DataVector &alpha, const DataVector &point, DataVector &gradient) override
OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalGradient
OperationEvalGradient ()
Constructor.
virtual ~OperationEvalGradient ()
Destructor.
Protected Attributes
SWeaklyFundamentalNakSplineBase base
1D spline basis
SWeaklyFundamentalNakSplineBaseDeriv1 baseDeriv1
1D spline basis derivative
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalGradient
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating weakly fundamental spline linear combinations on Boundary grids with not-a-knot-boundary conditions and their gradients.
Constructor & Destructor Documentation
OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive()
sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive()
sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::~OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive () inline override
Destructor.
Member Function Documentation
evalGradient() [1/2]
void sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
Reimplemented from sgpp::base::OperationEvalGradient.
References alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalGradient() [2/2]
double sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient (const DataVector & alpha, const DataVector & point, DataVector & gradient) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient of linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalGradient.
References sgpp::base::DataVector::add(), alpha, base, baseDeriv1, sgpp::base::WeaklyFundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::WeaklyFundamentalNakSplineBasisDeriv1< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SWeaklyFundamentalNakSplineBase sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::base protected
1D spline basis
Referenced by evalGradient(), and evalGradient().
baseDeriv1
SWeaklyFundamentalNakSplineBaseDeriv1 sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::baseDeriv1 protected
1D spline basis derivative
Referenced by evalGradient(), and evalGradient().
innerDerivative
DataVector sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalGradient(), and evalGradient().
pointInUnitCube
DataVector sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalGradient(), and evalGradient().
storage
GridStorage& sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::storage protected
storage of the sparse grid
Referenced by evalGradient(), and evalGradient().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive.cpp