SG++-Doxygen-Documentation: sgpp::base::Stretching Class Reference
sgpp::base::Stretching Class Reference
Stretching can be done in different ways:
#include <Stretching.hpp>
Public Member Functions
void calculateNeighborLookup (level_t maxlevel) const
void getAdjacentPositions (level_t level, index_t index, size_t d, double &posc, double &posl, double &posr) const
double getCoordinate (level_t level, index_t index, size_t d) const
std::vector< double > * getDiscreteVector (bool bSort) const
std::vector< level_t > getDiscreteVectorLevel () const
const Stretching1D & getStretching1D (size_t d) const
std::string getStretchingMode () const
void printLookupTable () const
std::string serialize (int version=SERIALIZATION_VERSION) const override
Serialize the Stretching into a string.
void serialize (std::ostream &ostream, int version=SERIALIZATION_VERSION) const override
Serialize the Stretching into a stream.
Stretching (const std::vector< BoundingBox1D > &boundaries, const std::vector< Stretching1D > &stretching1Ds)
Constructor for Stretching.
Stretching (size_t dimension)
Constructor for Stretching.
Stretching (size_t dimension, std::vector< double > *coordinates)
Constructor for Stretching.
void unserialize (const std::string &istr, const std::string &mode, int version)
Unserialize from a string.
void unserialize (std::istream &istr, const std::string &mode, int version)
Unserialize from a stream.
~Stretching () override
Destructor.
Public Member Functions inherited from sgpp::base::BoundingBox
BoundingBox (const std::vector< BoundingBox1D > &boundingBox1Ds)
Constructor for BoundingBox.
BoundingBox (size_t dimension)
Constructor for BoundingBox.
const BoundingBox1D & getBoundary (size_t d) const
Returns the left and right boundary for a specific dimension.
size_t getDimension () const
Returns the number of dimensions of this bounding box.
double getIntervalOffset (size_t d) const
Returns the offset in positive x-direction of the interval in one dimension.
double getIntervalWidth (size_t d) const
Calculates the width of the interval in one dimension.
bool hasDirichletBoundaryLeft (size_t d) const
Determines if the interval in the specified dimension has left Dirichlet boundary conditions.
bool hasDirichletBoundaryRight (size_t d) const
Determines if the interval in the specified dimension has right Dirichlet boundary conditions.
bool isContainingPoint (DataVector &point) const
Check whether the BoundingBox contains a given point.
bool isContainingPoint (size_t d, double point) const
Check whether the BoundingBox contains a given point in a specific dimension.
bool isUnitCube () const
Determine if this bounding box describes the unit cube \([0, 1]^d\).
void setBoundary (size_t d, const BoundingBox1D &boundingBox1D)
Sets left and right boundary for a specific dimension.
std::string toString () const
Converts the BoundingBox to a string.
void toString (std::string &text) const
Converts the BoundingBox to a string.
void transformPointsToBoundingBox (DataMatrix &points) const
Transform points in the unit cube \([0, 1]^d\) to points in the BoundingBox.
void transformPointsToUnitCube (DataMatrix &points) const
Transform points in the BoundingBox to points in the unit cube \([0, 1]^d\).
void transformPointToBoundingBox (DataVector &point) const
Transform a point in the unit cube \([0, 1]^d\) to a point in the BoundingBox.
double transformPointToBoundingBox (size_t d, double point) const
Transform a point in the unit interval \([0, 1]\) to a point in the BoundingBox in 1D.
void transformPointToUnitCube (DataVector &point) const
Transform a point in the BoundingBox to a point in the unit cube \([0, 1]^d\).
double transformPointToUnitCube (size_t d, double point) const
Transform a point in the BoundingBox to a point in the unit interval \([0, 1]\) in 1D.
virtual ~BoundingBox ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::BoundingBox
std::vector< BoundingBox1D > boundingBox1Ds
Array that contains all left boundaries for all dimensions.
size_t dimension
the number of dimensions used with the grid
Detailed Description
Stretching can be done in different ways:
No Stretching operation is done
Clenshaw-Curtis Stretching
Stretching is done via log/exp calculation
Sinh Stretching
Fitob Stretching
Discrete Stretching (No function used, grid points are directly taken)
Constructor & Destructor Documentation
Stretching() [1/3]
sgpp::base::Stretching::Stretching (size_t dimension) explicit
Constructor for Stretching.
initializes the Stretching with using no stretching
Parameters
dimension number of the dimensions used with the grid
Stretching() [2/3]
sgpp::base::Stretching::Stretching (const std::vector< BoundingBox1D > & boundaries, const std::vector< Stretching1D > & stretching1Ds)
Constructor for Stretching.
initializes the Stretching using the boundaries with the input type array given for each dimension
Parameters
boundaries BoundingBox1D struct to get the boundary values for Stretching
stretching1Ds array to define the stretching type
Stretching() [3/3]
sgpp::base::Stretching::Stretching (size_t dimension, std::vector< double > * coordinates)
Constructor for Stretching.
initializes the Stretching using the coordinates given. (For Janos' request)
Parameters
dimension number of the dimensions used with the grid
coordinates vector<double> array to get the boundaries, as well as the coordinates of the specific level the vector defines for each dimension.
References sgpp::base::BoundingBox::boundingBox1Ds, and sgpp::base::BoundingBox::dimension.
~Stretching()
sgpp::base::Stretching::~Stretching () override
Destructor.
Member Function Documentation
calculateNeighborLookup()
void sgpp::base::Stretching::calculateNeighborLookup (level_t maxlevel) const
getAdjacentPositions()
void sgpp::base::Stretching::getAdjacentPositions (level_t level, index_t index, size_t d, double & posc, double & posl, double & posr) const
References getCoordinate(), level, and LOOKUPMAX.
Referenced by sgpp::pde::DowndPhidPhiBBIterativeLinearStretched::operator()(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), and sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB().
getCoordinate()
double sgpp::base::Stretching::getCoordinate (level_t level, index_t index, size_t d) const inline
References sgpp::base::BoundingBox::boundingBox1Ds, and level.
Referenced by getAdjacentPositions(), sgpp::base::HashGridStorage::getCoordinate(), and sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB().
getDiscreteVector()
std::vector< double > * sgpp::base::Stretching::getDiscreteVector (bool bSort) const
References sgpp::base::BoundingBox::boundingBox1Ds, sgpp::base::BoundingBox::dimension, and sgpp::base::Stretching1D::lookup.
Referenced by serialize().
getDiscreteVectorLevel()
std::vector< level_t > sgpp::base::Stretching::getDiscreteVectorLevel () const
getStretching1D()
const Stretching1D & sgpp::base::Stretching::getStretching1D (size_t d) const inline
getStretchingMode()
std::string sgpp::base::Stretching::getStretchingMode () const
Referenced by sgpp::base::HashGridStorage::serialize().
printLookupTable()
void sgpp::base::Stretching::printLookupTable () const
References sgpp::base::BoundingBox::dimension, and LOOKUPSIZE.
serialize() [1/2]
std::string sgpp::base::Stretching::serialize (int version = SERIALIZATION_VERSION) const override virtual
Serialize the Stretching into a string.
Parameters
version the serialization version of the file
Returns
string that contains all Stretching information
Reimplemented from sgpp::base::BoundingBox.
References serialize().
Referenced by serialize(), sgpp::base::HashGridStorage::serialize(), python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
serialize() [2/2]
void sgpp::base::Stretching::serialize (std::ostream & ostream, int version = SERIALIZATION_VERSION) const override virtual
Serialize the Stretching into a stream.
Parameters
ostream reference to a stream into that all Stretching information is written
version the serialization version of the file
Reimplemented from sgpp::base::BoundingBox.
References sgpp::base::BoundingBox::dimension, getDiscreteVector(), sgpp::base::BoundingBox::serialize(), sgpp::base::Stretching1D::type, sgpp::base::Stretching1D::x_0, and sgpp::base::Stretching1D::xsi.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
unserialize() [1/2]
void sgpp::base::Stretching::unserialize (const std::string & istr, const std::string & mode, int version)
Unserialize from a string.
Parameters
istr string which contains a serialized Stretching
mode stretching mode ("analytic" or "discrete")
version the serialization version of the file
References unserialize().
Referenced by unserialize().
unserialize() [2/2]
void sgpp::base::Stretching::unserialize (std::istream & istr, const std::string & mode, int version)
Unserialize from a stream.
Parameters
istr stream which contains a serialized Stretching
mode stretching mode ("analytic" or "discrete")
version the serialization version of the file
References sgpp::base::BoundingBox::boundingBox1Ds, sgpp::base::BoundingBox::dimension, sgpp::base::Stretching1D::type, sgpp::base::BoundingBox::unserialize(), sgpp::base::Stretching1D::x_0, and sgpp::base::Stretching1D::xsi.
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/common/Stretching.hpp
base/src/sgpp/base/grid/common/Stretching.cpp