SG++-Doxygen-Documentation: sgpp::datadriven::LearnerSGDE Class Reference
sgpp::datadriven::LearnerSGDE Class Reference
#include <LearnerSGDE.hpp>
Public Member Functions
void cov (base::DataMatrix &cov, base::DataMatrix *bounds=nullptr) override
WARNING: Not yet implemented.
virtual double getAccuracy (base::DataMatrix &testDataset, const base::DataVector &referenceLabels, const double threshold)
Computes the classification accuracy.
virtual double getAccuracy (const base::DataVector &referenceLabels, const double threshold, const base::DataVector &predictedLabels)
Computes the classification accuracy.
size_t getDim () override
get number of dimensions
virtual double getError (base::DataMatrix &data, const base::DataVector &labels, const double threshold, std::string errorType)
Error evaluation required for convergence-based refinement.
virtual base::Grid * getGrid ()
returns the grid
size_t getNsamples () override
get number of samples
std::shared_ptr< base::DataMatrix > getSamples () override
returns the complete sample set
std::shared_ptr< base::DataVector > getSamples (size_t dim) override
returns the samples in the given dimension
std::shared_ptr< base::Grid > getSharedGrid ()
std::shared_ptr< base::DataVector > getSharedSurpluses ()
virtual base::DataVector * getSurpluses ()
returns the surpluses
void initialize (base::DataMatrix &samples) override
Create grid and perform cross-validation if enabled.
LearnerSGDE (const LearnerSGDE &learnerSGDE)
LearnerSGDE (LearnerSGDEConfiguration &learnerSGDEConfig)
LearnerSGDE (sgpp::base::RegularGridConfiguration &gridConfig, sgpp::base::AdaptivityConfiguration &adaptivityConfig, sgpp::solver::SLESolverConfiguration &solverConfig, sgpp::datadriven::RegularizationConfiguration &regularizationConfig, CrossvalidationConfiguration &crossValidationConfig)
Constructor.
double mean () override
This method computes the mean of the density function.
void pdf (base::DataMatrix &points, base::DataVector &res) override
Evaluation of the sparse grid density at a set of points.
double pdf (base::DataVector &x) override
This methods evaluates the sparse grid density at a single point.
virtual void predict (base::DataMatrix &testDataset, base::DataVector &predictedLabels)
Predicts class labels based on the trained model.
virtual void storeResults (base::DataMatrix &testDataset)
Stores classified data, grids and density function evaluations to csv files.
virtual void train ()
Learns the data.
virtual void train (base::Grid &grid, base::DataVector &alpha, base::DataMatrix &trainData, double lambdaReg)
Does the learning step (i.e.
virtual void trainOnline (base::DataVector &labels, base::DataMatrix &testData, base::DataVector &testLabels, base::DataMatrix *validData, base::DataVector *validLabels, base::DataVector &classLabels, size_t maxDataPasses, std::string refType, std::string refMonitor, size_t refPeriod, double accDeclineThreshold, size_t accDeclineBufferSize, size_t minRefInterval, bool usePrior)
Performs the sparse grid density estimation via online learning.
double variance () override
Computes the variance of the density function.
~LearnerSGDE () override
Public Member Functions inherited from sgpp::datadriven::DensityEstimator
virtual void corrcoef (base::DataMatrix &corr, base::DataMatrix *bounds=nullptr)
double crossEntropy (sgpp::base::DataMatrix &samples)
DensityEstimator ()
virtual double std_deviation ()
virtual ~DensityEstimator ()
Public Attributes
base::DataVector avgErrors
double error
Protected Member Functions
base::OperationMatrix * computeRegularizationMatrix (base::Grid &grid)
generates the regularization matrix
double computeResidual (base::Grid &grid, base::DataVector &alpha, base::DataMatrix &test, double lambdaReg)
Compute the residual for a given test data set on a learned grid.
std::shared_ptr< base::Grid > createRegularGrid ()
generates a regular grid
double mean (base::Grid &grid, base::DataVector &alpha)
double optimizeLambdaCV ()
Does cross-validation to obtain a suitable regularization parameter.
void splitset (std::vector< std::shared_ptr< base::DataMatrix > > &strain, std::vector< std::shared_ptr< base::DataMatrix > > &stest)
splits the complete sample set in a set of smaller training and test samples for cross-validation.
double variance (base::Grid &grid, base::DataVector &alpha)
Protected Attributes
sgpp::base::AdaptivityConfiguration adaptivityConfig
std::shared_ptr< base::DataVector > alpha
std::map< int, std::shared_ptr< base::DataVector > > alphas
std::map< int, size_t > appearances
sgpp::datadriven::CrossvalidationConfiguration crossValidationConfig
std::shared_ptr< base::Grid > grid
sgpp::base::RegularGridConfiguration gridConfig
std::map< int, std::shared_ptr< base::Grid > > grids
double lambdaReg
std::map< int, double > priors
sgpp::datadriven::RegularizationConfiguration regularizationConfig
sgpp::solver::SLESolverConfiguration solverConfig
std::shared_ptr< base::DataMatrix > trainData
std::shared_ptr< base::DataVector > trainLabels
bool usePrior
Constructor & Destructor Documentation
LearnerSGDE() [1/3]
sgpp::datadriven::LearnerSGDE::LearnerSGDE (sgpp::base::RegularGridConfiguration & gridConfig, sgpp::base::AdaptivityConfiguration & adaptivityConfig, sgpp::solver::SLESolverConfiguration & solverConfig, sgpp::datadriven::RegularizationConfiguration & regularizationConfig, CrossvalidationConfiguration & crossValidationConfig)
Constructor.
Parameters
gridConfig grid configuration
adaptivityConfig adaptive refinement configuration
solverConfig solver configuration (CG)
regularizationConfig config for regularization operator
crossValidationConfig configuration for the cross validation
LearnerSGDE() [2/3]
sgpp::datadriven::LearnerSGDE::LearnerSGDE (LearnerSGDEConfiguration & learnerSGDEConfig) explicit
LearnerSGDE() [3/3]
sgpp::datadriven::LearnerSGDE::LearnerSGDE (const LearnerSGDE & learnerSGDE)
References adaptivityConfig, alpha, crossValidationConfig, error, grid, gridConfig, lambdaReg, regularizationConfig, solverConfig, trainData, and usePrior.
~LearnerSGDE()
sgpp::datadriven::LearnerSGDE::~LearnerSGDE () override
Member Function Documentation
computeRegularizationMatrix()
base::OperationMatrix * sgpp::datadriven::LearnerSGDE::computeRegularizationMatrix (base::Grid & grid) protected
generates the regularization matrix
Parameters
grid grid
References sgpp::op_factory::createOperationIdentity(), sgpp::op_factory::createOperationLaplace(), grid, sgpp::datadriven::Identity, sgpp::datadriven::Laplace, regularizationConfig, and sgpp::datadriven::RegularizationConfiguration::type_.
Referenced by computeResidual(), train(), and trainOnline().
computeResidual()
double sgpp::datadriven::LearnerSGDE::computeResidual (base::Grid & grid, base::DataVector & alpha, base::DataMatrix & test, double lambdaReg) protected
Compute the residual for a given test data set on a learned grid.
$|(A - lambda C) alpha - 1/n B|$
This is used as quality criterion for the estimated density.
Parameters
grid grid
alpha coefficient vector
test test set
lambdaReg regularization parameters
Returns
References alpha, computeRegularizationMatrix(), sgpp::datadriven::DensitySystemMatrix::generateb(), sgpp::base::DataVector::getSize(), grid, sgpp::base::DataVector::l2Norm(), lambdaReg, and sgpp::datadriven::DensitySystemMatrix::mult().
Referenced by optimizeLambdaCV().
cov()
void sgpp::datadriven::LearnerSGDE::cov (base::DataMatrix & cov, base::DataMatrix * bounds = nullptr) override virtual
WARNING: Not yet implemented.
Implements sgpp::datadriven::DensityEstimator.
References alpha, cov(), sgpp::op_factory::createOperationCovariance(), and grid.
Referenced by python.uq.dists.Dist.Dist::corrcoeff(), and cov().
createRegularGrid()
std::shared_ptr< base::Grid > sgpp::datadriven::LearnerSGDE::createRegularGrid () protected
generates a regular grid
Returns
grid
References sgpp::base::Grid::createLinearBoundaryGrid(), sgpp::base::Grid::createLinearGrid(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, gridConfig, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::GeneralGridConfiguration::type_, and sgpp::base::Grid::unserialize().
Referenced by initialize(), and optimizeLambdaCV().
getAccuracy() [1/2]
double sgpp::datadriven::LearnerSGDE::getAccuracy (base::DataMatrix & testDataset, const base::DataVector & referenceLabels, const double threshold) virtual
Computes the classification accuracy.
Parameters
testDataset The data for which class labels should be predicted
referenceLabels The corresponding actual class labels
threshold The decision threshold (e.g. for class labels -1, 1 -> threshold = 0)
Returns
The resulting accuracy
References getAccuracy(), sgpp::base::DataMatrix::getNrows(), and predict().
Referenced by getAccuracy(), getError(), and trainOnline().
getAccuracy() [2/2]
double sgpp::datadriven::LearnerSGDE::getAccuracy (const base::DataVector & referenceLabels, const double threshold, const base::DataVector & predictedLabels) virtual
Computes the classification accuracy.
Parameters
referenceLabels The actual class labels
threshold The decision threshold (e.g. for class labels -1, 1 -> threshold = 0)
predictedLabels The predicted class labels
Returns
The resulting accuracy
References sgpp::base::DataVector::get(), and sgpp::base::DataVector::getSize().
getDim()
size_t sgpp::datadriven::LearnerSGDE::getDim () override virtual
get number of dimensions
Implements sgpp::datadriven::DensityEstimator.
References sgpp::base::GeneralGridConfiguration::dim_, and gridConfig.
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.uq.dists.Dist.Dist::cov(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), and python.uq.uq_setting.UQSetting.UQSetting::getDim().
getError()
double sgpp::datadriven::LearnerSGDE::getError (base::DataMatrix & data, const base::DataVector & labels, const double threshold, std::string errorType) virtual
Error evaluation required for convergence-based refinement.
Parameters
data The data points to measure the error on
labels The corresponding class labels
threshold The decision threshold (e.g. for class labels -1, 1 -> threshold = 0)
errorType The error type (only "Acc" possible, i.e. classification error based on accuracy)
Returns
The error evaluation
References getAccuracy().
Referenced by trainOnline().
getGrid()
base::Grid * sgpp::datadriven::LearnerSGDE::getGrid () virtual
returns the grid
References grid.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
getNsamples()
size_t sgpp::datadriven::LearnerSGDE::getNsamples () override virtual
get number of samples
Implements sgpp::datadriven::DensityEstimator.
References trainData.
Referenced by getSamples(), and optimizeLambdaCV().
getSamples() [1/2]
std::shared_ptr< base::DataMatrix > sgpp::datadriven::LearnerSGDE::getSamples () override virtual
returns the complete sample set
Implements sgpp::datadriven::DensityEstimator.
References trainData.
getSamples() [2/2]
std::shared_ptr< base::DataVector > sgpp::datadriven::LearnerSGDE::getSamples (size_t dim) override virtual
returns the samples in the given dimension
Parameters
dim
Implements sgpp::datadriven::DensityEstimator.
References getNsamples(), and trainData.
getSharedGrid()
std::shared_ptr< base::Grid > sgpp::datadriven::LearnerSGDE::getSharedGrid ()
References grid.
Referenced by sgpp::datadriven::RosenblattTransformation::initialize().
getSharedSurpluses()
std::shared_ptr< base::DataVector > sgpp::datadriven::LearnerSGDE::getSharedSurpluses ()
References alpha.
Referenced by sgpp::datadriven::RosenblattTransformation::initialize().
getSurpluses()
base::DataVector * sgpp::datadriven::LearnerSGDE::getSurpluses () virtual
returns the surpluses
References alpha, and sgpp::base::DataVector::get().
initialize()
void sgpp::datadriven::LearnerSGDE::initialize (base::DataMatrix & samples) override virtual
Create grid and perform cross-validation if enabled.
Parameters
samples DataMatrix (nrows = number of samples, ncols = dimensionality)
Implements sgpp::datadriven::DensityEstimator.
References alpha, createRegularGrid(), crossValidationConfig, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::CrossvalidationConfiguration::enable_, grid, gridConfig, sgpp::datadriven::CrossvalidationConfiguration::lambda_, lambdaReg, optimizeLambdaCV(), and trainData.
Referenced by sgpp::datadriven::RosenblattTransformation::initialize().
mean() [1/2]
double sgpp::datadriven::LearnerSGDE::mean () override virtual
This method computes the mean of the density function.
Implements sgpp::datadriven::DensityEstimator.
References alpha, grid, and mean().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), mean(), python.uq.dists.LibAGFDist.LibAGFDist::var(), python.uq.dists.SGDEdist.SGDEdist::var(), and variance().
mean() [2/2]
double sgpp::datadriven::LearnerSGDE::mean (base::Grid & grid, base::DataVector & alpha) protected
References alpha, sgpp::op_factory::createOperationFirstMoment(), sgpp::base::OperationFirstMoment::doQuadrature(), and grid.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), python.uq.dists.LibAGFDist.LibAGFDist::var(), and python.uq.dists.SGDEdist.SGDEdist::var().
optimizeLambdaCV()
double sgpp::datadriven::LearnerSGDE::optimizeLambdaCV () protected
Does cross-validation to obtain a suitable regularization parameter.
References alpha, computeResidual(), createRegularGrid(), crossValidationConfig, getNsamples(), grid, sgpp::datadriven::CrossvalidationConfiguration::kfold_, sgpp::datadriven::CrossvalidationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationConfiguration::lambdaSteps_, sgpp::datadriven::CrossvalidationConfiguration::logScale_, sgpp::datadriven::CrossvalidationConfiguration::silent_, splitset(), and train().
Referenced by initialize().
pdf() [1/2]
void sgpp::datadriven::LearnerSGDE::pdf (base::DataMatrix & points, base::DataVector & res) override virtual
Evaluation of the sparse grid density at a set of points.
Parameters
points DataMatrix (nrows = number of samples, ncols = dimensionality)
res DataVector (size = number of samples) where the results are stored
Implements sgpp::datadriven::DensityEstimator.
References alpha, sgpp::op_factory::createOperationMultipleEval(), sgpp::base::OperationMultipleEval::eval(), and grid.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
pdf() [2/2]
double sgpp::datadriven::LearnerSGDE::pdf (base::DataVector & x) override virtual
This methods evaluates the sparse grid density at a single point.
Parameters
x DataVector length equal to dimensionality
Implements sgpp::datadriven::DensityEstimator.
References alpha, sgpp::op_factory::createOperationEval(), and sgpp::base::OperationEval::eval().
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
predict()
void sgpp::datadriven::LearnerSGDE::predict (base::DataMatrix & testDataset, base::DataVector & predictedLabels) virtual
Predicts class labels based on the trained model.
Parameters
testDataset The data for which class labels should be predicted
predictedLabels The predicted class labels
References alphas, sgpp::op_factory::createOperationEval(), g, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grids, priors, sgpp::base::DataVector::set(), and usePrior.
Referenced by getAccuracy(), and storeResults().
splitset()
void sgpp::datadriven::LearnerSGDE::splitset (std::vector< std::shared_ptr< base::DataMatrix > > & strain, std::vector< std::shared_ptr< base::DataMatrix > > & stest) protected
splits the complete sample set in a set of smaller training and test samples for cross-validation.
Parameters
strain vector containing the training samples for cv
stest vector containing the test samples for cv
References crossValidationConfig, sgpp::datadriven::CrossvalidationConfiguration::kfold_, sgpp::datadriven::CrossvalidationConfiguration::seed_, sgpp::datadriven::CrossvalidationConfiguration::shuffle_, sgpp::datadriven::CrossvalidationConfiguration::silent_, and trainData.
Referenced by optimizeLambdaCV().
storeResults()
void sgpp::datadriven::LearnerSGDE::storeResults (base::DataMatrix & testDataset) virtual
Stores classified data, grids and density function evaluations to csv files.
Parameters
testDataset The data for which class labels should be predicted
References alphas, sgpp::base::DataMatrix::appendRow(), sgpp::base::HashGridStorage::begin(), sgpp::op_factory::createOperationEval(), sgpp::base::HashGridStorage::end(), g, sgpp::base::DataVector::get(), sgpp::base::HashGridStorage::getCoordinates(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), grid, grids, predict(), and sgpp::base::DataVector::set().
train() [1/2]
void sgpp::datadriven::LearnerSGDE::train () virtual
Learns the data.
References alpha, grid, lambdaReg, train(), and trainData.
Referenced by optimizeLambdaCV(), and train().
train() [2/2]
void sgpp::datadriven::LearnerSGDE::train (base::Grid & grid, base::DataVector & alpha, base::DataMatrix & trainData, double lambdaReg) virtual
Does the learning step (i.e.
computes pdf) on a given grid, training set and regularization parameter lambda
Parameters
grid grid
alpha coefficient vector
trainData sample set
lambdaReg regularization parameter
References adaptivityConfig, alpha, computeRegularizationMatrix(), sgpp::op_factory::createOperationEval(), crossValidationConfig, sgpp::solver::SLESolverConfiguration::eps_, sgpp::datadriven::DensitySystemMatrix::generateb(), sgpp::base::DataVector::get(), sgpp::solver::SGSolver::getResiduum(), grid, lambdaReg, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::GridGenerator::refine(), sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::DataVector::setAll(), sgpp::datadriven::CrossvalidationConfiguration::silent_, sgpp::solver::ConjugateGradients::solve(), solverConfig, sgpp::solver::SLESolverConfiguration::threshold_, and trainData.
Referenced by sgpp::datadriven::RosenblattTransformation::initialize().
trainOnline()
void sgpp::datadriven::LearnerSGDE::trainOnline (base::DataVector & labels, base::DataMatrix & testData, base::DataVector & testLabels, base::DataMatrix * validData, base::DataVector * validLabels, base::DataVector & classLabels, size_t maxDataPasses, std::string refType, std::string refMonitor, size_t refPeriod, double accDeclineThreshold, size_t accDeclineBufferSize, size_t minRefInterval, bool usePrior) virtual
Performs the sparse grid density estimation via online learning.
Parameters
labels The training labels
testData The test data
testLabels The corresponding test labels
validData The validation data
validLabels The corresponding validation labels
classLabels The ocurring class labels (e.g. -1,1)
maxDataPasses The number of passes over the whole training data
refType The refinement indicator (surplus, zero-crossings or data-based)
refMonitor The refinement strategy (periodic or convergence-based)
refPeriod The refinement interval (if periodic refinement is chosen)
accDeclineThreshold The convergence threshold (if convergence-based refinement is chosen)
accDeclineBufferSize The number of accuracy measurements which are used to check convergence (if convergence-based refinement is chosen)
minRefInterval The minimum number of data points (or data batches) which have to be processed before next refinement can be scheduled (if convergence-based refinement is chosen)
usePrior Specifies whether prior probabilities should be used to predict class labels
References adaptivityConfig, alpha, alphas, appearances, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), avgErrors, computeRegularizationMatrix(), sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationEval(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::solver::SLESolverConfiguration::eps_, error, g, sgpp::datadriven::DensitySystemMatrix::generateb(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), getAccuracy(), getError(), sgpp::base::DataVector::getSize(), grid, gridConfig, grids, lambdaReg, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::ModLinear, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::MultiGridRefinementFunctor::preComputeEvaluations(), priors, sgpp::datadriven::RefinementMonitor::pushToBuffer(), sgpp::datadriven::RefinementMonitor::refinementsNecessary(), sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::datadriven::MultiGridRefinementFunctor::setGridIndex(), sgpp::solver::ConjugateGradients::solve(), solverConfig, sgpp::solver::SLESolverConfiguration::threshold_, trainData, trainLabels, sgpp::base::GeneralGridConfiguration::type_, and usePrior.
variance() [1/2]
double sgpp::datadriven::LearnerSGDE::variance () override virtual
Computes the variance of the density function.
Implements sgpp::datadriven::DensityEstimator.
References alpha, grid, and variance().
Referenced by variance().
variance() [2/2]
double sgpp::datadriven::LearnerSGDE::variance (base::Grid & grid, base::DataVector & alpha) protected
References alpha, sgpp::op_factory::createOperationSecondMoment(), sgpp::base::OperationSecondMoment::doQuadrature(), grid, and mean().
Member Data Documentation
adaptivityConfig
sgpp::base::AdaptivityConfiguration sgpp::datadriven::LearnerSGDE::adaptivityConfig protected
Referenced by LearnerSGDE(), train(), and trainOnline().
alpha
std::shared_ptr<base::DataVector> sgpp::datadriven::LearnerSGDE::alpha protected
Referenced by computeResidual(), cov(), python.learner.Learner.Learner::doLearningIteration(), getSharedSurpluses(), getSurpluses(), initialize(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Interpolant.Interpolant::learnDataWithTest(), LearnerSGDE(), mean(), mean(), optimizeLambdaCV(), pdf(), pdf(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::toJson(), train(), train(), trainOnline(), variance(), and variance().
alphas
std::map<int, std::shared_ptr<base::DataVector> > sgpp::datadriven::LearnerSGDE::alphas protected
Referenced by predict(), storeResults(), and trainOnline().
appearances
std::map<int, size_t> sgpp::datadriven::LearnerSGDE::appearances protected
Referenced by trainOnline().
avgErrors
base::DataVector sgpp::datadriven::LearnerSGDE::avgErrors
Referenced by trainOnline().
crossValidationConfig
sgpp::datadriven::CrossvalidationConfiguration sgpp::datadriven::LearnerSGDE::crossValidationConfig protected
Referenced by initialize(), LearnerSGDE(), optimizeLambdaCV(), splitset(), and train().
error
double sgpp::datadriven::LearnerSGDE::error
Referenced by python.uq.dists.J.J::discretize(), python.learner.Regressor.Regressor::evalError(), python.uq.learner.Regressor.Regressor::evalError(), python.learner.Regressor.Regressor::getL2NormError(), python.uq.learner.Regressor.Regressor::getL2NormError(), python.learner.Regressor.Regressor::getMaxError(), python.uq.learner.Regressor.Regressor::getMaxError(), python.learner.Regressor.Regressor::getMinError(), python.uq.learner.Regressor.Regressor::getMinError(), LearnerSGDE(), and trainOnline().
grid
std::shared_ptr<base::Grid> sgpp::datadriven::LearnerSGDE::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), computeRegularizationMatrix(), computeResidual(), cov(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), getSharedGrid(), initialize(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), LearnerSGDE(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), mean(), mean(), python.uq.dists.SGDEdist.SGDEdist::mean(), optimizeLambdaCV(), pdf(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), storeResults(), python.uq.dists.SGDEdist.SGDEdist::toJson(), train(), train(), trainOnline(), python.uq.dists.SGDEdist.SGDEdist::var(), variance(), and variance().
gridConfig
sgpp::base::RegularGridConfiguration sgpp::datadriven::LearnerSGDE::gridConfig protected
Referenced by createRegularGrid(), getDim(), initialize(), LearnerSGDE(), and trainOnline().
grids
std::map<int, std::shared_ptr<base::Grid> > sgpp::datadriven::LearnerSGDE::grids protected
Referenced by predict(), storeResults(), and trainOnline().
lambdaReg
double sgpp::datadriven::LearnerSGDE::lambdaReg protected
Referenced by computeResidual(), initialize(), LearnerSGDE(), train(), train(), and trainOnline().
priors
std::map<int, double> sgpp::datadriven::LearnerSGDE::priors protected
Referenced by predict(), and trainOnline().
regularizationConfig
sgpp::datadriven::RegularizationConfiguration sgpp::datadriven::LearnerSGDE::regularizationConfig protected
Referenced by computeRegularizationMatrix(), and LearnerSGDE().
solverConfig
sgpp::solver::SLESolverConfiguration sgpp::datadriven::LearnerSGDE::solverConfig protected
Referenced by LearnerSGDE(), train(), and trainOnline().
trainData
std::shared_ptr<base::DataMatrix> sgpp::datadriven::LearnerSGDE::trainData protected
Referenced by python.uq.dists.KDEDist.KDEDist::__init__(), python.uq.dists.LibAGFDist.LibAGFDist::cdf(), getNsamples(), getSamples(), python.uq.dists.EstimatedDist.EstimatedDist::getSamples(), getSamples(), initialize(), LearnerSGDE(), python.uq.dists.KDEDist.KDEDist::marginalize(), python.uq.dists.SGDEdist.SGDEdist::marginalize(), python.uq.dists.KDEDist.KDEDist::marginalizeToDimX(), python.uq.dists.SGDEdist.SGDEdist::marginalizeToDimX(), python.uq.dists.LibAGFDist.LibAGFDist::pdf(), python.uq.dists.LibAGFDist.LibAGFDist::ppf(), splitset(), python.uq.dists.SGDEdist.SGDEdist::toJson(), train(), train(), and trainOnline().
trainLabels
std::shared_ptr<base::DataVector> sgpp::datadriven::LearnerSGDE::trainLabels protected
Referenced by trainOnline().
usePrior
bool sgpp::datadriven::LearnerSGDE::usePrior protected
Referenced by LearnerSGDE(), predict(), and trainOnline().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/LearnerSGDE.hpp
datadriven/src/sgpp/datadriven/application/LearnerSGDE.cpp