SG++-Doxygen-Documentation: sgpp::datadriven::RegressionLearner Class Reference
sgpp::datadriven::RegressionLearner Class Reference
The RegressionLearner class Solves a regression problem with continuous target vector.
#include <RegressionLearner.hpp>
Classes
class Solver
Public Member Functions
sgpp::base::Grid & getGrid ()
getGrid
std::shared_ptr< sgpp::base::Grid > getGridPtr ()
getGridPtr
size_t getGridSize () const
getGridSize
double getMSE (sgpp::base::DataMatrix &data, const sgpp::base::DataVector &y)
getMSE
sgpp::base::DataVector getWeights () const
getWeights
sgpp::base::DataVector predict (sgpp::base::DataMatrix &data)
predict
RegressionLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, datadriven::RegularizationConfiguration regularizationConfig)
RegressionLearner.
RegressionLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, datadriven::RegularizationConfiguration regularizationConfig, std::set< std::set< size_t > > terms)
RegressionLearner.
void setWeights (sgpp::base::DataVector weights)
setWeights
void train (sgpp::base::DataMatrix &trainDataset, sgpp::base::DataVector &classes)
train fits a sparse grid regression model.
Detailed Description
The RegressionLearner class Solves a regression problem with continuous target vector.
Constructor & Destructor Documentation
RegressionLearner() [1/2]
sgpp::datadriven::RegressionLearner::RegressionLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, datadriven::RegularizationConfiguration regularizationConfig, std::set< std::set< size_t > > terms)
RegressionLearner.
Parameters
gridConfig
adaptivityConfig
solverConfig is the solver used during each adaptivity step
finalSolverConfig is the solver used to build the final model
regularizationConfig
terms is a vector that contains all desired interaction terms. For example, if we want to include grid points that model an interaction between the first and the second predictor, we would include the vector [1,2] in terms.
RegressionLearner() [2/2]
sgpp::datadriven::RegressionLearner::RegressionLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, datadriven::RegularizationConfiguration regularizationConfig)
RegressionLearner.
Parameters
gridConfig
adaptivityConfig
solverConfig is the solver used during each adaptivity step
finalSolverConfig is the solver used to build the final model
regularizationConfig
Member Function Documentation
getGrid()
base::Grid & sgpp::datadriven::RegressionLearner::getGrid ()
getGrid
Returns
the grid
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
getGridPtr()
std::shared_ptr< sgpp::base::Grid > sgpp::datadriven::RegressionLearner::getGridPtr ()
getGridPtr
Returns
shared pointer to the grid
getGridSize()
size_t sgpp::datadriven::RegressionLearner::getGridSize () const
getGridSize
Returns
the size of the grid
Referenced by python.learner.TrainingStopPolicy.TrainingStopPolicy::hasGridSizeChanged(), and python.learner.TrainingStopPolicy.TrainingStopPolicy::isTrainingComplete().
getMSE()
double sgpp::datadriven::RegressionLearner::getMSE (sgpp::base::DataMatrix & data, const sgpp::base::DataVector & y)
getMSE
Parameters
data is the design matrix
y is the target
Returns
the mean-squared-error of the prediction of the model for the matrix data
References getMSE(), and predict().
Referenced by getMSE().
getWeights()
base::DataVector sgpp::datadriven::RegressionLearner::getWeights () const
getWeights
Returns
the weights
predict()
base::DataVector sgpp::datadriven::RegressionLearner::predict (sgpp::base::DataMatrix & data)
predict
Parameters
data are observations
Returns
the predicted target for matrix data
References sgpp::op_factory::createOperationMultipleEval().
Referenced by getMSE().
setWeights()
void sgpp::datadriven::RegressionLearner::setWeights (sgpp::base::DataVector weights)
setWeights
Parameters
weights are the new weights.
train()
void sgpp::datadriven::RegressionLearner::train (sgpp::base::DataMatrix & trainDataset, sgpp::base::DataVector & classes)
train fits a sparse grid regression model.
Parameters
trainDataset is the design matrix
classes is the (continuous) target
References sgpp::datadriven::RegressionLearner::Solver::cg, sgpp::op_factory::createOperationMultipleEval(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), and sgpp::base::AdaptivityConfiguration::numRefinements_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/RegressionLearner.hpp
datadriven/src/sgpp/datadriven/application/RegressionLearner.cpp