SG++-Doxygen-Documentation: sgpp::datadriven::Kernel Class Reference
sgpp::datadriven::Kernel Class Reference abstract
#include <KernelDensityEstimator.hpp>
Public Member Functions
virtual double cdf (double x)=0
virtual double derivative (double x)=0
virtual double eval (double x)=0
virtual KernelType getType ()=0
virtual double norm ()=0
virtual double variance ()=0
virtual ~Kernel ()
Constructor & Destructor Documentation
~Kernel()
sgpp::datadriven::Kernel::~Kernel () virtual
Member Function Documentation
cdf()
virtual double sgpp::datadriven::Kernel::cdf (double x) pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
Referenced by sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation1D().
derivative()
virtual double sgpp::datadriven::Kernel::derivative (double x) pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
eval()
virtual double sgpp::datadriven::Kernel::eval (double x) pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
Referenced by sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getType()
virtual KernelType sgpp::datadriven::Kernel::getType () pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
Referenced by sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::eval().
norm()
virtual double sgpp::datadriven::Kernel::norm () pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
Referenced by python.uq.dists.MultivariateNormal.MultivariateNormal::pdf().
variance()
virtual double sgpp::datadriven::Kernel::variance () pure virtual
Implemented in sgpp::datadriven::GaussianKernel, and sgpp::datadriven::EpanechnikovKernel.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp