SG++-Doxygen-Documentation: sgpp::datadriven::SparseGridDensityEstimatorConfiguration Class Reference
sgpp::datadriven::SparseGridDensityEstimatorConfiguration Class Reference
#include <SparseGridDensityEstimator.hpp>
Public Member Functions
SparseGridDensityEstimatorConfiguration * clone () override
void initConfig ()
SparseGridDensityEstimatorConfiguration ()
SparseGridDensityEstimatorConfiguration (const std::string &fileName)
sgpp::datadriven::RegularizationType stringToRegularizationType (std::string &regularizationType)
sgpp::solver::SLESolverType stringToSolverType (std::string &solverType)
Public Member Functions inherited from json::JSON
void clear ()
void deserialize (std::string content)
void deserializeFromString (const std::string &content)
JSON ()
JSON (const JSON &original)
JSON (const std::string &fileName)
DictNode & operator= (const DictNode &right)
JSON & operator= (const JSON &original)
Node & operator= (const Node &right) override
void serialize (const std::string &outFileName)
void serialize (std::ostream &outFile, size_t indentWidth) override
Public Member Functions inherited from json::DictNode
void addAttribute (const std::string &name, std::unique_ptr< Node > node) override
Node & addDictAttr (const std::string &name) override
Node & addIDAttr (const std::string &name, const bool &value) override
Node & addIDAttr (const std::string &name, const char *value) override
Node & addIDAttr (const std::string &name, const double &value) override
Node & addIDAttr (const std::string &name, const int64_t &value) override
Node & addIDAttr (const std::string &name, const std::string &value) override
Node & addIDAttr (const std::string &name, const uint64_t &value) override
Node & addListAttr (const std::string &name) override
Node & addTextAttr (const std::string &name, const std::string &value) override
bool contains (const std::string &key) override
DictNode ()
DictNode (const DictNode &original)
std::unique_ptr< Node > erase (Node &node) override
std::vector< std::string > & keys () override
DictNode & operator= (const DictNode &right)
Node & operator[] (const std::string &key) override
void parse (std::vector< Token > &stream) override
void parseAttributes (std::vector< Token > &stream)
std::unique_ptr< Node > removeAttribute (const std::string name) override
Node & replaceDictAttr (const std::string &name) override
Node & replaceIDAttr (const std::string &name, const bool &value) override
Node & replaceIDAttr (const std::string &name, const char *value) override
Node & replaceIDAttr (const std::string &name, const double &value) override
Node & replaceIDAttr (const std::string &name, const int64_t &value) override
Node & replaceIDAttr (const std::string &name, const std::string &value) override
Node & replaceIDAttr (const std::string &name, const uint64_t &value) override
Node & replaceListAttr (const std::string &name) override
Node & replaceTextAttr (const std::string &name, const std::string &value) override
size_t size () override
Public Member Functions inherited from json::Node
virtual Node & addDictValue ()
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListValue ()
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual std::unique_ptr< Node > erase ()
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const size_t index)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual ~Node ()=default
Friends
class SparseGridDensityEstimator
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Protected Attributes inherited from json::DictNode
std::map< std::string, std::unique_ptr< Node > > attributes
std::vector< std::string > keyOrder
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
SparseGridDensityEstimatorConfiguration() [1/2]
sgpp::datadriven::SparseGridDensityEstimatorConfiguration::SparseGridDensityEstimatorConfiguration ()
References initConfig().
Referenced by clone().
SparseGridDensityEstimatorConfiguration() [2/2]
sgpp::datadriven::SparseGridDensityEstimatorConfiguration::SparseGridDensityEstimatorConfiguration (const std::string & fileName) explicit
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, json::DictNode::contains(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::enable_, sgpp::solver::SLESolverConfiguration::eps_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::datadriven::FullGrid, sgpp::datadriven::HybridFullIntersections, initConfig(), sgpp::datadriven::InterpolateBoundaries1d, sgpp::datadriven::InterpolateExp, sgpp::datadriven::Intersections, sgpp::datadriven::IntersectionsJoin, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::kfold_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambda_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaSteps_, sgpp::base::GeneralGridConfiguration::level_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::logScale_, sgpp::datadriven::SGDEConfiguration::makePositive_, sgpp::datadriven::SGDEConfiguration::makePositive_candidateSearchAlgorithm_, sgpp::datadriven::SGDEConfiguration::makePositive_generateConsistentGrid_, sgpp::datadriven::SGDEConfiguration::makePositive_interpolationAlgorithm_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::seed_, sgpp::datadriven::SetToZero, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::shuffle_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::silent_, sgpp::base::Grid::stringToGridType(), stringToRegularizationType(), stringToSolverType(), sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::GeneralGridConfiguration::type_, sgpp::datadriven::RegularizationConfiguration::type_, sgpp::solver::SLESolverConfiguration::type_, sgpp::datadriven::SGDEConfiguration::unitIntegrand_, sgpp::solver::SLESolverConfiguration::verbose_, and json::json_exception::what().
Member Function Documentation
clone()
SparseGridDensityEstimatorConfiguration * sgpp::datadriven::SparseGridDensityEstimatorConfiguration::clone () override virtual
Reimplemented from json::JSON.
References clone(), and SparseGridDensityEstimatorConfiguration().
Referenced by clone().
initConfig()
void sgpp::datadriven::SparseGridDensityEstimatorConfiguration::initConfig ()
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::solver::CG, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::enable_, sgpp::solver::SLESolverConfiguration::eps_, sgpp::datadriven::Intersections, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::kfold_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambda_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaSteps_, sgpp::datadriven::Laplace, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::logScale_, sgpp::datadriven::SGDEConfiguration::makePositive_, sgpp::datadriven::SGDEConfiguration::makePositive_candidateSearchAlgorithm_, sgpp::datadriven::SGDEConfiguration::makePositive_generateConsistentGrid_, sgpp::datadriven::SGDEConfiguration::makePositive_interpolationAlgorithm_, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::seed_, sgpp::datadriven::SetToZero, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::shuffle_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::silent_, sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::GeneralGridConfiguration::type_, sgpp::datadriven::RegularizationConfiguration::type_, sgpp::solver::SLESolverConfiguration::type_, sgpp::datadriven::SGDEConfiguration::unitIntegrand_, and sgpp::solver::SLESolverConfiguration::verbose_.
Referenced by SparseGridDensityEstimatorConfiguration(), and SparseGridDensityEstimatorConfiguration().
stringToRegularizationType()
sgpp::datadriven::RegularizationType sgpp::datadriven::SparseGridDensityEstimatorConfiguration::stringToRegularizationType (std::string & regularizationType)
References sgpp::datadriven::Identity, and sgpp::datadriven::Laplace.
Referenced by SparseGridDensityEstimatorConfiguration().
stringToSolverType()
sgpp::solver::SLESolverType sgpp::datadriven::SparseGridDensityEstimatorConfiguration::stringToSolverType (std::string & solverType)
References sgpp::solver::BiCGSTAB, and sgpp::solver::CG.
Referenced by SparseGridDensityEstimatorConfiguration().
Friends And Related Symbol Documentation
SparseGridDensityEstimator
friend class SparseGridDensityEstimator friend
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/SparseGridDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/SparseGridDensityEstimator.cpp