SG++-Doxygen-Documentation: sgpp::base::OperationWeightedQuadratureNakBspline Class Reference
sgpp::base::OperationWeightedQuadratureNakBspline Class Reference
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
#include <OperationWeightedQuadratureNakBspline.hpp>
Public Member Functions
double doWeightedQuadrature (DataVector &alpha, sgpp::base::DistributionsVector pdfs) override
Quadrature for not a knot B-spline basis functions w.r.t.
OperationWeightedQuadratureNakBspline (GridStorage &storage, size_t degree, size_t quadOrder)
Constructor of OperationQuadratureNakBspline.
~OperationWeightedQuadratureNakBspline () override
Public Member Functions inherited from sgpp::base::OperationWeightedQuadrature
OperationWeightedQuadrature ()
Constructor.
virtual ~OperationWeightedQuadrature ()
Destructor.
Protected Attributes
SNakBsplineBase base
NakBsplineCombigrid Basis object.
std::shared_ptr< base::DataVector > quadCoordinates
quadrature rule coordinates
size_t quadOrder
quadrature rule order
std::shared_ptr< base::DataVector > quadWeights
quadrature rule weights
GridStorage & storage
Detailed Description
Quadrature on sparse grid, not a knot B-spline grid created by transformation of a not a knot B-spline combigrid.
Constructor & Destructor Documentation
OperationWeightedQuadratureNakBspline()
sgpp::base::OperationWeightedQuadratureNakBspline::OperationWeightedQuadratureNakBspline (GridStorage & storage, size_t degree, size_t quadOrder) inline
Constructor of OperationQuadratureNakBspline.
Parameters
storage Pointer to the grid's GridStorage object
degree the B-spline degree
quadOrder quadrature order
References sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), quadCoordinates, quadOrder, and quadWeights.
~OperationWeightedQuadratureNakBspline()
sgpp::base::OperationWeightedQuadratureNakBspline::~OperationWeightedQuadratureNakBspline () inline override
Member Function Documentation
doWeightedQuadrature()
double sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature (DataVector & alpha, sgpp::base::DistributionsVector pdfs) override virtual
Quadrature for not a knot B-spline basis functions w.r.t.
a probability density function
Parameters
alpha Coefficient vector for current grid
pdfs probability density functions
Implements sgpp::base::OperationWeightedQuadrature.
References alpha, base, sgpp::base::DistributionsVector::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::NakBsplineBasis< LT, IT >::getMean(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getSize(), quadCoordinates, quadWeights, and storage.
Member Data Documentation
base
SNakBsplineBase sgpp::base::OperationWeightedQuadratureNakBspline::base protected
NakBsplineCombigrid Basis object.
Referenced by doWeightedQuadrature().
quadCoordinates
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBspline::quadCoordinates protected
quadrature rule coordinates
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBspline().
quadOrder
size_t sgpp::base::OperationWeightedQuadratureNakBspline::quadOrder protected
quadrature rule order
Referenced by OperationWeightedQuadratureNakBspline().
quadWeights
std::shared_ptr<base::DataVector> sgpp::base::OperationWeightedQuadratureNakBspline::quadWeights protected
quadrature rule weights
Referenced by doWeightedQuadrature(), and OperationWeightedQuadratureNakBspline().
storage
GridStorage& sgpp::base::OperationWeightedQuadratureNakBspline::storage protected
Referenced by doWeightedQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBspline.hpp
base/src/sgpp/base/operation/hash/OperationWeightedQuadratureNakBspline.cpp