SG++-Doxygen-Documentation: sgpp::base::HierarchisationSLE Class Reference
sgpp::base::HierarchisationSLE Class Reference
Linear system of the hierarchization in a sparse grid.
#include <HierarchisationSLE.hpp>
Public Member Functions
void clone (std::unique_ptr< CloneableSLE > &clone) const override
size_t getDimension () const override
Pure virtual method returning the dimension (number of rows/columns) of the system.
Grid & getGrid ()
GridStorage & getGridStorage ()
double getMatrixEntry (size_t i, size_t j) override
HierarchisationSLE (Grid &grid)
Constructor.
HierarchisationSLE (Grid &grid, GridStorage &gridStorage)
Constructor.
bool isMatrixEntryNonZero (size_t i, size_t j) override
Public Member Functions inherited from sgpp::base::CloneableSLE
CloneableSLE ()
Constructor.
bool isCloneable () const override
~CloneableSLE () override
Destructor.
Public Member Functions inherited from sgpp::base::SLE
virtual size_t countNNZ ()
Count all non-zero entries.
virtual void matrixVectorMultiplication (const DataVector &x, DataVector &y)
Multiply the matrix with a vector.
SLE ()
Constructor.
virtual ~SLE ()
Destructor.
Protected Types
enum {
INVALID , BSPLINE , BSPLINE_BOUNDARY , BSPLINE_CLENSHAW_CURTIS ,
BSPLINE_MODIFIED , BSPLINE_MODIFIED_CLENSHAW_CURTIS , FUNDAMENTAL_NAK_SPLINE , FUNDAMENTAL_SPLINE ,
FUNDAMENTAL_SPLINE_MODIFIED , WEAKLY_FUNDAMENTAL_NAK_SPLINE , WEAKLY_FUNDAMENTAL_NAK_SPLINE_MODIFIED , WEAKLY_FUNDAMENTAL_SPLINE ,
LINEAR , LINEAR_BOUNDARY , LINEAR_CLENSHAW_CURTIS , LINEAR_CLENSHAW_CURTIS_BOUNDARY ,
LINEAR_MODIFIED , NATURAL_BSPLINE , NAK_BSPLINE , NAK_BSPLINE_MODIFIED ,
WAVELET , WAVELET_BOUNDARY , WAVELET_MODIFIED , NAK_BSPLINEBOUNDARY ,
MOD_POLY , POLY , POLYBOUNDARY , NAK_BSPLINE_EXTENDED ,
NAK_P_BSPLINE
}
type of grid/basis functions
Protected Member Functions
double evalBasisFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalBsplineBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalBsplineClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalBsplineModifiedClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalBsplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalFundamentalNakSplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalFundamentalSplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalFundamentalSplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalLinearBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalLinearClenshawCurtisBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalLinearClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalLinearFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalLinearModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalModPolyFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNakBsplineBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNakBsplineExtendedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNakBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNakBsplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNakPBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalNaturalBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalPolyBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalPolyFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWaveletBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWaveletFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWaveletModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWeaklyFundamentalNakSplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ)
double evalWeaklyFundamentalSplineFunctionAtGridPoint (size_t basisI, size_t pointJ)
Protected Attributes
enum sgpp::base::HierarchisationSLE:: { ... } basisType
type of grid/basis functions
std::unique_ptr< SBsplineBase > bsplineBasis
B-spline basis.
std::unique_ptr< SBsplineBoundaryBase > bsplineBoundaryBasis
B-spline boundary basis.
std::unique_ptr< SBsplineClenshawCurtisBase > bsplineClenshawCurtisBasis
B-spline Clenshaw-Curtis basis.
std::unique_ptr< SFundamentalNakSplineBase > fundamentalNakSplineBasis
fundamental not-a-knot spline basis
std::unique_ptr< SFundamentalSplineBase > fundamentalSplineBasis
fundamental spline basis
Grid & grid
sparse grid
GridStorage & gridStorage
grid storage
std::unique_ptr< SLinearBase > linearBasis
linear basis
std::unique_ptr< SLinearClenshawCurtisBase > linearClenshawCurtisBasis
linear Clenshaw-Curtis basis
std::unique_ptr< SLinearClenshawCurtisBoundaryBase > linearClenshawCurtisBoundaryBasis
linear Clenshaw-Curtis boundary basis
std::unique_ptr< SLinearBoundaryBase > linearL0BoundaryBasis
linear boundary basis
std::unique_ptr< SBsplineModifiedBase > modBsplineBasis
modified B-spline basis
std::unique_ptr< SBsplineModifiedClenshawCurtisBase > modBsplineClenshawCurtisBasis
modified B-spline Clenshaw-Curtis basis
std::unique_ptr< SFundamentalSplineModifiedBase > modFundamentalSplineBasis
modified fundamental spline basis
std::unique_ptr< SLinearModifiedBase > modLinearBasis
modified linear basis
std::unique_ptr< SNakBsplineModifiedBase > modNakBsplineBasis
modified not-a-knot B-spline basis
std::unique_ptr< SPolyModifiedBase > modPolyBasis
mod poly basis
std::unique_ptr< SWaveletModifiedBase > modWaveletBasis
modified wavelet basis
std::unique_ptr< SWeaklyFundamentalNakSplineModifiedBase > modWeaklyFundamentalNakSplineBasis
modified weakly fundamental not-a-knot spline basis
std::unique_ptr< SNakBsplineBase > nakBsplineBasis
not-a-knot B-spline basis
std::unique_ptr< SNakBsplineBoundaryBase > nakBsplineBoundaryBasis
not-a-knot B-spline Boundary basis
std::unique_ptr< SNakBsplineExtendedBase > nakBsplineExtendedBasis
nak Bspline extended basis
std::unique_ptr< SNakPBsplineBase > nakPBsplineBasis
nak Bspline extended basis
std::unique_ptr< SNaturalBsplineBase > naturalBsplineBasis
natural B-spline basis
std::unique_ptr< SPolyBase > polyBasis
poly basis
std::unique_ptr< SPolyBoundaryBase > polyBoundaryBasis
poly boundary basis
std::unique_ptr< SWaveletBase > waveletBasis
wavelet basis
std::unique_ptr< SWaveletBoundaryBase > waveletBoundaryBasis
wavelet boundary basis
std::unique_ptr< SWeaklyFundamentalNakSplineBase > weaklyFundamentalNakSplineBasis
weakly fundamental not-a-knot spline basis
std::unique_ptr< SWeaklyFundamentalSplineBase > weaklyFundamentalSplineBasis
weakly fundamental spline basis
Detailed Description
Linear system of the hierarchization in a sparse grid.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
type of grid/basis functions
Enumerator
INVALID
BSPLINE
BSPLINE_BOUNDARY
BSPLINE_CLENSHAW_CURTIS
BSPLINE_MODIFIED
BSPLINE_MODIFIED_CLENSHAW_CURTIS
FUNDAMENTAL_NAK_SPLINE
FUNDAMENTAL_SPLINE
FUNDAMENTAL_SPLINE_MODIFIED
WEAKLY_FUNDAMENTAL_NAK_SPLINE
WEAKLY_FUNDAMENTAL_NAK_SPLINE_MODIFIED
WEAKLY_FUNDAMENTAL_SPLINE
LINEAR
LINEAR_BOUNDARY
LINEAR_CLENSHAW_CURTIS
LINEAR_CLENSHAW_CURTIS_BOUNDARY
LINEAR_MODIFIED
NATURAL_BSPLINE
NAK_BSPLINE
NAK_BSPLINE_MODIFIED
WAVELET
WAVELET_BOUNDARY
WAVELET_MODIFIED
NAK_BSPLINEBOUNDARY
MOD_POLY
POLY
POLYBOUNDARY
NAK_BSPLINE_EXTENDED
NAK_P_BSPLINE
Constructor & Destructor Documentation
HierarchisationSLE() [1/2]
sgpp::base::HierarchisationSLE::HierarchisationSLE (Grid & grid) inline explicit
Constructor.
Do not destruct the grid before this object!
Parameters
grid sparse grid
HierarchisationSLE() [2/2]
sgpp::base::HierarchisationSLE::HierarchisationSLE (Grid & grid, GridStorage & gridStorage) inline
Constructor.
Do not destruct the grid before this object!
Parameters
grid sparse grid
gridStorage custom grid storage (use basis function according to grid, but use another set of grid points according to gridStorage)
References basisType, sgpp::base::Bspline, BSPLINE, BSPLINE_BOUNDARY, BSPLINE_CLENSHAW_CURTIS, BSPLINE_MODIFIED, BSPLINE_MODIFIED_CLENSHAW_CURTIS, bsplineBasis, sgpp::base::BsplineBoundary, bsplineBoundaryBasis, sgpp::base::BsplineClenshawCurtis, bsplineClenshawCurtisBasis, FUNDAMENTAL_NAK_SPLINE, FUNDAMENTAL_SPLINE, FUNDAMENTAL_SPLINE_MODIFIED, fundamentalNakSplineBasis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, fundamentalSplineBasis, sgpp::base::FundamentalSplineBoundary, sgpp::base::Grid::getType(), grid, sgpp::base::Linear, LINEAR, LINEAR_BOUNDARY, LINEAR_CLENSHAW_CURTIS, LINEAR_CLENSHAW_CURTIS_BOUNDARY, LINEAR_MODIFIED, linearBasis, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, linearClenshawCurtisBasis, sgpp::base::LinearClenshawCurtisBoundary, linearClenshawCurtisBoundaryBasis, linearL0BoundaryBasis, sgpp::base::ModBspline, modBsplineBasis, sgpp::base::ModBsplineClenshawCurtis, modBsplineClenshawCurtisBasis, sgpp::base::ModFundamentalSpline, modFundamentalSplineBasis, sgpp::base::ModLinear, modLinearBasis, sgpp::base::ModNakBspline, modNakBsplineBasis, sgpp::base::ModWavelet, modWaveletBasis, sgpp::base::ModWeaklyFundamentalNakSpline, modWeaklyFundamentalNakSplineBasis, NAK_BSPLINE, NAK_BSPLINE_EXTENDED, NAK_BSPLINE_MODIFIED, NAK_BSPLINEBOUNDARY, NAK_P_BSPLINE, sgpp::base::NakBspline, nakBsplineBasis, sgpp::base::NakBsplineBoundary, nakBsplineBoundaryBasis, sgpp::base::NakBsplineExtended, nakBsplineExtendedBasis, sgpp::base::NakPBspline, nakPBsplineBasis, NATURAL_BSPLINE, naturalBsplineBasis, sgpp::base::NaturalBsplineBoundary, sgpp::base::Wavelet, WAVELET, WAVELET_BOUNDARY, WAVELET_MODIFIED, waveletBasis, sgpp::base::WaveletBoundary, waveletBoundaryBasis, WEAKLY_FUNDAMENTAL_NAK_SPLINE, WEAKLY_FUNDAMENTAL_NAK_SPLINE_MODIFIED, WEAKLY_FUNDAMENTAL_SPLINE, weaklyFundamentalNakSplineBasis, sgpp::base::WeaklyFundamentalNakSplineBoundary, weaklyFundamentalSplineBasis, and sgpp::base::WeaklyFundamentalSplineBoundary.
Member Function Documentation
clone()
void sgpp::base::HierarchisationSLE::clone (std::unique_ptr< CloneableSLE > & clone) const inline override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::CloneableSLE.
References clone(), grid, and gridStorage.
Referenced by clone().
evalBasisFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBasisFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th basis function at the pointJ-th grid point
References basisType, BSPLINE, BSPLINE_BOUNDARY, BSPLINE_CLENSHAW_CURTIS, BSPLINE_MODIFIED, BSPLINE_MODIFIED_CLENSHAW_CURTIS, evalBsplineBoundaryFunctionAtGridPoint(), evalBsplineClenshawCurtisFunctionAtGridPoint(), evalBsplineFunctionAtGridPoint(), evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), evalBsplineModifiedFunctionAtGridPoint(), evalFundamentalNakSplineFunctionAtGridPoint(), evalFundamentalSplineFunctionAtGridPoint(), evalFundamentalSplineModifiedFunctionAtGridPoint(), evalLinearBoundaryFunctionAtGridPoint(), evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), evalLinearClenshawCurtisFunctionAtGridPoint(), evalLinearFunctionAtGridPoint(), evalLinearModifiedFunctionAtGridPoint(), evalModPolyFunctionAtGridPoint(), evalNakBsplineBoundaryFunctionAtGridPoint(), evalNakBsplineExtendedFunctionAtGridPoint(), evalNakBsplineFunctionAtGridPoint(), evalNakBsplineModifiedFunctionAtGridPoint(), evalNakPBsplineFunctionAtGridPoint(), evalNaturalBsplineFunctionAtGridPoint(), evalPolyBoundaryFunctionAtGridPoint(), evalPolyFunctionAtGridPoint(), evalWaveletBoundaryFunctionAtGridPoint(), evalWaveletFunctionAtGridPoint(), evalWaveletModifiedFunctionAtGridPoint(), evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), evalWeaklyFundamentalSplineFunctionAtGridPoint(), FUNDAMENTAL_NAK_SPLINE, FUNDAMENTAL_SPLINE, FUNDAMENTAL_SPLINE_MODIFIED, LINEAR, LINEAR_BOUNDARY, LINEAR_CLENSHAW_CURTIS, LINEAR_CLENSHAW_CURTIS_BOUNDARY, LINEAR_MODIFIED, MOD_POLY, NAK_BSPLINE, NAK_BSPLINE_EXTENDED, NAK_BSPLINE_MODIFIED, NAK_BSPLINEBOUNDARY, NAK_P_BSPLINE, NATURAL_BSPLINE, POLY, POLYBOUNDARY, WAVELET, WAVELET_BOUNDARY, WAVELET_MODIFIED, WEAKLY_FUNDAMENTAL_NAK_SPLINE, WEAKLY_FUNDAMENTAL_NAK_SPLINE_MODIFIED, and WEAKLY_FUNDAMENTAL_SPLINE.
Referenced by getMatrixEntry(), and isMatrixEntryNonZero().
evalBsplineBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBsplineBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th B-spline boundary basis function at the pointJ-th grid point
References bsplineBoundaryBasis, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), and gridStorage.
Referenced by evalBasisFunctionAtGridPoint().
evalBsplineClenshawCurtisFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBsplineClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th B-spline Clenshaw-Curtis basis function at the pointJ-th grid point
References bsplineClenshawCurtisBasis, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getUnitPointCoordinate(), and gridStorage.
Referenced by evalBasisFunctionAtGridPoint().
evalBsplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th B-spline basis function at the pointJ-th grid point
References bsplineBasis, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), and gridStorage.
Referenced by evalBasisFunctionAtGridPoint().
evalBsplineModifiedClenshawCurtisFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBsplineModifiedClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified Clenshaw-Curtis B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getUnitPointCoordinate(), gridStorage, and modBsplineClenshawCurtisBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalBsplineModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalBsplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modBsplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalFundamentalNakSplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalFundamentalNakSplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th fundamental not-a-knot spline basis function at the pointJ-th grid point
References fundamentalNakSplineBasis, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getUnitCoordinate(), and gridStorage.
Referenced by evalBasisFunctionAtGridPoint().
evalFundamentalSplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalFundamentalSplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th fundamental spline basis function at the pointJ-th grid point
References fundamentalSplineBasis, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), and gridStorage.
Referenced by evalBasisFunctionAtGridPoint().
evalFundamentalSplineModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalFundamentalSplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified fundamental spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modFundamentalSplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalLinearBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalLinearBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th linear boundary basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and linearL0BoundaryBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalLinearClenshawCurtisBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th linear Clenshaw-Curtis boundary basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getUnitPointCoordinate(), gridStorage, and linearClenshawCurtisBoundaryBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalLinearClenshawCurtisFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th linear Clenshaw-Curtis basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), sgpp::base::HashGridStorage::getUnitPointCoordinate(), gridStorage, and linearClenshawCurtisBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalLinearFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalLinearFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th linear basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and linearBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalLinearModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalLinearModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified linear basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modLinearBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalModPolyFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalModPolyFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th mod poly (modified Bungartz polynomials) basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modPolyBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNakBsplineBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNakBsplineBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th not-a-knot B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and nakBsplineBoundaryBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNakBsplineExtendedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNakBsplineExtendedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th nak Bspline extended basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and nakBsplineExtendedBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNakBsplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNakBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th not-a-knot B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and nakBsplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNakBsplineModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNakBsplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified not-a-knot B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modNakBsplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNakPBsplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNakPBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th nak polynomial Bspline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and nakPBsplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalNaturalBsplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalNaturalBsplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th natural B-spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getUnitCoordinate(), gridStorage, and naturalBsplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalPolyBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalPolyBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th poly boundary basis (Bungartz polynomialswith with boundary) function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and polyBoundaryBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalPolyFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalPolyFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th poly basis (Bungartz polynomials) function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and polyBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWaveletBoundaryFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWaveletBoundaryFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th wavelet boundary basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and waveletBoundaryBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWaveletFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWaveletFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th wavelet basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and waveletBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWaveletModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWaveletModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified wavelet basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointCoordinate(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), gridStorage, and modWaveletBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWeaklyFundamentalNakSplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th weakly fundamental not-a-knot spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getUnitCoordinate(), gridStorage, and weaklyFundamentalNakSplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th modified weakly fundamental not-a-knot spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getUnitCoordinate(), gridStorage, and modWeaklyFundamentalNakSplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
evalWeaklyFundamentalSplineFunctionAtGridPoint()
double sgpp::base::HierarchisationSLE::evalWeaklyFundamentalSplineFunctionAtGridPoint (size_t basisI, size_t pointJ) inline protected
Parameters
basisI basis function index
pointJ grid point index
Returns
value of the basisI-th weakly fundamental spline basis function at the pointJ-th grid point
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getUnitCoordinate(), gridStorage, and weaklyFundamentalSplineBasis.
Referenced by evalBasisFunctionAtGridPoint().
getDimension()
size_t sgpp::base::HierarchisationSLE::getDimension () const inline override virtual
Pure virtual method returning the dimension (number of rows/columns) of the system.
Returns
system dimension
Implements sgpp::base::SLE.
References sgpp::base::HashGridStorage::getSize(), and gridStorage.
getGrid()
Grid & sgpp::base::HierarchisationSLE::getGrid () inline
Returns
sparse grid
References grid.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
getGridStorage()
GridStorage & sgpp::base::HierarchisationSLE::getGridStorage () inline
Returns
grid storage
References gridStorage.
getMatrixEntry()
double sgpp::base::HierarchisationSLE::getMatrixEntry (size_t i, size_t j) inline override virtual
Parameters
i row index
j column index
Returns
value of the j-th basis function at the i-th grid point
Implements sgpp::base::SLE.
References evalBasisFunctionAtGridPoint().
Referenced by sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate().
isMatrixEntryNonZero()
bool sgpp::base::HierarchisationSLE::isMatrixEntryNonZero (size_t i, size_t j) inline override virtual
Parameters
i row index
j column index
Returns
whether the i-th grid point lies in the support of the j-th basis function
Implements sgpp::base::SLE.
References evalBasisFunctionAtGridPoint().
Member Data Documentation
[]
enum { ... } sgpp::base::HierarchisationSLE::basisType
type of grid/basis functions
Referenced by evalBasisFunctionAtGridPoint(), and HierarchisationSLE().
bsplineBasis
std::unique_ptr<SBsplineBase> sgpp::base::HierarchisationSLE::bsplineBasis protected
B-spline basis.
Referenced by evalBsplineFunctionAtGridPoint(), and HierarchisationSLE().
bsplineBoundaryBasis
std::unique_ptr<SBsplineBoundaryBase> sgpp::base::HierarchisationSLE::bsplineBoundaryBasis protected
B-spline boundary basis.
Referenced by evalBsplineBoundaryFunctionAtGridPoint(), and HierarchisationSLE().
bsplineClenshawCurtisBasis
std::unique_ptr<SBsplineClenshawCurtisBase> sgpp::base::HierarchisationSLE::bsplineClenshawCurtisBasis protected
B-spline Clenshaw-Curtis basis.
Referenced by evalBsplineClenshawCurtisFunctionAtGridPoint(), and HierarchisationSLE().
fundamentalNakSplineBasis
std::unique_ptr<SFundamentalNakSplineBase> sgpp::base::HierarchisationSLE::fundamentalNakSplineBasis protected
fundamental not-a-knot spline basis
Referenced by evalFundamentalNakSplineFunctionAtGridPoint(), and HierarchisationSLE().
fundamentalSplineBasis
std::unique_ptr<SFundamentalSplineBase> sgpp::base::HierarchisationSLE::fundamentalSplineBasis protected
fundamental spline basis
Referenced by evalFundamentalSplineFunctionAtGridPoint(), and HierarchisationSLE().
grid
Grid& sgpp::base::HierarchisationSLE::grid protected
sparse grid
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), clone(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), HierarchisationSLE(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
gridStorage
GridStorage& sgpp::base::HierarchisationSLE::gridStorage protected
grid storage
Referenced by clone(), evalBsplineBoundaryFunctionAtGridPoint(), evalBsplineClenshawCurtisFunctionAtGridPoint(), evalBsplineFunctionAtGridPoint(), evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), evalBsplineModifiedFunctionAtGridPoint(), evalFundamentalNakSplineFunctionAtGridPoint(), evalFundamentalSplineFunctionAtGridPoint(), evalFundamentalSplineModifiedFunctionAtGridPoint(), evalLinearBoundaryFunctionAtGridPoint(), evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), evalLinearClenshawCurtisFunctionAtGridPoint(), evalLinearFunctionAtGridPoint(), evalLinearModifiedFunctionAtGridPoint(), evalModPolyFunctionAtGridPoint(), evalNakBsplineBoundaryFunctionAtGridPoint(), evalNakBsplineExtendedFunctionAtGridPoint(), evalNakBsplineFunctionAtGridPoint(), evalNakBsplineModifiedFunctionAtGridPoint(), evalNakPBsplineFunctionAtGridPoint(), evalNaturalBsplineFunctionAtGridPoint(), evalPolyBoundaryFunctionAtGridPoint(), evalPolyFunctionAtGridPoint(), evalWaveletBoundaryFunctionAtGridPoint(), evalWaveletFunctionAtGridPoint(), evalWaveletModifiedFunctionAtGridPoint(), evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), evalWeaklyFundamentalSplineFunctionAtGridPoint(), getDimension(), and getGridStorage().
linearBasis
std::unique_ptr<SLinearBase> sgpp::base::HierarchisationSLE::linearBasis protected
linear basis
Referenced by evalLinearFunctionAtGridPoint(), and HierarchisationSLE().
linearClenshawCurtisBasis
std::unique_ptr<SLinearClenshawCurtisBase> sgpp::base::HierarchisationSLE::linearClenshawCurtisBasis protected
linear Clenshaw-Curtis basis
Referenced by evalLinearClenshawCurtisFunctionAtGridPoint(), and HierarchisationSLE().
linearClenshawCurtisBoundaryBasis
std::unique_ptr<SLinearClenshawCurtisBoundaryBase> sgpp::base::HierarchisationSLE::linearClenshawCurtisBoundaryBasis protected
linear Clenshaw-Curtis boundary basis
Referenced by evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), and HierarchisationSLE().
linearL0BoundaryBasis
std::unique_ptr<SLinearBoundaryBase> sgpp::base::HierarchisationSLE::linearL0BoundaryBasis protected
linear boundary basis
Referenced by evalLinearBoundaryFunctionAtGridPoint(), and HierarchisationSLE().
modBsplineBasis
std::unique_ptr<SBsplineModifiedBase> sgpp::base::HierarchisationSLE::modBsplineBasis protected
modified B-spline basis
Referenced by evalBsplineModifiedFunctionAtGridPoint(), and HierarchisationSLE().
modBsplineClenshawCurtisBasis
std::unique_ptr<SBsplineModifiedClenshawCurtisBase> sgpp::base::HierarchisationSLE::modBsplineClenshawCurtisBasis protected
modified B-spline Clenshaw-Curtis basis
Referenced by evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), and HierarchisationSLE().
modFundamentalSplineBasis
std::unique_ptr<SFundamentalSplineModifiedBase> sgpp::base::HierarchisationSLE::modFundamentalSplineBasis protected
modified fundamental spline basis
Referenced by evalFundamentalSplineModifiedFunctionAtGridPoint(), and HierarchisationSLE().
modLinearBasis
std::unique_ptr<SLinearModifiedBase> sgpp::base::HierarchisationSLE::modLinearBasis protected
modified linear basis
Referenced by evalLinearModifiedFunctionAtGridPoint(), and HierarchisationSLE().
modNakBsplineBasis
std::unique_ptr<SNakBsplineModifiedBase> sgpp::base::HierarchisationSLE::modNakBsplineBasis protected
modified not-a-knot B-spline basis
Referenced by evalNakBsplineModifiedFunctionAtGridPoint(), and HierarchisationSLE().
modPolyBasis
std::unique_ptr<SPolyModifiedBase> sgpp::base::HierarchisationSLE::modPolyBasis protected
mod poly basis
Referenced by evalModPolyFunctionAtGridPoint().
modWaveletBasis
std::unique_ptr<SWaveletModifiedBase> sgpp::base::HierarchisationSLE::modWaveletBasis protected
modified wavelet basis
Referenced by evalWaveletModifiedFunctionAtGridPoint(), and HierarchisationSLE().
modWeaklyFundamentalNakSplineBasis
std::unique_ptr<SWeaklyFundamentalNakSplineModifiedBase> sgpp::base::HierarchisationSLE::modWeaklyFundamentalNakSplineBasis protected
modified weakly fundamental not-a-knot spline basis
Referenced by evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), and HierarchisationSLE().
nakBsplineBasis
std::unique_ptr<SNakBsplineBase> sgpp::base::HierarchisationSLE::nakBsplineBasis protected
not-a-knot B-spline basis
Referenced by evalNakBsplineFunctionAtGridPoint(), and HierarchisationSLE().
nakBsplineBoundaryBasis
std::unique_ptr<SNakBsplineBoundaryBase> sgpp::base::HierarchisationSLE::nakBsplineBoundaryBasis protected
not-a-knot B-spline Boundary basis
Referenced by evalNakBsplineBoundaryFunctionAtGridPoint(), and HierarchisationSLE().
nakBsplineExtendedBasis
std::unique_ptr<SNakBsplineExtendedBase> sgpp::base::HierarchisationSLE::nakBsplineExtendedBasis protected
nak Bspline extended basis
Referenced by evalNakBsplineExtendedFunctionAtGridPoint(), and HierarchisationSLE().
nakPBsplineBasis
std::unique_ptr<SNakPBsplineBase> sgpp::base::HierarchisationSLE::nakPBsplineBasis protected
nak Bspline extended basis
Referenced by evalNakPBsplineFunctionAtGridPoint(), and HierarchisationSLE().
naturalBsplineBasis
std::unique_ptr<SNaturalBsplineBase> sgpp::base::HierarchisationSLE::naturalBsplineBasis protected
natural B-spline basis
Referenced by evalNaturalBsplineFunctionAtGridPoint(), and HierarchisationSLE().
polyBasis
std::unique_ptr<SPolyBase> sgpp::base::HierarchisationSLE::polyBasis protected
poly basis
Referenced by evalPolyFunctionAtGridPoint().
polyBoundaryBasis
std::unique_ptr<SPolyBoundaryBase> sgpp::base::HierarchisationSLE::polyBoundaryBasis protected
poly boundary basis
Referenced by evalPolyBoundaryFunctionAtGridPoint().
waveletBasis
std::unique_ptr<SWaveletBase> sgpp::base::HierarchisationSLE::waveletBasis protected
wavelet basis
Referenced by evalWaveletFunctionAtGridPoint(), and HierarchisationSLE().
waveletBoundaryBasis
std::unique_ptr<SWaveletBoundaryBase> sgpp::base::HierarchisationSLE::waveletBoundaryBasis protected
wavelet boundary basis
Referenced by evalWaveletBoundaryFunctionAtGridPoint(), and HierarchisationSLE().
weaklyFundamentalNakSplineBasis
std::unique_ptr<SWeaklyFundamentalNakSplineBase> sgpp::base::HierarchisationSLE::weaklyFundamentalNakSplineBasis protected
weakly fundamental not-a-knot spline basis
Referenced by evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), and HierarchisationSLE().
weaklyFundamentalSplineBasis
std::unique_ptr<SWeaklyFundamentalSplineBase> sgpp::base::HierarchisationSLE::weaklyFundamentalSplineBasis protected
weakly fundamental spline basis
Referenced by evalWeaklyFundamentalSplineFunctionAtGridPoint(), and HierarchisationSLE().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/sle/system/HierarchisationSLE.hpp