SG++-Doxygen-Documentation: sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary Class Reference
sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary Class Reference
This class is helper class to implement the complete Down of following bilinearform \(\int_{x} \frac{\partial \phi(x)}{x} \frac{\partial \phi(x)}{x} dx\) for a given dimension by an iterative algorithms on adaptive Sparse Grids with linear ansatzfunctions with boundaries.
#include <DowndPhidPhiBBIterativeLinearStretchedBoundary.hpp>
Public Member Functions
DowndPhidPhiBBIterativeLinearStretchedBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual void operator() (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
This operations performs the calculation of Down in the direction of dimension dim of following bilinearform: \(\int_{x} \frac{\partial \phi(x)}{x} \frac{\partial \phi(x)}{x} dx\).
virtual ~DowndPhidPhiBBIterativeLinearStretchedBoundary ()
Destructor.
Detailed Description
This class is helper class to implement the complete Down of following bilinearform \(\int_{x} \frac{\partial \phi(x)}{x} \frac{\partial \phi(x)}{x} dx\) for a given dimension by an iterative algorithms on adaptive Sparse Grids with linear ansatzfunctions with boundaries.
This is possible due to the fact that the operator's matrix has only entries on the diagonal.
-> the Up/Down can be implemented by iterating over all ansatzfunctions
Constructor & Destructor Documentation
DowndPhidPhiBBIterativeLinearStretchedBoundary()
sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::DowndPhidPhiBBIterativeLinearStretchedBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage Pointer to the grid's storage object
~DowndPhidPhiBBIterativeLinearStretchedBoundary()
sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::~DowndPhidPhiBBIterativeLinearStretchedBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator() (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) virtual
This operations performs the calculation of Down in the direction of dimension dim of following bilinearform: \(\int_{x} \frac{\partial \phi(x)}{x} \frac{\partial \phi(x)}{x} dx\).
Parameters
alpha sgpp::base::DataVector that contains the gridpoint's coefficients
result sgpp::base::DataVector that contains the result of the down operation
dim current fixed dimension of the 'execution direction'
References alpha, sgpp::base::DataVector::get(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridStorage::getSize(), sgpp::base::HashGridStorage::getStretching(), sgpp::base::BoundingBox::hasDirichletBoundaryLeft(), sgpp::base::BoundingBox::hasDirichletBoundaryRight(), level, sgpp::base::HashGridPoint::set(), and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linearstretched/boundary/DowndPhidPhiBBIterativeLinearStretchedBoundary.hpp
pde/src/sgpp/pde/basis/linearstretched/boundary/DowndPhidPhiBBIterativeLinearStretchedBoundary.cpp