SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensityMarginalizeLinear Class Reference
sgpp::datadriven::OperationDensityMarginalizeLinear Class Reference
Marginalize Probability Density Function.
#include <OperationDensityMarginalizeLinear.hpp>
Public Member Functions
void doMarginalize (base::DataVector &alpha, base::Grid *&mg, base::DataVector &malpha, unsigned int mdim) override
Marginalizes (Density) Functions.
OperationDensityMarginalizeLinear (base::Grid *grid)
~OperationDensityMarginalizeLinear () override
Public Member Functions inherited from sgpp::datadriven::OperationDensityMarginalize
OperationDensityMarginalize (base::Grid *grid)
virtual ~OperationDensityMarginalize ()
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::OperationDensityMarginalize
base::Grid * grid
Detailed Description
Marginalize Probability Density Function.
Constructor & Destructor Documentation
OperationDensityMarginalizeLinear()
sgpp::datadriven::OperationDensityMarginalizeLinear::OperationDensityMarginalizeLinear (base::Grid * grid) inline explicit
~OperationDensityMarginalizeLinear()
sgpp::datadriven::OperationDensityMarginalizeLinear::~OperationDensityMarginalizeLinear () inline override
Member Function Documentation
doMarginalize()
void sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize (base::DataVector & alpha, base::Grid *& mg, base::DataVector & malpha, unsigned int mdim) override virtual
Marginalizes (Density) Functions.
Parameters
alpha Coefficient vector for current grid
mg Referenz of grid pointer
malpha Coefficient vector for new grid (mg). Will be resized.
mdim Marginalize in dimension mdim
Note: Because of adaptively refined sparse grids, we cannot simply generate a regular grid. Thus, we need to add point after point to the new grid mg
Compute coefficients for marginalized density Each coefficient has to be weighted with the integral of the basis functions in direction mdim
Attention: The integral of one basis functions changes for if another type of basis is used!
Reimplemented from sgpp::datadriven::OperationDensityMarginalize.
References alpha, sgpp::base::Grid::createLinearGrid(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridStorage::getSize(), sgpp::base::Grid::getStorage(), sgpp::datadriven::OperationDensityMarginalize::grid, sgpp::base::HashGridStorage::insert(), sgpp::base::HashGridStorage::isContaining(), sgpp::base::HashGridStorage::recalcLeafProperty(), sgpp::base::HashGridPoint::set(), and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMarginalizeLinear.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMarginalizeLinear.cpp