SG++-Doxygen-Documentation: sgpp::base::OCLBufferWrapperSD< T > Class Template Reference
sgpp::base::OCLBufferWrapperSD< T > Class Template Reference
#include <OCLBufferWrapperSD.hpp>
Public Member Functions
void freeBuffer ()
cl_mem * getBuffer ()
std::vector< T > & getHostPointer ()
void initializeBuffer (size_t elements)
void intializeTo (std::vector< T > &hostBuffer, size_t dim, size_t offsetStart, size_t offsetEnd, bool storeStructOfArrays=false)
bool isInitialized ()
OCLBufferWrapperSD (std::shared_ptr< base::OCLDevice > device)
void readFromBuffer ()
size_t size ()
void writeToBuffer ()
~OCLBufferWrapperSD ()
Constructor & Destructor Documentation
OCLBufferWrapperSD()
template<typename T > sgpp::base::OCLBufferWrapperSD< T >::OCLBufferWrapperSD (std::shared_ptr< base::OCLDevice > device) inline explicit
~OCLBufferWrapperSD()
template<typename T > sgpp::base::OCLBufferWrapperSD< T >::~OCLBufferWrapperSD () inline
References sgpp::base::OCLBufferWrapperSD< T >::freeBuffer().
Member Function Documentation
freeBuffer()
template<typename T > void sgpp::base::OCLBufferWrapperSD< T >::freeBuffer () inline
Referenced by sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and sgpp::base::OCLBufferWrapperSD< T >::~OCLBufferWrapperSD().
getBuffer()
template<typename T > cl_mem * sgpp::base::OCLBufferWrapperSD< T >::getBuffer () inline
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation(), sgpp::datadriven::StreamingModOCLUnified::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLOpt::KernelMult< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLUnified::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLOpt::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMultTranspose< T >::multTranspose(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::multTranspose(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::prune_graph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation().
getHostPointer()
template<typename T > std::vector< T > & sgpp::base::OCLBufferWrapperSD< T >::getHostPointer () inline
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::finalize_graph_creation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::finalize_rhs_generation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::finish_mult(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), sgpp::datadriven::StreamingModOCLUnified::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLOpt::KernelMult< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLUnified::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLOpt::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMultTranspose< T >::multTranspose(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::multTranspose(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::prune_graph().
initializeBuffer()
template<typename T > void sgpp::base::OCLBufferWrapperSD< T >::initializeBuffer (size_t elements) inline
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult().
intializeTo()
template<typename T > void sgpp::base::OCLBufferWrapperSD< T >::intializeTo (std::vector< T > & hostBuffer, size_t dim, size_t offsetStart, size_t offsetEnd, bool storeStructOfArrays = false) inline
References sgpp::base::OCLBufferWrapperSD< T >::freeBuffer(), sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), sgpp::base::OCLBufferWrapperSD< T >::initializeBuffer(), sgpp::base::OCLBufferWrapperSD< T >::isInitialized(), sgpp::base::OCLBufferWrapperSD< T >::size(), and sgpp::base::OCLBufferWrapperSD< T >::writeToBuffer().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::initialize_alpha_buffer(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::initialize_dataset(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::KernelCreateGraph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::KernelDensityB(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::KernelDensityMult(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::KernelPruneGraph(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::prune_graph(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation().
isInitialized()
template<typename T > bool sgpp::base::OCLBufferWrapperSD< T >::isInitialized () inline
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::begin_graph_creation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::initialize_dataset(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::start_mult(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::start_rhs_generation().
readFromBuffer()
template<typename T > void sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer () inline
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::finalize_graph_creation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::finalize_rhs_generation(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::finish_mult(), sgpp::datadriven::StreamingModOCLUnified::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMult< real_type >::mult(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLOpt::KernelMult< T >::mult(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMult< T >::mult(), sgpp::datadriven::StreamingModOCLUnified::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLMaskMultiPlatform::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingModOCLOpt::KernelMultTranspose< real_type >::multTranspose(), sgpp::datadriven::StreamingOCLMultiPlatform::KernelMultTranspose< T >::multTranspose(), sgpp::datadriven::StreamingModOCLFastMultiPlatform::KernelMultTranspose< T >::multTranspose(), and sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::prune_graph().
size()
template<typename T > size_t sgpp::base::OCLBufferWrapperSD< T >::size () inline
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), python.data.DataContainer.DataContainer::getSize(), and sgpp::base::OCLBufferWrapperSD< T >::intializeTo().
writeToBuffer()
template<typename T > void sgpp::base::OCLBufferWrapperSD< T >::writeToBuffer () inline
Referenced by sgpp::base::OCLBufferWrapperSD< T >::intializeTo().
The documentation for this class was generated from the following file:
base/src/sgpp/base/opencl/OCLBufferWrapperSD.hpp