SG++-Doxygen-Documentation: sgpp::datadriven::Dataset Class Reference
sgpp::datadriven::Dataset Class Reference
#include <Dataset.hpp>
Public Member Functions
Dataset ()
Constructs an empty dataset (zero size).
Dataset (size_t numberInstances, size_t dimension)
Constructs an empty dataset with given size.
sgpp::base::DataMatrix & getData ()
const sgpp::base::DataMatrix & getData () const
size_t getDimension () const
size_t getNumberInstances () const
sgpp::base::DataVector & getTargets ()
const sgpp::base::DataVector & getTargets () const
Protected Attributes
sgpp::base::DataMatrix data
size_t dimension
size_t numberInstances
sgpp::base::DataVector targets
Constructor & Destructor Documentation
Dataset() [1/2]
sgpp::datadriven::Dataset::Dataset ()
Constructs an empty dataset (zero size).
Dataset() [2/2]
sgpp::datadriven::Dataset::Dataset (size_t numberInstances, size_t dimension)
Constructs an empty dataset with given size.
Parameters
numberInstances number of instances in the dataset
dimension number of dimensions in the dataset
Member Function Documentation
getData() [1/2]
sgpp::base::DataMatrix & sgpp::datadriven::Dataset::getData ()
Returns
training data of the dataset
References getData().
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::datadriven::RosenblattTransformation::doInverseTransformation(), sgpp::datadriven::LearnerSGDEOnOffParallel::doRefinementForAll(), sgpp::datadriven::RosenblattTransformation::doTransformation(), sgpp::datadriven::ModelFittingDensityEstimationCG::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationCombi::fit(), sgpp::datadriven::LearnerSGDEOnOffParallel::getAccuracy(), getData(), sgpp::datadriven::SortedDataset::getData(), sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), hpx_main(), sgpp::datadriven::RosenblattTransformation::initialize(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::MetaLearner::learnReferenceString(), sgpp::datadriven::MetaLearner::learnString(), main(), sgpp::datadriven::ResidualScore::measure(), sgpp::datadriven::MortonOrder::MortonOrder(), sgpp::datadriven::MortonOrder::orderDataset(), sgpp::datadriven::ARFFTools::readARFF(), sgpp::datadriven::CSVTools::readCSV(), sgpp::datadriven::MortonOrder::restoreDataset(), sgpp::datadriven::VisualizerClassification::runVisualization(), sgpp::datadriven::VisualizerDensityEstimation::runVisualization(), sgpp::datadriven::LearnerSGDEOnOffParallel::splitBatchIntoClasses(), sgpp::datadriven::Scorer::test(), sgpp::datadriven::ModelFittingClassification::update(), sgpp::datadriven::ModelFittingDensityEstimationCG::update(), sgpp::datadriven::ModelFittingDensityEstimationCombi::update(), sgpp::datadriven::ModelFittingDensityEstimationOnOff::update(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::update(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::update(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::update(), and sgpp::datadriven::CSVWriter::writeCSV().
getData() [2/2]
const sgpp::base::DataMatrix & sgpp::datadriven::Dataset::getData () const
Returns
training data of the dataset
References data.
getDimension()
size_t sgpp::datadriven::Dataset::getDimension () const
Returns
number of dimensions in the dataset
References dimension.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::datadriven::RosenblattTransformation::doInverseTransformation(), sgpp::datadriven::RosenblattTransformation::doTransformation(), sgpp::datadriven::ModelFittingLeastSquares::fit(), sgpp::datadriven::ModelFittingDensityRatioEstimation::fit(), sgpp::datadriven::ArffFileSampleProvider::getAllSamples(), sgpp::datadriven::CSVFileSampleProvider::getAllSamples(), sgpp::datadriven::ArffFileSampleProvider::getDim(), sgpp::datadriven::CSVFileSampleProvider::getDim(), sgpp::datadriven::LearnerSGDEOnOffParallel::getDimensionality(), sgpp::datadriven::VisualizerClassification::getHeatmapsClassification(), sgpp::datadriven::ArffFileSampleProvider::getNextSamples(), sgpp::datadriven::CSVFileSampleProvider::getNextSamples(), sgpp::datadriven::ArffFileSampleProvider::getNumSamples(), sgpp::datadriven::CSVFileSampleProvider::getNumSamples(), sgpp::datadriven::RefinementHandler::handleSurplusBasedRefinement(), hpx_main(), sgpp::datadriven::RosenblattTransformation::initialize(), sgpp::datadriven::VisualizerClassification::initializeMatrices(), sgpp::datadriven::VisualizerDensityEstimation::initializeMatrices(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::MetaLearner::learnReferenceString(), sgpp::datadriven::MetaLearner::learnString(), main(), sgpp::datadriven::LearnerSGDEOnOffParallel::train(), sgpp::datadriven::ModelFittingClassification::update(), and sgpp::datadriven::CSVWriter::writeCSV().
getNumberInstances()
size_t sgpp::datadriven::Dataset::getNumberInstances () const
Returns
number of instances in the dataset
References numberInstances.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::datadriven::LearnerSGDEOnOffParallel::assignBatchToWorker(), sgpp::datadriven::RosenblattTransformation::doInverseTransformation(), sgpp::datadriven::RosenblattTransformation::doTransformation(), sgpp::datadriven::SparseGridMinerSplitting::evaluateLambda(), sgpp::datadriven::LearnerSGDEOnOffParallel::getAccuracy(), sgpp::datadriven::ArffFileSampleProvider::getAllSamples(), sgpp::datadriven::CSVFileSampleProvider::getAllSamples(), sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), sgpp::datadriven::ArffFileSampleProvider::getNumSamples(), sgpp::datadriven::CSVFileSampleProvider::getNumSamples(), hpx_main(), sgpp::datadriven::RosenblattTransformation::initialize(), sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::MetaLearner::learnReferenceString(), sgpp::datadriven::MetaLearner::learnString(), main(), main(), sgpp::datadriven::SortedDataset::SortedDataset(), sgpp::datadriven::LearnerSGDEOnOffParallel::splitBatchIntoClasses(), sgpp::datadriven::Scorer::test(), sgpp::datadriven::LearnerSGDEOnOffParallel::train(), sgpp::datadriven::LearnerSGDEOnOffParallel::trainParallel(), sgpp::datadriven::ModelFittingClassification::update(), sgpp::datadriven::LearnerSGDEOnOffParallel::workBatch(), and sgpp::datadriven::CSVWriter::writeCSV().
getTargets() [1/2]
sgpp::base::DataVector & sgpp::datadriven::Dataset::getTargets ()
Returns
classes data of the dataset
References getTargets().
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assembleNextBatchData(), sgpp::datadriven::LearnerSGDEOnOffParallel::doRefinementForAll(), sgpp::datadriven::LearnerSGDEOnOffParallel::getAccuracy(), sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), getTargets(), sgpp::datadriven::MetaLearner::learnAndTestString(), sgpp::datadriven::MetaLearner::learnReferenceString(), sgpp::datadriven::MetaLearner::learnString(), sgpp::datadriven::MortonOrder::orderDataset(), sgpp::datadriven::ARFFTools::readARFF(), sgpp::datadriven::CSVTools::readCSV(), sgpp::datadriven::MortonOrder::restoreDataset(), sgpp::datadriven::LearnerSGDEOnOffParallel::splitBatchIntoClasses(), sgpp::datadriven::Scorer::test(), sgpp::datadriven::ModelFittingClassification::update(), and sgpp::datadriven::CSVWriter::writeCSV().
getTargets() [2/2]
const sgpp::base::DataVector & sgpp::datadriven::Dataset::getTargets () const
Returns
classes data of the dataset
References targets.
Member Data Documentation
data
sgpp::base::DataMatrix sgpp::datadriven::Dataset::data protected
Referenced by getData(), sgpp::datadriven::SortedDataset::restoreOrder(), sgpp::datadriven::SortedDataset::setOrder(), and sgpp::datadriven::SortedDataset::usePermutation().
dimension
size_t sgpp::datadriven::Dataset::dimension protected
Referenced by getDimension().
numberInstances
size_t sgpp::datadriven::Dataset::numberInstances protected
Referenced by getNumberInstances(), sgpp::datadriven::SortedDataset::setOrder(), sgpp::datadriven::SortedDataset::setOrder(), and sgpp::datadriven::SortedDataset::SortedDataset().
targets
sgpp::base::DataVector sgpp::datadriven::Dataset::targets protected
Referenced by getTargets(), sgpp::datadriven::SortedDataset::restoreOrder(), and sgpp::datadriven::SortedDataset::usePermutation().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/Dataset.hpp
datadriven/src/sgpp/datadriven/tools/Dataset.cpp