SG++-Doxygen-Documentation: sgpp::optimization::FuzzyExtensionPrincipleViaOptimization Class Reference
sgpp::optimization::FuzzyExtensionPrincipleViaOptimization Class Reference
Zadeh's fuzzy extension principle by solving optimization problems for each \(\alpha\) level.
#include <FuzzyExtensionPrincipleViaOptimization.hpp>
Public Member Functions
void clone (std::unique_ptr< FuzzyExtensionPrinciple > &clone) const override
FuzzyExtensionPrincipleViaOptimization (const base::ScalarFunction &f, size_t numberOfAlphaSegments=DEFAULT_NUMBER_OF_ALPHA_SEGMENTS)
Constructor.
FuzzyExtensionPrincipleViaOptimization (const FuzzyExtensionPrincipleViaOptimization &other)
Copy constructor.
FuzzyExtensionPrincipleViaOptimization (const optimizer::UnconstrainedOptimizer &optimizer, size_t numberOfAlphaSegments=DEFAULT_NUMBER_OF_ALPHA_SEGMENTS)
Constructor with custom optimization algorithm.
~FuzzyExtensionPrincipleViaOptimization () override
Destructor.
Public Member Functions inherited from sgpp::optimization::FuzzyExtensionPrinciple
FuzzyInterval * apply (const std::vector< FuzzyInterval * > &xFuzzy)
Apply the fuzzy extension principle to fuzzy input intervals.
FuzzyExtensionPrinciple (const base::ScalarFunction &f, size_t numberOfAlphaSegments=DEFAULT_NUMBER_OF_ALPHA_SEGMENTS)
Constructor.
FuzzyExtensionPrinciple (const FuzzyExtensionPrinciple &other)
Copy constructor.
const base::DataVector & getAlphaLevels () const
const std::vector< base::DataVector > & getMaximumPoints () const
const base::DataVector & getMaximumValues () const
const std::vector< base::DataVector > & getMinimumPoints () const
const base::DataVector & getMinimumValues () const
size_t getNumberOfAlphaSegments () const
const std::vector< base::DataVector > & getOptimizationDomainsLowerBounds () const
const std::vector< base::DataVector > & getOptimizationDomainsUpperBounds () const
void setNumberOfAlphaSegments (size_t numberOfAlphaSegments)
virtual ~FuzzyExtensionPrinciple ()
Destructor.
Protected Member Functions
void optimizeForSingleAlphaLevel (size_t j, base::DataVector &minimumPoint, double &minimumValue, base::DataVector &maximumPoint, double &maximumValue) override
Solve the minimization/maximization problem for a single \(\alpha\) level.
void prepareApply () override
Custom preparation method that is called before the parallelized optimizeForSingleAlphaLevel calls.
Protected Attributes
optimizer::MultiStart defaultOptimizer
default optimization algorithm
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionGradient > fGradientScaled
scaled objective gradient (confidence interval to unit hyper-cube)
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
std::unique_ptr< base::ScalarFunctionHessian > fHessianScaled
scaled objective Hessian (confidence interval to unit hyper-cube)
std::unique_ptr< base::ScalarFunction > fScaled
scaled objective function (confidence interval to unit hyper-cube)
std::unique_ptr< optimizer::UnconstrainedOptimizer > optimizer
optimization algorithm
Protected Attributes inherited from sgpp::optimization::FuzzyExtensionPrinciple
base::DataVector alphaLevels
number of \(\alpha\) segments
std::unique_ptr< base::ScalarFunction > f
function through which to propagate the uncertainties
size_t m
number of \(\alpha\) segments
std::vector< base::DataVector > maximumPoints
vector of maximum points (after apply call)
base::DataVector maximumValues
vector of maximum function values (after apply call)
std::vector< base::DataVector > minimumPoints
vector of minimum points (after apply call)
base::DataVector minimumValues
vector of minimum function values (after apply call)
std::vector< base::DataVector > optimizationDomainsLowerBounds
vector of lower bounds of input confidence intervals (after apply call)
std::vector< base::DataVector > optimizationDomainsUpperBounds
vector of upper bounds of input confidence intervals (after apply call)
Additional Inherited Members
Static Public Attributes inherited from sgpp::optimization::FuzzyExtensionPrinciple
static const size_t DEFAULT_NUMBER_OF_ALPHA_SEGMENTS = 10
default number of \(\alpha\) segments
Detailed Description
Zadeh's fuzzy extension principle by solving optimization problems for each \(\alpha\) level.
Constructor & Destructor Documentation
FuzzyExtensionPrincipleViaOptimization() [1/3]
sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::FuzzyExtensionPrincipleViaOptimization (const base::ScalarFunction & f, size_t numberOfAlphaSegments = DEFAULT_NUMBER_OF_ALPHA_SEGMENTS) explicit
Constructor.
By default, MultiStart is used as optimization algorithm.
Parameters
f function through which to propagate the uncertainties
numberOfAlphaSegments number of \(\alpha\) segments
References sgpp::optimization::optimizer::MultiStart::clone(), defaultOptimizer, and optimizer.
FuzzyExtensionPrincipleViaOptimization() [2/3]
sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::FuzzyExtensionPrincipleViaOptimization (const optimizer::UnconstrainedOptimizer & optimizer, size_t numberOfAlphaSegments = DEFAULT_NUMBER_OF_ALPHA_SEGMENTS) explicit
Constructor with custom optimization algorithm.
Parameters
optimizer optimization algorithm and function through which to propagate the uncertainties
numberOfAlphaSegments number of \(\alpha\) segments
References sgpp::optimization::FuzzyExtensionPrinciple::clone(), fGradient, fHessian, and optimizer.
FuzzyExtensionPrincipleViaOptimization() [3/3]
sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::FuzzyExtensionPrincipleViaOptimization (const FuzzyExtensionPrincipleViaOptimization & other)
Copy constructor.
Parameters
other other fuzzy extension principle
References fGradient, fGradientScaled, fHessian, fHessianScaled, fScaled, and optimizer.
~FuzzyExtensionPrincipleViaOptimization()
sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::~FuzzyExtensionPrincipleViaOptimization () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::clone (std::unique_ptr< FuzzyExtensionPrinciple > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::FuzzyExtensionPrinciple.
Reimplemented in sgpp::optimization::FuzzyExtensionPrincipleViaTransformation, and sgpp::optimization::FuzzyExtensionPrincipleViaVertexMethod.
References clone().
Referenced by clone().
optimizeForSingleAlphaLevel()
void sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::optimizeForSingleAlphaLevel (size_t j, base::DataVector & minimumPoint, double & minimumValue, base::DataVector & maximumPoint, double & maximumValue) override protected virtual
Solve the minimization/maximization problem for a single \(\alpha\) level.
Parameters
[in] j index of \(\alpha\) level
[out] minimumPoint minimum point
[out] minimumValue minimum function value
[out] maximumPoint maximum point
[out] maximumValue maximum function value
Implements sgpp::optimization::FuzzyExtensionPrinciple.
Reimplemented in sgpp::optimization::FuzzyExtensionPrincipleViaTransformation, and sgpp::optimization::FuzzyExtensionPrincipleViaVertexMethod.
References sgpp::optimization::FuzzyExtensionPrinciple::f, fGradientScaled, fHessianScaled, fScaled, sgpp::optimization::FuzzyExtensionPrinciple::m, sgpp::optimization::FuzzyExtensionPrinciple::maximumPoints, sgpp::optimization::FuzzyExtensionPrinciple::minimumPoints, sgpp::optimization::FuzzyExtensionPrinciple::optimizationDomainsLowerBounds, sgpp::optimization::FuzzyExtensionPrinciple::optimizationDomainsUpperBounds, optimizer, sgpp::base::ScaledScalarFunction::setLowerBounds(), sgpp::base::ScaledScalarFunctionGradient::setLowerBounds(), sgpp::base::ScaledScalarFunctionHessian::setLowerBounds(), sgpp::base::ScaledScalarFunction::setUpperBounds(), sgpp::base::ScaledScalarFunctionGradient::setUpperBounds(), sgpp::base::ScaledScalarFunctionHessian::setUpperBounds(), sgpp::base::ScaledScalarFunction::setValueFactor(), sgpp::base::ScaledScalarFunctionGradient::setValueFactor(), and sgpp::base::ScaledScalarFunctionHessian::setValueFactor().
prepareApply()
void sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::prepareApply () override protected virtual
Custom preparation method that is called before the parallelized optimizeForSingleAlphaLevel calls.
Reimplemented from sgpp::optimization::FuzzyExtensionPrinciple.
Reimplemented in sgpp::optimization::FuzzyExtensionPrincipleViaTransformation, and sgpp::optimization::FuzzyExtensionPrincipleViaVertexMethod.
References sgpp::optimization::FuzzyExtensionPrinciple::f, fGradient, fGradientScaled, fHessian, fHessianScaled, and fScaled.
Member Data Documentation
defaultOptimizer
optimizer::MultiStart sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::defaultOptimizer protected
default optimization algorithm
Referenced by FuzzyExtensionPrincipleViaOptimization().
fGradient
std::unique_ptr<base::ScalarFunctionGradient> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::fGradient protected
objective function gradient
Referenced by FuzzyExtensionPrincipleViaOptimization(), FuzzyExtensionPrincipleViaOptimization(), and prepareApply().
fGradientScaled
std::unique_ptr<base::ScalarFunctionGradient> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::fGradientScaled protected
scaled objective gradient (confidence interval to unit hyper-cube)
Referenced by FuzzyExtensionPrincipleViaOptimization(), optimizeForSingleAlphaLevel(), and prepareApply().
fHessian
std::unique_ptr<base::ScalarFunctionHessian> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::fHessian protected
objective function Hessian
Referenced by FuzzyExtensionPrincipleViaOptimization(), FuzzyExtensionPrincipleViaOptimization(), and prepareApply().
fHessianScaled
std::unique_ptr<base::ScalarFunctionHessian> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::fHessianScaled protected
scaled objective Hessian (confidence interval to unit hyper-cube)
Referenced by FuzzyExtensionPrincipleViaOptimization(), optimizeForSingleAlphaLevel(), and prepareApply().
fScaled
std::unique_ptr<base::ScalarFunction> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::fScaled protected
scaled objective function (confidence interval to unit hyper-cube)
Referenced by FuzzyExtensionPrincipleViaOptimization(), optimizeForSingleAlphaLevel(), and prepareApply().
optimizer
std::unique_ptr<optimizer::UnconstrainedOptimizer> sgpp::optimization::FuzzyExtensionPrincipleViaOptimization::optimizer protected
optimization algorithm
Referenced by FuzzyExtensionPrincipleViaOptimization(), FuzzyExtensionPrincipleViaOptimization(), FuzzyExtensionPrincipleViaOptimization(), and optimizeForSingleAlphaLevel().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/fuzzy/FuzzyExtensionPrincipleViaOptimization.hpp
optimization/src/sgpp/optimization/fuzzy/FuzzyExtensionPrincipleViaOptimization.cpp