SG++-Doxygen-Documentation: sgpp::base::WrapperVectorFunctionGradient Class Reference
sgpp::base::WrapperVectorFunctionGradient Class Reference
Implementation of VectorFunctionGradient that wraps a std::function object.
#include <WrapperVectorFunctionGradient.hpp>
Public Types
typedef std::function< void(const DataVector &, DataVector &, DataMatrix &)> FunctionGradientEvalType
Public Member Functions
void clone (std::unique_ptr< VectorFunctionGradient > &clone) const override
void eval (const DataVector &x, DataVector &value, DataMatrix &gradient) override
WrapperVectorFunctionGradient (size_t d, size_t m, FunctionGradientEvalType fGradient)
Constructor.
~WrapperVectorFunctionGradient () override
Destructor.
Public Member Functions inherited from sgpp::base::VectorFunctionGradient
size_t getNumberOfComponents () const
size_t getNumberOfParameters () const
VectorFunctionGradient (size_t d, size_t m)
Constructor.
virtual ~VectorFunctionGradient ()
Destructor.
Protected Attributes
FunctionGradientEvalType fGradient
function gradient to be wrapped
Protected Attributes inherited from sgpp::base::VectorFunctionGradient
size_t d
dimension of the domain
size_t m
number of components
Detailed Description
Implementation of VectorFunctionGradient that wraps a std::function object.
Member Typedef Documentation
FunctionGradientEvalType
typedef std::function<void(const DataVector&, DataVector&, DataMatrix&)> sgpp::base::WrapperVectorFunctionGradient::FunctionGradientEvalType
Constructor & Destructor Documentation
WrapperVectorFunctionGradient()
sgpp::base::WrapperVectorFunctionGradient::WrapperVectorFunctionGradient (size_t d, size_t m, FunctionGradientEvalType fGradient) inline
Constructor.
Parameters
d dimension of the domain
m number of components
fGradient function gradient to be wrapped
~WrapperVectorFunctionGradient()
sgpp::base::WrapperVectorFunctionGradient::~WrapperVectorFunctionGradient () inline override
Destructor.
Member Function Documentation
clone()
void sgpp::base::WrapperVectorFunctionGradient::clone (std::unique_ptr< VectorFunctionGradient > & clone) const inline override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::VectorFunctionGradient.
References clone(), sgpp::base::VectorFunctionGradient::d, fGradient, and sgpp::base::VectorFunctionGradient::m.
Referenced by clone().
eval()
void sgpp::base::WrapperVectorFunctionGradient::eval (const DataVector & x, DataVector & value, DataMatrix & gradient) inline override virtual
Parameters
[in] x evaluation point \(\vec{x} \in [0, 1]^d\)
[out] value \(g(\vec{x})\)
[out] gradient Jacobian \(\nabla g(\vec{x}) \in \mathbb{R}^{m \times d}\)
Implements sgpp::base::VectorFunctionGradient.
References fGradient.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
fGradient
FunctionGradientEvalType sgpp::base::WrapperVectorFunctionGradient::fGradient protected
function gradient to be wrapped
Referenced by clone(), and eval().
The documentation for this class was generated from the following file:
base/src/sgpp/base/function/vector/WrapperVectorFunctionGradient.hpp