SG++-Doxygen-Documentation: sgpp::datadriven::MetaLearner Class Reference
sgpp::datadriven::MetaLearner Class Reference
#include <MetaLearner.hpp>
Public Member Functions
base::DataVector & getLearnedAlpha ()
sgpp::base::Grid & getLearnedGrid ()
LearnerTiming getLearnerReferenceTiming ()
LearnerTiming getLearnerTiming ()
void learn (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &datasetFileName, bool isRegression=true)
double learnAndCompare (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &datasetFileName, size_t gridGranularity)
double learnAndCompareString (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &content, size_t gridGranularity)
void learnAndTest (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &datasetFileName, std::string &testFileName, bool isRegression=true)
void learnAndTestString (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &dataContent, std::string &testContent, bool isRegression=true)
void learnReference (std::string &fileName, bool isRegression=true)
void learnReferenceString (std::string &content, bool isRegression=true)
void learnString (sgpp::datadriven::OperationMultipleEvalConfiguration &operationConfiguration, std::string &content, bool isRegression=true)
MetaLearner ()=delete
MetaLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration solverFinalStep, sgpp::base::AdaptivityConfiguration adaptivityConfig, double lambda, bool verbose=false)
~MetaLearner ()
Constructor & Destructor Documentation
MetaLearner() [1/2]
sgpp::datadriven::MetaLearner::MetaLearner () delete
MetaLearner() [2/2]
sgpp::datadriven::MetaLearner::MetaLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration solverFinalStep, sgpp::base::AdaptivityConfiguration adaptivityConfig, double lambda, bool verbose = false)
References adaptivityConfig, and lambda.
~MetaLearner()
sgpp::datadriven::MetaLearner::~MetaLearner () inline
Member Function Documentation
getLearnedAlpha()
base::DataVector & sgpp::datadriven::MetaLearner::getLearnedAlpha ()
Referenced by main().
getLearnedGrid()
base::Grid & sgpp::datadriven::MetaLearner::getLearnedGrid ()
getLearnerReferenceTiming()
LearnerTiming sgpp::datadriven::MetaLearner::getLearnerReferenceTiming ()
getLearnerTiming()
LearnerTiming sgpp::datadriven::MetaLearner::getLearnerTiming ()
Referenced by main().
learn()
void sgpp::datadriven::MetaLearner::learn (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & datasetFileName, bool isRegression = true)
References learnString().
Referenced by main(), and main().
learnAndCompare()
double sgpp::datadriven::MetaLearner::learnAndCompare (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & datasetFileName, size_t gridGranularity)
References learnAndCompareString().
Referenced by main().
learnAndCompareString()
double sgpp::datadriven::MetaLearner::learnAndCompareString (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & content, size_t gridGranularity)
References sgpp::base::DataMatrix::appendRow(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), learnReferenceString(), and learnString().
Referenced by learnAndCompare().
learnAndTest()
void sgpp::datadriven::MetaLearner::learnAndTest (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & datasetFileName, std::string & testFileName, bool isRegression = true)
References learnAndTestString().
Referenced by main().
learnAndTestString()
void sgpp::datadriven::MetaLearner::learnAndTestString (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & dataContent, std::string & testContent, bool isRegression = true)
References sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::DataVector::get(), sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::base::DataMatrix::getNrows(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::base::DataVector::getSize(), sgpp::datadriven::Dataset::getTargets(), learnString(), sgpp::datadriven::mse, and sgpp::datadriven::ARFFTools::readARFFFromString().
Referenced by learnAndTest().
learnReference()
void sgpp::datadriven::MetaLearner::learnReference (std::string & fileName, bool isRegression = true)
References learnReferenceString().
learnReferenceString()
void sgpp::datadriven::MetaLearner::learnReferenceString (std::string & content, bool isRegression = true)
References dataset, sgpp::datadriven::DEFAULT, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::datadriven::Dataset::getTargets(), sgpp::datadriven::NONE, sgpp::datadriven::ARFFTools::readARFFFromString(), and trainingData.
Referenced by learnAndCompareString(), and learnReference().
learnString()
void sgpp::datadriven::MetaLearner::learnString (sgpp::datadriven::OperationMultipleEvalConfiguration & operationConfiguration, std::string & content, bool isRegression = true)
References dataset, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::datadriven::Dataset::getTargets(), sgpp::datadriven::ARFFTools::readARFFFromString(), and trainingData.
Referenced by learn(), learnAndCompareString(), and learnAndTestString().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/MetaLearner.hpp
datadriven/src/sgpp/datadriven/application/MetaLearner.cpp