SG++-Doxygen-Documentation: sgpp::solver::VarTimestep Class Reference
sgpp::solver::VarTimestep Class Reference
This class implements a step size control using Adams-Bashforth and Crank-Nicolson for solving ordinary partial equations.
#include <VarTimestep.hpp>
Public Member Functions
VarTimestep (std::string pred, std::string corr, size_t imax, double timestepSize, double eps, sgpp::base::ScreenOutput *screen=nullptr, double gamma=-1)
Std-Constructer.
virtual ~VarTimestep ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::StepsizeControl
void solve (SLESolver &LinearSystemSolver, sgpp::solver::OperationParabolicPDESolverSystem &System, bool bIdentifyLastStep=false, bool verbose=false)
Pure virtual Function that defines a solve method for an ODE solver.
StepsizeControl (size_t imax, double timestepSize, double eps, double sc, sgpp::base::ScreenOutput *screen=nullptr, double gamma=0.5)
Std-Constructer.
virtual ~StepsizeControl ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::ODESolver
ODESolver (size_t imax, double timestepSize)
Std-Constructor.
virtual ~ODESolver ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolver
double getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
double getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (double eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolver (size_t nMaximumIterations, double epsilon)
Std-Constructor.
virtual ~SGSolver ()
Std-Destructor.
Protected Member Functions
void corrector (SLESolver &LinearSystemSolver, sgpp::solver::OperationParabolicPDESolverSystem &System, double tmp_timestepsize, sgpp::base::DataVector &dv, sgpp::base::DataVector *rhs)
virtual double nextTimestep (double tmp_timestepsize, double tmp_timestepsize_old, double norm, double epsilon)
void predictor (SLESolver &LinearSystemSolver, sgpp::solver::OperationParabolicPDESolverSystem &System, double tmp_timestepsize, sgpp::base::DataVector &dv, sgpp::base::DataVector &corr, sgpp::base::DataVector *rhs)
Protected Member Functions inherited from sgpp::solver::StepsizeControl
double maxNorm (sgpp::solver::OperationParabolicPDESolverSystem &System, sgpp::base::DataVector &dv1, sgpp::base::DataVector &dv2)
virtual double norm (sgpp::solver::OperationParabolicPDESolverSystem &System, sgpp::base::DataVector &dv1, sgpp::base::DataVector &dv2)
double twoNorm (sgpp::solver::OperationParabolicPDESolverSystem &System, sgpp::base::DataVector &dv1, sgpp::base::DataVector &dv2)
Protected Attributes
std::string _corrector
std::string _predictor
Protected Attributes inherited from sgpp::solver::StepsizeControl
double _gamma
damping factor
std::string filename
double myEps
epsilon for the step size control
double mySC
temp. Stepsize Control
sgpp::base::ScreenOutput * myScreen
Pointer to sgpp::base::ScreenOutput object.
Protected Attributes inherited from sgpp::solver::SGSolver
double myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
double residuum
residuum
Detailed Description
This class implements a step size control using Adams-Bashforth and Crank-Nicolson for solving ordinary partial equations.
Constructor & Destructor Documentation
VarTimestep()
sgpp::solver::VarTimestep::VarTimestep (std::string pred, std::string corr, size_t imax, double timestepSize, double eps, sgpp::base::ScreenOutput * screen = nullptr, double gamma = -1)
Std-Constructer.
Parameters
pred used predictor
corr used corrector
imax number of maximum executed iterations
timestepSize the size of one timestep
eps the epsilon for the step size control
screen possible pointer to a sgpp::base::ScreenOutput object
gamma damping factor
References sgpp::solver::StepsizeControl::filename.
~VarTimestep()
sgpp::solver::VarTimestep::~VarTimestep () virtual
Std-Destructor.
Member Function Documentation
corrector()
void sgpp::solver::VarTimestep::corrector (SLESolver & LinearSystemSolver, sgpp::solver::OperationParabolicPDESolverSystem & System, double tmp_timestepsize, sgpp::base::DataVector & dv, sgpp::base::DataVector * rhs) protected virtual
Implements sgpp::solver::StepsizeControl.
References sgpp::solver::OperationParabolicPDESolverSystem::finishTimestep(), sgpp::solver::OperationParabolicPDESolverSystem::generateRHS(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForCG(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForSC(), sgpp::solver::OperationParabolicPDESolverSystem::setODESolver(), and sgpp::solver::SLESolver::solve().
nextTimestep()
double sgpp::solver::VarTimestep::nextTimestep (double tmp_timestepsize, double tmp_timestepsize_old, double norm, double epsilon) protected virtual
Implements sgpp::solver::StepsizeControl.
Reimplemented in sgpp::solver::StepsizeControlBDF, and sgpp::solver::StepsizeControlMC.
predictor()
void sgpp::solver::VarTimestep::predictor (SLESolver & LinearSystemSolver, sgpp::solver::OperationParabolicPDESolverSystem & System, double tmp_timestepsize, sgpp::base::DataVector & dv, sgpp::base::DataVector & corr, sgpp::base::DataVector * rhs) protected virtual
Implements sgpp::solver::StepsizeControl.
References sgpp::solver::OperationParabolicPDESolverSystem::abortTimestep(), sgpp::solver::OperationParabolicPDESolverSystem::finishTimestep(), sgpp::solver::OperationParabolicPDESolverSystem::generateRHS(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficients(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForCG(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForSC(), sgpp::base::DataVector::getSize(), sgpp::solver::OperationParabolicPDESolverSystem::setODESolver(), sgpp::solver::OperationParabolicPDESolverSystem::setTimestepSize(), and sgpp::solver::SLESolver::solve().
Member Data Documentation
_corrector
std::string sgpp::solver::VarTimestep::_corrector protected
_predictor
std::string sgpp::solver::VarTimestep::_predictor protected
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/ode/VarTimestep.hpp
solver/src/sgpp/solver/ode/VarTimestep.cpp