SG++-Doxygen-Documentation: sgpp::datadriven::OperationDotProductLinear Class Reference
sgpp::datadriven::OperationDotProductLinear Class Reference
#include <OperationDotProductLinear.hpp>
Public Member Functions
virtual double eval (sgpp::base::DataVector &x1, sgpp::base::DataVector &x2)
OperationDotProductLinear (sgpp::base::GridStorage *storage)
Constructor of OperationTestLinear.
virtual ~OperationDotProductLinear ()
Destructor.
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to the grid's GridStorage object.
Constructor & Destructor Documentation
OperationDotProductLinear()
sgpp::datadriven::OperationDotProductLinear::OperationDotProductLinear (sgpp::base::GridStorage * storage) inline explicit
Constructor of OperationTestLinear.
Parameters
storage Pointer to the grid's gridstorage obejct
~OperationDotProductLinear()
virtual sgpp::datadriven::OperationDotProductLinear::~OperationDotProductLinear () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::datadriven::OperationDotProductLinear::eval (sgpp::base::DataVector & x1, sgpp::base::DataVector & x2) virtual
References sgpp::base::LinearBasis< LT, IT >::eval(), sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), and storage.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::datadriven::OperationDotProductLinear::storage protected
Pointer to the grid's GridStorage object.
Referenced by eval().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDotProductLinear.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDotProductLinear.cpp