SG++-Doxygen-Documentation: sgpp::datadriven::OperationTestLinearStretched Class Reference
sgpp::datadriven::OperationTestLinearStretched Class Reference
This class implements OperationTest for a grids with linearstretched basis ansatzfunctions without boundaries.
#include <OperationTestLinearStretched.hpp>
Public Member Functions
virtual void calculateROCcurve (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &classes, sgpp::base::DataVector &thresholds, sgpp::base::DataMatrix &ROC_curve)
Computes the classification accuracy on some test data.
OperationTestLinearStretched (sgpp::base::GridStorage *storage)
Constructor of OperationTestLinearStretched.
virtual double test (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &classes)
Computes the classification accuracy on some test data.
virtual double testMSE (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &refValues)
Computes the regression accuracy on some test data.
virtual double testWithCharacteristicNumber (sgpp::base::DataVector &alpha, sgpp::base::DataMatrix &data, sgpp::base::DataVector &classes, sgpp::base::DataVector &charaNumbers)
Computes the classification accuracy on some test data.
virtual ~OperationTestLinearStretched ()
Destructor.
Public Member Functions inherited from sgpp::datadriven::OperationTest
OperationTest ()
Constructor.
virtual ~OperationTest ()
Destructor.
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to the grid's GridStorage object.
Detailed Description
This class implements OperationTest for a grids with linearstretched basis ansatzfunctions without boundaries.
Constructor & Destructor Documentation
OperationTestLinearStretched()
sgpp::datadriven::OperationTestLinearStretched::OperationTestLinearStretched (sgpp::base::GridStorage * storage) inline explicit
Constructor of OperationTestLinearStretched.
Parameters
storage Pointer to the grid's gridstorage obejct
~OperationTestLinearStretched()
virtual sgpp::datadriven::OperationTestLinearStretched::~OperationTestLinearStretched () inline virtual
Destructor.
Member Function Documentation
calculateROCcurve()
void sgpp::datadriven::OperationTestLinearStretched::calculateROCcurve (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & classes, sgpp::base::DataVector & thresholds, sgpp::base::DataMatrix & ROC_curve) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off variable at threshold
Also the number of the TP TN FP FN are determined
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector the holds the class information
thresholds the thresholds (between -1.0 and 1.0) for calculating the ROC curve
ROC_curve DataMatrix into which the ROC curve is stored
Implements sgpp::datadriven::OperationTest.
References alpha, storage, and sgpp::datadriven::test_calculateROCcurve().
test()
double sgpp::datadriven::OperationTestLinearStretched::test (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & classes) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off at 0.
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector holding the class information
Implements sgpp::datadriven::OperationTest.
References alpha, storage, and sgpp::datadriven::test_dataset().
testMSE()
double sgpp::datadriven::OperationTestLinearStretched::testMSE (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & refValues) virtual
Computes the regression accuracy on some test data.
The function is evaluated at the given points. Calculates the MSE between between the given values and the values evaluated on the sparse grid.
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
refValues sgpp::base::DataVector holding the reference function values
Implements sgpp::datadriven::OperationTest.
References alpha, storage, and sgpp::datadriven::test_dataset_mse().
Referenced by python.uq.manager.ASGCStatistics.ASGCStatistics::updateResults().
testWithCharacteristicNumber()
double sgpp::datadriven::OperationTestLinearStretched::testWithCharacteristicNumber (sgpp::base::DataVector & alpha, sgpp::base::DataMatrix & data, sgpp::base::DataVector & classes, sgpp::base::DataVector & charaNumbers) virtual
Computes the classification accuracy on some test data.
The function is evaluated at the given points. Tests on the classes {+1, -1}, cut-off at 0.
Also the number of the TP TN FP FN are determined
Parameters
alpha the coefficients of the sparse grid's base functions
data the coordinates of the evaluation points
classes sgpp::base::DataVector the holds the class information
charaNumbers the number of true positives, true negatives, false positives, false negatives (Vector of length 4)
Implements sgpp::datadriven::OperationTest.
References alpha, storage, and sgpp::datadriven::test_datasetWithCharacteristicNumber().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::datadriven::OperationTestLinearStretched::storage protected
Pointer to the grid's GridStorage object.
Referenced by calculateROCcurve(), test(), testMSE(), and testWithCharacteristicNumber().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationTestLinearStretched.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationTestLinearStretched.cpp