SG++-Doxygen-Documentation: sgpp::base::OperationFirstMomentLinearBoundary Class Reference
sgpp::base::OperationFirstMomentLinearBoundary Class Reference
FirstMomemnt of sparse grid function, linear grid without boundaries.
#include <OperationFirstMomentLinearBoundary.hpp>
Public Member Functions
double doQuadrature (const DataVector &alpha, DataMatrix *bounds=nullptr) override
Compute first moment of the function.
OperationFirstMomentLinearBoundary (GridStorage &storage)
Constructor of OperationFirstMomentLinearBoundary.
~OperationFirstMomentLinearBoundary () override
Public Member Functions inherited from sgpp::base::OperationFirstMoment
OperationFirstMoment ()
Constructor.
virtual ~OperationFirstMoment ()
Destructor.
Protected Attributes
GridStorage & storage
Detailed Description
FirstMomemnt of sparse grid function, linear grid without boundaries.
Constructor & Destructor Documentation
OperationFirstMomentLinearBoundary()
sgpp::base::OperationFirstMomentLinearBoundary::OperationFirstMomentLinearBoundary (GridStorage & storage) inline explicit
Constructor of OperationFirstMomentLinearBoundary.
Parameters
storage Pointer to the grid's GridStorage object
~OperationFirstMomentLinearBoundary()
sgpp::base::OperationFirstMomentLinearBoundary::~OperationFirstMomentLinearBoundary () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature (const DataVector & alpha, DataMatrix * bounds = nullptr) override virtual
Compute first moment of the function.
\[ \int_{\Omega} x\cdot f(x) dx. \]
Parameters
alpha Coefficient vector for current grid
bounds describes the boundaries of the hypercube of the original function
Implements sgpp::base::OperationFirstMoment.
References alpha, sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), level, and storage.
Member Data Documentation
storage
GridStorage& sgpp::base::OperationFirstMomentLinearBoundary::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationFirstMomentLinearBoundary.hpp
base/src/sgpp/base/operation/hash/OperationFirstMomentLinearBoundary.cpp