SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::MPIEnviroment Class Reference
sgpp::datadriven::clusteringmpi::MPIEnviroment Class Reference
#include <MPIEnviroment.hpp>
Public Member Functions
~MPIEnviroment ()
Static Public Member Functions
static void connect_nodes (base::OperationConfiguration conf)
static base::OperationConfiguration createMPIConfiguration (int compute_nodes, base::OCLOperationConfiguration node_opencl_configuration)
Create MPI configuration file based on a number of compute nodes their OpenCL configuration file.
static base::OperationConfiguration createMPIConfiguration (int compute_nodes, int opencl_devices_per_compute_node)
static base::OperationConfiguration createMPIConfiguration (int packagesize_master, int leutnant_nodes, int packagesize_leutnants, int slave_nodes_per_leutnant)
static MPI_Comm & get_communicator (void)
static base::OperationConfiguration & get_configuration (void)
static MPI_Comm & get_input_communicator (void)
static int get_node_count (void)
static int get_node_rank (void)
static int get_sub_worker_count (void)
static void init (int argc, char *argv[], bool verbose=false)
static void release (void)
Constructor & Destructor Documentation
~MPIEnviroment()
sgpp::datadriven::clusteringmpi::MPIEnviroment::~MPIEnviroment (void)
Member Function Documentation
connect_nodes()
void sgpp::datadriven::clusteringmpi::MPIEnviroment::connect_nodes (base::OperationConfiguration conf) static
References get_node_count().
createMPIConfiguration() [1/3]
base::OperationConfiguration sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration (int compute_nodes, base::OCLOperationConfiguration node_opencl_configuration) static
Create MPI configuration file based on a number of compute nodes their OpenCL configuration file.
Creates a MPI configuration with 3 Levels. One master node to control all other nodes, and one leutenant node on every compute node which controls all MPI nodes for this compute nodes. For each OpenCL device specified in the opencl configuration it will also create one worker. Duplicate devices will not be recognized hoewever.
Parameters
compute_nodes Number of compute nodes
node_opencl_configuration OpenCL configuration file
Returns
Finished MPI configuration
References json::DictNode::addAttribute(), json::DictNode::addIDAttr(), json::Node::keys(), and json::DictNode::keys().
createMPIConfiguration() [2/3]
base::OperationConfiguration sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration (int compute_nodes, int opencl_devices_per_compute_node) static
References json::DictNode::addAttribute(), and json::DictNode::addIDAttr().
createMPIConfiguration() [3/3]
base::OperationConfiguration sgpp::datadriven::clusteringmpi::MPIEnviroment::createMPIConfiguration (int packagesize_master, int leutnant_nodes, int packagesize_leutnants, int slave_nodes_per_leutnant) static
References json::DictNode::addAttribute(), and json::DictNode::addIDAttr().
get_communicator()
static MPI_Comm & sgpp::datadriven::clusteringmpi::MPIEnviroment::get_communicator (void) inline static
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::release_sub_workers(), and sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_sub_workers().
get_configuration()
static base::OperationConfiguration & sgpp::datadriven::clusteringmpi::MPIEnviroment::get_configuration (void) inline static
Referenced by sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
get_input_communicator()
static MPI_Comm & sgpp::datadriven::clusteringmpi::MPIEnviroment::get_input_communicator (void) inline static
get_node_count()
int sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_count (void) static
Referenced by connect_nodes().
get_node_rank()
int sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank (void) static
Referenced by sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::MPIWorkerGraphBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::DensityWorker::receive_and_send_initial_data(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::start_worker_main(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main(), and sgpp::datadriven::clusteringmpi::WorkerDummy::WorkerDummy().
get_sub_worker_count()
static int sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count (void) inline static
Referenced by sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::create_graph(), sgpp::datadriven::clusteringmpi::OperationPrunedGraphCreationMPI::create_graph(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::OperationDensityRhsMPI::generate_b(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::GraphCreationWorker(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::MPIWorkerBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::PrunedGraphCreationWorker(), sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::PrunedGraphCreationWorker(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::release_sub_workers(), sgpp::datadriven::clusteringmpi::DensityWorker::send_alpha(), sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_sub_workers(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::start_worker_main(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
init()
void sgpp::datadriven::clusteringmpi::MPIEnviroment::init (int argc, char * argv[], bool verbose = false) static
release()
void sgpp::datadriven::clusteringmpi::MPIEnviroment::release (void) static
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/MPIEnviroment.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/MPIEnviroment.cpp