SG++-Doxygen-Documentation: sgpp::datadriven::ZeroCrossingRefinementFunctor Class Reference
sgpp::datadriven::ZeroCrossingRefinementFunctor Class Reference
Zero-crossing-based refinement uses zero crossings of the difference PDFS f_1 - f_2 to determine areas of interest for the refinement process.
#include <ZeroCrossingRefinementFunctor.hpp>
Public Member Functions
size_t getNumGrids () override
Returns the number of grids the functor can / does refine.
size_t getRefinementsNum () const override
Returns the maximal number of points that should be refined.
double getRefinementThreshold () const override
Returns the threshold for refinement.
double operator() (base::GridStorage &storage, size_t seq) const override
This should be returning a refinement value for every grid point.
void preComputeEvaluations () override
Precomputes grid evaluations for all grids.
void setGridIndex (size_t grid_index) override
Sets the index (into the vector of grids) of the grid to be refined.
double start () const override
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
ZeroCrossingRefinementFunctor (std::vector< base::Grid * > grids, std::vector< base::DataVector * > alphas, std::vector< double > priors, size_t refinements_num=1, bool level_penalize=false, bool pre_compute=false, double threshold=0.0)
Constructor.
~ZeroCrossingRefinementFunctor () override
Public Member Functions inherited from sgpp::datadriven::MultiGridRefinementFunctor
virtual ~MultiGridRefinementFunctor ()
Public Member Functions inherited from sgpp::base::RefinementFunctor
virtual double getTotalRefinementValue (GridStorage &storage) const
Returns the total sum of local (error) indicators used for refinement.
RefinementFunctor ()
Constructor.
virtual ~RefinementFunctor ()
Destructor.
Protected Member Functions
void getChild (const base::HashGridPoint &gp, size_t d, bool left, base::HashGridPoint &child) const
std::vector< double > getEvalVector (size_t ind, size_t seq) const
Gets the evaluations of all grids at the coords of seq.
void getParent (const base::HashGridPoint &gp, size_t d, base::HashGridPoint &par) const
void goDown (base::HashGridPoint &gp, base::HashGridPoint &down, size_t d, bool left) const
Used for non-leaf grid points.
void goUp (base::HashGridPoint &gp, base::HashGridPoint &up, size_t d, bool left) const
Used for leaf grid points.
bool hasChild (const base::HashGridPoint &gp, size_t d, bool left) const
bool isLeftChild (const base::HashGridPoint &gp, size_t d) const
int sgn (double d) const
Protected Attributes
std::vector< base::DataVector * > alphas
size_t current_grid_index
std::vector< base::Grid * > grids
bool level_penalize
std::vector< std::map< std::string, double > > pre_comp_evals
Stores grid evaluations at all grids (vector) at the union of grid point coordinates over all grids (hashed by string representation in the map)
bool pre_compute
std::vector< double > priors
size_t refinements_num
double threshold
Additional Inherited Members
Public Types inherited from sgpp::base::RefinementFunctor
typedef double value_type
Detailed Description
Zero-crossing-based refinement uses zero crossings of the difference PDFS f_1 - f_2 to determine areas of interest for the refinement process.
The signs of a grid point pair evaluated at two PDFs are compared and only if the signs differ (a zero crossing lies between them) are they considered for the scoring.
The pairs of grid points are geometric neighbors, determined for each dimension separately.
Constructor & Destructor Documentation
ZeroCrossingRefinementFunctor()
sgpp::datadriven::ZeroCrossingRefinementFunctor::ZeroCrossingRefinementFunctor (std::vector< base::Grid * > grids, std::vector< base::DataVector * > alphas, std::vector< double > priors, size_t refinements_num = 1, bool level_penalize = false, bool pre_compute = false, double threshold = 0.0)
Constructor.
Parameters
grids Vector of grids. current_grid_index specifies the grid to be refined
alphas Vector of surpluses related to the grids
priors Vector of priors related to the classificator
refinements_num Maximum number of refinements done
level_penalize If a level penalizing is multiplied to the score (2^{|l|_1})
pre_compute Flag for precomputation of necessary grid evals. If true preComputeEvaluations needs to be called before each refinement step
threshold Threshold for refinement scores
References grids, and pre_comp_evals.
~ZeroCrossingRefinementFunctor()
sgpp::datadriven::ZeroCrossingRefinementFunctor::~ZeroCrossingRefinementFunctor () inline override
Member Function Documentation
getChild()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::getChild (const base::HashGridPoint & gp, size_t d, bool left, base::HashGridPoint & child) const protected
Parameters
gp the grid point we want the child from
child gets set to the left/right child in dim d of gp
left specifies if left or right child is returned
d specifies the dimension of the child. All other dims are kept constant
References sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), and sgpp::base::HashGridPoint::set().
Referenced by goDown(), and operator()().
getEvalVector()
std::vector< double > sgpp::datadriven::ZeroCrossingRefinementFunctor::getEvalVector (size_t ind, size_t seq) const protected
Gets the evaluations of all grids at the coords of seq.
References alphas, sgpp::op_factory::createOperationEval(), sgpp::base::HashGridPoint::getStandardCoordinates(), grids, pre_comp_evals, pre_compute, priors, and sgpp::base::DataVector::toString().
Referenced by operator()().
getNumGrids()
size_t sgpp::datadriven::ZeroCrossingRefinementFunctor::getNumGrids () override virtual
Returns the number of grids the functor can / does refine.
Implements sgpp::datadriven::MultiGridRefinementFunctor.
References grids.
getParent()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::getParent (const base::HashGridPoint & gp, size_t d, base::HashGridPoint & par) const protected
Parameters
gp the grid point we want the parent from
par gets set to the parent in dim d of gp
d specifies the dimension of the child. All other dims are kept constant
References sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), and sgpp::base::HashGridPoint::set().
Referenced by goUp().
getRefinementsNum()
size_t sgpp::datadriven::ZeroCrossingRefinementFunctor::getRefinementsNum () const override virtual
Returns the maximal number of points that should be refined.
The maximal number of points to refine is set in the constructor of the implementing class.
Returns
number of points that should refined. Default value: 1.
Reimplemented from sgpp::base::RefinementFunctor.
References refinements_num.
getRefinementThreshold()
double sgpp::datadriven::ZeroCrossingRefinementFunctor::getRefinementThreshold () const override virtual
Returns the threshold for refinement.
Only the grid points with absolute value of refinement criterion (e.g., alpha or error) greater or equal to this threshold will be refined.
Returns
threshold value for refinement. Default value: 0.
Implements sgpp::base::RefinementFunctor.
References threshold.
goDown()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::goDown (base::HashGridPoint & gp, base::HashGridPoint & down, size_t d, bool left) const protected
Used for non-leaf grid points.
Decends the tree in dir left until a leaf is reached. Modifies both gp and down. Result in down.
References getChild(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), goDown(), hasChild(), and sgpp::base::HashGridPoint::set().
Referenced by goDown(), and operator()().
goUp()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::goUp (base::HashGridPoint & gp, base::HashGridPoint & up, size_t d, bool left) const protected
Used for leaf grid points.
Goes up the tree in dir left until the current grid point is not left/right child of the parent grid point. Modifies both gp and up. Result in up.
References getParent(), goUp(), and isLeftChild().
Referenced by goUp(), and operator()().
hasChild()
bool sgpp::datadriven::ZeroCrossingRefinementFunctor::hasChild (const base::HashGridPoint & gp, size_t d, bool left) const protected
References current_grid_index, grids, sgpp::base::HashGridIterator::hintLeft(), sgpp::base::HashGridIterator::hintRight(), and sgpp::base::HashGridIterator::set().
Referenced by goDown(), and operator()().
isLeftChild()
bool sgpp::datadriven::ZeroCrossingRefinementFunctor::isLeftChild (const base::HashGridPoint & gp, size_t d) const protected
References sgpp::base::HashGridPoint::getIndex().
Referenced by goUp().
operator()()
double sgpp::datadriven::ZeroCrossingRefinementFunctor::operator() (base::GridStorage & storage, size_t seq) const override virtual
This should be returning a refinement value for every grid point.
The point with the highest value will be refined first.
Parameters
storage reference to the grids storage object
seq sequence number in the coefficients array
Returns
refinement value
Implements sgpp::base::RefinementFunctor.
References current_grid_index, getChild(), sgpp::base::HashGridStorage::getDimension(), getEvalVector(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridPoint::getLevelSum(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSequenceNumber(), goDown(), goUp(), grids, hasChild(), level_penalize, and sgn().
preComputeEvaluations()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::preComputeEvaluations () override virtual
Precomputes grid evaluations for all grids.
Used in combination with pre_compute flag = true. Should be called before refinement is done and needs to be re-called after a refinement step is over ie. the surplus vectors got recomputed
Reimplemented from sgpp::datadriven::MultiGridRefinementFunctor.
References alphas, sgpp::op_factory::createOperationEval(), grids, pre_comp_evals, and priors.
setGridIndex()
void sgpp::datadriven::ZeroCrossingRefinementFunctor::setGridIndex (size_t grid_index) override virtual
Sets the index (into the vector of grids) of the grid to be refined.
Parameters
grid_index The index of the grid to be refined
Implements sgpp::datadriven::MultiGridRefinementFunctor.
References current_grid_index.
Referenced by sgpp::datadriven::MultipleClassRefinementFunctor::refine().
sgn()
int sgpp::datadriven::ZeroCrossingRefinementFunctor::sgn (double d) const protected
Referenced by operator()().
start()
double sgpp::datadriven::ZeroCrossingRefinementFunctor::start () const override virtual
Returns the lower bound of refinement criterion (e.g., alpha or error) (lower bound).
The refinement value of grid points to be refined have to be larger than this value
Returns
lower bound
Implements sgpp::base::RefinementFunctor.
Member Data Documentation
alphas
std::vector<base::DataVector*> sgpp::datadriven::ZeroCrossingRefinementFunctor::alphas protected
Referenced by getEvalVector(), and preComputeEvaluations().
current_grid_index
size_t sgpp::datadriven::ZeroCrossingRefinementFunctor::current_grid_index protected
Referenced by hasChild(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), operator()(), and setGridIndex().
grids
std::vector<base::Grid*> sgpp::datadriven::ZeroCrossingRefinementFunctor::grids protected
Referenced by getEvalVector(), getNumGrids(), hasChild(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), operator()(), preComputeEvaluations(), sgpp::datadriven::MultipleClassRefinementFunctor::refine(), and ZeroCrossingRefinementFunctor().
level_penalize
bool sgpp::datadriven::ZeroCrossingRefinementFunctor::level_penalize protected
Referenced by operator()().
pre_comp_evals
std::vector<std::map<std::string, double> > sgpp::datadriven::ZeroCrossingRefinementFunctor::pre_comp_evals protected
Stores grid evaluations at all grids (vector) at the union of grid point coordinates over all grids (hashed by string representation in the map)
Referenced by getEvalVector(), preComputeEvaluations(), and ZeroCrossingRefinementFunctor().
pre_compute
bool sgpp::datadriven::ZeroCrossingRefinementFunctor::pre_compute protected
Referenced by getEvalVector().
priors
std::vector<double> sgpp::datadriven::ZeroCrossingRefinementFunctor::priors protected
Referenced by getEvalVector(), and preComputeEvaluations().
refinements_num
size_t sgpp::datadriven::ZeroCrossingRefinementFunctor::refinements_num protected
Referenced by getRefinementsNum(), and sgpp::datadriven::MultipleClassRefinementFunctor::refine().
threshold
double sgpp::datadriven::ZeroCrossingRefinementFunctor::threshold protected
Referenced by getRefinementThreshold().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/functors/classification/ZeroCrossingRefinementFunctor.hpp
datadriven/src/sgpp/datadriven/functors/classification/ZeroCrossingRefinementFunctor.cpp