SG++-Doxygen-Documentation: sgpp::base::PrecisionConverter Class Reference
sgpp::base::PrecisionConverter Class Reference
Copies data from DataVector objects into DataVectorSP objects and vice versa.
#include <PrecisionConverter.hpp>
Static Public Member Functions
static void convertDataMatrixSPToDataMatrix (const sgpp::base::DataMatrixSP &src, sgpp::base::DataMatrix &dest)
Copies data from DataMatrixSP object into DataMatrix object.
static void convertDataMatrixToDataMatrixSP (const sgpp::base::DataMatrix &src, sgpp::base::DataMatrixSP &dest)
Copies data from DataMatrix object into DataMatrixSP object.
static void convertDataVectorSPToDataVector (const sgpp::base::DataVectorSP &src, sgpp::base::DataVector &dest)
Copies data from DataVectorSP object into DataVector object.
static void convertDataVectorToDataVectorSP (const sgpp::base::DataVector &src, sgpp::base::DataVectorSP &dest)
Copies data from DataVector object into DataVectorSP object.
Detailed Description
Copies data from DataVector objects into DataVectorSP objects and vice versa.
Copies data from DataMatrix objects into DataMatrixSP objects and vice versa.
Member Function Documentation
convertDataMatrixSPToDataMatrix()
void sgpp::base::PrecisionConverter::convertDataMatrixSPToDataMatrix (const sgpp::base::DataMatrixSP & src, sgpp::base::DataMatrix & dest) static
Copies data from DataMatrixSP object into DataMatrix object.
Parameters
src source DataMatrixSP, single precision
dest destination DataMatrix, double precision
References sgpp::base::DataMatrixSP::get(), sgpp::base::DataMatrixSP::getNcols(), and sgpp::base::DataMatrixSP::getNrows().
Referenced by sgpp::datadriven::LearnerBaseSP::predict().
convertDataMatrixToDataMatrixSP()
void sgpp::base::PrecisionConverter::convertDataMatrixToDataMatrixSP (const sgpp::base::DataMatrix & src, sgpp::base::DataMatrixSP & dest) static
Copies data from DataMatrix object into DataMatrixSP object.
Parameters
src source DataMatrix, double precision
dest destination DataMatrixSP, single precision
References sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), and sgpp::base::DataMatrix::getNrows().
convertDataVectorSPToDataVector()
void sgpp::base::PrecisionConverter::convertDataVectorSPToDataVector (const sgpp::base::DataVectorSP & src, sgpp::base::DataVector & dest) static
Copies data from DataVectorSP object into DataVector object.
Parameters
src source DataVectorSP, single precision
dest destination DataVector, double precision
References sgpp::base::DataVectorSP::get(), and sgpp::base::DataVectorSP::getSize().
Referenced by sgpp::datadriven::LearnerBaseSP::dumpFunction(), sgpp::datadriven::LearnerBaseSP::dumpGrid(), sgpp::datadriven::LearnerBaseSP::predict(), and sgpp::datadriven::LearnerBaseSP::train().
convertDataVectorToDataVectorSP()
void sgpp::base::PrecisionConverter::convertDataVectorToDataVectorSP (const sgpp::base::DataVector & src, sgpp::base::DataVectorSP & dest) static
Copies data from DataVector object into DataVectorSP object.
Parameters
src source DataVector, double precision
dest destination DataVectorSP, single precision
References sgpp::base::DataVector::get(), and sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::LearnerBaseSP::predict().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/PrecisionConverter.hpp
base/src/sgpp/base/tools/PrecisionConverter.cpp