SG++-Doxygen-Documentation: sgpp::pde::PhiPhiUpModLinear Class Reference
sgpp::pde::PhiPhiUpModLinear Class Reference
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on mod-linear grids.
#include <PhiPhiUpModLinear.hpp>
Public Member Functions
void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of up in the direction of dimension dim
PhiPhiUpModLinear (sgpp::base::GridStorage *storage)
Constructor.
~PhiPhiUpModLinear ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double &fl, double &fr)
recursive function for the calculation of Up
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage object.
Detailed Description
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on mod-linear grids.
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::PhiPhiUpModLinear::grid_iterator protected
Constructor & Destructor Documentation
PhiPhiUpModLinear()
sgpp::pde::PhiPhiUpModLinear::PhiPhiUpModLinear (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiUpModLinear()
sgpp::pde::PhiPhiUpModLinear::~PhiPhiUpModLinear ()
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiUpModLinear::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim)
This operations performs the calculation of up in the direction of dimension dim
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the up operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
References rec().
rec()
void sgpp::pde::PhiPhiUpModLinear::rec (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim, double & fl, double & fr) protected
recursive function for the calculation of Up
Parameters
source sgpp::base::DataVector that contains the coefficients of the ansatzfunction
result sgpp::base::DataVector in which the result of the operation is stored
index reference to a griditerator object that is used navigate through the grid
dim the dimension in which the operation is executed
fl function value on the left boundary
fr function value on the right boundary
References sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), and rec().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::pde::PhiPhiUpModLinear::storage protected
Pointer to the sgpp::base::GridStorage object.
Referenced by rec().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/modlinear/algorithm_sweep/PhiPhiUpModLinear.hpp
pde/src/sgpp/pde/basis/modlinear/algorithm_sweep/PhiPhiUpModLinear.cpp