SG++-Doxygen-Documentation: sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive Class Reference
sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive Class Reference
Operation for evaluating B-spline linear combinations on Clenshaw-Curtis grids, their gradients and their Hessians.
#include <OperationEvalHessianBsplineClenshawCurtisNaive.hpp>
Public Member Functions
void evalHessian (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient, std::vector< DataMatrix > &hessian) override
double evalHessian (const DataVector &alpha, const DataVector &point, DataVector &gradient, DataMatrix &hessian) override
OperationEvalHessianBsplineClenshawCurtisNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalHessianBsplineClenshawCurtisNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalHessian
OperationEvalHessian ()
Constructor.
virtual ~OperationEvalHessian ()
Destructor.
Protected Attributes
SBsplineClenshawCurtisBase base
1D B-spline basis
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalHessian
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating B-spline linear combinations on Clenshaw-Curtis grids, their gradients and their Hessians.
Constructor & Destructor Documentation
OperationEvalHessianBsplineClenshawCurtisNaive()
sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::OperationEvalHessianBsplineClenshawCurtisNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalHessianBsplineClenshawCurtisNaive()
sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::~OperationEvalHessianBsplineClenshawCurtisNaive () inline override
Destructor.
Member Function Documentation
evalHessian() [1/2]
void sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient, std::vector< DataMatrix > & hessian) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
[out] hessian vector of Hessians of the linear combination
Reimplemented from sgpp::base::OperationEvalHessian.
References alpha, base, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalHessian() [2/2]
double sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian (const DataVector & alpha, const DataVector & point, DataVector & gradient, DataMatrix & hessian) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient vector of the linear combination
[out] hessian Hessian matrix of the linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalHessian.
References sgpp::base::DataMatrix::add(), sgpp::base::DataVector::add(), alpha, base, sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::BsplineClenshawCurtisBasis< LT, IT >::evalDxDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SBsplineClenshawCurtisBase sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::base protected
1D B-spline basis
Referenced by evalHessian(), and evalHessian().
innerDerivative
DataVector sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalHessian(), and evalHessian().
pointInUnitCube
DataVector sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalHessian(), and evalHessian().
storage
GridStorage& sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::storage protected
storage of the sparse grid
Referenced by evalHessian(), and evalHessian().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalHessianBsplineClenshawCurtisNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalHessianBsplineClenshawCurtisNaive.cpp