SG++-Doxygen-Documentation: sgpp::base::PrewaveletGridGenerator Class Reference
sgpp::base::PrewaveletGridGenerator Class Reference
GridGenerator for prewavelet grids without boundaries.
#include <PrewaveletGridGenerator.hpp>
Public Member Functions
void cliques (size_t level, size_t clique_size) override
Creates a sparse grid with fully connected cliques.
void cliques (size_t level, size_t clique_size, double T) override
Creates a sparse grid with fully connected cliques.
void coarsen (CoarseningFunctor &func, std::vector< size_t > *removedSeq) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void coarsenNFirstOnly (CoarseningFunctor &func, size_t numFirstOnly, std::vector< size_t > *removedSeq, size_t minIndexConsidered) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void full (size_t level) override
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
size_t getNumberOfRefinablePoints () override
Returns the number of points on the grid that can be refined in the next iteration.
size_t getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
size_t getNumberOfRemovablePoints () override
Returns the number of points on the grid that can be removed in the next iteration.
PrewaveletGridGenerator (GridStorage &storage, GridStorage &shadowstorage)
Constructor An adaptive grid with prewavelet ansatz functions requires for operations using the up-down algorithm shadow points.
void refine (RefinementFunctor &func, std::vector< size_t > *addedPoints=nullptr) override
Refines the grid and updates the shadow storage.
void refineMaxLevel (RefinementFunctor &func, size_t maxLevel) override
Refines a grid according to the settings of the RefinementFunctor func.
void regular (size_t level) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
void regular (size_t level, double T) override
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
~PrewaveletGridGenerator () override
Destructor.
Public Member Functions inherited from sgpp::base::GridGenerator
virtual void anisotropicFull (std::vector< size_t > dimlevels)
Creates an anisotropicFull Grid for certain level vector, for example [2,3,1] results in a 3x7x1 grid.
GridGenerator ()
Constructor.
virtual void refineInter (RefinementFunctor &func, const std::set< std::set< size_t > > &interactions)
Refines a grid according to the settings of the RefinementFunctor func.
virtual void regularInter (size_t level, const std::set< std::set< size_t > > &terms, double T)
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
virtual void truncated (size_t level, size_t l_user)
Creates a grid which doesn't contain the fullgrids with li<l_user, for any li level_t.
virtual ~GridGenerator ()
Destructor.
Protected Types
typedef index_type::index_type index_t
typedef GridStorage::point_type index_type
typedef index_type::level_type level_t
Protected Attributes
GridStorage & shadowstorage
GridStorage & storage
reference to the storage object
Detailed Description
GridGenerator for prewavelet grids without boundaries.
Member Typedef Documentation
index_t
typedef index_type::index_type sgpp::base::PrewaveletGridGenerator::index_t protected
index_type
typedef GridStorage::point_type sgpp::base::PrewaveletGridGenerator::index_type protected
level_t
typedef index_type::level_type sgpp::base::PrewaveletGridGenerator::level_t protected
Constructor & Destructor Documentation
PrewaveletGridGenerator()
sgpp::base::PrewaveletGridGenerator::PrewaveletGridGenerator (GridStorage & storage, GridStorage & shadowstorage)
Constructor An adaptive grid with prewavelet ansatz functions requires for operations using the up-down algorithm shadow points.
These shadow points a needed just for data transport, thus they do not have an influence on the final function. Please refer to sgpp::pde::UpDownOneOpDimWithShadow for more information.
Parameters
storage the grid storage object of the the grid, on which the hierarchisation should be executed
shadowstorage shadow points (see detailed description)
~PrewaveletGridGenerator()
sgpp::base::PrewaveletGridGenerator::~PrewaveletGridGenerator () override
Destructor.
Member Function Documentation
cliques() [1/2]
void sgpp::base::PrewaveletGridGenerator::cliques (size_t level, size_t clique_size) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::cliques(), level, and storage.
cliques() [2/2]
void sgpp::base::PrewaveletGridGenerator::cliques (size_t level, size_t clique_size, double T) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
T modifier for subgrid selection, T = 0 implies standard sparse grid. For further information see Griebel and Knapek's paper optimized tensor-product approximation spaces
Reimplemented from sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::cliques(), level, and storage.
coarsen()
void sgpp::base::PrewaveletGridGenerator::coarsen (CoarseningFunctor & func, std::vector< size_t > * removedSeq) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Parameters
func pointer to coarsening functor
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen(), and storage.
Referenced by coarsen(), coarsenNFirstOnly(), and getNumberOfRemovablePoints().
coarsenNFirstOnly()
void sgpp::base::PrewaveletGridGenerator::coarsenNFirstOnly (CoarseningFunctor & func, size_t numFirstOnly, std::vector< size_t > * removedSeq, size_t minIndexConsidered) override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Only numFirstOnly first grid points are checked for coarsening.
Parameters
func pointer to coarsening functor
numFirstOnly max. number grid points to be coarsened
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
minIndexConsidered Minimum index of grid points that will be coarsened
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::free_coarsen_NFirstOnly(), and storage.
full()
void sgpp::base::PrewaveletGridGenerator::full (size_t level) override virtual
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGenerator::full(), level, and storage.
getNumberOfRefinablePoints()
size_t sgpp::base::PrewaveletGridGenerator::getNumberOfRefinablePoints () override virtual
Returns the number of points on the grid that can be refined in the next iteration.
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
References sgpp::base::HashRefinement::getNumberOfRefinablePoints(), refine(), and storage.
getNumberOfRefinablePointsToMaxLevel()
size_t sgpp::base::PrewaveletGridGenerator::getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override virtual
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
Parameters
maxLevel no points on higher levels than maxLevel will be created
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
getNumberOfRemovablePoints()
size_t sgpp::base::PrewaveletGridGenerator::getNumberOfRemovablePoints () override virtual
Returns the number of points on the grid that can be removed in the next iteration.
Returns
the number of points on the grid that can be removed
Implements sgpp::base::GridGenerator.
References coarsen(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), and storage.
refine()
void sgpp::base::PrewaveletGridGenerator::refine (RefinementFunctor & func, std::vector< size_t > * addedPoints = nullptr) override virtual
Refines the grid and updates the shadow storage.
Implements sgpp::base::GridGenerator.
References sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), sgpp::base::HashRefinement::free_refine(), sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), refine(), shadowstorage, and storage.
Referenced by getNumberOfRefinablePoints(), and refine().
refineMaxLevel()
void sgpp::base::PrewaveletGridGenerator::refineMaxLevel (RefinementFunctor & func, size_t maxLevel) override virtual
Refines a grid according to the settings of the RefinementFunctor func.
additionally a maximum level for refinement is taken into account
Parameters
func pointer to refinement functor
maxLevel no points on higher levels than maxLevel will be created
Implements sgpp::base::GridGenerator.
regular() [1/2]
void sgpp::base::PrewaveletGridGenerator::regular (size_t level) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
References level, sgpp::base::HashGenerator::regular(), and storage.
regular() [2/2]
void sgpp::base::PrewaveletGridGenerator::regular (size_t level, double T) override virtual
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
If the used grid doesn't support the parameter t, t = 0 is used instead.
Parameters
level Grid level
T modifier for subgrid selection, T = 0 implies standard sparse grid. For further information see Griebel and Knapek's paper optimized tensor-product approximation spaces
Reimplemented from sgpp::base::GridGenerator.
References level, sgpp::base::HashGenerator::regular(), and storage.
Member Data Documentation
shadowstorage
GridStorage& sgpp::base::PrewaveletGridGenerator::shadowstorage protected
Referenced by refine().
storage
GridStorage& sgpp::base::PrewaveletGridGenerator::storage protected
reference to the storage object
Referenced by cliques(), cliques(), coarsen(), coarsenNFirstOnly(), full(), getNumberOfRefinablePoints(), getNumberOfRemovablePoints(), refine(), regular(), and regular().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/PrewaveletGridGenerator.hpp
base/src/sgpp/base/grid/generation/PrewaveletGridGenerator.cpp