SG++-Doxygen-Documentation: sgpp::base::DehierarchisationLinearClenshawCurtisBoundary Class Reference
sgpp::base::DehierarchisationLinearClenshawCurtisBoundary Class Reference
Class that implements the dehierarchisation on a polynomial sparse grid.
#include <DehierarchisationLinearClenshawCurtisBoundary.hpp>
Public Member Functions
DehierarchisationLinearClenshawCurtisBoundary (GridStorage &storage)
Constructor, must be bind to a grid.
void operator() (DataVector &source, DataVector &result, grid_iterator &index, size_t dim)
Implements operator() needed by the sweep class during the grid traversal.
~DehierarchisationLinearClenshawCurtisBoundary ()
Destructor.
Protected Types
typedef GridStorage::grid_iterator grid_iterator
typedef index_t index_type
typedef level_t level_type
Protected Member Functions
void rec (DataVector &source, DataVector &result, grid_iterator &index, size_t dim, double xl, double fl, double xr, double fr)
Recursive dehierarchisation algorithm, this algorithms works in-place -> source should be equal to result.
Protected Attributes
ClenshawCurtisTable & clenshawCurtisTable
clenshaw curtis points
GridStorage & storage
the grid object
Detailed Description
Class that implements the dehierarchisation on a polynomial sparse grid.
Therefore the ()operator has to be implement in order to use the sweep algorithm for the grid traversal
Member Typedef Documentation
grid_iterator
typedef GridStorage::grid_iterator sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::grid_iterator protected
index_type
typedef index_t sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::index_type protected
level_type
typedef level_t sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::level_type protected
Constructor & Destructor Documentation
DehierarchisationLinearClenshawCurtisBoundary()
sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::DehierarchisationLinearClenshawCurtisBoundary (GridStorage & storage) explicit
Constructor, must be bind to a grid.
Parameters
storage the grid storage object of the the grid, on which the dehierarchisation should be executed
~DehierarchisationLinearClenshawCurtisBoundary()
sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::~DehierarchisationLinearClenshawCurtisBoundary ()
Destructor.
Member Function Documentation
operator()()
void sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator() (DataVector & source, DataVector & result, grid_iterator & index, size_t dim)
Implements operator() needed by the sweep class during the grid traversal.
This function is applied to the whole grid.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
References clenshawCurtisTable, sgpp::base::HashGridIterator::get(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), and storage.
rec()
void sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec (DataVector & source, DataVector & result, grid_iterator & index, size_t dim, double xl, double fl, double xr, double fr) protected
Recursive dehierarchisation algorithm, this algorithms works in-place -> source should be equal to result.
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
xl position of closest neighbor to the left
fl function value of closest neighbor to the left
xr position of closest neighbor to the right
fr function value of closest neighbor to the right
References clenshawCurtisTable, sgpp::base::HashGridIterator::get(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), and rec().
Member Data Documentation
clenshawCurtisTable
ClenshawCurtisTable& sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::clenshawCurtisTable protected
clenshaw curtis points
Referenced by operator()(), and rec().
storage
GridStorage& sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::storage protected
the grid object
Referenced by operator()(), and rec().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinearClenshawCurtisBoundary.hpp
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinearClenshawCurtisBoundary.cpp