SG++-Doxygen-Documentation: sgpp::pde::UpDownOneOpDimWithShadow Class Reference
sgpp::pde::UpDownOneOpDimWithShadow Class Reference abstract
Implements the Up/Down scheme with one dimension with a special operation.
#include <UpDownOneOpDimWithShadow.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
UpDownOneOpDimWithShadow (sgpp::base::GridStorage *storage, sgpp::base::GridStorage *shadowStorage)
Constructor.
virtual ~UpDownOneOpDimWithShadow ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
virtual void down (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)=0
std 1D down operation
virtual void downOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)=0
special 1D down operation that is only executed in one direction
void expandGrid ()
This functions adds all grid points of the shadow storage into the actual grid.
void shrinkGrid ()
Removes the previously added shadow grid points from the actual grid.
virtual void specialOP (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
All calculations for op_dim.
virtual void up (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)=0
std 1D up operation
void updown (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
Recursive procedure for updown().
virtual void upOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)=0
special 1D up operation that is only executed in one direction
Protected Attributes
sgpp::base::GridStorage * shadowStorage
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Detailed Description
Implements the Up/Down scheme with one dimension with a special operation.
Before the actual operation starts, all grid points from the shadow storage are copied into the actual grid. After the calculation, all shadow grid points are deleted, the result vector is adapted accordingly.
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::UpDownOneOpDimWithShadow::grid_iterator protected
Constructor & Destructor Documentation
UpDownOneOpDimWithShadow()
sgpp::pde::UpDownOneOpDimWithShadow::UpDownOneOpDimWithShadow (sgpp::base::GridStorage * storage, sgpp::base::GridStorage * shadowStorage)
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
shadowStorage shadow storage
References shadowStorage, and storage.
~UpDownOneOpDimWithShadow()
sgpp::pde::UpDownOneOpDimWithShadow::~UpDownOneOpDimWithShadow () virtual
Destructor.
Member Function Documentation
down()
virtual void sgpp::pde::UpDownOneOpDimWithShadow::down (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected pure virtual
std 1D down operation
Parameters
dim dimension in which to apply the down-part
alpha vector of coefficients
result vector to store the results in
Implemented in sgpp::pde::OperationLaplacePrewavelet.
Referenced by updown().
downOpDim()
virtual void sgpp::pde::UpDownOneOpDimWithShadow::downOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected pure virtual
special 1D down operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that down-Gradient is applied
Implemented in sgpp::pde::OperationLaplacePrewavelet.
Referenced by specialOP().
expandGrid()
void sgpp::pde::UpDownOneOpDimWithShadow::expandGrid () protected
This functions adds all grid points of the shadow storage into the actual grid.
References sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), sgpp::base::HashGridStorage::insert(), shadowStorage, and storage.
Referenced by mult().
mult()
void sgpp::pde::UpDownOneOpDimWithShadow::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implements sgpp::base::OperationMatrix.
References sgpp::base::DataVector::add(), alpha, expandGrid(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataVector::getSize(), sgpp::base::HashGridStorage::getSize(), sgpp::base::DataVector::setAll(), shrinkGrid(), storage, and updown().
shrinkGrid()
void sgpp::pde::UpDownOneOpDimWithShadow::shrinkGrid () protected
Removes the previously added shadow grid points from the actual grid.
Thus, the grid is the same shape as before the call of mult.
References sgpp::base::HashGridStorage::deleteLast(), sgpp::base::HashGridStorage::getSize(), shadowStorage, and storage.
Referenced by mult().
specialOP()
void sgpp::pde::UpDownOneOpDimWithShadow::specialOP (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim, size_t op_dim) protected virtual
All calculations for op_dim.
Parameters
alpha the coefficients of the grid points
result the result of the operations
dim the current dimension in the recursion
op_dim the dimension in that a special operation is applied
References sgpp::base::DataVector::add(), alpha, downOpDim(), sgpp::base::DataVector::getSize(), sgpp::base::DataVector::setAll(), updown(), and upOpDim().
Referenced by updown().
up()
virtual void sgpp::pde::UpDownOneOpDimWithShadow::up (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected pure virtual
std 1D up operation
Parameters
dim dimension in which to apply the up-part
alpha vector of coefficients
result vector to store the results in
Implemented in sgpp::pde::OperationLaplacePrewavelet.
Referenced by updown().
updown()
void sgpp::pde::UpDownOneOpDimWithShadow::updown (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim, size_t op_dim) protected
Recursive procedure for updown().
Parameters
dim the current dimension
op_dim the dimension in which a special operation is applied
alpha vector of coefficients
result vector to store the results in
References sgpp::base::DataVector::add(), alpha, down(), sgpp::base::DataVector::getSize(), sgpp::base::DataVector::setAll(), specialOP(), up(), and updown().
Referenced by mult(), specialOP(), and updown().
upOpDim()
virtual void sgpp::pde::UpDownOneOpDimWithShadow::upOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected pure virtual
special 1D up operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that up-Gradient is applied
Implemented in sgpp::pde::OperationLaplacePrewavelet.
Referenced by specialOP().
Member Data Documentation
shadowStorage
sgpp::base::GridStorage* sgpp::pde::UpDownOneOpDimWithShadow::shadowStorage protected
Referenced by expandGrid(), shrinkGrid(), and UpDownOneOpDimWithShadow().
storage
sgpp::base::GridStorage* sgpp::pde::UpDownOneOpDimWithShadow::storage protected
Pointer to the grid's storage object.
Referenced by sgpp::pde::OperationLaplacePrewavelet::downOpDim(), expandGrid(), mult(), shrinkGrid(), sgpp::pde::OperationLaplacePrewavelet::up(), UpDownOneOpDimWithShadow(), and sgpp::pde::OperationLaplacePrewavelet::upOpDim().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/algorithm/UpDownOneOpDimWithShadow.hpp
pde/src/sgpp/pde/algorithm/UpDownOneOpDimWithShadow.cpp