SG++-Doxygen-Documentation: sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT > Class Template Reference
sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT > Class Template Reference
Not-a-knot B-spline basis.
#include <NakBsplineModifiedBasisDeriv2.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
NakBsplineModifiedBasisDeriv2 ()
Default constructor.
NakBsplineModifiedBasisDeriv2 (size_t degree)
Constructor.
~NakBsplineModifiedBasisDeriv2 () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
NakBsplineBasisDeriv2< LT, IT > nakBsplineBasisDeriv2
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >
Not-a-knot B-spline basis.
Constructor & Destructor Documentation
NakBsplineModifiedBasisDeriv2() [1/2]
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::NakBsplineModifiedBasisDeriv2 () inline
Default constructor.
NakBsplineModifiedBasisDeriv2() [2/2]
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::NakBsplineModifiedBasisDeriv2 (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::getDegree().
~NakBsplineModifiedBasisDeriv2()
template<class LT , class IT > sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::~NakBsplineModifiedBasisDeriv2 () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::getDegree(), and sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::nakBsplineBasisDeriv2.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian().
evalDx()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of wavelet basis function
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::nakBsplineBasisDeriv2.
Referenced by sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::eval(), and sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::NakBsplineModifiedBasisDeriv2().
getIntegral()
template<class LT , class IT > double sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
nakBsplineBasisDeriv2
template<class LT , class IT > NakBsplineBasisDeriv2<LT, IT> sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::nakBsplineBasisDeriv2 protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::eval(), and sgpp::base::NakBsplineModifiedBasisDeriv2< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/NakBsplineModifiedBasisDeriv2.hpp