SG++-Doxygen-Documentation: sgpp::base::DehierarchisationLinearStretchedBoundary Class Reference
sgpp::base::DehierarchisationLinearStretchedBoundary Class Reference
Class that implements the dehierarchisation on a linear sparse grid with boundaries.
#include <DehierarchisationLinearStretchedBoundary.hpp>
Public Member Functions
DehierarchisationLinearStretchedBoundary (GridStorage &storage)
Constructor, must be bind to a grid.
virtual void operator() (DataVector &source, DataVector &result, grid_iterator &index, size_t dim) override
Implements operator() needed by the sweep class during the grid traversal.
~DehierarchisationLinearStretchedBoundary () override
Destructor.
Public Member Functions inherited from sgpp::base::DehierarchisationLinearStretched
DehierarchisationLinearStretched (GridStorage &storage)
Constructor, must be bind to a grid.
virtual ~DehierarchisationLinearStretched ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::base::DehierarchisationLinearStretched
typedef GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::base::DehierarchisationLinearStretched
void rec (DataVector &source, DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
Recursive dehierarchisaton algorithm, this algorithms works in-place -> source should be equal to result.
Protected Attributes inherited from sgpp::base::DehierarchisationLinearStretched
GridStorage & storage
the grid object
Detailed Description
Class that implements the dehierarchisation on a linear sparse grid with boundaries.
Therefore the ()operator has to be implement in order to use the sweep algorithm for the grid traversal
Constructor & Destructor Documentation
DehierarchisationLinearStretchedBoundary()
sgpp::base::DehierarchisationLinearStretchedBoundary::DehierarchisationLinearStretchedBoundary (GridStorage & storage) explicit
Constructor, must be bind to a grid.
Parameters
storage the grid storage object of the the grid, on which the dehierarchisation should be executed
~DehierarchisationLinearStretchedBoundary()
sgpp::base::DehierarchisationLinearStretchedBoundary::~DehierarchisationLinearStretchedBoundary () override
Destructor.
Member Function Documentation
operator()()
void sgpp::base::DehierarchisationLinearStretchedBoundary::operator() (DataVector & source, DataVector & result, grid_iterator & index, size_t dim) override virtual
Implements operator() needed by the sweep class during the grid traversal.
This function is applied to the whole grid.
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
Parameters
source this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
result this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::base::DehierarchisationLinearStretched.
References sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), and sgpp::base::DehierarchisationLinearStretched::storage.
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinearStretchedBoundary.hpp
base/src/sgpp/base/operation/hash/common/algorithm_sweep/DehierarchisationLinearStretchedBoundary.cpp