SG++-Doxygen-Documentation: sgpp::base::HashGridStorage Class Reference
sgpp::base::HashGridStorage Class Reference
Generic hash table based storage of grid points.
#include <HashGridStorage.hpp>
Public Types
typedef HashGridIterator grid_iterator
iterator for grid points
typedef std::vector< point_pointer > grid_list
vector of index_pointers
typedef grid_list::const_iterator grid_list_const_iterator
const iterator of grid_list
typedef grid_list::iterator grid_list_iterator
iterator of grid_list
typedef std::unordered_map< point_pointer, size_t, HashGridPointPointerHashFunctor, HashGridPointPointerEqualityFunctor > grid_map
unordered_map of index_pointers
typedef grid_map::const_iterator grid_map_const_iterator
const_iterator of grid_map
typedef grid_map::iterator grid_map_iterator
iterator of grid_map
typedef const HashGridPoint * index_const_pointer
pointer to constant index_type
typedef HashGridPoint * point_pointer
pointer to index_type
typedef HashGridPoint point_type
type of grid points
Public Member Functions
grid_map_iterator begin ()
set iterator to the first position in the map
void clear ()
deletes all grid points in the storage
point_pointer create (point_type &index)
creates a pointer to index from a reference to index by creating a new instance of a index object
void deleteLast ()
This methods removes the gridpoint added last.
std::vector< size_t > deletePoints (std::list< size_t > &removePoints)
Remove several point from HashGridStorage.
void destroy (point_pointer index)
removes an index from gridstorage
grid_map_iterator end ()
sets the iterator to last position in the map
grid_map_iterator find (point_pointer index)
sets the iterator to a given index
std::vector< size_t > getAlgorithmicDimensions ()
returns the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
BoundingBox * getBoundingBox ()
get the bounding box of the current grid
double getCoordinate (HashGridPoint point, size_t d) const
Calculates the coordinate of a given grid point in specific dimension.
void getCoordinateArrays (DataMatrix &coordinates)
Converts this storage from AOS (array of structures) to SOA (structure of array) to speed up operations on the position of the grid points.
DataVector getCoordinates (const HashGridPoint &point) const
Calculates the coordinates of a given grid point.
void getCoordinates (const HashGridPoint &point, DataVector &coordinates) const
Calculates the coordinates of a given grid point.
size_t getDimension () const
gets the dimension of the grid
void getLevelForIntegral (DataMatrix &level)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative Laplace Calculations: the level won't contain the levels, it contains 2 to the neagative power of the level.
void getLevelIndexArraysForEval (DataMatrix &level, DataMatrix &index)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
void getLevelIndexArraysForEval (DataMatrixSP &level, DataMatrixSP &index)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
void getLevelIndexMaskArraysForModEval (DataMatrix &level, DataMatrix &index, DataMatrix &mask, DataMatrix &offset)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
void getLevelIndexMaskArraysForModEval (DataMatrixSP &level, DataMatrixSP &index, DataMatrixSP &mask, DataMatrixSP &offset)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
size_t getMaxLevel () const
returns the max.
size_t getNumberOfInnerPoints () const
gets the number of inner grid points
HashGridPoint & getPoint (size_t seq) const
gets the index number for given gridpoint by its sequence number
double getPointCoordinate (size_t seq, size_t d)
Calculates the coordinate of a given grid point in specific dimension.
DataVector getPointCoordinates (size_t seq)
Calculates the coordinate of a given grid point.
HashGridPoint::index_type getPointIndex (size_t seq, size_t d) const
gets index l in dimension d of a point given by its sequence number
HashGridPoint::level_type getPointLevel (size_t seq, size_t d) const
gets level l in dimension d of a point given by its sequence number
size_t getSequenceNumber (HashGridPoint &index) const
Gets the seq number for index.
size_t getSize () const
gets the size of the hashmap
Stretching * getStretching ()
get the stretching bounding box of the current grid
double getUnitCoordinate (HashGridPoint point, size_t d) const
Calculates corresponding unit hypercube coordinate of a given point in specific dimension, taking into account the BoundingBox and Stretching.
double getUnitPointCoordinate (size_t seq, size_t d)
Calculates the coordinate of a given grid point in specific dimension taking into account the BoundingBox and Stretching.
bool hasBoundingBoxOrStretching ()
HashGridStorage (BoundingBox &creationBoundingBox)
Constructor.
HashGridStorage (HashGridStorage &copyFrom)
Copy Constructor.
HashGridStorage (size_t dimension)
Constructor.
HashGridStorage (std::istream &istream)
Constructor that reads the data from an input stream.
HashGridStorage (std::string &istr)
Constructor that reads the data from a string.
HashGridStorage (Stretching &creationStretching)
Constructor.
size_t insert (const point_type &index)
insert a new index into map
void insert (point_type &index, std::vector< size_t > &insertedPoints)
insert a new index into map including all its ancestors.
bool isContaining (HashGridPoint &index) const
Tests if index is in the storage.
bool isInvalidSequenceNumber (size_t s)
Tests if seq number does not point to a valid grid point.
void operator= (const HashGridStorage &other)
Assignment operator.
HashGridPoint & operator[] (size_t seq)
gets the index number for given gridpoint by its sequence number
const HashGridPoint & operator[] (size_t seq) const
gets the index number for given gridpoint by its sequence number
void recalcLeafProperty ()
Recalculates the leaf-property of every grid point.
std::string serialize (int version=SERIALIZATION_VERSION) const
serialize the gridstorage into a string
void serialize (std::ostream &ostream, int version=SERIALIZATION_VERSION) const
serialize the gridstorage into a stream
void setAlgorithmicDimensions (std::vector< size_t > newAlgoDims)
sets the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
void setBoundingBox (BoundingBox &boundingBox)
sets the bounding box of the current grid
void setStretching (Stretching &stretching)
sets the stretching bounding box of the current grid
unsigned int store (point_pointer index)
stores a given index in the hashmap
std::string toString () const
serialize the gridstorage's gridpoints into a stream
void toString (std::ostream &stream) const
serialize the gridstorage's gridpoints into a stream
void unserializeNoAlgoDims (std::string &istr)
unserializes the grid from a string, algorithmic dimensions are not reseted
void update (point_type &index, size_t pos)
updates an already stored index
~HashGridStorage ()
Destructor.
Detailed Description
Generic hash table based storage of grid points.
Member Typedef Documentation
grid_iterator
typedef HashGridIterator sgpp::base::HashGridStorage::grid_iterator
iterator for grid points
grid_list
typedef std::vector<point_pointer> sgpp::base::HashGridStorage::grid_list
vector of index_pointers
grid_list_const_iterator
typedef grid_list::const_iterator sgpp::base::HashGridStorage::grid_list_const_iterator
const iterator of grid_list
grid_list_iterator
typedef grid_list::iterator sgpp::base::HashGridStorage::grid_list_iterator
iterator of grid_list
grid_map
typedef std::unordered_map<point_pointer, size_t, HashGridPointPointerHashFunctor, HashGridPointPointerEqualityFunctor> sgpp::base::HashGridStorage::grid_map
unordered_map of index_pointers
grid_map_const_iterator
typedef grid_map::const_iterator sgpp::base::HashGridStorage::grid_map_const_iterator
const_iterator of grid_map
grid_map_iterator
typedef grid_map::iterator sgpp::base::HashGridStorage::grid_map_iterator
iterator of grid_map
index_const_pointer
typedef const HashGridPoint* sgpp::base::HashGridStorage::index_const_pointer
pointer to constant index_type
point_pointer
typedef HashGridPoint* sgpp::base::HashGridStorage::point_pointer
pointer to index_type
point_type
typedef HashGridPoint sgpp::base::HashGridStorage::point_type
type of grid points
Constructor & Destructor Documentation
HashGridStorage() [1/6]
sgpp::base::HashGridStorage::HashGridStorage (size_t dimension) explicit
Constructor.
initializes the boundingBox with a trivial cube
Parameters
dimension the dimension of the sparse grid
HashGridStorage() [2/6]
sgpp::base::HashGridStorage::HashGridStorage (BoundingBox & creationBoundingBox) explicit
Constructor.
initializes the boundingBox with a reference to another boundingbox
Parameters
creationBoundingBox reference to bounding box object that describes the grid boundaries
HashGridStorage() [3/6]
sgpp::base::HashGridStorage::HashGridStorage (Stretching & creationStretching) explicit
Constructor.
initializes the stretching with a reference to another stretching
Parameters
creationStretching reference to stretching object that describes the grid boundaries and the stretching
HashGridStorage() [4/6]
sgpp::base::HashGridStorage::HashGridStorage (std::string & istr) explicit
Constructor that reads the data from a string.
Parameters
istr the string that contains the data
HashGridStorage() [5/6]
sgpp::base::HashGridStorage::HashGridStorage (std::istream & istream) explicit
Constructor that reads the data from an input stream.
Parameters
istream the inputstream that contains the data
HashGridStorage() [6/6]
sgpp::base::HashGridStorage::HashGridStorage (HashGridStorage & copyFrom) explicit
Copy Constructor.
References getSize(), and insert().
~HashGridStorage()
sgpp::base::HashGridStorage::~HashGridStorage ()
Destructor.
Member Function Documentation
begin()
HashGridStorage::grid_map_iterator sgpp::base::HashGridStorage::begin () inline
set iterator to the first position in the map
Returns
iterator pointing to the beginning of the map
Referenced by sgpp::optimization::HashRefinementMultiple::collectRefinablePoints(), sgpp::base::HashRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), sgpp::base::ForwardSelectorRefinement::collectRefinablePoints(), sgpp::base::ImpurityRefinement::collectRefinablePoints(), sgpp::base::MultipleClassRefinement::collectRefinablePoints(), sgpp::base::PredictiveRefinement::collectRefinablePoints(), sgpp::base::SubspaceRefinement::collectRefinablePoints(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::base::HashRefinement::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), sgpp::base::RefinementFunctor::getTotalRefinementValue(), sgpp::solver::StepsizeControl::maxNorm(), sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel(), sgpp::base::GridDataBase::setValuesFor(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), and sgpp::datadriven::LearnerSVM::storeResults().
clear()
void sgpp::base::HashGridStorage::clear ()
deletes all grid points in the storage
Referenced by operator=().
create()
HashGridStorage::point_pointer sgpp::base::HashGridStorage::create (point_type & index) inline
creates a pointer to index from a reference to index by creating a new instance of a index object
Parameters
index address of index object
Returns
pointer to new index object
References insert().
deleteLast()
void sgpp::base::HashGridStorage::deleteLast ()
This methods removes the gridpoint added last.
Use with coution, only needed for expanding the grid because of the shadow-storage of prewavelets. Please refer to the Prewavelet grid for further description of the shadow storage.
Referenced by sgpp::base::OperationHierarchisationPrewavelet::shrinkGrid(), and sgpp::pde::UpDownOneOpDimWithShadow::shrinkGrid().
deletePoints()
std::vector< size_t > sgpp::base::HashGridStorage::deletePoints (std::list< size_t > & removePoints)
Remove several point from HashGridStorage.
The points to removed are stored in a list. This function returns a vector of remaining points given by their
Parameters
removePoints vector containing the indices of the points that should be removed
Returns
a vector containing the indices of remaining points given by their "old" index
References recalcLeafProperty().
Referenced by sgpp::base::HashCoarsening::free_coarsen_NFirstOnly().
destroy()
void sgpp::base::HashGridStorage::destroy (point_pointer index) inline
removes an index from gridstorage
Parameters
index pointer to index that should be removed
end()
HashGridStorage::grid_map_iterator sgpp::base::HashGridStorage::end () inline
sets the iterator to last position in the map
Returns
iterator pointing to the end of the map
Referenced by sgpp::optimization::HashRefinementMultiple::collectRefinablePoints(), sgpp::base::HashRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), sgpp::base::ForwardSelectorRefinement::collectRefinablePoints(), sgpp::base::ImpurityRefinement::collectRefinablePoints(), sgpp::base::MultipleClassRefinement::collectRefinablePoints(), sgpp::base::PredictiveRefinement::collectRefinablePoints(), sgpp::base::SubspaceRefinement::collectRefinablePoints(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::base::ForwardSelectorRefinement::getIndicator(), sgpp::base::ImpurityRefinement::getIndicator(), sgpp::base::PredictiveRefinement::getIndicator(), sgpp::base::HashRefinement::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), sgpp::base::RefinementFunctor::getTotalRefinementValue(), sgpp::base::AbstractRefinement::isRefinable(), sgpp::solver::StepsizeControl::maxNorm(), sgpp::base::PrewaveletGridGenerator::refine(), sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel(), sgpp::base::GridDataBase::setValuesFor(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), and sgpp::datadriven::LearnerSVM::storeResults().
find()
HashGridStorage::grid_map_iterator sgpp::base::HashGridStorage::find (point_pointer index) inline
sets the iterator to a given index
Parameters
index the index to which the cursor should be moved
Returns
iterator pointing to the index
Referenced by sgpp::base::HashRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), sgpp::base::SubspaceRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::createGridpointLevelZeroConsistency(), sgpp::base::AbstractRefinement::createGridpointSubroutine(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::base::ForwardSelectorRefinement::getIndicator(), sgpp::base::ImpurityRefinement::getIndicator(), sgpp::base::PredictiveRefinement::getIndicator(), sgpp::base::HashRefinement::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::AbstractRefinement::isRefinable(), sgpp::solver::StepsizeControl::maxNorm(), sgpp::base::PrewaveletGridGenerator::refine(), and sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel().
getAlgorithmicDimensions()
std::vector< size_t > sgpp::base::HashGridStorage::getAlgorithmicDimensions () inline
returns the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
Returns
the algorithmic dimensions
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), and sgpp::base::Grid::getAlgorithmicDimensions().
getBoundingBox()
BoundingBox * sgpp::base::HashGridStorage::getBoundingBox ()
get the bounding box of the current grid
Returns
returns a pointer to HashGridStorage's bounding box
Referenced by sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinear::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::Grid::getBoundingBox(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::base::AlgorithmEvaluation< BASIS >::operator()(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinear::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), and sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()().
getCoordinate()
double sgpp::base::HashGridStorage::getCoordinate (HashGridPoint point, size_t d) const inline
Calculates the coordinate of a given grid point in specific dimension.
In contrast to HashGridPoint::getStandardCoordinate, this takes the BoundingBox and Stretching into account.
Parameters
point grid point
d dimension
Returns
coordinate of the point in dimension d
References sgpp::base::Stretching::getCoordinate(), sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), and level.
Referenced by getCoordinates(), getCoordinates(), getUnitCoordinate(), and getUnitPointCoordinate().
getCoordinateArrays()
void sgpp::base::HashGridStorage::getCoordinateArrays (DataMatrix & coordinates)
Converts this storage from AOS (array of structures) to SOA (structure of array) to speed up operations on the position of the grid points.
Parameters
coordinates DataMatrix to store the coordinates of the grid points
References getCoordinates(), sgpp::base::DataMatrix::resize(), and sgpp::base::DataMatrix::setRow().
Referenced by sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation(), and sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation().
getCoordinates() [1/2]
DataVector sgpp::base::HashGridStorage::getCoordinates (const HashGridPoint & point) const
Calculates the coordinates of a given grid point.
In contrast to HashGridPoint::getStandardCoordinates, this takes the BoundingBox and Stretching into account.
Parameters
point grid point
Returns
vector of coordinates
References getCoordinate().
getCoordinates() [2/2]
void sgpp::base::HashGridStorage::getCoordinates (const HashGridPoint & point, DataVector & coordinates) const
Calculates the coordinates of a given grid point.
In contrast to HashGridPoint::getStandardCoordinates, this takes the BoundingBox and Stretching into account.
Parameters
point grid point
[out] coordinates vector of coordinates
References getCoordinate().
Referenced by sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), getCoordinateArrays(), sgpp::pde::PDESolver::getGridNormalDistribution(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::HeatEquationSolver::initGridWithSmoothHeat(), sgpp::pde::HeatEquationSolverWithStretching::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeatFullDomain(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), and sgpp::datadriven::LearnerSVM::storeResults().
getDimension()
size_t sgpp::base::HashGridStorage::getDimension () const
gets the dimension of the grid
Returns
the dimension of the grid stored in this HashGridStorage object
Referenced by sgpp::datadriven::AlgorithmAdaBoostBase::AlgorithmAdaBoostBase(), sgpp::base::HashGenerator::cliques(), sgpp::base::HashGenerator::cliques_iter(), sgpp::base::HashRefinement::collectRefinablePoints(), sgpp::base::HashRefinementBoundaries::collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), sgpp::base::SubspaceRefinement::collectRefinablePoints(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::base::HashRefinementInteraction::createGridpoint(), sgpp::base::HashRefinement::createGridpoint(), sgpp::base::HashRefinementBoundaries::createGridpoint1D(), sgpp::base::HashRefinementBoundaries::createGridpointGeneral(), sgpp::base::HashRefinementBoundaries::createGridpointLevelZeroConsistency(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::base::OperationConvertPrewavelet::doConvertFromLinear(), sgpp::base::OperationConvertPrewavelet::doConvertToLinear(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationLinear::doDehierarchisation(), sgpp::base::OperationHierarchisationLinearBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::base::OperationHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationLinearStretched::doDehierarchisation(), sgpp::base::OperationHierarchisationLinearStretchedBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationModLinear::doDehierarchisation(), sgpp::base::OperationHierarchisationModLinearClenshawCurtis::doDehierarchisation(), sgpp::base::OperationHierarchisationModPoly::doDehierarchisation(), sgpp::base::OperationHierarchisationModPolyClenshawCurtis::doDehierarchisation(), sgpp::base::OperationHierarchisationPoly::doDehierarchisation(), sgpp::base::OperationHierarchisationPolyBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationPolyClenshawCurtis::doDehierarchisation(), sgpp::base::OperationHierarchisationPolyClenshawCurtisBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationPrewavelet::doDehierarchisation(), sgpp::base::OperationStencilHierarchisationLinear::doDehierarchisation(), sgpp::base::OperationStencilHierarchisationModLinear::doDehierarchisation(), sgpp::base::OperationHierarchisationLinear::doHierarchisation(), sgpp::base::OperationHierarchisationLinearBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationLinearClenshawCurtis::doHierarchisation(), sgpp::base::OperationHierarchisationLinearClenshawCurtisBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationLinearStretched::doHierarchisation(), sgpp::base::OperationHierarchisationLinearStretchedBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationModLinear::doHierarchisation(), sgpp::base::OperationHierarchisationModLinearClenshawCurtis::doHierarchisation(), sgpp::base::OperationHierarchisationModPoly::doHierarchisation(), sgpp::base::OperationHierarchisationModPolyClenshawCurtis::doHierarchisation(), sgpp::base::OperationHierarchisationPoly::doHierarchisation(), sgpp::base::OperationHierarchisationPolyBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationPolyClenshawCurtis::doHierarchisation(), sgpp::base::OperationHierarchisationPolyClenshawCurtisBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationPrewavelet::doHierarchisation(), sgpp::base::OperationStencilHierarchisationLinear::doHierarchisation(), sgpp::base::OperationStencilHierarchisationModLinear::doHierarchisation(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentLinear::doQuadrature(), sgpp::base::OperationFirstMomentLinearBoundary::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModLinear::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentLinear::doQuadrature(), sgpp::base::OperationSecondMomentLinearBoundary::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModLinear::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakPBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::datadriven::OperationDotProductLinear::eval(), sgpp::datadriven::OperationDotProductModLinear::eval(), sgpp::base::HierarchisationSLE::evalBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineModifiedFunctionAtGridPoint(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::HierarchisationSLE::evalLinearBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalModPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineExtendedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakPBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNaturalBsplineFunctionAtGridPoint(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::HierarchisationSLE::evalPolyBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalSplineFunctionAtGridPoint(), sgpp::base::BreadthFirstSearch< FUNC >::execute(), sgpp::base::Grid::getDimension(), sgpp::base::ForwardSelectorRefinement::getIndicator(), sgpp::base::ImpurityRefinement::getIndicator(), sgpp::base::PredictiveRefinement::getIndicator(), sgpp::pde::PDESolver::getNumberDimensions(), sgpp::base::HashRefinement::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::datadriven::OperationRegularizationDiagonal::initAnisotropicPenalty(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), sgpp::datadriven::OperationRegularizationDiagonal::initIsotropicPenalty(), sgpp::base::OperationEvalPrewavelet::integrate(), sgpp::base::AbstractRefinement::isRefinable(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::pde::UpDownOneOpDimWithShadow::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates(), sgpp::datadriven::GridPointBasedRefinementFunctor::operator()(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::operator()(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()(), sgpp::base::GetAffectedBasisFunctions< BASIS >::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::PrewaveletGridGenerator::refine(), sgpp::base::ANOVAHashRefinement::refineGridpoint(), sgpp::base::HashRefinement::refineGridpoint(), sgpp::base::HashRefinementBoundaries::refineGridpoint(), sgpp::base::HashRefinementBoundariesMaxLevel::refineGridpoint(), sgpp::base::SubspaceRefinement::refineGridpointsCollection(), sgpp::base::StandardGridGenerator::refineInter(), sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), sgpp::base::HashGenerator::regularInter(), sgpp::base::HashGenerator::regularWithBoundaries(), sgpp::base::HashGenerator::regularWithPeriodicBoundaries(), sgpp::base::HashGridIterator::resetToLevelZero(), sgpp::base::HashGenerator::square_rec(), sgpp::base::HashGenerator::squareRoot(), sgpp::base::sweep< FUNC >::sweep1D(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), and sgpp::base::HashGenerator::truncated().
getLevelForIntegral()
void sgpp::base::HashGridStorage::getLevelForIntegral (DataMatrix & level)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative Laplace Calculations: the level won't contain the levels, it contains 2 to the neagative power of the level.
Parameters
level DataMatrix to store the grid's modified level
References level.
getLevelIndexArraysForEval() [1/2]
void sgpp::base::HashGridStorage::getLevelIndexArraysForEval (DataMatrix & level, DataMatrix & index)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
The Level array won't contain the levels, it contains the level to the power of two
Parameters
level DataMatrix to store the grid's level to the power of two
index DataMatrix to store the grid's indices
References level, and sgpp::base::DataMatrix::set().
Referenced by sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotPeriodic::mult(), and sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult().
getLevelIndexArraysForEval() [2/2]
void sgpp::base::HashGridStorage::getLevelIndexArraysForEval (DataMatrixSP & level, DataMatrixSP & index)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
The Level array won't contain the levels, it contains the level to the power of two
Parameters
level DataMatrix to store the grid's level to the power of two
index DataMatrix to store the grid's indices
References level, and sgpp::base::DataMatrixSP::set().
getLevelIndexMaskArraysForModEval() [1/2]
void sgpp::base::HashGridStorage::getLevelIndexMaskArraysForModEval (DataMatrix & level, DataMatrix & index, DataMatrix & mask, DataMatrix & offset)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
The Level array won't contain the levels, it contains the level to the power of two.
The returned format is only useful for a multi-evaluation of modlinear grids
Parameters
level DataMatrix to store the grid's level to the power of two
index DataMatrix to store the grid's indices
mask DataMatrix to store masks of operations
offset DataMatrix to store offset for operations
References level, and sgpp::base::DataMatrix::set().
getLevelIndexMaskArraysForModEval() [2/2]
void sgpp::base::HashGridStorage::getLevelIndexMaskArraysForModEval (DataMatrixSP & level, DataMatrixSP & index, DataMatrixSP & mask, DataMatrixSP & offset)
Converts this storage from AOS (array of structures) to SOA (structure of array) with modification to speed up iterative function evaluation.
The Level array won't contain the levels, it contains the level to the power of two.
The returned format is only useful for a multi-evaluation of modlinear grids
Parameters
level DataMatrixSP to store the grid's level to the power of two
index DataMatrixSP to store the grid's indices
mask DataMatrixSP to store masks of operations
offset DataMatrixSP to store offset for operations
References f, level, and sgpp::base::DataMatrixSP::set().
getMaxLevel()
size_t sgpp::base::HashGridStorage::getMaxLevel () const
returns the max.
depth in all dimension of the grid
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates(), sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates(), and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates().
getNumberOfInnerPoints()
size_t sgpp::base::HashGridStorage::getNumberOfInnerPoints () const
gets the number of inner grid points
Returns
the number of inner grid points
Referenced by sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::pde::PDESolver::getNumberInnerGridPoints(), and sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs().
getPoint()
HashGridPoint & sgpp::base::HashGridStorage::getPoint (size_t seq) const inline
gets the index number for given gridpoint by its sequence number
Parameters
seq the sequence number of the index
Returns
gridpoint object (pointer)
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::base::HashGenerator::cliques_iter(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::base::HashRefinementBoundaries::createGridpointLevelZeroConsistency(), sgpp::base::AbstractRefinement::createGridpointSubroutine(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::OperationDensitySampling1DLinear::doSampling1D(), sgpp::datadriven::OperationInverseRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationDotProductLinear::eval(), sgpp::datadriven::OperationDotProductModLinear::eval(), sgpp::base::OperationHierarchisationPrewavelet::expandGrid(), sgpp::pde::UpDownOneOpDimWithShadow::expandGrid(), sgpp::base::HashCoarsening::free_coarsen_NFirstOnly(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::generateb(), sgpp::pde::PDESolver::getGridNormalDistribution(), getUnitPointCoordinate(), sgpp::base::GridDataBase::GridDataBase(), sgpp::base::HashGridIterator::hint(), sgpp::datadriven::OperationRegularizationDiagonal::initAnisotropicPenalty(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::HeatEquationSolver::initGridWithSmoothHeat(), sgpp::pde::HeatEquationSolverWithStretching::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeatFullDomain(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), sgpp::datadriven::OperationRegularizationDiagonal::initIsotropicPenalty(), sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates(), sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation(), sgpp::datadriven::DataBasedRefinementFunctor::operator()(), sgpp::datadriven::GridPointBasedRefinementFunctor::operator()(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::base::SurplusVolumeRefinementFunctor::operator()(), sgpp::base::SurplusVolumeCoarseningFunctor::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::GridPrinter::printLevelIndexGrid(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), sgpp::base::PrewaveletGridGenerator::refine(), sgpp::base::MultipleClassRefinement::refineGridpoint(), sgpp::base::AbstractRefinement::refineGridpoint1D(), sgpp::base::HashRefinement::refineGridpoint1D(), sgpp::base::ForwardSelectorRefinement::refineGridpointsCollection(), sgpp::base::ImpurityRefinement::refineGridpointsCollection(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), sgpp::base::ForwardSelectorRefinementIndicator::runOperator(), and sgpp::base::PredictiveRefinementIndicator::runOperator().
getPointCoordinate()
double sgpp::base::HashGridStorage::getPointCoordinate (size_t seq, size_t d) inline
Calculates the coordinate of a given grid point in specific dimension.
Parameters
seq the sequence number of the index
d dimension
Returns
coordinate of the point in dimension d
References level.
Referenced by sgpp::base::HierarchisationSLE::evalBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalModPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineExtendedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakPBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletModifiedFunctionAtGridPoint(), getPointCoordinates(), and getUnitPointCoordinate().
getPointCoordinates()
DataVector sgpp::base::HashGridStorage::getPointCoordinates (size_t seq) inline
Calculates the coordinate of a given grid point.
Parameters
seq the sequence number of the index
Returns
coordinates of the point
References getPointCoordinate().
Referenced by sgpp::base::VectorDistributionRefinementFunctor::operator()().
getPointIndex()
HashGridPoint::index_type sgpp::base::HashGridStorage::getPointIndex (size_t seq, size_t d) const inline
gets index l in dimension d of a point given by its sequence number
Parameters
seq the sequence number of the index
d the dimension in which the ansatz function should be read
Returns
level
Referenced by sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakPBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature(), sgpp::base::HierarchisationSLE::evalBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalModPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineExtendedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakPBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletFunctionAtGridPoint(), and sgpp::base::HierarchisationSLE::evalWaveletModifiedFunctionAtGridPoint().
getPointLevel()
HashGridPoint::level_type sgpp::base::HashGridStorage::getPointLevel (size_t seq, size_t d) const inline
gets level l in dimension d of a point given by its sequence number
Parameters
seq the sequence number of the index
d the dimension in which the ansatz function should be read
Returns
level
Referenced by sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakPBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature(), sgpp::base::HierarchisationSLE::evalBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalFundamentalSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalModPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineExtendedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakBsplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNakPBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalPolyFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletBoundaryFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWaveletFunctionAtGridPoint(), and sgpp::base::HierarchisationSLE::evalWaveletModifiedFunctionAtGridPoint().
getSequenceNumber()
size_t sgpp::base::HashGridStorage::getSequenceNumber (HashGridPoint & index) const inline
Gets the seq number for index.
Parameters
index pointer to index which sequence number should be determined
Returns
the seq number for index
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::collectNeighbors(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::ForwardSelectorRefinement::getIndicator(), sgpp::base::ImpurityRefinement::getIndicator(), sgpp::base::PredictiveRefinement::getIndicator(), sgpp::base::GridDataBase::GridDataBase(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::HashGridIterator::leftChild(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::MultipleClassRefinement::refineGridpoint(), sgpp::base::ForwardSelectorRefinement::refineGridpointsCollection(), sgpp::base::ImpurityRefinement::refineGridpointsCollection(), sgpp::base::SubspaceRefinement::refineGridpointsCollection(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToLevelZero(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::set(), sgpp::base::HashGridIterator::set(), sgpp::base::HashGridIterator::stepLeft(), sgpp::base::HashGridIterator::stepRight(), and sgpp::base::HashGridIterator::up().
getSize()
size_t sgpp::base::HashGridStorage::getSize () const
gets the size of the hashmap
Returns
returns the size of the hashmap
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::AlgorithmAdaBoostBase::AlgorithmAdaBoostBase(), sgpp::base::HashGenerator::anisotropicFull(), sgpp::base::DirichletUpdateVector::applyDirichletConditions(), sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::base::HashGenerator::cliques(), sgpp::base::HashGenerator::cliques_iter(), python.uq.uq_setting.UQSetting.UQSetting::convert(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::datadriven::OperationDensitySampling1DLinear::doSampling1D(), sgpp::datadriven::OperationInverseRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation1D(), sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineExtended::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakBsplineModified::doWeightedQuadrature(), sgpp::base::OperationWeightedQuadratureNakPBspline::doWeightedQuadrature(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::datadriven::OperationDotProductLinear::eval(), sgpp::datadriven::OperationDotProductModLinear::eval(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::BreadthFirstSearch< FUNC >::execute(), sgpp::base::OperationHierarchisationPrewavelet::expandGrid(), sgpp::pde::UpDownOneOpDimWithShadow::expandGrid(), sgpp::base::HashCoarsening::free_coarsen(), sgpp::base::HashCoarsening::free_coarsen_NFirstOnly(), sgpp::base::ForwardSelectorRefinement::free_refine(), sgpp::base::ImpurityRefinement::free_refine(), sgpp::base::PredictiveRefinement::free_refine(), sgpp::base::HashRefinement::free_refine(), sgpp::base::HashRefinementBoundaries::free_refine(), sgpp::base::SubspaceRefinement::free_refine(), sgpp::base::HashGenerator::full(), sgpp::base::HashGenerator::fullWithBoundary(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::generateb(), sgpp::base::HierarchisationSLE::getDimension(), sgpp::pde::PDESolver::getNumberGridPoints(), sgpp::optimization::HashRefinementMultiple::getNumberOfRefinablePoints(), sgpp::base::HashRefinement::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundaries::getNumberOfRefinablePoints(), sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::HashCoarsening::getNumberOfRemovablePoints(), sgpp::base::Grid::getSize(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), sgpp::base::GridDataBase::GridDataBase(), HashGridStorage(), sgpp::base::OperationEvalPrewavelet::integrate(), sgpp::datadriven::OperationRegularizationDiagonal::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::pde::UpDownOneOpDimWithShadow::mult(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPeriodic::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::DirichletUpdateVector::multiply(), sgpp::base::DirichletUpdateVector::multiplyBoundary(), sgpp::base::DirichletUpdateVector::multiplyBoundaryVector(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreaming::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::multTranspose(), sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates(), sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation(), sgpp::pde::OperationLaplaceExplicitLinear::OperationLaplaceExplicitLinear(), sgpp::datadriven::OperationRegularizationDiagonal::OperationRegularizationDiagonal(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinear::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretched::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), operator=(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs(), sgpp::base::PrewaveletGridGenerator::refine(), sgpp::base::ForwardSelectorRefinement::refineGridpointsCollection(), sgpp::base::ImpurityRefinement::refineGridpointsCollection(), sgpp::base::SubspaceRefinement::refineGridpointsCollection(), sgpp::pde::PDESolver::refineInitialGridSurplus(), sgpp::pde::PDESolver::refineInitialGridSurplusSubDomain(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevel(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevelSubDomain(), sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel(), sgpp::base::HashGenerator::regular(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), sgpp::base::HashGenerator::regularInter(), sgpp::base::HashGenerator::regularWithBoundaries(), sgpp::base::HashGenerator::regularWithPeriodicBoundaries(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution(), sgpp::base::DirichletUpdateVector::setBoundariesToZero(), sgpp::base::DirichletUpdateVector::setInnerPointsToZero(), sgpp::base::OperationHierarchisationPrewavelet::shrinkGrid(), sgpp::pde::UpDownOneOpDimWithShadow::shrinkGrid(), sgpp::base::HashGenerator::squareRoot(), and sgpp::base::HashGenerator::truncated().
getStretching()
Stretching * sgpp::base::HashGridStorage::getStretching ()
get the stretching bounding box of the current grid
Returns
returns a pointer to HashGridStorage's bounding box
Referenced by sgpp::base::Grid::getStretching(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretched::operator()(), and sgpp::base::DehierarchisationLinearStretched::rec().
getUnitCoordinate()
double sgpp::base::HashGridStorage::getUnitCoordinate (HashGridPoint point, size_t d) const inline
Calculates corresponding unit hypercube coordinate of a given point in specific dimension, taking into account the BoundingBox and Stretching.
References getCoordinate(), and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::base::HierarchisationSLE::evalFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalNaturalBsplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), and sgpp::base::HierarchisationSLE::evalWeaklyFundamentalSplineFunctionAtGridPoint().
getUnitPointCoordinate()
double sgpp::base::HashGridStorage::getUnitPointCoordinate (size_t seq, size_t d) inline
Calculates the coordinate of a given grid point in specific dimension taking into account the BoundingBox and Stretching.
Parameters
seq the sequence number of the index
d dimension
Returns
coordinate of the point in dimension d
References getCoordinate(), getPoint(), getPointCoordinate(), and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::base::HierarchisationSLE::evalBsplineClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalBsplineModifiedClenshawCurtisFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisBoundaryFunctionAtGridPoint(), and sgpp::base::HierarchisationSLE::evalLinearClenshawCurtisFunctionAtGridPoint().
hasBoundingBoxOrStretching()
bool sgpp::base::HashGridStorage::hasBoundingBoxOrStretching () inline
insert() [1/2]
size_t sgpp::base::HashGridStorage::insert (const point_type & index)
insert a new index into map
Parameters
index reference to the index that should be inserted
Returns
References insert().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::base::HashGenerator::boundaries_rec(), sgpp::base::HashGenerator::boundaries_Truncated_rec_1d(), sgpp::base::HashGenerator::cliques_iter(), sgpp::datadriven::ClassificationRefinementFunctor::collectNeighbors(), create(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::base::HashRefinementInteraction::createGridpoint(), sgpp::base::HashRefinement::createGridpoint(), sgpp::base::HashRefinementInconsistent::createGridpoint(), sgpp::base::HashRefinementBoundaries::createGridpointGeneral(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationHierarchisationPrewavelet::expandGrid(), sgpp::pde::UpDownOneOpDimWithShadow::expandGrid(), HashGridStorage(), insert(), insert(), sgpp::base::Grid::insertPoint(), sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation(), operator=(), sgpp::optimization::HashRefinementMultiple::refineGridpoint1D(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), sgpp::base::HashGenerator::square_rec(), sgpp::base::HashGenerator::trunc_rec(), and update().
insert() [2/2]
void sgpp::base::HashGridStorage::insert (point_type & index, std::vector< size_t > & insertedPoints)
insert a new index into map including all its ancestors.
Boundary points are not added
Parameters
index reference to the index that should be inserted
insertedPoints containing the indices of the new points
References sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridPoint::getParent(), insert(), isContaining(), and sgpp::base::HashGridPoint::set().
isContaining()
bool sgpp::base::HashGridStorage::isContaining (HashGridPoint & index) const inline
Tests if index is in the storage.
Parameters
index pointer to index that should be tested
Returns
true if the index is in the storage
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::ClassificationRefinementFunctor::collectNeighbors(), sgpp::base::HashRefinementBoundaries::createGridpointLevelZeroConsistency(), sgpp::base::AbstractRefinement::createGridpointSubroutine(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::HashGridIterator::hintLeft(), sgpp::base::HashGridIterator::hintRight(), insert(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), recalcLeafProperty(), sgpp::optimization::HashRefinementMultiple::refineGridpoint1D(), sgpp::base::HashRefinement::refineGridpoint1D(), sgpp::base::HashRefinementBoundaries::refineGridpoint1D(), sgpp::base::HashRefinementBoundariesMaxLevel::refineGridpoint1D(), and sgpp::datadriven::ClassificationRefinementFunctor::stepDown().
isInvalidSequenceNumber()
bool sgpp::base::HashGridStorage::isInvalidSequenceNumber (size_t s) inline
Tests if seq number does not point to a valid grid point.
Parameters
s sequence number that should be tested
Returns
true if we are not EOF
Referenced by sgpp::base::HashGridIterator::getGridDepth(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::ConvertLinearToPrewavelet::operator()(), sgpp::base::ConvertPrewaveletToLinear::operator()(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpPrewavelet::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
operator=()
void sgpp::base::HashGridStorage::operator= (const HashGridStorage & other)
Assignment operator.
References clear(), getSize(), and insert().
operator[]() [1/2]
HashGridPoint & sgpp::base::HashGridStorage::operator[] (size_t seq) inline
gets the index number for given gridpoint by its sequence number
Parameters
seq the sequence number of the index
Returns
gridpoint object (pointer)
operator[]() [2/2]
const HashGridPoint & sgpp::base::HashGridStorage::operator[] (size_t seq) const inline
gets the index number for given gridpoint by its sequence number
Parameters
seq the sequence number of the index
Returns
gridpoint object (constant pointer)
recalcLeafProperty()
void sgpp::base::HashGridStorage::recalcLeafProperty ()
Recalculates the leaf-property of every grid point.
This might be useful in case of a grid unserialization
References isContaining().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), deletePoints(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), and sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize().
serialize() [1/2]
std::string sgpp::base::HashGridStorage::serialize (int version = SERIALIZATION_VERSION) const
serialize the gridstorage into a string
Parameters
version the serialization version of the file
Returns
a string that contains all gridstorage information
References serialize().
Referenced by serialize(), sgpp::base::Grid::serialize(), python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
serialize() [2/2]
void sgpp::base::HashGridStorage::serialize (std::ostream & ostream, int version = SERIALIZATION_VERSION) const
serialize the gridstorage into a stream
Parameters
ostream reference to a stream into that all gridstorage information is written
version the serialization version of the file
References sgpp::base::Stretching::getStretchingMode(), sgpp::base::BoundingBox::serialize(), and sgpp::base::Stretching::serialize().
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
setAlgorithmicDimensions()
void sgpp::base::HashGridStorage::setAlgorithmicDimensions (std::vector< size_t > newAlgoDims)
sets the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
Parameters
newAlgoDims std::vector containing the algorithmic dimensions
Referenced by sgpp::base::Grid::setAlgorithmicDimensions().
setBoundingBox()
void sgpp::base::HashGridStorage::setBoundingBox (BoundingBox & boundingBox)
sets the bounding box of the current grid
Parameters
boundingBox bounding box to which the HashGridStorage's pointer is set
Referenced by sgpp::base::Grid::setBoundingBox().
setStretching()
void sgpp::base::HashGridStorage::setStretching (Stretching & stretching)
sets the stretching bounding box of the current grid
Parameters
stretching stretching to which the HashGridStorage's pointer is set
Referenced by sgpp::base::BsplineClenshawCurtisGrid::BsplineClenshawCurtisGrid(), sgpp::base::LinearClenshawCurtisBoundaryGrid::LinearClenshawCurtisBoundaryGrid(), sgpp::base::LinearClenshawCurtisGrid::LinearClenshawCurtisGrid(), sgpp::base::ModBsplineClenshawCurtisGrid::ModBsplineClenshawCurtisGrid(), sgpp::base::ModLinearClenshawCurtisGrid::ModLinearClenshawCurtisGrid(), sgpp::base::ModPolyClenshawCurtisGrid::ModPolyClenshawCurtisGrid(), sgpp::base::PolyClenshawCurtisBoundaryGrid::PolyClenshawCurtisBoundaryGrid(), sgpp::base::PolyClenshawCurtisGrid::PolyClenshawCurtisGrid(), and sgpp::base::Grid::setStretching().
store()
unsigned int sgpp::base::HashGridStorage::store (point_pointer index) inline
stores a given index in the hashmap
Parameters
index pointer to index that should be stored
Returns
sequence number
toString() [1/2]
std::string sgpp::base::HashGridStorage::toString () const
serialize the gridstorage's gridpoints into a stream
Returns
returns the string that contains all gridpoint information
References toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), and toString().
toString() [2/2]
void sgpp::base::HashGridStorage::toString (std::ostream & stream) const
serialize the gridstorage's gridpoints into a stream
Parameters
stream reference to a stream into that all gridpoint information is written
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
unserializeNoAlgoDims()
void sgpp::base::HashGridStorage::unserializeNoAlgoDims (std::string & istr)
unserializes the grid from a string, algorithmic dimensions are not reseted
Parameters
istr the string that contains the data
update()
void sgpp::base::HashGridStorage::update (point_type & index, size_t pos)
updates an already stored index
Parameters
index reference to the index that should be updated
pos position where the index should be stored
References insert().
Referenced by sgpp::base::HashGenerator::cliques_iter(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), python.uq.refinement.RefinementStrategy.Ranking::rank(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), and python.learner.LearnedKnowledge.LearnedKnowledge::setMemento().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/storage/hashmap/HashGridStorage.hpp
base/src/sgpp/base/grid/storage/hashmap/HashGridStorage.cpp