SG++-Doxygen-Documentation: sgpp::pde::OperationLaplacePrewavelet Class Reference
sgpp::pde::OperationLaplacePrewavelet Class Reference
Implementation for linear functions of Laplace Operation, prewavelet grids without boundaries.
#include <OperationLaplacePrewavelet.hpp>
Public Member Functions
OperationLaplacePrewavelet (sgpp::base::GridStorage *storage, sgpp::base::GridStorage *shadowstorage)
Constructor of OperationLaplacePrewavelet.
virtual ~OperationLaplacePrewavelet ()
Destructor.
Public Member Functions inherited from sgpp::pde::UpDownOneOpDimWithShadow
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
UpDownOneOpDimWithShadow (sgpp::base::GridStorage *storage, sgpp::base::GridStorage *shadowStorage)
Constructor.
virtual ~UpDownOneOpDimWithShadow ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
virtual void down (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D down operation
virtual void downOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D down operation that is only executed in one direction
virtual void up (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D up operation
virtual void upOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D up operation that is only executed in one direction
Protected Member Functions inherited from sgpp::pde::UpDownOneOpDimWithShadow
void expandGrid ()
This functions adds all grid points of the shadow storage into the actual grid.
void shrinkGrid ()
Removes the previously added shadow grid points from the actual grid.
virtual void specialOP (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
All calculations for op_dim.
void updown (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
Recursive procedure for updown().
Additional Inherited Members
Protected Types inherited from sgpp::pde::UpDownOneOpDimWithShadow
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Attributes inherited from sgpp::pde::UpDownOneOpDimWithShadow
sgpp::base::GridStorage * shadowStorage
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Detailed Description
Implementation for linear functions of Laplace Operation, prewavelet grids without boundaries.
With prewavelets the calculation of the gradient part of the up down algorithm is the more complicated one whereas the normal part is eased. For details on the implementation please refer to the documentation of the detail-classes LaplaceDownGradientPrewavelet.hpp, LaplaceUpGradientPrewavelet.hpp and LaplaceDownPrewavelet.hpp.
Constructor & Destructor Documentation
OperationLaplacePrewavelet()
sgpp::pde::OperationLaplacePrewavelet::OperationLaplacePrewavelet (sgpp::base::GridStorage * storage, sgpp::base::GridStorage * shadowstorage)
Constructor of OperationLaplacePrewavelet.
Parameters
storage Pointer to the grid's gridstorage obejct
shadowstorage shadow storage fuer prewavelets
~OperationLaplacePrewavelet()
sgpp::pde::OperationLaplacePrewavelet::~OperationLaplacePrewavelet () virtual
Destructor.
Member Function Documentation
down()
void sgpp::pde::OperationLaplacePrewavelet::down (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D down operation
Parameters
dim dimension in which to apply the down-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDimWithShadow.
downOpDim()
void sgpp::pde::OperationLaplacePrewavelet::downOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D down operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that down-Gradient is applied
Implements sgpp::pde::UpDownOneOpDimWithShadow.
References alpha, sgpp::pde::UpDownOneOpDimWithShadow::storage, and sgpp::base::sweep< FUNC >::sweep1D().
up()
void sgpp::pde::OperationLaplacePrewavelet::up (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D up operation
Parameters
dim dimension in which to apply the up-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDimWithShadow.
References alpha, sgpp::pde::UpDownOneOpDimWithShadow::storage, and sgpp::base::sweep< FUNC >::sweep1D().
upOpDim()
void sgpp::pde::OperationLaplacePrewavelet::upOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D up operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that up-Gradient is applied
Implements sgpp::pde::UpDownOneOpDimWithShadow.
References alpha, sgpp::pde::UpDownOneOpDimWithShadow::storage, and sgpp::base::sweep< FUNC >::sweep1D().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplacePrewavelet.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplacePrewavelet.cpp