SG++-Doxygen-Documentation: sgpp::pde::PhiPhiDownBBLinearStretched Class Reference
sgpp::pde::PhiPhiDownBBLinearStretched Class Reference
Implementation of sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\).
#include <PhiPhiDownBBLinearStretched.hpp>
Public Member Functions
virtual void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
PhiPhiDownBBLinearStretched (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiDownBBLinearStretched ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
recursive function for the calculation of Down with sgpp::base::Stretching
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage Object.
sgpp::base::Stretching * stretching
Pointer to the bounding box Obejct.
Detailed Description
Implementation of sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\).
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::PhiPhiDownBBLinearStretched::grid_iterator protected
Constructor & Destructor Documentation
PhiPhiDownBBLinearStretched()
sgpp::pde::PhiPhiDownBBLinearStretched::PhiPhiDownBBLinearStretched (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiDownBBLinearStretched()
sgpp::pde::PhiPhiDownBBLinearStretched::~PhiPhiDownBBLinearStretched () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiDownBBLinearStretched::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the down operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented in sgpp::pde::PhiPhiDownBBLinearStretchedBoundary.
References rec().
rec()
void sgpp::pde::PhiPhiDownBBLinearStretched::rec (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim, double fl, double fr) protected
recursive function for the calculation of Down with sgpp::base::Stretching
Parameters
source sgpp::base::DataVector that contains the coefficients of the ansatzfunction
result sgpp::base::DataVector in which the result of the operation is stored
index reference to a griditerator object that is used navigate through the grid
dim the dimension in which the operation is executed
fl function value on the left boundary
fr function value on the right boundary
References sgpp::base::HashGridIterator::get(), sgpp::base::Stretching::getAdjacentPositions(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, stretching, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), and rec().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::pde::PhiPhiDownBBLinearStretched::storage protected
Pointer to the sgpp::base::GridStorage Object.
Referenced by rec().
stretching
sgpp::base::Stretching* sgpp::pde::PhiPhiDownBBLinearStretched::stretching protected
Pointer to the bounding box Obejct.
Referenced by rec().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linearstretched/noboundary/algorithm_sweep/PhiPhiDownBBLinearStretched.hpp
pde/src/sgpp/pde/basis/linearstretched/noboundary/algorithm_sweep/PhiPhiDownBBLinearStretched.cpp