SG++-Doxygen-Documentation: sgpp::datadriven::LearnerVectorizedPerformanceCalculator Class Reference
sgpp::datadriven::LearnerVectorizedPerformanceCalculator Class Reference
Class that provides functionality in order to determine a LearnerVectorized's performance.
#include <LearnerVectorizedPerformanceCalculator.hpp>
Static Public Member Functions
static LearnerVectorizedPerformance getGFlopAndGByte (sgpp::base::Grid &Grid, size_t numInstances, sgpp::solver::SLESolverType solver, size_t numIterations, size_t sizeDatatype, bool reuseAlpha, bool verbose=false)
Calculate the performance of LearnerVectorized.
Detailed Description
Class that provides functionality in order to determine a LearnerVectorized's performance.
Member Function Documentation
getGFlopAndGByte()
LearnerVectorizedPerformance sgpp::datadriven::LearnerVectorizedPerformanceCalculator::getGFlopAndGByte (sgpp::base::Grid & Grid, size_t numInstances, sgpp::solver::SLESolverType solver, size_t numIterations, size_t sizeDatatype, bool reuseAlpha, bool verbose = false) static
Calculate the performance of LearnerVectorized.
Parameters
Grid reference to grid used bt the Learner
numInstances number of training instances
numIterations number of iterations the solver executed
solver the selected solver
sizeDatatype the size of the employed datatype in bytes
reuseAlpha set to true if the CG solver has reuseAlpha set to true
verbose prints some details to stdout
Returns
a LearnerVectorizedPerformance struct containing the results
References sgpp::solver::BiCGSTAB, g, sgpp::datadriven::LearnerVectorizedPerformance::GByte_, sgpp::base::HashGridPoint::get(), sgpp::datadriven::LearnerVectorizedPerformance::GFlop_, grid(), h, level, and sgpp::base::ModLinear.
Referenced by sgpp::datadriven::LearnerLeastSquaresIdentity::postProcessing().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/tools/LearnerVectorizedPerformanceCalculator.hpp
datadriven/src/sgpp/datadriven/tools/LearnerVectorizedPerformanceCalculator.cpp