SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI Class Reference
sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI Class Reference
#include <OperationCreateGraphMPI.hpp>
Public Member Functions
virtual void create_graph (std::vector< int > &result)
OperationGraphCreationMPI (sgpp::base::DataMatrix &data, int k)
virtual ~OperationGraphCreationMPI ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::GraphCreationWorker
GraphCreationWorker ()
GraphCreationWorker (sgpp::base::DataMatrix &data, int k)
void start_worker_main (void)
virtual ~GraphCreationWorker (void)
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual ~MPIWorkerBase (void)
Additional Inherited Members
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::GraphCreationWorker
void divide_workpackages (int *package, std::vector< int > &graph)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase
MPIWorkerGraphBase (sgpp::base::DataMatrix &data, int k)
MPIWorkerGraphBase (std::string operationName)
MPIWorkerGraphBase (std::string operationName, sgpp::base::DataMatrix &data, int k)
virtual ~MPIWorkerGraphBase (void)
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::GraphCreationWorker
double lambda
MPI_Comm & master_worker_comm
DensityOCLMultiPlatform::OperationCreateGraphOCL * op
bool opencl_node
bool overseer_node
MPI_Comm & sub_worker_comm
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase
double * dataset
int dataset_size
int dimensions
int k
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
bool verbose
Constructor & Destructor Documentation
OperationGraphCreationMPI()
sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::OperationGraphCreationMPI (sgpp::base::DataMatrix & data, int k) inline
~OperationGraphCreationMPI()
virtual sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::~OperationGraphCreationMPI () inline virtual
Member Function Documentation
create_graph()
virtual void sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::create_graph (std::vector< int > & result) inline virtual
References sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dataset_size, sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dimensions, sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::k, sgpp::datadriven::clusteringmpi::MPIWorkerBase::start_sub_workers(), and sgpp::datadriven::clusteringmpi::GraphCreationWorker::sub_worker_comm.
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationCreateGraphMPI.hpp