SG++-Doxygen-Documentation: sgpp::datadriven::StreamingModOCLUnified::Configuration Class Reference
sgpp::datadriven::StreamingModOCLUnified::Configuration Class Reference
#include <Configuration.hpp>
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
static const std::string & getKernelName ()
Member Function Documentation
augmentDefaultParameters()
static void sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), getKernelName(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::createStreamingModOCLUnifiedConfigured().
getKernelName()
static const std::string & sgpp::datadriven::StreamingModOCLUnified::Configuration::getKernelName () inline static
Referenced by augmentDefaultParameters(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLUnified< T >::OperationMultiEvalStreamingModOCLUnified().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingModOCLUnified/Configuration.hpp