SG++-Doxygen-Documentation: sgpp::base::ComponentScalarFunction Class Reference
sgpp::base::ComponentScalarFunction Class Reference
One component of a vector-valued function.
#include <ComponentScalarFunction.hpp>
Public Member Functions
void clone (std::unique_ptr< ScalarFunction > &clone) const override
ComponentScalarFunction (ScalarFunction &f, std::vector< double > defaultValues=std::vector< double >())
Constructor.
ComponentScalarFunction (VectorFunction &f, size_t k, std::vector< double > defaultValues=std::vector< double >())
Constructor.
double eval (const DataVector &x) override
~ComponentScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Protected Member Functions
void initialize ()
Protected Attributes
std::vector< double > defaultValues
vector of default values, indicating free variables with NAN
size_t dF
dimension of underlying function
ScalarFunction * fScalar
scalar-valued function
VectorFunction * fVector
vector-valued function
size_t k
index of component
DataVector tmpVec1
temporary vector 1
DataVector tmpVec2
temporary vector 2
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
One component of a vector-valued function.
Given a vector-valued \(f\colon [0, 1]^d \to \mathbb{R}^m\) and indices \(1 \le i_1 < \dotsb < i_n \le d\), this class represents a new function \(g\colon [0, 1]^n \to \mathbb{R}\) with \(g(y_{i_1}, \dotsc, y_{i_n}) := f_k(y_1, \dotsc, y_d)\), where \(y_t\) is constant for \(t \in \{i_1, \dotsc, i_n\}\).
The resulting function \(g\) is similar to a "slice plot" of the component \(f_k\) of \(f\).
Constructor & Destructor Documentation
ComponentScalarFunction() [1/2]
sgpp::base::ComponentScalarFunction::ComponentScalarFunction (ScalarFunction & f, std::vector< double > defaultValues = std::vector<double>()) inline
Constructor.
Use it like this: ComponentScalarFunction g(f, {NAN, NAN, 0.42}); where f is a scalar-valued function with 3 parameters. This selects the first two parameters of f, while constantly using 0.42 for the third parameter.
Parameters
f scalar-valued function
defaultValues Vector of constant default values. It can be either empty (the default) or a vector of exactly m doubles, each of which can be finite or NAN. If the vector is empty, it will be initialized as m NANs (i.e., no restriction of the parameter domain). Each NAN represents a free parameter \(x_t\), while the finite entries denote the constant values for the corresponding parameter.
References initialize().
ComponentScalarFunction() [2/2]
sgpp::base::ComponentScalarFunction::ComponentScalarFunction (VectorFunction & f, size_t k, std::vector< double > defaultValues = std::vector<double>()) inline
Constructor.
Use it like this: ComponentScalarFunction g(f, 3, {NAN, NAN, 0.42}); where f is a vector-valued function with 5 components and 3 parameters. This selects the first two parameters and the fourth component of f, while constantly using 0.42 for the third parameter.
Parameters
f vector-valued function (m components)
k index of component \(f_k\) to select (between 0 and m - 1)
defaultValues see other constructor
References initialize().
~ComponentScalarFunction()
sgpp::base::ComponentScalarFunction::~ComponentScalarFunction () inline override
Destructor.
Member Function Documentation
clone()
void sgpp::base::ComponentScalarFunction::clone (std::unique_ptr< ScalarFunction > & clone) const inline override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone().
Referenced by clone().
eval()
double sgpp::base::ComponentScalarFunction::eval (const DataVector & x) inline override virtual
Parameters
x evaluation point \(\vec{x} \in [0, 1]^n\)
Returns
\(g(\vec{x}) := f_k(y_1, \dotsc, y_d)\) where \((x_1, \dotsc, x_n) = (y_{i_1}, \dotsc, y_{i_n})\)
Implements sgpp::base::ScalarFunction.
References defaultValues, dF, sgpp::base::ScalarFunction::eval(), sgpp::base::VectorFunction::eval(), fScalar, fVector, k, tmpVec1, and tmpVec2.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
initialize()
void sgpp::base::ComponentScalarFunction::initialize () inline protected
References defaultValues, dF, and tmpVec1.
Referenced by ComponentScalarFunction(), and ComponentScalarFunction().
Member Data Documentation
defaultValues
std::vector<double> sgpp::base::ComponentScalarFunction::defaultValues protected
vector of default values, indicating free variables with NAN
Referenced by eval(), and initialize().
dF
size_t sgpp::base::ComponentScalarFunction::dF protected
dimension of underlying function
Referenced by eval(), and initialize().
fScalar
ScalarFunction* sgpp::base::ComponentScalarFunction::fScalar protected
scalar-valued function
Referenced by eval().
fVector
VectorFunction* sgpp::base::ComponentScalarFunction::fVector protected
vector-valued function
Referenced by eval().
k
size_t sgpp::base::ComponentScalarFunction::k protected
index of component
Referenced by eval(), python.uq.uq_setting.UQSettingManager.Sampler::expandSample(), python.uq.uq_setting.UQSettingManager.Sampler::reset(), and python.uq.uq_setting.UQSettingManager.Sampler::unitSample().
tmpVec1
DataVector sgpp::base::ComponentScalarFunction::tmpVec1 protected
temporary vector 1
Referenced by eval(), and initialize().
tmpVec2
DataVector sgpp::base::ComponentScalarFunction::tmpVec2 protected
temporary vector 2
Referenced by eval().
The documentation for this class was generated from the following file:
base/src/sgpp/base/function/scalar/ComponentScalarFunction.hpp