SG++-Doxygen-Documentation: sgpp::base::OperationEval Class Reference
sgpp::base::OperationEval Class Reference abstract
Operation that evaluates the current sparse grid function defined by the coefficient vector alpha at a given point.
#include <OperationEval.hpp>
Public Member Functions
virtual void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value)
virtual double eval (const DataVector &alpha, const DataVector &point)=0
Evaluates the sparse grid function at a given point.
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Detailed Description
Operation that evaluates the current sparse grid function defined by the coefficient vector alpha at a given point.
Constructor & Destructor Documentation
OperationEval()
sgpp::base::OperationEval::OperationEval () inline
Default constructor.
~OperationEval()
virtual sgpp::base::OperationEval::~OperationEval () inline virtual
Destructor.
Member Function Documentation
eval() [1/2]
virtual void sgpp::base::OperationEval::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) inline virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
Reimplemented in sgpp::base::OperationEvalBsplineBoundaryNaive, sgpp::base::OperationEvalBsplineClenshawCurtisNaive, sgpp::base::OperationEvalBsplineNaive, sgpp::base::OperationEvalFundamentalNakSplineNaive, sgpp::base::OperationEvalFundamentalSplineNaive, sgpp::base::OperationEvalLinearBoundaryNaive, sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive, sgpp::base::OperationEvalLinearClenshawCurtisNaive, sgpp::base::OperationEvalLinearNaive, sgpp::base::OperationEvalModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalModBsplineNaive, sgpp::base::OperationEvalModFundamentalSplineNaive, sgpp::base::OperationEvalModLinearClenshawCurtisNaive, sgpp::base::OperationEvalModLinearNaive, sgpp::base::OperationEvalModNakBsplineNaive, sgpp::base::OperationEvalModPolyClenshawCurtisNaive, sgpp::base::OperationEvalModPolyNaive, sgpp::base::OperationEvalModWaveletNaive, sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalNakBsplineBoundaryNaive, sgpp::base::OperationEvalNakBsplineExtendedNaive, sgpp::base::OperationEvalNakBsplineModifiedNaive, sgpp::base::OperationEvalNakBsplineNaive, sgpp::base::OperationEvalNakPBsplineNaive, sgpp::base::OperationEvalNaturalBsplineBoundaryNaive, sgpp::base::OperationEvalPolyBoundaryNaive, sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive, sgpp::base::OperationEvalPolyClenshawCurtisNaive, sgpp::base::OperationEvalPolyNaive, sgpp::base::OperationEvalWaveletBoundaryNaive, sgpp::base::OperationEvalWaveletNaive, sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive.
References alpha, eval(), and m.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
virtual double sgpp::base::OperationEval::eval (const DataVector & alpha, const DataVector & point) pure virtual
Evaluates the sparse grid function at a given point.
Parameters
alpha The coefficients of the sparse grid's basis functions
point The coordinates of the evaluation point
Implemented in sgpp::combigrid::OperationEvalFullGrid, sgpp::base::OperationEvalBsplineBoundaryNaive, sgpp::base::OperationEvalBsplineClenshawCurtisNaive, sgpp::base::OperationEvalBsplineNaive, sgpp::base::OperationEvalFundamentalNakSplineNaive, sgpp::base::OperationEvalFundamentalSplineNaive, sgpp::base::OperationEvalLinear, sgpp::base::OperationEvalLinearBoundary, sgpp::base::OperationEvalLinearBoundaryNaive, sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive, sgpp::base::OperationEvalLinearClenshawCurtisNaive, sgpp::base::OperationEvalLinearNaive, sgpp::base::OperationEvalLinearStretched, sgpp::base::OperationEvalLinearStretchedBoundary, sgpp::base::OperationEvalModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalModBsplineNaive, sgpp::base::OperationEvalModFundamentalSplineNaive, sgpp::base::OperationEvalModLinear, sgpp::base::OperationEvalModLinearClenshawCurtisNaive, sgpp::base::OperationEvalModLinearNaive, sgpp::base::OperationEvalModNakBsplineNaive, sgpp::base::OperationEvalModPoly, sgpp::base::OperationEvalModPolyClenshawCurtisNaive, sgpp::base::OperationEvalModPolyNaive, sgpp::base::OperationEvalModWaveletNaive, sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalNakBsplineBoundaryNaive, sgpp::base::OperationEvalNakBsplineExtendedNaive, sgpp::base::OperationEvalNakBsplineModifiedNaive, sgpp::base::OperationEvalNakBsplineNaive, sgpp::base::OperationEvalNakPBsplineNaive, sgpp::base::OperationEvalNaturalBsplineBoundaryNaive, sgpp::base::OperationEvalPeriodic, sgpp::base::OperationEvalPoly, sgpp::base::OperationEvalPolyBoundary, sgpp::base::OperationEvalPolyBoundaryNaive, sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive, sgpp::base::OperationEvalPolyClenshawCurtisNaive, sgpp::base::OperationEvalPolyNaive, sgpp::base::OperationEvalPrewavelet, sgpp::base::OperationEvalWaveletBoundaryNaive, sgpp::base::OperationEvalWaveletNaive, sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), eval(), sgpp::datadriven::ModelFittingDensityRatioEstimation::evaluate(), sgpp::datadriven::ModelFittingLeastSquares::evaluate(), sgpp::pde::PDESolver::evaluatePoint(), and sgpp::datadriven::LearnerSGDE::pdf().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationEval.hpp