SG++-Doxygen-Documentation: sgpp::base::LinearPeriodicBasis< LT, IT > Class Template Reference
sgpp::base::LinearPeriodicBasis< LT, IT > Class Template Reference
linear basis functions with boundaries And here we have another implicit dependence on tensor products
#include <LinearPeriodicBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
Evaluate a basis function.
double eval (LT level, IT index, double p, double q, double t)
Evaluate a basis function with an offset and scaling factor Has a dependence on the absolute position of grid point and support.
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
~LinearPeriodicBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Detailed Description
template<class LT, class IT>
class sgpp::base::LinearPeriodicBasis< LT, IT >
linear basis functions with boundaries And here we have another implicit dependence on tensor products
Constructor & Destructor Documentation
~LinearPeriodicBasis()
template<class LT , class IT > sgpp::base::LinearPeriodicBasis< LT, IT >::~LinearPeriodicBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::LinearPeriodicBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Evaluate a basis function.
Has a dependence on the absolute position of grid point and support.
Parameters
l the level of the current basis function
i the index of the current basis function
x the absolute position of the evaluation point
Implements sgpp::base::Basis< LT, IT >.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), and sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec().
eval() [2/2]
template<class LT , class IT > double sgpp::base::LinearPeriodicBasis< LT, IT >::eval (LT level, IT index, double p, double q, double t) inline
Evaluate a basis function with an offset and scaling factor Has a dependence on the absolute position of grid point and support.
Parameters
level the level of the current basis function
index the index of the current basis function
p the absolute position of the evaluation point
q the scaling factor of the basis function
t the offset of the basis function
References level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::LinearPeriodicBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::LinearPeriodicBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
getIntegral()
template<class LT , class IT > double sgpp::base::LinearPeriodicBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/LinearPeriodicBasis.hpp