SG++-Doxygen-Documentation: sgpp::base::Distribution Class Reference
sgpp::base::Distribution Class Reference abstract
stores a sparse grid not a knot B-spline interpolant in the framework of a respsonse surface
#include <Distribution.hpp>
Public Member Functions
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
virtual double eval (double x)=0
virtual sgpp::base::DataVector getBounds ()=0
virtual sgpp::base::DataVector getCharacteristics ()=0
return all relevant characteristic values (e.g.
virtual sgpp::base::DistributionType getType ()=0
virtual double sample ()=0
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Protected Attributes
std::default_random_engine gen
Detailed Description
stores a sparse grid not a knot B-spline interpolant in the framework of a respsonse surface
Constructor & Destructor Documentation
Distribution()
sgpp::base::Distribution::Distribution (typename std::chrono::system_clock::duration::rep seed = 777) inline
Constructor.
Parameters
seed if a seed should be set, ii.e. for precalculating and reusing grids set one here, otherwise a pseudo random seed is set automatically
References gen.
~Distribution()
virtual sgpp::base::Distribution::~Distribution () inline virtual
Destructor.
Member Function Documentation
eval()
virtual double sgpp::base::Distribution::eval (double x) pure virtual
Implemented in sgpp::base::DistributionBeta, sgpp::base::DistributionLogNormal, sgpp::base::DistributionNormal, sgpp::base::DistributionTruncExponential, sgpp::base::DistributionTruncGamma, sgpp::base::DistributionTruncNormal, and sgpp::base::DistributionUniform.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
virtual sgpp::base::DataVector sgpp::base::Distribution::getBounds () pure virtual
Implemented in sgpp::base::DistributionBeta, sgpp::base::DistributionLogNormal, sgpp::base::DistributionNormal, sgpp::base::DistributionTruncExponential, sgpp::base::DistributionTruncGamma, sgpp::base::DistributionTruncNormal, and sgpp::base::DistributionUniform.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
virtual sgpp::base::DataVector sgpp::base::Distribution::getCharacteristics () pure virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implemented in sgpp::base::DistributionBeta, sgpp::base::DistributionLogNormal, sgpp::base::DistributionNormal, sgpp::base::DistributionTruncExponential, sgpp::base::DistributionTruncGamma, sgpp::base::DistributionTruncNormal, and sgpp::base::DistributionUniform.
getType()
virtual sgpp::base::DistributionType sgpp::base::Distribution::getType () pure virtual
Implemented in sgpp::base::DistributionBeta, sgpp::base::DistributionLogNormal, sgpp::base::DistributionNormal, sgpp::base::DistributionTruncExponential, sgpp::base::DistributionTruncGamma, sgpp::base::DistributionTruncNormal, and sgpp::base::DistributionUniform.
sample()
virtual double sgpp::base::Distribution::sample () pure virtual
Implemented in sgpp::base::DistributionBeta, sgpp::base::DistributionLogNormal, sgpp::base::DistributionNormal, sgpp::base::DistributionTruncExponential, sgpp::base::DistributionTruncGamma, sgpp::base::DistributionTruncNormal, and sgpp::base::DistributionUniform.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList(), and samples().
samples()
sgpp::base::DataVector sgpp::base::Distribution::samples (size_t num)
References sample().
Referenced by python.uq.sampler.Sample.SamplesIterator::__next__(), python.uq.dists.DataDist.DataDist::cdf(), python.uq.dists.DataDist.DataDist::mean(), python.uq.dists.DataDist.DataDist::rvs(), python.uq.dists.LibAGFDist.LibAGFDist::rvs(), python.uq.dists.DataDist.DataDist::toJson(), and python.uq.dists.DataDist.DataDist::var().
Member Data Documentation
gen
std::default_random_engine sgpp::base::Distribution::gen protected
Referenced by Distribution(), python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList(), python.uq.uq_setting.UQSettingManager.Sampler::reset(), python.uq.uq_setting.UQSettingManager.UQSettingManager::run_distinct_paths(), python.uq.uq_setting.UQSettingManager.UQSettingManager::run_sensitivity(), sgpp::base::DistributionBeta::sample(), sgpp::base::DistributionLogNormal::sample(), sgpp::base::DistributionNormal::sample(), sgpp::base::DistributionTruncExponential::sample(), sgpp::base::DistributionTruncGamma::sample(), sgpp::base::DistributionTruncNormal::sample(), sgpp::base::DistributionUniform::sample(), and python.uq.uq_setting.UQSettingManager.Sampler::unitSample().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/Distribution.hpp
base/src/sgpp/base/tools/Distribution.cpp