SG++-Doxygen-Documentation: sgpp::base::PolyBoundaryBasis< LT, IT > Class Template Reference
sgpp::base::PolyBoundaryBasis< LT, IT > Class Template Reference
Polynomial basis functions with boundaries.
#include <PolyBoundaryBasis.hpp>
Public Member Functions
double eval (LT level, IT index, double p) override
Evaluate the basis function with given level and index.
double eval (LT level, IT index, double p, double offset, double width)
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
double evalHierToTop (LT level, IT index, DataVector &coeffs, double pos)
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
PolyBoundaryBasis (size_t degree)
Constructor.
~PolyBoundaryBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
SPolyBase polyBasis
poly basis
Detailed Description
template<class LT, class IT>
class sgpp::base::PolyBoundaryBasis< LT, IT >
Polynomial basis functions with boundaries.
Version
$HEAD$
Constructor & Destructor Documentation
PolyBoundaryBasis()
template<class LT , class IT > sgpp::base::PolyBoundaryBasis< LT, IT >::PolyBoundaryBasis (size_t degree) inline explicit
Constructor.
Parameters
degree the polynom's max. degree
~PolyBoundaryBasis()
template<class LT , class IT > sgpp::base::PolyBoundaryBasis< LT, IT >::~PolyBoundaryBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::PolyBoundaryBasis< LT, IT >::eval (LT level, IT index, double x) inline override virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyBasis< LT, IT >::eval(), level, and sgpp::base::PolyBoundaryBasis< LT, IT >::polyBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::PolyBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyBoundaryBasis< LT, IT >::evalHierToTop(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), and sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB().
eval() [2/2]
template<class LT , class IT > double sgpp::base::PolyBoundaryBasis< LT, IT >::eval (LT level, IT index, double p, double offset, double width) inline
References sgpp::base::PolyBoundaryBasis< LT, IT >::eval(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::PolyBoundaryBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyBasis< LT, IT >::evalDx(), level, and sgpp::base::PolyBoundaryBasis< LT, IT >::polyBasis.
Referenced by sgpp::pde::OperationLaplacePolyBoundary::mult().
evalHierToTop()
template<class LT , class IT > double sgpp::base::PolyBoundaryBasis< LT, IT >::evalHierToTop (LT level, IT index, DataVector & coeffs, double pos) inline
References sgpp::base::PolyBoundaryBasis< LT, IT >::eval(), and level.
Referenced by sgpp::base::DehierarchisationPolyBoundary::rec(), and sgpp::base::HierarchisationPolyBoundary::rec().
getDegree()
template<class LT , class IT > size_t sgpp::base::PolyBoundaryBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyBasis< LT, IT >::getDegree(), and sgpp::base::PolyBoundaryBasis< LT, IT >::polyBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::PolyBoundaryBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyBasis< LT, IT >::getIntegral(), level, and sgpp::base::PolyBoundaryBasis< LT, IT >::polyBasis.
Referenced by sgpp::base::OperationQuadraturePolyBoundary::doQuadrature().
Member Data Documentation
polyBasis
template<class LT , class IT > SPolyBase sgpp::base::PolyBoundaryBasis< LT, IT >::polyBasis protected
poly basis
Referenced by sgpp::base::PolyBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyBoundaryBasis< LT, IT >::evalDx(), sgpp::base::PolyBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::PolyBoundaryBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/PolyBoundaryBasis.hpp