SG++-Doxygen-Documentation: sgpp::base::OperationQuadrature Class Reference
sgpp::base::OperationQuadrature Class Reference abstract
This class provides the quadrature of a sparse grid function.
#include <OperationQuadrature.hpp>
Public Member Functions
virtual double doQuadrature (DataVector &alpha)=0
Integrate the sparse grid function.
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Detailed Description
This class provides the quadrature of a sparse grid function.
Constructor & Destructor Documentation
OperationQuadrature()
sgpp::base::OperationQuadrature::OperationQuadrature () inline
Constructor.
~OperationQuadrature()
virtual sgpp::base::OperationQuadrature::~OperationQuadrature () inline virtual
Destructor.
Member Function Documentation
doQuadrature()
virtual double sgpp::base::OperationQuadrature::doQuadrature (DataVector & alpha) pure virtual
Integrate the sparse grid function.
Parameters
alpha the function's values in the nodal basis
Implemented in sgpp::base::OperationQuadratureBspline, sgpp::base::OperationQuadratureBsplineBoundary, sgpp::base::OperationQuadratureBsplineClenshawCurtis, sgpp::base::OperationQuadratureFundamentalSpline, sgpp::base::OperationQuadratureLinear, sgpp::base::OperationQuadratureLinearBoundary, sgpp::base::OperationQuadratureLinearClenshawCurtis, sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary, sgpp::base::OperationQuadratureModBspline, sgpp::base::OperationQuadratureModBsplineClenshawCurtis, sgpp::base::OperationQuadratureModFundamentalSpline, sgpp::base::OperationQuadratureModLinear, sgpp::base::OperationQuadratureModLinearClenshawCurtis, sgpp::base::OperationQuadratureModPoly, sgpp::base::OperationQuadratureModPolyClenshawCurtis, sgpp::base::OperationQuadratureNakBsplineBoundary, sgpp::base::OperationQuadratureNakBsplineExtended, sgpp::base::OperationQuadratureNakBsplineModified, sgpp::base::OperationQuadratureNakPBspline, sgpp::base::OperationQuadraturePoly, sgpp::base::OperationQuadraturePolyBoundary, sgpp::base::OperationQuadraturePolyClenshawCurtis, sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary, sgpp::quadrature::OperationQuadratureMCAdvanced, and sgpp::base::OperationQuadratureMC.
Referenced by sgpp::optimization::SplineResponseSurface::getIntegral(), sgpp::optimization::SplineResponseSurfaceVector::getIntegrals(), sgpp::datadriven::SparseGridDensityEstimator::initialize(), and sgpp::datadriven::DBMatOnlineDE::normalizeQuadrature().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationQuadrature.hpp