SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T > Class Template Reference
sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T > Class Template Reference
OpenCL kernel for density based pruning of a graph.
#include <KernelPruneGraph.hpp>
Public Member Functions
KernelPruneGraph (std::shared_ptr< base::OCLDevice > dev, size_t dims, T treshold, size_t k, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node &kernelConfiguration, std::vector< int > &pointsVector, std::vector< T > &alphaVector, std::vector< T > &dataVector)
double prune_graph (std::vector< int > &graph, size_t startid, size_t chunksize)
Deletes nodes and edges in areas of low density.
~KernelPruneGraph ()
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
Adds all possible building parameters to the configuration if they do not exist yet.
Detailed Description
template<typename T>
class sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >
OpenCL kernel for density based pruning of a graph.
Constructor & Destructor Documentation
KernelPruneGraph()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::KernelPruneGraph (std::shared_ptr< base::OCLDevice > dev, size_t dims, T treshold, size_t k, std::shared_ptr< base::OCLManagerMultiPlatform > manager, json::Node & kernelConfiguration, std::vector< int > & pointsVector, std::vector< T > & alphaVector, std::vector< T > & dataVector) inline
References json::Node::getBool(), json::Node::getUInt(), and sgpp::base::OCLBufferWrapperSD< T >::intializeTo().
~KernelPruneGraph()
template<typename T > sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::~KernelPruneGraph () inline
Member Function Documentation
augmentDefaultParameters()
template<typename T > static void sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
Adds all possible building parameters to the configuration if they do not exist yet.
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters().
prune_graph()
template<typename T > double sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::prune_graph (std::vector< int > & graph, size_t startid, size_t chunksize) inline
Deletes nodes and edges in areas of low density.
References sgpp::datadriven::DensityOCLMultiPlatform::SourceBuilderPruneGraph< real_type >::generateSource(), sgpp::base::OCLBufferWrapperSD< T >::getBuffer(), sgpp::base::OCLBufferWrapperSD< T >::getHostPointer(), sgpp::base::OCLBufferWrapperSD< T >::intializeTo(), and sgpp::base::OCLBufferWrapperSD< T >::readFromBuffer().
Referenced by sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCLMultiPlatform< T >::prune_graph().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationPruneGraphOCL/KernelPruneGraph.hpp