SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL Class Reference
sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL Class Reference abstract
Pure virtual base class for the graph pruning operation.
#include <OperationPruneGraphOCL.hpp>
Public Member Functions
OperationPruneGraphOCL ()
virtual void prune_graph (std::vector< int > &graph, size_t startid=0, size_t chunksize=0)=0
Deletes all nodes and edges within areas of low density which are in the given graph chunk.
virtual ~OperationPruneGraphOCL (void)
Static Public Member Functions
static void load_default_parameters (base::OCLOperationConfiguration *parameters)
Detailed Description
Pure virtual base class for the graph pruning operation.
Constructor & Destructor Documentation
OperationPruneGraphOCL()
sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::OperationPruneGraphOCL () inline
~OperationPruneGraphOCL()
virtual sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::~OperationPruneGraphOCL (void) inline virtual
Member Function Documentation
load_default_parameters()
static void sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters (base::OCLOperationConfiguration * parameters) inline static
References json::DictNode::addIDAttr(), sgpp::datadriven::DensityOCLMultiPlatform::KernelPruneGraph< T >::augmentDefaultParameters(), and json::DictNode::contains().
Referenced by sgpp::datadriven::pruneNearestNeighborGraphConfigured(), sgpp::datadriven::pruneNearestNeighborGraphConfigured(), sgpp::datadriven::pruneNearestNeighborGraphConfigured(), and sgpp::datadriven::pruneNearestNeighborGraphConfigured().
prune_graph()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::prune_graph (std::vector< int > & graph, size_t startid = 0, size_t chunksize = 0) pure virtual
Deletes all nodes and edges within areas of low density which are in the given graph chunk.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::finalize_opencl_operation(), and main().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationPruneGraphOCL/OperationPruneGraphOCL.hpp