SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL Class Reference
sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL Class Reference abstract
Pure virtual base class for the k nearest neighbor opencl operation.
#include <OperationCreateGraphOCL.hpp>
Public Member Functions
virtual void begin_graph_creation (int startid, int chunksize)=0
virtual void create_graph (std::vector< int > &resultVector, int startid=0, int chunksize=0)=0
Pure virtual function to create the k nearest neighbor graph for some datapoints of a dataset.
virtual void finalize_graph_creation (std::vector< int > &resultVector, int startid, int chunksize)=0
OperationCreateGraphOCL ()
virtual ~OperationCreateGraphOCL (void)
Static Public Member Functions
static std::vector< size_t > find_clusters (std::vector< int > &graph, size_t k)
Assign a clusterindex for each datapoint using the connected components of the graph.
static void load_default_parameters (base::OCLOperationConfiguration *parameters)
Add the default parameters to the the configuration.
Static Protected Member Functions
static size_t find_neighbors (size_t index, std::vector< int > &nodes, size_t cluster, size_t k, std::vector< size_t > &clusterList, bool overwrite=false)
Recursive function for traversing the k nearest neighbor graph.
Detailed Description
Pure virtual base class for the k nearest neighbor opencl operation.
Constructor & Destructor Documentation
OperationCreateGraphOCL()
sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::OperationCreateGraphOCL () inline
~OperationCreateGraphOCL()
virtual sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::~OperationCreateGraphOCL (void) inline virtual
Member Function Documentation
begin_graph_creation()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::begin_graph_creation (int startid, int chunksize) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >.
Referenced by sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::begin_opencl_operation().
create_graph()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::create_graph (std::vector< int > & resultVector, int startid = 0, int chunksize = 0) pure virtual
Pure virtual function to create the k nearest neighbor graph for some datapoints of a dataset.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >.
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), main(), and sgpp::datadriven::clusteringmpi::GraphCreationWorker::start_worker_main().
finalize_graph_creation()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::finalize_graph_creation (std::vector< int > & resultVector, int startid, int chunksize) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCLSingleDevice< T >.
Referenced by sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::finalize_opencl_operation().
find_clusters()
static std::vector< size_t > sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::find_clusters (std::vector< int > & graph, size_t k) inline static
Assign a clusterindex for each datapoint using the connected components of the graph.
References find_neighbors().
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), and main().
find_neighbors()
static size_t sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::find_neighbors (size_t index, std::vector< int > & nodes, size_t cluster, size_t k, std::vector< size_t > & clusterList, bool overwrite = false) inline static protected
Recursive function for traversing the k nearest neighbor graph.
References find_neighbors().
Referenced by find_clusters(), and find_neighbors().
load_default_parameters()
static void sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters (base::OCLOperationConfiguration * parameters) inline static
Add the default parameters to the the configuration.
References json::DictNode::addIDAttr(), sgpp::datadriven::DensityOCLMultiPlatform::KernelCreateGraph< T >::augmentDefaultParameters(), and json::DictNode::contains().
Referenced by sgpp::datadriven::createNearestNeighborGraphConfigured(), sgpp::datadriven::createNearestNeighborGraphConfigured(), sgpp::datadriven::createNearestNeighborGraphConfigured(), and sgpp::datadriven::createNearestNeighborGraphConfigured().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationCreateGraphOCL/OperationCreateGraphOCL.hpp