SG++-Doxygen-Documentation: sgpp::datadriven::AbstractOperationMultipleEvalSubspace Class Reference
sgpp::datadriven::AbstractOperationMultipleEvalSubspace Class Reference abstract
#include <AbstractOperationMultipleEvalSubspace.hpp>
Public Member Functions
AbstractOperationMultipleEvalSubspace (base::Grid &grid, base::DataMatrix &dataset)
virtual size_t getAlignment ()=0
double getDuration () override
virtual size_t getPaddedDatasetSize ()
void mult (sgpp::base::DataVector &source, sgpp::base::DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multImpl (base::DataVector &alpha, base::DataVector &result, const size_t start_index_data, const size_t end_index_data)=0
void multTranspose (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
virtual void multTransposeImpl (sgpp::base::DataVector &source, sgpp::base::DataVector &result, const size_t start_index_data, const size_t end_index_data)=0
~AbstractOperationMultipleEvalSubspace () override
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual std::string getImplementationName ()
Name of this implementation of the operation.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual void prepare ()
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
virtual ~OperationMultipleEval ()
Destructor.
Static Public Member Functions
static size_t getChunkDataPoints ()
static size_t getChunkGridPoints ()
Protected Attributes
base::GridStorage * storage
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Constructor & Destructor Documentation
AbstractOperationMultipleEvalSubspace()
sgpp::datadriven::AbstractOperationMultipleEvalSubspace::AbstractOperationMultipleEvalSubspace (base::Grid & grid, base::DataMatrix & dataset) inline
~AbstractOperationMultipleEvalSubspace()
sgpp::datadriven::AbstractOperationMultipleEvalSubspace::~AbstractOperationMultipleEvalSubspace () inline override
Member Function Documentation
getAlignment()
virtual size_t sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getAlignment () pure virtual
Implemented in sgpp::datadriven::OperationMultipleEvalSubspaceCombined, and sgpp::datadriven::OperationMultipleEvalSubspaceSimple.
Referenced by mult(), and multTranspose().
getChunkDataPoints()
static size_t sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getChunkDataPoints () inline static
getChunkGridPoints()
static size_t sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getChunkGridPoints () inline static
getDuration()
double sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getDuration () inline override virtual
Implements sgpp::base::OperationMultipleEval.
getPaddedDatasetSize()
virtual size_t sgpp::datadriven::AbstractOperationMultipleEvalSubspace::getPaddedDatasetSize () inline virtual
Reimplemented in sgpp::datadriven::OperationMultipleEvalSubspaceCombined.
References sgpp::base::OperationMultipleEval::dataset, and sgpp::base::DataMatrix::getNrows().
Referenced by mult(), and multTranspose().
mult()
void sgpp::datadriven::AbstractOperationMultipleEvalSubspace::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) inline override virtual
Multiplication of \(B^T\) with vector \(\alpha\).
Parameters
alpha vector, to which \(B\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References getAlignment(), sgpp::datadriven::PartitioningTool::getOpenMPPartitionSegment(), getPaddedDatasetSize(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMultipleEval::isPrepared, multImpl(), sgpp::base::OperationMultipleEval::prepare(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::setAll(), sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
multImpl()
virtual void sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multImpl (base::DataVector & alpha, base::DataVector & result, const size_t start_index_data, const size_t end_index_data) pure virtual
Implemented in sgpp::datadriven::OperationMultipleEvalSubspaceCombined, and sgpp::datadriven::OperationMultipleEvalSubspaceSimple.
Referenced by mult().
multTranspose()
void sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTranspose (sgpp::base::DataVector & source, sgpp::base::DataVector & result) inline override virtual
Multiplication of \(B\) with vector \(\alpha\).
Parameters
source vector, to which \(B^T\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References alpha, getAlignment(), sgpp::datadriven::PartitioningTool::getOpenMPPartitionSegment(), getPaddedDatasetSize(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMultipleEval::isPrepared, multTransposeImpl(), sgpp::base::OperationMultipleEval::prepare(), sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::setAll(), sgpp::base::SGppStopwatch::start(), and sgpp::base::SGppStopwatch::stop().
multTransposeImpl()
virtual void sgpp::datadriven::AbstractOperationMultipleEvalSubspace::multTransposeImpl (sgpp::base::DataVector & source, sgpp::base::DataVector & result, const size_t start_index_data, const size_t end_index_data) pure virtual
Implemented in sgpp::datadriven::OperationMultipleEvalSubspaceCombined, and sgpp::datadriven::OperationMultipleEvalSubspaceSimple.
Referenced by multTranspose().
Member Data Documentation
storage
base::GridStorage* sgpp::datadriven::AbstractOperationMultipleEvalSubspace::storage protected
Referenced by sgpp::datadriven::OperationMultipleEvalSubspaceCombined::OperationMultipleEvalSubspaceCombined().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/AbstractOperationMultipleEvalSubspace.hpp