SG++-Doxygen-Documentation: sgpp::base::ConfigurationParameters Class Reference
sgpp::base::ConfigurationParameters Class Reference abstract
#include <ConfigurationParameters.hpp>
Public Member Functions
void clear ()
virtual std::shared_ptr< ConfigurationParameters > clone ()=0
ConfigurationParameters ()
ConfigurationParameters (std::string fileName, std::map< std::string, std::string > defaultParameters=std::map< std::string, std::string >())
std::string & get (const std::string &key)
bool getAsBoolean (const std::string &key)
std::vector< std::string > getAsList (const std::string &key)
uint64_t getAsUnsigned (const std::string &key)
std::vector< std::string > getKeys ()
void readFromFile (std::string fileName)
void readFromMap (const std::map< std::string, std::string > &parametersMap)
void set (const std::string key, std::string value)
void writeToFile (std::string fileName)
virtual ~ConfigurationParameters ()
Protected Attributes
std::map< std::string, std::string > parameters
Constructor & Destructor Documentation
ConfigurationParameters() [1/2]
sgpp::base::ConfigurationParameters::ConfigurationParameters ()
ConfigurationParameters() [2/2]
sgpp::base::ConfigurationParameters::ConfigurationParameters (std::string fileName, std::map< std::string, std::string > defaultParameters = std::map<std::string, std::string>())
References readFromFile(), and readFromMap().
~ConfigurationParameters()
sgpp::base::ConfigurationParameters::~ConfigurationParameters () virtual
Member Function Documentation
clear()
void sgpp::base::ConfigurationParameters::clear ()
References parameters.
clone()
virtual std::shared_ptr< ConfigurationParameters > sgpp::base::ConfigurationParameters::clone () pure virtual
Implemented in sgpp::base::OCLConfigurationParameters.
get()
std::string & sgpp::base::ConfigurationParameters::get (const std::string & key)
References parameters.
Referenced by getAsList().
getAsBoolean()
bool sgpp::base::ConfigurationParameters::getAsBoolean (const std::string & key)
References parameters.
getAsList()
std::vector< std::string > sgpp::base::ConfigurationParameters::getAsList (const std::string & key)
References get().
getAsUnsigned()
uint64_t sgpp::base::ConfigurationParameters::getAsUnsigned (const std::string & key)
References parameters.
getKeys()
std::vector< std::string > sgpp::base::ConfigurationParameters::getKeys ()
References parameters.
readFromFile()
void sgpp::base::ConfigurationParameters::readFromFile (std::string fileName)
References fileName, and parameters.
Referenced by ConfigurationParameters(), and sgpp::base::OCLConfigurationParameters::OCLConfigurationParameters().
readFromMap()
void sgpp::base::ConfigurationParameters::readFromMap (const std::map< std::string, std::string > & parametersMap)
References parameters.
Referenced by ConfigurationParameters(), and sgpp::base::OCLConfigurationParameters::OCLConfigurationParameters().
set()
void sgpp::base::ConfigurationParameters::set (const std::string key, std::string value)
References parameters.
writeToFile()
void sgpp::base::ConfigurationParameters::writeToFile (std::string fileName)
References fileName, and parameters.
Referenced by python.uq.uq_setting.UQSetting.UQSetting::run(), and python.uq.uq_setting.UQSetting.UQSetting::waitForResults().
Member Data Documentation
parameters
std::map<std::string, std::string> sgpp::base::ConfigurationParameters::parameters protected
Referenced by clear(), get(), getAsBoolean(), getAsUnsigned(), getKeys(), sgpp::base::OCLConfigurationParameters::OCLConfigurationParameters(), sgpp::base::OCLConfigurationParameters::OCLConfigurationParameters(), readFromFile(), readFromMap(), set(), and writeToFile().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/ConfigurationParameters.hpp
base/src/sgpp/base/tools/ConfigurationParameters.cpp