SG++-Doxygen-Documentation: sgpp::base::OperationEvalPrewavelet Class Reference
sgpp::base::OperationEvalPrewavelet Class Reference
This class implements OperationEval for a grids with prewavelet basis ansatzfunctions without boundaries.
#include <OperationEvalPrewavelet.hpp>
Public Member Functions
double eval (const DataVector &alpha, const DataVector &point) override
Evaluates the sparse grid function at a given point.
virtual double integrate (const DataVector &alpha)
OperationEvalPrewavelet (GridStorage &storage)
Constructor.
virtual double test (const DataVector &alpha, const DataVector &data, const DataVector &classes)
~OperationEvalPrewavelet () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
virtual void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value)
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
GridStorage & storage
Pointer to GridStorage object.
Detailed Description
This class implements OperationEval for a grids with prewavelet basis ansatzfunctions without boundaries.
Constructor & Destructor Documentation
OperationEvalPrewavelet()
sgpp::base::OperationEvalPrewavelet::OperationEvalPrewavelet (GridStorage & storage) inline explicit
Constructor.
Parameters
storage the grid's GridStorage object
~OperationEvalPrewavelet()
sgpp::base::OperationEvalPrewavelet::~OperationEvalPrewavelet () inline override
Destructor.
Member Function Documentation
eval()
double sgpp::base::OperationEvalPrewavelet::eval (const DataVector & alpha, const DataVector & point) override virtual
Evaluates the sparse grid function at a given point.
Parameters
alpha The coefficients of the sparse grid's basis functions
point The coordinates of the evaluation point
Implements sgpp::base::OperationEval.
References alpha, and storage.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
integrate()
double sgpp::base::OperationEvalPrewavelet::integrate (const DataVector & alpha) virtual
References alpha, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getSize(), level, and storage.
test()
double sgpp::base::OperationEvalPrewavelet::test (const DataVector & alpha, const DataVector & data, const DataVector & classes) virtual
Member Data Documentation
storage
GridStorage& sgpp::base::OperationEvalPrewavelet::storage protected
Pointer to GridStorage object.
Referenced by eval(), and integrate().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalPrewavelet.hpp
base/src/sgpp/base/operation/hash/OperationEvalPrewavelet.cpp