SG++-Doxygen-Documentation: sgpp::base::HashGridIterator Class Reference
sgpp::base::HashGridIterator Class Reference
This class can be used for storage agnostic algorithms.
#include <HashGridIterator.hpp>
Public Types
typedef HashGridPoint::index_type index_t
index type
typedef HashGridPoint index_type
type of grid points
typedef HashGridPoint::level_type level_t
level type
Public Member Functions
void get (size_t d, index_type::level_type &l, index_type::index_type &i) const
Gets level l and index i in dimension d of the current grid point.
level_t getGridDepth (size_t dim)
Returns the the maximal level of the grid in the given dimension.
HashGridIterator (HashGridIterator &copy)
Copy Constructor of the griditerator object.
HashGridIterator (HashGridStorage &storage)
Constructor of the griditerator object.
bool hint () const
returns true if there are no more children in any dimension
bool hintLeft (size_t d)
returns true if there are more left children in dimension d
bool hintRight (size_t d)
returns true if there are more right children in dimension d
bool isInnerPoint () const
determines if the grid point is an inner grid point
void leftChild (size_t dim)
left child in direction dim
void push (size_t d, index_type::level_type l, index_type::index_type i)
Sets level l and index i in dimension d of the current grid point.
void resetToLeftLevelZero (size_t dim)
left level zero ansatz function for a given dimension
void resetToLevelOne (size_t d)
resets the iterator to the top if dimension d
void resetToLevelZero ()
Sets 0,0 in every dimension (Left Level zero ansatzfunction)
void resetToRightLevelZero (size_t dim)
right level zero ansatz function for a given dimension
void rightChild (size_t dim)
right child in direction dim
size_t seq () const
returns the current sequence number
void set (const index_type &point)
Sets the iterator to a grid point.
void set (size_t d, index_type::level_type l, index_type::index_type i)
Sets level l and index i in dimension d of the current grid point.
void stepLeft (size_t d)
step left in direction dim
void stepRight (size_t d)
step right in direction dim
std::string toString ()
Generates a string with level and index of the gridpoint.
void up (size_t d)
hierarchical parent in direction dim
~HashGridIterator ()
Destructor.
Detailed Description
This class can be used for storage agnostic algorithms.
GridPoint has to support: constructor, get, set, push, rehash
Member Typedef Documentation
index_t
typedef HashGridPoint::index_type sgpp::base::HashGridIterator::index_t
index type
index_type
typedef HashGridPoint sgpp::base::HashGridIterator::index_type
type of grid points
level_t
typedef HashGridPoint::level_type sgpp::base::HashGridIterator::level_t
level type
Constructor & Destructor Documentation
HashGridIterator() [1/2]
sgpp::base::HashGridIterator::HashGridIterator (HashGridStorage & storage) explicit
Constructor of the griditerator object.
Parameters
storage reference to the hashmap that stores the grid points
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridPoint::push(), and sgpp::base::HashGridPoint::rehash().
HashGridIterator() [2/2]
sgpp::base::HashGridIterator::HashGridIterator (HashGridIterator & copy) explicit
Copy Constructor of the griditerator object.
Parameters
copy a HashGridIterator object that is used to build this instance
References get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridPoint::push(), and sgpp::base::HashGridPoint::rehash().
~HashGridIterator()
sgpp::base::HashGridIterator::~HashGridIterator ()
Destructor.
Member Function Documentation
get()
void sgpp::base::HashGridIterator::get (size_t d, index_type::level_type & l, index_type::index_type & i) const inline
Gets level l and index i in dimension d of the current grid point.
Parameters
d the dimension of interest
l the ansatz function's level
i the ansatz function's index
References sgpp::base::HashGridPoint::get().
Referenced by HashGridIterator(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::ConvertLinearToPrewavelet::operator()(), sgpp::base::ConvertPrewaveletToLinear::operator()(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpPrewavelet::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
getGridDepth()
HashGridIterator::level_t sgpp::base::HashGridIterator::getGridDepth (size_t dim)
Returns the the maximal level of the grid in the given dimension.
Parameters
dim the dimension
References sgpp::base::HashGridPoint::get(), hintLeft(), hintRight(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), leftChild(), rightChild(), and set().
Referenced by sgpp::base::ConvertLinearToPrewavelet::operator()(), sgpp::base::ConvertPrewaveletToLinear::operator()(), sgpp::base::DehierarchisationModLinearClenshawCurtis::operator()(), sgpp::base::DehierarchisationModPoly::operator()(), sgpp::base::DehierarchisationModPolyClenshawCurtis::operator()(), sgpp::base::DehierarchisationPoly::operator()(), sgpp::base::DehierarchisationPolyBoundary::operator()(), sgpp::base::DehierarchisationPolyClenshawCurtis::operator()(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationModLinearClenshawCurtis::operator()(), sgpp::base::HierarchisationModPoly::operator()(), sgpp::base::HierarchisationModPolyClenshawCurtis::operator()(), sgpp::base::HierarchisationPoly::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtis::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), and sgpp::pde::LaplaceUpGradientPrewavelet::operator()().
hint()
bool sgpp::base::HashGridIterator::hint () const
returns true if there are no more children in any dimension
Returns
returns true if there are no more children in any dimension
References sgpp::base::HashGridStorage::getPoint(), and sgpp::base::HashGridPoint::isLeaf().
Referenced by sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
hintLeft()
bool sgpp::base::HashGridIterator::hintLeft (size_t d)
returns true if there are more left children in dimension d
Parameters
d the moving direction
Returns
true if there are more left children in dimension d
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::isContaining(), and sgpp::base::HashGridPoint::set().
Referenced by getGridDepth(), sgpp::datadriven::ZeroCrossingRefinementFunctor::hasChild(), sgpp::pde::LaplaceUpPrewavelet::operator()(), and sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec().
hintRight()
bool sgpp::base::HashGridIterator::hintRight (size_t d)
returns true if there are more right children in dimension d
Parameters
d the moving direction
Returns
true if there are more right children in dimension d
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::isContaining(), and sgpp::base::HashGridPoint::set().
Referenced by getGridDepth(), sgpp::datadriven::ZeroCrossingRefinementFunctor::hasChild(), sgpp::pde::LaplaceUpPrewavelet::operator()(), and sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec().
isInnerPoint()
bool sgpp::base::HashGridIterator::isInnerPoint () const
determines if the grid point is an inner grid point
Returns
true if the grid point is an inner grid point
References sgpp::base::HashGridPoint::isInnerPoint().
leftChild()
void sgpp::base::HashGridIterator::leftChild (size_t dim)
left child in direction dim
Parameters
dim dimension in which we should step to the left child
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::BreadthFirstSearch< FUNC >::execute(), getGridDepth(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
push()
void sgpp::base::HashGridIterator::push (size_t d, index_type::level_type l, index_type::index_type i) inline
Sets level l and index i in dimension d of the current grid point.
Does not recompute hash value of the current grid point.
Parameters
d the dimension of the gridpoint
l the ansatz function's level
i the ansatz function's index
References sgpp::base::HashGridPoint::push().
Referenced by sgpp::base::OperationMultipleEvalInterModLinear::mult(), and sgpp::base::OperationMultipleEvalInterModLinear::multTranspose().
resetToLeftLevelZero()
void sgpp::base::HashGridIterator::resetToLeftLevelZero (size_t dim)
left level zero ansatz function for a given dimension
Parameters
dim dimension in which we should step to level zero
References sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationPolyBoundary::operator()(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
resetToLevelOne()
void sgpp::base::HashGridIterator::resetToLevelOne (size_t d)
resets the iterator to the top if dimension d
Parameters
d the moving direction
References sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
resetToLevelZero()
void sgpp::base::HashGridIterator::resetToLevelZero ()
Sets 0,0 in every dimension (Left Level zero ansatzfunction)
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridPoint::push(), and sgpp::base::HashGridPoint::rehash().
Referenced by sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::operator()(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), and sgpp::base::sweep< FUNC >::sweep1D_Boundary().
resetToRightLevelZero()
void sgpp::base::HashGridIterator::resetToRightLevelZero (size_t dim)
right level zero ansatz function for a given dimension
Parameters
dim dimension in which we should step to level zero
References sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationPolyBoundary::operator()(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
rightChild()
void sgpp::base::HashGridIterator::rightChild (size_t dim)
right child in direction dim
Parameters
dim dimension in which we should step to the right child
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by getGridDepth(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), and sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB().
seq()
size_t sgpp::base::HashGridIterator::seq () const
returns the current sequence number
Returns
the current sequence number
Referenced by python.learner.folding.FoldingPolicy.FoldingPolicy::createFoldsets(), sgpp::base::BreadthFirstSearch< FUNC >::execute(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationModFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalNakSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationModFundamentalSpline::operator()(), sgpp::base::ConvertLinearToPrewavelet::operator()(), sgpp::base::ConvertPrewaveletToLinear::operator()(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationPolyBoundary::operator()(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::operator()(), sgpp::base::HierarchisationPolyBoundary::operator()(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::operator()(), sgpp::base::DehierarchisationLinearBoundary::operator()(), sgpp::base::DehierarchisationLinearStretchedBoundary::operator()(), sgpp::base::HierarchisationLinearBoundary::operator()(), sgpp::base::HierarchisationLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpPrewavelet::operator()(), sgpp::base::AlgorithmEvaluation< BASIS >::rec(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearPeriodicBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec(), sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
set() [1/2]
void sgpp::base::HashGridIterator::set (const index_type & point) inline
Sets the iterator to a grid point.
Recomputes the hash value of the current grid point.
Parameters
point new grid point
References sgpp::base::HashGridStorage::getSequenceNumber().
set() [2/2]
void sgpp::base::HashGridIterator::set (size_t d, index_type::level_type l, index_type::index_type i) inline
Sets level l and index i in dimension d of the current grid point.
Recomputes the hash value of the current grid point.
Parameters
d the dimension of interest
l the ansatz function's level
i the ansatz function's index
References sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::BreadthFirstSearch< FUNC >::execute(), getGridDepth(), sgpp::datadriven::ZeroCrossingRefinementFunctor::hasChild(), sgpp::base::OperationMultipleEvalInterModLinear::mult(), sgpp::base::OperationMultipleEvalInterModLinear::multTranspose(), sgpp::base::ConvertLinearToPrewavelet::operator()(), sgpp::base::ConvertPrewaveletToLinear::operator()(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpGradientPrewavelet::operator()(), sgpp::pde::LaplaceUpPrewavelet::operator()(), and sgpp::base::GetAffectedBasisFunctions< PrewaveletBasis< unsigned int, unsigned int > >::rec().
stepLeft()
void sgpp::base::HashGridIterator::stepLeft (size_t d)
step left in direction dim
Parameters
d the moving direction
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
stepRight()
void sgpp::base::HashGridIterator::stepRight (size_t d)
step right in direction dim
Parameters
d the moving direction
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::BreadthFirstSearch< FUNC >::execute(), sgpp::pde::LaplaceDownGradientPrewavelet::operator()(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
toString()
std::string sgpp::base::HashGridIterator::toString ()
Generates a string with level and index of the gridpoint.
Returns
string into which the gridpoint is written
References sgpp::base::HashGridPoint::toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
up()
void sgpp::base::HashGridIterator::up (size_t d)
hierarchical parent in direction dim
Parameters
d the moving direction
References sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getSequenceNumber(), and sgpp::base::HashGridPoint::set().
Referenced by sgpp::base::BreadthFirstSearch< FUNC >::execute(), sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationModPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPoly::rec(), sgpp::base::DehierarchisationPolyBoundary::rec(), sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), sgpp::base::DehierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationModLinearClenshawCurtis::rec(), sgpp::base::HierarchisationModPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPoly::rec(), sgpp::base::HierarchisationPolyBoundary::rec(), sgpp::base::HierarchisationPolyClenshawCurtis::rec(), sgpp::base::HierarchisationPolyClenshawCurtisBoundary::rec(), sgpp::base::DehierarchisationModPoly::rec(), sgpp::base::HierarchisationModPoly::rec(), sgpp::base::DehierarchisationLinear::rec(), sgpp::base::DehierarchisationLinearStretched::rec(), sgpp::base::DehierarchisationModLinear::rec(), sgpp::base::HierarchisationLinear::rec(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HierarchisationModLinear::rec(), sgpp::base::DehierarchisationLinearClenshawCurtis::rec(), sgpp::base::DehierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::HierarchisationLinearClenshawCurtis::rec(), sgpp::base::HierarchisationLinearClenshawCurtisBoundary::rec(), sgpp::base::StencilDehierarchisationLinear::rec(), sgpp::base::StencilDehierarchisationModLinear::rec(), sgpp::base::StencilHierarchisationLinear::rec(), sgpp::base::StencilHierarchisationModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::dPhidPhiUpModLinear::rec(), sgpp::pde::PhiPhiUpBBLinear::rec(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::pde::PhiPhiUpModLinear::rec(), sgpp::pde::dPhidPhiDownModLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinearStretched::rec(), sgpp::pde::PhiPhiDownModLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::PhiPhiUpBBLinear::recBB(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/storage/hashmap/HashGridIterator.hpp
base/src/sgpp/base/grid/storage/hashmap/HashGridIterator.cpp