SG++-Doxygen-Documentation: sgpp::base::DistributionNormal Class Reference
sgpp::base::DistributionNormal Class Reference
#include <DistributionNormal.hpp>
Public Member Functions
DistributionNormal (double mean, double stddev)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
According to Wikipedia (https://de.wikipedia.org/wiki/Normalverteilung#Streuintervalle) inside the interval [mean-z*sigma,mean+z*sigma] lie 2*Phi(z)-1 of the mass of the normal distribution.
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionNormal ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Constructor & Destructor Documentation
DistributionNormal()
sgpp::base::DistributionNormal::DistributionNormal (double mean, double stddev) inline
Constructor.
~DistributionNormal()
virtual sgpp::base::DistributionNormal::~DistributionNormal () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionNormal::eval (double x) inline virtual
Implements sgpp::base::Distribution.
References M_PI.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionNormal::getBounds () inline virtual
According to Wikipedia (https://de.wikipedia.org/wiki/Normalverteilung#Streuintervalle) inside the interval [mean-z*sigma,mean+z*sigma] lie 2*Phi(z)-1 of the mass of the normal distribution.
For z = 7 less than 10^(-9) are outside [mean - 7*sigma, mean + 7*sigma] For z = 8 less than 10^(-14) are outside [mean - 8*sigma, mean + 8*sigma] For z = 9 less than 10^(-18) are outside [mean - 9*sigma, mean + 9*sigma]
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionNormal::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionNormal::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Normal.
sample()
double sgpp::base::DistributionNormal::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionNormal.hpp