SG++-Doxygen-Documentation: sgpp::base::HashRefinement Class Reference
sgpp::base::HashRefinement Class Reference
Free refinement class for sparse grids.
#include <HashRefinement.hpp>
Public Member Functions
void free_refine (GridStorage &storage, RefinementFunctor &functor, std::vector< size_t > *addedPoints=nullptr) override
Refines a grid according to a RefinementFunctor provided.
size_t getNumberOfRefinablePoints (GridStorage &storage) override
Computes and returns the number of grid points, which can be refined.
void refineGridpoint1D (GridStorage &storage, GridPoint &point, size_t d) override
Refine one grid point along a single direction.
void refineGridpoint1D (GridStorage &storage, size_t seq, size_t d) override
Refine one grid point along a single direction.
~HashRefinement () override
Public Member Functions inherited from sgpp::base::AbstractRefinement
virtual size_t getIndexOfMin (RefinementFunctor::value_type *array, size_t length)
Returns the index of the first occurrence of minimal element in array.
bool isRefinable (GridStorage &storage, GridPoint &point)
Check if the grid point is refinable.
virtual ~AbstractRefinement ()
Destructor.
Protected Member Functions
virtual void addElementToCollection (const GridStorage::grid_map_iterator &iter, AbstractRefinement::refinement_list_type current_value_list, size_t refinements_num, AbstractRefinement::refinement_container_type &collection)
Adds elements to the collection.
void collectRefinablePoints (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection) override
Examines the grid points and stores the indices those that can be refined and have maximal indicator values.
void createGridpoint (GridStorage &storage, GridPoint &point) override
This method creates a new point on the grid.
AbstractRefinement::refinement_list_type getIndicator (GridStorage &storage, const GridStorage::grid_map_iterator &iter, const RefinementFunctor &functor) const override
Generates a list with indicator elements.
void refineGridpoint (GridStorage &storage, size_t refine_index) override
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
void refineGridpointsCollection (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection) override
Extends the grid adding elements defined in collection.
Protected Member Functions inherited from sgpp::base::AbstractRefinement
virtual void createGridpoint1D (GridPoint &point, size_t d, GridStorage &storage, index_t &source_index, level_t &source_level)
Creates children grid points along single direction.
virtual void createGridpointSubroutine (GridStorage &storage, GridPoint &point)
Subroutine for grid point creation.
Additional Inherited Members
Public Types inherited from sgpp::base::AbstractRefinement
typedef std::vector< refinement_pair_type > refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
typedef AbstractRefinement_refinement_key refinement_key_type
Type of the identifier of the refinement atom (e.g.
typedef std::forward_list< AbstractRefinement::refinement_pair_type > refinement_list_type
typedef std::pair< std::shared_ptr< refinement_key_type >, refinement_value_type > refinement_pair_type
Pair for the refinement key and value.
typedef double refinement_value_type
Type of functor value assigned to each refinement atom.
Static Public Member Functions inherited from sgpp::base::AbstractRefinement
static bool compare_pairs (const refinement_pair_type &lhs, const refinement_pair_type &rhs)
Comparison of the refinement_pair_type.
Detailed Description
Free refinement class for sparse grids.
Constructor & Destructor Documentation
~HashRefinement()
sgpp::base::HashRefinement::~HashRefinement () inline override
Member Function Documentation
addElementToCollection()
void sgpp::base::HashRefinement::addElementToCollection (const GridStorage::grid_map_iterator & iter, AbstractRefinement::refinement_list_type current_value_list, size_t refinements_num, AbstractRefinement::refinement_container_type & collection) protected virtual
Adds elements to the collection.
This method is responsible for selection the elements with most important indicators and to limit the size of collection to refinements_num elements.
Parameters
iter storage iterator
current_value_list list with elements that contain keys and values that specify refinement
refinements_num number of elements to refine
collection container where element pairs for refinement need to be stored
References sgpp::base::AbstractRefinement::compare_pairs().
Referenced by sgpp::optimization::HashRefinementMultiple::collectRefinablePoints(), collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), and sgpp::base::MultipleClassRefinement::collectRefinablePoints().
collectRefinablePoints()
void sgpp::base::HashRefinement::collectRefinablePoints (GridStorage & storage, RefinementFunctor & functor, AbstractRefinement::refinement_container_type & collection) override protected virtual
Examines the grid points and stores the indices those that can be refined and have maximal indicator values.
Parameters
storage hashmap that stores the grid points
functor a PredictiveRefinementIndicator specifying the refinement criteria
collection container that contains elements to refine (empty initially)
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::optimization::HashRefinementMultiple, sgpp::base::HashRefinementInteraction, and sgpp::base::MultipleClassRefinement.
References addElementToCollection(), sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), sgpp::base::HashGridStorage::getDimension(), getIndicator(), and sgpp::base::RefinementFunctor::getRefinementsNum().
Referenced by free_refine().
createGridpoint()
void sgpp::base::HashRefinement::createGridpoint (GridStorage & storage, GridPoint & point) override protected virtual
This method creates a new point on the grid.
It checks if some parents or children are needed in other dimensions.
Parameters
storage hashmap that stores the gridpoints
point The point that should be inserted
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::HashRefinementInteraction, and sgpp::base::HashRefinementInconsistent.
References sgpp::base::AbstractRefinement::createGridpoint1D(), sgpp::base::HashGridStorage::getDimension(), and sgpp::base::HashGridStorage::insert().
Referenced by refineGridpoint1D().
free_refine()
void sgpp::base::HashRefinement::free_refine (GridStorage & storage, RefinementFunctor & functor, std::vector< size_t > * addedPoints = nullptr) override virtual
Refines a grid according to a RefinementFunctor provided.
Refines up to RefinementFunctor::getRefinementsNum() grid points if possible, and if their refinement value is larger than RefinementFunctor::start() and their absolute value is larger or equal than RefinementFunctor::getRefinementThreshold() If addedPoints is supplied and not a zero pointer, then newly created grid points are appended to this vector.
Parameters
storage hashmap that stores the grid points
functor a RefinementFunctor specifying the refinement criteria
addedPoints pointer to vector to append newly created grid points to
Assumption: during the refinement process the only change made to the storage is the following: New (if any) gridpoints are appended (to the end) of the storage
Implements sgpp::base::AbstractRefinement.
References collectRefinablePoints(), sgpp::base::HashGridStorage::getSize(), and refineGridpointsCollection().
Referenced by sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorSOO::generate(), sgpp::base::PrewaveletGridGenerator::refine(), and sgpp::base::StandardGridGenerator::refine().
getIndicator()
AbstractRefinement::refinement_list_type sgpp::base::HashRefinement::getIndicator (GridStorage & storage, const GridStorage::grid_map_iterator & iter, const RefinementFunctor & functor) const override protected virtual
Generates a list with indicator elements.
Parameters
storage grid storage
iter iterator
functor refinement functor
Returns
list with indicator elements
Implements sgpp::base::AbstractRefinement.
Referenced by sgpp::optimization::HashRefinementMultiple::collectRefinablePoints(), collectRefinablePoints(), sgpp::base::HashRefinementInteraction::collectRefinablePoints(), and sgpp::base::MultipleClassRefinement::collectRefinablePoints().
getNumberOfRefinablePoints()
size_t sgpp::base::HashRefinement::getNumberOfRefinablePoints (GridStorage & storage) override virtual
Computes and returns the number of grid points, which can be refined.
This is the number of grid points that have at least one child missing.
Parameters
storage hashmap that stores the grid points
Returns
The number of grid points that can be refined
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::optimization::HashRefinementMultiple.
References sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), sgpp::base::HashGridStorage::getDimension(), and sgpp::base::HashGridStorage::getSize().
Referenced by sgpp::base::PrewaveletGridGenerator::getNumberOfRefinablePoints(), and sgpp::base::StandardGridGenerator::getNumberOfRefinablePoints().
refineGridpoint()
void sgpp::base::HashRefinement::refineGridpoint (GridStorage & storage, size_t refine_index) override protected virtual
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
Parameters
storage hashmap that stores the gridpoints
refine_index The index in the hashmap of the point that should be refined
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::MultipleClassRefinement.
References sgpp::base::HashGridStorage::getDimension(), and refineGridpoint1D().
Referenced by refineGridpointsCollection().
refineGridpoint1D() [1/2]
void sgpp::base::HashRefinement::refineGridpoint1D (GridStorage & storage, GridPoint & point, size_t d) override virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
point point to refine
d direction
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::optimization::HashRefinementMultiple.
References createGridpoint(), and sgpp::base::HashGridStorage::isContaining().
Referenced by sgpp::base::ANOVAHashRefinement::refineGridpoint(), refineGridpoint(), and refineGridpoint1D().
refineGridpoint1D() [2/2]
void sgpp::base::HashRefinement::refineGridpoint1D (GridStorage & storage, size_t seq, size_t d) override virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
seq sequential number of the grid point
d direction
Reimplemented from sgpp::base::AbstractRefinement.
References sgpp::base::HashGridStorage::getPoint(), and refineGridpoint1D().
refineGridpointsCollection()
void sgpp::base::HashRefinement::refineGridpointsCollection (GridStorage & storage, RefinementFunctor & functor, AbstractRefinement::refinement_container_type & collection) override protected virtual
Extends the grid adding elements defined in collection.
Parameters
storage hashmap that stores the grid points
functor a PredictiveRefinementIndicator specifying the refinement criteria
collection container that contains elements to refine (empty initially)
Implements sgpp::base::AbstractRefinement.
References sgpp::base::RefinementFunctor::getRefinementThreshold(), and refineGridpoint().
Referenced by free_refine().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/hashmap/HashRefinement.hpp
base/src/sgpp/base/grid/generation/hashmap/HashRefinement.cpp