SG++-Doxygen-Documentation: sgpp::base::OperationEvalNakBsplineExtendedNaive Class Reference
sgpp::base::OperationEvalNakBsplineExtendedNaive Class Reference
Operation for evaluating Extended B-spline linear combinations on Noboundary grids.
#include <OperationEvalNakBsplineExtendedNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalNakBsplineExtendedNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalNakBsplineExtendedNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SNakBsplineExtendedBase base
1D B-spline basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Detailed Description
Operation for evaluating Extended B-spline linear combinations on Noboundary grids.
Constructor & Destructor Documentation
OperationEvalNakBsplineExtendedNaive()
sgpp::base::OperationEvalNakBsplineExtendedNaive::OperationEvalNakBsplineExtendedNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalNakBsplineExtendedNaive()
sgpp::base::OperationEvalNakBsplineExtendedNaive::~OperationEvalNakBsplineExtendedNaive () inline override
Destructor.
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalNakBsplineExtendedNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::NakBsplineExtendedBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalNakBsplineExtendedNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::NakBsplineExtendedBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SNakBsplineExtendedBase sgpp::base::OperationEvalNakBsplineExtendedNaive::base protected
1D B-spline basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalNakBsplineExtendedNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalNakBsplineExtendedNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalNakBsplineExtendedNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalNakBsplineExtendedNaive.cpp