SG++-Doxygen-Documentation: sgpp::solver::BiCGStab Class Reference
sgpp::solver::BiCGStab Class Reference
#include <BiCGStab.hpp>
Public Member Functions
BiCGStab (size_t imax, double epsilon)
Std-Constructor.
virtual void solve (sgpp::base::OperationMatrix &SystemMatrix, sgpp::base::DataVector &alpha, sgpp::base::DataVector &b, bool reuse=false, bool verbose=false, double max_threshold=-1.0)
max_threashold is ignored in this solver
virtual ~BiCGStab ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SLESolver
SLESolver (size_t imax, double epsilon)
Std-Constructor.
virtual ~SLESolver ()
Std-Destructor.
Public Member Functions inherited from sgpp::solver::SGSolver
double getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
double getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (double eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolver (size_t nMaximumIterations, double epsilon)
Std-Constructor.
virtual ~SGSolver ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolver
double myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
double residuum
residuum
Constructor & Destructor Documentation
BiCGStab()
sgpp::solver::BiCGStab::BiCGStab (size_t imax, double epsilon)
Std-Constructor.
~BiCGStab()
sgpp::solver::BiCGStab::~BiCGStab () virtual
Std-Destructor.
Member Function Documentation
solve()
void sgpp::solver::BiCGStab::solve (sgpp::base::OperationMatrix & SystemMatrix, sgpp::base::DataVector & alpha, sgpp::base::DataVector & b, bool reuse = false, bool verbose = false, double max_threshold = -1.0) virtual
max_threashold is ignored in this solver
Reference: http://www.iue.tuwien.ac.at/phd/heinreichsberger/node70.html http://www.numerik.math.tu-graz.ac.at/kurse/lgs/SIMNET6.pdf http://netlib.org
Implements sgpp::solver::SLESolver.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVector::dotProduct(), sgpp::base::DataVector::getSize(), sgpp::base::OperationMatrix::mult(), sgpp::solver::SGSolver::myEpsilon, sgpp::solver::SGSolver::nIterations, sgpp::solver::SGSolver::nMaxIterations, sgpp::solver::SGSolver::residuum, and sgpp::base::DataVector::setAll().
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/sle/BiCGStab.hpp
solver/src/sgpp/solver/sle/BiCGStab.cpp