SG++-Doxygen-Documentation: json::ListNode Class Reference
json::ListNode Class Reference
#include <ListNode.hpp>
Public Member Functions
Node & addDictValue () override
Node & addIdValue (const bool &value) override
Node & addIdValue (const char *value) override
Node & addIdValue (const double &value) override
Node & addIdValue (const int64_t &value) override
Node & addIdValue (const std::string &value) override
Node & addIdValue (const uint64_t &value) override
Node & addListValue () override
Node & addTextValue (const std::string &value) override
void addValue (std::unique_ptr< Node > node) override
Node * clone () override
std::unique_ptr< Node > erase (Node &node) override
ListNode ()
ListNode (const ListNode &original)
ListNode & operator= (const ListNode &right)
Node & operator= (const Node &right) override
Node & operator[] (const size_t index) override
void parse (std::vector< Token > &stream) override
std::unique_ptr< Node > removeValue (size_t index) override
void serialize (std::ostream &outFile, size_t indentWidth) override
size_t size () override
Public Member Functions inherited from json::Node
virtual void addAttribute (const std::string &name, std::unique_ptr< Node > node)
virtual Node & addDictAttr (const std::string &name)
virtual Node & addIDAttr (const std::string &name, const bool &value)
virtual Node & addIDAttr (const std::string &name, const char *value)
virtual Node & addIDAttr (const std::string &name, const double &value)
virtual Node & addIDAttr (const std::string &name, const int64_t &value)
virtual Node & addIDAttr (const std::string &name, const std::string &value)
virtual Node & addIDAttr (const std::string &name, const uint64_t &value)
virtual Node & addListAttr (const std::string &name)
virtual Node & addTextAttr (const std::string &name, const std::string &value)
virtual bool contains (const std::string &key)
virtual std::unique_ptr< Node > erase ()
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
virtual std::vector< std::string > & keys ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const std::string &key)
virtual std::unique_ptr< Node > removeAttribute (const std::string name)
virtual Node & replaceDictAttr (const std::string &name)
virtual Node & replaceIDAttr (const std::string &name, const bool &value)
virtual Node & replaceIDAttr (const std::string &name, const char *value)
virtual Node & replaceIDAttr (const std::string &name, const double &value)
virtual Node & replaceIDAttr (const std::string &name, const int64_t &value)
virtual Node & replaceIDAttr (const std::string &name, const std::string &value)
virtual Node & replaceIDAttr (const std::string &name, const uint64_t &value)
virtual Node & replaceListAttr (const std::string &name)
virtual Node & replaceTextAttr (const std::string &name, const std::string &value)
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual ~Node ()=default
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
ListNode() [1/2]
json::ListNode::ListNode ()
Referenced by addListValue(), clone(), and parse().
ListNode() [2/2]
json::ListNode::ListNode (const ListNode & original)
References json::Node::orderedKeyIndex, and json::Node::parent.
Member Function Documentation
addDictValue()
Node & json::ListNode::addDictValue () override virtual
Reimplemented from json::Node.
References addValue().
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
addIdValue() [1/6]
Node & json::ListNode::addIdValue (const bool & value) override virtual
Reimplemented from json::Node.
References addValue().
addIdValue() [2/6]
Node & json::ListNode::addIdValue (const char * value) override virtual
Reimplemented from json::Node.
References addIdValue().
Referenced by addIdValue(), and sgpp::datadriven::DBMatDatabase::putDataMatrix().
addIdValue() [3/6]
Node & json::ListNode::addIdValue (const double & value) override virtual
Reimplemented from json::Node.
References addValue().
addIdValue() [4/6]
Node & json::ListNode::addIdValue (const int64_t & value) override virtual
Reimplemented from json::Node.
References addValue().
addIdValue() [5/6]
Node & json::ListNode::addIdValue (const std::string & value) override virtual
Reimplemented from json::Node.
References addValue().
addIdValue() [6/6]
Node & json::ListNode::addIdValue (const uint64_t & value) override virtual
Reimplemented from json::Node.
References addValue().
addListValue()
Node & json::ListNode::addListValue () override virtual
Reimplemented from json::Node.
References addValue(), and ListNode().
addTextValue()
Node & json::ListNode::addTextValue (const std::string & value) override virtual
Reimplemented from json::Node.
References addValue().
addValue()
void json::ListNode::addValue (std::unique_ptr< Node > node) override virtual
Reimplemented from json::Node.
Referenced by addDictValue(), addIdValue(), addIdValue(), addIdValue(), addIdValue(), addIdValue(), addListValue(), and addTextValue().
clone()
Node * json::ListNode::clone () override virtual
Implements json::Node.
References ListNode().
erase()
std::unique_ptr< Node > json::ListNode::erase (Node & node) override virtual
Reimplemented from json::Node.
References json::Node::parent.
operator=() [1/2]
ListNode & json::ListNode::operator= (const ListNode & right)
References json::Node::orderedKeyIndex, and json::Node::parent.
Referenced by operator=().
operator=() [2/2]
Node & json::ListNode::operator= (const Node & right) override virtual
Reimplemented from json::Node.
References operator=().
operator[]()
Node & json::ListNode::operator[] (const size_t index) override virtual
Reimplemented from json::Node.
parse()
void json::ListNode::parse (std::vector< Token > & stream) override virtual
Implements json::Node.
References json::COMMA, json::ID, json::LBRACE, json::LBRACKET, ListNode(), json::RBRACKET, and json::STRING.
removeValue()
std::unique_ptr< Node > json::ListNode::removeValue (size_t index) override virtual
Reimplemented from json::Node.
serialize()
void json::ListNode::serialize (std::ostream & outFile, size_t indentWidth) override virtual
Implements json::Node.
References json::Node::SERIALIZE_INDENT.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
size()
size_t json::ListNode::size () override virtual
Implements json::Node.
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig(), sgpp::datadriven::DataMiningConfigParser::getMultiDataSourceConfig(), and python.data.DataContainer.DataContainer::getSize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/json/ListNode.hpp
base/src/sgpp/base/tools/json/ListNode.cpp