SG++-Doxygen-Documentation: sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration Class Reference
sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration Class Reference
#include <Configuration.hpp>
Static Public Member Functions
static void augmentDefaultParameters (sgpp::base::OCLOperationConfiguration &parameters)
static const std::string & getKernelName ()
Member Function Documentation
augmentDefaultParameters()
static void sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters (sgpp::base::OCLOperationConfiguration & parameters) inline static
References json::Node::addDictAttr(), json::Node::addIDAttr(), json::DictNode::addIDAttr(), json::Node::addTextAttr(), json::Node::contains(), json::DictNode::contains(), getKernelName(), json::Node::keys(), and json::DictNode::keys().
Referenced by sgpp::datadriven::createStreamingModOCLFastMultiPlatformConfigured().
getKernelName()
static const std::string & sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::getKernelName () inline static
Referenced by augmentDefaultParameters(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLFastMultiPlatform< T >::OperationMultiEvalStreamingModOCLFastMultiPlatform().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingModOCLFastMultiPlattform/Configuration.hpp