SG++-Doxygen-Documentation: sgpp::datadriven::VisualizerConfiguration Class Reference
sgpp::datadriven::VisualizerConfiguration Class Reference
#include <VisualizerConfiguration.hpp>
Public Member Functions
VisualizationGeneralConfig & getGeneralConfig ()
read general configuration parameters
VisualizationParameters & getVisualizationParameters ()
read general configuration parameters
void readParams (const DataMiningConfigParser &parser)
obtain parameters from a parser
void setupDefaults ()
set default values for all members based on the desired scenario.
VisualizerConfiguration ()=default
Default Constructor.
~VisualizerConfiguration ()=default
Default Constructor.
Protected Attributes
VisualizationGeneralConfig generalConfig
Contains general configuration for the Visualizer.
VisualizationParameters visualizationParameters
Contains the numerical parameters used to run the visualization algorithm.
Constructor & Destructor Documentation
VisualizerConfiguration()
sgpp::datadriven::VisualizerConfiguration::VisualizerConfiguration () default
Default Constructor.
~VisualizerConfiguration()
sgpp::datadriven::VisualizerConfiguration::~VisualizerConfiguration () default
Default Constructor.
Member Function Documentation
getGeneralConfig()
VisualizationGeneralConfig & sgpp::datadriven::VisualizerConfiguration::getGeneralConfig ()
read general configuration parameters
References generalConfig.
Referenced by sgpp::datadriven::VisualizerDensityEstimation::getHeatmap2D(), sgpp::datadriven::VisualizerClassification::getHeatmap2DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmap3D(), sgpp::datadriven::VisualizerClassification::getHeatmap3DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getHeatmapMore4D(), sgpp::datadriven::VisualizerClassification::getHeatmapMore4DClassification(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts1D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCuts2D(), sgpp::datadriven::VisualizerDensityEstimation::getLinearCutsMore3D(), sgpp::datadriven::VisualizerClassification::runVisualization(), and sgpp::datadriven::VisualizerDensityEstimation::runVisualization().
getVisualizationParameters()
VisualizationParameters & sgpp::datadriven::VisualizerConfiguration::getVisualizationParameters ()
read general configuration parameters
References visualizationParameters.
Referenced by sgpp::datadriven::VisualizerClassification::runVisualization(), and sgpp::datadriven::VisualizerDensityEstimation::runVisualization().
readParams()
void sgpp::datadriven::VisualizerConfiguration::readParams (const DataMiningConfigParser & parser)
obtain parameters from a parser
Parameters
parser the parser object to read from
References generalConfig, setupDefaults(), and visualizationParameters.
setupDefaults()
void sgpp::datadriven::VisualizerConfiguration::setupDefaults ()
set default values for all members based on the desired scenario.
References sgpp::datadriven::VisualizationGeneralConfig::algorithm_, sgpp::datadriven::CSV, generalConfig, sgpp::datadriven::VisualizationParameters::maxNumberIterations_, sgpp::datadriven::VisualizationGeneralConfig::numBatches_, sgpp::datadriven::VisualizationParameters::numberCores_, sgpp::datadriven::VisualizationParameters::perplexity_, sgpp::datadriven::VisualizationParameters::seed_, sgpp::datadriven::VisualizationParameters::targetDimension_, sgpp::datadriven::VisualizationGeneralConfig::targetDirectory_, sgpp::datadriven::VisualizationGeneralConfig::targetFileType_, sgpp::datadriven::VisualizationParameters::theta_, and visualizationParameters.
Referenced by readParams().
Member Data Documentation
generalConfig
VisualizationGeneralConfig sgpp::datadriven::VisualizerConfiguration::generalConfig protected
Contains general configuration for the Visualizer.
Referenced by getGeneralConfig(), readParams(), and setupDefaults().
visualizationParameters
VisualizationParameters sgpp::datadriven::VisualizerConfiguration::visualizationParameters protected
Contains the numerical parameters used to run the visualization algorithm.
Referenced by getVisualizationParameters(), readParams(), and setupDefaults().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/visualization/VisualizerConfiguration.hpp
datadriven/src/sgpp/datadriven/datamining/modules/visualization/VisualizerConfiguration.cpp