SG++-Doxygen-Documentation: sgpp::datadriven::MPITaskScheduler Class Reference
sgpp::datadriven::MPITaskScheduler Class Reference abstract
#include <MPITaskScheduler.hpp>
Public Member Functions
virtual void assignTaskStaticTaskSize (TaskType taskType, AssignTaskResult &result)=0
Request for a task of specific type to be assigned.
virtual void assignTaskVariableTaskSize (TaskType taskType, AssignTaskResult &result)=0
Request for a task of specific type to be assigned.
virtual bool isReadyForRefinement ()=0
Check whether the master is allowed to transit into the refinement phase.
virtual void onMergeRequestIncoming (size_t batchOffset, size_t batchSize, size_t remoteGridVersion, size_t localGridVersion)=0
Callback for when training results are received from workers.
virtual void onRefinementStarted ()=0
Callback for when refinement is about to begin.
void setLearnerInstance (LearnerSGDEOnOffParallel *instance)
Set the learner instance for which to task schedule.
virtual ~MPITaskScheduler ()=default
Default destructor to override if necessary.
Protected Attributes
LearnerSGDEOnOffParallel * learnerInstance {}
The learner instance used to interrogate system state if necessary.
Constructor & Destructor Documentation
~MPITaskScheduler()
virtual sgpp::datadriven::MPITaskScheduler::~MPITaskScheduler () virtual default
Default destructor to override if necessary.
Member Function Documentation
assignTaskStaticTaskSize()
virtual void sgpp::datadriven::MPITaskScheduler::assignTaskStaticTaskSize (TaskType taskType, AssignTaskResult & result) pure virtual
Request for a task of specific type to be assigned.
This type of task does not include variable task size.
Parameters
taskType
result
Implemented in sgpp::datadriven::RoundRobinScheduler.
Referenced by sgpp::datadriven::RefinementHandler::updateClassVariablesAfterRefinement().
assignTaskVariableTaskSize()
virtual void sgpp::datadriven::MPITaskScheduler::assignTaskVariableTaskSize (TaskType taskType, AssignTaskResult & result) pure virtual
Request for a task of specific type to be assigned.
The MPI Task Scheduler will decide on the task size.
Parameters
taskType The type of the task to be assigned.
result The result of assigning the task.
Implemented in sgpp::datadriven::RoundRobinScheduler.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::assignBatchToWorker().
isReadyForRefinement()
virtual bool sgpp::datadriven::MPITaskScheduler::isReadyForRefinement () pure virtual
Check whether the master is allowed to transit into the refinement phase.
Returns
Whether to start refinement.
Implemented in sgpp::datadriven::RoundRobinScheduler.
Referenced by sgpp::datadriven::RefinementHandler::checkReadyForRefinement().
onMergeRequestIncoming()
virtual void sgpp::datadriven::MPITaskScheduler::onMergeRequestIncoming (size_t batchOffset, size_t batchSize, size_t remoteGridVersion, size_t localGridVersion) pure virtual
Callback for when training results are received from workers.
Can be used to update tracking of assigned batches.
Parameters
batchOffset The offset of the batch that was trained from.
batchSize The size of the batch used for training.
remoteGridVersion The grid version of the worker used for training.
localGridVersion The grid version of the master upond reception.
Implemented in sgpp::datadriven::RoundRobinScheduler.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues().
onRefinementStarted()
virtual void sgpp::datadriven::MPITaskScheduler::onRefinementStarted () pure virtual
Callback for when refinement is about to begin.
Implemented in sgpp::datadriven::RoundRobinScheduler.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::trainParallel().
setLearnerInstance()
void sgpp::datadriven::MPITaskScheduler::setLearnerInstance (LearnerSGDEOnOffParallel * instance)
Set the learner instance for which to task schedule.
Parameters
instance The learner instance.
References learnerInstance.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::LearnerSGDEOnOffParallel().
Member Data Documentation
learnerInstance
LearnerSGDEOnOffParallel* sgpp::datadriven::MPITaskScheduler::learnerInstance {} protected
The learner instance used to interrogate system state if necessary.
Referenced by sgpp::datadriven::RoundRobinScheduler::assignTaskStaticTaskSize(), sgpp::datadriven::RoundRobinScheduler::RoundRobinScheduler(), and setLearnerInstance().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/learnersgdeonoffparallel/MPITaskScheduler.hpp
datadriven/src/sgpp/datadriven/application/learnersgdeonoffparallel/MPITaskScheduler.cpp