SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::DensityWorker Class Reference
sgpp::datadriven::clusteringmpi::DensityWorker Class Reference
#include <OperationDensityMPI.hpp>
Public Member Functions
DensityWorker ()
DensityWorker (base::Grid &grid, double lambda)
DensityWorker (base::Grid &grid, double lambda, std::string ocl_conf_filename)
virtual ~DensityWorker ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
virtual ~MPIWorkerGridBase ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual ~MPIWorkerBase (void)
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
MPIWorkerPackageBase (std::string operationName, int multiplier)
MPIWorkerPackageBase (std::string operationName, int multiplier, std::string ocl_conf_filename)
void start_worker_main (void)
virtual ~MPIWorkerPackageBase ()
Protected Member Functions
void begin_opencl_operation (int *workpackage)
void finalize_opencl_operation (double *result_buffer, int *workpackage)
void receive_alpha (double **alpha)
void receive_and_send_initial_data (void)
void send_alpha (double **alpha)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
MPIWorkerGridBase (std::string operationName)
MPIWorkerGridBase (std::string operationName, base::Grid &grid)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
void divide_workpackages (int *package, double *erg)
Protected Attributes
double * alpha
double lambda
size_t oldgridsize
DensityOCLMultiPlatform::OperationDensity * op
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGridBase
int complete_gridsize
int grid_dimensions
int * gridpoints
int gridsize
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
bool verbose
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >
MPI_Comm & master_worker_comm
MPI_Datatype mpi_typ
size_t opencl_device
bool opencl_node
size_t opencl_platform
bool overseer_node
int packagesize_multiplier
base::OCLOperationConfiguration * parameters
bool prefetching
bool redistribute
int secondary_workpackage [2]
size_t size
MPI_Comm & sub_worker_comm
Constructor & Destructor Documentation
DensityWorker() [1/3]
sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker () inline
References alpha, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::complete_gridsize, sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::grid_dimensions, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::gridpoints, lambda, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::master_worker_comm, oldgridsize, op, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::opencl_device, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::opencl_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::opencl_platform, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::parameters, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
DensityWorker() [2/3]
sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker (base::Grid & grid, double lambda) inline
References alpha, sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), lambda, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
DensityWorker() [3/3]
sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker (base::Grid & grid, double lambda, std::string ocl_conf_filename) inline
References alpha, sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), lambda, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
~DensityWorker()
virtual sgpp::datadriven::clusteringmpi::DensityWorker::~DensityWorker () inline virtual
References op, and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::opencl_node.
Member Function Documentation
begin_opencl_operation()
void sgpp::datadriven::clusteringmpi::DensityWorker::begin_opencl_operation (int * workpackage) inline protected virtual
Implements sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >.
References op, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::start_partial_mult().
finalize_opencl_operation()
void sgpp::datadriven::clusteringmpi::DensityWorker::finalize_opencl_operation (double * result_buffer, int * workpackage) inline protected virtual
Implements sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >.
References sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::finish_partial_mult(), and op.
receive_alpha()
void sgpp::datadriven::clusteringmpi::DensityWorker::receive_alpha (double ** alpha) inline protected
References alpha, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::complete_gridsize, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::grid_dimensions, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::gridsize, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::master_worker_comm, and oldgridsize.
Referenced by receive_and_send_initial_data().
receive_and_send_initial_data()
void sgpp::datadriven::clusteringmpi::DensityWorker::receive_and_send_initial_data (void) inline protected virtual
Implements sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >.
References alpha, sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::initialize_alpha(), op, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::opencl_node, receive_alpha(), send_alpha(), and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
send_alpha()
void sgpp::datadriven::clusteringmpi::DensityWorker::send_alpha (double ** alpha) inline protected
References alpha, sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::complete_gridsize, sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerGridBase::grid_dimensions, and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< double >::sub_worker_comm.
Referenced by sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), and receive_and_send_initial_data().
Member Data Documentation
alpha
double* sgpp::datadriven::clusteringmpi::DensityWorker::alpha protected
Referenced by DensityWorker(), DensityWorker(), DensityWorker(), python.learner.Learner.Learner::doLearningIteration(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Interpolant.Interpolant::learnDataWithTest(), sgpp::datadriven::clusteringmpi::OperationDensityMultMPI::mult(), python.uq.dists.SGDEdist.SGDEdist::pdf(), receive_alpha(), receive_and_send_initial_data(), send_alpha(), and python.uq.dists.SGDEdist.SGDEdist::toJson().
lambda
double sgpp::datadriven::clusteringmpi::DensityWorker::lambda protected
Referenced by DensityWorker(), DensityWorker(), and DensityWorker().
oldgridsize
size_t sgpp::datadriven::clusteringmpi::DensityWorker::oldgridsize protected
Referenced by DensityWorker(), and receive_alpha().
op
DensityOCLMultiPlatform::OperationDensity* sgpp::datadriven::clusteringmpi::DensityWorker::op protected
Referenced by begin_opencl_operation(), DensityWorker(), finalize_opencl_operation(), receive_and_send_initial_data(), and ~DensityWorker().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationDensityMPI.hpp