SG++-Doxygen-Documentation: sgpp::base::AdaptivityThresholdTypeParser Class Reference
sgpp::base::AdaptivityThresholdTypeParser Class Reference
#include <AdaptivityThresholdTypeParser.hpp>
Static Public Member Functions
static AdaptivityThresholdType parse (const std::string &input)
Convert strings to values sgpp::base::AdaptivityThresholdType.
static const std::string & toString (AdaptivityThresholdType type)
generate string representations for values of sgpp::base::AdaptivityThresholdType.
Member Function Documentation
parse()
AdaptivityThresholdType sgpp::base::AdaptivityThresholdTypeParser::parse (const std::string & input) static
Convert strings to values sgpp::base::AdaptivityThresholdType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::base::AdaptivityThresholdType.
Returns
the corresponding sgpp::base::AdaptivityThresholdType.
References sgpp::base::Absolute, and sgpp::base::Relative.
Referenced by sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig().
toString()
const std::string & sgpp::base::AdaptivityThresholdTypeParser::toString (AdaptivityThresholdType type) static
generate string representations for values of sgpp::base::AdaptivityThresholdType.
Parameters
type enum value.
Returns
string representation of a sgpp::base::AdaptivityThresholdType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DMConfigTools::dumpToStream(), sgpp::datadriven::DataMiningConfigParser::getFitterAdaptivityConfig(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/AdaptivityThresholdTypeParser.hpp
base/src/sgpp/base/grid/AdaptivityThresholdTypeParser.cpp