SG++-Doxygen-Documentation: sgpp::base::WaveletModifiedBasis< LT, IT > Class Template Reference
sgpp::base::WaveletModifiedBasis< LT, IT > Class Template Reference
Modified wavelet basis on Noboundary grids.
#include <WaveletModifiedBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
~WaveletModifiedBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Detailed Description
template<class LT, class IT>
class sgpp::base::WaveletModifiedBasis< LT, IT >
Modified wavelet basis on Noboundary grids.
Constructor & Destructor Documentation
~WaveletModifiedBasis()
template<class LT , class IT > sgpp::base::WaveletModifiedBasis< LT, IT >::~WaveletModifiedBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::WaveletModifiedBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of modified wavelet basis function
Implements sgpp::base::Basis< LT, IT >.
References h.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative().
evalDx()
template<class LT , class IT > double sgpp::base::WaveletModifiedBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of modified wavelet basis function
Implements sgpp::base::Basis< LT, IT >.
References h.
Referenced by sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative().
evalDxDx()
template<class LT , class IT > double sgpp::base::WaveletModifiedBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of modified wavelet basis function
References h.
Referenced by sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), and sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::WaveletModifiedBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
getIntegral()
template<class LT , class IT > double sgpp::base::WaveletModifiedBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/WaveletModifiedBasis.hpp