SG++-Doxygen-Documentation: sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates Class Reference
sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates Class Reference
#include <OperationMakePositiveCandidateSetAlgorithm.hpp>
Public Member Functions
void nextCandidates (base::Grid &grid, base::DataVector &alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > &candidates) override
Load the next candidate set that contains grid points with the currently explored levelsum.
size_t numCandidates () override
base::DataVector & numCandidatesPerIteration () override
OperationMakePositiveFindIntersectionCandidates (size_t maxLevel)
~OperationMakePositiveFindIntersectionCandidates () override
Public Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
size_t costsComputingCandidates ()
base::DataVector & costsComputingCandidatesPerIteration ()
base::DataVector & numCandidatesPerLevel ()
OperationMakePositiveCandidateSetAlgorithm (size_t maxLevel)
Constructor.
void setVerbose (bool pverbose)
Set verbosity level.
virtual ~OperationMakePositiveCandidateSetAlgorithm ()
Desctructor.
Protected Member Functions
void computeIntersection (base::HashGridPoint &gpi, base::HashGridPoint &gpj, base::HashGridPoint &gpintersection)
virtual void findIntersections (base::Grid &grid, base::DataVector &alpha, size_t levelSum, std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > &res)
bool haveOverlappingSupport (base::HashGridPoint &gpi, base::HashGridPoint &gpj)
bool haveOverlappingSupport (base::HashGridPoint &gpi, base::HashGridPoint &gpj, size_t dim)
virtual void initializeCandidates (base::Grid &grid, std::vector< size_t > &negativeGridPoints)
Protected Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
void findNodesWithNegativeCoefficients (base::DataVector &alpha, std::vector< size_t > &negativeGridPoints, double tol=-1e-14)
Extract grid points with negative coefficient.
Static Protected Member Functions
static bool compareGridPointsByHash (const std::shared_ptr< base::HashGridPoint > &lhs, const std::shared_ptr< base::HashGridPoint > &rhs)
Protected Attributes
std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > candidates
std::set< std::shared_ptr< base::HashGridPoint >, HashGridPointCompare > currentIntersections
std::unordered_map< size_t, std::shared_ptr< std::vector< std::shared_ptr< base::HashGridPoint > > > > intersections
std::set< std::shared_ptr< base::HashGridPoint >, HashGridPointCompare > nextIntersections
base::DataVector numCandidatesIteration
Protected Attributes inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
base::DataVector costsPerIteration
comparison costs per iteration
base::DataVector gridPointsPerLevel
candiddate grid points per level
size_t iteration
iteration counter
size_t maxLevel
maximum full grid level for the candidate set
bool verbose
verbosity level
Constructor & Destructor Documentation
OperationMakePositiveFindIntersectionCandidates()
sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::OperationMakePositiveFindIntersectionCandidates (size_t maxLevel) explicit
~OperationMakePositiveFindIntersectionCandidates()
sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::~OperationMakePositiveFindIntersectionCandidates () override
Member Function Documentation
compareGridPointsByHash()
bool sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::compareGridPointsByHash (const std::shared_ptr< base::HashGridPoint > & lhs, const std::shared_ptr< base::HashGridPoint > & rhs) static protected
Referenced by findIntersections(), initializeCandidates(), and sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::initializeCandidates().
computeIntersection()
void sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection (base::HashGridPoint & gpi, base::HashGridPoint & gpj, base::HashGridPoint & gpintersection) protected
References sgpp::base::HashGridPoint::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), and sgpp::base::HashGridPoint::set().
Referenced by findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections().
findIntersections()
void sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::findIntersections (base::Grid & grid, base::DataVector & alpha, size_t levelSum, std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > & res) protected virtual
Reimplemented in sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin, and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates.
References compareGridPointsByHash(), computeIntersection(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::costsPerIteration, currentIntersections, grid(), intersections, nextIntersections, numCandidatesIteration, sgpp::base::DataVector::setAll(), sgpp::base::DataVector::sum(), and sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::verbose.
Referenced by nextCandidates().
haveOverlappingSupport() [1/2]
bool sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport (base::HashGridPoint & gpi, base::HashGridPoint & gpj) protected
References sgpp::base::HashGridPoint::getDimension(), and haveOverlappingSupport().
haveOverlappingSupport() [2/2]
bool sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport (base::HashGridPoint & gpi, base::HashGridPoint & gpj, size_t dim) protected
References sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), and sgpp::base::HashGridPoint::isHierarchicalAncestor().
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), haveOverlappingSupport(), initializeCandidates(), and sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::initializeCandidates().
initializeCandidates()
void sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::initializeCandidates (base::Grid & grid, std::vector< size_t > & negativeGridPoints) protected virtual
Reimplemented in sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin.
References compareGridPointsByHash(), currentIntersections, grid(), haveOverlappingSupport(), intersections, and sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::verbose.
Referenced by nextCandidates(), and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates().
nextCandidates()
void sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextCandidates (base::Grid & grid, base::DataVector & alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > & candidates) override virtual
Load the next candidate set that contains grid points with the currently explored levelsum.
Parameters
grid current sparse grid that needs to be extended
alpha corresponding coefficient vector
levelSum current levelsum to be explored
candidates vector that contains the candidate set for the current levelsum
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
Reimplemented in sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates.
References alpha, candidates, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::costsPerIteration, findIntersections(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::findNodesWithNegativeCoefficients(), sgpp::base::HashGridStorage::getMaxLevel(), sgpp::base::DataVector::getSize(), grid(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::gridPointsPerLevel, initializeCandidates(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::iteration, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::maxLevel, numCandidatesIteration, sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::setAll(), sgpp::base::DataVector::sum(), and sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::verbose.
numCandidates()
size_t sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::numCandidates () override virtual
Returns
total number of candidates
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
References candidates.
numCandidatesPerIteration()
base::DataVector & sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::numCandidatesPerIteration () override virtual
Returns
number of candidates that have been computed per iteration
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
References numCandidatesIteration.
Member Data Documentation
candidates
std::unordered_map<size_t, std::shared_ptr<base::HashGridPoint> > sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::candidates protected
Referenced by python.uq.operations.forcePositivity.findCandidateSet.CandidateSet::hasMoreCandidates(), nextCandidates(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates(), python.uq.operations.forcePositivity.findCandidateSet.CandidateSet::nextCandidateSet(), numCandidates(), and python.uq.refinement.RefinementManager.RefinementManager::refineGrid().
currentIntersections
std::set<std::shared_ptr<base::HashGridPoint>, HashGridPointCompare> sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::currentIntersections protected
Referenced by findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), initializeCandidates(), and sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::initializeCandidates().
intersections
std::unordered_map<size_t, std::shared_ptr<std::vector<std::shared_ptr<base::HashGridPoint> > > > sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::intersections protected
Referenced by findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), initializeCandidates(), and sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::initializeCandidates().
nextIntersections
std::set<std::shared_ptr<base::HashGridPoint>, HashGridPointCompare> sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextIntersections protected
Referenced by findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections().
numCandidatesIteration
base::DataVector sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::numCandidatesIteration protected
Referenced by findIntersections(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidatesJoin::findIntersections(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections(), nextCandidates(), and numCandidatesPerIteration().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.cpp