SG++-Doxygen-Documentation: sgpp::base::AbstractRefinement Class Reference
sgpp::base::AbstractRefinement Class Reference abstract
Abstract refinement class for sparse grids.
#include <AbstractRefinement.hpp>
Public Types
typedef std::vector< refinement_pair_type > refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
typedef AbstractRefinement_refinement_key refinement_key_type
Type of the identifier of the refinement atom (e.g.
typedef std::forward_list< AbstractRefinement::refinement_pair_type > refinement_list_type
typedef std::pair< std::shared_ptr< refinement_key_type >, refinement_value_type > refinement_pair_type
Pair for the refinement key and value.
typedef double refinement_value_type
Type of functor value assigned to each refinement atom.
Public Member Functions
virtual void free_refine (GridStorage &storage, RefinementFunctor &functor, std::vector< size_t > *addedPoints=nullptr)=0
Refines a grid according to a RefinementFunctor provided.
virtual size_t getIndexOfMin (RefinementFunctor::value_type *array, size_t length)
Returns the index of the first occurrence of minimal element in array.
virtual size_t getNumberOfRefinablePoints (GridStorage &storage)=0
Computes and returns the number of grid points, which can be refined.
bool isRefinable (GridStorage &storage, GridPoint &point)
Check if the grid point is refinable.
virtual void refineGridpoint1D (GridStorage &storage, GridPoint &point, size_t d)=0
Refine one grid point along a single direction.
virtual void refineGridpoint1D (GridStorage &storage, size_t seq, size_t d)
Refine one grid point along a single direction.
virtual ~AbstractRefinement ()
Destructor.
Static Public Member Functions
static bool compare_pairs (const refinement_pair_type &lhs, const refinement_pair_type &rhs)
Comparison of the refinement_pair_type.
Protected Member Functions
virtual void collectRefinablePoints (GridStorage &storage, RefinementFunctor &functor, refinement_container_type &collection)=0
Identifies the sparse grid refinement atoms (points or subspaces) with the largest indicator values.
virtual void createGridpoint (GridStorage &storage, GridPoint &point)=0
This method creates a new point on the grid.
virtual void createGridpoint1D (GridPoint &point, size_t d, GridStorage &storage, index_t &source_index, level_t &source_level)
Creates children grid points along single direction.
virtual void createGridpointSubroutine (GridStorage &storage, GridPoint &point)
Subroutine for grid point creation.
virtual refinement_list_type getIndicator (GridStorage &storage, const GridStorage::grid_map_iterator &iter, const RefinementFunctor &functor) const =0
virtual void refineGridpoint (GridStorage &storage, size_t refine_index)=0
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
virtual void refineGridpointsCollection (GridStorage &storage, RefinementFunctor &functor, refinement_container_type &collection)=0
Refines the collection of points.
Friends
class RefinementDecorator
Detailed Description
Abstract refinement class for sparse grids.
Member Typedef Documentation
refinement_container_type
typedef std::vector<refinement_pair_type> sgpp::base::AbstractRefinement::refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
refinement_key_type
typedef AbstractRefinement_refinement_key sgpp::base::AbstractRefinement::refinement_key_type
Type of the identifier of the refinement atom (e.g.
a grid point or a subspace)
refinement_list_type
typedef std::forward_list<AbstractRefinement::refinement_pair_type> sgpp::base::AbstractRefinement::refinement_list_type
refinement_pair_type
typedef std::pair<std::shared_ptr<refinement_key_type>, refinement_value_type> sgpp::base::AbstractRefinement::refinement_pair_type
Pair for the refinement key and value.
refinement_value_type
typedef double sgpp::base::AbstractRefinement::refinement_value_type
Type of functor value assigned to each refinement atom.
Constructor & Destructor Documentation
~AbstractRefinement()
virtual sgpp::base::AbstractRefinement::~AbstractRefinement () inline virtual
Destructor.
Member Function Documentation
collectRefinablePoints()
virtual void sgpp::base::AbstractRefinement::collectRefinablePoints (GridStorage & storage, RefinementFunctor & functor, refinement_container_type & collection) protected pure virtual
Identifies the sparse grid refinement atoms (points or subspaces) with the largest indicator values.
Parameters
storage hashmap that stores the grid points
functor a RefinementFunctor specifying the refinement criteria
collection container with grid element identifiers (e.g. sequence number, grid point) and corresponding refinement values (usually empty)
Implemented in sgpp::optimization::HashRefinementMultiple, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, sgpp::base::HashRefinementInteraction, sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::MultipleClassRefinement, sgpp::base::PredictiveRefinement, and sgpp::base::SubspaceRefinement.
Referenced by sgpp::base::RefinementDecorator::collectRefinablePoints().
compare_pairs()
static bool sgpp::base::AbstractRefinement::compare_pairs (const refinement_pair_type & lhs, const refinement_pair_type & rhs) inline static
Comparison of the refinement_pair_type.
This way the priority queue has the elements with the smallest refinement_value_type on top
Referenced by sgpp::base::HashRefinement::addElementToCollection(), sgpp::base::HashRefinementBoundaries::addElementToCollection(), sgpp::base::PredictiveRefinement::addElementToCollection(), sgpp::base::ForwardSelectorRefinement::addElementToCollection(), sgpp::base::ImpurityRefinement::addElementToCollection(), and sgpp::base::SubspaceRefinement::collectRefinablePoints().
createGridpoint()
virtual void sgpp::base::AbstractRefinement::createGridpoint (GridStorage & storage, GridPoint & point) protected pure virtual
This method creates a new point on the grid.
It checks if some parents or children are needed in other dimensions.
Parameters
storage hashmap that stores the gridpoints
point The point that should be inserted
Implemented in sgpp::base::HashRefinementInteraction, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, and sgpp::base::HashRefinementInconsistent.
Referenced by sgpp::base::RefinementDecorator::createGridpoint(), and createGridpointSubroutine().
createGridpoint1D()
void sgpp::base::AbstractRefinement::createGridpoint1D (GridPoint & point, size_t d, GridStorage & storage, index_t & source_index, level_t & source_level) protected virtual
Creates children grid points along single direction.
Parameters
point The point that should be refined
d direction
storage hashmap that stores the gridpoints
source_index index value in the dimension d
source_level level value in the dimension d
Reimplemented in sgpp::base::HashRefinementBoundaries.
References createGridpointSubroutine().
Referenced by sgpp::base::HashRefinementInteraction::createGridpoint(), sgpp::base::HashRefinement::createGridpoint(), and sgpp::base::HashRefinementBoundaries::createGridpoint1D().
createGridpointSubroutine()
virtual void sgpp::base::AbstractRefinement::createGridpointSubroutine (GridStorage & storage, GridPoint & point) inline protected virtual
Subroutine for grid point creation.
Parameters
storage hashmap that stores the gridpoints
point The point that should be inserted
References createGridpoint(), sgpp::base::HashGridStorage::find(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::isContaining(), and sgpp::base::HashGridPoint::setLeaf().
Referenced by createGridpoint1D(), and sgpp::base::HashRefinementBoundaries::createGridpoint1D().
free_refine()
virtual void sgpp::base::AbstractRefinement::free_refine (GridStorage & storage, RefinementFunctor & functor, std::vector< size_t > * addedPoints = nullptr) pure virtual
Refines a grid according to a RefinementFunctor provided.
Refines up to RefinementFunctor::getRefinementsNum() grid points if possible, and if their refinement value is larger than RefinementFunctor::start() and their absolute value is larger or equal than RefinementFunctor::getRefinementThreshold() If addedPoints is supplied and not a zero pointer, then newly created grid points are appended to this vector.
Parameters
storage hashmap that stores the grid points
functor a RefinementFunctor specifying the refinement criteria
addedPoints pointer to vector to append newly created grid points to
Implemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, and sgpp::base::SubspaceRefinement.
Referenced by sgpp::base::RefinementDecorator::free_refine().
getIndexOfMin()
size_t sgpp::base::AbstractRefinement::getIndexOfMin (RefinementFunctor::value_type * array, size_t length) virtual
Returns the index of the first occurrence of minimal element in array.
Used to find which entry is to be replaced next searching the maximum ones.
Parameters
array array with values
length length of array
Returns
index of the first occurrence of minimal element in array
Referenced by sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel().
getIndicator()
virtual refinement_list_type sgpp::base::AbstractRefinement::getIndicator (GridStorage & storage, const GridStorage::grid_map_iterator & iter, const RefinementFunctor & functor) const protected pure virtual
Implemented in sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, and sgpp::base::PredictiveRefinement.
Referenced by sgpp::base::RefinementDecorator::getIndicator().
getNumberOfRefinablePoints()
virtual size_t sgpp::base::AbstractRefinement::getNumberOfRefinablePoints (GridStorage & storage) pure virtual
Computes and returns the number of grid points, which can be refined.
This is the number of grid points that have at least one child missing.
Parameters
storage hashmap that stores the grid points
Returns
The number of grid points that can be refined
Implemented in sgpp::optimization::HashRefinementMultiple, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, and sgpp::base::HashRefinementBoundaries.
Referenced by sgpp::base::RefinementDecorator::getNumberOfRefinablePoints().
isRefinable()
bool sgpp::base::AbstractRefinement::isRefinable (GridStorage & storage, GridPoint & point)
Check if the grid point is refinable.
Parameters
storage hashmap that stores the grid points
point grid point
References sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), and sgpp::base::HashGridStorage::getDimension().
refineGridpoint()
virtual void sgpp::base::AbstractRefinement::refineGridpoint (GridStorage & storage, size_t refine_index) protected pure virtual
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
Parameters
storage hashmap that stores the gridpoints
refine_index The index in the hashmap of the point that should be refined
Implemented in sgpp::base::ANOVAHashRefinement, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, sgpp::base::HashRefinementBoundariesMaxLevel, and sgpp::base::MultipleClassRefinement.
Referenced by sgpp::base::RefinementDecorator::refineGridpoint().
refineGridpoint1D() [1/2]
virtual void sgpp::base::AbstractRefinement::refineGridpoint1D (GridStorage & storage, GridPoint & point, size_t d) pure virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
point point to refine
d direction
Implemented in sgpp::optimization::HashRefinementMultiple, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, and sgpp::base::HashRefinementBoundariesMaxLevel.
Referenced by sgpp::base::RefinementDecorator::refineGridpoint1D(), and refineGridpoint1D().
refineGridpoint1D() [2/2]
void sgpp::base::AbstractRefinement::refineGridpoint1D (GridStorage & storage, size_t seq, size_t d) virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
seq sequential number of the grid point
d direction
Reimplemented in sgpp::base::HashRefinement.
References sgpp::base::HashGridStorage::getPoint(), and refineGridpoint1D().
refineGridpointsCollection()
virtual void sgpp::base::AbstractRefinement::refineGridpointsCollection (GridStorage & storage, RefinementFunctor & functor, refinement_container_type & collection) protected pure virtual
Refines the collection of points.
Parameters
storage hashmap that stores the grid points
functor a RefinementFunctor specifying the refinement criteria
collection container with grid element identifiers (e.g. sequence number, grid point) and corresponding refinement values
Implemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, sgpp::base::RefinementDecorator, sgpp::base::HashRefinement, sgpp::base::HashRefinementBoundaries, sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, and sgpp::base::SubspaceRefinement.
Referenced by sgpp::base::RefinementDecorator::refineGridpointsCollection().
Friends And Related Symbol Documentation
RefinementDecorator
friend class RefinementDecorator friend
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/hashmap/AbstractRefinement.hpp
base/src/sgpp/base/grid/generation/hashmap/AbstractRefinement.cpp