SG++-Doxygen-Documentation: sgpp::base::NakBsplineBoundaryBasis< LT, IT > Class Template Reference
sgpp::base::NakBsplineBoundaryBasis< LT, IT > Class Template Reference
Hierarchical Not-a-knot B-spline basis.
#include <NakBsplineBoundaryBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
size_t getDegree () const override
double getIntegral (LT l, IT i) override
double getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights)
NakBsplineBoundaryBasis ()
Default constructor.
NakBsplineBoundaryBasis (size_t degree)
Constructor.
~NakBsplineBoundaryBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
NakBsplineBasis< LT, IT > nakBsplineBasis
not a knot B-spline basis
Detailed Description
template<class LT, class IT>
class sgpp::base::NakBsplineBoundaryBasis< LT, IT >
Hierarchical Not-a-knot B-spline basis.
This basis has the canonical choice of a constant basis function on level 0
Constructor & Destructor Documentation
NakBsplineBoundaryBasis() [1/2]
template<class LT , class IT > sgpp::base::NakBsplineBoundaryBasis< LT, IT >::NakBsplineBoundaryBasis () inline
Default constructor.
NakBsplineBoundaryBasis() [2/2]
template<class LT , class IT > sgpp::base::NakBsplineBoundaryBasis< LT, IT >::NakBsplineBoundaryBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree().
~NakBsplineBoundaryBasis()
template<class LT , class IT > sgpp::base::NakBsplineBoundaryBasis< LT, IT >::~NakBsplineBoundaryBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::NakBsplineBoundaryBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::nakBsplineBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), and sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::NakBsplineBoundaryBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::nakBsplineBasis.
getDegree()
template<class LT , class IT > size_t sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::nakBsplineBasis.
Referenced by sgpp::base::NakBsplineBoundaryBasis< LT, IT >::eval(), sgpp::base::NakBsplineBoundaryBasis< LT, IT >::evalDx(), sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getIntegral(), sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getMean(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::NakBsplineBoundaryBasis().
getIntegral()
template<class LT , class IT > double sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
integral of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getMean().
Referenced by sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature().
getMean()
template<class LT , class IT > double sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights) inline
References sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree().
Referenced by sgpp::base::OperationWeightedQuadratureNakBsplineBoundary::doWeightedQuadrature(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getIntegral().
Member Data Documentation
nakBsplineBasis
template<class LT , class IT > NakBsplineBasis<LT, IT> sgpp::base::NakBsplineBoundaryBasis< LT, IT >::nakBsplineBasis protected
not a knot B-spline basis
Referenced by sgpp::base::NakBsplineBoundaryBasis< LT, IT >::eval(), sgpp::base::NakBsplineBoundaryBasis< LT, IT >::evalDx(), and sgpp::base::NakBsplineBoundaryBasis< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/NakBsplineBoundaryBasis.hpp