SG++-Doxygen-Documentation: sgpp::optimization::optimizer::NLCG Class Reference
sgpp::optimization::optimizer::NLCG Class Reference
Gradient-based nonlinear conjugate gradient method.
#include <NLCG.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getBeta () const
double getEpsilon () const
double getGamma () const
double getRestartThreshold () const
double getTolerance () const
NLCG (const base::ScalarFunction &f, const base::ScalarFunctionGradient &fGradient, size_t maxItCount=DEFAULT_N, double beta=DEFAULT_BETA, double gamma=DEFAULT_GAMMA, double tolerance=DEFAULT_TOLERANCE, double epsilon=DEFAULT_EPSILON, double restartThreshold=DEFAULT_RESTART_THRESHOLD)
Constructor.
NLCG (const NLCG &other)
Copy constructor.
void optimize () override
Pure virtual method for optimization of the objective function.
void setBeta (double beta)
void setEpsilon (double epsilon)
void setGamma (double gamma)
void setRestartThreshold (double restartThreshold)
void setTolerance (double tolerance)
~NLCG () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_BETA = 0.5
default beta (parameter for Armijo's rule)
static constexpr double DEFAULT_EPSILON = 1e-18
default epsilon (parameter for Armijo's rule)
static constexpr double DEFAULT_GAMMA = 1e-2
default gamma (parameter for Armijo's rule)
static constexpr double DEFAULT_RESTART_THRESHOLD = 0.1
default restart threshold
static constexpr double DEFAULT_TOLERANCE = 1e-8
default tolerance (parameter for Armijo's rule)
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double alpha
restart threshold
double beta
beta (parameter for Armijo's rule)
double eps
epsilon (parameter for Armijo's rule)
double gamma
gamma (parameter for Armijo's rule)
double tol
tolerance (parameter for Armijo's rule)
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Gradient-based nonlinear conjugate gradient method.
The method is restarted with the steepest descent direction if the normalized absolute value of the inner product of two successive gradients exceeds a "restart threshold" \(\alpha\).
Constructor & Destructor Documentation
NLCG() [1/2]
sgpp::optimization::optimizer::NLCG::NLCG (const base::ScalarFunction & f, const base::ScalarFunctionGradient & fGradient, size_t maxItCount = DEFAULT_N, double beta = DEFAULT_BETA, double gamma = DEFAULT_GAMMA, double tolerance = DEFAULT_TOLERANCE, double epsilon = DEFAULT_EPSILON, double restartThreshold = DEFAULT_RESTART_THRESHOLD)
Constructor.
Parameters
f objective function
fGradient objective function gradient
maxItCount maximal number of iterations
beta beta (parameter for Armijo's rule)
gamma gamma (parameter for Armijo's rule)
tolerance tolerance (parameter for Armijo's rule)
epsilon epsilon (parameter for Armijo's rule)
restartThreshold restart threshold
NLCG() [2/2]
sgpp::optimization::optimizer::NLCG::NLCG (const NLCG & other)
Copy constructor.
Parameters
other optimizer to be copied
~NLCG()
sgpp::optimization::optimizer::NLCG::~NLCG () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::NLCG::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getBeta()
double sgpp::optimization::optimizer::NLCG::getBeta () const
Returns
beta (parameter for Armijo's rule)
References beta.
getEpsilon()
double sgpp::optimization::optimizer::NLCG::getEpsilon () const
Returns
epsilon (parameter for Armijo's rule)
References eps.
getGamma()
double sgpp::optimization::optimizer::NLCG::getGamma () const
Returns
gamma (parameter for Armijo's rule)
References gamma.
getRestartThreshold()
double sgpp::optimization::optimizer::NLCG::getRestartThreshold () const
Returns
restart threshold
References alpha.
getTolerance()
double sgpp::optimization::optimizer::NLCG::getTolerance () const
Returns
tolerance (parameter for Armijo's rule)
References tol.
optimize()
void sgpp::optimization::optimizer::NLCG::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References alpha, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), beta, sgpp::base::DataVector::dotProduct(), eps, sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fGradient, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, gamma, sgpp::base::Printer::getInstance(), sgpp::base::DataVector::l2Norm(), sgpp::optimization::optimizer::lineSearchArmijo(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), tol, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setBeta()
void sgpp::optimization::optimizer::NLCG::setBeta (double beta)
Parameters
beta beta (parameter for Armijo's rule)
References beta.
setEpsilon()
void sgpp::optimization::optimizer::NLCG::setEpsilon (double epsilon)
Parameters
epsilon epsilon (parameter for Armijo's rule)
References eps.
setGamma()
void sgpp::optimization::optimizer::NLCG::setGamma (double gamma)
Parameters
gamma gamma (parameter for Armijo's rule)
References gamma.
setRestartThreshold()
void sgpp::optimization::optimizer::NLCG::setRestartThreshold (double restartThreshold)
Parameters
restartThreshold restart threshold
References alpha.
setTolerance()
void sgpp::optimization::optimizer::NLCG::setTolerance (double tolerance)
Parameters
tolerance tolerance (parameter for Armijo's rule)
References tol.
Member Data Documentation
alpha
double sgpp::optimization::optimizer::NLCG::alpha protected
restart threshold
Referenced by python.learner.Learner.Learner::doLearningIteration(), getRestartThreshold(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Interpolant.Interpolant::learnDataWithTest(), optimize(), python.uq.dists.SGDEdist.SGDEdist::pdf(), setRestartThreshold(), and python.uq.dists.SGDEdist.SGDEdist::toJson().
beta
double sgpp::optimization::optimizer::NLCG::beta protected
beta (parameter for Armijo's rule)
Referenced by getBeta(), optimize(), and setBeta().
DEFAULT_BETA
constexpr double sgpp::optimization::optimizer::NLCG::DEFAULT_BETA = 0.5 static constexpr
default beta (parameter for Armijo's rule)
DEFAULT_EPSILON
constexpr double sgpp::optimization::optimizer::NLCG::DEFAULT_EPSILON = 1e-18 static constexpr
default epsilon (parameter for Armijo's rule)
DEFAULT_GAMMA
constexpr double sgpp::optimization::optimizer::NLCG::DEFAULT_GAMMA = 1e-2 static constexpr
default gamma (parameter for Armijo's rule)
DEFAULT_RESTART_THRESHOLD
constexpr double sgpp::optimization::optimizer::NLCG::DEFAULT_RESTART_THRESHOLD = 0.1 static constexpr
default restart threshold
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::NLCG::DEFAULT_TOLERANCE = 1e-8 static constexpr
default tolerance (parameter for Armijo's rule)
eps
double sgpp::optimization::optimizer::NLCG::eps protected
epsilon (parameter for Armijo's rule)
Referenced by getEpsilon(), optimize(), and setEpsilon().
gamma
double sgpp::optimization::optimizer::NLCG::gamma protected
gamma (parameter for Armijo's rule)
Referenced by getGamma(), optimize(), and setGamma().
tol
double sgpp::optimization::optimizer::NLCG::tol protected
tolerance (parameter for Armijo's rule)
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/NLCG.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/NLCG.cpp