SG++-Doxygen-Documentation: sgpp::solver::OperationParabolicPDESolverSystem Class Reference
sgpp::solver::OperationParabolicPDESolverSystem Class Reference abstract
Abstract definition of a System that is used to solve parabolic partial differential equations.
#include <OperationParabolicPDESolverSystem.hpp>
Public Member Functions
void abortTimestep ()
aborts the current timestep execution
virtual void coarsenAndRefine (bool isLastTimestep=false)=0
virtual void finishTimestep ()=0
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
virtual sgpp::base::DataVector * generateRHS ()=0
generates the right hand side of the system
sgpp::base::Grid * getGrid ()
get the pointer to the underlying grid object
sgpp::base::DataVector * getGridCoefficients ()
gets a pointer to the sparse grids coefficients with evtl.
virtual sgpp::base::DataVector * getGridCoefficientsForCG ()=0
gets a pointer to the sparse grids coefficients used in the CG method to solve one timestep.
void getGridCoefficientsForSC (sgpp::base::DataVector &Values)
stores the values of the (dehierarchized) grid in the sgpp::base::DataVector Values used by time step size control methods
sgpp::base::GridStorage * getGridStorage ()
std::string getODESolver ()
Returns the specified ODE solver for this instance.
sgpp::base::GridStorage * getOldGridStorage ()
sgpp::base::GridStorage * getSecondGridStorage ()
size_t getSumGridPointsComplete ()
Returns the number of average grid points for the complete grid.
size_t getSumGridPointsInner ()
Returns the number of average grid points for the inner grid.
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)=0
Multiplicates a vector with the matrix.
OperationParabolicPDESolverSystem ()
Constructor.
void saveAlpha ()
stores the current alpha_complete into alpha_complete_old to be available in the next timestep
void setODESolver (std::string ode)
defines the used ODE Solver for this instance, this is important because the implementation of mult and generateRHS depends on the used ODE solver
void setTimestepSize (double newTimestepSize)
set the size of the new timestep
virtual void startTimestep ()=0
Implements some start jobs of every timestep, e.g.discounting boundaries.
virtual ~OperationParabolicPDESolverSystem ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Attributes
sgpp::base::DataVector * alpha_complete
Pointer to the alphas (ansatzfunctions' coefficients)
sgpp::base::DataVector * alpha_complete_old
Pointer to the alphas from the last timestep, needed when using variable timestep sizes.
sgpp::base::DataVector * alpha_complete_tmp
Pointer to temporary alphas, needed when using variable timestep sizes.
bool bnewODESolver
checks whether a new ODE solver has been selected after creation
sgpp::base::Grid * BoundGrid
Pointer to the grid object.
size_t numSumGridpointsComplete
Stores number of average gridpoints, complete grid.
size_t numSumGridpointsInner
Stores number of average gridpoints, inner grid.
sgpp::base::GridStorage * oldGridStorage
Pointer to the grid from the last iteration.
sgpp::base::DataVector * rhs
sgpp::base::GridStorage * secondGridStorage
Pointer to the grid from the last aborted iteration.
double TimestepSize
the size of one timestep used in the ODE Solver
double TimestepSize_old
the size of the last timestep
std::string tOperationMode
specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler ImEul for implicit Euler CrNic for Crank Nicolson solver
Detailed Description
Abstract definition of a System that is used to solve parabolic partial differential equations.
So an instance of this class has to pass to any ODE Solver used in SGpp.
\(A \dot{u} = L \vec{u}\)
A: mass matrix L: space discretization (L-Operator)
Constructor & Destructor Documentation
OperationParabolicPDESolverSystem()
sgpp::solver::OperationParabolicPDESolverSystem::OperationParabolicPDESolverSystem ()
Constructor.
References bnewODESolver, numSumGridpointsComplete, and numSumGridpointsInner.
~OperationParabolicPDESolverSystem()
sgpp::solver::OperationParabolicPDESolverSystem::~OperationParabolicPDESolverSystem () virtual
Destructor.
Member Function Documentation
abortTimestep()
void sgpp::solver::OperationParabolicPDESolverSystem::abortTimestep ()
aborts the current timestep execution
References alpha_complete, alpha_complete_tmp, BoundGrid, sgpp::base::Grid::getStorage(), and secondGridStorage.
Referenced by sgpp::solver::VarTimestep::predictor(), and sgpp::solver::StepsizeControl::solve().
coarsenAndRefine()
virtual void sgpp::solver::OperationParabolicPDESolverSystem::coarsenAndRefine (bool isLastTimestep = false) pure virtual
Implemented in sgpp::pde::HeatEquationParabolicPDESolverSystem, and sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP.
Referenced by sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), sgpp::solver::Euler::solve(), and sgpp::solver::StepsizeControl::solve().
finishTimestep()
virtual void sgpp::solver::OperationParabolicPDESolverSystem::finishTimestep () pure virtual
performs some action that might be needed after a timestep has be finished in the ODE Solver, e.g.
some boundary adjustments.
Implemented in sgpp::pde::HeatEquationParabolicPDESolverSystem, and sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP.
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::VarTimestep::predictor(), sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), and sgpp::solver::Euler::solve().
generateRHS()
virtual sgpp::base::DataVector * sgpp::solver::OperationParabolicPDESolverSystem::generateRHS () pure virtual
generates the right hand side of the system
Returns
returns the rhs
Implemented in sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP, sgpp::pde::OperationParabolicPDESolverSystemDirichlet, and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries.
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::VarTimestep::predictor(), sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), and sgpp::solver::Euler::solve().
getGrid()
sgpp::base::Grid * sgpp::solver::OperationParabolicPDESolverSystem::getGrid ()
get the pointer to the underlying grid object
Returns
returns a pointer to the underlying grid object
References BoundGrid.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), and sgpp::solver::Euler::solve().
getGridCoefficients()
sgpp::base::DataVector * sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficients ()
gets a pointer to the sparse grids coefficients with evtl.
boundaries
Returns
alpha vector of complete grid
References alpha_complete.
Referenced by sgpp::solver::VarTimestep::predictor(), sgpp::solver::Euler::solve(), and sgpp::solver::StepsizeControl::solve().
getGridCoefficientsForCG()
virtual sgpp::base::DataVector * sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForCG () pure virtual
gets a pointer to the sparse grids coefficients used in the CG method to solve one timestep.
This is useful because (direchlet) boundaries can be skipped when solving the system.
Returns
alpha vector for CG method
Implemented in sgpp::pde::OperationParabolicPDESolverSystemDirichlet, and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries.
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::StepsizeControl::maxNorm(), sgpp::solver::VarTimestep::predictor(), sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), and sgpp::solver::Euler::solve().
getGridCoefficientsForSC()
void sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForSC (sgpp::base::DataVector & Values)
stores the values of the (dehierarchized) grid in the sgpp::base::DataVector Values used by time step size control methods
Parameters
Values sgpp::base::DataVector in which the values will be stored
References alpha_complete, sgpp::op_factory::createOperationHierarchisation(), and sgpp::base::OperationHierarchisation::doDehierarchisation().
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::VarTimestep::predictor(), and sgpp::solver::StepsizeControl::solve().
getGridStorage()
sgpp::base::GridStorage * sgpp::solver::OperationParabolicPDESolverSystem::getGridStorage ()
References BoundGrid, and sgpp::base::Grid::getStorage().
Referenced by sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), and sgpp::solver::StepsizeControl::maxNorm().
getODESolver()
std::string sgpp::solver::OperationParabolicPDESolverSystem::getODESolver ()
Returns the specified ODE solver for this instance.
Returns
the ODE solver: ExEul, ImEul or CrNic
References tOperationMode.
getOldGridStorage()
sgpp::base::GridStorage * sgpp::solver::OperationParabolicPDESolverSystem::getOldGridStorage ()
References oldGridStorage.
Referenced by sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), and sgpp::solver::StepsizeControl::maxNorm().
getSecondGridStorage()
sgpp::base::GridStorage * sgpp::solver::OperationParabolicPDESolverSystem::getSecondGridStorage ()
References secondGridStorage.
getSumGridPointsComplete()
size_t sgpp::solver::OperationParabolicPDESolverSystem::getSumGridPointsComplete ()
Returns the number of average grid points for the complete grid.
Returns
the number of average grid points for the complete grid
References numSumGridpointsComplete.
getSumGridPointsInner()
size_t sgpp::solver::OperationParabolicPDESolverSystem::getSumGridPointsInner ()
Returns the number of average grid points for the inner grid.
Returns
the number of average grid points for the inner grid
References numSumGridpointsInner.
mult()
virtual void sgpp::solver::OperationParabolicPDESolverSystem::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) pure virtual
Multiplicates a vector with the matrix.
Parameters
alpha sgpp::base::DataVector that contains the ansatzfunctions' coefficients
result sgpp::base::DataVector into which the result of the space discretization operation is stored
Implements sgpp::base::OperationMatrix.
Implemented in sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP, sgpp::pde::OperationParabolicPDESolverSystemDirichlet, and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries.
saveAlpha()
void sgpp::solver::OperationParabolicPDESolverSystem::saveAlpha ()
stores the current alpha_complete into alpha_complete_old to be available in the next timestep
References alpha_complete, alpha_complete_old, alpha_complete_tmp, BoundGrid, sgpp::base::Grid::getStorage(), and oldGridStorage.
Referenced by sgpp::solver::AdamsBashforth::solve(), and sgpp::solver::StepsizeControl::solve().
setODESolver()
void sgpp::solver::OperationParabolicPDESolverSystem::setODESolver (std::string ode)
defines the used ODE Solver for this instance, this is important because the implementation of mult and generateRHS depends on the used ODE solver
Parameters
ode the used ODESolver: ExEul, ImEul or CrNic
References bnewODESolver, and tOperationMode.
Referenced by sgpp::solver::VarTimestep::corrector(), sgpp::solver::VarTimestep::predictor(), and sgpp::solver::AdamsBashforth::solve().
setTimestepSize()
void sgpp::solver::OperationParabolicPDESolverSystem::setTimestepSize (double newTimestepSize)
set the size of the new timestep
Parameters
newTimestepSize the size of the next timestep
References TimestepSize, and TimestepSize_old.
Referenced by sgpp::solver::VarTimestep::predictor().
startTimestep()
virtual void sgpp::solver::OperationParabolicPDESolverSystem::startTimestep () pure virtual
Implements some start jobs of every timestep, e.g.discounting boundaries.
Implemented in sgpp::pde::HeatEquationParabolicPDESolverSystem, and sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP.
Referenced by sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS().
Member Data Documentation
alpha_complete
sgpp::base::DataVector* sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete protected
Pointer to the alphas (ansatzfunctions' coefficients)
Referenced by abortTimestep(), sgpp::pde::HeatEquationParabolicPDESolverSystem::finishTimestep(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::finishTimestep(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), getGridCoefficients(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::getGridCoefficientsForCG(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::getGridCoefficientsForCG(), getGridCoefficientsForSC(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), and saveAlpha().
alpha_complete_old
sgpp::base::DataVector* sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete_old protected
Pointer to the alphas from the last timestep, needed when using variable timestep sizes.
Referenced by sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), and saveAlpha().
alpha_complete_tmp
sgpp::base::DataVector* sgpp::solver::OperationParabolicPDESolverSystem::alpha_complete_tmp protected
Pointer to temporary alphas, needed when using variable timestep sizes.
Referenced by abortTimestep(), and saveAlpha().
bnewODESolver
bool sgpp::solver::OperationParabolicPDESolverSystem::bnewODESolver protected
checks whether a new ODE solver has been selected after creation
Referenced by OperationParabolicPDESolverSystem(), and setODESolver().
BoundGrid
sgpp::base::Grid* sgpp::solver::OperationParabolicPDESolverSystem::BoundGrid protected
Pointer to the grid object.
Referenced by abortTimestep(), getGrid(), getGridStorage(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), and saveAlpha().
numSumGridpointsComplete
size_t sgpp::solver::OperationParabolicPDESolverSystem::numSumGridpointsComplete protected
Stores number of average gridpoints, complete grid.
Referenced by getSumGridPointsComplete(), OperationParabolicPDESolverSystem(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::OperationParabolicPDESolverSystemDirichlet(), and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::OperationParabolicPDESolverSystemFreeBoundaries().
numSumGridpointsInner
size_t sgpp::solver::OperationParabolicPDESolverSystem::numSumGridpointsInner protected
Stores number of average gridpoints, inner grid.
Referenced by getSumGridPointsInner(), OperationParabolicPDESolverSystem(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::OperationParabolicPDESolverSystemDirichlet(), and sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::OperationParabolicPDESolverSystemFreeBoundaries().
oldGridStorage
sgpp::base::GridStorage* sgpp::solver::OperationParabolicPDESolverSystem::oldGridStorage protected
Pointer to the grid from the last iteration.
Referenced by getOldGridStorage(), and saveAlpha().
rhs
sgpp::base::DataVector* sgpp::solver::OperationParabolicPDESolverSystem::rhs protected
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), sgpp::pde::HeatEquationParabolicPDESolverSystem::~HeatEquationParabolicPDESolverSystem(), and sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::~HeatEquationParabolicPDESolverSystemParallelOMP().
secondGridStorage
sgpp::base::GridStorage* sgpp::solver::OperationParabolicPDESolverSystem::secondGridStorage protected
Pointer to the grid from the last aborted iteration.
Referenced by abortTimestep(), and getSecondGridStorage().
TimestepSize
double sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize protected
the size of one timestep used in the ODE Solver
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), and setTimestepSize().
TimestepSize_old
double sgpp::solver::OperationParabolicPDESolverSystem::TimestepSize_old protected
the size of the last timestep
Referenced by sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), and setTimestepSize().
tOperationMode
std::string sgpp::solver::OperationParabolicPDESolverSystem::tOperationMode protected
specifies in which solver this matrix is used, valid values are: ExEul for explicit Euler ImEul for implicit Euler CrNic for Crank Nicolson solver
Referenced by sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::generateRHS(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::generateRHS(), getODESolver(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::mult(), sgpp::pde::OperationParabolicPDESolverSystemDirichlet::mult(), sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries::mult(), and setODESolver().
The documentation for this class was generated from the following files:
solver/src/sgpp/solver/operation/hash/OperationParabolicPDESolverSystem.hpp
solver/src/sgpp/solver/operation/hash/OperationParabolicPDESolverSystem.cpp