SG++-Doxygen-Documentation: sgpp::pde::OperationMatrixLTwoDotPeriodic Class Reference
sgpp::pde::OperationMatrixLTwoDotPeriodic Class Reference
Implements the standard L 2 scalar product on periodic grids.
#include <OperationMatrixLTwoDotPeriodic.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationMatrixLTwoDotPeriodic (sgpp::base::GridStorage *gridStorage)
Constructor.
virtual ~OperationMatrixLTwoDotPeriodic ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Attributes
sgpp::base::GridStorage * gridStorage
Detailed Description
Implements the standard L 2 scalar product on periodic grids.
Constructor & Destructor Documentation
OperationMatrixLTwoDotPeriodic()
sgpp::pde::OperationMatrixLTwoDotPeriodic::OperationMatrixLTwoDotPeriodic (sgpp::base::GridStorage * gridStorage) explicit
Constructor.
Parameters
gridStorage pointer to the GridStorage of the grid
References gridStorage.
~OperationMatrixLTwoDotPeriodic()
sgpp::pde::OperationMatrixLTwoDotPeriodic::~OperationMatrixLTwoDotPeriodic () virtual
Destructor.
Member Function Documentation
mult()
void sgpp::pde::OperationMatrixLTwoDotPeriodic::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataMatrix::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getLevelIndexArraysForEval(), sgpp::base::DataVector::getSize(), sgpp::base::HashGridStorage::getSize(), gridStorage, and level.
Member Data Documentation
gridStorage
sgpp::base::GridStorage* sgpp::pde::OperationMatrixLTwoDotPeriodic::gridStorage protected
Referenced by mult(), and OperationMatrixLTwoDotPeriodic().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotPeriodic.hpp
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotPeriodic.cpp