SG++-Doxygen-Documentation: python.utils.json.JsonWriter Class Reference
python.utils.json.JsonWriter Class Reference
Writer for json-formatted objects.
Public Member Functions
write (self, obj, escaped_forward_slash=False)
Protected Member Functions
_append (self, s)
_write (self, obj)
Protected Attributes
_escaped_forward_slash
_results
Detailed Description
Writer for json-formatted objects.
Member Function Documentation
_append()
python.utils.json.JsonWriter._append (self, s) protected
References python.utils.json.JsonWriter._results.
Referenced by python.utils.json.JsonWriter._write().
_write()
python.utils.json.JsonWriter._write (self, obj) protected
References python.utils.json.JsonWriter._append(), python.utils.json.JsonWriter._escaped_forward_slash, and python.utils.json.JsonWriter._write().
Referenced by python.utils.json.JsonWriter._write().
write()
python.utils.json.JsonWriter.write (self, obj, escaped_forward_slash = False)
Member Data Documentation
_escaped_forward_slash
python.utils.json.JsonWriter._escaped_forward_slash protected
Referenced by python.utils.json.JsonWriter._write().
_results
python.utils.json.JsonWriter._results protected
Referenced by python.utils.json.JsonWriter._append().
The documentation for this class was generated from the following file:
datadriven/python/utils/json.py