SG++-Doxygen-Documentation: sgpp::pde::LaplaceEnhancedDownBBLinearBoundary Class Reference
sgpp::pde::LaplaceEnhancedDownBBLinearBoundary Class Reference
Implementation of sweep operator () for enhanced Laplace operator, down operation.
#include <LaplaceEnhancedDownBBLinearBoundary.hpp>
Public Member Functions
LaplaceEnhancedDownBBLinearBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual void operator() (sgpp::base::DataMatrix &source, sgpp::base::DataMatrix &result, grid_iterator &index, size_t dim)
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
virtual ~LaplaceEnhancedDownBBLinearBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::LaplaceEnhancedDownBBLinear
LaplaceEnhancedDownBBLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual ~LaplaceEnhancedDownBBLinear ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::LaplaceEnhancedDownBBLinear
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::LaplaceEnhancedDownBBLinear
void rec (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Down (L2 scalar product) without Bounding Box
void rec_GL (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (gradient and L2 scalar product) without Bounding Box
void rec_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Down (gradient) without Bounding Box
void rec_LG (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar product and gradient) without Bounding Box
void rec_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar products) without Bounding Box
void recBB (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Down (L2 scalar product) with Bounding Box
void recBB_GL (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (gradient and L2 scalar product) with Bounding Box
void recBB_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Down (gradient) with Bounding Box
void recBB_LG (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar product and gradient) with Bounding Box
void recBB_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar products) with Bounding Box
Protected Attributes inherited from sgpp::pde::LaplaceEnhancedDownBBLinear
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::BoundingBox * boundingBox
Pointer to the bounding box Obejct.
size_t cur_algo_dim_
current algorithmic dimension for the overall operator
const size_t numAlgoDims_
number of algorithmic dimensions
double * ptr_result_
pointer to DataMatrix containing result coefficients
double * ptr_source_
pointer to DataMatrix containing source coefficients
double q_
stretching of basis functions in current algorithmic domain
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage Object.
double t_
translation of basis function in current algorithmic domain
Detailed Description
Implementation of sweep operator () for enhanced Laplace operator, down operation.
This sweep operator calculates all downs (L2 scalar products and gradient) for a given dimension.
Constructor & Destructor Documentation
LaplaceEnhancedDownBBLinearBoundary()
sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::LaplaceEnhancedDownBBLinearBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~LaplaceEnhancedDownBBLinearBoundary()
sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::~LaplaceEnhancedDownBBLinearBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator() (sgpp::base::DataMatrix & source, sgpp::base::DataMatrix & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
Parameters
source sgpp::base::DataMatrix that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataMatrix that contains the result of the down operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction', here all downs are calculated
Reimplemented from sgpp::pde::LaplaceEnhancedDownBBLinear.
References sgpp::pde::LaplaceEnhancedDownBBLinear::algoDims, sgpp::pde::LaplaceEnhancedDownBBLinear::boundingBox, sgpp::pde::LaplaceEnhancedDownBBLinear::cur_algo_dim_, sgpp::base::DataMatrix::get(), sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::DataMatrix::getPointer(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::pde::LaplaceEnhancedDownBBLinear::numAlgoDims_, sgpp::pde::LaplaceEnhancedDownBBLinear::ptr_result_, sgpp::pde::LaplaceEnhancedDownBBLinear::ptr_source_, sgpp::pde::LaplaceEnhancedDownBBLinear::q_, sgpp::pde::LaplaceEnhancedDownBBLinear::rec(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), sgpp::pde::LaplaceEnhancedDownBBLinear::storage, and sgpp::pde::LaplaceEnhancedDownBBLinear::t_.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/LaplaceEnhancedDownBBLinearBoundary.hpp
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/LaplaceEnhancedDownBBLinearBoundary.cpp