SG++-Doxygen-Documentation: sgpp::pde::PhiPhiDownBBLinearBoundary Class Reference
sgpp::pde::PhiPhiDownBBLinearBoundary Class Reference
Implementation of sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
#include <PhiPhiDownBBLinearBoundary.hpp>
Public Member Functions
virtual void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of down in the direction of dimension dim
PhiPhiDownBBLinearBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiDownBBLinearBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::PhiPhiDownBBLinear
PhiPhiDownBBLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiDownBBLinear ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::PhiPhiDownBBLinear
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::PhiPhiDownBBLinear
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
recursive function for the calculation of Down without Bounding Box
void recBB (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double fl, double fr, double q, double t)
recursive function for the calculation of Down with Bouding Box
Protected Attributes inherited from sgpp::pde::PhiPhiDownBBLinear
sgpp::base::BoundingBox * boundingBox
Pointer to the bounding box Obejct.
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage Object.
Detailed Description
Implementation of sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
Constructor & Destructor Documentation
PhiPhiDownBBLinearBoundary()
sgpp::pde::PhiPhiDownBBLinearBoundary::PhiPhiDownBBLinearBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiDownBBLinearBoundary()
sgpp::pde::PhiPhiDownBBLinearBoundary::~PhiPhiDownBBLinearBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiDownBBLinearBoundary::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of down in the direction of dimension dim
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
On level zero the getfixDirechletBoundaries of the storage object evaluated
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the down operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::pde::PhiPhiDownBBLinear.
References sgpp::pde::PhiPhiDownBBLinear::boundingBox, sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::BoundingBox::hasDirichletBoundaryLeft(), sgpp::base::BoundingBox::hasDirichletBoundaryRight(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::pde::PhiPhiDownBBLinear::rec(), sgpp::pde::PhiPhiDownBBLinear::recBB(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), and sgpp::pde::PhiPhiDownBBLinear::storage.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/PhiPhiDownBBLinearBoundary.hpp
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/PhiPhiDownBBLinearBoundary.cpp