SG++-Doxygen-Documentation: sgpp::base::OperationEvalGradient Class Reference
sgpp::base::OperationEvalGradient Class Reference abstract
Abstract operation for evaluating a linear combination of basis functions and its gradient.
#include <OperationEvalGradient.hpp>
Public Member Functions
virtual void evalGradient (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient)
virtual double evalGradient (const DataVector &alpha, const DataVector &point, DataVector &gradient)=0
OperationEvalGradient ()
Constructor.
virtual ~OperationEvalGradient ()
Destructor.
Public Attributes
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Abstract operation for evaluating a linear combination of basis functions and its gradient.
Constructor & Destructor Documentation
OperationEvalGradient()
sgpp::base::OperationEvalGradient::OperationEvalGradient () inline
Constructor.
~OperationEvalGradient()
virtual sgpp::base::OperationEvalGradient::~OperationEvalGradient () inline virtual
Destructor.
Member Function Documentation
evalGradient() [1/2]
virtual void sgpp::base::OperationEvalGradient::evalGradient (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient) inline virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
Reimplemented in sgpp::base::OperationEvalGradientBsplineBoundaryNaive, sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive, sgpp::base::OperationEvalGradientBsplineNaive, sgpp::base::OperationEvalGradientFundamentalNakSplineNaive, sgpp::base::OperationEvalGradientFundamentalSplineNaive, sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalGradientModBsplineNaive, sgpp::base::OperationEvalGradientModFundamentalSplineNaive, sgpp::base::OperationEvalGradientModNakBsplineNaive, sgpp::base::OperationEvalGradientModWaveletNaive, sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive, sgpp::base::OperationEvalGradientNakBsplineExtendedNaive, sgpp::base::OperationEvalGradientNakBsplineModifiedNaive, sgpp::base::OperationEvalGradientNakBsplineNaive, sgpp::base::OperationEvalGradientNakPBsplineNaive, sgpp::base::OperationEvalGradientWaveletBoundaryNaive, sgpp::base::OperationEvalGradientWaveletNaive, sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive.
References alpha, evalGradient(), m, sgpp::base::DataMatrix::resize(), and sgpp::base::DataMatrix::setRow().
evalGradient() [2/2]
virtual double sgpp::base::OperationEvalGradient::evalGradient (const DataVector & alpha, const DataVector & point, DataVector & gradient) pure virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient vector of the linear combination
Returns
value of the linear combination
Implemented in sgpp::base::OperationEvalGradientBsplineBoundaryNaive, sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive, sgpp::base::OperationEvalGradientBsplineNaive, sgpp::base::OperationEvalGradientFundamentalNakSplineNaive, sgpp::base::OperationEvalGradientFundamentalSplineNaive, sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive, sgpp::base::OperationEvalGradientModBsplineNaive, sgpp::base::OperationEvalGradientModFundamentalSplineNaive, sgpp::base::OperationEvalGradientModNakBsplineNaive, sgpp::base::OperationEvalGradientModWaveletNaive, sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive, sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive, sgpp::base::OperationEvalGradientNakBsplineExtendedNaive, sgpp::base::OperationEvalGradientNakBsplineModifiedNaive, sgpp::base::OperationEvalGradientNakBsplineNaive, sgpp::base::OperationEvalGradientNakPBsplineNaive, sgpp::base::OperationEvalGradientWaveletBoundaryNaive, sgpp::base::OperationEvalGradientWaveletNaive, sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive, and sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive.
Referenced by evalGradient().
Member Data Documentation
pointInUnitCube
DataVector sgpp::base::OperationEvalGradient::pointInUnitCube
untransformed evaluation point (temporary vector)
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationEvalGradient.hpp