SG++-Doxygen-Documentation: sgpp::base::sle_solver::SLESolver Class Reference
sgpp::base::sle_solver::SLESolver Class Reference abstract
Abstract class for solving systems of linear equations.
#include <SLESolver.hpp>
Public Member Functions
SLESolver ()
Constructor.
virtual bool solve (SLE &system, DataMatrix &B, DataMatrix &X) const
Virtual method for solving multiple linear systems with different right-hand sides.
virtual bool solve (SLE &system, DataVector &b, DataVector &x) const =0
Pure virtual method for a solving linear system.
virtual ~SLESolver ()
Destructor.
Detailed Description
Abstract class for solving systems of linear equations.
Constructor & Destructor Documentation
SLESolver()
sgpp::base::sle_solver::SLESolver::SLESolver () inline
Constructor.
~SLESolver()
virtual sgpp::base::sle_solver::SLESolver::~SLESolver () inline virtual
Destructor.
Member Function Documentation
solve() [1/2]
virtual bool sgpp::base::sle_solver::SLESolver::solve (SLE & system, DataMatrix & B, DataMatrix & X) const inline virtual
Virtual method for solving multiple linear systems with different right-hand sides.
Defaults to calling the solve() method for a single right-hand side multiple times.
Parameters
system system to be solved
B matrix of right-hand sides
[out] X matrix of solutions to the systems
Returns
whether all went well (false if errors occurred)
Reimplemented in sgpp::base::sle_solver::Armadillo, sgpp::base::sle_solver::Auto, sgpp::base::sle_solver::Eigen, and sgpp::base::sle_solver::UMFPACK.
References sgpp::base::DataMatrix::getColumn(), sgpp::base::SLE::getDimension(), sgpp::base::DataMatrix::getNcols(), m, and solve().
solve() [2/2]
virtual bool sgpp::base::sle_solver::SLESolver::solve (SLE & system, DataVector & b, DataVector & x) const pure virtual
Pure virtual method for a solving linear system.
Parameters
system system to be solved
b right-hand side
[out] x solution to the system
Returns
whether all went well (false if errors occurred)
Implemented in sgpp::base::sle_solver::Armadillo, sgpp::base::sle_solver::Auto, sgpp::base::sle_solver::BiCGStab, sgpp::base::sle_solver::Eigen, sgpp::base::sle_solver::GaussianElimination, sgpp::base::sle_solver::Gmmpp, and sgpp::base::sle_solver::UMFPACK.
Referenced by sgpp::optimization::optimizer::LevenbergMarquardt::optimize(), sgpp::optimization::optimizer::AdaptiveNewton::optimize(), sgpp::optimization::optimizer::Newton::optimize(), and solve().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/sle/solver/SLESolver.hpp