SG++-Doxygen-Documentation: sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type > Class Template Reference
sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type > Class Template Reference
#include <StreamingBSplineOCLKernelSourceBuilder.hpp>
Public Member Functions
std::string generateSourceMult (size_t dims)
std::string generateSourceMultTrans (size_t dims)
StreamingBSplineOCLKernelSourceBuilder (size_t degree, std::shared_ptr< base::OCLOperationConfiguration > parameters)
Protected Member Functions
std::string getBSplineEvalFormula () const
std::string getDegreePlusOneHalvedString () const
Static Protected Member Functions
static std::string replace (const std::string &str, const std::string &searchStr, const std::string &replaceStr)
static std::string replace (const std::string &str, const std::string &searchStr, size_t replaceNumber)
static void replaceInPlace (std::string &str, const std::string &searchStr, const std::string &replaceStr)
static void replaceInPlace (std::string &str, const std::string &searchStr, size_t number)
Constructor & Destructor Documentation
StreamingBSplineOCLKernelSourceBuilder()
template<typename real_type > sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::StreamingBSplineOCLKernelSourceBuilder (size_t degree, std::shared_ptr< base::OCLOperationConfiguration > parameters) inline
Member Function Documentation
generateSourceMult()
template<typename real_type > std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMult (size_t dims) inline
References sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::getBSplineEvalFormula(), sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::getDegreePlusOneHalvedString(), sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replace(), and sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replaceInPlace().
generateSourceMultTrans()
template<typename real_type > std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMultTrans (size_t dims) inline
getBSplineEvalFormula()
template<typename real_type > std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::getBSplineEvalFormula () const inline protected
References sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replace().
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMult().
getDegreePlusOneHalvedString()
template<typename real_type > std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::getDegreePlusOneHalvedString () const inline protected
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMult().
replace() [1/2]
template<typename real_type > static std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replace (const std::string & str, const std::string & searchStr, const std::string & replaceStr) inline static protected
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMult(), and sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::getBSplineEvalFormula().
replace() [2/2]
template<typename real_type > static std::string sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replace (const std::string & str, const std::string & searchStr, size_t replaceNumber) inline static protected
replaceInPlace() [1/2]
template<typename real_type > static void sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replaceInPlace (std::string & str, const std::string & searchStr, const std::string & replaceStr) inline static protected
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::generateSourceMult().
replaceInPlace() [2/2]
template<typename real_type > static void sgpp::datadriven::StreamingBSplineOCLKernelSourceBuilder< real_type >::replaceInPlace (std::string & str, const std::string & searchStr, size_t number) inline static protected
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingBSplineOCL/StreamingBSplineOCLKernelSourceBuilder.hpp