SG++-Doxygen-Documentation: sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates Class Reference
sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates Class Reference
#include <OperationMakePositiveCandidateSetAlgorithm.hpp>
Public Member Functions
void nextCandidates (base::Grid &grid, base::DataVector &alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > &candidates) override
Load the next candidate set that contains grid points with the currently explored levelsum.
size_t numCandidates () override
base::DataVector & numCandidatesPerIteration () override
OperationMakePositiveLoadFullGridCandidates (size_t maxLevel)
~OperationMakePositiveLoadFullGridCandidates () override
Public Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
size_t costsComputingCandidates ()
base::DataVector & costsComputingCandidatesPerIteration ()
base::DataVector & numCandidatesPerLevel ()
OperationMakePositiveCandidateSetAlgorithm (size_t maxLevel)
Constructor.
void setVerbose (bool pverbose)
Set verbosity level.
virtual ~OperationMakePositiveCandidateSetAlgorithm ()
Desctructor.
Additional Inherited Members
Protected Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
void findNodesWithNegativeCoefficients (base::DataVector &alpha, std::vector< size_t > &negativeGridPoints, double tol=-1e-14)
Extract grid points with negative coefficient.
Protected Attributes inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
base::DataVector costsPerIteration
comparison costs per iteration
base::DataVector gridPointsPerLevel
candiddate grid points per level
size_t iteration
iteration counter
size_t maxLevel
maximum full grid level for the candidate set
bool verbose
verbosity level
Constructor & Destructor Documentation
OperationMakePositiveLoadFullGridCandidates()
sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::OperationMakePositiveLoadFullGridCandidates (size_t maxLevel) explicit
~OperationMakePositiveLoadFullGridCandidates()
sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::~OperationMakePositiveLoadFullGridCandidates () override
Member Function Documentation
nextCandidates()
void sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::nextCandidates (base::Grid & grid, base::DataVector & alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > & candidates) override virtual
Load the next candidate set that contains grid points with the currently explored levelsum.
Parameters
grid current sparse grid that needs to be extended
alpha corresponding coefficient vector
levelSum current levelsum to be explored
candidates vector that contains the candidate set for the current levelsum
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getMaxLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), grid(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::gridPointsPerLevel, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::iteration, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::maxLevel, and sgpp::base::DataVector::setAll().
numCandidates()
size_t sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::numCandidates () override virtual
Returns
total number of candidates
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
numCandidatesPerIteration()
base::DataVector & sgpp::datadriven::OperationMakePositiveLoadFullGridCandidates::numCandidatesPerIteration () override virtual
Returns
number of candidates that have been computed per iteration
Implements sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.cpp