SG++-Doxygen-Documentation: sgpp::base::OperationWeightedSecondMomentNak Class Reference
sgpp::base::OperationWeightedSecondMomentNak Class Reference
This class provides the second moment of a sparse grid function f given as interpolant of any not a knot B-spline basis w.r.t.
#include <OperationWeightedSecondMomentNak.hpp>
Public Member Functions
double doWeightedQuadrature (DataVector &alpha, sgpp::base::DistributionsVector pdfs) override
Quadrature for not a knot B-spline basis functions w.r.t.
std::shared_ptr< sgpp::base::SBasis > initializeBasis (sgpp::base::GridType gridType, size_t degree)
initializes a nak B spline basis according to gridType and degree
OperationWeightedSecondMomentNak (GridStorage &storage, GridType gridType, size_t degree, size_t quadOrder)
Constructor of OperationQuadratureNakBsplineExtended.
~OperationWeightedSecondMomentNak () override
Public Member Functions inherited from sgpp::base::OperationWeightedSecondMoment
OperationWeightedSecondMoment ()
Constructor.
virtual ~OperationWeightedSecondMoment ()
Destructor.
Detailed Description
This class provides the second moment of a sparse grid function f given as interpolant of any not a knot B-spline basis w.r.t.
a probability density function rho, i.e. int f(x)^2 rho (x) dx
Constructor & Destructor Documentation
OperationWeightedSecondMomentNak()
sgpp::base::OperationWeightedSecondMomentNak::OperationWeightedSecondMomentNak (GridStorage & storage, GridType gridType, size_t degree, size_t quadOrder) inline
Constructor of OperationQuadratureNakBsplineExtended.
Parameters
storage Pointer to the grid's GridStorage object
gridType grid type
degree the B-spline degree
quadOrder quadrature order
References sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), and initializeBasis().
~OperationWeightedSecondMomentNak()
sgpp::base::OperationWeightedSecondMomentNak::~OperationWeightedSecondMomentNak () inline override
Member Function Documentation
doWeightedQuadrature()
double sgpp::base::OperationWeightedSecondMomentNak::doWeightedQuadrature (DataVector & alpha, sgpp::base::DistributionsVector pdfs) override virtual
Quadrature for not a knot B-spline basis functions w.r.t.
a probability density function
Parameters
alpha Coefficient vector for current grid
pdfs probability density functions
Implements sgpp::base::OperationWeightedSecondMoment.
References alpha, sgpp::base::DistributionsVector::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPointIndex(), sgpp::base::HashGridStorage::getPointLevel(), and sgpp::base::DataVector::getSize().
initializeBasis()
std::shared_ptr< sgpp::base::SBasis > sgpp::base::OperationWeightedSecondMomentNak::initializeBasis (sgpp::base::GridType gridType, size_t degree)
initializes a nak B spline basis according to gridType and degree
Parameters
gridType type of the basis
degree degree of the basis
Returns
the nak Bsplien basis
References sgpp::base::ModNakBspline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, and sgpp::base::NakPBspline.
Referenced by OperationWeightedSecondMomentNak().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationWeightedSecondMomentNak.hpp
base/src/sgpp/base/operation/hash/OperationWeightedSecondMomentNak.cpp