SG++-Doxygen-Documentation: sgpp::base::BsplineModifiedBasis< LT, IT > Class Template Reference
sgpp::base::BsplineModifiedBasis< LT, IT > Class Template Reference
Modified B-spline basis on Noboundary grids.
#include <BsplineModifiedBasis.hpp>
Public Member Functions
BsplineModifiedBasis ()
Default constructor.
BsplineModifiedBasis (size_t degree)
Constructor.
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
double getIntegral (LT l, IT i) override
double modifiedBSpline (double x, size_t p) const
double modifiedBSplineDx (double x, size_t p) const
double modifiedBSplineDxDx (double x, size_t p) const
~BsplineModifiedBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::BsplineModifiedBasis< LT, IT >
Modified B-spline basis on Noboundary grids.
Constructor & Destructor Documentation
BsplineModifiedBasis() [1/2]
template<class LT , class IT > sgpp::base::BsplineModifiedBasis< LT, IT >::BsplineModifiedBasis () inline
Default constructor.
BsplineModifiedBasis() [2/2]
template<class LT , class IT > sgpp::base::BsplineModifiedBasis< LT, IT >::BsplineModifiedBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
~BsplineModifiedBasis()
template<class LT , class IT > sgpp::base::BsplineModifiedBasis< LT, IT >::~BsplineModifiedBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of modified B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis, and sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSpline().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), and sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of modified B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis, and sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDx().
Referenced by sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), and sgpp::pde::OperationLaplaceModBspline::mult().
evalDxDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of modified B-spline basis function
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis, and sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDxDx().
Referenced by sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::BsplineModifiedBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
value of the integral
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::OperationQuadratureModBspline::doQuadrature().
modifiedBSpline()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSpline (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of modified uniform B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::BsplineModifiedBasis< LT, IT >::eval().
modifiedBSplineDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDx (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of derivative of modified uniform B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::BsplineModifiedBasis< LT, IT >::evalDx().
modifiedBSplineDxDx()
template<class LT , class IT > double sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDxDx (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of 2nd derivative of modified uniform B-spline (e.g. index == 1)
References sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::BsplineModifiedBasis< LT, IT >::evalDxDx().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::BsplineModifiedBasis< LT, IT >::bsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::BsplineModifiedBasis< LT, IT >::eval(), sgpp::base::BsplineModifiedBasis< LT, IT >::evalDx(), sgpp::base::BsplineModifiedBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineModifiedBasis< LT, IT >::getDegree(), sgpp::base::BsplineModifiedBasis< LT, IT >::getIntegral(), sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSpline(), sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDx(), and sgpp::base::BsplineModifiedBasis< LT, IT >::modifiedBSplineDxDx().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/BsplineModifiedBasis.hpp