SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::GraphCreationWorker Class Reference
sgpp::datadriven::clusteringmpi::GraphCreationWorker Class Reference
#include <OperationCreateGraphMPI.hpp>
Public Member Functions
GraphCreationWorker ()
GraphCreationWorker (sgpp::base::DataMatrix &data, int k)
void start_worker_main (void)
virtual ~GraphCreationWorker (void)
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual ~MPIWorkerBase (void)
Protected Member Functions
void divide_workpackages (int *package, std::vector< int > &graph)
Protected Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase
MPIWorkerGraphBase (sgpp::base::DataMatrix &data, int k)
MPIWorkerGraphBase (std::string operationName)
MPIWorkerGraphBase (std::string operationName, sgpp::base::DataMatrix &data, int k)
virtual ~MPIWorkerGraphBase (void)
Protected Attributes
double lambda
MPI_Comm & master_worker_comm
DensityOCLMultiPlatform::OperationCreateGraphOCL * op
bool opencl_node
bool overseer_node
MPI_Comm & sub_worker_comm
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase
double * dataset
int dataset_size
int dimensions
int k
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
bool verbose
Constructor & Destructor Documentation
GraphCreationWorker() [1/2]
sgpp::datadriven::clusteringmpi::GraphCreationWorker::GraphCreationWorker () inline
References sgpp::datadriven::createNearestNeighborGraphConfigured(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dataset, sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dataset_size, sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dimensions, sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::k, op, opencl_node, and overseer_node.
GraphCreationWorker() [2/2]
sgpp::datadriven::clusteringmpi::GraphCreationWorker::GraphCreationWorker (sgpp::base::DataMatrix & data, int k) inline
~GraphCreationWorker()
virtual sgpp::datadriven::clusteringmpi::GraphCreationWorker::~GraphCreationWorker (void) inline virtual
References op, and opencl_node.
Member Function Documentation
divide_workpackages()
void sgpp::datadriven::clusteringmpi::GraphCreationWorker::divide_workpackages (int * package, std::vector< int > & graph) inline protected
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_configuration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), json::Node::getInt(), sgpp::datadriven::clusteringmpi::SimpleQueue< T >::is_finished(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::k, sgpp::datadriven::clusteringmpi::SimpleQueue< T >::receive_result(), sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
Referenced by sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::create_graph(), and start_worker_main().
start_worker_main()
void sgpp::datadriven::clusteringmpi::GraphCreationWorker::start_worker_main (void) inline virtual
Implements sgpp::datadriven::clusteringmpi::MPIWorkerBase.
References sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::create_graph(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dataset, sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dataset_size, sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::dimensions, divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerGraphBase::k, master_worker_comm, op, opencl_node, sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
Member Data Documentation
lambda
double sgpp::datadriven::clusteringmpi::GraphCreationWorker::lambda protected
master_worker_comm
MPI_Comm& sgpp::datadriven::clusteringmpi::GraphCreationWorker::master_worker_comm protected
Referenced by start_worker_main().
op
DensityOCLMultiPlatform::OperationCreateGraphOCL* sgpp::datadriven::clusteringmpi::GraphCreationWorker::op protected
Referenced by GraphCreationWorker(), start_worker_main(), and ~GraphCreationWorker().
opencl_node
bool sgpp::datadriven::clusteringmpi::GraphCreationWorker::opencl_node protected
Referenced by GraphCreationWorker(), start_worker_main(), and ~GraphCreationWorker().
overseer_node
bool sgpp::datadriven::clusteringmpi::GraphCreationWorker::overseer_node protected
Referenced by GraphCreationWorker().
sub_worker_comm
MPI_Comm& sgpp::datadriven::clusteringmpi::GraphCreationWorker::sub_worker_comm protected
Referenced by sgpp::datadriven::clusteringmpi::OperationGraphCreationMPI::create_graph(), divide_workpackages(), and start_worker_main().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationCreateGraphMPI.hpp