SG++-Doxygen-Documentation: sgpp::base::HashGridPoint Class Reference
sgpp::base::HashGridPoint Class Reference
This Class represents one Gridpoint.
#include <HashGridPoint.hpp>
Public Types
typedef uint32_t index_type
index type
typedef uint32_t level_type
level type
Public Member Functions
HashGridPoint & assign (const HashGridPoint &rhs)
A wrapper for operator=.
bool equals (const HashGridPoint &rhs) const
checks whether this gridpoints is identical to another one
void get (size_t d, level_type &l, index_type &i) const
gets level l and index i in dimension d by reference parameters
size_t getDimension () const
Gets the dimension of the gridpoint.
size_t getHash () const
gets the hash value of the current instance
index_type getIndex (size_t d) const
gets index i in dimension d
void getLeftBoundaryPoint (size_t dim)
Sets the index to the grid point at the left boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
void getLeftChild (size_t dim)
Sets the index to the left child.
void getLeftLevelZero (size_t dim)
Sets the index to the left level zero parent.
level_type getLevel (size_t d) const
gets level l in dimension d
level_type getLevelMax () const
Returns the maximum of the one-dimensional levels, i.e., \(|\vec{l}|_\infty \).
level_type getLevelMin () const
Returns the minimum of the one-dimensional levels.
level_type getLevelSum () const
Returns the sum of the one-dimensional levels, i.e., \(|\vec{l}|_1 \).
void getParent (size_t dim)
Sets the index to the parent WARNING: this just works for grids without boundaries.
void getRightBoundaryPoint (size_t dim)
Sets the index to the grid point at the right boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
void getRightChild (size_t dim)
Sets the index to the right child.
void getRightLevelZero (size_t dim)
Sets the index to the right level zero parent.
void getRoot (size_t d)
Resets the index to the top level in direction d.
double getStandardCoordinate (size_t d) const
determines the coordinate in a given dimension "Standard" means no bounding box (i.e., the domain is the unit hypercube) and no stretching (i.e., the points have the standard locations \(i \cdot 2^{-\ell}\)).
void getStandardCoordinates (DataVector &coordinates) const
Sets the entries of DataVector p to the coordinates of the gridpoint "Standard" means no bounding box (i.e., the domain is the unit hypercube) and no stretching (i.e., the points have the standard locations \(i \cdot 2^{-\ell}\)).
HashGridPoint ()
Standard-Constructor.
HashGridPoint (const HashGridPoint &o)
Copy-Constructor.
HashGridPoint (size_t dimension)
Constructor of a n-Dim gridpoint.
HashGridPoint (std::istream &istream, int version)
Serialisation-Constructor.
bool isHierarchicalAncestor (HashGridPoint &gpj)
checks if this is a hierarchical ancestor of gpj
bool isHierarchicalAncestor (HashGridPoint &gpj, size_t dim)
checks if this is a hierarchical ancestor of gpj in dimension dim
bool isInnerPoint () const
Determines if the grid point is an inner grid point.
bool isLeaf ()
Checks if this grid point has not a single child in any dimension.
HashGridPoint & operator= (const HashGridPoint &rhs)
operator to assign the current grid point with the values of another one
void push (size_t d, level_type l, index_type i)
Sets level l and index i in dimension d and doesn't rehash the HashGridPoint object.
void push (size_t d, level_type l, index_type i, bool isLeaf)
Sets level l and index i in dimension d and the Leaf property and doesn't rehash the HashGridPoint object.
void rehash ()
rehashs the current gridpoint and sets hInv
void serialize (std::ostream &ostream, int version)
Serialize this Gridpoint e.g.
void set (size_t d, level_type l, index_type i)
Sets level l and index i in dimension d and rehashs the HashGridPoint object.
void set (size_t d, level_type l, index_type i, bool isLeaf)
Sets level l and index i in dimension d and the Leaf property and rehashs the HashGridPoint object.
void setAsHierarchicalGridPoint (size_t dim, level_type level, index_type index)
Sets the index to the grid point at the left boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
void setLeaf (bool isLeaf)
Set the leaf property; a grid point is called a leaf, if it has not a single child.
std::string toString () const
Generates a string with level and index of the gridpoint.
void toString (std::ostream &stream) const
Generates a string with level and index of the gridpoint.
~HashGridPoint ()
Destructor.
Friends
struct HashGridPointEqualityFunctor
struct HashGridPointHashFunctor
struct HashGridPointPointerEqualityFunctor
struct HashGridPointPointerHashFunctor
Detailed Description
This Class represents one Gridpoint.
A Gridpoint is given by its ansatzfunctions that are not zero in every dimension. Instances of this class are members in the hashmap that represents the whole grid.
Member Typedef Documentation
index_type
typedef uint32_t sgpp::base::HashGridPoint::index_type
index type
level_type
typedef uint32_t sgpp::base::HashGridPoint::level_type
level type
Constructor & Destructor Documentation
HashGridPoint() [1/4]
sgpp::base::HashGridPoint::HashGridPoint (size_t dimension) explicit
Constructor of a n-Dim gridpoint.
Parameters
dimension the dimension of the gridpoint
HashGridPoint() [2/4]
sgpp::base::HashGridPoint::HashGridPoint ()
Standard-Constructor.
HashGridPoint() [3/4]
sgpp::base::HashGridPoint::HashGridPoint (const HashGridPoint & o)
Copy-Constructor.
Parameters
o constant reference to HashGridPoint object
References rehash().
HashGridPoint() [4/4]
sgpp::base::HashGridPoint::HashGridPoint (std::istream & istream, int version)
Serialisation-Constructor.
Parameters
istream instream object the contains the information about the gridpoint
version the serialization version of the file
References rehash().
~HashGridPoint()
sgpp::base::HashGridPoint::~HashGridPoint ()
Destructor.
Member Function Documentation
assign()
HashGridPoint & sgpp::base::HashGridPoint::assign (const HashGridPoint & rhs)
A wrapper for operator=.
Parameters
rhs a reference to a HashGridPoint that contains the values that should be copied
Returns
returns a reference HashGridPoint
References operator=().
equals()
bool sgpp::base::HashGridPoint::equals (const HashGridPoint & rhs) const
checks whether this gridpoints is identical to another one
Running under WINDOW this is defined the way around, MSDN 2009: A binary predicate f(x,y) is a function object that has two argument objects x and y and a return value of true or false. An ordering imposed on a hash_map is a strict weak ordering if the binary predicate is irreflexive, antisymmetric, and transitive and if equivalence is transitive, where two objects x and y are defined to be equivalent when both f(x,y) and f(y,x) are false -> equalsSGLRBHash
Parameters
rhs reference the another HashGridPoint instance
Returns
true if the gridpoints are identical otherwise false
Referenced by sgpp::base::HashGridPointEqualityFunctor::operator()(), and sgpp::base::HashGridPointPointerEqualityFunctor::operator()().
get()
void sgpp::base::HashGridPoint::get (size_t d, level_type & l, index_type & i) const inline
gets level l and index i in dimension d by reference parameters
Parameters
d the dimension in which the ansatz function should be read
l reference parameter for the level of the ansatz function
i reference parameter for the index of the ansatz function
Referenced by sgpp::base::HashGenerator::boundaries_rec(), sgpp::base::HashGenerator::boundaries_truncated_rec(), sgpp::base::HashGenerator::cliques_iter(), sgpp::datadriven::RefinementHandler::doRefinementForClass(), sgpp::datadriven::OperationDotProductLinear::eval(), sgpp::datadriven::OperationDotProductModLinear::eval(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::base::HashGridIterator::get(), sgpp::datadriven::LearnerVectorizedPerformanceCalculator::getGFlopAndGByte(), sgpp::base::HashGridIterator::getGridDepth(), getLeftChild(), getParent(), getRightChild(), sgpp::base::HashGridIterator::hintLeft(), sgpp::base::HashGridIterator::hintRight(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::PrewaveletGridGenerator::refine(), sgpp::base::MultipleClassRefinement::refineGridpoint(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGenerator::square_rec(), sgpp::datadriven::ClassificationRefinementFunctor::stepDown(), sgpp::base::HashGridIterator::stepLeft(), sgpp::base::HashGridIterator::stepRight(), sgpp::base::HashGenerator::trunc_rec(), and sgpp::base::HashGridIterator::up().
getDimension()
size_t sgpp::base::HashGridPoint::getDimension () const
Gets the dimension of the gridpoint.
Returns
the dimension of the gridpoint
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection(), sgpp::combigrid::FullGrid::findGridPointInFullGrid(), sgpp::base::AbstractRefinement_refinement_key::getLevelVector(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport(), and sgpp::base::operator<<().
getHash()
size_t sgpp::base::HashGridPoint::getHash () const
gets the hash value of the current instance
Returns
the hash value of the instance
Referenced by sgpp::base::HashGridPointHashFunctor::operator()(), and sgpp::base::HashGridPointPointerHashFunctor::operator()().
getIndex()
index_type sgpp::base::HashGridPoint::getIndex (size_t d) const inline
gets index i in dimension d
Parameters
d the dimension in which the ansatz function should be read
Returns
index
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::HierarchisationSLE::evalFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::HierarchisationSLE::evalNaturalBsplineFunctionAtGridPoint(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalSplineFunctionAtGridPoint(), sgpp::combigrid::FullGrid::findGridPointInFullGrid(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getChild(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getParent(), sgpp::datadriven::ZeroCrossingRefinementFunctor::goDown(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport(), sgpp::base::HashGridStorage::insert(), sgpp::datadriven::PiecewiseConstantRegression::Node::integrate(), isHierarchicalAncestor(), sgpp::datadriven::ZeroCrossingRefinementFunctor::isLeftChild(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::GridPrinter::printLevelIndexGrid(), and sgpp::optimization::file_io::writeGrid().
getLeftBoundaryPoint()
void sgpp::base::HashGridPoint::getLeftBoundaryPoint (size_t dim) inline
Sets the index to the grid point at the left boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
Parameters
dim the dimension in which the modification is taken place
References set().
getLeftChild()
void sgpp::base::HashGridPoint::getLeftChild (size_t dim) inline
Sets the index to the left child.
Parameters
dim the dimension in which the modification is taken place
References get(), and set().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), and sgpp::datadriven::OperationMultiEvalCuda::prepare().
getLeftLevelZero()
void sgpp::base::HashGridPoint::getLeftLevelZero (size_t dim) inline
Sets the index to the left level zero parent.
Parameters
dim the dimension in which the modification is taken place
References set().
getLevel()
level_type sgpp::base::HashGridPoint::getLevel (size_t d) const inline
gets level l in dimension d
Parameters
d the dimension in which the ansatz function should be read
Returns
level
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::HierarchisationSLE::evalFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::HierarchisationSLE::evalNaturalBsplineFunctionAtGridPoint(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalNakSplineModifiedFunctionAtGridPoint(), sgpp::base::HierarchisationSLE::evalWeaklyFundamentalSplineFunctionAtGridPoint(), sgpp::combigrid::FullGrid::findGridPointInFullGrid(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorSOO::generate(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getChild(), sgpp::base::AbstractRefinement_refinement_key::getLevelVector(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getParent(), sgpp::datadriven::ZeroCrossingRefinementFunctor::goDown(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace(), sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix(), sgpp::base::HashGridStorage::insert(), sgpp::datadriven::PiecewiseConstantRegression::Node::integrate(), isHierarchicalAncestor(), sgpp::datadriven::DataBasedRefinementFunctor::isWithinSupport(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyNaive::multTranspose(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::base::GridPrinter::printLevelIndexGrid(), sgpp::base::MultipleClassRefinement::refineGridpoint(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), and sgpp::optimization::file_io::writeGrid().
getLevelMax()
HashGridPoint::level_type sgpp::base::HashGridPoint::getLevelMax () const
Returns the maximum of the one-dimensional levels, i.e., \(|\vec{l}|_\infty \).
Returns
the maximum of the one-dimensional levels
Referenced by sgpp::base::HashGenerator::cliques_iter(), sgpp::datadriven::OperationRegularizationDiagonal::initAnisotropicPenalty(), sgpp::datadriven::OperationRegularizationDiagonal::initIsotropicPenalty(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), and sgpp::base::HashGenerator::regular_periodic_boundary_iter().
getLevelMin()
HashGridPoint::level_type sgpp::base::HashGridPoint::getLevelMin () const
Returns the minimum of the one-dimensional levels.
Returns
the minimum of the one-dimensional levels
Referenced by sgpp::datadriven::OperationRegularizationDiagonal::initAnisotropicPenalty(), and sgpp::datadriven::OperationRegularizationDiagonal::initIsotropicPenalty().
getLevelSum()
HashGridPoint::level_type sgpp::base::HashGridPoint::getLevelSum () const
Returns the sum of the one-dimensional levels, i.e., \(|\vec{l}|_1 \).
Returns
the sum of the one-dimensional levels
Referenced by sgpp::base::HashGenerator::cliques_iter(), sgpp::datadriven::ClassificationRefinementFunctor::collectNeighbors(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::datadriven::DataBasedRefinementFunctor::operator()(), sgpp::datadriven::GridPointBasedRefinementFunctor::operator()(), sgpp::datadriven::ZeroCrossingRefinementFunctor::operator()(), sgpp::base::SurplusVolumeRefinementFunctor::operator()(), sgpp::base::SurplusVolumeCoarseningFunctor::operator()(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), and sgpp::base::HashGenerator::regular_periodic_boundary_iter().
getParent()
void sgpp::base::HashGridPoint::getParent (size_t dim) inline
Sets the index to the parent WARNING: this just works for grids without boundaries.
Parameters
dim the dimension in which the modification is taken place
References get(), and set().
Referenced by sgpp::base::HashGridStorage::insert().
getRightBoundaryPoint()
void sgpp::base::HashGridPoint::getRightBoundaryPoint (size_t dim) inline
Sets the index to the grid point at the right boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
Parameters
dim the dimension in which the modification is taken place
References set().
getRightChild()
void sgpp::base::HashGridPoint::getRightChild (size_t dim) inline
Sets the index to the right child.
Parameters
dim the dimension in which the modification is taken place
References get(), and set().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), and sgpp::datadriven::OperationMultiEvalCuda::prepare().
getRightLevelZero()
void sgpp::base::HashGridPoint::getRightLevelZero (size_t dim) inline
Sets the index to the right level zero parent.
Parameters
dim the dimension in which the modification is taken place
References set().
getRoot()
void sgpp::base::HashGridPoint::getRoot (size_t d) inline
Resets the index to the top level in direction d.
Parameters
d the dimension in which the modification is taken place
References set().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids().
getStandardCoordinate()
double sgpp::base::HashGridPoint::getStandardCoordinate (size_t d) const inline
determines the coordinate in a given dimension "Standard" means no bounding box (i.e., the domain is the unit hypercube) and no stretching (i.e., the points have the standard locations \(i \cdot 2^{-\ell}\)).
Parameters
d the dimension in which the coordinate should be calculated
Returns
the coordinate in the given dimension
Referenced by sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted(), sgpp::base::HashRefinementInteraction::createGridpoint(), sgpp::datadriven::OperationDensitySampling1DLinear::doSampling1D(), sgpp::datadriven::OperationInverseRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation1D(), getStandardCoordinates(), sgpp::datadriven::PiecewiseConstantRegression::Node::integrate(), sgpp::datadriven::DataBasedRefinementFunctor::isWithinSupport(), sgpp::base::operator<<(), and sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature().
getStandardCoordinates()
void sgpp::base::HashGridPoint::getStandardCoordinates (DataVector & coordinates) const
Sets the entries of DataVector p to the coordinates of the gridpoint "Standard" means no bounding box (i.e., the domain is the unit hypercube) and no stretching (i.e., the points have the standard locations \(i \cdot 2^{-\ell}\)).
Parameters
coordinates the DataVector that should be overwritten with the coordinates
References getStandardCoordinate(), and sgpp::base::DataVector::set().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::OperationMakePositiveInterpolateBoundaryOfSupport::computeHierarchicalCoefficients(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getEvalVector(), sgpp::base::MultipleClassPoint::MultipleClassPoint(), sgpp::datadriven::GridPointBasedRefinementFunctor::operator()(), and sgpp::base::HashGenerator::regular_inter_iter().
isHierarchicalAncestor() [1/2]
bool sgpp::base::HashGridPoint::isHierarchicalAncestor (HashGridPoint & gpj)
checks if this is a hierarchical ancestor of gpj
Parameters
gpj
Returns
References isHierarchicalAncestor().
Referenced by sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport(), and isHierarchicalAncestor().
isHierarchicalAncestor() [2/2]
bool sgpp::base::HashGridPoint::isHierarchicalAncestor (HashGridPoint & gpj, size_t dim)
checks if this is a hierarchical ancestor of gpj in dimension dim
Parameters
gpj
dim
Returns
References getIndex(), and getLevel().
isInnerPoint()
bool sgpp::base::HashGridPoint::isInnerPoint () const
Determines if the grid point is an inner grid point.
Inner points are exactly those points which are not on the boundary in any dimension.
Returns
true if the grid point is an inner grid point
Referenced by sgpp::base::DirichletUpdateVector::applyDirichletConditions(), sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doDehierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::base::HashGridIterator::isInnerPoint(), sgpp::base::DirichletUpdateVector::multiplyBoundary(), sgpp::base::DirichletUpdateVector::multiplyBoundaryVector(), sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation(), sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs(), sgpp::base::DirichletUpdateVector::setBoundariesToZero(), and sgpp::base::DirichletUpdateVector::setInnerPointsToZero().
isLeaf()
bool sgpp::base::HashGridPoint::isLeaf ()
Checks if this grid point has not a single child in any dimension.
Returns
Returns true if this grid point has no children, otherwise false
Referenced by sgpp::base::HashGenerator::boundaries_rec(), sgpp::base::OperationHierarchisationPrewavelet::expandGrid(), sgpp::base::HashGridIterator::hint(), push(), set(), setLeaf(), and sgpp::base::HashGenerator::trunc_rec().
operator=()
HashGridPoint & sgpp::base::HashGridPoint::operator= (const HashGridPoint & rhs)
operator to assign the current grid point with the values of another one
Parameters
rhs a reference to a HashGridPoint that contains the values that should be copied
Returns
returns a reference HashGridPoint
References rehash().
Referenced by assign().
push() [1/2]
void sgpp::base::HashGridPoint::push (size_t d, level_type l, index_type i) inline
Sets level l and index i in dimension d and doesn't rehash the HashGridPoint object.
Parameters
d the dimension in which the ansatzfunction is set
l the level of the ansatzfunction
i the index of the ansatzfunction
Referenced by sgpp::base::HashGenerator::boundaries_rec(), sgpp::base::HashGenerator::boundaries_truncated_rec(), sgpp::base::HashGenerator::boundaries_Truncated_rec_1d(), sgpp::base::HashGenerator::cliques_iter(), sgpp::base::HashGenerator::createAnisotropicFullGrid(), sgpp::base::HashGenerator::createFullGridIterative(), sgpp::base::HashGenerator::createFullGridTruncatedIterative(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::Grid::insertPoint(), sgpp::base::HashGridIterator::push(), sgpp::base::HashGenerator::regular_boundary_truncated_iter(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGenerator::regular_iter(), sgpp::base::HashGenerator::regular_periodic_boundary_iter(), sgpp::base::HashGridIterator::resetToLevelZero(), sgpp::base::HashGenerator::square_rec(), and sgpp::base::HashGenerator::trunc_rec().
push() [2/2]
void sgpp::base::HashGridPoint::push (size_t d, level_type l, index_type i, bool isLeaf) inline
Sets level l and index i in dimension d and the Leaf property and doesn't rehash the HashGridPoint object.
Parameters
d the dimension in which the ansatzfunction is set
l the level of the ansatzfunction
i the index of the ansatzfunction
isLeaf specifies if this gridpoint has any childrens in any dimension
References isLeaf().
rehash()
void sgpp::base::HashGridPoint::rehash ()
rehashs the current gridpoint and sets hInv
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::base::HashGridIterator::HashGridIterator(), sgpp::base::HashGridIterator::HashGridIterator(), HashGridPoint(), HashGridPoint(), operator=(), sgpp::base::HashGenerator::regular_inter_iter(), sgpp::base::HashGridIterator::resetToLevelZero(), set(), and set().
serialize()
void sgpp::base::HashGridPoint::serialize (std::ostream & ostream, int version)
Serialize this Gridpoint e.g.
for a storage or checkpointing
Parameters
ostream outstream object to which the gridpoint's information is written
version the serialization version of the file
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
set() [1/2]
void sgpp::base::HashGridPoint::set (size_t d, level_type l, index_type i) inline
Sets level l and index i in dimension d and rehashs the HashGridPoint object.
Parameters
d the dimension in which the ansatzfunction is set
l the level of the ansatzfunction
i the index of the ansatzfunction
References rehash().
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorSOO::generate(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getChild(), getLeftBoundaryPoint(), getLeftChild(), getLeftLevelZero(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getParent(), getParent(), getRightBoundaryPoint(), getRightChild(), getRightLevelZero(), getRoot(), sgpp::datadriven::ZeroCrossingRefinementFunctor::goDown(), sgpp::base::HashGridIterator::hintLeft(), sgpp::base::HashGridIterator::hintRight(), sgpp::base::HashGridStorage::insert(), sgpp::base::Grid::insertPoint(), sgpp::base::HashGridIterator::leftChild(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::optimization::file_io::readGrid(), sgpp::base::SubspaceRefinement::refineGridpointsCollection(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::set(), setAsHierarchicalGridPoint(), sgpp::datadriven::ClassificationRefinementFunctor::stepDown(), sgpp::base::HashGridIterator::stepLeft(), sgpp::base::HashGridIterator::stepRight(), and sgpp::base::HashGridIterator::up().
set() [2/2]
void sgpp::base::HashGridPoint::set (size_t d, level_type l, index_type i, bool isLeaf) inline
Sets level l and index i in dimension d and the Leaf property and rehashs the HashGridPoint object.
Parameters
d the dimension in which the ansatzfunction is set
l the level of the ansatzfunction
i the index of the ansatzfunction
isLeaf specifies if this gridpoint has any childrens in any dimension
References isLeaf(), and rehash().
setAsHierarchicalGridPoint()
void sgpp::base::HashGridPoint::setAsHierarchicalGridPoint (size_t dim, level_type level, index_type index) inline
Sets the index to the grid point at the left boundary of the support For details see ´http://graphics.stanford.edu/~seander/bithacks.html´ and ´http://supertech.csail.mit.edu/papers/debruijn.pdf´ WARNING: this just works for grids with non-overlapping basis functions at the same level and for uint32_t as index_type.
Parameters
dim the dimension in which the modification is taken place
level level in direction dim
index index in direction dim
References level, and set().
Referenced by sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), and sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx().
setLeaf()
void sgpp::base::HashGridPoint::setLeaf (bool isLeaf)
Set the leaf property; a grid point is called a leaf, if it has not a single child.
Parameters
isLeaf specifies if the current index is a leaf (i.e. has no child nodes) or not
References isLeaf().
Referenced by sgpp::base::HashGenerator::boundaries_rec(), sgpp::base::HashGenerator::boundaries_truncated_rec(), sgpp::base::HashRefinementBoundaries::createGridpointLevelZeroConsistency(), sgpp::base::AbstractRefinement::createGridpointSubroutine(), sgpp::base::HashGenerator::square_rec(), and sgpp::base::HashGenerator::trunc_rec().
toString() [1/2]
std::string sgpp::base::HashGridPoint::toString () const
Generates a string with level and index of the gridpoint.
The format is [l1, i1, l2, i2, ..., ld, id]. Needed for Java compatibility.
Returns
string into which the gridpoint is written
References toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::base::OperationHierarchisationPrewavelet::expandGrid(), sgpp::base::GridDataBase::get(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), sgpp::base::HashGridIterator::toString(), and toString().
toString() [2/2]
void sgpp::base::HashGridPoint::toString (std::ostream & stream) const
Generates a string with level and index of the gridpoint.
The format is [l1, i1, l2, i2, ..., ld, id].
Parameters
stream reference to a output stream
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
Friends And Related Symbol Documentation
HashGridPointEqualityFunctor
friend struct HashGridPointEqualityFunctor friend
HashGridPointHashFunctor
friend struct HashGridPointHashFunctor friend
HashGridPointPointerEqualityFunctor
friend struct HashGridPointPointerEqualityFunctor friend
HashGridPointPointerHashFunctor
friend struct HashGridPointPointerHashFunctor friend
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/storage/hashmap/HashGridPoint.hpp
base/src/sgpp/base/grid/storage/hashmap/HashGridPoint.cpp