SG++-Doxygen-Documentation: sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive Class Reference
sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive Class Reference
Operation for evaluating Langrange spline linear combinations on Boundary grids.
#include <OperationEvalWeaklyFundamentalSplineBoundaryNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalWeaklyFundamentalSplineBoundaryNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalWeaklyFundamentalSplineBoundaryNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SWeaklyFundamentalSplineBase base
1D B-spline basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Detailed Description
Operation for evaluating Langrange spline linear combinations on Boundary grids.
Constructor & Destructor Documentation
OperationEvalWeaklyFundamentalSplineBoundaryNaive()
sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::OperationEvalWeaklyFundamentalSplineBoundaryNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalWeaklyFundamentalSplineBoundaryNaive()
sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::~OperationEvalWeaklyFundamentalSplineBoundaryNaive () inline override
Destructor.
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::WeaklyFundamentalSplineBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SWeaklyFundamentalSplineBase sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::base protected
1D B-spline basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalWeaklyFundamentalSplineBoundaryNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalWeaklyFundamentalSplineBoundaryNaive.cpp