SG++-Doxygen-Documentation: sgpp::datadriven::RefinementHandler Class Reference
sgpp::datadriven::RefinementHandler Class Reference
#include <RefinementHandler.hpp>
Public Member Functions
bool checkReadyForRefinement () const
Check whether all grids are consistent and the scheduler is currently allowing refinement.
size_t checkRefinementNecessary (const std::string &refMonitor, size_t refPeriod, size_t batchSize, double currentValidError, double currentTrainError, size_t numberOfCompletedRefinements, RefinementMonitor &monitor, sgpp::base::AdaptivityConfiguration adaptivityConfig)
Check whether refinement is currently necessary according to the guidelines set by the user.
void doRefinementForClass (const std::string &refType, RefinementResult *refinementResult, const std::vector< std::pair< std::unique_ptr< DBMatOnlineDE >, size_t > > &onlineObjects, Grid &grid, DataVector &alpha, bool preCompute, MultiGridRefinementFunctor *refinementFunctor, size_t classIndex, sgpp::base::AdaptivityConfiguration &adaptivityConfig)
Handles refinement for a specific class.
RefinementResult & getRefinementResult (size_t classIndex)
Fetches the currently stored refinement results for a specific class.
RefinementHandler (LearnerSGDEOnOffParallel *learnerInstance, size_t numClasses)
Creates the refinement handler for a specific learner instance.
void updateClassVariablesAfterRefinement (size_t classIndex, RefinementResult *refinementResult, DBMatOnlineDE *densEst, Grid &grid)
After refinement completes locally or refinement results have been received over MPI, this method uses the results to adjust the grid and alpha vector.
Protected Member Functions
size_t handleDataAndZeroBasedRefinement (bool preCompute, MultiGridRefinementFunctor *func, size_t idx, base::Grid &grid, base::GridGenerator &gridGen) const
Logic that handles data-based and zero-crossing refinement functors.
size_t handleSurplusBasedRefinement (DBMatOnlineDE *densEst, Grid &grid, DataVector &alpha, base::GridGenerator &gridGen, sgpp::base::AdaptivityConfiguration adaptivityConfig) const
Logic that handles surplus based refinement functors.
Protected Attributes
LearnerSGDEOnOffParallel * learnerInstance
std::vector< RefinementResult > vectorRefinementResults
Constructor & Destructor Documentation
RefinementHandler()
sgpp::datadriven::RefinementHandler::RefinementHandler (LearnerSGDEOnOffParallel * learnerInstance, size_t numClasses)
Creates the refinement handler for a specific learner instance.
Parameters
learnerInstance The instance of the learner to handle refinement for
numClasses The number of classes for the current problem
References learnerInstance, and vectorRefinementResults.
Member Function Documentation
checkReadyForRefinement()
bool sgpp::datadriven::RefinementHandler::checkReadyForRefinement () const
Check whether all grids are consistent and the scheduler is currently allowing refinement.
Returns
Whether refinement is currently possible
References sgpp::datadriven::LearnerSGDEOnOffParallel::checkAllGridsConsistent(), sgpp::datadriven::LearnerSGDEOnOffParallel::getScheduler(), sgpp::datadriven::MPITaskScheduler::isReadyForRefinement(), and learnerInstance.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::trainParallel().
checkRefinementNecessary()
size_t sgpp::datadriven::RefinementHandler::checkRefinementNecessary (const std::string & refMonitor, size_t refPeriod, size_t batchSize, double currentValidError, double currentTrainError, size_t numberOfCompletedRefinements, RefinementMonitor & monitor, sgpp::base::AdaptivityConfiguration adaptivityConfig)
Check whether refinement is currently necessary according to the guidelines set by the user.
Parameters
refMonitor String constant specifying the monitor to use for refinement
refPeriod The minimum period in which refinement cycles are allowed
batchSize The number of instances that were added by the current batch
currentValidError The current validation error
currentTrainError The current training error
numberOfCompletedRefinements The number of refinement cycles already completed
monitor The convergence monitor, if any
adaptivityConfig the configuration for the adaptivity of the grids
Returns
How many refinement cycles should be started
References adaptivityConfig, sgpp::datadriven::LearnerSGDEOnOffParallel::getError(), sgpp::datadriven::LearnerSGDEOnOffParallel::getOffline(), sgpp::datadriven::LearnerSGDEOnOffParallel::getTrainData(), sgpp::datadriven::LearnerSGDEOnOffParallel::getValidationData(), learnerInstance, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::RefinementMonitor::pushToBuffer(), and sgpp::datadriven::RefinementMonitor::refinementsNecessary().
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::trainParallel().
doRefinementForClass()
void sgpp::datadriven::RefinementHandler::doRefinementForClass (const std::string & refType, RefinementResult * refinementResult, const std::vector< std::pair< std::unique_ptr< DBMatOnlineDE >, size_t > > & onlineObjects, Grid & grid, DataVector & alpha, bool preCompute, MultiGridRefinementFunctor * refinementFunctor, size_t classIndex, sgpp::base::AdaptivityConfiguration & adaptivityConfig)
Handles refinement for a specific class.
Parameters
refType String constant specifying the type of refinement functor
refinementResult The RefinementResult used to store changes for the grid
onlineObjects The density estimation online objects
grid the grid of the online object of the current class
alpha the surplusses of the current class
preCompute Whether to precompute the functor's evaluation step
refinementFunctor The refinement functor to use
classIndex The index of the current class for which refinement is taking place
adaptivityConfig the configuration for the adaptivity of the grids
References adaptivityConfig, sgpp::datadriven::RefinementResult::addedGridPoints, alpha, D, sgpp::datadriven::RefinementResult::deletedGridPointsIndices, sgpp::base::HashGridPoint::get(), sgpp::datadriven::LearnerSGDEOnOffParallel::getDimensionality(), grid(), handleDataAndZeroBasedRefinement(), handleSurplusBasedRefinement(), learnerInstance, and updateClassVariablesAfterRefinement().
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::doRefinementForAll().
getRefinementResult()
RefinementResult & sgpp::datadriven::RefinementHandler::getRefinementResult (size_t classIndex)
Fetches the currently stored refinement results for a specific class.
Parameters
classIndex The class to search refinement results for
Returns
A reference to the stored refinement results
References vectorRefinementResults.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::computeNewSystemMatrixDecomposition(), sgpp::datadriven::LearnerSGDEOnOffParallel::doRefinementForAll(), sgpp::datadriven::LearnerSGDEOnOffParallel::mergeAlphaValues(), sgpp::datadriven::MPIMethods::receiveGridComponentsUpdate(), and sgpp::datadriven::LearnerSGDEOnOffParallel::train().
handleDataAndZeroBasedRefinement()
size_t sgpp::datadriven::RefinementHandler::handleDataAndZeroBasedRefinement (bool preCompute, MultiGridRefinementFunctor * func, size_t idx, base::Grid & grid, base::GridGenerator & gridGen) const protected
Logic that handles data-based and zero-crossing refinement functors.
Parameters
preCompute Whether to precompute evaluations in the functor
func Pointer to the refinement functor itself
idx Class index
grid The grid for the current class
gridGen The grid's generator for the current grid
Returns
The number of added grid points
References grid(), sgpp::datadriven::MultiGridRefinementFunctor::preComputeEvaluations(), sgpp::base::GridGenerator::refine(), and sgpp::datadriven::MultiGridRefinementFunctor::setGridIndex().
Referenced by doRefinementForClass().
handleSurplusBasedRefinement()
size_t sgpp::datadriven::RefinementHandler::handleSurplusBasedRefinement (DBMatOnlineDE * densEst, base::Grid & grid, DataVector & alpha, base::GridGenerator & gridGen, sgpp::base::AdaptivityConfiguration adaptivityConfig) const protected
Logic that handles surplus based refinement functors.
Parameters
densEst Online objects for use in density estimation for the current class
grid The current classes grid
alpha The current surpluss vector
gridGen The current grid's grid generator
adaptivityConfig the configuration for the adaptivity
Returns
The number of added grid points
References adaptivityConfig, alpha, sgpp::op_factory::createOperationEval(), sgpp::base::DataVector::get(), sgpp::datadriven::Dataset::getDimension(), sgpp::base::DataVector::getSize(), sgpp::datadriven::LearnerSGDEOnOffParallel::getTrainData(), grid(), learnerInstance, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, and sgpp::base::GridGenerator::refine().
Referenced by doRefinementForClass().
updateClassVariablesAfterRefinement()
void sgpp::datadriven::RefinementHandler::updateClassVariablesAfterRefinement (size_t classIndex, RefinementResult * refinementResult, DBMatOnlineDE * densEst, Grid & grid)
After refinement completes locally or refinement results have been received over MPI, this method uses the results to adjust the grid and alpha vector.
If this is run on the master, the grid changes will be exported over MPI. If the system matrix is refineable, a system matrix update will be assigned to workers over MPI.
Parameters
classIndex The index of the class being updated
refinementResult The grid changes from the refinement cycle
densEst A pointer to the online object specfic to this class
grid the grid of the current density function
References sgpp::datadriven::RefinementResult::addedGridPoints, sgpp::datadriven::MPIMethods::assignSystemMatrixUpdate(), sgpp::datadriven::MPITaskScheduler::assignTaskStaticTaskSize(), sgpp::datadriven::LearnerSGDEOnOffParallel::checkGridStateConsistent(), D, sgpp::datadriven::RefinementResult::deletedGridPointsIndices, sgpp::datadriven::LearnerSGDEOnOffParallel::getDimensionality(), sgpp::datadriven::LearnerSGDEOnOffParallel::getLocalGridVersion(), sgpp::datadriven::LearnerSGDEOnOffParallel::getOffline(), sgpp::datadriven::LearnerSGDEOnOffParallel::getScheduler(), grid(), sgpp::datadriven::MPIMethods::isMaster(), learnerInstance, level, sgpp::datadriven::RECOMPUTE_SYSTEM_MATRIX_DECOMPOSITION, sgpp::datadriven::MPIMethods::sendRefinementUpdates(), sgpp::datadriven::LearnerSGDEOnOffParallel::setLocalGridVersion(), and sgpp::datadriven::LearnerSGDEOnOffParallel::updateAlpha().
Referenced by doRefinementForClass(), and sgpp::datadriven::MPIMethods::receiveGridComponentsUpdate().
Member Data Documentation
learnerInstance
LearnerSGDEOnOffParallel* sgpp::datadriven::RefinementHandler::learnerInstance protected
Referenced by checkReadyForRefinement(), checkRefinementNecessary(), doRefinementForClass(), handleSurplusBasedRefinement(), RefinementHandler(), and updateClassVariablesAfterRefinement().
vectorRefinementResults
std::vector<RefinementResult> sgpp::datadriven::RefinementHandler::vectorRefinementResults protected
Referenced by getRefinementResult(), and RefinementHandler().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/learnersgdeonoffparallel/RefinementHandler.hpp
datadriven/src/sgpp/datadriven/application/learnersgdeonoffparallel/RefinementHandler.cpp