SG++-Doxygen-Documentation: sgpp::base::OCLStretchedBuffer Class Reference
sgpp::base::OCLStretchedBuffer Class Reference
#include <OCLStretchedBuffer.hpp>
Public Member Functions
void freeBuffer ()
cl_mem * getBuffer (size_t deviceNumber)
void * getMappedHostBuffer ()
void initializeBuffer (size_t sizeofType, size_t elements)
bool isInitialized ()
OCLStretchedBuffer (std::shared_ptr< OCLManager > manager)
void readFromBuffer (size_t *indexStart, size_t *indexEnd)
void writeToBuffer ()
~OCLStretchedBuffer ()
Constructor & Destructor Documentation
OCLStretchedBuffer()
sgpp::base::OCLStretchedBuffer::OCLStretchedBuffer (std::shared_ptr< OCLManager > manager) explicit
~OCLStretchedBuffer()
sgpp::base::OCLStretchedBuffer::~OCLStretchedBuffer ()
References freeBuffer().
Member Function Documentation
freeBuffer()
void sgpp::base::OCLStretchedBuffer::freeBuffer ()
Referenced by ~OCLStretchedBuffer().
getBuffer()
cl_mem * sgpp::base::OCLStretchedBuffer::getBuffer (size_t deviceNumber)
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::mult(), and sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::multTranspose().
getMappedHostBuffer()
void * sgpp::base::OCLStretchedBuffer::getMappedHostBuffer ()
initializeBuffer()
void sgpp::base::OCLStretchedBuffer::initializeBuffer (size_t sizeofType, size_t elements)
Referenced by doStuffOld().
isInitialized()
bool sgpp::base::OCLStretchedBuffer::isInitialized ()
readFromBuffer()
void sgpp::base::OCLStretchedBuffer::readFromBuffer (size_t * indexStart, size_t * indexEnd)
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::mult(), and sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::multTranspose().
writeToBuffer()
void sgpp::base::OCLStretchedBuffer::writeToBuffer ()
The documentation for this class was generated from the following files:
base/src/sgpp/base/opencl/OCLStretchedBuffer.hpp
base/src/sgpp/base/opencl/OCLStretchedBuffer.cpp