SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensityMargTo1D Class Reference
sgpp::datadriven::OperationDensityMargTo1D Class Reference
Marginalize Probability Density Function.
#include <OperationDensityMargTo1D.hpp>
Public Member Functions
virtual void margToDimX (base::DataVector *alpha, base::Grid *&grid_x, base::DataVector *&alpha_x, size_t dim_x)
Keep applying marginalizes to (Density) Functions, until it's reduced to 1 dimension (dim_x)
virtual void margToDimXs (base::DataVector *alpha, base::Grid *&grid_x, base::DataVector *&alpha_x, std::vector< size_t > &dim_x)
Keep applying marginalizes to (Density) Functions, until it's reduced to d dimensions (dim_x)
OperationDensityMargTo1D (base::Grid *grid)
virtual ~OperationDensityMargTo1D ()
Protected Member Functions
void computeMarginalizationIndices (std::vector< size_t > &dim_x, size_t numDims, std::vector< size_t > &margDims)
void marg_next_dim (base::Grid *g_in, base::DataVector *a_in, base::Grid *&g_out, base::DataVector *&a_out, std::vector< size_t > margDims, size_t ix)
Protected Attributes
base::Grid * grid
Detailed Description
Marginalize Probability Density Function.
Constructor & Destructor Documentation
OperationDensityMargTo1D()
sgpp::datadriven::OperationDensityMargTo1D::OperationDensityMargTo1D (base::Grid * grid) inline explicit
~OperationDensityMargTo1D()
virtual sgpp::datadriven::OperationDensityMargTo1D::~OperationDensityMargTo1D () inline virtual
Member Function Documentation
computeMarginalizationIndices()
void sgpp::datadriven::OperationDensityMargTo1D::computeMarginalizationIndices (std::vector< size_t > & dim_x, size_t numDims, std::vector< size_t > & margDims) protected
Referenced by margToDimXs().
marg_next_dim()
void sgpp::datadriven::OperationDensityMargTo1D::marg_next_dim (base::Grid * g_in, base::DataVector * a_in, base::Grid *& g_out, base::DataVector *& a_out, std::vector< size_t > margDims, size_t ix) protected
References sgpp::op_factory::createOperationDensityMarginalize(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), and marg_next_dim().
Referenced by marg_next_dim(), and margToDimXs().
margToDimX()
void sgpp::datadriven::OperationDensityMargTo1D::margToDimX (base::DataVector * alpha, base::Grid *& grid_x, base::DataVector *& alpha_x, size_t dim_x) virtual
Keep applying marginalizes to (Density) Functions, until it's reduced to 1 dimension (dim_x)
Parameters
alpha Coefficient vector for current grid
grid_x output 1D grid pointer
alpha_x Coefficient vector for new grid (grid_x). Will be initialized.
dim_x Target dimension, all other dimensions will be marginalized
References alpha, sgpp::base::Grid::getDimension(), grid, and margToDimXs().
Referenced by sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), and sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim().
margToDimXs()
void sgpp::datadriven::OperationDensityMargTo1D::margToDimXs (base::DataVector * alpha, base::Grid *& grid_x, base::DataVector *& alpha_x, std::vector< size_t > & dim_x) virtual
Keep applying marginalizes to (Density) Functions, until it's reduced to d dimensions (dim_x)
Parameters
alpha Coefficient vector for current grid
grid_x output 1D grid pointer
alpha_x Coefficient vector for new grid (grid_x). Will be initialized.
dim_x Target dimension, all other dimensions will be marginalized
References alpha, sgpp::base::Grid::clone(), computeMarginalizationIndices(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataVector::getSize(), grid, marg_next_dim(), and sgpp::base::DataVector::set().
Referenced by margToDimX().
Member Data Documentation
grid
base::Grid* sgpp::datadriven::OperationDensityMargTo1D::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), margToDimX(), margToDimXs(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMargTo1D.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityMargTo1D.cpp