SG++-Doxygen-Documentation: sgpp::datadriven::OperationLimitFunctionValueRange Class Reference
sgpp::datadriven::OperationLimitFunctionValueRange Class Reference
#include <OperationLimitFunctionValueRange.hpp>
Public Member Functions
void doLimitation (base::Grid &grid, base::DataVector &alpha, double ylower, double yupper, bool limitNodalValues=true)
void doLowerLimitation (base::Grid &grid, base::DataVector &alpha, double ylower, bool limitNodalValues=true)
void doUpperLimitation (base::Grid &grid, base::DataVector &alpha, double yupper, bool limitNodalValues=true)
std::vector< size_t > & getAddedGridPoints ()
std::vector< size_t > & getAddedGridPointsForRangeLimitation ()
size_t numAddedGridPoints ()
size_t numAddedGridPointsForRangeLimitation ()
OperationLimitFunctionValueRange (datadriven::MakePositiveCandidateSearchAlgorithm candiateSearch=MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm=MakePositiveInterpolationAlgorithm::SetToZero, sgpp::base::ScalarFunction *f=nullptr)
virtual ~OperationLimitFunctionValueRange ()
Constructor & Destructor Documentation
OperationLimitFunctionValueRange()
sgpp::datadriven::OperationLimitFunctionValueRange::OperationLimitFunctionValueRange (datadriven::MakePositiveCandidateSearchAlgorithm candiateSearch = MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm = MakePositiveInterpolationAlgorithm::SetToZero, sgpp::base::ScalarFunction * f = nullptr)
References sgpp::op_factory::createOperationMakePositive(), and f.
~OperationLimitFunctionValueRange()
sgpp::datadriven::OperationLimitFunctionValueRange::~OperationLimitFunctionValueRange () virtual
Member Function Documentation
doLimitation()
void sgpp::datadriven::OperationLimitFunctionValueRange::doLimitation (base::Grid & grid, base::DataVector & alpha, double ylower, double yupper, bool limitNodalValues = true)
References alpha, doLowerLimitation(), doUpperLimitation(), and grid().
doLowerLimitation()
void sgpp::datadriven::OperationLimitFunctionValueRange::doLowerLimitation (base::Grid & grid, base::DataVector & alpha, double ylower, bool limitNodalValues = true)
References alpha, and grid().
Referenced by doLimitation().
doUpperLimitation()
void sgpp::datadriven::OperationLimitFunctionValueRange::doUpperLimitation (base::Grid & grid, base::DataVector & alpha, double yupper, bool limitNodalValues = true)
References alpha, and grid().
Referenced by doLimitation().
getAddedGridPoints()
std::vector< size_t > & sgpp::datadriven::OperationLimitFunctionValueRange::getAddedGridPoints ()
Returns
vector containing the indices of the added grid points
getAddedGridPointsForRangeLimitation()
std::vector< size_t > & sgpp::datadriven::OperationLimitFunctionValueRange::getAddedGridPointsForRangeLimitation ()
Returns
vector containing the indices which have just been added for range limiting
numAddedGridPoints()
size_t sgpp::datadriven::OperationLimitFunctionValueRange::numAddedGridPoints ()
Returns
number of newly added grid points
numAddedGridPointsForRangeLimitation()
size_t sgpp::datadriven::OperationLimitFunctionValueRange::numAddedGridPointsForRangeLimitation ()
Returns
number of newly added grid points for guaranteeing the range
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationLimitFunctionValueRange.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationLimitFunctionValueRange.cpp