SG++-Doxygen-Documentation: sgpp::datadriven::OperationInverseRosenblattTransformationPoly Class Reference
sgpp::datadriven::OperationInverseRosenblattTransformationPoly Class Reference
keep applying marginalize to function until it's reduced to only 1 dimension
#include <OperationInverseRosenblattTransformationPoly.hpp>
Public Member Functions
void doTransformation (base::DataVector *alpha, base::DataMatrix *pointscdf, base::DataMatrix *points)
Transformation with mixed starting dimensions.
void doTransformation (base::DataVector *alpha, base::DataMatrix *pointscdf, base::DataMatrix *points, size_t dim_start)
Transformation with specified starting dimension.
OperationInverseRosenblattTransformationPoly (base::Grid *grid)
virtual ~OperationInverseRosenblattTransformationPoly ()
Public Member Functions inherited from sgpp::datadriven::OperationInverseRosenblattTransformation
OperationInverseRosenblattTransformation ()
virtual ~OperationInverseRosenblattTransformation ()
Protected Member Functions
double doTransformation1D (base::Grid *grid1d, base::DataVector *alpha1d, double coord1d)
void doTransformation_in_next_dim (base::Grid *g_in, base::DataVector *a_in, size_t op_dim, base::DataVector *cdfs1d, base::DataVector *coords1d, size_t &curr_dim)
void doTransformation_start_dimX (base::Grid *g_in, base::DataVector *a_in, size_t dim_start, base::DataVector *cdfs1d, base::DataVector *coords1d)
Protected Attributes
base::Grid * grid
Detailed Description
keep applying marginalize to function until it's reduced to only 1 dimension
Constructor & Destructor Documentation
OperationInverseRosenblattTransformationPoly()
sgpp::datadriven::OperationInverseRosenblattTransformationPoly::OperationInverseRosenblattTransformationPoly (base::Grid * grid) inline explicit
~OperationInverseRosenblattTransformationPoly()
virtual sgpp::datadriven::OperationInverseRosenblattTransformationPoly::~OperationInverseRosenblattTransformationPoly () inline virtual
Member Function Documentation
doTransformation() [1/2]
void sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation (base::DataVector * alpha, base::DataMatrix * pointscdf, base::DataMatrix * points) virtual
Transformation with mixed starting dimensions.
Parameters
alpha Coefficient vector for current grid
pointscdf Input Matrix
points Output Matrix
Implements sgpp::datadriven::OperationInverseRosenblattTransformation.
References alpha, sgpp::op_factory::createOperationDensityMargTo1D(), doTransformation1D(), doTransformation_start_dimX(), sgpp::base::DataMatrix::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid, sgpp::base::DataMatrix::set(), and sgpp::base::DataMatrix::setRow().
doTransformation() [2/2]
void sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation (base::DataVector * alpha, base::DataMatrix * pointscdf, base::DataMatrix * points, size_t dim_start) virtual
Transformation with specified starting dimension.
Parameters
alpha Coefficient vector for current grid
pointscdf Input Matrix
points Output Matrix
dim_start Starting dimension
Implements sgpp::datadriven::OperationInverseRosenblattTransformation.
References alpha, sgpp::op_factory::createOperationDensityMargTo1D(), doTransformation1D(), doTransformation_start_dimX(), sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), grid, sgpp::base::DataMatrix::set(), and sgpp::base::DataMatrix::setRow().
doTransformation1D()
double sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation1D (base::Grid * grid1d, base::DataVector * alpha1d, double coord1d) protected
References sgpp::op_factory::createOperationInverseRosenblattTransformation1D().
Referenced by doTransformation(), doTransformation(), and doTransformation_in_next_dim().
doTransformation_in_next_dim()
void sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim (base::Grid * g_in, base::DataVector * a_in, size_t op_dim, base::DataVector * cdfs1d, base::DataVector * coords1d, size_t & curr_dim) protected
References sgpp::op_factory::createOperationDensityConditional(), sgpp::op_factory::createOperationDensityMargTo1D(), sgpp::datadriven::OperationDensityConditional::doConditional(), doTransformation1D(), doTransformation_in_next_dim(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataVector::getSize(), sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), and sgpp::base::DataVector::set().
Referenced by doTransformation_in_next_dim(), and doTransformation_start_dimX().
doTransformation_start_dimX()
void sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_start_dimX (base::Grid * g_in, base::DataVector * a_in, size_t dim_start, base::DataVector * cdfs1d, base::DataVector * coords1d) protected
References doTransformation_in_next_dim(), and sgpp::base::DataVector::getSize().
Referenced by doTransformation(), and doTransformation().
Member Data Documentation
grid
base::Grid* sgpp::datadriven::OperationInverseRosenblattTransformationPoly::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), doTransformation(), doTransformation(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationInverseRosenblattTransformationPoly.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationInverseRosenblattTransformationPoly.cpp