SG++-Doxygen-Documentation: sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary Class Reference
sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary Class Reference
Implementation for PolyClenshawCurtisBoundary functions of Laplace Operation, linear grids without boundaries.
#include <OperationLaplacePolyClenshawCurtisBoundary.hpp>
Public Member Functions
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationLaplacePolyClenshawCurtisBoundary (sgpp::base::Grid *grid)
Constructor that creates an own matrix i.e.
virtual ~OperationLaplacePolyClenshawCurtisBoundary ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Implementation for PolyClenshawCurtisBoundary functions of Laplace Operation, linear grids without boundaries.
Constructor & Destructor Documentation
OperationLaplacePolyClenshawCurtisBoundary()
sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::OperationLaplacePolyClenshawCurtisBoundary (sgpp::base::Grid * grid) explicit
Constructor that creates an own matrix i.e.
matrix is destroyed by the destructor of OperationLaplacePolyClenshawCurtisBoundary
Parameters
grid the sparse grid
~OperationLaplacePolyClenshawCurtisBoundary()
sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::~OperationLaplacePolyClenshawCurtisBoundary () virtual
Destructor.
Member Function Documentation
mult()
void sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
int nabla phi_i(x) * nabla phi_j(x) dx = sum_k int (dx_k phi_i(x)) * (dx_k phi_j(x)) dx = sum_k int (phi'_{i_k}(x_k) * phi'_{i_k}(x_k) * prod_{l!=k} phi_{i_l}(x_l) * phi_{j_l}(x_l)) dx = sum_k int (phi'_{i_k}(x_k) * phi'_{j_k}(x_k)) dx_k * prod_{l!=k} int (phi_{i_l}(x_l) * phi_{j_l}(x_l)) dx_l
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalDx(), sgpp::base::Grid::getBasis(), sgpp::base::Grid::getDimension(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::DataVector::getSize(), sgpp::base::Grid::getSize(), sgpp::base::HashGridStorage::getSize(), and sgpp::base::Grid::getStorage().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplacePolyClenshawCurtisBoundary.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplacePolyClenshawCurtisBoundary.cpp