SG++-Doxygen-Documentation: sgpp::pde::dPhidPhiUpModLinear Class Reference
sgpp::pde::dPhidPhiUpModLinear Class Reference
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \frac{\partial \phi(x)}{\partial x} \frac{\partial \phi(x)}{\partial x} dx\) on mod-linear grids.
#include <dPhidPhiUpModLinear.hpp>
Public Member Functions
dPhidPhiUpModLinear (sgpp::base::GridStorage *storage)
Constructor.
void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of upGradient in the direction of dimension dim
~dPhidPhiUpModLinear ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double &f)
recursive function for the calculation of upGradient
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to sgpp::base::GridStorage object.
Detailed Description
Implementation of sweep operator (): 1D Up for Bilinearform \(\int_{x} \frac{\partial \phi(x)}{\partial x} \frac{\partial \phi(x)}{\partial x} dx\) on mod-linear grids.
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::dPhidPhiUpModLinear::grid_iterator protected
Constructor & Destructor Documentation
dPhidPhiUpModLinear()
sgpp::pde::dPhidPhiUpModLinear::dPhidPhiUpModLinear (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~dPhidPhiUpModLinear()
sgpp::pde::dPhidPhiUpModLinear::~dPhidPhiUpModLinear ()
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::dPhidPhiUpModLinear::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim)
This operations performs the calculation of upGradient in the direction of dimension dim
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the down operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
References f, and rec().
rec()
void sgpp::pde::dPhidPhiUpModLinear::rec (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim, double & f) protected
recursive function for the calculation of upGradient
Parameters
source sgpp::base::DataVector that contains the coefficients of the ansatzfunction
result sgpp::base::DataVector in which the result of the operation is stored
index reference to a griditerator object that is used navigate through the grid
dim the dimension in which the operation is executed
f function value in the middle
References f, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), rec(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by operator()(), and rec().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::pde::dPhidPhiUpModLinear::storage protected
Pointer to sgpp::base::GridStorage object.
Referenced by rec().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/modlinear/algorithm_sweep/dPhidPhiUpModLinear.hpp
pde/src/sgpp/pde/basis/modlinear/algorithm_sweep/dPhidPhiUpModLinear.cpp