SG++-Doxygen-Documentation: sgpp::datadriven::OperationDotProductModLinear Class Reference
sgpp::datadriven::OperationDotProductModLinear Class Reference
#include <OperationDotProductModLinear.hpp>
Public Member Functions
virtual double eval (sgpp::base::DataVector &x1, sgpp::base::DataVector &x2)
OperationDotProductModLinear (sgpp::base::GridStorage *storage)
Constructor of OperationTestLinear.
virtual ~OperationDotProductModLinear ()
Destructor.
Protected Attributes
sgpp::base::GridStorage * storage
Pointer to the grid's GridStorage object.
Constructor & Destructor Documentation
OperationDotProductModLinear()
sgpp::datadriven::OperationDotProductModLinear::OperationDotProductModLinear (sgpp::base::GridStorage * storage) inline explicit
Constructor of OperationTestLinear.
Parameters
storage Pointer to the grid's gridstorage obejct
~OperationDotProductModLinear()
virtual sgpp::datadriven::OperationDotProductModLinear::~OperationDotProductModLinear () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::datadriven::OperationDotProductModLinear::eval (sgpp::base::DataVector & x1, sgpp::base::DataVector & x2) virtual
References sgpp::base::LinearModifiedBasis< LT, IT >::eval(), sgpp::base::HashGridPoint::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSize(), and storage.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
storage
sgpp::base::GridStorage* sgpp::datadriven::OperationDotProductModLinear::storage protected
Pointer to the grid's GridStorage object.
Referenced by eval().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDotProductModLinear.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDotProductModLinear.cpp