SG++-Doxygen-Documentation: sgpp::base::DistributionTruncNormal Class Reference
sgpp::base::DistributionTruncNormal Class Reference
Truncated normal distribution.
#include <DistributionTruncNormal.hpp>
Public Member Functions
DistributionTruncNormal (double mean, double stddev, double lower, double upper, long int seed=777)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionTruncNormal ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Detailed Description
Truncated normal distribution.
Only accepts samples within [lower,upper] Results should be normalized by dividing them by mean(f(x)==1) w.r.t. the same truncated normal distribution
Constructor & Destructor Documentation
DistributionTruncNormal()
sgpp::base::DistributionTruncNormal::DistributionTruncNormal (double mean, double stddev, double lower, double upper, long int seed = 777) inline
Constructor.
~DistributionTruncNormal()
virtual sgpp::base::DistributionTruncNormal::~DistributionTruncNormal () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionTruncNormal::eval (double x) inline virtual
Implements sgpp::base::Distribution.
References M_PI.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionTruncNormal::getBounds () inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionTruncNormal::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionTruncNormal::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::TruncNormal.
sample()
double sgpp::base::DistributionTruncNormal::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionTruncNormal.hpp