SG++-Doxygen-Documentation: sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type > Class Template Reference
sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type > Class Template Reference
#include <StreamingBSplineOCLKernelImpl.hpp>
Public Member Functions
double mult (real_type *level, real_type *index, size_t gridSize, real_type *dataset, size_t datasetSize, real_type *alpha, real_type *result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data)
double multTranspose (real_type *level, real_type *index, size_t gridSize, real_type *dataset, size_t datasetSize, real_type *source, real_type *result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data)
void resetKernel ()
StreamingBSplineOCLKernelImpl (size_t dims, size_t degree, std::shared_ptr< base::OCLManager > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters)
~StreamingBSplineOCLKernelImpl ()
Constructor & Destructor Documentation
StreamingBSplineOCLKernelImpl()
template<typename real_type > sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::StreamingBSplineOCLKernelImpl (size_t dims, size_t degree, std::shared_ptr< base::OCLManager > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters) inline
~StreamingBSplineOCLKernelImpl()
template<typename real_type > sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::~StreamingBSplineOCLKernelImpl () inline
References sgpp::base::OCLClonedBuffer::freeBuffer().
Member Function Documentation
mult()
template<typename real_type > double sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::mult (real_type * level, real_type * index, size_t gridSize, real_type * dataset, size_t datasetSize, real_type * alpha, real_type * result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data) inline
References alpha, dataset, sgpp::base::OCLClonedBuffer::getBuffer(), sgpp::base::OCLStretchedBuffer::getBuffer(), sgpp::base::LinearLoadBalancer::getPartitionSegments(), level, sgpp::base::OCLStretchedBuffer::readFromBuffer(), and sgpp::base::LinearLoadBalancer::update().
multTranspose()
template<typename real_type > double sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::multTranspose (real_type * level, real_type * index, size_t gridSize, real_type * dataset, size_t datasetSize, real_type * source, real_type * result, const size_t start_index_grid, const size_t end_index_grid, const size_t start_index_data, const size_t end_index_data) inline
References dataset, sgpp::base::OCLClonedBuffer::getBuffer(), sgpp::base::OCLStretchedBuffer::getBuffer(), sgpp::base::LinearLoadBalancer::getPartitionSegments(), level, sgpp::base::OCLStretchedBuffer::readFromBuffer(), and sgpp::base::LinearLoadBalancer::update().
resetKernel()
template<typename real_type > void sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::resetKernel () inline
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingBSplineOCL/StreamingBSplineOCLKernelImpl.hpp