SG++-Doxygen-Documentation: sgpp::datadriven::DBMatDMSOrthoAdapt Class Reference
sgpp::datadriven::DBMatDMSOrthoAdapt Class Reference
This class solves an (lhs + lambda*I) * alpha = b system of linear equations after the offline and online phases are done.
#include <DBMatDMSOrthoAdapt.hpp>
Public Member Functions
DBMatDMSOrthoAdapt ()=default
Constructor.
void solve (sgpp::base::DataMatrix &T_inv, sgpp::base::DataMatrix &Q, sgpp::base::DataMatrix &B, sgpp::base::DataVector &b, sgpp::base::DataVector &alpha)
Solves the system after the corresponding offline and online objects are done with decomposing and adaptivity, resp.
void solveParallel (DataMatrixDistributed &T_inv, DataMatrixDistributed &Q, DataMatrixDistributed &B, DataVectorDistributed &b, DataVectorDistributed &alpha)
Parallel (distributed) version of solve.
Public Member Functions inherited from sgpp::datadriven::DBMatDecompMatrixSolver
DBMatDecompMatrixSolver ()
Public Member Functions inherited from sgpp::solver::SGSolver
double getEpsilon ()
gets the the epsilon, that is used in the SGSolver
size_t getNumberIterations ()
function that returns the number of needed solve steps
double getResiduum ()
function the returns the residuum (current or final), error of the solver
void setEpsilon (double eps)
resets the epsilon, that is used in the SGSolver
void setMaxIterations (size_t nIterations)
resets the number of maximum iterations
SGSolver (size_t nMaximumIterations, double epsilon)
Std-Constructor.
virtual ~SGSolver ()
Std-Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::solver::SGSolver
double myEpsilon
epsilon needed in the, e.g. final error in the iterative solver, or a timestep
size_t nIterations
Number of Iterations needed for the solve.
size_t nMaxIterations
Number of maximum iterations for cg.
double residuum
residuum
Detailed Description
This class solves an (lhs + lambda*I) * alpha = b system of linear equations after the offline and online phases are done.
Constructor & Destructor Documentation
DBMatDMSOrthoAdapt()
sgpp::datadriven::DBMatDMSOrthoAdapt::DBMatDMSOrthoAdapt () default
Constructor.
Member Function Documentation
solve()
void sgpp::datadriven::DBMatDMSOrthoAdapt::solve (sgpp::base::DataMatrix & T_inv, sgpp::base::DataMatrix & Q, sgpp::base::DataMatrix & B, sgpp::base::DataVector & b, sgpp::base::DataVector & alpha)
Solves the system after the corresponding offline and online objects are done with decomposing and adaptivity, resp.
The computation done: alpha = Q*T_inv*Q^t*b + B*b
Parameters
T_inv Inverse of a tridiagonal matrix
Q Orthogonal matrix, part of hessenberg_decomp of the lhs matrix
B Storage of the online objects refined/coarsened points
b The right side of the system
alpha The solution vector of the system, computed values go there
References alpha, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), sgpp::base::DataVector::getPointer(), and sgpp::base::DataVector::getSize().
solveParallel()
void sgpp::datadriven::DBMatDMSOrthoAdapt::solveParallel (DataMatrixDistributed & T_inv, DataMatrixDistributed & Q, DataMatrixDistributed & B, DataVectorDistributed & b, DataVectorDistributed & alpha)
Parallel (distributed) version of solve.
Parameters
T_inv Inverse of a tridiagonal matrix
Q Orthogonal matrix, part of hessenberg_decomp of the lhs matrix
B Storage of the online objects refined/coarsened points
b The right side of the system
alpha The solution vector of the system, computed values go there
References alpha, sgpp::datadriven::DataMatrixDistributed::getGlobalCols(), sgpp::datadriven::DataMatrixDistributed::getGlobalRows(), and sgpp::datadriven::DataMatrixDistributed::mult().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatDMSOrthoAdapt.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatDMSOrthoAdapt.cpp