SG++-Doxygen-Documentation: sgpp::base::GridDataBase Class Reference
sgpp::base::GridDataBase Class Reference
Class that allows to keep a storage of arbitrary grid points.
#include <GridDataBase.hpp>
Public Types
typedef grid_map::const_iterator grid_map_const_iterator
typedef grid_map::iterator grid_map_iterator
Public Member Functions
grid_map_iterator begin ()
Return iterator to beginning.
void clear ()
Clears database, removing all entries.
size_t dim () const
Returns the dimensionality of the grid points.
grid_map_iterator end ()
Return iterator to end.
double get (GridPoint *gi)
Get value for grid point from database.
GridDataBase (const std::string &filename)
Constructor, reading from existing database.
GridDataBase (Grid *grid, DataVector &values)
Constructor, copying from existing grid and values.
GridDataBase (size_t dim)
Standard Constructor, creating an empty database with dimensionality dim.
bool hasKey (GridPoint *gi)
Test, whether database already contains a grid point.
void load (const std::string filename)
Loads database in ASCII or binary format.
void remove (GridPoint *gi)
Remove grid point from database.
void save (std::string filename, char ftype=GridDataBase::ascii)
Save database to file.
void set (GridPoint *gi, double value)
Store (grid point - value) pair in database.
void setValuesFor (Grid *grid, DataVector &values)
Set values for given grid from stored ones in database.
size_t size () const
Returns the number of grid points that are currently stored in the database.
std::string toString ()
Returns std::string representation of database.
~GridDataBase ()
Destructor.
Static Public Attributes
static const char ascii = 'a'
static const char binary = 'b'
Detailed Description
Class that allows to keep a storage of arbitrary grid points.
It has the functionality of a dictionary that is used for storing and retrieving grid points. Internally, a hash_map is used.
Note: GridDataBase currently supports only to store pairs of (grid point -> double).
Member Typedef Documentation
grid_map_const_iterator
typedef grid_map::const_iterator sgpp::base::GridDataBase::grid_map_const_iterator
grid_map_iterator
typedef grid_map::iterator sgpp::base::GridDataBase::grid_map_iterator
Constructor & Destructor Documentation
GridDataBase() [1/3]
sgpp::base::GridDataBase::GridDataBase (size_t dim) explicit
Standard Constructor, creating an empty database with dimensionality dim.
Parameters
dim the dimensionality of the grid points
GridDataBase() [2/3]
sgpp::base::GridDataBase::GridDataBase (Grid * grid, DataVector & values)
Constructor, copying from existing grid and values.
Parameters
grid the grid to copy from
values the initial values
References sgpp::base::HashGridStorage::getPoint(), sgpp::base::HashGridStorage::getSequenceNumber(), sgpp::base::HashGridStorage::getSize(), grid(), and set().
GridDataBase() [3/3]
sgpp::base::GridDataBase::GridDataBase (const std::string & filename) explicit
Constructor, reading from existing database.
Parameters
filename filename of database file
References dim().
~GridDataBase()
sgpp::base::GridDataBase::~GridDataBase ()
Destructor.
References clear().
Member Function Documentation
begin()
GridDataBase::grid_map_iterator sgpp::base::GridDataBase::begin ()
Return iterator to beginning.
Entries are of type pair<GridPoint, double>.
Returns
iterator to beginning.
clear()
void sgpp::base::GridDataBase::clear ()
Clears database, removing all entries.
Dimensionality is maintained.
Referenced by ~GridDataBase().
dim()
size_t sgpp::base::GridDataBase::dim () const inline
Returns the dimensionality of the grid points.
Returns
the dimensionality of the grid points
Referenced by python.data.DataContainer.DataContainer::__init__(), python.uq.dists.EstimatedDist.EstimatedDist::_convertEvalPoint(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.dists.KDEDist.KDEDist::cov(), python.uq.dists.SGDEdist.SGDEdist::cov(), python.data.DataContainer.DataContainer::getDataSubsetByIndexList(), python.data.DataContainer.DataContainer::getDim(), python.uq.dists.EstimatedDist.EstimatedDist::getDim(), python.uq.dists.LibAGFDist.LibAGFDist::getDim(), python.uq.dists.NatafDist.NatafDist::getDim(), GridDataBase(), load(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.uq.dists.EstimatedDist.EstimatedDist::rvs(), python.uq.dists.NatafDist.NatafDist::rvs(), python.uq.dists.KDEDist.KDEDist::rvs(), python.uq.dists.SGDEdist.SGDEdist::rvs(), python.uq.operations.natafTransformation.NatafTransformation::trans_X_to_Z(), and python.uq.operations.natafTransformation.NatafTransformation::trans_Z_to_X().
end()
GridDataBase::grid_map_iterator sgpp::base::GridDataBase::end ()
Return iterator to end.
Returns
iterator to end.
get()
double sgpp::base::GridDataBase::get (GridPoint * gi)
Get value for grid point from database.
Return nullptr if not existant.
Parameters
gi a grid point
Returns
value
References sgpp::base::HashGridPoint::toString().
Referenced by setValuesFor().
hasKey()
bool sgpp::base::GridDataBase::hasKey (GridPoint * gi)
Test, whether database already contains a grid point.
Parameters
gi a grid point
Returns
false, if grid point not in database
load()
void sgpp::base::GridDataBase::load (const std::string filename)
Loads database in ASCII or binary format.
Adds (grid point - value) mappings to current database. Overwrites existing entries. To load a new database, use GridDataBase::GridDataBase(std::string filename).
Parameters
filename name of file
References dim().
remove()
void sgpp::base::GridDataBase::remove (GridPoint * gi)
Remove grid point from database.
Do nothing, if not in database.
Parameters
gi grid point
Referenced by python.uq.uq_setting.UQSetting.UQSetting::cleanUp().
save()
void sgpp::base::GridDataBase::save (std::string filename, char ftype = GridDataBase::ascii)
Save database to file.
Overwrites existing files without warning! Writes either ASCII (default) or binary format.
Parameters
filename name of file
ftype filetype (either ASCII, GridDataBase::asc (default), or binary, GridDataBase::bin)
References ascii.
set()
void sgpp::base::GridDataBase::set (GridPoint * gi, double value)
Store (grid point - value) pair in database.
Parameters
gi a grid point
value the value to store
Referenced by GridDataBase().
setValuesFor()
void sgpp::base::GridDataBase::setValuesFor (Grid * grid, DataVector & values)
Set values for given grid from stored ones in database.
Parameters
grid a grid
values the corresponding coefficient vector
References sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), get(), and grid().
size()
size_t sgpp::base::GridDataBase::size () const inline
Returns the number of grid points that are currently stored in the database.
Returns
the size of the database
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), and python.data.DataContainer.DataContainer::getSize().
toString()
std::string sgpp::base::GridDataBase::toString ()
Returns std::string representation of database.
Returns
string representation
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
Member Data Documentation
ascii
const char sgpp::base::GridDataBase::ascii = 'a' static
Referenced by save().
binary
const char sgpp::base::GridDataBase::binary = 'b' static
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/GridDataBase.hpp
base/src/sgpp/base/grid/GridDataBase.cpp