SG++-Doxygen-Documentation: sgpp::base::BoundingBox Class Reference
sgpp::base::BoundingBox Class Reference
This class implements the boundaries of the sparse grid.
#include <BoundingBox.hpp>
Public Member Functions
BoundingBox (const std::vector< BoundingBox1D > &boundingBox1Ds)
Constructor for BoundingBox.
BoundingBox (size_t dimension)
Constructor for BoundingBox.
const BoundingBox1D & getBoundary (size_t d) const
Returns the left and right boundary for a specific dimension.
size_t getDimension () const
Returns the number of dimensions of this bounding box.
double getIntervalOffset (size_t d) const
Returns the offset in positive x-direction of the interval in one dimension.
double getIntervalWidth (size_t d) const
Calculates the width of the interval in one dimension.
bool hasDirichletBoundaryLeft (size_t d) const
Determines if the interval in the specified dimension has left Dirichlet boundary conditions.
bool hasDirichletBoundaryRight (size_t d) const
Determines if the interval in the specified dimension has right Dirichlet boundary conditions.
bool isContainingPoint (DataVector &point) const
Check whether the BoundingBox contains a given point.
bool isContainingPoint (size_t d, double point) const
Check whether the BoundingBox contains a given point in a specific dimension.
bool isUnitCube () const
Determine if this bounding box describes the unit cube \([0, 1]^d\).
virtual std::string serialize (int version=SERIALIZATION_VERSION) const
Serialize the BoundingBox into a string.
virtual void serialize (std::ostream &ostream, int version=SERIALIZATION_VERSION) const
Serialize the BoundingBox into a stream.
void setBoundary (size_t d, const BoundingBox1D &boundingBox1D)
Sets left and right boundary for a specific dimension.
std::string toString () const
Converts the BoundingBox to a string.
void toString (std::string &text) const
Converts the BoundingBox to a string.
void transformPointsToBoundingBox (DataMatrix &points) const
Transform points in the unit cube \([0, 1]^d\) to points in the BoundingBox.
void transformPointsToUnitCube (DataMatrix &points) const
Transform points in the BoundingBox to points in the unit cube \([0, 1]^d\).
void transformPointToBoundingBox (DataVector &point) const
Transform a point in the unit cube \([0, 1]^d\) to a point in the BoundingBox.
double transformPointToBoundingBox (size_t d, double point) const
Transform a point in the unit interval \([0, 1]\) to a point in the BoundingBox in 1D.
void transformPointToUnitCube (DataVector &point) const
Transform a point in the BoundingBox to a point in the unit cube \([0, 1]^d\).
double transformPointToUnitCube (size_t d, double point) const
Transform a point in the BoundingBox to a point in the unit interval \([0, 1]\) in 1D.
virtual void unserialize (const std::string &istr, int version)
Unserialize from a string.
virtual void unserialize (std::istream &istr, int version)
Unserialize from a stream.
virtual ~BoundingBox ()
Destructor.
Protected Attributes
std::vector< BoundingBox1D > boundingBox1Ds
Array that contains all left boundaries for all dimensions.
size_t dimension
the number of dimensions used with the grid
Detailed Description
This class implements the boundaries of the sparse grid.
Internally the grid is set up on a trivial cube.
This class gives the class gives the opportunity to stretch this cube in every dimension separately.
Constructor & Destructor Documentation
BoundingBox() [1/2]
sgpp::base::BoundingBox::BoundingBox (size_t dimension) explicit
Constructor for BoundingBox.
initializes the Bounding with a N-d trivial cube
Parameters
dimension number of the dimensions used with the grid
BoundingBox() [2/2]
sgpp::base::BoundingBox::BoundingBox (const std::vector< BoundingBox1D > & boundingBox1Ds) explicit
Constructor for BoundingBox.
initializes the Bounding with specific values for all dimensions
Parameters
boundingBox1Ds array that contains all boundaries
~BoundingBox()
sgpp::base::BoundingBox::~BoundingBox () virtual
Destructor.
Member Function Documentation
getBoundary()
const BoundingBox1D & sgpp::base::BoundingBox::getBoundary (size_t d) const inline
Returns the left and right boundary for a specific dimension.
Parameters
d the dimension in which the boundary should be read
Returns
a BoundingBox1D object that contains the boundaries
References boundingBox1Ds.
Referenced by sgpp::base::OperationEvalModLinear::eval(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), sgpp::base::GridPrinter::printGrid(), sgpp::base::GridPrinterForStretching::printGrid(), sgpp::base::GridPrinter::printGridDomain(), sgpp::base::GridPrinterForStretching::printGridDomainStretching(), and sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB().
getDimension()
size_t sgpp::base::BoundingBox::getDimension () const
Returns the number of dimensions of this bounding box.
Returns
number of dimensions
References dimension.
Referenced by sgpp::pde::HeatEquationSolver::constructGrid(), sgpp::pde::PoissonEquationSolver::constructGrid(), sgpp::pde::HeatEquationSolverWithStretching::constructGrid(), sgpp::base::OperationEvalModLinear::eval(), sgpp::base::EvalCuboidGenerator::getEvaluationCuboid(), and sgpp::base::EvalCuboidGeneratorForStretching::getEvaluationCuboid().
getIntervalOffset()
double sgpp::base::BoundingBox::getIntervalOffset (size_t d) const inline
Returns the offset in positive x-direction of the interval in one dimension.
Parameters
d dimension in which the offset of the interval should be determined
Returns
offset in positive x-direction of the interval
References boundingBox1Ds.
Referenced by sgpp::base::HashGridStorage::getCoordinate(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinear::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinear::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinear::operator()(), sgpp::pde::PhiPhiUpBBLinear::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), transformPointToBoundingBox(), and transformPointToUnitCube().
getIntervalWidth()
double sgpp::base::BoundingBox::getIntervalWidth (size_t d) const inline
Calculates the width of the interval in one dimension.
Parameters
d the dimension in which the width of the interval should be determined
Returns
width of the interval
References boundingBox1Ds.
Referenced by sgpp::base::OperationQuadratureBspline::doQuadrature(), sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureLinear::doQuadrature(), sgpp::base::OperationQuadratureLinearBoundary::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureLinearClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureModBspline::doQuadrature(), sgpp::base::OperationQuadratureModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModFundamentalSpline::doQuadrature(), sgpp::base::OperationQuadratureModLinear::doQuadrature(), sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureModPoly::doQuadrature(), sgpp::base::OperationQuadratureModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineBoundary::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineExtended::doQuadrature(), sgpp::base::OperationQuadratureNakBsplineModified::doQuadrature(), sgpp::base::OperationQuadratureNakPBspline::doQuadrature(), sgpp::base::OperationQuadraturePoly::doQuadrature(), sgpp::base::OperationQuadraturePolyBoundary::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadratureFunc(), sgpp::base::OperationQuadratureMC::doQuadratureL2Error(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::HashGridStorage::getCoordinate(), sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator()(), sgpp::pde::LaplaceEnhancedDownBBLinear::operator()(), sgpp::pde::LaplaceEnhancedUpBBLinear::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinear::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinear::operator()(), sgpp::pde::PhiPhiUpBBLinear::operator()(), sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()(), sgpp::base::GetAffectedBasisFunctions< LinearBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), sgpp::base::GetAffectedBasisFunctions< LinearClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB(), transformPointToBoundingBox(), and transformPointToUnitCube().
hasDirichletBoundaryLeft()
bool sgpp::base::BoundingBox::hasDirichletBoundaryLeft (size_t d) const
Determines if the interval in the specified dimension has left Dirichlet boundary conditions.
Parameters
d the dimension for which the left boundary condition should be determined
Returns
true if Dirichlet Boundary conditions, otherwise false
References sgpp::base::BoundingBox1D::bDirichletLeft, and boundingBox1Ds.
Referenced by sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::UpdPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), and sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()().
hasDirichletBoundaryRight()
bool sgpp::base::BoundingBox::hasDirichletBoundaryRight (size_t d) const
Determines if the interval in the specified dimension has right Dirichlet boundary conditions.
Parameters
d the dimension for which the right boundary condition should be determined
Returns
true if Dirichlet Boundary conditions, otherwise false
References boundingBox1Ds.
Referenced by sgpp::pde::DowndPhidPhiBBIterativeLinearStretchedBoundary::operator()(), sgpp::pde::DowndPhidPhiBBIterativeLinearBoundary::operator()(), sgpp::pde::PhiPhiDownBBLinearBoundary::operator()(), sgpp::pde::PhiPhiUpBBLinearBoundary::operator()(), and sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator()().
isContainingPoint() [1/2]
bool sgpp::base::BoundingBox::isContainingPoint (DataVector & point) const inline
Check whether the BoundingBox contains a given point.
Parameters
point point to be checked
Returns
whether the point is contained in the BoundingBox
References dimension, and isContainingPoint().
Referenced by isContainingPoint(), sgpp::base::AlgorithmEvaluation< BASIS >::operator()(), and sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()().
isContainingPoint() [2/2]
bool sgpp::base::BoundingBox::isContainingPoint (size_t d, double point) const inline
Check whether the BoundingBox contains a given point in a specific dimension.
Parameters
d dimension to be checked
point 1D point to be checked
Returns
whether the point is contained in the BoundingBox in the given dimension
References boundingBox1Ds.
isUnitCube()
bool sgpp::base::BoundingBox::isUnitCube () const
Determine if this bounding box describes the unit cube \([0, 1]^d\).
Returns
true if this bounding box is the unit cube, otherwise false
References boundingBox1Ds, and dimension.
serialize() [1/2]
std::string sgpp::base::BoundingBox::serialize (int version = SERIALIZATION_VERSION) const virtual
Serialize the BoundingBox into a string.
Parameters
version the serialization version of the file
Returns
string that contains all BoundingBox information
Reimplemented in sgpp::base::Stretching.
References serialize().
Referenced by serialize(), sgpp::base::HashGridStorage::serialize(), sgpp::base::Stretching::serialize(), python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
serialize() [2/2]
void sgpp::base::BoundingBox::serialize (std::ostream & ostream, int version = SERIALIZATION_VERSION) const virtual
Serialize the BoundingBox into a stream.
Parameters
ostream reference to a stream into that all BoundingBox information is written
version the serialization version of the file
Reimplemented in sgpp::base::Stretching.
References sgpp::base::BoundingBox1D::bDirichletLeft, sgpp::base::BoundingBox1D::bDirichletRight, boundingBox1Ds, dimension, sgpp::base::BoundingBox1D::leftBoundary, and sgpp::base::BoundingBox1D::rightBoundary.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
setBoundary()
void sgpp::base::BoundingBox::setBoundary (size_t d, const BoundingBox1D & boundingBox1D)
Sets left and right boundary for a specific dimension.
Parameters
d the dimension in which the boundary should be changed
boundingBox1D reference to a BoundingBox1D object that contains the new boundaries
References boundingBox1Ds.
toString() [1/2]
std::string sgpp::base::BoundingBox::toString () const
Converts the BoundingBox to a string.
Returns
string to which the data is written
References toString().
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), python.learner.formatter.GridFormatter.GridFormatter::serialize(), and toString().
toString() [2/2]
void sgpp::base::BoundingBox::toString (std::string & text) const
Converts the BoundingBox to a string.
Parameters
text string to which the data is written
References boundingBox1Ds, and dimension.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
transformPointsToBoundingBox()
void sgpp::base::BoundingBox::transformPointsToBoundingBox (DataMatrix & points) const inline
Transform points in the unit cube \([0, 1]^d\) to points in the BoundingBox.
Parameters
[in,out] points points to be transformed in-place
References dimension, sgpp::base::DataMatrix::getNrows(), and transformPointToBoundingBox().
transformPointsToUnitCube()
void sgpp::base::BoundingBox::transformPointsToUnitCube (DataMatrix & points) const inline
Transform points in the BoundingBox to points in the unit cube \([0, 1]^d\).
Parameters
[in,out] points points to be transformed in-place (row-wise)
References dimension, sgpp::base::DataMatrix::getNrows(), and transformPointToUnitCube().
Referenced by sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalLinearNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModBsplineNaive::mult(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::mult(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::mult(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::mult(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::base::OperationMultipleEvalPolyNaive::mult(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalLinearNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModBsplineNaive::multTranspose(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalModPolyClenshawCurtisNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineExtendedNaive::multTranspose(), sgpp::base::OperationMultipleEvalNakBsplineModifiedNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisBoundaryNaive::multTranspose(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose(), and sgpp::base::OperationMultipleEvalPolyNaive::multTranspose().
transformPointToBoundingBox() [1/2]
void sgpp::base::BoundingBox::transformPointToBoundingBox (DataVector & point) const inline
Transform a point in the unit cube \([0, 1]^d\) to a point in the BoundingBox.
Parameters
[in,out] point point to be transformed in-place
References dimension, and transformPointToBoundingBox().
Referenced by sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadratureFunc(), sgpp::base::OperationQuadratureMC::doQuadratureL2Error(), transformPointsToBoundingBox(), and transformPointToBoundingBox().
transformPointToBoundingBox() [2/2]
double sgpp::base::BoundingBox::transformPointToBoundingBox (size_t d, double point) const inline
Transform a point in the unit interval \([0, 1]\) to a point in the BoundingBox in 1D.
Parameters
d dimension
point 1D point in unit interval
Returns
transformed 1D point in the BoundingBox
References getIntervalOffset(), and getIntervalWidth().
transformPointToUnitCube() [1/2]
void sgpp::base::BoundingBox::transformPointToUnitCube (DataVector & point) const inline
Transform a point in the BoundingBox to a point in the unit cube \([0, 1]^d\).
Parameters
[in,out] point point to be transformed in-place
References dimension, and transformPointToUnitCube().
Referenced by sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalLinearBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalLinearNaive::eval(), sgpp::base::OperationEvalModBsplineClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModBsplineNaive::eval(), sgpp::base::OperationEvalModFundamentalSplineNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearNaive::eval(), sgpp::base::OperationEvalModNakBsplineNaive::eval(), sgpp::base::OperationEvalModPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModPolyNaive::eval(), sgpp::base::OperationEvalModWaveletNaive::eval(), sgpp::base::OperationEvalModWeaklyFundamentalNakSplineNaive::eval(), sgpp::base::OperationEvalNakBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalNakBsplineExtendedNaive::eval(), sgpp::base::OperationEvalNakBsplineModifiedNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakPBsplineNaive::eval(), sgpp::base::OperationEvalNaturalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalPolyBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisBoundaryNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyNaive::eval(), sgpp::base::OperationEvalWaveletBoundaryNaive::eval(), sgpp::base::OperationEvalWaveletNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalNakSplineBoundaryNaive::eval(), sgpp::base::OperationEvalWeaklyFundamentalSplineBoundaryNaive::eval(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineClenshawCurtisNaive::evalGradient(), sgpp::base::OperationEvalGradientModBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineModifiedNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakPBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWaveletNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalNakSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientWeaklyFundamentalSplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineClenshawCurtisNaive::evalHessian(), sgpp::base::OperationEvalHessianModBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModNakBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWaveletNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalNakSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianWeaklyFundamentalSplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineClenshawCurtisNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModNakBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWaveletNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalNakSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeWeaklyFundamentalSplineBoundaryNaive::evalPartialDerivative(), sgpp::base::HashGridStorage::getUnitCoordinate(), sgpp::base::HashGridStorage::getUnitPointCoordinate(), sgpp::base::AlgorithmEvaluation< BASIS >::operator()(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()(), transformPointsToUnitCube(), and transformPointToUnitCube().
transformPointToUnitCube() [2/2]
double sgpp::base::BoundingBox::transformPointToUnitCube (size_t d, double point) const inline
Transform a point in the BoundingBox to a point in the unit interval \([0, 1]\) in 1D.
Parameters
d dimension
point 1D point in the BoundingBox
Returns
transformed 1D point in the unit interval
References getIntervalOffset(), and getIntervalWidth().
unserialize() [1/2]
void sgpp::base::BoundingBox::unserialize (const std::string & istr, int version) virtual
Unserialize from a string.
Parameters
istr string which contains a serialized BoundingBox
version the serialization version of the file
References unserialize().
Referenced by unserialize(), and sgpp::base::Stretching::unserialize().
unserialize() [2/2]
void sgpp::base::BoundingBox::unserialize (std::istream & istr, int version) virtual
Unserialize from a stream.
Parameters
istr stream which contains a serialized BoundingBox
version the serialization version of the file
References sgpp::base::BoundingBox1D::bDirichletLeft, sgpp::base::BoundingBox1D::bDirichletRight, boundingBox1Ds, dimension, sgpp::base::BoundingBox1D::leftBoundary, and sgpp::base::BoundingBox1D::rightBoundary.
Member Data Documentation
boundingBox1Ds
std::vector<BoundingBox1D> sgpp::base::BoundingBox::boundingBox1Ds protected
Array that contains all left boundaries for all dimensions.
Referenced by getBoundary(), sgpp::base::Stretching::getCoordinate(), sgpp::base::Stretching::getDiscreteVector(), getIntervalOffset(), getIntervalWidth(), hasDirichletBoundaryLeft(), hasDirichletBoundaryRight(), isContainingPoint(), isUnitCube(), serialize(), setBoundary(), sgpp::base::Stretching::Stretching(), toString(), sgpp::base::Stretching::unserialize(), and unserialize().
dimension
size_t sgpp::base::BoundingBox::dimension protected
the number of dimensions used with the grid
Referenced by getDimension(), sgpp::base::Stretching::getDiscreteVector(), isContainingPoint(), isUnitCube(), sgpp::base::Stretching::printLookupTable(), serialize(), sgpp::base::Stretching::serialize(), sgpp::base::Stretching::Stretching(), toString(), transformPointsToBoundingBox(), transformPointsToUnitCube(), transformPointToBoundingBox(), transformPointToUnitCube(), sgpp::base::Stretching::unserialize(), and unserialize().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/common/BoundingBox.hpp
base/src/sgpp/base/grid/common/BoundingBox.cpp