SG++-Doxygen-Documentation: sgpp::datadriven::HPOConfig Class Reference
sgpp::datadriven::HPOConfig Class Reference
Configuration for HyperparameterOptimizer.
#include <HPOConfig.hpp>
Public Member Functions
const std::vector< int64_t > & getConstraints () const
double getLambda () const
int64_t getNRandom () const
int64_t getNRuns () const
int64_t getNTrainSamples () const
int64_t getSeed () const
const std::vector< int64_t > & getStages () const
HPOConfig ()=default
void setConstraints (const std::vector< int64_t > &constraints)
void setLambda (double lambda)
void setNRandom (int64_t nRandom)
void setNRuns (int64_t nRuns)
void setNTrainSamples (int64_t nTrainSamples)
void setSeed (int64_t seed)
void setStages (const std::vector< int64_t > &stages)
void setupDefaults ()
Detailed Description
Configuration for HyperparameterOptimizer.
Constructor & Destructor Documentation
HPOConfig()
sgpp::datadriven::HPOConfig::HPOConfig () default
Member Function Documentation
getConstraints()
const std::vector< int64_t > & sgpp::datadriven::HPOConfig::getConstraints () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), and sgpp::datadriven::HarmonicaHyperparameterOptimizer::run().
getLambda()
double sgpp::datadriven::HPOConfig::getLambda () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), and sgpp::datadriven::HarmonicaHyperparameterOptimizer::run().
getNRandom()
int64_t sgpp::datadriven::HPOConfig::getNRandom () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), and sgpp::datadriven::BoHyperparameterOptimizer::run().
getNRuns()
int64_t sgpp::datadriven::HPOConfig::getNRuns () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), and sgpp::datadriven::BoHyperparameterOptimizer::run().
getNTrainSamples()
int64_t sgpp::datadriven::HPOConfig::getNTrainSamples () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
getSeed()
int64_t sgpp::datadriven::HPOConfig::getSeed () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), sgpp::datadriven::BoHyperparameterOptimizer::run(), and sgpp::datadriven::HarmonicaHyperparameterOptimizer::run().
getStages()
const std::vector< int64_t > & sgpp::datadriven::HPOConfig::getStages () const
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig(), and sgpp::datadriven::HarmonicaHyperparameterOptimizer::run().
setConstraints()
void sgpp::datadriven::HPOConfig::setConstraints (const std::vector< int64_t > & constraints)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setLambda()
void sgpp::datadriven::HPOConfig::setLambda (double lambda)
References lambda.
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setNRandom()
void sgpp::datadriven::HPOConfig::setNRandom (int64_t nRandom)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setNRuns()
void sgpp::datadriven::HPOConfig::setNRuns (int64_t nRuns)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setNTrainSamples()
void sgpp::datadriven::HPOConfig::setNTrainSamples (int64_t nTrainSamples)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setSeed()
void sgpp::datadriven::HPOConfig::setSeed (int64_t seed)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setStages()
void sgpp::datadriven::HPOConfig::setStages (const std::vector< int64_t > & stages)
Referenced by sgpp::datadriven::DataMiningConfigParser::getHPOConfig().
setupDefaults()
void sgpp::datadriven::HPOConfig::setupDefaults ()
Referenced by sgpp::datadriven::HyperparameterOptimizer::HyperparameterOptimizer().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/hpo/HPOConfig.hpp
datadriven/src/sgpp/datadriven/datamining/modules/hpo/HPOConfig.cpp