SG++-Doxygen-Documentation: sgpp::optimization::optimizer::Newton Class Reference
sgpp::optimization::optimizer::Newton Class Reference
Gradient-based nonlinear conjugate gradient method.
#include <Newton.hpp>
Public Member Functions
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getAlpha1 () const
double getAlpha2 () const
double getBeta () const
double getEpsilon () const
double getGamma () const
double getP () const
double getTolerance () const
Newton (const base::ScalarFunction &f, const base::ScalarFunctionHessian &fHessian, size_t maxItCount, double beta, double gamma, double tolerance, double epsilon, double alpha1, double alpha2, double p, const base::sle_solver::SLESolver &sleSolver)
Constructor.
Newton (const base::ScalarFunction &f, const base::ScalarFunctionHessian &fHessian, size_t maxItCount=DEFAULT_N, double beta=DEFAULT_BETA, double gamma=DEFAULT_GAMMA, double tolerance=DEFAULT_TOLERANCE, double epsilon=DEFAULT_EPSILON, double alpha1=DEFAULT_ALPHA1, double alpha2=DEFAULT_ALPHA2, double p=DEFAULT_P)
Constructor.
Newton (const Newton &other)
Copy constructor.
void optimize () override
Pure virtual method for optimization of the objective function.
void setAlpha1 (double alpha1)
void setAlpha2 (double alpha2)
void setBeta (double beta)
void setEpsilon (double epsilon)
void setGamma (double gamma)
void setP (double p)
void setTolerance (double tolerance)
~Newton () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_ALPHA1 = 1e-6
default steepest descent restart parameter 1
static constexpr double DEFAULT_ALPHA2 = 1e-6
default steepest descent restart parameter 2
static constexpr double DEFAULT_BETA = 0.5
default beta (parameter for Armijo's rule)
static constexpr double DEFAULT_EPSILON = 1e-18
default epsilon (parameter for Armijo's rule)
static constexpr double DEFAULT_GAMMA = 1e-2
default gamma (parameter for Armijo's rule)
static constexpr double DEFAULT_P = 0.1
default steepest descent restart exponent
static constexpr double DEFAULT_TOLERANCE = 1e-8
default tolerance (parameter for Armijo's rule)
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
double alpha1
steepest descent restart parameter 1
double alpha2
steepest descent restart parameter 2
double beta
beta (parameter for Armijo's rule)
const base::sle_solver::GaussianElimination defaultSleSolver
default linear solver
double eps
epsilon (parameter for Armijo's rule)
double gamma
gamma (parameter for Armijo's rule)
double p
steepest descent restart exponent
const base::sle_solver::SLESolver & sleSolver
linear solver
double tol
tolerance (parameter for Armijo's rule)
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Gradient-based nonlinear conjugate gradient method.
The method is restarted with the steepest descent direction if the inner product of negated gradient and search direction is not big enough (criterion depending on three parameters).
Constructor & Destructor Documentation
Newton() [1/3]
sgpp::optimization::optimizer::Newton::Newton (const base::ScalarFunction & f, const base::ScalarFunctionHessian & fHessian, size_t maxItCount = DEFAULT_N, double beta = DEFAULT_BETA, double gamma = DEFAULT_GAMMA, double tolerance = DEFAULT_TOLERANCE, double epsilon = DEFAULT_EPSILON, double alpha1 = DEFAULT_ALPHA1, double alpha2 = DEFAULT_ALPHA2, double p = DEFAULT_P)
Constructor.
By default, GaussianElimination is used to solve the linear systems.
Parameters
f objective function
fHessian objective function Hessian
maxItCount maximal number of iterations
beta beta (parameter for Armijo's rule)
gamma gamma (parameter for Armijo's rule)
tolerance tolerance (parameter for Armijo's rule)
epsilon epsilon (parameter for Armijo's rule)
alpha1 steepest descent restart parameter 1
alpha2 steepest descent restart parameter 2
p steepest descent restart exponent
Newton() [2/3]
sgpp::optimization::optimizer::Newton::Newton (const base::ScalarFunction & f, const base::ScalarFunctionHessian & fHessian, size_t maxItCount, double beta, double gamma, double tolerance, double epsilon, double alpha1, double alpha2, double p, const base::sle_solver::SLESolver & sleSolver)
Constructor.
Do not destruct the solver before this object!
Parameters
f objective function
fHessian objective function Hessian
maxItCount maximal number of iterations
beta beta (parameter for Armijo's rule)
gamma gamma (parameter for Armijo's rule)
tolerance tolerance (parameter for Armijo's rule)
epsilon epsilon (parameter for Armijo's rule)
alpha1 steepest descent restart parameter 1
alpha2 steepest descent restart parameter 2
p steepest descent restart exponent
sleSolver reference to linear solver for solving the linear systems (Hessian as coefficient matrix)
Newton() [3/3]
sgpp::optimization::optimizer::Newton::Newton (const Newton & other)
Copy constructor.
Parameters
other optimizer to be copied
~Newton()
sgpp::optimization::optimizer::Newton::~Newton () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::Newton::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getAlpha1()
double sgpp::optimization::optimizer::Newton::getAlpha1 () const
Returns
steepest descent restart parameter 1
References alpha1.
getAlpha2()
double sgpp::optimization::optimizer::Newton::getAlpha2 () const
Returns
steepest descent restart parameter 2
References alpha2.
getBeta()
double sgpp::optimization::optimizer::Newton::getBeta () const
Returns
beta (parameter for Armijo's rule)
References beta.
getEpsilon()
double sgpp::optimization::optimizer::Newton::getEpsilon () const
Returns
epsilon (parameter for Armijo's rule)
References eps.
getGamma()
double sgpp::optimization::optimizer::Newton::getGamma () const
Returns
gamma (parameter for Armijo's rule)
References gamma.
getP()
double sgpp::optimization::optimizer::Newton::getP () const
Returns
steepest descent restart exponent
References p.
getTolerance()
double sgpp::optimization::optimizer::Newton::getTolerance () const
Returns
tolerance (parameter for Armijo's rule)
References tol.
optimize()
void sgpp::optimization::optimizer::Newton::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References alpha1, alpha2, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), beta, sgpp::base::Printer::disableStatusPrinting(), sgpp::base::Printer::enableStatusPrinting(), eps, sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHessian, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, gamma, sgpp::base::Printer::getInstance(), sgpp::base::Printer::isStatusPrintingEnabled(), sgpp::base::DataVector::l2Norm(), sgpp::optimization::optimizer::lineSearchArmijo(), sgpp::optimization::optimizer::UnconstrainedOptimizer::N, p, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), sleSolver, sgpp::base::sle_solver::SLESolver::solve(), tol, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setAlpha1()
void sgpp::optimization::optimizer::Newton::setAlpha1 (double alpha1)
Parameters
alpha1 steepest descent restart parameter 1
References alpha1.
setAlpha2()
void sgpp::optimization::optimizer::Newton::setAlpha2 (double alpha2)
Parameters
alpha2 steepest descent restart parameter 2
References alpha2.
setBeta()
void sgpp::optimization::optimizer::Newton::setBeta (double beta)
Parameters
beta beta (parameter for Armijo's rule)
References beta.
setEpsilon()
void sgpp::optimization::optimizer::Newton::setEpsilon (double epsilon)
Parameters
epsilon epsilon (parameter for Armijo's rule)
References eps.
setGamma()
void sgpp::optimization::optimizer::Newton::setGamma (double gamma)
Parameters
gamma gamma (parameter for Armijo's rule)
References gamma.
setP()
void sgpp::optimization::optimizer::Newton::setP (double p)
Parameters
p steepest descent restart exponent
References p.
setTolerance()
void sgpp::optimization::optimizer::Newton::setTolerance (double tolerance)
Parameters
tolerance tolerance (parameter for Armijo's rule)
References tol.
Member Data Documentation
alpha1
double sgpp::optimization::optimizer::Newton::alpha1 protected
steepest descent restart parameter 1
Referenced by getAlpha1(), optimize(), and setAlpha1().
alpha2
double sgpp::optimization::optimizer::Newton::alpha2 protected
steepest descent restart parameter 2
Referenced by getAlpha2(), optimize(), and setAlpha2().
beta
double sgpp::optimization::optimizer::Newton::beta protected
beta (parameter for Armijo's rule)
Referenced by getBeta(), optimize(), and setBeta().
DEFAULT_ALPHA1
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_ALPHA1 = 1e-6 static constexpr
default steepest descent restart parameter 1
DEFAULT_ALPHA2
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_ALPHA2 = 1e-6 static constexpr
default steepest descent restart parameter 2
DEFAULT_BETA
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_BETA = 0.5 static constexpr
default beta (parameter for Armijo's rule)
DEFAULT_EPSILON
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_EPSILON = 1e-18 static constexpr
default epsilon (parameter for Armijo's rule)
DEFAULT_GAMMA
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_GAMMA = 1e-2 static constexpr
default gamma (parameter for Armijo's rule)
DEFAULT_P
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_P = 0.1 static constexpr
default steepest descent restart exponent
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::Newton::DEFAULT_TOLERANCE = 1e-8 static constexpr
default tolerance (parameter for Armijo's rule)
defaultSleSolver
const base::sle_solver::GaussianElimination sgpp::optimization::optimizer::Newton::defaultSleSolver protected
default linear solver
eps
double sgpp::optimization::optimizer::Newton::eps protected
epsilon (parameter for Armijo's rule)
Referenced by getEpsilon(), optimize(), and setEpsilon().
gamma
double sgpp::optimization::optimizer::Newton::gamma protected
gamma (parameter for Armijo's rule)
Referenced by getGamma(), optimize(), and setGamma().
p
double sgpp::optimization::optimizer::Newton::p protected
steepest descent restart exponent
Referenced by getP(), optimize(), and setP().
sleSolver
const base::sle_solver::SLESolver& sgpp::optimization::optimizer::Newton::sleSolver protected
linear solver
Referenced by optimize().
tol
double sgpp::optimization::optimizer::Newton::tol protected
tolerance (parameter for Armijo's rule)
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/Newton.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/Newton.cpp