SG++-Doxygen-Documentation: sgpp::base::BsplineBoundaryBasis< LT, IT > Class Template Reference
sgpp::base::BsplineBoundaryBasis< LT, IT > Class Template Reference
B-spline basis on Boundary grids.
#include <BsplineBoundaryBasis.hpp>
Public Member Functions
BsplineBoundaryBasis ()
Default constructor.
BsplineBoundaryBasis (size_t degree)
Constructor.
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
double getIntegral (LT l, IT i) override
returns the integal of the current basis function
~BsplineBoundaryBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::BsplineBoundaryBasis< LT, IT >
B-spline basis on Boundary grids.
Constructor & Destructor Documentation
BsplineBoundaryBasis() [1/2]
template<class LT , class IT > sgpp::base::BsplineBoundaryBasis< LT, IT >::BsplineBoundaryBasis () inline
Default constructor.
BsplineBoundaryBasis() [2/2]
template<class LT , class IT > sgpp::base::BsplineBoundaryBasis< LT, IT >::BsplineBoundaryBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
~BsplineBoundaryBasis()
template<class LT , class IT > sgpp::base::BsplineBoundaryBasis< LT, IT >::~BsplineBoundaryBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::BsplineBoundaryBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of boundary B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalBsplineBoundaryNaive::eval(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), and sgpp::base::OperationMultipleEvalBsplineBoundaryNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::BsplineBoundaryBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of boundary B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineBoundaryNaive::evalPartialDerivative(), and sgpp::pde::OperationLaplaceBsplineBoundary::mult().
evalDxDx()
template<class LT , class IT > double sgpp::base::BsplineBoundaryBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of boundary B-spline basis function
References sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian(), and sgpp::base::OperationEvalHessianBsplineBoundaryNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::BsplineBoundaryBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::BsplineBoundaryBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::OperationQuadratureBsplineBoundary::doQuadrature().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::BsplineBoundaryBasis< LT, IT >::bsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::BsplineBoundaryBasis< LT, IT >::eval(), sgpp::base::BsplineBoundaryBasis< LT, IT >::evalDx(), sgpp::base::BsplineBoundaryBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::BsplineBoundaryBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/BsplineBoundaryBasis.hpp