SG++-Doxygen-Documentation: sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T > Class Template Reference
sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T > Class Template Reference abstract
#include <OperationPackageBaseMPI.hpp>
Public Member Functions
MPIWorkerPackageBase (std::string operationName, int multiplier)
MPIWorkerPackageBase (std::string operationName, int multiplier, std::string ocl_conf_filename)
void start_worker_main (void)
virtual ~MPIWorkerPackageBase ()
Public Member Functions inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
MPIWorkerBase ()
MPIWorkerBase (std::string worker_class_name)
void release_sub_workers (void)
void start_sub_workers (void)
virtual ~MPIWorkerBase (void)
Protected Member Functions
virtual void begin_opencl_operation (int *workpackage)=0
void divide_workpackages (int *package, T *erg)
virtual void finalize_opencl_operation (T *result_buffer, int *workpackage)=0
virtual void receive_and_send_initial_data (void)=0
Protected Attributes
MPI_Comm & master_worker_comm
MPI_Datatype mpi_typ
size_t opencl_device = 0
bool opencl_node
size_t opencl_platform = 0
bool overseer_node
int packagesize_multiplier
base::OCLOperationConfiguration * parameters
bool prefetching
bool redistribute
int secondary_workpackage [2]
size_t size
MPI_Comm & sub_worker_comm
Protected Attributes inherited from sgpp::datadriven::clusteringmpi::MPIWorkerBase
bool verbose
Constructor & Destructor Documentation
MPIWorkerPackageBase() [1/2]
template<class T > sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase (std::string operationName, int multiplier) inline
References json::JSON::deserialize(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_configuration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), json::Node::getBool(), json::Node::getUInt(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::master_worker_comm, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::mpi_typ, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_device, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_platform, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::overseer_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::parameters, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::prefetching, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::redistribute, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::size, and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::sub_worker_comm.
MPIWorkerPackageBase() [2/2]
template<class T > sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase (std::string operationName, int multiplier, std::string ocl_conf_filename) inline
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_configuration(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), json::Node::getBool(), json::Node::getUInt(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::mpi_typ, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_device, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_platform, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::overseer_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::parameters, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::prefetching, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::redistribute, json::JSON::serialize(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::size, and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::sub_worker_comm.
~MPIWorkerPackageBase()
template<class T > virtual sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::~MPIWorkerPackageBase () inline virtual
Member Function Documentation
begin_opencl_operation()
template<class T > virtual void sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::begin_opencl_operation (int * workpackage) protected pure virtual
Implemented in sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker, sgpp::datadriven::clusteringmpi::DensityWorker, and sgpp::datadriven::clusteringmpi::DensityRhsWorker.
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
divide_workpackages()
template<class T > void sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages (int * package, T * erg) inline protected
References sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::SimpleQueue< T >::is_finished(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::packagesize_multiplier, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::prefetching, sgpp::datadriven::clusteringmpi::SimpleQueue< T >::receive_result(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::redistribute, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::size, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
finalize_opencl_operation()
template<class T > virtual void sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::finalize_opencl_operation (T * result_buffer, int * workpackage) protected pure virtual
Implemented in sgpp::datadriven::clusteringmpi::DensityWorker, sgpp::datadriven::clusteringmpi::DensityRhsWorker, and sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker.
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
receive_and_send_initial_data()
template<class T > virtual void sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::receive_and_send_initial_data (void) protected pure virtual
Implemented in sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker, sgpp::datadriven::clusteringmpi::DensityWorker, and sgpp::datadriven::clusteringmpi::DensityRhsWorker.
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
start_worker_main()
template<class T > void sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main (void) inline virtual
Implements sgpp::datadriven::clusteringmpi::MPIWorkerBase.
References sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::begin_opencl_operation(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::finalize_opencl_operation(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_node_rank(), sgpp::datadriven::clusteringmpi::MPIEnviroment::get_sub_worker_count(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::master_worker_comm, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::mpi_typ, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_node, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::packagesize_multiplier, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::prefetching, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::receive_and_send_initial_data(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::secondary_workpackage, sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::sub_worker_comm, and sgpp::datadriven::clusteringmpi::MPIWorkerBase::verbose.
Member Data Documentation
master_worker_comm
template<class T > MPI_Comm& sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::master_worker_comm protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
mpi_typ
template<class T > MPI_Datatype sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::mpi_typ protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
opencl_device
template<class T > size_t sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_device = 0 protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
opencl_node
template<class T > bool sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_node protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
opencl_platform
template<class T > size_t sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::opencl_platform = 0 protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
overseer_node
template<class T > bool sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::overseer_node protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
packagesize_multiplier
template<class T > int sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::packagesize_multiplier protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
parameters
template<class T > base::OCLOperationConfiguration* sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::parameters protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
prefetching
template<class T > bool sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::prefetching protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
redistribute
template<class T > bool sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::redistribute protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
secondary_workpackage
template<class T > int sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::secondary_workpackage[2] protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
size
template<class T > size_t sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::size protected
Referenced by python.data.DataContainer.DataContainer::__init__(), python.data.DataContainer.DataContainer::__next__(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), python.data.DataContainer.DataContainer::getSize(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase().
sub_worker_comm
template<class T > MPI_Comm& sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::sub_worker_comm protected
Referenced by sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::divide_workpackages(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::MPIWorkerPackageBase(), and sgpp::datadriven::clusteringmpi::MPIWorkerPackageBase< T >::start_worker_main().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMPI/OperationPackageBaseMPI.hpp