SG++-Doxygen-Documentation: sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates Class Reference
sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates Class Reference
#include <OperationMakePositiveCandidateSetAlgorithm.hpp>
Public Member Functions
void findIntersections (base::Grid &grid, base::DataVector &alpha, size_t levelSum, std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > &res) override
void nextCandidates (base::Grid &grid, base::DataVector &alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > &candidates) override
Load the next candidate set that contains grid points with the currently explored levelsum.
OperationMakePositiveHybridFindIntersectionCandidates (size_t maxLevel)
~OperationMakePositiveHybridFindIntersectionCandidates () override
Public Member Functions inherited from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates
size_t numCandidates () override
base::DataVector & numCandidatesPerIteration () override
OperationMakePositiveFindIntersectionCandidates (size_t maxLevel)
~OperationMakePositiveFindIntersectionCandidates () override
Public Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
size_t costsComputingCandidates ()
base::DataVector & costsComputingCandidatesPerIteration ()
base::DataVector & numCandidatesPerLevel ()
OperationMakePositiveCandidateSetAlgorithm (size_t maxLevel)
Constructor.
void setVerbose (bool pverbose)
Set verbosity level.
virtual ~OperationMakePositiveCandidateSetAlgorithm ()
Desctructor.
Additional Inherited Members
Protected Member Functions inherited from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates
void computeIntersection (base::HashGridPoint &gpi, base::HashGridPoint &gpj, base::HashGridPoint &gpintersection)
bool haveOverlappingSupport (base::HashGridPoint &gpi, base::HashGridPoint &gpj)
bool haveOverlappingSupport (base::HashGridPoint &gpi, base::HashGridPoint &gpj, size_t dim)
virtual void initializeCandidates (base::Grid &grid, std::vector< size_t > &negativeGridPoints)
Protected Member Functions inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
void findNodesWithNegativeCoefficients (base::DataVector &alpha, std::vector< size_t > &negativeGridPoints, double tol=-1e-14)
Extract grid points with negative coefficient.
Static Protected Member Functions inherited from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates
static bool compareGridPointsByHash (const std::shared_ptr< base::HashGridPoint > &lhs, const std::shared_ptr< base::HashGridPoint > &rhs)
Protected Attributes inherited from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates
std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > candidates
std::set< std::shared_ptr< base::HashGridPoint >, HashGridPointCompare > currentIntersections
std::unordered_map< size_t, std::shared_ptr< std::vector< std::shared_ptr< base::HashGridPoint > > > > intersections
std::set< std::shared_ptr< base::HashGridPoint >, HashGridPointCompare > nextIntersections
base::DataVector numCandidatesIteration
Protected Attributes inherited from sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm
base::DataVector costsPerIteration
comparison costs per iteration
base::DataVector gridPointsPerLevel
candiddate grid points per level
size_t iteration
iteration counter
size_t maxLevel
maximum full grid level for the candidate set
bool verbose
verbosity level
Constructor & Destructor Documentation
OperationMakePositiveHybridFindIntersectionCandidates()
sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::OperationMakePositiveHybridFindIntersectionCandidates (size_t maxLevel) explicit
~OperationMakePositiveHybridFindIntersectionCandidates()
sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::~OperationMakePositiveHybridFindIntersectionCandidates () override
Member Function Documentation
findIntersections()
void sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections (base::Grid & grid, base::DataVector & alpha, size_t levelSum, std::unordered_map< size_t, std::shared_ptr< base::HashGridPoint > > & res) override virtual
Reimplemented from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates.
References sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::computeIntersection(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::costsPerIteration, sgpp::op_factory::createOperationEvalNaive(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::currentIntersections, grid(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::haveOverlappingSupport(), sgpp::base::DataVector::insert(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::intersections, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::iteration, sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::nextIntersections, sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::numCandidatesIteration, sgpp::base::DataVector::resizeZero(), sgpp::base::DataVector::sum(), and sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::verbose.
Referenced by nextCandidates().
nextCandidates()
void sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates (base::Grid & grid, base::DataVector & alpha, size_t levelSum, std::vector< std::shared_ptr< base::HashGridPoint > > & candidates) override virtual
Load the next candidate set that contains grid points with the currently explored levelsum.
Parameters
grid current sparse grid that needs to be extended
alpha corresponding coefficient vector
levelSum current levelsum to be explored
candidates vector that contains the candidate set for the current levelsum
Reimplemented from sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates.
References alpha, sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::candidates, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::costsPerIteration, findIntersections(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::findNodesWithNegativeCoefficients(), sgpp::base::HashGridStorage::getMaxLevel(), sgpp::base::DataVector::getSize(), sgpp::base::Grid::getStorage(), grid(), sgpp::datadriven::OperationMakePositiveFindIntersectionCandidates::initializeCandidates(), sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::iteration, sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::maxLevel, sgpp::base::DataVector::sum(), and sgpp::datadriven::OperationMakePositiveCandidateSetAlgorithm::verbose.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationMakePositiveCandidateSetAlgorithm.cpp