SG++-Doxygen-Documentation: sgpp::base::EvalCuboidGenerator Class Reference
sgpp::base::EvalCuboidGenerator Class Reference
This class builds a cuboid in the d-dimension space.
#include <EvalCuboidGenerator.hpp>
Public Member Functions
EvalCuboidGenerator ()
Constructor.
void getEvaluationCuboid (DataMatrix &EvaluationPoints, BoundingBox &SubDomain, size_t points)
This function builds an cuboid which will be stored into the EvaluationPoint variable of this function.
~EvalCuboidGenerator ()
Destructor.
Detailed Description
This class builds a cuboid in the d-dimension space.
This cuboid is discretesized by a regular full grid.
Constructor & Destructor Documentation
EvalCuboidGenerator()
sgpp::base::EvalCuboidGenerator::EvalCuboidGenerator ()
Constructor.
~EvalCuboidGenerator()
sgpp::base::EvalCuboidGenerator::~EvalCuboidGenerator ()
Destructor.
Member Function Documentation
getEvaluationCuboid()
void sgpp::base::EvalCuboidGenerator::getEvaluationCuboid (DataMatrix & EvaluationPoints, BoundingBox & SubDomain, size_t points)
This function builds an cuboid which will be stored into the EvaluationPoint variable of this function.
This is by done by building a cuboid around a bounding box. Be aware that this function returns points to the power of d points.
Parameters
EvaluationPoints DataMatrix that will contain the evaluation points afterwards
SubDomain the bounding box of the evaluation cuboid
points number of points used in every dimension
References sgpp::base::BoundingBox::getDimension(), sgpp::base::DataMatrix::resize(), and sgpp::base::DataMatrix::setRow().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/EvalCuboidGenerator.hpp
base/src/sgpp/base/tools/EvalCuboidGenerator.cpp