SG++-Doxygen-Documentation: sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > > Class Reference
sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > > Class Reference
Template Specialization for PolyClenshawCurtisBoundaryBasis basis.
#include <GetAffectedBasisFunctions.hpp>
Public Member Functions
GetAffectedBasisFunctions (GridStorage &storage)
void operator() (SPolyBoundaryBase &basis, const DataVector &point, std::vector< std::pair< size_t, double > > &result)
~GetAffectedBasisFunctions ()
Protected Member Functions
void rec (SPolyBoundaryBase &basis, const DataVector &point, size_t current_dim, double value, GridStorage::grid_iterator &working, std::vector< std::pair< size_t, double > > &result)
void recBB (SPolyBoundaryBase &basis, const DataVector &point, size_t current_dim, double value, GridStorage::grid_iterator &working, std::vector< std::pair< size_t, double > > &result)
Protected Attributes
BoundingBox * BB
GridStorage & storage
Detailed Description
Template Specialization for PolyClenshawCurtisBoundaryBasis basis.
Constructor & Destructor Documentation
GetAffectedBasisFunctions()
sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::GetAffectedBasisFunctions (GridStorage & storage) inline explicit
~GetAffectedBasisFunctions()
sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::~GetAffectedBasisFunctions () inline
Member Function Documentation
operator()()
void sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::operator() (SPolyBoundaryBase & basis, const DataVector & point, std::vector< std::pair< size_t, double > > & result) inline
References sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::HashGridIterator::resetToLevelZero(), and sgpp::base::GetAffectedBasisFunctions< BASIS >::storage.
rec()
void sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::rec (SPolyBoundaryBase & basis, const DataVector & point, size_t current_dim, double value, GridStorage::grid_iterator & working, std::vector< std::pair< size_t, double > > & result) inline protected
References sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::HashGridIterator::get(), sgpp::base::HashGridStorage::getDimension(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::GetAffectedBasisFunctions< BASIS >::rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::seq(), and sgpp::base::GetAffectedBasisFunctions< BASIS >::storage.
recBB()
void sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::recBB (SPolyBoundaryBase & basis, const DataVector & point, size_t current_dim, double value, GridStorage::grid_iterator & working, std::vector< std::pair< size_t, double > > & result) inline protected
References sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::HashGridIterator::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::seq(), and sgpp::base::GetAffectedBasisFunctions< BASIS >::storage.
Member Data Documentation
BB
BoundingBox* sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::BB protected
storage
GridStorage& sgpp::base::GetAffectedBasisFunctions< PolyClenshawCurtisBoundaryBasis< unsigned int, unsigned int > >::storage protected
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/GetAffectedBasisFunctions.hpp