SG++-Doxygen-Documentation: sgpp::base::sle_solver::Gmmpp Class Reference
sgpp::base::sle_solver::Gmmpp Class Reference
Linear system solver using Gmm++ (iterative sparse solver).
#include <Gmmpp.hpp>
Public Member Functions
bool solve (SLE &system, DataVector &b, DataVector &x) const override
~Gmmpp () override
Destructor.
Public Member Functions inherited from sgpp::base::sle_solver::SLESolver
SLESolver ()
Constructor.
virtual bool solve (SLE &system, DataMatrix &B, DataMatrix &X) const
Virtual method for solving multiple linear systems with different right-hand sides.
virtual ~SLESolver ()
Destructor.
Detailed Description
Linear system solver using Gmm++ (iterative sparse solver).
Constructor & Destructor Documentation
~Gmmpp()
sgpp::base::sle_solver::Gmmpp::~Gmmpp () override
Destructor.
Member Function Documentation
solve()
bool sgpp::base::sle_solver::Gmmpp::solve (SLE & system, DataVector & b, DataVector & x) const override virtual
Parameters
system system to be solved
b right-hand side
[out] x solution to the system
Returns
whether all went well (false if errors occurred)
Implements sgpp::base::sle_solver::SLESolver.
References sgpp::base::SLE::getDimension(), sgpp::base::Printer::getInstance(), sgpp::base::SLE::getMatrixEntry(), sgpp::base::SLE::isCloneable(), sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusNewLine(), sgpp::base::Printer::printStatusUpdate(), and sgpp::base::sle_solver::solveInternal().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/sle/solver/Gmmpp.hpp
base/src/sgpp/base/tools/sle/solver/Gmmpp.cpp