SG++-Doxygen-Documentation: sgpp::base::OperationEvalModLinear Class Reference
sgpp::base::OperationEvalModLinear Class Reference
This class implements OperationEval for a grids with mod linear basis ansatzfunctions with.
#include <OperationEvalModLinear.hpp>
Public Member Functions
double eval (const DataVector &alpha, const DataVector &point) override
Evaluates the sparse grid function at a given point.
OperationEvalModLinear (GridStorage &storage)
Constructor.
~OperationEvalModLinear () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
virtual void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value)
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
GridStorage & storage
Pointer to GridStorage object.
Detailed Description
This class implements OperationEval for a grids with mod linear basis ansatzfunctions with.
Constructor & Destructor Documentation
OperationEvalModLinear()
sgpp::base::OperationEvalModLinear::OperationEvalModLinear (GridStorage & storage) inline explicit
Constructor.
Parameters
storage the grid's GridStorage object
~OperationEvalModLinear()
sgpp::base::OperationEvalModLinear::~OperationEvalModLinear () inline override
Destructor.
Member Function Documentation
eval()
double sgpp::base::OperationEvalModLinear::eval (const DataVector & alpha, const DataVector & point) override virtual
Evaluates the sparse grid function at a given point.
Parameters
alpha The coefficients of the sparse grid's basis functions
point The coordinates of the evaluation point
Implements sgpp::base::OperationEval.
References alpha, sgpp::base::DataVector::copyFrom(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::BoundingBox::getDimension(), sgpp::base::BoundingBox1D::leftBoundary, sgpp::base::BoundingBox1D::rightBoundary, and storage.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
storage
GridStorage& sgpp::base::OperationEvalModLinear::storage protected
Pointer to GridStorage object.
Referenced by eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalModLinear.hpp
base/src/sgpp/base/operation/hash/OperationEvalModLinear.cpp