SG++-Doxygen-Documentation: sgpp::datadriven::ScorerFactory Class Reference
sgpp::datadriven::ScorerFactory Class Reference
Factory to build the scorer.
#include <ScorerFactory.hpp>
Public Member Functions
Scorer * buildRegularizationScorer (const RegularizationConfiguration &config)
Assemble a sgpp::datadriven::Scorer for regularization optimization based on the configuration.
Scorer * buildScorer (const DataMiningConfigParser &parser)
Assemble a sgpp::datadriven::Scorer object based on the configuration.
ScorerFactory ()=default
Default constructor.
~ScorerFactory ()=default
Destructor.
Protected Member Functions
Metric * buildMetric (ScorerMetricType config) const
Build a sgpp::datadriven::Metric object based on the given metric type enum value.
Metric * buildRegularizationMetric (RegularizationMetricType config) const
Build a sgpp::datadriven::Metric object based on the given metric type enum value.
Detailed Description
Factory to build the scorer.
Constructor & Destructor Documentation
ScorerFactory()
sgpp::datadriven::ScorerFactory::ScorerFactory () default
Default constructor.
~ScorerFactory()
sgpp::datadriven::ScorerFactory::~ScorerFactory () default
Destructor.
Member Function Documentation
buildMetric()
Metric * sgpp::datadriven::ScorerFactory::buildMetric (ScorerMetricType config) const protected
Build a sgpp::datadriven::Metric object based on the given metric type enum value.
Parameters
config sgpp::datadriven::ScorerMetricType describing which sgpp::datadriven::Metric to generate.
Returns
Fully configured instance of a sgpp::datadriven::Metric object.
References sgpp::datadriven::accuracy, sgpp::datadriven::mse, and sgpp::datadriven::nll.
Referenced by buildScorer().
buildRegularizationMetric()
Metric * sgpp::datadriven::ScorerFactory::buildRegularizationMetric (RegularizationMetricType config) const protected
Build a sgpp::datadriven::Metric object based on the given metric type enum value.
Parameters
config sgpp::datadriven::RegularizationMetricType describing which sgpp::datadriven::Metric to generate.
Returns
Fully configured instance of a sgpp::datadriven::Metric object.
References sgpp::datadriven::accuracy, sgpp::datadriven::mse, sgpp::datadriven::nll, and sgpp::datadriven::residual.
Referenced by buildRegularizationScorer().
buildRegularizationScorer()
Scorer * sgpp::datadriven::ScorerFactory::buildRegularizationScorer (const RegularizationConfiguration & config)
Assemble a sgpp::datadriven::Scorer for regularization optimization based on the configuration.
Parameters
config regularization config
Returns
Fully configured instance of a sgpp::datadriven::Scorer object.
References buildRegularizationMetric(), and sgpp::datadriven::RegularizationConfiguration::regularizationMetric_.
buildScorer()
Scorer * sgpp::datadriven::ScorerFactory::buildScorer (const DataMiningConfigParser & parser)
Assemble a sgpp::datadriven::Scorer object based on the configuration.
Parameters
parser Instance of sgpp::datadriven::DataMiningConfigParser that reads the required data from the config file.
Returns
Fully configured instance of a sgpp::datadriven::Scorer object.
References buildMetric(), and sgpp::datadriven::ScorerConfiguration::metric_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/builder/ScorerFactory.hpp
datadriven/src/sgpp/datadriven/datamining/builder/ScorerFactory.cpp