SG++-Doxygen-Documentation: sgpp::base::GeneralizedBoundaryGridGenerator Class Reference
sgpp::base::GeneralizedBoundaryGridGenerator Class Reference
This class provides the interface for the grid generation for grids with boundaries, pentagon cut through sub space scheme.
#include <GeneralizedBoundaryGridGenerator.hpp>
Public Member Functions
void cliques (size_t level, size_t clique_size) override
Creates a sparse grid with fully connected cliques.
void coarsen (CoarseningFunctor &func, std::vector< size_t > *removedSeq) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void coarsenNFirstOnly (CoarseningFunctor &func, size_t numFirstOnly, std::vector< size_t > *removedSeq, size_t minIndexConsidered) override
Coarsens a grid according to the settings of the CoarseningFunctor func.
void full (size_t level) override
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
GeneralizedBoundaryGridGenerator (GridStorage &storage)
Constructor.
size_t getNumberOfRefinablePoints () override
Returns the number of points on the grid that can be refined in the next iteration.
size_t getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) override
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
size_t getNumberOfRemovablePoints () override
Returns the number of points on the grid that can be removed in the next iteration.
void refine (RefinementFunctor &func, std::vector< size_t > *addedPoints=nullptr) override
Refines a grid according to the settings of the RefinementFunctor func.
void refineMaxLevel (RefinementFunctor &func, size_t maxLevel) override
Refines a grid according to the settings of the RefinementFunctor func.
void regular (size_t level) override
Creates a regular truncated boundary grid with given level and l_user=1 Is the same as the regular truncated grid.
void truncated (size_t level, size_t l_user) override
Creates a super truncated boundary grid with given level and l_user.
~GeneralizedBoundaryGridGenerator () override
Destructor.
Public Member Functions inherited from sgpp::base::GridGenerator
virtual void anisotropicFull (std::vector< size_t > dimlevels)
Creates an anisotropicFull Grid for certain level vector, for example [2,3,1] results in a 3x7x1 grid.
virtual void cliques (size_t level, size_t clique_size, double T)
Creates a sparse grid with fully connected cliques.
GridGenerator ()
Constructor.
virtual void refineInter (RefinementFunctor &func, const std::set< std::set< size_t > > &interactions)
Refines a grid according to the settings of the RefinementFunctor func.
virtual void regular (size_t level, double T)
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
virtual void regularInter (size_t level, const std::set< std::set< size_t > > &terms, double T)
Creates a regular sparse grid for a certain level \(n \), i.e., \(*V_n^{(1)} = *\bigoplus_{|\vec{l}|_1 \leq n+d-1} W_{\vec{l}}\).
virtual ~GridGenerator ()
Destructor.
Protected Attributes
GridStorage & storage
reference to the grid's storage object
Detailed Description
This class provides the interface for the grid generation for grids with boundaries, pentagon cut through sub space scheme.
Constructor & Destructor Documentation
GeneralizedBoundaryGridGenerator()
sgpp::base::GeneralizedBoundaryGridGenerator::GeneralizedBoundaryGridGenerator (GridStorage & storage) explicit
Constructor.
Parameters
storage template type that holds the grid points
~GeneralizedBoundaryGridGenerator()
sgpp::base::GeneralizedBoundaryGridGenerator::~GeneralizedBoundaryGridGenerator () override
Destructor.
Member Function Documentation
cliques()
void sgpp::base::GeneralizedBoundaryGridGenerator::cliques (size_t level, size_t clique_size) override virtual
Creates a sparse grid with fully connected cliques.
Parameters
level Grid level
clique_size clique size
Implements sgpp::base::GridGenerator.
coarsen()
void sgpp::base::GeneralizedBoundaryGridGenerator::coarsen (CoarseningFunctor & func, std::vector< size_t > * removedSeq) inline override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Parameters
func pointer to coarsening functor
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
Implements sgpp::base::GridGenerator.
coarsenNFirstOnly()
void sgpp::base::GeneralizedBoundaryGridGenerator::coarsenNFirstOnly (CoarseningFunctor & func, size_t numFirstOnly, std::vector< size_t > * removedSeq, size_t minIndexConsidered) inline override virtual
Coarsens a grid according to the settings of the CoarseningFunctor func.
Only numFirstOnly first grid points are checked for coarsening.
Parameters
func pointer to coarsening functor
numFirstOnly max. number grid points to be coarsened
removedSeq pointer to vector to append the seq numbers of coarsened grid points to.
minIndexConsidered Minimum index of grid points that will be coarsened
Implements sgpp::base::GridGenerator.
full()
void sgpp::base::GeneralizedBoundaryGridGenerator::full (size_t level) inline override virtual
Creates a full grid for a certain level \(n \), i.e., \(V_n = *\bigoplus_{|\vec{l}|_\infty *\leq n} W_{\vec{l}}\).
Parameters
level Grid level
Implements sgpp::base::GridGenerator.
getNumberOfRefinablePoints()
size_t sgpp::base::GeneralizedBoundaryGridGenerator::getNumberOfRefinablePoints () inline override virtual
Returns the number of points on the grid that can be refined in the next iteration.
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
getNumberOfRefinablePointsToMaxLevel()
size_t sgpp::base::GeneralizedBoundaryGridGenerator::getNumberOfRefinablePointsToMaxLevel (size_t maxLevel) inline override virtual
Returns the number of points on the grid that can be refined in the next iteration additionally a maximum level for refinement is taken into account.
Parameters
maxLevel no points on higher levels than maxLevel will be created
Returns
the number of points on the grid that can be refined
Implements sgpp::base::GridGenerator.
getNumberOfRemovablePoints()
size_t sgpp::base::GeneralizedBoundaryGridGenerator::getNumberOfRemovablePoints () inline override virtual
Returns the number of points on the grid that can be removed in the next iteration.
Returns
the number of points on the grid that can be removed
Implements sgpp::base::GridGenerator.
refine()
void sgpp::base::GeneralizedBoundaryGridGenerator::refine (RefinementFunctor & func, std::vector< size_t > * addedPoints = nullptr) inline override virtual
Refines a grid according to the settings of the RefinementFunctor func.
Parameters
func reference to refinement functor
addedPoints pointer to vector to add newly created grid points to
Implements sgpp::base::GridGenerator.
refineMaxLevel()
void sgpp::base::GeneralizedBoundaryGridGenerator::refineMaxLevel (RefinementFunctor & func, size_t maxLevel) inline override virtual
Refines a grid according to the settings of the RefinementFunctor func.
additionally a maximum level for refinement is taken into account
Parameters
func pointer to refinement functor
maxLevel no points on higher levels than maxLevel will be created
Implements sgpp::base::GridGenerator.
regular()
void sgpp::base::GeneralizedBoundaryGridGenerator::regular (size_t level) override virtual
Creates a regular truncated boundary grid with given level and l_user=1 Is the same as the regular truncated grid.
Implements sgpp::base::GridGenerator.
References level, and truncated().
truncated()
void sgpp::base::GeneralizedBoundaryGridGenerator::truncated (size_t level, size_t l_user) override virtual
Creates a super truncated boundary grid with given level and l_user.
Parameters
level the maximum level of the grid
l_user the number of fullgrids cut off from the boundaries.
Reimplemented from sgpp::base::GridGenerator.
References level, storage, and sgpp::base::HashGenerator::truncated().
Referenced by regular().
Member Data Documentation
storage
GridStorage& sgpp::base::GeneralizedBoundaryGridGenerator::storage protected
reference to the grid's storage object
Referenced by truncated().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/GeneralizedBoundaryGridGenerator.hpp
base/src/sgpp/base/grid/generation/GeneralizedBoundaryGridGenerator.cpp