SG++-Doxygen-Documentation: sgpp::datadriven::KernelDensityEstimator Class Reference
sgpp::datadriven::KernelDensityEstimator Class Reference
#include <KernelDensityEstimator.hpp>
Public Member Functions
void cov (base::DataMatrix &cov, base::DataMatrix *bounds=nullptr) override
double evalSubset (base::DataVector &x, std::vector< size_t > skipElements)
void getBandwidths (base::DataVector &sigma)
void getConditionalizationFactor (base::DataVector &pcond)
getter and setter functions
size_t getDim () override
Kernel & getKernel ()
size_t getNsamples () override
void getSample (size_t isample, base::DataVector &sample)
std::shared_ptr< base::DataMatrix > getSamples () override
std::shared_ptr< base::DataVector > getSamples (size_t dim) override
void initialize (base::DataMatrix &samples) override
void initialize (std::vector< std::shared_ptr< base::DataVector > > &samplesVec)
void initializeKernel (KernelType kernelType)
KernelDensityEstimator (base::DataMatrix &samples, KernelType kernelType=KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType=BandwidthOptimizationType::SILVERMANSRULE)
KernelDensityEstimator (const KernelDensityEstimator &kde)
KernelDensityEstimator (KernelType kernelType=KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType=BandwidthOptimizationType::SILVERMANSRULE)
KernelDensityEstimator (std::vector< std::shared_ptr< base::DataVector > > &samplesVec, KernelType kernelType=KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType=BandwidthOptimizationType::SILVERMANSRULE)
KernelDensityEstimator * marginalize (size_t idim)
KernelDensityEstimator * margToDimX (size_t idim)
double mean () override
void pdf (base::DataMatrix &points, base::DataVector &res) override
double pdf (base::DataVector &x) override
void setBandwidths (const base::DataVector &sigma)
void setConditionalizationFactor (base::DataVector &pcond)
void updateConditionalizationFactors (base::DataVector &x, std::vector< size_t > &dims, base::DataVector &pcond)
double variance () override
~KernelDensityEstimator () override
Public Member Functions inherited from sgpp::datadriven::DensityEstimator
virtual void corrcoef (base::DataMatrix &corr, base::DataMatrix *bounds=nullptr)
double crossEntropy (sgpp::base::DataMatrix &samples)
DensityEstimator ()
virtual double std_deviation ()
virtual ~DensityEstimator ()
Constructor & Destructor Documentation
KernelDensityEstimator() [1/4]
sgpp::datadriven::KernelDensityEstimator::KernelDensityEstimator (KernelType kernelType = KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType = BandwidthOptimizationType::SILVERMANSRULE) explicit
References initializeKernel().
KernelDensityEstimator() [2/4]
sgpp::datadriven::KernelDensityEstimator::KernelDensityEstimator (std::vector< std::shared_ptr< base::DataVector > > & samplesVec, KernelType kernelType = KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType = BandwidthOptimizationType::SILVERMANSRULE) explicit
References initialize(), and initializeKernel().
KernelDensityEstimator() [3/4]
sgpp::datadriven::KernelDensityEstimator::KernelDensityEstimator (base::DataMatrix & samples, KernelType kernelType = KernelType::GAUSSIAN, BandwidthOptimizationType bandwidthOptimizationType = BandwidthOptimizationType::SILVERMANSRULE) explicit
References initialize(), and initializeKernel().
KernelDensityEstimator() [4/4]
sgpp::datadriven::KernelDensityEstimator::KernelDensityEstimator (const KernelDensityEstimator & kde)
References initializeKernel().
~KernelDensityEstimator()
sgpp::datadriven::KernelDensityEstimator::~KernelDensityEstimator () override
Member Function Documentation
cov()
void sgpp::datadriven::KernelDensityEstimator::cov (base::DataMatrix & cov, base::DataMatrix * bounds = nullptr) override virtual
Implements sgpp::datadriven::DensityEstimator.
References cov(), sgpp::op_factory::createOperationDensityMarginalizeKDE(), mean(), sgpp::base::DataVector::setAll(), and variance().
Referenced by python.uq.dists.Dist.Dist::corrcoeff(), and cov().
evalSubset()
double sgpp::datadriven::KernelDensityEstimator::evalSubset (base::DataVector & x, std::vector< size_t > skipElements)
getBandwidths()
void sgpp::datadriven::KernelDensityEstimator::getBandwidths (base::DataVector & sigma)
References sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::OperationInverseRosenblattTransformationKDE::OperationInverseRosenblattTransformationKDE(), sgpp::datadriven::OperationRosenblattTransformationKDE::OperationRosenblattTransformationKDE(), and python.uq.dists.KDEDist.KDEDist::toJson().
getConditionalizationFactor()
void sgpp::datadriven::KernelDensityEstimator::getConditionalizationFactor (base::DataVector & pcond)
getter and setter functions
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), and sgpp::datadriven::OperationDensityConditionalKDE::doConditional().
getDim()
size_t sgpp::datadriven::KernelDensityEstimator::getDim () override virtual
Implements sgpp::datadriven::DensityEstimator.
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), python.uq.dists.Dist.Dist::cov(), sgpp::datadriven::OperationDensityConditionalKDE::doConditional(), sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), python.uq.uq_setting.UQSetting.UQSetting::getDim(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::OperationInverseRosenblattTransformationKDE(), sgpp::datadriven::SilvermansRule::optimizeBandwidths(), and sgpp::datadriven::ScottsRule::optimizeBandwidths().
getKernel()
Kernel & sgpp::datadriven::KernelDensityEstimator::getKernel ()
Referenced by sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation1D(), and sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::eval().
getNsamples()
size_t sgpp::datadriven::KernelDensityEstimator::getNsamples () override virtual
Implements sgpp::datadriven::DensityEstimator.
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), sgpp::datadriven::OperationDensityConditionalKDE::doConditional(), and sgpp::datadriven::OperationInverseRosenblattTransformationKDE::OperationInverseRosenblattTransformationKDE().
getSample()
void sgpp::datadriven::KernelDensityEstimator::getSample (size_t isample, base::DataVector & sample)
getSamples() [1/2]
std::shared_ptr< base::DataMatrix > sgpp::datadriven::KernelDensityEstimator::getSamples () override virtual
Implements sgpp::datadriven::DensityEstimator.
Referenced by sgpp::datadriven::OperationRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation(), sgpp::datadriven::OperationRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation(), sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::KDEMaximumLikelihoodCrossValidation(), sgpp::datadriven::SilvermansRule::optimizeBandwidths(), and sgpp::datadriven::ScottsRule::optimizeBandwidths().
getSamples() [2/2]
std::shared_ptr< base::DataVector > sgpp::datadriven::KernelDensityEstimator::getSamples (size_t dim) override virtual
Implements sgpp::datadriven::DensityEstimator.
initialize() [1/2]
void sgpp::datadriven::KernelDensityEstimator::initialize (base::DataMatrix & samples) override virtual
Implements sgpp::datadriven::DensityEstimator.
References sgpp::base::DataVector::setAll().
Referenced by sgpp::datadriven::OperationDensityMarginalizeKDE::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeKDE::doMarginalize(), KernelDensityEstimator(), KernelDensityEstimator(), sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimX(), and sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimXs().
initialize() [2/2]
void sgpp::datadriven::KernelDensityEstimator::initialize (std::vector< std::shared_ptr< base::DataVector > > & samplesVec)
References sgpp::base::DataVector::setAll().
initializeKernel()
void sgpp::datadriven::KernelDensityEstimator::initializeKernel (KernelType kernelType)
References sgpp::datadriven::EPANECHNIKOV, and sgpp::datadriven::GAUSSIAN.
Referenced by KernelDensityEstimator(), KernelDensityEstimator(), KernelDensityEstimator(), and KernelDensityEstimator().
marginalize()
KernelDensityEstimator * sgpp::datadriven::KernelDensityEstimator::marginalize (size_t idim)
References sgpp::op_factory::createOperationDensityMarginalizeKDE().
margToDimX()
KernelDensityEstimator * sgpp::datadriven::KernelDensityEstimator::margToDimX (size_t idim)
References sgpp::op_factory::createOperationDensityMarginalizeKDE().
mean()
double sgpp::datadriven::KernelDensityEstimator::mean () override virtual
Implements sgpp::datadriven::DensityEstimator.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), cov(), python.uq.dists.LibAGFDist.LibAGFDist::var(), python.uq.dists.SGDEdist.SGDEdist::var(), and variance().
pdf() [1/2]
void sgpp::datadriven::KernelDensityEstimator::pdf (base::DataMatrix & points, base::DataVector & res) override virtual
Implements sgpp::datadriven::DensityEstimator.
References pdf(), and sgpp::base::DataVector::setAll().
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
pdf() [2/2]
double sgpp::datadriven::KernelDensityEstimator::pdf (base::DataVector & x) override virtual
Implements sgpp::datadriven::DensityEstimator.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), python.uq.dists.Dist.Dist::l2error(), and pdf().
setBandwidths()
void sgpp::datadriven::KernelDensityEstimator::setBandwidths (const base::DataVector & sigma)
References sgpp::base::DataVector::getSize().
Referenced by sgpp::datadriven::KDEMaximumLikelihoodCrossValidation::eval().
setConditionalizationFactor()
void sgpp::datadriven::KernelDensityEstimator::setConditionalizationFactor (base::DataVector & pcond)
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), and sgpp::datadriven::OperationDensityConditionalKDE::doConditional().
updateConditionalizationFactors()
void sgpp::datadriven::KernelDensityEstimator::updateConditionalizationFactors (base::DataVector & x, std::vector< size_t > & dims, base::DataVector & pcond)
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), and sgpp::datadriven::OperationDensityConditionalKDE::doConditional().
variance()
double sgpp::datadriven::KernelDensityEstimator::variance () override virtual
Implements sgpp::datadriven::DensityEstimator.
References mean(), and mu.
Referenced by cov().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp