SG++-Doxygen-Documentation: sgpp::base::ScreenOutput Class Reference
sgpp::base::ScreenOutput Class Reference
This is used to implement the output on the command line.
#include <ScreenOutput.hpp>
Public Member Functions
ScreenOutput ()
Standard constructor.
void update (size_t progress, std::string status)
update function running windows
void writeEmptyLines (size_t numLines)
writes empty lines
void writeHelp (std::string helpText)
writes some help information to the console
void writeStartSolve (std::string text)
start the screen output
void writeTitle (std::string appTitle, std::string appAuthor)
writes the header of the screen output
~ScreenOutput ()
Standard destructor.
Detailed Description
This is used to implement the output on the command line.
Constructor & Destructor Documentation
ScreenOutput()
sgpp::base::ScreenOutput::ScreenOutput ()
Standard constructor.
~ScreenOutput()
sgpp::base::ScreenOutput::~ScreenOutput ()
Standard destructor.
Member Function Documentation
update()
void sgpp::base::ScreenOutput::update (size_t progress, std::string status)
update function running windows
Parameters
progress percentage value
status status in words
Referenced by python.uq.refinement.RefinementStrategy.Ranking::rank(), python.learner.LearnedKnowledge.LearnedKnowledge::setMemento(), sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), sgpp::solver::Euler::solve(), and sgpp::solver::StepsizeControl::solve().
writeEmptyLines()
void sgpp::base::ScreenOutput::writeEmptyLines (size_t numLines)
writes empty lines
Parameters
numLines number of empty lines to display
Referenced by sgpp::solver::AdamsBashforth::solve(), sgpp::solver::CrankNicolson::solve(), sgpp::solver::Euler::solve(), sgpp::solver::StepsizeControl::solve(), sgpp::pde::HeatEquationSolver::solveCrankNicolson(), sgpp::pde::HeatEquationSolverWithStretching::solveCrankNicolson(), sgpp::pde::HeatEquationSolver::solveExplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveExplicitEuler(), sgpp::pde::HeatEquationSolver::solveImplicitEuler(), and sgpp::pde::HeatEquationSolverWithStretching::solveImplicitEuler().
writeHelp()
void sgpp::base::ScreenOutput::writeHelp (std::string helpText)
writes some help information to the console
Parameters
helpText the helptext to be displayed
writeStartSolve()
void sgpp::base::ScreenOutput::writeStartSolve (std::string text)
start the screen output
Parameters
text the start text to be displayed
Referenced by sgpp::pde::HeatEquationSolver::solveCrankNicolson(), sgpp::pde::HeatEquationSolverWithStretching::solveCrankNicolson(), sgpp::pde::HeatEquationSolver::solveExplicitEuler(), sgpp::pde::HeatEquationSolverWithStretching::solveExplicitEuler(), sgpp::pde::HeatEquationSolver::solveImplicitEuler(), and sgpp::pde::HeatEquationSolverWithStretching::solveImplicitEuler().
writeTitle()
void sgpp::base::ScreenOutput::writeTitle (std::string appTitle, std::string appAuthor)
writes the header of the screen output
Parameters
appTitle the application's title
appAuthor the application's author
Referenced by sgpp::pde::HeatEquationSolver::initScreen(), sgpp::pde::HeatEquationSolverWithStretching::initScreen(), and sgpp::pde::PoissonEquationSolver::initScreen().
The documentation for this class was generated from the following files:
base/src/sgpp/base/application/ScreenOutput.hpp
base/src/sgpp/base/application/ScreenOutput.cpp