SG++-Doxygen-Documentation: sgpp::datadriven::FitterConfigurationDensityEstimation Class Reference
sgpp::datadriven::FitterConfigurationDensityEstimation Class Reference
Configuration for fitter scenarios using density estimation.
#include <FitterConfigurationDensityEstimation.hpp>
Public Member Functions
FitterConfiguration * clone () const override
Polymorphic clone pattern.
FitterConfigurationDensityEstimation ()=default
void readParams (const DataMiningConfigParser &parser) override
First setup default values, then read new input values from configuration file.
void setupDefaults () override
set default values for all members based on the desired scenario.
Public Member Functions inherited from sgpp::datadriven::FitterConfiguration
void dumpToStream (std::ostream &stream_out=std::cout) const
print out all parameters to stream
FitterConfiguration ()=default
Sets up a Fitter configuration with its default values.
FitterConfiguration (const FitterConfiguration &rhs)=default
Copy constructor.
FitterConfiguration (FitterConfiguration &&rhs)=default
Move constructor.
datadriven::CrossvalidationConfiguration & getCrossvalidationConfig ()
Get or set how the crossvalidation should behave.
const datadriven::CrossvalidationConfiguration & getCrossvalidationConfig () const
Get how the crossvalidation should behave.
const datadriven::DatabaseConfiguration & getDatabaseConfig () const
Returns the database configuration, i.e.
datadriven::DensityEstimationConfiguration & getDensityEstimationConfig ()
Get or set how the density estimation should behave.
const datadriven::DensityEstimationConfiguration & getDensityEstimationConfig () const
Get how the density estimation should behave.
const datadriven::GeometryConfiguration & getGeometryConfig () const
base::GeneralGridConfiguration & getGridConfig ()
Get or set initial conditions for the grid before adaptive refinement.
const base::GeneralGridConfiguration & getGridConfig () const
Get initial conditions for the grid before adaptive refinement.
const datadriven::LearnerConfiguration & getLearnerConfig () const
Returns the configuration for the learner's behaviour.
datadriven::OperationMultipleEvalConfiguration & getMultipleEvalConfig ()
Get or set implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
const datadriven::OperationMultipleEvalConfiguration & getMultipleEvalConfig () const
Get implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
const datadriven::ParallelConfiguration & getParallelConfig () const
Returns the configuration for parallelization with ScaLAPACK.
base::AdaptivityConfiguration & getRefinementConfig ()
Get or set how the adaptivity algorithms for the grid should behave.
const base::AdaptivityConfiguration & getRefinementConfig () const
Get how the adaptivity algorithms for the grid should behave.
datadriven::RegularizationConfiguration & getRegularizationConfig ()
Get or set the type of regularization operation to use.
const datadriven::RegularizationConfiguration & getRegularizationConfig () const
Get the type of regularization operation to use.
solver::SLESolverConfiguration & getSolverFinalConfig ()
Get or set configuration for the linear system solver when solving the final, refined system.
const solver::SLESolverConfiguration & getSolverFinalConfig () const
Get configuration for the linear system solver when solving the final, refined system.
solver::SLESolverConfiguration & getSolverRefineConfig ()
Get or set configuration for the linear system solver which should be used while building adaptive grids.
const solver::SLESolverConfiguration & getSolverRefineConfig () const
Get configuration for the linear system solver which should be used while building adaptive grids.
FitterConfiguration & operator= (const FitterConfiguration &rhs)=default
Copy assign operator.
FitterConfiguration & operator= (FitterConfiguration &&rhs)=default
Move assign operator.
virtual ~FitterConfiguration ()=default
virtual destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::FitterConfiguration
base::AdaptivityConfiguration adaptivityConfig
Configure how the adaptivity algorithms for the grid should behave.
datadriven::CrossvalidationConfiguration crossvalidationConfig
Configure how the crossvalidation should behave.
datadriven::DatabaseConfiguration databaseConfig
Configure where the lhs datamatrix decomposition database is stored.
datadriven::DensityEstimationConfiguration densityEstimationConfig
Configure how the density estimation should behave.
datadriven::GeometryConfiguration geometryConfig
base::GeneralGridConfiguration gridConfig
Initial conditions for the grid before adaptive refinement.
datadriven::LearnerConfiguration learnerConfig
Configuration for the learner's behaviour.
datadriven::OperationMultipleEvalConfiguration multipleEvalConfig
Determine implementation (openMP, MPI, GPU) that should be used for sgpp::base::OperationMultipleEval.
datadriven::ParallelConfiguration parallelConfig
Configuration for parallelization with ScaLAPACK.
datadriven::RegularizationConfiguration regularizationConfig
Set the type of regularization operation to use and specify the influence of the regularization term vs data term from 0 (no regularization) to 1 (no data term).
solver::SLESolverConfiguration solverFinalConfig
Configuration for the linear system solver when solving the final, refined system.
solver::SLESolverConfiguration solverRefineConfig
Configuration for the linear system solver which should be used while building adaptive grids.
Detailed Description
Configuration for fitter scenarios using density estimation.
Constructor & Destructor Documentation
FitterConfigurationDensityEstimation()
sgpp::datadriven::FitterConfigurationDensityEstimation::FitterConfigurationDensityEstimation () default
Referenced by clone().
Member Function Documentation
clone()
FitterConfiguration * sgpp::datadriven::FitterConfigurationDensityEstimation::clone () const override virtual
Polymorphic clone pattern.
Returns
deep copy of this object. New object is owned by caller.
Implements sgpp::datadriven::FitterConfiguration.
References FitterConfigurationDensityEstimation().
readParams()
void sgpp::datadriven::FitterConfigurationDensityEstimation::readParams (const DataMiningConfigParser & parser) override virtual
First setup default values, then read new input values from configuration file.
Parameters
parser the parsed configuration file.
Implements sgpp::datadriven::FitterConfiguration.
References sgpp::datadriven::FitterConfiguration::adaptivityConfig, sgpp::datadriven::FitterConfiguration::databaseConfig, sgpp::datadriven::FitterConfiguration::densityEstimationConfig, sgpp::datadriven::FitterConfiguration::geometryConfig, sgpp::datadriven::FitterConfiguration::gridConfig, sgpp::datadriven::FitterConfiguration::learnerConfig, sgpp::datadriven::FitterConfiguration::parallelConfig, sgpp::datadriven::FitterConfiguration::regularizationConfig, setupDefaults(), sgpp::datadriven::FitterConfiguration::solverFinalConfig, and sgpp::datadriven::FitterConfiguration::solverRefineConfig.
Referenced by sgpp::datadriven::ClassificationFitterFactory::ClassificationFitterFactory(), sgpp::datadriven::DensityEstimationFitterFactory::DensityEstimationFitterFactory(), and main().
setupDefaults()
void sgpp::datadriven::FitterConfigurationDensityEstimation::setupDefaults () override virtual
set default values for all members based on the desired scenario.
Reimplemented from sgpp::datadriven::FitterConfiguration.
References sgpp::datadriven::FitterConfiguration::setupDefaults().
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::addNewModel(), sgpp::datadriven::ModelFittingDensityEstimationCombi::fit(), readParams(), and sgpp::datadriven::FitterConfigurationClassification::setupDefaults().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfigurationDensityEstimation.hpp
datadriven/src/sgpp/datadriven/datamining/modules/fitting/FitterConfigurationDensityEstimation.cpp