SG++-Doxygen-Documentation: sgpp::datadriven::OperationInverseRosenblattTransformationKDE Class Reference
sgpp::datadriven::OperationInverseRosenblattTransformationKDE Class Reference
Do inverse transformation in all dimensions.
#include <OperationInverseRosenblattTransformationKDE.hpp>
Public Member Functions
virtual void doShuffledTransformation (base::DataMatrix &pointsUniform, base::DataMatrix &pointsCdf)
virtual void doTransformation (base::DataMatrix &pointsUniform, base::DataMatrix &pointsCdf)
inverse Rosenblatt Transformation with mixed starting dimension
double doTransformation1D (double y, base::DataVector &samples1d, double sigma, double xlower, double xupper, double ylower, double yupper, base::DataVector &kern)
do the inverse Rosenblatt transformation for one data point for given samples
double getMaxInversionError ()
get the maximum error made during inversion
OperationInverseRosenblattTransformationKDE (datadriven::KernelDensityEstimator &kde, double sigmaFactor=6.0, double inversionEpsilon=1e-10, std::uint64_t seed=std::mt19937_64::default_seed)
virtual ~OperationInverseRosenblattTransformationKDE ()
Detailed Description
Do inverse transformation in all dimensions.
Constructor & Destructor Documentation
OperationInverseRosenblattTransformationKDE()
sgpp::datadriven::OperationInverseRosenblattTransformationKDE::OperationInverseRosenblattTransformationKDE (datadriven::KernelDensityEstimator & kde, double sigmaFactor = 6.0, double inversionEpsilon = 1e-10, std::uint64_t seed = std::mt19937_64::default_seed)
References sgpp::datadriven::KernelDensityEstimator::getBandwidths(), sgpp::datadriven::KernelDensityEstimator::getDim(), and sgpp::datadriven::KernelDensityEstimator::getNsamples().
~OperationInverseRosenblattTransformationKDE()
sgpp::datadriven::OperationInverseRosenblattTransformationKDE::~OperationInverseRosenblattTransformationKDE () virtual
Member Function Documentation
doShuffledTransformation()
void sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doShuffledTransformation (base::DataMatrix & pointsUniform, base::DataMatrix & pointsCdf) virtual
References doTransformation1D(), sgpp::datadriven::Kernel::eval(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::datadriven::KernelDensityEstimator::getDim(), sgpp::datadriven::KernelDensityEstimator::getKernel(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::datadriven::KernelDensityEstimator::getSamples(), and sgpp::base::DataMatrix::setRow().
doTransformation()
void sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation (base::DataMatrix & pointsUniform, base::DataMatrix & pointsCdf) virtual
inverse Rosenblatt Transformation with mixed starting dimension
Parameters
pointsUniform data points to be transformed DataMatrix (rows: # of samples, columns: # of dims)
pointsCdf Output DataMatrix (rows: # of samples, columns: # of dims)
References doTransformation1D(), sgpp::datadriven::Kernel::eval(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::datadriven::KernelDensityEstimator::getKernel(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::datadriven::KernelDensityEstimator::getSamples(), and sgpp::base::DataMatrix::setRow().
doTransformation1D()
double sgpp::datadriven::OperationInverseRosenblattTransformationKDE::doTransformation1D (double y, base::DataVector & samples1d, double sigma, double xlower, double xupper, double ylower, double yupper, base::DataVector & kern)
do the inverse Rosenblatt transformation for one data point for given samples
Parameters
y data point to be inverted
samples1d training samples in the dimension to be transformed
sigma bandwidth of the kernels in the current dimension
xlower lower bound for x-space
xupper upper bound for x-space
ylower lower bound for y-space
yupper upper bound for y-space
kern kernel evaluations
Returns
error of inversion
References sgpp::base::DataVector::getSize().
Referenced by doShuffledTransformation(), and doTransformation().
getMaxInversionError()
double sgpp::datadriven::OperationInverseRosenblattTransformationKDE::getMaxInversionError ()
get the maximum error made during inversion
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationInverseRosenblattTransformationKDE.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationInverseRosenblattTransformationKDE.cpp