SG++-Doxygen-Documentation: sgpp::datadriven::DBMatObjectStore Class Reference
sgpp::datadriven::DBMatObjectStore Class Reference
#include <DBMatObjectStore.hpp>
Classes
class ObjectContainer
Datastructure to store offline objects together with their configuration.
Public Member Functions
DBMatObjectStore ()
Default constructor.
DBMatObjectStore (const std::string &fileName)
Constructor with path to database file.
const DBMatOfflinePermutable * getBaseObject (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig, sgpp::base::GeneralGridConfiguration &baseGridConfig)
Returns a suitable base object for the permutation and blow-up approach.
const DBMatOffline * getObject (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig)
Returns an identical offline object to the specified configuration.
void putObject (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig, const DBMatOffline *object)
Stores a given offline object together with its configuration in the object store.
Protected Member Functions
const ObjectContainer & getObjectContainer (size_t index) const
Returns the object container for the given index.
size_t getObjectContainerIndex (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::datadriven::GeometryConfiguration &geometryConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig, bool searchBase=false)
Returns the index to a suitable offline object.
Protected Attributes
std::string dbFilePath
bool hasDatabase
std::vector< ObjectContainer > objects
Constructor & Destructor Documentation
DBMatObjectStore() [1/2]
sgpp::datadriven::DBMatObjectStore::DBMatObjectStore ()
Default constructor.
DBMatObjectStore() [2/2]
sgpp::datadriven::DBMatObjectStore::DBMatObjectStore (const std::string & fileName) explicit
Constructor with path to database file.
Parameters
fileName
Member Function Documentation
getBaseObject()
const DBMatOfflinePermutable * sgpp::datadriven::DBMatObjectStore::getBaseObject (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig, sgpp::base::GeneralGridConfiguration & baseGridConfig)
Returns a suitable base object for the permutation and blow-up approach.
The grid configuration of the stored base object is returned in baseGridConfig. If no suitable base object exists, a nullptr is returned.
Parameters
gridConfig Grid configuration of the desired offline object
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
baseGridConfig Reference to a grid configuration. Gets overridden by the grid configuration of the returned base object
Returns
const DBMatOfflinePermutable*
References adaptivityConfig, sgpp::datadriven::DBMatObjectStore::ObjectContainer::getGridConfig(), getObjectContainer(), getObjectContainerIndex(), and sgpp::datadriven::DBMatObjectStore::ObjectContainer::getOfflineObject().
getObject()
const DBMatOffline * sgpp::datadriven::DBMatObjectStore::getObject (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig)
Returns an identical offline object to the specified configuration.
If no such object exits, a nullptr is returned
Parameters
gridConfig Grid configuration
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
Returns
const DBMatOffline*
References adaptivityConfig, getObjectContainer(), getObjectContainerIndex(), and sgpp::datadriven::DBMatObjectStore::ObjectContainer::getOfflineObject().
getObjectContainer()
const DBMatObjectStore::ObjectContainer & sgpp::datadriven::DBMatObjectStore::getObjectContainer (size_t index) const protected
Returns the object container for the given index.
Parameters
index Index of the object container
Returns
const ObjectContainer&
References objects.
Referenced by getBaseObject(), and getObject().
getObjectContainerIndex()
size_t sgpp::datadriven::DBMatObjectStore::getObjectContainerIndex (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig, bool searchBase = false) protected
Returns the index to a suitable offline object.
If searchBase = true, a suitable base object for the permutation and blow-up approach is searched for. If no suitable object exists, SIZE_MAX is returned.
Parameters
gridConfig Grid configuration
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
searchBase Flag to specify whether an identical offline object or a suitable base object is to be searched
Returns
int
References adaptivityConfig, and objects.
Referenced by getBaseObject(), and getObject().
putObject()
void sgpp::datadriven::DBMatObjectStore::putObject (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::datadriven::GeometryConfiguration & geometryConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig, const DBMatOffline * object)
Stores a given offline object together with its configuration in the object store.
Parameters
gridConfig Grid configuration
geometryConfig Geometry configuration for geometry aware sparse grids
adaptivityConfig Adaptivity configuration
regularizationConfig Regularization configuration
densityEstimationConfig Density estimation configuration
object The object to be stored
References adaptivityConfig, and objects.
Member Data Documentation
dbFilePath
std::string sgpp::datadriven::DBMatObjectStore::dbFilePath protected
hasDatabase
bool sgpp::datadriven::DBMatObjectStore::hasDatabase protected
objects
std::vector<ObjectContainer> sgpp::datadriven::DBMatObjectStore::objects protected
Referenced by getObjectContainer(), getObjectContainerIndex(), and putObject().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatObjectStore.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatObjectStore.cpp