SG++-Doxygen-Documentation: sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary Class Reference
sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary Class Reference
Quadrature on sparse grid, polynomial grid without boundaries.
#include <OperationQuadraturePolyClenshawCurtisBoundary.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for piecewise polynomial basis functions of max.
OperationQuadraturePolyClenshawCurtisBoundary (GridStorage &storage, size_t degree)
Constructor of OperationQuadraturePolyClenshawCurtisBoundary.
~OperationQuadraturePolyClenshawCurtisBoundary () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SPolyClenshawCurtisBoundaryBase base
Poly Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, polynomial grid without boundaries.
Constructor & Destructor Documentation
OperationQuadraturePolyClenshawCurtisBoundary()
sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::OperationQuadraturePolyClenshawCurtisBoundary (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadraturePolyClenshawCurtisBoundary.
Parameters
storage Pointer to the grid's GridStorage object
degree the polynom's max. degree
~OperationQuadraturePolyClenshawCurtisBoundary()
sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::~OperationQuadraturePolyClenshawCurtisBoundary () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::doQuadrature (DataVector & alpha) override virtual
Quadrature for piecewise polynomial basis functions of max.
degree 3
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SPolyClenshawCurtisBoundaryBase sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::base protected
Poly Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadraturePolyClenshawCurtisBoundary::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadraturePolyClenshawCurtisBoundary.hpp
base/src/sgpp/base/operation/hash/OperationQuadraturePolyClenshawCurtisBoundary.cpp