SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureModLinear Class Reference
sgpp::base::OperationQuadratureModLinear Class Reference
Quadrature on sparse grid, modified linear grid.
#include <OperationQuadratureModLinear.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for modified piecewise linear hat basis functions.
OperationQuadratureModLinear (GridStorage &storage)
Constructor of OperationQuadratureModLinear.
~OperationQuadratureModLinear () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SLinearModifiedBase base
ModLinear Basis object.
GridStorage & storage
Pointer to the grid's GridStorage object.
Detailed Description
Quadrature on sparse grid, modified linear grid.
Constructor & Destructor Documentation
OperationQuadratureModLinear()
sgpp::base::OperationQuadratureModLinear::OperationQuadratureModLinear (GridStorage & storage) inline explicit
Constructor of OperationQuadratureModLinear.
Parameters
storage Pointer to the grid's GridStorage object
~OperationQuadratureModLinear()
sgpp::base::OperationQuadratureModLinear::~OperationQuadratureModLinear () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureModLinear::doQuadrature (DataVector & alpha) override virtual
Quadrature for modified piecewise linear hat basis functions.
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::DataVector::get(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::BoundingBox::getIntervalWidth(), and storage.
Member Data Documentation
base
SLinearModifiedBase sgpp::base::OperationQuadratureModLinear::base protected
ModLinear Basis object.
storage
GridStorage& sgpp::base::OperationQuadratureModLinear::storage protected
Pointer to the grid's GridStorage object.
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureModLinear.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureModLinear.cpp