SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureLinearBoundary Class Reference
sgpp::base::OperationQuadratureLinearBoundary Class Reference
Quadrature on sparse grid, linear grid without boundaries.
#include <OperationQuadratureLinearBoundary.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for piecewise linear hat basis functions.
OperationQuadratureLinearBoundary (GridStorage &storage)
Constructor of OperationQuadratureLinear.
~OperationQuadratureLinearBoundary () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
GridStorage & storage
Detailed Description
Quadrature on sparse grid, linear grid without boundaries.
Constructor & Destructor Documentation
OperationQuadratureLinearBoundary()
sgpp::base::OperationQuadratureLinearBoundary::OperationQuadratureLinearBoundary (GridStorage & storage) inline explicit
Constructor of OperationQuadratureLinear.
Parameters
storage Pointer to the grid's GridStorage object
~OperationQuadratureLinearBoundary()
sgpp::base::OperationQuadratureLinearBoundary::~OperationQuadratureLinearBoundary () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureLinearBoundary::doQuadrature (DataVector & alpha) override virtual
Quadrature for piecewise linear hat basis functions.
Computes
\[ \sum_{\vec{l}} 2^{-|\vec{l}|}\alpha_{\vec{l}}. \]
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::DataVector::get(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::BoundingBox::getIntervalWidth(), and storage.
Member Data Documentation
storage
GridStorage& sgpp::base::OperationQuadratureLinearBoundary::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureLinearBoundary.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureLinearBoundary.cpp