SG++-Doxygen-Documentation: sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet Class Reference
sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet Class Reference
This class uses OperationEllipticPDESolverSystemDirichlet to define a solver system for the Poission Equation.
#include <PoissonEquationEllipticPDESolverSystemDirichlet.hpp>
Public Member Functions
PoissonEquationEllipticPDESolverSystemDirichlet (sgpp::base::Grid &SparseGrid, sgpp::base::DataVector &rhs)
Constructor.
virtual ~PoissonEquationEllipticPDESolverSystemDirichlet ()
Destructor.
Public Member Functions inherited from sgpp::pde::OperationEllipticPDESolverSystemDirichlet
virtual sgpp::base::DataVector * generateRHS ()
generates the right hand side of the system
virtual sgpp::base::DataVector * getGridCoefficientsForCG ()
gets a pointer to the sparse grids coefficients used in the CG method to solve one timestep.
virtual void getSolutionBoundGrid (sgpp::base::DataVector &Solution, sgpp::base::DataVector &SolutionInner)
Gets the solution for the complete grid.
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Multiplicates a vector with the matrix \(L \).
OperationEllipticPDESolverSystemDirichlet (sgpp::base::Grid &SparseGrid, sgpp::base::DataVector &rhs)
Constructor.
virtual ~OperationEllipticPDESolverSystemDirichlet ()
Destructor.
Public Member Functions inherited from sgpp::pde::OperationEllipticPDESolverSystem
size_t getNumGridPointsComplete ()
Returns the number of grid points for the complete grid.
size_t getNumGridPointsInner ()
Returns the number of grid points for the inner grid.
OperationEllipticPDESolverSystem (sgpp::base::Grid &SparseGrid, sgpp::base::DataVector &rhs)
Constructor.
virtual ~OperationEllipticPDESolverSystem ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
void applyLOperatorComplete (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's system matrix, on complete grid - with boundaries
void applyLOperatorInner (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
applies the PDE's system matrix, on inner grid only
Protected Attributes
sgpp::base::OperationMatrix * Laplace_Complete
sgpp::base::OperationMatrix * Laplace_Inner
Protected Attributes inherited from sgpp::pde::OperationEllipticPDESolverSystemDirichlet
sgpp::base::DataVector * alpha_inner
Pointer to the alphas (ansatzfunctions' coefficients; inner points only)
sgpp::base::DirichletUpdateVector * BoundaryUpdate
Routine to modify the boundaries/inner points of the grid.
sgpp::base::DirichletGridConverter * GridConverter
Class that allows a simple conversion between a grid with and a without boundary points.
sgpp::base::Grid * InnerGrid
Pointer to the inner grid object.
sgpp::base::DataVector * rhs_inner
rhs for the inner grid
Protected Attributes inherited from sgpp::pde::OperationEllipticPDESolverSystem
sgpp::base::Grid * BoundGrid
Pointer to the grid object.
size_t numGridpointsComplete
Stores number of gridpoints, complete grid.
size_t numGridpointsInner
Stores number of gridpoints, inner grid.
sgpp::base::DataVector * rhs
the right hand side of the system
Detailed Description
This class uses OperationEllipticPDESolverSystemDirichlet to define a solver system for the Poission Equation.
For the mult-routine only the Laplace-Operator is required
Constructor & Destructor Documentation
PoissonEquationEllipticPDESolverSystemDirichlet()
sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::PoissonEquationEllipticPDESolverSystemDirichlet (sgpp::base::Grid & SparseGrid, sgpp::base::DataVector & rhs)
Constructor.
Parameters
SparseGrid reference to a sparse grid on which the Poisson Equation should be solved
rhs the right hand side for solving the elliptic PDE
References sgpp::pde::OperationEllipticPDESolverSystem::BoundGrid, sgpp::op_factory::createOperationLaplace(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::InnerGrid, Laplace_Complete, and Laplace_Inner.
~PoissonEquationEllipticPDESolverSystemDirichlet()
sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::~PoissonEquationEllipticPDESolverSystemDirichlet () virtual
Destructor.
References Laplace_Complete, and Laplace_Inner.
Member Function Documentation
applyLOperatorComplete()
void sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::applyLOperatorComplete (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's system matrix, on complete grid - with boundaries
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
Implements sgpp::pde::OperationEllipticPDESolverSystemDirichlet.
References alpha, Laplace_Complete, and sgpp::base::OperationMatrix::mult().
applyLOperatorInner()
void sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::applyLOperatorInner (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) protected virtual
applies the PDE's system matrix, on inner grid only
Parameters
alpha the coefficients of the sparse grid's ansatzfunctions
result reference to the sgpp::base::DataVector into which the result is written
Implements sgpp::pde::OperationEllipticPDESolverSystemDirichlet.
References alpha, Laplace_Inner, and sgpp::base::OperationMatrix::mult().
Member Data Documentation
Laplace_Complete
sgpp::base::OperationMatrix* sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::Laplace_Complete protected
Referenced by applyLOperatorComplete(), PoissonEquationEllipticPDESolverSystemDirichlet(), and ~PoissonEquationEllipticPDESolverSystemDirichlet().
Laplace_Inner
sgpp::base::OperationMatrix* sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::Laplace_Inner protected
Referenced by applyLOperatorInner(), PoissonEquationEllipticPDESolverSystemDirichlet(), and ~PoissonEquationEllipticPDESolverSystemDirichlet().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/algorithm/PoissonEquationEllipticPDESolverSystemDirichlet.hpp
pde/src/sgpp/pde/algorithm/PoissonEquationEllipticPDESolverSystemDirichlet.cpp