SG++-Doxygen-Documentation: sgpp::base::PolyClenshawCurtisBasis< LT, IT > Class Template Reference
sgpp::base::PolyClenshawCurtisBasis< LT, IT > Class Template Reference
Polynomial basis functions.
#include <PolyClenshawCurtisBasis.hpp>
Public Member Functions
double eval (LT level, IT index, double p) override
Evaluate the basis function with given level and index.
double evalBasis (LT level, IT index, double p)
Evaluate a basis function.
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
double evalHierToTop (LT level, IT index, DataVector &coeffs, double pos)
Evaluates all the hierarchical ancestors of the node defined by level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
PolyClenshawCurtisBasis (size_t degree)
Constructor.
~PolyClenshawCurtisBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
ClenshawCurtisTable & clenshawCurtisTable
reference to the Clenshaw-Curtis cache table
size_t degree
the polynom's max degree
std::vector< int > idxtable
Detailed Description
template<class LT, class IT>
class sgpp::base::PolyClenshawCurtisBasis< LT, IT >
Polynomial basis functions.
Version
$HEAD$
Constructor & Destructor Documentation
PolyClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::PolyClenshawCurtisBasis< LT, IT >::PolyClenshawCurtisBasis (size_t degree) inline explicit
Constructor.
Parameters
degree the polynom's max. degree
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree, and sgpp::base::PolyClenshawCurtisBasis< LT, IT >::idxtable.
~PolyClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::PolyClenshawCurtisBasis< LT, IT >::~PolyClenshawCurtisBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval (LT level, IT index, double x) inline override virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::ClenshawCurtisTable::getPoint(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::OperationEvalPolyClenshawCurtisNaive::eval(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalHierToTop(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), and sgpp::base::OperationMultipleEvalPolyClenshawCurtisNaive::multTranspose().
evalBasis()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis (LT level, IT index, double p) inline
Evaluate a basis function.
Has a dependence on the absolute position of grid point and support.
We compute the roots in units of h = grid spacing at level l = 2 ** -l.
Due to limited polynomial degree, we compute the roots of the Lagrange polynomial bottom up.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::idxtable, level, and sgpp::base::HashGridPoint::setAsHierarchicalGridPoint().
Referenced by sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval().
evalDx()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::ClenshawCurtisTable::getPoint(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::idxtable, level, and sgpp::base::HashGridPoint::setAsHierarchicalGridPoint().
Referenced by sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::evalDx(), and sgpp::pde::OperationLaplacePolyClenshawCurtis::mult().
evalHierToTop()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalHierToTop (LT level, IT index, DataVector & coeffs, double pos) inline
Evaluates all the hierarchical ancestors of the node defined by level and index.
NOTE: It does not evaluate the current node itself.
Parameters
level
index
coeffs
pos
Returns
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), and level.
Referenced by sgpp::base::DehierarchisationPolyClenshawCurtis::rec(), and sgpp::base::HierarchisationPolyClenshawCurtis::rec().
getDegree()
template<class LT , class IT > size_t sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree.
Referenced by sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getDegree(), and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getDegree().
getIntegral()
template<class LT , class IT > double sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::PolyClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree, sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::QuadRule1D::getLevelPointsAndWeights(), sgpp::base::ClenshawCurtisTable::getPoint(), h, and level.
Referenced by sgpp::base::OperationQuadraturePolyClenshawCurtis::doQuadrature(), sgpp::base::PolyClenshawCurtisBoundaryBasis< LT, IT >::getIntegral(), and sgpp::base::PolyModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
Member Data Documentation
clenshawCurtisTable
template<class LT , class IT > ClenshawCurtisTable& sgpp::base::PolyClenshawCurtisBasis< LT, IT >::clenshawCurtisTable protected
reference to the Clenshaw-Curtis cache table
Referenced by sgpp::base::PolyClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), and sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral().
degree
template<class LT , class IT > size_t sgpp::base::PolyClenshawCurtisBasis< LT, IT >::degree protected
the polynom's max degree
Referenced by sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getDegree(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::getIntegral(), and sgpp::base::PolyClenshawCurtisBasis< LT, IT >::PolyClenshawCurtisBasis().
idxtable
template<class LT , class IT > std::vector<int> sgpp::base::PolyClenshawCurtisBasis< LT, IT >::idxtable protected
Referenced by sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalBasis(), sgpp::base::PolyClenshawCurtisBasis< LT, IT >::evalDx(), and sgpp::base::PolyClenshawCurtisBasis< LT, IT >::PolyClenshawCurtisBasis().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/PolyClenshawCurtisBasis.hpp