SG++-Doxygen-Documentation: sgpp::datadriven::ClassificationLearner Class Reference
sgpp::datadriven::ClassificationLearner Class Reference
The ClassificationLearner class Solves a classification problem.
#include <ClassificationLearner.hpp>
Public Member Functions
ClassificationLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, sgpp::datadriven::RegularizationConfiguration regularizationConfig)
ClassificationLearner.
ClassificationLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, sgpp::datadriven::RegularizationConfiguration regularizationConfig, std::set< std::set< size_t > > terms)
ClassificationLearner.
double getAccuracy (sgpp::base::DataMatrix &data, const sgpp::base::DataVector &y)
getAccuracy
size_t getGridSize () const
getGridSize
sgpp::base::DataVector predict (sgpp::base::DataMatrix &data)
predict
std::pair< sgpp::base::DataVector, sgpp::base::DataVector > predictWithCertainty (sgpp::base::DataMatrix &data)
predict
void train (sgpp::base::DataMatrix &trainDataset, sgpp::base::DataVector &classes)
train fits a sparse grid regression model.
Detailed Description
The ClassificationLearner class Solves a classification problem.
Constructor & Destructor Documentation
ClassificationLearner() [1/2]
sgpp::datadriven::ClassificationLearner::ClassificationLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, sgpp::datadriven::RegularizationConfiguration regularizationConfig, std::set< std::set< size_t > > terms)
ClassificationLearner.
Parameters
gridConfig
adaptivityConfig
solverConfig is the solver used during each adaptivity step
finalSolverConfig is the solver used to build the final model
regularizationConfig
terms is a vector that contains all desired interaction terms. For example, if we want to include grid points that model an interaction between the first and the second predictor, we would include the vector [1,2] in terms.
ClassificationLearner() [2/2]
sgpp::datadriven::ClassificationLearner::ClassificationLearner (sgpp::base::RegularGridConfiguration gridConfig, sgpp::base::AdaptivityConfiguration adaptivityConfig, sgpp::solver::SLESolverConfiguration solverConfig, sgpp::solver::SLESolverConfiguration finalSolverConfig, sgpp::datadriven::RegularizationConfiguration regularizationConfig)
ClassificationLearner.
Parameters
gridConfig
adaptivityConfig
solverConfig is the solver used during each adaptivity step
finalSolverConfig is the solver used to build the final model
regularizationConfig
Member Function Documentation
getAccuracy()
double sgpp::datadriven::ClassificationLearner::getAccuracy (sgpp::base::DataMatrix & data, const sgpp::base::DataVector & y)
getAccuracy
Parameters
data is the design matrix
y is the target
Returns
the accuracy of the prediction of the model for the matrix data
References getAccuracy(), and predict().
Referenced by getAccuracy().
getGridSize()
size_t sgpp::datadriven::ClassificationLearner::getGridSize () const
getGridSize
Returns
the grid size
Referenced by python.learner.TrainingStopPolicy.TrainingStopPolicy::hasGridSizeChanged(), and python.learner.TrainingStopPolicy.TrainingStopPolicy::isTrainingComplete().
predict()
sgpp::base::DataVector sgpp::datadriven::ClassificationLearner::predict (sgpp::base::DataMatrix & data)
predict
Parameters
data are observations
Returns
the predicted target for matrix data
Referenced by getAccuracy().
predictWithCertainty()
std::pair< sgpp::base::DataVector, sgpp::base::DataVector > sgpp::datadriven::ClassificationLearner::predictWithCertainty (sgpp::base::DataMatrix & data)
predict
Parameters
data are observations
Returns
the predicted target for matrix data and the certainty of the model, that the observation belongs to the predicted class.
train()
void sgpp::datadriven::ClassificationLearner::train (sgpp::base::DataMatrix & trainDataset, sgpp::base::DataVector & classes)
train fits a sparse grid regression model.
Parameters
trainDataset is the design matrix
classes is the (continuous) target
References sgpp::base::DataVector::getSize().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/ClassificationLearner.hpp
datadriven/src/sgpp/datadriven/application/ClassificationLearner.cpp