SG++-Doxygen-Documentation: python.uq.refinement.RefinementStrategy.SurplusRanking Class Reference
python.uq.refinement.RefinementStrategy.SurplusRanking Class Reference
Public Member Functions
__init__ (self)
update (self, grid, v, gpi, *args, **kws)
Public Member Functions inherited from python.uq.refinement.RefinementStrategy.Ranking
getKnowledgeType (self)
rank (self, grid, gp, alphas, params, t=0, *args, **kws)
Additional Inherited Members
Protected Attributes inherited from python.uq.refinement.RefinementStrategy.Ranking
_dtype
_ranking
Constructor & Destructor Documentation
__init__()
python.uq.refinement.RefinementStrategy.SurplusRanking.__init__ (self)
Reimplemented from python.uq.refinement.RefinementStrategy.Ranking.
References python.uq.refinement.RefinementStrategy.SurplusRanking.__init__().
Referenced by python.uq.refinement.RefinementStrategy.SurplusRanking.__init__().
Member Function Documentation
update()
python.uq.refinement.RefinementStrategy.SurplusRanking.update (self, grid, v, gpi, * args, ** kws)
Reimplemented from python.uq.refinement.RefinementStrategy.Ranking.
Referenced by python.uq.refinement.RefinementStrategy.Ranking.rank(), and python.learner.LearnedKnowledge.LearnedKnowledge.setMemento().
The documentation for this class was generated from the following file:
datadriven/python/uq/refinement/RefinementStrategy.py