SG++-Doxygen-Documentation: sgpp::datadriven::SparseGridDensityEstimator Class Reference
sgpp::datadriven::SparseGridDensityEstimator Class Reference
#include <SparseGridDensityEstimator.hpp>
Public Member Functions
void cov (base::DataMatrix &cov, base::DataMatrix *bounds=nullptr) override
Computes the covariance of the density function.
size_t getDim () override
get number of dimensions
virtual base::Grid & getGrid ()
returns the grid
size_t getNsamples () override
get number of samples
std::shared_ptr< base::DataMatrix > getSamples () override
returns the complete sample set
std::shared_ptr< base::DataVector > getSamples (size_t dim) override
returns the samples in the given dimension
virtual base::DataVector & getSurpluses ()
returns the surpluses
void initialize (base::DataMatrix &samples) override
Estimate a sparse grid density based on the given data set and the specified configurations.
virtual sgpp::datadriven::SparseGridDensityEstimator * marginalize (size_t idim)
Marginalize the density in one dimension and return result.
virtual sgpp::datadriven::SparseGridDensityEstimator * margToDimX (size_t idim)
Compute marginal density.
double mean () override
This method computes the mean of the density function.
void pdf (base::DataMatrix &points, base::DataVector &res) override
Evaluation of the sparse grid density at a set of points.
double pdf (base::DataVector &x) override
This methods evaluates the sparse grid density at a single point.
SparseGridDensityEstimator (base::Grid &grid, base::DataVector &alpha, base::DataMatrix &samples)
construct learner from given grid and coefficients
SparseGridDensityEstimator (const SparseGridDensityEstimator &learnerSGDE)
SparseGridDensityEstimator (sgpp::base::RegularGridConfiguration &gridConfig, sgpp::base::AdaptivityConfiguration &adaptivityConfig, sgpp::solver::SLESolverConfiguration &solverConfig, sgpp::datadriven::RegularizationConfiguration &regularizationConfig, CrossvalidationForRegularizationConfiguration &crossvalidationConfig, SGDEConfiguration &sgdeConfig)
Constructor.
SparseGridDensityEstimator (SparseGridDensityEstimatorConfiguration &learnerSGDEConfig)
virtual void train (base::Grid &grid, base::DataVector &alpha, base::DataMatrix &train, double lambdaReg)
Does the learning step on a given grid, training set and regularization parameter lambda.
double variance () override
Computes the variance of the density function.
~SparseGridDensityEstimator () override
Public Member Functions inherited from sgpp::datadriven::DensityEstimator
virtual void corrcoef (base::DataMatrix &corr, base::DataMatrix *bounds=nullptr)
double crossEntropy (sgpp::base::DataMatrix &samples)
DensityEstimator ()
virtual double std_deviation ()
virtual ~DensityEstimator ()
Protected Member Functions
std::shared_ptr< datadriven::DensitySystemMatrix > computeDensitySystemMatrix (base::Grid &grid, base::DataMatrix &train, double lambdaReg)
generates the density system matrix
base::OperationMatrix * computeLTwoDotProductMatrix (base::Grid &grid)
generates the L^2 dot product matrix
base::OperationMultipleEval * computeMultipleEvalMatrix (base::Grid &grid, base::DataMatrix &train)
generates the MultipleEval matrix
base::OperationMatrix * computeRegularizationMatrix (base::Grid &grid)
generates the regularization matrix
double computeResidual (base::Grid &grid, base::DataVector &alpha, base::DataMatrix &test, double lambdaReg)
Compute the residual for a given test data set on a learned grid.
std::shared_ptr< base::Grid > createRegularGrid ()
generates a regular grid
double mean (base::Grid &grid, base::DataVector &alpha)
double optimizeLambdaCV ()
Does cross-validation to obtain a suitable regularization parameter.
void splitset (std::vector< std::shared_ptr< base::DataMatrix > > &strain, std::vector< std::shared_ptr< base::DataMatrix > > &stest)
splits the complete sample set in a set of smaller training and test samples for cross-validation.
double variance (base::Grid &grid, base::DataVector &alpha)
Protected Attributes
sgpp::base::AdaptivityConfiguration adaptivityConfig
std::shared_ptr< base::DataVector > alpha
CrossvalidationForRegularizationConfiguration crossvalidationConfig
std::shared_ptr< base::Grid > grid
sgpp::base::RegularGridConfiguration gridConfig
sgpp::datadriven::RegularizationConfiguration regularizationConfig
std::shared_ptr< base::DataMatrix > samples
SGDEConfiguration sgdeConfig
sgpp::solver::SLESolverConfiguration solverConfig
Constructor & Destructor Documentation
SparseGridDensityEstimator() [1/4]
sgpp::datadriven::SparseGridDensityEstimator::SparseGridDensityEstimator (sgpp::base::RegularGridConfiguration & gridConfig, sgpp::base::AdaptivityConfiguration & adaptivityConfig, sgpp::solver::SLESolverConfiguration & solverConfig, sgpp::datadriven::RegularizationConfiguration & regularizationConfig, CrossvalidationForRegularizationConfiguration & crossvalidationConfig, SGDEConfiguration & sgdeConfig)
Constructor.
Parameters
gridConfig grid configuration
adaptivityConfig adaptive refinement configuration
solverConfig solver configuration (CG)
regularizationConfig config for regularization operator
crossvalidationConfig configuration for the cross validation
sgdeConfig configuration for the sparse grid density estimation
SparseGridDensityEstimator() [2/4]
sgpp::datadriven::SparseGridDensityEstimator::SparseGridDensityEstimator (SparseGridDensityEstimatorConfiguration & learnerSGDEConfig) explicit
SparseGridDensityEstimator() [3/4]
sgpp::datadriven::SparseGridDensityEstimator::SparseGridDensityEstimator (base::Grid & grid, base::DataVector & alpha, base::DataMatrix & samples)
construct learner from given grid and coefficients
Parameters
grid
alpha
samples
References alpha, grid, and samples.
SparseGridDensityEstimator() [4/4]
sgpp::datadriven::SparseGridDensityEstimator::SparseGridDensityEstimator (const SparseGridDensityEstimator & learnerSGDE)
References adaptivityConfig, alpha, crossvalidationConfig, grid, gridConfig, regularizationConfig, samples, sgdeConfig, and solverConfig.
~SparseGridDensityEstimator()
sgpp::datadriven::SparseGridDensityEstimator::~SparseGridDensityEstimator () override
Member Function Documentation
computeDensitySystemMatrix()
std::shared_ptr< datadriven::DensitySystemMatrix > sgpp::datadriven::SparseGridDensityEstimator::computeDensitySystemMatrix (base::Grid & grid, base::DataMatrix & train, double lambdaReg) protected
generates the density system matrix
Parameters
grid grid
train train
lambdaReg regularization parameter
References computeLTwoDotProductMatrix(), computeMultipleEvalMatrix(), computeRegularizationMatrix(), grid, and train().
Referenced by computeResidual(), and train().
computeLTwoDotProductMatrix()
base::OperationMatrix * sgpp::datadriven::SparseGridDensityEstimator::computeLTwoDotProductMatrix (base::Grid & grid) protected
generates the L^2 dot product matrix
Parameters
grid grid
References sgpp::op_factory::createOperationLTwoDotProduct(), and grid.
Referenced by computeDensitySystemMatrix().
computeMultipleEvalMatrix()
base::OperationMultipleEval * sgpp::datadriven::SparseGridDensityEstimator::computeMultipleEvalMatrix (base::Grid & grid, base::DataMatrix & train) protected
generates the MultipleEval matrix
Parameters
grid grid
train training data
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::op_factory::createOperationMultipleEval(), sgpp::op_factory::createOperationMultipleEvalNaive(), grid, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPolyClenshawCurtis, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, and train().
Referenced by computeDensitySystemMatrix().
computeRegularizationMatrix()
base::OperationMatrix * sgpp::datadriven::SparseGridDensityEstimator::computeRegularizationMatrix (base::Grid & grid) protected
generates the regularization matrix
Parameters
grid grid
References sgpp::op_factory::createOperationIdentity(), sgpp::op_factory::createOperationLaplace(), grid, sgpp::datadriven::Identity, sgpp::datadriven::Laplace, regularizationConfig, and sgpp::datadriven::RegularizationConfiguration::type_.
Referenced by computeDensitySystemMatrix().
computeResidual()
double sgpp::datadriven::SparseGridDensityEstimator::computeResidual (base::Grid & grid, base::DataVector & alpha, base::DataMatrix & test, double lambdaReg) protected
Compute the residual for a given test data set on a learned grid.
$|(A - lambda C) alpha - 1/n B|$
This is used as quality criterion for the estimated density.
Parameters
grid grid
alpha coefficient vector
test test set
lambdaReg regularization parameter
Returns
References alpha, computeDensitySystemMatrix(), sgpp::base::DataVector::getSize(), grid, and sgpp::base::DataVector::l2Norm().
Referenced by optimizeLambdaCV().
cov()
void sgpp::datadriven::SparseGridDensityEstimator::cov (base::DataMatrix & cov, base::DataMatrix * bounds = nullptr) override virtual
Computes the covariance of the density function.
Implements sgpp::datadriven::DensityEstimator.
References alpha, cov(), sgpp::op_factory::createOperationCovariance(), and grid.
Referenced by python.uq.dists.Dist.Dist::corrcoeff(), and cov().
createRegularGrid()
std::shared_ptr< base::Grid > sgpp::datadriven::SparseGridDensityEstimator::createRegularGrid () protected
generates a regular grid
Returns
grid
References sgpp::base::Grid::createGrid(), gridConfig, and sgpp::base::GeneralGridConfiguration::level_.
Referenced by initialize(), and optimizeLambdaCV().
getDim()
size_t sgpp::datadriven::SparseGridDensityEstimator::getDim () override virtual
get number of dimensions
Implements sgpp::datadriven::DensityEstimator.
References sgpp::base::GeneralGridConfiguration::dim_, and gridConfig.
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.uq.dists.Dist.Dist::cov(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), and python.uq.uq_setting.UQSetting.UQSetting::getDim().
getGrid()
base::Grid & sgpp::datadriven::SparseGridDensityEstimator::getGrid () virtual
returns the grid
References grid.
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
getNsamples()
size_t sgpp::datadriven::SparseGridDensityEstimator::getNsamples () override virtual
get number of samples
Implements sgpp::datadriven::DensityEstimator.
References samples.
Referenced by getSamples(), and optimizeLambdaCV().
getSamples() [1/2]
std::shared_ptr< base::DataMatrix > sgpp::datadriven::SparseGridDensityEstimator::getSamples () override virtual
returns the complete sample set
Implements sgpp::datadriven::DensityEstimator.
References samples.
getSamples() [2/2]
std::shared_ptr< base::DataVector > sgpp::datadriven::SparseGridDensityEstimator::getSamples (size_t dim) override virtual
returns the samples in the given dimension
Parameters
dim
Implements sgpp::datadriven::DensityEstimator.
References getNsamples(), and samples.
getSurpluses()
base::DataVector & sgpp::datadriven::SparseGridDensityEstimator::getSurpluses () virtual
returns the surpluses
References alpha.
initialize()
void sgpp::datadriven::SparseGridDensityEstimator::initialize (base::DataMatrix & samples) override virtual
Estimate a sparse grid density based on the given data set and the specified configurations.
Parameters
samples DataMatrix (nrows = number of samples, ncols = dimensionality)
Implements sgpp::datadriven::DensityEstimator.
References alpha, sgpp::op_factory::createOperationMakePositive(), sgpp::op_factory::createOperationQuadrature(), createRegularGrid(), crossvalidationConfig, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::OperationQuadrature::doQuadrature(), sgpp::datadriven::CrossvalidationForRegularizationConfiguration::enable_, sgpp::base::DataMatrix::getNcols(), grid, gridConfig, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambda_, sgpp::datadriven::OperationMakePositive::makePositive(), sgpp::datadriven::SGDEConfiguration::makePositive_, sgpp::datadriven::SGDEConfiguration::makePositive_candidateSearchAlgorithm_, sgpp::datadriven::SGDEConfiguration::makePositive_generateConsistentGrid_, sgpp::datadriven::SGDEConfiguration::makePositive_interpolationAlgorithm_, optimizeLambdaCV(), samples, sgdeConfig, train(), and sgpp::datadriven::SGDEConfiguration::unitIntegrand_.
marginalize()
SparseGridDensityEstimator * sgpp::datadriven::SparseGridDensityEstimator::marginalize (size_t idim) virtual
Marginalize the density in one dimension and return result.
Parameters
idim dimension which should be marginalized
References alpha, sgpp::op_factory::createOperationDensityMarginalize(), grid, samples, and sgpp::base::DataMatrix::setColumn().
margToDimX()
SparseGridDensityEstimator * sgpp::datadriven::SparseGridDensityEstimator::margToDimX (size_t idim) virtual
Compute marginal density.
Parameters
idim dimension which should be left after marginalization
References alpha, sgpp::op_factory::createOperationDensityMargTo1D(), grid, samples, and sgpp::base::DataMatrix::setColumn().
mean() [1/2]
double sgpp::datadriven::SparseGridDensityEstimator::mean () override virtual
This method computes the mean of the density function.
Implements sgpp::datadriven::DensityEstimator.
References alpha, grid, and mean().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), mean(), python.uq.dists.LibAGFDist.LibAGFDist::var(), and python.uq.dists.SGDEdist.SGDEdist::var().
mean() [2/2]
double sgpp::datadriven::SparseGridDensityEstimator::mean (base::Grid & grid, base::DataVector & alpha) protected
References alpha, sgpp::op_factory::createOperationFirstMoment(), and grid.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::computeMoments(), python.uq.analysis.mc.MCAnalysis.MCAnalysis::computeMoments(), python.uq.dists.LibAGFDist.LibAGFDist::var(), and python.uq.dists.SGDEdist.SGDEdist::var().
optimizeLambdaCV()
double sgpp::datadriven::SparseGridDensityEstimator::optimizeLambdaCV () protected
Does cross-validation to obtain a suitable regularization parameter.
References alpha, computeResidual(), createRegularGrid(), crossvalidationConfig, getNsamples(), grid, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::kfold_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaEnd_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaStart_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::lambdaSteps_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::logScale_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::silent_, splitset(), and train().
Referenced by initialize().
pdf() [1/2]
void sgpp::datadriven::SparseGridDensityEstimator::pdf (base::DataMatrix & points, base::DataVector & res) override virtual
Evaluation of the sparse grid density at a set of points.
Parameters
points DataMatrix (nrows = number of samples, ncols = dimensionality)
res DataVector (size = number of samples) where the results are stored
Implements sgpp::datadriven::DensityEstimator.
References alpha, sgpp::op_factory::createOperationMultipleEval(), and grid.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
pdf() [2/2]
double sgpp::datadriven::SparseGridDensityEstimator::pdf (base::DataVector & x) override virtual
This methods evaluates the sparse grid density at a single point.
Parameters
x DataVector length equal to dimensionality
Implements sgpp::datadriven::DensityEstimator.
References alpha, sgpp::op_factory::createOperationEval(), and grid.
Referenced by python.uq.dists.Dist.Dist::crossEntropy(), python.uq.dists.J.J::discretize(), python.uq.dists.Dist.Dist::klDivergence(), and python.uq.dists.Dist.Dist::l2error().
splitset()
void sgpp::datadriven::SparseGridDensityEstimator::splitset (std::vector< std::shared_ptr< base::DataMatrix > > & strain, std::vector< std::shared_ptr< base::DataMatrix > > & stest) protected
splits the complete sample set in a set of smaller training and test samples for cross-validation.
Parameters
strain vector containing the training samples for cv
stest vector containing the test samples for cv
References crossvalidationConfig, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::kfold_, samples, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::seed_, sgpp::datadriven::CrossvalidationForRegularizationConfiguration::shuffle_, and sgpp::datadriven::CrossvalidationForRegularizationConfiguration::silent_.
Referenced by optimizeLambdaCV().
train()
void sgpp::datadriven::SparseGridDensityEstimator::train (base::Grid & grid, base::DataVector & alpha, base::DataMatrix & train, double lambdaReg) virtual
Does the learning step on a given grid, training set and regularization parameter lambda.
Parameters
grid grid
alpha coefficient vector
train sample set
lambdaReg regularization parameter
References adaptivityConfig, alpha, computeDensitySystemMatrix(), sgpp::op_factory::createOperationEval(), crossvalidationConfig, sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SGSolver::getResiduum(), grid, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::GridGenerator::refine(), sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::DataVector::setAll(), sgpp::datadriven::CrossvalidationForRegularizationConfiguration::silent_, sgpp::solver::ConjugateGradients::solve(), solverConfig, sgpp::solver::SLESolverConfiguration::threshold_, train(), and sgpp::solver::SLESolverConfiguration::verbose_.
Referenced by computeDensitySystemMatrix(), computeMultipleEvalMatrix(), initialize(), optimizeLambdaCV(), and train().
variance() [1/2]
double sgpp::datadriven::SparseGridDensityEstimator::variance () override virtual
Computes the variance of the density function.
Implements sgpp::datadriven::DensityEstimator.
References alpha, grid, and variance().
Referenced by variance().
variance() [2/2]
double sgpp::datadriven::SparseGridDensityEstimator::variance (base::Grid & grid, base::DataVector & alpha) protected
References alpha, sgpp::op_factory::createOperationFirstMoment(), sgpp::op_factory::createOperationSecondMoment(), and grid.
Member Data Documentation
adaptivityConfig
sgpp::base::AdaptivityConfiguration sgpp::datadriven::SparseGridDensityEstimator::adaptivityConfig protected
Referenced by SparseGridDensityEstimator(), and train().
alpha
std::shared_ptr<base::DataVector> sgpp::datadriven::SparseGridDensityEstimator::alpha protected
Referenced by computeResidual(), cov(), python.learner.Learner.Learner::doLearningIteration(), getSurpluses(), initialize(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Interpolant.Interpolant::learnDataWithTest(), marginalize(), margToDimX(), mean(), mean(), optimizeLambdaCV(), pdf(), pdf(), python.uq.dists.SGDEdist.SGDEdist::pdf(), SparseGridDensityEstimator(), SparseGridDensityEstimator(), python.uq.dists.SGDEdist.SGDEdist::toJson(), train(), variance(), and variance().
crossvalidationConfig
CrossvalidationForRegularizationConfiguration sgpp::datadriven::SparseGridDensityEstimator::crossvalidationConfig protected
Referenced by initialize(), optimizeLambdaCV(), SparseGridDensityEstimator(), splitset(), and train().
grid
std::shared_ptr<base::Grid> sgpp::datadriven::SparseGridDensityEstimator::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), computeDensitySystemMatrix(), computeLTwoDotProductMatrix(), computeMultipleEvalMatrix(), computeRegularizationMatrix(), computeResidual(), cov(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), initialize(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), marginalize(), margToDimX(), mean(), mean(), python.uq.dists.SGDEdist.SGDEdist::mean(), optimizeLambdaCV(), pdf(), pdf(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), SparseGridDensityEstimator(), SparseGridDensityEstimator(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), train(), python.uq.dists.SGDEdist.SGDEdist::var(), variance(), and variance().
gridConfig
sgpp::base::RegularGridConfiguration sgpp::datadriven::SparseGridDensityEstimator::gridConfig protected
Referenced by createRegularGrid(), getDim(), initialize(), and SparseGridDensityEstimator().
regularizationConfig
sgpp::datadriven::RegularizationConfiguration sgpp::datadriven::SparseGridDensityEstimator::regularizationConfig protected
Referenced by computeRegularizationMatrix(), and SparseGridDensityEstimator().
samples
std::shared_ptr<base::DataMatrix> sgpp::datadriven::SparseGridDensityEstimator::samples protected
Referenced by python.uq.sampler.Sample.SamplesIterator::__next__(), python.uq.dists.DataDist.DataDist::cdf(), getNsamples(), getSamples(), getSamples(), initialize(), marginalize(), margToDimX(), python.uq.dists.DataDist.DataDist::mean(), python.uq.dists.DataDist.DataDist::rvs(), python.uq.dists.LibAGFDist.LibAGFDist::rvs(), SparseGridDensityEstimator(), SparseGridDensityEstimator(), splitset(), python.uq.dists.DataDist.DataDist::toJson(), and python.uq.dists.DataDist.DataDist::var().
sgdeConfig
SGDEConfiguration sgpp::datadriven::SparseGridDensityEstimator::sgdeConfig protected
Referenced by initialize(), and SparseGridDensityEstimator().
solverConfig
sgpp::solver::SLESolverConfiguration sgpp::datadriven::SparseGridDensityEstimator::solverConfig protected
Referenced by SparseGridDensityEstimator(), and train().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/SparseGridDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/SparseGridDensityEstimator.cpp