SG++-Doxygen-Documentation: sgpp::base::HashRefinementBoundariesMaxLevel Class Reference
sgpp::base::HashRefinementBoundariesMaxLevel Class Reference
Standard free refinement class for sparse grids with boundaries with a maximal level depth of refinement.
#include <HashRefinementBoundariesMaxLevel.hpp>
Public Member Functions
size_t getNumberOfRefinablePointsToMaxLevel (GridStorage &storage, unsigned int maxLevel)
Calculates the number of points, which can be refined.
void refineGridpoint1D (GridStorage &storage, GridPoint &point, size_t d) override
Refine one grid point along a single direction.
void refineGridpoint1D (GridStorage &storage, GridPoint &point, size_t d, unsigned int maxLevel)
Refine one grid point along a single direction.
void refineToMaxLevel (GridStorage &storage, RefinementFunctor &functor, unsigned int maxLevel)
Performs the refinement on grid.
Public Member Functions inherited from sgpp::base::HashRefinementBoundaries
void free_refine (GridStorage &storage, RefinementFunctor &functor, std::vector< size_t > *addedPoints=nullptr) override
Performs the refinement on grid.
size_t getNumberOfRefinablePoints (GridStorage &storage) override
Calculates the number of points, which can be refined.
Public Member Functions inherited from sgpp::base::AbstractRefinement
virtual size_t getIndexOfMin (RefinementFunctor::value_type *array, size_t length)
Returns the index of the first occurrence of minimal element in array.
bool isRefinable (GridStorage &storage, GridPoint &point)
Check if the grid point is refinable.
virtual void refineGridpoint1D (GridStorage &storage, size_t seq, size_t d)
Refine one grid point along a single direction.
virtual ~AbstractRefinement ()
Destructor.
Protected Member Functions
void refineGridpoint (GridStorage &storage, size_t refine_index) override
This method refines a grid point be generating the children in every dimension of the grid.
void refineGridpoint (GridStorage &storage, size_t refine_index, unsigned int maxLevel)
This method refines a grid point be generating the children in every dimension of the grid.
Protected Member Functions inherited from sgpp::base::HashRefinementBoundaries
virtual void addElementToCollection (const GridStorage::grid_map_iterator &iter, AbstractRefinement::refinement_list_type current_value_list, size_t refinements_num, AbstractRefinement::refinement_container_type &collection)
Adds elements to the collection.
void collectRefinablePoints (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection) override
Examines the grid points and stores the indices those that can be refined and have maximal indicator values.
void createGridpoint (GridStorage &storage, GridPoint &point) override
Wrapper for the two functions create_gridpoint_general and create_gridpoint_levelZeroConsistency which have both to be executed if a gridpoint is refined.
void createGridpoint1D (GridPoint &point, size_t d, GridStorage &storage, index_t &source_index, level_t &source_level) override
Creates children grid points along single direction.
void createGridpointGeneral (GridStorage &storage, GridPoint &point)
This method creates a new point on the grid.
void createGridpointLevelZeroConsistency (GridStorage &storage, GridPoint &point)
Assures that we have always a consistent grid with both functions 0,0 and 0,1 on level zero.
AbstractRefinement::refinement_list_type getIndicator (GridStorage &storage, const GridStorage::grid_map_iterator &iter, const RefinementFunctor &functor) const override
Generates a list with indicator elements.
void refineGridpointsCollection (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection) override
Extends the grid adding elements defined in collection.
Protected Member Functions inherited from sgpp::base::AbstractRefinement
virtual void createGridpointSubroutine (GridStorage &storage, GridPoint &point)
Subroutine for grid point creation.
Additional Inherited Members
Public Types inherited from sgpp::base::AbstractRefinement
typedef std::vector< refinement_pair_type > refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
typedef AbstractRefinement_refinement_key refinement_key_type
Type of the identifier of the refinement atom (e.g.
typedef std::forward_list< AbstractRefinement::refinement_pair_type > refinement_list_type
typedef std::pair< std::shared_ptr< refinement_key_type >, refinement_value_type > refinement_pair_type
Pair for the refinement key and value.
typedef double refinement_value_type
Type of functor value assigned to each refinement atom.
Static Public Member Functions inherited from sgpp::base::AbstractRefinement
static bool compare_pairs (const refinement_pair_type &lhs, const refinement_pair_type &rhs)
Comparison of the refinement_pair_type.
Detailed Description
Standard free refinement class for sparse grids with boundaries with a maximal level depth of refinement.
Member Function Documentation
getNumberOfRefinablePointsToMaxLevel()
size_t sgpp::base::HashRefinementBoundariesMaxLevel::getNumberOfRefinablePointsToMaxLevel (GridStorage & storage, unsigned int maxLevel)
Calculates the number of points, which can be refined.
Parameters
storage hashmap that stores the grid points
maxLevel no points on higher levels than maxLevel will be created
References sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), sgpp::base::HashGridStorage::getDimension(), and sgpp::base::HashGridStorage::getSize().
Referenced by sgpp::base::BoundaryGridGenerator::getNumberOfRefinablePointsToMaxLevel(), sgpp::base::L0BoundaryGridGenerator::getNumberOfRefinablePointsToMaxLevel(), and sgpp::base::StretchedBoundaryGridGenerator::getNumberOfRefinablePointsToMaxLevel().
refineGridpoint() [1/2]
void sgpp::base::HashRefinementBoundaries::refineGridpoint (GridStorage & storage, size_t refine_index) override protected virtual
This method refines a grid point be generating the children in every dimension of the grid.
Parameters
storage hashmap that stores the gridpoints
refine_index the index in the hashmap of the point that should be refined
Reimplemented from sgpp::base::HashRefinementBoundaries.
refineGridpoint() [2/2]
void sgpp::base::HashRefinementBoundariesMaxLevel::refineGridpoint (GridStorage & storage, size_t refine_index, unsigned int maxLevel) protected
This method refines a grid point be generating the children in every dimension of the grid.
Parameters
storage hashmap that stores the gridpoints
refine_index the index in the hashmap of the point that should be refined
maxLevel no points on higher levels than maxLevel will be created
References sgpp::base::HashGridStorage::getDimension(), and refineGridpoint1D().
Referenced by refineToMaxLevel().
refineGridpoint1D() [1/2]
void sgpp::base::HashRefinementBoundaries::refineGridpoint1D (GridStorage & storage, GridPoint & point, size_t d) override virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
point point to refine
d direction
Reimplemented from sgpp::base::HashRefinementBoundaries.
refineGridpoint1D() [2/2]
void sgpp::base::HashRefinementBoundariesMaxLevel::refineGridpoint1D (GridStorage & storage, GridPoint & point, size_t d, unsigned int maxLevel)
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
point point to refine
d direction
maxLevel no points on higher levels than maxLevel will be created
References sgpp::base::HashRefinementBoundaries::createGridpoint(), and sgpp::base::HashGridStorage::isContaining().
Referenced by refineGridpoint().
refineToMaxLevel()
void sgpp::base::HashRefinementBoundariesMaxLevel::refineToMaxLevel (GridStorage & storage, RefinementFunctor & functor, unsigned int maxLevel)
Performs the refinement on grid.
Parameters
storage hashmap that stores the grid points
functor a function used to determine if refinement is needed
maxLevel no points on higher levels than maxLevel will be created
References sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::HashGridStorage::find(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::AbstractRefinement::getIndexOfMin(), sgpp::base::RefinementFunctor::getRefinementsNum(), sgpp::base::RefinementFunctor::getRefinementThreshold(), sgpp::base::HashGridStorage::getSize(), refineGridpoint(), and sgpp::base::RefinementFunctor::start().
Referenced by sgpp::base::BoundaryGridGenerator::refineMaxLevel(), sgpp::base::L0BoundaryGridGenerator::refineMaxLevel(), and sgpp::base::StretchedBoundaryGridGenerator::refineMaxLevel().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/hashmap/HashRefinementBoundariesMaxLevel.hpp
base/src/sgpp/base/grid/generation/hashmap/HashRefinementBoundariesMaxLevel.cpp