SG++-Doxygen-Documentation: sgpp::pde::LaplaceEnhancedUpBBLinearBoundary Class Reference
sgpp::pde::LaplaceEnhancedUpBBLinearBoundary Class Reference
Implementation of sweep operator () for enhanced Laplace operator, up operation.
#include <LaplaceEnhancedUpBBLinearBoundary.hpp>
Public Member Functions
LaplaceEnhancedUpBBLinearBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual void operator() (sgpp::base::DataMatrix &source, sgpp::base::DataMatrix &result, grid_iterator &index, size_t dim)
This operations performs the calculation of up in the direction of dimension dim on a grid with fix Dirichlet 0 boundary conditions.
virtual ~LaplaceEnhancedUpBBLinearBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::LaplaceEnhancedUpBBLinear
LaplaceEnhancedUpBBLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual ~LaplaceEnhancedUpBBLinear ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::LaplaceEnhancedUpBBLinear
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::LaplaceEnhancedUpBBLinear
void rec (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Up (L2 scalar product) without Bounding Box
void rec_GL (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (L2 scalar product and gradient) without Bounding Box
void rec_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Up (gradient) without Bounding Box
void rec_LG (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (gradient and L2 scalar product) without Bounding Box
void rec_LL (double &fl, double &fr, double &fl2, double &fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (L2 scalar products) without Bounding Box
void recBB (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Up (L2 scalar product) with Bounding Box
void recBB_GL (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (gradient and L2 scalar product) with Bounding Box
void recBB_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Up (gradient) with Bounding Box
void recBB_LG (double &fl, double &fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (L2 scalar product and gradient) with Bounding Box
void recBB_LL (double &fl, double &fr, double &fl2, double &fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Up (L2 scalar products) with Bounding Box
Protected Attributes inherited from sgpp::pde::LaplaceEnhancedUpBBLinear
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::BoundingBox * boundingBox
Pointer to the bounding box Obejct.
size_t cur_algo_dim_
current algorithmic dimension for the overall operator
const size_t numAlgoDims_
number of algorithmic dimensions
double * ptr_result_
pointer to DataMatrix containing result coefficients
double * ptr_source_
pointer to DataMatrix containing source coefficients
double q_
stretching of basis functions in current algorithmic domain
sgpp::base::GridStorage * storage
Pointer to sgpp::base::GridStorage object.
double t_
translation of basis function in current algorithmic domain
Detailed Description
Implementation of sweep operator () for enhanced Laplace operator, up operation.
This sweep operator calculates all ups (L2 scalar products and gradient) for a given dimension.
Constructor & Destructor Documentation
LaplaceEnhancedUpBBLinearBoundary()
sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::LaplaceEnhancedUpBBLinearBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~LaplaceEnhancedUpBBLinearBoundary()
sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::~LaplaceEnhancedUpBBLinearBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::LaplaceEnhancedUpBBLinearBoundary::operator() (sgpp::base::DataMatrix & source, sgpp::base::DataMatrix & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of up in the direction of dimension dim on a grid with fix Dirichlet 0 boundary conditions.
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the up operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::pde::LaplaceEnhancedUpBBLinear.
References sgpp::pde::LaplaceEnhancedUpBBLinear::algoDims, sgpp::pde::LaplaceEnhancedUpBBLinear::boundingBox, sgpp::pde::LaplaceEnhancedUpBBLinear::cur_algo_dim_, sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::DataMatrix::getPointer(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::pde::LaplaceEnhancedUpBBLinear::numAlgoDims_, sgpp::pde::LaplaceEnhancedUpBBLinear::ptr_result_, sgpp::pde::LaplaceEnhancedUpBBLinear::ptr_source_, sgpp::pde::LaplaceEnhancedUpBBLinear::q_, sgpp::pde::LaplaceEnhancedUpBBLinear::rec(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_GL(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::rec_LL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_GL(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_grad(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LG(), sgpp::pde::LaplaceEnhancedUpBBLinear::recBB_LL(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), sgpp::pde::LaplaceEnhancedUpBBLinear::storage, and sgpp::pde::LaplaceEnhancedUpBBLinear::t_.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/LaplaceEnhancedUpBBLinearBoundary.hpp
pde/src/sgpp/pde/basis/linear/boundary/algorithm_sweep/LaplaceEnhancedUpBBLinearBoundary.cpp