SG++-Doxygen-Documentation: sgpp::pde::PhiPhiDownBBLinearStretchedBoundary Class Reference
sgpp::pde::PhiPhiDownBBLinearStretchedBoundary Class Reference
Implementation of sgpp::base::sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
#include <PhiPhiDownBBLinearStretchedBoundary.hpp>
Public Member Functions
virtual void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of down in the direction of dimension dim
PhiPhiDownBBLinearStretchedBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiDownBBLinearStretchedBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::PhiPhiDownBBLinearStretched
PhiPhiDownBBLinearStretched (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiDownBBLinearStretched ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::PhiPhiDownBBLinearStretched
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::PhiPhiDownBBLinearStretched
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
recursive function for the calculation of Down with sgpp::base::Stretching
Protected Attributes inherited from sgpp::pde::PhiPhiDownBBLinearStretched
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage Object.
sgpp::base::Stretching * stretching
Pointer to the bounding box Obejct.
Detailed Description
Implementation of sgpp::base::sweep operator (): 1D Down for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
Constructor & Destructor Documentation
PhiPhiDownBBLinearStretchedBoundary()
sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::PhiPhiDownBBLinearStretchedBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiDownBBLinearStretchedBoundary()
sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::~PhiPhiDownBBLinearStretchedBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiDownBBLinearStretchedBoundary::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of down in the direction of dimension dim
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
On level zero the getfixDirechletBoundaries of the storage object evaluated
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the down operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::pde::PhiPhiDownBBLinearStretched.
References sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), and sgpp::base::HashGridIterator::seq().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linearstretched/boundary/algorithm_sweep/PhiPhiDownBBLinearStretchedBoundary.hpp
pde/src/sgpp/pde/basis/linearstretched/boundary/algorithm_sweep/PhiPhiDownBBLinearStretchedBoundary.cpp