SG++-Doxygen-Documentation: sgpp::datadriven::CombiScheme Class Reference
sgpp::datadriven::CombiScheme Class Reference
#include <CombiScheme.hpp>
Public Member Functions
CombiScheme ()
Empty Constructor.
std::vector< std::pair< std::vector< size_t >, int > > getCombiScheme ()
return the combigrid scheme (levelvectors of the components and their coefficients)
void initialize (size_t dim, size_t level)
Initialize the combigrid scheme.
bool isRefinable (std::vector< size_t > levelvec)
check if the component of levelvec is refinable
bool refineComponent (std::vector< size_t > levelvec)
update the scheme by component of levelvec
Constructor & Destructor Documentation
CombiScheme()
sgpp::datadriven::CombiScheme::CombiScheme () inline
Empty Constructor.
Member Function Documentation
getCombiScheme()
std::vector< std::pair< std::vector< size_t >, int > > sgpp::datadriven::CombiScheme::getCombiScheme ()
return the combigrid scheme (levelvectors of the components and their coefficients)
Returns
levelvectors of the components and their corresponding coefficients
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::adapt(), and sgpp::datadriven::ModelFittingDensityEstimationCombi::fit().
initialize()
void sgpp::datadriven::CombiScheme::initialize (size_t dim, size_t level)
Initialize the combigrid scheme.
Parameters
dim dimension
level level
References level.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::fit().
isRefinable()
bool sgpp::datadriven::CombiScheme::isRefinable (std::vector< size_t > levelvec)
check if the component of levelvec is refinable
Parameters
levelvec vector for the component in question
Returns
whether we can refine the scheme
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::adapt(), and refineComponent().
refineComponent()
bool sgpp::datadriven::CombiScheme::refineComponent (std::vector< size_t > levelvec)
update the scheme by component of levelvec
Parameters
levelvec vector for the component in question
Returns
whether the scheme was refined
References isRefinable().
Referenced by sgpp::datadriven::ModelFittingDensityEstimationCombi::adapt().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/CombiScheme.hpp
datadriven/src/sgpp/datadriven/algorithm/CombiScheme.cpp