SG++-Doxygen-Documentation: sgpp::datadriven::OperationMultipleEvalSubspaceCombined Class Reference
sgpp::datadriven::OperationMultipleEvalSubspaceCombined Class Reference
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
#include <OperationMultipleEvalSubspaceCombined.hpp>
Public Member Functions
size_t getAlignment () override
Alignment required by the vector instruction set SG++ is compiled with.
std::string getImplementationName () override
Name of the implementation, useful for benchmarking different implementation approaches.
size_t getPaddedDatasetSize () override
Size of the dataset after padding.
void multImpl (sgpp::base::DataVector &source, sgpp::base::DataVector &result, const size_t start_index_data, const size_t end_index_data) override
Internal mult operator, should not be called directly.
void multTransposeImpl (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, const size_t start_index_data, const size_t end_index_data) override
Internal eval operator, should not be called directly.
OperationMultipleEvalSubspaceCombined (sgpp::base::Grid &grid, sgpp::base::DataMatrix &dataset)
Creates a new instance of the OperationMultipleEvalSubspaceCombined class.
sgpp::base::DataMatrix * padDataset (sgpp::base::DataMatrix &dataset)
Pads the dataset.
void prepare () override
Updates the internal data structures to reflect changes to the grid, e.g.
~OperationMultipleEvalSubspaceCombined ()
Destructor.
Public Member Functions inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
AbstractOperationMultipleEvalSubspace (base::Grid &grid, base::DataMatrix &dataset)
double getDuration () override
void mult (sgpp::base::DataVector &source, sgpp::base::DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
~AbstractOperationMultipleEvalSubspace () override
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual ~OperationMultipleEval ()
Destructor.
Static Public Member Functions
static void calculateIndexCombined (size_t dim, size_t nextIterationToRecalc, const double *const (&dataTuplePtr)[4], std::vector< uint32_t > &hInversePtr, uint32_t *(&intermediates)[4], double *(&evalIndexValues)[4], uint32_t(&indexFlat)[4], double(&phiEval)[4])
static void calculateIndexCombined2 (size_t dim, size_t nextIterationToRecalc, const double *const (&dataTuplePtr)[4], const double *const (&dataTuplePtr2)[4], std::vector< uint32_t > &hInversePtr, uint32_t *(&intermediates)[4], uint32_t *(&intermediates2)[4], double *(&evalIndexValues)[4], double *(&evalIndexValues2)[4], uint32_t(&indexFlat)[4], uint32_t(&indexFlat2)[4], double(&phiEval)[4], double(&phiEval2)[4])
Static Public Member Functions inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
static size_t getChunkDataPoints ()
static size_t getChunkGridPoints ()
Additional Inherited Members
Protected Attributes inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
base::GridStorage * storage
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Detailed Description
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
Constructor & Destructor Documentation
OperationMultipleEvalSubspaceCombined()
sgpp::datadriven::OperationMultipleEvalSubspaceCombined::OperationMultipleEvalSubspaceCombined (sgpp::base::Grid & grid, sgpp::base::DataMatrix & dataset)
Creates a new instance of the OperationMultipleEvalSubspaceCombined class.
Parameters
grid grid to be evaluated
dataset set of evaluation points
References sgpp::base::OperationMultipleEval::dataset, fileName, sgpp::base::DataMatrix::getNcols(), sgpp::base::Grid::getStorage(), padDataset(), and sgpp::datadriven::AbstractOperationMultipleEvalSubspace::storage.
~OperationMultipleEvalSubspaceCombined()
sgpp::datadriven::OperationMultipleEvalSubspaceCombined::~OperationMultipleEvalSubspaceCombined ()
Destructor.
Member Function Documentation
calculateIndexCombined()
static void sgpp::datadriven::OperationMultipleEvalSubspaceCombined::calculateIndexCombined (size_t dim, size_t nextIterationToRecalc, const double *const (&) dataTuplePtr[4], std::vector< uint32_t > & hInversePtr, uint32_t *(&) intermediates[4], double *(&) evalIndexValues[4], uint32_t(&) indexFlat[4], double(&) phiEval[4]) inline static
calculateIndexCombined2()
static void sgpp::datadriven::OperationMultipleEvalSubspaceCombined::calculateIndexCombined2 (size_t dim, size_t nextIterationToRecalc, const double *const (&) dataTuplePtr[4], const double *const (&) dataTuplePtr2[4], std::vector< uint32_t > & hInversePtr, uint32_t *(&) intermediates[4], uint32_t *(&) intermediates2[4], double *(&) evalIndexValues[4], double *(&) evalIndexValues2[4], uint32_t(&) indexFlat[4], uint32_t(&) indexFlat2[4], double(&) phiEval[4], double(&) phiEval2[4]) inline static
getAlignment()
size_t sgpp::datadriven::OperationMultipleEvalSubspaceCombined::getAlignment () override virtual
Alignment required by the vector instruction set SG++ is compiled with.
Returns
alignment requirement
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References X86COMBINED_PARALLEL_DATA_POINTS.
getImplementationName()
std::string sgpp::datadriven::OperationMultipleEvalSubspaceCombined::getImplementationName () override virtual
Name of the implementation, useful for benchmarking different implementation approaches.
Returns
name of the implementation
Reimplemented from sgpp::base::OperationMultipleEval.
getPaddedDatasetSize()
size_t sgpp::datadriven::OperationMultipleEvalSubspaceCombined::getPaddedDatasetSize () override virtual
Size of the dataset after padding.
Returns
size of the padded dataset>
Reimplemented from sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References sgpp::base::DataMatrix::getNrows().
multImpl()
void sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multImpl (sgpp::base::DataVector & source, sgpp::base::DataVector & result, const size_t start_index_data, const size_t end_index_data) override virtual
Internal mult operator, should not be called directly.
See also
OperationMultipleEval
Parameters
source source operand for the operator
result stores the result
start_index_data beginning of the range to process
end_index_data end of the range to process
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getPointer(), sgpp::datadriven::SubspaceNodeCombined::indexFlatSurplusPairs, sgpp::datadriven::SubspaceNodeCombined::LIST, sgpp::base::DataVector::set(), sgpp::datadriven::SubspaceNodeCombined::subspaceArray, sgpp::datadriven::SubspaceNodeCombined::type, X86COMBINED_PARALLEL_DATA_POINTS, and X86COMBINED_VEC_PADDING.
multTransposeImpl()
void sgpp::datadriven::OperationMultipleEvalSubspaceCombined::multTransposeImpl (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, const size_t start_index_data, const size_t end_index_data) override virtual
Internal eval operator, should not be called directly.
See also
OperationMultipleEval
Parameters
alpha surplusses of the grid
result will contain the evaluation results for the given range.
start_index_data beginning of the range to evaluate
end_index_data end of the range to evaluate
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References alpha, sgpp::datadriven::SubspaceNodeCombined::ARRAY, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getPointer(), sgpp::datadriven::SubspaceNodeCombined::indexFlatSurplusPairs, sgpp::datadriven::SubspaceNodeCombined::LIST, sgpp::datadriven::SubspaceNodeCombined::lockSubspace(), sgpp::datadriven::SubspaceNodeCombined::subspaceArray, sgpp::datadriven::SubspaceNodeCombined::type, sgpp::datadriven::SubspaceNodeCombined::unlockSubspace(), X86COMBINED_PARALLEL_DATA_POINTS, and X86COMBINED_VEC_PADDING.
padDataset()
DataMatrix * sgpp::datadriven::OperationMultipleEvalSubspaceCombined::padDataset (sgpp::base::DataMatrix & dataset)
Pads the dataset.
Parameters
dataset dataset to be padded
Returns
padded dataset
References sgpp::base::OperationMultipleEval::dataset, sgpp::base::DataMatrix::getAdditionallyReservedRows(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataMatrix::reserveAdditionalRows(), sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::set(), sgpp::base::DataMatrix::setRow(), X86COMBINED_PARALLEL_DATA_POINTS, and X86COMBINED_VEC_PADDING.
Referenced by OperationMultipleEvalSubspaceCombined().
prepare()
void sgpp::datadriven::OperationMultipleEvalSubspaceCombined::prepare () override virtual
Updates the internal data structures to reflect changes to the grid, e.g.
due to refinement.
Reimplemented from sgpp::base::OperationMultipleEval.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined_listMultInner.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined_multImpl.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined_multTransposeImpl.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined_prepareSubspaceIterator.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/combined/OperationMultipleEvalSubspaceCombined_uncachedMultTransposeInner.cpp