SG++-Doxygen-Documentation: sgpp::base::Grid Class Reference
sgpp::base::Grid Class Reference abstract
abstract base class for all types grids used in sgpp the class gives pure virtual function definitions that have to be implemented by all types of grids
#include <Grid.hpp>
Public Member Functions
Grid * clone ()
copies a grid
Grid * createGridOfEquivalentType (size_t numDims)
creates an equivalent grid without copying the grid points
std::vector< size_t > getAlgorithmicDimensions ()
returns the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
virtual SBasis & getBasis ()=0
Returns the Basis class associated with the grid.
virtual BoundingBox & getBoundingBox ()
gets a reference to the GridStorage's BoundingsBox object
size_t getDimension () const
Returns the number of dimensions.
virtual GridGenerator & getGenerator ()=0
size_t getSize () const
Returns the number of points on the grid.
virtual GridStorage & getStorage ()
gets a reference to the GridStorage object
virtual Stretching & getStretching ()
gets a reference to the GridStorage's Stretching object
virtual sgpp::base::GridType getType ()=0
Returns a string that identifies the grid type uniquely.
std::string getTypeAsString ()
Returns a string that identifies the grid type uniquely.
sgpp::base::GridType getZeroBoundaryType ()
Returns the grid type that corresponds to the actual type but does no boundary treatment.
Grid (const Grid &other)=delete
delete copy constructor
void insertPoint (size_t dim, unsigned int levels[], unsigned int indices[], bool isLeaf)
Insert one point to the grid.
void refine (DataVector &vector, int numOfPoints)
Refine grid Refine the given number of points on the grid according to the vector.
std::string serialize (int version=SERIALIZATION_VERSION)
Serializes grid to a string.
virtual void serialize (std::ostream &ostr, int version=SERIALIZATION_VERSION)
Serializes the grid.
void serialize (std::string &ostr, int version=SERIALIZATION_VERSION)
Serializes grid to a string.
void setAlgorithmicDimensions (std::vector< size_t > newAlgoDims)
sets the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
virtual void setBoundingBox (BoundingBox &boundingBox)
sets the GridStorage's BoundingsBox
virtual void setStretching (Stretching &stretching)
sets the GridStorage's Stretching pointer to a Stretching object
virtual ~Grid ()
Desctructor.
Static Public Member Functions
static Grid * createBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a B-spline trapezoid boundary grid
static Grid * createBsplineClenshawCurtisGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a B-spline Clenshaw-Curtis grid
static Grid * createBsplineGrid (size_t dim, size_t degree)
creates a B-spline grid
static Grid * createFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createFundamentalSplineGrid (size_t dim, size_t degree)
creates a fundamental spline grid
static Grid * createGrid (RegularGridConfiguration gridConfig)
creates a grid defined by the grid configuration
static Grid * createLinearBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a linear boundary grid
static Grid * createLinearClenshawCurtisBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a linear Clenshaw-Curtis boundary grid
static Grid * createLinearClenshawCurtisGrid (size_t dim)
creates a linear Clenshaw-Curtis grid
static Grid * createLinearGrid (size_t dim)
Creates and returns a grid without grid points on the boundary (zero boundary conditions) with piecewise linear basis functions.
static Grid * createLinearGridStencil (size_t dim)
creates a stencil for a linear grid (without boundaries)
static Grid * createLinearStretchedBoundaryGrid (size_t dim)
creates a linearstretched truncated boundary grid
static Grid * createLinearStretchedGrid (size_t dim)
creates a linear stretched grid without boundaries
static Grid * createLinearTruncatedBoundaryGrid (size_t dim)
creates a truncated boundary grid=contains all the gridpoints of the fullgrids which have \(|l|<level and li>=l_user\)
static Grid * createModBsplineClenshawCurtisGrid (size_t dim, size_t degree)
creates a modified B-spline Clenshaw-Curtis grid
static Grid * createModBsplineGrid (size_t dim, size_t degree)
creates a modified B-spline grid
static Grid * createModFundamentalSplineGrid (size_t dim, size_t degree)
creates a modified fundamental spline grid
static Grid * createModLinearClenshawCurtisGrid (size_t dim)
creates a modified linear Clenshaw-Curtis grid
static Grid * createModLinearGrid (size_t dim)
creates a modified linear grid
static Grid * createModLinearGridStencil (size_t dim)
creates a stencil for a modified linear grid (without boundaries)
static Grid * createModNakBsplineGrid (size_t dim, size_t degree)
static Grid * createModPolyClenshawCurtisGrid (size_t dim, size_t degree)
creates a modified poly grid with clenshaw curtis points
static Grid * createModPolyGrid (size_t dim, size_t degree)
creates a modified polynomial grid
static Grid * createModWaveletGrid (size_t dim)
creates a modified wavelet grid
static Grid * createModWeaklyFundamentalNakSplineGrid (size_t dim, size_t degree)
static Grid * createNakBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createNakBsplineExtendedGrid (size_t dim, size_t degree)
creates a not a knot B-Spline extended grid
static Grid * createNakBsplineGrid (size_t dim, size_t degree)
creates a not a knot B-Spline grid
static Grid * createNakPBsplineGrid (size_t dim, size_t degree)
creates a not a knot polynomial B-Spline extended grid
static Grid * createNaturalBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a not a knot B-Spline boundary grid
static Grid * createPeriodicGrid (size_t dim)
creates a periodic grid
static Grid * createPolyBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a polynomial grid with truncated boundary
static Grid * createPolyClenshawCurtisBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
creates a poly Clenshaw Curtis boundary grid with clenshaw curtis points
static Grid * createPolyClenshawCurtisGrid (size_t dim, size_t degree)
creates a poly grid with clenshaw curtis points
static Grid * createPolyGrid (size_t dim, size_t degree)
creates a polynomial grid
static Grid * createPrewaveletGrid (size_t dim)
creates a prewavelet grid
static Grid * createSquareRootGrid (size_t dim)
creates a square root grid (h-grid)
static Grid * createWaveletBoundaryGrid (size_t dim, level_t boundaryLevel=1)
creates a wavelet trapezoid boundary grid
static Grid * createWaveletGrid (size_t dim)
creates a wavelet grid
static Grid * createWeaklyFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static Grid * createWeaklyFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel=1)
static GridType stringToGridType (const std::string &gridType)
Conversion from string to grid type.
static Grid * unserialize (const std::string &istr)
reads a grid out of a string
static Grid * unserialize (std::istream &istr)
reads a grid out of a stream
static Grid * unserializeFromFile (std::string filename)
opens a file given by name and reads a grid out of the stored string @ param filename name of the file
Protected Types
typedef Grid *(* Factory) (std::istream &)
typedef std::map< std::string, Grid::Factory > factoryMap
typedef std::map< sgpp::base::GridType, std::string > gridTypeVerboseMap
Protected Member Functions
Grid (BoundingBox &boundingBox)
Constructor initializing the grid storage with the given BoundingBox.
Grid (size_t dim)
Constructor initializing the grid storage with the given dimensionality.
Grid (std::istream &istr)
This constructor creates a new GridStorage out of the stream.
Grid (Stretching &stretching)
Constructor initializing the grid storage with the given Stretching.
Static Protected Member Functions
static Grid * nullFactory (std::istream &)
Factory for everything we don't know.
Protected Attributes
GridStorage storage
GridStorage object of the grid.
Detailed Description
abstract base class for all types grids used in sgpp the class gives pure virtual function definitions that have to be implemented by all types of grids
Member Typedef Documentation
Factory
typedef Grid *(* sgpp::base::Grid::Factory) (std::istream &) protected
factoryMap
typedef std::map<std::string, Grid::Factory> sgpp::base::Grid::factoryMap protected
gridTypeVerboseMap
typedef std::map<sgpp::base::GridType, std::string> sgpp::base::Grid::gridTypeVerboseMap protected
Constructor & Destructor Documentation
Grid() [1/5]
sgpp::base::Grid::Grid (const Grid & other) delete
delete copy constructor
Parameters
other
References createGrid().
Grid() [2/5]
sgpp::base::Grid::Grid (std::istream & istr) explicit protected
This constructor creates a new GridStorage out of the stream.
For derived classes create an own constructor wich takes a std::istream and calls this function. Add your own static unserialize function and add it in typeMap().
Parameters
istr inputstream that contains the grid information
Grid() [3/5]
sgpp::base::Grid::Grid (size_t dim) explicit protected
Constructor initializing the grid storage with the given dimensionality.
Parameters
dim dimensionality
Grid() [4/5]
sgpp::base::Grid::Grid (BoundingBox & boundingBox) explicit protected
Constructor initializing the grid storage with the given BoundingBox.
Parameters
boundingBox BoundingBox of the grid
Grid() [5/5]
sgpp::base::Grid::Grid (Stretching & stretching) explicit protected
Constructor initializing the grid storage with the given Stretching.
Parameters
stretching Stretching of the grid
~Grid()
sgpp::base::Grid::~Grid () virtual
Desctructor.
Member Function Documentation
clone()
Grid * sgpp::base::Grid::clone ()
copies a grid
References createGridOfEquivalentType(), getDimension(), and storage.
Referenced by sgpp::datadriven::LearnerSGDEOnOffParallel::LearnerSGDEOnOffParallel(), sgpp::datadriven::OperationDensityMargTo1D::margToDimXs(), sgpp::datadriven::VisualizerDensityEstimation::storeGrid(), sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson(), and sgpp::datadriven::VisualizerDensityEstimation::storeHeatmapJson().
createBsplineBoundaryGrid()
Grid * sgpp::base::Grid::createBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
creates a B-spline trapezoid boundary grid
Level 4* sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
boundaryLevel on which level the boundary grid points and basis functions should be added; the default is 1, which results in a grid with the same resolution on the boundary as on the main axis
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createBsplineClenshawCurtisGrid()
Grid * sgpp::base::Grid::createBsplineClenshawCurtisGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
creates a B-spline Clenshaw-Curtis grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
boundaryLevel on which level the boundary grid points and basis functions should be added; the default is 1, which results in a grid with the same resolution on the boundary as on the main axis
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createBsplineGrid()
Grid * sgpp::base::Grid::createBsplineGrid (size_t dim, size_t degree) static
creates a B-spline grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createFundamentalNakSplineBoundaryGrid()
Grid * sgpp::base::Grid::createFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
Referenced by createGrid(), and createGridOfEquivalentType().
createFundamentalSplineBoundaryGrid()
Grid * sgpp::base::Grid::createFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
Referenced by createGrid(), and createGridOfEquivalentType().
createFundamentalSplineGrid()
Grid * sgpp::base::Grid::createFundamentalSplineGrid (size_t dim, size_t degree) static
creates a fundamental spline grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createGrid()
Grid * sgpp::base::Grid::createGrid (RegularGridConfiguration gridConfig) static
creates a grid defined by the grid configuration
Parameters
gridConfig grid configuration
Returns
grid
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createBsplineBoundaryGrid(), createBsplineClenshawCurtisGrid(), createBsplineGrid(), createFundamentalNakSplineBoundaryGrid(), createFundamentalSplineBoundaryGrid(), createFundamentalSplineGrid(), createLinearBoundaryGrid(), createLinearClenshawCurtisBoundaryGrid(), createLinearClenshawCurtisGrid(), createLinearGrid(), createLinearStretchedBoundaryGrid(), createLinearStretchedGrid(), createLinearTruncatedBoundaryGrid(), createModBsplineClenshawCurtisGrid(), createModBsplineGrid(), createModFundamentalSplineGrid(), createModLinearClenshawCurtisGrid(), createModLinearGrid(), createModLinearGridStencil(), createModNakBsplineGrid(), createModPolyClenshawCurtisGrid(), createModPolyGrid(), createModWaveletGrid(), createModWeaklyFundamentalNakSplineGrid(), createNakBsplineBoundaryGrid(), createNakBsplineExtendedGrid(), createNakBsplineGrid(), createNakPBsplineGrid(), createNaturalBsplineBoundaryGrid(), createPeriodicGrid(), createPolyBoundaryGrid(), createPolyClenshawCurtisBoundaryGrid(), createPolyClenshawCurtisGrid(), createPolyGrid(), createPrewaveletGrid(), createSquareRootGrid(), createWaveletBoundaryGrid(), createWaveletGrid(), createWeaklyFundamentalNakSplineBoundaryGrid(), createWeaklyFundamentalSplineBoundaryGrid(), sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::filename_, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModLinearStencil, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::NaturalBsplineBoundary, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Prewavelet, sgpp::base::SquareRoot, sgpp::base::GeneralGridConfiguration::type_, unserialize(), sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
Referenced by sgpp::datadriven::SparseGridDensityEstimator::createRegularGrid(), Grid(), and sgpp::base::OperationArbitraryBoundaryHierarchisation::OperationArbitraryBoundaryHierarchisation().
createGridOfEquivalentType()
Grid * sgpp::base::Grid::createGridOfEquivalentType (size_t numDims)
creates an equivalent grid without copying the grid points
Parameters
numDims number of dimensions
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createBsplineBoundaryGrid(), createBsplineClenshawCurtisGrid(), createBsplineGrid(), createFundamentalNakSplineBoundaryGrid(), createFundamentalSplineBoundaryGrid(), createFundamentalSplineGrid(), createLinearBoundaryGrid(), createLinearClenshawCurtisBoundaryGrid(), createLinearClenshawCurtisGrid(), createLinearGrid(), createLinearStretchedBoundaryGrid(), createLinearStretchedGrid(), createLinearTruncatedBoundaryGrid(), createModBsplineClenshawCurtisGrid(), createModBsplineGrid(), createModFundamentalSplineGrid(), createModLinearClenshawCurtisGrid(), createModLinearGrid(), createModLinearGridStencil(), createModNakBsplineGrid(), createModPolyClenshawCurtisGrid(), createModPolyGrid(), createModWaveletGrid(), createModWeaklyFundamentalNakSplineGrid(), createNakBsplineBoundaryGrid(), createNakBsplineExtendedGrid(), createNakBsplineGrid(), createNakPBsplineGrid(), createNaturalBsplineBoundaryGrid(), createPeriodicGrid(), createPolyBoundaryGrid(), createPolyClenshawCurtisBoundaryGrid(), createPolyClenshawCurtisGrid(), createPolyGrid(), createPrewaveletGrid(), createSquareRootGrid(), createWaveletBoundaryGrid(), createWaveletGrid(), createWeaklyFundamentalNakSplineBoundaryGrid(), createWeaklyFundamentalSplineBoundaryGrid(), sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, getGenerator(), getType(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModLinearStencil, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::NaturalBsplineBoundary, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Prewavelet, sgpp::base::SquareRoot, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
Referenced by clone(), sgpp::datadriven::OperationDensityConditional::doConditional(), and sgpp::datadriven::OperationDensityMarginalize::doMarginalize().
createLinearBoundaryGrid()
Grid * sgpp::base::Grid::createLinearBoundaryGrid (size_t dim, level_t boundaryLevel = 1) static
creates a linear boundary grid
"Level 4 sparse grid with boundaryLevel = 0"
"Level 4 sparse grid with boundaryLevel = 1"
"Level 4 sparse grid with boundaryLevel = 2"
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
boundaryLevel on which level the boundary grid points and basis functions should be added; the default is 1, which results in a grid with the same resolution on the boundary as on the main axis
Returns
grid
Referenced by sgpp::datadriven::GridFactory::createGrid(), createGrid(), createGridOfEquivalentType(), sgpp::datadriven::LearnerSGDE::createRegularGrid(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), and sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost().
createLinearClenshawCurtisBoundaryGrid()
Grid * sgpp::base::Grid::createLinearClenshawCurtisBoundaryGrid (size_t dim, level_t boundaryLevel = 1) static
creates a linear Clenshaw-Curtis boundary grid
Parameters
dim the grid's dimension
boundaryLevel level of the boundary
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createLinearClenshawCurtisGrid()
Grid * sgpp::base::Grid::createLinearClenshawCurtisGrid (size_t dim) static
creates a linear Clenshaw-Curtis grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createLinearGrid()
Grid * sgpp::base::Grid::createLinearGrid (size_t dim) static
Creates and returns a grid without grid points on the boundary (zero boundary conditions) with piecewise linear basis functions.
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by sgpp::datadriven::GridFactory::createGrid(), createGrid(), createGridOfEquivalentType(), sgpp::datadriven::LearnerSGD::createRegularGrid(), sgpp::datadriven::LearnerSGDE::createRegularGrid(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), hpx_main(), main(), main(), and sgpp::datadriven::LearnerSGDE::trainOnline().
createLinearGridStencil()
Grid * sgpp::base::Grid::createLinearGridStencil (size_t dim) static
creates a stencil for a linear grid (without boundaries)
Level 4 sparse grid
Parameters
dim the grid's dimension
Returns
grid
createLinearStretchedBoundaryGrid()
Grid * sgpp::base::Grid::createLinearStretchedBoundaryGrid (size_t dim) static
creates a linearstretched truncated boundary grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Referenced by createGrid(), and createGridOfEquivalentType().
createLinearStretchedGrid()
Grid * sgpp::base::Grid::createLinearStretchedGrid (size_t dim) static
creates a linear stretched grid without boundaries
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createLinearTruncatedBoundaryGrid()
Grid * sgpp::base::Grid::createLinearTruncatedBoundaryGrid (size_t dim) static
creates a truncated boundary grid=contains all the gridpoints of the fullgrids which have \(|l|<level and li>=l_user\)
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModBsplineClenshawCurtisGrid()
Grid * sgpp::base::Grid::createModBsplineClenshawCurtisGrid (size_t dim, size_t degree) static
creates a modified B-spline Clenshaw-Curtis grid
"Level 4 sparse grid"
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModBsplineGrid()
Grid * sgpp::base::Grid::createModBsplineGrid (size_t dim, size_t degree) static
creates a modified B-spline grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModFundamentalSplineGrid()
Grid * sgpp::base::Grid::createModFundamentalSplineGrid (size_t dim, size_t degree) static
creates a modified fundamental spline grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModLinearClenshawCurtisGrid()
Grid * sgpp::base::Grid::createModLinearClenshawCurtisGrid (size_t dim) static
creates a modified linear Clenshaw-Curtis grid
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModLinearGrid()
Grid * sgpp::base::Grid::createModLinearGrid (size_t dim) static
creates a modified linear grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by sgpp::datadriven::GridFactory::createGrid(), createGrid(), createGridOfEquivalentType(), sgpp::datadriven::LearnerSGD::createRegularGrid(), sgpp::datadriven::LearnerSVM::createRegularGrid(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), hpx_main(), main(), and sgpp::datadriven::LearnerSGDE::trainOnline().
createModLinearGridStencil()
Grid * sgpp::base::Grid::createModLinearGridStencil (size_t dim) static
creates a stencil for a modified linear grid (without boundaries)
Level 4 sparse grid
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModNakBsplineGrid()
Grid * sgpp::base::Grid::createModNakBsplineGrid (size_t dim, size_t degree) static
Referenced by createGrid(), and createGridOfEquivalentType().
createModPolyClenshawCurtisGrid()
Grid * sgpp::base::Grid::createModPolyClenshawCurtisGrid (size_t dim, size_t degree) static
creates a modified poly grid with clenshaw curtis points
Parameters
dim the grid's dimension
degree the polynom's max. degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModPolyGrid()
Grid * sgpp::base::Grid::createModPolyGrid (size_t dim, size_t degree) static
creates a modified polynomial grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the polynom's max. degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModWaveletGrid()
Grid * sgpp::base::Grid::createModWaveletGrid (size_t dim) static
creates a modified wavelet grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createModWeaklyFundamentalNakSplineGrid()
Grid * sgpp::base::Grid::createModWeaklyFundamentalNakSplineGrid (size_t dim, size_t degree) static
Referenced by createGrid(), and createGridOfEquivalentType().
createNakBsplineBoundaryGrid()
Grid * sgpp::base::Grid::createNakBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
Referenced by createGrid(), and createGridOfEquivalentType().
createNakBsplineExtendedGrid()
Grid * sgpp::base::Grid::createNakBsplineExtendedGrid (size_t dim, size_t degree) static
creates a not a knot B-Spline extended grid
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted(), createGrid(), createGridOfEquivalentType(), and sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature().
createNakBsplineGrid()
Grid * sgpp::base::Grid::createNakBsplineGrid (size_t dim, size_t degree) static
creates a not a knot B-Spline grid
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createNakPBsplineGrid()
Grid * sgpp::base::Grid::createNakPBsplineGrid (size_t dim, size_t degree) static
creates a not a knot polynomial B-Spline extended grid
Parameters
dim the grid's dimension
degree the B-spline degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createNaturalBsplineBoundaryGrid()
Grid * sgpp::base::Grid::createNaturalBsplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
creates a not a knot B-Spline boundary grid
Parameters
dim the grid's dimension
degree the B-spline degree
boundaryLevel the level of the boundary grid
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPeriodicGrid()
Grid * sgpp::base::Grid::createPeriodicGrid (size_t dim) static
creates a periodic grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPolyBoundaryGrid()
Grid * sgpp::base::Grid::createPolyBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
creates a polynomial grid with truncated boundary
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the polynom's max. degree
boundaryLevel on which level the boundary grid points and basis functions should be added; the default is 1, which results in a grid with the same resolution on the boundary as on the main axis
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPolyClenshawCurtisBoundaryGrid()
Grid * sgpp::base::Grid::createPolyClenshawCurtisBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
creates a poly Clenshaw Curtis boundary grid with clenshaw curtis points
Parameters
dim the grid's dimension
degree the polynom's max. degree
boundaryLevel level at which boundary points are added
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPolyClenshawCurtisGrid()
Grid * sgpp::base::Grid::createPolyClenshawCurtisGrid (size_t dim, size_t degree) static
creates a poly grid with clenshaw curtis points
Parameters
dim the grid's dimension
degree the polynom's max. degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPolyGrid()
Grid * sgpp::base::Grid::createPolyGrid (size_t dim, size_t degree) static
creates a polynomial grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
degree the polynom's max. degree
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createPrewaveletGrid()
Grid * sgpp::base::Grid::createPrewaveletGrid (size_t dim) static
creates a prewavelet grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createSquareRootGrid()
Grid * sgpp::base::Grid::createSquareRootGrid (size_t dim) static
creates a square root grid (h-grid)
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createWaveletBoundaryGrid()
Grid * sgpp::base::Grid::createWaveletBoundaryGrid (size_t dim, level_t boundaryLevel = 1) static
creates a wavelet trapezoid boundary grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
boundaryLevel on which level the boundary grid points and basis functions should be added; the default is 1, which results in a grid with the same resolution on the boundary as on the main axis
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createWaveletGrid()
Grid * sgpp::base::Grid::createWaveletGrid (size_t dim) static
creates a wavelet grid
Level 4 sparse grid
"Hierarchical basis functions up to level 3"
Parameters
dim the grid's dimension
Returns
grid
Referenced by createGrid(), and createGridOfEquivalentType().
createWeaklyFundamentalNakSplineBoundaryGrid()
Grid * sgpp::base::Grid::createWeaklyFundamentalNakSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
Referenced by createGrid(), and createGridOfEquivalentType().
createWeaklyFundamentalSplineBoundaryGrid()
Grid * sgpp::base::Grid::createWeaklyFundamentalSplineBoundaryGrid (size_t dim, size_t degree, level_t boundaryLevel = 1) static
Referenced by createGrid(), and createGridOfEquivalentType().
getAlgorithmicDimensions()
std::vector< size_t > sgpp::base::Grid::getAlgorithmicDimensions ()
returns the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
Returns
the algorithmic dimensions
References sgpp::base::HashGridStorage::getAlgorithmicDimensions(), and storage.
Referenced by sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), and sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs().
getBasis()
virtual SBasis & sgpp::base::Grid::getBasis () pure virtual
Returns the Basis class associated with the grid.
Returns
Basis class associated with the grid
Implemented in sgpp::base::BsplineBoundaryGrid, sgpp::base::BsplineClenshawCurtisGrid, sgpp::base::BsplineGrid, sgpp::base::FundamentalNakSplineBoundaryGrid, sgpp::base::FundamentalSplineBoundaryGrid, sgpp::base::FundamentalSplineGrid, sgpp::base::LinearBoundaryGrid, sgpp::base::LinearClenshawCurtisBoundaryGrid, sgpp::base::LinearClenshawCurtisGrid, sgpp::base::LinearGrid, sgpp::base::LinearGridStencil, sgpp::base::LinearL0BoundaryGrid, sgpp::base::LinearStretchedBoundaryGrid, sgpp::base::LinearStretchedGrid, sgpp::base::LinearTruncatedBoundaryGrid, sgpp::base::ModBsplineClenshawCurtisGrid, sgpp::base::ModBsplineGrid, sgpp::base::ModFundamentalSplineGrid, sgpp::base::ModLinearClenshawCurtisGrid, sgpp::base::ModLinearGrid, sgpp::base::ModLinearGridStencil, sgpp::base::ModNakBsplineGrid, sgpp::base::ModPolyClenshawCurtisGrid, sgpp::base::ModPolyGrid, sgpp::base::ModWaveletGrid, sgpp::base::ModWeaklyFundamentalNakSplineGrid, sgpp::base::NakBsplineBoundaryGrid, sgpp::base::NakBsplineExtendedGrid, sgpp::base::NakBsplineGrid, sgpp::base::NakPBsplineGrid, sgpp::base::NaturalBsplineBoundaryGrid, sgpp::base::PeriodicGrid, sgpp::base::PolyBoundaryGrid, sgpp::base::PolyClenshawCurtisBoundaryGrid, sgpp::base::PolyClenshawCurtisGrid, sgpp::base::PolyGrid, sgpp::base::PrewaveletGrid, sgpp::base::SquareRootGrid, sgpp::base::WaveletBoundaryGrid, sgpp::base::WaveletGrid, sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid, and sgpp::base::WeaklyFundamentalSplineBoundaryGrid.
References insertPoint().
Referenced by sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::base::PredictiveRefinementIndicator::operator()(), sgpp::base::ForwardSelectorRefinementIndicator::update(), and sgpp::base::ImpurityRefinementIndicator::update().
getBoundingBox()
BoundingBox & sgpp::base::Grid::getBoundingBox () virtual
gets a reference to the GridStorage's BoundingsBox object
Returns
reference to the GridStorage's BoundingsBox object
References sgpp::base::HashGridStorage::getBoundingBox(), and storage.
Referenced by sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::pde::HeatEquationSolver::constructGrid(), sgpp::pde::PoissonEquationSolver::constructGrid(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadratureFunc(), sgpp::base::OperationQuadratureMC::doQuadratureL2Error(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::base::GridPrinter::printGrid(), and sgpp::pde::PDESolver::setGrid().
getDimension()
size_t sgpp::base::Grid::getDimension () const
Returns the number of dimensions.
Returns
the number of dimensions
References sgpp::base::HashGridStorage::getDimension(), and storage.
Referenced by clone(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadratureFunc(), sgpp::base::OperationQuadratureMC::doQuadratureL2Error(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensityRejectionSamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::LearnerBaseSP::dumpFunction(), sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), sgpp::datadriven::OperationDensityMargTo1D::margToDimXs(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::quadrature::OperationQuadratureMCAdvanced::OperationQuadratureMCAdvanced(), sgpp::base::GridPrinter::printGrid(), sgpp::base::GridPrinterForStretching::printGrid(), sgpp::base::GridPrinter::printGridDomain(), sgpp::base::GridPrinterForStretching::printGridDomainStretching(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), and sgpp::pde::PDESolver::setGrid().
getGenerator()
virtual GridGenerator & sgpp::base::Grid::getGenerator () pure virtual
Returns
reference to a GridGenerator object
Implemented in sgpp::base::BsplineBoundaryGrid, sgpp::base::BsplineClenshawCurtisGrid, sgpp::base::BsplineGrid, sgpp::base::FundamentalNakSplineBoundaryGrid, sgpp::base::FundamentalSplineBoundaryGrid, sgpp::base::FundamentalSplineGrid, sgpp::base::LinearBoundaryGrid, sgpp::base::LinearClenshawCurtisBoundaryGrid, sgpp::base::LinearClenshawCurtisGrid, sgpp::base::LinearGrid, sgpp::base::LinearGridStencil, sgpp::base::LinearL0BoundaryGrid, sgpp::base::LinearStretchedBoundaryGrid, sgpp::base::LinearStretchedGrid, sgpp::base::LinearTruncatedBoundaryGrid, sgpp::base::ModBsplineClenshawCurtisGrid, sgpp::base::ModBsplineGrid, sgpp::base::ModFundamentalSplineGrid, sgpp::base::ModLinearClenshawCurtisGrid, sgpp::base::ModLinearGrid, sgpp::base::ModLinearGridStencil, sgpp::base::ModNakBsplineGrid, sgpp::base::ModPolyClenshawCurtisGrid, sgpp::base::ModPolyGrid, sgpp::base::ModWaveletGrid, sgpp::base::ModWeaklyFundamentalNakSplineGrid, sgpp::base::NakBsplineBoundaryGrid, sgpp::base::NakBsplineExtendedGrid, sgpp::base::NakBsplineGrid, sgpp::base::NakPBsplineGrid, sgpp::base::NaturalBsplineBoundaryGrid, sgpp::base::PeriodicGrid, sgpp::base::PolyBoundaryGrid, sgpp::base::PolyClenshawCurtisBoundaryGrid, sgpp::base::PolyClenshawCurtisGrid, sgpp::base::PolyGrid, sgpp::base::PrewaveletGrid, sgpp::base::SquareRootGrid, sgpp::base::WaveletBoundaryGrid, sgpp::base::WaveletGrid, sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid, and sgpp::base::WeaklyFundamentalSplineBoundaryGrid.
Referenced by sgpp::pde::PDESolver::coarsenInitialGridSurplus(), sgpp::pde::HeatEquationSolver::constructGrid(), sgpp::pde::PoissonEquationSolver::constructGrid(), sgpp::pde::HeatEquationSolverWithStretching::constructGrid(), sgpp::datadriven::GridFactory::createGrid(), createGridOfEquivalentType(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::datadriven::LearnerBaseSP::InitializeGrid(), refine(), sgpp::pde::PDESolver::refineInitialGridSurplus(), sgpp::pde::PDESolver::refineInitialGridSurplusSubDomain(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevel(), sgpp::pde::PDESolver::refineInitialGridSurplusToMaxLevelSubDomain(), and sgpp::datadriven::LearnerBaseSP::train().
getSize()
size_t sgpp::base::Grid::getSize () const
Returns the number of points on the grid.
Returns
the number of points on the grid
References sgpp::base::HashGridStorage::getSize(), and storage.
Referenced by sgpp::pde::PDESolver::coarsenInitialGridSurplus(), python.uq.uq_setting.UQSetting.UQSetting::convert(), sgpp::datadriven::GridFactory::createGrid(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::getGridCoefficientsForCG(), sgpp::pde::PDESolver::getGridNormalDistribution(), sgpp::optimization::ASInterpolantScalarFunction::getSize(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::HeatEquationSolver::initGridWithSmoothHeat(), sgpp::pde::HeatEquationSolverWithStretching::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeatFullDomain(), sgpp::datadriven::LearnerBaseSP::InitializeGrid(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::OperationEllipticPDESolverSystemDirichlet(), sgpp::datadriven::LearnerBaseSP::predict(), sgpp::base::GridPrinter::printGrid(), sgpp::base::GridPrinterForStretching::printGrid(), sgpp::base::GridPrinter::printGridDomain(), sgpp::base::GridPrinterForStretching::printGridDomainStretching(), sgpp::datadriven::LearnerSGDEOnOffParallel::printGridSizeStatistics(), sgpp::base::GridPrinter::printLevelIndexGrid(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution(), and sgpp::datadriven::LearnerBaseSP::train().
getStorage()
GridStorage & sgpp::base::Grid::getStorage () virtual
gets a reference to the GridStorage object
Returns
reference to the GridStorage obeject
References storage.
Referenced by sgpp::solver::OperationParabolicPDESolverSystem::abortTimestep(), sgpp::datadriven::AlgorithmAdaBoostBase::AlgorithmAdaBoostBase(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorComplete(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::applyLOperatorInner(), sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::pde::HeatEquationSolver::constructGrid(), sgpp::pde::PoissonEquationSolver::constructGrid(), sgpp::pde::HeatEquationSolverWithStretching::constructGrid(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensityConditionalLinear::doConditional(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinearClenshawCurtisBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationModWeaklyFundamentalNakSpline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBspline::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNakBsplineExtended::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationNaturalBsplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWavelet::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWaveletBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationWeaklyFundamentalSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalSpline::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationModFundamentalSpline::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalSpline::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalSplineBoundary::doDehierarchisation(), sgpp::base::OperationHierarchisationModFundamentalSpline::doDehierarchisation(), sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationFundamentalSpline::doHierarchisation(), sgpp::base::OperationHierarchisationFundamentalSplineBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationModFundamentalSpline::doHierarchisation(), sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationFundamentalSpline::doHierarchisation(), sgpp::base::OperationHierarchisationFundamentalSplineBoundary::doHierarchisation(), sgpp::base::OperationHierarchisationModFundamentalSpline::doHierarchisation(), sgpp::datadriven::OperationDensityMarginalize::doMarginalize(), sgpp::datadriven::OperationDensityMarginalizeLinear::doMarginalize(), sgpp::base::OperationFirstMomentBspline::doQuadrature(), sgpp::base::OperationFirstMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationFirstMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModBspline::doQuadrature(), sgpp::base::OperationFirstMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentModPoly::doQuadrature(), sgpp::base::OperationFirstMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPoly::doQuadrature(), sgpp::base::OperationFirstMomentPolyBoundary::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationFirstMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBspline::doQuadrature(), sgpp::base::OperationSecondMomentBsplineBoundary::doQuadrature(), sgpp::base::OperationSecondMomentBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModBspline::doQuadrature(), sgpp::base::OperationSecondMomentModBsplineClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentModPoly::doQuadrature(), sgpp::base::OperationSecondMomentModPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPoly::doQuadrature(), sgpp::base::OperationSecondMomentPolyBoundary::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtis::doQuadrature(), sgpp::base::OperationSecondMomentPolyClenshawCurtisBoundary::doQuadrature(), sgpp::datadriven::AlgorithmAdaBoostBase::doRefinement(), sgpp::datadriven::OperationDensitySampling1DLinear::doSampling1D(), sgpp::datadriven::OperationInverseRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation1D(), sgpp::optimization::IterativeGridGenerator::evalFunction(), sgpp::optimization::IterativeGridGeneratorFuzzyRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate(), sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::optimization::IterativeGridGeneratorSOO::generate(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::generateb(), sgpp::solver::OperationParabolicPDESolverSystem::getGridStorage(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), sgpp::pde::OperationLaplaceBspline::mult(), sgpp::pde::OperationLaplaceBsplineBoundary::mult(), sgpp::pde::OperationLaplaceBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModBspline::mult(), sgpp::pde::OperationLaplaceModBsplineClenshawCurtis::mult(), sgpp::pde::OperationLaplaceModPoly::mult(), sgpp::pde::OperationLaplaceModPolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePoly::mult(), sgpp::pde::OperationLaplacePolyBoundary::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtis::mult(), sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBspline::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModBspline::mult(), sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotModLinear::mult(), sgpp::pde::OperationMatrixLTwoDotModPoly::mult(), sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPoly::mult(), sgpp::pde::OperationMatrixLTwoDotPolyBoundary::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis::mult(), sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary::mult(), sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::nextCandidates(), sgpp::pde::OperationEllipticPDESolverSystemDirichlet::OperationEllipticPDESolverSystemDirichlet(), sgpp::datadriven::OperationMultiEvalModMaskStreaming::OperationMultiEvalModMaskStreaming(), sgpp::datadriven::OperationMultiEvalStreaming::OperationMultiEvalStreaming(), sgpp::datadriven::OperationMultiEvalStreamingBSpline::OperationMultiEvalStreamingBSpline(), sgpp::datadriven::OperationMultiEvalStreamingBSplineOCL< T >::OperationMultiEvalStreamingBSplineOCL(), sgpp::datadriven::OperationMultipleEvalSubspaceCombined::OperationMultipleEvalSubspaceCombined(), sgpp::datadriven::MultipleClassRefinementFunctor::operator()(), sgpp::datadriven::OperationMultiEvalCuda::prepare(), sgpp::optimization::IterativeGridGenerator::printIterativeGridGenerator(), sgpp::base::GridPrinter::printLevelIndexGrid(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs(), sgpp::datadriven::MultipleClassRefinementFunctor::refine(), sgpp::base::MultipleClassRefinement::refineGridpoint(), sgpp::solver::OperationParabolicPDESolverSystem::saveAlpha(), sgpp::pde::PDESolver::setGrid(), and sgpp::optimization::IterativeGridGenerator::undoRefinement().
getStretching()
Stretching & sgpp::base::Grid::getStretching () virtual
gets a reference to the GridStorage's Stretching object
Returns
reference to the GridStorage's Stretching object
References sgpp::base::HashGridStorage::getStretching(), and storage.
Referenced by sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), sgpp::pde::HeatEquationSolverWithStretching::constructGrid(), and sgpp::base::GridPrinterForStretching::printGrid().
getType()
virtual sgpp::base::GridType sgpp::base::Grid::getType () pure virtual
Returns a string that identifies the grid type uniquely.
Returns
string that identifies the grid type uniquely
Implemented in sgpp::base::BsplineBoundaryGrid, sgpp::base::BsplineClenshawCurtisGrid, sgpp::base::BsplineGrid, sgpp::base::FundamentalNakSplineBoundaryGrid, sgpp::base::FundamentalSplineBoundaryGrid, sgpp::base::FundamentalSplineGrid, sgpp::base::LinearBoundaryGrid, sgpp::base::LinearClenshawCurtisBoundaryGrid, sgpp::base::LinearClenshawCurtisGrid, sgpp::base::LinearGrid, sgpp::base::LinearGridStencil, sgpp::base::LinearL0BoundaryGrid, sgpp::base::LinearStretchedBoundaryGrid, sgpp::base::LinearStretchedGrid, sgpp::base::LinearTruncatedBoundaryGrid, sgpp::base::ModBsplineClenshawCurtisGrid, sgpp::base::ModBsplineGrid, sgpp::base::ModFundamentalSplineGrid, sgpp::base::ModLinearClenshawCurtisGrid, sgpp::base::ModLinearGrid, sgpp::base::ModLinearGridStencil, sgpp::base::ModNakBsplineGrid, sgpp::base::ModPolyClenshawCurtisGrid, sgpp::base::ModPolyGrid, sgpp::base::ModWaveletGrid, sgpp::base::ModWeaklyFundamentalNakSplineGrid, sgpp::base::NakBsplineBoundaryGrid, sgpp::base::NakBsplineExtendedGrid, sgpp::base::NakBsplineGrid, sgpp::base::NakPBsplineGrid, sgpp::base::NaturalBsplineBoundaryGrid, sgpp::base::PeriodicGrid, sgpp::base::PolyBoundaryGrid, sgpp::base::PolyClenshawCurtisBoundaryGrid, sgpp::base::PolyClenshawCurtisGrid, sgpp::base::PolyGrid, sgpp::base::PrewaveletGrid, sgpp::base::SquareRootGrid, sgpp::base::WaveletBoundaryGrid, sgpp::base::WaveletGrid, sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid, and sgpp::base::WeaklyFundamentalSplineBoundaryGrid.
Referenced by sgpp::base::DirichletGridConverter::buildInnerGridWithCoefs(), createGridOfEquivalentType(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate(), getTypeAsString(), getZeroBoundaryType(), sgpp::base::HierarchisationSLE::HierarchisationSLE(), sgpp::optimization::IterativeGridGeneratorLinearSurplus::IterativeGridGeneratorLinearSurplus(), sgpp::base::DirichletGridConverter::rebuildInnerGridWithCoefs(), and serialize().
getTypeAsString()
std::string sgpp::base::Grid::getTypeAsString ()
Returns a string that identifies the grid type uniquely.
Returns
string that identifies the grid type uniquely
References getType().
getZeroBoundaryType()
GridType sgpp::base::Grid::getZeroBoundaryType ()
Returns the grid type that corresponds to the actual type but does no boundary treatment.
Returns
grid type
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, getType(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModLinearStencil, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::NaturalBsplineBoundary, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Prewavelet, sgpp::base::SquareRoot, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
insertPoint()
void sgpp::base::Grid::insertPoint (size_t dim, unsigned int levels[], unsigned int indices[], bool isLeaf)
Insert one point to the grid.
Parameters
dim dimension of the grid
levels array with levels of the point
indices array with indices of the point
isLeaf indicator whether the point is a leaf
References sgpp::base::HashGridStorage::insert(), sgpp::base::HashGridPoint::push(), sgpp::base::HashGridPoint::set(), and storage.
Referenced by python.uq.refinement.AdmissibleSet.AdmissibleSparseGridNodeSet::addCollocationNode(), python.uq.refinement.AdmissibleSet.RefinableNodesSet::create(), and getBasis().
nullFactory()
Grid * sgpp::base::Grid::nullFactory (std::istream &) static protected
Factory for everything we don't know.
refine()
void sgpp::base::Grid::refine (DataVector & vector, int numOfPoints)
Refine grid Refine the given number of points on the grid according to the vector.
Parameters
vector DataVector vector with errors for each basis function or alpha-vector
numOfPoints integer number of points to refine
References getGenerator(), and sgpp::base::GridGenerator::refine().
serialize() [1/3]
std::string sgpp::base::Grid::serialize (int version = SERIALIZATION_VERSION)
Serializes grid to a string.
Needed for Java compatibility.
Parameters
version the serialization version of the file
Returns
string into which the grid is written
References serialize().
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
serialize() [2/3]
void sgpp::base::Grid::serialize (std::ostream & ostr, int version = SERIALIZATION_VERSION) virtual
Serializes the grid.
Override if additional information need to be saved. Call base function before writing anything!
Parameters
ostr stream to which the grid is written
version the serialization version of the file
Reimplemented in sgpp::base::BsplineBoundaryGrid, sgpp::base::BsplineClenshawCurtisGrid, sgpp::base::BsplineGrid, sgpp::base::FundamentalNakSplineBoundaryGrid, sgpp::base::FundamentalSplineBoundaryGrid, sgpp::base::FundamentalSplineGrid, sgpp::base::LinearBoundaryGrid, sgpp::base::LinearClenshawCurtisBoundaryGrid, sgpp::base::LinearClenshawCurtisGrid, sgpp::base::ModBsplineClenshawCurtisGrid, sgpp::base::ModBsplineGrid, sgpp::base::ModFundamentalSplineGrid, sgpp::base::ModLinearClenshawCurtisGrid, sgpp::base::ModNakBsplineGrid, sgpp::base::ModPolyClenshawCurtisGrid, sgpp::base::ModPolyGrid, sgpp::base::ModWeaklyFundamentalNakSplineGrid, sgpp::base::NakBsplineBoundaryGrid, sgpp::base::NakBsplineExtendedGrid, sgpp::base::NakBsplineGrid, sgpp::base::NakPBsplineGrid, sgpp::base::NaturalBsplineBoundaryGrid, sgpp::base::PolyBoundaryGrid, sgpp::base::PolyClenshawCurtisBoundaryGrid, sgpp::base::PolyClenshawCurtisGrid, sgpp::base::PolyGrid, sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid, and sgpp::base::WeaklyFundamentalSplineBoundaryGrid.
References getType(), sgpp::base::HashGridStorage::serialize(), and storage.
Referenced by python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), and python.utils.GzipSerializer.GzipSerializer::serializeToFile().
serialize() [3/3]
void sgpp::base::Grid::serialize (std::string & ostr, int version = SERIALIZATION_VERSION)
Serializes grid to a string.
Needed for Python compatibility. Calls serialize(std::ostream&).
Parameters
ostr string into which the grid is written
version the serialization version of the file
References serialize().
Referenced by sgpp::pde::PDESolver::getGrid(), sgpp::datadriven::LearnerBaseSP::LearnerBaseSP(), sgpp::datadriven::OperationMultiEvalHPX::mult(), serialize(), sgpp::base::BsplineBoundaryGrid::serialize(), sgpp::base::BsplineClenshawCurtisGrid::serialize(), sgpp::base::BsplineGrid::serialize(), sgpp::base::FundamentalNakSplineBoundaryGrid::serialize(), sgpp::base::FundamentalSplineBoundaryGrid::serialize(), sgpp::base::FundamentalSplineGrid::serialize(), sgpp::base::LinearBoundaryGrid::serialize(), sgpp::base::LinearClenshawCurtisBoundaryGrid::serialize(), sgpp::base::LinearClenshawCurtisGrid::serialize(), sgpp::base::ModBsplineClenshawCurtisGrid::serialize(), sgpp::base::ModBsplineGrid::serialize(), sgpp::base::ModFundamentalSplineGrid::serialize(), sgpp::base::ModLinearClenshawCurtisGrid::serialize(), sgpp::base::ModNakBsplineGrid::serialize(), sgpp::base::ModPolyClenshawCurtisGrid::serialize(), sgpp::base::ModPolyGrid::serialize(), sgpp::base::ModWeaklyFundamentalNakSplineGrid::serialize(), sgpp::base::NakBsplineBoundaryGrid::serialize(), sgpp::base::NakBsplineExtendedGrid::serialize(), sgpp::base::NakBsplineGrid::serialize(), sgpp::base::NakPBsplineGrid::serialize(), sgpp::base::NaturalBsplineBoundaryGrid::serialize(), sgpp::base::PolyBoundaryGrid::serialize(), sgpp::base::PolyClenshawCurtisBoundaryGrid::serialize(), sgpp::base::PolyClenshawCurtisGrid::serialize(), sgpp::base::PolyGrid::serialize(), sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid::serialize(), sgpp::base::WeaklyFundamentalSplineBoundaryGrid::serialize(), serialize(), python.learner.formatter.GridFormatter.GridFormatter::serializeToFile(), python.learner.formatter.LearnedKnowledgeFormatter.LearnedKnowledgeFormatter::serializeToFile(), python.learner.formatter.LearnerFormatter.LearnerFormatter::serializeToFile(), python.uq.analysis.asgc.ASGCKnowledgeFormatter.ASGCKnowledgeFormatter::serializeToFile(), python.uq.sampler.asgc.ASGCSamplerFormatter.ASGCSamplerFormatter::serializeToFile(), python.uq.uq_setting.UQSettingFormatter.UQSettingFormatter::serializeToFile(), python.utils.GzipSerializer.GzipSerializer::serializeToFile(), and sgpp::datadriven::ModelFittingBaseSingleGrid::storeFitter().
setAlgorithmicDimensions()
void sgpp::base::Grid::setAlgorithmicDimensions (std::vector< size_t > newAlgoDims)
sets the algorithmic dimensions (the dimensions in which the Up Down operations should be applied)
Parameters
newAlgoDims std::vector containing the algorithmic dimensions
References sgpp::base::HashGridStorage::setAlgorithmicDimensions(), and storage.
setBoundingBox()
void sgpp::base::Grid::setBoundingBox (BoundingBox & boundingBox) virtual
sets the GridStorage's BoundingsBox
References sgpp::base::HashGridStorage::setBoundingBox(), and storage.
setStretching()
void sgpp::base::Grid::setStretching (Stretching & stretching) virtual
sets the GridStorage's Stretching pointer to a Stretching object
Parameters
stretching pointer to the GridStorage's Stretching object
References sgpp::base::HashGridStorage::setStretching(), and storage.
stringToGridType()
GridType sgpp::base::Grid::stringToGridType (const std::string & gridType) static
Conversion from string to grid type.
Parameters
gridType grid type as a string
Returns
actual grid type
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModLinearStencil, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::NaturalBsplineBoundary, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Prewavelet, sgpp::base::SquareRoot, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
Referenced by sgpp::datadriven::SparseGridDensityEstimatorConfiguration::SparseGridDensityEstimatorConfiguration().
unserialize() [1/2]
Grid * sgpp::base::Grid::unserialize (const std::string & istr) static
reads a grid out of a string
Parameters
istr string that contains the grid information
Returns
grid
References unserialize().
Referenced by createGrid(), sgpp::datadriven::LearnerSGDE::createRegularGrid(), sgpp::datadriven::LearnerBase::LearnerBase(), sgpp::datadriven::LearnerBaseSP::LearnerBaseSP(), sgpp::datadriven::MultipleEvalHPX::LocalityMultiplier::LocalityMultiplier(), sgpp::pde::PDESolver::setGrid(), unserialize(), and unserializeFromFile().
unserialize() [2/2]
Grid * sgpp::base::Grid::unserialize (std::istream & istr) static
reads a grid out of a stream
Parameters
istr inputstream that contains the grid information
Returns
grid
unserializeFromFile()
Grid * sgpp::base::Grid::unserializeFromFile (std::string filename) static
opens a file given by name and reads a grid out of the stored string @ param filename name of the file
Returns
grid
References unserialize().
Referenced by sgpp::optimization::SplineResponseSurfaceVector::SplineResponseSurfaceVector().
Member Data Documentation
storage
GridStorage sgpp::base::Grid::storage protected
GridStorage object of the grid.
Referenced by sgpp::base::BsplineClenshawCurtisGrid::BsplineClenshawCurtisGrid(), clone(), getAlgorithmicDimensions(), getBoundingBox(), getDimension(), getSize(), getStorage(), getStretching(), insertPoint(), sgpp::base::LinearClenshawCurtisBoundaryGrid::LinearClenshawCurtisBoundaryGrid(), sgpp::base::LinearClenshawCurtisGrid::LinearClenshawCurtisGrid(), sgpp::base::ModBsplineClenshawCurtisGrid::ModBsplineClenshawCurtisGrid(), sgpp::base::ModLinearClenshawCurtisGrid::ModLinearClenshawCurtisGrid(), sgpp::base::ModPolyClenshawCurtisGrid::ModPolyClenshawCurtisGrid(), sgpp::base::PolyClenshawCurtisBoundaryGrid::PolyClenshawCurtisBoundaryGrid(), sgpp::base::PolyClenshawCurtisGrid::PolyClenshawCurtisGrid(), serialize(), setAlgorithmicDimensions(), setBoundingBox(), and setStretching().
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/Grid.hpp
base/src/sgpp/base/grid/Grid.cpp