SG++-Doxygen-Documentation: sgpp::base::sweep< FUNC > Class Template Reference
sgpp::base::sweep< FUNC > Class Template Reference
Standard sweep operation FUNC should be a class with overwritten operator().
#include <sweep.hpp>
Public Member Functions
sweep (FUNC &functor, GridStorage &storage)
Create a new sweep object with a copied functor.
sweep (GridStorage &storage)
Create a new sweep object with a default constructed functor.
void sweep1D (DataMatrix &source, DataMatrix &result, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep1D (DataVector &source, DataVector &result, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep1D_Boundary (DataMatrix &source, DataMatrix &result, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep1D_Boundary (DataVector &source, DataVector &result, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
~sweep ()
Destructor.
Protected Types
typedef GridStorage::grid_iterator grid_iterator
Protected Member Functions
void sweep_Boundary_rec (DataMatrix &source, DataMatrix &result, grid_iterator &index, std::vector< size_t > &dim_list, size_t dim_rem, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep_Boundary_rec (DataVector &source, DataVector &result, grid_iterator &index, std::vector< size_t > &dim_list, size_t dim_rem, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep_rec (DataMatrix &source, DataMatrix &result, grid_iterator &index, std::vector< size_t > &dim_list, size_t dim_rem, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
void sweep_rec (DataVector &source, DataVector &result, grid_iterator &index, std::vector< size_t > &dim_list, size_t dim_rem, size_t dim_sweep)
Descends on all dimensions beside dim_sweep.
Protected Attributes
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
FUNC functor
Object of FUNC, this is executed by sweep.
const size_t numAlgoDims_
number of algorithmic dimensions
GridStorage & storage
Pointer to the grid's storage object.
Detailed Description
template<class FUNC>
class sgpp::base::sweep< FUNC >
Standard sweep operation FUNC should be a class with overwritten operator().
For an example see laplace_up_functor in laplace.hpp. It must be default constructable or copyable. STORAGE must provide a grid_iterator supporting left_child, step_right, up, hint and seq.
Member Typedef Documentation
grid_iterator
template<class FUNC > typedef GridStorage::grid_iterator sgpp::base::sweep< FUNC >::grid_iterator protected
Constructor & Destructor Documentation
sweep() [1/2]
template<class FUNC > sgpp::base::sweep< FUNC >::sweep (GridStorage & storage) inline explicit
Create a new sweep object with a default constructed functor.
Parameters
storage the storage that contains the grid points
sweep() [2/2]
template<class FUNC > sgpp::base::sweep< FUNC >::sweep (FUNC & functor, GridStorage & storage) inline
Create a new sweep object with a copied functor.
Parameters
functor the functor that is executed on the grid
storage the storage that contains the grid points
~sweep()
template<class FUNC > sgpp::base::sweep< FUNC >::~sweep () inline
Destructor.
Member Function Documentation
sweep1D() [1/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep1D (DataMatrix & source, DataMatrix & result, size_t dim_sweep) inline
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep Boundaries are not regarded
Parameters
source a DataMatrix containing the source coefficients of the grid points
result a DataMatrix containing the result coefficients of the grid points
dim_sweep the dimension in which the functor is executed
References sgpp::base::sweep< FUNC >::numAlgoDims_, sgpp::base::sweep< FUNC >::storage, and sgpp::base::sweep< FUNC >::sweep_rec().
sweep1D() [2/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep1D (DataVector & source, DataVector & result, size_t dim_sweep) inline
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep Boundaries are not regarded
Parameters
source a DataVector containing the source coefficients of the grid points
result a DataVector containing the result coefficients of the grid points
dim_sweep the dimension in which the functor is executed
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::sweep< FUNC >::storage, and sgpp::base::sweep< FUNC >::sweep_rec().
Referenced by sgpp::base::OperationHierarchisationPrewavelet::doDehierarchisation(), sgpp::base::OperationHierarchisationPrewavelet::doHierarchisation(), sgpp::pde::OperationLaplaceEnhancedLinear::down(), sgpp::pde::OperationLaplaceLinear::down(), sgpp::pde::OperationLaplaceLinearStretched::down(), sgpp::pde::OperationLaplaceModLinear::down(), sgpp::pde::OperationLTwoDotProductLinear::down(), sgpp::pde::OperationLTwoDotProductLinearStretched::down(), sgpp::pde::OperationLaplaceModLinear::downOpDim(), sgpp::pde::OperationLaplacePrewavelet::downOpDim(), sgpp::pde::OperationLaplaceEnhancedLinear::up(), sgpp::pde::OperationLaplaceLinear::up(), sgpp::pde::OperationLaplaceLinearStretched::up(), sgpp::pde::OperationLaplaceModLinear::up(), sgpp::pde::OperationLaplacePrewavelet::up(), sgpp::pde::OperationLTwoDotProductLinear::up(), sgpp::pde::OperationLTwoDotProductLinearStretched::up(), sgpp::pde::OperationLaplaceModLinear::upOpDim(), and sgpp::pde::OperationLaplacePrewavelet::upOpDim().
sweep1D_Boundary() [1/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep1D_Boundary (DataMatrix & source, DataMatrix & result, size_t dim_sweep) inline
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep Boundaries are regarded
Parameters
source a DataMatrix containing the source coefficients of the grid points
result a DataMatrix containing the result coefficients of the grid points
dim_sweep the dimension in which the functor is executed
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridIterator::resetToLevelZero(), sgpp::base::sweep< FUNC >::storage, and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
sweep1D_Boundary() [2/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep1D_Boundary (DataVector & source, DataVector & result, size_t dim_sweep) inline
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep Boundaries are regarded
Parameters
source a DataVector containing the source coefficients of the grid points
result a DataVector containing the result coefficients of the grid points
dim_sweep the dimension in which the functor is executed
References sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridIterator::resetToLevelZero(), sgpp::base::sweep< FUNC >::storage, and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
Referenced by sgpp::pde::OperationLaplaceEnhancedLinearBoundary::down(), sgpp::pde::OperationLaplaceLinearBoundary::down(), sgpp::pde::OperationLaplaceLinearStretchedBoundary::down(), sgpp::pde::OperationLTwoDotProductLinearBoundary::down(), sgpp::pde::OperationLTwoDotProductLinearStretchedBoundary::down(), sgpp::pde::OperationLaplaceEnhancedLinearBoundary::up(), sgpp::pde::OperationLaplaceLinearBoundary::up(), sgpp::pde::OperationLaplaceLinearStretchedBoundary::up(), sgpp::pde::OperationLTwoDotProductLinearBoundary::up(), and sgpp::pde::OperationLTwoDotProductLinearStretchedBoundary::up().
sweep_Boundary_rec() [1/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep_Boundary_rec (DataMatrix & source, DataMatrix & result, grid_iterator & index, std::vector< size_t > & dim_list, size_t dim_rem, size_t dim_sweep) inline protected
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep. Boundaries are regarded
Parameters
source coefficients of the sparse grid
result coefficients of the function computed by sweep
index current grid position
dim_list list of dimensions, that should be handled
dim_rem number of remaining dims
dim_sweep static dimension, in this dimension the functor is executed
References sgpp::base::sweep< FUNC >::functor, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), sgpp::base::sweep< FUNC >::storage, sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::HashGridIterator::up().
sweep_Boundary_rec() [2/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep_Boundary_rec (DataVector & source, DataVector & result, grid_iterator & index, std::vector< size_t > & dim_list, size_t dim_rem, size_t dim_sweep) inline protected
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep. Boundaries are regarded
Parameters
source coefficients of the sparse grid
result coefficients of the function computed by sweep
index current grid position
dim_list list of dimensions, that should be handled
dim_rem number of remaining dims
dim_sweep static dimension, in this dimension the functor is executed
References sgpp::base::sweep< FUNC >::functor, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), sgpp::base::sweep< FUNC >::storage, sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::HashGridIterator::up().
Referenced by sgpp::base::sweep< FUNC >::sweep1D_Boundary(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), and sgpp::base::sweep< FUNC >::sweep_Boundary_rec().
sweep_rec() [1/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep_rec (DataMatrix & source, DataMatrix & result, grid_iterator & index, std::vector< size_t > & dim_list, size_t dim_rem, size_t dim_sweep) inline protected
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep. Boundaries are not regarded
Parameters
source coefficients of the sparse grid
result coefficients of the function computed by sweep
index current grid position
dim_list list of dimensions, that should be handled
dim_rem number of remaining dims
dim_sweep static dimension, in this dimension the functor is executed
References sgpp::base::sweep< FUNC >::functor, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), sgpp::base::sweep< FUNC >::storage, sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::HashGridIterator::up().
sweep_rec() [2/2]
template<class FUNC > void sgpp::base::sweep< FUNC >::sweep_rec (DataVector & source, DataVector & result, grid_iterator & index, std::vector< size_t > & dim_list, size_t dim_rem, size_t dim_sweep) inline protected
Descends on all dimensions beside dim_sweep.
Class functor for dim_sweep. Boundaries are not regarded
Parameters
source coefficients of the sparse grid
result coefficients of the function computed by sweep
index current grid position
dim_list list of dimensions, that should be handled
dim_rem number of remaining dims
dim_sweep static dimension, in this dimension the functor is executed
References sgpp::base::sweep< FUNC >::functor, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), sgpp::base::sweep< FUNC >::storage, sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::HashGridIterator::up().
Referenced by sgpp::base::sweep< FUNC >::sweep1D(), sgpp::base::sweep< FUNC >::sweep1D(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
Member Data Documentation
algoDims
template<class FUNC > const std::vector<size_t> sgpp::base::sweep< FUNC >::algoDims protected
algorithmic dimensions, operator is applied in this dimensions
functor
template<class FUNC > FUNC sgpp::base::sweep< FUNC >::functor protected
Object of FUNC, this is executed by sweep.
Referenced by sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
numAlgoDims_
template<class FUNC > const size_t sgpp::base::sweep< FUNC >::numAlgoDims_ protected
number of algorithmic dimensions
Referenced by sgpp::base::sweep< FUNC >::sweep1D().
storage
template<class FUNC > GridStorage& sgpp::base::sweep< FUNC >::storage protected
Pointer to the grid's storage object.
Referenced by sgpp::base::sweep< FUNC >::sweep1D(), sgpp::base::sweep< FUNC >::sweep1D(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), sgpp::base::sweep< FUNC >::sweep1D_Boundary(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_Boundary_rec(), sgpp::base::sweep< FUNC >::sweep_rec(), and sgpp::base::sweep< FUNC >::sweep_rec().
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/sweep.hpp