SG++-Doxygen-Documentation: sgpp::datadriven::Scorer Class Reference
sgpp::datadriven::Scorer Class Reference
Base class for supervised learning used to fit a model and quantify accuracy using a sgpp::datadriven::Metric with either testing or cross validation.
#include <Scorer.hpp>
Public Member Functions
Scorer & operator= (const Scorer &rhs)=delete
Scorer & operator= (Scorer &&rhs)=default
Move assign operator.
Scorer (Metric *metric)
Constructor.
Scorer (Scorer &&rhs)=default
Move constructor.
double test (ModelFittingBase &model, Dataset &testDataset, bool lowerIsBetter=false)
evaluate the accuracy on the test set using the sgpp::datadriven::Metric.
~Scorer ()=default
Destructor.
Detailed Description
Base class for supervised learning used to fit a model and quantify accuracy using a sgpp::datadriven::Metric with either testing or cross validation.
Splits a dataset into testing and training parts, trains the model and measures the accuracy.
Constructor & Destructor Documentation
Scorer() [1/2]
sgpp::datadriven::Scorer::Scorer (Metric * metric) explicit
Constructor.
Parameters
metric sgpp::datadriven::Metric to to quantify approximation quality of a trained model. Scorer will take ownership of this object. puts a random seed.
Scorer() [2/2]
sgpp::datadriven::Scorer::Scorer (Scorer && rhs) default
Move constructor.
Parameters
rhs R-value reference to a scorer object to moved from.
~Scorer()
sgpp::datadriven::Scorer::~Scorer () default
Destructor.
Member Function Documentation
operator=() [1/2]
Scorer & sgpp::datadriven::Scorer::operator= (const Scorer & rhs) delete
operator=() [2/2]
Scorer & sgpp::datadriven::Scorer::operator= (Scorer && rhs) default
Move assign operator.
Parameters
rhs R-value reference to an a scorer object to move from.
Returns
rerefernce to this with updated values.
test()
double sgpp::datadriven::Scorer::test (ModelFittingBase & model, Dataset & testDataset, bool lowerIsBetter = false)
evaluate the accuracy on the test set using the sgpp::datadriven::Metric.
Parameters
model model to be fitted based on the train dataset.
testDataset dataset used quantify accuracy using sgpp::datadriven::Metric.
lowerIsBetter sets up the metric so that a lower score indicates a better result
Returns
accuracy of the fit.
References sgpp::datadriven::ModelFittingBase::evaluate(), sgpp::datadriven::Dataset::getData(), sgpp::datadriven::ModelFittingBase::getFitterConfiguration(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::datadriven::FitterConfiguration::getParallelConfig(), sgpp::datadriven::Dataset::getTargets(), and sgpp::datadriven::ParallelConfiguration::scalapackEnabled_.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/scoring/Scorer.hpp
datadriven/src/sgpp/datadriven/datamining/modules/scoring/Scorer.cpp