SG++-Doxygen-Documentation: sgpp::base::OperationEvalGradientFundamentalNakSplineNaive Class Reference
sgpp::base::OperationEvalGradientFundamentalNakSplineNaive Class Reference
Operation for evaluating fundamental not-a-knot spline linear combinations and their gradients.
#include <OperationEvalGradientFundamentalNakSplineNaive.hpp>
Public Member Functions
void evalGradient (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient) override
double evalGradient (const DataVector &alpha, const DataVector &point, DataVector &gradient) override
OperationEvalGradientFundamentalNakSplineNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalGradientFundamentalNakSplineNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalGradient
OperationEvalGradient ()
Constructor.
virtual ~OperationEvalGradient ()
Destructor.
Protected Attributes
SFundamentalNakSplineBase base
1D fundamental not-a-knot spline basis
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalGradient
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating fundamental not-a-knot spline linear combinations and their gradients.
Constructor & Destructor Documentation
OperationEvalGradientFundamentalNakSplineNaive()
sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::OperationEvalGradientFundamentalNakSplineNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree fundamental not-a-knot spline degree
~OperationEvalGradientFundamentalNakSplineNaive()
sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::~OperationEvalGradientFundamentalNakSplineNaive () inline override
Destructor.
Member Function Documentation
evalGradient() [1/2]
void sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
Reimplemented from sgpp::base::OperationEvalGradient.
References alpha, base, sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalGradient() [2/2]
double sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::evalGradient (const DataVector & alpha, const DataVector & point, DataVector & gradient) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient of linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalGradient.
References sgpp::base::DataVector::add(), alpha, base, sgpp::base::FundamentalNakSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalNakSplineBasis< LT, IT >::evalDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SFundamentalNakSplineBase sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::base protected
1D fundamental not-a-knot spline basis
Referenced by evalGradient(), and evalGradient().
innerDerivative
DataVector sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalGradient(), and evalGradient().
pointInUnitCube
DataVector sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalGradient(), and evalGradient().
storage
GridStorage& sgpp::base::OperationEvalGradientFundamentalNakSplineNaive::storage protected
storage of the sparse grid
Referenced by evalGradient(), and evalGradient().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalGradientFundamentalNakSplineNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalGradientFundamentalNakSplineNaive.cpp