SG++-Doxygen-Documentation: sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary Class Reference
sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary Class Reference
Implementation of the application of a diagonal matrix to a DataVector for regularization.
#include <OperationRegularizationDiagonalLinearBoundary.hpp>
Public Member Functions
OperationRegularizationDiagonalLinearBoundary (base::GridStorage *storage, int mode, double k)
Constructor of OperationRegularizationDiagonalLinearBoundary.
Public Member Functions inherited from sgpp::datadriven::OperationRegularizationDiagonal
virtual void mult (base::DataVector &alpha, base::DataVector &result)
Multiplication with diagonal matrix.
OperationRegularizationDiagonal (base::GridStorage *storage, int mode, double k)
Constructor of OperationRegularizationDiagonal.
virtual ~OperationRegularizationDiagonal ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
virtual void initH0HkLaplace (double k)
Initialize H0HkLaplace.
virtual void initHkmix (double k)
Initialize Hkmix.
Protected Member Functions inherited from sgpp::datadriven::OperationRegularizationDiagonal
virtual void init ()
Check for mode and run corresponding init.
virtual void initAnisotropicPenalty ()
Initialize ANISOTROPIC_PENALTY, ignores constructor parameter k.
virtual void initIsotropicPenalty ()
Initialize ISOTROPIC_PENALTY, ignores constructor parameter k.
Additional Inherited Members
Static Public Attributes inherited from sgpp::datadriven::OperationRegularizationDiagonal
static const int ANISOTROPIC_PENALTY = 4
static const int H0HKLAPLACE = 2
Diagonal scaling for pseudo-laplace, replacing \(L_2\) with \(H^0\) in 1d.
static const int HKMIX = 1
Diagonal scaling for \(H^k_\textbf{mix}\)-norm (product of \(H^k\) 1D norms)
static const int ISOTROPIC_PENALTY = 3
Protected Attributes inherited from sgpp::datadriven::OperationRegularizationDiagonal
base::DataVector diagonal
double k
int mode
size_t size
base::GridStorage * storage
Detailed Description
Implementation of the application of a diagonal matrix to a DataVector for regularization.
This class implements several scaling possibilities for piecewise linear basis functions with and without boundaries.
Constructor & Destructor Documentation
OperationRegularizationDiagonalLinearBoundary()
sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::OperationRegularizationDiagonalLinearBoundary (base::GridStorage * storage, int mode, double k)
Constructor of OperationRegularizationDiagonalLinearBoundary.
Parameters
storage Pointer to grid's storage object
mode Mode, specifying which regularization to use. Example: OperationRegularizationDiagonal::HKMIX.
k Parameter for \(H^k\)
References sgpp::datadriven::OperationRegularizationDiagonal::init().
Member Function Documentation
initH0HkLaplace()
void sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initH0HkLaplace (double k) protected virtual
Initialize H0HkLaplace.
Parameters
k Parameter k
Implements sgpp::datadriven::OperationRegularizationDiagonal.
References sgpp::datadriven::OperationRegularizationDiagonal::diagonal, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::datadriven::OperationRegularizationDiagonal::k, sgpp::datadriven::OperationRegularizationDiagonal::size, and sgpp::datadriven::OperationRegularizationDiagonal::storage.
initHkmix()
void sgpp::datadriven::OperationRegularizationDiagonalLinearBoundary::initHkmix (double k) protected virtual
Initialize Hkmix.
Parameters
k Parameter k
Implements sgpp::datadriven::OperationRegularizationDiagonal.
References sgpp::datadriven::OperationRegularizationDiagonal::diagonal, sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::datadriven::OperationRegularizationDiagonal::k, sgpp::datadriven::OperationRegularizationDiagonal::size, and sgpp::datadriven::OperationRegularizationDiagonal::storage.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRegularizationDiagonalLinearBoundary.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationRegularizationDiagonalLinearBoundary.cpp