SG++-Doxygen-Documentation: sgpp::base::LinearLoadBalancer Class Reference
sgpp::base::LinearLoadBalancer Class Reference
#include <LinearLoadBalancer.hpp>
Public Member Functions
void getPartitionSegments (size_t start, size_t end, size_t blockSize, size_t *segmentStart, size_t *segmentEnd)
LinearLoadBalancer (std::shared_ptr< OCLManager > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters)
void update (double *timings)
~LinearLoadBalancer ()
Constructor & Destructor Documentation
LinearLoadBalancer()
sgpp::base::LinearLoadBalancer::LinearLoadBalancer (std::shared_ptr< OCLManager > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters) inline
~LinearLoadBalancer()
sgpp::base::LinearLoadBalancer::~LinearLoadBalancer () inline
Member Function Documentation
getPartitionSegments()
void sgpp::base::LinearLoadBalancer::getPartitionSegments (size_t start, size_t end, size_t blockSize, size_t * segmentStart, size_t * segmentEnd) inline
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::mult(), and sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::multTranspose().
update()
void sgpp::base::LinearLoadBalancer::update (double * timings) inline
Referenced by sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::mult(), sgpp::datadriven::StreamingBSplineOCLKernelImpl< real_type >::multTranspose(), python.uq.refinement.RefinementStrategy.Ranking::rank(), and python.learner.LearnedKnowledge.LearnedKnowledge::setMemento().
The documentation for this class was generated from the following file:
base/src/sgpp/base/opencl/LinearLoadBalancer.hpp