SG++-Doxygen-Documentation: sgpp::base::OperationHierarchisation Class Reference
sgpp::base::OperationHierarchisation Class Reference abstract
This class implements the hierarchisation and dehierarchisation on the sparse grid.
#include <OperationHierarchisation.hpp>
Public Member Functions
virtual void doDehierarchisation (DataVector &alpha)=0
Implements the dehierarchisation on a sparse grid.
virtual void doHierarchisation (DataVector &node_values)=0
Implements the hierarchisation on a sparse grid.
OperationHierarchisation ()
Constructor.
virtual ~OperationHierarchisation ()
Destructor.
Detailed Description
This class implements the hierarchisation and dehierarchisation on the sparse grid.
Constructor & Destructor Documentation
OperationHierarchisation()
sgpp::base::OperationHierarchisation::OperationHierarchisation () inline
Constructor.
~OperationHierarchisation()
virtual sgpp::base::OperationHierarchisation::~OperationHierarchisation () inline virtual
Destructor.
Member Function Documentation
doDehierarchisation()
virtual void sgpp::base::OperationHierarchisation::doDehierarchisation (DataVector & alpha) pure virtual
Implements the dehierarchisation on a sparse grid.
Parameters
alpha the coefficients of the sparse grid's basis functions
Implemented in sgpp::base::OperationArbitraryBoundaryHierarchisation, sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary, sgpp::base::OperationHierarchisationFundamentalSpline, sgpp::base::OperationHierarchisationFundamentalSplineBoundary, sgpp::base::OperationHierarchisationLinear, sgpp::base::OperationHierarchisationLinearBoundary, sgpp::base::OperationHierarchisationLinearClenshawCurtis, sgpp::base::OperationHierarchisationLinearClenshawCurtisBoundary, sgpp::base::OperationHierarchisationLinearStretched, sgpp::base::OperationHierarchisationLinearStretchedBoundary, sgpp::base::OperationHierarchisationModBspline, sgpp::base::OperationHierarchisationModFundamentalSpline, sgpp::base::OperationHierarchisationModLinear, sgpp::base::OperationHierarchisationModLinearClenshawCurtis, sgpp::base::OperationHierarchisationModPoly, sgpp::base::OperationHierarchisationModPolyClenshawCurtis, sgpp::base::OperationHierarchisationModWavelet, sgpp::base::OperationHierarchisationPoly, sgpp::base::OperationHierarchisationPolyBoundary, sgpp::base::OperationHierarchisationPolyClenshawCurtis, sgpp::base::OperationHierarchisationPolyClenshawCurtisBoundary, sgpp::base::OperationHierarchisationPrewavelet, sgpp::base::OperationStencilHierarchisationLinear, sgpp::base::OperationStencilHierarchisationModLinear, and sgpp::base::OperationStencilHierarchisation.
Referenced by sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForSC().
doHierarchisation()
virtual void sgpp::base::OperationHierarchisation::doHierarchisation (DataVector & node_values) pure virtual
Implements the hierarchisation on a sparse grid.
Parameters
node_values the function's values in the nodal basis
Implemented in sgpp::base::OperationArbitraryBoundaryHierarchisation, sgpp::base::OperationHierarchisationFundamentalNakSplineBoundary, sgpp::base::OperationHierarchisationFundamentalSpline, sgpp::base::OperationHierarchisationFundamentalSplineBoundary, sgpp::base::OperationHierarchisationLinear, sgpp::base::OperationHierarchisationLinearBoundary, sgpp::base::OperationHierarchisationLinearClenshawCurtis, sgpp::base::OperationHierarchisationLinearClenshawCurtisBoundary, sgpp::base::OperationHierarchisationLinearStretched, sgpp::base::OperationHierarchisationLinearStretchedBoundary, sgpp::base::OperationHierarchisationModBspline, sgpp::base::OperationHierarchisationModFundamentalSpline, sgpp::base::OperationHierarchisationModLinear, sgpp::base::OperationHierarchisationModLinearClenshawCurtis, sgpp::base::OperationHierarchisationModPoly, sgpp::base::OperationHierarchisationModPolyClenshawCurtis, sgpp::base::OperationHierarchisationModWavelet, sgpp::base::OperationHierarchisationPoly, sgpp::base::OperationHierarchisationPolyBoundary, sgpp::base::OperationHierarchisationPolyClenshawCurtis, sgpp::base::OperationHierarchisationPolyClenshawCurtisBoundary, sgpp::base::OperationHierarchisationPrewavelet, sgpp::base::OperationStencilHierarchisationLinear, sgpp::base::OperationStencilHierarchisationModLinear, and sgpp::base::OperationStencilHierarchisation.
Referenced by sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::HeatEquationSolver::initGridWithSmoothHeat(), sgpp::pde::HeatEquationSolverWithStretching::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), and sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeatFullDomain().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationHierarchisation.hpp