SG++-Doxygen-Documentation: sgpp::base::OperationEvalLinearNaive Class Reference
sgpp::base::OperationEvalLinearNaive Class Reference
#include <OperationEvalLinearNaive.hpp>
Public Member Functions
void eval (const DataMatrix &alpha, const DataVector &point, DataVector &value) override
double eval (const DataVector &alpha, const DataVector &point) override
OperationEvalLinearNaive (GridStorage &storage)
Constructor.
~OperationEvalLinearNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEval
OperationEval ()
Default constructor.
virtual ~OperationEval ()
Destructor.
Protected Attributes
SLinearBase base
1D linear basis
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Constructor & Destructor Documentation
OperationEvalLinearNaive()
sgpp::base::OperationEvalLinearNaive::OperationEvalLinearNaive (GridStorage & storage) inline explicit
Constructor.
Parameters
storage storage of the sparse grid
~OperationEvalLinearNaive()
sgpp::base::OperationEvalLinearNaive::~OperationEvalLinearNaive () inline override
Destructor.
Member Function Documentation
eval() [1/2]
void sgpp::base::OperationEvalLinearNaive::eval (const DataMatrix & alpha, const DataVector & point, DataVector & value) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of linear combination
Reimplemented from sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), m, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
eval() [2/2]
double sgpp::base::OperationEvalLinearNaive::eval (const DataVector & alpha, const DataVector & point) override virtual
Parameters
alpha coefficient vector
point evaluation point
Returns
value of the linear combination
Implements sgpp::base::OperationEval.
References alpha, base, sgpp::base::LinearBasis< LT, IT >::eval(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), pointInUnitCube, storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Referenced by sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), sgpp::optimization::OperationMultipleHierarchisationLinear::doDehierarchisation(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
Member Data Documentation
base
SLinearBase sgpp::base::OperationEvalLinearNaive::base protected
1D linear basis
Referenced by eval(), and eval().
pointInUnitCube
DataVector sgpp::base::OperationEvalLinearNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by eval(), and eval().
storage
GridStorage& sgpp::base::OperationEvalLinearNaive::storage protected
storage of the sparse grid
Referenced by eval(), and eval().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalLinearNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalLinearNaive.cpp