SG++-Doxygen-Documentation: sgpp::datadriven::PiecewiseConstantRegression::Node Class Reference
sgpp::datadriven::PiecewiseConstantRegression::Node Class Reference
#include <Node.hpp>
Public Member Functions
double evaluate (std::vector< double > &point)
double getAverage (std::vector< size_t > &supportIndizes, std::vector< double > &x, std::vector< double > &h)
uint64_t getChildCount ()
std::vector< double > getChildH (size_t d)
uint64_t getHierarchizationMaxLevel ()
std::vector< double > getLeftChildX (size_t d)
double getMSE ()
double getMSE (std::vector< size_t > &supportIndizes, std::vector< double > &x, std::vector< double > &h, double supportValue)
std::vector< double > getRightChildX (size_t d)
std::vector< size_t > getSupportIndizes (std::vector< double > &x, std::vector< double > &h, std::vector< size_t > &parentSupport)
void hierarchize (double targetMSE, size_t targetMaxLevel, double parentValue=0.0, size_t refineDim=0, size_t levelLimit=0)
std::unique_ptr< Node > hierarchizeChild (std::vector< double > &x, std::vector< double > &h, std::vector< size_t > &parentSupport, double supportValue, double targetMSE, size_t targetMaxLevel, size_t nextDim, size_t levelLimit)
double integrate (sgpp::base::GridPoint &gridPoint, size_t &integratedNodes, size_t levelLimit=0)
Node (std::vector< double > x, std::vector< double > h, std::vector< size_t > supportIndizes, base::DataMatrix &dataset, base::DataVector &values, bool verbose=false)
Static Public Attributes
static uint64_t hierarchizeMaxLevel
static uint64_t integratedNodes
Constructor & Destructor Documentation
Node()
sgpp::datadriven::PiecewiseConstantRegression::Node::Node (std::vector< double > x, std::vector< double > h, std::vector< size_t > supportIndizes, base::DataMatrix & dataset, base::DataVector & values, bool verbose = false)
Member Function Documentation
evaluate()
double sgpp::datadriven::PiecewiseConstantRegression::Node::evaluate (std::vector< double > & point)
Referenced by getMSE().
getAverage()
double sgpp::datadriven::PiecewiseConstantRegression::Node::getAverage (std::vector< size_t > & supportIndizes, std::vector< double > & x, std::vector< double > & h)
Referenced by hierarchize().
getChildCount()
uint64_t sgpp::datadriven::PiecewiseConstantRegression::Node::getChildCount ()
getChildH()
std::vector< double > sgpp::datadriven::PiecewiseConstantRegression::Node::getChildH (size_t d)
Referenced by hierarchize().
getHierarchizationMaxLevel()
uint64_t sgpp::datadriven::PiecewiseConstantRegression::Node::getHierarchizationMaxLevel ()
References hierarchizeMaxLevel.
getLeftChildX()
std::vector< double > sgpp::datadriven::PiecewiseConstantRegression::Node::getLeftChildX (size_t d)
Referenced by hierarchize().
getMSE() [1/2]
double sgpp::datadriven::PiecewiseConstantRegression::Node::getMSE () inline
References dataset, evaluate(), and sgpp::datadriven::mse.
Referenced by hierarchizeChild().
getMSE() [2/2]
double sgpp::datadriven::PiecewiseConstantRegression::Node::getMSE (std::vector< size_t > & supportIndizes, std::vector< double > & x, std::vector< double > & h, double supportValue)
References sgpp::datadriven::mse.
getRightChildX()
std::vector< double > sgpp::datadriven::PiecewiseConstantRegression::Node::getRightChildX (size_t d)
Referenced by hierarchize().
getSupportIndizes()
std::vector< size_t > sgpp::datadriven::PiecewiseConstantRegression::Node::getSupportIndizes (std::vector< double > & x, std::vector< double > & h, std::vector< size_t > & parentSupport)
References sgpp::base::DataMatrix::getRow(), and h.
Referenced by hierarchizeChild().
hierarchize()
void sgpp::datadriven::PiecewiseConstantRegression::Node::hierarchize (double targetMSE, size_t targetMaxLevel, double parentValue = 0.0, size_t refineDim = 0, size_t levelLimit = 0)
References getAverage(), getChildH(), getLeftChildX(), getRightChildX(), hierarchizeChild(), and hierarchizeMaxLevel.
hierarchizeChild()
std::unique_ptr< Node > sgpp::datadriven::PiecewiseConstantRegression::Node::hierarchizeChild (std::vector< double > & x, std::vector< double > & h, std::vector< size_t > & parentSupport, double supportValue, double targetMSE, size_t targetMaxLevel, size_t nextDim, size_t levelLimit)
References getMSE(), getSupportIndizes(), h, and sgpp::datadriven::mse.
Referenced by hierarchize().
integrate()
double sgpp::datadriven::PiecewiseConstantRegression::Node::integrate (sgpp::base::GridPoint & gridPoint, size_t & integratedNodes, size_t levelLimit = 0)
References sgpp::base::LinearBasis< LT, IT >::eval(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridPoint::getStandardCoordinate(), h, and integratedNodes.
Referenced by sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::generateb().
Member Data Documentation
hierarchizeMaxLevel
uint64_t sgpp::datadriven::PiecewiseConstantRegression::Node::hierarchizeMaxLevel static
Referenced by getHierarchizationMaxLevel(), and hierarchize().
integratedNodes
uint64_t sgpp::datadriven::PiecewiseConstantRegression::Node::integratedNodes static
Referenced by integrate().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationPiecewiseConstantRegression/Node.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationPiecewiseConstantRegression/Node.cpp