SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureBspline Class Reference
sgpp::base::OperationQuadratureBspline Class Reference
Quadrature on sparse grid, Bsplinenomial grid without boundaries.
#include <OperationQuadratureBspline.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for piecewise Bsplinenomial basis functions of max.
OperationQuadratureBspline (GridStorage &storage, size_t degree)
Constructor of OperationQuadratureBspline.
~OperationQuadratureBspline () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SBsplineBase base
Bspline Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, Bsplinenomial grid without boundaries.
Constructor & Destructor Documentation
OperationQuadratureBspline()
sgpp::base::OperationQuadratureBspline::OperationQuadratureBspline (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadratureBspline.
Parameters
storage Pointer to the grid's GridStorage object
degree the Bsplines degree
~OperationQuadratureBspline()
sgpp::base::OperationQuadratureBspline::~OperationQuadratureBspline () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureBspline::doQuadrature (DataVector & alpha) override virtual
Quadrature for piecewise Bsplinenomial basis functions of max.
degree 3
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BsplineBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SBsplineBase sgpp::base::OperationQuadratureBspline::base protected
Bspline Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadratureBspline::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureBspline.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureBspline.cpp