SG++-Doxygen-Documentation: sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT > Class Template Reference
sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT > Class Template Reference
weakly fundamental not-a-knot spline basis.
#include <WeaklyFundamentalNakSplineModifiedBasisDeriv1.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
size_t getDegree () const override
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
WeaklyFundamentalNakSplineModifiedBasisDeriv1 ()
Default constructor.
WeaklyFundamentalNakSplineModifiedBasisDeriv1 (size_t degree)
Constructor.
~WeaklyFundamentalNakSplineModifiedBasisDeriv1 () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
WeaklyFundamentalNakSplineBasisDeriv1< LT, IT > weaklyFundamentalNakSplineBasisDeriv1
Unmodified basis.
Detailed Description
template<class LT, class IT>
class sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >
weakly fundamental not-a-knot spline basis.
Constructor & Destructor Documentation
WeaklyFundamentalNakSplineModifiedBasisDeriv1() [1/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineModifiedBasisDeriv1 () inline
Default constructor.
WeaklyFundamentalNakSplineModifiedBasisDeriv1() [2/2]
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineModifiedBasisDeriv1 (size_t degree) inline explicit
Constructor.
Parameters
degree Spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::getDegree().
~WeaklyFundamentalNakSplineModifiedBasisDeriv1()
template<class LT , class IT > sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::~WeaklyFundamentalNakSplineModifiedBasisDeriv1 () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::getDegree(), and sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::weaklyFundamentalNakSplineBasisDeriv1.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientModWeaklyFundamentalNakSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianModWeaklyFundamentalNakSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeModWeaklyFundamentalNakSplineNaive::evalPartialDerivative().
evalDx()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
getDegree()
template<class LT , class IT > size_t sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::weaklyFundamentalNakSplineBasisDeriv1.
Referenced by sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), and sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::WeaklyFundamentalNakSplineModifiedBasisDeriv1().
getIntegral()
template<class LT , class IT > double sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
Member Data Documentation
weaklyFundamentalNakSplineBasisDeriv1
template<class LT , class IT > WeaklyFundamentalNakSplineBasisDeriv1<LT, IT> sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::weaklyFundamentalNakSplineBasisDeriv1 protected
Unmodified basis.
Referenced by sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::eval(), and sgpp::base::WeaklyFundamentalNakSplineModifiedBasisDeriv1< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/WeaklyFundamentalNakSplineModifiedBasisDeriv1.hpp