SG++-Doxygen-Documentation: sgpp::base::RefinementDecorator Class Reference
sgpp::base::RefinementDecorator Class Reference
RefinementDecorator enhances the behavior of underlying Refinement objects using Decorator design pattern .
#include <RefinementDecorator.hpp>
Public Member Functions
bool checkAdmissibility (GridStorage &storage, GridPoint &subspace)
virtual void free_refine (GridStorage &storage, RefinementFunctor &functor, std::vector< size_t > *addedPoints=nullptr)
Refines a grid according to a RefinementFunctor provided.
virtual size_t getNumberOfRefinablePoints (GridStorage &storage)
Computes and returns the number of grid points, which can be refined.
virtual void refineGridpoint1D (GridStorage &storage, GridPoint &point, size_t d)
Refine one grid point along a single direction.
RefinementDecorator (AbstractRefinement *refinement)
Constructor.
virtual ~RefinementDecorator ()
Public Member Functions inherited from sgpp::base::AbstractRefinement
virtual size_t getIndexOfMin (RefinementFunctor::value_type *array, size_t length)
Returns the index of the first occurrence of minimal element in array.
bool isRefinable (GridStorage &storage, GridPoint &point)
Check if the grid point is refinable.
virtual void refineGridpoint1D (GridStorage &storage, size_t seq, size_t d)
Refine one grid point along a single direction.
virtual ~AbstractRefinement ()
Destructor.
Protected Member Functions
virtual void collectRefinablePoints (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection)
Examines the grid points and stores the indices those that can be refined and have maximal indicator values.
virtual void createGridpoint (GridStorage &storage, GridPoint &point)
This method creates a new point on the grid.
AbstractRefinement * get_decorated_refinement ()
Returns the pointer to decorated Refinement object.
virtual AbstractRefinement::refinement_list_type getIndicator (GridStorage &storage, const GridStorage::grid_map_iterator &iter, const RefinementFunctor &functor) const
Generates a list with indicator elements.
virtual void refineGridpoint (GridStorage &storage, size_t refine_index)
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
virtual void refineGridpointsCollection (GridStorage &storage, RefinementFunctor &functor, AbstractRefinement::refinement_container_type &collection)
Refines the collection of points.
void set_decorated_refiment (AbstractRefinement *refinement)
Sets the pointer of the decorated Refinement object to the given object.
Protected Member Functions inherited from sgpp::base::AbstractRefinement
virtual void createGridpoint1D (GridPoint &point, size_t d, GridStorage &storage, index_t &source_index, level_t &source_level)
Creates children grid points along single direction.
virtual void createGridpointSubroutine (GridStorage &storage, GridPoint &point)
Subroutine for grid point creation.
Additional Inherited Members
Public Types inherited from sgpp::base::AbstractRefinement
typedef std::vector< refinement_pair_type > refinement_container_type
Container for the collection of the refinement atoms and the corresponding value.
typedef AbstractRefinement_refinement_key refinement_key_type
Type of the identifier of the refinement atom (e.g.
typedef std::forward_list< AbstractRefinement::refinement_pair_type > refinement_list_type
typedef std::pair< std::shared_ptr< refinement_key_type >, refinement_value_type > refinement_pair_type
Pair for the refinement key and value.
typedef double refinement_value_type
Type of functor value assigned to each refinement atom.
Static Public Member Functions inherited from sgpp::base::AbstractRefinement
static bool compare_pairs (const refinement_pair_type &lhs, const refinement_pair_type &rhs)
Comparison of the refinement_pair_type.
Detailed Description
RefinementDecorator enhances the behavior of underlying Refinement objects using Decorator design pattern .
Although not abstract, this class is thought to be a base class as it simply delegates the function calls to the decorated object. Subclasses will implement more sophisticated behavior.
Constructor & Destructor Documentation
RefinementDecorator()
sgpp::base::RefinementDecorator::RefinementDecorator (AbstractRefinement * refinement) inline explicit
Constructor.
Parameters
refinement object implementing the core functionality (e.g. refinement with or without boundaries).
~RefinementDecorator()
virtual sgpp::base::RefinementDecorator::~RefinementDecorator () inline virtual
Member Function Documentation
checkAdmissibility()
bool sgpp::base::RefinementDecorator::checkAdmissibility (GridStorage & storage, GridPoint & subspace)
collectRefinablePoints()
void sgpp::base::RefinementDecorator::collectRefinablePoints (GridStorage & storage, RefinementFunctor & functor, AbstractRefinement::refinement_container_type & collection) protected virtual
Examines the grid points and stores the indices those that can be refined and have maximal indicator values.
Parameters
storage hashmap that stores the grid points
functor a PredictiveRefinementIndicator specifying the refinement criteria
collection container that contains elements to refine (empty initially)
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, and sgpp::base::SubspaceRefinement.
References sgpp::base::AbstractRefinement::collectRefinablePoints().
createGridpoint()
void sgpp::base::RefinementDecorator::createGridpoint (GridStorage & storage, GridPoint & point) protected virtual
This method creates a new point on the grid.
It checks if some parents or children are needed in other dimensions.
Parameters
storage hashmap that stores the gridpoints
point The point that should be inserted
Implements sgpp::base::AbstractRefinement.
References sgpp::base::AbstractRefinement::createGridpoint().
free_refine()
void sgpp::base::RefinementDecorator::free_refine (GridStorage & storage, RefinementFunctor & functor, std::vector< size_t > * addedPoints = nullptr) virtual
Refines a grid according to a RefinementFunctor provided.
Refines up to RefinementFunctor::getRefinementsNum() grid points if possible, and if their refinement value is larger than RefinementFunctor::start() and their absolute value is larger or equal than RefinementFunctor::getRefinementThreshold()
Parameters
storage hashmap that stores the grid points
functor a RefinementFunctor specifying the refinement criteria
addedPoints pointer to vector to append newly created grid points to
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, and sgpp::base::SubspaceRefinement.
References sgpp::base::AbstractRefinement::free_refine().
get_decorated_refinement()
AbstractRefinement * sgpp::base::RefinementDecorator::get_decorated_refinement () inline protected
Returns the pointer to decorated Refinement object.
getIndicator()
AbstractRefinement::refinement_list_type sgpp::base::RefinementDecorator::getIndicator (GridStorage & storage, const GridStorage::grid_map_iterator & iter, const RefinementFunctor & functor) const protected virtual
Generates a list with indicator elements.
Parameters
storage grid storage
iter iterator
functor refinement functor
Returns
list with indicator elements
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, and sgpp::base::PredictiveRefinement.
References sgpp::base::AbstractRefinement::getIndicator().
Referenced by sgpp::base::SubspaceRefinement::collectRefinablePoints().
getNumberOfRefinablePoints()
size_t sgpp::base::RefinementDecorator::getNumberOfRefinablePoints (GridStorage & storage) virtual
Computes and returns the number of grid points, which can be refined.
This is the number of grid points that have at least one child missing.
Parameters
storage hashmap that stores the grid points
Returns
The number of grid points that can be refined
Implements sgpp::base::AbstractRefinement.
References sgpp::base::AbstractRefinement::getNumberOfRefinablePoints().
refineGridpoint()
void sgpp::base::RefinementDecorator::refineGridpoint (GridStorage & storage, size_t refine_index) protected virtual
This method refines a grid point by generating the children in every dimension of the grid and all their missing ancestors by calling create_gridpoint().
Parameters
storage hashmap that stores the gridpoints
refine_index The index in the hashmap of the point that should be refined
Implements sgpp::base::AbstractRefinement.
References sgpp::base::AbstractRefinement::refineGridpoint().
Referenced by sgpp::base::ForwardSelectorRefinement::refineGridpointsCollection(), sgpp::base::ImpurityRefinement::refineGridpointsCollection(), and sgpp::base::SubspaceRefinement::refineGridpointsCollection().
refineGridpoint1D()
void sgpp::base::RefinementDecorator::refineGridpoint1D (GridStorage & storage, GridPoint & point, size_t d) virtual
Refine one grid point along a single direction.
Parameters
storage hashmap that stores the grid points
point point to refine
d direction
Implements sgpp::base::AbstractRefinement.
References sgpp::base::AbstractRefinement::refineGridpoint1D().
Referenced by sgpp::base::PredictiveRefinement::refineGridpointsCollection().
refineGridpointsCollection()
void sgpp::base::RefinementDecorator::refineGridpointsCollection (GridStorage & storage, RefinementFunctor & functor, AbstractRefinement::refinement_container_type & collection) protected virtual
Refines the collection of points.
Parameters
storage hashmap that stores the grid points
functor a PredictiveRefinementIndicator specifying the refinement criteria
collection container that contains elements to refine (empty initially)
Implements sgpp::base::AbstractRefinement.
Reimplemented in sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, sgpp::base::ForwardSelectorRefinement, sgpp::base::ImpurityRefinement, sgpp::base::PredictiveRefinement, and sgpp::base::SubspaceRefinement.
References sgpp::base::AbstractRefinement::refineGridpointsCollection().
set_decorated_refiment()
void sgpp::base::RefinementDecorator::set_decorated_refiment (AbstractRefinement * refinement) inline protected
Sets the pointer of the decorated Refinement object to the given object.
Parameters
refinement object the pointer should be set to
The documentation for this class was generated from the following files:
base/src/sgpp/base/grid/generation/refinement_strategy/RefinementDecorator.hpp
base/src/sgpp/base/grid/generation/refinement_strategy/RefinementDecorator.cpp