SG++-Doxygen-Documentation: sgpp::optimization::test_problems::G05Objective Class Reference
sgpp::optimization::test_problems::G05Objective Class Reference
G05 objective function.
#include <G05.hpp>
Public Member Functions
void clone (std::unique_ptr< base::ScalarFunction > &clone) const override
double evalUndisplaced (const base::DataVector &x) override
G05Objective ()
Constructor.
~G05Objective () override
Destructor.
Public Member Functions inherited from sgpp::optimization::test_problems::TestScalarFunction
double eval (const base::DataVector &x) override
Evaluate displaced function.
const base::DataVector & getDisplacement () const
void setDisplacement (const base::DataVector &displacement)
TestScalarFunction (size_t d)
Constructor.
~TestScalarFunction () override
Destructor.
Public Member Functions inherited from sgpp::base::ScalarFunction
virtual void eval (const DataMatrix &x, DataVector &value)
Convenience method for calculating \(f(\vec{x})\) for multiple \(\vec{x}\).
size_t getNumberOfParameters () const
ScalarFunction (size_t d)
Constructor.
virtual ~ScalarFunction ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::optimization::test_problems::TestScalarFunction
base::DataVector displacement
displacement vector
base::DataVector xTmp
temporary vector for displacing
Protected Attributes inherited from sgpp::base::ScalarFunction
size_t d
dimension of the domain
Detailed Description
G05 objective function.
Definition:
\[\bar{f}(\bar{\vec{x}}) := 3 \bar{x}_1 + \left(\frac{\bar{x}_1}{100}\right)^3 + \frac{2}{3} \left(\frac{\bar{x}_2}{100}\right)^3\]
Constructor & Destructor Documentation
G05Objective()
sgpp::optimization::test_problems::G05Objective::G05Objective ()
Constructor.
Referenced by clone().
~G05Objective()
sgpp::optimization::test_problems::G05Objective::~G05Objective () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::test_problems::G05Objective::clone (std::unique_ptr< base::ScalarFunction > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::base::ScalarFunction.
References clone(), and G05Objective().
Referenced by clone().
evalUndisplaced()
double sgpp::optimization::test_problems::G05Objective::evalUndisplaced (const base::DataVector & x) override virtual
Parameters
x point \(\vec{x} \in [0, 1]^d\)
Returns
\(f(\vec{x})\)
Implements sgpp::optimization::test_problems::TestScalarFunction.
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/test_problems/constrained/G05.hpp
optimization/src/sgpp/optimization/test_problems/constrained/G05.cpp