SG++-Doxygen-Documentation: sgpp::datadriven::VisualizationTypesParser Class Reference
sgpp::datadriven::VisualizationTypesParser Class Reference
Convenience class to convert strings to sgpp::datadriven::VisualizationTypesParser and generate string representations for values of sgpp::datadriven::VisualizationFileType.
#include <VisualizationTypesParser.hpp>
Static Public Member Functions
static VisualizationFileType parseFileType (const std::string &input)
Convert strings to values sgpp::datadriven::VisualizationFileType.
static const std::string & toString (VisualizationFileType type)
generate string representations for values of sgpp::datadriven::DataSourceFileType.
Detailed Description
Convenience class to convert strings to sgpp::datadriven::VisualizationTypesParser and generate string representations for values of sgpp::datadriven::VisualizationFileType.
Member Function Documentation
parseFileType()
VisualizationFileType sgpp::datadriven::VisualizationTypesParser::parseFileType (const std::string & input) static
Convert strings to values sgpp::datadriven::VisualizationFileType.
Throws if there is no valid representation
Parameters
input case insensitive string representation of a sgpp::datadriven::VisualizationFileType.
Returns
the corresponding sgpp::datadriven::VisualizationFileType.
References sgpp::datadriven::CSV, and sgpp::datadriven::json.
Referenced by sgpp::datadriven::DataMiningConfigParser::getVisualizationGeneralConfig().
toString()
const std::string & sgpp::datadriven::VisualizationTypesParser::toString (VisualizationFileType type) static
generate string representations for values of sgpp::datadriven::DataSourceFileType.
Parameters
type enum value.
Returns
string representation of a sgpp::datadriven::DataSourceFileType.
Referenced by python.controller.LearnerEventController.LearnerEventController::__repr__(), python.controller.SolverEventController.SolverEventController::__repr__(), python.learner.Learner.Learner::createMemento(), python.uq.learner.Learner.Learner::createMemento(), sgpp::datadriven::DataMiningConfigParser::getVisualizationGeneralConfig(), and python.learner.formatter.GridFormatter.GridFormatter::serialize().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/visualization/VisualizationTypesParser.hpp
datadriven/src/sgpp/datadriven/datamining/modules/visualization/VisualizationTypesParser.cpp