SG++-Doxygen-Documentation: sgpp::base::BsplineBasis< LT, IT > Class Template Reference
sgpp::base::BsplineBasis< LT, IT > Class Template Reference
B-spline basis on Noboundary grids.
#include <BsplineBasis.hpp>
Public Member Functions
BsplineBasis ()
Default constructor.
BsplineBasis (size_t degree)
Constructor.
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
size_t getDegree () const override
double getIntegral (LT level, IT index) override
double uniformBSpline (double x, size_t p) const
double uniformBSplineDx (double x, size_t p) const
double uniformBSplineDxDx (double x, size_t p) const
~BsplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
size_t degree
degree of the B-spline
Detailed Description
template<class LT, class IT>
class sgpp::base::BsplineBasis< LT, IT >
B-spline basis on Noboundary grids.
Constructor & Destructor Documentation
BsplineBasis() [1/2]
template<class LT , class IT > sgpp::base::BsplineBasis< LT, IT >::BsplineBasis () inline
Default constructor.
BsplineBasis() [2/2]
template<class LT , class IT > sgpp::base::BsplineBasis< LT, IT >::BsplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::BsplineBasis< LT, IT >::degree.
~BsplineBasis()
template<class LT , class IT > sgpp::base::BsplineBasis< LT, IT >::~BsplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBasis< LT, IT >::degree, and sgpp::base::BsplineBasis< LT, IT >::uniformBSpline().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalBsplineNaive::eval(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationMultipleEvalBsplineNaive::mult(), sgpp::pde::OperationLaplaceBspline::mult(), and sgpp::base::OperationMultipleEvalBsplineNaive::multTranspose().
evalDx()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBasis< LT, IT >::degree, and sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDx().
Referenced by sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientBsplineNaive::evalGradient(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeBsplineNaive::evalPartialDerivative(), and sgpp::pde::OperationLaplaceBspline::mult().
evalDxDx()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of B-spline basis function
References sgpp::base::BsplineBasis< LT, IT >::degree, and sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDxDx().
Referenced by sgpp::base::OperationEvalHessianBsplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianBsplineNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::BsplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBasis< LT, IT >::degree.
getIntegral()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
Parameters
level level of basis function
index index of basis function
Returns
value of the Integral
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::BsplineBasis< LT, IT >::degree, and level.
Referenced by sgpp::base::OperationQuadratureBspline::doQuadrature().
uniformBSpline()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::uniformBSpline (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of uniform B-spline (with knots \(\{0, 1, ..., p+1\}\))
References sgpp::base::BsplineBasis< LT, IT >::uniformBSpline().
Referenced by sgpp::base::BsplineBasis< LT, IT >::eval(), sgpp::optimization::test_problems::TremblingParabolaObjective::splineTrembling(), sgpp::base::BsplineBasis< LT, IT >::uniformBSpline(), sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDx(), and sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDxDx().
uniformBSplineDx()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDx (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of derivative of uniform B-spline (with knots \(\{0, 1, ..., p+1\}\))
References sgpp::base::BsplineBasis< LT, IT >::uniformBSpline().
Referenced by sgpp::base::BsplineBasis< LT, IT >::evalDx().
uniformBSplineDxDx()
template<class LT , class IT > double sgpp::base::BsplineBasis< LT, IT >::uniformBSplineDxDx (double x, size_t p) const inline
Parameters
x evaluation point
p B-spline degree
Returns
value of 2nd derivative of uniform B-spline (with knots \(\{0, 1, ..., p+1\}\))
References sgpp::base::BsplineBasis< LT, IT >::uniformBSpline().
Referenced by sgpp::base::BsplineBasis< LT, IT >::evalDxDx().
Member Data Documentation
degree
template<class LT , class IT > size_t sgpp::base::BsplineBasis< LT, IT >::degree protected
degree of the B-spline
Referenced by sgpp::base::BsplineBasis< LT, IT >::BsplineBasis(), sgpp::base::BsplineBasis< LT, IT >::eval(), sgpp::base::BsplineBasis< LT, IT >::evalDx(), sgpp::base::BsplineBasis< LT, IT >::evalDxDx(), sgpp::base::BsplineBasis< LT, IT >::getDegree(), and sgpp::base::BsplineBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/BsplineBasis.hpp