SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensityConditionalKDE Class Reference
sgpp::datadriven::OperationDensityConditionalKDE Class Reference
#include <OperationDensityConditionalKDE.hpp>
Public Member Functions
virtual void condToDimX (size_t mdim, base::DataVector &xbar, datadriven::KernelDensityEstimator &conditionalizedKDE)
Conditional (Density) Functions to a 1d density where the remaining dimension is mdim.
virtual void condToDimXs (std::vector< size_t > &mdims, base::DataVector &xbar, datadriven::KernelDensityEstimator &conditionalizedKDE)
Conditional (Density) Functions to a dd density where the remaining dimensions are mdims.
virtual void doConditional (size_t mdim, double xbar, datadriven::KernelDensityEstimator &conditionalizedKDE)
Conditional (Density) Functions.
virtual void doConditional (std::vector< size_t > &mdims, base::DataVector &xbar, datadriven::KernelDensityEstimator &conditionalizedKDE)
Conditional (Density) Functions.
OperationDensityConditionalKDE (datadriven::KernelDensityEstimator &kde)
virtual ~OperationDensityConditionalKDE ()
Constructor & Destructor Documentation
OperationDensityConditionalKDE()
sgpp::datadriven::OperationDensityConditionalKDE::OperationDensityConditionalKDE (datadriven::KernelDensityEstimator & kde) explicit
~OperationDensityConditionalKDE()
sgpp::datadriven::OperationDensityConditionalKDE::~OperationDensityConditionalKDE () virtual
Member Function Documentation
condToDimX()
void sgpp::datadriven::OperationDensityConditionalKDE::condToDimX (size_t mdim, base::DataVector & xbar, datadriven::KernelDensityEstimator & conditionalizedKDE) virtual
Conditional (Density) Functions to a 1d density where the remaining dimension is mdim.
Parameters
mdim conditionalize all dimensions but mdim
xbar point at which to conditionalize
conditionalizedKDE conditionalized kernel density
References sgpp::op_factory::createOperationDensityMarginalizeKDE(), sgpp::datadriven::KernelDensityEstimator::getConditionalizationFactor(), sgpp::datadriven::KernelDensityEstimator::getDim(), sgpp::datadriven::KernelDensityEstimator::getNsamples(), sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimX(), sgpp::datadriven::KernelDensityEstimator::setConditionalizationFactor(), and sgpp::datadriven::KernelDensityEstimator::updateConditionalizationFactors().
condToDimXs()
void sgpp::datadriven::OperationDensityConditionalKDE::condToDimXs (std::vector< size_t > & mdims, base::DataVector & xbar, datadriven::KernelDensityEstimator & conditionalizedKDE) virtual
Conditional (Density) Functions to a dd density where the remaining dimensions are mdims.
Parameters
mdims conditionalize all dimensions but the ones in mdims
xbar point at which to conditionalize
conditionalizedKDE conditionalized kernel density
doConditional() [1/2]
void sgpp::datadriven::OperationDensityConditionalKDE::doConditional (size_t mdim, double xbar, datadriven::KernelDensityEstimator & conditionalizedKDE) virtual
Conditional (Density) Functions.
Parameters
mdim Marginalize in dimension mdim
xbar Point at which to conditionalize
conditionalizedKDE conditionalized kernel density
doConditional() [2/2]
void sgpp::datadriven::OperationDensityConditionalKDE::doConditional (std::vector< size_t > & mdims, base::DataVector & xbar, datadriven::KernelDensityEstimator & conditionalizedKDE) virtual
Conditional (Density) Functions.
Parameters
mdims Conditionalize in dimensions mdims
xbar Point at which to conditionalize
conditionalizedKDE conditionalized kernel density
References sgpp::op_factory::createOperationDensityMarginalizeKDE(), sgpp::datadriven::KernelDensityEstimator::getConditionalizationFactor(), sgpp::datadriven::KernelDensityEstimator::getDim(), sgpp::datadriven::KernelDensityEstimator::getNsamples(), sgpp::datadriven::OperationDensityMarginalizeKDE::margToDimXs(), sgpp::datadriven::KernelDensityEstimator::setConditionalizationFactor(), and sgpp::datadriven::KernelDensityEstimator::updateConditionalizationFactors().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityConditionalKDE.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensityConditionalKDE.cpp