SG++-Doxygen-Documentation: sgpp::base::OperationMatrix Class Reference
sgpp::base::OperationMatrix Class Reference abstract
Abstract definition of a matrix operator interface.
#include <OperationMatrix.hpp>
Public Member Functions
virtual void mult (DataVector &alpha, DataVector &result)=0
starts the Multiplication with the matrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Abstract definition of a matrix operator interface.
Every time you need to apply a matrix to the ansatzfunction's coefficients derive a class from OperationMatrix
Constructor & Destructor Documentation
OperationMatrix()
sgpp::base::OperationMatrix::OperationMatrix () inline
Constructor.
~OperationMatrix()
virtual sgpp::base::OperationMatrix::~OperationMatrix () inline virtual
Destructor.
Member Function Documentation
mult()
virtual void sgpp::base::OperationMatrix::mult (DataVector & alpha, DataVector & result) pure virtual
starts the Multiplication with the matrix
Parameters
alpha DataVector that contains the ansatzfunctions' coefficients
result DataVector into which the result of the Laplace operation is stored
Implemented in sgpp::datadriven::DensityDifferenceSystemMatrix, sgpp::datadriven::DensitySystemMatrix, sgpp::datadriven::DMSystemMatrix, sgpp::datadriven::LogDensitySystemMatrix, sgpp::datadriven::SystemMatrixDensityRatioEstimation, sgpp::datadriven::SystemMatrixLeastSquaresIdentity, sgpp::datadriven::clusteringmpi::OperationDensityMultMPI, sgpp::datadriven::OperationRegularizationDiagonal, sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >, sgpp::datadriven::DMSystemMatrixBase, sgpp::datadriven::DMSystemMatrixDRE, sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity, sgpp::base::OperationDiagonal, sgpp::base::OperationIdentity, sgpp::datadriven::DMWeightMatrix, sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix, sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP, sgpp::pde::StdUpDown, sgpp::pde::UpDownFourOpDims, sgpp::pde::UpDownOneOpDim, sgpp::pde::UpDownOneOpDimEnhanced, sgpp::pde::UpDownOneOpDimWithShadow, sgpp::pde::UpDownTwoOpDims, sgpp::pde::OperationEllipticPDESolverSystemDirichlet, sgpp::pde::OperationEllipticPDESolverSystemFreeBoundaries, sgpp::pde::OperationLaplaceBspline, sgpp::pde::OperationLaplaceBsplineBoundary, sgpp::pde::OperationLaplaceBsplineClenshawCurtis, sgpp::pde::OperationLaplaceExplicitBspline, sgpp::pde::OperationLaplaceExplicitLinear, sgpp::pde::OperationLaplaceExplicitModBspline, sgpp::pde::OperationLaplaceModBspline, sgpp::pde::OperationLaplaceModBsplineClenshawCurtis, sgpp::pde::OperationLaplaceModPoly, sgpp::pde::OperationLaplaceModPolyClenshawCurtis, sgpp::pde::OperationLaplacePoly, sgpp::pde::OperationLaplacePolyBoundary, sgpp::pde::OperationLaplacePolyClenshawCurtis, sgpp::pde::OperationLaplacePolyClenshawCurtisBoundary, sgpp::pde::OperationMatrixLTwoDotBspline, sgpp::pde::OperationMatrixLTwoDotBsplineBoundary, sgpp::pde::OperationMatrixLTwoDotBsplineClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotExplicitBspline, sgpp::pde::OperationMatrixLTwoDotExplicitBsplineBoundary, sgpp::pde::OperationMatrixLTwoDotExplicitBsplineClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotExplicitLinear, sgpp::pde::OperationMatrixLTwoDotExplicitLinearBoundary, sgpp::pde::OperationMatrixLTwoDotExplicitModBspline, sgpp::pde::OperationMatrixLTwoDotExplicitModBsplineClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotExplicitModifiedLinear, sgpp::pde::OperationMatrixLTwoDotExplicitModLinear, sgpp::pde::OperationMatrixLTwoDotExplicitModPoly, sgpp::pde::OperationMatrixLTwoDotExplicitModPolyClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotExplicitPeriodic, sgpp::pde::OperationMatrixLTwoDotExplicitPoly, sgpp::pde::OperationMatrixLTwoDotExplicitPolyBoundary, sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotExplicitPolyClenshawCurtisBoundary, sgpp::pde::OperationMatrixLTwoDotModBspline, sgpp::pde::OperationMatrixLTwoDotModBsplineClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotModLinear, sgpp::pde::OperationMatrixLTwoDotModPoly, sgpp::pde::OperationMatrixLTwoDotModPolyClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotPeriodic, sgpp::pde::OperationMatrixLTwoDotPoly, sgpp::pde::OperationMatrixLTwoDotPolyBoundary, sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtis, sgpp::pde::OperationMatrixLTwoDotPolyClenshawCurtisBoundary, sgpp::pde::OperationParabolicPDESolverSystemDirichlet, sgpp::pde::OperationParabolicPDESolverSystemFreeBoundaries, sgpp::pde::OperationEllipticPDESolverSystem, and sgpp::solver::OperationParabolicPDESolverSystem.
Referenced by sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::applyLOperatorComplete(), sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::applyLOperatorInner(), sgpp::datadriven::DMWeightMatrix::mult(), sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::mult(), sgpp::solver::BiCGStab::solve(), and sgpp::solver::ConjugateGradients::solve().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/OperationMatrix.hpp