SG++-Doxygen-Documentation: sgpp::datadriven::DensitySystemMatrix Class Reference
sgpp::datadriven::DensitySystemMatrix Class Reference
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
#include <DensitySystemMatrix.hpp>
Public Member Functions
void computeUnweightedRhs (base::DataVector &b)
Computes the unweighted right hand side of the classification equation.
DensitySystemMatrix (base::Grid &grid, base::DataMatrix &trainData, base::OperationMatrix *C, double lambda)
Std-Constructor.
DensitySystemMatrix (sgpp::base::OperationMatrix *A, sgpp::base::OperationMultipleEval *B, sgpp::base::OperationMatrix *C, double lambda, size_t numSamples)
Std-Constructor.
void generateb (base::DataVector &b)
Generates the right hand side of the classification equation.
void mult (base::DataVector &alpha, base::DataVector &result)
Generates the left hand side of the classification equation.
virtual ~DensitySystemMatrix ()
Std-Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
Constructor & Destructor Documentation
DensitySystemMatrix() [1/2]
sgpp::datadriven::DensitySystemMatrix::DensitySystemMatrix (sgpp::base::OperationMatrix * A, sgpp::base::OperationMultipleEval * B, sgpp::base::OperationMatrix * C, double lambda, size_t numSamples)
Std-Constructor.
Parameters
A L^2 dot product matrix of some grid
B MultipleEval matrix of grid and data points
C the regression functional
lambda the regression parameter
numSamples number of data samples
DensitySystemMatrix() [2/2]
sgpp::datadriven::DensitySystemMatrix::DensitySystemMatrix (base::Grid & grid, base::DataMatrix & trainData, base::OperationMatrix * C, double lambda)
Std-Constructor.
Parameters
grid reference to the sparse grid
trainData reference to DataVector that contains the training data
C the regression functional
lambda the regression parameter
References sgpp::op_factory::createOperationLTwoDotProduct(), sgpp::op_factory::createOperationMultipleEval(), and grid().
~DensitySystemMatrix()
sgpp::datadriven::DensitySystemMatrix::~DensitySystemMatrix () virtual
Std-Destructor.
Member Function Documentation
computeUnweightedRhs()
void sgpp::datadriven::DensitySystemMatrix::computeUnweightedRhs (base::DataVector & b)
Computes the unweighted right hand side of the classification equation.
Parameters
b reference to the vector which will contain the result of the matrix vector multiplication on the rhs
References sgpp::base::DataVector::setAll().
Referenced by generateb(), and sgpp::datadriven::ModelFittingDensityEstimationCG::update().
generateb()
void sgpp::datadriven::DensitySystemMatrix::generateb (base::DataVector & b)
Generates the right hand side of the classification equation.
Parameters
b reference to the vector which will contain the result of the matrix vector multiplication on the rhs
References computeUnweightedRhs(), and sgpp::base::DataVector::mult().
Referenced by sgpp::datadriven::LearnerSGDE::computeResidual(), sgpp::datadriven::DBMatOnlineDE::resDensity(), sgpp::datadriven::LearnerSGDE::train(), and sgpp::datadriven::LearnerSGDE::trainOnline().
mult()
void sgpp::datadriven::DensitySystemMatrix::mult (base::DataVector & alpha, base::DataVector & result) virtual
Generates the left hand side of the classification equation.
Parameters
alpha parameters for the sparse grid functions
result reference to the vector which will contain the result
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataVector::axpy(), sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::datadriven::LearnerSGDE::computeResidual(), and sgpp::datadriven::DBMatOnlineDE::resDensity().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DensitySystemMatrix.hpp
datadriven/src/sgpp/datadriven/algorithm/DensitySystemMatrix.cpp