SG++-Doxygen-Documentation: sgpp::datadriven::OperationDensitySamplingLinear Class Reference
sgpp::datadriven::OperationDensitySamplingLinear Class Reference
keep applying marginalize to function until it's reduced to only 1 dimension
#include <OperationDensitySamplingLinear.hpp>
Public Member Functions
void doSampling (base::DataVector *alpha, base::DataMatrix *&samples, size_t num_samples)
Sampling with mixed starting dimensions.
void doSampling (base::DataVector *alpha, base::DataMatrix *&samples, size_t num_samples, size_t dim_x)
Sampling with specified starting dimension.
OperationDensitySamplingLinear (base::Grid *grid)
virtual ~OperationDensitySamplingLinear ()
Public Member Functions inherited from sgpp::datadriven::OperationDensitySampling
OperationDensitySampling ()
virtual ~OperationDensitySampling ()
Protected Member Functions
void doSampling_in_next_dim (base::Grid *g_in, base::DataVector *a_in, size_t dim_x, base::DataVector *&sampleVec, size_t &curr_dim, unsigned int *seedp)
void doSampling_start_dimX (base::Grid *g_in, base::DataVector *a_in, size_t dim_start, base::DataVector *&sampleVec, unsigned int *seedp)
Protected Attributes
base::Grid * grid
Detailed Description
keep applying marginalize to function until it's reduced to only 1 dimension
Constructor & Destructor Documentation
OperationDensitySamplingLinear()
sgpp::datadriven::OperationDensitySamplingLinear::OperationDensitySamplingLinear (base::Grid * grid) inline explicit
~OperationDensitySamplingLinear()
virtual sgpp::datadriven::OperationDensitySamplingLinear::~OperationDensitySamplingLinear () inline virtual
Member Function Documentation
doSampling() [1/2]
void sgpp::datadriven::OperationDensitySamplingLinear::doSampling (base::DataVector * alpha, base::DataMatrix *& samples, size_t num_samples) virtual
Sampling with mixed starting dimensions.
Parameters
alpha Coefficient vector for current grid
samples Output DataMatrix (rows: # of samples, columns: # of dims)
num_samples # of samples to draw
Implements sgpp::datadriven::OperationDensitySampling.
References sgpp::op_factory::createOperationDensityMargTo1D(), sgpp::op_factory::createOperationDensitySampling1D(), sgpp::datadriven::OperationDensitySampling1D::doSampling1D(), doSampling_start_dimX(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataVector::getSize(), grid, sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), and sgpp::base::DataVector::set().
doSampling() [2/2]
void sgpp::datadriven::OperationDensitySamplingLinear::doSampling (base::DataVector * alpha, base::DataMatrix *& samples, size_t num_samples, size_t dim_x) virtual
Sampling with specified starting dimension.
Parameters
alpha Coefficient vector for current grid
samples Output DataMatrix (rows: # of samples, columns: # of dims)
num_samples # of samples to draw
dim_x Starting dimension
Implements sgpp::datadriven::OperationDensitySampling.
References sgpp::op_factory::createOperationDensityMargTo1D(), sgpp::op_factory::createOperationDensitySampling1D(), sgpp::datadriven::OperationDensitySampling1D::doSampling1D(), doSampling_start_dimX(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), grid, sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), and sgpp::base::DataVector::set().
doSampling_in_next_dim()
void sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim (base::Grid * g_in, base::DataVector * a_in, size_t dim_x, base::DataVector *& sampleVec, size_t & curr_dim, unsigned int * seedp) protected
References sgpp::op_factory::createOperationDensityConditional(), sgpp::op_factory::createOperationDensityMargTo1D(), sgpp::op_factory::createOperationDensitySampling1D(), sgpp::datadriven::OperationDensityConditional::doConditional(), sgpp::datadriven::OperationDensitySampling1D::doSampling1D(), doSampling_in_next_dim(), sgpp::base::DataVector::get(), sgpp::base::Grid::getDimension(), sgpp::base::DataVector::getSize(), sgpp::datadriven::OperationDensityMargTo1D::margToDimX(), and sgpp::base::DataVector::set().
Referenced by doSampling_in_next_dim(), and doSampling_start_dimX().
doSampling_start_dimX()
void sgpp::datadriven::OperationDensitySamplingLinear::doSampling_start_dimX (base::Grid * g_in, base::DataVector * a_in, size_t dim_start, base::DataVector *& sampleVec, unsigned int * seedp) protected
References doSampling_in_next_dim(), and sgpp::base::DataVector::getSize().
Referenced by doSampling(), and doSampling().
Member Data Documentation
grid
base::Grid* sgpp::datadriven::OperationDensitySamplingLinear::grid protected
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.learner.Learner.Learner::applyData(), python.tools.Matrix::ApplyMatrix(), python.uq.dists.SGDEdist.SGDEdist::cdf(), python.uq.learner.Interpolant.Interpolant::doLearningIteration(), python.learner.Learner.Learner::doLearningIteration(), doSampling(), doSampling(), python.learner.Classifier.Classifier::evalError(), python.uq.learner.Interpolant.Interpolant::evalError(), python.tools.Matrix::generateb(), python.controller.CheckpointController.CheckpointController::generateFoldValidationJob(), python.uq.learner.SimulationLearner.SimulationLearner::getCollocationNodes(), python.uq.learner.SimulationLearner.SimulationLearner::getGrid(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), python.learner.Learner.Learner::learnData(), python.learner.Learner.Learner::learnDataWithFolding(), python.uq.learner.Regressor.Regressor::learnDataWithFolding(), python.learner.Learner.Learner::learnDataWithTest(), python.uq.learner.Regressor.Regressor::learnDataWithTest(), python.controller.CheckpointController.CheckpointController::loadAll(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), python.uq.dists.SGDEdist.SGDEdist::mean(), python.uq.dists.SGDEdist.SGDEdist::pdf(), python.uq.dists.SGDEdist.SGDEdist::ppf(), python.learner.Classifier.Classifier::refineGrid(), python.learner.Regressor.Regressor::refineGrid(), python.uq.learner.Regressor.Regressor::refineGrid(), python.uq.learner.SimulationLearner.SimulationLearner::refineGrid(), python.controller.CheckpointController.CheckpointController::saveGrid(), python.controller.CheckpointController.CheckpointController::setGrid(), python.learner.Learner.Learner::setGrid(), python.uq.learner.Learner.Learner::setGrid(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGrid::split(), python.uq.dists.SGDEdist.SGDEdist::toJson(), and python.uq.dists.SGDEdist.SGDEdist::var().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensitySamplingLinear.hpp
datadriven/src/sgpp/datadriven/operation/hash/simple/OperationDensitySamplingLinear.cpp