SG++-Doxygen-Documentation: sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT > Class Template Reference
Modified polynomial base functions.
#include <LinearModifiedClenshawCurtisBasis.hpp>
Public Member Functions
double eval (LT level, IT index, double p) override
Evaluate the basis function with given level and index.
double eval (LT level, IT index, double p, double offset, double width)
double evalDx (LT level, IT index, double x) override
Evaluate the basis functions derivative with given level and index.
double evalHierToTop (LT level, IT index, DataVector &coeffs, double pos)
Evaluates all the hierarchical ancestors of the node defined by level and index.
size_t getDegree () const override
Returns the polynomial degree of the basis.
double getIntegral (LT level, IT index) override
returns the integal of the current basis function
LinearModifiedClenshawCurtisBasis ()
Constructor.
~LinearModifiedClenshawCurtisBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
ClenshawCurtisTable & clenshawCurtisTable
reference to the Clenshaw-Curtis cache table
SLinearClenshawCurtisBase linearBasis
poly basis
Detailed Description
template<class LT, class IT>
class sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >
Modified polynomial base functions.
Special polynomial functions to cover values unequal 0 at the border. Implemented as seen in AWR 2 paper by Prof. Bungartz (http://www5.in.tum.de/wiki/index.php/Algorithmen_des_Wissenschaftlichen_Rechnens_II_-_Winter_08)
Constructor & Destructor Documentation
LinearModifiedClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::LinearModifiedClenshawCurtisBasis () inline
Constructor.
~LinearModifiedClenshawCurtisBasis()
template<class LT , class IT > sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::~LinearModifiedClenshawCurtisBasis () inline override
Destructor.
Member Function Documentation
eval() [1/2]
template<class LT , class IT > double sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval (LT level, IT index, double x) inline override virtual
Evaluate the basis function with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis function.
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::ClenshawCurtisTable::getPoint(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::OperationEvalModLinearClenshawCurtisNaive::eval(), sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::evalHierToTop(), sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::mult(), and sgpp::base::OperationMultipleEvalModLinearClenshawCurtisNaive::multTranspose().
eval() [2/2]
template<class LT , class IT > double sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval (LT level, IT index, double p, double offset, double width) inline
References sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), and level.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalDx()
template<class LT , class IT > double sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::evalDx (LT level, IT index, double x) inline override virtual
Evaluate the basis functions derivative with given level and index.
Parameters
level level of the basis function
index index of the basis function
x evaluation point
Returns
value of the basis functions derivative.
Implements sgpp::base::Basis< LT, IT >.
evalHierToTop()
template<class LT , class IT > double sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::evalHierToTop (LT level, IT index, DataVector & coeffs, double pos) inline
Evaluates all the hierarchical ancestors of the node defined by level and index.
NOTE: It does not evaluate the current node itself.
Parameters
level
index
coeffs
pos
Returns
References sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), and level.
Referenced by sgpp::base::DehierarchisationModLinearClenshawCurtis::rec(), and sgpp::base::HierarchisationModLinearClenshawCurtis::rec().
getDegree()
template<class LT , class IT > size_t sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::getDegree () const inline override virtual
Returns the polynomial degree of the basis.
Returns
polynomial degree of the basis
Implements sgpp::base::Basis< LT, IT >.
getIntegral()
template<class LT , class IT > double sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::getIntegral (LT level, IT index) inline override virtual
returns the integal of the current basis function
Parameters
level level of the basis function
index index of the basis function
Returns
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable, sgpp::base::LinearClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::ClenshawCurtisTable::getPoint(), level, and sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::linearBasis.
Referenced by sgpp::base::OperationQuadratureModLinearClenshawCurtis::doQuadrature().
Member Data Documentation
clenshawCurtisTable
template<class LT , class IT > ClenshawCurtisTable& sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::clenshawCurtisTable protected
reference to the Clenshaw-Curtis cache table
Referenced by sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::eval(), and sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
linearBasis
template<class LT , class IT > SLinearClenshawCurtisBase sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::linearBasis protected
poly basis
Referenced by sgpp::base::LinearModifiedClenshawCurtisBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/LinearModifiedClenshawCurtisBasis.hpp