SG++-Doxygen-Documentation: sgpp::datadriven::ResidualScore Class Reference
sgpp::datadriven::ResidualScore Class Reference
Metric that is based on a residual score of the model.
#include <ResidualScore.hpp>
Public Member Functions
Metric * clone () const override
Polymorphic clone pattern.
double measure (const DataVector &predictedValues, const DataVector &trueValues, const ModelFittingBase &model, Dataset &testDataset) const override
Measure the quality of the trained model.
double measureLowerIsBetter (const DataVector &predictedValues, const DataVector &trueValues, const ModelFittingBase &model, Dataset &testDataset) const override
Measure the quality of the trained model.
Public Member Functions inherited from sgpp::datadriven::Metric
Metric ()=default
Default constructor.
Metric (const Metric &rhs)=default
Copy constructor.
Metric (Metric &&rhs)=default
Move constructor.
Metric & operator= (const Metric &rhs)=default
Copy assign operator.
Metric & operator= (Metric &&rhs)=default
Move assign operator.
virtual ~Metric ()=default
virtual destructor.
Detailed Description
Metric that is based on a residual score of the model.
For density estimation, this is || R * alpha_lambda - b_val ||_2
Member Function Documentation
clone()
Metric * sgpp::datadriven::ResidualScore::clone () const override virtual
Polymorphic clone pattern.
Returns
deep copy of this object. New object is owned by caller.
Implements sgpp::datadriven::Metric.
measure()
double sgpp::datadriven::ResidualScore::measure (const DataVector & predictedValues, const DataVector & trueValues, const ModelFittingBase & model, Dataset & testDataset) const override virtual
Measure the quality of the trained model.
Gives the metric access to the trained model, as this is required for some scores.
Parameters
predictedValues ignored
trueValues ignored
model reference to the model
testDataset dataset with test data
Implements sgpp::datadriven::Metric.
References sgpp::datadriven::ModelFittingBase::computeResidual(), and sgpp::datadriven::Dataset::getData().
Referenced by measureLowerIsBetter().
measureLowerIsBetter()
double sgpp::datadriven::ResidualScore::measureLowerIsBetter (const DataVector & predictedValues, const DataVector & trueValues, const ModelFittingBase & model, Dataset & testDataset) const override virtual
Measure the quality of the trained model.
Gives the metric access to the trained model, as this is required for some scores.
Parameters
predictedValues ignored
trueValues ignored
model reference to the model
testDataset dataset with test data
Implements sgpp::datadriven::Metric.
References measure().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/scoring/ResidualScore.hpp
datadriven/src/sgpp/datadriven/datamining/modules/scoring/ResidualScore.cpp