SG++-Doxygen-Documentation: sgpp::datadriven::RefinementMonitorFactory Class Reference
sgpp::datadriven::RefinementMonitorFactory Class Reference
Factory to create refinement monitors.
#include <RefinementMonitorFactory.hpp>
Public Member Functions
RefinementMonitor * createRefinementMonitor (const sgpp::base::AdaptivityConfiguration &adaptivityConfig) const
Creates a refinement monitor.
RefinementMonitorFactory ()=default
Detailed Description
Factory to create refinement monitors.
Constructor & Destructor Documentation
RefinementMonitorFactory()
sgpp::datadriven::RefinementMonitorFactory::RefinementMonitorFactory () default
Member Function Documentation
createRefinementMonitor()
RefinementMonitor * sgpp::datadriven::RefinementMonitorFactory::createRefinementMonitor (const sgpp::base::AdaptivityConfiguration & adaptivityConfig) const
Creates a refinement monitor.
Parameters
adaptivityConfig configuration for the adaptivity of the sparse grid
Returns
a new refinement monitor instance
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::errorBasedRefinement_, sgpp::base::AdaptivityConfiguration::errorBufferSize_, sgpp::base::AdaptivityConfiguration::errorConvergenceThreshold_, sgpp::base::AdaptivityConfiguration::errorMinInterval_, and sgpp::base::AdaptivityConfiguration::refinementPeriod_.
Referenced by sgpp::datadriven::SparseGridMinerCrossValidation::learn(), sgpp::datadriven::SparseGridMinerSplitting::learn(), and sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/RefinementMonitorFactory.hpp
datadriven/src/sgpp/datadriven/algorithm/RefinementMonitorFactory.cpp