SG++-Doxygen-Documentation: sgpp::pde::PhiPhiUpBBLinearStretchedBoundary Class Reference
sgpp::pde::PhiPhiUpBBLinearStretchedBoundary Class Reference
Implementation of sgpp::base::sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
#include <PhiPhiUpBBLinearStretchedBoundary.hpp>
Public Member Functions
virtual void operator() (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim)
This operations performs the calculation of up in the direction of dimension dim
PhiPhiUpBBLinearStretchedBoundary (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiUpBBLinearStretchedBoundary ()
Destructor.
Public Member Functions inherited from sgpp::pde::PhiPhiUpBBLinearStretched
PhiPhiUpBBLinearStretched (sgpp::base::GridStorage *storage)
Constructor.
virtual ~PhiPhiUpBBLinearStretched ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::pde::PhiPhiUpBBLinearStretched
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::pde::PhiPhiUpBBLinearStretched
void rec (sgpp::base::DataVector &source, sgpp::base::DataVector &result, grid_iterator &index, size_t dim, double &fl, double &fr)
recursive function for the calculation of Up without bounding Box support
Protected Attributes inherited from sgpp::pde::PhiPhiUpBBLinearStretched
sgpp::base::GridStorage * storage
Pointer to sgpp::base::GridStorage object.
sgpp::base::Stretching * stretching
Pointer to the sgpp::base::Stretching Object.
Detailed Description
Implementation of sgpp::base::sweep operator (): 1D Up for Bilinearform \(\int_{x} \phi(x) \phi(x) dx\) on linear boundary grids.
Constructor & Destructor Documentation
PhiPhiUpBBLinearStretchedBoundary()
sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::PhiPhiUpBBLinearStretchedBoundary (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~PhiPhiUpBBLinearStretchedBoundary()
sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::~PhiPhiUpBBLinearStretchedBoundary () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::PhiPhiUpBBLinearStretchedBoundary::operator() (sgpp::base::DataVector & source, sgpp::base::DataVector & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of up in the direction of dimension dim
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
Parameters
source sgpp::base::DataVector that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataVector that contains the result of the up operation
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::pde::PhiPhiUpBBLinearStretched.
References sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::BoundingBox::hasDirichletBoundaryLeft(), sgpp::base::BoundingBox::hasDirichletBoundaryRight(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::pde::PhiPhiUpBBLinearStretched::rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), sgpp::pde::PhiPhiUpBBLinearStretched::storage, and sgpp::pde::PhiPhiUpBBLinearStretched::stretching.
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linearstretched/boundary/algorithm_sweep/PhiPhiUpBBLinearStretchedBoundary.hpp
pde/src/sgpp/pde/basis/linearstretched/boundary/algorithm_sweep/PhiPhiUpBBLinearStretchedBoundary.cpp