SG++-Doxygen-Documentation: sgpp::datadriven::SparseGridMinerSplittingTwoDatasets Class Reference
sgpp::datadriven::SparseGridMinerSplittingTwoDatasets Class Reference
SparseGridMinerSplittingTwoDatasets models a datamining process that involves two input datasets that are first split into validation and training data.
#include <SparseGridMinerSplittingTwoDatasets.hpp>
Public Member Functions
double learn (bool verbose) override
Perform Learning cycle: Get samples from data source and based on the scoring procedure, generalize data by fitting and asses quality of the fit.
SparseGridMinerSplittingTwoDatasets & operator= (const SparseGridMinerSplittingTwoDatasets &rhs)=delete
Default copy assign operator deleted - not all members can be copied.
SparseGridMinerSplittingTwoDatasets & operator= (SparseGridMinerSplittingTwoDatasets &&rhs)=default
Default Move assign operator.
SparseGridMinerSplittingTwoDatasets (const SparseGridMinerSplittingTwoDatasets &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned.
SparseGridMinerSplittingTwoDatasets (SparseGridMinerSplittingTwoDatasets &&rhs)=default
Default Move constructor.
SparseGridMinerSplittingTwoDatasets (std::vector< DataSourceSplitting * > dataSource, ModelFittingBase *fitter, Scorer *scorer, Visualizer *visualizer)
Constructor.
~SparseGridMinerSplittingTwoDatasets () override=default
Default destructor.
Public Member Functions inherited from sgpp::datadriven::SparseGridMiner
ModelFittingBase * getModel ()
Returns the trained model.
Visualizer * getVisualizer ()
SparseGridMiner & operator= (const SparseGridMiner &rhs)=delete
Default copy assign operator deleted because not all members can be copied.
SparseGridMiner & operator= (SparseGridMiner &&rhs)=default
Default Move assign operator.
void setModel (ModelFittingBase *model)
SparseGridMiner (const SparseGridMiner &rhs)=delete
Copy constructor deleted - not all members can be copied or cloned .
SparseGridMiner (ModelFittingBase *fitter, Scorer *scorer, Visualizer *visualizer)
Constructor.
SparseGridMiner (SparseGridMiner &&rhs)=default
Default Move constructor .
double test (Dataset &testDataset)
Evaluate the model on a certain test dataset.
virtual ~SparseGridMiner ()=default
Default destructor.
Additional Inherited Members
Static Public Member Functions inherited from sgpp::datadriven::SparseGridMiner
static void print (const char *message)
Print output on one process.
static void print (const std::string &message)
Print output on one process.
static void print (std::ostringstream &messageStream)
Print output on one process.
Protected Attributes inherited from sgpp::datadriven::SparseGridMiner
std::unique_ptr< ModelFittingBase > fitter
Fitter that trains a model based on data samples.
std::unique_ptr< Scorer > scorer
Scorer that quantifies the quality of a fit.
std::unique_ptr< Visualizer > visualizer
Detailed Description
SparseGridMinerSplittingTwoDatasets models a datamining process that involves two input datasets that are first split into validation and training data.
The model is then trained on the training data for several epochs.
Constructor & Destructor Documentation
SparseGridMinerSplittingTwoDatasets() [1/3]
sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::SparseGridMinerSplittingTwoDatasets (std::vector< DataSourceSplitting * > dataSource, ModelFittingBase * fitter, Scorer * scorer, Visualizer * visualizer)
Constructor.
Parameters
dataSource vector of configured instances of data source object, that will provide samples to learn from. The miner instance will take ownership of the passed object.
fitter configured instance of fitter object that generalize the model. The miner instance will take ownership of the passed object.
scorer configured instance of scorer object that will assess the quality of the generalization provided by the fitter on testing data. The miner instance will take ownership of the passed object.
visualizer configured instance of viusalizer object that will produce the output to visualize the model and its results
SparseGridMinerSplittingTwoDatasets() [2/3]
sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::SparseGridMinerSplittingTwoDatasets (const SparseGridMinerSplittingTwoDatasets & rhs) delete
Copy constructor deleted - not all members can be copied or cloned.
Parameters
rhs the object to copy from
SparseGridMinerSplittingTwoDatasets() [3/3]
sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::SparseGridMinerSplittingTwoDatasets (SparseGridMinerSplittingTwoDatasets && rhs) default
Default Move constructor.
Parameters
rhs the object to move from
~SparseGridMinerSplittingTwoDatasets()
sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::~SparseGridMinerSplittingTwoDatasets () override default
Default destructor.
Member Function Documentation
learn()
double sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::learn (bool verbose) override virtual
Perform Learning cycle: Get samples from data source and based on the scoring procedure, generalize data by fitting and asses quality of the fit.
The learning process first divides the data into training and validation data and trains the model for several epochs on the training data.
Implements sgpp::datadriven::SparseGridMiner.
References sgpp::datadriven::RefinementMonitorFactory::createRefinementMonitor(), sgpp::datadriven::SparseGridMiner::fitter, sgpp::datadriven::RefinementMonitor::pushToBuffer(), sgpp::datadriven::RefinementMonitor::refinementsNecessary(), and sgpp::datadriven::SparseGridMiner::scorer.
operator=() [1/2]
SparseGridMinerSplittingTwoDatasets & sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::operator= (const SparseGridMinerSplittingTwoDatasets & rhs) delete
Default copy assign operator deleted - not all members can be copied.
Parameters
rhs the object to copy from
operator=() [2/2]
SparseGridMinerSplittingTwoDatasets & sgpp::datadriven::SparseGridMinerSplittingTwoDatasets::operator= (SparseGridMinerSplittingTwoDatasets && rhs) default
Default Move assign operator.
Parameters
rhs the object to move from
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/base/SparseGridMinerSplittingTwoDatasets.hpp
datadriven/src/sgpp/datadriven/datamining/base/SparseGridMinerSplittingTwoDatasets.cpp