SG++-Doxygen-Documentation: sgpp::base::NakBsplineBasis< LT, IT > Class Template Reference
sgpp::base::NakBsplineBasis< LT, IT > Class Template Reference
Not-a-knot B-spline basis.
#include <NakBsplineBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
size_t getDegree () const override
double getIntegral (LT l, IT i) override
double getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights)
NakBsplineBasis ()
Default constructor.
NakBsplineBasis (size_t degree)
Constructor.
~NakBsplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis for B-spline evaluation.
Detailed Description
template<class LT, class IT>
class sgpp::base::NakBsplineBasis< LT, IT >
Not-a-knot B-spline basis.
Constructor & Destructor Documentation
NakBsplineBasis() [1/2]
template<class LT , class IT > sgpp::base::NakBsplineBasis< LT, IT >::NakBsplineBasis () inline
Default constructor.
NakBsplineBasis() [2/2]
template<class LT , class IT > sgpp::base::NakBsplineBasis< LT, IT >::NakBsplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree B-spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::NakBsplineBasis< LT, IT >::getDegree().
~NakBsplineBasis()
template<class LT , class IT > sgpp::base::NakBsplineBasis< LT, IT >::~NakBsplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::NakBsplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBasis< LT, IT >::bsplineBasis, and sgpp::base::NakBsplineBasis< LT, IT >::getDegree().
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalNakBsplineNaive::eval(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineBoundaryNaive::evalGradient(), sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalHessianNakBsplineBoundaryNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeNakBsplineBoundaryNaive::evalPartialDerivative().
evalDx()
template<class LT , class IT > double sgpp::base::NakBsplineBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of B-spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBasis< LT, IT >::bsplineBasis, and sgpp::base::NakBsplineBasis< LT, IT >::getDegree().
Referenced by sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient(), and sgpp::base::OperationEvalGradientNakBsplineNaive::evalGradient().
getDegree()
template<class LT , class IT > size_t sgpp::base::NakBsplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
B-spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBasis< LT, IT >::bsplineBasis.
Referenced by sgpp::base::NakBsplineBasis< LT, IT >::eval(), sgpp::base::NakBsplineBasis< LT, IT >::evalDx(), sgpp::base::NakBsplineBasis< LT, IT >::getIntegral(), sgpp::base::NakBsplineBasis< LT, IT >::getMean(), and sgpp::base::NakBsplineBasis< LT, IT >::NakBsplineBasis().
getIntegral()
template<class LT , class IT > double sgpp::base::NakBsplineBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
integral of basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::NakBsplineBasis< LT, IT >::getDegree(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), and sgpp::base::NakBsplineBasis< LT, IT >::getMean().
getMean()
template<class LT , class IT > double sgpp::base::NakBsplineBasis< LT, IT >::getMean (LT l, IT i, std::shared_ptr< sgpp::base::Distribution > pdf, std::shared_ptr< sgpp::base::DataVector > quadCoordinates, std::shared_ptr< sgpp::base::DataVector > quadWeights) inline
Parameters
l level of basis function
i index of basis function
pdf probability density function
quadCoordinates coordinates of the quadrature rule to be used
quadWeights weights of the quadrature rule to be used
Returns
integral of basis function
References sgpp::base::NakBsplineBasis< LT, IT >::getDegree().
Referenced by sgpp::base::OperationWeightedQuadratureNakBspline::doWeightedQuadrature(), and sgpp::base::NakBsplineBasis< LT, IT >::getIntegral().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::NakBsplineBasis< LT, IT >::bsplineBasis protected
B-spline basis for B-spline evaluation.
Referenced by sgpp::base::NakBsplineBasis< LT, IT >::eval(), sgpp::base::NakBsplineBasis< LT, IT >::evalDx(), and sgpp::base::NakBsplineBasis< LT, IT >::getDegree().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/NakBsplineBasis.hpp