SG++-Doxygen-Documentation: sgpp::datadriven::GaussianKernel Class Reference
sgpp::datadriven::GaussianKernel Class Reference
#include <KernelDensityEstimator.hpp>
Public Member Functions
double cdf (double x) override
double derivative (double x) override
double eval (double x) override
KernelType getType () override
double norm () override
double variance () override
~GaussianKernel () override
Public Member Functions inherited from sgpp::datadriven::Kernel
virtual ~Kernel ()
Constructor & Destructor Documentation
~GaussianKernel()
sgpp::datadriven::GaussianKernel::~GaussianKernel () override
Member Function Documentation
cdf()
double sgpp::datadriven::GaussianKernel::cdf (double x) override virtual
Implements sgpp::datadriven::Kernel.
References M_SQRT2.
derivative()
double sgpp::datadriven::GaussianKernel::derivative (double x) override virtual
Implements sgpp::datadriven::Kernel.
References eval().
eval()
double sgpp::datadriven::GaussianKernel::eval (double x) override virtual
Implements sgpp::datadriven::Kernel.
Referenced by derivative(), and python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getType()
KernelType sgpp::datadriven::GaussianKernel::getType () override virtual
Implements sgpp::datadriven::Kernel.
References sgpp::datadriven::GAUSSIAN.
norm()
double sgpp::datadriven::GaussianKernel::norm () override virtual
Implements sgpp::datadriven::Kernel.
References M_SQRT2PI.
Referenced by python.uq.dists.MultivariateNormal.MultivariateNormal::pdf().
variance()
double sgpp::datadriven::GaussianKernel::variance () override virtual
Implements sgpp::datadriven::Kernel.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp