SG++-Doxygen-Documentation: sgpp::optimization::optimizer::AdaptiveNewton Class Reference
sgpp::optimization::optimizer::AdaptiveNewton Class Reference
Newton method with adaptive step size.
#include <AdaptiveNewton.hpp>
Public Member Functions
AdaptiveNewton (const AdaptiveNewton &other)
Copy constructor.
AdaptiveNewton (const base::ScalarFunction &f, const base::ScalarFunctionHessian &fHessian, size_t maxItCount, double tolerance, double stepSizeIncreaseFactor, double stepSizeDecreaseFactor, double dampingIncreaseFactor, double dampingDecreaseFactor, double lineSearchAccuracy, const base::sle_solver::SLESolver &sleSolver)
Constructor.
AdaptiveNewton (const base::ScalarFunction &f, const base::ScalarFunctionHessian &fHessian, size_t maxItCount=DEFAULT_N, double tolerance=DEFAULT_TOLERANCE, double stepSizeIncreaseFactor=DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor=DEFAULT_STEP_SIZE_DECREASE_FACTOR, double dampingIncreaseFactor=DEFAULT_DAMPING_INCREASE_FACTOR, double dampingDecreaseFactor=DEFAULT_DAMPING_DECREASE_FACTOR, double lineSearchAccuracy=DEFAULT_LINE_SEARCH_ACCURACY)
Constructor.
void clone (std::unique_ptr< UnconstrainedOptimizer > &clone) const override
double getDampingDecreaseFactor () const
double getDampingIncreaseFactor () const
double getLineSearchAccuracy () const
double getStepSizeDecreaseFactor () const
double getStepSizeIncreaseFactor () const
double getTolerance () const
void optimize () override
Pure virtual method for optimization of the objective function.
void setDampingDecreaseFactor (double dampingDecreaseFactor)
void setDampingIncreaseFactor (double dampingIncreaseFactor)
void setLineSearchAccuracy (double lineSearchAccuracy)
void setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
void setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
void setTolerance (double tolerance)
~AdaptiveNewton () override
Destructor.
Public Member Functions inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
const base::DataMatrix & getHistoryOfOptimalPoints () const
const base::DataVector & getHistoryOfOptimalValues () const
size_t getN () const
base::ScalarFunction & getObjectiveFunction () const
base::ScalarFunctionGradient * getObjectiveGradient () const
base::ScalarFunctionHessian * getObjectiveHessian () const
const base::DataVector & getOptimalPoint () const
double getOptimalValue () const
const base::DataVector & getStartingPoint () const
void setN (size_t N)
virtual void setObjectiveFunction (const base::ScalarFunction &f)
virtual void setObjectiveGradient (const base::ScalarFunctionGradient *fGradient)
virtual void setObjectiveHessian (const base::ScalarFunctionHessian *fHessian)
void setStartingPoint (const base::DataVector &startingPoint)
UnconstrainedOptimizer (const base::ScalarFunction &f, const base::ScalarFunctionGradient *fGradient, const base::ScalarFunctionHessian *fHessian, size_t N=DEFAULT_N)
Constructor.
UnconstrainedOptimizer (const UnconstrainedOptimizer &other)
Copy constructor.
virtual ~UnconstrainedOptimizer ()
Destructor.
Static Public Attributes
static constexpr double DEFAULT_DAMPING_DECREASE_FACTOR = 0.5
default damping decrease factor
static constexpr double DEFAULT_DAMPING_INCREASE_FACTOR = 1.0
default damping increase factor
static constexpr double DEFAULT_LINE_SEARCH_ACCURACY = 0.01
default line search accuracy
static constexpr double DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5
default step size decrease factor
static constexpr double DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2
default step size increase factor
static constexpr double DEFAULT_TOLERANCE = 1e-6
default tolerance
Static Public Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
static const size_t DEFAULT_N = 1000
default maximal number of iterations or function evaluations
Protected Attributes
const base::sle_solver::GaussianElimination defaultSleSolver
default linear solver
double rhoAlphaMinus
step size decrease factor
double rhoAlphaPlus
step size increase factor
double rhoLambdaMinus
damping decrease factor
double rhoLambdaPlus
damping increase factor
double rhoLs
line search accuracy
const base::sle_solver::SLESolver & sleSolver
linear solver
double theta
tolerance
Protected Attributes inherited from sgpp::optimization::optimizer::UnconstrainedOptimizer
std::unique_ptr< base::ScalarFunction > f
objective function
std::unique_ptr< base::ScalarFunctionGradient > fGradient
objective function gradient
std::unique_ptr< base::ScalarFunctionHessian > fHessian
objective function Hessian
base::DataVector fHist
search history vector (optimal values)
double fOpt
result of optimization (optimal function value)
size_t N
maximal number of iterations or function evaluations
base::DataVector x0
starting point
base::DataMatrix xHist
search history matrix (optimal points)
base::DataVector xOpt
result of optimization (location of optimum)
Detailed Description
Newton method with adaptive step size.
Constructor & Destructor Documentation
AdaptiveNewton() [1/3]
sgpp::optimization::optimizer::AdaptiveNewton::AdaptiveNewton (const base::ScalarFunction & f, const base::ScalarFunctionHessian & fHessian, size_t maxItCount = DEFAULT_N, double tolerance = DEFAULT_TOLERANCE, double stepSizeIncreaseFactor = DEFAULT_STEP_SIZE_INCREASE_FACTOR, double stepSizeDecreaseFactor = DEFAULT_STEP_SIZE_DECREASE_FACTOR, double dampingIncreaseFactor = DEFAULT_DAMPING_INCREASE_FACTOR, double dampingDecreaseFactor = DEFAULT_DAMPING_DECREASE_FACTOR, double lineSearchAccuracy = DEFAULT_LINE_SEARCH_ACCURACY)
Constructor.
By default, GaussianElimination is used to solve the linear systems.
Parameters
f objective function
fHessian objective function Hessian
maxItCount maximal number of function evaluations
tolerance tolerance
stepSizeIncreaseFactor step size increase factor
stepSizeDecreaseFactor step size decrease factor
dampingIncreaseFactor damping increase factor
dampingDecreaseFactor damping decrease factor
lineSearchAccuracy line search accuracy
AdaptiveNewton() [2/3]
sgpp::optimization::optimizer::AdaptiveNewton::AdaptiveNewton (const base::ScalarFunction & f, const base::ScalarFunctionHessian & fHessian, size_t maxItCount, double tolerance, double stepSizeIncreaseFactor, double stepSizeDecreaseFactor, double dampingIncreaseFactor, double dampingDecreaseFactor, double lineSearchAccuracy, const base::sle_solver::SLESolver & sleSolver)
Constructor.
Do not destruct the solver before this object!
Parameters
f objective function
fHessian objective function Hessian
maxItCount maximal number of function evaluations
tolerance tolerance
stepSizeIncreaseFactor step size increase factor
stepSizeDecreaseFactor step size decrease factor
dampingIncreaseFactor damping increase factor
dampingDecreaseFactor damping decrease factor
lineSearchAccuracy line search accuracy
sleSolver reference to linear solver for solving the linear systems (Hessian as coefficient matrix)
AdaptiveNewton() [3/3]
sgpp::optimization::optimizer::AdaptiveNewton::AdaptiveNewton (const AdaptiveNewton & other)
Copy constructor.
Parameters
other optimizer to be copied
~AdaptiveNewton()
sgpp::optimization::optimizer::AdaptiveNewton::~AdaptiveNewton () override
Destructor.
Member Function Documentation
clone()
void sgpp::optimization::optimizer::AdaptiveNewton::clone (std::unique_ptr< UnconstrainedOptimizer > & clone) const override virtual
Parameters
[out] clone pointer to cloned object
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References clone().
Referenced by clone().
getDampingDecreaseFactor()
double sgpp::optimization::optimizer::AdaptiveNewton::getDampingDecreaseFactor () const
Returns
damping decrease factor
References rhoLambdaMinus.
getDampingIncreaseFactor()
double sgpp::optimization::optimizer::AdaptiveNewton::getDampingIncreaseFactor () const
Returns
damping increase factor
References rhoLambdaPlus.
getLineSearchAccuracy()
double sgpp::optimization::optimizer::AdaptiveNewton::getLineSearchAccuracy () const
Returns
line search accuracy
References rhoLs.
getStepSizeDecreaseFactor()
double sgpp::optimization::optimizer::AdaptiveNewton::getStepSizeDecreaseFactor () const
Returns
step size decrease factor
References rhoAlphaMinus.
getStepSizeIncreaseFactor()
double sgpp::optimization::optimizer::AdaptiveNewton::getStepSizeIncreaseFactor () const
Returns
step size increase factor
References rhoAlphaPlus.
getTolerance()
double sgpp::optimization::optimizer::AdaptiveNewton::getTolerance () const
Returns
tolerance
References theta.
optimize()
void sgpp::optimization::optimizer::AdaptiveNewton::optimize () override virtual
Pure virtual method for optimization of the objective function.
The result of the optimization process can be obtained by member functions, e.g., getOptimalPoint() and getOptimalValue().
Implements sgpp::optimization::optimizer::UnconstrainedOptimizer.
References alpha, sgpp::base::DataVector::append(), sgpp::base::DataMatrix::appendRow(), sgpp::base::Printer::disableStatusPrinting(), sgpp::base::DataVector::dotProduct(), sgpp::base::Printer::enableStatusPrinting(), sgpp::optimization::optimizer::UnconstrainedOptimizer::f, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHessian, sgpp::optimization::optimizer::UnconstrainedOptimizer::fHist, sgpp::optimization::optimizer::UnconstrainedOptimizer::fOpt, sgpp::base::Printer::getInstance(), sgpp::base::Printer::isStatusPrintingEnabled(), sgpp::base::DataVector::l2Norm(), lambda, sgpp::optimization::optimizer::UnconstrainedOptimizer::N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataMatrix::resize(), rhoAlphaMinus, rhoAlphaPlus, rhoLambdaMinus, rhoLambdaPlus, rhoLs, sleSolver, sgpp::base::sle_solver::SLESolver::solve(), theta, sgpp::base::DataVector::toString(), sgpp::optimization::optimizer::UnconstrainedOptimizer::x0, sgpp::optimization::optimizer::UnconstrainedOptimizer::xHist, and sgpp::optimization::optimizer::UnconstrainedOptimizer::xOpt.
setDampingDecreaseFactor()
void sgpp::optimization::optimizer::AdaptiveNewton::setDampingDecreaseFactor (double dampingDecreaseFactor)
Parameters
dampingDecreaseFactor damping decrease factor
References rhoLambdaMinus.
setDampingIncreaseFactor()
void sgpp::optimization::optimizer::AdaptiveNewton::setDampingIncreaseFactor (double dampingIncreaseFactor)
Parameters
dampingIncreaseFactor damping increase factor
References rhoLambdaPlus.
setLineSearchAccuracy()
void sgpp::optimization::optimizer::AdaptiveNewton::setLineSearchAccuracy (double lineSearchAccuracy)
Parameters
lineSearchAccuracy line search accuracy
References rhoLs.
setStepSizeDecreaseFactor()
void sgpp::optimization::optimizer::AdaptiveNewton::setStepSizeDecreaseFactor (double stepSizeDecreaseFactor)
Parameters
stepSizeDecreaseFactor step size decrease factor
References rhoAlphaMinus.
setStepSizeIncreaseFactor()
void sgpp::optimization::optimizer::AdaptiveNewton::setStepSizeIncreaseFactor (double stepSizeIncreaseFactor)
Parameters
stepSizeIncreaseFactor step size increase factor
References rhoAlphaPlus.
setTolerance()
void sgpp::optimization::optimizer::AdaptiveNewton::setTolerance (double tolerance)
Parameters
tolerance tolerance
References theta.
Member Data Documentation
DEFAULT_DAMPING_DECREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_DAMPING_DECREASE_FACTOR = 0.5 static constexpr
default damping decrease factor
DEFAULT_DAMPING_INCREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_DAMPING_INCREASE_FACTOR = 1.0 static constexpr
default damping increase factor
DEFAULT_LINE_SEARCH_ACCURACY
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_LINE_SEARCH_ACCURACY = 0.01 static constexpr
default line search accuracy
DEFAULT_STEP_SIZE_DECREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_STEP_SIZE_DECREASE_FACTOR = 0.5 static constexpr
default step size decrease factor
DEFAULT_STEP_SIZE_INCREASE_FACTOR
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_STEP_SIZE_INCREASE_FACTOR = 1.2 static constexpr
default step size increase factor
DEFAULT_TOLERANCE
constexpr double sgpp::optimization::optimizer::AdaptiveNewton::DEFAULT_TOLERANCE = 1e-6 static constexpr
default tolerance
defaultSleSolver
const base::sle_solver::GaussianElimination sgpp::optimization::optimizer::AdaptiveNewton::defaultSleSolver protected
default linear solver
rhoAlphaMinus
double sgpp::optimization::optimizer::AdaptiveNewton::rhoAlphaMinus protected
step size decrease factor
Referenced by getStepSizeDecreaseFactor(), optimize(), and setStepSizeDecreaseFactor().
rhoAlphaPlus
double sgpp::optimization::optimizer::AdaptiveNewton::rhoAlphaPlus protected
step size increase factor
Referenced by getStepSizeIncreaseFactor(), optimize(), and setStepSizeIncreaseFactor().
rhoLambdaMinus
double sgpp::optimization::optimizer::AdaptiveNewton::rhoLambdaMinus protected
damping decrease factor
Referenced by getDampingDecreaseFactor(), optimize(), and setDampingDecreaseFactor().
rhoLambdaPlus
double sgpp::optimization::optimizer::AdaptiveNewton::rhoLambdaPlus protected
damping increase factor
Referenced by getDampingIncreaseFactor(), optimize(), and setDampingIncreaseFactor().
rhoLs
double sgpp::optimization::optimizer::AdaptiveNewton::rhoLs protected
line search accuracy
Referenced by getLineSearchAccuracy(), optimize(), and setLineSearchAccuracy().
sleSolver
const base::sle_solver::SLESolver& sgpp::optimization::optimizer::AdaptiveNewton::sleSolver protected
linear solver
Referenced by optimize().
theta
double sgpp::optimization::optimizer::AdaptiveNewton::theta protected
tolerance
Referenced by getTolerance(), optimize(), and setTolerance().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/optimizer/unconstrained/AdaptiveNewton.hpp
optimization/src/sgpp/optimization/optimizer/unconstrained/AdaptiveNewton.cpp