SG++-Doxygen-Documentation: sgpp::base::RandomNumberGenerator Class Reference
sgpp::base::RandomNumberGenerator Class Reference
Singleton class for generating pseudo-random numbers (wrapper around std::mt19937 from <random>).
#include <RandomNumberGenerator.hpp>
Public Types
typedef std::mt19937::result_type SeedType
type of the seed
Public Member Functions
double getGaussianRN (double mean=0.0, double stdDev=1.0)
Generate a Gaussian pseudo-random number.
void getGaussianRV (DataVector &vector, double mean=0.0, double stdDev=1.0)
Fills vector with Gaussian pseudo-random numbers.
SeedType getSeed () const
size_t getUniformIndexRN (size_t size)
Generate a uniform pseudo-random array index.
double getUniformRN (double a=0.0, double b=1.0)
Generate a uniform pseudo-random number.
void getUniformRV (DataVector &vector, double a=0.0, double b=1.0)
Fills vector with uniform pseudo-random numbers.
void setSeed ()
Reseeds with time-dependent seed.
void setSeed (SeedType seed)
Reseeds.
Static Public Member Functions
static RandomNumberGenerator & getInstance ()
Protected Attributes
std::mt19937 generator
random number generator
SeedType seed
seed
Detailed Description
Singleton class for generating pseudo-random numbers (wrapper around std::mt19937 from <random>).
Member Typedef Documentation
SeedType
typedef std::mt19937::result_type sgpp::base::RandomNumberGenerator::SeedType
type of the seed
Member Function Documentation
getGaussianRN()
double sgpp::base::RandomNumberGenerator::getGaussianRN (double mean = 0.0, double stdDev = 1.0)
Generate a Gaussian pseudo-random number.
Parameters
mean mean of the Gaussian distribution
stdDev standard deviation of the Gaussian distribution
Returns
Gaussian pseudo-random number
References generator.
Referenced by sgpp::optimization::test_problems::ConstrainedTestProblem::generateDisplacement(), sgpp::optimization::test_problems::UnconstrainedTestProblem::generateDisplacement(), getGaussianRV(), and sgpp::optimization::optimizer::CMAES::optimize().
getGaussianRV()
void sgpp::base::RandomNumberGenerator::getGaussianRV (DataVector & vector, double mean = 0.0, double stdDev = 1.0)
Fills vector with Gaussian pseudo-random numbers.
Parameters
[out] vector vector to be filled, has to have desired size beforehand
mean mean of the Gaussian distribution
stdDev standard deviation of the Gaussian distribution
References getGaussianRN(), and sgpp::base::DataVector::getSize().
getInstance()
RandomNumberGenerator & sgpp::base::RandomNumberGenerator::getInstance () static
Returns
singleton instance
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), sgpp::optimization::test_problems::ConstrainedTestProblem::generateDisplacement(), sgpp::optimization::test_problems::UnconstrainedTestProblem::generateDisplacement(), sgpp::optimization::ResponseSurface::l2Error(), sgpp::optimization::ResponseSurface::nrmsError(), sgpp::optimization::optimizer::CMAES::optimize(), sgpp::optimization::optimizer::DifferentialEvolution::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), and sgpp::optimization::ResponseSurface::precalculateErrorTestData().
getSeed()
RandomNumberGenerator::SeedType sgpp::base::RandomNumberGenerator::getSeed () const
Returns
seed
References seed.
getUniformIndexRN()
size_t sgpp::base::RandomNumberGenerator::getUniformIndexRN (size_t size)
Generate a uniform pseudo-random array index.
Parameters
size size of the array
Returns
discrete uniform pseudo-random number in \(\{0, \dotsc, \text{\texttt{size}} - 1\}\)
References generator.
Referenced by sgpp::optimization::optimizer::DifferentialEvolution::optimize().
getUniformRN()
double sgpp::base::RandomNumberGenerator::getUniformRN (double a = 0.0, double b = 1.0)
Generate a uniform pseudo-random number.
Parameters
a lower bound
b upper bound
Returns
uniform pseudo-random number in \([a, b]\)
References generator.
Referenced by sgpp::optimization::ResponseSurfaceVector::averageL2Error(), sgpp::optimization::ResponseSurfaceVector::averageNRMSE(), getUniformRV(), sgpp::optimization::ResponseSurface::l2Error(), sgpp::optimization::ResponseSurface::nrmsError(), sgpp::optimization::optimizer::DifferentialEvolution::optimize(), sgpp::optimization::optimizer::MultiStart::optimize(), and sgpp::optimization::ResponseSurface::precalculateErrorTestData().
getUniformRV()
void sgpp::base::RandomNumberGenerator::getUniformRV (DataVector & vector, double a = 0.0, double b = 1.0)
Fills vector with uniform pseudo-random numbers.
Parameters
[out] vector vector to be filled, has to have desired size beforehand
a lower bound
b upper bound
References sgpp::base::DataVector::getSize(), and getUniformRN().
setSeed() [1/2]
void sgpp::base::RandomNumberGenerator::setSeed ()
Reseeds with time-dependent seed.
References setSeed().
Referenced by setSeed().
setSeed() [2/2]
void sgpp::base::RandomNumberGenerator::setSeed (RandomNumberGenerator::SeedType seed)
Reseeds.
Parameters
seed seed to be used
References generator, and seed.
Member Data Documentation
generator
std::mt19937 sgpp::base::RandomNumberGenerator::generator protected
random number generator
Referenced by getGaussianRN(), getUniformIndexRN(), getUniformRN(), and setSeed().
seed
SeedType sgpp::base::RandomNumberGenerator::seed protected
seed
Referenced by getSeed(), setSeed(), and python.uq.learner.builder.RegressorSpecificationDescriptor.FoldingDescriptor::withSeed().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/RandomNumberGenerator.hpp
base/src/sgpp/base/tools/RandomNumberGenerator.cpp