SG++-Doxygen-Documentation: python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder Class Reference
python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder Class Reference
Public Member Functions
__init__ (self, builder=None)
getDescriptor (self)
Public Member Functions inherited from python.uq.parameters.ParameterBuilder.GeneralParameterBuilder
andGetResult (self)
new (self)
Additional Inherited Members
Protected Attributes inherited from python.uq.parameters.ParameterBuilder.GeneralParameterBuilder
_builder
_params
Detailed Description
Deterministic parameter builder
Constructor & Destructor Documentation
__init__()
python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder.__init__ (self, builder = None)
Reimplemented from python.uq.parameters.ParameterBuilder.GeneralParameterBuilder.
References python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder.__init__().
Referenced by python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder.__init__().
Member Function Documentation
getDescriptor()
python.uq.parameters.ParameterBuilder.DeterministicParameterBuilder.getDescriptor (self)
Reimplemented from python.uq.parameters.ParameterBuilder.GeneralParameterBuilder.
Referenced by python.uq.parameters.ParameterBuilder.GeneralParameterBuilder.new().
The documentation for this class was generated from the following file:
datadriven/python/uq/parameters/ParameterBuilder.py