SG++-Doxygen-Documentation: sgpp::optimization::SplineResponseSurface Class Reference
sgpp::optimization::SplineResponseSurface Class Reference
stores a sparse grid not a knot B-spline interpolant in the framework of a respsonse surface
#include <SplineResponseSurface.hpp>
Public Member Functions
double eval (sgpp::base::DataVector v) override
evaluates this response surface
double evalGradient (sgpp::base::DataVector v, sgpp::base::DataVector &gradient) override
evaluates the response surface and its gradient
sgpp::base::DataVector getCoefficients ()
std::shared_ptr< sgpp::base::Grid > getGrid ()
double getIntegral ()
return the integral of the response surface
sgpp::base::DataVector getLowerBounds ()
double getMean (sgpp::base::DistributionsVector pdfs, size_t quadOrder)
return the mean of the response surface w.r.t.
size_t getSize ()
sgpp::base::DataVector getUpperBounds ()
sgpp::base::DataVector getVariance (sgpp::base::DistributionsVector pdfs, size_t quadOrder)
return the variance of the response surface w.r.t.
void nextSurplusAdaptiveGrid (size_t refinementsNum, bool verbose=false)
refines the grid surplus adaptive but does not recalculate interpolation coefficients
sgpp::base::DataVector optimize ()
calculates the minimimum with gradient descent
void refineSurplusAdaptive (size_t refinementsNum, bool verbose=false)
refines the grid surplus adaptive and recalculates the interpoaltion coefficients
void regular (size_t level)
creates a regular sparse grid interpolant
void regularByPoints (size_t numPoints, bool verbose=false)
creates a regular grid of the lowest level with more grid points than specified
void ritterNovak (size_t maxNumGridPoints, double gamma, size_t initialLevel=3, bool verbose=false)
creates an adaptive grid based on Ritter-Novak this is favourable for optimization
SplineResponseSurface (std::shared_ptr< sgpp::base::Grid > grid, sgpp::base::DataVector coefficients, sgpp::base::DataVector lb, sgpp::base::DataVector ub, size_t degree=3)
Constructor.
SplineResponseSurface (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, sgpp::base::DataVector lb, sgpp::base::DataVector ub, sgpp::base::GridType gridType, size_t degree=3, size_t boundaryLevel=1)
Constructor.
SplineResponseSurface (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, std::shared_ptr< sgpp::base::Grid > grid, sgpp::base::DataVector lb, sgpp::base::DataVector ub, size_t degree=3)
Constructor.
void surplusAdaptive (size_t maxNumGridPoints, size_t initialLevel, size_t refinementsNum=3, bool verbose=false)
creates a surplus adaptive sparse grid interpolant
~SplineResponseSurface () override
Destructor.
Public Member Functions inherited from sgpp::optimization::ResponseSurface
double l2Error (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, size_t numMCPoints=1000)
Calculates the l2 error between interpolant and objective function.
sgpp::base::DataVector nrmsError (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, size_t numMCPoints=1000)
Calculates the normalized root mean square error between interpolant and objective function in random points.
sgpp::base::DataVector nrmsErrorFromTestData (const std::string &fileName, size_t numMCPoints, size_t numDim)
Calculates the normalized root mean square error between interpolant and objective function from a precalculated set of test points and according values (this set is usually generated by ResponseSurface::precalculateErrorTestData)
void precalculateErrorTestData (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, size_t numMCPoints, const std::string &fileName)
Evaluates the objective function in random points and stores these points with the according evaluation value The stored set of test data can then later be used to calculate and compare the approximation error.
ResponseSurface (size_t numDim)
Constructor.
virtual ~ResponseSurface ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from sgpp::optimization::ResponseSurface
double domainVolume ()
calculates the volume of the tensor product domain given by lb and ub
void transformPoint (sgpp::base::DataVector &v, sgpp::base::DataVector lBounds, sgpp::base::DataVector uBounds, sgpp::base::DataVector newlBounds, sgpp::base::DataVector newuBounds)
transforms a point in hyper-rectangle [lBounds,rBounds] to the hyper-rectangle [newlBounds,newuBounds]
Protected Attributes inherited from sgpp::optimization::ResponseSurface
std::shared_ptr< sgpp::base::ScalarFunction > interpolant
std::shared_ptr< sgpp::base::ScalarFunctionGradient > interpolantGradient
sgpp::base::DataVector lb
size_t numDim
sgpp::base::DataVector ub
Detailed Description
stores a sparse grid not a knot B-spline interpolant in the framework of a respsonse surface
Constructor & Destructor Documentation
SplineResponseSurface() [1/3]
sgpp::optimization::SplineResponseSurface::SplineResponseSurface (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, sgpp::base::DataVector lb, sgpp::base::DataVector ub, sgpp::base::GridType gridType, size_t degree = 3, size_t boundaryLevel = 1) inline
Constructor.
Parameters
objectiveFunc objective Function
lb lower bounds
ub upper bounds
gridType type of the interpolants grid/basis
degree degree of the interpolants basis
boundaryLevel boundary level
Note: Currently boundaryLevel is only available for gridType nakBsplineBoundary
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalSpline, sgpp::optimization::ResponseSurface::lb, sgpp::base::ModBspline, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::optimization::ResponseSurface::numDim, sgpp::base::PolyBoundary, sgpp::optimization::ResponseSurface::ub, and sgpp::base::WeaklyFundamentalNakSplineBoundary.
SplineResponseSurface() [2/3]
sgpp::optimization::SplineResponseSurface::SplineResponseSurface (std::shared_ptr< sgpp::base::ScalarFunction > objectiveFunc, std::shared_ptr< sgpp::base::Grid > grid, sgpp::base::DataVector lb, sgpp::base::DataVector ub, size_t degree = 3) inline
Constructor.
Parameters
objectiveFunc objective Function
grid grid
lb lower bounds
ub upper bounds
degree degree of the interpolants basis
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalSpline, sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, sgpp::optimization::ResponseSurface::lb, sgpp::base::ModBspline, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::optimization::ResponseSurface::numDim, sgpp::base::PolyBoundary, sgpp::optimization::ResponseSurface::ub, and sgpp::base::WeaklyFundamentalNakSplineBoundary.
SplineResponseSurface() [3/3]
sgpp::optimization::SplineResponseSurface::SplineResponseSurface (std::shared_ptr< sgpp::base::Grid > grid, sgpp::base::DataVector coefficients, sgpp::base::DataVector lb, sgpp::base::DataVector ub, size_t degree = 3) inline
Constructor.
Parameters
grid grid
coefficients coefficients matching the grid
lb lower bounds
ub upper bounds
degree degree of the interpolants basis
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalSpline, sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, sgpp::optimization::ResponseSurface::lb, sgpp::base::ModBspline, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::optimization::ResponseSurface::numDim, sgpp::base::PolyBoundary, sgpp::optimization::ResponseSurface::ub, and sgpp::base::WeaklyFundamentalNakSplineBoundary.
~SplineResponseSurface()
sgpp::optimization::SplineResponseSurface::~SplineResponseSurface () inline override
Destructor.
Member Function Documentation
eval()
double sgpp::optimization::SplineResponseSurface::eval (sgpp::base::DataVector v) override virtual
evaluates this response surface
Parameters
v point to evaluate in
Returns
the evaluation
Reimplemented from sgpp::optimization::ResponseSurface.
References sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::lb, sgpp::optimization::ResponseSurface::transformPoint(), and sgpp::optimization::ResponseSurface::ub.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
evalGradient()
double sgpp::optimization::SplineResponseSurface::evalGradient (sgpp::base::DataVector v, sgpp::base::DataVector & gradient) override virtual
evaluates the response surface and its gradient
Parameters
v point to evaluate in
gradient reference to return the repsonse surfaces gradient evaluted in v
Returns
the evaluation
Implements sgpp::optimization::ResponseSurface.
References sgpp::base::DataVector::getSize(), sgpp::optimization::ResponseSurface::interpolantGradient, sgpp::optimization::ResponseSurface::lb, sgpp::optimization::ResponseSurface::transformPoint(), and sgpp::optimization::ResponseSurface::ub.
getCoefficients()
sgpp::base::DataVector sgpp::optimization::SplineResponseSurface::getCoefficients () inline
Returns
the interpolation coefficients
getGrid()
std::shared_ptr< sgpp::base::Grid > sgpp::optimization::SplineResponseSurface::getGrid () inline
Returns
the interpolation grid
Referenced by python.uq.analysis.asgc.ASGCKnowledge.ASGCKnowledge::getSparseGridFunction(), python.uq.learner.SimulationLearner.SimulationLearner::learnData(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithFolding(), python.uq.learner.SimulationLearner.SimulationLearner::learnDataWithTest(), and python.uq.learner.SimulationLearner.SimulationLearner::refineGrid().
getIntegral()
double sgpp::optimization::SplineResponseSurface::getIntegral ()
return the integral of the response surface
References sgpp::op_factory::createOperationQuadrature(), sgpp::optimization::ResponseSurface::domainVolume(), and sgpp::base::OperationQuadrature::doQuadrature().
getLowerBounds()
sgpp::base::DataVector sgpp::optimization::SplineResponseSurface::getLowerBounds () inline
Returns
the lower bounds of the domain
References sgpp::optimization::ResponseSurface::lb.
getMean()
double sgpp::optimization::SplineResponseSurface::getMean (sgpp::base::DistributionsVector pdfs, size_t quadOrder)
return the mean of the response surface w.r.t.
a probability density function
Parameters
pdfs the probability density function
quadOrder order of the Gauss Legendre quadrature
References sgpp::op_factory::createOperationWeightedQuadrature(), and sgpp::base::OperationWeightedQuadrature::doWeightedQuadrature().
Referenced by getVariance().
getSize()
size_t sgpp::optimization::SplineResponseSurface::getSize () inline
Returns
the number of grid points
Referenced by python.uq.uq_setting.UQSetting.UQSetting::convert(), python.uq.uq_setting.UQSetting.UQSetting::getTimeDependentResults(), python.uq.uq_setting.UQSetting.UQSetting::runSamples(), and python.uq.uq_setting.UQSetting.UQSetting::runSamples_withoutDistribution().
getUpperBounds()
sgpp::base::DataVector sgpp::optimization::SplineResponseSurface::getUpperBounds () inline
Returns
the upper bounds of the domain
References sgpp::optimization::ResponseSurface::ub.
getVariance()
sgpp::base::DataVector sgpp::optimization::SplineResponseSurface::getVariance (sgpp::base::DistributionsVector pdfs, size_t quadOrder)
return the variance of the response surface w.r.t.
a probability density function
Parameters
pdfs the probability density function
quadOrder order of the Gauss Legendre quadrature
Returns
vector [v,mS,m] containing the variance v and the meanSquare mS and mean m used to compute it
References sgpp::op_factory::createOperationWeightedSecondMoment(), sgpp::base::OperationWeightedSecondMoment::doWeightedQuadrature(), and getMean().
nextSurplusAdaptiveGrid()
void sgpp::optimization::SplineResponseSurface::nextSurplusAdaptiveGrid (size_t refinementsNum, bool verbose = false)
refines the grid surplus adaptive but does not recalculate interpolation coefficients
Parameters
refinementsNum number of grid points which should be refined
verbose print information on the refine points
Referenced by refineSurplusAdaptive().
optimize()
sgpp::base::DataVector sgpp::optimization::SplineResponseSurface::optimize ()
calculates the minimimum with gradient descent
Returns
argmin of the response surface
The gradient method needs a starting point. We use the grid point with the smallest (most promising) function value and save it in x0.
References sgpp::optimization::optimizer::UnconstrainedOptimizer::getOptimalPoint(), sgpp::base::DataVector::getPointer(), sgpp::base::DataVector::getSize(), sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, sgpp::optimization::ResponseSurface::lb, sgpp::optimization::ResponseSurface::numDim, sgpp::optimization::optimizer::GradientDescent::optimize(), sgpp::optimization::optimizer::UnconstrainedOptimizer::setStartingPoint(), sgpp::optimization::ResponseSurface::transformPoint(), and sgpp::optimization::ResponseSurface::ub.
refineSurplusAdaptive()
void sgpp::optimization::SplineResponseSurface::refineSurplusAdaptive (size_t refinementsNum, bool verbose = false)
refines the grid surplus adaptive and recalculates the interpoaltion coefficients
Parameters
refinementsNum number of grid points which should be refined
verbose print information on the refine points
References nextSurplusAdaptiveGrid().
Referenced by surplusAdaptive().
regular()
void sgpp::optimization::SplineResponseSurface::regular (size_t level)
creates a regular sparse grid interpolant
Parameters
level level of the regular sparse grid
References sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, level, sgpp::base::ModPoly, and sgpp::base::PolyBoundary.
Referenced by surplusAdaptive().
regularByPoints()
void sgpp::optimization::SplineResponseSurface::regularByPoints (size_t numPoints, bool verbose = false)
creates a regular grid of the lowest level with more grid points than specified
Parameters
numPoints desired number of grid points
verbose print extra info
References sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, level, sgpp::base::ModPoly, and sgpp::base::PolyBoundary.
ritterNovak()
void sgpp::optimization::SplineResponseSurface::ritterNovak (size_t maxNumGridPoints, double gamma, size_t initialLevel = 3, bool verbose = false)
creates an adaptive grid based on Ritter-Novak this is favourable for optimization
Parameters
maxNumGridPoints maximum number of grid points of the interpolants grid
gamma Ritter Novak adaptivity parameter between 0 and1
initialLevel initial level for the refinement
verbose print extra info
References sgpp::optimization::IterativeGridGeneratorRitterNovak::generate(), sgpp::optimization::ResponseSurface::interpolant, and sgpp::optimization::ResponseSurface::interpolantGradient.
surplusAdaptive()
void sgpp::optimization::SplineResponseSurface::surplusAdaptive (size_t maxNumGridPoints, size_t initialLevel, size_t refinementsNum = 3, bool verbose = false)
creates a surplus adaptive sparse grid interpolant
Parameters
maxNumGridPoints maximum number of grid points of the interpolants grid
initialLevel first a regular grid of initialLevel is created.
refinementsNum max number of grid points, added in each refinement step
verbose print extra info
References sgpp::optimization::ResponseSurface::interpolant, sgpp::optimization::ResponseSurface::interpolantGradient, sgpp::base::ModPoly, sgpp::base::PolyBoundary, refineSurplusAdaptive(), and regular().
The documentation for this class was generated from the following files:
optimization/src/sgpp/optimization/function/scalar/SplineResponseSurface.hpp
optimization/src/sgpp/optimization/function/scalar/SplineResponseSurface.cpp