SG++-Doxygen-Documentation: sgpp::datadriven::MinerFactory Class Reference
sgpp::datadriven::MinerFactory Class Reference abstract
Abstract factory to build different kinds of Miners based on a configuration which is parsed from a file.
#include <MinerFactory.hpp>
Public Member Functions
virtual sgpp::datadriven::HyperparameterOptimizer * buildHPO (const std::string &path) const
virtual SparseGridMiner * buildMiner (const std::string &path) const
Factory method to build a miner object based on a configuration file.
MinerFactory ()=default
Default constructor.
virtual ~MinerFactory ()=default
Virtual destructor.
Protected Member Functions
virtual DataSourceCrossValidation * createDataSourceCrossValidation (const DataMiningConfigParser &parser) const
Factory method to build a cross validation data source, i.e.
virtual DataSourceSplitting * createDataSourceSplitting (const DataMiningConfigParser &parser) const
Factory method to build a splitting based data source, i.e.
virtual std::vector< DataSourceSplitting * > createDataSourceSplittingTwoDatasets (const DataMiningConfigParser &parser) const
virtual ModelFittingBase * createFitter (const DataMiningConfigParser &parser) const =0
Build an instance of a sgpp::datadriven::ModelFittingBase object as specified in the configuration file.
virtual FitterFactory * createFitterFactory (const DataMiningConfigParser &parser) const =0
virtual Scorer * createScorer (const DataMiningConfigParser &parser) const
Factory method to build a scorer instance base d on a configuration file.
virtual Visualizer * createVisualizer (const DataMiningConfigParser &parser) const =0
Factory method to build a visualizer instance base on a configuration file.
Detailed Description
Abstract factory to build different kinds of Miners based on a configuration which is parsed from a file.
A miner consists of a data source, a fitter and a scorer. A concrete Factory class has to implement the required interfaces.
Constructor & Destructor Documentation
MinerFactory()
sgpp::datadriven::MinerFactory::MinerFactory () default
Default constructor.
~MinerFactory()
virtual sgpp::datadriven::MinerFactory::~MinerFactory () virtual default
Virtual destructor.
Member Function Documentation
buildHPO()
sgpp::datadriven::HyperparameterOptimizer * sgpp::datadriven::MinerFactory::buildHPO (const std::string & path) const virtual
Reimplemented in sgpp::datadriven::DensityEstimationMinerFactory.
References buildMiner(), and createFitterFactory().
buildMiner()
SparseGridMiner * sgpp::datadriven::MinerFactory::buildMiner (const std::string & path) const virtual
Factory method to build a miner object based on a configuration file.
Parameters
path Path to a configuration file that defines the structure of the miner object.
Reimplemented in sgpp::datadriven::DensityDifferenceEstimationMinerFactory, and sgpp::datadriven::DensityRatioEstimationMinerFactory.
References createDataSourceCrossValidation(), createDataSourceSplitting(), createFitter(), createScorer(), and createVisualizer().
Referenced by buildHPO(), and sgpp::datadriven::DensityEstimationMinerFactory::buildHPO().
createDataSourceCrossValidation()
DataSourceCrossValidation * sgpp::datadriven::MinerFactory::createDataSourceCrossValidation (const DataMiningConfigParser & parser) const protected virtual
Factory method to build a cross validation data source, i.e.
a data source that can separate one fold from the data as validation set and use the rest for training
Parameters
parser the datamining configuration parser instance to create the data source from
Returns
the data source instance
References sgpp::datadriven::DataSourceBuilder::crossValidationFromConfig().
Referenced by buildMiner(), sgpp::datadriven::DensityDifferenceEstimationMinerFactory::buildMiner(), and sgpp::datadriven::DensityRatioEstimationMinerFactory::buildMiner().
createDataSourceSplitting()
DataSourceSplitting * sgpp::datadriven::MinerFactory::createDataSourceSplitting (const DataMiningConfigParser & parser) const protected virtual
Factory method to build a splitting based data source, i.e.
a data source that splits data into validation and training data.
Parameters
parser the datamining configuration parser instance to create the data source from
Returns
the data source instance
References sgpp::datadriven::DataSourceBuilder::splittingFromConfig().
Referenced by buildMiner().
createDataSourceSplittingTwoDatasets()
virtual std::vector< DataSourceSplitting * > sgpp::datadriven::MinerFactory::createDataSourceSplittingTwoDatasets (const DataMiningConfigParser & parser) const inline protected virtual
createFitter()
virtual ModelFittingBase * sgpp::datadriven::MinerFactory::createFitter (const DataMiningConfigParser & parser) const protected pure virtual
Build an instance of a sgpp::datadriven::ModelFittingBase object as specified in the configuration file.
Parameters
parser parser object that provides methods to query the configuration file.
Returns
Fully configured fitter (instance of a sgpp::datadriven::ModelFittingBase object) as specified in the configuration file.
Referenced by buildMiner().
createFitterFactory()
virtual FitterFactory * sgpp::datadriven::MinerFactory::createFitterFactory (const DataMiningConfigParser & parser) const protected pure virtual
Referenced by buildHPO().
createScorer()
Scorer * sgpp::datadriven::MinerFactory::createScorer (const DataMiningConfigParser & parser) const protected virtual
Factory method to build a scorer instance base d on a configuration file.
Parameters
parser the datamining configuration parser instance to create the scorer from
Returns
the scorer instance
Referenced by buildMiner(), sgpp::datadriven::DensityDifferenceEstimationMinerFactory::buildMiner(), and sgpp::datadriven::DensityRatioEstimationMinerFactory::buildMiner().
createVisualizer()
virtual Visualizer * sgpp::datadriven::MinerFactory::createVisualizer (const DataMiningConfigParser & parser) const protected pure virtual
Factory method to build a visualizer instance base on a configuration file.
Parameters
parser the datamining configuration parser instance to create the scorer from
Returns
the scorer instance
Referenced by buildMiner().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/builder/MinerFactory.hpp
datadriven/src/sgpp/datadriven/datamining/builder/MinerFactory.cpp