SG++-Doxygen-Documentation: sgpp::datadriven::OperationMultipleEvalConfiguration Class Reference
sgpp::datadriven::OperationMultipleEvalConfiguration Class Reference
#include <DatadrivenOperationCommon.hpp>
Public Member Functions
OperationMultipleEvalMPIType getMPIType ()
std::string & getName ()
std::shared_ptr< base::OperationConfiguration > getParameters ()
OperationMultipleEvalSubType getSubType ()
OperationMultipleEvalType getType ()
OperationMultipleEvalConfiguration (OperationMultipleEvalType type, OperationMultipleEvalSubType subType, base::OperationConfiguration &parameters, std::string name="unnamed")
OperationMultipleEvalConfiguration (OperationMultipleEvalType type, OperationMultipleEvalSubType subType, OperationMultipleEvalMPIType mpiType, base::OperationConfiguration &parameters, std::string name="unnamed")
OperationMultipleEvalConfiguration (OperationMultipleEvalType type=OperationMultipleEvalType::DEFAULT, OperationMultipleEvalSubType subType=OperationMultipleEvalSubType::DEFAULT, OperationMultipleEvalMPIType mpiType=OperationMultipleEvalMPIType::NONE, std::string name="unnamed")
Constructor & Destructor Documentation
OperationMultipleEvalConfiguration() [1/3]
sgpp::datadriven::OperationMultipleEvalConfiguration::OperationMultipleEvalConfiguration (OperationMultipleEvalType type = OperationMultipleEvalType::DEFAULT, OperationMultipleEvalSubType subType = OperationMultipleEvalSubType::DEFAULT, OperationMultipleEvalMPIType mpiType = OperationMultipleEvalMPIType::NONE, std::string name = "unnamed") inline
OperationMultipleEvalConfiguration() [2/3]
sgpp::datadriven::OperationMultipleEvalConfiguration::OperationMultipleEvalConfiguration (OperationMultipleEvalType type, OperationMultipleEvalSubType subType, base::OperationConfiguration & parameters, std::string name = "unnamed") inline
References sgpp::base::OperationConfiguration::clone().
OperationMultipleEvalConfiguration() [3/3]
sgpp::datadriven::OperationMultipleEvalConfiguration::OperationMultipleEvalConfiguration (OperationMultipleEvalType type, OperationMultipleEvalSubType subType, OperationMultipleEvalMPIType mpiType, base::OperationConfiguration & parameters, std::string name = "unnamed") inline
References sgpp::base::OperationConfiguration::clone().
Member Function Documentation
getMPIType()
OperationMultipleEvalMPIType sgpp::datadriven::OperationMultipleEvalConfiguration::getMPIType () inline
Referenced by sgpp::op_factory::createOperationMultipleEval().
getName()
std::string & sgpp::datadriven::OperationMultipleEvalConfiguration::getName () inline
getParameters()
std::shared_ptr< base::OperationConfiguration > sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters () inline
Referenced by sgpp::datadriven::createStreamingBSplineOCLConfigured(), sgpp::datadriven::createStreamingModOCLFastMultiPlatformConfigured(), sgpp::datadriven::createStreamingModOCLMaskMultiPlatformConfigured(), sgpp::datadriven::createStreamingModOCLOptConfigured(), sgpp::datadriven::createStreamingModOCLUnifiedConfigured(), sgpp::datadriven::createStreamingOCLMultiPlatformConfigured(), python.uq.learner.SimulationLearner.SimulationLearner::getLearner(), and sgpp::datadriven::OperationMultiEvalHPX::mult().
getSubType()
OperationMultipleEvalSubType sgpp::datadriven::OperationMultipleEvalConfiguration::getSubType () inline
Referenced by sgpp::op_factory::createOperationMultipleEval(), and sgpp::datadriven::OperationMultiEvalHPX::mult().
getType()
OperationMultipleEvalType sgpp::datadriven::OperationMultipleEvalConfiguration::getType () inline
Referenced by sgpp::op_factory::createOperationMultipleEval(), and sgpp::datadriven::OperationMultiEvalHPX::mult().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/DatadrivenOperationCommon.hpp