SG++-Doxygen-Documentation: sgpp::pde::OperationMatrixLTwoDotExplicitLinear Class Reference
sgpp::pde::OperationMatrixLTwoDotExplicitLinear Class Reference
Explicit representation of the matrix \((\Phi_i,\Phi_j)_{L2}\) for a sparse grid.
#include <OperationMatrixLTwoDotExplicitLinear.hpp>
Public Member Functions
void buildMatrixWithBounds (sgpp::base::DataMatrix *mat, sgpp::base::Grid *grid, size_t i_start=0, size_t i_end=0, size_t j_start=0, size_t j_end=0)
generalization of "buildMatrix" function, creates L2-dot-product matrix for specified bounds
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
Implementation of standard matrix multiplication.
OperationMatrixLTwoDotExplicitLinear ()
Constructor that only builds the object, without initialization.
OperationMatrixLTwoDotExplicitLinear (sgpp::base::DataMatrix *m, sgpp::base::Grid *grid)
Constructor that uses an external matrix pointer to construct the matrix, i.e.
OperationMatrixLTwoDotExplicitLinear (sgpp::base::Grid *grid)
Constructor that creates an own matrix i.e.
virtual ~OperationMatrixLTwoDotExplicitLinear ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Detailed Description
Explicit representation of the matrix \((\Phi_i,\Phi_j)_{L2}\) for a sparse grid.
Constructor & Destructor Documentation
OperationMatrixLTwoDotExplicitLinear() [1/3]
sgpp::pde::OperationMatrixLTwoDotExplicitLinear::OperationMatrixLTwoDotExplicitLinear ()
Constructor that only builds the object, without initialization.
OperationMatrixLTwoDotExplicitLinear() [2/3]
sgpp::pde::OperationMatrixLTwoDotExplicitLinear::OperationMatrixLTwoDotExplicitLinear (sgpp::base::DataMatrix * m, sgpp::base::Grid * grid)
Constructor that uses an external matrix pointer to construct the matrix, i.e.
matrix is NOT destroyed by the destructor of OperationMatrixLTwoDotExplicitLinearFullGrid
Parameters
m pointer to datamatrix of size (number of grid point) x (number of grid points)
grid the sparse grid
References grid(), and m.
OperationMatrixLTwoDotExplicitLinear() [3/3]
sgpp::pde::OperationMatrixLTwoDotExplicitLinear::OperationMatrixLTwoDotExplicitLinear (sgpp::base::Grid * grid) explicit
Constructor that creates an own matrix i.e.
matrix is destroyed by the destructor of OperationMatrixLTwoDotExplicitLinearFullGrid
Parameters
grid the sparse grid
References grid().
~OperationMatrixLTwoDotExplicitLinear()
sgpp::pde::OperationMatrixLTwoDotExplicitLinear::~OperationMatrixLTwoDotExplicitLinear () virtual
Destructor.
Member Function Documentation
buildMatrixWithBounds()
void sgpp::pde::OperationMatrixLTwoDotExplicitLinear::buildMatrixWithBounds (sgpp::base::DataMatrix * mat, sgpp::base::Grid * grid, size_t i_start = 0, size_t i_end = 0, size_t j_start = 0, size_t j_end = 0) inline
generalization of "buildMatrix" function, creates L2-dot-product matrix for specified bounds
Parameters
mat matrix for storage of L2 producs
grid the underlying grid
i_start start index for row iteration
i_end end index for row iteration
j_start start index for column iteration
j_end end index for column iteration
References sgpp::base::DataMatrix::get(), grid(), level, and sgpp::base::DataMatrix::set().
mult()
void sgpp::pde::OperationMatrixLTwoDotExplicitLinear::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) virtual
Implementation of standard matrix multiplication.
Parameters
alpha DataVector that is multiplied to the matrix
result DataVector into which the result of multiplication is stored
Implements sgpp::base::OperationMatrix.
References alpha, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), and sgpp::base::DataVector::getSize().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotExplicitLinear.hpp
pde/src/sgpp/pde/operation/hash/OperationMatrixLTwoDotExplicitLinear.cpp