SG++-Doxygen-Documentation: sgpp::base::DistributionUniform Class Reference
sgpp::base::DistributionUniform Class Reference
#include <DistributionUniform.hpp>
Public Member Functions
DistributionUniform (double l=0, double r=1)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionUniform ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Constructor & Destructor Documentation
DistributionUniform()
sgpp::base::DistributionUniform::DistributionUniform (double l = 0, double r = 1) inline explicit
Constructor.
~DistributionUniform()
virtual sgpp::base::DistributionUniform::~DistributionUniform () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionUniform::eval (double x) inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionUniform::getBounds () inline virtual
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), getCharacteristics(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionUniform::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
References getBounds().
getType()
sgpp::base::DistributionType sgpp::base::DistributionUniform::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Uniform.
sample()
double sgpp::base::DistributionUniform::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionUniform.hpp