SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOfflineDenseIChol Class Reference
sgpp::datadriven::DBMatOfflineDenseIChol Class Reference
DBMatOfflineChol specialization that uses a parallel, iterative incomplete cholesky factorization on a dense matrix.
#include <DBMatOfflineDenseIChol.hpp>
Public Member Functions
void choleskyModification (Grid &grid, datadriven::DensityEstimationConfiguration &densityEstimationConfig, size_t newPoints, std::vector< size_t > &deletedPoints, double lambda) override
Updates offline cholesky factorization based on coarsed (deletedPoints) and refined (newPoints) gridPoints.
DBMatOffline * clone () const override
Interface for the clone idiom.
DBMatOfflineDenseIChol ()
DBMatOfflineDenseIChol (const std::string &fileName)
void decomposeMatrix (const RegularizationConfiguration &regularizationConfig, const DensityEstimationConfiguration &densityEstimationConfig) override
Decomposes the matrix according to the chosen decomposition type.
sgpp::datadriven::MatrixDecompositionType getDecompositionType () override
Returns the decomposition type of the DBMatOffline object.
Public Member Functions inherited from sgpp::datadriven::DBMatOfflineChol
void compute_inverse () override
void compute_inverse_parallel (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig) override
parallel/distributed version of compute_inverse()
DBMatOfflineChol ()
DBMatOfflineChol (const std::string &fileName)
void decomposeMatrixParallel (RegularizationConfiguration &regularizationConfig, DensityEstimationConfiguration &densityEstimationConfig, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig) override
The parallel/distributed version of decomposeMatrix(...)
const DataMatrix & getUnmodifiedR () override
Get the unmodified (without added lambda) system matrix R.
const DataMatrixDistributed & getUnmodifiedRDistributed (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig) override
Get the unmodified (without added lambda) system matrix R.
bool isRefineable () override
Only Offline objects based on Cholesky decomposition, or orthogonal adaptivity can be refined.
void updateRegularization (double lambda) override
Modifies the decomposition to update the regularization parameter lambda.
void updateRegularizationParallel (double lambda, std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig) override
Modifies the parallel decomposition to update the regularization parameter lambda.
Public Member Functions inherited from sgpp::datadriven::DBMatOfflineGE
void buildMatrix (Grid *grid, const RegularizationConfiguration &regularizationConfig) override
Builds the right hand side matrix with identity regularization term.
DBMatOfflineGE (const std::string &fileName)
Public Member Functions inherited from sgpp::datadriven::DBMatOffline
void compute_L2_refine_vectors (DataMatrix *mat_refine, Grid *grid, size_t newPoints)
computes vectors of L2 products of grid points for refinement
DBMatOffline (const DBMatOffline &rhs)
Copy Constructor.
DBMatOffline (const std::string &fileName)
Constructor Create offline object from serialized offline object.
DBMatOffline (DBMatOffline &&rhs)=default
Default move constructor.
DataMatrixDistributed & getDecomposedInverseDistributed ()
Get a reference to the distributed decomposed matrix, analogously to getDecomposedMatrixDistributed()
DataMatrix & getDecomposedMatrix ()
Get a reference to the decomposed matrix.
DataMatrixDistributed & getDecomposedMatrixDistributed ()
Get a reference to the distributed decomposed matrix.
virtual size_t getGridSize ()
Returns the dimensionality of the quadratic lhs matrix (i.e.
DataMatrix & getInverseMatrix ()
Get a reference to the inverse matrix.
DataMatrix & getLhsMatrix_ONLY_FOR_TESTING ()
Allows access to lhs matrix, which is meant ONLY FOR TESTING.
DBMatOffline & operator= (const DBMatOffline &rhs)
Default copy assign operator.
DBMatOffline & operator= (DBMatOffline &&rhs)=default
Default move assign operator.
void printMatrix ()
Prints the matrix onto standard output.
virtual void store (const std::string &fileName)
Serialize the DBMatOffline Object.
virtual void syncDistributedDecomposition (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the decomposed matrix.
virtual void syncDistributedInverse (std::shared_ptr< BlacsProcessGrid > processGrid, const ParallelConfiguration &parallelConfig)
Synchronizes the inverse matrix.
virtual ~DBMatOffline ()=default
Default virtual destructor.
Static Public Member Functions
static void ichol (const DataMatrix &matrix, DataMatrix &result, size_t sweeps=4, size_t startRow=0)
perform parlallel incomplete cholesky factorization of a matrix.
Additional Inherited Members
Public Attributes inherited from sgpp::datadriven::DBMatOffline
std::set< std::set< size_t > > interactions
Protected Member Functions inherited from sgpp::datadriven::DBMatOfflineChol
void choleskyAddPoint (DataVector &newCol, size_t size)
Updates the cholesky factor when a new grid point is added (e.g.
void choleskyPermutation (size_t k, size_t l, size_t job)
Permutes the rows of the cholesky factor based on permutations of the system matrix (e.g.
Protected Member Functions inherited from sgpp::datadriven::DBMatOfflineGE
DBMatOfflineGE ()
Protected Member Functions inherited from sgpp::datadriven::DBMatOffline
DBMatOffline ()
void parseInter (const std::string &fileName, std::set< std::set< size_t > > &interactions) const
Read the Interactionsterms from a serialized DBMatOfflibe object.
Protected Attributes inherited from sgpp::datadriven::DBMatOffline
bool isConstructed
bool isDecomposed
DataMatrixDistributed lhsDistributed
DataMatrixDistributed lhsDistributedInverse
DataMatrix lhsInverse
DataMatrix lhsMatrix
Detailed Description
DBMatOfflineChol specialization that uses a parallel, iterative incomplete cholesky factorization on a dense matrix.
The current implementation is a proof of concept.
Constructor & Destructor Documentation
DBMatOfflineDenseIChol() [1/2]
sgpp::datadriven::DBMatOfflineDenseIChol::DBMatOfflineDenseIChol ()
DBMatOfflineDenseIChol() [2/2]
sgpp::datadriven::DBMatOfflineDenseIChol::DBMatOfflineDenseIChol (const std::string & fileName) explicit
Member Function Documentation
choleskyModification()
void sgpp::datadriven::DBMatOfflineDenseIChol::choleskyModification (Grid & grid, datadriven::DensityEstimationConfiguration & densityEstimationConfig, size_t newPoints, std::vector< size_t > & deletedPoints, double lambda) override virtual
Updates offline cholesky factorization based on coarsed (deletedPoints) and refined (newPoints) gridPoints.
We ignore coarsening.
Parameters
grid the underlying grid
densityEstimationConfig configuration for the density estimation
newPoints amount of refined points
deletedPoints list of indices of last coarsed points that are ignored.
lambda the regularization parameter
Reimplemented from sgpp::datadriven::DBMatOfflineChol.
References sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNrows(), grid(), ichol(), sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsRefine_, lambda, level, sgpp::datadriven::DBMatOffline::lhsMatrix, and sgpp::base::DataMatrix::set().
clone()
DBMatOffline * sgpp::datadriven::DBMatOfflineDenseIChol::clone () const override virtual
Interface for the clone idiom.
Returns
a copy of this very object as a pointer to a new DBMatOffline object which is owned by the caller.
Reimplemented from sgpp::datadriven::DBMatOfflineChol.
decomposeMatrix()
void sgpp::datadriven::DBMatOfflineDenseIChol::decomposeMatrix (const RegularizationConfiguration & regularizationConfig, const DensityEstimationConfiguration & densityEstimationConfig) override virtual
Decomposes the matrix according to the chosen decomposition type.
The number of rows of the stored result depends on the decomposition type.
Parameters
regularizationConfig the regularization configuration
densityEstimationConfig the density estimation configuration
Reimplemented from sgpp::datadriven::DBMatOfflineChol.
References sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), ichol(), sgpp::datadriven::DensityEstimationConfiguration::iCholSweepsDecompose_, sgpp::datadriven::DBMatOffline::isConstructed, sgpp::datadriven::DBMatOffline::isDecomposed, sgpp::datadriven::DBMatOffline::lhsMatrix, and sgpp::base::DataMatrix::set().
getDecompositionType()
sgpp::datadriven::MatrixDecompositionType sgpp::datadriven::DBMatOfflineDenseIChol::getDecompositionType () override virtual
Returns the decomposition type of the DBMatOffline object.
Returns
the type of matrix decomposition
Reimplemented from sgpp::datadriven::DBMatOfflineChol.
References sgpp::datadriven::DenseIchol.
ichol()
void sgpp::datadriven::DBMatOfflineDenseIChol::ichol (const DataMatrix & matrix, DataMatrix & result, size_t sweeps = 4, size_t startRow = 0) static
perform parlallel incomplete cholesky factorization of a matrix.
This is an out of place operation.
Parameters
matrix the matrix to be decomposed
result data matrix that will hold the decomposed matrix
sweeps how many iterations of the algorithm are required until the result is good enough?
startRow on which row to start the decomposition (needed for refinement)
References sgpp::base::DataMatrix::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getSize(), and sgpp::base::DataMatrix::set().
Referenced by choleskyModification(), sgpp::datadriven::DBMatDMSDenseIChol::choleskyUpdateLambda(), and decomposeMatrix().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/algorithm/DBMatOfflineDenseIChol.hpp
datadriven/src/sgpp/datadriven/algorithm/DBMatOfflineDenseIChol.cpp