SG++-Doxygen-Documentation: sgpp::pde::LaplaceEnhancedDownBBLinear Class Reference
sgpp::pde::LaplaceEnhancedDownBBLinear Class Reference
Implementation of sweep operator () for enhanced Laplace operator, down operation.
#include <LaplaceEnhancedDownBBLinear.hpp>
Public Member Functions
LaplaceEnhancedDownBBLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual void operator() (sgpp::base::DataMatrix &source, sgpp::base::DataMatrix &result, grid_iterator &index, size_t dim)
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
virtual ~LaplaceEnhancedDownBBLinear ()
Destructor.
Protected Types
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Member Functions
void rec (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Down (L2 scalar product) without Bounding Box
void rec_GL (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (gradient and L2 scalar product) without Bounding Box
void rec_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Down (gradient) without Bounding Box
void rec_LG (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar product and gradient) without Bounding Box
void rec_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar products) without Bounding Box
void recBB (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of Down (L2 scalar product) with Bounding Box
void recBB_GL (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (gradient and L2 scalar product) with Bounding Box
void recBB_grad (size_t dim, grid_iterator &index)
recursive function for the calculation of Down (gradient) with Bounding Box
void recBB_LG (double fl, double fr, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar product and gradient) with Bounding Box
void recBB_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator &index)
recursive function for the calculation of merged-Down (L2 scalar products) with Bounding Box
Protected Attributes
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::BoundingBox * boundingBox
Pointer to the bounding box Obejct.
size_t cur_algo_dim_
current algorithmic dimension for the overall operator
const size_t numAlgoDims_
number of algorithmic dimensions
double * ptr_result_
pointer to DataMatrix containing result coefficients
double * ptr_source_
pointer to DataMatrix containing source coefficients
double q_
stretching of basis functions in current algorithmic domain
sgpp::base::GridStorage * storage
Pointer to the sgpp::base::GridStorage Object.
double t_
translation of basis function in current algorithmic domain
Detailed Description
Implementation of sweep operator () for enhanced Laplace operator, down operation.
This sweep operator calculates all downs (L2 scalar products and gradient) for a given dimension.
Member Typedef Documentation
grid_iterator
typedef sgpp::base::GridStorage::grid_iterator sgpp::pde::LaplaceEnhancedDownBBLinear::grid_iterator protected
Constructor & Destructor Documentation
LaplaceEnhancedDownBBLinear()
sgpp::pde::LaplaceEnhancedDownBBLinear::LaplaceEnhancedDownBBLinear (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~LaplaceEnhancedDownBBLinear()
sgpp::pde::LaplaceEnhancedDownBBLinear::~LaplaceEnhancedDownBBLinear () virtual
Destructor.
Member Function Documentation
operator()()
void sgpp::pde::LaplaceEnhancedDownBBLinear::operator() (sgpp::base::DataMatrix & source, sgpp::base::DataMatrix & result, grid_iterator & index, size_t dim) virtual
This operations performs the calculation of down in the direction of dimension dim on a grid with Dirichlet 0 boundary conditions.
Parameters
source sgpp::base::DataMatrix that contains the gridpoint's coefficients (values from the vector of the laplace operation)
result sgpp::base::DataMatrix that contains the result of the down operation
index an iterator object of the grid
dim current fixed dimension of the 'execution direction', here all downs are calculated
Reimplemented in sgpp::pde::LaplaceEnhancedDownBBLinearBoundary.
References algoDims, boundingBox, cur_algo_dim_, sgpp::base::BoundingBox::getIntervalOffset(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::DataMatrix::getPointer(), numAlgoDims_, ptr_result_, ptr_source_, q_, rec(), rec_GL(), rec_grad(), rec_LG(), rec_LL(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), recBB_LL(), and t_.
rec()
void sgpp::pde::LaplaceEnhancedDownBBLinear::rec (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of Down (L2 scalar product) without Bounding Box
Parameters
fl function value on the left boundary
fr function value on the right boundary
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, rec(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and rec().
rec_GL()
void sgpp::pde::LaplaceEnhancedDownBBLinear::rec_GL (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (gradient and L2 scalar product) without Bounding Box
Parameters
fl first function value on the left boundary, L2 scalar product
fr first function value on the right boundary, L2 scalar product
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, rec_GL(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and rec_GL().
rec_grad()
void sgpp::pde::LaplaceEnhancedDownBBLinear::rec_grad (size_t dim, grid_iterator & index) protected
recursive function for the calculation of Down (gradient) without Bounding Box
Parameters
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, rec_grad(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and rec_grad().
rec_LG()
void sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LG (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (L2 scalar product and gradient) without Bounding Box
Parameters
fl first function value on the left boundary, L2 scalar product
fr first function value on the right boundary, L2 scalar product
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, rec_LG(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and rec_LG().
rec_LL()
void sgpp::pde::LaplaceEnhancedDownBBLinear::rec_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (L2 scalar products) without Bounding Box
Parameters
fl first function value on the left boundary
fr first function value on the right boundary
fl2 second function value on the left boundary
fr2 second function value on the right boundary
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References alpha, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), and operator()().
recBB()
void sgpp::pde::LaplaceEnhancedDownBBLinear::recBB (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of Down (L2 scalar product) with Bounding Box
Parameters
fl function value on the left boundary
fr function value on the right boundary
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, q_, recBB(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and recBB().
recBB_GL()
void sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_GL (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (gradient and L2 scalar product) with Bounding Box
Parameters
fl first function value on the left boundary, L2 scalar product
fr first function value on the right boundary, L2 scalar product
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, q_, recBB_GL(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and recBB_GL().
recBB_grad()
void sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_grad (size_t dim, grid_iterator & index) protected
recursive function for the calculation of Down (gradient) with Bounding Box
Parameters
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, q_, recBB_grad(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and recBB_grad().
recBB_LG()
void sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LG (double fl, double fr, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (L2 scalar product and gradient) with Bounding Box
Parameters
fl first function value on the left boundary, L2 scalar product
fr first function value on the right boundary, L2 scalar product
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, q_, recBB_LG(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and recBB_LG().
recBB_LL()
void sgpp::pde::LaplaceEnhancedDownBBLinear::recBB_LL (double fl, double fr, double fl2, double fr2, size_t dim, grid_iterator & index) protected
recursive function for the calculation of merged-Down (L2 scalar products) with Bounding Box
Parameters
fl first function value on the left boundary
fr first function value on the right boundary
fl2 second function value on the left boundary
fr2 second function value on the right boundary
dim current fixed dimension of the 'execution direction', here all downs are calculated
index an iterator object of the grid
References cur_algo_dim_, sgpp::base::HashGridIterator::get(), h, sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), numAlgoDims_, ptr_result_, ptr_source_, q_, recBB_LL(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::stepRight(), storage, and sgpp::base::HashGridIterator::up().
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), and recBB_LL().
Member Data Documentation
algoDims
const std::vector<size_t> sgpp::pde::LaplaceEnhancedDownBBLinear::algoDims protected
algorithmic dimensions, operator is applied in this dimensions
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), and operator()().
boundingBox
sgpp::base::BoundingBox* sgpp::pde::LaplaceEnhancedDownBBLinear::boundingBox protected
Pointer to the bounding box Obejct.
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), and operator()().
cur_algo_dim_
size_t sgpp::pde::LaplaceEnhancedDownBBLinear::cur_algo_dim_ protected
current algorithmic dimension for the overall operator
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), rec(), rec_GL(), rec_grad(), rec_LG(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
numAlgoDims_
const size_t sgpp::pde::LaplaceEnhancedDownBBLinear::numAlgoDims_ protected
number of algorithmic dimensions
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), rec(), rec_GL(), rec_grad(), rec_LG(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
ptr_result_
double* sgpp::pde::LaplaceEnhancedDownBBLinear::ptr_result_ protected
pointer to DataMatrix containing result coefficients
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), rec(), rec_GL(), rec_grad(), rec_LG(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
ptr_source_
double* sgpp::pde::LaplaceEnhancedDownBBLinear::ptr_source_ protected
pointer to DataMatrix containing source coefficients
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), rec(), rec_GL(), rec_grad(), rec_LG(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
q_
double sgpp::pde::LaplaceEnhancedDownBBLinear::q_ protected
stretching of basis functions in current algorithmic domain
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), operator()(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
storage
sgpp::base::GridStorage* sgpp::pde::LaplaceEnhancedDownBBLinear::storage protected
Pointer to the sgpp::base::GridStorage Object.
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), rec(), rec_GL(), rec_grad(), rec_LG(), recBB(), recBB_GL(), recBB_grad(), recBB_LG(), and recBB_LL().
t_
double sgpp::pde::LaplaceEnhancedDownBBLinear::t_ protected
translation of basis function in current algorithmic domain
Referenced by sgpp::pde::LaplaceEnhancedDownBBLinearBoundary::operator()(), and operator()().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/basis/linear/noboundary/algorithm_sweep/LaplaceEnhancedDownBBLinear.hpp
pde/src/sgpp/pde/basis/linear/noboundary/algorithm_sweep/LaplaceEnhancedDownBBLinear.cpp