SG++-Doxygen-Documentation: sgpp::pde::OperationLaplaceModLinear Class Reference
sgpp::pde::OperationLaplaceModLinear Class Reference
Implementation of Laplace for mod linear functions.
#include <OperationLaplaceModLinear.hpp>
Public Member Functions
OperationLaplaceModLinear (sgpp::base::GridStorage *storage)
Constructor.
virtual ~OperationLaplaceModLinear ()
Destructor.
Public Member Functions inherited from sgpp::pde::UpDownOneOpDim
virtual void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result)
starts the Multiplication with the matrix
void multParallelBuildingBlock (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t operationDim)
This functions provides the same functionality as the normal mult routine.
UpDownOneOpDim (sgpp::base::GridStorage *storage)
Constructor.
UpDownOneOpDim (sgpp::base::GridStorage *storage, sgpp::base::DataVector &coef)
Constructor.
virtual ~UpDownOneOpDim ()
Destructor.
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Protected Member Functions
virtual void down (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D down operation
virtual void downOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D down operation that is only executed in one direction
virtual void up (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
std 1D up operation
virtual void upOpDim (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim)
special 1D up operation that is only executed in one direction
Protected Member Functions inherited from sgpp::pde::UpDownOneOpDim
virtual void specialOP (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
All calculations for gradient_dim, parallel version using OpenMP 3.
void updown (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, size_t dim, size_t op_dim)
Recursive procedure for updown(), parallel version using OpenMP 3.
Additional Inherited Members
Protected Types inherited from sgpp::pde::UpDownOneOpDim
typedef sgpp::base::GridStorage::grid_iterator grid_iterator
Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
const std::vector< size_t > algoDims
algorithmic dimensions, operator is applied in this dimensions
sgpp::base::DataVector * coefs
Pointer to the sgpp::base::DataVector of the coefs.
const size_t numAlgoDims_
number of algorithmic dimensions
sgpp::base::GridStorage * storage
Pointer to the grid's storage object.
Static Protected Attributes inherited from sgpp::pde::UpDownOneOpDim
static const size_t maxParallelDims_ = TASKS_PARALLEL_UPDOWN
max number of parallel stages (dimension recursive calls)
Detailed Description
Implementation of Laplace for mod linear functions.
Constructor & Destructor Documentation
OperationLaplaceModLinear()
sgpp::pde::OperationLaplaceModLinear::OperationLaplaceModLinear (sgpp::base::GridStorage * storage) explicit
Constructor.
Parameters
storage the grid's sgpp::base::GridStorage object
~OperationLaplaceModLinear()
sgpp::pde::OperationLaplaceModLinear::~OperationLaplaceModLinear () virtual
Destructor.
Member Function Documentation
down()
void sgpp::pde::OperationLaplaceModLinear::down (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D down operation
Parameters
dim dimension in which to apply the down-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::base::DataVector::setAll(), sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
downOpDim()
void sgpp::pde::OperationLaplaceModLinear::downOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D down operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that down-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::base::DataVector::setAll(), sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
up()
void sgpp::pde::OperationLaplaceModLinear::up (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
std 1D up operation
Parameters
dim dimension in which to apply the up-part
alpha vector of coefficients
result vector to store the results in
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::base::DataVector::setAll(), sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
upOpDim()
void sgpp::pde::OperationLaplaceModLinear::upOpDim (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, size_t dim) protected virtual
special 1D up operation that is only executed in one direction
Parameters
alpha the coefficients of the gridpoints
result vector with the result of this operation
dim the dimension in that up-Gradient is applied
Implements sgpp::pde::UpDownOneOpDim.
References alpha, sgpp::base::DataVector::setAll(), sgpp::pde::UpDownOneOpDim::storage, and sgpp::base::sweep< FUNC >::sweep1D().
The documentation for this class was generated from the following files:
pde/src/sgpp/pde/operation/hash/OperationLaplaceModLinear.hpp
pde/src/sgpp/pde/operation/hash/OperationLaplaceModLinear.cpp