SG++-Doxygen-Documentation: sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T > Class Template Reference
sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T > Class Template Reference
#include <OperationMultiEvalStreamingModOCLOpt.hpp>
Public Member Functions
double getDuration ()
void mult (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (sgpp::base::DataVector &source, sgpp::base::DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
OperationMultiEvalStreamingModOCLOpt (base::Grid &grid, base::DataMatrix &dataset, std::shared_ptr< base::OCLManagerMultiPlatform > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters)
void prepare () override
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
~OperationMultiEvalStreamingModOCLOpt ()
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual std::string getImplementationName ()
Name of this implementation of the operation.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual ~OperationMultipleEval ()
Destructor.
Protected Attributes
size_t datasetSizePadded
size_t datasetSizeUnpadded
std::vector< std::shared_ptr< base::OCLDevice > > devices
size_t dims
double duration
size_t gridSizePadded
size_t gridSizeUnpadded
std::vector< T > indexFast
Member to store the sparse grid's indices for better vectorization.
std::vector< T > indexMask
Member to store the sparse grid's indices for better vectorization.
std::vector< T > kernelDataset
std::vector< T > levelFast
Member to store the sparse grid's levels for better vectorization.
std::vector< T > levelMask
Member to store the sparse grid's levels for better vectorization.
std::shared_ptr< base::OCLManagerMultiPlatform > manager
std::vector< T > maskMask
Member to store the sparse grid's mask for better vectorization.
std::vector< StreamingModOCLOpt::KernelMult< T > > multKernels
std::vector< StreamingModOCLOpt::KernelMultTranspose< T > > multTransposeKernels
sgpp::base::SGppStopwatch myTimer
Timer object to handle time measurements.
std::vector< T > offsetMask
Member to store the sparse grid's offset for better vectorization.
size_t overallDataBlockingSize
size_t overallGridBlockingSize
std::shared_ptr< base::OCLOperationConfiguration > parameters
sgpp::base::DataMatrix preparedDataset
std::shared_ptr< sgpp::base::QueueLoadBalancerOpenMP > queueLoadBalancerMult
std::shared_ptr< sgpp::base::QueueLoadBalancerOpenMP > queueLoadBalancerMultTrans
base::GridStorage & storage
bool verbose
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Constructor & Destructor Documentation
OperationMultiEvalStreamingModOCLOpt()
template<typename T > sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt (base::Grid & grid, base::DataMatrix & dataset, std::shared_ptr< base::OCLManagerMultiPlatform > manager, std::shared_ptr< base::OCLOperationConfiguration > parameters) inline
References sgpp::base::OperationMultipleEval::dataset, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::devices, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::dims, sgpp::datadriven::StreamingModOCLOpt::Configuration::getKernelName(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getSize(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multKernels, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTransposeKernels, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallDataBlockingSize, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallGridBlockingSize, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::prepare(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::queueLoadBalancerMult, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::queueLoadBalancerMultTrans, and sgpp::base::DataMatrix::transpose().
~OperationMultiEvalStreamingModOCLOpt()
template<typename T > sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::~OperationMultiEvalStreamingModOCLOpt () inline
Member Function Documentation
getDuration()
template<typename T > double sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::getDuration () inline virtual
Implements sgpp::base::OperationMultipleEval.
References sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::duration.
mult()
template<typename T > void sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result) inline override virtual
Multiplication of \(B^T\) with vector \(\alpha\).
Parameters
alpha vector, to which \(B\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References alpha, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::datasetSizePadded, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::devices, sgpp::base::DataVector::getSize(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::gridSizePadded, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallDataBlockingSize, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::prepare(), sgpp::base::SGppStopwatch::start(), sgpp::base::SGppStopwatch::stop(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::verbose.
multTranspose()
template<typename T > void sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose (sgpp::base::DataVector & source, sgpp::base::DataVector & result) inline override virtual
Multiplication of \(B\) with vector \(\alpha\).
Parameters
source vector, to which \(B^T\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::datasetSizePadded, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::devices, sgpp::base::DataVector::getSize(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::gridSizePadded, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallGridBlockingSize, sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::prepare(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::queueLoadBalancerMultTrans, sgpp::base::SGppStopwatch::start(), sgpp::base::SGppStopwatch::stop(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::verbose.
prepare()
template<typename T > void sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::prepare () inline override virtual
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
This function is by default called with each "mult()", "multTranspose()" or evaluation operation and can be ignored from an external perspective. This is not overridden by every kernel.
Reimplemented from sgpp::base::OperationMultipleEval.
References sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::devices.
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
Member Data Documentation
datasetSizePadded
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::datasetSizePadded protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose().
datasetSizeUnpadded
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::datasetSizeUnpadded protected
devices
template<typename T > std::vector<std::shared_ptr<base::OCLDevice> > sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::devices protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::prepare().
dims
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::dims protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
duration
template<typename T > double sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::duration protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::getDuration().
gridSizePadded
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::gridSizePadded protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose().
gridSizeUnpadded
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::gridSizeUnpadded protected
indexFast
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::indexFast protected
Member to store the sparse grid's indices for better vectorization.
indexMask
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::indexMask protected
Member to store the sparse grid's indices for better vectorization.
kernelDataset
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::kernelDataset protected
levelFast
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::levelFast protected
Member to store the sparse grid's levels for better vectorization.
levelMask
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::levelMask protected
Member to store the sparse grid's levels for better vectorization.
manager
template<typename T > std::shared_ptr<base::OCLManagerMultiPlatform> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::manager protected
maskMask
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::maskMask protected
Member to store the sparse grid's mask for better vectorization.
multKernels
template<typename T > std::vector<StreamingModOCLOpt::KernelMult<T> > sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multKernels protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
multTransposeKernels
template<typename T > std::vector<StreamingModOCLOpt::KernelMultTranspose<T> > sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTransposeKernels protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
myTimer
template<typename T > sgpp::base::SGppStopwatch sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::myTimer protected
Timer object to handle time measurements.
offsetMask
template<typename T > std::vector<T> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::offsetMask protected
Member to store the sparse grid's offset for better vectorization.
overallDataBlockingSize
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallDataBlockingSize protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
overallGridBlockingSize
template<typename T > size_t sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::overallGridBlockingSize protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
parameters
template<typename T > std::shared_ptr<base::OCLOperationConfiguration> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::parameters protected
preparedDataset
template<typename T > sgpp::base::DataMatrix sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::preparedDataset protected
queueLoadBalancerMult
template<typename T > std::shared_ptr<sgpp::base::QueueLoadBalancerOpenMP> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::queueLoadBalancerMult protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
queueLoadBalancerMultTrans
template<typename T > std::shared_ptr<sgpp::base::QueueLoadBalancerOpenMP> sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::queueLoadBalancerMultTrans protected
Referenced by sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), and sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::OperationMultiEvalStreamingModOCLOpt().
storage
template<typename T > base::GridStorage& sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::storage protected
verbose
template<typename T > bool sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::verbose protected
Referenced by python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::addFullGridPoints(), python.uq.refinement.RefinementManager.RefinementManager::candidates(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::computeCandidates(), python.uq.operations.forcePositivity.findIntersections.IntersectionCandidates::findIntersections(), python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::getLocalMaxLevel(), python.uq.manager.ASGCUQManager.ASGCUQManager::learnDataWithoutTest(), python.uq.manager.ASGCUQManager.ASGCUQManager::learnDataWithTest(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makeCurrentNodalValuesPositive(), python.uq.operations.forcePositivity.operationMakePositive.OperationMakePositive::makePositive(), python.uq.operations.forcePositivity.operationMakePositiveFast.OperationMakePositiveFast::makePositive(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::mult(), sgpp::datadriven::OperationMultiEvalStreamingModOCLOpt< T >::multTranspose(), python.uq.manager.ASGCUQManager.ASGCUQManager::recomputeStats(), python.uq.refinement.RefinementManager.RefinementManager::refineGrid(), and python.uq.operations.forcePositivity.localFullGridSearch.LocalFullGridCandidates::splitFullGrids().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalStreamingModOCLOpt/OperationMultiEvalStreamingModOCLOpt.hpp