SG++-Doxygen-Documentation: sgpp::base::OperationQuadraturePoly Class Reference
sgpp::base::OperationQuadraturePoly Class Reference
Quadrature on sparse grid, polynomial grid without boundaries.
#include <OperationQuadraturePoly.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for piecewise polynomial basis functions of max.
OperationQuadraturePoly (GridStorage &storage, size_t degree)
Constructor of OperationQuadraturePoly.
~OperationQuadraturePoly () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SPolyBase base
Poly Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, polynomial grid without boundaries.
Constructor & Destructor Documentation
OperationQuadraturePoly()
sgpp::base::OperationQuadraturePoly::OperationQuadraturePoly (GridStorage & storage, size_t degree) inline
Constructor of OperationQuadraturePoly.
Parameters
storage Pointer to the grid's GridStorage object
degree the polynom's max. degree
~OperationQuadraturePoly()
sgpp::base::OperationQuadraturePoly::~OperationQuadraturePoly () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadraturePoly::doQuadrature (DataVector & alpha) override virtual
Quadrature for piecewise polynomial basis functions of max.
degree 3
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::PolyBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SPolyBase sgpp::base::OperationQuadraturePoly::base protected
Poly Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadraturePoly::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadraturePoly.hpp
base/src/sgpp/base/operation/hash/OperationQuadraturePoly.cpp