SG++-Doxygen-Documentation: sgpp::base::OperationMultipleEvalInterModLinear Class Reference
sgpp::base::OperationMultipleEvalInterModLinear Class Reference
This class implements OperationMultipleEval for a grids with mod linear basis ansatzfunctions and a set of interactions that limit the subspaces that are included.
#include <OperationMultipleEvalInterModLinear.hpp>
Public Member Functions
double getDuration () override
void mult (DataVector &alpha, DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (DataVector &source, DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEvalInterModLinear (Grid &grid, DataMatrix &dataset, std::set< std::set< size_t > > &interactions)
Constructor.
~OperationMultipleEvalInterModLinear () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual std::string getImplementationName ()
Name of this implementation of the operation.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual void prepare ()
Used for kernel-specific setup like special data structures that are defined from the current state of the grid.
virtual ~OperationMultipleEval ()
Destructor.
Protected Attributes
std::set< std::set< size_t > > interactions
GridStorage & storage
Pointer to GridStorage object.
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Detailed Description
This class implements OperationMultipleEval for a grids with mod linear basis ansatzfunctions and a set of interactions that limit the subspaces that are included.
The evaluation iterates over all allowed subspaces and only viewes ansatzfunctions of level > 1 since the level one ansatz function evaluates to 1
This Operation is more efficeint than the OperationMultipleEvalModLinear.
Constructor & Destructor Documentation
OperationMultipleEvalInterModLinear()
sgpp::base::OperationMultipleEvalInterModLinear::OperationMultipleEvalInterModLinear (Grid & grid, DataMatrix & dataset, std::set< std::set< size_t > > & interactions) inline
Constructor.
Parameters
grid grid
dataset the dataset that should be evaluated
interactions the interactionterms that limit what subspaces are included
References interactions.
~OperationMultipleEvalInterModLinear()
sgpp::base::OperationMultipleEvalInterModLinear::~OperationMultipleEvalInterModLinear () inline override
Destructor.
Member Function Documentation
getDuration()
double sgpp::base::OperationMultipleEvalInterModLinear::getDuration () inline override virtual
Implements sgpp::base::OperationMultipleEval.
mult()
void sgpp::base::OperationMultipleEvalInterModLinear::mult (DataVector & alpha, DataVector & result) override virtual
Multiplication of \(B^T\) with vector \(\alpha\).
Parameters
alpha vector, to which \(B\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References sgpp::base::DataVector::add(), alpha, sgpp::base::OperationMultipleEval::dataset, sgpp::base::LinearModifiedBasis< LT, IT >::eval(), sgpp::base::HashGridIterator::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), interactions, sgpp::base::HashGridStorage::isInvalidSequenceNumber(), level, sgpp::base::HashGridIterator::push(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::set(), sgpp::base::DataVector::setAll(), and storage.
multTranspose()
void sgpp::base::OperationMultipleEvalInterModLinear::multTranspose (DataVector & source, DataVector & result) override virtual
Multiplication of \(B\) with vector \(\alpha\).
Parameters
source vector, to which \(B^T\) is applied. Typically the coefficient vector
result the result vector of the matrix vector multiplication
Implements sgpp::base::OperationMultipleEval.
References sgpp::base::DataVector::add(), sgpp::base::OperationMultipleEval::dataset, sgpp::base::LinearModifiedBasis< LT, IT >::eval(), sgpp::base::HashGridIterator::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getRow(), sgpp::base::DataVector::getSize(), interactions, sgpp::base::HashGridStorage::isInvalidSequenceNumber(), level, sgpp::base::HashGridIterator::push(), sgpp::base::HashGridIterator::seq(), sgpp::base::HashGridIterator::set(), sgpp::base::DataVector::setAll(), and storage.
Member Data Documentation
interactions
std::set<std::set<size_t> > sgpp::base::OperationMultipleEvalInterModLinear::interactions protected
Referenced by mult(), multTranspose(), and OperationMultipleEvalInterModLinear().
storage
GridStorage& sgpp::base::OperationMultipleEvalInterModLinear::storage protected
Pointer to GridStorage object.
Referenced by mult(), and multTranspose().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationMultipleEvalInterModLinear.hpp
base/src/sgpp/base/operation/hash/OperationMultipleEvalInterModLinear.cpp