SG++-Doxygen-Documentation: sgpp::base::HierarchisationLinearStretchedBoundary Class Reference
sgpp::base::HierarchisationLinearStretchedBoundary Class Reference
Class that implements the hierarchisation on a linear sparse grid with boundaries.
#include <HierarchisationLinearStretchedBoundary.hpp>
Public Member Functions
HierarchisationLinearStretchedBoundary (GridStorage &storage)
Constructor, must be bind to a grid.
virtual void operator() (DataVector &source, DataVector &result, grid_iterator &index, size_t dim) override
Implements operator() needed by the sweep class during the grid traversal.
~HierarchisationLinearStretchedBoundary () override
Destructor.
Public Member Functions inherited from sgpp::base::HierarchisationLinearStretched
HierarchisationLinearStretched (GridStorage &storage)
Constructor, must be bind to a grid.
virtual ~HierarchisationLinearStretched ()
Destructor.
Additional Inherited Members
Protected Types inherited from sgpp::base::HierarchisationLinearStretched
typedef GridStorage::grid_iterator grid_iterator
Protected Member Functions inherited from sgpp::base::HierarchisationLinearStretched
void rec (DataVector &source, DataVector &result, grid_iterator &index, size_t dim, double fl, double fr)
Recursive hierarchisation algorithm, this algorithms works in-place -> source should be equal to result.
Protected Attributes inherited from sgpp::base::HierarchisationLinearStretched
GridStorage & storage
the grid object
Stretching * stretch
the stretching object
Detailed Description
Class that implements the hierarchisation on a linear sparse grid with boundaries.
Therefore the ()operator has to be implement in order to use the sweep algorithm for the grid traversal
Constructor & Destructor Documentation
HierarchisationLinearStretchedBoundary()
sgpp::base::HierarchisationLinearStretchedBoundary::HierarchisationLinearStretchedBoundary (GridStorage & storage) explicit
Constructor, must be bind to a grid.
Parameters
storage the grid storage object of the the grid, on which the hierarchisation should be executed
~HierarchisationLinearStretchedBoundary()
sgpp::base::HierarchisationLinearStretchedBoundary::~HierarchisationLinearStretchedBoundary () override
Destructor.
Member Function Documentation
operator()()
void sgpp::base::HierarchisationLinearStretchedBoundary::operator() (DataVector & source, DataVector & result, grid_iterator & index, size_t dim) override virtual
Implements operator() needed by the sweep class during the grid traversal.
This function is applied to the whole grid.
For level zero it's assumed, that both ansatz-functions do exist: 0,0 and 0,1 If one is missing this code might produce some bad errors (segmentation fault, wrong calculation result) So please assure that both functions do exist!
Parameters
source this DataVector holds the node base coefficients of the function that should be applied to the sparse grid
result this DataVector holds the linear base coefficients of the sparse grid's ansatz-functions
index a iterator object of the grid
dim current fixed dimension of the 'execution direction'
Reimplemented from sgpp::base::HierarchisationLinearStretched.
References sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HierarchisationLinearStretched::rec(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::HashGridIterator::seq(), and sgpp::base::HierarchisationLinearStretched::storage.
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/common/algorithm_sweep/HierarchisationLinearStretchedBoundary.hpp
base/src/sgpp/base/operation/hash/common/algorithm_sweep/HierarchisationLinearStretchedBoundary.cpp