SG++-Doxygen-Documentation: sgpp::datadriven::LearnerScenario Class Reference
sgpp::datadriven::LearnerScenario Class Reference
#include <LearnerScenario.hpp>
Public Member Functions
base::AdaptivityConfiguration getAdaptivityConfiguration ()
std::string getDatasetFileName ()
base::RegularGridConfiguration getGridConfig ()
InternalPrecision getInternalPrecision ()
double getLambda ()
solver::SLESolverConfiguration getSolverConfigurationFinal ()
solver::SLESolverConfiguration getSolverConfigurationRefine ()
datadriven::TestsetConfiguration getTestsetConfiguration ()
bool hasTestsetConfiguration ()
bool isInitialized () const
LearnerScenario ()
LearnerScenario (std::string datasetFileName, double lambda, InternalPrecision internalPrecision, base::RegularGridConfiguration gridConfig, solver::SLESolverConfiguration SLESolverConfigRefine, solver::SLESolverConfiguration SLESolverConfigFinal, base::AdaptivityConfiguration adaptivityConfig)
LearnerScenario (std::string datasetFileName, double lambda, InternalPrecision internalPrecision, base::RegularGridConfiguration gridConfig, solver::SLESolverConfiguration SLESolverConfigRefine, solver::SLESolverConfiguration SLESolverConfigFinal, base::AdaptivityConfiguration adaptivityConfig, datadriven::TestsetConfiguration testsetConfiguration)
LearnerScenario (std::string scenarioFileName)
void setAdaptivityConfiguration (base::AdaptivityConfiguration &adaptivityConfig)
void setDatasetFileName (std::string datasetFileName)
void setGridConfig (base::RegularGridConfiguration &gridConfig)
void setInternalPrecision (InternalPrecision internalPrecision)
void setLambda (double lambda)
void setSolverConfigurationFinal (solver::SLESolverConfiguration &solverConfigFinal)
void setSolverConfigurationRefine (solver::SLESolverConfiguration &solverConfigRefine)
void setTestsetConfiguration (datadriven::TestsetConfiguration &testsetConfig)
Public Member Functions inherited from json::JSON
void clear ()
virtual JSON * clone ()
void deserialize (std::string content)
void deserializeFromString (const std::string &content)
JSON ()
JSON (const JSON &original)
JSON (const std::string &fileName)
DictNode & operator= (const DictNode &right)
JSON & operator= (const JSON &original)
Node & operator= (const Node &right) override
void serialize (const std::string &outFileName)
void serialize (std::ostream &outFile, size_t indentWidth) override
Public Member Functions inherited from json::DictNode
void addAttribute (const std::string &name, std::unique_ptr< Node > node) override
Node & addDictAttr (const std::string &name) override
Node & addIDAttr (const std::string &name, const bool &value) override
Node & addIDAttr (const std::string &name, const char *value) override
Node & addIDAttr (const std::string &name, const double &value) override
Node & addIDAttr (const std::string &name, const int64_t &value) override
Node & addIDAttr (const std::string &name, const std::string &value) override
Node & addIDAttr (const std::string &name, const uint64_t &value) override
Node & addListAttr (const std::string &name) override
Node & addTextAttr (const std::string &name, const std::string &value) override
bool contains (const std::string &key) override
DictNode ()
DictNode (const DictNode &original)
std::unique_ptr< Node > erase (Node &node) override
std::vector< std::string > & keys () override
DictNode & operator= (const DictNode &right)
Node & operator[] (const std::string &key) override
void parse (std::vector< Token > &stream) override
void parseAttributes (std::vector< Token > &stream)
std::unique_ptr< Node > removeAttribute (const std::string name) override
Node & replaceDictAttr (const std::string &name) override
Node & replaceIDAttr (const std::string &name, const bool &value) override
Node & replaceIDAttr (const std::string &name, const char *value) override
Node & replaceIDAttr (const std::string &name, const double &value) override
Node & replaceIDAttr (const std::string &name, const int64_t &value) override
Node & replaceIDAttr (const std::string &name, const std::string &value) override
Node & replaceIDAttr (const std::string &name, const uint64_t &value) override
Node & replaceListAttr (const std::string &name) override
Node & replaceTextAttr (const std::string &name, const std::string &value) override
size_t size () override
Public Member Functions inherited from json::Node
virtual Node & addDictValue ()
virtual Node & addIdValue (const bool &value)
virtual Node & addIdValue (const char *value)
virtual Node & addIdValue (const double &value)
virtual Node & addIdValue (const int64_t &value)
virtual Node & addIdValue (const std::string &value)
virtual Node & addIdValue (const uint64_t &value)
virtual Node & addListValue ()
virtual Node & addTextValue (const std::string &value)
virtual void addValue (std::unique_ptr< Node > node)
virtual std::unique_ptr< Node > erase ()
virtual std::string & get ()
virtual bool getBool ()
virtual double getDouble ()
virtual int64_t getInt ()
virtual uint64_t getUInt ()
Node ()
Node (const Node &right)=default
virtual Node & operator[] (const size_t index)
virtual std::unique_ptr< Node > removeValue (size_t index)
virtual void set (const std::string &value)
virtual void setBool (bool boolValue)
virtual void setDouble (double doubleValue)
virtual void setInt (int64_t intValue)
virtual void setUInt (uint64_t uintValue)
virtual ~Node ()=default
Additional Inherited Members
Public Attributes inherited from json::Node
size_t orderedKeyIndex
Node * parent
Protected Attributes inherited from json::DictNode
std::map< std::string, std::unique_ptr< Node > > attributes
std::vector< std::string > keyOrder
Static Protected Attributes inherited from json::Node
static const int SERIALIZE_INDENT = 3
Constructor & Destructor Documentation
LearnerScenario() [1/4]
sgpp::datadriven::LearnerScenario::LearnerScenario ()
LearnerScenario() [2/4]
sgpp::datadriven::LearnerScenario::LearnerScenario (std::string scenarioFileName) explicit
LearnerScenario() [3/4]
sgpp::datadriven::LearnerScenario::LearnerScenario (std::string datasetFileName, double lambda, InternalPrecision internalPrecision, base::RegularGridConfiguration gridConfig, solver::SLESolverConfiguration SLESolverConfigRefine, solver::SLESolverConfiguration SLESolverConfigFinal, base::AdaptivityConfiguration adaptivityConfig)
References setAdaptivityConfiguration(), setDatasetFileName(), setGridConfig(), setInternalPrecision(), setLambda(), setSolverConfigurationFinal(), and setSolverConfigurationRefine().
LearnerScenario() [4/4]
sgpp::datadriven::LearnerScenario::LearnerScenario (std::string datasetFileName, double lambda, InternalPrecision internalPrecision, base::RegularGridConfiguration gridConfig, solver::SLESolverConfiguration SLESolverConfigRefine, solver::SLESolverConfiguration SLESolverConfigFinal, base::AdaptivityConfiguration adaptivityConfig, datadriven::TestsetConfiguration testsetConfiguration)
References setAdaptivityConfiguration(), setDatasetFileName(), setGridConfig(), setInternalPrecision(), setLambda(), setSolverConfigurationFinal(), setSolverConfigurationRefine(), and setTestsetConfiguration().
Member Function Documentation
getAdaptivityConfiguration()
base::AdaptivityConfiguration sgpp::datadriven::LearnerScenario::getAdaptivityConfiguration ()
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, and sgpp::base::AdaptivityConfiguration::refinementThreshold_.
Referenced by main().
getDatasetFileName()
std::string sgpp::datadriven::LearnerScenario::getDatasetFileName ()
Referenced by main().
getGridConfig()
base::RegularGridConfiguration sgpp::datadriven::LearnerScenario::getGridConfig ()
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::ModLinear, and sgpp::base::GeneralGridConfiguration::type_.
Referenced by main().
getInternalPrecision()
InternalPrecision sgpp::datadriven::LearnerScenario::getInternalPrecision ()
References sgpp::datadriven::Double, sgpp::datadriven::Float, and json::Node::get().
getLambda()
double sgpp::datadriven::LearnerScenario::getLambda ()
Referenced by main().
getSolverConfigurationFinal()
solver::SLESolverConfiguration sgpp::datadriven::LearnerScenario::getSolverConfigurationFinal ()
References sgpp::solver::BiCGSTAB, sgpp::solver::CG, sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::solver::SLESolverConfiguration::threshold_, and sgpp::solver::SLESolverConfiguration::type_.
Referenced by main().
getSolverConfigurationRefine()
solver::SLESolverConfiguration sgpp::datadriven::LearnerScenario::getSolverConfigurationRefine ()
References sgpp::solver::BiCGSTAB, sgpp::solver::CG, sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::solver::SLESolverConfiguration::threshold_, and sgpp::solver::SLESolverConfiguration::type_.
Referenced by main().
getTestsetConfiguration()
datadriven::TestsetConfiguration sgpp::datadriven::LearnerScenario::getTestsetConfiguration ()
References sgpp::datadriven::TestsetConfiguration::alphaReferenceFileName, sgpp::datadriven::TestsetConfiguration::expectedLargestDifference, sgpp::datadriven::TestsetConfiguration::expectedMSE, and sgpp::datadriven::TestsetConfiguration::hasTestDataset.
Referenced by main().
hasTestsetConfiguration()
bool sgpp::datadriven::LearnerScenario::hasTestsetConfiguration ()
isInitialized()
bool sgpp::datadriven::LearnerScenario::isInitialized () const
setAdaptivityConfiguration()
void sgpp::datadriven::LearnerScenario::setAdaptivityConfiguration (base::AdaptivityConfiguration & adaptivityConfig)
References adaptivityConfig, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, and sgpp::base::AdaptivityConfiguration::refinementThreshold_.
Referenced by LearnerScenario(), and LearnerScenario().
setDatasetFileName()
void sgpp::datadriven::LearnerScenario::setDatasetFileName (std::string datasetFileName)
Referenced by LearnerScenario(), and LearnerScenario().
setGridConfig()
void sgpp::datadriven::LearnerScenario::setGridConfig (base::RegularGridConfiguration & gridConfig)
References sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::base::GeneralGridConfiguration::dim_, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::base::ModLinear, and sgpp::base::GeneralGridConfiguration::type_.
Referenced by LearnerScenario(), and LearnerScenario().
setInternalPrecision()
void sgpp::datadriven::LearnerScenario::setInternalPrecision (InternalPrecision internalPrecision)
References sgpp::datadriven::Float.
Referenced by LearnerScenario(), and LearnerScenario().
setLambda()
void sgpp::datadriven::LearnerScenario::setLambda (double lambda)
References lambda.
Referenced by LearnerScenario(), and LearnerScenario().
setSolverConfigurationFinal()
void sgpp::datadriven::LearnerScenario::setSolverConfigurationFinal (solver::SLESolverConfiguration & solverConfigFinal)
References sgpp::solver::BiCGSTAB, sgpp::solver::CG, sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::solver::SLESolverConfiguration::threshold_, and sgpp::solver::SLESolverConfiguration::type_.
Referenced by LearnerScenario(), and LearnerScenario().
setSolverConfigurationRefine()
void sgpp::datadriven::LearnerScenario::setSolverConfigurationRefine (solver::SLESolverConfiguration & solverConfigRefine)
References sgpp::solver::BiCGSTAB, sgpp::solver::CG, sgpp::solver::SLESolverConfiguration::eps_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::solver::SLESolverConfiguration::threshold_, and sgpp::solver::SLESolverConfiguration::type_.
Referenced by LearnerScenario(), and LearnerScenario().
setTestsetConfiguration()
void sgpp::datadriven::LearnerScenario::setTestsetConfiguration (datadriven::TestsetConfiguration & testsetConfig)
References sgpp::datadriven::TestsetConfiguration::alphaReferenceFileName, sgpp::datadriven::TestsetConfiguration::expectedLargestDifference, sgpp::datadriven::TestsetConfiguration::expectedMSE, and sgpp::datadriven::TestsetConfiguration::hasTestDataset.
Referenced by LearnerScenario().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/LearnerScenario.hpp
datadriven/src/sgpp/datadriven/application/LearnerScenario.cpp