SG++-Doxygen-Documentation: sgpp::base::FundamentalSplineBasis< LT, IT > Class Template Reference
sgpp::base::FundamentalSplineBasis< LT, IT > Class Template Reference
Fundamental spline basis.
#include <FundamentalSplineBasis.hpp>
Public Member Functions
double eval (LT l, IT i, double x) override
double evalDx (LT l, IT i, double x) override
double evalDxDx (LT l, IT i, double x)
FundamentalSplineBasis ()
Default constructor.
FundamentalSplineBasis (size_t degree)
Constructor.
size_t getDegree () const override
double getIntegral (LT l, IT i) override
~FundamentalSplineBasis () override
Destructor.
Public Member Functions inherited from sgpp::base::Basis< LT, IT >
virtual ~Basis ()
Destructor.
Protected Attributes
BsplineBasis< LT, IT > bsplineBasis
B-spline basis.
std::vector< double > coefficients
B-spline coefficients.
DataVector coordinates
coordinates and weights for calculating integrals
bool integrationInitialized = false
DataVector weights
Detailed Description
template<class LT, class IT>
class sgpp::base::FundamentalSplineBasis< LT, IT >
Fundamental spline basis.
Constructor & Destructor Documentation
FundamentalSplineBasis() [1/2]
template<class LT , class IT > sgpp::base::FundamentalSplineBasis< LT, IT >::FundamentalSplineBasis () inline
Default constructor.
FundamentalSplineBasis() [2/2]
template<class LT , class IT > sgpp::base::FundamentalSplineBasis< LT, IT >::FundamentalSplineBasis (size_t degree) inline explicit
Constructor.
Parameters
degree spline degree, must be odd (if it's even, degree - 1 is used)
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis, and sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients.
~FundamentalSplineBasis()
template<class LT , class IT > sgpp::base::FundamentalSplineBasis< LT, IT >::~FundamentalSplineBasis () inline override
Destructor.
Member Function Documentation
eval()
template<class LT , class IT > double sgpp::base::FundamentalSplineBasis< LT, IT >::eval (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of fundamental spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis, and sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalFundamentalSplineNaive::eval(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), sgpp::base::HierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::DehierarchisationFundamentalSpline::operator()(), sgpp::base::DehierarchisationFundamentalSplineBoundary::operator()(), sgpp::base::HierarchisationFundamentalSpline::operator()(), and sgpp::base::HierarchisationFundamentalSplineBoundary::operator()().
evalDx()
template<class LT , class IT > double sgpp::base::FundamentalSplineBasis< LT, IT >::evalDx (LT l, IT i, double x) inline override virtual
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of derivative of fundamental spline basis function
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis, and sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients.
Referenced by sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalGradientFundamentalSplineNaive::evalGradient(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative(), and sgpp::base::OperationEvalPartialDerivativeFundamentalSplineNaive::evalPartialDerivative().
evalDxDx()
template<class LT , class IT > double sgpp::base::FundamentalSplineBasis< LT, IT >::evalDxDx (LT l, IT i, double x) inline
Parameters
l level of basis function
i index of basis function
x evaluation point
Returns
value of 2nd derivative of fundamental spline basis function
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis, and sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients.
Referenced by sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian(), and sgpp::base::OperationEvalHessianFundamentalSplineNaive::evalHessian().
getDegree()
template<class LT , class IT > size_t sgpp::base::FundamentalSplineBasis< LT, IT >::getDegree () const inline override virtual
Returns
fundamental spline degree
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis.
getIntegral()
template<class LT , class IT > double sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral (LT l, IT i) inline override virtual
Parameters
l level of basis function
i index of basis function
Returns
value of the integral
Implements sgpp::base::Basis< LT, IT >.
References sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis, sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients, sgpp::base::FundamentalSplineBasis< LT, IT >::coordinates, sgpp::base::FundamentalSplineBasis< LT, IT >::eval(), sgpp::base::GaussLegendreQuadRule1D::getLevelPointsAndWeightsNormalized(), h, sgpp::base::FundamentalSplineBasis< LT, IT >::integrationInitialized, and sgpp::base::FundamentalSplineBasis< LT, IT >::weights.
Referenced by sgpp::base::OperationQuadratureFundamentalSpline::doQuadrature().
Member Data Documentation
bsplineBasis
template<class LT , class IT > BsplineBasis<LT, IT> sgpp::base::FundamentalSplineBasis< LT, IT >::bsplineBasis protected
B-spline basis.
Referenced by sgpp::base::FundamentalSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalSplineBasis< LT, IT >::evalDx(), sgpp::base::FundamentalSplineBasis< LT, IT >::evalDxDx(), sgpp::base::FundamentalSplineBasis< LT, IT >::FundamentalSplineBasis(), sgpp::base::FundamentalSplineBasis< LT, IT >::getDegree(), and sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral().
coefficients
template<class LT , class IT > std::vector<double> sgpp::base::FundamentalSplineBasis< LT, IT >::coefficients protected
B-spline coefficients.
Referenced by sgpp::base::FundamentalSplineBasis< LT, IT >::eval(), sgpp::base::FundamentalSplineBasis< LT, IT >::evalDx(), sgpp::base::FundamentalSplineBasis< LT, IT >::evalDxDx(), sgpp::base::FundamentalSplineBasis< LT, IT >::FundamentalSplineBasis(), and sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral().
coordinates
template<class LT , class IT > DataVector sgpp::base::FundamentalSplineBasis< LT, IT >::coordinates protected
coordinates and weights for calculating integrals
Referenced by sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral().
integrationInitialized
template<class LT , class IT > bool sgpp::base::FundamentalSplineBasis< LT, IT >::integrationInitialized = false protected
Referenced by sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral().
weights
template<class LT , class IT > DataVector sgpp::base::FundamentalSplineBasis< LT, IT >::weights protected
Referenced by sgpp::base::FundamentalSplineBasis< LT, IT >::getIntegral().
The documentation for this class was generated from the following file:
base/src/sgpp/base/operation/hash/common/basis/FundamentalSplineBasis.hpp