SG++-Doxygen-Documentation: sgpp::base::AlgorithmEvaluationTransposed< BASIS > Class Template Reference
sgpp::base::AlgorithmEvaluationTransposed< BASIS > Class Template Reference
Basic algorithm for getting all affected basis functions.
#include <AlgorithmEvaluationTransposed.hpp>
Public Member Functions
AlgorithmEvaluationTransposed (GridStorage &storage)
void operator() (BASIS &basis, const DataVector &point, double alpha, DataVector &result)
Returns evaluations of all basis functions that are non-zero at a given evaluation point.
~AlgorithmEvaluationTransposed ()
Protected Member Functions
void rec (BASIS &basis, DataVector &point, size_t current_dim, double value, GridStorage::grid_iterator &working, index_t *source, double alpha, DataVector &result)
Recursive traversal of the "tree" of basis functions for evaluation, used in operator().
Protected Attributes
GridStorage & storage
Detailed Description
template<class BASIS>
class sgpp::base::AlgorithmEvaluationTransposed< BASIS >
Basic algorithm for getting all affected basis functions.
This implicitly assumes a tensor-product approach and local support. No grid points on the border are supported.
Constructor & Destructor Documentation
AlgorithmEvaluationTransposed()
template<class BASIS > sgpp::base::AlgorithmEvaluationTransposed< BASIS >::AlgorithmEvaluationTransposed (GridStorage & storage) inline explicit
~AlgorithmEvaluationTransposed()
template<class BASIS > sgpp::base::AlgorithmEvaluationTransposed< BASIS >::~AlgorithmEvaluationTransposed () inline
Member Function Documentation
operator()()
template<class BASIS > void sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator() (BASIS & basis, const DataVector & point, double alpha, DataVector & result) inline
Returns evaluations of all basis functions that are non-zero at a given evaluation point.
For a given evaluation point \(x\), it stores tuples (std::pair) of \((i,\phi_i(x))\) in the result vector for all basis functions that are non-zero. If one wants to evaluate \(f_N(x)\), one only has to compute
\[ \sum_{r\in\mathbf{result}} \alpha[r\rightarrow\mathbf{first}] \cdot r\rightarrow\mathbf{second}. \]
Parameters
basis a sparse grid basis
point evaluation point within the domain
alpha the coefficient of the regarded ansatzfunction
result vector that will contain the local support of the given ansatzfuction for all evaluations points
References alpha, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::BoundingBox::isContainingPoint(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
rec()
template<class BASIS > void sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec (BASIS & basis, DataVector & point, size_t current_dim, double value, GridStorage::grid_iterator & working, index_t * source, double alpha, DataVector & result) inline protected
Recursive traversal of the "tree" of basis functions for evaluation, used in operator().
For a given evaluation point \(x\), it stores tuples (std::pair) of \((i,\phi_i(x))\) in the result vector for all basis functions that are non-zero.
Parameters
basis a sparse grid basis
point evaluation point within the domain
current_dim the dimension currently looked at (recursion parameter)
value the value of the evaluation of the current basis function up to (excluding) dimension current_dim (product of the evaluations of the one-dimensional ones)
working iterator working on the GridStorage of the basis
source array of indices for each dimension (identifying the indices of the current grid point)
alpha the coefficient of current ansatzfunction
result vector that will contain the local support of the given ansatzfuction for all evaluations points
References alpha, sgpp::base::HashGridIterator::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::HashGridIterator::leftChild(), sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::seq(), and sgpp::base::AlgorithmEvaluationTransposed< BASIS >::storage.
Referenced by sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()(), and sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec().
Member Data Documentation
storage
template<class BASIS > GridStorage& sgpp::base::AlgorithmEvaluationTransposed< BASIS >::storage protected
Referenced by sgpp::base::AlgorithmEvaluationTransposed< BASIS >::operator()(), and sgpp::base::AlgorithmEvaluationTransposed< BASIS >::rec().
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/AlgorithmEvaluationTransposed.hpp