SG++-Doxygen-Documentation: sgpp::base::OperationQuadratureLinearClenshawCurtis Class Reference
sgpp::base::OperationQuadratureLinearClenshawCurtis Class Reference
Quadrature on sparse grid, linear grid without boundaries.
#include <OperationQuadratureLinearClenshawCurtis.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha) override
Quadrature for piecewise linear hat basis functions.
OperationQuadratureLinearClenshawCurtis (GridStorage &storage)
Constructor of OperationQuadratureLinearClenshawCurtis.
~OperationQuadratureLinearClenshawCurtis () override
Public Member Functions inherited from sgpp::base::OperationQuadrature
OperationQuadrature ()
Constructor.
virtual ~OperationQuadrature ()
Destructor.
Protected Attributes
SLinearClenshawCurtisBase base
Poly Boundary Basis object.
GridStorage & storage
Detailed Description
Quadrature on sparse grid, linear grid without boundaries.
Constructor & Destructor Documentation
OperationQuadratureLinearClenshawCurtis()
sgpp::base::OperationQuadratureLinearClenshawCurtis::OperationQuadratureLinearClenshawCurtis (GridStorage & storage) inline explicit
Constructor of OperationQuadratureLinearClenshawCurtis.
Parameters
storage Pointer to the grid's GridStorage object
~OperationQuadratureLinearClenshawCurtis()
sgpp::base::OperationQuadratureLinearClenshawCurtis::~OperationQuadratureLinearClenshawCurtis () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationQuadratureLinearClenshawCurtis::doQuadrature (DataVector & alpha) override virtual
Quadrature for piecewise linear hat basis functions.
Computes
\[ \sum_{\vec{l}} 2^{-|\vec{l}|}\alpha_{\vec{l}}. \]
Parameters
alpha Coefficient vector for current grid
Implements sgpp::base::OperationQuadrature.
References alpha, base, sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::LinearClenshawCurtisBasis< LT, IT >::getIntegral(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getPoint(), sgpp::base::DataVector::getSize(), and storage.
Member Data Documentation
base
SLinearClenshawCurtisBase sgpp::base::OperationQuadratureLinearClenshawCurtis::base protected
Poly Boundary Basis object.
Referenced by doQuadrature().
storage
GridStorage& sgpp::base::OperationQuadratureLinearClenshawCurtis::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationQuadratureLinearClenshawCurtis.hpp
base/src/sgpp/base/operation/hash/OperationQuadratureLinearClenshawCurtis.cpp