SG++-Doxygen-Documentation: sgpp::base::OperationSecondMomentModLinear Class Reference
sgpp::base::OperationSecondMomentModLinear Class Reference
SecondMomemnt of sparse grid function, linear grid without boundaries.
#include <OperationSecondMomentModLinear.hpp>
Public Member Functions
double doQuadrature (DataVector &alpha, DataMatrix *bounds=nullptr) override
Compute first moment of the function.
OperationSecondMomentModLinear (GridStorage &storage)
Constructor of OperationSecondMomentModLinear.
~OperationSecondMomentModLinear () override
Public Member Functions inherited from sgpp::base::OperationSecondMoment
OperationSecondMoment ()
Constructor.
virtual ~OperationSecondMoment ()
Destructor.
Protected Attributes
GridStorage & storage
Detailed Description
SecondMomemnt of sparse grid function, linear grid without boundaries.
Constructor & Destructor Documentation
OperationSecondMomentModLinear()
sgpp::base::OperationSecondMomentModLinear::OperationSecondMomentModLinear (GridStorage & storage) inline explicit
Constructor of OperationSecondMomentModLinear.
Parameters
storage Pointer to the grid's GridStorage object
~OperationSecondMomentModLinear()
sgpp::base::OperationSecondMomentModLinear::~OperationSecondMomentModLinear () inline override
Member Function Documentation
doQuadrature()
double sgpp::base::OperationSecondMomentModLinear::doQuadrature (DataVector & alpha, DataMatrix * bounds = nullptr) override virtual
Compute first moment of the function.
\[ \int_{\Omega} x\cdot f(x) dx. \]
Parameters
alpha Coefficient vector for current grid
bounds describes the boundaries of the hypercube of the original function
Implements sgpp::base::OperationSecondMoment.
References alpha, sgpp::base::HashGridStorage::begin(), sgpp::base::HashGridStorage::end(), sgpp::base::DataVector::get(), sgpp::base::DataMatrix::get(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), level, and storage.
Member Data Documentation
storage
GridStorage& sgpp::base::OperationSecondMomentModLinear::storage protected
Referenced by doQuadrature().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationSecondMomentModLinear.hpp
base/src/sgpp/base/operation/hash/OperationSecondMomentModLinear.cpp