SG++-Doxygen-Documentation: sgpp::base::sle_solver::BiCGStab Class Reference
sgpp::base::sle_solver::BiCGStab Class Reference
Linear system solver implementing the iterative BiCGStab method.
#include <BiCGStab.hpp>
Public Member Functions
BiCGStab ()
Constructor.
BiCGStab (size_t maxItCount, double tolerance, const DataVector &startingPoint)
size_t getMaxItCount () const
const DataVector & getStartingPoint () const
double getTolerance () const
void setMaxItCount (size_t maxItCount)
void setStartingPoint (const DataVector &startingPoint)
void setTolerance (double tolerance)
bool solve (SLE &system, DataVector &b, DataVector &x) const override
~BiCGStab () override
Destructor.
Public Member Functions inherited from sgpp::base::sle_solver::SLESolver
SLESolver ()
Constructor.
virtual bool solve (SLE &system, DataMatrix &B, DataMatrix &X) const
Virtual method for solving multiple linear systems with different right-hand sides.
virtual ~SLESolver ()
Destructor.
Static Public Attributes
static const size_t DEFAULT_MAX_IT_COUNT = 1000
default maximal number of iterations
static constexpr double DEFAULT_TOLERANCE = 1e-10
default tolerance
Protected Attributes
size_t N
maximal number of iterations
double tol
tolerance
DataVector x0
starting vector
Detailed Description
Linear system solver implementing the iterative BiCGStab method.
Constructor & Destructor Documentation
BiCGStab() [1/2]
sgpp::base::sle_solver::BiCGStab::BiCGStab ()
Constructor.
BiCGStab() [2/2]
sgpp::base::sle_solver::BiCGStab::BiCGStab (size_t maxItCount, double tolerance, const DataVector & startingPoint)
Parameters
maxItCount maximal number of iterations
tolerance tolerance
startingPoint starting vector
~BiCGStab()
sgpp::base::sle_solver::BiCGStab::~BiCGStab () override
Destructor.
Member Function Documentation
getMaxItCount()
size_t sgpp::base::sle_solver::BiCGStab::getMaxItCount () const
Returns
maximal number of iterations
References N.
getStartingPoint()
const DataVector & sgpp::base::sle_solver::BiCGStab::getStartingPoint () const
Returns
starting vector
References x0.
getTolerance()
double sgpp::base::sle_solver::BiCGStab::getTolerance () const
Returns
tolerance
References tol.
setMaxItCount()
void sgpp::base::sle_solver::BiCGStab::setMaxItCount (size_t maxItCount)
Parameters
maxItCount maximal number of iterations
References N.
setStartingPoint()
void sgpp::base::sle_solver::BiCGStab::setStartingPoint (const DataVector & startingPoint)
Parameters
startingPoint starting vector
References sgpp::base::DataVector::getSize(), and x0.
setTolerance()
void sgpp::base::sle_solver::BiCGStab::setTolerance (double tolerance)
Parameters
tolerance tolerance
References tol.
solve()
bool sgpp::base::sle_solver::BiCGStab::solve (SLE & system, DataVector & b, DataVector & x) const override virtual
Parameters
system system to be solved
b right-hand side
[out] x solution to the system
Returns
whether all went well (false if errors occurred)
Implements sgpp::base::sle_solver::SLESolver.
References alpha, sgpp::base::DataVector::dotProduct(), sgpp::base::Printer::getInstance(), sgpp::base::SLE::getMatrixEntry(), sgpp::base::DataVector::getSize(), sgpp::base::SLE::matrixVectorMultiplication(), N, sgpp::base::Printer::printStatusBegin(), sgpp::base::Printer::printStatusEnd(), sgpp::base::Printer::printStatusUpdate(), sgpp::base::DataVector::setAll(), tol, and x0.
Referenced by sgpp::optimization::IterativeGridGeneratorLinearSurplus::generate().
Member Data Documentation
DEFAULT_MAX_IT_COUNT
const size_t sgpp::base::sle_solver::BiCGStab::DEFAULT_MAX_IT_COUNT = 1000 static
default maximal number of iterations
DEFAULT_TOLERANCE
constexpr double sgpp::base::sle_solver::BiCGStab::DEFAULT_TOLERANCE = 1e-10 static constexpr
default tolerance
N
size_t sgpp::base::sle_solver::BiCGStab::N protected
maximal number of iterations
Referenced by getMaxItCount(), setMaxItCount(), and solve().
tol
double sgpp::base::sle_solver::BiCGStab::tol protected
tolerance
Referenced by getTolerance(), setTolerance(), and solve().
x0
DataVector sgpp::base::sle_solver::BiCGStab::x0 protected
starting vector
Referenced by getStartingPoint(), setStartingPoint(), and solve().
The documentation for this class was generated from the following files:
base/src/sgpp/base/tools/sle/solver/BiCGStab.hpp
base/src/sgpp/base/tools/sle/solver/BiCGStab.cpp