SG++-Doxygen-Documentation: sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > > Class Reference
sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > > Class Reference
Template Specialization for LinearStretchedBoundaryBasis basis.
#include <GetAffectedBasisFunctions.hpp>
Public Member Functions
GetAffectedBasisFunctions (GridStorage &storage)
void operator() (SLinearStretchedBoundaryBase &basis, const DataVector &point, std::vector< std::pair< size_t, double > > &result)
~GetAffectedBasisFunctions ()
Protected Member Functions
void recBB (SLinearStretchedBoundaryBase &basis, const DataVector &point, size_t current_dim, double value, GridStorage::grid_iterator &working, std::vector< std::pair< size_t, double > > &result)
Protected Attributes
GridStorage & storage
Stretching * stretch
Detailed Description
Template Specialization for LinearStretchedBoundaryBasis basis.
Constructor & Destructor Documentation
GetAffectedBasisFunctions()
sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::GetAffectedBasisFunctions (GridStorage & storage) inline explicit
~GetAffectedBasisFunctions()
sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::~GetAffectedBasisFunctions () inline
Member Function Documentation
operator()()
void sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::operator() (SLinearStretchedBoundaryBase & basis, const DataVector & point, std::vector< std::pair< size_t, double > > & result) inline
References sgpp::base::HashGridIterator::resetToLevelZero(), and sgpp::base::GetAffectedBasisFunctions< BASIS >::storage.
recBB()
void sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::recBB (SLinearStretchedBoundaryBase & basis, const DataVector & point, size_t current_dim, double value, GridStorage::grid_iterator & working, std::vector< std::pair< size_t, double > > & result) inline protected
calculate using the right-hand ramp
calculate using the left-hand ramp
References sgpp::base::LinearStretchedBoundaryBasis< LT, IT >::eval(), sgpp::base::HashGridIterator::get(), sgpp::base::Stretching::getAdjacentPositions(), sgpp::base::BoundingBox::getBoundary(), sgpp::base::Stretching::getCoordinate(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridIterator::hint(), sgpp::base::HashGridStorage::isInvalidSequenceNumber(), sgpp::base::BoundingBox1D::leftBoundary, sgpp::base::HashGridIterator::leftChild(), sgpp::base::HashGridIterator::resetToLeftLevelZero(), sgpp::base::HashGridIterator::resetToLevelOne(), sgpp::base::HashGridIterator::resetToRightLevelZero(), sgpp::base::BoundingBox1D::rightBoundary, sgpp::base::HashGridIterator::rightChild(), sgpp::base::HashGridIterator::seq(), and sgpp::base::GetAffectedBasisFunctions< BASIS >::storage.
Member Data Documentation
storage
GridStorage& sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::storage protected
stretch
Stretching* sgpp::base::GetAffectedBasisFunctions< LinearStretchedBoundaryBasis< unsigned int, unsigned int > >::stretch protected
The documentation for this class was generated from the following file:
base/src/sgpp/base/algorithm/GetAffectedBasisFunctions.hpp