SG++-Doxygen-Documentation: sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity Class Reference
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity Class Reference abstract
Base class for density multiplication operation.
#include <OperationDensityOCL.hpp>
Public Member Functions
virtual void finalize_rhs_generation (sgpp::base::DataVector &b, size_t start_id, size_t chunksize)=0
virtual void finish_partial_mult (double *result, int start_id, int chunksize)=0
virtual void generateb (base::DataMatrix &dataset, sgpp::base::DataVector &b, size_t start_id=0, size_t chunksize=0)=0
Generates the right hand side vector for the density equation.
virtual void initialize_alpha (double *alpha)=0
Use before calling partial_mult directly.
virtual void initialize_dataset (base::DataMatrix &dataset)=0
virtual void mult (base::DataVector &alpha, base::DataVector &result)=0
Execute one matrix-vector multiplication with the density matrix.
OperationDensity ()
virtual void start_partial_mult (int start_id, int chunksize)=0
Execute a partial (startindex to startindex+chunksize) multiplication with the density matrix.
virtual void start_rhs_generation (size_t start_id, size_t chunksize)=0
Public Member Functions inherited from sgpp::base::OperationMatrix
OperationMatrix ()
Constructor.
virtual ~OperationMatrix ()
Destructor.
Static Public Member Functions
static void load_default_parameters (base::OCLOperationConfiguration *parameters)
Generate the default parameters in die json configuration.
Detailed Description
Base class for density multiplication operation.
Constructor & Destructor Documentation
OperationDensity()
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::OperationDensity () inline
Member Function Documentation
finalize_rhs_generation()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::finalize_rhs_generation (sgpp::base::DataVector & b, size_t start_id, size_t chunksize) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityRhsWorker::finalize_opencl_operation().
finish_partial_mult()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::finish_partial_mult (double * result, int start_id, int chunksize) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityWorker::finalize_opencl_operation().
generateb()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::generateb (base::DataMatrix & dataset, sgpp::base::DataVector & b, size_t start_id = 0, size_t chunksize = 0) pure virtual
Generates the right hand side vector for the density equation.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), main(), and main().
initialize_alpha()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::initialize_alpha (double * alpha) pure virtual
Use before calling partial_mult directly.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityWorker::receive_and_send_initial_data().
initialize_dataset()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::initialize_dataset (base::DataMatrix & dataset) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityRhsWorker::receive_and_send_initial_data().
load_default_parameters()
static void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters (base::OCLOperationConfiguration * parameters) inline static
Generate the default parameters in die json configuration.
References json::DictNode::addIDAttr(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityB< T >::augmentDefaultParameters(), sgpp::datadriven::DensityOCLMultiPlatform::KernelDensityMult< T >::augmentDefaultParameters(), and json::DictNode::contains().
Referenced by sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), and sgpp::datadriven::createDensityOCLMultiPlatformConfigured().
mult()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::mult (base::DataVector & alpha, base::DataVector & result) pure virtual
Execute one matrix-vector multiplication with the density matrix.
Implements sgpp::base::OperationMatrix.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
start_partial_mult()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::start_partial_mult (int start_id, int chunksize) pure virtual
Execute a partial (startindex to startindex+chunksize) multiplication with the density matrix.
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityWorker::begin_opencl_operation().
start_rhs_generation()
virtual void sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::start_rhs_generation (size_t start_id, size_t chunksize) pure virtual
Implemented in sgpp::datadriven::DensityOCLMultiPlatform::OperationDensityOCLMultiPlatform< T >.
Referenced by sgpp::datadriven::clusteringmpi::DensityRhsWorker::begin_opencl_operation().
The documentation for this class was generated from the following file:
datadriven/src/sgpp/datadriven/operation/hash/OperationDensityOCLMultiPlatform/OperationDensityOCL.hpp