SG++-Doxygen-Documentation: sgpp::datadriven::RuleOfThumb Class Reference
sgpp::datadriven::RuleOfThumb Class Reference
#include <KernelDensityEstimator.hpp>
Static Public Member Functions
static double getSampleMean (base::DataVector &data)
static double getSampleStd (base::DataVector &data)
static double getSampleVariance (base::DataVector &data)
Member Function Documentation
getSampleMean()
double sgpp::datadriven::RuleOfThumb::getSampleMean (base::DataVector & data) static
Referenced by getSampleVariance().
getSampleStd()
double sgpp::datadriven::RuleOfThumb::getSampleStd (base::DataVector & data) static
References getSampleVariance().
Referenced by sgpp::datadriven::SilvermansRule::optimizeBandwidths(), and sgpp::datadriven::ScottsRule::optimizeBandwidths().
getSampleVariance()
double sgpp::datadriven::RuleOfThumb::getSampleVariance (base::DataVector & data) static
References getSampleMean().
Referenced by getSampleStd().
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.hpp
datadriven/src/sgpp/datadriven/application/KernelDensityEstimator.cpp