SG++-Doxygen-Documentation: sgpp::base::DistributionLogNormal Class Reference
sgpp::base::DistributionLogNormal Class Reference
#include <DistributionLogNormal.hpp>
Public Member Functions
DistributionLogNormal (double mean, double stddev)
Constructor.
double eval (double x)
sgpp::base::DataVector getBounds ()
See DistributionNormal.cpp: 2*Phi(z)-1 of a normal distirbutions mass lie inside the interval [mean-z*sigma,mean+z*sigma].
sgpp::base::DataVector getCharacteristics ()
return all relevant characteristic values (e.g.
sgpp::base::DistributionType getType ()
double sample ()
virtual ~DistributionLogNormal ()
Destructor.
Public Member Functions inherited from sgpp::base::Distribution
Distribution (typename std::chrono::system_clock::duration::rep seed=777)
Constructor.
sgpp::base::DataVector samples (size_t num)
virtual ~Distribution ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from sgpp::base::Distribution
std::default_random_engine gen
Constructor & Destructor Documentation
DistributionLogNormal()
sgpp::base::DistributionLogNormal::DistributionLogNormal (double mean, double stddev) inline
Constructor.
~DistributionLogNormal()
virtual sgpp::base::DistributionLogNormal::~DistributionLogNormal () inline virtual
Destructor.
Member Function Documentation
eval()
double sgpp::base::DistributionLogNormal::eval (double x) inline virtual
Implements sgpp::base::Distribution.
References M_PI.
Referenced by python.uq.analysis.asgc.ASGCAnalysis.ASGCAnalysis::estimateDensity().
getBounds()
sgpp::base::DataVector sgpp::base::DistributionLogNormal::getBounds () inline virtual
See DistributionNormal.cpp: 2*Phi(z)-1 of a normal distirbutions mass lie inside the interval [mean-z*sigma,mean+z*sigma].
Therefore corresponding accuracies for logNormal distribution are achieved in an interval [exp(mean-z*sigma),exp(mean+z*sigma)] As for the normal distribution, we choose z=9 for precision of ~ 10^(-18)
Implements sgpp::base::Distribution.
Referenced by python.uq.dists.J.J::discretize(), and python.uq.dists.Dist.Dist::l2error().
getCharacteristics()
sgpp::base::DataVector sgpp::base::DistributionLogNormal::getCharacteristics () inline virtual
return all relevant characteristic values (e.g.
mean and standarddeviation for normal distribution)
Implements sgpp::base::Distribution.
getType()
sgpp::base::DistributionType sgpp::base::DistributionLogNormal::getType () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Lognormal.
sample()
double sgpp::base::DistributionLogNormal::sample () inline virtual
Implements sgpp::base::Distribution.
References sgpp::base::Distribution::gen.
Referenced by python.uq.uq_setting.UQSettingManager.UQSettingManager::do_sampleList().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/DistributionLogNormal.hpp