SG++-Doxygen-Documentation: sgpp::base::SLE Class Reference
sgpp::base::SLE Class Reference abstract
Abstract class representing a system of linear equations.
#include <SLE.hpp>
Public Member Functions
virtual size_t countNNZ ()
Count all non-zero entries.
virtual size_t getDimension () const =0
Pure virtual method returning the dimension (number of rows/columns) of the system.
virtual double getMatrixEntry (size_t i, size_t j)=0
Pure virtual method for retrieving a matrix entry.
virtual bool isCloneable () const
virtual bool isMatrixEntryNonZero (size_t i, size_t j)=0
Pure virtual method for checking if a matrix entry vanishes or not.
virtual void matrixVectorMultiplication (const DataVector &x, DataVector &y)
Multiply the matrix with a vector.
SLE ()
Constructor.
virtual ~SLE ()
Destructor.
Detailed Description
Abstract class representing a system of linear equations.
All row and column indices are zero based.
Constructor & Destructor Documentation
SLE()
sgpp::base::SLE::SLE () inline
Constructor.
~SLE()
virtual sgpp::base::SLE::~SLE () inline virtual
Destructor.
Member Function Documentation
countNNZ()
virtual size_t sgpp::base::SLE::countNNZ () inline virtual
Count all non-zero entries.
Standard implementation with \(\mathcal{O}(n^2)\) checks.
Returns
number of non-zero entries
References getDimension(), and isMatrixEntryNonZero().
getDimension()
virtual size_t sgpp::base::SLE::getDimension () const pure virtual
Pure virtual method returning the dimension (number of rows/columns) of the system.
Returns
system dimension
Implemented in sgpp::base::FullSLE, sgpp::base::HierarchisationSLE, and sgpp::combigrid::OperationPoleHierarchisationGeneral::HierarchisationGeneralSLE.
Referenced by countNNZ(), matrixVectorMultiplication(), sgpp::base::Printer::printSLE(), sgpp::base::sle_solver::SLESolver::solve(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Auto::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), and sgpp::base::sle_solver::Gmmpp::solve().
getMatrixEntry()
virtual double sgpp::base::SLE::getMatrixEntry (size_t i, size_t j) pure virtual
Pure virtual method for retrieving a matrix entry.
Parameters
i row index
j column index
Returns
(i,j)-th entry of the matrix
Implemented in sgpp::base::FullSLE, sgpp::base::HierarchisationSLE, and sgpp::combigrid::OperationPoleHierarchisationGeneral::HierarchisationGeneralSLE.
Referenced by matrixVectorMultiplication(), sgpp::base::Printer::printSLE(), sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), sgpp::base::sle_solver::BiCGStab::solve(), sgpp::base::sle_solver::GaussianElimination::solve(), and sgpp::base::sle_solver::Gmmpp::solve().
isCloneable()
virtual bool sgpp::base::SLE::isCloneable () const inline virtual
Returns
whether this system derives from CloneableSLE or not (standard: false)
Reimplemented in sgpp::base::CloneableSLE.
Referenced by sgpp::base::sle_solver::Armadillo::solve(), sgpp::base::sle_solver::Eigen::solve(), sgpp::base::sle_solver::UMFPACK::solve(), and sgpp::base::sle_solver::Gmmpp::solve().
isMatrixEntryNonZero()
virtual bool sgpp::base::SLE::isMatrixEntryNonZero (size_t i, size_t j) pure virtual
Pure virtual method for checking if a matrix entry vanishes or not.
Parameters
i row index
j column index
Returns
whether the (i,j)-th entry of the matrix is non-zero
Implemented in sgpp::base::FullSLE, sgpp::base::HierarchisationSLE, and sgpp::combigrid::OperationPoleHierarchisationGeneral::HierarchisationGeneralSLE.
Referenced by countNNZ(), and sgpp::base::sle_solver::Auto::solve().
matrixVectorMultiplication()
virtual void sgpp::base::SLE::matrixVectorMultiplication (const DataVector & x, DataVector & y) inline virtual
Multiply the matrix with a vector.
Standard implementation with \(\mathcal{O}(n^2)\) scalar multiplications.
Parameters
x vector to be multiplied
[out] y \(y = Ax\)
References getDimension(), getMatrixEntry(), and sgpp::base::DataVector::setAll().
Referenced by sgpp::base::sle_solver::BiCGStab::solve().
The documentation for this class was generated from the following file:
base/src/sgpp/base/tools/sle/system/SLE.hpp