SG++-Doxygen-Documentation: sgpp::datadriven::OperationMultipleEvalSubspaceSimple Class Reference
sgpp::datadriven::OperationMultipleEvalSubspaceSimple Class Reference
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
#include <OperationMultipleEvalSubspaceSimple.hpp>
Public Member Functions
size_t getAlignment () override
Alignment required by the vector instruction set SG++ is compiled with.
std::string getImplementationName () override
Name of the implementation, useful for benchmarking different implementation approaches.
void multImpl (sgpp::base::DataVector &source, sgpp::base::DataVector &result, const size_t start_index_data, const size_t end_index_data) override
Internal mult operator, should not be called directly.
void multTransposeImpl (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result, const size_t start_index_data, const size_t end_index_data) override
Internal eval operator, should not be called directly.
OperationMultipleEvalSubspaceSimple (base::Grid &grid, base::DataMatrix &dataset)
Creates a new instance of the OperationMultipleEvalSubspaceSimple class.
void prepare () override
Updates the internal data structures to reflect changes to the grid, e.g.
~OperationMultipleEvalSubspaceSimple ()
Destructor.
Public Member Functions inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
AbstractOperationMultipleEvalSubspace (base::Grid &grid, base::DataMatrix &dataset)
double getDuration () override
virtual size_t getPaddedDatasetSize ()
void mult (sgpp::base::DataVector &source, sgpp::base::DataVector &result) override
Multiplication of \(B^T\) with vector \(\alpha\).
void multTranspose (sgpp::base::DataVector &alpha, sgpp::base::DataVector &result) override
Multiplication of \(B\) with vector \(\alpha\).
~AbstractOperationMultipleEvalSubspace () override
Public Member Functions inherited from sgpp::base::OperationMultipleEval
void eval (DataVector &alpha, DataVector &result)
Evaluate multiple datapoints with the specified grid.
virtual void mult (DataVector &alpha, DataVector &result, size_t startIndexData, size_t endIndexData)
Multiplication of \(B^T\) with vector \(\alpha\).
virtual void multTranspose (DataVector &source, DataVector &result, size_t startIndexGrid, size_t endIndexGrid)
Multiplication of \(B\) with vector \(\alpha\).
OperationMultipleEval (sgpp::base::Grid &grid, DataMatrix &dataset)
Constructor.
virtual ~OperationMultipleEval ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
static size_t getChunkDataPoints ()
static size_t getChunkGridPoints ()
Protected Attributes inherited from sgpp::datadriven::AbstractOperationMultipleEvalSubspace
base::GridStorage * storage
Protected Attributes inherited from sgpp::base::OperationMultipleEval
DataMatrix & dataset
Grid & grid
bool isPrepared
Detailed Description
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
Verification and debugging variant, should not be used. Instead, use the OperationMultipleEvalSubspaceCombined.
Constructor & Destructor Documentation
OperationMultipleEvalSubspaceSimple()
sgpp::datadriven::OperationMultipleEvalSubspaceSimple::OperationMultipleEvalSubspaceSimple (base::Grid & grid, base::DataMatrix & dataset)
Creates a new instance of the OperationMultipleEvalSubspaceSimple class.
Parameters
grid grid to be evaluated
dataset set of evaluation points
References sgpp::base::DataMatrix::getNcols().
~OperationMultipleEvalSubspaceSimple()
sgpp::datadriven::OperationMultipleEvalSubspaceSimple::~OperationMultipleEvalSubspaceSimple ()
Destructor.
Member Function Documentation
getAlignment()
size_t sgpp::datadriven::OperationMultipleEvalSubspaceSimple::getAlignment () override virtual
Alignment required by the vector instruction set SG++ is compiled with.
Returns
alignment requirement
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
getImplementationName()
std::string sgpp::datadriven::OperationMultipleEvalSubspaceSimple::getImplementationName () override virtual
Name of the implementation, useful for benchmarking different implementation approaches.
Returns
name of the implementation
Reimplemented from sgpp::base::OperationMultipleEval.
multImpl()
void sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multImpl (sgpp::base::DataVector & source, sgpp::base::DataVector & result, const size_t start_index_data, const size_t end_index_data) override virtual
Internal mult operator, should not be called directly.
See also
OperationMultipleEval
Parameters
source source operand for the operator
result stores the result
start_index_data beginning of the range to process
end_index_data end of the range to process
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References sgpp::base::OperationMultipleEval::dataset, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataVector::getPointer(), sgpp::base::DataMatrix::getRow(), and sgpp::base::DataVector::set().
multTransposeImpl()
void sgpp::datadriven::OperationMultipleEvalSubspaceSimple::multTransposeImpl (sgpp::base::DataVector & alpha, sgpp::base::DataVector & result, const size_t start_index_data, const size_t end_index_data) override virtual
Internal eval operator, should not be called directly.
See also
OperationMultipleEval
Parameters
alpha surplusses of the grid
result will contain the evaluation results for the given range.
start_index_data beginning of the range to evaluate
end_index_data end of the range to evaluate
Implements sgpp::datadriven::AbstractOperationMultipleEvalSubspace.
References alpha, sgpp::base::OperationMultipleEval::dataset, sgpp::base::DataMatrix::getNcols(), sgpp::base::DataVector::getPointer(), and sgpp::base::DataMatrix::getRow().
prepare()
void sgpp::datadriven::OperationMultipleEvalSubspaceSimple::prepare () override virtual
Updates the internal data structures to reflect changes to the grid, e.g.
due to refinement.
Reimplemented from sgpp::base::OperationMultipleEval.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/simple/OperationMultipleEvalSubspaceSimple.hpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/simple/OperationMultipleEvalSubspaceSimple.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/simple/OperationMultipleEvalSubspaceSimple_multImpl.cpp
datadriven/src/sgpp/datadriven/operation/hash/OperationMultipleEvalSubspace/simple/OperationMultipleEvalSubspaceSimple_multTransposeImpl.cpp