SG++-Doxygen-Documentation: sgpp::base::OperationEvalGradientNakBsplineExtendedNaive Class Reference
sgpp::base::OperationEvalGradientNakBsplineExtendedNaive Class Reference
Operation for evaluating nak B-spline linear combinations on Noboundary grids and their gradients.
#include <OperationEvalGradientNakBsplineExtendedNaive.hpp>
Public Member Functions
void evalGradient (const DataMatrix &alpha, const DataVector &point, DataVector &value, DataMatrix &gradient) override
double evalGradient (const DataVector &alpha, const DataVector &point, DataVector &gradient) override
OperationEvalGradientNakBsplineExtendedNaive (GridStorage &storage, size_t degree)
Constructor.
~OperationEvalGradientNakBsplineExtendedNaive () override
Destructor.
Public Member Functions inherited from sgpp::base::OperationEvalGradient
OperationEvalGradient ()
Constructor.
virtual ~OperationEvalGradient ()
Destructor.
Protected Attributes
SNakBsplineExtendedBase base
1D B-spline basis
DataVector innerDerivative
inner derivative (temporary vector)
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
GridStorage & storage
storage of the sparse grid
Additional Inherited Members
Public Attributes inherited from sgpp::base::OperationEvalGradient
DataVector pointInUnitCube
untransformed evaluation point (temporary vector)
Detailed Description
Operation for evaluating nak B-spline linear combinations on Noboundary grids and their gradients.
Constructor & Destructor Documentation
OperationEvalGradientNakBsplineExtendedNaive()
sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::OperationEvalGradientNakBsplineExtendedNaive (GridStorage & storage, size_t degree) inline
Constructor.
Parameters
storage storage of the sparse grid
degree B-spline degree
~OperationEvalGradientNakBsplineExtendedNaive()
sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::~OperationEvalGradientNakBsplineExtendedNaive () inline override
Destructor.
Member Function Documentation
evalGradient() [1/2]
void sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient (const DataMatrix & alpha, const DataVector & point, DataVector & value, DataMatrix & gradient) override virtual
Parameters
alpha coefficient matrix (each column is a coefficient vector)
point evaluation point
[out] value values of the linear combination
[out] gradient Jacobian of the linear combination (each row is a gradient vector)
Reimplemented from sgpp::base::OperationEvalGradient.
References alpha, base, sgpp::base::NakBsplineExtendedBasis< LT, IT >::eval(), sgpp::base::NakBsplineExtendedBasis< LT, IT >::evalDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, m, pointInUnitCube, sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::setAll(), sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
evalGradient() [2/2]
double sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::evalGradient (const DataVector & alpha, const DataVector & point, DataVector & gradient) override virtual
Parameters
alpha coefficient vector
point evaluation point
[out] gradient gradient of linear combination
Returns
value of the linear combination
Implements sgpp::base::OperationEvalGradient.
References sgpp::base::DataVector::add(), alpha, base, sgpp::base::NakBsplineExtendedBasis< LT, IT >::eval(), sgpp::base::NakBsplineExtendedBasis< LT, IT >::evalDx(), sgpp::base::HashGridStorage::getBoundingBox(), sgpp::base::HashGridStorage::getDimension(), sgpp::base::HashGridPoint::getIndex(), sgpp::base::BoundingBox::getIntervalWidth(), sgpp::base::HashGridPoint::getLevel(), sgpp::base::HashGridStorage::getSize(), innerDerivative, pointInUnitCube, sgpp::base::DataVector::setAll(), storage, and sgpp::base::BoundingBox::transformPointToUnitCube().
Member Data Documentation
base
SNakBsplineExtendedBase sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::base protected
1D B-spline basis
Referenced by evalGradient(), and evalGradient().
innerDerivative
DataVector sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::innerDerivative protected
inner derivative (temporary vector)
Referenced by evalGradient(), and evalGradient().
pointInUnitCube
DataVector sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::pointInUnitCube protected
untransformed evaluation point (temporary vector)
Referenced by evalGradient(), and evalGradient().
storage
GridStorage& sgpp::base::OperationEvalGradientNakBsplineExtendedNaive::storage protected
storage of the sparse grid
Referenced by evalGradient(), and evalGradient().
The documentation for this class was generated from the following files:
base/src/sgpp/base/operation/hash/OperationEvalGradientNakBsplineExtendedNaive.hpp
base/src/sgpp/base/operation/hash/OperationEvalGradientNakBsplineExtendedNaive.cpp