SG++-Doxygen-Documentation: sgpp::datadriven::ArffFileSampleProvider Class Reference
sgpp::datadriven::ArffFileSampleProvider Class Reference
ArffFileSampleProvider allows reading data in ARFF format into a sgpp::datadriven::Dataset object.
#include <ArffFileSampleProvider.hpp>
Public Member Functions
ArffFileSampleProvider (DataShufflingFunctor *shuffling=nullptr)
Default constructor.
SampleProvider * clone () const override
Clone Pattern to allow copying of derived classes.
Dataset * getAllSamples () override
Asks to return all available samples.
size_t getDim () const override
Returns the maximal dimensionality of the data.
Dataset * getNextSamples (size_t howMany) override
Lets the user request a certain amount of samples.
size_t getNumSamples () const override
Returns the number of samples availible or throws if not possible.
void readFile (const std::string &filePath, bool hasTargets, size_t readinCutoff=-1, std::vector< size_t > readinColumns=std::vector< size_t >(), std::vector< double > readinClasses=std::vector< double >()) override
Open an existing ARFF file, parse it and store its contents inside this class.
void readString (const std::string &input, bool hasTargets, size_t readinCutoff=-1, std::vector< size_t > readinColumns=std::vector< size_t >(), std::vector< double > readinClasses=std::vector< double >()) override
Parse contents of a string containing information in ARFF format, parse it and store its contents inside this class.
void reset () override
Resets the state of the sample provider (e.g.
~ArffFileSampleProvider () override
Explicit destructor to avoid memory leaks.
Public Member Functions inherited from sgpp::datadriven::SampleProvider
SampleProvider & operator= (const SampleProvider &rhs)=default
SampleProvider & operator= (SampleProvider &&rhs)=default
SampleProvider ()=default
SampleProvider (const SampleProvider &rhs)=default
SampleProvider (SampleProvider &&rhs)=default
virtual ~SampleProvider ()=default
Detailed Description
ArffFileSampleProvider allows reading data in ARFF format into a sgpp::datadriven::Dataset object.
Data can currently be either be a string formatted in ARFF or a file containing ARFF data.
Constructor & Destructor Documentation
ArffFileSampleProvider()
sgpp::datadriven::ArffFileSampleProvider::ArffFileSampleProvider (DataShufflingFunctor * shuffling = nullptr) explicit
Default constructor.
Parameters
shuffling functor to permute the training data indexes
~ArffFileSampleProvider()
sgpp::datadriven::ArffFileSampleProvider::~ArffFileSampleProvider () inline override
Explicit destructor to avoid memory leaks.
Member Function Documentation
clone()
SampleProvider * sgpp::datadriven::ArffFileSampleProvider::clone () const override virtual
Clone Pattern to allow copying of derived classes.
Returns
a Pointer to a new instance of sgpp::datadriven::ArffFileSampleProvider with copied state. Caller owns the new object.
Implements sgpp::datadriven::SampleProvider.
getAllSamples()
Dataset * sgpp::datadriven::ArffFileSampleProvider::getAllSamples () override virtual
Asks to return all available samples.
This functionality is designed for returning all available samples from an entire file.
Returns
sgpp::datadriven::Dataset* Pointer to a new sgpp::datadriven::Dataset object. This object is owned by the caller.
Implements sgpp::datadriven::SampleProvider.
References sgpp::datadriven::Dataset::getDimension(), getNextSamples(), and sgpp::datadriven::Dataset::getNumberInstances().
getDim()
size_t sgpp::datadriven::ArffFileSampleProvider::getDim () const override virtual
Returns the maximal dimensionality of the data.
Returns
dimensionality of the sgpp::datadriven::Dataset.
Implements sgpp::datadriven::SampleProvider.
References sgpp::datadriven::Dataset::getDimension().
Referenced by python.uq.dists.SGDEdist.SGDEdist::__str__(), python.uq.dists.Dist.Dist::cov(), python.uq.parameters.ParameterSet.ParameterSet::extractActiveSubset(), python.uq.dists.KDEDist.KDEDist::getBandwidths(), python.uq.dists.EstimatedDist.EstimatedDist::getBounds(), and python.uq.uq_setting.UQSetting.UQSetting::getDim().
getNextSamples()
Dataset * sgpp::datadriven::ArffFileSampleProvider::getNextSamples (size_t howMany) override virtual
Lets the user request a certain amount of samples.
This functionality is is designed for streaming algorithms where data is processed in batches.
Parameters
howMany number requested amount of samples. The amount of actually provided samples can be smaller, if there is not sufficient data.
Returns
sgpp::datadriven::Dataset* Pointer to a new sgpp::datadriven::Dataset object containing at most the requested amount of samples. This object is owned by the caller.
Implements sgpp::datadriven::SampleProvider.
References sgpp::datadriven::Dataset::getDimension().
Referenced by getAllSamples().
getNumSamples()
size_t sgpp::datadriven::ArffFileSampleProvider::getNumSamples () const override virtual
Returns the number of samples availible or throws if not possible.
Returns
the number of samples availible
Implements sgpp::datadriven::SampleProvider.
References sgpp::datadriven::Dataset::getDimension(), and sgpp::datadriven::Dataset::getNumberInstances().
readFile()
void sgpp::datadriven::ArffFileSampleProvider::readFile (const std::string & filePath, bool hasTargets, size_t readinCutoff = -1, std::vector< size_t > readinColumns = std::vector<size_t>(), std::vector< double > readinClasses = std::vector<double>()) override virtual
Open an existing ARFF file, parse it and store its contents inside this class.
Throws if file can not be opened or parsed.
Parameters
filePath Path to an existing file.
hasTargets whether the file has targest (i.e. supervised learning)
readinCutoff see FileSampleProvider.hpp
readinColumns see FileSampleProvider.hpp
readinClasses see FileSampleProvider.hpp
Implements sgpp::datadriven::FileSampleProvider.
References fileName, and sgpp::datadriven::ARFFTools::readARFFFromFile().
readString()
void sgpp::datadriven::ArffFileSampleProvider::readString (const std::string & input, bool hasTargets, size_t readinCutoff = -1, std::vector< size_t > readinColumns = std::vector<size_t>(), std::vector< double > readinClasses = std::vector<double>()) override virtual
Parse contents of a string containing information in ARFF format, parse it and store its contents inside this class.
Throws if string can not be parsed.
Parameters
input string containing information in ARFF file format
hasTargets whether the file has targest (i.e. supervised learning)
readinCutoff see FileSampleProvider.hpp
readinColumns see FileSampleProvider.hpp
readinClasses see FileSampleProvider.hpp
Implements sgpp::datadriven::FileSampleProvider.
References sgpp::datadriven::ARFFTools::readARFFFromString().
reset()
void sgpp::datadriven::ArffFileSampleProvider::reset () override virtual
Resets the state of the sample provider (e.g.
to start a new epoch)
Implements sgpp::datadriven::SampleProvider.
The documentation for this class was generated from the following files:
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/ArffFileSampleProvider.hpp
datadriven/src/sgpp/datadriven/datamining/modules/dataSource/ArffFileSampleProvider.cpp