SG++-Doxygen-Documentation: datadriven/examplesOCL/clustering_poster.cpp File Reference
clustering_poster.cpp File Reference
#include <sgpp/base/datatypes/DataVector.hpp>
#include <sgpp/base/grid/Grid.hpp>
#include <sgpp/base/grid/GridStorage.hpp>
#include <sgpp/base/grid/generation/GridGenerator.hpp>
#include <sgpp/base/opencl/OCLOperationConfiguration.hpp>
#include <sgpp/datadriven/DatadrivenOpFactory.hpp>
#include <sgpp/datadriven/operation/hash/OperationCreateGraphOCL/OpFactory.hpp>
#include <sgpp/datadriven/operation/hash/OperationDensityMultiplicationAVX/OperationDensityMultiplicationAVX.hpp>
#include <sgpp/datadriven/operation/hash/OperationDensityOCLMultiPlatform/OpFactory.hpp>
#include <sgpp/datadriven/operation/hash/OperationPruneGraphOCL/OpFactory.hpp>
#include <sgpp/datadriven/tools/ARFFTools.hpp>
#include <sgpp/globaldef.hpp>
#include <sgpp/solver/sle/ConjugateGradients.hpp>
#include <boost/program_options.hpp>
#include <chrono>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References alpha, sgpp::datadriven::createDensityOCLMultiPlatformConfigured(), sgpp::base::Grid::createLinearGrid(), sgpp::op_factory::createOperationMultipleEval(), dataset, sgpp::datadriven::DEFAULT, sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::generateb(), sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::base::DataMatrix::getNrows(), grid(), h, lambda, level, sgpp::datadriven::ARFFTools::readARFFFromFile(), sgpp::base::GridGenerator::regular(), sgpp::solver::ConjugateGradients::solve(), sgpp::datadriven::STREAMING, sgpp::base::DataVector::toString(), and trainingData.