SG++-Doxygen-Documentation: datadriven/examplesOCL/createLearnerScenario.cpp File Reference
createLearnerScenario.cpp File Reference
#include <sgpp/base/opencl/OCLOperationConfiguration.hpp>
#include <sgpp/base/operation/hash/OperationMultipleEval.hpp>
#include <sgpp/datadriven/DatadrivenOpFactory.hpp>
#include <sgpp/datadriven/application/LearnerScenario.hpp>
#include <sgpp/datadriven/application/MetaLearner.hpp>
#include <sgpp/datadriven/operation/hash/DatadrivenOperationCommon.hpp>
#include <sgpp/datadriven/tools/ARFFTools.hpp>
#include <sgpp/globaldef.hpp>
#include <iostream>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References adaptivityConfig, alpha, sgpp::datadriven::TestsetConfiguration::alphaReferenceFileName, sgpp::base::GeneralGridConfiguration::boundaryLevel_, sgpp::solver::CG, sgpp::base::GeneralGridConfiguration::dim_, sgpp::datadriven::Double, sgpp::solver::SLESolverConfiguration::eps_, sgpp::datadriven::TestsetConfiguration::expectedLargestDifference, sgpp::datadriven::TestsetConfiguration::expectedMSE, sgpp::datadriven::Float, sgpp::datadriven::LearnerScenario::getAdaptivityConfiguration(), sgpp::datadriven::LearnerScenario::getDatasetFileName(), sgpp::datadriven::LearnerScenario::getGridConfig(), sgpp::datadriven::LearnerScenario::getLambda(), sgpp::datadriven::MetaLearner::getLearnedAlpha(), sgpp::datadriven::LearnerScenario::getSolverConfigurationFinal(), sgpp::datadriven::LearnerScenario::getSolverConfigurationRefine(), sgpp::datadriven::TestsetConfiguration::hasTestDataset, lambda, sgpp::datadriven::MetaLearner::learn(), sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::base::GeneralGridConfiguration::maxDegree_, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::ModLinear, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, json::DictNode::replaceIDAttr(), json::JSON::serialize(), sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::DataVector::toFile(), sgpp::base::GeneralGridConfiguration::type_, and sgpp::solver::SLESolverConfiguration::type_.