SG_BASE = 1
SG_COMBIGRID = 1
SG_OPTIMIZATION = 1
SG_PDE = 1
SG_SOLVER = 1

SG_PARALLEL = 1
SG_FINANCE = 1
SG_MISC = 1
SG_DATADRIVEN = 1

SG_PYTHON = 0
SG_JAVA = 0

COMPILE_BOOST_TESTS = 1
RUN_BOOST_TESTS = 0
RUN_CPPLINT = 0
PYDOC = 0

USE_DAKOTA = 1
CPPPATH = "/home/franzefn/opt/dakota/include"
LIBPATH = "/home/franzefn/opt/dakota/lib"
USE_ARMADILLO = 1
USE_EIGEN = 1
USE_UMFPACK = 1

VERBOSE = 1
BUILD_STATICLIB = 0
OPT = 1

# CPPFLAGS = "-p"
# LINKFLAGS = "-pg"
