SG++-Doxygen-Documentation: datadriven/examplesOCL/degradationReproducer.cpp File Reference
degradationReproducer.cpp File Reference
#include <sgpp/datadriven/application/MetaLearner.hpp>
#include <sgpp/datadriven/operation/hash/DatadrivenOperationCommon.hpp>
#include <sgpp/base/opencl/OCLOperationConfiguration.hpp>
#include <sgpp/datadriven/application/LearnerScenario.hpp>
#include <sgpp/base/datatypes/DataMatrix.hpp>
#include <sgpp/base/datatypes/DataVector.hpp>
#include <sgpp/base/exception/application_exception.hpp>
#include <fstream>
#include <iostream>
#include <string>
Functions
int main (int argc, char **argv)
void verifyLearned (sgpp::datadriven::TestsetConfiguration &testsetConfiguration, DataVector &alpha)
Variables
std::string baseFolder = "datadriven/performanceTests/scenarios/"
Function Documentation
main()
int main (int argc, char ** argv)
References baseFolder, sgpp::datadriven::LearnerScenario::getAdaptivityConfiguration(), sgpp::datadriven::LearnerScenario::getDatasetFileName(), sgpp::datadriven::LearnerScenario::getGridConfig(), sgpp::datadriven::LearnerScenario::getLambda(), sgpp::datadriven::LearnerScenario::getSolverConfigurationFinal(), sgpp::datadriven::LearnerScenario::getSolverConfigurationRefine(), sgpp::datadriven::LearnerScenario::getTestsetConfiguration(), sgpp::datadriven::MetaLearner::learn(), sgpp::datadriven::OCLMP, sgpp::datadriven::STREAMING, and sgpp::base::operation_exception::what().
verifyLearned()
void verifyLearned (sgpp::datadriven::TestsetConfiguration & testsetConfiguration, DataVector & alpha)
References alpha, sgpp::datadriven::TestsetConfiguration::alphaReferenceFileName, sgpp::datadriven::TestsetConfiguration::expectedLargestDifference, sgpp::datadriven::TestsetConfiguration::expectedMSE, and sgpp::base::DataVector::getSize().
Variable Documentation
baseFolder
std::string baseFolder = "datadriven/performanceTests/scenarios/"
Referenced by main().