var dir_c93926576de4a81318ab71c39d7afc5c =
[
    [ "AdaptiveGradientDescent.cpp", "AdaptiveGradientDescent_8cpp.html", null ],
    [ "AdaptiveGradientDescent.hpp", "AdaptiveGradientDescent_8hpp.html", "AdaptiveGradientDescent_8hpp" ],
    [ "AdaptiveNewton.cpp", "AdaptiveNewton_8cpp.html", null ],
    [ "AdaptiveNewton.hpp", "AdaptiveNewton_8hpp.html", "AdaptiveNewton_8hpp" ],
    [ "BFGS.cpp", "BFGS_8cpp.html", null ],
    [ "BFGS.hpp", "BFGS_8hpp.html", "BFGS_8hpp" ],
    [ "CMAES.cpp", "CMAES_8cpp.html", null ],
    [ "CMAES.hpp", "CMAES_8hpp.html", "CMAES_8hpp" ],
    [ "DifferentialEvolution.cpp", "DifferentialEvolution_8cpp.html", null ],
    [ "DifferentialEvolution.hpp", "DifferentialEvolution_8hpp.html", "DifferentialEvolution_8hpp" ],
    [ "GradientDescent.cpp", "GradientDescent_8cpp.html", null ],
    [ "GradientDescent.hpp", "GradientDescent_8hpp.html", "GradientDescent_8hpp" ],
    [ "LineSearchArmijo.hpp", "LineSearchArmijo_8hpp.html", "LineSearchArmijo_8hpp" ],
    [ "MultiStart.cpp", "MultiStart_8cpp.html", null ],
    [ "MultiStart.hpp", "MultiStart_8hpp.html", "MultiStart_8hpp" ],
    [ "NelderMead.cpp", "NelderMead_8cpp.html", null ],
    [ "NelderMead.hpp", "NelderMead_8hpp.html", "NelderMead_8hpp" ],
    [ "Newton.cpp", "Newton_8cpp.html", null ],
    [ "Newton.hpp", "Newton_8hpp.html", "Newton_8hpp" ],
    [ "NLCG.cpp", "NLCG_8cpp.html", null ],
    [ "NLCG.hpp", "NLCG_8hpp.html", "NLCG_8hpp" ],
    [ "Rprop.cpp", "Rprop_8cpp.html", null ],
    [ "Rprop.hpp", "Rprop_8hpp.html", "Rprop_8hpp" ],
    [ "UnconstrainedOptimizer.hpp", "UnconstrainedOptimizer_8hpp.html", "UnconstrainedOptimizer_8hpp" ]
];