var dir_cc58c086ea718db481d79e6432c2a345 =
[
    [ "copyright.doxy", "copyright_8doxy.html", null ],
    [ "development.doxy", "development_8doxy.html", null ],
    [ "example_benchmark_gridInteraction_cpp.doxy", "example__benchmark__gridInteraction__cpp_8doxy.html", null ],
    [ "example_dataMatrixSerializeDemo_cpp.doxy", "example__dataMatrixSerializeDemo__cpp_8doxy.html", null ],
    [ "example_dataMatrixSerializeDemo_py.doxy", "example__dataMatrixSerializeDemo__py_8doxy.html", null ],
    [ "example_dataVectorSerializeDemo_cpp.doxy", "example__dataVectorSerializeDemo__cpp_8doxy.html", null ],
    [ "example_dataVectorSerializeDemo_py.doxy", "example__dataVectorSerializeDemo__py_8doxy.html", null ],
    [ "example_detectPlatformConfiguration_cpp.doxy", "example__detectPlatformConfiguration__cpp_8doxy.html", null ],
    [ "example_gridInteractionExample_cpp.doxy", "example__gridInteractionExample__cpp_8doxy.html", null ],
    [ "example_gridTExample_cpp.doxy", "example__gridTExample__cpp_8doxy.html", null ],
    [ "example_gridTExample_py.doxy", "example__gridTExample__py_8doxy.html", null ],
    [ "example_json_cpp.doxy", "example__json__cpp_8doxy.html", null ],
    [ "example_predictiveANOVARefinement_py.doxy", "example__predictiveANOVARefinement__py_8doxy.html", null ],
    [ "example_predictiveRefinement_cpp.doxy", "example__predictiveRefinement__cpp_8doxy.html", null ],
    [ "example_predictiveRefinement_py.doxy", "example__predictiveRefinement__py_8doxy.html", null ],
    [ "example_quadrature_cpp.doxy", "example__quadrature__cpp_8doxy.html", null ],
    [ "example_quadrature_py.doxy", "example__quadrature__py_8doxy.html", null ],
    [ "example_refinement_cpp.doxy", "example__refinement__cpp_8doxy.html", null ],
    [ "example_refinement_java.doxy", "example__refinement__java_8doxy.html", null ],
    [ "example_refinement_py.doxy", "example__refinement__py_8doxy.html", null ],
    [ "example_subspaceRefinement_py.doxy", "example__subspaceRefinement__py_8doxy.html", null ],
    [ "example_tutorial_cpp.doxy", "example__tutorial__cpp_8doxy.html", null ],
    [ "example_tutorial_java.doxy", "example__tutorial__java_8doxy.html", null ],
    [ "example_tutorial_m.doxy", "example__tutorial__m_8doxy.html", null ],
    [ "example_tutorial_py.doxy", "example__tutorial__py_8doxy.html", null ],
    [ "example_unserializeGrid_cpp.doxy", "example__unserializeGrid__cpp_8doxy.html", null ],
    [ "examples.doxy", "examples_8doxy.html", null ],
    [ "examples_cpp.doxy", "examples__cpp_8doxy.html", null ],
    [ "examples_java.doxy", "examples__java_8doxy.html", null ],
    [ "examples_m.doxy", "examples__m_8doxy.html", null ],
    [ "examples_py.doxy", "examples__py_8doxy.html", null ],
    [ "GridTypes.doxy", "GridTypes_8doxy.html", null ],
    [ "mainpage.doxy", "mainpage_8doxy.html", null ],
    [ "misc.doxy", "misc_8doxy.html", null ]
];