SG++-Doxygen-Documentation: datadriven/examplesOCL/multTest.cpp File Reference
multTest.cpp File Reference
#include <sgpp/base/grid/generation/functors/SurplusRefinementFunctor.hpp>
#include <sgpp/base/opencl/OCLOperationConfiguration.hpp>
#include <sgpp/base/operation/BaseOpFactory.hpp>
#include <sgpp/base/operation/hash/OperationMultipleEval.hpp>
#include <sgpp/datadriven/DatadrivenOpFactory.hpp>
#include <sgpp/datadriven/operation/hash/DatadrivenOperationCommon.hpp>
#include <sgpp/datadriven/tools/ARFFTools.hpp>
#include <sgpp/globaldef.hpp>
#include <random>
#include <string>
Functions
void doAllRefinements (sgpp::base::AdaptivityConfiguration &adaptivityConfig, sgpp::base::Grid &grid, sgpp::base::GridGenerator &gridGen, sgpp::base::DataVector &alpha)
int main (int argc, char **argv)
Function Documentation
doAllRefinements()
void doAllRefinements (sgpp::base::AdaptivityConfiguration & adaptivityConfig, sgpp::base::Grid & grid, sgpp::base::GridGenerator & gridGen, sgpp::base::DataVector & alpha)
References adaptivityConfig, alpha, sgpp::base::DataVector::getSize(), grid(), sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::GridGenerator::refine(), and sgpp::base::AdaptivityConfiguration::refinementThreshold_.
main()
int main (int argc, char ** argv)
References adaptivityConfig, alpha, sgpp::base::Grid::createLinearGrid(), sgpp::base::Grid::createModLinearGrid(), sgpp::op_factory::createOperationMultipleEval(), dataset, dataSizeVectorResult, doAllRefinements(), fileName, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::base::DataVector::getSize(), grid(), level, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::datadriven::OCLUNIFIED, sgpp::base::AdaptivityConfiguration::percent_, sgpp::datadriven::ARFFTools::readARFFFromFile(), sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::base::GridGenerator::regular(), sgpp::datadriven::STREAMING, and trainingData.