var GaussLegendreQuadrature_8py =
[
    [ "python.uq.quadrature.strategies.GaussLegendreQuadrature.GaussLegendreQuadrature", "classpython_1_1uq_1_1quadrature_1_1strategies_1_1GaussLegendreQuadrature_1_1GaussLegendreQuadrature.html", "classpython_1_1uq_1_1quadrature_1_1strategies_1_1GaussLegendreQuadrature_1_1GaussLegendreQuadrature" ]
];