SG++-Doxygen-Documentation: datadriven/examplesOCL/learner.cpp File Reference
learner.cpp File Reference
#include <sgpp/datadriven/application/MetaLearner.hpp>
#include <sgpp/datadriven/operation/hash/DatadrivenOperationCommon.hpp>
#include <sgpp/globaldef.hpp>
#include <boost/program_options.hpp>
#include <string>
#include <vector>
Namespaces
namespace sgpp
Class that stores, generates and manipulates a density function during online phase in on/off learning.
namespace sgpp::base
namespace sgpp::datadriven
namespace sgpp::solver
Enumerations
enum class sgpp::datadriven::LearnerMode { sgpp::datadriven::LEARN , sgpp::datadriven::LEARNCOMPARE , sgpp::datadriven::LEARNTEST }
Functions
int main (int argc, char *argv[])
void sgpp::base::validate (boost::any &v, const std::vector< std::string > &values, sgpp::base::GridType *target_type, int)
void sgpp::datadriven::validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::LearnerMode *target_type, int)
void sgpp::datadriven::validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::OperationMultipleEvalSubType *target_type, int)
void sgpp::datadriven::validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::OperationMultipleEvalType *target_type, int)
void sgpp::solver::validate (boost::any &v, const std::vector< std::string > &values, sgpp::solver::SLESolverType *target_type, int)
Function Documentation
main()
int main (int argc, char * argv[])
References adaptivityConfig, sgpp::solver::CG, sgpp::datadriven::DEFAULT, sgpp::base::GeneralGridConfiguration::dim_, sgpp::solver::SLESolverConfiguration::eps_, lambda, sgpp::datadriven::LEARN, sgpp::datadriven::MetaLearner::learn(), sgpp::datadriven::MetaLearner::learnAndCompare(), sgpp::datadriven::MetaLearner::learnAndTest(), sgpp::datadriven::LEARNCOMPARE, sgpp::datadriven::LEARNTEST, sgpp::base::GeneralGridConfiguration::level_, sgpp::base::Linear, sgpp::solver::SLESolverConfiguration::maxIterations_, sgpp::base::AdaptivityConfiguration::maxLevelType_, sgpp::base::AdaptivityConfiguration::numRefinementPoints_, sgpp::base::AdaptivityConfiguration::numRefinements_, sgpp::base::AdaptivityConfiguration::percent_, sgpp::base::AdaptivityConfiguration::refinementThreshold_, sgpp::solver::SLESolverConfiguration::threshold_, sgpp::base::GeneralGridConfiguration::type_, and sgpp::solver::SLESolverConfiguration::type_.