var LinearQuadratureStrategy_8py =
[
    [ "python.uq.quadrature.linearform.LinearQuadratureStrategy.LinearQuadratureStrategy", "classpython_1_1uq_1_1quadrature_1_1linearform_1_1LinearQuadratureStrategy_1_1LinearQuadratureStrategy.html", "classpython_1_1uq_1_1quadrature_1_1linearform_1_1LinearQuadratureStrategy_1_1LinearQuadratureStrategy" ]
];