SG++-Doxygen-Documentation: datadriven/examplesOCL/memoryTest.cpp File Reference
memoryTest.cpp File Reference
#include <sgpp/base/opencl/OCLClonedBufferMultiPlatform.hpp>
#include <sgpp/base/opencl/OCLManagerMultiPlatform.hpp>
#include <sgpp/base/opencl/OCLOperationConfiguration.hpp>
#include <sgpp/base/opencl/OCLStretchedBufferMultiPlatform.hpp>
#include <sgpp/base/opencl/OCLClonedBuffer.hpp>
#include <sgpp/base/opencl/OCLManager.hpp>
#include <sgpp/base/opencl/OCLStretchedBuffer.hpp>
#include <iostream>
#include <chrono>
#include <random>
#include <thread>
Functions
void doStuff (std::shared_ptr< sgpp::base::OCLManagerMultiPlatform > manager, double *values, size_t valueSize)
void doStuffOld (std::shared_ptr< sgpp::base::OCLManager > manager, double *values, size_t valueSize)
int main (int argc, char **argv)
Function Documentation
doStuff()
void doStuff (std::shared_ptr< sgpp::base::OCLManagerMultiPlatform > manager, double * values, size_t valueSize)
References sgpp::base::OCLStretchedBufferMultiPlatform::freeBuffer(), and sgpp::base::OCLStretchedBufferMultiPlatform::initializeBuffer().
Referenced by main().
doStuffOld()
void doStuffOld (std::shared_ptr< sgpp::base::OCLManager > manager, double * values, size_t valueSize)
References sgpp::base::OCLStretchedBuffer::initializeBuffer().
main()
int main (int argc, char ** argv)
References doStuff().