SG++-Doxygen-Documentation: datadriven/examplesOCL/multiEvalPerformance.cpp File Reference
multiEvalPerformance.cpp File Reference
#include <sgpp/base/operation/BaseOpFactory.hpp>
#include <sgpp/base/operation/hash/OperationMultipleEval.hpp>
#include <sgpp/datadriven/DatadrivenOpFactory.hpp>
#include <sgpp/datadriven/tools/ARFFTools.hpp>
#include <sgpp/globaldef.hpp>
#include <random>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References alpha, sgpp::base::Grid::createLinearGrid(), sgpp::op_factory::createOperationMultipleEval(), dataset, fileName, sgpp::datadriven::Dataset::getData(), sgpp::datadriven::Dataset::getDimension(), sgpp::datadriven::Dataset::getNumberInstances(), sgpp::base::DataVector::getSize(), grid(), level, sgpp::datadriven::OCL, sgpp::datadriven::ARFFTools::readARFFFromFile(), sgpp::datadriven::STREAMING, and trainingData.