SG++-Doxygen-Documentation: python.uq.tools Namespace Reference
python.uq.tools Namespace Reference
Functions
addValidSequenceNumber (names=None, n=5)
check (n, dim, nmax=50000)
createGrid (dim, level, borderType, isFull=False)
eval_fullGrid (level, dim, border=True)
eval_linear (ppd, dim, norm_offset=0.0)
gzOpen (filename, mode="r")
natural_sort (accLevel)
unique (accLevel)
writeCSV (filename, samples, delim=' ')
writeDataARFF (data, merge=False)
Function Documentation
addValidSequenceNumber()
python.uq.tools.addValidSequenceNumber (names = None, n = 5)
check()
python.uq.tools.check (n, dim, nmax = 50000)
Referenced by python.uq.tools.eval_linear().
createGrid()
python.uq.tools.createGrid (dim, level, borderType, isFull = False)
eval_fullGrid()
python.uq.tools.eval_fullGrid (level, dim, border = True)
eval_linear()
python.uq.tools.eval_linear (ppd, dim, norm_offset = 0.0)
References python.uq.tools.check().
gzOpen()
python.uq.tools.gzOpen (filename, mode = "r")
Referenced by python.uq.tools.writeDataARFF().
natural_sort()
python.uq.tools.natural_sort (accLevel)
unique()
python.uq.tools.unique (accLevel)
writeCSV()
python.uq.tools.writeCSV (filename, samples, delim = ' ')
writeDataARFF()
python.uq.tools.writeDataARFF (data, merge = False)
References python.uq.tools.gzOpen().