SG++-Doxygen-Documentation: python.plotDeltas3d Namespace Reference
python.plotDeltas3d Namespace Reference
Functions
adaptiveGeneratorToDataframe (adaptiveGenerator)
get_projected_cubes_and_colors (dataframe, dim, scalarMap)
plotDeltas3D (dataframe, dim=['l_0', 'l_1', 'l_2'])
quad (plane='xy', origin=None, width=1, height=1, depth=0)
subcube (origin=(0, 0, 0), width=1, height=1, depth=1)
subcube_at (midpoint=(1, 1, 1))
Function Documentation
adaptiveGeneratorToDataframe()
python.plotDeltas3d.adaptiveGeneratorToDataframe (adaptiveGenerator)
Referenced by python.plotDeltas3d.plotDeltas3D().
get_projected_cubes_and_colors()
python.plotDeltas3d.get_projected_cubes_and_colors (dataframe, dim, scalarMap)
References python.plotDeltas3d.subcube_at().
Referenced by python.plotDeltas3d.plotDeltas3D().
plotDeltas3D()
python.plotDeltas3d.plotDeltas3D (dataframe, dim = ['l_0', 'l_1', 'l_2'])
print 3d cube representation of adaptive scheme
expects a pandas dataframe with column 'delta' and level indices 'l_*'
References python.plotDeltas3d.adaptiveGeneratorToDataframe(), python.plotDeltas3d.get_projected_cubes_and_colors(), python.plotDeltas3d.subcube(), and python.plotDeltas3d.subcube_at().
quad()
python.plotDeltas3d.quad (plane = 'xy', origin = None, width = 1, height = 1, depth = 0)
returns a rectangle
subcube()
python.plotDeltas3d.subcube (origin = (0, 0, 0), width = 1, height = 1, depth = 1)
Referenced by python.plotDeltas3d.plotDeltas3D(), and python.plotDeltas3d.subcube_at().
subcube_at()
python.plotDeltas3d.subcube_at (midpoint = (1, 1, 1))
References python.plotDeltas3d.subcube().
Referenced by python.plotDeltas3d.get_projected_cubes_and_colors(), and python.plotDeltas3d.plotDeltas3D().