var namespacepython_1_1uq_1_1sampler_1_1asgc_1_1ASGCSamplerBuilder =
[
    [ "ASGCSamplerBuilder", "classpython_1_1uq_1_1sampler_1_1asgc_1_1ASGCSamplerBuilder_1_1ASGCSamplerBuilder.html", "classpython_1_1uq_1_1sampler_1_1asgc_1_1ASGCSamplerBuilder_1_1ASGCSamplerBuilder" ],
    [ "ASGCSamplerStopPolicyDescriptor", "classpython_1_1uq_1_1sampler_1_1asgc_1_1ASGCSamplerBuilder_1_1ASGCSamplerStopPolicyDescriptor.html", "classpython_1_1uq_1_1sampler_1_1asgc_1_1ASGCSamplerBuilder_1_1ASGCSamplerStopPolicyDescriptor" ]
];