SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOfflineFactory Namespace Reference
sgpp::datadriven::DBMatOfflineFactory Namespace Reference
factories to build the specialization of the DBMatOffline objects.
Functions
DBMatOffline * buildFromFile (const std::string &fname)
Read a serialized DBMatOffline object and construct a new object with the information.
DBMatOffline * buildOfflineObject (const sgpp::base::GeneralGridConfiguration &gridConfig, const sgpp::base::AdaptivityConfiguration &adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration &regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration &densityEstimationConfig)
Based on the configuration file, build the appropriate DBMatOffline object and return it.
Detailed Description
factories to build the specialization of the DBMatOffline objects.
Function Documentation
buildFromFile()
DBMatOffline * sgpp::datadriven::DBMatOfflineFactory::buildFromFile (const std::string & fname)
Read a serialized DBMatOffline object and construct a new object with the information.
Parameters
fname Path to the serialized DBMatOffline object.
Returns
new instance of DBMatOffline implementor owned by caller.
References sgpp::datadriven::Chol, sgpp::datadriven::DenseIchol, sgpp::datadriven::Eigen, fileName, sgpp::datadriven::LU, sgpp::datadriven::OrthoAdapt, sgpp::datadriven::SMW_chol, sgpp::datadriven::SMW_ortho, and sgpp::base::StringTokenizer::tokenize().
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::fit(), and sgpp::datadriven::DBMatPermutationFactory::getPermutedObject().
buildOfflineObject()
DBMatOffline * sgpp::datadriven::DBMatOfflineFactory::buildOfflineObject (const sgpp::base::GeneralGridConfiguration & gridConfig, const sgpp::base::AdaptivityConfiguration & adaptivityConfig, const sgpp::datadriven::RegularizationConfiguration & regularizationConfig, const sgpp::datadriven::DensityEstimationConfiguration & densityEstimationConfig)
Based on the configuration file, build the appropriate DBMatOffline object and return it.
Parameters
gridConfig The configuration of the grid
adaptivityConfig The configuration of the grid adaptivity
regularizationConfig The configuration of the grid regularization
densityEstimationConfig The configuration of the matrix decomposition
Returns
new instance of DBMatOffline implementor owned by caller.
References sgpp::datadriven::Chol, sgpp::datadriven::DensityEstimationConfiguration::decomposition_, sgpp::datadriven::DenseIchol, sgpp::datadriven::Eigen, sgpp::datadriven::LU, sgpp::datadriven::OrthoAdapt, sgpp::datadriven::SMW_chol, and sgpp::datadriven::SMW_ortho.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::fit(), sgpp::datadriven::DBMatPermutationFactory::getPermutedObject(), sgpp::datadriven::LearnerSGDEOnOffParallel::LearnerSGDEOnOffParallel(), and main().