SG++-Doxygen-Documentation: sgpp::combigrid Namespace Reference
sgpp::combigrid Namespace Reference
Classes
class AdaptiveCombinationGridGenerator
The AdaptiveCombinationGridGenerator is a (potentially changing) representation of a combination grid that also tracks the Quantities of Interest; in contrast to a CombinationGrid, it stores the full downward closed set of levels.
class AveragingPriorityEstimator
the AveragingLevelManager from holzmudd's combigrid module: The priority returned is the average of delta divided by the number of grid points (as a measure for work intensity) over all the predecessor grids.
class CombinationGrid
Class for representing a collection of full grids together with one scalar coefficient per full grid.
class FullGrid
Full grid essentially represented by its level and a HeterogeneousBasis.
class HeterogeneousBasis
Potentially hetereogeneous basis on full grids, i.e., a dim-dimensional vector of 1D bases of type sgpp::base::Basis.
class IndexVectorIterator
Iterator over the indices contained in a FullGrid.
class IndexVectorRange
Class for iterating over the indices contained in a FullGrid via ranged-based for loops.
class LevelVectorTools
Various tools for LevelVectors, mainly for generating specific vectors of LevelVectors.
class OperationEvalCombinationGrid
Operation for evaluating a combination grid function (linear combination of linear combinations of full grid basis functions, where the coefficients of the outer linear combination are given by the combination grid).
class OperationEvalFullGrid
Operation for evaluating a full grid function (linear combination of full grid basis functions).
class OperationPole
Operation on a pole of a full grid.
class OperationPoleDehierarchisationLinear
Operation of dehierarchising values on a 1D pole of a full grid with linear basis functions.
class OperationPoleHierarchisationGeneral
Operation of hierarchising values on a 1D pole of a full grid with general basis functions by solving a linear system.
class OperationPoleHierarchisationLinear
Operation of hierarchising values on a 1D pole of a full grid with linear basis functions.
class OperationPoleNodalisationBspline
Operation of nodalising values on a 1D pole of a full grid with B-spline basis functions.
class OperationPoleNodalisationLinear
Operation of nodalising values on a 1D pole of a full grid with linear basis functions.
class OperationUPCombinationGrid
Operation for applying 1D OperationPole operators on all poles of all full grids of some combination grid, in all dimensions via the unidirectional principle (UP).
class OperationUPFullGrid
Operation for applying 1D OperationPole operators on all poles of a full grid in all dimensions via the unidirectional principle (UP).
class PriorityEstimator
a generic priority estimator for level vectors that don't have a definite result / QoI yet
class RelevanceCalculator
a generic relevance calculator for dimensionally-adaptive combination technique
class WeightedRelevanceCalculator
the weighted relevance calculator introduced in [0]
Typedefs
typedef std::vector< index_t > IndexVector
index multi-index
typedef std::vector< level_t > LevelVector
level multi-index
Functions
base::DataVector getStandardCoefficientsFromLevelSet (const std::vector< LevelVector > &levelSet)
Typedef Documentation
IndexVector
typedef std::vector<index_t> sgpp::combigrid::IndexVector
index multi-index
LevelVector
typedef std::vector<level_t> sgpp::combigrid::LevelVector
level multi-index
Function Documentation
getStandardCoefficientsFromLevelSet()
base::DataVector sgpp::combigrid::getStandardCoefficientsFromLevelSet (const std::vector< LevelVector > & levelSet)
References level.
Referenced by sgpp::combigrid::CombinationGrid::fromSubspaces(), sgpp::combigrid::AdaptiveCombinationGridGenerator::getCombinationGrid(), and sgpp::combigrid::AdaptiveCombinationGridGenerator::getCurrentResult().