SG++-Doxygen-Documentation: python.uq.plot.plot2d Namespace Reference
python.uq.plot.plot2d Namespace Reference
Functions
addContours (xv, yv, Z, levels=None, clabels=None, manual_locations=None)
plotDensity2d (U, n=50, addContour=True, color_bar_label=r '$\hat{f}(\xi_1, \xi_2) $', levels=None, clabels=None, manual_locations=None)
plotFunction2d (f, addContour=True, n=101, xlim=[0, 1], ylim=[0, 1], color_bar_label=r ' $u(\xi_1, \xi_2) $', levels=None, clabels=None, manual_locations=None)
plotGrid2d (grid, alpha=None, show_numbers=True, xlim=(0, 1), ylim=(0, 1), *args, **kws)
plotSamples2d (samples)
plotScatter2d (samples, values, bounds=None, color_bar_label=r"$u(x)$")
plotSG2d (grid, alpha, addContour=True, n=100, show_negative=False, show_grid_points=False, show_numbers=False, colorbarLabel=r"$\hat{f}_{\mathcal{I}}(\xi)$", levels=None, clabels=None, manual_locations=None)
plotSGDE2d (U, n=100)
plotTimedependentDensity2d (Us, us, ts, addContour=True, color_bar_label=r '$\hat{F}(\xi_1, \xi_2) $', levels=None, clabels=None, manual_locations=None)
plotTimedependentDensity2dWithRawData (xv, yv, Z, ts, us, addContour=True, color_bar_label=r '$\hat{F}(\xi_1, \xi_2) $', levels=None, clabels=None, manual_locations=None)
Function Documentation
addContours()
python.uq.plot.plot2d.addContours (xv, yv, Z, levels = None, clabels = None, manual_locations = None)
Referenced by python.uq.plot.plot2d.plotDensity2d(), python.uq.plot.plot2d.plotFunction2d(), python.uq.plot.plot2d.plotSG2d(), python.uq.plot.plot2d.plotTimedependentDensity2d(), and python.uq.plot.plot2d.plotTimedependentDensity2dWithRawData().
plotDensity2d()
python.uq.plot.plot2d.plotDensity2d (U, n = 50, addContour = True, color_bar_label = r'$\hat{f}(\xi_1, \xi_2)$', levels = None, clabels = None, manual_locations = None)
References python.uq.plot.plot2d.addContours().
plotFunction2d()
python.uq.plot.plot2d.plotFunction2d (f, addContour = True, n = 101, xlim = [0, 1], ylim = [0, 1], color_bar_label = r'$u(\xi_1, \xi_2)$', levels = None, clabels = None, manual_locations = None)
References python.uq.plot.plot2d.addContours(), and f.
plotGrid2d()
python.uq.plot.plot2d.plotGrid2d (grid, alpha = None, show_numbers = True, xlim = (0, 1), ylim = (0, 1), * args, ** kws)
plotSamples2d()
python.uq.plot.plot2d.plotSamples2d (samples)
plotScatter2d()
python.uq.plot.plot2d.plotScatter2d (samples, values, bounds = None, color_bar_label = r"$u(x)$")
plotSG2d()
python.uq.plot.plot2d.plotSG2d (grid, alpha, addContour = True, n = 100, show_negative = False, show_grid_points = False, show_numbers = False, colorbarLabel = r"$\hat{f}_{\mathcal{I}}(\xi)$", levels = None, clabels = None, manual_locations = None)
References python.uq.plot.plot2d.addContours().
plotSGDE2d()
python.uq.plot.plot2d.plotSGDE2d (U, n = 100)
plotTimedependentDensity2d()
python.uq.plot.plot2d.plotTimedependentDensity2d (Us, us, ts, addContour = True, color_bar_label = r'$\hat{F}(\xi_1, \xi_2)$', levels = None, clabels = None, manual_locations = None)
References python.uq.plot.plot2d.addContours().
plotTimedependentDensity2dWithRawData()
python.uq.plot.plot2d.plotTimedependentDensity2dWithRawData (xv, yv, Z, ts, us, addContour = True, color_bar_label = r'$\hat{F}(\xi_1, \xi_2)$', levels = None, clabels = None, manual_locations = None)
References python.uq.plot.plot2d.addContours().