SG++-Doxygen-Documentation: sgpp::datadriven::DBMatOnlineDEFactory Namespace Reference
sgpp::datadriven::DBMatOnlineDEFactory Namespace Reference
Functions
DBMatOnlineDE * buildDBMatOnlineDE (DBMatOffline &offline, Grid &grid, double lambda, double beta=0, MatrixDecompositionType matDecompType=MatrixDecompositionType::Chol)
Factory to build a DBMatOnlineDE object to manipulate the decomposition in offline object.
Function Documentation
buildDBMatOnlineDE()
DBMatOnlineDE * sgpp::datadriven::DBMatOnlineDEFactory::buildDBMatOnlineDE (DBMatOffline & offline, Grid & grid, double lambda, double beta = 0, MatrixDecompositionType matDecompType = MatrixDecompositionType::Chol)
Factory to build a DBMatOnlineDE object to manipulate the decomposition in offline object.
Parameters
offline offline object that holds the decomposed system matrix
grid the underlying grid
lambda regularization strength (todo(fuchsgruber): maybe remove this)
beta plasticity weighting factor. If set to 0, no plasticity takes place.
matDecompType the matrix decomposition type of the online matrix
References sgpp::datadriven::Chol, sgpp::datadriven::DenseIchol, sgpp::datadriven::Eigen, grid(), lambda, sgpp::datadriven::LU, sgpp::datadriven::OrthoAdapt, sgpp::datadriven::SMW_chol, and sgpp::datadriven::SMW_ortho.
Referenced by sgpp::datadriven::ModelFittingDensityEstimationOnOff::fit(), sgpp::datadriven::ModelFittingDensityEstimationOnOffParallel::fit(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationOnOff::fit(), and sgpp::datadriven::LearnerSGDEOnOffParallel::LearnerSGDEOnOffParallel().