SG++-Doxygen-Documentation: python.painlesscg Namespace Reference
python.painlesscg Namespace Reference
Functions
ApplyA (B, C, alpha, result, x, l)
BiCGStab (b, alpha, imax, epsilon, ApplyMatrix, verbose=True)
cg (y, alpha, grid, x, imax, epsilon, l, verbose=True)
cg_new (b, alpha, imax, epsilon, ApplyMatrix, reuse=False, verbose=True, max_threshold=None)
Conjugated Gradient method for sparse grids, solving A.alpha=b.
sd (y, alpha, grid, x, imax, epsilon, l)
Function Documentation
ApplyA()
python.painlesscg.ApplyA (B, C, alpha, result, x, l)
Referenced by python.painlesscg.cg(), and python.painlesscg.sd().
BiCGStab()
python.painlesscg.BiCGStab (b, alpha, imax, epsilon, ApplyMatrix, verbose = True)
cg()
python.painlesscg.cg (y, alpha, grid, x, imax, epsilon, l, verbose = True)
References python.painlesscg.ApplyA().
cg_new()
python.painlesscg.cg_new (b, alpha, imax, epsilon, ApplyMatrix, reuse = False, verbose = True, max_threshold = None)
Conjugated Gradient method for sparse grids, solving A.alpha=b.
The resulting vector is stored in alpha.
Parameters
b RHS of equation
alpha vector of unknowns
imax max. number of iterations (abort, if reached)
epsilon accuracy requirements (reduce initial norm of residuum |delta_0| below epsilon*|delta_0|)
ApplyMatrix procedure that applies A to a vector
reuse starting vector is 0 by default. If true, use current values in alpha
verbose verbose output (default False)
max_threshold maximal threshold
Returns
tuple (number of iterations, final norm of residuum)
sd()
python.painlesscg.sd (y, alpha, grid, x, imax, epsilon, l)
References python.painlesscg.ApplyA().