SG++-Doxygen-Documentation: sgpp::op_factory Namespace Reference
sgpp::op_factory Namespace Reference
Functions
base::OperationHierarchisation * createOperationArbitraryBoundaryHierarchisation (base::Grid &grid)
Factory method, returning an OperationArbitraryBoundaryHierarchisation for the grid at hand.
base::OperationConvert * createOperationConvert (base::Grid &grid)
Factory method, returning an OperationConvert for the grid at hand.
datadriven::OperationCovariance * createOperationCovariance (base::Grid &grid)
Factory method, returning an OperationCovariance for the grid at hand.
datadriven::OperationDensityConditional * createOperationDensityConditional (base::Grid &grid)
Factory method, returning an OperationDensityConditional for the grid.
datadriven::OperationDensityConditionalKDE * createOperationDensityConditionalKDE (datadriven::KernelDensityEstimator &kde)
Factory method, returning an OperationDensityConditionalKDE for the kernel density.
datadriven::OperationDensityMarginalize * createOperationDensityMarginalize (base::Grid &grid)
Factory method, returning an OperationDensityMarginalize for the grid.
datadriven::OperationDensityMarginalizeKDE * createOperationDensityMarginalizeKDE (datadriven::KernelDensityEstimator &kde)
Factory method, returning an OperationDensityMarginalizeKDE for the kernel density.
datadriven::OperationDensityMargTo1D * createOperationDensityMargTo1D (base::Grid &grid)
Factory method, returning an OperationDensityMargTo1D for the grid.
datadriven::OperationDensityRejectionSampling * createOperationDensityRejectionSampling (base::Grid &grid)
Factory method, returning an OperationDensityRejectionSampling for the grid.
datadriven::OperationDensitySampling * createOperationDensitySampling (base::Grid &grid)
Factory method, returning an OperationDensitySampling for the grid.
datadriven::OperationDensitySampling1D * createOperationDensitySampling1D (base::Grid &grid)
Factory method, returning an OperationDensitySampling1D for the grid.
base::OperationMatrix * createOperationDiagonal (base::Grid &grid, double multiplicationFactor=0.25)
Factory method, returning an OperationDiagonal (OperationMatrix) for the grid at hand.
base::OperationEval * createOperationEval (base::Grid &grid)
Factory method, returning an OperationEval for the grid at hand.
base::OperationEvalGradient * createOperationEvalGradientNaive (base::Grid &grid)
Factory method, returning an OperationEvalGradient for the grid at hand.
base::OperationEvalHessian * createOperationEvalHessianNaive (base::Grid &grid)
Factory method, returning an OperationEvalHessian for the grid at hand.
base::OperationEval * createOperationEvalNaive (base::Grid &grid)
Factory method, returning an OperationEval for the grid at hand.
base::OperationEvalPartialDerivative * createOperationEvalPartialDerivativeNaive (base::Grid &grid)
Factory method, returning an OperationEvalPartialDerivative for the grid at hand.
base::OperationFirstMoment * createOperationFirstMoment (base::Grid &grid)
Factory method, returning an OperationFirstMoment for the grid at hand.
base::OperationHierarchisation * createOperationHierarchisation (base::Grid &grid)
Factory method, returning an OperationHierarchisation for the grid at hand.
base::OperationMatrix * createOperationIdentity (base::Grid &grid)
Factory method, returning an OperationIdentity for the grid at hand.
datadriven::OperationInverseRosenblattTransformation * createOperationInverseRosenblattTransformation (base::Grid &grid)
Factory method, returning an OperationInverseRosenblattTransformation for the grid.
datadriven::OperationTransformation1D * createOperationInverseRosenblattTransformation1D (base::Grid &grid)
Factory method, returning an OperationInverseRosenblattTransformation1D for the grid.
datadriven::OperationInverseRosenblattTransformationKDE * createOperationInverseRosenblattTransformationKDE (datadriven::KernelDensityEstimator &kde)
Factory method, returning an OperationInverseRosenblattTransformationKDE for the kde.
base::OperationMatrix * createOperationLaplace (base::Grid &grid)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLaplace (base::Grid &grid, sgpp::base::DataVector &coef)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLaplaceEnhanced (base::Grid &grid)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLaplaceEnhanced (base::Grid &grid, sgpp::base::DataVector &coef)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLaplaceExplicit (base::DataMatrix *m, base::Grid &grid)
Factory method, returning an OperationLaplaceExplicit (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLaplaceExplicit (base::Grid &grid)
Factory method, returning an OperationLaplaceExplicit (OperationMatrix) for the grid at hand.
datadriven::OperationLimitFunctionValueRange * createOperationLimitFunctionValueRange (datadriven::MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm=datadriven::MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm=datadriven::MakePositiveInterpolationAlgorithm::SetToZero, sgpp::base::ScalarFunction *f=nullptr)
Factory method, returning an OperationLimitFunctionValueRange for an arbitrary function f or some sparse grid, which is yet to be defined.
base::OperationMatrix * createOperationLTwoDotExplicit (base::DataMatrix *m, base::Grid &grid)
Factory method, returning an OperationLTwoDotExplicit (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLTwoDotExplicit (base::Grid &grid)
Factory method, returning an OperationLTwoDotExplicit (OperationMatrix) for the grid at hand.
base::OperationMatrix * createOperationLTwoDotProduct (base::Grid &grid)
Factory method, returning an OperationLTwoDotProduct (OperationMatrix) for the grid at hand.
datadriven::OperationMakePositive * createOperationMakePositive (datadriven::MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm=datadriven::MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm=datadriven::MakePositiveInterpolationAlgorithm::SetToZero, bool generateConsistentGrid=true, sgpp::base::ScalarFunction *f=nullptr)
Factory method, returning an OperationMakePositive for an arbitrary function f or some sparse grid, which is yet to be defined.
base::OperationMultipleEval * createOperationMultipleEval (base::Grid &grid, base::DataMatrix &dataset)
Factory method, returning an OperationMultipleEval for the grid at hand.
base::OperationMultipleEval * createOperationMultipleEval (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
Factory method, returning an OperationMultipleEval for the grid.
base::OperationMultipleEval * createOperationMultipleEvalInter (base::Grid &grid, base::DataMatrix &dataset, std::set< std::set< size_t > > interactions)
Similar to createOperationMultipleEval, but makes use of interaction terms during evaluation.
base::OperationMultipleEval * createOperationMultipleEvalNaive (base::Grid &grid, base::DataMatrix &dataset)
Factory method, returning an OperationMultipleEvalNaive for the grid at hand.
optimization::OperationMultipleHierarchisation * createOperationMultipleHierarchisation (base::Grid &grid)
Creates a OperationMultipleHierarchisation for the given sgpp::optimization grid.
base::OperationQuadrature * createOperationQuadrature (base::Grid &grid)
Factory method, returning an OperationQuadrature for the grid at hand.
quadrature::OperationQuadratureMCAdvanced * createOperationQuadratureMCAdvanced (base::Grid &grid, size_t numberOfSamples, std::uint64_t seed=std::mt19937_64::default_seed)
Creates an OperationQuadratureMCAdvanced.
base::OperationMatrix * createOperationRegularizationDiagonal (base::Grid &grid, int mode, double k)
Factory method, returning an OperationRegularizationDiagonal for the grid at hand.
datadriven::OperationRosenblattTransformation * createOperationRosenblattTransformation (base::Grid &grid)
Factory method, returning an OperationRosenblattTransformation for the grid.
datadriven::OperationTransformation1D * createOperationRosenblattTransformation1D (base::Grid &grid)
Factory method, returning an OperationRosenblattTransformation for the grid.
datadriven::OperationRosenblattTransformationKDE * createOperationRosenblattTransformationKDE (datadriven::KernelDensityEstimator &kde)
Factory method, returning an OperationRosenblattTransformationKDE for the kde.
base::OperationSecondMoment * createOperationSecondMoment (base::Grid &grid)
Factory method, returning an OperationSecondMoment for the grid at hand.
datadriven::OperationTest * createOperationTest (base::Grid &grid)
Factory method, returning an OperationTest for the grid at hand.
base::OperationWeightedQuadrature * createOperationWeightedQuadrature (base::Grid &grid, size_t quadOrder)
Factory method, returning an OperationWeightedQuadrature for the grid at hand.
base::OperationWeightedSecondMoment * createOperationWeightedSecondMoment (base::Grid &grid, size_t quadOrder)
Factory method, returning an OperationWeightedSecondMoment for the grid at hand.
Function Documentation
createOperationArbitraryBoundaryHierarchisation()
base::OperationHierarchisation * sgpp::op_factory::createOperationArbitraryBoundaryHierarchisation (base::Grid & grid)
Factory method, returning an OperationArbitraryBoundaryHierarchisation for the grid at hand.
Note: object has to be freed after use. This operation should be used if the boundary level of your grid is larger than 1.
Parameters
grid Grid which is to be used for hierarchisation
Returns
Pointer to the new OperationArbitraryBoundaryHierarchisation object for the Grid grid
References createOperationArbitraryBoundaryHierarchisation(), and grid().
Referenced by createOperationArbitraryBoundaryHierarchisation().
createOperationConvert()
base::OperationConvert * sgpp::op_factory::createOperationConvert (base::Grid & grid)
Factory method, returning an OperationConvert for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for conversion
Returns
Pointer to the new OperationConvert object for the Grid grid
References sgpp::base::PrewaveletGrid::getShadowStorage(), grid(), and sgpp::base::Prewavelet.
createOperationCovariance()
datadriven::OperationCovariance * sgpp::op_factory::createOperationCovariance (base::Grid & grid)
Factory method, returning an OperationCovariance for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationCovariance object for the Grid grid
References grid().
Referenced by sgpp::datadriven::LearnerSGDE::cov(), and sgpp::datadriven::SparseGridDensityEstimator::cov().
createOperationDensityConditional()
datadriven::OperationDensityConditional * sgpp::op_factory::createOperationDensityConditional (base::Grid & grid)
Factory method, returning an OperationDensityConditional for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensityConditional for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), and sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim().
createOperationDensityConditionalKDE()
datadriven::OperationDensityConditionalKDE * sgpp::op_factory::createOperationDensityConditionalKDE (datadriven::KernelDensityEstimator & kde)
Factory method, returning an OperationDensityConditionalKDE for the kernel density.
Parameters
kde kernel density which is to be used for the operation
Returns
Pointer to new OperationDensityConditionalKDE
createOperationDensityMarginalize()
datadriven::OperationDensityMarginalize * sgpp::op_factory::createOperationDensityMarginalize (base::Grid & grid)
Factory method, returning an OperationDensityMarginalize for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensityMarginalize for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by sgpp::datadriven::OperationDensityMargTo1D::marg_next_dim(), and sgpp::datadriven::SparseGridDensityEstimator::marginalize().
createOperationDensityMarginalizeKDE()
datadriven::OperationDensityMarginalizeKDE * sgpp::op_factory::createOperationDensityMarginalizeKDE (datadriven::KernelDensityEstimator & kde)
Factory method, returning an OperationDensityMarginalizeKDE for the kernel density.
Parameters
kde kernel density which is to be used for the operation
Returns
Pointer to new OperationDensityMarginalizeKDE
References createOperationDensityMarginalizeKDE().
Referenced by sgpp::datadriven::OperationDensityConditionalKDE::condToDimX(), sgpp::datadriven::KernelDensityEstimator::cov(), createOperationDensityMarginalizeKDE(), sgpp::datadriven::OperationDensityConditionalKDE::doConditional(), sgpp::datadriven::KernelDensityEstimator::marginalize(), and sgpp::datadriven::KernelDensityEstimator::margToDimX().
createOperationDensityMargTo1D()
datadriven::OperationDensityMargTo1D * sgpp::op_factory::createOperationDensityMargTo1D (base::Grid & grid)
Factory method, returning an OperationDensityMargTo1D for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensityMarginalize for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationDensityMargTo1D(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationDensityMargTo1D(), sgpp::datadriven::OperationCovariance::doQuadrature(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation_in_next_dim(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation_in_next_dim(), and sgpp::datadriven::SparseGridDensityEstimator::margToDimX().
createOperationDensityRejectionSampling()
datadriven::OperationDensityRejectionSampling * sgpp::op_factory::createOperationDensityRejectionSampling (base::Grid & grid)
Factory method, returning an OperationDensityRejectionSampling for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensitySampling1D for the Grid grid
References grid(), and sgpp::base::Linear.
createOperationDensitySampling()
datadriven::OperationDensitySampling * sgpp::op_factory::createOperationDensitySampling (base::Grid & grid)
Factory method, returning an OperationDensitySampling for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensitySampling1D for the Grid grid
References grid(), and sgpp::base::Linear.
createOperationDensitySampling1D()
datadriven::OperationDensitySampling1D * sgpp::op_factory::createOperationDensitySampling1D (base::Grid & grid)
Factory method, returning an OperationDensitySampling1D for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationDensitySampling1D for the Grid grid
References grid(), and sgpp::base::Linear.
Referenced by sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySamplingLinear::doSampling(), and sgpp::datadriven::OperationDensitySamplingLinear::doSampling_in_next_dim().
createOperationDiagonal()
base::OperationMatrix * sgpp::op_factory::createOperationDiagonal (base::Grid & grid, double multiplicationFactor = 0.25)
Factory method, returning an OperationDiagonal (OperationMatrix) for the grid at hand.
Parameters
grid Grid which is to be used
multiplicationFactor MultiplicationFactor which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References grid().
createOperationEval()
base::OperationEval * sgpp::op_factory::createOperationEval (base::Grid & grid)
Factory method, returning an OperationEval for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationEval object for the Grid grid
References createOperationEval(), sgpp::base::ModPolyGrid::getDegree(), sgpp::base::PolyBoundaryGrid::getDegree(), sgpp::base::PolyGrid::getDegree(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::Prewavelet, and sgpp::base::SquareRoot.
Referenced by createOperationEval(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostR2(), sgpp::datadriven::AlgorithmAdaBoostBase::doAdaBoostRT(), sgpp::datadriven::AlgorithmAdaBoostBase::doDiscreteAdaBoost(), sgpp::base::OperationQuadratureMC::doQuadratureL2Error(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadratureL2Error(), sgpp::datadriven::AlgorithmAdaBoostBase::doRealAdaBoost(), sgpp::datadriven::OperationDensityRejectionSamplingLinear::doSampling(), sgpp::datadriven::OperationDensitySampling1DLinear::doSampling1D(), sgpp::datadriven::OperationInverseRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationLinear::doTransformation1D(), sgpp::datadriven::DBMatOnlineDE::eval(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::evaluate(), sgpp::datadriven::ModelFittingDensityEstimationCG::evaluate(), sgpp::datadriven::ModelFittingDensityRatioEstimation::evaluate(), sgpp::datadriven::ModelFittingLeastSquares::evaluate(), sgpp::pde::PDESolver::evaluatePoint(), sgpp::datadriven::ZeroCrossingRefinementFunctor::getEvalVector(), sgpp::datadriven::RefinementHandler::handleSurplusBasedRefinement(), sgpp::base::MultipleClassPoint::MultipleClassPoint(), sgpp::datadriven::GridPointBasedRefinementFunctor::operator()(), sgpp::datadriven::LearnerSGDE::pdf(), sgpp::datadriven::SparseGridDensityEstimator::pdf(), sgpp::datadriven::GridPointBasedRefinementFunctor::preComputeEvaluations(), sgpp::datadriven::ZeroCrossingRefinementFunctor::preComputeEvaluations(), sgpp::datadriven::LearnerSGDE::predict(), sgpp::base::GridPrinter::printGrid(), sgpp::base::GridPrinterForStretching::printGrid(), sgpp::base::GridPrinter::printGridDomain(), sgpp::base::GridPrinterForStretching::printGridDomainStretching(), sgpp::datadriven::LearnerSGD::storeResults(), sgpp::datadriven::LearnerSGDE::storeResults(), sgpp::datadriven::SparseGridDensityEstimator::train(), sgpp::datadriven::LearnerSGDE::train(), and sgpp::datadriven::LearnerSGDE::trainOnline().
createOperationEvalGradientNaive()
base::OperationEvalGradient * sgpp::op_factory::createOperationEvalGradientNaive (base::Grid & grid)
Factory method, returning an OperationEvalGradient for the grid at hand.
Implementations of OperationEvalGradientNaive returned by this function should use a "naive" method for evaluating sparse grid function gradients, e.g. evaluate all basis functions by brute force. Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationEvalGradient object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::BsplineBoundaryGrid::getDegree(), sgpp::base::BsplineClenshawCurtisGrid::getDegree(), sgpp::base::BsplineGrid::getDegree(), sgpp::base::FundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineGrid::getDegree(), sgpp::base::ModBsplineClenshawCurtisGrid::getDegree(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModFundamentalSplineGrid::getDegree(), sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::ModWeaklyFundamentalNakSplineGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::NakBsplineExtendedGrid::getDegree(), sgpp::base::NakBsplineGrid::getDegree(), sgpp::base::NakPBsplineGrid::getDegree(), sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::WeaklyFundamentalSplineBoundaryGrid::getDegree(), grid(), sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
createOperationEvalHessianNaive()
base::OperationEvalHessian * sgpp::op_factory::createOperationEvalHessianNaive (base::Grid & grid)
Factory method, returning an OperationEvalHessian for the grid at hand.
Implementations of OperationEvalHessianNaive returned by this function should use a "naive" method for evaluating sparse grid function Hessians, e.g. evaluate all basis functions by brute force. Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationEvalHessian object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::BsplineBoundaryGrid::getDegree(), sgpp::base::BsplineClenshawCurtisGrid::getDegree(), sgpp::base::BsplineGrid::getDegree(), sgpp::base::FundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineGrid::getDegree(), sgpp::base::ModBsplineClenshawCurtisGrid::getDegree(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModFundamentalSplineGrid::getDegree(), sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::ModWeaklyFundamentalNakSplineGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::WeaklyFundamentalSplineBoundaryGrid::getDegree(), grid(), sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBsplineBoundary, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
createOperationEvalNaive()
base::OperationEval * sgpp::op_factory::createOperationEvalNaive (base::Grid & grid)
Factory method, returning an OperationEval for the grid at hand.
In contrast to OperationEval, implementations of OperationEval returned by this function should use a "naive" method for evaluating sparse grid functions, e.g. evaluate all basis functions by brute force. Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationEval object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationEvalNaive(), sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::BsplineBoundaryGrid::getDegree(), sgpp::base::BsplineClenshawCurtisGrid::getDegree(), sgpp::base::BsplineGrid::getDegree(), sgpp::base::FundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineGrid::getDegree(), sgpp::base::ModBsplineClenshawCurtisGrid::getDegree(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModFundamentalSplineGrid::getDegree(), sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::ModPolyClenshawCurtisGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::NakBsplineExtendedGrid::getDegree(), sgpp::base::NakBsplineGrid::getDegree(), sgpp::base::NakPBsplineGrid::getDegree(), sgpp::base::NaturalBsplineBoundaryGrid::getDegree(), sgpp::base::PolyClenshawCurtisGrid::getDegree(), sgpp::base::WeaklyFundamentalSplineBoundaryGrid::getDegree(), sgpp::base::ModPolyGrid::getDegree(), sgpp::base::PolyBoundaryGrid::getDegree(), sgpp::base::PolyClenshawCurtisBoundaryGrid::getDegree(), sgpp::base::PolyGrid::getDegree(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::NaturalBsplineBoundary, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
Referenced by sgpp::datadriven::OperationMakePositiveSetToZero::computeHierarchicalCoefficients(), sgpp::datadriven::OperationMakePositiveInterpolateExp::computeHierarchicalCoefficients(), sgpp::datadriven::OperationMakePositiveInterpolateBoundaryOfSupport::computeHierarchicalCoefficients(), sgpp::datadriven::OperationMakePositiveInterpolateFunction::computeHierarchicalCoefficients(), createOperationEvalNaive(), sgpp::datadriven::OperationRosenblattTransformation1DBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformation1DPolyClenshawCurtisBoundary::doTransformation1D(), and sgpp::datadriven::OperationMakePositiveHybridFindIntersectionCandidates::findIntersections().
createOperationEvalPartialDerivativeNaive()
base::OperationEvalPartialDerivative * sgpp::op_factory::createOperationEvalPartialDerivativeNaive (base::Grid & grid)
Factory method, returning an OperationEvalPartialDerivative for the grid at hand.
Implementations of OperationEvalPartialDerivativeNaive returned by this function should use a "naive" method for evaluating sparse grid function partial derivatives, e.g. evaluate all basis functions by brute force. Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationEvalPartialDerivative object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::BsplineBoundaryGrid::getDegree(), sgpp::base::BsplineClenshawCurtisGrid::getDegree(), sgpp::base::BsplineGrid::getDegree(), sgpp::base::FundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineBoundaryGrid::getDegree(), sgpp::base::FundamentalSplineGrid::getDegree(), sgpp::base::ModBsplineClenshawCurtisGrid::getDegree(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModFundamentalSplineGrid::getDegree(), sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::ModWeaklyFundamentalNakSplineGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::WeaklyFundamentalNakSplineBoundaryGrid::getDegree(), sgpp::base::WeaklyFundamentalSplineBoundaryGrid::getDegree(), grid(), sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModNakBspline, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBsplineBoundary, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
createOperationFirstMoment()
base::OperationFirstMoment * sgpp::op_factory::createOperationFirstMoment (base::Grid & grid)
Factory method, returning an OperationFirstMoment for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for quadrature
Returns
Pointer to the new OperationFirstMoment for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationFirstMoment(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationFirstMoment(), sgpp::datadriven::LearnerSGDE::mean(), sgpp::datadriven::SparseGridDensityEstimator::mean(), and sgpp::datadriven::SparseGridDensityEstimator::variance().
createOperationHierarchisation()
base::OperationHierarchisation * sgpp::op_factory::createOperationHierarchisation (base::Grid & grid)
Factory method, returning an OperationHierarchisation for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for hierarchisation
Returns
Pointer to the new OperationHierarchisation object for the Grid grid
References createOperationHierarchisation(), sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, sgpp::base::ModPolyClenshawCurtisGrid::getDegree(), sgpp::base::PolyClenshawCurtisGrid::getDegree(), sgpp::base::ModPolyGrid::getDegree(), sgpp::base::PolyBoundaryGrid::getDegree(), sgpp::base::PolyClenshawCurtisBoundaryGrid::getDegree(), sgpp::base::PolyGrid::getDegree(), sgpp::base::PrewaveletGrid::getShadowStorage(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStencil, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModLinearStencil, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, sgpp::base::Prewavelet, and sgpp::base::SquareRoot.
Referenced by sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted(), createOperationHierarchisation(), sgpp::base::OperationArbitraryBoundaryHierarchisation::doHierarchisation(), sgpp::solver::OperationParabolicPDESolverSystem::getGridCoefficientsForSC(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeat(), sgpp::pde::PoissonEquationSolver::initGridWithExpHeatFullDomain(), sgpp::pde::HeatEquationSolver::initGridWithSmoothHeat(), sgpp::pde::HeatEquationSolverWithStretching::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeat(), sgpp::pde::PoissonEquationSolver::initGridWithSmoothHeatFullDomain(), sgpp::datadriven::OperationMakePositive::makeCurrentNodalValuesPositive(), sgpp::base::GridPrinter::printSparseGrid(), sgpp::base::GridPrinterForStretching::printSparseGrid(), sgpp::base::GridPrinter::printSparseGridExpTransform(), sgpp::base::GridPrinterForStretching::printSparseGridExpTransform(), and sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature().
createOperationIdentity()
base::OperationMatrix * sgpp::op_factory::createOperationIdentity (base::Grid & grid)
Factory method, returning an OperationIdentity for the grid at hand.
Note: object has to be freed after use. Just calls OperationIdentity() independent of grid; factory method provided for uniform use.
Returns
Pointer to the new OperationIdentity object
References createOperationIdentity().
Referenced by sgpp::datadriven::AlgorithmAdaBoostIdentity::alphaSolver(), sgpp::datadriven::LearnerSGDE::computeRegularizationMatrix(), sgpp::datadriven::SparseGridDensityEstimator::computeRegularizationMatrix(), sgpp::datadriven::Learner::createDMSystem(), createOperationIdentity(), and sgpp::datadriven::DBMatOnlineDE::resDensity().
createOperationInverseRosenblattTransformation()
datadriven::OperationInverseRosenblattTransformation * sgpp::op_factory::createOperationInverseRosenblattTransformation (base::Grid & grid)
Factory method, returning an OperationInverseRosenblattTransformation for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationInverseRosenblattTransformation for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationInverseRosenblattTransformation(), grid(), sgpp::base::Linear, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationInverseRosenblattTransformation(), and sgpp::datadriven::RosenblattTransformation::doInverseTransformation().
createOperationInverseRosenblattTransformation1D()
datadriven::OperationTransformation1D * sgpp::op_factory::createOperationInverseRosenblattTransformation1D (base::Grid & grid)
Factory method, returning an OperationInverseRosenblattTransformation1D for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationInverseRosenblattTransformation1D for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationInverseRosenblattTransformation1D(), grid(), sgpp::base::Linear, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationInverseRosenblattTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationBspline::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationModBspline::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationModPoly::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationPoly::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation1D().
createOperationInverseRosenblattTransformationKDE()
datadriven::OperationInverseRosenblattTransformationKDE * sgpp::op_factory::createOperationInverseRosenblattTransformationKDE (datadriven::KernelDensityEstimator & kde)
Factory method, returning an OperationInverseRosenblattTransformationKDE for the kde.
Parameters
kde KernelDensityEstimator for which the inverse Rosenblatt transformation should be computed
Returns
Pointer to new OperationInverseRosenblattTransformationKDE for the kde
References createOperationInverseRosenblattTransformationKDE().
Referenced by createOperationInverseRosenblattTransformationKDE().
createOperationLaplace() [1/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplace (base::Grid & grid)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationLaplace(), sgpp::base::PrewaveletGrid::getShadowStorage(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, sgpp::base::PolyClenshawCurtisBoundary, and sgpp::base::Prewavelet.
Referenced by sgpp::datadriven::LearnerSGDE::computeRegularizationMatrix(), sgpp::datadriven::SparseGridDensityEstimator::computeRegularizationMatrix(), sgpp::datadriven::Learner::createDMSystem(), createOperationLaplace(), createOperationLaplace(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), and sgpp::pde::PoissonEquationEllipticPDESolverSystemDirichlet::PoissonEquationEllipticPDESolverSystemDirichlet().
createOperationLaplace() [2/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplace (base::Grid & grid, sgpp::base::DataVector & coef)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
coef Coefficient vector for OperationLaplace
Returns
Pointer to the new OperationMatrix object for the Grid grid
References createOperationLaplace(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, and sgpp::base::LinearL0Boundary.
createOperationLaplaceEnhanced() [1/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplaceEnhanced (base::Grid & grid)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
This Laplacian is implemented by a multi-dimensional sweep operation
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, and sgpp::base::LinearL0Boundary.
createOperationLaplaceEnhanced() [2/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplaceEnhanced (base::Grid & grid, sgpp::base::DataVector & coef)
Factory method, returning an OperationLaplace (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
This Laplacian is implemented by a multi-dimensional sweep operation
Parameters
grid Grid which is to be used
coef Coefficient vector for OperationLaplace
Returns
Pointer to the new OperationMatrix object for the Grid grid
References grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, and sgpp::base::LinearL0Boundary.
createOperationLaplaceExplicit() [1/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplaceExplicit (base::DataMatrix * m, base::Grid & grid)
Factory method, returning an OperationLaplaceExplicit (OperationMatrix) for the grid at hand.
Note: object has to be freed after use. The DataMatrix m is used to store the the matrix and is not destroyed if the OperationMatrix is destroyed.
Parameters
grid Grid which is to be used
m DataMatrix in which the data is stored
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, grid(), sgpp::base::Linear, m, and sgpp::base::ModBspline.
createOperationLaplaceExplicit() [2/2]
base::OperationMatrix * sgpp::op_factory::createOperationLaplaceExplicit (base::Grid & grid)
Factory method, returning an OperationLaplaceExplicit (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, grid(), sgpp::base::Linear, and sgpp::base::ModBspline.
createOperationLimitFunctionValueRange()
datadriven::OperationLimitFunctionValueRange * sgpp::op_factory::createOperationLimitFunctionValueRange (datadriven::MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm = datadriven::MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm = datadriven::MakePositiveInterpolationAlgorithm::SetToZero, sgpp::base::ScalarFunction * f = nullptr)
Factory method, returning an OperationLimitFunctionValueRange for an arbitrary function f or some sparse grid, which is yet to be defined.
Note: object has to be freed after use.
Parameters
candidateSearchAlgorithm defines algorithm for candidate set enumeration
interpolationAlgorithm defines algorithm for coefficient estimation of extension set
f function to be approximated (as an alternative to a sparse grid function)
Returns
Pointer to the new OperationLimitFunctionValueRange object for the Grid grid
References f.
createOperationLTwoDotExplicit() [1/2]
base::OperationMatrix * sgpp::op_factory::createOperationLTwoDotExplicit (base::DataMatrix * m, base::Grid & grid)
Factory method, returning an OperationLTwoDotExplicit (OperationMatrix) for the grid at hand.
Note: object has to be freed after use. The DataMatrix m is used to store the the matrix and is not destroyed if the OperationMatrix is destroyed.
Parameters
grid Grid which is to be used
m DataMatrix in which the data is stored
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationLTwoDotExplicit(), grid(), sgpp::base::Linear, sgpp::base::LinearL0Boundary, m, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
createOperationLTwoDotExplicit() [2/2]
base::OperationMatrix * sgpp::op_factory::createOperationLTwoDotExplicit (base::Grid & grid)
Factory method, returning an OperationLTwoDotExplicit (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationLTwoDotExplicit(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by sgpp::datadriven::DBMatOffline::buildMatrix(), createOperationLTwoDotExplicit(), createOperationLTwoDotExplicit(), and sgpp::datadriven::DBMatDMSDenseIChol::DBMatDMSDenseIChol().
createOperationLTwoDotProduct()
base::OperationMatrix * sgpp::op_factory::createOperationLTwoDotProduct (base::Grid & grid)
Factory method, returning an OperationLTwoDotProduct (OperationMatrix) for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
Returns
Pointer to the new OperationMatrix object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationLTwoDotProduct(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by sgpp::datadriven::SparseGridDensityEstimator::computeLTwoDotProductMatrix(), createOperationLTwoDotProduct(), sgpp::datadriven::DensityDifferenceSystemMatrix::DensityDifferenceSystemMatrix(), sgpp::datadriven::DensitySystemMatrix::DensitySystemMatrix(), sgpp::pde::HeatEquationParabolicPDESolverSystem::HeatEquationParabolicPDESolverSystem(), sgpp::pde::HeatEquationParabolicPDESolverSystemParallelOMP::HeatEquationParabolicPDESolverSystemParallelOMP(), and sgpp::datadriven::PiecewiseConstantSmoothedRegressionSystemMatrix::PiecewiseConstantSmoothedRegressionSystemMatrix().
createOperationMakePositive()
datadriven::OperationMakePositive * sgpp::op_factory::createOperationMakePositive (datadriven::MakePositiveCandidateSearchAlgorithm candidateSearchAlgorithm = datadriven::MakePositiveCandidateSearchAlgorithm::Intersections, datadriven::MakePositiveInterpolationAlgorithm interpolationAlgorithm = datadriven::MakePositiveInterpolationAlgorithm::SetToZero, bool generateConsistentGrid = true, sgpp::base::ScalarFunction * f = nullptr)
Factory method, returning an OperationMakePositive for an arbitrary function f or some sparse grid, which is yet to be defined.
Note: object has to be freed after use.
Parameters
candidateSearchAlgorithm defines algorithm for candidate set enumeration
interpolationAlgorithm defines algorithm for coefficient estimation of extension set
generateConsistentGrid if set to true, all hierarchical ancestors are available in the resulting grid
f function to be approximated (as an alternative to a sparse grid function)
Returns
Pointer to the new OperationMakePositive object for the Grid grid
References f.
Referenced by sgpp::datadriven::SparseGridDensityEstimator::initialize(), and sgpp::datadriven::OperationLimitFunctionValueRange::OperationLimitFunctionValueRange().
createOperationMultipleEval() [1/2]
base::OperationMultipleEval * sgpp::op_factory::createOperationMultipleEval (base::Grid & grid, base::DataMatrix & dataset)
Factory method, returning an OperationMultipleEval for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
dataset The dataset (DataMatrix, one datapoint per row) that is to be evaluated for the sparse grid function
Returns
Pointer to the new OperationMultipleEval object for the Grid grid
References createOperationMultipleEval(), dataset, grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::Periodic, sgpp::base::Poly, sgpp::base::PolyBoundary, and sgpp::base::Prewavelet.
Referenced by sgpp::datadriven::ClassificationRefinementFunctor::adaptAllGrids(), sgpp::datadriven::PrimalDualSVM::add(), sgpp::datadriven::DataBasedRefinementFunctor::computeH(), sgpp::datadriven::SparseGridDensityEstimator::computeMultipleEvalMatrix(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchParallel(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), createOperationMultipleEval(), createOperationMultipleEval(), sgpp::datadriven::DensityDifferenceSystemMatrix::DensityDifferenceSystemMatrix(), sgpp::datadriven::DensitySystemMatrix::DensitySystemMatrix(), sgpp::datadriven::DMSystemMatrix::DMSystemMatrix(), sgpp::datadriven::DMWeightMatrix::DMWeightMatrix(), sgpp::quadrature::OperationQuadratureMCAdvanced::doQuadrature(), sgpp::base::OperationQuadratureMC::doQuadrature(), sgpp::datadriven::OperationDensityRejectionSamplingLinear::doSampling(), sgpp::datadriven::DBMatOnlineDE::eval(), sgpp::datadriven::DBMatOnlineDE::evalParallel(), sgpp::datadriven::ModelFittingDensityDifferenceEstimationCG::evaluate(), sgpp::datadriven::ModelFittingDensityEstimationCG::evaluate(), sgpp::datadriven::ModelFittingDensityRatioEstimation::evaluate(), sgpp::datadriven::ModelFittingLeastSquares::evaluate(), sgpp::pde::PDESolver::evaluateCuboid(), sgpp::base::ForwardSelectorRefinementIndicator::ForwardSelectorRefinementIndicator(), sgpp::datadriven::DMSystemMatrix::generateb(), sgpp::datadriven::LearnerSGD::getBatchError(), sgpp::datadriven::LearnerSGD::getError(), hpx_main(), sgpp::datadriven::MultipleEvalHPX::LocalityMultiplier::LocalityMultiplier(), main(), main(), sgpp::datadriven::DMSystemMatrix::mult(), sgpp::datadriven::LearnerBase::multTranspose(), sgpp::datadriven::LearnerLeastSquaresIdentity::multTranspose(), sgpp::datadriven::LearnerSGDE::pdf(), sgpp::datadriven::SparseGridDensityEstimator::pdf(), sgpp::datadriven::LearnerSGD::predict(), sgpp::datadriven::RegressionLearner::predict(), sgpp::datadriven::LearnerBase::predict(), sgpp::datadriven::LearnerLeastSquaresIdentity::predict(), sgpp::datadriven::LearnerBaseSP::predict(), sgpp::datadriven::PrimalDualSVM::predictRaw(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::setImplementation(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::setImplementation(), sgpp::datadriven::SystemMatrixDensityRatioEstimation::SystemMatrixDensityRatioEstimation(), sgpp::datadriven::SystemMatrixLeastSquaresIdentity::SystemMatrixLeastSquaresIdentity(), sgpp::datadriven::LearnerLeastSquaresIdentity::testRegular(), sgpp::datadriven::RegressionLearner::train(), and sgpp::datadriven::LearnerSGD::train().
createOperationMultipleEval() [2/2]
base::OperationMultipleEval * sgpp::op_factory::createOperationMultipleEval (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
Factory method, returning an OperationMultipleEval for the grid.
Parameters
grid Grid which is to be used for the operation
dataset dataset to be evaluated
configuration configuration to be used (evalType and evalSubType)
Returns
Pointer to new OperationMultipleEval for the Grid grid
References sgpp::base::Bspline, sgpp::datadriven::COMBINED, createOperationMultipleEval(), sgpp::datadriven::createStreamingBSplineOCLConfigured(), sgpp::datadriven::createStreamingModOCLFastMultiPlatformConfigured(), sgpp::datadriven::createStreamingModOCLMaskMultiPlatformConfigured(), sgpp::datadriven::createStreamingModOCLOptConfigured(), sgpp::datadriven::createStreamingOCLMultiPlatformConfigured(), sgpp::datadriven::CUDA, dataset, sgpp::datadriven::DEFAULT, sgpp::datadriven::OperationMultipleEvalConfiguration::getMPIType(), sgpp::datadriven::OperationMultipleEvalConfiguration::getSubType(), sgpp::datadriven::OperationMultipleEvalConfiguration::getType(), grid(), sgpp::datadriven::HPX, sgpp::base::Linear, sgpp::datadriven::MASTERSLAVE, sgpp::base::ModLinear, sgpp::datadriven::MORTONORDER, sgpp::datadriven::OCL, sgpp::datadriven::OCLFASTMP, sgpp::datadriven::OCLMASKMP, sgpp::datadriven::OCLMP, sgpp::datadriven::OCLOPT, sgpp::base::Poly, sgpp::datadriven::SCALAPACK, sgpp::datadriven::SIMPLE, sgpp::datadriven::STREAMING, and sgpp::datadriven::SUBSPACELINEAR.
createOperationMultipleEvalInter()
base::OperationMultipleEval * sgpp::op_factory::createOperationMultipleEvalInter (base::Grid & grid, base::DataMatrix & dataset, std::set< std::set< size_t > > interactions)
Similar to createOperationMultipleEval, but makes use of interaction terms during evaluation.
Parameters
grid Grid which is to be used
dataset The dataset (DataMatrix, one datapoint per row) that is to be evaluated for the sparse grid function
interactions A list of Interaction the SG is reduced to
Returns
Pointer to the new OperationMultipleEval object for the Grid grid
References dataset, grid(), and sgpp::base::ModLinear.
Referenced by sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatch(), sgpp::datadriven::DBMatOnlineDE::computeWeightedBFromBatchTwoDatasets(), and sgpp::datadriven::DBMatOnlineDE::eval().
createOperationMultipleEvalNaive()
base::OperationMultipleEval * sgpp::op_factory::createOperationMultipleEvalNaive (base::Grid & grid, base::DataMatrix & dataset)
Factory method, returning an OperationMultipleEvalNaive for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used
dataset The dataset (DataMatrix, one datapoint per row) that is to be evaluated for the sparse grid function
Returns
Pointer to the new OperationMultipleEval object for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationMultipleEvalNaive(), dataset, grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModNakBspline, sgpp::base::ModPolyClenshawCurtis, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by sgpp::datadriven::SparseGridDensityEstimator::computeMultipleEvalMatrix(), and createOperationMultipleEvalNaive().
createOperationMultipleHierarchisation()
optimization::OperationMultipleHierarchisation * sgpp::op_factory::createOperationMultipleHierarchisation (base::Grid & grid)
Creates a OperationMultipleHierarchisation for the given sgpp::optimization grid.
Don't forget to delete the object after use.
Parameters
grid sparse grid
Returns
pointer to a OperationMultipleHierarchisation object for the grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationMultipleHierarchisation(), sgpp::base::FundamentalNakSplineBoundary, sgpp::base::FundamentalSpline, sgpp::base::FundamentalSplineBoundary, grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModNakBspline, sgpp::base::ModWavelet, sgpp::base::ModWeaklyFundamentalNakSpline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NaturalBsplineBoundary, sgpp::base::Wavelet, sgpp::base::WaveletBoundary, sgpp::base::WeaklyFundamentalNakSplineBoundary, and sgpp::base::WeaklyFundamentalSplineBoundary.
Referenced by createOperationMultipleHierarchisation().
createOperationQuadrature()
base::OperationQuadrature * sgpp::op_factory::createOperationQuadrature (base::Grid & grid)
Factory method, returning an OperationQuadrature for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for quadrature
Returns
Pointer to the new OperationQuadrature for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationQuadrature(), sgpp::base::FundamentalSpline, sgpp::base::BsplineBoundaryGrid::getDegree(), sgpp::base::BsplineClenshawCurtisGrid::getDegree(), sgpp::base::BsplineGrid::getDegree(), sgpp::base::FundamentalSplineGrid::getDegree(), sgpp::base::ModBsplineClenshawCurtisGrid::getDegree(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModFundamentalSplineGrid::getDegree(), sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::ModPolyClenshawCurtisGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::NakBsplineExtendedGrid::getDegree(), sgpp::base::NakPBsplineGrid::getDegree(), sgpp::base::PolyClenshawCurtisGrid::getDegree(), sgpp::base::ModPolyGrid::getDegree(), sgpp::base::PolyBoundaryGrid::getDegree(), sgpp::base::PolyClenshawCurtisBoundaryGrid::getDegree(), sgpp::base::PolyGrid::getDegree(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearClenshawCurtis, sgpp::base::LinearClenshawCurtisBoundary, sgpp::base::LinearL0Boundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModFundamentalSpline, sgpp::base::ModLinear, sgpp::base::ModLinearClenshawCurtis, sgpp::base::ModNakBspline, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, sgpp::base::NakPBspline, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationQuadrature(), sgpp::optimization::SplineResponseSurface::getIntegral(), sgpp::optimization::SplineResponseSurfaceVector::getIntegrals(), sgpp::datadriven::SparseGridDensityEstimator::initialize(), and sgpp::datadriven::DBMatOnlineDE::normalizeQuadrature().
createOperationQuadratureMCAdvanced()
quadrature::OperationQuadratureMCAdvanced * sgpp::op_factory::createOperationQuadratureMCAdvanced (base::Grid & grid, size_t numberOfSamples, std::uint64_t seed = std::mt19937_64::default_seed)
Creates an OperationQuadratureMCAdvanced.
Parameters
grid Reference to the grid object
numberOfSamples Number of Monte Carlo samples
seed Custom seed (defaults to default seed of mt19937_64)
References grid().
createOperationRegularizationDiagonal()
base::OperationMatrix * sgpp::op_factory::createOperationRegularizationDiagonal (base::Grid & grid, int mode, double k)
Factory method, returning an OperationRegularizationDiagonal for the grid at hand.
Parameters
grid Grid which is to be used for OperationRegularizationDiagonal
mode Mode, specifying which regularization to use. Example: OperationRegularizationDiagonal::HKMIX.
k Parameter for \(H^k\)
Returns
Pointer to the new OperationRegularizationDiagonal object for the Grid grid
References grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, and sgpp::base::ModLinear.
createOperationRosenblattTransformation()
datadriven::OperationRosenblattTransformation * sgpp::op_factory::createOperationRosenblattTransformation (base::Grid & grid)
Factory method, returning an OperationRosenblattTransformation for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationRosenblattTransformation for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationRosenblattTransformation(), grid(), sgpp::base::Linear, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationRosenblattTransformation(), and sgpp::datadriven::RosenblattTransformation::doTransformation().
createOperationRosenblattTransformation1D()
datadriven::OperationTransformation1D * sgpp::op_factory::createOperationRosenblattTransformation1D (base::Grid & grid)
Factory method, returning an OperationRosenblattTransformation for the grid.
Parameters
grid Grid which is to be used for the operation
Returns
Pointer to new OperationRosenblattTransformation1D for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationRosenblattTransformation1D(), grid(), sgpp::base::Linear, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationRosenblattTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationBsplineBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModBspline::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModBsplineClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationModPolyClenshawCurtis::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationPoly::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationPolyBoundary::doTransformation1D(), sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtis::doTransformation1D(), and sgpp::datadriven::OperationRosenblattTransformationPolyClenshawCurtisBoundary::doTransformation1D().
createOperationRosenblattTransformationKDE()
datadriven::OperationRosenblattTransformationKDE * sgpp::op_factory::createOperationRosenblattTransformationKDE (datadriven::KernelDensityEstimator & kde)
Factory method, returning an OperationRosenblattTransformationKDE for the kde.
Parameters
kde KernelDensityEstimator for which the Rosenblatt transformation should be computed
Returns
Pointer to new OperationRosenblattTransformationKDE for the kde
References createOperationRosenblattTransformationKDE().
Referenced by createOperationRosenblattTransformationKDE().
createOperationSecondMoment()
base::OperationSecondMoment * sgpp::op_factory::createOperationSecondMoment (base::Grid & grid)
Factory method, returning an OperationSecondMoment for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for quadrature
Returns
Pointer to the new OperationSecondMoment for the Grid grid
References sgpp::base::Bspline, sgpp::base::BsplineBoundary, sgpp::base::BsplineClenshawCurtis, createOperationSecondMoment(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearTruncatedBoundary, sgpp::base::ModBspline, sgpp::base::ModBsplineClenshawCurtis, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModPolyClenshawCurtis, sgpp::base::Poly, sgpp::base::PolyBoundary, sgpp::base::PolyClenshawCurtis, and sgpp::base::PolyClenshawCurtisBoundary.
Referenced by createOperationSecondMoment(), sgpp::datadriven::LearnerSGDE::variance(), and sgpp::datadriven::SparseGridDensityEstimator::variance().
createOperationTest()
datadriven::OperationTest * sgpp::op_factory::createOperationTest (base::Grid & grid)
Factory method, returning an OperationTest for the grid at hand.
Parameters
grid Grid which is to be used for OperationTest
Returns
Pointer to the new OperationTest object for the Grid grid
References createOperationTest(), sgpp::base::ModBsplineGrid::getDegree(), sgpp::base::ModPolyGrid::getDegree(), sgpp::base::PolyGrid::getDegree(), grid(), sgpp::base::Linear, sgpp::base::LinearBoundary, sgpp::base::LinearL0Boundary, sgpp::base::LinearStretched, sgpp::base::LinearStretchedBoundary, sgpp::base::ModBspline, sgpp::base::ModLinear, sgpp::base::ModPoly, sgpp::base::ModWavelet, sgpp::base::Poly, and sgpp::base::Prewavelet.
Referenced by createOperationTest().
createOperationWeightedQuadrature()
base::OperationWeightedQuadrature * sgpp::op_factory::createOperationWeightedQuadrature (base::Grid & grid, size_t quadOrder)
Factory method, returning an OperationWeightedQuadrature for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for quadrature
quadOrder quadrature order
Returns
Pointer to the new OperationWeightedQuadrature for the Grid grid
References sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::NakBsplineExtendedGrid::getDegree(), sgpp::base::NakBsplineGrid::getDegree(), sgpp::base::NakPBsplineGrid::getDegree(), grid(), sgpp::base::ModNakBspline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, and sgpp::base::NakPBspline.
Referenced by sgpp::datadriven::PolynomialChaosExpansion::adaptiveQuadratureWeighted(), sgpp::optimization::SplineResponseSurface::getMean(), sgpp::optimization::SplineResponseSurfaceVector::getMeans(), and sgpp::datadriven::PolynomialChaosExpansion::sparseGridQuadrature().
createOperationWeightedSecondMoment()
base::OperationWeightedSecondMoment * sgpp::op_factory::createOperationWeightedSecondMoment (base::Grid & grid, size_t quadOrder)
Factory method, returning an OperationWeightedSecondMoment for the grid at hand.
Note: object has to be freed after use.
Parameters
grid Grid which is to be used for quadrature
quadOrder quadrature order
Returns
Pointer to the new OperationSecondMoment for the Grid grid
References sgpp::base::ModNakBsplineGrid::getDegree(), sgpp::base::NakBsplineBoundaryGrid::getDegree(), sgpp::base::NakBsplineExtendedGrid::getDegree(), sgpp::base::NakBsplineGrid::getDegree(), sgpp::base::NakPBsplineGrid::getDegree(), grid(), sgpp::base::ModNakBspline, sgpp::base::NakBspline, sgpp::base::NakBsplineBoundary, sgpp::base::NakBsplineExtended, and sgpp::base::NakPBspline.
Referenced by sgpp::optimization::SplineResponseSurface::getVariance(), and sgpp::optimization::SplineResponseSurfaceVector::getVariances().