SG++-Doxygen-Documentation: python.tools Namespace Reference
python.tools Namespace Reference
Classes
class Matrix
Functions
appendToDict (dict, key, val)
checkData (data)
gzOpen (filename, mode="r")
isARFFFile (filename)
makedir (path, verbose=False)
normalize (data, border=0.0, filename=None, minvals=None, maxvals=None, verbose=False)
normalizeClasses (data, border=0.0, minborder=-sys.maxsize-1, verbose=False)
readAlpha (filename)
readAlphaARFF (filename)
readAlphaTrivial (filename, delim=None)
readCheckpoint (filename)
readData (filename)
readDataARFF (filename)
readDataTrivial (filename, delim=None, hasclass=True)
readGrid (filename)
readGridAlpha (fnamegrid, fnamealpha)
readNormfile (filename)
split_DataVector_by_proportion (data, proportion)
split_DataVectors_by_proportion_stratified (data, classes, proportion)
split_n_folds (data, num_partitions, seed=None)
split_n_folds_sequential (data, num_partitions)
split_n_folds_stratified (data, num_partitions, seed=None)
writeAlphaARFF (filename, alpha)
writeCheckpoint (filename, grid, alpha, adaption=None, fold=None)
writeDataARFF (data, merge=False)
writeDataMaple (data, merge)
writeDataVectorMaple (data, filename, format="%s", maple_name="X", check=True)
writeGnuplot (filename, grid, alpha, resolution, mode="w", data=None, fvals=None)
writeGnuplotFctn (filename, dim, fctn, resolution, mode="w")
writeGnuplotGrid (filename, grid)
writeGrid (filename, grid)
writeLockFile (filename, txt, mode="a")
writeNormfile (filename, border, minvals, maxvals)
writeStats (filename, txt, mode="a")
writeStringToFile (s, filename, check=True)
Variables
int ARFF = 1
dict base_types
dict CModes
int NOTAFILE = -1
int SIMPLE = 0
Function Documentation
appendToDict()
python.tools.appendToDict (dict, key, val)
checkData()
python.tools.checkData (data)
gzOpen()
python.tools.gzOpen (filename, mode = "r")
Referenced by python.tools.isARFFFile(), python.tools.readDataARFF(), python.tools.readDataTrivial(), python.tools.readGrid(), python.tools.readNormfile(), python.toolsExtended.readReferenceMatrix(), python.tools.writeAlphaARFF(), python.tools.writeDataARFF(), python.tools.writeGnuplot(), python.tools.writeGnuplotFctn(), python.tools.writeGrid(), python.tools.writeLockFile(), and python.tools.writeStringToFile().
isARFFFile()
python.tools.isARFFFile (filename)
References python.tools.gzOpen().
Referenced by python.tools.readAlpha(), and python.tools.readData().
makedir()
python.tools.makedir (path, verbose = False)
normalize()
python.tools.normalize (data, border = 0.0, filename = None, minvals = None, maxvals = None, verbose = False)
References python.tools.writeNormfile().
normalizeClasses()
python.tools.normalizeClasses (data, border = 0.0, minborder = -sys.maxsize-1, verbose = False)
readAlpha()
python.tools.readAlpha (filename)
References python.tools.isARFFFile(), and python.tools.readAlphaTrivial().
Referenced by python.tools.readGridAlpha().
readAlphaARFF()
python.tools.readAlphaARFF (filename)
readAlphaTrivial()
python.tools.readAlphaTrivial (filename, delim = None)
Referenced by python.tools.readAlpha().
readCheckpoint()
python.tools.readCheckpoint (filename)
readData()
python.tools.readData (filename)
References python.tools.isARFFFile().
readDataARFF()
python.tools.readDataARFF (filename)
References python.tools.gzOpen().
readDataTrivial()
python.tools.readDataTrivial (filename, delim = None, hasclass = True)
References python.tools.gzOpen().
readGrid()
python.tools.readGrid (filename)
References python.tools.gzOpen().
readGridAlpha()
python.tools.readGridAlpha (fnamegrid, fnamealpha)
References python.tools.readAlpha().
readNormfile()
python.tools.readNormfile (filename)
References python.tools.gzOpen().
split_DataVector_by_proportion()
python.tools.split_DataVector_by_proportion (data, proportion)
split_DataVectors_by_proportion_stratified()
python.tools.split_DataVectors_by_proportion_stratified (data, classes, proportion)
split_n_folds()
python.tools.split_n_folds (data, num_partitions, seed = None)
split_n_folds_sequential()
python.tools.split_n_folds_sequential (data, num_partitions)
split_n_folds_stratified()
python.tools.split_n_folds_stratified (data, num_partitions, seed = None)
writeAlphaARFF()
python.tools.writeAlphaARFF (filename, alpha)
References python.tools.gzOpen().
writeCheckpoint()
python.tools.writeCheckpoint (filename, grid, alpha, adaption = None, fold = None)
writeDataARFF()
python.tools.writeDataARFF (data, merge = False)
References python.tools.gzOpen().
writeDataMaple()
python.tools.writeDataMaple (data, merge)
writeDataVectorMaple()
python.tools.writeDataVectorMaple (data, filename, format = "%s", maple_name = "X", check = True)
References python.tools.writeStringToFile().
writeGnuplot()
python.tools.writeGnuplot (filename, grid, alpha, resolution, mode = "w", data = None, fvals = None)
References python.tools.gzOpen().
writeGnuplotFctn()
python.tools.writeGnuplotFctn (filename, dim, fctn, resolution, mode = "w")
References python.tools.gzOpen().
writeGnuplotGrid()
python.tools.writeGnuplotGrid (filename, grid)
writeGrid()
python.tools.writeGrid (filename, grid)
References python.tools.gzOpen().
writeLockFile()
python.tools.writeLockFile (filename, txt, mode = "a")
References python.tools.gzOpen().
Referenced by python.tools.writeStats().
writeNormfile()
python.tools.writeNormfile (filename, border, minvals, maxvals)
References python.tools.writeStringToFile().
Referenced by python.tools.normalize().
writeStats()
python.tools.writeStats (filename, txt, mode = "a")
References python.tools.writeLockFile().
writeStringToFile()
python.tools.writeStringToFile (s, filename, check = True)
References python.tools.gzOpen().
Referenced by python.tools.writeDataVectorMaple(), and python.tools.writeNormfile().
Variable Documentation
ARFF
int python.tools.ARFF = 1
base_types
dict python.tools.base_types
Initial value:
=  {
    #    "linear" : {"base" : SLinearBase, "b" : SGridOperationB, "t" : test_dataset_linear, "laplace" : SGridOperationLaplace},
    #    "modlinear" : {"base" : SLinearModifiedBase, "b" : SGridModOperationB, "t" : test_dataset_modlin},
    #    "poly" : {"base" : "SPolyBase", },
}
CModes
dict python.tools.CModes
Initial value:
=  {
    "laplace": "Classical Laplacian. See OpLaplaceAdaptive",
    "identity": "Identity matrix, most efficient.",
    "identity_no_level1": "Identity matrix, most efficient. But do not penalize Level 1",
    "anisotropicpenalty": "Preferres quadratical supports. See OperationRegularizationDiagonal.",
    "levelsum": "Sum of the levels, scaled by the gridlevel (usually 2 for adaptive SGs).",
    "isotropicpenalty": "Energy-norm-like SGs. See OperationRegularizationDiagonal.",
    "rowsum": "Sum of the rows of classical Laplacian. See OpLaplaceAdaptive",
    "hkmix": "H^k_mix norm; requires parameter Hk",
    "h0hklaplace": "Pseudo-Laplace with H^k in one, and 'H^0' in the remaining dimensions each; requires paramer Hk"}
NOTAFILE
int python.tools.NOTAFILE = -1
SIMPLE
int python.tools.SIMPLE = 0