SG++-Doxygen-Documentation: sgpp::optimization::file_io Namespace Reference
sgpp::optimization::file_io Namespace Reference
Namespace with functions to write data (vectors, matrices, grids, ...) to a file.
Functions
template<>
const char * getTypeString (const std::vector< double > &A)
template<>
const char * getTypeString (const std::vector< double > &A)
template<>
const char * getTypeString (const std::vector< float > &A)
template<>
const char * getTypeString (const std::vector< float > &A)
template<>
const char * getTypeString (const std::vector< std::string > &A)
template<>
const char * getTypeString (const std::vector< std::string > &A)
template<class T >
const char * getTypeString (const std::vector< T > &A)
template<>
const char * getTypeString (const std::vector< uint16_t > &A)
template<>
const char * getTypeString (const std::vector< uint16_t > &A)
template<>
const char * getTypeString (const std::vector< uint32_t > &A)
template<>
const char * getTypeString (const std::vector< uint32_t > &A)
template<>
const char * getTypeString (const std::vector< uint64_t > &A)
template<>
const char * getTypeString (const std::vector< uint64_t > &A)
template<>
const char * getTypeString (const std::vector< uint8_t > &A)
template<>
const char * getTypeString (const std::vector< uint8_t > &A)
template<>
void readEntry (std::ifstream &f, std::string &entry)
Read string from input stream (called by readMatrix()).
template<>
void readEntry (std::ifstream &f, std::string &entry)
Read string from input stream (called by readMatrix()).
template<class T >
void readEntry (std::ifstream &f, T &entry)
Read bytes of entry representation from input stream (called by readMatrix()).
void readGrid (const std::string &filename, base::GridStorage &gridStorage)
Read a grid (only grid points) from a file.
void readGrid (const std::string &filename, base::GridStorage &gridStorage, base::DataVector &functionValues)
Read a grid (grid points and function values) from a file.
void readMatrix (const std::string &filename, base::DataMatrix &A)
Read a matrix from a file.
template<class T >
void readMatrix (const std::string &filename, std::vector< T > &A, size_t &m, size_t &n)
Read a matrix (stored row-wise in a std::vector) from a file.
void readVector (const std::string &filename, base::DataVector &x)
Read a base::DataVector from a file.
template<class T >
void readVector (const std::string &filename, std::vector< T > &x)
Read a std::vector from a file.
template<>
void writeEntry (std::ofstream &f, const std::string &entry)
Write string to output stream (called by writeMatrix()).
template<>
void writeEntry (std::ofstream &f, const std::string &entry)
Write string to output stream (called by writeMatrix()).
template<class T >
void writeEntry (std::ofstream &f, const T &entry)
Write bytes of entry representation to output stream (called by writeMatrix()).
void writeGrid (const std::string &filename, const base::GridStorage &gridStorage)
Write a grid (only grid points) to a file.
void writeGrid (const std::string &filename, const base::GridStorage &gridStorage, const base::DataVector &functionValues)
Write a grid (grid points and function values) to a file.
void writeMatrix (const std::string &filename, base::DataMatrix &A)
Write a base::DataMatrix to a file.
template<class T >
void writeMatrix (const std::string &filename, const std::vector< T > &A, size_t m, size_t n)
Write a matrix (stored row-wise in a std::vector) to a file.
void writeVector (const std::string &filename, base::DataVector &x)
Write a base::DataVector to a file.
template<class T >
void writeVector (const std::string &filename, const std::vector< T > &x)
Write a std::vector to a file.
Detailed Description
Namespace with functions to write data (vectors, matrices, grids, ...) to a file.
Function Documentation
getTypeString() [1/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< double > & A)
Parameters
A ignored
Returns
type string for double (right-padded "double")
getTypeString() [2/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< double > & A)
Parameters
A ignored
Returns
type string for double (right-padded "double")
getTypeString() [3/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< float > & A)
Parameters
A ignored
Returns
type string for float (right-padded "float")
getTypeString() [4/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< float > & A)
Parameters
A ignored
Returns
type string for float (right-padded "float")
getTypeString() [5/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< std::string > & A)
Parameters
A ignored
Returns
type string for string (right-padded "string")
getTypeString() [6/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< std::string > & A)
Parameters
A ignored
Returns
type string for string (right-padded "string")
getTypeString() [7/15]
template<class T > const char * sgpp::optimization::file_io::getTypeString (const std::vector< T > & A)
Parameters
A ignored
Returns
type string for unknown types (right-padded "other")
getTypeString() [8/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint16_t > & A)
Parameters
A ignored
Returns
type string for uint16_t (right-padded "uint16")
getTypeString() [9/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint16_t > & A)
Parameters
A ignored
Returns
type string for uint16_t (right-padded "uint16")
getTypeString() [10/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint32_t > & A)
Parameters
A ignored
Returns
type string for uint32_t (right-padded "uint32")
getTypeString() [11/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint32_t > & A)
Parameters
A ignored
Returns
type string for uint32_t (right-padded "uint32")
getTypeString() [12/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint64_t > & A)
Parameters
A ignored
Returns
type string for uint64_t (right-padded "uint64")
getTypeString() [13/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint64_t > & A)
Parameters
A ignored
Returns
type string for uint64_t (right-padded "uint64")
getTypeString() [14/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint8_t > & A)
Parameters
A ignored
Returns
type string for uint8_t (right-padded "uint8")
Referenced by readMatrix(), and writeMatrix().
getTypeString() [15/15]
template<> const char * sgpp::optimization::file_io::getTypeString (const std::vector< uint8_t > & A)
Parameters
A ignored
Returns
type string for uint8_t (right-padded "uint8")
Referenced by readMatrix(), and writeMatrix().
readEntry() [1/3]
template<> void sgpp::optimization::file_io::readEntry (std::ifstream & f, std::string & entry)
Read string from input stream (called by readMatrix()).
Parameters
f input stream to be read
[out] entry entry to be read
References f.
Referenced by readMatrix().
readEntry() [2/3]
template<> void sgpp::optimization::file_io::readEntry (std::ifstream & f, std::string & entry)
Read string from input stream (called by readMatrix()).
Parameters
f input stream to be read
[out] entry entry to be read
References f.
Referenced by readMatrix().
readEntry() [3/3]
template<class T > void sgpp::optimization::file_io::readEntry (std::ifstream & f, T & entry)
Read bytes of entry representation from input stream (called by readMatrix()).
Parameters
f input stream to be read
[out] entry entry to be read
References f.
readGrid() [1/2]
void sgpp::optimization::file_io::readGrid (const std::string & filename, base::GridStorage & gridStorage)
Read a grid (only grid points) from a file.
The format is as in writeGrid (discarding function values).
Parameters
filename filename of the file to be read
[out] gridStorage grid storage containing the grid points
readGrid() [2/2]
void sgpp::optimization::file_io::readGrid (const std::string & filename, base::GridStorage & gridStorage, base::DataVector & functionValues)
Read a grid (grid points and function values) from a file.
The format is as in writeGrid.
Parameters
filename filename of the file to be read
[out] gridStorage grid storage containing the grid points
[out] functionValues vector of function values
References f, and sgpp::base::HashGridPoint::set().
readMatrix() [1/2]
void sgpp::optimization::file_io::readMatrix (const std::string & filename, base::DataMatrix & A)
Read a matrix from a file.
The format is as in writeMatrix.
Parameters
filename filename of the file to be read
[out] A matrix
References m, readMatrix(), and sgpp::base::DataMatrix::resize().
Referenced by readMatrix(), readVector(), and readVector().
readMatrix() [2/2]
template<class T > void sgpp::optimization::file_io::readMatrix (const std::string & filename, std::vector< T > & A, size_t & m, size_t & n)
Read a matrix (stored row-wise in a std::vector) from a file.
The format is as in writeMatrix.
Parameters
filename filename of the file to be written
[out] A matrix
[out] m number of rows
[out] n number of columns
References f, getTypeString(), m, and readEntry().
readVector() [1/2]
void sgpp::optimization::file_io::readVector (const std::string & filename, base::DataVector & x)
Read a base::DataVector from a file.
It's readMatrix with the vector as one row.
Parameters
filename filename of the file to be read
[out] x vector
References m, and readMatrix().
readVector() [2/2]
template<class T > void sgpp::optimization::file_io::readVector (const std::string & filename, std::vector< T > & x)
Read a std::vector from a file.
It's readMatrix with the vector as one row.
Parameters
filename filename of the file to be read
[out] x vector
References m, and readMatrix().
writeEntry() [1/3]
template<> void sgpp::optimization::file_io::writeEntry (std::ofstream & f, const std::string & entry)
Write string to output stream (called by writeMatrix()).
Parameters
f output stream to be written to
entry entry to be written
References f.
Referenced by writeMatrix().
writeEntry() [2/3]
template<> void sgpp::optimization::file_io::writeEntry (std::ofstream & f, const std::string & entry)
Write string to output stream (called by writeMatrix()).
Parameters
f output stream to be written to
entry entry to be written
References f.
Referenced by writeMatrix().
writeEntry() [3/3]
template<class T > void sgpp::optimization::file_io::writeEntry (std::ofstream & f, const T & entry)
Write bytes of entry representation to output stream (called by writeMatrix()).
Parameters
f output stream to be written to
entry entry to be written
References f.
writeGrid() [1/2]
void sgpp::optimization::file_io::writeGrid (const std::string & filename, const base::GridStorage & gridStorage)
Write a grid (only grid points) to a file.
The format is the same as the version with functions values with all function values set to zero.
Parameters
filename filename of the file to be written
gridStorage grid storage containing the grid points
writeGrid() [2/2]
void sgpp::optimization::file_io::writeGrid (const std::string & filename, const base::GridStorage & gridStorage, const base::DataVector & functionValues)
Write a grid (grid points and function values) to a file.
The format is as follows:
size_t   N (number of grid points)
size_t   d (dimension)
for j = 0, ..., N-1
    for t = 0, ..., d-1
        double           grid_point[j].coord(t)
        unsigned int     grid_point[j].level(t)
        unsigned int     grid_point[j].index(t)
    end
    double   function_value[j]
end
Parameters
filename filename of the file to be written
gridStorage grid storage containing the grid points
functionValues vector of function values
References f, sgpp::base::HashGridPoint::getIndex(), sgpp::base::HashGridPoint::getLevel(), and sgpp::base::DataVector::getSize().
writeMatrix() [1/2]
void sgpp::optimization::file_io::writeMatrix (const std::string & filename, base::DataMatrix & A)
Write a base::DataMatrix to a file.
Parameters
filename filename of the file to be written
A matrix
References sgpp::base::DataMatrix::getNcols(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataMatrix::getPointer(), and writeMatrix().
Referenced by writeMatrix(), writeVector(), and writeVector().
writeMatrix() [2/2]
template<class T > void sgpp::optimization::file_io::writeMatrix (const std::string & filename, const std::vector< T > & A, size_t m, size_t n)
Write a matrix (stored row-wise in a std::vector) to a file.
The format is as follows:
size_t       m
size_t       n
char[16]     type string (one of "uint8", "uint16", "uint32",
             "uint64", "double", "string", or "other",
             right-padded with spaces to 16 characters)
for i = 0, ..., m*n - 1
    T        A[i] (size depending on template parameter,
             strings are written null-terminatedly)
end
Parameters
filename filename of the file to be written
A matrix
m number of rows
n number of columns
References f, getTypeString(), m, and writeEntry().
writeVector() [1/2]
void sgpp::optimization::file_io::writeVector (const std::string & filename, base::DataVector & x)
Write a base::DataVector to a file.
It's writeMatrix with the vector as one row.
Parameters
filename filename of the file to be written
x vector
References sgpp::base::DataVector::getPointer(), sgpp::base::DataVector::getSize(), and writeMatrix().
writeVector() [2/2]
template<class T > void sgpp::optimization::file_io::writeVector (const std::string & filename, const std::vector< T > & x)
Write a std::vector to a file.
It's writeMatrix with the vector as one row.
Parameters
filename filename of the file to be written
x vector
References writeMatrix().