SG++-Doxygen-Documentation: python.hierarchisation Namespace Reference
python.hierarchisation Namespace Reference
Functions
buildParable (dim)
builds parable test function over [0,1]^d
buildParableBoundary (dim)
build parable test function over [0,1]^d with boundaries
callback_deprecated (option, opt, value, parser)
Outputs a deprecated warning for an option.
runHierarchisationDehierarchisationLinearBoundaryRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
runHierarchisationDehierarchisationLinearRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
runHierarchisationDehierarchisationLinearRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
runHierarchisationDehierarchisationModLinearRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
runHierarchisationDehierarchisationModLinearTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
Function Documentation
buildParable()
python.hierarchisation.buildParable (dim)
builds parable test function over [0,1]^d
Parameters
dim dimension of the parable's space
Returns
returns a string that contains the function as string
Referenced by python.hierarchisation.runHierarchisationDehierarchisationLinearRegularTest(), python.hierarchisation.runHierarchisationDehierarchisationLinearRegularTestPrintND(), and python.hierarchisation.runHierarchisationDehierarchisationModLinearTestPrintND().
buildParableBoundary()
python.hierarchisation.buildParableBoundary (dim)
build parable test function over [0,1]^d with boundaries
Parameters
dim dimension of the parable's space
Returns
returns a string that contains the function as string
Referenced by python.hierarchisation.runHierarchisationDehierarchisationLinearBoundaryRegularTestPrintND(), python.hierarchisation.runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTest(), python.hierarchisation.runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTestPrintND(), and python.hierarchisation.runHierarchisationDehierarchisationModLinearRegularTest().
callback_deprecated()
python.hierarchisation.callback_deprecated (option, opt, value, parser)
Outputs a deprecated warning for an option.
Parameters
option Parameter set by the OptionParser
opt Parameter set by the OptionParser
value Parameter set by the OptionParser
parser Parameter set by the OptionParser
runHierarchisationDehierarchisationLinearBoundaryRegularTestPrintND()
python.hierarchisation.runHierarchisationDehierarchisationLinearBoundaryRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
resolution the number of testpoints in every dimension
References python.hierarchisation.buildParableBoundary().
runHierarchisationDehierarchisationLinearRegularTest()
python.hierarchisation.runHierarchisationDehierarchisationLinearRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
References python.hierarchisation.buildParable().
runHierarchisationDehierarchisationLinearRegularTestPrintND()
python.hierarchisation.runHierarchisationDehierarchisationLinearRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
resolution the number of testpoints in every dimension
References python.hierarchisation.buildParable().
runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTest()
python.hierarchisation.runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
References python.hierarchisation.buildParableBoundary().
runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTestPrintND()
python.hierarchisation.runHierarchisationDehierarchisationLinearTruncatedBoundaryRegularTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
resolution the number of testpoints in every dimension
References python.hierarchisation.buildParableBoundary().
runHierarchisationDehierarchisationModLinearRegularTest()
python.hierarchisation.runHierarchisationDehierarchisationModLinearRegularTest (dim, level)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
References python.hierarchisation.buildParableBoundary(), and python.hierarchisation.runHierarchisationDehierarchisationModLinearRegularTest().
Referenced by python.hierarchisation.runHierarchisationDehierarchisationModLinearRegularTest().
runHierarchisationDehierarchisationModLinearTestPrintND()
python.hierarchisation.runHierarchisationDehierarchisationModLinearTestPrintND (dim, level, resolution)
tests the hierarchisation and dehierarchisation routine of sgpp with a sparse and evals the hierachified sparse grid
Parameters
dim the dimension of the test grid
level the max. level of the test sparse grid
resolution the number of testpoints in every dimension
References python.hierarchisation.buildParable().