SG++-Doxygen-Documentation: python.utils.json Namespace Reference
python.utils.json Namespace Reference
Classes
class _StringGenerator
json.py implements a JSON (http://json.org) reader and writer.
class JsonReader
Reader for json-formatted objects.
class JsonWriter
Writer for json-formatted objects.
class ReadException
Exceptions which can happen during the reading process.
class WriteException
Exceptions which can happen during the writing process.
Functions
read (s)
write (obj, escaped_forward_slash=False)
Function Documentation
read()
python.utils.json.read (s)
References python.utils.json.read().
Referenced by python.utils.json.read().
write()
python.utils.json.write (obj, escaped_forward_slash = False)
References python.utils.json.write().
Referenced by python.utils.json.write().