SG++-Doxygen-Documentation: sgpp::datadriven Namespace Reference
sgpp::datadriven Namespace Reference
Namespaces
namespace clusteringmpi
namespace ClusteringOCL
namespace DBMatOfflineFactory
factories to build the specialization of the DBMatOffline objects.
namespace DBMatOnlineDEFactory
namespace DensityOCLMultiPlatform
namespace MultipleEvalHPX
namespace PermutationUtil
namespace PiecewiseConstantRegression
namespace streamingBSplineOCL
namespace StreamingModOCLFastMultiPlatform
namespace StreamingModOCLMaskMultiPlatform
namespace StreamingModOCLOpt
namespace StreamingModOCLUnified
namespace StreamingOCLMultiPlatform
namespace x86simple
Classes
class AbstractOperationMultipleEvalSubspace
class Accuracy
Metric that quantifies the difference between predicted values and actual values in terms of mean squared error (MSE).
class AlgorithmAdaBoostBase
class AlgorithmAdaBoostIdentity
class AlgorithmMultipleEvaluationDistributed
Abstract implementation for distributed multiple function evaluations.
class ArffFileSampleProvider
ArffFileSampleProvider allows reading data in ARFF format into a sgpp::datadriven::Dataset object.
class ARFFTools
Class that provides functionality to read ARFF files.
struct AssignBatchNetworkMessage
Message wrapped in MPI_Packet specifying an order to a worker to train from a batch.
struct AssignSystemMatrixUpdateNetworkMessage
Message wrapped in MPI_Packet specifying an order to a worker to update a class' system matrix decomposition.
struct AssignTaskResult
Used by the MPI Task Scheduler to deliver the result of assigning the requested task.
class BayesianOptimization
Class to host all methods to perform Bayesian Optimization.
class BlacsProcessGrid
This class represents a BLACS process grid for use with ScaLAPACK.
class BOConfig
Container class to store a conrete hyperparameter configuration for interaction with Bayesian Optimization.
class BoHyperparameterOptimizer
BoHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
class ClassificationFitterFactory
Concrete factory to build instances of sgpp::datadriven::ModelFittingClassification.
class ClassificationLearner
The ClassificationLearner class Solves a classification problem.
class ClassificationMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for classification.
class ClassificationRefinementFunctor
Classification refinement builds up the combined grid of all classes, then iterates through it always keeping track of the neighbors to detect class changes between neighbors.
struct ClassificatorQuality
struct to encapsulate the classsifiers quality by its characteristic numbers
class CombiScheme
class ConfigurationBit
This class implements a boolean representation of hyperparameters for harmonica.
class ConfigurationRestriction
This class represents a constraint on the ConfigurationBits used by harmonica.
class ContinuousParameter
Concrete class for hyperparameter with continuous values.
struct CrossvalidationConfiguration
struct CrossvalidationForRegularizationConfiguration
class CSVFileSampleProvider
CSVFileSampleProvider allows reading data in CSV format into a sgpp::datadriven::Dataset object.
class CSVTools
Class that provides functionality to read CSV files.
class CSVWriter
Class that provides functionality to write a Dataset to a CSV file.
struct DatabaseConfiguration
Configuration structure for the offline datamatrix decomposition database.
class DataBasedRefinementFunctor
Data based refinement uses data points to find refinement candidates.
class DataMatrixDistributed
Class to represent a DataMatrix which is distributed on a process grid.
class DataMiningConfigParser
class Dataset
class DatasetGenerator
class DatasetTools
class DataShufflingFunctor
A class to provide functionality to shuffle (reorder) the data samples before the sample provider accesses it.
class DataShufflingFunctorCrossValidation
A pseudo shuffling functor, that maps indices 0...foldSize-1 to the current fold while mapping the other indices sequentially to the rest of the dataset.
class DataShufflingFunctorFactory
Concrete factory to build an instance of sgpp::datadriven::DataShufflingFunctor.
class DataShufflingFunctorRandom
A simple shuffling functor for data samples that performs a random shuffling of the data.
class DataShufflingFunctorSequential
A simple shuffling functor for data samples that performs no shuffling at all, i.e.
class DataSource
DataSource is a high level, easy to use interface for accessing data provided by a all kinds of sgpp::datadriven::SampleProvider.
class DataSourceBuilder
Generate an instance of sgpp::datadriven::DataSource using the Builder Pattern.
struct DataSourceConfig
Configuration structure used for all kinds of SampleProviders including default values.
class DataSourceCrossValidation
DataSourceCrossValidation is a high level interface to provide functionality for processing data using a cross validation enviroment.
class DataSourceFileTypeParser
Convenience class to convert strings to sgpp::datadriven::DataSourceFileType and generate string representations for values of sgpp::datadriven::DataSourceFileType.
class DataSourceIterator
Iterator object for walking convenient walking over the batches of a sgpp::datadriven::DataSource.
class DataSourceShufflingTypeParser
Convenience class to convert strings to sgpp::datadriven::DataSourceShufflingType and generate string representations for values of sgpp::datadriven::DataSourceShufflingType.
class DataSourceSplitting
DataSourceSlitting is a high level interface to provide functionality for processing data epoch-wise with a validation set that is retrieved at initialization time using the first samples the sample provider provides.
class DataTransformation
DataTransformation is an abstraction for an object that provides different transformations on datasets, for example Rosenblatt-transformation to get a uniform distribution over the unit cube.
class DataTransformationBuilder
Helper class to build all kinds of transformation based on given configuration.
struct DataTransformationConfig
class DataTransformationTypeParser
Convenience class to convert strings to sgpp::datadriven::DataTransformationType and generate string representations for values of sgpp::datadriven::DataTransformationType.
class DataVectorDistributed
class DBMatDatabase
A database class to store and retrieve online matrix decompositions for the sparse grid density estimation.
class DBMatDecompMatrixSolver
class DBMatDMS_SMW
This class solves an (lhs + lambda*I) * alpha = b system of linear equations after the offline and online phases are done.
class DBMatDMSChol
Class to solve the system of equations with a LL'-decomposed matrix.
class DBMatDMSDenseIChol
Solve the system of equations with a LL'-decomposed matrix where LL' is created by an iterative, incomplete cholesky factorization on a dense matrix.
class DBMatDMSOrthoAdapt
This class solves an (lhs + lambda*I) * alpha = b system of linear equations after the offline and online phases are done.
class DBMatObjectStore
class DBMatOffline
Class that is used to decompose and store the left-hand-side matrix for the density based classification approach (The classification is divided into two parts: the offline step that does not depend on the actual data and the online step that depends on the data).
class DBMatOfflineChol
DBMatOffline specialization that uses a cholesky factorization on a dense matrix.
class DBMatOfflineDenseIChol
DBMatOfflineChol specialization that uses a parallel, iterative incomplete cholesky factorization on a dense matrix.
class DBMatOfflineGE
DBMatOffline specialization as a base class for all algorithms based on gaussian elimination on a dense matrix.
class DBMatOfflineOrthoAdapt
class DBMatOfflinePermutable
class DBMatOnline
Class for objects that can be used in the online step of the classification (The classification is divided into two parts: the offline step that does not depend on the actual data and the online step that depends on the data)
class DBMatOnlineDE
Class that stores, generates and manipulates a density function during online phase in on/off learning.
class DBMatOnlineDE_SMW
class DBMatOnlineDEChol
class DBMatOnlineDEOrthoAdapt
class DBMatPermutationFactory
class DensityDifferenceEstimationMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for Density Difference Estimation.
class DensityDifferenceSystemMatrix
Class that implements the virtual class OperationMatrix for the application of density estimation for the Systemmatrix by using a density difference function for two input datasets.
struct DensityEstimationConfiguration
class DensityEstimationFitterFactory
Concrete factory to build instances of sgpp::datadriven::ModelFittingDensityEstimation.
class DensityEstimationMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for Density Estimation.
class DensityEstimationTypeParser
class DensityEstimator
class DensityRatioEstimationMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for Density Ratio Estimation.
class DensitySystemMatrix
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
class DiscreteParameter
concrete class for hyperparameter with discrete values
class DMConfigTools
class DMSystemMatrix
Class that implements the virtual class base::OperationMatrix for applications for the Systemmatrix.
class DMSystemMatrixBase
Abstract class that defines the virtual class base::OperationMatrix for classification and regression problems.
class DMSystemMatrixBaseSP
Abstract class that defines the virtual class base::OperationMatrix for classification and regression problems (single precision version)
class DMSystemMatrixDRE
Abstract class that defines the virtual class base::OperationMatrix for the density ratio estimation problem.
class DMWeightMatrix
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix with weight.
class EpanechnikovKernel
class FileSampleDecorator
FileSampleDecorator provides an interface to provide generic manipulations for various kinds of sgpp::datadriven::FileSampleProvider using the decorator pattern.
class FileSampleProvider
sgpp::datadriven::FileSampleProvider is an specialization of sgpp::datadriven::SampleProvider and provides an interface for all sample providers that get their samples from files.
class FitterConfiguration
General configuration object for fitters.
class FitterConfigurationClassification
Configuration for fitter scenarios using classification.
class FitterConfigurationDensityEstimation
Configuration for fitter scenarios using density estimation.
class FitterConfigurationLeastSquares
Configuration for fitter scenarios using least squares optimization.
class FitterFactory
Abstract factory to build all kinds of fitters/models based on a given configuration.
class FitterTypeParser
Convenience class to convert strings to sgpp::datadriven::FitterType and generate string representations for values of sgpp::datadriven::FitterType.
class Friedman1Generator
class Friedman2Generator
class Friedman3Generator
class GaussianKernel
struct GeometryConfiguration
class GeometryConfigurationParser
class GridFactory
Factory class to create grids based on a configuration file.
class GridPointBasedRefinementFunctor
Grid Point based refinement for classification problems solved by a SG density estimation approach.
class Harmonica
Class to host all methods required to perform the harmonica algorithm.
class HarmonicaHyperparameterOptimizer
HarmonicaHyperparameterOptimizer coordinates data input, fitting and validation modules similarly to SparseGridMiner.
struct HashGridPointCompare
class HPOConfig
Configuration for HyperparameterOptimizer.
class HyperParameter
Class to represent a hyperparameter.
class HyperparameterOptimizer
HyperparameterOptimizer uses fitters provided by a fitterFactory to test in a SparseGridMiner It offers access to different hyperparameter optimization procedures.
class KDEMaximumLikelihoodCrossValidation
class Kernel
class KernelDensityEstimator
class Learner
This class implements standard sparse grid regression with an arbitrary regularization operator.
class LearnerBase
Abstract class that implements a regression/classification learner based on spatial adaptive Sparse Grids.
class LearnerBaseSP
Abstract class that implements a regression/classification learner based on spatial adaptive Sparse Grids.
struct LearnerConfiguration
Structure that contains information about the learners behaviour.
class LearnerLeastSquaresIdentity
This class implements standard sparse grid regression with an Identity matrix as regularization operator.
class LearnerScenario
class LearnerSGD
LearnerSGD learns the data using stochastic gradient descent.
class LearnerSGDE
class LearnerSGDEConfiguration
class LearnerSGDEOnOffParallel
LearnerSGDEOnOffParallel learns the data using sparse grid density estimation.
class LearnerSVM
LearnerSVM learns the data using support vector machines and sparse grid kernels.
struct LearnerTiming
strcut to encapsulate the learner's timings during training
struct LearnerVectorizedPerformance
struct that defines return for calculation the performance of a vectorized learner
class LearnerVectorizedPerformanceCalculator
Class that provides functionality in order to determine a LearnerVectorized's performance.
class LeastSquaresRegressionFitterFactory
Concrete factory to build instances of sgpp::datadriven::ModelFittingLeastSquares.
class LeastSquaresRegressionMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for Least Squares Regression.
struct LevelIndexPair
Pair to hold the level and the index of a grid point in one dimension.
class LogDensitySystemMatrix
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
struct MakePositiveConfiguration
class MatrixDecompositionTypeParser
class MaximumLikelihoodCrossValidation
struct MergeGridNetworkMessage
Packet wrapper in MPI_Packet containing segmented data from the alpha vector of the trained system.
struct MessageTrackRequest
Structure that holds data for pending tracking requests that need to be checked against incoming messages.
class MetaLearner
class Metric
We use metrics to quantify approximation quality of a trained model.
class MinerFactory
Abstract factory to build different kinds of Miners based on a configuration which is parsed from a file.
class ModelFittingBase
Base class for arbitrary machine learning models based on adaptive sparse grids.
class ModelFittingBaseSingleGrid
Base class for models operating on a single grid (i.e.
class ModelFittingClassification
Fitter object that encapsulates density based classification using instances of ModelFittingDensityEstimation for each class.
class ModelFittingDensityDifferenceEstimationCG
Fitter object that encapsulates the usage of sparse grid density difference estimation with identity as regularization.
class ModelFittingDensityDifferenceEstimationOnOff
Fitter object that encapsulates the usage of sparse grid density difference estimation with identity as regularization.
class ModelFittingDensityEstimation
Abstract super class to encapsulate density estimation models such as using offline/-online splitting or conjugate gradients in order to solve the system.
class ModelFittingDensityEstimationCG
Fitter object that encapsulates the usage of sparse grid density estimation with identity as regularization.
class ModelFittingDensityEstimationCombi
Abstract super class to encapsulate density estimation models working with multiple Grids.
class ModelFittingDensityEstimationOnOff
Fitter object that encapsulates the usage of sparse grid density estimation with identity as regularization.
class ModelFittingDensityEstimationOnOffParallel
Fitter object that encapsulates the usage of sparse grid density estimation with identity as regularization.
class ModelFittingDensityRatioEstimation
Fitter object that encapsulates the usage of sparse grid based density ratio estimation, based on the regression model with identity as regularization.
class ModelFittingLeastSquares
Fitter object that encapsulates the usage of sparse grid based regression with identity as regularization.
class MortonOrder
struct MPI_Packet
A packet sent over MPI, using a command as a descriptor, and a wrapped package in the payload for data.
class MPIMethods
class MPIRequestPool
class MPITaskScheduler
class MSE
Metric that quantifies the difference between predicted values and actual values in terms of mean squared error (MSE).
class MultiGridRefinementFunctor
Abstract super-class for refinement functors operating on multiple grids.
class MultipleClassRefinementFunctor
Multiple class refinement is based on the zero-crossing based refinement.
class MultiSurplusRefinementFunctor
Wrapper of SurplusRefinementFunctor for multi grid scenarios.
class NearestNeighbors
The NearestNeighbors class.
class NegativeLogLikelihood
Metric that quantifies the likelihood of a dataset given the density function.
class OperationCovariance
This class provides the covariance matrix a sparse grid function.
class OperationDensityConditional
Conditionalize Probability Density Function.
class OperationDensityConditionalKDE
class OperationDensityConditionalLinear
Marginalize Probability Density Function.
class OperationDensityMarginalize
Marginalize Probability Density Function.
class OperationDensityMarginalizeKDE
Marginalize Probability Density Function.
class OperationDensityMarginalizeLinear
Marginalize Probability Density Function.
class OperationDensityMargTo1D
Marginalize Probability Density Function.
class OperationDensityRejectionSampling
Sampling on all dimensions.
class OperationDensityRejectionSamplingLinear
Sampling with rejection sampling method.
class OperationDensitySampling
Sampling on all dimensions.
class OperationDensitySampling1D
Sample 1D Probability Density Function.
class OperationDensitySampling1DLinear
class OperationDensitySamplingLinear
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationDotProductLinear
class OperationDotProductModLinear
class OperationInverseRosenblattTransformation
Sampling on all dimensions.
class OperationInverseRosenblattTransformation1DBspline
class OperationInverseRosenblattTransformation1DBsplineBoundary
class OperationInverseRosenblattTransformation1DBsplineClenshawCurtis
class OperationInverseRosenblattTransformation1DLinear
class OperationInverseRosenblattTransformation1DModBspline
class OperationInverseRosenblattTransformation1DModBsplineClenshawCurtis
class OperationInverseRosenblattTransformation1DModPoly
class OperationInverseRosenblattTransformation1DModPolyClenshawCurtis
class OperationInverseRosenblattTransformation1DPoly
class OperationInverseRosenblattTransformation1DPolyBoundary
class OperationInverseRosenblattTransformation1DPolyClenshawCurtis
class OperationInverseRosenblattTransformation1DPolyClenshawCurtisBoundary
class OperationInverseRosenblattTransformationBspline
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationBsplineBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationBsplineClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationKDE
Do inverse transformation in all dimensions.
class OperationInverseRosenblattTransformationLinear
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationModBspline
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationModBsplineClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationModPoly
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationModPolyClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationPoly
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationPolyBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationPolyClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationInverseRosenblattTransformationPolyClenshawCurtisBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationLimitFunctionValueRange
class OperationMakePositive
This class enforces the function value range of a sparse grid function to be larger than 0.
class OperationMakePositiveCandidateSetAlgorithm
class OperationMakePositiveFindIntersectionCandidates
class OperationMakePositiveFindIntersectionCandidatesJoin
class OperationMakePositiveHybridFindIntersectionCandidates
class OperationMakePositiveInterpolateBoundaryOfSupport
class OperationMakePositiveInterpolateExp
class OperationMakePositiveInterpolateFunction
class OperationMakePositiveInterpolationAlgorithm
class OperationMakePositiveLoadFullGridCandidates
class OperationMakePositiveSetToZero
class OperationMultiEvalCuda
OperationMultipleEval for polynomial basis functions (grad >= 2) using CUDA on grids without boundary nodes.
class OperationMultiEvalHPX
This class is a HPX wrapper for other MultiEval-operations that uses a very simple master-slave distributed processing.
class OperationMultiEvalModMaskStreaming
class OperationMultiEvalMPI
This class is a MPI wrapper for other MultiEval-operations that uses a very simple master-slave MPI parallelization.
class OperationMultiEvalStreaming
class OperationMultiEvalStreamingBSpline
class OperationMultiEvalStreamingBSplineOCL
class OperationMultiEvalStreamingModOCLFastMultiPlatform
class OperationMultiEvalStreamingModOCLMaskMultiPlatform
class OperationMultiEvalStreamingModOCLOpt
class OperationMultiEvalStreamingModOCLUnified
class OperationMultipleEvalConfiguration
class OperationMultipleEvalDistributed
Distributed interface for OperationMultipleEval.
class OperationMultipleEvalLinearDistributed
This class is a distributed version of sgpp::base::OperationMultipleEvalLinear, it uses ScaLAPACK.
class OperationMultipleEvalMatrix
wrapper class for matrix multiplication for use in solver
class OperationMultipleEvalModLinearDistributed
This class is a distributed version of sgpp::base::OperationMultipleEvalModLinear, it uses ScaLAPACK.
class OperationMultipleEvalSubspaceCombined
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
class OperationMultipleEvalSubspaceSimple
Multiple evaluation operation that uses the subspace structure to save work compared to the naive or streaming variants.
class OperationPiecewiseConstantRegression
class OperationRegularizationDiagonal
Implementation of the application of a diagonal matrix to a DataVector for regularization.
class OperationRegularizationDiagonalLinearBoundary
Implementation of the application of a diagonal matrix to a DataVector for regularization.
class OperationRosenblattTransformation
Sampling on all dimensions.
class OperationRosenblattTransformation1DBspline
class OperationRosenblattTransformation1DBsplineBoundary
class OperationRosenblattTransformation1DBsplineClenshawCurtis
class OperationRosenblattTransformation1DLinear
class OperationRosenblattTransformation1DModBspline
class OperationRosenblattTransformation1DModBsplineClenshawCurtis
class OperationRosenblattTransformation1DModPoly
class OperationRosenblattTransformation1DModPolyClenshawCurtis
class OperationRosenblattTransformation1DPoly
class OperationRosenblattTransformation1DPolyBoundary
class OperationRosenblattTransformation1DPolyClenshawCurtis
class OperationRosenblattTransformation1DPolyClenshawCurtisBoundary
class OperationRosenblattTransformationBspline
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationBsplineBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationBsplineClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationKDE
Do transformation in all dimensions.
class OperationRosenblattTransformationLinear
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationModBspline
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationModBsplineClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationModPoly
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationModPolyClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationPoly
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationPolyBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationPolyClenshawCurtis
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationRosenblattTransformationPolyClenshawCurtisBoundary
keep applying marginalize to function until it's reduced to only 1 dimension
class OperationTest
Operation the tests the function that is applied the current Sparse sgpp::base::Grid at a given point.
class OperationTestLinear
This class implements OperationTest for a grids with linear basis ansatzfunctions without boundaries.
class OperationTestLinearBoundary
This class implements OperationTest for a grids with linear basis ansatzfunctions with boundaries.
class OperationTestLinearStretched
This class implements OperationTest for a grids with linearstretched basis ansatzfunctions without boundaries.
class OperationTestLinearStretchedBoundary
This class implements OperationTest for a grids with linear basis ansatzfunctions with boundaries.
class OperationTestModBspline
This class implements OperationTest for a grids with modified bspline basis functions with a certain degree.
class OperationTestModLinear
This class implements sgpp::base::OperationEval for a grids with mod linear basis ansatzfunctions with.
class OperationTestModPoly
This class implements OperationTest for a grids with mod poly basis ansatzfunctions with.
class OperationTestModWavelet
This class implements OperationTest for a grid with mod wavelet basis ansatzfunctions.
class OperationTestPoly
This class implements OperationTest for a grids with poly basis ansatzfunctions with.
class OperationTestPrewavelet
This class implements OperationTest for a grids with prewavelet basis ansatzfunctions without boundaries.
class OperationTransformation1D
Sample 1D Probability Density Function.
struct ParallelConfiguration
Struct that stores all the configuration information for parallelization with ScaLAPACK.
class PartitioningTool
The methods in this class calculate size and offset of a segment for a partition of a domain.
class PendingMPIRequest
class PiecewiseConstantSmoothedRegressionSystemMatrix
Class that implements the virtual class OperationMatrix for the application of classification for the Systemmatrix by using a density function.
class PolynomialChaosExpansion
a PCE object providing different methods to calculate the PCE coefficients and evaluating the expansion
class PrimalDualSVM
Implementation of a support vector machine in primal formulation which additionally stores support vectors.
class RefinementHandler
class RefinementMonitor
Superclass for refinement monitors.
class RefinementMonitorConvergence
A monitor to decide if a learning algorithm has converged.
class RefinementMonitorFactory
Factory to create refinement monitors.
class RefinementMonitorPeriodic
A monitor that decides whether refinements should be performed using a simple periodic approach: After at least a certain amount of instances has arrived, the monitor will allow a new refinement.
struct RefinementResult
Structure to hold the grid modifications for a refinement cycle for one class.
struct RefinementResultNetworkMessage
Packet wrapped in an UPDATE_GRID MPI_Packet, containing segmented changes for a specified class.
struct RefinementResultSystemMatrixNetworkMessage
Packet wrapped in a RefinementResultNetwork Message that contains additional information required when updating the system matrix.
class RegressionLearner
The RegressionLearner class Solves a regression problem with continuous target vector.
struct RegularizationConfiguration
class RegularizationTypeParser
class ResidualScore
Metric that is based on a residual score of the model.
class RosenblattTransformation
struct RosenblattTransformationConfig
Configuration structure for Rosenblatt transformation including default values.
class RoundRobinScheduler
class RuleOfThumb
class SampleProvider
SampleProvider is an abstraction for object that provide sample data from various sources for example datasets from files (ARFF, CSV) or synthetic datasets generated by sampling functions (Friedmann datasets).
class Scorer
Base class for supervised learning used to fit a model and quantify accuracy using a sgpp::datadriven::Metric with either testing or cross validation.
struct ScorerConfiguration
Set of parameters to define a scorer instance.
class ScorerFactory
Factory to build the scorer.
class ScorerMetricTypeParser
Convenience class to convert strings to sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType and generate string representations for values of sgpp::datadriven::ScorerMetricType or sgpp::datadriven::RegularizationMetricType.
class ScottsRule
struct SGDEConfiguration
class SilvermansRule
class SortedDataset
Dataset that can be ordered. Accessing the included DataMatrix might invalidate the order.
class SparseGridDensityEstimator
class SparseGridDensityEstimatorConfiguration
class SparseGridMiner
SparseGridMiner models the entire mining process for data mining with sparse grids.
class SparseGridMinerCrossValidation
SparseGridMinerCrossValidation models a datamining process that involves cross validation to validate the accuracy of the model itself.
class SparseGridMinerSplitting
SparseGridMiner models a datamining process that involves a dataset that is first split into validation and training data.
class SparseGridMinerSplittingTwoDatasets
SparseGridMinerSplittingTwoDatasets models a datamining process that involves two input datasets that are first split into validation and training data.
struct StencilConfiguration
class StreamingBSplineOCLKernelImpl
class StreamingBSplineOCLKernelSourceBuilder
class SubspaceNodeCombined
class SubspaceNodeSimple
class SystemMatrixDensityRatioEstimation
Class that implements the virtual class base::OperationMatrix for the application of density ratio estimation for SystemMatrixDRE.
class SystemMatrixLeastSquaresIdentity
Class that implements the virtual class base::OperationMatrix for the application of classification for the Systemmatrix.
class TestsetConfiguration
class TunableParameter
class UniversalMinerFactory
Concrete Factory that builds an instance of sgpp::datadriven::SparseGridMiner for the fitting task specified by the configuration.
struct VectorHash
Hash to make an unordered_set over an vector of size_t's possible.
struct VisualizationGeneralConfig
struct VisualizationParameters
class VisualizationTypesParser
Convenience class to convert strings to sgpp::datadriven::VisualizationTypesParser and generate string representations for values of sgpp::datadriven::VisualizationFileType.
class Visualizer
class VisualizerClassification
class VisualizerConfiguration
class VisualizerDensityEstimation
class VisualizerDummy
class ZeroCrossingRefinementFunctor
Zero-crossing-based refinement uses zero crossings of the difference PDFS f_1 - f_2 to determine areas of interest for the refinement process.
Typedefs
typedef std::vector< LevelIndexPair > LevelIndexVector
Vector that holds level index pairs for every dimensions.
Enumerations
enum class BandwidthOptimizationType { NONE , SILVERMANSRULE , SCOTTSRULE , MAXIMUMLIKELIHOOD }
enum class DataSourceFileType { NONE , ARFF , CSV }
Supported file types for sgpp::datadriven::FileSampleProvider.
enum class DataSourceShufflingType { random , sequential }
Enumeration of all supported shuffling types used to permute samples in a dataset.
enum class DataTransformationType { NONE , ROSENBLATT }
Supported transformation types for sgpp::datadriven::DataTransformation.
enum class DensityEstimationType { CG , Decomposition }
enum class distributionType {
Normal , Beta , Uniform , Exponential ,
Gamma
}
enum class FitterType {
RegressionLeastSquares , DensityEstimation , DensityRatioEstimation , DensityDifferenceEstimation ,
Classification
}
Different fitter scenarios have different default values and support different operations.
enum class InternalPrecision { Float , Double }
enum class KernelType { GAUSSIAN , EPANECHNIKOV }
enum class LearnerMode { LEARN , LEARNCOMPARE , LEARNTEST }
enum class MakePositiveCandidateSearchAlgorithm { FullGrid , Intersections , HybridFullIntersections , IntersectionsJoin }
enum class MakePositiveInterpolationAlgorithm { SetToZero , InterpolateExp , InterpolateBoundaries1d , InterpolateFunction }
enum class MatrixDecompositionType {
LU , Eigen , Chol , DenseIchol ,
OrthoAdapt , SMW_ortho , SMW_chol
}
enum MPI_COMMAND_ID {
NULL_COMMAND , UPDATE_GRID , MERGE_GRID , ASSIGN_BATCH ,
COMPUTE_UPDATE_SYSTEM_MATRIX_DECOMPOSITION , SHUTDOWN , WORKER_SHUTDOWN_SUCCESS
}
Different commands sent over MPI to allow the receiver to identify the message's contents.
enum class OperationMultipleEvalMPIType { NONE , MASTERSLAVE , HPX }
enum class OperationMultipleEvalSubType {
DEFAULT , SIMPLE , COMBINED , OCL ,
OCLFASTMP , OCLMP , OCLMASKMP , OCLOPT ,
OCLUNIFIED , CUDA
}
enum class OperationMultipleEvalType {
DEFAULT , STREAMING , SUBSPACELINEAR , ADAPTIVE ,
MORTONORDER , SCALAPACK
}
enum RefinementResultsUpdateType { ADDED_GRID_POINTS_LIST , DELETED_GRID_POINTS_LIST , SYSTEM_MATRIX_DECOMPOSITION }
The type of message received in a UPDATE_GRID message type.
enum class RegularizationMetricType { mse , nll , accuracy , residual }
enum class RegularizationType {
Identity , Laplace , Diagonal , Lasso ,
ElasticNet , GroupLasso
}
enum class ScorerMetricType { mse , nll , accuracy }
Enumeration of all supported metrics used to quantify approximation quality of a trained model.
enum class StencilType {
DirectNeighbour , AllHierarchicalParent , NextHierarchicalParent , Block ,
None
}
enum TaskType { TRAIN_FROM_BATCH , RECOMPUTE_SYSTEM_MATRIX_DECOMPOSITION }
Used for the MPI Task Scheduler to differentiate between assigning tasks of different types.
enum class VisualizationFileType { CSV , json }
Functions
DensityOCLMultiPlatform::OperationDensity * createDensityOCLMultiPlatformConfigured (base::Grid &grid, size_t dimension, double lambda, base::OCLOperationConfiguration *parameters, size_t platform_id, size_t device_id)
DensityOCLMultiPlatform::OperationDensity * createDensityOCLMultiPlatformConfigured (base::Grid &grid, size_t dimension, double lambda, std::string opencl_conf)
Generates opencl density multiplication operation.
DensityOCLMultiPlatform::OperationDensity * createDensityOCLMultiPlatformConfigured (base::Grid &grid, size_t dimension, double lambda, std::string opencl_conf, size_t platform_id, size_t device_id)
Generates opencl density multiplication operation given opencl device and configuration file.
DensityOCLMultiPlatform::OperationDensity * createDensityOCLMultiPlatformConfigured (int *gridpoints, size_t gridsize, size_t dimension, double lambda, base::OCLOperationConfiguration *parameters, size_t platform_id, size_t device_id)
DensityOCLMultiPlatform::OperationDensity * createDensityOCLMultiPlatformConfigured (int *gridpoints, size_t gridsize, size_t dimension, double lambda, std::string opencl_conf, size_t platform_id, size_t device_id)
Generates opencl density multiplication operation given opencl device and a serialized grid.
DensityOCLMultiPlatform::OperationCreateGraphOCL * createNearestNeighborGraphConfigured (base::DataMatrix &dataset, size_t k, size_t dimensions, std::string opencl_conf)
Generates the k nearest neighbors graph creation.
DensityOCLMultiPlatform::OperationCreateGraphOCL * createNearestNeighborGraphConfigured (base::DataMatrix &dataset, size_t k, size_t dimensions, std::string opencl_conf, size_t platformid, size_t devicdeid)
Generates the k nearest neighbors graph creation using a specific opencl device and a datamatrix.
DensityOCLMultiPlatform::OperationCreateGraphOCL * createNearestNeighborGraphConfigured (double *dataset, size_t dataset_size, size_t k, size_t dimensions, sgpp::base::OCLOperationConfiguration *parameters, size_t platformid, size_t deviceid)
DensityOCLMultiPlatform::OperationCreateGraphOCL * createNearestNeighborGraphConfigured (double *dataset, size_t dataset_size, size_t k, size_t dimensions, std::string opencl_conf, size_t platformid, size_t devicdeid)
Generates the k nearest neighbors graph creation using a specific opencl device and a double vector.
base::OperationMultipleEval * createStreamingBSplineOCLConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
base::OperationMultipleEval * createStreamingModOCLFastMultiPlatformConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
base::OperationMultipleEval * createStreamingModOCLMaskMultiPlatformConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
base::OperationMultipleEval * createStreamingModOCLOptConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
base::OperationMultipleEval * createStreamingModOCLUnifiedConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
base::OperationMultipleEval * createStreamingOCLMultiPlatformConfigured (base::Grid &grid, base::DataMatrix &dataset, sgpp::datadriven::OperationMultipleEvalConfiguration &configuration)
Factory method for creating a new instance of this variant of OperationMultipleEval.
DensityOCLMultiPlatform::OperationPruneGraphOCL * pruneNearestNeighborGraphConfigured (base::Grid &grid, size_t dimensions, base::DataVector &alpha, base::DataMatrix &data, double treshold, size_t k, std::string opencl_conf)
Generates the graph pruning operation.
DensityOCLMultiPlatform::OperationPruneGraphOCL * pruneNearestNeighborGraphConfigured (base::Grid &grid, size_t dimensions, base::DataVector &alpha, base::DataMatrix &data, double treshold, size_t k, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the graph pruning operation for a specific opencl device.
DensityOCLMultiPlatform::OperationPruneGraphOCL * pruneNearestNeighborGraphConfigured (int *gridpoints, size_t gridsize, size_t dimensions, double *alpha, base::DataMatrix &data, double treshold, size_t k, sgpp::base::OCLOperationConfiguration *parameters, size_t platformid, size_t deviceid)
DensityOCLMultiPlatform::OperationPruneGraphOCL * pruneNearestNeighborGraphConfigured (int *gridpoints, size_t gridsize, size_t dimensions, double *alpha, base::DataMatrix &data, double treshold, size_t k, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the graph pruning operation for a specific opencl device using a serialized grid.
template<class BASIS >
void test_calculateROCcurve (base::GridStorage *storage, BASIS &basis, base::DataVector &alpha, base::DataMatrix &data, base::DataVector &classes, base::DataVector &thresholds, base::DataMatrix &ROC_curve)
Returns the number of correctly classified instances in data without boundaries.
template<class BASIS >
double test_dataset (base::GridStorage *storage, BASIS &basis, base::DataVector &alpha, base::DataMatrix &data, base::DataVector &classes)
Returns the number of correctly classified instances in data without boundaries.
template<class BASIS >
double test_dataset_mse (base::GridStorage *storage, BASIS &basis, base::DataVector &alpha, base::DataMatrix &data, base::DataVector &refValues)
Returns the MSE for given functions values at the evaluation points.
template<class BASIS >
double test_datasetWithCharacteristicNumber (base::GridStorage *storage, BASIS &basis, base::DataVector &alpha, base::DataMatrix &data, base::DataVector &classes, base::DataVector &charaNumbers, double threshold)
Returns the number of correctly classified instances in data without boundaries.
void validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::LearnerMode *target_type, int)
void validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::OperationMultipleEvalSubType *target_type, int)
void validate (boost::any &v, const std::vector< std::string > &values, sgpp::datadriven::OperationMultipleEvalType *target_type, int)
Variables
const int csrc_ = 7
const int ctxt_ = 1
const int dtype_ = 0
const int kDescriptor_ = 9
const std::string keyDecompositionType = "decomposition"
const std::string keyDensityEstimationConfiguration = "densityEstimationConfiguration"
const std::string keyFilepath = "filepath"
const std::string keyGridConfiguration = "gridConfiguration"
const std::string keyGridDimension = "dimension"
const std::string keyGridLevel = "level"
const std::string keyGridType = "type"
const std::string keyRegularizationConfiguration = "regularizationConfiguration"
const std::string keyRegularizationStrength = "lambda"
const int lld_ = 8
const char *const lowerTriangular = "L"
const int m_ = 2
const int mb_ = 4
const int n_ = 3
const int nb_ = 5
const char *const pblasConjugate = "C"
const char *const pblasNoTranspose = "N"
const char *const pblasTranspose = "T"
const int rsrc_ = 6
const char *const upperTriangular = "U"
Typedef Documentation
LevelIndexVector
typedef std::vector<LevelIndexPair> sgpp::datadriven::LevelIndexVector
Vector that holds level index pairs for every dimensions.
Enumeration Type Documentation
BandwidthOptimizationType
enum class sgpp::datadriven::BandwidthOptimizationType strong
Enumerator
NONE
SILVERMANSRULE
SCOTTSRULE
MAXIMUMLIKELIHOOD
DataSourceFileType
enum class sgpp::datadriven::DataSourceFileType strong
Supported file types for sgpp::datadriven::FileSampleProvider.
Enumerator
NONE
ARFF
CSV
DataSourceShufflingType
enum class sgpp::datadriven::DataSourceShufflingType strong
Enumeration of all supported shuffling types used to permute samples in a dataset.
An entry exists for each object that derives from sgpp::datadriven::DataShufflingFunctor. Used for configuration and factory methods.
Enumerator
random
sequential
DataTransformationType
enum class sgpp::datadriven::DataTransformationType strong
Supported transformation types for sgpp::datadriven::DataTransformation.
Enumerator
NONE
ROSENBLATT
DensityEstimationType
enum class sgpp::datadriven::DensityEstimationType strong
Enumerator
CG
Decomposition
distributionType
enum class sgpp::datadriven::distributionType strong
Enumerator
Normal
Beta
Uniform
Exponential
Gamma
FitterType
enum class sgpp::datadriven::FitterType strong
Different fitter scenarios have different default values and support different operations.
Enumerator
RegressionLeastSquares
DensityEstimation
DensityRatioEstimation
DensityDifferenceEstimation
Classification
InternalPrecision
enum class sgpp::datadriven::InternalPrecision strong
Enumerator
Float
Double
KernelType
enum class sgpp::datadriven::KernelType strong
Enumerator
GAUSSIAN
EPANECHNIKOV
LearnerMode
enum class sgpp::datadriven::LearnerMode strong
Enumerator
LEARN
LEARNCOMPARE
LEARNTEST
MakePositiveCandidateSearchAlgorithm
enum class sgpp::datadriven::MakePositiveCandidateSearchAlgorithm strong
Enumerator
FullGrid
Intersections
HybridFullIntersections
IntersectionsJoin
MakePositiveInterpolationAlgorithm
enum class sgpp::datadriven::MakePositiveInterpolationAlgorithm strong
Enumerator
SetToZero
InterpolateExp
InterpolateBoundaries1d
InterpolateFunction
MatrixDecompositionType
enum class sgpp::datadriven::MatrixDecompositionType strong
Enumerator
LU
Eigen
Chol
DenseIchol
OrthoAdapt
SMW_ortho
SMW_chol
MPI_COMMAND_ID
enum sgpp::datadriven::MPI_COMMAND_ID
Different commands sent over MPI to allow the receiver to identify the message's contents.
Enumerator
NULL_COMMAND
Used to identify packets where the command id has not been set.
UPDATE_GRID
A packet that contains changes to the grid or the system matrix.
MERGE_GRID
A packet that contains results from a training.
ASSIGN_BATCH
A packet that assigns a batch with specified parameters to a worker.
COMPUTE_UPDATE_SYSTEM_MATRIX_DECOMPOSITION
A packet that assigns updating the system matrix decomposition to a worker.
SHUTDOWN
A packet that instructs a worker to shutdown its MPI facilities after completing all requests.
WORKER_SHUTDOWN_SUCCESS
A confirmation packet sent by a worker to acknowledge all requests were completed.
OperationMultipleEvalMPIType
enum class sgpp::datadriven::OperationMultipleEvalMPIType strong
Enumerator
NONE
MASTERSLAVE
HPX
OperationMultipleEvalSubType
enum class sgpp::datadriven::OperationMultipleEvalSubType strong
Enumerator
DEFAULT
SIMPLE
COMBINED
OCL
OCLFASTMP
OCLMP
OCLMASKMP
OCLOPT
OCLUNIFIED
CUDA
OperationMultipleEvalType
enum class sgpp::datadriven::OperationMultipleEvalType strong
Enumerator
DEFAULT
STREAMING
SUBSPACELINEAR
ADAPTIVE
MORTONORDER
SCALAPACK
RefinementResultsUpdateType
enum sgpp::datadriven::RefinementResultsUpdateType
The type of message received in a UPDATE_GRID message type.
Enumerator
ADDED_GRID_POINTS_LIST
Packet contains a set of coordinates for newly created grid points.
DELETED_GRID_POINTS_LIST
Packet contains a set of indices for grid points which were deleted.
SYSTEM_MATRIX_DECOMPOSITION
Packet contains a part of an updated system matrix decomposition.
RegularizationMetricType
enum class sgpp::datadriven::RegularizationMetricType strong
Enumerator
mse
nll
accuracy
residual
RegularizationType
enum class sgpp::datadriven::RegularizationType strong
Enumerator
Identity
Laplace
Diagonal
Lasso
ElasticNet
GroupLasso
ScorerMetricType
enum class sgpp::datadriven::ScorerMetricType strong
Enumeration of all supported metrics used to quantify approximation quality of a trained model.
An entry exists for each object that derives from sgpp::datadriven::Metric. Used for configuration and factory methods.
Enumerator
mse
nll
accuracy
StencilType
enum class sgpp::datadriven::StencilType strong
Enumerator
DirectNeighbour
AllHierarchicalParent
NextHierarchicalParent
Block
None
TaskType
enum sgpp::datadriven::TaskType
Used for the MPI Task Scheduler to differentiate between assigning tasks of different types.
Enumerator
TRAIN_FROM_BATCH
RECOMPUTE_SYSTEM_MATRIX_DECOMPOSITION
VisualizationFileType
enum class sgpp::datadriven::VisualizationFileType strong
Enumerator
CSV
json
Function Documentation
createDensityOCLMultiPlatformConfigured() [1/5]
DensityOCLMultiPlatform::OperationDensity * sgpp::datadriven::createDensityOCLMultiPlatformConfigured (base::Grid & grid, size_t dimension, double lambda, base::OCLOperationConfiguration * parameters, size_t platform_id, size_t device_id)
References grid(), lambda, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), sgpp::datadriven::clusteringmpi::DensityRhsWorker::DensityRhsWorker(), sgpp::datadriven::clusteringmpi::DensityWorker::DensityWorker(), main(), and main().
createDensityOCLMultiPlatformConfigured() [2/5]
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity * sgpp::datadriven::createDensityOCLMultiPlatformConfigured (base::Grid & grid, size_t dimension, double lambda, std::string opencl_conf)
Generates opencl density multiplication operation.
References json::DictNode::contains(), grid(), lambda, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
createDensityOCLMultiPlatformConfigured() [3/5]
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity * sgpp::datadriven::createDensityOCLMultiPlatformConfigured (base::Grid & grid, size_t dimension, double lambda, std::string opencl_conf, size_t platform_id, size_t device_id)
Generates opencl density multiplication operation given opencl device and configuration file.
References grid(), lambda, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
createDensityOCLMultiPlatformConfigured() [4/5]
DensityOCLMultiPlatform::OperationDensity * sgpp::datadriven::createDensityOCLMultiPlatformConfigured (int * gridpoints, size_t gridsize, size_t dimension, double lambda, base::OCLOperationConfiguration * parameters, size_t platform_id, size_t device_id)
References lambda, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
createDensityOCLMultiPlatformConfigured() [5/5]
sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity * sgpp::datadriven::createDensityOCLMultiPlatformConfigured (int * gridpoints, size_t gridsize, size_t dimension, double lambda, std::string opencl_conf, size_t platform_id, size_t device_id)
Generates opencl density multiplication operation given opencl device and a serialized grid.
References lambda, and sgpp::datadriven::DensityOCLMultiPlatform::OperationDensity::load_default_parameters().
createNearestNeighborGraphConfigured() [1/4]
DensityOCLMultiPlatform::OperationCreateGraphOCL * sgpp::datadriven::createNearestNeighborGraphConfigured (base::DataMatrix & dataset, size_t k, size_t dimensions, std::string opencl_conf)
Generates the k nearest neighbors graph creation.
References json::DictNode::contains(), dataset, and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters().
createNearestNeighborGraphConfigured() [2/4]
DensityOCLMultiPlatform::OperationCreateGraphOCL * sgpp::datadriven::createNearestNeighborGraphConfigured (base::DataMatrix & dataset, size_t k, size_t dimensions, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the k nearest neighbors graph creation using a specific opencl device and a datamatrix.
References dataset, and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters().
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), sgpp::datadriven::clusteringmpi::GraphCreationWorker::GraphCreationWorker(), main(), and sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::PrunedGraphCreationWorker().
createNearestNeighborGraphConfigured() [3/4]
DensityOCLMultiPlatform::OperationCreateGraphOCL * sgpp::datadriven::createNearestNeighborGraphConfigured (double * dataset, size_t dataset_size, size_t k, size_t dimensions, sgpp::base::OCLOperationConfiguration * parameters, size_t platformid, size_t deviceid)
References dataset, and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters().
createNearestNeighborGraphConfigured() [4/4]
DensityOCLMultiPlatform::OperationCreateGraphOCL * sgpp::datadriven::createNearestNeighborGraphConfigured (double * dataset, size_t dataset_size, size_t k, size_t dimensions, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the k nearest neighbors graph creation using a specific opencl device and a double vector.
References dataset, and sgpp::datadriven::DensityOCLMultiPlatform::OperationCreateGraphOCL::load_default_parameters().
createStreamingBSplineOCLConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingBSplineOCLConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
References dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
Referenced by sgpp::op_factory::createOperationMultipleEval().
createStreamingModOCLFastMultiPlatformConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingModOCLFastMultiPlatformConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
References sgpp::datadriven::StreamingModOCLFastMultiPlatform::Configuration::augmentDefaultParameters(), dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
Referenced by sgpp::op_factory::createOperationMultipleEval().
createStreamingModOCLMaskMultiPlatformConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingModOCLMaskMultiPlatformConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
References sgpp::datadriven::StreamingModOCLMaskMultiPlatform::Configuration::augmentDefaultParameters(), dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
Referenced by sgpp::op_factory::createOperationMultipleEval().
createStreamingModOCLOptConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingModOCLOptConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
References sgpp::datadriven::StreamingModOCLOpt::Configuration::augmentDefaultParameters(), dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
Referenced by sgpp::op_factory::createOperationMultipleEval().
createStreamingModOCLUnifiedConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingModOCLUnifiedConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
References sgpp::datadriven::StreamingModOCLUnified::Configuration::augmentDefaultParameters(), dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
createStreamingOCLMultiPlatformConfigured()
base::OperationMultipleEval * sgpp::datadriven::createStreamingOCLMultiPlatformConfigured (base::Grid & grid, base::DataMatrix & dataset, sgpp::datadriven::OperationMultipleEvalConfiguration & configuration)
Factory method for creating a new instance of this variant of OperationMultipleEval.
This factory method configures the resulting object by using the parameters of the provided configuration. If no parameters are provided, the default parameter values are used. If a configuration is provided, but some entries were not set, this class adds the missing entries with their default values. This class is the non-templated entry point for the templated inner objects. Templates are used to implement different floating point precision.
See also
OperationMultiEvalStreamingOCLMultiPlatform
Parameters
grid The sparse grid to evaluate
dataset The datapoints to evaluate
configuration Configuration that may contain a parameter object for configuration details
References sgpp::datadriven::StreamingOCLMultiPlatform::Configuration::augmentDefaultParameters(), dataset, sgpp::datadriven::OperationMultipleEvalConfiguration::getParameters(), and grid().
Referenced by sgpp::op_factory::createOperationMultipleEval().
pruneNearestNeighborGraphConfigured() [1/4]
sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL * sgpp::datadriven::pruneNearestNeighborGraphConfigured (base::Grid & grid, size_t dimensions, base::DataVector & alpha, base::DataMatrix & data, double treshold, size_t k, std::string opencl_conf)
Generates the graph pruning operation.
References alpha, json::DictNode::contains(), grid(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters().
pruneNearestNeighborGraphConfigured() [2/4]
sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL * sgpp::datadriven::pruneNearestNeighborGraphConfigured (base::Grid & grid, size_t dimensions, base::DataVector & alpha, base::DataMatrix & data, double treshold, size_t k, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the graph pruning operation for a specific opencl device.
References alpha, grid(), and sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters().
Referenced by sgpp::datadriven::ClusteringOCL::OperationClusteringOCL< T >::calculate_clusters(), main(), and sgpp::datadriven::clusteringmpi::PrunedGraphCreationWorker::PrunedGraphCreationWorker().
pruneNearestNeighborGraphConfigured() [3/4]
DensityOCLMultiPlatform::OperationPruneGraphOCL * sgpp::datadriven::pruneNearestNeighborGraphConfigured (int * gridpoints, size_t gridsize, size_t dimensions, double * alpha, base::DataMatrix & data, double treshold, size_t k, sgpp::base::OCLOperationConfiguration * parameters, size_t platformid, size_t deviceid)
References alpha, and sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters().
pruneNearestNeighborGraphConfigured() [4/4]
sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL * sgpp::datadriven::pruneNearestNeighborGraphConfigured (int * gridpoints, size_t gridsize, size_t dimensions, double * alpha, base::DataMatrix & data, double treshold, size_t k, std::string opencl_conf, size_t platformid, size_t deviceid)
Generates the graph pruning operation for a specific opencl device using a serialized grid.
References alpha, and sgpp::datadriven::DensityOCLMultiPlatform::OperationPruneGraphOCL::load_default_parameters().
test_calculateROCcurve()
template<class BASIS > void sgpp::datadriven::test_calculateROCcurve (base::GridStorage * storage, BASIS & basis, base::DataVector & alpha, base::DataMatrix & data, base::DataVector & classes, base::DataVector & thresholds, base::DataMatrix & ROC_curve)
Returns the number of correctly classified instances in data without boundaries.
Parameters
storage base::GridStorage object that contains the grid points
basis reference to class that implements to current basis
alpha the coefficients of the grid points
data the data the should be tested
classes the reference classes
thresholds the thresholds (between -1.0 and 1.0) for calculating the ROC curve
ROC_curve DataMatrix into which the ROC curve is stored
References alpha, sgpp::base::DataVector::get(), sgpp::base::DataMatrix::getNrows(), sgpp::base::DataVector::getSize(), sgpp::base::DataMatrix::resize(), sgpp::base::DataMatrix::set(), and test_datasetWithCharacteristicNumber().
Referenced by sgpp::datadriven::OperationTestLinear::calculateROCcurve(), sgpp::datadriven::OperationTestLinearBoundary::calculateROCcurve(), sgpp::datadriven::OperationTestLinearStretched::calculateROCcurve(), sgpp::datadriven::OperationTestLinearStretchedBoundary::calculateROCcurve(), sgpp::datadriven::OperationTestModBspline::calculateROCcurve(), sgpp::datadriven::OperationTestModLinear::calculateROCcurve(), sgpp::datadriven::OperationTestModPoly::calculateROCcurve(), sgpp::datadriven::OperationTestModWavelet::calculateROCcurve(), sgpp::datadriven::OperationTestPoly::calculateROCcurve(), and sgpp::datadriven::OperationTestPrewavelet::calculateROCcurve().
test_dataset()
template<class BASIS > double sgpp::datadriven::test_dataset (base::GridStorage * storage, BASIS & basis, base::DataVector & alpha, base::DataMatrix & data, base::DataVector & classes)
Returns the number of correctly classified instances in data without boundaries.
Parameters
storage base::GridStorage object that contains the grid points
basis reference to class that implements to current basis
alpha the coefficients of the grid points
data the data the should be tested
classes the reference classes
References alpha.
Referenced by sgpp::datadriven::OperationTestLinearStretchedBoundary::test(), sgpp::datadriven::OperationTestModBspline::test(), sgpp::datadriven::OperationTestModPoly::test(), sgpp::datadriven::OperationTestPoly::test(), sgpp::datadriven::OperationTestLinear::test(), sgpp::datadriven::OperationTestLinearBoundary::test(), sgpp::datadriven::OperationTestLinearStretched::test(), sgpp::datadriven::OperationTestModLinear::test(), sgpp::datadriven::OperationTestModWavelet::test(), and sgpp::datadriven::OperationTestPrewavelet::test().
test_dataset_mse()
template<class BASIS > double sgpp::datadriven::test_dataset_mse (base::GridStorage * storage, BASIS & basis, base::DataVector & alpha, base::DataMatrix & data, base::DataVector & refValues)
Returns the MSE for given functions values at the evaluation points.
Parameters
storage base::GridStorage object that contains the grid points
basis reference to class that implements to current basis
alpha the coefficients of the grid points
data the data the should be tested
refValues the function values at the evaluation points
References alpha, sgpp::base::DataVector::getSize(), mse, sgpp::base::DataVector::sqr(), sgpp::base::DataVector::sub(), and sgpp::base::DataVector::sum().
Referenced by sgpp::datadriven::OperationTestLinearStretchedBoundary::testMSE(), sgpp::datadriven::OperationTestModBspline::testMSE(), sgpp::datadriven::OperationTestModPoly::testMSE(), sgpp::datadriven::OperationTestPoly::testMSE(), sgpp::datadriven::OperationTestLinear::testMSE(), sgpp::datadriven::OperationTestLinearBoundary::testMSE(), sgpp::datadriven::OperationTestLinearStretched::testMSE(), sgpp::datadriven::OperationTestModLinear::testMSE(), sgpp::datadriven::OperationTestModWavelet::testMSE(), and sgpp::datadriven::OperationTestPrewavelet::testMSE().
test_datasetWithCharacteristicNumber()
template<class BASIS > double sgpp::datadriven::test_datasetWithCharacteristicNumber (base::GridStorage * storage, BASIS & basis, base::DataVector & alpha, base::DataMatrix & data, base::DataVector & classes, base::DataVector & charaNumbers, double threshold)
Returns the number of correctly classified instances in data without boundaries.
Parameters
storage base::GridStorage object that contains the grid points
basis reference to class that implements to current basis
alpha the coefficients of the grid points
data the data the should be tested
classes the reference classes
charaNumbers the number of true positives, true negatives, false positives, false negatives (Vector of length 4)
threshold threshold which decides if an instance belongs a given class
References alpha, sgpp::base::DataVector::getSize(), and sgpp::base::DataVector::set().
Referenced by test_calculateROCcurve(), sgpp::datadriven::OperationTestLinear::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestLinearBoundary::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestLinearStretched::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestLinearStretchedBoundary::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestModBspline::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestModLinear::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestModPoly::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestModWavelet::testWithCharacteristicNumber(), sgpp::datadriven::OperationTestPoly::testWithCharacteristicNumber(), and sgpp::datadriven::OperationTestPrewavelet::testWithCharacteristicNumber().
validate() [1/3]
void sgpp::datadriven::validate (boost::any & v, const std::vector< std::string > & values, sgpp::datadriven::LearnerMode * target_type, int)
References LEARN, LEARNCOMPARE, and LEARNTEST.
validate() [2/3]
void sgpp::datadriven::validate (boost::any & v, const std::vector< std::string > & values, sgpp::datadriven::OperationMultipleEvalSubType * target_type, int)
References COMBINED, DEFAULT, OCL, OCLFASTMP, OCLMASKMP, OCLMP, and SIMPLE.
validate() [3/3]
void sgpp::datadriven::validate (boost::any & v, const std::vector< std::string > & values, sgpp::datadriven::OperationMultipleEvalType * target_type, int)
References DEFAULT, STREAMING, and SUBSPACELINEAR.
Variable Documentation
csrc_
const int sgpp::datadriven::csrc_ = 7
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
ctxt_
const int sgpp::datadriven::ctxt_ = 1
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
dtype_
const int sgpp::datadriven::dtype_ = 0
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
kDescriptor_
const int sgpp::datadriven::kDescriptor_ = 9
keyDecompositionType
const std::string sgpp::datadriven::keyDecompositionType = "decomposition"
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyDensityEstimationConfiguration
const std::string sgpp::datadriven::keyDensityEstimationConfiguration = "densityEstimationConfiguration"
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyFilepath
const std::string sgpp::datadriven::keyFilepath = "filepath"
Referenced by sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), sgpp::datadriven::DBMatDatabase::getDataMatrix(), and sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyGridConfiguration
const std::string sgpp::datadriven::keyGridConfiguration = "gridConfiguration"
Referenced by sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), and sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyGridDimension
const std::string sgpp::datadriven::keyGridDimension = "dimension"
Referenced by sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), and sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyGridLevel
const std::string sgpp::datadriven::keyGridLevel = "level"
Referenced by sgpp::datadriven::DBMatDatabase::getBaseDataMatrix(), and sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyGridType
const std::string sgpp::datadriven::keyGridType = "type"
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyRegularizationConfiguration
const std::string sgpp::datadriven::keyRegularizationConfiguration = "regularizationConfiguration"
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
keyRegularizationStrength
const std::string sgpp::datadriven::keyRegularizationStrength = "lambda"
Referenced by sgpp::datadriven::DBMatDatabase::putDataMatrix().
lld_
const int sgpp::datadriven::lld_ = 8
Referenced by sgpp::datadriven::DataMatrixDistributed::copyFrom(), sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed(), and sgpp::datadriven::DataMatrixDistributed::resize().
lowerTriangular
const char* const sgpp::datadriven::lowerTriangular = "L"
Referenced by sgpp::datadriven::DataMatrixDistributed::solveCholesky().
m_
const int sgpp::datadriven::m_ = 2
Referenced by sgpp::datadriven::DataMatrixDistributed::copyFrom(), sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed(), and sgpp::datadriven::DataMatrixDistributed::resize().
mb_
const int sgpp::datadriven::mb_ = 4
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
n_
const int sgpp::datadriven::n_ = 3
Referenced by sgpp::datadriven::DataMatrixDistributed::copyFrom(), sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed(), and sgpp::datadriven::DataMatrixDistributed::resize().
nb_
const int sgpp::datadriven::nb_ = 5
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
pblasConjugate
const char* const sgpp::datadriven::pblasConjugate = "C"
pblasNoTranspose
const char* const sgpp::datadriven::pblasNoTranspose = "N"
Referenced by sgpp::datadriven::DataMatrixDistributed::add(), sgpp::datadriven::DataMatrixDistributed::mult(), and sgpp::datadriven::DataMatrixDistributed::mult().
pblasTranspose
const char* const sgpp::datadriven::pblasTranspose = "T"
Referenced by sgpp::datadriven::DataMatrixDistributed::add(), sgpp::datadriven::DataMatrixDistributed::mult(), and sgpp::datadriven::DataMatrixDistributed::mult().
rsrc_
const int sgpp::datadriven::rsrc_ = 6
Referenced by sgpp::datadriven::DataMatrixDistributed::DataMatrixDistributed().
upperTriangular
const char* const sgpp::datadriven::upperTriangular = "U"
Referenced by sgpp::datadriven::DataMatrixDistributed::solveCholesky().