SG++-Doxygen-Documentation: sgpp::datadriven::PermutationUtil Namespace Reference
sgpp::datadriven::PermutationUtil Namespace Reference
Functions
std::vector< size_t > deleteOnesFromLevelVec (std::vector< size_t > vectorWithOnes)
Removes all elements equal to 1 from a vector and returns the obtained vector.
sgpp::base::GeneralGridConfiguration getNormalizedConfig (sgpp::base::GeneralGridConfiguration gridConfig)
Returns a grid configuration with level vector without elements equal to 1 and adjusted dimension.
bool isPermutation (std::vector< size_t > vec1, std::vector< size_t > vec2)
Cecks whether vec1 is permutation of vec2.
Function Documentation
deleteOnesFromLevelVec()
std::vector< size_t > sgpp::datadriven::PermutationUtil::deleteOnesFromLevelVec (std::vector< size_t > vectorWithOnes)
Removes all elements equal to 1 from a vector and returns the obtained vector.
Parameters
vectorWithOnes The input vector.
Returns
std::vector<size_t>
Referenced by sgpp::datadriven::DBMatObjectStore::ObjectContainer::configMatches(), getNormalizedConfig(), sgpp::datadriven::DBMatOfflineOrthoAdapt::permuteDecomposition(), and sgpp::datadriven::DBMatOfflinePermutable::permuteMatrix().
getNormalizedConfig()
sgpp::base::GeneralGridConfiguration sgpp::datadriven::PermutationUtil::getNormalizedConfig (sgpp::base::GeneralGridConfiguration gridConfig)
Returns a grid configuration with level vector without elements equal to 1 and adjusted dimension.
Parameters
gridConfig Grid condiguration to normalize.
Returns
sgpp::base::GeneralGridConfiguration
References deleteOnesFromLevelVec(), sgpp::base::GeneralGridConfiguration::dim_, and sgpp::base::GeneralGridConfiguration::levelVector_.
Referenced by sgpp::datadriven::DBMatPermutationFactory::getPermutedObject().
isPermutation()
bool sgpp::datadriven::PermutationUtil::isPermutation (std::vector< size_t > vec1, std::vector< size_t > vec2)
Cecks whether vec1 is permutation of vec2.
Parameters
vec1 First input vector.
vec2 Second input vector.
Returns
true
false
Referenced by sgpp::datadriven::DBMatObjectStore::ObjectContainer::configMatches().