SG++-Doxygen-Documentation: python.uq.operations.discretizeProduct Namespace Reference
python.uq.operations.discretizeProduct Namespace Reference
Functions
computeErrors (jgrid, jalpha, grid1, alpha1, grid2, alpha2, n=200)
dehierarchizeOnNewGrid (gridResult, grid, alpha)
discretizeProduct (grid1, alpha1, grid2, alpha2)
interpolateProduct (grid1, alpha1, grid2, alpha2, grid_result)
refine (jgrid, jalpha)
Variables
list refinable = []
Function Documentation
computeErrors()
python.uq.operations.discretizeProduct.computeErrors (jgrid, jalpha, grid1, alpha1, grid2, alpha2, n = 200)
Compute some errors to estimate the quality of the
interpolation.
@param jgrid: Grid, new discretization
@param jalpha: DataVector, new surpluses
@param grid1: Grid, old discretization
@param alpha1: DataVector, old surpluses
@param grid2: Grid, old discretization
@param alpha2: DataVector, old surpluses
@return: tuple(<float>, <float>), maxdrift, l2norm
dehierarchizeOnNewGrid()
python.uq.operations.discretizeProduct.dehierarchizeOnNewGrid (gridResult, grid, alpha)
Referenced by python.uq.operations.discretizeProduct.interpolateProduct().
discretizeProduct()
python.uq.operations.discretizeProduct.discretizeProduct (grid1, alpha1, grid2, alpha2)
Discretizes the product of two sparse grid functions:
    h(x) := f(x) * g(x)
on a full grid with piecewise polynomial basis. Therefore
a maximum number of grid points 10^6 is allowed.
@param grid1: Grid, grid of f
@param alpha1: DataVector, hierarchical coefficients of f
@param grid2: Grid, grid of g
@param alpha2: DataVector, hierarchical coefficients of g
References python.uq.operations.discretizeProduct.interpolateProduct().
interpolateProduct()
python.uq.operations.discretizeProduct.interpolateProduct (grid1, alpha1, grid2, alpha2, grid_result)
References python.uq.operations.discretizeProduct.dehierarchizeOnNewGrid().
Referenced by python.uq.operations.discretizeProduct.discretizeProduct().
refine()
python.uq.operations.discretizeProduct.refine (jgrid, jalpha)
Variable Documentation
refinable
list python.uq.operations.discretizeProduct.refinable = []