SG++-Doxygen-Documentation: python.classifier Namespace Reference
python.classifier Namespace Reference
Functions
assembleTrainingVector (dvecs, cvecs, omit)
buildTrainingVector (data)
buildYVector (data)
callback_deprecated (option, opt, value, parser)
constructGrid (dim)
doApply ()
doEval ()
doEvalStdin ()
doFold ()
doFoldf ()
doFoldr ()
doFolds ()
doFoldStratified ()
doNormal ()
doTest ()
evaluateError (classes, alpha, m)
Subroutine evaluation of error.
exec_mode (mode)
format_optionlist (l)
formTxt (te_refine, tr_refine, num_refine, withHeader=True)
returns txt variable for stats
formTxtVal (te_refine, tr_refine, val_refine, num_points, withHeader=True)
returns txt variable for stats with validation set
getEpochsErrorIncreasing (list)
returns the number of epochs the error is increasing
getNumOfPoints (options, grid)
openAlphaFile (filename)
openFile (filename)
performFold (dvec, cvec)
performFoldNew (dvec, cvec, ifold)
performFoldRegression (dvec, cvec)
run (grid, training, classes)
testValuesWithCharacteristicNumbers (grid, alpha, test, classes, evalValues)
testVector (grid, alpha, test, classes)
testVectorFast (grid, alpha, test, classes)
testVectorFastMSE (grid, alpha, test, vals)
testVectorFastWithCharacteristicNumbers (grid, alpha, test, classes)
testVectorValues (grid, alpha, test, classes, evalValues)
Variables
action
args
callback
choices
CMode = options.CMode.lower()
default
dest
False
help
metavar
dict modes
None
options
parser = OptionParser()
type
Function Documentation
assembleTrainingVector()
python.classifier.assembleTrainingVector (dvecs, cvecs, omit)
Referenced by python.classifier.performFold(), python.classifier.performFoldNew(), and python.classifier.performFoldRegression().
buildTrainingVector()
python.classifier.buildTrainingVector (data)
Referenced by python.classifier.doApply(), python.classifier.doFoldf(), python.classifier.doNormal(), and python.classifier.doTest().
buildYVector()
python.classifier.buildYVector (data)
Referenced by python.classifier.doApply(), python.classifier.doFoldf(), python.classifier.doNormal(), and python.classifier.doTest().
callback_deprecated()
python.classifier.callback_deprecated (option, opt, value, parser)
constructGrid()
python.classifier.constructGrid (dim)
Referenced by python.classifier.doApply(), python.classifier.doEval(), python.classifier.doEvalStdin(), python.classifier.doNormal(), python.classifier.doTest(), python.classifier.performFold(), python.classifier.performFoldNew(), and python.classifier.performFoldRegression().
doApply()
python.classifier.doApply ()
References python.classifier.buildTrainingVector(), python.classifier.buildYVector(), python.classifier.constructGrid(), python.classifier.evaluateError(), python.classifier.openAlphaFile(), and python.classifier.openFile().
doEval()
python.classifier.doEval ()
References python.classifier.constructGrid(), python.classifier.evaluateError(), python.classifier.openAlphaFile(), and python.classifier.openFile().
doEvalStdin()
python.classifier.doEvalStdin ()
References python.classifier.constructGrid(), and python.classifier.openAlphaFile().
doFold()
python.classifier.doFold ()
References python.classifier.openFile(), python.classifier.performFold(), and python.classifier.performFoldRegression().
doFoldf()
python.classifier.doFoldf ()
References python.classifier.buildTrainingVector(), python.classifier.buildYVector(), python.classifier.openFile(), python.classifier.performFold(), and python.classifier.performFoldRegression().
doFoldr()
python.classifier.doFoldr ()
References python.classifier.openFile(), python.classifier.performFold(), and python.classifier.performFoldRegression().
doFolds()
python.classifier.doFolds ()
References python.classifier.openFile(), python.classifier.performFold(), and python.classifier.performFoldRegression().
doFoldStratified()
python.classifier.doFoldStratified ()
References python.classifier.openFile(), and python.classifier.performFoldNew().
doNormal()
python.classifier.doNormal ()
References python.classifier.buildTrainingVector(), python.classifier.buildYVector(), python.classifier.constructGrid(), python.classifier.openFile(), and python.classifier.run().
doTest()
python.classifier.doTest ()
References python.classifier.buildTrainingVector(), python.classifier.buildYVector(), python.classifier.constructGrid(), python.classifier.evaluateError(), python.classifier.formTxt(), python.classifier.getEpochsErrorIncreasing(), python.classifier.getNumOfPoints(), python.classifier.openFile(), and python.classifier.testVectorFastWithCharacteristicNumbers().
evaluateError()
python.classifier.evaluateError (classes, alpha, m)
Subroutine evaluation of error.
Todo:
remove printing messages from the subroutine and place it into the suited methods
Referenced by python.classifier.doApply(), python.classifier.doEval(), python.classifier.doTest(), and python.classifier.run().
exec_mode()
python.classifier.exec_mode (mode)
References python.classifier.format_optionlist(), and python.classifier.type.
format_optionlist()
python.classifier.format_optionlist (l)
References python.classifier.type.
Referenced by python.classifier.exec_mode().
formTxt()
python.classifier.formTxt (te_refine, tr_refine, num_refine, withHeader = True)
returns txt variable for stats
Referenced by python.classifier.doTest(), python.classifier.performFold(), and python.classifier.performFoldRegression().
formTxtVal()
python.classifier.formTxtVal (te_refine, tr_refine, val_refine, num_points, withHeader = True)
returns txt variable for stats with validation set
Referenced by python.classifier.performFoldNew().
getEpochsErrorIncreasing()
python.classifier.getEpochsErrorIncreasing (list)
returns the number of epochs the error is increasing
Parameters
list List with MSE's from different refinement iterations
Referenced by python.classifier.doTest().
getNumOfPoints()
python.classifier.getNumOfPoints (options, grid)
Referenced by python.classifier.doTest(), python.classifier.performFold(), python.classifier.performFoldNew(), python.classifier.performFoldRegression(), and python.classifier.run().
openAlphaFile()
python.classifier.openAlphaFile (filename)
Referenced by python.classifier.doApply(), python.classifier.doEval(), and python.classifier.doEvalStdin().
openFile()
python.classifier.openFile (filename)
Referenced by python.classifier.doApply(), python.classifier.doEval(), python.classifier.doFold(), python.classifier.doFoldf(), python.classifier.doFoldr(), python.classifier.doFolds(), python.classifier.doFoldStratified(), python.classifier.doNormal(), and python.classifier.doTest().
performFold()
python.classifier.performFold (dvec, cvec)
References python.classifier.assembleTrainingVector(), python.classifier.constructGrid(), python.classifier.formTxt(), python.classifier.getNumOfPoints(), and python.classifier.testVectorFast().
Referenced by python.classifier.doFold(), python.classifier.doFoldf(), python.classifier.doFoldr(), and python.classifier.doFolds().
performFoldNew()
python.classifier.performFoldNew (dvec, cvec, ifold)
References python.classifier.assembleTrainingVector(), python.classifier.constructGrid(), python.classifier.formTxtVal(), python.classifier.getNumOfPoints(), and python.classifier.testVectorFast().
Referenced by python.classifier.doFoldStratified().
performFoldRegression()
python.classifier.performFoldRegression (dvec, cvec)
Perform n-fold cross-validation.
@param dvec contains n DataMatrices for the single folds;
@param cvec contains n DataVectors with function values for the single folds
References python.classifier.assembleTrainingVector(), python.classifier.constructGrid(), python.classifier.formTxt(), python.classifier.getNumOfPoints(), and python.classifier.testVectorFastMSE().
Referenced by python.classifier.doFold(), python.classifier.doFoldf(), python.classifier.doFoldr(), and python.classifier.doFolds().
run()
python.classifier.run (grid, training, classes)
References python.classifier.evaluateError(), and python.classifier.getNumOfPoints().
Referenced by python.classifier.doNormal().
testValuesWithCharacteristicNumbers()
python.classifier.testValuesWithCharacteristicNumbers (grid, alpha, test, classes, evalValues)
testVector()
python.classifier.testVector (grid, alpha, test, classes)
testVectorFast()
python.classifier.testVectorFast (grid, alpha, test, classes)
Referenced by python.classifier.performFold(), and python.classifier.performFoldNew().
testVectorFastMSE()
python.classifier.testVectorFastMSE (grid, alpha, test, vals)
Referenced by python.classifier.performFoldRegression().
testVectorFastWithCharacteristicNumbers()
python.classifier.testVectorFastWithCharacteristicNumbers (grid, alpha, test, classes)
Referenced by python.classifier.doTest().
testVectorValues()
python.classifier.testVectorValues (grid, alpha, test, classes, evalValues)
Variable Documentation
action
python.classifier.action
args
python.classifier.args
callback
python.classifier.callback
choices
python.classifier.choices
CMode
python.classifier.CMode = options.CMode.lower()
default
python.classifier.default
dest
python.classifier.dest
False
python.classifier.False
help
python.classifier.help
metavar
python.classifier.metavar
modes
dict python.classifier.modes
None
python.classifier.None
options
python.classifier.options
parser
python.classifier.parser = OptionParser()
type
python.classifier.type
Referenced by python.classifier.exec_mode(), and python.classifier.format_optionlist().