var namespacepython_1_1learner_1_1folding_1_1SequentialFoldingPolicy =
[
    [ "SequentialFoldingPolicy", "classpython_1_1learner_1_1folding_1_1SequentialFoldingPolicy_1_1SequentialFoldingPolicy.html", "classpython_1_1learner_1_1folding_1_1SequentialFoldingPolicy_1_1SequentialFoldingPolicy" ]
];