var OperationMultipleHierarchisationModBsplineClenshawCurtis_8hpp =
[
    [ "sgpp::optimization::OperationMultipleHierarchisationModBsplineClenshawCurtis", "classsgpp_1_1optimization_1_1OperationMultipleHierarchisationModBsplineClenshawCurtis.html", "classsgpp_1_1optimization_1_1OperationMultipleHierarchisationModBsplineClenshawCurtis" ]
];