var OperationMultipleEvalStreamingModOCLMaskMultiPlatform_2OperatorFactory_8cpp =
[
    [ "createStreamingModOCLMaskMultiPlatformConfigured", "OperationMultipleEvalStreamingModOCLMaskMultiPlatform_2OperatorFactory_8cpp.html#ada422f55789f582f2a0e43cf1a4ca30f", null ]
];