var OperationMultipleEvalStreamingModOCLFastMultiPlattform_2OperatorFactory_8hpp =
[
    [ "createStreamingModOCLFastMultiPlatformConfigured", "OperationMultipleEvalStreamingModOCLFastMultiPlattform_2OperatorFactory_8hpp.html#a0ab2a548033b8164182b02d4bb22791d", null ]
];