var RefinementStrategy_8py =
[
    [ "python.uq.refinement.RefinementStrategy.AnchoredExpectationValueOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredExpectationValueOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredExpectationValueOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.AnchoredMeanSquaredOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredMeanSquaredOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredMeanSquaredOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.AnchoredVarianceOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredVarianceOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredVarianceOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.AnchoredWeightedL2OptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredWeightedL2OptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1AnchoredWeightedL2OptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.ExpectationValueBFRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1ExpectationValueBFRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1ExpectationValueBFRanking" ],
    [ "python.uq.refinement.RefinementStrategy.ExpectationValueOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1ExpectationValueOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1ExpectationValueOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.LinearSurplusEstimationRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1LinearSurplusEstimationRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1LinearSurplusEstimationRanking" ],
    [ "python.uq.refinement.RefinementStrategy.MeanSquaredOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1MeanSquaredOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1MeanSquaredOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.PredictiveRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1PredictiveRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1PredictiveRanking" ],
    [ "python.uq.refinement.RefinementStrategy.Ranking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1Ranking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1Ranking" ],
    [ "python.uq.refinement.RefinementStrategy.SquaredSurplusBFRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SquaredSurplusBFRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SquaredSurplusBFRanking" ],
    [ "python.uq.refinement.RefinementStrategy.SquaredSurplusRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SquaredSurplusRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SquaredSurplusRanking" ],
    [ "python.uq.refinement.RefinementStrategy.SurplusRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRanking" ],
    [ "python.uq.refinement.RefinementStrategy.SurplusRatioEstimationRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRatioEstimationRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRatioEstimationRanking" ],
    [ "python.uq.refinement.RefinementStrategy.SurplusRatioRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRatioRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1SurplusRatioRanking" ],
    [ "python.uq.refinement.RefinementStrategy.VarianceBFRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1VarianceBFRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1VarianceBFRanking" ],
    [ "python.uq.refinement.RefinementStrategy.VarianceOptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1VarianceOptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1VarianceOptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.WeightedL2BFRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedL2BFRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedL2BFRanking" ],
    [ "python.uq.refinement.RefinementStrategy.WeightedL2OptRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedL2OptRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedL2OptRanking" ],
    [ "python.uq.refinement.RefinementStrategy.WeightedSurplusBFRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedSurplusBFRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedSurplusBFRanking" ],
    [ "python.uq.refinement.RefinementStrategy.WeightedSurplusRanking", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedSurplusRanking.html", "classpython_1_1uq_1_1refinement_1_1RefinementStrategy_1_1WeightedSurplusRanking" ]
];