#!/bin/bash


scons SG_BASE=1 SG_DATADRIVEN=1 SG_PDE=1 SG_FINANCE=1 SG_MISC=1 SG_COMBIGRID=1 SG_SOLVER=1 SG_PARALLEL=1 SG_PYTHON=1

# scons OMP=1

# Test:
# scons

# Failed:
# scons SG_PYTHON=0
# scons CPPFLAGS=-g
# scons CPPFLAGS=-O0
# scons CPPFLAGS=-g,-O0
# scons CPPFLAGS=-g,-O0,-std=c++0x
