# Copyright (C) 2008-today The SG++ Project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at 
# sgpp.sparsegrids.org


Import('env')
Import('src_objs')

j_env = env.Clone()

j_env.AppendUnique(SWIGFLAGS=['-c++','-java', '-package', 'weka.de.tum.in.www5.sgpp'])
#j_env.Append(CPPPATH=['#/src/sgpp', env['JNI_CPPPATH'], env['JNI_CPPPATH'] + '/' + env['JNI_OS']])
j_env.AppendUnique(CPPPATH=['#/src/sgpp'])
j_env.Append(CPPFLAGS=['-fno-strict-aliasing'])

wekajsgpp = j_env.SharedLibrary(target="jsgpp", source = ['jsgpp.i']+src_objs, SHLIBPREFIX = 'lib')

from glob import glob
files = glob('*.java')
dep = env.Install('#/wekasgpp/weka/de/tum/in/www5/sgpp', files)
Depends(dep, wekajsgpp)
#Command('', files, Mkdir('wekasgpp/weka/de/tum/in/www5/sgpp'))

#for f in files:
#	Command('#/wekasgpp/weka/de/tum/in/www5/sgpp/' + f, f, Copy('$TARGET', 'tmp/build_jsgpp_weka/' + f))	
#	#Command('#/lib/jsgpp/' + f, f, Copy('$TARGET', 'tmp/build_jsgpp/' + f))
dep = env.InstallAs('#/wekasgpp/', wekajsgpp)
Depends(dep, wekajsgpp)
#Command('#/wekasgpp/libjsgpp.so', wekajsgpp, Copy('$TARGET', '$SOURCE'))

Export('wekajsgpp')
