var searchData=
[
  ['g03_0',['G03',['../classsgpp_1_1optimization_1_1test__problems_1_1G03.html',1,'sgpp::optimization::test_problems']]],
  ['g03equalityconstraint_1',['G03EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G03EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g03inequalityconstraint_2',['G03InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G03InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g03objective_3',['G03Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G03Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g04_4',['G04',['../classsgpp_1_1optimization_1_1test__problems_1_1G04.html',1,'sgpp::optimization::test_problems']]],
  ['g04equalityconstraint_5',['G04EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G04EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g04inequalityconstraint_6',['G04InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G04InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g04objective_7',['G04Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G04Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g04squared_8',['G04Squared',['../classsgpp_1_1optimization_1_1test__problems_1_1G04Squared.html',1,'sgpp::optimization::test_problems']]],
  ['g04squaredequalityconstraint_9',['G04SquaredEqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G04SquaredEqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g04squaredinequalityconstraint_10',['G04SquaredInequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G04SquaredInequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g04squaredobjective_11',['G04SquaredObjective',['../classsgpp_1_1optimization_1_1test__problems_1_1G04SquaredObjective.html',1,'sgpp::optimization::test_problems']]],
  ['g05_12',['G05',['../classsgpp_1_1optimization_1_1test__problems_1_1G05.html',1,'sgpp::optimization::test_problems']]],
  ['g05equalityconstraint_13',['G05EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G05EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g05inequalityconstraint_14',['G05InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G05InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g05objective_15',['G05Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G05Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g06_16',['G06',['../classsgpp_1_1optimization_1_1test__problems_1_1G06.html',1,'sgpp::optimization::test_problems']]],
  ['g06equalityconstraint_17',['G06EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G06EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g06inequalityconstraint_18',['G06InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G06InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g06objective_19',['G06Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G06Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g08_20',['G08',['../classsgpp_1_1optimization_1_1test__problems_1_1G08.html',1,'sgpp::optimization::test_problems']]],
  ['g08equalityconstraint_21',['G08EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G08EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g08inequalityconstraint_22',['G08InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G08InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g08objective_23',['G08Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G08Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g09_24',['G09',['../classsgpp_1_1optimization_1_1test__problems_1_1G09.html',1,'sgpp::optimization::test_problems']]],
  ['g09equalityconstraint_25',['G09EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G09EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g09inequalityconstraint_26',['G09InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G09InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g09objective_27',['G09Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G09Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g10_28',['G10',['../classsgpp_1_1optimization_1_1test__problems_1_1G10.html',1,'sgpp::optimization::test_problems']]],
  ['g10equalityconstraint_29',['G10EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G10EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g10inequalityconstraint_30',['G10InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G10InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g10objective_31',['G10Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G10Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g11_32',['G11',['../classsgpp_1_1optimization_1_1test__problems_1_1G11.html',1,'sgpp::optimization::test_problems']]],
  ['g11equalityconstraint_33',['G11EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G11EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g11inequalityconstraint_34',['G11InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G11InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g11objective_35',['G11Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G11Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g12_36',['G12',['../classsgpp_1_1optimization_1_1test__problems_1_1G12.html',1,'sgpp::optimization::test_problems']]],
  ['g12equalityconstraint_37',['G12EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G12EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g12inequalityconstraint_38',['G12InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G12InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g12objective_39',['G12Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G12Objective.html',1,'sgpp::optimization::test_problems']]],
  ['g13_40',['G13',['../classsgpp_1_1optimization_1_1test__problems_1_1G13.html',1,'sgpp::optimization::test_problems']]],
  ['g13equalityconstraint_41',['G13EqualityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G13EqualityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g13inequalityconstraint_42',['G13InequalityConstraint',['../classsgpp_1_1optimization_1_1test__problems_1_1G13InequalityConstraint.html',1,'sgpp::optimization::test_problems']]],
  ['g13objective_43',['G13Objective',['../classsgpp_1_1optimization_1_1test__problems_1_1G13Objective.html',1,'sgpp::optimization::test_problems']]],
  ['gausshermitequadrature_44',['GaussHermiteQuadrature',['../classpython_1_1uq_1_1quadrature_1_1strategies_1_1GaussHermiteQuadrature_1_1GaussHermiteQuadrature.html',1,'python::uq::quadrature::strategies::GaussHermiteQuadrature']]],
  ['gausshermitequadrule1d_45',['GaussHermiteQuadRule1D',['../classsgpp_1_1base_1_1GaussHermiteQuadRule1D.html',1,'sgpp::base']]],
  ['gaussianelimination_46',['GaussianElimination',['../classsgpp_1_1base_1_1sle__solver_1_1GaussianElimination.html',1,'sgpp::base::sle_solver']]],
  ['gaussiankernel_47',['GaussianKernel',['../classsgpp_1_1datadriven_1_1GaussianKernel.html',1,'sgpp::datadriven']]],
  ['gausslegendrequadrature_48',['GaussLegendreQuadrature',['../classpython_1_1uq_1_1quadrature_1_1strategies_1_1GaussLegendreQuadrature_1_1GaussLegendreQuadrature.html',1,'python::uq::quadrature::strategies::GaussLegendreQuadrature']]],
  ['gausslegendrequadrule1d_49',['GaussLegendreQuadRule1D',['../classsgpp_1_1base_1_1GaussLegendreQuadRule1D.html',1,'sgpp::base']]],
  ['generalgridconfiguration_50',['GeneralGridConfiguration',['../structsgpp_1_1base_1_1GeneralGridConfiguration.html',1,'sgpp::base']]],
  ['generalgridtypeparser_51',['GeneralGridTypeParser',['../classsgpp_1_1base_1_1GeneralGridTypeParser.html',1,'sgpp::base']]],
  ['generalizedboundarygridgenerator_52',['GeneralizedBoundaryGridGenerator',['../classsgpp_1_1base_1_1GeneralizedBoundaryGridGenerator.html',1,'sgpp::base']]],
  ['generalparameterbuilder_53',['GeneralParameterBuilder',['../classpython_1_1uq_1_1parameters_1_1ParameterBuilder_1_1GeneralParameterBuilder.html',1,'python::uq::parameters::ParameterBuilder']]],
  ['generation_5fexception_54',['generation_exception',['../classsgpp_1_1base_1_1generation__exception.html',1,'sgpp::base']]],
  ['geometryconfiguration_55',['GeometryConfiguration',['../structsgpp_1_1datadriven_1_1GeometryConfiguration.html',1,'sgpp::datadriven']]],
  ['geometryconfigurationparser_56',['GeometryConfigurationParser',['../classsgpp_1_1datadriven_1_1GeometryConfigurationParser.html',1,'sgpp::datadriven']]],
  ['getaffectedbasisfunctions_57',['GetAffectedBasisFunctions',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20linearboundarybasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_58',['GetAffectedBasisFunctions&lt; LinearBoundaryBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01LinearBoundaryBasis_3_01unsigned_01int_00_01unsigned_01int_01_4_01_4.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20linearclenshawcurtisboundarybasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_59',['GetAffectedBasisFunctions&lt; LinearClenshawCurtisBoundaryBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01LinearClenshawCurtisBoundaryBasis_3_01unsignefb37d362b4d04e962fe9f52e2e3f78ce.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20linearperiodicbasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_60',['GetAffectedBasisFunctions&lt; LinearPeriodicBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01LinearPeriodicBasis_3_01unsigned_01int_00_01unsigned_01int_01_4_01_4.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20linearstretchedboundarybasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_61',['GetAffectedBasisFunctions&lt; LinearStretchedBoundaryBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01LinearStretchedBoundaryBasis_3_01unsigned_01if54998c7919fc319bb2749b619fedf39.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20polyboundarybasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_62',['GetAffectedBasisFunctions&lt; PolyBoundaryBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01PolyBoundaryBasis_3_01unsigned_01int_00_01unsigned_01int_01_4_01_4.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20polyclenshawcurtisboundarybasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_63',['GetAffectedBasisFunctions&lt; PolyClenshawCurtisBoundaryBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01PolyClenshawCurtisBoundaryBasis_3_01unsigned_5ab37ff97d8cad6b555fb9bec907e194.html',1,'sgpp::base']]],
  ['getaffectedbasisfunctions_3c_20prewaveletbasis_3c_20unsigned_20int_2c_20unsigned_20int_20_3e_20_3e_64',['GetAffectedBasisFunctions&lt; PrewaveletBasis&lt; unsigned int, unsigned int &gt; &gt;',['../classsgpp_1_1base_1_1GetAffectedBasisFunctions_3_01PrewaveletBasis_3_01unsigned_01int_00_01unsigned_01int_01_4_01_4.html',1,'sgpp::base']]],
  ['gettype_65',['getType',['../structsgpp_1_1datadriven_1_1streamingBSplineOCL_1_1getType.html',1,'sgpp::datadriven::streamingBSplineOCL']]],
  ['gettype_3c_20double_20_3e_66',['getType&lt; double &gt;',['../structsgpp_1_1datadriven_1_1streamingBSplineOCL_1_1getType_3_01double_01_4.html',1,'sgpp::datadriven::streamingBSplineOCL']]],
  ['gettype_3c_20float_20_3e_67',['getType&lt; float &gt;',['../structsgpp_1_1datadriven_1_1streamingBSplineOCL_1_1getType_3_01float_01_4.html',1,'sgpp::datadriven::streamingBSplineOCL']]],
  ['gmmpp_68',['Gmmpp',['../classsgpp_1_1base_1_1sle__solver_1_1Gmmpp.html',1,'sgpp::base::sle_solver']]],
  ['goldsteinprice_69',['GoldsteinPrice',['../classsgpp_1_1optimization_1_1test__problems_1_1GoldsteinPrice.html',1,'sgpp::optimization::test_problems']]],
  ['goldsteinpriceobjective_70',['GoldsteinPriceObjective',['../classsgpp_1_1optimization_1_1test__problems_1_1GoldsteinPriceObjective.html',1,'sgpp::optimization::test_problems']]],
  ['gradientdescent_71',['GradientDescent',['../classsgpp_1_1optimization_1_1optimizer_1_1GradientDescent.html',1,'sgpp::optimization::optimizer']]],
  ['graphcreationworker_72',['GraphCreationWorker',['../classsgpp_1_1datadriven_1_1clusteringmpi_1_1GraphCreationWorker.html',1,'sgpp::datadriven::clusteringmpi']]],
  ['grid_73',['Grid',['../classsgpp_1_1base_1_1Grid.html',1,'sgpp::base']]],
  ['griddatabase_74',['GridDataBase',['../classsgpp_1_1base_1_1GridDataBase.html',1,'sgpp::base']]],
  ['griddescriptor_75',['griddescriptor',['../classpython_1_1learner_1_1LearnerBuilder_1_1LearnerBuilder_1_1GridDescriptor.html',1,'python.learner.LearnerBuilder.LearnerBuilder.GridDescriptor'],['../classpython_1_1uq_1_1learner_1_1builder_1_1GridDescriptor_1_1GridDescriptor.html',1,'python.uq.learner.builder.GridDescriptor.GridDescriptor']]],
  ['gridfactory_76',['GridFactory',['../classsgpp_1_1datadriven_1_1GridFactory.html',1,'sgpp::datadriven']]],
  ['gridformatter_77',['GridFormatter',['../classpython_1_1learner_1_1formatter_1_1GridFormatter_1_1GridFormatter.html',1,'python::learner::formatter::GridFormatter']]],
  ['gridgenerator_78',['GridGenerator',['../classsgpp_1_1base_1_1GridGenerator.html',1,'sgpp::base']]],
  ['gridimageformatter_79',['GridImageFormatter',['../classpython_1_1learner_1_1formatter_1_1GridImageFormatter_1_1GridImageFormatter.html',1,'python::learner::formatter::GridImageFormatter']]],
  ['gridpointbasedrefinementfunctor_80',['GridPointBasedRefinementFunctor',['../classsgpp_1_1datadriven_1_1GridPointBasedRefinementFunctor.html',1,'sgpp::datadriven']]],
  ['gridprinter_81',['GridPrinter',['../classsgpp_1_1base_1_1GridPrinter.html',1,'sgpp::base']]],
  ['gridprinterforstretching_82',['GridPrinterForStretching',['../classsgpp_1_1base_1_1GridPrinterForStretching.html',1,'sgpp::base']]],
  ['gridstencil_83',['GridStencil',['../classsgpp_1_1base_1_1GridStencil.html',1,'sgpp::base']]],
  ['gridtypeparser_84',['GridTypeParser',['../classsgpp_1_1base_1_1GridTypeParser.html',1,'sgpp::base']]],
  ['griewank_85',['Griewank',['../classsgpp_1_1optimization_1_1test__problems_1_1Griewank.html',1,'sgpp::optimization::test_problems']]],
  ['griewankobjective_86',['GriewankObjective',['../classsgpp_1_1optimization_1_1test__problems_1_1GriewankObjective.html',1,'sgpp::optimization::test_problems']]],
  ['grouplassofunction_87',['GroupLassoFunction',['../classsgpp_1_1solver_1_1GroupLassoFunction.html',1,'sgpp::solver']]],
  ['gzipserializer_88',['GzipSerializer',['../classpython_1_1utils_1_1GzipSerializer_1_1GzipSerializer.html',1,'python::utils::GzipSerializer']]]
];
