# Copyright (C) 2009 Technische Universitaet Muenchen
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice at http://www5.in.tum.de/SGpp

# author Dirk Pflueger (Dirk.Pflueger@in.tum.de)

Import('env pysgpp')

test_env = env.Clone()
# install prerequisites to tests directory
ti = env.Install('#/tests/',
                      [pysgpp, '#/tmp/build_pysgpp/pysgpp.py', '#/bin/tools.py'])

# run tests
bld = Builder(action = "python $SOURCE")
test_env.Append(BUILDERS = {'Test' : bld})
tests = test_env.Test('test_pysgpp.py')
Requires(tests, ti)
AlwaysBuild(tests)

test_env.Alias('test', tests)

