# Copyright (C) 2008-today The SG++ Project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at 
# sgpp.sparsegrids.org

# Import('env pysgpp')
Import('env pysgppInstall')

test_env = env.Clone()
# install prerequisites to tests directory
# ti = env.Install('#/tests/',
#                       [pysgpp, '#/tmp/build_pysgpp/pysgpp.py', '#/bin/tools.py'])

# run tests
bld = Builder(action = "python $SOURCE")
test_env.Append(BUILDERS = {'Test' : bld})
tests = test_env.Test('test_pysgpp.py')
Requires(tests, pysgppInstall)
AlwaysBuild(tests) 

test_env.Alias('test', tests)

