#!/bin/bash
start=1
end=%i

nodes=${start}
while [ ${nodes} -le ${end} ]; do
	cd Nodes-${nodes}
	cat runscript.sh
	echo
	read -p "Run test? (y/n)" -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		sbatch runscript.sh
	fi
	cd ..
        let nodes=nodes*2
done
