#!/bin/bash
set -e
start=1
end=%i

nodes=${start}
while [ ${nodes} -le ${end} ]; do
# for i in `seq $start $end`; do
	cd Nodes-${nodes}
	cat runscript.pbs
	echo
	read -p "Run test? (y/n)" -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		qsub runscript.pbs
		# read -p "" #Wait for Enter
	fi
	cd ..
        let nodes=nodes*2
done
