#!/bin/bash
#PBS -N %s 
#PBS -l nodes=%i:ppn=1
#PBS -l walltime=%s
#PBS -M David.Pfander@ipvs.uni-stuttgart.de
#PBS -m abe
#PBS -j oe
set -e

# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR

aprun ./mpi_examples MPIConf.cfg %s 8
