#ifndef DMSYSTEMMATRIXVECTORIZEDIDENTITYALLREDUCE_H
#define DMSYSTEMMATRIXVECTORIZEDIDENTITYALLREDUCE_H

class DMSystemMatrixVectorizedIdentityAllreduce
{
public:
	DMSystemMatrixVectorizedIdentityAllreduce();
};

#endif // DMSYSTEMMATRIXVECTORIZEDIDENTITYALLREDUCE_H
