#############################################################################
# This file is part of sgpp, a program package making use of spatially      #
# adaptive sparse grids to solve numerical problems                         #
#                                                                           #
# Copyright (C)                                                             #
#                                                                           #
#                                                                           #
# pysgpp is free software; you can redistribute it and/or modify            #
# it under the terms of the GNU Lesser General Public License as published  #
# by the Free Software Foundation; either version 3 of the License, or      #
# (at your option) any later version.                                       #
#                                                                           #
# pysgpp is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU Lesser General Public License for more details.                       #
#                                                                           #
# You should have received a copy of the GNU Lesser General Public License  #
# along with pysgpp; if not, write to the Free Software                     #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA #
# or see <http://www.gnu.org/licenses/>.                                    #
#############################################################################


Import("env")

srcs = Split("""
data/DataVector.cpp

grid/Grid.cpp
grid/type/LinearBoundaryGrid.cpp
grid/type/LinearBoundaryUScaledGrid.cpp
grid/type/LinearGrid.cpp
grid/type/ModLinearGrid.cpp
grid/type/ModPolyGrid.cpp
grid/type/PolyGrid.cpp
grid/generation/StandardGridGenerator.cpp
grid/generation/BoundaryGridGenerator.cpp
grid/generation/BoundaryUScaledGridGenerator.cpp

basis/linear/operation/OperationBLinear.cpp
basis/linear/operation/OperationEvalLinear.cpp
basis/linear/operation/OperationHierarchisationLinear.cpp
basis/modlinear/operation/OperationBModLinear.cpp
basis/modlinear/operation/OperationEvalModLinear.cpp
basis/modlinear/operation/OperationHierarchisationModLinear.cpp
basis/modpoly/operation/OperationBModPoly.cpp
basis/modpoly/operation/OperationEvalModPoly.cpp
basis/modpoly/operation/OperationHierarchisationModPoly.cpp
basis/poly/operation/OperationBPoly.cpp
basis/poly/operation/OperationEvalPoly.cpp
basis/poly/operation/OperationHierarchisationPoly.cpp
basis/linearboundary/operation/OperationHierarchisationLinearBoundary.cpp
basis/linearboundary/operation/OperationEvalLinearBoundary.cpp
basis/linearboundary/operation/OperationBLinearBoundary.cpp
basis/linearboundaryUScaled/operation/OperationHierarchisationLinearBoundaryUScaled.cpp
basis/linearboundaryUScaled/operation/OperationEvalLinearBoundaryUScaled.cpp
basis/linearboundaryUScaled/operation/OperationBLinearBoundaryUScaled.cpp

linearSystem/LinearSystem.cpp

""")



sg_env = env.Clone()

sg_env.Append(CPPPATH=['#/src/sgpp'])

src_objs = sg_env.SharedObject(srcs)
Export('src_objs')

libsgpp = sg_env.Library(target="sgpp", source = srcs + src_objs, SHLIBPREFIX = '_')
Export('libsgpp')
