#############################################################################
# This file is part of sgpp, a program package making use of spatially      #
# adaptive sparse grids to solve numerical problems                         #
#                                                                           #
# Copyright (C)                                                             #
#                                                                           #
#                                                                           #
# pysgpp is free software; you can redistribute it and/or modify            #
# it under the terms of the GNU Lesser General Public License as published  #
# by the Free Software Foundation; either version 3 of the License, or      #
# (at your option) any later version.                                       #
#                                                                           #
# pysgpp is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU Lesser General Public License for more details.                       #
#                                                                           #
# You should have received a copy of the GNU Lesser General Public License  #
# along with pysgpp; if not, write to the Free Software                     #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA #
# or see <http://www.gnu.org/licenses/>.                                    #
#############################################################################


Import("env")


srcs = Split("""
data/DataVector.cpp
data/DataMatrix.cpp

grid/Grid.cpp

grid/common/BoundingBox.cpp

grid/type/LinearBoundaryGrid.cpp
grid/type/LinearTrapezoidBoundaryGrid.cpp
grid/type/LinearGrid.cpp
grid/type/ModLinearGrid.cpp

grid/generation/StandardGridGenerator.cpp
grid/generation/BoundaryGridGenerator.cpp
grid/generation/TrapezoidBoundaryGridGenerator.cpp

basis/linear/noboundary/operation/datadriven/OperationBLinear.cpp
basis/linear/noboundary/operation/datadriven/OperationTestLinear.cpp
basis/linear/noboundary/operation/common/OperationEvalLinear.cpp
basis/linear/noboundary/operation/common/OperationHierarchisationLinear.cpp

basis/linear/noboundary/algorithm_sweep/DehierarchisationLinear.cpp
basis/linear/noboundary/algorithm_sweep/HierarchisationLinear.cpp

basis/linear/boundary/operation/common/OperationHierarchisationLinearBoundary.cpp
basis/linear/boundary/operation/common/OperationEvalLinearBoundary.cpp
basis/linear/boundary/operation/datadriven/OperationBLinearBoundary.cpp
basis/linear/boundary/operation/datadriven/OperationTestLinearBoundary.cpp

basis/linear/boundary/algorithm_sweep/DehierarchisationLinearBoundary.cpp
basis/linear/boundary/algorithm_sweep/HierarchisationLinearBoundary.cpp

basis/modlinear/operation/datadriven/OperationBModLinear.cpp
basis/modlinear/operation/datadriven/OperationTestModLinear.cpp
basis/modlinear/operation/common/OperationEvalModLinear.cpp
basis/modlinear/operation/common/OperationHierarchisationModLinear.cpp

basis/modlinear/algorithm_sweep/DehierarchisationModLinear.cpp
basis/modlinear/algorithm_sweep/HierarchisationModLinear.cpp

algorithm/datadriven/DMSystemMatrix.cpp

""")



sg_env = env.Clone()

sg_env.Append(CPPPATH=['#/src/sgpp'])

src_objs = sg_env.SharedObject(srcs)
Export('src_objs')

libsgpp = sg_env.Library(target="sgpp", source = srcs + src_objs, SHLIBPREFIX = '_')
#libsgpp = sg_env.SharedLibrary(target="sgpp", source = srcs + src_objs, SHLIBPREFIX = '_')
Export('libsgpp')
