#############################################################################
# This file is part of sgpp, a program package making use of spatially      #
# adaptive sparse grids to solve numerical problems                         #
#                                                                           #
# Copyright (C)                                                             #
#                                                                           #
#                                                                           #
# pysgpp is free software; you can redistribute it and/or modify            #
# it under the terms of the GNU Lesser General Public License as published  #
# by the Free Software Foundation; either version 3 of the License, or      #
# (at your option) any later version.                                       #
#                                                                           #
# pysgpp is distributed in the hope that it will be useful,                 #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU Lesser General Public License for more details.                       #
#                                                                           #
# You should have received a copy of the GNU Lesser General Public License  #
# along with pysgpp; if not, write to the Free Software                     #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA #
# or see <http://www.gnu.org/licenses/>.                                    #
#############################################################################


Import("env")


srcs = Split("""
data/DataVector.cpp

grid/Grid.cpp

grid/common/BoundingBox.cpp
grid/common/DirichletUpdateVector.cpp

grid/type/LinearBoundaryGrid.cpp
grid/type/LinearTrapezoidBoundaryGrid.cpp
grid/type/LinearGrid.cpp
grid/type/ModLinearGrid.cpp
grid/type/PolyGrid.cpp
grid/type/ModPolyGrid.cpp
grid/type/ModWaveletGrid.cpp
grid/type/ModBsplineGrid.cpp

grid/generation/StandardGridGenerator.cpp
grid/generation/BoundaryGridGenerator.cpp
grid/generation/TrapezoidBoundaryGridGenerator.cpp

basis/linear/noboundary/operation/datadriven/OperationBLinear.cpp
basis/linear/noboundary/operation/datadriven/OperationTestLinear.cpp
basis/linear/noboundary/operation/common/OperationEvalLinear.cpp
basis/linear/noboundary/operation/common/OperationHierarchisationLinear.cpp
basis/linear/noboundary/operation/pde/OperationLTwoDotProductLinear.cpp
basis/linear/noboundary/operation/pde/OperationLaplaceLinear.cpp

basis/linear/boundary/operation/common/OperationHierarchisationLinearBoundary.cpp
basis/linear/boundary/operation/common/OperationEvalLinearBoundary.cpp
basis/linear/boundary/operation/common/OperationUpDownTestLinearBoundary.cpp
basis/linear/boundary/operation/datadriven/OperationBLinearBoundary.cpp
basis/linear/boundary/operation/datadriven/OperationTestLinearBoundary.cpp
basis/linear/boundary/operation/pde/finance/OperationDeltaLinearBoundary.cpp
basis/linear/boundary/operation/pde/finance/OperationGammaLinearBoundary.cpp
basis/linear/boundary/operation/pde/finance/OperationDeltaLogLinearBoundary.cpp
basis/linear/boundary/operation/pde/finance/OperationGammaLogLinearBoundary.cpp
basis/linear/boundary/operation/pde/OperationLTwoDotProductLinearBoundary.cpp
basis/linear/boundary/operation/pde/OperationLaplaceLinearBoundary.cpp

basis/modlinear/operation/datadriven/OperationBModLinear.cpp
basis/modlinear/operation/datadriven/OperationTestModLinear.cpp
basis/modlinear/operation/common/OperationEvalModLinear.cpp
basis/modlinear/operation/common/OperationHierarchisationModLinear.cpp
basis/modlinear/operation/pde/OperationLaplaceModLinear.cpp


basis/poly/operation/datadriven/OperationBPoly.cpp
basis/poly/operation/datadriven/OperationTestPoly.cpp
basis/poly/operation/common/OperationEvalPoly.cpp
basis/poly/operation/common/OperationHierarchisationPoly.cpp

basis/modpoly/operation/datadriven/OperationBModPoly.cpp
basis/modpoly/operation/datadriven/OperationTestModPoly.cpp
basis/modpoly/operation/common/OperationEvalModPoly.cpp
basis/modpoly/operation/common/OperationHierarchisationModPoly.cpp


basis/modwavelet/operation/datadriven/OperationBModWavelet.cpp
basis/modwavelet/operation/datadriven/OperationTestModWavelet.cpp
basis/modwavelet/operation/common/OperationEvalModWavelet.cpp
basis/modwavelet/operation/common/OperationHierarchisationModWavelet.cpp


basis/modbspline/operation/datadriven/OperationBModBspline.cpp
basis/modbspline/operation/datadriven/OperationTestModBspline.cpp
basis/modbspline/operation/common/OperationEvalModBspline.cpp
basis/modbspline/operation/common/OperationHierarchisationModBspline.cpp

algorithm/datadriven/DMSystemMatrix.cpp
algorithm/pde/BlackScholesTimestepMatrix.cpp
algorithm/pde/HeatEquationTimestepMatrix.cpp
algorithm/pde/StdUpDown.cpp
algorithm/pde/UpDownOneOpDim.cpp
algorithm/pde/UpDownTwoOpDims.cpp

application/common/ScreenOutput.cpp
application/pde/BlackScholesSolver.cpp
application/pde/HeatEquationSolver.cpp

solver/sle/ConjugateGradients.cpp
solver/sle/BiCGStab.cpp
solver/ode/Euler.cpp
solver/ode/CrankNicolson.cpp

tools/common/StdNormalDistribution.cpp
tools/common/GridPrinter.cpp
tools/common/SGppStopwatch.cpp
tools/finance/IOToolBonnSG.cpp

""")



sg_env = env.Clone()

sg_env.Append(CPPPATH=['#/src/sgpp'])

src_objs = sg_env.SharedObject(srcs)
Export('src_objs')

libsgpp = sg_env.Library(target="sgpp", source = srcs + src_objs, SHLIBPREFIX = '_')
Export('libsgpp')
