#ifndef SGPP_OPT_HPP
#define SGPP_OPT_HPP

#include "opt/function/InterpolantFunction.hpp"
#include "opt/function/InterpolantFunctionGradient.hpp"
#include "opt/function/InterpolantFunctionHessian.hpp"
#include "opt/function/ObjectiveFunction.hpp"
#include "opt/function/ObjectiveFunctionGradient.hpp"
#include "opt/function/ObjectiveFunctionHessian.hpp"
#include "opt/function/TestFunction.hpp"
#include "opt/function/test/Ackley.hpp"
#include "opt/function/test/Beale.hpp"
#include "opt/function/test/Branin.hpp"
#include "opt/function/test/Easom.hpp"
#include "opt/function/test/Eggholder.hpp"
#include "opt/function/test/GoldsteinPrice.hpp"
#include "opt/function/test/Griewank.hpp"
#include "opt/function/test/Hartman3.hpp"
#include "opt/function/test/Hartman6.hpp"
#include "opt/function/test/Himmelblau.hpp"
#include "opt/function/test/HoelderTable.hpp"
#include "opt/function/test/Michalewicz.hpp"
#include "opt/function/test/Mladineo.hpp"
#include "opt/function/test/Rastrigin.hpp"
#include "opt/function/test/Rosenbrock.hpp"
#include "opt/function/test/SHCB.hpp"
#include "opt/function/test/Schaeffler.hpp"
#include "opt/function/test/Schwefel.hpp"
#include "opt/function/test/Sphere.hpp"

#include "opt/gridgen/IterativeGridGenerator.hpp"
#include "opt/gridgen/IterativeGridGeneratorFerenczi.hpp"
#include "opt/gridgen/IterativeGridGeneratorLinearSurplus.hpp"

#include "opt/optimization/ArmijoRule.hpp"
#include "opt/optimization/Optimizer.hpp"
#include "opt/optimization/OptimizerFRPR.hpp"
#include "opt/optimization/OptimizerGradientMethod.hpp"
#include "opt/optimization/OptimizerNelderMead.hpp"
#include "opt/optimization/OptimizerNewton.hpp"
#include "opt/optimization/numrecipes/Bracketmethod.hpp"
#include "opt/optimization/numrecipes/Brent.hpp"
#include "opt/optimization/numrecipes/F1dim.hpp"
#include "opt/optimization/numrecipes/Frprmn.hpp"
#include "opt/optimization/numrecipes/Linemethod.hpp"
#include "opt/optimization/numrecipes/ObjectiveFunction.hpp"

#include "opt/sle/FullSystem.hpp"
#include "opt/sle/HierarchisationSystem.hpp"
#include "opt/sle/Solver.hpp"
#include "opt/sle/SolverArmadillo.hpp"
#include "opt/sle/SolverAuto.hpp"
#include "opt/sle/SolverBiCGStab.hpp"
#include "opt/sle/SolverEigen.hpp"
#include "opt/sle/SolverUMFPACK.hpp"
#include "opt/sle/System.hpp"

#include "opt/tools/Printer.hpp"

#endif
