import os
import fnmatch

Import('env')

objs = []
print "use_ocl:", env['USE_OCL']
if env['USE_OCL']:
  for currentFolder, subdirNames, fileNames in os.walk("."):
    for fileName in fnmatch.filter(fileNames, '*.cpp'):
      sourceFile = os.path.join(currentFolder, fileName)
      objs.append(env.SharedObject(sourceFile))
Return('objs')