# Copyright (C) 2008-today The SG++ project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org


import os
import Helper
import ModuleHelper

Import("*")

moduleDependencies = ["sgppbase"]
additionalDependencies = []

# otherwise libgp won't find eigen
if os.path.isdir('/usr/include/eigen3'):
  env.AppendUnique(CPPPATH=['/usr/include/eigen3'])

Helper.checkForLibrary(config, env, additionalDependencies,
    "BayesOpt", "USE_BAYESOPT", "bayesopt/bayesopt.hpp", ["bayesopt", "nlopt", "m"])
Helper.checkForLibrary(config, env, additionalDependencies,
    "libgp", "USE_LIBGP", "gp.h", "gp")

module = ModuleHelper.Module(moduleDependencies, additionalDependencies)

module.scanSource()
module.buildLibrary()
module.generatePythonDocstrings()
if env["ARCH"] != "mic":
  module.buildExamples()
  module.runExamples()
module.buildBoostTests()
module.runBoostTests()
module.checkStyle()
