import os
import fnmatch

Import('env')

objs = []
if not '-msse3' in env['CPPFLAGS'] and env['USE_DOUBLE_PRECISION']:
  print "compling with avx+ source!!!"
  for currentFolder, subdirNames, fileNames in os.walk("."):
    for fileName in fnmatch.filter(fileNames, '*.cpp'):
      sourceFile = os.path.join(currentFolder, fileName)
      objs.append(env.SharedObject(sourceFile))
Return('objs')