import os
import fnmatch

Import('env')

cpps = []
hpps = []
objs = []

if not '-msse3' in env['CPPFLAGS'] and env['USE_DOUBLE_PRECISION']:
  print "compling with avx+ source!!!"
  for currentFolder, subdirNames, fileNames in os.walk("."):
    for fileName in fnmatch.filter(fileNames, '*.cpp'):
      cpp = os.path.join(currentFolder, fileName)
      cpps.append(cpp)
      objs.append(env.SharedObject(cpp))
  for fileName in fnmatch.filter(fileNames, '*.hpp'):
    hpp = os.path.join(currentFolder, fileName)
    hpps.append(hpp)

returnTuple = (cpps, hpps, objs)
Return('returnTuple')
