# Copyright (C) 2008-today The SG++ project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org

import ModuleHelper

Import("*")

if env["COMPILER"].upper() == "OPENMPI" or env["COMPILER"].upper() == "MPICH":
  module.scanSource(".")
