# Copyright (C) 2009 Technische Universitaet Muenchen
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice at http://www5.in.tum.de/SGpp

# author Dirk Pflueger (Dirk.Pflueger@in.tum.de)
#base/grid/combination/FullGrid.cpp
#base/grid/combination/FullGridSet.cpp
#base/grid/combination/LinearFullGrid.cpp

Import('env')
Import('BUILD_DIR')
Import('moduleName')

dependencies = ["base"]

srcs = Split("""
basisfunction/CombiLinearBasisFunction.cpp
combigrid/SerialCombiGrid.cpp
combigrid/AdaptiveSerialCombiGrid.cpp
combigrid/AdaptiveSerialCombiGridVariableCoefficients.cpp
combischeme/CombiS_CT.cpp  
combischeme/CombiSchemeBasis.cpp  
combischeme/CombiTS_CT.cpp
combischeme/CombiArbitraryScheme.cpp
converter/CombiSGppConverter.cpp
domain/CombiDomain1D.cpp
domain/CombiGridDomain.cpp
domain/CombiUniformStretching.cpp
domain/CombiTanStretching.cpp
domain/CombiAtanSpecialStretching.cpp
multigridFG/multigrid/Multigrid.cpp
multigridFG/multigrid/MultigridFAS.cpp
multigridFG/multigrid/ProlongationRestriction.cpp
multigridFG/operators/PoissonOperator.cpp
multigridFG/operators/TikhonovOperator.cpp
multigridFG/utils/RunPoisson.cpp
multigridFG/utils/RunTikhonov.cpp
plotter/GridPlotter.cpp
utils/CombigridLevelVector.cpp
operation/OperationMatrixLTwoExplicitFullGrid.cpp
""")

objs = []
for sourceFile in srcs:
    objs.append(env.SharedObject(sourceFile))

lib = env.SharedLibrary(target="sgpp" + moduleName, source = objs, LIBPATH = BUILD_DIR, LIBS=['sgppbase'])
env.Install(BUILD_DIR, lib)
# # static libraries get the suffix "static" which allos scons to correctly resolve the dependencies 
# # of the shared libaries on the static libraries on windows
libStatic = env.StaticLibrary(target = "sgpp" + moduleName + "static", source = objs, SHLIBPREFIX = 'lib')
env.Install(BUILD_DIR, libStatic)
