# Contents to release
base
#build.log
#build_sgpp
combigrid
#config.log
CPPLINT.cfg
custom.py_example
datadriven
#datasets
#debugging.arff.gz
doc
Doxyfile_template
#finance
INSTRUCTIONS
INSTRUCTIONS_MAC
INSTRUCTIONS_WINDOWS
#jsgpp
#lib
#misc
moduleDoxy
optimization
#parallel
pde
pysgpp
quadrature
README.md
SConstruct
setup.py
#sgpp-deb
site_scons
solver
#temp_coding_days
#tmptmp
#TODO
### start tools folder
#tools/buildForMIC.sh
#tools/buildForMIC_with_unit_tests_mpi.sh
#tools/buildForMIC_with_unit_tests.sh
#tools/buildOnCmd.sh
#tools/buildOnKepler.sh
#tools/buildOnNeonMPI.sh
#tools/buildOnNeon.sh
#tools/buildOnPCSGS07.sh
#tools/buildOnVGPU2.sh
#tools/buildOnWinter.sh
#tools/copyStatsTogether.py
#tools/copyToMic0.sh
tools/cpplint.py
tools/cpplint.py.orig
tools/org.wangzw.cppstyle_1.4.0.6.jar
tools/pyedit_pythontidy.py
tools/PythonTidy.py
#tools/rename_headers.py
#tools/runExperiments.sh
tools/valgrind-amdocl.supp
tools/valgrind-ocl.supp
tools/valgrind-python.supp
### end tools folder
#visu
#wekasgpp
