#!groovy

def buildbadge = addEmbeddableBadgeConfiguration(id: "Jenkins", subject: "SGpp Jenkins Tests", status: "skipped")


pipeline {
  agent { label 'pcsgs03' }
  options {
    buildDiscarder(
      logRotator(
        daysToKeepStr: "21",
        numToKeepStr: "50",
        artifactDaysToKeepStr: "21",
        artifactNumToKeepStr: "50"
      )
    )
    disableConcurrentBuilds()
  }

  triggers {
    githubPush() // Trigger by push to respective github branch
    pollSCM 'H/5 * * * *' // Fallback polling solution as some pushes are somehow lost
  }

  environment {
    GITHUB_TOKEN = credentials('GITHUB_TOKEN_OCTOTIGER')
    BRANCH_NAME = "${env.BRANCH_NAME}"
    WORKSPACE= "${env.WORKSPACE}"
    SGPP_SPACK_HOME= "/scratch/jenkins/spack-sgpp"
    SGPP_SPACK_CONFIGURATION= "/scratch/jenkins/spack-sgpp-configuration"
    SGPP_TMP_DIR= "/scratch/jenkins/sgpp-tmp"
    PARALLEL_PROCESSES_USED=8 
  }

  stages {
    stage('Iterate spack variants') {
      steps{
        script{
          buildbadge.setStatus('running')
          def variantList = ['sgpp@master%gcc@13.3.0',\
                             'sgpp@master%clang@18.1.3 ^openblas~fortran ^py-scipy%gcc@13.3.0',\
                             'sgpp@master%clang@18.1.3 +python +optimization +quadrature +solver +datadriven +combigrid +doc +eigen +visualization +misc cflags="-Werror" ^openblas~fortran ^py-scipy%gcc@13.3.0',\
                             'sgpp@master +python +optimization +quadrature +solver +datadriven +combigrid +doc +eigen +visualization +misc cflags="-Werror" %gcc@13.3.0 ^swig@4.1 ^python@3.9',\
                             'sgpp@master +python +optimization +quadrature +solver +datadriven +combigrid +doc +eigen +visualization +misc cflags="-Werror" %gcc@13.3.0 ^swig@4.1 ^python@3.13',\
                             'sgpp@master +python +optimization +quadrature +solver ~datadriven +combigrid +doc +eigen +visualization ~misc cflags="-Werror" %gcc@13.3.0 ^swig@4.1 ^python@3.13+debug',\
                             'sgpp@master +debug +python +optimization +quadrature +solver ~datadriven +combigrid +doc +eigen +visualization ~misc cflags="-Werror" %gcc@13.3.0 ^swig@4.1 ^python@3.13+debug',\
                             'sgpprmaster ~python +optimization +quadrature +solver +datadriven +combigrid +misc +opencl cflags="-Werror" %gcc@13.3.0 ^swig@4.1 ',\
                             ]
          def variantDescription = ['SGpp: Basic GCC Tests',\
                             'SGpp: Basic Clang Tests',\
                             'SGpp: Full Release Clang Tests with Python 3.13',\
                             'SGpp: Full Release GCC Tests with Python 3.9',\
                             'SGpp: Full Release GCC Tests with Python 3.13',\
                             'SGpp: Full Release GCC Tests with Python 3.13 Debug Version',\
                             'SGpp: Full Debug GCC Tests with Python 3.13 Debug Version',\
                             'SGpp: Full Release GCC Tests with Datadriven and OpenCL',\
                             ]
          for (int i = 0; i < variantList.size(); i++) {
            sh """
            github_token=\$(echo \${GITHUB_TOKEN} | cut -f2 -d':')
            curl --verbose\
            --request POST \
            --url "https://api.github.com/repos/sgpp/sgpp/statuses/\$GIT_COMMIT" \
            --header "Content-Type: application/json" \
            --header "authorization: Bearer \${github_token}" \
            --data "{
            \\"state\\": \\"pending\\",
            \\"context\\": \\"${variantDescription[i]}\\",
            \\"description\\": \\"Jenkins CI Job: ${variantDescription[i]}\\",
            \\"target_url\\": \\"https://jenkins-sim.informatik.uni-stuttgart.de/job/sgpp/job/\$BRANCH_NAME/\$BUILD_NUMBER/consoleText\\"
            }"
            """
            def variant_build_status = "success"
            try {
            stage("Build and Test ${variantList[i]}") {
              sh """
              cd ${WORKSPACE}
              pwd
              echo "Running tests ${variantDescription[i]}:"
              echo "--------------------------------------"
              echo ""
              echo "SGpp Spack Dir: ${SGPP_SPACK_HOME}"
              echo "SGpp Spack Config Dir: ${SGPP_SPACK_CONFIGURATION}"
              export TMPDIR=${SGPP_TMP_DIR}
              export SPACK_USER_CONFIG_PATH=${SGPP_SPACK_CONFIGURATION}
              source ${SGPP_SPACK_HOME}/share/spack/setup-env.sh
              echo "Input spec: ${variantList[i]}"
              rm -rf .sconsign.dblite
              spack clean -a
              echo "Concretized spec:"
              spack spec --fresh "${variantList[i]}"
              export OMP_NUM_THREADS=${PARALLEL_PROCESSES_USED}
              spack dev-build -j ${PARALLEL_PROCESSES_USED} --fresh --until=build --test=root "${variantList[i]}"
              """
            }
            } catch(err) {
              variant_build_status = "failure"
            }
            sh """
            github_token=\$(echo \${GITHUB_TOKEN} | cut -f2 -d':')
            curl --verbose\
            --request POST \
            --url "https://api.github.com/repos/sgpp/sgpp/statuses/\$GIT_COMMIT" \
            --header "Content-Type: application/json" \
            --header "authorization: Bearer \${github_token}" \
            --data "{
            \\"state\\": \\"${variant_build_status}\\",
            \\"context\\": \\"${variantDescription[i]}\\",
            \\"description\\": \\"Jenkins CI Job: ${variantDescription[i]}\\",
            \\"target_url\\": \\"https://jenkins-sim.informatik.uni-stuttgart.de/job/sgpp/job/\$BRANCH_NAME/\$BUILD_NUMBER/consoleText\\"
            }"
            """
          }
        }
      }
    }
  }
  post {
    success {
      script {
        buildbadge.setStatus('success')
      }
    }
    failure {
      script {
        buildbadge.setStatus('failing')
      }
    }
    aborted {
      script {
        buildbadge.setStatus('aborted')
      }
    }
  }
}
