#!groovy

def buildbadge = addEmbeddableBadgeConfiguration(id: "Jenkins", subject: "Jenkins Tests", status: "skipped")

if (currentBuild.getBuildCauses().toString().contains('BranchIndexingCause')) {
    print "INFO: Build on ${env.BRANCH_NAME}/${env.BUILD_NUMBER} triggered by branch indexing..."
    if (env.BRANCH_NAME != "master") {
        if (env.BUILD_NUMBER != "1") { // Always execute first build to load this configuration and thus the triggers
            print "INFO: Build on ${env.BRANCH_NAME}/${env.BUILD_NUMBER} skipped due being triggered by Branch Indexing instead of SCM change!"
            buildbadge.setStatus('skipped')
            currentBuild.result = 'ABORTED'
            return // early exit to avoid redundant builds
        }
    }
} else {
    print "INFO: Build on ${env.BRANCH_NAME}/${env.BUILD_NUMBER} triggered by SCM change..."
    print "Proceeding!"
}

pipeline {
    agent { label 'pcsgs03' }

    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "21",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "21",
                artifactNumToKeepStr: "50"
            )
        )
    disableConcurrentBuilds()
    }

    triggers {
        githubPush() // Trigger by push to respective github branch
        pollSCM 'H/30 * * * *' // Fallback polling solution as some pushes are somehow lost
    }

    environment {
        GITHUB_TOKEN = credentials('GITHUB_TOKEN_OCTOTIGER')
        BRANCH_NAME = "${env.BRANCH_NAME}"
        WORKSPACE= "${env.WORKSPACE}"
        SGPP_SPACK_HOME= "/scratch/jenkins/spack-sgpp"
        SGPP_SPACK_CONFIGURATION= "/scratch/jenkins/spack-sgpp-configuration"
	MAINTAINER_MAIL = credentials('OCTOTIGER_MAINTAINER_EMAIL')
    }

    stages{
        stage('Dependency -- CMake')
        {
            steps{
                script{
		sh '''
		    cd ${WORKSPACE}
                    pwd
                    echo "SGpp Spack Dir: ${SGPP_SPACK_HOME}"
                    echo "SGpp Spack Config Dir: ${SGPP_SPACK_CONFIGURATION}"
                    echo "Mail: ${MAINTAINER_MAIL}"
                }
            }
        }
}


}
