from pysgpp.extensions.datadriven.uq.quadrature.strategies.GaussHermiteQuadrature import GaussHermiteQuadrature
from pysgpp.extensions.datadriven.uq.quadrature.strategies.GaussLegendreQuadrature import GaussLegendreQuadrature
from pysgpp.extensions.datadriven.uq.quadrature.strategies.QuadratureStrategy import QuadratureStrategy
from pysgpp.extensions.datadriven.uq.quadrature.strategies.QuadratureFactory import QuadratureFactory
