// Copyright (C) 2008-today The SG++ project
// This file is part of the SG++ project. For conditions of distribution and
// use, please see the copyright notice provided with SG++ or at
// sgpp.sparsegrids.org

#pragma once

#include <sgpp/datadriven/datamining/modules/dataSource/DataSource.hpp>
#include <sgpp/datadriven/tools/Dataset.hpp>

namespace sgpp {
namespace datadriven {
// forward declaration to break dependency cycle
class DataSource;

// TODO(lettrich): Check if this class really complies with the definition of an iterator.
/**
 * Iterator object for walking convenient walking over the batches of a
 * #sgpp::datadriven::DataSource
 */
class DataSourceIterator {
 public:
  /**
   * Constructor
   * @param sampleProvider DataSource to iterate over
   * @param counter current iteration of the #sgpp::datadriven::DataSource.
   */
  DataSourceIterator(DataSource &sampleProvider, size_t counter);

  /**
   * Compares two #sgpp::datadriven::DataSourceIterator objects for equality. Required for
   * iteration.
   * @param other The other iterator to compare this object to.
   * @return True if the iterators do not have an equal amount of iterations.
   */
  bool operator!=(const DataSourceIterator &other) const;
  // TODO(lettrich): Discuss if this is robust enough or if we have to check for other stuff as well
  // e.g. equal objects they point to.

  /**
   * Go to the next #sgpp::datadriven::Dataset (if available).
   * @return const reference to this object with updated state.
   */
  const DataSourceIterator &operator++();

  /**
   * Dereferencing an iterator yields the object the iterator currently points to.
   * @return: A Pointer to a new #sgpp::datadriven::Dataset. It is generated by the
   * #sgpp::datadriven::DataSource which provides the data which might change its state. The
   * #sgpp::datadriven::Dataset is owned
   * by the caller.
   */
  Dataset *operator*();

 private:
  /**
   * The sample provider to iterate over
   */
  DataSource &sampleProvider;

  /**
   * Private counter to keep track of the current iteration.
   */
  size_t counter;
};
} /* namespace datadriven */
} /* namespace sgpp */
