# Copyright (C) 2009 Technische Universitaet Muenchen
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice at http://www5.in.tum.de/SGpp

# author Joerg Blank (blankj@in.tum.de), Dirk Pflueger (Dirk.Pflueger@in.tum.de), Alexander Heinecke (Alexander.Heinecke@mytum.de)


srcs = Split("""
pysgpp.i
""")

Import('env')


src_objs = []
if env['SG_BASE']:
	Import('src_objs_base')
	src_objs += src_objs_base
if env['SG_DATADRIVEN']:
	Import('src_objs_datadriven')
	src_objs += src_objs_datadriven
if env['SG_SOLVER']:
	Import('src_objs_solver')
	src_objs += src_objs_solver
if env['SG_FINANCE']:
	Import('src_objs_finance')
	src_objs += src_objs_finance
if env['SG_PDE']:
	Import('src_objs_pde')
	src_objs += src_objs_pde
if env['SG_PARALLEL']:
	Import('src_objs_parallel')
	src_objs += src_objs_parallel
if env['SG_COMBIGRID']:
	Import('src_objs_combigrid')
	src_objs += src_objs_combigrid

py_env = env.Clone()



py_env.AppendUnique(SWIGFLAGS=['-c++','-python'] + ['-D'+c for c in py_env['CPPDEFINES']], CPPPATH=['#/src/sgpp'])

pysgpp = py_env.SharedLibrary(target="pysgpp", source = src_objs+srcs, SHLIBPREFIX = '_')

Export('pysgpp')
Return('pysgpp')
