from pysgpp.extensions.datadriven.uq.quadrature.trilinearform.TrilinearQuadratureStrategy import TrilinearQuadratureStrategy
from pysgpp.extensions.datadriven.uq.quadrature.trilinearform.TrilinearGaussQuadratureStrategy import TrilinearGaussQuadratureStrategy
