
dbg = Environment(CCFLAGS = '-g -O3', LINKFLAGS='--static')
dbg['ENV']['TERM'] = 'xterm'

def CheckExec(context, cmd):
    context.Message( 'Checking for %s...' % (cmd) )
    ret = context.env.WhereIs(cmd)
    if ret == None:
        ret = ''
    context.Result(ret)
    return ret

config = dbg.Configure(custom_tests = { 'CheckExec' : CheckExec})
if config.CheckExec('clang++'):
    dbg['CXX'] = 'clang++'


dbg.Program('main', 'main.cpp',
            LIBS = ['sgppbase', 'sgppmcm'],
            LIBPATH='../../../lib/sgpp/',
            CPPPATH = '../../../src/sgpp/')
