# Copyright (C) 2008-today The SG++ project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org

import ModuleHelper

Import("*")

moduleDependencies = []

additionalDependencies = []
if env["USE_OCL"]:
    additionalDependencies += ["OpenCL"]

module = ModuleHelper.Module(moduleDependencies, additionalDependencies)

module.scanSource()
module.buildLibrary()
module.generatePythonDocstrings()
if env["ARCH"] != "mic":
  module.buildExamples()

module.runPythonTests() 
module.buildBoostTests()
module.runBoostTests()
module.runCpplint()
