# Copyright (C) 2008-today The SG++ project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org

import Helper
import ModuleHelper

Import("*")

moduleDependencies = []

additionalDependencies = []
if env["USE_OCL"]:
    additionalDependencies += ["OpenCL"]

Helper.checkForLibrary(config, env, additionalDependencies,
    "UMFPACK", "USE_UMFPACK", "suitesparse/umfpack.h", "umfpack")
Helper.checkForLibrary(config, env, additionalDependencies,
    "Eigen", "USE_EIGEN", "eigen3/Eigen/Dense", None)
Helper.checkForLibrary(config, env, additionalDependencies,
    "Armadillo", "USE_ARMADILLO", "armadillo", "armadillo")
Helper.checkForLibrary(config, env, additionalDependencies,
    "Gmm++", "USE_GMMPP", "gmm/gmm.h", None)

module = ModuleHelper.Module(moduleDependencies, additionalDependencies)

module.scanSource()
module.buildLibrary()
module.generatePythonDocstrings()
if env["ARCH"] != "mic":
  module.buildExamples()
  module.runExamples()

module.runPythonTests() 
module.buildBoostTests()
module.runBoostTests()
module.checkStyle()
