# Copyright (C) 2009 Technische Universitaet Muenchen
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice at http://www5.in.tum.de/SGpp

# author Dirk Pflueger (Dirk.Pflueger@in.tum.de), Joerg Blank (blankj@in.tum.de), Alexander Heinecke (Alexander.Heinecke@mytum.de)


Import('env')

src_objs = []
if env['SG_BASE']:
	Import('src_objs_base')
	src_objs += src_objs_base
if env['SG_DATADRIVEN']:
	Import('src_objs_datadriven')
	src_objs += src_objs_datadriven
if env['SG_SOLVER']:
	Import('src_objs_solver')
	src_objs += src_objs_solver
if env['SG_FINANCE']:
	Import('src_objs_finance')
	src_objs += src_objs_finance
if env['SG_PDE']:
	Import('src_objs_pde')
	src_objs += src_objs_pde
if env['SG_PARALLEL']:
	Import('src_objs_parallel')
	src_objs += src_objs_parallel
if env['SG_COMBIGRID']:
	Import('src_objs_combigrid')
	src_objs += src_objs_combigrid

j_env = env.Clone()

# remove compiler warnings caused by swig (as we cannot do anything against them, 
# and as they confuse jenkins):
j_env.AppendUnique(CPPFLAGS=['-w'])

j_env.AppendUnique(SWIGFLAGS=['-c++','-java', '-package', 'sgpp'])
j_env.AppendUnique(CPPPATH=['#/src/sgpp'])
j_env.AppendUnique(CPPFLAGS=['-fno-strict-aliasing'])

jsgpp = j_env.SharedLibrary(target="jsgpp", source = ['jsgpp.i']+src_objs, SHLIBPREFIX = 'lib')

from glob import glob
files = glob('*.java')
env.Install('#/lib/jsgpp/sgpp/', files)

Return('jsgpp')
