# Copyright (C) 2008-today The SG++ Project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org

import Helper
import ModuleHelper

Import("*")

moduleDependencies = ["sgppoptimization", "sgpppde", "sgppsolver", "sgppquadrature", "sgppbase"]
additionalDependencies = []

Helper.checkForLibrary(config, env, additionalDependencies,
    "PECOS", "USE_DAKOTA", "pecos_global_defs.hpp", "libpecos_src")
Helper.checkForLibrary(config, env, additionalDependencies,
    "PECOS_teuchcore", "USE_DAKOTA", "pecos_global_defs.hpp", "libteuchoscore")
Helper.checkForLibrary(config, env, additionalDependencies,
    "PECOS_teuchnumerics", "USE_DAKOTA", "pecos_global_defs.hpp", "libteuchosnumerics")
Helper.checkForLibrary(config, env, additionalDependencies,
    "PECOS_dak", "USE_DAKOTA", "pecos_global_defs.hpp", "dakota_src")

module = ModuleHelper.Module(moduleDependencies, additionalDependencies)

module.scanSource()
module.buildLibrary()
module.generatePythonDocstrings()
module.buildExamples()
module.buildBoostTests()
module.runBoostTests()
module.runCpplint()
