# Copyright (C) 2008-today The SG++ Project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at 
# sgpp.sparsegrids.org

import os
import fnmatch

Import('env')
Import('BUILD_DIR')
Import('PYSGPP_BUILD_PATH')
Import('moduleName')
Import('libraryTargetList')
Import('installTargetList')

dependencies = ["base"]

objs = []
for currentFolder, subdirNames, fileNames in os.walk("src"):
    if currentFolder.startswith("src/sgpp/combigrid/test") or currentFolder.startswith("src/sgpp/combigrid/tests") or currentFolder.startswith  ("src/sgpp/combigrid/multigridFG/test"):
        continue
    for fileName in fnmatch.filter(fileNames, '*.cpp'):
        sourceFile = os.path.join(currentFolder, fileName)
        objs.append(env.SharedObject(sourceFile))

lib = env.SharedLibrary(target="sgpp%s" % moduleName,
                        source=objs,
                        LIBPATH=BUILD_DIR,
                        LIBS=['sgppbase'])
env.Depends(lib, "#/" + BUILD_DIR.path + "/libsgppbase.so")
libInstall = env.Install(BUILD_DIR, lib)
# # static libraries get the suffix "static" which allos scons to correctly resolve the dependencies 
# # of the shared libaries on the static libraries on windows
libStatic = env.StaticLibrary(target="sgpp%static" % moduleName,
                              source=objs,
                              SHLIBPREFIX='lib')
libStaticInstall = env.Install(BUILD_DIR, libStatic)
env.Depends(libInstall, libStaticInstall)

libraryTargetList.append(lib)
installTargetList.append(libInstall)
